JEOD: jeod::LineContactFacetFactory Class Reference
jeod::LineContactFacetFactory Class Reference
Creates a PointContactFacet from an InteractionFacet.
#include <line_contact_facet_factory.hh>
Public Member Functions
LineContactFacetFactory ()
Default Constructor.
~LineContactFacetFactory () override
Destructor.
InteractionFacet * create_facet (Facet *facet, FacetParams *params) override
Create a PointContactFacet from a CircularFlatPlate facet and a ContactParams object.
bool is_correct_factory (Facet *facet) override
PointContactFacetFactory specific implementation of this function.
Public Member Functions inherited from jeod::InteractionFacetFactory
InteractionFacetFactory ()
Default Constructor.
virtual ~InteractionFacetFactory ()
Destructor.
Private Member Functions
LineContactFacetFactory & operator= (const LineContactFacetFactory &rhs)
LineContactFacetFactory (const LineContactFacetFactory &rhs)
Friends
class InputProcessor
void init_attrjeod__LineContactFacetFactory ()
Additional Inherited Members
Protected Attributes inherited from jeod::InteractionFacetFactory
bool trick_bool
Unused data field to expedite dynamic allocation in Trick environment.
Detailed Description
Creates a PointContactFacet from an InteractionFacet.
Definition at line 85 of file line_contact_facet_factory.hh.
Constructor & Destructor Documentation
LineContactFacetFactory() [1/2]
jeod::LineContactFacetFactory::LineContactFacetFactory (void)
Default Constructor.
Definition at line 53 of file line_contact_facet_factory.cc.
References JEOD_REGISTER_CLASS.
~LineContactFacetFactory()
jeod::LineContactFacetFactory::~LineContactFacetFactory (void) override
Destructor.
Definition at line 64 of file line_contact_facet_factory.cc.
LineContactFacetFactory() [2/2]
jeod::LineContactFacetFactory::LineContactFacetFactory (const LineContactFacetFactory & rhs) private
Member Function Documentation
create_facet()
InteractionFacet * jeod::LineContactFacetFactory::create_facet (Facet * facet, FacetParams * params) override virtual
Create a PointContactFacet from a CircularFlatPlate facet and a ContactParams object.
Returns
The new EllipsoidContactFacet. Note that this is allocated and YOU are responsible for destroying it at the end!
Parameters
[in] facet The CircularFlatPlate. This MUST be a circular flat plate or the algorithm will send a failure message
[in] params ContactParams
Implements jeod::InteractionFacetFactory.
Definition at line 82 of file line_contact_facet_factory.cc.
References jeod::InteractionFacet::base_facet, jeod::Vector3::copy(), jeod::ContactFacet::create_vehicle_point(), jeod::MassBody::dyn_owner, jeod::MessageHandler::fail(), jeod::Facet::get_mass_body_ptr(), jeod::ContactMessages::initialization_error, JEOD_ALLOC_CLASS_OBJECT, jeod::Cylinder::length, jeod::LineContactFacet::length, jeod::FlatPlate::normal, jeod::ContactFacet::normal, jeod::ContactFacet::position, jeod::Facet::position, jeod::FlatPlateCircular::radius, jeod::PointContactFacet::radius, jeod::LineContactFacet::set_max_dimension(), jeod::ContactFacet::surface_type, and jeod::ContactFacet::vehicle_body.
is_correct_factory()
bool jeod::LineContactFacetFactory::is_correct_factory (Facet * facet) override virtual
PointContactFacetFactory specific implementation of this function.
If the Facet is of type CircularFlatPlate, returns true. False otherwise
Returns
true if facet is a FlatPlateCircular, false otherwise
Parameters
[in] facet The facet to check
Implements jeod::InteractionFacetFactory.
Definition at line 161 of file line_contact_facet_factory.cc.
operator=()
LineContactFacetFactory& jeod::LineContactFacetFactory::operator= (const LineContactFacetFactory & rhs) private
Friends And Related Function Documentation
init_attrjeod__LineContactFacetFactory
void init_attrjeod__LineContactFacetFactory () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file line_contact_facet_factory.hh.
The documentation for this class was generated from the following files:
line_contact_facet_factory.hh
line_contact_facet_factory.cc