JEOD: jeod::CheckItem Class Reference
jeod::CheckItem Class Reference
Provides several static methods for checking whether a computed value agrees with an expected value to within some tolerance.
#include <check_item.hh>
Static Public Member Functions
static bool within_tolerance (double computed, double expected, double abs_tol)
Test whether the computed value agrees with the expected value.
static bool within_tolerance (double computed, double expected, double abs_tol, double rel_tol)
Test whether the computed value agrees with the expected value.
static bool within_tolerance (const double computed[3], const double expected[3], double abs_tol)
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
static bool within_tolerance (const double computed[3], const double expected[3], double abs_tol, bool result[3])
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
static bool within_tolerance (const double computed[3], const double expected[3], double abs_tol, double rel_tol)
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
static bool within_tolerance (const double computed[3], const double expected[3], double abs_tol, double rel_tol, bool result[3])
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
static bool within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol)
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
static bool within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol, bool result[3][3])
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
static bool within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol, double rel_tol)
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
static bool within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol, double rel_tol, bool result[3][3])
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
static bool is_within (double computed, double lower_lim, double upper_lim)
Test whether the computed value is between the specified bounds, inclusive.
static bool is_within (const double computed[3], const double lower_lim[3], const double upper_lim[3])
Test whether each element of the computed vector is between the corresponding elements of the lower and upper bound vectors, inclusive.
static bool is_within (const double computed[3], const double lower_lim[3], const double upper_lim[3], bool result[3])
Test whether each element of the computed vector is between the corresponding elements of the lower and upper bound vectors, inclusive.
static bool is_within (const double computed[3][3], const double lower_lim[3][3], const double upper_lim[3][3])
Test whether each element of the computed matrix is between the corresponding elements of the lower and upper bound matrices, inclusive.
static bool is_within (const double computed[3][3], const double lower_lim[3][3], const double upper_lim[3][3], bool result[3][3])
Test whether each element of the computed matrix is between the corresponding elements of the lower and upper bound matrices, inclusive.
static bool is_zero (const double computed, double abs_tol)
Test whether the computed value is approximately equal to zero.
static bool is_zero (const double computed[3], double abs_tol)
Test whether each element of the computed vector is approximately zero.
static bool is_zero (const double computed[3], double abs_tol, bool result[3])
Test whether each element of the computed vector is approximately zero.
static bool is_zero (const double computed[3][3], double abs_tol)
Test whether each element of the computed matrix is approximately zero.
static bool is_zero (const double computed[3][3], double abs_tol, bool result[3][3])
Test whether each element of the computed matrix is approximately zero.
static bool is_identity (const double computed[3][3], double diag_tol, double off_diag_tol)
Test whether the computed matrix is more or less the identity matrix.
static bool is_identity (const double computed[3][3], double diag_tol, double off_diag_tol, bool result[3][3])
Test whether the computed matrix is more or less the identity matrix.
static bool is_identity (const Quaternion &computed, double scalar_tol, double vector_tol)
Test whether the computed quaternion is the real unit quaternion.
static bool is_unit (const double computed, double abs_tol)
Test whether the computed value is approximately equal to one.
static bool is_unit (const double computed[3], double abs_tol)
Test whether the computed vector is more or less a unit vector.
static bool is_unit (const double computed[3][3], double unit_tol, double normal_tol)
Test whether the computed matrix is more or less a rotation matrix.
static bool is_unit (const Quaternion &computed, double abs_tol)
Test whether the computed quaternion is more or less a unit quaternion.
static bool within_rss_tolerance (const double computed[3], const double expected[3], double rss_tolerance)
Test whether the computed and expected vectors are close to one another in a root sum square (Euclidean norm) sense.
static bool within_rss_tolerance (const double computed[3][3], const double expected[3][3], double rss_tolerance)
Test whether the computed and expected matrices are close to one another in a root sum square (Frobenius norm) sense.
static bool within_eigen_tolerance (const double computed[3][3], const double expected[3][3], double angular_tolerance)
Test whether the computed and expected matrices are close to one another in an eigen rotation sense.
static bool within_eigen_tolerance (const Quaternion &computed, const Quaternion &expected, double angular_tolerance)
Test whether the computed and expected quaternions are close to one another in an eigen rotation sense.
Detailed Description
Provides several static methods for checking whether a computed value agrees with an expected value to within some tolerance.
The methods are defined inline and are overloaded. The table that follows describes these methods.
Method Applies to Comments
within_tolerance scalar, vector, matrix Two basic methods exist for each type. One tests that each computed elements is within an absolute tolerance of the corresponding expected element. The other uses an absolute tolerance for small expected values but a relative tolerance for larger values. For composite articles, each basic test comes in two flavors: A gross test and an item-by-item test.
is_within scalar, vector, matrix Tests whether each computed element lies between the corresponding lower and upper bound elements.
is_zero scalar, vector, matrix Tests whether each computed element is approximately zero.
is_identity matrix, quaternion Tests whether the computed item is the identity matrix / real unit quaternion.
is_unit scalar, vector, matrix, quaternion Tests whether the computed item is a 'unit'. For scalars, this means 1 (but not -1). For vectors and quaternions, this means the test item is approximately a unit vector/unit quaternion. For matrices, the test is for a right-handed orthogonal matrix.
within_rss_tolerance vector, matrix Tests whether the root sum square of the vector/matrix is within the specified tolerance.
within_eigen_tolerance orthogonal matrix, unit quaternion Tests whether the eigen rotation from expected to computed is within the specified tolerance.
Definition at line 134 of file check_item.hh.
Member Function Documentation
is_identity() [1/3]
bool jeod::CheckItem::is_identity (const double computed[3][3], double diag_tol, double off_diag_tol) inline static
Test whether the computed matrix is more or less the identity matrix.
Returns
Is the matrix an identity matrix?
Parameters
[in] computed The computed matrix
[in] diag_tol Max error, diagonal elements
[in] off_diag_tol Max error, off-diagonal elements
Definition at line 646 of file check_item.hh.
References is_unit(), and is_zero().
is_identity() [2/3]
bool jeod::CheckItem::is_identity (const double computed[3][3], double diag_tol, double off_diag_tol, bool result[3][3]) inline static
Test whether the computed matrix is more or less the identity matrix.
Returns
Is the matrix an identity matrix?
Parameters
[in] computed The computed matrix
[in] diag_tol Max error, diagonal elements
[in] off_diag_tol Max error, off-diagonal elements
[out] result Item-by-item status
Definition at line 663 of file check_item.hh.
References is_unit(), and is_zero().
is_identity() [3/3]
bool jeod::CheckItem::is_identity (const Quaternion & computed, double scalar_tol, double vector_tol) inline static
Test whether the computed quaternion is the real unit quaternion.
Returns
Is this the real unit quaternion?
Parameters
[in] computed The computed quaternion
[in] scalar_tol Max error, scalar part
[in] vector_tol Max error, vector elements
Definition at line 686 of file check_item.hh.
References is_unit(), is_zero(), jeod::Quaternion::scalar, and jeod::Quaternion::vector.
is_unit() [1/4]
bool jeod::CheckItem::is_unit (const double computed, double abs_tol) inline static
Test whether the computed value is approximately equal to one.
Returns
Is this one?
Parameters
[in] computed The computed value
[in] abs_tol Max absolute error
Definition at line 706 of file check_item.hh.
Referenced by is_identity(), and is_unit().
is_unit() [2/4]
bool jeod::CheckItem::is_unit (const double computed[3], double abs_tol) inline static
Test whether the computed vector is more or less a unit vector.
Returns
Is this a unit vector?
Parameters
[in] computed The computed vector
[in] abs_tol Max absolute error
Definition at line 717 of file check_item.hh.
References is_within(), and jeod::Vector3::vmagsq().
is_unit() [3/4]
bool jeod::CheckItem::is_unit (const double computed[3][3], double unit_tol, double normal_tol) inline static
Test whether the computed matrix is more or less a rotation matrix.
Returns
Is this an orthogonal matrix?
Parameters
[in] computed The computed matrix
[in] unit_tol Unit vector tolerance
[in] normal_tol Normality tolerance
Definition at line 729 of file check_item.hh.
References jeod::Vector3::cross(), jeod::Vector3::dot(), is_unit(), and is_zero().
is_unit() [4/4]
bool jeod::CheckItem::is_unit (const Quaternion & computed, double abs_tol) inline static
Test whether the computed quaternion is more or less a unit quaternion.
Returns
Is this a unit quaternion?
Parameters
[in] computed The computed quaternion
[in] abs_tol Max absolute error
Definition at line 748 of file check_item.hh.
References is_within(), and jeod::Quaternion::norm_sq().
is_within() [1/5]
bool jeod::CheckItem::is_within (double computed, double lower_lim, double upper_lim) inline static
Test whether the computed value is between the specified bounds, inclusive.
Returns
Is the computed value within bounds?
Parameters
[in] computed The computed value
[in] lower_lim The lower limit
[in] upper_lim The upper limit
Definition at line 475 of file check_item.hh.
Referenced by is_unit(), and is_within().
is_within() [2/5]
bool jeod::CheckItem::is_within (const double computed[3], const double lower_lim[3], const double upper_lim[3]) inline static
Test whether each element of the computed vector is between the corresponding elements of the lower and upper bound vectors, inclusive.
Returns
Is the computed value within bounds?
Parameters
[in] computed The computed value
[in] lower_lim The lower limit
[in] upper_lim The upper limit
Definition at line 488 of file check_item.hh.
References is_within().
is_within() [3/5]
bool jeod::CheckItem::is_within (const double computed[3], const double lower_lim[3], const double upper_lim[3], bool result[3]) inline static
Test whether each element of the computed vector is between the corresponding elements of the lower and upper bound vectors, inclusive.
Returns
Is the computed value within bounds?
Parameters
[in] computed The computed value
[in] lower_lim The lower limit
[in] upper_lim The upper limit
[out] result Item-by-item status
Definition at line 503 of file check_item.hh.
References is_within().
is_within() [4/5]
bool jeod::CheckItem::is_within (const double computed[3][3], const double lower_lim[3][3], const double upper_lim[3][3]) inline static
Test whether each element of the computed matrix is between the corresponding elements of the lower and upper bound matrices, inclusive.
Returns
Is the computed value within bounds?
Parameters
[in] computed The computed value
[in] lower_lim The lower limit
[in] upper_lim The upper limit
Definition at line 523 of file check_item.hh.
References is_within().
is_within() [5/5]
bool jeod::CheckItem::is_within (const double computed[3][3], const double lower_lim[3][3], const double upper_lim[3][3], bool result[3][3]) inline static
Test whether each element of the computed matrix is between the corresponding elements of the lower and upper bound matrices, inclusive.
Returns
Is the computed value within bounds?
Parameters
[in] computed The computed value
[in] lower_lim The lower limit
[in] upper_lim The upper limit
[out] result Item-by-item status
Definition at line 540 of file check_item.hh.
References is_within().
is_zero() [1/5]
bool jeod::CheckItem::is_zero (const double computed, double abs_tol) inline static
Test whether the computed value is approximately equal to zero.
Returns
Is this zero?
Parameters
[in] computed The computed value
[in] abs_tol Max absolute error
Definition at line 569 of file check_item.hh.
Referenced by is_identity(), is_unit(), is_zero(), and within_rss_tolerance().
is_zero() [2/5]
bool jeod::CheckItem::is_zero (const double computed[3], double abs_tol) inline static
Test whether each element of the computed vector is approximately zero.
Returns
Is this a zero vector?
Parameters
[in] computed The computed vector
[in] abs_tol Max absolute error
Definition at line 580 of file check_item.hh.
References is_zero().
is_zero() [3/5]
bool jeod::CheckItem::is_zero (const double computed[3], double abs_tol, bool result[3]) inline static
Test whether each element of the computed vector is approximately zero.
Returns
Is this a zero vector?
Parameters
[in] computed The computed vector
[in] abs_tol Max absolute error
[out] result Item-by-item status
Definition at line 592 of file check_item.hh.
References is_zero().
is_zero() [4/5]
bool jeod::CheckItem::is_zero (const double computed[3][3], double abs_tol) inline static
Test whether each element of the computed matrix is approximately zero.
Returns
Is this a zero matrix?
Parameters
[in] computed The computed matrix
[in] abs_tol Max absolute error
Definition at line 607 of file check_item.hh.
References is_zero().
is_zero() [5/5]
bool jeod::CheckItem::is_zero (const double computed[3][3], double abs_tol, bool result[3][3]) inline static
Test whether each element of the computed matrix is approximately zero.
Returns
Is this a zero matrix?
Parameters
[in] computed The computed matrix
[in] abs_tol Max absolute error
[out] result Item-by-item status
Definition at line 619 of file check_item.hh.
References is_zero().
within_eigen_tolerance() [1/2]
bool jeod::CheckItem::within_eigen_tolerance (const double computed[3][3], const double expected[3][3], double angular_tolerance) inline static
Test whether the computed and expected matrices are close to one another in an eigen rotation sense.
The test passes if the eigen rotation from expected to computed is a small angle.
Returns
Is the matrix within tolerance?
Parameters
[in] computed The computed transformation matrix
[in] expected The expected transformation matrix
[in] angular_tolerance Allowed angular error
Units: r
Definition at line 819 of file check_item.hh.
References jeod::Orientation::compute_eigen_rotation_from_matrix(), and jeod::Matrix3x3::product_left_transpose().
within_eigen_tolerance() [2/2]
bool jeod::CheckItem::within_eigen_tolerance (const Quaternion & computed, const Quaternion & expected, double angular_tolerance) inline static
Test whether the computed and expected quaternions are close to one another in an eigen rotation sense.
The test passes if the eigen rotation from expected to computed is a small angle.
Returns
Is the quaternion within tolerance?
Parameters
[in] computed The computed quaternion
[in] expected The expected value
[in] angular_tolerance Allowed angular error
Units: r
Definition at line 841 of file check_item.hh.
References jeod::Quaternion::eigen_compare().
within_rss_tolerance() [1/2]
bool jeod::CheckItem::within_rss_tolerance (const double computed[3], const double expected[3], double rss_tolerance) inline static
Test whether the computed and expected vectors are close to one another in a root sum square (Euclidean norm) sense.
Returns
Is the vector within tolerance?
Parameters
[in] computed The computed matrix
[in] expected The expected matrix
[in] rss_tolerance Allowed RSS error
Definition at line 771 of file check_item.hh.
References jeod::Vector3::diff(), is_zero(), and jeod::Vector3::vmagsq().
within_rss_tolerance() [2/2]
bool jeod::CheckItem::within_rss_tolerance (const double computed[3][3], const double expected[3][3], double rss_tolerance) inline static
Test whether the computed and expected matrices are close to one another in a root sum square (Frobenius norm) sense.
Returns
Is the matrix within tolerance?
Parameters
[in] computed The computed matrix
[in] expected The expected matrix
[in] rss_tolerance Allowed RSS error
Definition at line 785 of file check_item.hh.
References jeod::Vector3::diff(), is_zero(), and jeod::Vector3::vmagsq().
within_tolerance() [1/10]
bool jeod::CheckItem::within_tolerance (double computed, double expected, double abs_tol) inline static
Test whether the computed value agrees with the expected value.
This method compares the absolute error to the provided absolute tolerance.
Assumptions and Limitations
The absolute tolerance is assumed to be positive.
An error smaller than the absolute tolerance is assumed to be calculable. The expected value must be absolutely smaller than 5e15 times absolute tolerance lest the comparison devolve to equality. An absolute ratio of 1e14 or smaller is preferable.
Returns
Is the computed value within tolerance?
Parameters
[in] computed The computed value
[in] expected The expected value
[in] abs_tol Max absolute error
Definition at line 274 of file check_item.hh.
Referenced by within_tolerance().
within_tolerance() [2/10]
bool jeod::CheckItem::within_tolerance (double computed, double expected, double abs_tol, double rel_tol) inline static
Test whether the computed value agrees with the expected value.
This method compares the absolute error to a computed tolerance. This computed tolerance is the absolute tolerance for small values of the expected value but the product of the relative tolerance and the expected value for larger values of the expected value.
Assumptions and Limitations
The provided tolerances are assumed to be positive.
Returns
Is the computed value within tolerance?
Parameters
[in] computed The computed value
[in] expected The expected value
[in] abs_tol Max absolute error, used when expected is small
[in] rel_tol Max relative error, for not-so-small values
Definition at line 294 of file check_item.hh.
within_tolerance() [3/10]
bool jeod::CheckItem::within_tolerance (const double computed[3], const double expected[3], double abs_tol) inline static
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
See the corresponding scalar version for the nature of the test.
Returns
Is the vector within tolerance?
Parameters
[in] computed The computed value
[in] expected The expected value
[in] abs_tol Max absolute error
Definition at line 308 of file check_item.hh.
References within_tolerance().
within_tolerance() [4/10]
bool jeod::CheckItem::within_tolerance (const double computed[3], const double expected[3], double abs_tol, bool result[3]) inline static
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
See the corresponding scalar version for the nature of the test.
Returns
Is the vector within tolerance?
Parameters
[in] computed The computed value
[in] expected The expected value
[in] abs_tol Max absolute error
[out] result Item-by-item status
Definition at line 324 of file check_item.hh.
References within_tolerance().
within_tolerance() [5/10]
bool jeod::CheckItem::within_tolerance (const double computed[3], const double expected[3], double abs_tol, double rel_tol) inline static
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
See the corresponding scalar version for the nature of the test.
Returns
Is the vector within tolerance?
Parameters
[in] computed The computed value
[in] expected The expected value
[in] abs_tol Max absolute error
[in] rel_tol Max relative error
Definition at line 346 of file check_item.hh.
References within_tolerance().
within_tolerance() [6/10]
bool jeod::CheckItem::within_tolerance (const double computed[3], const double expected[3], double abs_tol, double rel_tol, bool result[3]) inline static
Test whether each element of the computed vector agrees with the corresponding element of the expected vector.
See the corresponding scalar version for the nature of the test.
Returns
Is the vector within tolerance?
Parameters
[in] computed The computed value
[in] expected The expected value
[in] abs_tol Max absolute error
[in] rel_tol Max relative error
[out] result Item-by-item status
Definition at line 367 of file check_item.hh.
References within_tolerance().
within_tolerance() [7/10]
bool jeod::CheckItem::within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol) inline static
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
See the corresponding scalar version for the nature of the test.
Returns
Is the matrix within tolerance?
Parameters
[in] computed The computed matrix
[in] expected The expected matrix
[in] abs_tol Max absolute error
Definition at line 386 of file check_item.hh.
References within_tolerance().
within_tolerance() [8/10]
bool jeod::CheckItem::within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol, bool result[3][3]) inline static
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
See the corresponding scalar version for the nature of the test.
Returns
Is the matrix within tolerance?
Parameters
[in] computed The computed matrix
[in] expected The expected matrix
[in] abs_tol Max absolute error
[out] result Item-by-item status
Definition at line 402 of file check_item.hh.
References within_tolerance().
within_tolerance() [9/10]
bool jeod::CheckItem::within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol, double rel_tol) inline static
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
See the corresponding scalar version for the nature of the test.
Returns
Is the matrix within tolerance?
Parameters
[in] computed The computed matrix
[in] expected The expected matrix
[in] abs_tol Max absolute error
[in] rel_tol Max relative error
Definition at line 426 of file check_item.hh.
References within_tolerance().
within_tolerance() [10/10]
bool jeod::CheckItem::within_tolerance (const double computed[3][3], const double expected[3][3], double abs_tol, double rel_tol, bool result[3][3]) inline static
Test whether each element of the computed matrix agrees with the corresponding element of the expected matrix.
See the corresponding scalar version for the nature of the test.
Returns
Is the matrix within tolerance?
Parameters
[in] computed The computed matrix
[in] expected The expected matrix
[in] abs_tol Max absolute error
[in] rel_tol Max relative error
[out] result Item-by-item status
Definition at line 447 of file check_item.hh.
References within_tolerance().
The documentation for this class was generated from the following file:
check_item.hh