JEOD: jeod::CmdlineParser Class Reference
jeod::CmdlineParser Class Reference
A CmdlineParser parses command line options.
#include <cmdline_parser.hh>
Data Structures
class BaseIntOptionValue
A BaseIntOptionValue is a BaseOptionValue whose target is an int.
class BaseOptionValue
The BaseOptionValue is the base class for all option descriptor classes.
class CounterOptionValue
A CounterOptionValue represents a counter: Each occurrence of the option on the command line increments the target value.
class DoubleOptionValue
A DoubleOptionValue represents a command line option that takes a double as an argument.
class IntOptionValue
An IntOptionValue represents a command line option that takes an integer as an argument.
class NegatedOptionValue
A NegatedptionValue is a refinement of a command line switch.
class StringOptionValue
A StringOptionValue represents a command line option that takes a string as an argument.
class SwitchOptionValue
A SwitchOptionValue represents a command line switch.
class ToggleOptionValue
A ToggleOptionValue is a refinement of a command line switch.
Public Member Functions
CmdlineParser ()
Default constructor.
~CmdlineParser ()
Destructor.
int parse (int &argc, char **argv)
Parse the command line.
void add (const char *, bool *)
Add a switch to the list of recognized command line options.
void add_switch (const char *, bool *)
Add a switch to the list of recognized command line options.
void add_toggle (const char *, bool, bool *)
Add a toggle to the list of recognized command line options.
void add_counter (const char *, int *)
Add a switch to the list of recognized command line options.
void add_string (const char *, const char *, const char **)
Add a string option to the list of recognized command line options.
void add_int (const char *, int, int *)
Add an integer option to the list of recognized command line options.
void add_double (const char *, double, double *)
Add a double option to the list of recognized command line options.
Private Types
typedef std::map< const std::string, BaseOptionValue * > OptionTable
Contains the option names mapped to type.
Private Member Functions
void check_timing (const char *, int, const char *, const std::string &)
Check whether it is OK to call the named method.
bool check_registration (const char *, int, const char *, const std::string &)
Ensure that the option name has not yet been registered.
bool check_prereqs (const char *, int, const char *, const std::string &)
Check timing and registration prerequisites.
bool check_toggle_prereqs (const char *, int, const char *, const std::string &, const std::string &)
Check timing and registration prerequisites.
CmdlineParser (const CmdlineParser &)
Not implemented.
CmdlineParser & operator= (const CmdlineParser &)
Not implemented.
Private Attributes
OptionTable option_table
All command line options and their types.
bool parsed
Has the CmdlineParser::parse() been called?
Detailed Description
A CmdlineParser parses command line options.
Using a command line parser in a unit test program is as easy as 1-2-3:
Declar variables.
Specify the options to be parsed, including where to put the data.
Parse the command line.
A simple example that recognizes -foo and -bar as command line switches:
// Step 1: Declare variables.
TestSimInterface sim_interface;
CmdlineParser cmdline_parser;
bool foo, bar;
// Step 2: Specify the options to be parsed and where to put the data.
cmdline_parser.add ("foo", foo);
cmdline_parser.add ("bar", bar);
// Step 3: Parse the command line.
cmdline_parser.parse ();
Suppose the program is compiled and linked to generate an executable named 'my_program'. If, for example, a user runs the program as ./my_program -bar, the values of the variable foo will be false and bar will true in this case.
The model also supports options that take arguments. To illustrate, the following makes the 'bar' option an integer with a default value of 42; the 'foo' option remains a simple switch.
// Step 1: Declare variables.
TestSimInterface sim_interface;
CmdlineParser cmdline_parser;
bool foo = false;
int bar = 42;
// Step 2: Specify the options to be parsed and where to put the data.
cmdline_parser.add_switch ("foo", foo);
cmdline_parser.add_int ("bar", bar);
// Step 2: Parse the command line.
cmdline_parser.parse ();
This modified version is almost as simple as the simple example. The variable bar is now an int instead of a bool and the calls to add() are now calls to to add_<type>(). The add() method would have worked here for foo, but it is better to use the full name in this case for consistency.
The model supports the following option types:
Switch. Switches are the simplest kind of command line option. The switch value is false/true if the option is absent from/present in the argument list.
Toggle. A toggle is similar to a switch but adds the ability to turn the switch off. A toggle named 'foo' means that -foo sets the value for 'foo' while -nofoo clears the value.
Counter. A counter increments an integer count for each occurrence on the command line. For example, with a counter named 'debug', the value of the counter will be two if the command line contains two separate -debug options.
String. A string option represents a command line option that takes a string as an argument. As with the add_int() example above, a default value must be specified with string options.
Integer. An integer option represents a command line option that takes a integer value as an argument.
Double. A double option represents a command line option that takes a double value as an argument. These too have a default value.
Definition at line 143 of file cmdline_parser.hh.
Member Typedef Documentation
OptionTable
typedef std::map<const std::string, BaseOptionValue*> jeod::CmdlineParser::OptionTable private
Contains the option names mapped to type.
Definition at line 684 of file cmdline_parser.hh.
Constructor & Destructor Documentation
CmdlineParser() [1/2]
jeod::CmdlineParser::CmdlineParser (void)
Default constructor.
Definition at line 48 of file cmdline_parser.cc.
~CmdlineParser()
jeod::CmdlineParser::~CmdlineParser (void)
Destructor.
Definition at line 59 of file cmdline_parser.cc.
References option_table.
CmdlineParser() [2/2]
jeod::CmdlineParser::CmdlineParser (const CmdlineParser &) explicit private
Not implemented.
Member Function Documentation
add()
void jeod::CmdlineParser::add (const char * option_name, bool * target)
Add a switch to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in,out] target The receiver of the default and parsed value.
Definition at line 77 of file cmdline_parser.cc.
References add_switch().
add_counter()
void jeod::CmdlineParser::add_counter (const char * option_name, int * target)
Add a switch to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in,out] target The receiver of the default and parsed value.
Definition at line 149 of file cmdline_parser.cc.
References check_prereqs(), and option_table.
add_double()
void jeod::CmdlineParser::add_double (const char * option_name, double default_value, double * target)
Add a double option to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in] default_value The default value for this option.
[in,out] target The receiver of the default and parsed value.
Definition at line 226 of file cmdline_parser.cc.
References check_prereqs(), and option_table.
add_int()
void jeod::CmdlineParser::add_int (const char * option_name, int default_value, int * target)
Add an integer option to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in] default_value The default value for this option.
[in,out] target The receiver of the default and parsed value.
Definition at line 200 of file cmdline_parser.cc.
References check_prereqs(), and option_table.
add_string()
void jeod::CmdlineParser::add_string (const char * option_name, const char * default_value, const char ** target)
Add a string option to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in] default_value The default value for this option.
[in,out] target The receiver of the default and parsed value.
Definition at line 174 of file cmdline_parser.cc.
References check_prereqs(), and option_table.
add_switch()
void jeod::CmdlineParser::add_switch (const char * option_name, bool * target)
Add a switch to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in,out] target The receiver of the default and parsed value.
Definition at line 91 of file cmdline_parser.cc.
References check_prereqs(), and option_table.
Referenced by add().
add_toggle()
void jeod::CmdlineParser::add_toggle (const char * option_name, bool default_value, bool * target)
Add a toggle to the list of recognized command line options.
Parameters
[in] option_name The option name, sans the leading hyphen.
[in] default_value The default value for this option.
[in,out] target The receiver of the default and parsed value.
Definition at line 116 of file cmdline_parser.cc.
References check_toggle_prereqs(), and option_table.
check_prereqs()
bool jeod::CmdlineParser::check_prereqs (const char * file, int line, const char * method_name, const std::string & option_name) private
Check timing and registration prerequisites.
Parameters
[in] file __FILE_
[in] line __LINE_
[in] method_name The method name, used for error reporting.
[in] option_name The option name, sans the leading hyphen.
Definition at line 425 of file cmdline_parser.cc.
References check_registration(), and check_timing().
Referenced by add_counter(), add_double(), add_int(), add_string(), and add_switch().
check_registration()
bool jeod::CmdlineParser::check_registration (const char * file, int line, const char * method_name, const std::string & option_name) private
Ensure that the option name has not yet been registered.
Parameters
[in] file __FILE_
[in] line __LINE_
[in] method_name The method name, used for error reporting.
[in] option_name The option name, sans the leading hyphen.
Definition at line 388 of file cmdline_parser.cc.
References jeod::MessageHandler::error(), jeod::TestHarnessMessages::inconsistent_setup, and option_table.
Referenced by check_prereqs(), and check_toggle_prereqs().
check_timing()
void jeod::CmdlineParser::check_timing (const char * file, int line, const char * method_name, const std::string & option_name) private
Check whether it is OK to call the named method.
Parameters
[in] file __FILE_
[in] line __LINE_
[in] method_name The method name, used for error reporting.
[in] option_name The option name, sans the leading hyphen.
Definition at line 364 of file cmdline_parser.cc.
References jeod::MessageHandler::fail(), jeod::TestHarnessMessages::inconsistent_setup, and parsed.
Referenced by check_prereqs(), and check_toggle_prereqs().
check_toggle_prereqs()
bool jeod::CmdlineParser::check_toggle_prereqs (const char * file, int line, const char * method_name, const std::string & option_name, const std::string & negated_name) private
Check timing and registration prerequisites.
Parameters
[in] file __FILE_
[in] line __LINE_
[in] method_name The method name, used for error reporting.
[in] option_name The option name, sans the leading hyphen.
[in] negated_name The option name prefixed with "no".
Definition at line 446 of file cmdline_parser.cc.
References check_registration(), and check_timing().
Referenced by add_toggle().
operator=()
CmdlineParser& jeod::CmdlineParser::operator= (const CmdlineParser &) private
Not implemented.
parse()
int jeod::CmdlineParser::parse (int & argc, char ** argv)
Parse the command line.
Returns
Parse status; zero=OK, non-zero=error.
Parameters
[in,out] argc The number of command line entries.
[in,out] argv The command line entries.
Definition at line 252 of file cmdline_parser.cc.
References jeod::MessageHandler::error(), jeod::TestHarnessMessages::inconsistent_setup, jeod::TestHarnessMessages::invalid_option, jeod::CmdlineParser::BaseOptionValue::name, option_table, parsed, and jeod::MessageHandler::warn().
Field Documentation
option_table
OptionTable jeod::CmdlineParser::option_table private
All command line options and their types.
trick_io(**) trick_units(–)
Definition at line 693 of file cmdline_parser.hh.
Referenced by add_counter(), add_double(), add_int(), add_string(), add_switch(), add_toggle(), check_registration(), parse(), and ~CmdlineParser().
parsed
bool jeod::CmdlineParser::parsed private
Has the CmdlineParser::parse() been called?
trick_units(–)
Definition at line 698 of file cmdline_parser.hh.
Referenced by check_timing(), and parse().
The documentation for this class was generated from the following files:
cmdline_parser.hh
cmdline_parser.cc