JEOD: jeod::LvlhFrame Class Reference
jeod::LvlhFrame Class Reference
The class used to represent an LVLH reference frame associated with a subject DynBody.
#include <lvlh_frame.hh>
Public Member Functions
LvlhFrame ()
Construct an LvlhFrame object.
~LvlhFrame ()
Destruct an LvlhFrame object.
void initialize (DynManager &dyn_manager)
Begin initialization of an LvlhFrame.
void update ()
Update the state.
void set_subject_name (const std::string &new_name)
Set the subject_name to the supplied value.
void set_planet_name (const std::string &new_name)
Set the planet_name to the supplied value.
void set_subject_frame (RefFrame &new_frame)
Set the subject_frame to the supplied value.
void set_planet (BasePlanet &new_planet)
Set the planet whose PCI frame will be the reference for LVLH.
Data Fields
RefFrame frame
The LVLH frame defined by the subject frame's motion with respect to the reference planet.
std::string subject_name
The frame whose motion defines LVLH.
std::string planet_name
The planet used as reference for the LVLH frame.
Protected Member Functions
void compute_lvlh_frame (const RefFrameTrans &rel_trans)
Update the state of the LVLH frame wrt its parent.
Protected Attributes
RefFrame * subject_frame
The (moving) frame specified with subject_name.
RefFrame * planet_centered_inertial
The inertial frame with origin at the center of the specified planet.
Private Member Functions
LvlhFrame (const LvlhFrame &)
LvlhFrame & operator= (const LvlhFrame &)
Private Attributes
DynManager * local_dm
A local pointer to the dynamics manager needed for clean-up.
Friends
class InputProcessor
void init_attrjeod__LvlhFrame ()
Detailed Description
The class used to represent an LVLH reference frame associated with a subject DynBody.
Definition at line 84 of file lvlh_frame.hh.
Constructor & Destructor Documentation
LvlhFrame() [1/2]
jeod::LvlhFrame::LvlhFrame (void)
Construct an LvlhFrame object.
Definition at line 51 of file lvlh_frame.cc.
~LvlhFrame()
jeod::LvlhFrame::~LvlhFrame (void)
Destruct an LvlhFrame object.
Definition at line 69 of file lvlh_frame.cc.
References frame, local_dm, planet_centered_inertial, jeod::RefFrame::remove_from_parent(), jeod::RefFrameManager::remove_ref_frame(), subject_frame, and jeod::Subscription::unsubscribe().
LvlhFrame() [2/2]
jeod::LvlhFrame::LvlhFrame (const LvlhFrame &) private
Member Function Documentation
compute_lvlh_frame()
void jeod::LvlhFrame::compute_lvlh_frame (const RefFrameTrans & rel_trans) protected
Update the state of the LVLH frame wrt its parent.
Parameters
[in] rel_trans Planet relative state
Definition at line 267 of file lvlh_frame.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_quaternion(), jeod::Vector3::copy(), jeod::Vector3::cross(), frame, jeod::Vector3::normalize(), jeod::RefFrameTrans::position, jeod::RefFrameState::rot, jeod::Vector3::scale(), jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::RefFrameTrans::velocity, jeod::Vector3::vmag(), and jeod::Vector3::vmagsq().
Referenced by update().
initialize()
void jeod::LvlhFrame::initialize (DynManager & dyn_manager)
Begin initialization of an LvlhFrame.
Parameters
[in,out] dyn_manager Dynamics manager
Definition at line 96 of file lvlh_frame.cc.
References jeod::RefFrame::add_child(), jeod::EphemeridesManager::add_ref_frame(), jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::ang_vel_unit, jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_base_planet(), jeod::RefFrameManager::find_ref_frame(), frame, jeod::RefFrame::get_name(), jeod::BasePlanet::inertial, jeod::Vector3::initialize(), jeod::LvlhFrameMessages::invalid_configuration, jeod::LvlhFrameMessages::invalid_name, local_dm, planet_centered_inertial, planet_name, jeod::RefFrameState::rot, jeod::RefFrame::set_name(), jeod::RefFrame::state, subject_frame, subject_name, and jeod::Subscription::subscribe().
Referenced by jeod::DynBodyInitLvlhState::apply(), and jeod::LvlhDerivedState::initialize().
operator=()
LvlhFrame& jeod::LvlhFrame::operator= (const LvlhFrame &) private
set_planet()
void jeod::LvlhFrame::set_planet (BasePlanet & new_planet)
Set the planet whose PCI frame will be the reference for LVLH.
Parameters
[in] new_planet new planet.
Definition at line 255 of file lvlh_frame.cc.
References jeod::BasePlanet::inertial, and planet_centered_inertial.
Referenced by jeod::DynBodyInitLvlhState::apply().
set_planet_name()
void jeod::LvlhFrame::set_planet_name (const std::string & new_name)
Set the planet_name to the supplied value.
Parameters
[in] new_name new name.
Definition at line 243 of file lvlh_frame.cc.
References planet_name.
Referenced by jeod::LvlhDerivedState::initialize().
set_subject_frame()
void jeod::LvlhFrame::set_subject_frame (RefFrame & new_frame)
Set the subject_frame to the supplied value.
Parameters
[in] new_frame new frame.
Definition at line 231 of file lvlh_frame.cc.
References subject_frame.
Referenced by jeod::DynBodyInitLvlhState::apply(), and jeod::LvlhDerivedState::initialize().
set_subject_name()
void jeod::LvlhFrame::set_subject_name (const std::string & new_name)
Set the subject_name to the supplied value.
Parameters
[in] new_name new name.
Definition at line 220 of file lvlh_frame.cc.
References subject_name.
update()
void jeod::LvlhFrame::update (void)
Update the state.
Definition at line 190 of file lvlh_frame.cc.
References compute_lvlh_frame(), jeod::RefFrame::compute_relative_state(), frame, jeod::RefFrame::get_parent(), planet_centered_inertial, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, subject_frame, jeod::RefFrame::timestamp(), and jeod::RefFrameState::trans.
Referenced by jeod::DynBodyInitLvlhState::apply(), and jeod::LvlhDerivedState::update().
Friends And Related Function Documentation
init_attrjeod__LvlhFrame
void init_attrjeod__LvlhFrame () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file lvlh_frame.hh.
Field Documentation
frame
RefFrame jeod::LvlhFrame::frame
The LVLH frame defined by the subject frame's motion with respect to the reference planet.
trick_units(–)
Definition at line 95 of file lvlh_frame.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_lvlh_frame(), initialize(), jeod::LvlhDerivedState::initialize(), update(), jeod::LvlhDerivedState::update(), and ~LvlhFrame().
local_dm
DynManager* jeod::LvlhFrame::local_dm private
A local pointer to the dynamics manager needed for clean-up.
trick_units(–)
Definition at line 124 of file lvlh_frame.hh.
Referenced by initialize(), and ~LvlhFrame().
planet_centered_inertial
RefFrame* jeod::LvlhFrame::planet_centered_inertial protected
The inertial frame with origin at the center of the specified planet.
trick_units(–)
Definition at line 117 of file lvlh_frame.hh.
Referenced by initialize(), set_planet(), update(), and ~LvlhFrame().
planet_name
std::string jeod::LvlhFrame::planet_name
The planet used as reference for the LVLH frame.
trick_units(–)
Definition at line 105 of file lvlh_frame.hh.
Referenced by initialize(), and set_planet_name().
subject_frame
RefFrame* jeod::LvlhFrame::subject_frame protected
The (moving) frame specified with subject_name.
trick_units(–)
Definition at line 112 of file lvlh_frame.hh.
Referenced by initialize(), set_subject_frame(), update(), and ~LvlhFrame().
subject_name
std::string jeod::LvlhFrame::subject_name
The frame whose motion defines LVLH.
Can be on a vehicle or not.trick_units(–)
Definition at line 100 of file lvlh_frame.hh.
Referenced by initialize(), and set_subject_name().
The documentation for this class was generated from the following files:
lvlh_frame.hh
lvlh_frame.cc