JEOD: jeod::SpringPairInteraction Class Reference
jeod::SpringPairInteraction Class Reference
Simple spring contact parameters.
#include <spring_pair_interaction.hh>
Public Member Functions
SpringPairInteraction ()
Default Constructor.
~SpringPairInteraction () override
Destructor.
void calculate_forces (ContactFacet *subject, ContactFacet *target, RelativeDerivedState *rel_state, double *penetration_vector, double *rel_velocity) override
force calculation for a simple spring based contact dynamics model, takes in geometry information from the appropriate ContactFacet::calculate_forces but doesn't know about specific type of ContactFacet
Public Member Functions inherited from jeod::PairInteraction
PairInteraction ()
Default Constructor.
virtual ~PairInteraction ()
Destructor.
bool is_correct_interaction (ContactParams *subject_params, ContactParams *target_params)
Check a pair of contact params for a match to the ones defined for this pair_interaction.
Data Fields
double spring_k
Spring stiffness constant.
double damping_b
Spring damping constant.
double mu
Coefficent of friction.
Data Fields inherited from jeod::PairInteraction
char * params_1
contact param type that defines this pair interaction.
char * params_2
contact param type that defines this pair interaction.
double friction_mag
magnitude of the friction force on the contact surfaces.
Private Member Functions
SpringPairInteraction & operator= (const SpringPairInteraction &rhs)
SpringPairInteraction (const SpringPairInteraction &rhs)
Friends
class InputProcessor
void init_attrjeod__SpringPairInteraction ()
Detailed Description
Simple spring contact parameters.
Definition at line 82 of file spring_pair_interaction.hh.
Constructor & Destructor Documentation
SpringPairInteraction() [1/2]
jeod::SpringPairInteraction::SpringPairInteraction (void)
Default Constructor.
Definition at line 50 of file spring_pair_interaction.cc.
~SpringPairInteraction()
jeod::SpringPairInteraction::~SpringPairInteraction (void) override
Destructor.
Definition at line 65 of file spring_pair_interaction.cc.
SpringPairInteraction() [2/2]
jeod::SpringPairInteraction::SpringPairInteraction (const SpringPairInteraction & rhs) private
Member Function Documentation
calculate_forces()
void jeod::SpringPairInteraction::calculate_forces (ContactFacet * subject, ContactFacet * target, RelativeDerivedState * rel_state, double * penetration_vector, double * rel_velocity) override virtual
force calculation for a simple spring based contact dynamics model, takes in geometry information from the appropriate ContactFacet::calculate_forces but doesn't know about specific type of ContactFacet
Parameters
[in,out] subject subject frame of the relative state
[in,out] target target frame of the relative state
[in] rel_state relative state between subject and target in subject frame
[in] penetration_vector vector that characterises the interpenetration of the subject and the target
[in] rel_velocity relative velocity of the subject and the target in the subject frame
Implements jeod::PairInteraction.
Definition at line 86 of file spring_pair_interaction.cc.
References jeod::ContactFacet::calculate_torque(), jeod::Vector3::cross(), damping_b, jeod::Vector3::dot(), jeod::InteractionFacet::force, jeod::PairInteraction::friction_mag, mu, jeod::Vector3::negate(), jeod::Vector3::normalize(), jeod::RelativeDerivedState::rel_state, jeod::RefFrameState::rot, jeod::Vector3::scale(), spring_k, jeod::RefFrame::state, jeod::DynBody::structure, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::ContactFacet::vehicle_body, jeod::ContactFacet::vehicle_point, jeod::Vector3::vmag(), and jeod::Vector3::zero_small().
operator=()
SpringPairInteraction& jeod::SpringPairInteraction::operator= (const SpringPairInteraction & rhs) private
Friends And Related Function Documentation
init_attrjeod__SpringPairInteraction
void init_attrjeod__SpringPairInteraction () friend
InputProcessor
friend class InputProcessor friend
Definition at line 85 of file spring_pair_interaction.hh.
Field Documentation
damping_b
double jeod::SpringPairInteraction::damping_b
Spring damping constant.
trick_units(N*s/m)
Definition at line 96 of file spring_pair_interaction.hh.
Referenced by calculate_forces().
mu
double jeod::SpringPairInteraction::mu
Coefficent of friction.
trick_units(–)
Definition at line 101 of file spring_pair_interaction.hh.
Referenced by calculate_forces().
spring_k
double jeod::SpringPairInteraction::spring_k
Spring stiffness constant.
trick_units(N/m)
Definition at line 91 of file spring_pair_interaction.hh.
Referenced by calculate_forces().
The documentation for this class was generated from the following files:
spring_pair_interaction.hh
spring_pair_interaction.cc