MODEL_TYPE  = utils
MODEL_NAME  = orientation
MODEL_TITLE = 'Orientation Model'

DOT_FILES = \
	representations.dot

# Figures generated by dot
DOT_PDF_FILES = $(subst .dot,.pdf,$(DOT_FILES))

EXTRA_DEPENDS = $(DOT_PDF_FILES)
