JEOD: jeod::Matrix3x3 Class Reference
jeod::Matrix3x3 Class Reference
Provides static methods for operations that involve 3x3 matrices.
#include <matrix3x3.hh>
Static Public Member Functions
static void initialize (double mat[3][3])
Zero-fill matrix: mat[i][j] = 0.0.
static void identity (double mat[3][3])
Construct identity matrix: mat[i][j] = delta_ij.
static void cross_matrix (double const vec[3], double cross_mat[3][3])
Construct the skew symmetric cross product matrix: mat[i][k] = epsilon_ijk vec[j], epsilon_ijk is the Levi-Cevita symbol.
static void outer_product (double const vec_left[3], double const vec_right[3], double prod[3][3])
Construct the outer product of two vectors: mat[i][j] = vec_left[i] * vec_right[j].
static void negate (double mat[3][3])
Negated matrix in-place: mat[i][j] = -mat[i][j].
static void transpose (double mat[3][3])
Transpose matrix in-place: mat[i][j] = mat[j][i].
static void scale (double scalar, double mat[3][3])
Scale matrix in-place, mat[i][j] = scalar * mat[i][j].
static void incr (double const addend[3][3], double mat[3][3])
Increment matrix in-place: mat[i][j] = mat[i][j] + addend[i][j].
static void decr (double const subtrahend[3][3], double mat[3][3])
Decrement matrix in-place: mat[i][j] = mat[i][j] - subtrahend[i][j].
static void copy (double const input_mat[3][3], double copy[3][3])
Copy matrix: copy[i][j] = mat[i][j].
static void negate (double const input_mat[3][3], double copy[3][3])
Negate matrix: copy[i][j] = -mat[i][j].
static void transpose (double const input_mat[3][3], double trans[3][3])
Transpose matrix: copy[i][j] = mat[j][i].
static void scale (double const mat[3][3], double scalar, double prod[3][3])
Scale matrix: copy[i][j] = scalar * mat[i][j].
static void add (double const augend[3][3], double const addend[3][3], double sum[3][3])
Add matrices: sum[i][j] = augend[i][j] + addend[i][j].
static void subtract (double const minuend[3][3], double const subtrahend[3][3], double diff[3][3])
Subtract matrices: diff[i][j] = minuend[i][j] - subtrahend[i][j].
static void product (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3])
Compute the matrix product mat_left * mat_right: prod[i][j] = mat_left[i][k] * mat_right[k][j].
static void product_left_transpose (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3])
Compute the matrix product mat_left^T * mat_right: prod[i][j] = mat_left[k][i] * mat_right[k][j].
static void product_right_transpose (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3])
Compute the matrix product mat_left * mat_right^T: prod[i][j] = sum_k mat_left[i][k] * mat_right[j][k].
static void product_transpose_transpose (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3])
Compute the matrix product mat_left^T * mat_right^T: prod[i][j] = sum_k mat_left[k][i] * mat_right[j][k].
static void transform_matrix (double const trans[3][3], double const mat[3][3], double prod[3][3])
Compute the matrix product trans * mat * trans^T prod[i][j] = trans[i][k] * mat[k][l] * trans[j][l].
static void transpose_transform_matrix (double const trans[3][3], double const mat[3][3], double prod[3][3])
Compute the matrix product trans^T * mat * trans prod[i][j] = trans[k][i] * mat[k][l] * trans[l][j].
static int invert (double const matrix[3][3], double inverse[3][3])
Compute the inverse of a 3x3 matrix.
static int invert_symmetric (double const matrix[3][3], double inverse[3][3])
Compute the inverse of a symmetric 3x3 matrix.
static void print (double const mat[3][3])
Print matrix to standard error.
Detailed Description
Provides static methods for operations that involve 3x3 matrices.
Definition at line 72 of file matrix3x3.hh.
Member Function Documentation
add()
void jeod::Matrix3x3::add (double const augend[3][3], double const addend[3][3], double sum[3][3]) inline static
Add matrices: sum[i][j] = augend[i][j] + addend[i][j].
Parameters
[in] augend Matrix
[in] addend Matrix
[out] sum Sum
Definition at line 410 of file matrix3x3_inline.hh.
Referenced by jeod::MassBody::calc_composite_inertia().
copy()
void jeod::Matrix3x3::copy (double const input_mat[3][3], double copy[3][3]) inline static
Copy matrix: copy[i][j] = mat[i][j].
Parameters
[in] input_mat Source matrix
[out] copy Matrix copy
Definition at line 296 of file matrix3x3_inline.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::attach_to_frame(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::MassPoint::compute_state_wrt_pred(), jeod::RefFrameRot::copy(), jeod::MassPointState::copy_state(), jeod::PlanetRotation::get_rotation(), jeod::Orientation::get_transform(), jeod::GravityManager::gravitation(), jeod::MassPointState::incr_right(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), jeod::MassBody::initialize_mass(), jeod::MassPointInit::initialize_mass_point(), jeod::MassPropertiesInit::initialize_mass_properties(), negate(), jeod::Orientation::Orientation(), jeod::BasePlanet::set_alt_pfix(), jeod::DynBody::set_attitude_matrix(), jeod::ConstraintFrame::set_struct_to_constraint_frame(), jeod::Orientation::set_transform(), jeod::GravityTorque::update(), jeod::MassBody::update_mass_properties(), and jeod::MassPointState::update_orientation().
cross_matrix()
void jeod::Matrix3x3::cross_matrix (double const vec[3], double cross_mat[3][3]) inline static
Construct the skew symmetric cross product matrix: mat[i][k] = epsilon_ijk vec[j], epsilon_ijk is the Levi-Cevita symbol.
Parameters
[in] vec Vector
[out] cross_mat Cross product matrix
Definition at line 115 of file matrix3x3_inline.hh.
decr()
void jeod::Matrix3x3::decr (double const subtrahend[3][3], double mat[3][3]) inline static
Decrement matrix in-place: mat[i][j] = mat[i][j] - subtrahend[i][j].
Parameters
[in] subtrahend Decrement
[in,out] mat Decremented matrix
Definition at line 271 of file matrix3x3_inline.hh.
identity()
void jeod::Matrix3x3::identity (double mat[3][3]) inline static
Construct identity matrix: mat[i][j] = delta_ij.
Parameters
[out] mat Identity matrix
Definition at line 94 of file matrix3x3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::BodyAttachAligned::apply(), jeod::BasePlanet::BasePlanet(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::ConstraintFrame::ConstraintFrame(), jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver(), jeod::RefFrameRot::initialize(), jeod::MassPointState::initialize_mass_point(), jeod::MassBody::MassBody(), jeod::MassPointState::MassPointState(), jeod::MassPointState::negate(), jeod::Orientation::Orientation(), jeod::PendulumConstraintComponent::PendulumConstraintComponent(), jeod::PlanetRotation::PlanetRotation(), and jeod::NutationJ2000::update_rotation().
incr()
void jeod::Matrix3x3::incr (double const addend[3][3], double mat[3][3]) inline static
Increment matrix in-place: mat[i][j] = mat[i][j] + addend[i][j].
Parameters
[in] addend Increment
[in,out] mat Incremented matrix
Definition at line 246 of file matrix3x3_inline.hh.
Referenced by jeod::MassBody::calc_composite_inertia(), and jeod::GravityManager::gravitation().
initialize()
void jeod::Matrix3x3::initialize (double mat[3][3]) inline static
Zero-fill matrix: mat[i][j] = 0.0.
Parameters
[out] mat Zero-filled matrix
Definition at line 76 of file matrix3x3_inline.hh.
Referenced by jeod::DynBody::attach_child(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::PrecessionMars::compute_fixed_matrices(), jeod::Orientation::compute_matrix_from_euler_angles(), jeod::ConstrainedRigidMass::ConstrainedRigidMass(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), jeod::MassBody::detach_update_properties(), jeod::GravityControls::gravitation(), jeod::GravityControls::GravityControls(), jeod::GravityInteraction::GravityInteraction(), jeod::MassProperties::MassProperties(), jeod::MassPropertiesInit::MassPropertiesInit(), jeod::PlanetRNP::PlanetRNP(), jeod::PrecessionMars::PrecessionMars(), jeod::MassBody::update_mass_properties(), and jeod::NutationMars::update_rotation().
invert()
int jeod::Matrix3x3::invert (double const matrix[3][3], double inverse[3][3]) static
Compute the inverse of a 3x3 matrix.
Assumptions and Limitations
Input and output matrices are distinct.
Input matrix is well-conditioned.
Returns
0=success, non-zero=singular
Parameters
[in] matrix Matrix to invert
[out] inverse Inverse
Definition at line 75 of file dm_invert.cc.
References jeod::MessageHandler::error(), and jeod::MathMessages::ill_conditioned.
invert_symmetric()
int jeod::Matrix3x3::invert_symmetric (double const matrix[3][3], double inverse[3][3]) static
Compute the inverse of a symmetric 3x3 matrix.
Assumptions and Limitations
Input and output matrices are distinct.
Input matrix is symmetric.
Determinate is non-zero.
Returns
0=success, non-zero=singular
Parameters
[in] matrix Symmetric matrix to invert
[out] inverse Inverse
Definition at line 76 of file dm_invert_symm.cc.
References jeod::MessageHandler::error(), and jeod::MathMessages::ill_conditioned.
Referenced by jeod::MassBody::detach_update_properties(), and jeod::MassBody::update_mass_properties().
negate() [1/2]
void jeod::Matrix3x3::negate (double mat[3][3]) inline static
Negated matrix in-place: mat[i][j] = -mat[i][j].
Parameters
[in,out] mat Negated matrix
Definition at line 169 of file matrix3x3_inline.hh.
negate() [2/2]
void jeod::Matrix3x3::negate (double const input_mat[3][3], double copy[3][3]) inline static
Negate matrix: copy[i][j] = -mat[i][j].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] input_mat Source matrix
[out] copy Negated matrix
Definition at line 325 of file matrix3x3_inline.hh.
References copy().
outer_product()
void jeod::Matrix3x3::outer_product (double const vec_left[3], double const vec_right[3], double prod[3][3]) inline static
Construct the outer product of two vectors: mat[i][j] = vec_left[i] * vec_right[j].
Parameters
[in] vec_left Vector
[in] vec_right Vector
[out] prod Outer product matrix
Definition at line 145 of file matrix3x3_inline.hh.
print()
void jeod::Matrix3x3::print (double const mat[3][3]) inline static
Print matrix to standard error.
Parameters
[in] mat Matrix to print
Definition at line 736 of file matrix3x3_inline.hh.
product()
void jeod::Matrix3x3::product (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3]) inline static
Compute the matrix product mat_left * mat_right: prod[i][j] = mat_left[i][k] * mat_right[k][j].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] mat_left Multiplier
[in] mat_right Multiplicand
[out] prod Product
Definition at line 468 of file matrix3x3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::BasePlanet::calculate_alt_pfix(), jeod::PrecessionMars::compute_fixed_matrices(), jeod::Orientation::compute_matrix_from_euler_angles(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::PlanetRNP::propagate_rnp(), transform_matrix(), jeod::DynBodyConstraintsSolver::transform_matrix_from_root(), transpose_transform_matrix(), jeod::ConstraintFrame::update_root_to_constraint_frame(), and jeod::PrecessionMars::update_rotation().
product_left_transpose()
void jeod::Matrix3x3::product_left_transpose (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3]) inline static
Compute the matrix product mat_left^T * mat_right: prod[i][j] = mat_left[k][i] * mat_right[k][j].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] mat_left Multiplier
[in] mat_right Multiplicand
[out] prod Product
Definition at line 525 of file matrix3x3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), transpose_transform_matrix(), and jeod::CheckItem::within_eigen_tolerance().
product_right_transpose()
void jeod::Matrix3x3::product_right_transpose (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3]) inline static
Compute the matrix product mat_left * mat_right^T: prod[i][j] = sum_k mat_left[i][k] * mat_right[j][k].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] mat_left Multiplier
[in] mat_right Multiplicand
[out] prod Product
Definition at line 582 of file matrix3x3_inline.hh.
Referenced by jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), transform_matrix(), and jeod::SpiceEphemOrientation::update().
product_transpose_transpose()
void jeod::Matrix3x3::product_transpose_transpose (double const mat_left[3][3], double const mat_right[3][3], double prod[3][3]) inline static
Compute the matrix product mat_left^T * mat_right^T: prod[i][j] = sum_k mat_left[k][i] * mat_right[j][k].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] mat_left Multiplier
[in] mat_right Multiplicand
[out] prod Product
Definition at line 639 of file matrix3x3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::PlanetRNP::propagate_rnp(), and jeod::PlanetRNP::update_rnp().
scale() [1/2]
void jeod::Matrix3x3::scale (double scalar, double mat[3][3]) inline static
Scale matrix in-place, mat[i][j] = scalar * mat[i][j].
Parameters
[in] scalar Scalar
[in,out] mat Scaled matrix
Definition at line 221 of file matrix3x3_inline.hh.
scale() [2/2]
void jeod::Matrix3x3::scale (double const mat[3][3], double scalar, double prod[3][3]) inline static
Scale matrix: copy[i][j] = scalar * mat[i][j].
Parameters
[in] mat Matrix
[in] scalar Scalar
[out] prod Product
Definition at line 383 of file matrix3x3_inline.hh.
subtract()
void jeod::Matrix3x3::subtract (double const minuend[3][3], double const subtrahend[3][3], double diff[3][3]) inline static
Subtract matrices: diff[i][j] = minuend[i][j] - subtrahend[i][j].
Parameters
[in] minuend Matrix
[in] subtrahend Matrix
[out] diff Difference
Definition at line 437 of file matrix3x3_inline.hh.
Referenced by jeod::MassPropertiesInit::initialize_mass_properties().
transform_matrix()
void jeod::Matrix3x3::transform_matrix (double const trans[3][3], double const mat[3][3], double prod[3][3]) inline static
Compute the matrix product trans * mat * trans^T prod[i][j] = trans[i][k] * mat[k][l] * trans[j][l].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] trans Transformation matrix
[in] mat Matrix to transform
[out] prod Product
Definition at line 696 of file matrix3x3_inline.hh.
References product(), and product_right_transpose().
Referenced by jeod::MassPropertiesInit::initialize_mass_properties(), and jeod::GravityTorque::update().
transpose() [1/2]
void jeod::Matrix3x3::transpose (double mat[3][3]) inline static
Transpose matrix in-place: mat[i][j] = mat[j][i].
Parameters
[in,out] mat Transposed matrix
Definition at line 194 of file matrix3x3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::MassPoint::compute_pred_rel_state(), jeod::RefFrame::compute_relative_state(), jeod::PlanetRotation::get_rotation_transpose(), jeod::MassPointInit::initialize_mass_point(), jeod::MassPointState::negate(), jeod::RefFrameState::negate(), jeod::PlanetRNP::propagate_rnp(), and jeod::EulerDerivedState::update().
transpose() [2/2]
void jeod::Matrix3x3::transpose (double const input_mat[3][3], double trans[3][3]) inline static
Transpose matrix: copy[i][j] = mat[j][i].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] input_mat Source matrix
[out] trans Matrix transpose
Definition at line 355 of file matrix3x3_inline.hh.
transpose_transform_matrix()
void jeod::Matrix3x3::transpose_transform_matrix (double const trans[3][3], double const mat[3][3], double prod[3][3]) inline static
Compute the matrix product trans^T * mat * trans prod[i][j] = trans[k][i] * mat[k][l] * trans[l][j].
Assumptions and Limitations
Input and output matrices are distinct.
Parameters
[in] trans Transformation matrix
[in] mat Matrix to transform
[out] prod Product
Definition at line 719 of file matrix3x3_inline.hh.
References product(), and product_left_transpose().
Referenced by jeod::MassBody::calc_composite_inertia(), and jeod::SphericalHarmonicsGravityControls::calc_nonspherical().
The documentation for this class was generated from the following files:
matrix3x3.hh
matrix3x3_inline.hh
dm_invert.cc
dm_invert_symm.cc