JEOD: jeod::PointContactFacetFactory Class Reference
jeod::PointContactFacetFactory Class Reference
Creates a PointContactFacet from an InteractionFacet.
#include <point_contact_facet_factory.hh>
Public Member Functions
PointContactFacetFactory ()
Default Constructor.
~PointContactFacetFactory () override
Destructor.
InteractionFacet * create_facet (Facet *facet, FacetParams *params) override
Create a PointContactFacet from a CircularFlatPlate facet and a ContactParams object.
bool is_correct_factory (Facet *facet) override
PointContactFacetFactory specific implementation of this function.
Public Member Functions inherited from jeod::InteractionFacetFactory
InteractionFacetFactory ()
Default Constructor.
virtual ~InteractionFacetFactory ()
Destructor.
Private Member Functions
PointContactFacetFactory & operator= (const PointContactFacetFactory &rhs)
PointContactFacetFactory (const PointContactFacetFactory &rhs)
Friends
class InputProcessor
void init_attrjeod__PointContactFacetFactory ()
Additional Inherited Members
Protected Attributes inherited from jeod::InteractionFacetFactory
bool trick_bool
Unused data field to expedite dynamic allocation in Trick environment.
Detailed Description
Creates a PointContactFacet from an InteractionFacet.
Definition at line 85 of file point_contact_facet_factory.hh.
Constructor & Destructor Documentation
PointContactFacetFactory() [1/2]
jeod::PointContactFacetFactory::PointContactFacetFactory (void)
Default Constructor.
Definition at line 53 of file point_contact_facet_factory.cc.
References JEOD_REGISTER_CLASS.
~PointContactFacetFactory()
jeod::PointContactFacetFactory::~PointContactFacetFactory (void) override
Destructor.
Definition at line 64 of file point_contact_facet_factory.cc.
PointContactFacetFactory() [2/2]
jeod::PointContactFacetFactory::PointContactFacetFactory (const PointContactFacetFactory & rhs) private
Member Function Documentation
create_facet()
InteractionFacet * jeod::PointContactFacetFactory::create_facet (Facet * facet, FacetParams * params) override virtual
Create a PointContactFacet from a CircularFlatPlate facet and a ContactParams object.
Returns
The new EllipsoidContactFacet. Note that this is allocated and YOU are responsible for destroying it at the end!
Parameters
[in] facet The CircularFlatPlate. This MUST be a circular flat plate or the algorithm will send a failure message
[in] params ContactParams
Implements jeod::InteractionFacetFactory.
Definition at line 82 of file point_contact_facet_factory.cc.
References jeod::InteractionFacet::base_facet, jeod::Vector3::copy(), jeod::ContactFacet::create_vehicle_point(), jeod::MassBody::dyn_owner, jeod::MessageHandler::fail(), jeod::Facet::get_mass_body_ptr(), jeod::ContactMessages::initialization_error, JEOD_ALLOC_CLASS_OBJECT, jeod::FlatPlate::normal, jeod::ContactFacet::normal, jeod::ContactFacet::position, jeod::Facet::position, jeod::FlatPlateCircular::radius, jeod::PointContactFacet::radius, jeod::PointContactFacet::set_max_dimension(), jeod::ContactFacet::surface_type, and jeod::ContactFacet::vehicle_body.
is_correct_factory()
bool jeod::PointContactFacetFactory::is_correct_factory (Facet * facet) override virtual
PointContactFacetFactory specific implementation of this function.
If the Facet is of type CircularFlatPlate, returns true. False otherwise
Returns
true if facet is a FlatPlateCircular, false otherwise
Parameters
[in] facet The facet to check
Implements jeod::InteractionFacetFactory.
Definition at line 159 of file point_contact_facet_factory.cc.
operator=()
PointContactFacetFactory& jeod::PointContactFacetFactory::operator= (const PointContactFacetFactory & rhs) private
Friends And Related Function Documentation
init_attrjeod__PointContactFacetFactory
void init_attrjeod__PointContactFacetFactory () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file point_contact_facet_factory.hh.
The documentation for this class was generated from the following files:
point_contact_facet_factory.hh
point_contact_facet_factory.cc