/* Autogenerated from environment/atmosphere/data/solar_mean.d */

/*
PURPOSE:
   (Earth's mean mean solar activity MET atmospheric parameters.)

REFERENCE:
   (((Jacchia, L.G.) (New Static Models of the Thermosphere and
       Exosphere with Empirical Temperature Profiles) (Smithsonian
       Astrophysical Observatory Special Report No. 313) (--) (1970) (--))
    ((Jacchia, L.G.) (Revised Static Models of the Termosphere
       and Exosphere with Emperical Temperature Profiles)
       (Smithsonian Astrophysical Observatory Report No. 332) (--)
       (1971) (--)))

ASSUMPTIONS AND LIMITATIONS:
   (Parameters for mean solar activity.)


*/

class METAtmosphere;
#define JEOD_FRIEND_CLASS METAtmosphere_solar_mean_default_data

// JEOD includes
#include "environment/atmosphere/MET/include/MET_atmosphere.hh"

// Unsupported includes
#include "../include/solar_mean.hh"

//! Namespace jeod
namespace jeod
{

void METAtmosphere_solar_mean_default_data::initialize(METAtmosphere * METAtmosphere_ptr)
{
    /* Geomagnetic and solar activity parmeters. */
    METAtmosphere_ptr->geo_index_type = METAtmosphere::ATMOS_MET_GI_AP;
    METAtmosphere_ptr->geo_index = 15.7;
    METAtmosphere_ptr->F10 = 128.8;
    METAtmosphere_ptr->F10B = 128.8;
}
} // namespace jeod
