JEOD: jeod::TimeConverter_TAI_GPS Class Reference
jeod::TimeConverter_TAI_GPS Class Reference
Define class TimeConverter_TAI_GPS, which converts between International Atomic Time and the clock associated with the Global Positioning System.
#include <time_converter_tai_gps.hh>
Public Member Functions
TimeConverter_TAI_GPS ()
Construct a TimeConverter_TAI_GPS.
~TimeConverter_TAI_GPS () override
Destroy a TimeConverter_TAI_GPS.
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void convert_a_to_b (void) override
Convert from TimeTAI to TimeGPS.
void convert_b_to_a (void) override
Convert from TimeGPS to TimeTAI.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()
Destroy a TimeConverter.
virtual bool is_initialized (void)
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void reset_a_to_b_offset (void)
Resets the offset between type a and type b mid-sim.
virtual void verify_table_lookup_ends (void)
This function does absolutely nothing.
double get_a_to_b_offset (void)
Return the offset from the parent time object to this object.
Private Member Functions
TimeConverter_TAI_GPS (const TimeConverter_TAI_GPS &)
TimeConverter_TAI_GPS & operator= (const TimeConverter_TAI_GPS &)
Private Attributes
TimeTAI * tai_ptr
Converter parent time, always a TimeTAI for this converter.
TimeGPS * gps_ptr
Converter parent time, always a TimeGPS for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_TAI_GPS ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name
name of time-type "a".
std::string b_name
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()
Construct a TimeConverter.
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized
whether converter has been initialized.
double a_to_b_offset
Difference between the two time-types.
Direction valid_directions
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Define class TimeConverter_TAI_GPS, which converts between International Atomic Time and the clock associated with the Global Positioning System.
Definition at line 88 of file time_converter_tai_gps.hh.
Constructor & Destructor Documentation
TimeConverter_TAI_GPS() [1/2]
jeod::TimeConverter_TAI_GPS::TimeConverter_TAI_GPS (void)
Construct a TimeConverter_TAI_GPS.
Definition at line 59 of file time_converter_tai_gps.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::ANY_DIRECTION, jeod::TimeConverter::b_name, gps_ptr, tai_ptr, and jeod::TimeConverter::valid_directions.
~TimeConverter_TAI_GPS()
jeod::TimeConverter_TAI_GPS::~TimeConverter_TAI_GPS (void) override
Destroy a TimeConverter_TAI_GPS.
Definition at line 137 of file time_converter_tai_gps.cc.
TimeConverter_TAI_GPS() [2/2]
jeod::TimeConverter_TAI_GPS::TimeConverter_TAI_GPS (const TimeConverter_TAI_GPS &) private
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_TAI_GPS::convert_a_to_b (void) override virtual
Convert from TimeTAI to TimeGPS.
Reimplemented from jeod::TimeConverter.
Definition at line 113 of file time_converter_tai_gps.cc.
References jeod::TimeConverter::a_to_b_offset, gps_ptr, jeod::JeodBaseTime::seconds, jeod::TimeGPS::set_time_by_seconds(), and tai_ptr.
convert_b_to_a()
void jeod::TimeConverter_TAI_GPS::convert_b_to_a (void) override virtual
Convert from TimeGPS to TimeTAI.
Reimplemented from jeod::TimeConverter.
Definition at line 125 of file time_converter_tai_gps.cc.
References jeod::TimeConverter::a_to_b_offset, gps_ptr, jeod::JeodBaseTime::seconds, jeod::TimeStandard::set_time_by_seconds(), and tai_ptr.
initialize()
void jeod::TimeConverter_TAI_GPS::initialize (JeodBaseTime * parent_ptr, JeodBaseTime * child_ptr, const int int_dir) override virtual
Initialize the converter.
Assumptions and Limitations
None
Parameters
[in] parent_ptr Time used to initialize the converter
[in] child_ptr Other Time used to initialize the converter
[in] int_dir Conversion direction: +1 a=parent; -1 b=parent; 0 error
Implements jeod::TimeConverter.
Definition at line 80 of file time_converter_tai_gps.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::MessageHandler::fail(), gps_ptr, jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, tai_ptr, jeod::TimeStandard::tjt_at_epoch, and jeod::TimeConverter::verify_setup().
operator=()
TimeConverter_TAI_GPS& jeod::TimeConverter_TAI_GPS::operator= (const TimeConverter_TAI_GPS &) private
Friends And Related Function Documentation
init_attrjeod__TimeConverter_TAI_GPS
void init_attrjeod__TimeConverter_TAI_GPS () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file time_converter_tai_gps.hh.
Field Documentation
gps_ptr
TimeGPS* jeod::TimeConverter_TAI_GPS::gps_ptr private
Converter parent time, always a TimeGPS for this converter.
trick_units(–)
Definition at line 102 of file time_converter_tai_gps.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), initialize(), and TimeConverter_TAI_GPS().
tai_ptr
TimeTAI* jeod::TimeConverter_TAI_GPS::tai_ptr private
Converter parent time, always a TimeTAI for this converter.
trick_units(–)
Definition at line 97 of file time_converter_tai_gps.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), initialize(), and TimeConverter_TAI_GPS().
The documentation for this class was generated from the following files:
time_converter_tai_gps.hh
time_converter_tai_gps.cc