JEOD: jeod::DynManager Class Reference
jeod::DynManager Class Reference
The DynManager class manages the dynamic elements of a simulation.
#include <dyn_manager.hh>
Public Member Functions
DynManager ()
DynManager default constructor.
~DynManager () override
DynManager destructor.
DynManager (const DynManager &)=delete
DynManager & operator= (const DynManager &)=delete
bool is_initialized ()
Determine if the manager has been initialized.
void initialize_model (DynManagerInit &init, TimeManager &time_mngr)
Begin initialization of the JEOD manager model.
void initialize_model (JeodIntegratorInterface &integ_if, DynManagerInit &init, TimeManager &time_mngr)
Begin initialization of the JEOD manager model.
void initialize_simulation ()
Complete initialization of the JEOD manager model.
void set_gravity_manager (GravityManager &gravity) override
Set the Gravity Manager to the specified reference.
void initialize_gravity_controls () override
Initialize the gravity controls for each dynamic body.
void reset_gravity_controls () override
Reset the gravity controls for each dynamic body.
void gravitation ()
Compute gravitational acceleration on each root body.
void add_mass_body (MassBody &mass_body) override
Add a mass body to the mass body registry.
void add_mass_body (MassBody *mass_body) override
Add a mass body to the mass body registry.
MassBody * find_mass_body (const std::string &name) const override
Find the mass body with the given name.
bool is_mass_body_registered (const MassBody *mass_body) const override
Determine if the specified body has been registered with the DynManager.
void add_dyn_body (DynBody &dyn_body) override
Add a dynamic body to the dynamic body registry.
DynBody * find_dyn_body (const std::string &name) const override
Find the dynamic body with the given name.
std::vector< DynBody * > get_dyn_bodies () const override
Return a copy of the list of registered dynamic bodies.
bool is_dyn_body_registered (const DynBody *dyn_body) const override
Determine if the specified body has been registered with the DynManager.
void add_integ_group (DynamicsIntegrationGroup &integ_group) override
Add an integration group to the integration group registry.
bool is_integ_group_registered (const DynamicsIntegrationGroup *integ_group) const override
Determine if the specified group has been registered with the DynManager.
void add_body_action (BodyAction &body_action)
Add a body action to the list of such.
void remove_body_action (const std::string &action_name_in)
Remove a body action to the list of such.
void perform_actions ()
Perform dynamic body actions that are ready to be applied.
void initialize_integ_groups ()
Complete initialization of the initialization groups.
void update_integration_group (JeodIntegrationGroup &group) override
Add DynBody objects to the default integration group.
void initialize_dyn_bodies ()
Initialize dynamic bodies.
void initialize_dyn_body (DynBody &body)
Initialize a specific dynamic body.
void compute_derivatives ()
Collect forces and torques on each body and compute derivatives.
void reset_integrators () override
Force all integrators to reset themselves.
void reset_integrators (DynamicsIntegrationGroup &integ_group) override
Instruct specific integrator to reset itself.
int integrate (double to_sim_time, TimeManager &)
Propagate all vehicles and propagate time.
double timestamp () const override
Return last update time.
const std::string name () const
Return identifier.
void shutdown ()
Shutdown the manager.
Public Member Functions inherited from jeod::JeodIntegrationGroupOwner
virtual ~JeodIntegrationGroupOwner ()=default
Destructor.
Public Member Functions inherited from jeod::BaseDynManager
~BaseDynManager () override=default
Public Member Functions inherited from jeod::BaseEphemeridesManager
~BaseEphemeridesManager () override=default
Destructor.
Public Member Functions inherited from jeod::BaseRefFrameManager
virtual ~BaseRefFrameManager ()=default
Destructor.
Public Member Functions inherited from jeod::EphemeridesManager
EphemeridesManager ()
EphemeridesManager default constructor.
~EphemeridesManager () override
EphemeridesManager destructor.
EphemeridesManager (const EphemeridesManager &)=delete
EphemeridesManager & operator= (const EphemeridesManager &)=delete
bool ref_frame_tree_needs_rebuild () const
Query if the reference frame tree needs to be rebuilt.
void ephem_note_tree_status_change () override
Denote that the reference frame tree needs to be rebuilt.
void add_planet (BasePlanet &planet) override
Add a planet to the planets registry.
void add_planet (Planet &planet) override
Add a planet to the registry.
BasePlanet * find_base_planet (const std::string &name) const override
Find the planet with the given name.
Planet * find_planet (const std::string &name) const override
Find the planet with the given name.
unsigned int get_num_planets () const override
Return number of registered planets.
void add_ephemeris (EphemerisInterface &ephem_if) override
Add an ephemeris model to the list of managed models.
void clear_added_ephemerides () override
Deactivate any registered ephemeris items and remove them from the list.
void disable_add_ephemeris () override
Make subsequent calls to add_ephemeris deactivate the specified ephemeris model instead of adding it to the list of managed models.
void add_ephem_item (EphemerisItem &ephem_item) override
Add an ephemeris item to the set of ephemeris items known to the ephemerides manager.
EphemerisItem * find_ephem_item (const std::string &name) const override
Find the first registered EphemerisItem with the given name.
EphemerisOrientation * find_ephem_angle (const std::string &name) const override
Find the EphemerisOrientation with the given name.
EphemerisPoint * find_ephem_point (const std::string &name) const override
Find the EphemerisPoint with the given name.
void add_integ_frame (EphemerisRefFrame &ref_frame) override
Add a frame to the reference frame and integration frame lists.
EphemerisRefFrame * find_integ_frame (const std::string &name) const override
Find the integration frame with the given name.
bool is_integ_frame (const RefFrame &ref_frame) const override
Determine if supplied frame is an integration frame.
unsigned int find_integ_frame_index (const EphemerisRefFrame &ref_frame) const override
Find the index of provided frame in the integration frames vector.
const std::vector< EphemerisRefFrame * > & get_integ_frames () const override
Get a copy of the vector of integration frames.
void add_ref_frame (RefFrame &ref_frame) override
Add a reference frame to the reference frame registry.
void set_target_frame (RefFrame &ref_frame)
Set the target-frame reference for the ref-frame and all known EphemItems with similar target-frame names.
void initialize_ephemerides ()
Initialize the ephemeris models.
void activate_ephemerides ()
Activate ephemeris items based on frame subscription status, activate ephemeris models, and build the reference frame tree.
void update_ephemerides ()
Update each ephemeris model.
Public Member Functions inherited from jeod::RefFrameManager
RefFrameManager ()
RefFrameManager default constructor.
~RefFrameManager () override
RefFrameManager destructor.
RefFrameManager (const RefFrameManager &)=delete
RefFrameManager & operator= (const RefFrameManager &)=delete
void add_ref_frame (RefFrame &ref_frame) override
Add a reference frame to the reference frame registry.
void remove_ref_frame (RefFrame &ref_frame) override
Remove a reference frame from the reference frame registry.
RefFrame * find_ref_frame (const std::string &name) const override
Find the reference frame with the given name.
RefFrame * find_ref_frame (const std::string &prefix, const std::string &suffix) const override
Find the reference frame with the dot-conjoined name "${prefix}.${suffix}".
void check_ref_frame_ownership () const override
Check that each active reference frame has an owner.
void reset_tree_root_node () override
Reset the root node in anticipation of rebuilding the entire tree.
void add_frame_to_tree (RefFrame &ref_frame, RefFrame *parent) override
Insert a reference frame in the reference frame tree.
void subscribe_to_frame (const std::string &frame_name) override
Subscribe to a reference frame, with the frame specified by name.
void subscribe_to_frame (RefFrame &frame) override
Subscribe to a reference frame, with the frame specified as an argument.
void unsubscribe_to_frame (const std::string &frame_name) override
Remove subscription to a reference frame, with the frame specified by name.
void unsubscribe_to_frame (RefFrame &frame) override
Remove subscription to a reference frame, with the frame specified as an argument.
bool frame_is_subscribed (const std::string &frame_name) override
Checks whether frame has subscribers; frame specified by name.
bool frame_is_subscribed (RefFrame &frame) override
Checks whether frame has subscribers; frame provided as an argument.
Data Fields
bool deriv_ephem_update {}
Update ephemerides at the derivative rate?
bool gravity_off {}
This flag exists primarily to support unit tests.
DynManagerInit::EphemerisMode mode {DynManagerInit::EphemerisMode_Ephemerides}
The ephemeris mode in which the dynamics manager operates.
Trick::Integrator * sim_integrator {}
Pointer to the integration object used by the simulation engine itself.
Protected Member Functions
virtual void initialize_model_internal (DynManagerInit &init, TimeManager &time_mngr)
Begin initialization of the JEOD manager model.
void perform_mass_body_initializations (MassBody *body=nullptr)
Initialize all queued body actions that derive from MassBodyInit and apply those that are immediately ready to be applied.
void perform_mass_attach_initializations ()
Initialize all queued body actions that derive from MassBodyAttach and apply those that are immediately ready to be applied.
void perform_dyn_body_initializations (DynBody *body=nullptr)
Initialize dynamic bodies.
void check_for_uninitialized_states ()
Ensure that all of the required states have been set.
Protected Member Functions inherited from jeod::RefFrameManager
bool validate_name (const char *file, unsigned int line, const std::string &variable_value, const std::string &variable_type, const std::string &variable_name) const
Check whether a name is trivially valid/invalid.
Protected Attributes
bool initialized {}
Have all initializations been performed?
GravityManager * gravity_manager {}
The model that encapsulates all of the gravity models.
er7_utils::IntegratorConstructor * integ_constructor {}
Integrator generator.
JeodIntegratorInterface * integ_interface {}
Interface with the simulation integration structure.
DynamicsIntegrationGroup * default_integ_group {}
The integration group used for simple monolithic simulations.
SinglePointEphemeris * simple_ephemeris {}
Simple ephemeris for use in empty space and single planet modes.
std::vector< MassBody * > mass_bodies
List of vehicle models.
std::vector< DynBody * > dyn_bodies
List of vehicle models.
std::vector< DynamicsIntegrationGroup * > integ_groups
List of integration groups.
std::list< BodyAction * > body_actions
List of body initializers.
Protected Attributes inherited from jeod::EphemeridesManager
bool single_ephem_mode {}
Set via a call to disable_add_ephemeris, typically to allow a simple ephemeris model to be active with all other models made inactive.
bool regenerate_ref_frame_tree {}
Set when the reference frame tree needs to be regenerated.
double update_time {}
Time of last update.
JeodPointerVector< BasePlanet >::type planets
The planets in a simulation, typically defined at the S_define level.
JeodPointerVector< EphemerisInterface >::type ephemerides
The ephemerides models managed by this EphemeridesManager.
JeodPointerVector< EphemerisItem >::type ephem_items
The heads of the ephemeris item lists.
JeodPointerVector< EphemerisRefFrame >::type integ_frames
List of reference frames that are not rotating with respect to the root node of the reference frame tree.
Protected Attributes inherited from jeod::RefFrameManager
RefFrame * root_node {}
The root node of the reference frame tree.
JeodPointerVector< RefFrame >::type ref_frames
List of reference frames.
Friends
class InputProcessor
void init_attrjeod__DynManager ()
Detailed Description
The DynManager class manages the dynamic elements of a simulation.
The primary functions of a DynManager are to:
Dynamically determine which ephemerides are needed in a simulation.
Initialize ephemeris models and keep them in sync with the rest of the simulation.
Initialize mass bodies and dynamic bodies independently of the order in which these bodies are declared in the S_define file.
Coordinate the computation of the cumulative forces and torques and gravitational effects on the dynamic bodies in a simulation.
Coordinate the integration of time and and of dynamic body states.
Apply asynchronous actions to bodies.
The DynManager can operate in one of three modes: empty space, single planet, and ephemeris mode. The DynManager inherits from EphemerisInterface so that when it operates in empty space or single-planet mode it can properly register itself as the owner of the reference frame tree root node.
Definition at line 113 of file dyn_manager.hh.
Constructor & Destructor Documentation
DynManager() [1/2]
jeod::DynManager::DynManager ()
DynManager default constructor.
Definition at line 65 of file dyn_manager.cc.
References JEOD_REGISTER_CLASS, and jeod::JeodIntegrationGroup::register_classes().
~DynManager()
jeod::DynManager::~DynManager () override
DynManager destructor.
Definition at line 84 of file dyn_manager.cc.
References default_integ_group, integ_constructor, integ_interface, JEOD_DELETE_OBJECT, and simple_ephemeris.
DynManager() [2/2]
jeod::DynManager::DynManager (const DynManager &) delete
Member Function Documentation
add_body_action()
void jeod::DynManager::add_body_action (BodyAction & body_action)
Add a body action to the list of such.
Parameters
[in,out] body_action Body action
Definition at line 168 of file dyn_manager.cc.
References body_actions, jeod::DynManagerMessages::duplicate_entry, jeod::MessageHandler::error(), jeod::BodyAction::initialize(), and initialized.
add_dyn_body()
void jeod::DynManager::add_dyn_body (DynBody & dyn_body) override virtual
Add a dynamic body to the dynamic body registry.
Parameters
dyn_body Dynamic body to be added to the registry.
Implements jeod::BaseDynManager.
Definition at line 95 of file dyn_bodies_primitives.cc.
References add_mass_body(), jeod::NamedItem::c_str(), jeod::DynManagerMessages::duplicate_entry, dyn_bodies, jeod::MessageHandler::error(), find_dyn_body(), find_mass_body(), jeod::NamedItem::get_name(), jeod::DynManagerMessages::invalid_name, is_dyn_body_registered(), jeod::DynBody::mass, jeod::DynBody::name, jeod::RefFrameManager::validate_name(), and jeod::MessageHandler::warn().
add_integ_group()
void jeod::DynManager::add_integ_group (DynamicsIntegrationGroup & integ_group) override virtual
Add an integration group to the integration group registry.
Parameters
integ_group Integration group to be added.
Implements jeod::BaseDynManager.
Definition at line 62 of file integ_group_primitives.cc.
References default_integ_group, jeod::DynManagerMessages::duplicate_entry, jeod::MessageHandler::error(), jeod::DynManagerMessages::inconsistent_setup, initialized, integ_groups, and is_integ_group_registered().
Referenced by jeod::JeodDynbodyIntegrationLoop::initialize_integ_loop(), and jeod::DynamicsIntegrationGroup::register_group().
add_mass_body() [1/2]
void jeod::DynManager::add_mass_body (MassBody & mass_body) override virtual
Add a mass body to the mass body registry.
Parameters
mass_body Mass body to be added to the registry.
Implements jeod::BaseDynManager.
Definition at line 89 of file mass_bodies_primitives.cc.
References jeod::NamedItem::c_str(), jeod::DynManagerMessages::duplicate_entry, jeod::MessageHandler::error(), find_mass_body(), jeod::NamedItem::get_name(), is_mass_body_registered(), mass_bodies, jeod::MassBody::name, and jeod::RefFrameManager::validate_name().
Referenced by add_dyn_body(), and add_mass_body().
add_mass_body() [2/2]
void jeod::DynManager::add_mass_body (MassBody * mass_body) override virtual
Add a mass body to the mass body registry.
Parameters
mass_body Mass body to be added to the registry.
Implements jeod::BaseDynManager.
Definition at line 128 of file mass_bodies_primitives.cc.
References add_mass_body(), jeod::MessageHandler::error(), and jeod::DynManagerMessages::null_pointer.
check_for_uninitialized_states()
void jeod::DynManager::check_for_uninitialized_states () protected
Ensure that all of the required states have been set.
Definition at line 337 of file initialize_dyn_bodies.cc.
References jeod::RefFrameItems::Att_Rate, jeod::NamedItem::c_str(), dyn_bodies, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::RefFrameItems::get(), jeod::DynBody::get_initialized_states(), jeod::DynManagerMessages::inconsistent_setup, jeod::RefFrameItems::is_empty(), jeod::DynBody::name, jeod::RefFrameItems::Pos_Vel, jeod::RefFrameItems::Pos_Vel_Att_Rate, jeod::RefFrameItems::remove(), jeod::DynBody::rotational_dynamics, jeod::RefFrameItems::set(), jeod::RefFrameItems::to_string(), and jeod::DynBody::translational_dynamics.
Referenced by initialize_dyn_bodies().
compute_derivatives()
void jeod::DynManager::compute_derivatives () inline
Collect forces and torques on each body and compute derivatives.
Definition at line 216 of file dyn_manager.hh.
References jeod::DynamicsIntegrationGroup::collect_derivatives(), and default_integ_group.
find_dyn_body()
DynBody * jeod::DynManager::find_dyn_body (const std::string & body_name) const override virtual
Find the dynamic body with the given name.
Parameters
body_name Dynamic body name
Returns
Pointer to found DynBody; NULL if not found.
Implements jeod::BaseDynManager.
Definition at line 55 of file dyn_bodies_primitives.cc.
References dyn_bodies, jeod::NamedItem::get_name(), jeod::DynBody::name, and jeod::RefFrameManager::validate_name().
Referenced by add_dyn_body(), and jeod::DynBodyInit::find_dyn_body().
find_mass_body()
MassBody * jeod::DynManager::find_mass_body (const std::string & body_name) const override virtual
Find the mass body with the given name.
Parameters
body_name Mass body name
Returns
Pointer to found MassBody; NULL if not found.
Implements jeod::BaseDynManager.
Definition at line 49 of file mass_bodies_primitives.cc.
References jeod::NamedItem::ends_with(), mass_bodies, jeod::MassBody::name, and jeod::RefFrameManager::validate_name().
Referenced by add_dyn_body(), and add_mass_body().
get_dyn_bodies()
std::vector<DynBody *> jeod::DynManager::get_dyn_bodies () const inline override virtual
Return a copy of the list of registered dynamic bodies.
Returns
Copy of dyn_bodies data member
Implements jeod::BaseDynManager.
Definition at line 178 of file dyn_manager.hh.
References dyn_bodies.
Referenced by jeod::JeodDynbodyIntegrationLoop::add_sim_object_bodies(), and jeod::JeodDynbodyIntegrationLoop::remove_sim_object_bodies().
gravitation()
void jeod::DynManager::gravitation ()
Compute gravitational acceleration on each root body.
Definition at line 119 of file gravitation.cc.
References default_integ_group, jeod::DynamicsIntegrationGroup::deriv_ephem_update, deriv_ephem_update, jeod::MessageHandler::error(), jeod::DynamicsIntegrationGroup::gravitation(), gravity_manager, gravity_off, jeod::DynManagerMessages::inconsistent_setup, and initialized.
initialize_dyn_bodies()
void jeod::DynManager::initialize_dyn_bodies ()
Initialize dynamic bodies.
Definition at line 55 of file initialize_dyn_bodies.cc.
References body_actions, check_for_uninitialized_states(), jeod::MassBody::compute_inverse_inertia, dyn_bodies, jeod::BodyAction::initialize(), jeod::DynBody::is_root_body(), jeod::DynBody::mass, perform_dyn_body_initializations(), perform_mass_attach_initializations(), perform_mass_body_initializations(), and jeod::MassBody::update_mass_properties().
Referenced by initialize_simulation().
initialize_dyn_body()
void jeod::DynManager::initialize_dyn_body (DynBody & body)
Initialize a specific dynamic body.
Assumptions and Limitations
The body in question is assumed to be an isolated body.
Parameters
[in,out] body Body to be initialized
Definition at line 99 of file initialize_dyn_bodies.cc.
References jeod::DynBody::mass, perform_dyn_body_initializations(), perform_mass_body_initializations(), and jeod::MassBody::update_mass_properties().
Referenced by jeod::PropagatedPlanet::ephem_update().
initialize_gravity_controls()
void jeod::DynManager::initialize_gravity_controls () override virtual
Initialize the gravity controls for each dynamic body.
Assumptions and Limitations
Not called in empty space mode.
Implements jeod::BaseDynManager.
Definition at line 49 of file gravitation.cc.
References dyn_bodies, jeod::MessageHandler::error(), gravity_manager, gravity_off, jeod::DynManagerMessages::inconsistent_setup, and jeod::DynBody::initialize_controls().
Referenced by initialize_simulation().
initialize_integ_groups()
void jeod::DynManager::initialize_integ_groups ()
Complete initialization of the initialization groups.
Definition at line 100 of file initialize_simulation.cc.
References default_integ_group, jeod::DynamicsIntegrationGroup::initialize_group(), and integ_groups.
Referenced by initialize_simulation().
initialize_model() [1/2]
void jeod::DynManager::initialize_model (DynManagerInit & init, TimeManager & time_mngr)
Begin initialization of the JEOD manager model.
Parameters
[in,out] init Initialization data
[in,out] time_mngr Time manager
Definition at line 61 of file initialize_model.cc.
References jeod::JeodSimulationInterface::create_integrator_interface().
initialize_model() [2/2]
void jeod::DynManager::initialize_model (JeodIntegratorInterface & integ_if, DynManagerInit & init, TimeManager & time_mngr)
Begin initialization of the JEOD manager model.
Parameters
[in,out] integ_if Integrator interface
[in,out] init Initialization data
[in,out] time_mngr Time manager
Class: (initialization)
Definition at line 78 of file initialize_model.cc.
References jeod::JeodIntegratorInterface::get_integrator(), initialize_model_internal(), integ_interface, and sim_integrator.
initialize_model_internal()
void jeod::DynManager::initialize_model_internal (DynManagerInit & init, TimeManager & time_mngr) protected virtual
Begin initialization of the JEOD manager model.
Assumptions and Limitations
The user-input item selection table must have at most one selection rule for a given name. This limitation is an enforced constraint.
Parameters
[in,out] init Initialization data
[in,out] time_mngr Time manager
Definition at line 95 of file initialize_model.cc.
References jeod::DynManagerInit::central_point_name, jeod::EphemeridesManager::clear_added_ephemerides(), jeod::DynamicsIntegrationGroup::create_group(), default_integ_group, jeod::EphemeridesManager::disable_add_ephemeris(), jeod::DynManagerInit::EphemerisMode_EmptySpace, jeod::DynManagerInit::EphemerisMode_Ephemerides, jeod::DynManagerInit::EphemerisMode_SinglePlanet, jeod::MessageHandler::fail(), jeod::TimeManager::get_jeod_integration_time(), jeod::DynManagerMessages::inconsistent_setup, jeod::SinglePointEphemeris::initialize_model(), jeod::DynManagerInit::integ_constructor, integ_constructor, jeod::DynManagerInit::integ_group_constructor, integ_groups, integ_interface, jeod::JeodIntegratorInterface::interpret_integration_type(), jeod::DynManagerMessages::invalid_name, JEOD_ALLOC_CLASS_OBJECT, jeod::DynManagerInit::jeod_integ_opt, jeod::DynManagerInit::mode, mode, jeod::SinglePointEphemeris::set_name(), jeod::DynManagerInit::sim_integ_opt, and simple_ephemeris.
Referenced by initialize_model().
initialize_simulation()
void jeod::DynManager::initialize_simulation ()
Complete initialization of the JEOD manager model.
Definition at line 46 of file initialize_simulation.cc.
References jeod::EphemeridesManager::activate_ephemerides(), jeod::RefFrameManager::check_ref_frame_ownership(), jeod::DynManagerInit::EphemerisMode_EmptySpace, gravity_manager, gravity_off, jeod::DynManagerMessages::inconsistent_setup, initialize_dyn_bodies(), jeod::EphemeridesManager::initialize_ephemerides(), initialize_gravity_controls(), initialize_integ_groups(), jeod::GravityManager::initialize_state(), initialized, mode, jeod::EphemeridesManager::update_ephemerides(), and jeod::MessageHandler::warn().
integrate()
int jeod::DynManager::integrate (double to_sim_time, TimeManager &) inline
Propagate all vehicles and propagate time.
Parameters
to_sim_time Simulation time seconds of end of integration interval.
Returns
zero if complete, non-zero if incomplete.
Definition at line 240 of file dyn_manager.hh.
References default_integ_group.
is_dyn_body_registered()
bool jeod::DynManager::is_dyn_body_registered (const DynBody * dyn_body) const override virtual
Determine if the specified body has been registered with the DynManager.
Parameters
dyn_body Dynamic body to be found.
Returns
True if body has been registered, false otherwise.
Implements jeod::BaseDynManager.
Definition at line 86 of file dyn_bodies_primitives.cc.
References dyn_bodies.
Referenced by add_dyn_body(), and jeod::DynBodyInit::initialize().
is_initialized()
bool jeod::DynManager::is_initialized () inline
Determine if the manager has been initialized.
Returns
Initialization status
Definition at line 131 of file dyn_manager.hh.
References initialized.
Referenced by jeod::JeodDynbodyIntegrationLoop::add_sim_object(), and jeod::JeodDynbodyIntegrationLoop::remove_sim_object().
is_integ_group_registered()
bool jeod::DynManager::is_integ_group_registered (const DynamicsIntegrationGroup * integ_group) const override virtual
Determine if the specified group has been registered with the DynManager.
Parameters
integ_group Integration group to be found.
Returns
True if integ_group has been registered, false otherwise.
Implements jeod::BaseDynManager.
Definition at line 53 of file integ_group_primitives.cc.
References integ_groups.
Referenced by add_integ_group(), and jeod::DynamicsIntegrationGroup::register_group().
is_mass_body_registered()
bool jeod::DynManager::is_mass_body_registered (const MassBody * mass_body) const override virtual
Determine if the specified body has been registered with the DynManager.
Parameters
mass_body Mass body to be found.
Returns
True if body has been registered, false otherwise.
Implements jeod::BaseDynManager.
Definition at line 80 of file mass_bodies_primitives.cc.
References mass_bodies.
Referenced by add_mass_body().
name()
const std::string jeod::DynManager::name () const
Return identifier.
Returns
Name
Definition at line 108 of file dyn_manager.cc.
operator=()
DynManager& jeod::DynManager::operator= (const DynManager &) delete
perform_actions()
void jeod::DynManager::perform_actions ()
Perform dynamic body actions that are ready to be applied.
Definition at line 41 of file perform_actions.cc.
References jeod::BodyAction::apply(), body_actions, and jeod::BodyAction::is_ready().
perform_dyn_body_initializations()
void jeod::DynManager::perform_dyn_body_initializations (DynBody * body = nullptr) protected
Initialize dynamic bodies.
Parameters
[in,out] body Body to be initialized
Definition at line 220 of file initialize_dyn_bodies.cc.
References jeod::BodyAction::apply(), body_actions, jeod::MessageHandler::error(), jeod::DynManagerMessages::inconsistent_setup, jeod::BodyAction::is_ready(), jeod::BodyAction::is_same_subject_body(), jeod::DynBody::mass, jeod::EphemeridesManager::regenerate_ref_frame_tree, jeod::DynBodyInit::report_failure(), and jeod::EphemeridesManager::update_ephemerides().
Referenced by initialize_dyn_bodies(), and initialize_dyn_body().
perform_mass_attach_initializations()
void jeod::DynManager::perform_mass_attach_initializations () protected
Initialize all queued body actions that derive from MassBodyAttach and apply those that are immediately ready to be applied.
Definition at line 171 of file initialize_dyn_bodies.cc.
References jeod::BodyAction::apply(), body_actions, jeod::BodyAction::initialize(), and jeod::BodyAction::is_ready().
Referenced by initialize_dyn_bodies().
perform_mass_body_initializations()
void jeod::DynManager::perform_mass_body_initializations (MassBody * body = nullptr) protected
Initialize all queued body actions that derive from MassBodyInit and apply those that are immediately ready to be applied.
Parameters
[in,out] body Body to be initialized
Definition at line 116 of file initialize_dyn_bodies.cc.
References jeod::BodyAction::apply(), body_actions, jeod::BodyAction::initialize(), jeod::BodyAction::is_ready(), and jeod::BodyAction::is_same_subject_body().
Referenced by initialize_dyn_bodies(), and initialize_dyn_body().
remove_body_action()
void jeod::DynManager::remove_body_action (const std::string & action_name_in)
Remove a body action to the list of such.
Parameters
[in] action_name_in Name of the action to remove
Definition at line 205 of file dyn_manager.cc.
References jeod::BodyAction::action_name, body_actions, and jeod::BodyAction::shutdown().
reset_gravity_controls()
void jeod::DynManager::reset_gravity_controls () override virtual
Reset the gravity controls for each dynamic body.
Assumptions and Limitations
Not called in empty space mode.
Implements jeod::BaseDynManager.
Definition at line 82 of file gravitation.cc.
References dyn_bodies, jeod::MessageHandler::error(), gravity_manager, gravity_off, jeod::DynManagerMessages::inconsistent_setup, and jeod::DynBody::reset_controls().
reset_integrators() [1/2]
void jeod::DynManager::reset_integrators () override virtual
Force all integrators to reset themselves.
Implements jeod::BaseDynManager.
Definition at line 227 of file dyn_manager.cc.
References default_integ_group, and integ_groups.
reset_integrators() [2/2]
void jeod::DynManager::reset_integrators (DynamicsIntegrationGroup & integ_group) inline override virtual
Instruct specific integrator to reset itself.
Parameters
integ_group Integration group to be reset.
Implements jeod::BaseDynManager.
Definition at line 230 of file dyn_manager.hh.
set_gravity_manager()
void jeod::DynManager::set_gravity_manager (GravityManager & gravity) override virtual
Set the Gravity Manager to the specified reference.
Parameters
[in] gravity Gravity Manager
Implements jeod::BaseDynManager.
Definition at line 125 of file dyn_manager.cc.
References jeod::MessageHandler::error(), gravity_manager, gravity_off, jeod::DynManagerMessages::inconsistent_setup, initialized, and jeod::DynManagerMessages::singleton_error.
shutdown()
void jeod::DynManager::shutdown ()
Shutdown the manager.
Empty for now.
Definition at line 116 of file dyn_manager.cc.
timestamp()
double jeod::DynManager::timestamp () const override virtual
Return last update time.
Returns
Name
Implements jeod::BaseDynManager.
Definition at line 99 of file dyn_manager.cc.
References jeod::EphemeridesManager::update_time.
update_integration_group()
void jeod::DynManager::update_integration_group (JeodIntegrationGroup & group) override virtual
Add DynBody objects to the default integration group.
Parameters
[in,out] group Group to be updated
Implements jeod::JeodIntegrationGroupOwner.
Definition at line 126 of file initialize_simulation.cc.
References jeod::DynamicsIntegrationGroup::add_dyn_body(), default_integ_group, dyn_bodies, jeod::MessageHandler::fail(), and jeod::DynManagerMessages::inconsistent_setup.
Friends And Related Function Documentation
init_attrjeod__DynManager
void init_attrjeod__DynManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 117 of file dyn_manager.hh.
Field Documentation
body_actions
std::list<BodyAction *> jeod::DynManager::body_actions protected
List of body initializers.
Definition at line 340 of file dyn_manager.hh.
Referenced by add_body_action(), initialize_dyn_bodies(), perform_actions(), perform_dyn_body_initializations(), perform_mass_attach_initializations(), perform_mass_body_initializations(), and remove_body_action().
default_integ_group
DynamicsIntegrationGroup* jeod::DynManager::default_integ_group {} protected
The integration group used for simple monolithic simulations.
trick_units(–)
Definition at line 315 of file dyn_manager.hh.
Referenced by add_integ_group(), compute_derivatives(), gravitation(), initialize_integ_groups(), initialize_model_internal(), integrate(), reset_integrators(), update_integration_group(), and ~DynManager().
deriv_ephem_update
bool jeod::DynManager::deriv_ephem_update {}
Update ephemerides at the derivative rate?
trick_units(–)
Definition at line 259 of file dyn_manager.hh.
Referenced by gravitation().
dyn_bodies
std::vector<DynBody *> jeod::DynManager::dyn_bodies protected
List of vehicle models.
Definition at line 330 of file dyn_manager.hh.
Referenced by add_dyn_body(), check_for_uninitialized_states(), find_dyn_body(), get_dyn_bodies(), initialize_dyn_bodies(), initialize_gravity_controls(), is_dyn_body_registered(), reset_gravity_controls(), and update_integration_group().
gravity_manager
GravityManager* jeod::DynManager::gravity_manager {} protected
The model that encapsulates all of the gravity models.
trick_units(–)
Definition at line 300 of file dyn_manager.hh.
Referenced by gravitation(), initialize_gravity_controls(), initialize_simulation(), reset_gravity_controls(), and set_gravity_manager().
gravity_off
bool jeod::DynManager::gravity_off {}
This flag exists primarily to support unit tests.
Typical simulations should not set this flag. The intent is to support simulations that use planetary ephemerides but neither need nor have a gravity model.trick_units(–)
Definition at line 266 of file dyn_manager.hh.
Referenced by gravitation(), initialize_gravity_controls(), initialize_simulation(), reset_gravity_controls(), and set_gravity_manager().
initialized
bool jeod::DynManager::initialized {} protected
Have all initializations been performed?
trick_units(–)
Definition at line 295 of file dyn_manager.hh.
Referenced by add_body_action(), add_integ_group(), gravitation(), initialize_simulation(), is_initialized(), and set_gravity_manager().
integ_constructor
er7_utils::IntegratorConstructor* jeod::DynManager::integ_constructor {} protected
Integrator generator.
trick_units(–)
Definition at line 305 of file dyn_manager.hh.
Referenced by initialize_model_internal(), and ~DynManager().
integ_groups
std::vector<DynamicsIntegrationGroup *> jeod::DynManager::integ_groups protected
List of integration groups.
Definition at line 335 of file dyn_manager.hh.
Referenced by add_integ_group(), initialize_integ_groups(), initialize_model_internal(), is_integ_group_registered(), and reset_integrators().
integ_interface
JeodIntegratorInterface* jeod::DynManager::integ_interface {} protected
Interface with the simulation integration structure.
trick_units(–)
Definition at line 310 of file dyn_manager.hh.
Referenced by initialize_model(), initialize_model_internal(), and ~DynManager().
mass_bodies
std::vector<MassBody *> jeod::DynManager::mass_bodies protected
List of vehicle models.
Definition at line 325 of file dyn_manager.hh.
Referenced by add_mass_body(), find_mass_body(), and is_mass_body_registered().
mode
DynManagerInit::EphemerisMode jeod::DynManager::mode {DynManagerInit::EphemerisMode_Ephemerides}
The ephemeris mode in which the dynamics manager operates.
trick_units(–)
Definition at line 271 of file dyn_manager.hh.
Referenced by initialize_model_internal(), and initialize_simulation().
sim_integrator
Trick::Integrator* jeod::DynManager::sim_integrator {}
Pointer to the integration object used by the simulation engine itself.
trick_units(–)
Definition at line 276 of file dyn_manager.hh.
Referenced by initialize_model().
simple_ephemeris
SinglePointEphemeris* jeod::DynManager::simple_ephemeris {} protected
Simple ephemeris for use in empty space and single planet modes.
trick_units(–)
Definition at line 320 of file dyn_manager.hh.
Referenced by initialize_model_internal(), and ~DynManager().
The documentation for this class was generated from the following files:
dyn_manager.hh
dyn_bodies_primitives.cc
dyn_manager.cc
gravitation.cc
initialize_dyn_bodies.cc
initialize_model.cc
initialize_simulation.cc
integ_group_primitives.cc
mass_bodies_primitives.cc
perform_actions.cc