JEOD: jeod::BaseRefFrameManager Class Reference
jeod::BaseRefFrameManager Class Reference abstract
The RefFrameManager class manages the reference frames in a simulation.
#include <base_ref_frame_manager.hh>
Public Member Functions
virtual ~BaseRefFrameManager ()
Destructor.
virtual void add_ref_frame (RefFrame &ref_frame)=0
Add a reference frame to the list of such.
virtual void remove_ref_frame (RefFrame &ref_frame)=0
Remove a reference frame from the list of such.
virtual RefFrame * find_ref_frame (const char *name) const =0
Find a reference frame.
virtual RefFrame * find_ref_frame (const char *prefix, const char *suffix) const =0
Find a reference frame.
virtual void check_ref_frame_ownership () const =0
Check whether each reference frame has an owner.
virtual void reset_tree_root_node ()=0
Reset the root node in anticipation of rebuilding the entire tree.
virtual void add_frame_to_tree (RefFrame &ref_frame, RefFrame *parent)=0
Add a reference frame to the reference frame tree.
virtual void subscribe_to_frame (const char *frame_name)=0
Add a subscription to a reference frame.
virtual void subscribe_to_frame (RefFrame &frame)=0
Add a subscription to a reference frame.
virtual void unsubscribe_to_frame (const char *frame_name)=0
Remove a subscription from a reference frame.
virtual void unsubscribe_to_frame (RefFrame &frame)=0
Remove a subscription from a reference frame.
virtual bool frame_is_subscribed (const char *frame_name)=0
Check whether a reference frame has subscriptions.
virtual bool frame_is_subscribed (RefFrame &frame)=0
Check whether a reference frame has subscriptions.
Friends
class InputProcessor
void init_attrjeod__BaseRefFrameManager ()
Detailed Description
The RefFrameManager class manages the reference frames in a simulation.
This class defines the external interfaces to that class.
Definition at line 80 of file base_ref_frame_manager.hh.
Constructor & Destructor Documentation
~BaseRefFrameManager()
virtual jeod::BaseRefFrameManager::~BaseRefFrameManager () inline virtual
Destructor.
Definition at line 93 of file base_ref_frame_manager.hh.
Member Function Documentation
add_frame_to_tree()
virtual void jeod::BaseRefFrameManager::add_frame_to_tree (RefFrame & ref_frame, RefFrame * parent) pure virtual
Add a reference frame to the reference frame tree.
Parameters
ref_frame Frame to be added.
parent Parent of the frame.
Implemented in jeod::RefFrameManager.
add_ref_frame()
virtual void jeod::BaseRefFrameManager::add_ref_frame (RefFrame & ref_frame) pure virtual
Add a reference frame to the list of such.
Parameters
ref_frame Frame to be added.
Implemented in jeod::EphemeridesManager, and jeod::RefFrameManager.
Referenced by jeod::DynBody::add_mass_body_frames(), jeod::DynBody::add_mass_point(), jeod::DynBody::initialize_model(), and jeod::BasePlanet::register_planet().
check_ref_frame_ownership()
virtual void jeod::BaseRefFrameManager::check_ref_frame_ownership () const pure virtual
Check whether each reference frame has an owner.
Implemented in jeod::RefFrameManager.
find_ref_frame() [1/2]
virtual RefFrame* jeod::BaseRefFrameManager::find_ref_frame (const char * name) const pure virtual
Find a reference frame.
Parameters
name Frame to be found.
Returns
Found reference frame.
Implemented in jeod::RefFrameManager.
Referenced by jeod::DynBody::attach_to_frame(), and jeod::DynBody::find_body_frame().
find_ref_frame() [2/2]
virtual RefFrame* jeod::BaseRefFrameManager::find_ref_frame (const char * prefix, const char * suffix) const pure virtual
Find a reference frame.
Parameters
prefix Prefix of frame to be found.
suffix Suffix of frame to be found.
Returns
Found reference frame.
Implemented in jeod::RefFrameManager.
frame_is_subscribed() [1/2]
virtual bool jeod::BaseRefFrameManager::frame_is_subscribed (const char * frame_name) pure virtual
Check whether a reference frame has subscriptions.
Parameters
frame_name Frame to be checked.
Returns
True if frame has subscriptions, false otherwise.
Implemented in jeod::RefFrameManager.
frame_is_subscribed() [2/2]
virtual bool jeod::BaseRefFrameManager::frame_is_subscribed (RefFrame & frame) pure virtual
Check whether a reference frame has subscriptions.
Parameters
frame Frame to be checked.
Returns
True if frame has subscriptions, false otherwise.
Implemented in jeod::RefFrameManager.
remove_ref_frame()
virtual void jeod::BaseRefFrameManager::remove_ref_frame (RefFrame & ref_frame) pure virtual
Remove a reference frame from the list of such.
Parameters
ref_frame Frame to be removed.
Implemented in jeod::RefFrameManager.
Referenced by jeod::DynBody::detach_mass_body_frames(), and jeod::DynBody::~DynBody().
reset_tree_root_node()
virtual void jeod::BaseRefFrameManager::reset_tree_root_node () pure virtual
Reset the root node in anticipation of rebuilding the entire tree.
Implemented in jeod::RefFrameManager.
subscribe_to_frame() [1/2]
virtual void jeod::BaseRefFrameManager::subscribe_to_frame (const char * frame_name) pure virtual
Add a subscription to a reference frame.
Parameters
frame_name Frame to which subscription is to be issued.
Implemented in jeod::RefFrameManager.
Referenced by jeod::SphericalHarmonicsTidalEffects::initialize(), jeod::GravityControls::reset_control(), and jeod::DynBody::set_integ_frame().
subscribe_to_frame() [2/2]
virtual void jeod::BaseRefFrameManager::subscribe_to_frame (RefFrame & frame) pure virtual
Add a subscription to a reference frame.
Parameters
frame Frame to which subscription is to be issued.
Implemented in jeod::RefFrameManager.
unsubscribe_to_frame() [1/2]
virtual void jeod::BaseRefFrameManager::unsubscribe_to_frame (const char * frame_name) pure virtual
Remove a subscription from a reference frame.
Parameters
frame_name Frame from which subscription is to be removed.
Implemented in jeod::RefFrameManager.
Referenced by jeod::GravityControls::reset_control(), and jeod::DynBody::set_integ_frame().
unsubscribe_to_frame() [2/2]
virtual void jeod::BaseRefFrameManager::unsubscribe_to_frame (RefFrame & frame) pure virtual
Remove a subscription from a reference frame.
Parameters
frame Frame from which subscription is to be removed.
Implemented in jeod::RefFrameManager.
Friends And Related Function Documentation
init_attrjeod__BaseRefFrameManager
void init_attrjeod__BaseRefFrameManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 82 of file base_ref_frame_manager.hh.
The documentation for this class was generated from the following file:
base_ref_frame_manager.hh