JEOD: jeod::StructureIntegratedDynBody Class Reference
jeod::StructureIntegratedDynBody Class Reference
Extends DynBody to integrate an object's structural reference frame as opposed to its center of mass.
#include <structure_integrated_dyn_body.hh>
Public Member Functions
StructureIntegratedDynBody ()
Constructor.
~StructureIntegratedDynBody () override
Destructor.
void collect_forces_and_torques () override
Compute the rotational and translational accelerations that result from the collected forces and torques acting on the vehicle.
void set_solver (DynBodyConstraintsSolver &solver_in)
Set the solver to be used to solve contraints.
void add_constraint (DynBodyConstraint *constraint)
Add a constraint to the constraints solver.
virtual void solve_constraints ()
Solve for constraint forces and torques acting on the vehicle and apply them to the vehicle.
void compute_vehicle_point_derivatives (const BodyRefFrame &frame, FrameDerivs &derivs) override
Compute the state derivatives at a vehicle point.
bool detach (DynBody &other_body) override
Break the logical connectivity between parent and child.
Public Member Functions inherited from jeod::DynBody
DynBody ()
DynBody default constructor.
~DynBody () override
DynBody destructor.
virtual void initialize_model (BaseDynManager &dyn_manager_in)
Initialize internal and external interrelations, including registration / with the dynamics manager.
void activate ()
Activate a DynBody object.
void deactivate ()
Deactivate a DynBody object.
void set_name (const std::string &name_in)
Set the name of the vehicle.
virtual void add_control (GravityControls *control)
Add a new GravityControls to the list in grav_interaction.
virtual void initialize_controls (GravityManager &grav_manager)
Initialize the gravity controls of this DynBody.
virtual void reset_controls ()
Make the frame subscriptions for each control consistent with the requirements for that control.
virtual void sort_controls ()
Sort the gravity controls in ascending acceleration magnitude order.
virtual void create_body_integrators (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls, const JeodIntegrationTime &time_mngr)
Create the integrator (integrators) needed to propagate the translational and rotational state of a DynBody.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage) override
Integrate state by the specified dynamic time interval.
virtual void switch_integration_frames (EphemerisRefFrame &new_integ_frame)
Switch the integration frame for this body and all its child bodies to the indicated frame.
virtual void switch_integration_frames (const char *new_integ_frame_name)
Switch the integration frame for this body and all its child bodies to the frame indicated by the provided name.
void create_integrators (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls, const er7_utils::TimeInterface &time_if) override
This interface is required by er7_utils::IntegrableObject.
void destroy_integrators (void) override
Destroy the integrators.
void reset_integrators (void) override
Reset the translational and rotational integrators.
virtual BodyRefFrame * find_body_frame (const char *frame_id) const
Find the BodyRefFrame named by the provided identifier.
DynamicsIntegrationGroup * get_dynamics_integration_group ()
Get the DynamicsIntegrationGroup that integrates this DynBody object.
JeodPointerVector< er7_utils::IntegrableObject >::type get_integrable_objects ()
Get the IntegrableObjects associated with this DynBody.
void clear_integrable_objects ()
Remove all IntegrableObjects associated with this DynBody.
void migrate_integrable_objects ()
Call this method before switching this dyn body to a new group if you want the associated integrable objects to follow.
void add_integrable_object (er7_utils::IntegrableObject &associated_integrable_object)
Add an IntegrableObject to be integrated with this DynBody.
void remove_integrable_object (er7_utils::IntegrableObject &associated_integrable_object)
Remove an IntegrableObject from association with this DynBody.
void set_position (const double position[3], BodyRefFrame &subject_frame)
Set the position of the vehicle.
void set_velocity (const double velocity[3], BodyRefFrame &subject_frame)
Set the velocity of the vehicle.
void set_attitude_left_quaternion (const Quaternion &left_quat, BodyRefFrame &subject_frame)
Set the attitude of the vehicle.
void set_attitude_right_quaternion (const Quaternion &right_quat, BodyRefFrame &subject_frame)
Set the attitude of the vehicle.
void set_attitude_matrix (const double matrix[3][3], BodyRefFrame &subject_frame)
Set the attitude of the vehicle.
void set_attitude_rate (const double attitude_rate[3], BodyRefFrame &subject_frame)
Set the attitude rate of the vehicle.
void set_state (RefFrameItems::Items set_items, const RefFrameState &state, BodyRefFrame &subject_frame)
Set the parts of the specified reference frame as indicated by the set_items parameter from the supplied state and propagate these items to all dynamic bodies attached to this body.
void set_state_source (RefFrameItems::Items items, BodyRefFrame &frame)
Set the source of aspects of the state.
virtual void propagate_state ()
Propagate state from the integrated state to attached bodies.
virtual void update_integrated_state ()
Propagate state from state owners to the integrated state.
virtual void compute_vehicle_point_states (RefFrameItems::Items set_items)
Propagate structure frame state to vehicle points.
bool is_root_body ()
Indicates whether this DynBody object is a root body.
virtual const DynBody * get_parent_body () const
Returns this DynBody object's parent body.
virtual const DynBody * get_root_body () const
Finds this DynBody object's root body.
virtual void add_mass_point (const MassPointInit &mass_point_init)
Add a mass point to the dyn body's list of such and make a vehicle point that corresponds to the added mass point.
const BodyRefFrame * find_vehicle_point (const char *pt_name) const
Find the vehicle point with the given name.
const RefFrameItems & get_initialized_states () const
Indicate which state elements have been initialized.
bool initialized_states_contains (RefFrameItems::Items test_items) const
Indicate whether the specified state elements have been initialized.
virtual bool add_mass_body (const char *this_point_name, const char *child_point_name, MassBody &child)
virtual bool add_mass_body (const double offset[3], const double T_pstr_cstr[3][3], MassBody &child)
virtual bool attach_to (const char *this_point_name, const char *parent_point_name, DynBody &parent)
Attach this dyn body's root body as a child of the specified dyn body such that the specified mass points on the two bodies are coincident and the frames associated with those mass points are related by a 180 degree yaw.
virtual bool attach_to (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &parent)
Attach this dyn body's root body as a child of the specified dyn body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with respect to the parent body's structural axes as specified.
virtual bool attach_child (const char *this_point_name, const char *child_point_name, DynBody &child)
Attach a child DynBody by point specification.
virtual bool attach_child (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &child)
Attach a child DynBody by location specification.
virtual bool attach_to_frame (const char *parent_ref_frame_name)
virtual bool attach_to_frame (RefFrame &parent)
virtual bool attach_to_frame (const char *this_point_name, const char *parent_ref_frame_name, const double offset_pframe_cpt_pframe[3], const double T_pframe_cpt[3][3])
virtual bool attach_to_frame (const double offset_pframe_cstr_pframe[3], const double T_pframe_cstr[3][3], RefFrame &parent)
virtual bool detach (void)
Detach this DynBody from its parent RefFrame or DynBody parent.
virtual bool remove_mass_body (MassBody &child)
Remove connectivity between this (parent) DynBody and the argument (child) MassBody mass subbody.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Data Fields
BodyWrenchCollect effector_wrench_collection
Collection of effector wrenches.
Data Fields inherited from jeod::DynBody
MassBody mass
Mass properties of the vehicle, defined about the structure reference frame.
NamedItem & name
Body name, reference linked to mass.name.
char * integ_frame_name
The name of the reference frame with respect to which the body's reference frames (core, composite, structure, plus vehicle point frames) are to be represented and propagated.
EphemerisRefFrame * integ_frame
The current integration frame.
BodyRefFrame core_body
Vehicle core body reference frame.
BodyRefFrame composite_body
Vehicle composite body reference frame.
BodyRefFrame structure
Vehicle structural reference frame.
bool translational_dynamics
Is translational dynamics enabled? The body's translational state is integrated only if this member is true.
bool rotational_dynamics
Is rotational dynamics enabled? The body's rotational state is integrated only if this member is true.
bool compute_point_derivative
Should the point derivatives for the body be computed? A child body's translational and rotational derivatives are only computed if this is true.
bool three_dof
Is this a three degrees of freedom (translation only) body? This data member has effect only when set prior to the creation of the body's integrators.
GeneralizedSecondOrderODETechnique::TechniqueType rotation_integration
Specifies the preferred mechanism for integrating rotational state.
bool autoupdate_vehicle_points
Are vehicle points automatically updated? The vehicle points are automatically calculated at initialization time but are only automatically updated at runtime if this member is true.
GravityInteraction grav_interaction
Gravitational interactions.
FrameDerivs derivs
Translational/rotational accelerations.
BodyForceCollect collect
Force/Torque collection mechanism.
Protected Member Functions
void attach_update_properties (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &child) override
Set the relation between parent and child and update the mass properties.
const VehicleProperties & get_vehicle_properties () const
Get the vehicle properties as a const reference.
er7_utils::IntegratorResult trans_integ (double dyn_dt, unsigned int target_stage) override
Integrate the translational state of a StructureIntegratedDynBody.
er7_utils::IntegratorResult rot_integ (double dyn_dt, unsigned int target_stage) override
Integrate the rotational state of a StructureIntegratedDynBody.
void collect_local_forces_and_torques ()
Collect the local forces and torques that directly act on the vehicle.
void PropagateForcesAndTorques ()
Propagate forces and torques up the kinematic chain.
void compute_inertial_torque ()
Compute the inertial torque.
void compute_rotational_acceleration ()
Compute the body- and structure-referenced rotational acceleration.
void compute_translational_acceleration ()
Compute the inertial-referenced translational acceleration vector.
void complete_translational_acceleration ()
Finalize computation of the inertial-referenced translational acceleration vector.
Protected Member Functions inherited from jeod::DynBody
virtual void set_integ_frame (EphemerisRefFrame &new_integ_frame)
Set the integration frame for this body and all its child bodies to the provided frame.
virtual void set_integ_frame (const char *new_integ_frame_name)
Set the integration frame for this body and all its child bodies to the frame indicated by the provided name.
void set_state_source_internal (RefFrameItems::Items items, BodyRefFrame &frame)
Set the source of aspects of the state.
virtual DynBody * get_parent_body_internal ()
Returns this DynBody object's parent body.
virtual DynBody * get_root_body_internal ()
Finds this DynBody object's root body.
virtual bool attach_validate_parent (const DynBody &parent, bool generate_message) const
Validate whether the pending attachment is legal from a connectivity point of view.
virtual bool attach_validate_child (const DynBody &child, bool generate_message) const
Validate whether the pending attachment is legal from a physical point of view.
virtual bool add_mass_body_validate (const MassBody &child, bool generate_message) const
Validate whether the pending sub body is legal from a mass tree point of view.
virtual void add_mass_body_frames (MassBody &subbody)
For a newly attached mass sub-body, create body frames for the root sub-body and all child sub-bodies via recursion.
virtual void detach_mass_body_frames (MassBody &subbody)
For a newly detached mass sub-body, remove body frames for the root sub-body and all child sub-bodies via recursion.
virtual void attach_establish_links (DynBody &parent)
Establish the logical connectivity between parent and child.
virtual void process_dynamic_attachment (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &root_body, DynBody &child_body)
Process the attachment event of one body from another.
virtual void detach_mass_internal (MassBody &child)
Update parent and child properties to reflect that they are detached.
virtual void propagate_state_from_structure ()
Propagate state to attached bodies starting from this body's structural frame.
virtual void propagate_state_from_composite ()
Propagate state to attached bodies starting from this body's composite frame.
void compute_ref_point_transform (const BodyRefFrame &source_frame, const MassPoint **const ref_point, MassPointState &rel_state)
Compute the relative state between the integrated frame's mass point and the source frame's mass point.
void compute_derived_state_forward (const BodyRefFrame &source_frame, const MassPoint &rel_state, BodyRefFrame &derived_frame) const
Compute a derived state given the source state and the position/ attitude transformation from the source to the derived state.
void compute_state_elements_forward (const BodyRefFrame &source_frame, const MassPoint &rel_state, const RefFrameItems &state_items, BodyRefFrame &derived_frame) const
Compute selected aspects of the derived state given the source state and the position/ attitude transformation from the source to the derived state.
void compute_derived_state_reverse (const BodyRefFrame &source_frame, const MassPoint &rel_state, BodyRefFrame &derived_frame) const
Compute a derived state given the source state and the position/ attitude transformation from the derived to the source state.
void compute_state_elements_reverse (const BodyRefFrame &source_frame, const MassPoint &rel_state, const RefFrameItems &state_items, BodyRefFrame &derived_frame) const
Compute selected aspects of the derived state given the source state and the position/ attitude transformation from the derived to the source state.
Protected Attributes
DynBodyConstraintsSolver * constraints_solver
The solver for constraint forces and torques, if there are any.
Wrench effector_wrench
Wrench into which the effector wrenches are accumulated.
FrameDerivs struct_derivs
Translational/rotational accelerations of the structural frame.
VehicleProperties vehicle_properties
Various properties of the vehicle, for the constraints solver.
VehicleNonGravState non_grav_state
Rotational and translational behaviors, for the constraints solver.
double inertial_accel_struct_omega [3]
Structure-referenced inertial acceleration at the structure frame origin due to vehicle angular velocity.
double inertial_accel_struct_omega_dot [3]
Structure-referenced inertial acceleration at the structure frame origin due to vehicle angular acceleration.
double inertial_accel_struct [3]
Structure-referenced inertial acceleration at the structure frame origin.
double inertial_accel_inrtl [3]
Inertial-referenced inertial acceleration at the structure frame origin.
Protected Attributes inherited from jeod::DynBody
BaseDynManager *& dyn_manager
The dynamics manager for the simulation.
const JeodIntegrationTime * time_manager
The time manager to be used to obtain timestamp information.
DynBody * dyn_parent
The DynBody to which this body is attached.
DynBodyGenericFrameAttachment frame_attach
The RefFrame this body is attached to.
std::list< DynBody * > dyn_children
The subset of the dynamic bodies attached to this dynamic body.
std::list< MassBody * > mass_children
The subset of the mass bodies attached to this dynamic body that are themselves not dynamic bodies.
std::list< BodyRefFrame * > vehicle_points
An array of vehicle points associated with this dynamic body.
RefFrameItems initialized_states
Enum value indicating which of position, velocity, attitude, and rate have been initialized.
BodyRefFrame * position_source
The reference frame that contains the user-set position.
BodyRefFrame * velocity_source
The reference frame that contains the user-set velocity.
BodyRefFrame * attitude_source
The reference frame that contains the user-set attitude.
BodyRefFrame * rate_source
The reference frame that contains the user-set attitude rate.
BodyRefFrame * integrated_frame
The reference frame whose state is updated via the state integrator.
std::vector< er7_utils::IntegrableObject * > associated_integrable_objects
List of integrable objects to be integrated with this DynBody.
er7_utils::IntegratorResultMergerContainer integ_results_merger
The object that merges integration results.
RestartableT3SecondOrderODEIntegrator trans_integrator
Translational state checkpointable/restartable integrator generator.
RestartableSO3SecondOrderODEIntegrator rot_integrator
Rotational state checkpointable/restartable integrator generator.
Private Member Functions
StructureIntegratedDynBody (const StructureIntegratedDynBody &)
Not implemented.
StructureIntegratedDynBody & operator= (const StructureIntegratedDynBody &)
Not implemented.
Friends
class InputProcessor
class DynBodyConstraintsSolver
void init_attrjeod__StructureIntegratedDynBody ()
Detailed Description
Extends DynBody to integrate an object's structural reference frame as opposed to its center of mass.
In addition to structure integration, this class introduces two new concepts, wrenches and constrained objects. A wrench encapsulates a force applied at a point and a torque, with the torque induced by the force due to an off-centerline force direction automatically calculated by JEOD. A constrained object is an object that lies outside the DynBody system boundary that exchanges translational and/or rotational momentum with the DynBody and that is somehow constrained by the translation and/or rotational behavior of the DynBody.
These new concepts might be migrated up the DynBody inheritance chain in subsequent releases of JEOD.
Definition at line 91 of file structure_integrated_dyn_body.hh.
Constructor & Destructor Documentation
StructureIntegratedDynBody() [1/2]
jeod::StructureIntegratedDynBody::StructureIntegratedDynBody ()
Constructor.
Definition at line 36 of file structure_integrated_dyn_body.cc.
References jeod::DynBody::integrated_frame, JEOD_REGISTER_CLASS, and jeod::DynBody::structure.
~StructureIntegratedDynBody()
jeod::StructureIntegratedDynBody::~StructureIntegratedDynBody () override
Destructor.
Definition at line 59 of file structure_integrated_dyn_body.cc.
StructureIntegratedDynBody() [2/2]
jeod::StructureIntegratedDynBody::StructureIntegratedDynBody (const StructureIntegratedDynBody &) private
Not implemented.
Member Function Documentation
add_constraint()
void jeod::StructureIntegratedDynBody::add_constraint (DynBodyConstraint * constraint)
Add a constraint to the constraints solver.
Note
Both the constraint and the solver must be non-null.
Parameters
constraint The constraint to be added to the solver.
Definition at line 125 of file structure_integrated_dyn_body_solve.cc.
References jeod::DynBodyConstraintsSolver::add_constraint(), constraints_solver, jeod::MessageHandler::fail(), and jeod::DynBodyMessages::invalid_body.
attach_update_properties()
void jeod::StructureIntegratedDynBody::attach_update_properties (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody & child) override protected virtual
Set the relation between parent and child and update the mass properties.
Parameters
[in] offset_pstr_cstr_pstr Location of the child body's structural origin with respect to the parent body's structural origin, specified in structural coordinates of the parent body.
[in] T_pstr_cstr Transformation matrix from the parent body's structural frame to the child body's structural frame.
[in,out] child The child body being attached to this body.
Reimplemented from jeod::DynBody.
Definition at line 37 of file structure_integrated_dyn_body_solve.cc.
References jeod::DynBodyConstraintsSolver::attach(), jeod::DynBody::attach_update_properties(), jeod::NamedItem::c_str(), constraints_solver, jeod::MessageHandler::fail(), jeod::DynBodyMessages::invalid_attachment, jeod::DynBody::name, and vehicle_properties.
collect_forces_and_torques()
void jeod::StructureIntegratedDynBody::collect_forces_and_torques () override virtual
Compute the rotational and translational accelerations that result from the collected forces and torques acting on the vehicle.
This function should be called as a derivative class job, with a moderately high phase number. Functions that calculate the gravitational acceleration and the effector, environmental, and non-transmitted forces and torques should be called as scheduled jobs or as lower phase derivative class jobs.
Reimplemented from jeod::DynBody.
Definition at line 77 of file structure_integrated_dyn_body_collect.cc.
References jeod::DynBody::collect, collect_local_forces_and_torques(), jeod::MassBody::composite_properties, compute_inertial_torque(), compute_rotational_acceleration(), compute_translational_acceleration(), jeod::DynBody::derivs, jeod::DynBody::dyn_children, jeod::DynBody::dyn_parent, jeod::BodyForceCollect::effector_forc, jeod::BodyForceCollect::effector_torq, effector_wrench, jeod::BodyForceCollect::environ_forc, jeod::BodyForceCollect::environ_torq, jeod::BodyForceCollect::extern_forc_inrtl, jeod::BodyForceCollect::extern_forc_struct, jeod::BodyForceCollect::extern_torq_body, jeod::BodyForceCollect::extern_torq_struct, jeod::Wrench::get_force(), jeod::Wrench::get_torque(), jeod::Vector3::incr(), jeod::BodyForceCollect::inertial_torq, jeod::Vector3::initialize(), jeod::DynBody::mass, jeod::BodyForceCollect::no_xmit_forc, jeod::BodyForceCollect::no_xmit_torq, jeod::FrameDerivs::non_grav_accel, jeod::MassPointState::position, PropagateForcesAndTorques(), jeod::FrameDerivs::rot_accel, jeod::DynBody::rotational_dynamics, struct_derivs, jeod::Vector3::sum(), jeod::FrameDerivs::trans_accel, jeod::Wrench::transform_to_point(), and jeod::DynBody::translational_dynamics.
collect_local_forces_and_torques()
void jeod::StructureIntegratedDynBody::collect_local_forces_and_torques () protected
Collect the local forces and torques that directly act on the vehicle.
Definition at line 180 of file structure_integrated_dyn_body_collect.cc.
References jeod::BodyWrenchCollect::accumulate(), jeod::accumulate_forces(), jeod::accumulate_torques(), jeod::DynBody::collect, jeod::BodyForceCollect::collect_effector_forc, jeod::BodyForceCollect::collect_effector_torq, jeod::BodyForceCollect::collect_environ_forc, jeod::BodyForceCollect::collect_environ_torq, jeod::BodyForceCollect::collect_no_xmit_forc, jeod::BodyForceCollect::collect_no_xmit_torq, jeod::BodyForceCollect::effector_forc, jeod::BodyForceCollect::effector_torq, effector_wrench, effector_wrench_collection, jeod::BodyForceCollect::environ_forc, jeod::BodyForceCollect::environ_torq, jeod::Vector3::initialize(), jeod::BodyForceCollect::no_xmit_forc, jeod::BodyForceCollect::no_xmit_torq, jeod::Wrench::reset_force_and_torque(), jeod::DynBody::rotational_dynamics, and jeod::DynBody::translational_dynamics.
Referenced by collect_forces_and_torques().
complete_translational_acceleration()
void jeod::StructureIntegratedDynBody::complete_translational_acceleration () protected
Finalize computation of the inertial-referenced translational acceleration vector.
Definition at line 417 of file structure_integrated_dyn_body_collect.cc.
References jeod::MassBody::composite_properties, jeod::Vector3::cross(), jeod::DynBody::derivs, jeod::GravityInteraction::grav_accel, jeod::DynBody::grav_interaction, inertial_accel_inrtl, inertial_accel_struct, inertial_accel_struct_omega, inertial_accel_struct_omega_dot, jeod::DynBody::mass, jeod::FrameDerivs::non_grav_accel, jeod::MassPointState::position, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, jeod::RefFrame::state, struct_derivs, jeod::DynBody::structure, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::FrameDerivs::trans_accel, and jeod::Vector3::transform_transpose().
Referenced by compute_translational_acceleration(), and solve_constraints().
compute_inertial_torque()
void jeod::StructureIntegratedDynBody::compute_inertial_torque () protected
Compute the inertial torque.
Definition at line 330 of file structure_integrated_dyn_body_collect.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::DynBody::collect, jeod::MassBody::composite_properties, jeod::Vector3::cross(), jeod::MassProperties::inertia, jeod::BodyForceCollect::inertial_torq, jeod::DynBody::mass, jeod::RefFrameState::rot, jeod::RefFrame::state, jeod::DynBody::structure, jeod::MassPointState::T_parent_this, and jeod::Vector3::transform().
Referenced by collect_forces_and_torques().
compute_rotational_acceleration()
void jeod::StructureIntegratedDynBody::compute_rotational_acceleration () protected
Compute the body- and structure-referenced rotational acceleration.
Definition at line 355 of file structure_integrated_dyn_body_collect.cc.
References jeod::DynBody::collect, jeod::MassBody::composite_properties, jeod::DynBody::derivs, jeod::Vector3::diff(), jeod::BodyForceCollect::extern_torq_body, jeod::BodyForceCollect::extern_torq_struct, jeod::BodyForceCollect::inertial_torq, jeod::MassProperties::inverse_inertia, jeod::DynBody::mass, jeod::FrameDerivs::rot_accel, struct_derivs, jeod::MassPointState::T_parent_this, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), and jeod::Vector3::zero_small().
Referenced by collect_forces_and_torques().
compute_translational_acceleration()
void jeod::StructureIntegratedDynBody::compute_translational_acceleration () protected
Compute the inertial-referenced translational acceleration vector.
Definition at line 387 of file structure_integrated_dyn_body_collect.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::DynBody::collect, complete_translational_acceleration(), jeod::MassBody::composite_properties, jeod::Vector3::cross(), jeod::DynBody::derivs, jeod::BodyForceCollect::extern_forc_inrtl, jeod::BodyForceCollect::extern_forc_struct, inertial_accel_struct_omega, jeod::MassProperties::inverse_mass, jeod::DynBody::mass, jeod::FrameDerivs::non_grav_accel, jeod::MassPointState::position, jeod::RefFrameState::rot, jeod::Vector3::scale(), jeod::RefFrame::state, jeod::DynBody::structure, jeod::RefFrameRot::T_parent_this, and jeod::Vector3::transform_transpose().
Referenced by collect_forces_and_torques().
compute_vehicle_point_derivatives()
void jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives (const BodyRefFrame & frame, FrameDerivs & derivs) override virtual
Compute the state derivatives at a vehicle point.
Parameters
frame The vehicle point, as a BodyRefFrame, at which derivatives are to be calculated.
derivs The calculated derivatives.
Reimplemented from jeod::DynBody.
Definition at line 33 of file structure_integrated_dyn_body_pt_accel.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::NamedItem::c_str(), jeod::DynBody::composite_body, jeod::Quaternion::compute_left_quat_deriv(), jeod::MassPoint::compute_relative_state(), jeod::Vector3::cross(), jeod::Vector3::diff(), jeod::MessageHandler::error(), jeod::DynBody::get_root_body(), jeod::GravityInteraction::grav_grad, jeod::DynBody::grav_interaction, jeod::DynBodyMessages::invalid_frame, jeod::DynBody::mass, jeod::BodyRefFrame::mass_point, jeod::DynBody::name, jeod::FrameDerivs::non_grav_accel, jeod::MassPointState::position, jeod::RefFrameRot::Q_parent_this, jeod::FrameDerivs::Qdot_parent_this, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, jeod::RefFrame::state, struct_derivs, jeod::DynBody::structure, jeod::MassBody::structure_point, jeod::Vector3::sum(), jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::FrameDerivs::trans_accel, jeod::Vector3::transform(), and jeod::Vector3::transform_transpose().
detach()
bool jeod::StructureIntegratedDynBody::detach (DynBody & other_body) override virtual
Break the logical connectivity between parent and child.
Parameters
[in,out] other_body The other body to detach from
Reimplemented from jeod::DynBody.
Definition at line 70 of file structure_integrated_dyn_body_solve.cc.
References jeod::NamedItem::c_str(), constraints_solver, detach(), jeod::DynBodyConstraintsSolver::detach(), jeod::DynBody::detach(), jeod::MessageHandler::fail(), jeod::DynBody::get_parent_body(), jeod::DynBodyMessages::invalid_attachment, jeod::DynBody::name, and vehicle_properties.
Referenced by detach().
get_vehicle_properties()
const VehicleProperties& jeod::StructureIntegratedDynBody::get_vehicle_properties () const inline protected
Get the vehicle properties as a const reference.
Definition at line 269 of file structure_integrated_dyn_body.hh.
References vehicle_properties.
operator=()
StructureIntegratedDynBody& jeod::StructureIntegratedDynBody::operator= (const StructureIntegratedDynBody &) private
Not implemented.
PropagateForcesAndTorques()
void jeod::StructureIntegratedDynBody::PropagateForcesAndTorques () protected
Propagate forces and torques up the kinematic chain.
Definition at line 236 of file structure_integrated_dyn_body_collect.cc.
References jeod::DynBody::collect, jeod::DynBody::composite_body, jeod::MassBody::composite_properties, jeod::RefFrame::compute_relative_state(), jeod::Vector3::cross_incr(), jeod::Vector3::diff(), jeod::DynBody::dyn_parent, jeod::BodyForceCollect::effector_forc, jeod::BodyForceCollect::effector_torq, effector_wrench, jeod::BodyForceCollect::environ_forc, jeod::BodyForceCollect::environ_torq, jeod::Vector3::incr(), jeod::Vector3::initialize(), jeod::DynBody::mass, jeod::RefFrameTrans::position, jeod::MassPointState::position, jeod::DynBody::rotational_dynamics, jeod::DynBody::structure, jeod::MassBody::structure_point, jeod::MassPointState::T_parent_this, jeod::RefFrameState::trans, jeod::Wrench::transform_to_parent(), jeod::Vector3::transform_transpose(), and jeod::DynBody::translational_dynamics.
Referenced by collect_forces_and_torques().
rot_integ()
er7_utils::IntegratorResult jeod::StructureIntegratedDynBody::rot_integ (double dyn_dt, unsigned int target_stage) override protected virtual
Integrate the rotational state of a StructureIntegratedDynBody.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Reimplemented from jeod::DynBody.
Definition at line 52 of file structure_integrated_dyn_body_integration.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::ang_vel_unit, jeod::Quaternion::compute_left_quat_deriv(), jeod::DynBody::derivs, jeod::Vector3::initialize(), jeod::RestartableSO3SecondOrderODEIntegrator::integrate(), jeod::Quaternion::left_quat_to_transformation(), jeod::Quaternion::normalize_integ(), jeod::RefFrameRot::Q_parent_this, jeod::FrameDerivs::Qdot_parent_this, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, jeod::DynBody::rot_integrator, jeod::Vector3::scale(), jeod::RefFrame::state, struct_derivs, jeod::DynBody::structure, jeod::RefFrameRot::T_parent_this, and jeod::Vector3::vmag().
set_solver()
void jeod::StructureIntegratedDynBody::set_solver (DynBodyConstraintsSolver & solver_in)
Set the solver to be used to solve contraints.
Definition at line 108 of file structure_integrated_dyn_body_solve.cc.
References jeod::NamedItem::c_str(), constraints_solver, jeod::MessageHandler::fail(), jeod::DynBodyMessages::invalid_body, and jeod::DynBody::name.
Referenced by jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver().
solve_constraints()
void jeod::StructureIntegratedDynBody::solve_constraints () virtual
Solve for constraint forces and torques acting on the vehicle and apply them to the vehicle.
This function should be called as a derivative class job, with a very high phase number. Functions that calculate the constraints should be called as derivative class jobs with a phase intermediate between that of collect_forces_and_torques and of this function.
Definition at line 142 of file structure_integrated_dyn_body_solve.cc.
References jeod::VehicleNonGravState::accel_struct, jeod::RefFrameRot::ang_vel_this, jeod::DynBody::collect, complete_translational_acceleration(), jeod::DynBody::composite_body, jeod::MassBody::composite_properties, constraints_solver, jeod::Vector3::copy(), jeod::DynBody::derivs, jeod::DynBody::dyn_parent, jeod::BodyForceCollect::extern_forc_struct, jeod::MessageHandler::fail(), jeod::BodyForceCollect::inertial_torq, jeod::VehicleNonGravState::inertial_torque_struct, jeod::DynBodyMessages::invalid_body, jeod::MassProperties::inverse_mass, jeod::DynBody::mass, jeod::FrameDerivs::non_grav_accel, non_grav_state, jeod::VehicleNonGravState::omega_body, jeod::VehicleNonGravState::omega_dot_body, jeod::VehicleNonGravState::omega_dot_struct, jeod::VehicleNonGravState::omega_struct, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, jeod::DynBody::rotational_dynamics, jeod::Vector3::scale(), jeod::DynBodyConstraintsSolver::solve(), jeod::RefFrame::state, struct_derivs, jeod::DynBody::structure, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::Vector3::transform_transpose(), jeod::DynBody::translational_dynamics, and vehicle_properties.
trans_integ()
er7_utils::IntegratorResult jeod::StructureIntegratedDynBody::trans_integ (double dyn_dt, unsigned int target_stage) override protected virtual
Integrate the translational state of a StructureIntegratedDynBody.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Reimplemented from jeod::DynBody.
Definition at line 38 of file structure_integrated_dyn_body_integration.cc.
References jeod::RestartableT3SecondOrderODEIntegrator::integrate(), jeod::RefFrameTrans::position, jeod::RefFrame::state, struct_derivs, jeod::DynBody::structure, jeod::RefFrameState::trans, jeod::FrameDerivs::trans_accel, jeod::DynBody::trans_integrator, and jeod::RefFrameTrans::velocity.
Friends And Related Function Documentation
DynBodyConstraintsSolver
friend class DynBodyConstraintsSolver friend
Definition at line 95 of file structure_integrated_dyn_body.hh.
init_attrjeod__StructureIntegratedDynBody
void init_attrjeod__StructureIntegratedDynBody () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file structure_integrated_dyn_body.hh.
Field Documentation
constraints_solver
DynBodyConstraintsSolver* jeod::StructureIntegratedDynBody::constraints_solver protected
The solver for constraint forces and torques, if there are any.
This needs to be assigned prior to initialization time in simulations that invoke member function solve_constraints() during runtime. This can be left unassigned (null) in simulations that do not have vehicular constraints.trick_units(–)
Definition at line 200 of file structure_integrated_dyn_body.hh.
Referenced by add_constraint(), attach_update_properties(), detach(), set_solver(), and solve_constraints().
effector_wrench
Wrench jeod::StructureIntegratedDynBody::effector_wrench protected
Wrench into which the effector wrenches are accumulated.
trick_units(–)
Definition at line 205 of file structure_integrated_dyn_body.hh.
Referenced by collect_forces_and_torques(), collect_local_forces_and_torques(), and PropagateForcesAndTorques().
effector_wrench_collection
BodyWrenchCollect jeod::StructureIntegratedDynBody::effector_wrench_collection
Collection of effector wrenches.
The effector wrenches are assembled into the collection at the S_define level via
vcollect containing_body.effector_wrench_collection.collect_wrench {
    pointer_to_wrench1,
    ...
    pointer_to_wrench_n
};
The collected effector wrenches are processed by the collect_forces_and_torques member function.
Note: For completion, there probably should be collected environmental and non-transmitted wrenches as well as effector wrenches.trick_units(–)
Definition at line 118 of file structure_integrated_dyn_body.hh.
Referenced by collect_local_forces_and_torques().
inertial_accel_inrtl
double jeod::StructureIntegratedDynBody::inertial_accel_inrtl[3] protected
Inertial-referenced inertial acceleration at the structure frame origin.
trick_units(m/s2)
Definition at line 242 of file structure_integrated_dyn_body.hh.
Referenced by complete_translational_acceleration().
inertial_accel_struct
double jeod::StructureIntegratedDynBody::inertial_accel_struct[3] protected
Structure-referenced inertial acceleration at the structure frame origin.
trick_units(m/s2)
Definition at line 237 of file structure_integrated_dyn_body.hh.
Referenced by complete_translational_acceleration().
inertial_accel_struct_omega
double jeod::StructureIntegratedDynBody::inertial_accel_struct_omega[3] protected
Structure-referenced inertial acceleration at the structure frame origin due to vehicle angular velocity.
trick_units(m/s2)
Definition at line 226 of file structure_integrated_dyn_body.hh.
Referenced by complete_translational_acceleration(), and compute_translational_acceleration().
inertial_accel_struct_omega_dot
double jeod::StructureIntegratedDynBody::inertial_accel_struct_omega_dot[3] protected
Structure-referenced inertial acceleration at the structure frame origin due to vehicle angular acceleration.
trick_units(m/s2)
Definition at line 232 of file structure_integrated_dyn_body.hh.
Referenced by complete_translational_acceleration().
non_grav_state
VehicleNonGravState jeod::StructureIntegratedDynBody::non_grav_state protected
Rotational and translational behaviors, for the constraints solver.
trick_units(–)
Definition at line 220 of file structure_integrated_dyn_body.hh.
Referenced by solve_constraints().
struct_derivs
FrameDerivs jeod::StructureIntegratedDynBody::struct_derivs protected
Translational/rotational accelerations of the structural frame.
trick_units(–)
Definition at line 210 of file structure_integrated_dyn_body.hh.
Referenced by collect_forces_and_torques(), complete_translational_acceleration(), compute_rotational_acceleration(), compute_vehicle_point_derivatives(), rot_integ(), solve_constraints(), and trans_integ().
vehicle_properties
VehicleProperties jeod::StructureIntegratedDynBody::vehicle_properties protected
Various properties of the vehicle, for the constraints solver.
trick_units(–)
Definition at line 215 of file structure_integrated_dyn_body.hh.
Referenced by attach_update_properties(), detach(), get_vehicle_properties(), and solve_constraints().
The documentation for this class was generated from the following files:
structure_integrated_dyn_body.hh
structure_integrated_dyn_body.cc
structure_integrated_dyn_body_collect.cc
structure_integrated_dyn_body_integration.cc
structure_integrated_dyn_body_pt_accel.cc
structure_integrated_dyn_body_solve.cc