JEOD: jeod::AerodynamicDrag Class Reference
jeod::AerodynamicDrag Class Reference
The main class for calculating aerodynamic drag.
#include <aero_drag.hh>
Public Member Functions
AerodynamicDrag ()
default constructor
virtual ~AerodynamicDrag ()
Destructor.
void aero_drag (double inertial_velocity[3], AtmosphereState *atmos_ptr, double T_inertial_struct[3][3], double mass, double center_grav[3])
Calculates the total aerodynamic drag force and torque, from the information given.
void set_aero_surface (AeroSurface &to_set)
Set the surface this AeroDrag object will calculate drag for.
void clear_aero_surface ()
Remove any AeroSurface being used for calculation.
Data Fields
bool active
On = aerodynamics enabled.
bool constant_density
Use constant density for aero drag?
double density
Density of the last time AerodynamicDrag was used.
double aero_force [3]
Total Force due to aero drag, resulting from all plates combined.
double aero_torque [3]
Total torque due to aero drag, resulting from all plates combined.
AeroDragParameters param
parameters shared with plate model
bool use_default_behavior
Use the default behavior?
AeroSurface * aero_surface_ptr
Pointer to the current aero surface.
DefaultAero * default_behavior
Pointer to an object that defines the default aero behavior.
DefaultAero ballistic_drag
Spherical, ballistic drag.
Private Member Functions
AerodynamicDrag (const AerodynamicDrag &)
AerodynamicDrag & operator= (const AerodynamicDrag &)
Detailed Description
The main class for calculating aerodynamic drag.
Definition at line 141 of file aero_drag.hh.
Constructor & Destructor Documentation
AerodynamicDrag() [1/2]
jeod::AerodynamicDrag::AerodynamicDrag (void)
default constructor
Definition at line 68 of file aero_drag.cc.
References aero_force, aero_torque, ballistic_drag, default_behavior, and jeod::Vector3::initialize().
~AerodynamicDrag()
jeod::AerodynamicDrag::~AerodynamicDrag (void) virtual
Destructor.
Definition at line 87 of file aero_drag.cc.
AerodynamicDrag() [2/2]
jeod::AerodynamicDrag::AerodynamicDrag (const AerodynamicDrag &) private
Member Function Documentation
aero_drag()
void jeod::AerodynamicDrag::aero_drag (double inertial_velocity[3], AtmosphereState * atmos_ptr, double T_inertial_struct[3][3], double mass, double center_grav[3])
Calculates the total aerodynamic drag force and torque, from the information given.
Parameters
[in] inertial_velocity vehicle velocity in inertial RF
Units: M/s
[in] atmos_ptr Pointer to the AtmosphereState used for density and wind information
[in] T_inertial_struct Transformation matrix from the inertial frame to the structural
[in] mass kg Mass of the vehicle
[in] center_grav position of the center of gravity, in the structural frame
Units: M
Definition at line 103 of file aero_drag.cc.
References active, jeod::AeroSurface::aero_facets, aero_force, aero_surface_ptr, aero_torque, jeod::AeroFacet::aerodrag_force(), jeod::DefaultAero::aerodrag_force(), constant_density, default_behavior, jeod::AtmosphereState::density, density, jeod::Vector3::diff(), jeod::AeroDragParameters::dynamic_pressure, jeod::AeroSurface::facets_size, jeod::MessageHandler::fail(), jeod::InteractionFacet::force, jeod::Vector3::incr(), jeod::Vector3::initialize(), param, jeod::AerodynamicsMessages::runtime_error, jeod::Vector3::scale(), jeod::InteractionFacet::torque, jeod::Vector3::transform(), jeod::Vector3::unit(), use_default_behavior, jeod::Vector3::vmag(), and jeod::AtmosphereState::wind.
clear_aero_surface()
void jeod::AerodynamicDrag::clear_aero_surface ()
Remove any AeroSurface being used for calculation.
Note: The variable "use_default_behavior" must be set to true if there is no set aero surface
Definition at line 206 of file aero_drag.cc.
References aero_surface_ptr.
operator=()
AerodynamicDrag& jeod::AerodynamicDrag::operator= (const AerodynamicDrag &) private
set_aero_surface()
void jeod::AerodynamicDrag::set_aero_surface (AeroSurface & to_set)
Set the surface this AeroDrag object will calculate drag for.
Parameters
[in] to_set The AeroSurface to be used
Definition at line 194 of file aero_drag.cc.
References aero_surface_ptr.
Field Documentation
active
bool jeod::AerodynamicDrag::active
On = aerodynamics enabled.
trick_units(–)
Definition at line 146 of file aero_drag.hh.
Referenced by aero_drag().
aero_force
double jeod::AerodynamicDrag::aero_force[3]
Total Force due to aero drag, resulting from all plates combined.
trick_units(N)
Definition at line 163 of file aero_drag.hh.
Referenced by aero_drag(), and AerodynamicDrag().
aero_surface_ptr
AeroSurface* jeod::AerodynamicDrag::aero_surface_ptr
Pointer to the current aero surface.
trick_units(–)
Definition at line 183 of file aero_drag.hh.
Referenced by aero_drag(), clear_aero_surface(), and set_aero_surface().
aero_torque
double jeod::AerodynamicDrag::aero_torque[3]
Total torque due to aero drag, resulting from all plates combined.
trick_units(N*m)
Definition at line 168 of file aero_drag.hh.
Referenced by aero_drag(), and AerodynamicDrag().
ballistic_drag
DefaultAero jeod::AerodynamicDrag::ballistic_drag
Spherical, ballistic drag.
The default, default behavior. Can be overridden by resetting the "default_behavior" pointertrick_units(–)
Definition at line 197 of file aero_drag.hh.
Referenced by AerodynamicDrag().
constant_density
bool jeod::AerodynamicDrag::constant_density
Use constant density for aero drag?
trick_units(–)
Definition at line 151 of file aero_drag.hh.
Referenced by aero_drag().
default_behavior
DefaultAero* jeod::AerodynamicDrag::default_behavior
Pointer to an object that defines the default aero behavior.
This is used if the AeroSurface pointer in aero_drag is set to NULL. Defaults to ballistic drag, but can be overriddentrick_units(–)
Definition at line 190 of file aero_drag.hh.
Referenced by aero_drag(), and AerodynamicDrag().
density
double jeod::AerodynamicDrag::density
Density of the last time AerodynamicDrag was used.
If constant_density is set true, then this is the density that will be usedtrick_units(kg/m3)
Definition at line 158 of file aero_drag.hh.
Referenced by aero_drag().
param
AeroDragParameters jeod::AerodynamicDrag::param
parameters shared with plate model
trick_units(–)
Definition at line 173 of file aero_drag.hh.
Referenced by aero_drag().
use_default_behavior
bool jeod::AerodynamicDrag::use_default_behavior
Use the default behavior?
trick_units(–)
Definition at line 178 of file aero_drag.hh.
Referenced by aero_drag().
The documentation for this class was generated from the following files:
aero_drag.hh
aero_drag.cc