JEOD: jeod::LinearSystemSolver Class Reference
jeod::LinearSystemSolver Class Reference abstract
Represents a linear system of equations, A*x = b, where A is conceptually an NxN matrix, and x and b are conceptually N-vectors.
#include <linear_system_solver.hh>
Public Types
using DoubleVectorT = JeodPrimitiveVector< double >::type
Vector of doubles.
using AMatrixViewT = SubArrayView< TwoDArray, double >
A slice of the A matrix.
using BVectorViewT = SubVectorView< std::vector< double >, double >
A slice of the b vector.
Public Member Functions
LinearSystemSolver ()
Default constructor.
virtual ~LinearSystemSolver ()
Destructor.
virtual void set_max_dimensions (unsigned max_dims_in)
Set the maximum dimensionality of the problem.
virtual void set_n_dimensions (unsigned n_dims)
Set the current dimensionality of the problem.
AMatrixViewT make_a_matrix_view (const SolverTypes::IndexPairT &row_range, const SolverTypes::IndexPairT &col_range)
Create a view to a portion of the A matrix.
BVectorViewT make_b_vector_view (const SolverTypes::IndexPairT &row_range)
Create a view to a portion of the b vector.
virtual unsigned solve (DoubleVectorT &x)=0
Solve for x in A*x = b.
LinearSystemSolver (const LinearSystemSolver &)=delete
LinearSystemSolver & operator= (const LinearSystemSolver &)=delete
Protected Attributes
TwoDArray a_matrix
The matrix A in A*x = b.
DoubleVectorT b_vector
The vector b in A*x = b.
unsigned max_dims {}
The maximum number of dimensions, to scope sizing of A and b.
unsigned n_dimensions {}
The current dimensionality of the problem.
unsigned n_rows {}
The number of rows currently in use.
unsigned n_cols {}
The number of columns currently in use.
Friends
class InputProcessor
void init_attrjeod__LinearSystemSolver ()
Detailed Description
Represents a linear system of equations, A*x = b, where A is conceptually an NxN matrix, and x and b are conceptually N-vectors.
This class solves for x in A*x = b. How it does that is up to a derived class. solve is pure virtual in this base class template.
An implementor of an instantiable derived class of this class template must implement the solve method.
A user of this class template
Sets the number of degrees of freedom N,
Populates the A matrix and b vector, and
Requests the object to solve for x.
Users must not assume that solve leaves the populated A matrix and b vector untouched. To the contrary, an instantiable solver might well modify these elements in the process of solving the matrix equation. It is up to the user to fully populate the A matrix and b vector prior to calling solve.
Definition at line 87 of file linear_system_solver.hh.
Member Typedef Documentation
AMatrixViewT
using jeod::LinearSystemSolver::AMatrixViewT = SubArrayView<TwoDArray, double>
A slice of the A matrix.
Definition at line 101 of file linear_system_solver.hh.
BVectorViewT
using jeod::LinearSystemSolver::BVectorViewT = SubVectorView<std::vector<double>, double>
A slice of the b vector.
Definition at line 106 of file linear_system_solver.hh.
DoubleVectorT
using jeod::LinearSystemSolver::DoubleVectorT = JeodPrimitiveVector<double>::type
Vector of doubles.
Definition at line 95 of file linear_system_solver.hh.
Constructor & Destructor Documentation
LinearSystemSolver() [1/2]
jeod::LinearSystemSolver::LinearSystemSolver () inline
Default constructor.
Definition at line 114 of file linear_system_solver.hh.
References b_vector, JEOD_REGISTER_CHECKPOINTABLE, and JEOD_REGISTER_NONEXPORTED_CLASS.
~LinearSystemSolver()
virtual jeod::LinearSystemSolver::~LinearSystemSolver () inline virtual
Destructor.
Definition at line 126 of file linear_system_solver.hh.
References b_vector, and JEOD_DEREGISTER_CHECKPOINTABLE.
LinearSystemSolver() [2/2]
jeod::LinearSystemSolver::LinearSystemSolver (const LinearSystemSolver &) delete
Member Function Documentation
make_a_matrix_view()
AMatrixViewT jeod::LinearSystemSolver::make_a_matrix_view (const SolverTypes::IndexPairT & row_range, const SolverTypes::IndexPairT & col_range) inline
Create a view to a portion of the A matrix.
Definition at line 161 of file linear_system_solver.hh.
References a_matrix.
Referenced by jeod::DynBodyConstraintsSolver::build_system_of_equations().
make_b_vector_view()
BVectorViewT jeod::LinearSystemSolver::make_b_vector_view (const SolverTypes::IndexPairT & row_range) inline
Create a view to a portion of the b vector.
Definition at line 170 of file linear_system_solver.hh.
References b_vector.
Referenced by jeod::DynBodyConstraintsSolver::build_system_of_equations().
operator=()
LinearSystemSolver& jeod::LinearSystemSolver::operator= (const LinearSystemSolver &) delete
set_max_dimensions()
virtual void jeod::LinearSystemSolver::set_max_dimensions (unsigned max_dims_in) inline virtual
Set the maximum dimensionality of the problem.
Reimplemented in jeod::GaussJordanSolver.
Definition at line 136 of file linear_system_solver.hh.
References a_matrix, b_vector, max_dims, and jeod::TwoDArray::reserve().
Referenced by jeod::GaussJordanSolver::set_max_dimensions(), and set_n_dimensions().
set_n_dimensions()
virtual void jeod::LinearSystemSolver::set_n_dimensions (unsigned n_dims) inline virtual
Set the current dimensionality of the problem.
Reimplemented in jeod::GaussJordanSolver.
Definition at line 149 of file linear_system_solver.hh.
References a_matrix, b_vector, n_cols, n_dimensions, n_rows, jeod::TwoDArray::resize(), and set_max_dimensions().
Referenced by jeod::DynBodyConstraintsSolver::build_system_of_equations(), and jeod::GaussJordanSolver::set_n_dimensions().
solve()
virtual unsigned jeod::LinearSystemSolver::solve (DoubleVectorT & x) pure virtual
Solve for x in A*x = b.
Implemented in jeod::GaussJordanSolver.
Referenced by jeod::DynBodyConstraintsSolver::solve().
Friends And Related Function Documentation
init_attrjeod__LinearSystemSolver
void init_attrjeod__LinearSystemSolver () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file linear_system_solver.hh.
Field Documentation
a_matrix
TwoDArray jeod::LinearSystemSolver::a_matrix protected
The matrix A in A*x = b.
trick_io(**)
Definition at line 190 of file linear_system_solver.hh.
Referenced by make_a_matrix_view(), set_max_dimensions(), set_n_dimensions(), and jeod::GaussJordanSolver::solve().
b_vector
DoubleVectorT jeod::LinearSystemSolver::b_vector protected
The vector b in A*x = b.
trick_io(**)
Definition at line 195 of file linear_system_solver.hh.
Referenced by LinearSystemSolver(), make_b_vector_view(), set_max_dimensions(), set_n_dimensions(), jeod::GaussJordanSolver::solve(), and ~LinearSystemSolver().
max_dims
unsigned jeod::LinearSystemSolver::max_dims {} protected
The maximum number of dimensions, to scope sizing of A and b.
trick_units(–)
Definition at line 200 of file linear_system_solver.hh.
Referenced by jeod::GaussJordanSolver::set_max_dimensions(), and set_max_dimensions().
n_cols
unsigned jeod::LinearSystemSolver::n_cols {} protected
The number of columns currently in use.
By default, this is the current dimensionality of the problem.trick_units(–)
Definition at line 217 of file linear_system_solver.hh.
Referenced by set_n_dimensions().
n_dimensions
unsigned jeod::LinearSystemSolver::n_dimensions {} protected
The current dimensionality of the problem.
trick_units(–)
Definition at line 205 of file linear_system_solver.hh.
Referenced by set_n_dimensions(), and jeod::GaussJordanSolver::solve().
n_rows
unsigned jeod::LinearSystemSolver::n_rows {} protected
The number of rows currently in use.
By default, this is the current dimensionality of the problem.trick_units(–)
Definition at line 211 of file linear_system_solver.hh.
Referenced by set_n_dimensions().
The documentation for this class was generated from the following file:
linear_system_solver.hh