JEOD: jeod::Wrench Class Reference
jeod::Wrench Class Reference
A wrench comprises a torque and a force applied at a point on a DynBody.
#include <wrench.hh>
Public Member Functions
Wrench (bool active_in=true)
Default constructor.
Wrench (const double torque_in[3], const double force_in[3], const double point_in[3], bool active_in=true)
Non-default constructor that sets all elements of the wrench.
Wrench (const double point_in[3], bool active_in=true)
Non-default constructor that sets the point and active flag.
virtual ~Wrench ()=default
Destructor.
Wrench (const Wrench &)=default
Copy constructor.
Wrench & operator= (const Wrench &)=default
Copy assignment operator.
Wrench (Wrench &&)=default
Move constructor.
Wrench & operator= (Wrench &&)=default
Move assignment operator.
Wrench & operator+= (const Wrench &other)
Increment this wrench by the other, but only if both are active.
void activate ()
Mark this wrench as active.
void deactivate ()
Mark this wrench as inactive.
bool is_active () const
Is this wrench active?
void reset_force_and_torque ()
Set the force and torque to zero.
void reset_torque ()
Set the torque to zero.
void reset_force ()
Set the force to zero.
void reset_point ()
Set the point to zero.
void set (const double torque_in[3], const double force_in[3], const double point_in[3])
Set all vector elements of the wrench.
void set_torque (const double torque_in[3])
Set the torque to the specified value.
void set_force (const double force_in[3])
Set the force to the specified value.
void set_force (const double force_in[3], const double point_in[3])
Set the force and the point of application to the specified values.
void set_point (const double point_in[3])
Set the point of application to the specified value.
void scale_torque (double scale)
Scale the torque by the specified value.
void scale_force (double scale)
Scale the force by the specified value.
const double * get_torque () const
Const getter of the torque vector.
const double * get_force () const
Const getter of the force vector.
const double * get_point () const
Const getter of the point vector.
Wrench & accumulate (const std::vector< Wrench *> &collection)
Accumulate the wrenches in the collection to form a combined wrench about the current wrench point, which remains unchanged.
Wrench & accumulate (const std::vector< Wrench *> &collection, const double new_point[3])
Accumulate the wrenches in the collection to form a combined wrench about the specified wrench point.
Wrench transform_to_point (const double new_point[3]) const
Construct an equivalent Wrench about the specified point.
Wrench transform_to_parent (const MassPointState &point_state) const
Construct an equivalent Wrench about the current point, but in a different reference frame.
Private Attributes
double torque [3]
The torque exerted on the DynBody by the force/torque agent, expressed in structural coordinates.
double force [3]
The force exerted on the DynBody by the force/torque agent, expressed in structural coordinates.
double point [3]
The structural coordinates of the point at which the force is applied.
bool active
Indicated whether the wrench is active (true) or inactive (false).
Friends
class InputProcessor
void init_attrjeod__Wrench ()
Detailed Description
A wrench comprises a torque and a force applied at a point on a DynBody.
The torque should not include the torque due to the application of the force.
A Trick simulation issues vcollect statements such as
 vcollect vehicle.dyn_body.collect_wrench.collection
 {
     wrench_model1.wrench,
     wrench_model2.wrench
 };
Definition at line 81 of file wrench.hh.
Constructor & Destructor Documentation
Wrench() [1/5]
jeod::Wrench::Wrench (bool active_in = true) inline explicit
Default constructor.
The wrench is marked as active, and the torque, force, and point vectors are all initialized to zero. This constructor can also be used as a non-default constructor that marks the wrench as inactive by calling it with one argument (a boolean) whose value is false.
Parameters
active_in True (default) indicates the wrench is active.
Definition at line 97 of file wrench.hh.
References force, jeod::Vector3::initialize(), point, and torque.
Wrench() [2/5]
jeod::Wrench::Wrench (const double torque_in[3], const double force_in[3], const double point_in[3], bool active_in = true) inline explicit
Non-default constructor that sets all elements of the wrench.
Parameters
torque_in The intrinsic torque for this wrench.
force_in The force applied at the point.
point_in The point at which forces are applied.
active_in True (default) indicates the wrench is active.
Definition at line 114 of file wrench.hh.
References jeod::Vector3::copy(), force, point, and torque.
Wrench() [3/5]
jeod::Wrench::Wrench (const double point_in[3], bool active_in = true) inline explicit
Non-default constructor that sets the point and active flag.
The torque and force and initialized to zero.
Parameters
point_in The point at which forces are applied.
active_in True (default) indicates the wrench is active.
Definition at line 133 of file wrench.hh.
References jeod::Vector3::copy(), force, jeod::Vector3::initialize(), point, and torque.
~Wrench()
virtual jeod::Wrench::~Wrench () virtual default
Destructor.
Wrench() [4/5]
jeod::Wrench::Wrench (const Wrench &) default
Copy constructor.
Wrench() [5/5]
jeod::Wrench::Wrench (Wrench &&) default
Move constructor.
Member Function Documentation
accumulate() [1/2]
Wrench& jeod::Wrench::accumulate (const std::vector< Wrench *> & collection) inline
Accumulate the wrenches in the collection to form a combined wrench about the current wrench point, which remains unchanged.
Parameters
collection The wrenches to be accumulated.
Definition at line 372 of file wrench.hh.
References reset_force_and_torque().
Referenced by jeod::BodyWrenchCollect::accumulate(), and accumulate().
accumulate() [2/2]
Wrench& jeod::Wrench::accumulate (const std::vector< Wrench *> & collection, const double new_point[3]) inline
Accumulate the wrenches in the collection to form a combined wrench about the specified wrench point.
Parameters
collection The wrenches to be accumulated.
new_point The point about which the wrenches to be accumulated.
Definition at line 390 of file wrench.hh.
References accumulate(), and set_point().
activate()
void jeod::Wrench::activate () inline
Mark this wrench as active.
Definition at line 198 of file wrench.hh.
References active.
deactivate()
void jeod::Wrench::deactivate () inline
Mark this wrench as inactive.
Definition at line 207 of file wrench.hh.
References active.
get_force()
const double* jeod::Wrench::get_force () const inline
Const getter of the force vector.
Definition at line 352 of file wrench.hh.
References force.
Referenced by jeod::accumulate_wrenches(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
get_point()
const double* jeod::Wrench::get_point () const inline
Const getter of the point vector.
Definition at line 361 of file wrench.hh.
References point.
get_torque()
const double* jeod::Wrench::get_torque () const inline
Const getter of the torque vector.
Definition at line 343 of file wrench.hh.
References torque.
Referenced by jeod::accumulate_wrenches(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), jeod::TorqueConstraintComponent::setup_constraint(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
is_active()
bool jeod::Wrench::is_active (void) const inline
Is this wrench active?
Definition at line 216 of file wrench.hh.
References active.
Referenced by jeod::accumulate_wrenches().
operator+=()
Wrench& jeod::Wrench::operator+= (const Wrench & other) inline
Increment this wrench by the other, but only if both are active.
The other wrench is effectively reseated to this wrench's point prior to incrementing.
Parameters
other Wrench with which this wrench is to be incremented.
Returns
*this.
Definition at line 180 of file wrench.hh.
References active, jeod::Vector3::cross_incr(), jeod::Vector3::diff(), force, jeod::Vector3::incr(), point, and torque.
operator=() [1/2]
Wrench& jeod::Wrench::operator= (const Wrench &) default
Copy assignment operator.
operator=() [2/2]
Wrench& jeod::Wrench::operator= (Wrench &&) default
Move assignment operator.
reset_force()
void jeod::Wrench::reset_force () inline
Set the force to zero.
The torque and point remain unaltered.
Definition at line 244 of file wrench.hh.
References force, and jeod::Vector3::initialize().
reset_force_and_torque()
void jeod::Wrench::reset_force_and_torque () inline
Set the force and torque to zero.
The point remains unaltered.
Definition at line 225 of file wrench.hh.
References force, jeod::Vector3::initialize(), and torque.
Referenced by accumulate(), jeod::accumulate_wrenches(), jeod::StructureIntegratedDynBody::collect_local_forces_and_torques(), and jeod::DynBodyAttachedBodyConstraint::set_constraint_values().
reset_point()
void jeod::Wrench::reset_point () inline
Set the point to zero.
The torque and force remain unaltered.
Definition at line 253 of file wrench.hh.
References jeod::Vector3::initialize(), and point.
reset_torque()
void jeod::Wrench::reset_torque () inline
Set the torque to zero.
The force and point remain unaltered.
Definition at line 235 of file wrench.hh.
References jeod::Vector3::initialize(), and torque.
scale_force()
void jeod::Wrench::scale_force (double scale) inline
Scale the force by the specified value.
The torque and point of application remain unchanged.
Definition at line 334 of file wrench.hh.
References force, and jeod::Vector3::scale().
Referenced by jeod::ForceConstraintComponent::set_constraint_value().
scale_torque()
void jeod::Wrench::scale_torque (double scale) inline
Scale the torque by the specified value.
The force and point of application remain unaltered.
Definition at line 324 of file wrench.hh.
References jeod::Vector3::scale(), and torque.
Referenced by jeod::TorqueConstraintComponent::set_constraint_value().
set()
void jeod::Wrench::set (const double torque_in[3], const double force_in[3], const double point_in[3]) inline
Set all vector elements of the wrench.
Parameters
torque_in The intrinsic torque for this wrench.
force_in The force applied at the point.
point_in The point at which forces are applied.
Definition at line 265 of file wrench.hh.
References jeod::Vector3::copy(), force, point, and torque.
set_force() [1/2]
void jeod::Wrench::set_force (const double force_in[3]) inline
Set the force to the specified value.
The torque and point of application remain unchanged.
Definition at line 290 of file wrench.hh.
References jeod::Vector3::copy(), and force.
Referenced by jeod::ForceConstraintComponent::setup_constraint().
set_force() [2/2]
void jeod::Wrench::set_force (const double force_in[3], const double point_in[3]) inline
Set the force and the point of application to the specified values.
The torque remain unchanged.
Definition at line 300 of file wrench.hh.
References jeod::Vector3::copy(), force, and point.
set_point()
void jeod::Wrench::set_point (const double point_in[3]) inline
Set the point of application to the specified value.
The force and torque remain unchanged.
Definition at line 313 of file wrench.hh.
References jeod::Vector3::copy(), and point.
Referenced by jeod::BodyWrenchCollect::accumulate(), accumulate(), jeod::accumulate_wrenches(), and jeod::DynBodyAttachedBodyConstraint::set_constraint_values().
set_torque()
void jeod::Wrench::set_torque (const double torque_in[3]) inline
Set the torque to the specified value.
The force and point of application remain unaltered.
Definition at line 280 of file wrench.hh.
References jeod::Vector3::copy(), and torque.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), and jeod::TorqueConstraintComponent::setup_constraint().
transform_to_parent()
Wrench jeod::Wrench::transform_to_parent (const MassPointState & point_state) const inline
Construct an equivalent Wrench about the current point, but in a different reference frame.
Parameters
point_state Contains the position and orientation of the current frame in the parent frame.
Returns
Equivalent wrench in the parent frame.
Definition at line 421 of file wrench.hh.
References force, jeod::Vector3::incr(), point, jeod::MassPointState::position, jeod::MassPointState::T_parent_this, torque, and jeod::Vector3::transform_transpose().
Referenced by jeod::StructureIntegratedDynBody::PropagateForcesAndTorques().
transform_to_point()
Wrench jeod::Wrench::transform_to_point (const double new_point[3]) const inline
Construct an equivalent Wrench about the specified point.
Parameters
new_point The point about which this is to be represented.
Returns
Equivalent wrench about the specified point.
Definition at line 404 of file wrench.hh.
References active, jeod::Vector3::cross_incr(), jeod::Vector3::diff(), force, point, and torque.
Referenced by jeod::StructureIntegratedDynBody::collect_forces_and_torques(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
Friends And Related Function Documentation
init_attrjeod__Wrench
void init_attrjeod__Wrench () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file wrench.hh.
Field Documentation
active
bool jeod::Wrench::active private
Indicated whether the wrench is active (true) or inactive (false).
inactive wrenches are not collected.trick_units(–)
Definition at line 466 of file wrench.hh.
Referenced by activate(), deactivate(), is_active(), operator+=(), and transform_to_point().
force
double jeod::Wrench::force[3] private
The force exerted on the DynBody by the force/torque agent, expressed in structural coordinates.
trick_units(N)
Definition at line 455 of file wrench.hh.
Referenced by get_force(), operator+=(), reset_force(), reset_force_and_torque(), scale_force(), set(), set_force(), transform_to_parent(), transform_to_point(), and Wrench().
point
double jeod::Wrench::point[3] private
The structural coordinates of the point at which the force is applied.
trick_units(m)
Definition at line 460 of file wrench.hh.
Referenced by get_point(), operator+=(), reset_point(), set(), set_force(), set_point(), transform_to_parent(), transform_to_point(), and Wrench().
torque
double jeod::Wrench::torque[3] private
The torque exerted on the DynBody by the force/torque agent, expressed in structural coordinates.
This torque should not include the torque that results from the force not passing through the center of mass. A typical thruster, for example, should have the torque set to zero. On the other hand, a Hall effect thruster will have a non-zero torque due to the swirling of the exhaust.trick_units(N*m)
Definition at line 449 of file wrench.hh.
Referenced by get_torque(), operator+=(), reset_force_and_torque(), reset_torque(), scale_torque(), set(), set_torque(), transform_to_parent(), transform_to_point(), and Wrench().
The documentation for this class was generated from the following file:
wrench.hh