JEOD: jeod::RNPMars Class Reference
jeod::RNPMars Class Reference
Implements the "Pathfinder" Mars RNP model using the generic RNP framework.
#include <rnp_mars.hh>
Public Member Functions
RNPMars ()
Default constructor.
~RNPMars () override=default
RNPMars & operator= (const RNPMars &)=delete
RNPMars (const RNPMars &)=delete
void initialize (DynManager &manager) override
Perform setup of the object, then call the base class initializer.
void update_rnp (TimeTT &time_tt)
Update the complete RNP and supply it to the Dynamics Manager.
void update_axial_rotation (TimeTT &time_tt)
Update rotation portion of RNP and supply RNP to dynamics manager.
double timestamp () const override
Return the last time at which the RNP was updated.
std::string get_name () const override
Return the internal name of the object.
void ephem_update () override
Define 'alias' to call axial update function, for polymorphism.
Public Member Functions inherited from jeod::PlanetRNP
PlanetRNP ()=default
~PlanetRNP () override=default
PlanetRNP & operator= (const PlanetRNP &rhs)=delete
PlanetRNP (const PlanetRNP &rhs)=delete
void update_rnp ()
Invokes the calculation for all rotation models contained in the RNP, used on the last time set in each model through PlanetRotation::set_time.
void update_axial_rotation ()
Same as update_rnp, but only the axial_rotation will be updated.
void propagate_rnp ()
Multiples out the (up to) four planet rotation models (nutation, precession, polar motion and rotation), leaving out models whose pointers are NULL, and feeds it to the planet attitude found in the dyn manager given in initialize.
Public Member Functions inherited from jeod::PlanetOrientation
PlanetOrientation ()=default
~PlanetOrientation () override=default
PlanetOrientation & operator= (const PlanetOrientation &rhs)=delete
PlanetOrientation (const PlanetOrientation &rhs)=delete
void activate () override
Activates the PlanetOrientation model.
void deactivate () override
Deactivates the PlanetOrientation model.
void ephem_initialize (EphemeridesManager &manager) override
Implements the EphemInterface pure virtual function ephem_initialize.
void ephem_activate (EphemeridesManager &manager) override
Mark the model as being activate or inactive.
void ephem_build_tree (EphemeridesManager &manager) override
Function, for a particular ephemeris model, nominally builds the particular models portions of the reference frame tree.
void set_name (std::string name_in)
Setter for the name.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface () override=default
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()=default
virtual ~ActivateInterface ()=default
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Data Fields
RotationMars RMars
"Pathfinder" Mars rotation model.
NutationMars NMars
"Pathfinder" Mars nutation model.
PrecessionMars PMars
"Pathfinder" Mars precession model.
std::string internal_name {"RNPMars"}
The hard coded internal name to be returned on calling the overridden EphemerisInterface function "get_name".
Data Fields inherited from jeod::PlanetRNP
PlanetRotation * nutation {}
Pointer to the nutation model.
PlanetRotation * precession {}
Pointer to the precession model.
PlanetRotation * polar_motion {}
Pointer to the polar_motion model.
PlanetRotation * rotation {}
Pointer to the rotation model.
RNPFidelity rnp_type {FullRNP}
The fidelity of the RNP model.
bool enable_polar {true}
Gives the option of turning on or off polar motion.
double NP_matrix [3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } }
Rotation Matrix representing: transpose(nutation->rotation) * transpose(precession->rotation)
Data Fields inherited from jeod::PlanetOrientation
bool active {true}
Is the orientation model actively updating? Defaults to true.
Planet * planet {}
The planet the attitude model will be working on.
std::string name {""}
Name of the planet the attitude model will be working on.
RefFrameRot * planet_rot_state {}
The current rotational state of the planet.
double planet_omega {}
Nominal axial velocity of the earth.
EphemerisOrientation orient_interface
The ephemeris interface to the in question orientation.
Private Member Functions
void get_dyn_time_ptr (TimeTT &time_tt)
Get simulation time via a two-step pointer trail.
Private Attributes
TimeTT * tt_ptr {}
Pointer to the TimeTT used to update this object when ephem_update is invoked.
TimeDyn * time_dyn_ptr {}
Pointer to the TimeDyn object, used to time stamp the reference frame when it is being updated.
double last_updated_time_full {}
The last update time for the RNP, when updated through update_rnp.
bool never_updated_full {true}
Indicates that last_updated_time_full has never been populated, and that the update must be done regardless of given time.
double last_updated_time_rotational {}
The last rotational update time, when updated through update_axial_rotation, referencing TimeDyn.seconds.
bool never_updated_rotational {true}
Indicates that last_updated_time_rotational has never been populated, and that the update must be done regardless of given time.
Friends
class InputProcessor
void init_attrjeod__RNPMars ()
Additional Inherited Members
Public Types inherited from jeod::PlanetRNP
enum RNPFidelity { FullRNP = 0, RotationOnly = 1, ConstantNP = 2 }
Specifies the initialization fidelity of the RNP model.
Protected Attributes inherited from jeod::PlanetRNP
double scratch_matrix [3][3] {}
A transformation matrix used for intermediate math steps.
Detailed Description
Implements the "Pathfinder" Mars RNP model using the generic RNP framework.
Definition at line 101 of file rnp_mars.hh.
Constructor & Destructor Documentation
RNPMars() [1/2]
jeod::RNPMars::RNPMars ()
Default constructor.
Definition at line 68 of file rnp_mars.cc.
References jeod::PlanetRNP::enable_polar, NMars, jeod::PlanetRNP::nutation, PMars, jeod::PlanetRNP::polar_motion, jeod::PlanetRNP::precession, RMars, and jeod::PlanetRNP::rotation.
~RNPMars()
jeod::RNPMars::~RNPMars () override default
RNPMars() [2/2]
jeod::RNPMars::RNPMars (const RNPMars &) delete
Member Function Documentation
ephem_update()
void jeod::RNPMars::ephem_update () override virtual
Define 'alias' to call axial update function, for polymorphism.
Implements jeod::EphemerisInterface.
Definition at line 251 of file rnp_mars.cc.
References jeod::PlanetOrientation::active, jeod::MessageHandler::inform(), jeod::EphemerisItem::is_active(), jeod::PlanetOrientation::orient_interface, jeod::RNPMessages::setup_error, tt_ptr, and jeod::PlanetRNP::update_axial_rotation().
get_dyn_time_ptr()
void jeod::RNPMars::get_dyn_time_ptr (TimeTT & time_tt) private
Get simulation time via a two-step pointer trail.
Parameters
[in] time_tt Current TT time
Definition at line 275 of file rnp_mars.cc.
References jeod::MessageHandler::fail(), jeod::TimeManager::get_time_ptr(), jeod::RNPMessages::setup_error, time_dyn_ptr, and jeod::JeodBaseTime::time_manager.
Referenced by update_axial_rotation(), and update_rnp().
get_name()
std::string jeod::RNPMars::get_name () const override virtual
Return the internal name of the object.
Implements jeod::PlanetRNP.
Definition at line 243 of file rnp_mars.cc.
References internal_name.
initialize()
void jeod::RNPMars::initialize (DynManager & dyn_manager) override virtual
Perform setup of the object, then call the base class initializer.
Parameters
[in,out] dyn_manager Ref to dynamics manager
Reimplemented from jeod::PlanetOrientation.
Definition at line 87 of file rnp_mars.cc.
References jeod::PrecessionMars::compute_fixed_matrices(), jeod::PlanetRNP::ConstantNP, jeod::PlanetRNP::FullRNP, jeod::PlanetOrientation::initialize(), NMars, jeod::PrecessionMars::nutation, jeod::RotationMars::nutation, jeod::PlanetOrientation::planet_omega, jeod::RotationMars::planet_rotational_velocity, PMars, RMars, jeod::PlanetRNP::rnp_type, jeod::PlanetRNP::RotationOnly, and jeod::RotationMars::use_full_rnp.
operator=()
RNPMars& jeod::RNPMars::operator= (const RNPMars &) delete
timestamp()
double jeod::RNPMars::timestamp () const override virtual
Return the last time at which the RNP was updated.
Implements jeod::EphemerisInterface.
Definition at line 235 of file rnp_mars.cc.
References last_updated_time_rotational.
update_axial_rotation()
void jeod::RNPMars::update_axial_rotation (TimeTT & time_tt)
Update rotation portion of RNP and supply RNP to dynamics manager.
Parameters
[in] time_tt Current TT time
Definition at line 182 of file rnp_mars.cc.
References jeod::PlanetOrientation::active, jeod::Numerical::compare_exact(), jeod::TimeManager::dyn_time, jeod::PlanetRNP::FullRNP, get_dyn_time_ptr(), last_updated_time_rotational, never_updated_rotational, jeod::BasePlanet::pfix, jeod::PlanetOrientation::planet, jeod::PlanetRNP::rnp_type, jeod::PlanetRNP::rotation, jeod::JeodBaseTime::seconds, jeod::RefFrame::set_timestamp(), time_dyn_ptr, jeod::JeodBaseTime::time_manager, jeod::PlanetRNP::update_axial_rotation(), and jeod::PlanetRotation::update_time().
update_rnp()
void jeod::RNPMars::update_rnp (TimeTT & time_tt)
Update the complete RNP and supply it to the Dynamics Manager.
Parameters
[in] time_tt Current Terrestrial Time
Definition at line 119 of file rnp_mars.cc.
References jeod::PlanetOrientation::active, jeod::Numerical::compare_exact(), jeod::TimeManager::dyn_time, jeod::PlanetRNP::FullRNP, get_dyn_time_ptr(), last_updated_time_full, last_updated_time_rotational, never_updated_full, never_updated_rotational, jeod::PlanetRNP::nutation, jeod::BasePlanet::pfix, jeod::PlanetOrientation::planet, jeod::PlanetRNP::precession, jeod::PlanetRNP::rnp_type, jeod::PlanetRNP::rotation, jeod::JeodBaseTime::seconds, jeod::RefFrame::set_timestamp(), time_dyn_ptr, jeod::JeodBaseTime::time_manager, tt_ptr, jeod::PlanetRNP::update_rnp(), and jeod::PlanetRotation::update_time().
Friends And Related Function Documentation
init_attrjeod__RNPMars
void init_attrjeod__RNPMars () friend
InputProcessor
friend class InputProcessor friend
Definition at line 103 of file rnp_mars.hh.
Field Documentation
internal_name
std::string jeod::RNPMars::internal_name {"RNPMars"}
The hard coded internal name to be returned on calling the overridden EphemerisInterface function "get_name".
trick_units(–)
Definition at line 124 of file rnp_mars.hh.
Referenced by get_name().
last_updated_time_full
double jeod::RNPMars::last_updated_time_full {} private
The last update time for the RNP, when updated through update_rnp.
References TimeDyn.seconds. If the time from time_dyn_ptr is the same as this update time, then the RNP will not be updated; prevents unnecessary updating.trick_units(s)
Definition at line 145 of file rnp_mars.hh.
Referenced by update_rnp().
last_updated_time_rotational
double jeod::RNPMars::last_updated_time_rotational {} private
The last rotational update time, when updated through update_axial_rotation, referencing TimeDyn.seconds.
If the time from time_dyn_ptr matches this update time, then the R component of the RNP will not be updated; prevents unnecessary updating.trick_units(s)
Definition at line 159 of file rnp_mars.hh.
Referenced by timestamp(), update_axial_rotation(), and update_rnp().
never_updated_full
bool jeod::RNPMars::never_updated_full {true} private
Indicates that last_updated_time_full has never been populated, and that the update must be done regardless of given time.
trick_units(–)
Definition at line 151 of file rnp_mars.hh.
Referenced by update_rnp().
never_updated_rotational
bool jeod::RNPMars::never_updated_rotational {true} private
Indicates that last_updated_time_rotational has never been populated, and that the update must be done regardless of given time.
trick_units(–)
Definition at line 165 of file rnp_mars.hh.
Referenced by update_axial_rotation(), and update_rnp().
NMars
NutationMars jeod::RNPMars::NMars
"Pathfinder" Mars nutation model.
trick_units(–)
Definition at line 113 of file rnp_mars.hh.
Referenced by initialize(), and RNPMars().
PMars
PrecessionMars jeod::RNPMars::PMars
"Pathfinder" Mars precession model.
trick_units(–)
Definition at line 118 of file rnp_mars.hh.
Referenced by initialize(), and RNPMars().
RMars
RotationMars jeod::RNPMars::RMars
"Pathfinder" Mars rotation model.
trick_units(–)
Definition at line 108 of file rnp_mars.hh.
Referenced by initialize(), and RNPMars().
time_dyn_ptr
TimeDyn* jeod::RNPMars::time_dyn_ptr {} private
Pointer to the TimeDyn object, used to time stamp the reference frame when it is being updated.
trick_units(–)
Definition at line 137 of file rnp_mars.hh.
Referenced by get_dyn_time_ptr(), update_axial_rotation(), and update_rnp().
tt_ptr
TimeTT* jeod::RNPMars::tt_ptr {} private
Pointer to the TimeTT used to update this object when ephem_update is invoked.
trick_units(–)
Definition at line 131 of file rnp_mars.hh.
Referenced by ephem_update(), and update_rnp().
The documentation for this class was generated from the following files:
rnp_mars.hh
rnp_mars.cc