JEOD: jeod::LinePointContactPair Class Reference
jeod::LinePointContactPair Class Reference
An point to point contact pair for use in the contact model.
#include <line_point_contact_pair.hh>
Public Member Functions
LinePointContactPair ()=default
~LinePointContactPair () override=default
LinePointContactPair & operator= (const LineContactPair &)=delete
LinePointContactPair (const LineContactPair &)=delete
void in_contact () override
Determine if contact has occurred between the facets of the pair.
void initialize_pair (ContactFacet *subject_facet, ContactFacet *target_facet) override
Initialize the contact pair by setting the subject, target, and creating the relstate if possible.
Public Member Functions inherited from jeod::ContactPair
ContactPair ()=default
virtual ~ContactPair ()=default
ContactPair & operator= (const ContactPair &)=delete
ContactPair (const ContactPair &)=delete
bool in_range ()
test whether the pair is in range for interaction
bool is_active ()
Determine if contact can occur between the two facets.
bool is_complete ()
Determine if the pair has a target facet.
ContactFacet * get_subject ()
Determine if the pair has a target facet.
ContactFacet * get_target ()
Determine if the pair has a target facet.
virtual void initialize_relstate (DynManager *dyn_manager)
Initialize the relative state between the facets and register with the dynamics manager.
virtual bool check_tree ()
Make sure the two contact facets are not on the same mass tree.
Data Fields
LineContactFacet * line_subject {}
pointer to the contact facet that is the subject of the associated relative states.
PointContactFacet * point_target {}
pointer to the contact facet that is the target of the associated relative states.
Data Fields inherited from jeod::ContactPair
PairInteraction * interaction {}
Parameters that define the force calculation function between the subjec and target.
double interaction_distance {}
rel_state distance at which in_contact should be called
Friends
class InputProcessor
void init_attrjeod__LinePointContactPair ()
Additional Inherited Members
Protected Attributes inherited from jeod::ContactPair
RelativeDerivedState rel_state
Current relative state between the subject and the target in the subject frame.
ContactFacet * subject {}
pointer to the contact facet that is the subject of the associated relative states.
ContactFacet * target {}
pointer to the contact facet that is the target of the associated relative states.
Detailed Description
An point to point contact pair for use in the contact model.
Definition at line 85 of file line_point_contact_pair.hh.
Constructor & Destructor Documentation
LinePointContactPair() [1/2]
jeod::LinePointContactPair::LinePointContactPair () default
~LinePointContactPair()
jeod::LinePointContactPair::~LinePointContactPair () override default
LinePointContactPair() [2/2]
jeod::LinePointContactPair::LinePointContactPair (const LineContactPair &) delete
Member Function Documentation
in_contact()
void jeod::LinePointContactPair::in_contact () override virtual
Determine if contact has occurred between the facets of the pair.
Implements jeod::ContactPair.
Definition at line 49 of file line_point_contact_pair.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::LineContactFacet::calculate_contact_point(), jeod::PointContactFacet::calculate_contact_point(), jeod::PairInteraction::calculate_forces(), jeod::PointContactFacet::contact_point, jeod::Vector3::copy(), jeod::Vector3::cross(), jeod::Vector3::diff(), jeod::ContactUtils::dist_line_segments(), jeod::Vector3::initialize(), jeod::ContactPair::interaction, jeod::LineContactFacet::length, line_subject, jeod::Vector3::normalize(), point_target, jeod::RefFrameTrans::position, jeod::RelativeDerivedState::rel_state, jeod::ContactPair::rel_state, jeod::RefFrameState::rot, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::RefFrameTrans::velocity, and jeod::Vector3::vmag().
initialize_pair()
void jeod::LinePointContactPair::initialize_pair (ContactFacet * subject_facet, ContactFacet * target_facet) override virtual
Initialize the contact pair by setting the subject, target, and creating the relstate if possible.
Parameters
[in,out] subject_facet subject ContactFacet
[in,out] target_facet target ContactFacet
Implements jeod::ContactPair.
Definition at line 132 of file line_point_contact_pair.cc.
References jeod::InteractionFacet::base_facet, jeod::RelativeDerivedState::ComputeTargetStateinSubject, jeod::NamedItem::construct_name(), jeod::RelativeDerivedState::direction_sense, jeod::RefFrame::get_name(), line_subject, jeod::RelativeDerivedState::name, jeod::Facet::name, point_target, jeod::ContactPair::rel_state, jeod::ContactPair::subject, jeod::RelativeDerivedState::subject_frame_name, jeod::ContactPair::target, jeod::RelativeDerivedState::target_frame_name, and jeod::ContactFacet::vehicle_point.
Referenced by jeod::LineContactFacet::create_pair().
operator=()
LinePointContactPair& jeod::LinePointContactPair::operator= (const LineContactPair &) delete
Friends And Related Function Documentation
init_attrjeod__LinePointContactPair
void init_attrjeod__LinePointContactPair () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file line_point_contact_pair.hh.
Field Documentation
line_subject
LineContactFacet* jeod::LinePointContactPair::line_subject {}
pointer to the contact facet that is the subject of the associated relative states.
trick_units(–)
Definition at line 91 of file line_point_contact_pair.hh.
Referenced by in_contact(), and initialize_pair().
point_target
PointContactFacet* jeod::LinePointContactPair::point_target {}
pointer to the contact facet that is the target of the associated relative states.
trick_units(–)
Definition at line 96 of file line_point_contact_pair.hh.
Referenced by in_contact(), and initialize_pair().
The documentation for this class was generated from the following files:
line_point_contact_pair.hh
line_point_contact_pair.cc