JEOD: jeod::BasicJeodTrickSimInterface Class Reference
jeod::BasicJeodTrickSimInterface Class Reference
The BasicJeodTrickSimInterface implements the required capabilities of the generic JeodSimulationInterface in a Trick simulation environment.
#include <trick_sim_interface.hh>
Public Member Functions
BasicJeodTrickSimInterface (MessageHandler &message_handler)
Construct a BasicJeodTrickSimInterface object.
~BasicJeodTrickSimInterface () override
Destroy a BasicJeodTrickSimInterface object.
void set_checkpoint_file_name (const std::string &name)
Set the checkpoint file name.
std::string get_checkpoint_file_name () const
Get the checkpoint file name.
void set_mode (JeodSimulationInterface::Mode new_mode) override
Set the mode.
void checkpoint_allocations (void)
Dump the allocation information to the checkpoint file.
void restore_allocations (void)
Restore the allocated data per the checkpoint file.
void checkpoint_containers (void)
Dump the container objects to the checkpoint file.
void restore_containers (void)
Restore the container objects from the checkpoint file.
void open_checkpoint_file (void)
Open the checkpoint output file.
void close_checkpoint_file (void)
Close the checkpoint output file.
void open_restart_file (void)
Open the checkpoint input file.
void close_restart_file (void)
Close the checkpoint input file.
Public Member Functions inherited from jeod::JeodSimulationInterface
JeodSimulationInterface ()
Construct a JeodSimulationInterface object.
virtual ~JeodSimulationInterface ()
Destruct a JeodSimulationInterface object.
virtual void configure (const JeodSimulationInterfaceInit &config)
Configure a JeodSimulationInterface object.
Mode get_mode (void) const
Get the current mode.
Protected Member Functions
JeodIntegratorInterface * create_integrator_internal (void) override
Create an integration interface object.
double get_job_cycle_internal (void) override
Get the current job's cycle time.
JeodMemoryInterface & get_memory_interface_internal (void) override
Get the memory interface.
SectionedInputStream get_checkpoint_reader_internal (const std::string &section_id) override
Get a reader to a section of the currently open checkpoint file.
SectionedOutputStream get_checkpoint_writer_internal (const std::string &section_id) override
Get a writer to a section of the currently open checkpoint file.
Protected Attributes
MessageHandler & generic_message_handler
The global MessageHandler.
JeodTrick10MemoryInterface trick_memory_interface
The interface between JEOD and Trick's memory management schemes.
JeodMemoryManager memory_manager
The global JEOD memory manager.
std::string checkpoint_file_name
The name of the segmented checkpoint file used for the next checkpoint / restart action.
std::string section_start
String indicating the start of a checkpoint file section.
std::string section_end
String indicating the end of a checkpoint file section.
CheckPointInputManager * checkpoint_reader
The object that manages reading from a checkpoint file.
CheckPointOutputManager * checkpoint_writer
The object that manages writing to a checkpoint file.
Protected Attributes inherited from jeod::JeodSimulationInterface
Mode mode
The mode in which the simulation interface is operating.
Mode saved_mode
The mode prior to a checkpoint or restart process.
Private Member Functions
BasicJeodTrickSimInterface (const BasicJeodTrickSimInterface &)
Not implemented.
BasicJeodTrickSimInterface & operator= (const BasicJeodTrickSimInterface &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__BasicJeodTrickSimInterface ()
Additional Inherited Members
Public Types inherited from jeod::JeodSimulationInterface
enum Mode {
Construction = 0, PreCheckpoint = 1, Checkpoint = 2, PostCheckpoint = 3,
Restart = 4, Restore = 5, Initialization = 6, Operational = 7,
Shutdown = 8, Dead = 9, NumModes = 10
}
Defines the states of the JeodSimulationInterface state machine.
Static Public Member Functions inherited from jeod::JeodSimulationInterface
static JeodIntegratorInterface * create_integrator_interface (void)
Create a simulation integrator interface object.
static double get_job_cycle (void)
Get the cycle time of the currently executing job.
static std::string get_name_at_address (const void *addr, const JeodMemoryTypeDescriptor *tdesc)
Translate the given address to a symbolic name.
static void * get_address_at_name (const std::string &name)
Translate the given symbolic name to an address.
static JeodMemoryInterface & get_memory_interface (void)
Get the interface with the simulation memory model.
static SectionedInputStream get_checkpoint_reader (const std::string &section_id)
Get a reader of a section of the currently open checkpoint file.
static SectionedOutputStream get_checkpoint_writer (const std::string &section_id)
Get a writer to a section of the currently open checkpoint file.
Static Protected Attributes inherited from jeod::JeodSimulationInterface
static JeodSimulationInterface * sim_interface = nullptr
The singleton instance of a SimulationInterface object that must be created by a conforming JEOD simulation before any call can be made to one of the three static methods declared above.
Detailed Description
The BasicJeodTrickSimInterface implements the required capabilities of the generic JeodSimulationInterface in a Trick simulation environment.
By virtue of member data ownership, the class creates the requisite MessageHandler and MemoryManager and does so in the correct order.
Definition at line 89 of file trick_sim_interface.hh.
Constructor & Destructor Documentation
BasicJeodTrickSimInterface() [1/2]
jeod::BasicJeodTrickSimInterface::BasicJeodTrickSimInterface (MessageHandler & message_handler) explicit
Construct a BasicJeodTrickSimInterface object.
Parameters
[in,out] message_handler handler
Units: Message
Definition at line 62 of file trick_sim_interface.cc.
References generic_message_handler, JEOD_REGISTER_CLASS, jeod::MessageHandler::register_contents(), section_end, and section_start.
~BasicJeodTrickSimInterface()
jeod::BasicJeodTrickSimInterface::~BasicJeodTrickSimInterface (void) override
Destroy a BasicJeodTrickSimInterface object.
Definition at line 98 of file trick_sim_interface.cc.
References checkpoint_reader, and checkpoint_writer.
BasicJeodTrickSimInterface() [2/2]
jeod::BasicJeodTrickSimInterface::BasicJeodTrickSimInterface (const BasicJeodTrickSimInterface &) private
Not implemented.
Member Function Documentation
checkpoint_allocations()
void jeod::BasicJeodTrickSimInterface::checkpoint_allocations (void)
Dump the allocation information to the checkpoint file.
Definition at line 312 of file trick_sim_interface.cc.
References jeod::JeodTrick10MemoryInterface::checkpoint_allocations(), jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported(), and trick_memory_interface.
checkpoint_containers()
void jeod::BasicJeodTrickSimInterface::checkpoint_containers (void)
Dump the container objects to the checkpoint file.
Definition at line 338 of file trick_sim_interface.cc.
References jeod::JeodTrick10MemoryInterface::checkpoint_containers(), jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported(), and trick_memory_interface.
close_checkpoint_file()
void jeod::BasicJeodTrickSimInterface::close_checkpoint_file (void)
Close the checkpoint output file.
Definition at line 229 of file trick_sim_interface.cc.
References checkpoint_writer.
close_restart_file()
void jeod::BasicJeodTrickSimInterface::close_restart_file (void)
Close the checkpoint input file.
Definition at line 300 of file trick_sim_interface.cc.
References checkpoint_reader.
create_integrator_internal()
JeodIntegratorInterface * jeod::BasicJeodTrickSimInterface::create_integrator_internal (void) override protected virtual
Create an integration interface object.
Returns
Integrator interface that encapsulates an sim engine integrator.
Implements jeod::JeodSimulationInterface.
Definition at line 135 of file trick_sim_interface.cc.
References JEOD_ALLOC_CLASS_OBJECT.
get_checkpoint_file_name()
std::string jeod::BasicJeodTrickSimInterface::get_checkpoint_file_name () const inline
Get the checkpoint file name.
Definition at line 110 of file trick_sim_interface.hh.
References checkpoint_file_name.
get_checkpoint_reader_internal()
SectionedInputStream jeod::BasicJeodTrickSimInterface::get_checkpoint_reader_internal (const std::string & section_id) override protected virtual
Get a reader to a section of the currently open checkpoint file.
Returns
Checkpoint reader
Parameters
[in] section_id Section name
Implements jeod::JeodSimulationInterface.
Definition at line 281 of file trick_sim_interface.cc.
References checkpoint_reader, jeod::CheckPointInputManager::create_section_reader(), jeod::MessageHandler::error(), and jeod::SimInterfaceMessages::phasing_error.
get_checkpoint_writer_internal()
SectionedOutputStream jeod::BasicJeodTrickSimInterface::get_checkpoint_writer_internal (const std::string & section_id) override protected virtual
Get a writer to a section of the currently open checkpoint file.
Returns
Checkpoint writer
Parameters
[in] section_id Section name
Implements jeod::JeodSimulationInterface.
Definition at line 210 of file trick_sim_interface.cc.
References checkpoint_writer, jeod::CheckPointOutputManager::create_section_writer(), jeod::MessageHandler::error(), and jeod::SimInterfaceMessages::phasing_error.
get_job_cycle_internal()
double jeod::BasicJeodTrickSimInterface::get_job_cycle_internal (void) override protected virtual
Get the current job's cycle time.
Returns
Current job's cycle time
Units: s
Implements jeod::JeodSimulationInterface.
Definition at line 147 of file trick_sim_interface.cc.
get_memory_interface_internal()
JeodMemoryInterface & jeod::BasicJeodTrickSimInterface::get_memory_interface_internal (void) override protected virtual
Get the memory interface.
Returns
Memory interface
Implements jeod::JeodSimulationInterface.
Definition at line 159 of file trick_sim_interface.cc.
References trick_memory_interface.
open_checkpoint_file()
void jeod::BasicJeodTrickSimInterface::open_checkpoint_file (void)
Open the checkpoint output file.
Definition at line 170 of file trick_sim_interface.cc.
References checkpoint_file_name, checkpoint_writer, jeod::JeodTrick10MemoryInterface::get_trick_checkpoint_file(), jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported(), section_end, section_start, and trick_memory_interface.
open_restart_file()
void jeod::BasicJeodTrickSimInterface::open_restart_file (void)
Open the checkpoint input file.
Definition at line 241 of file trick_sim_interface.cc.
References checkpoint_file_name, checkpoint_reader, jeod::JeodTrick10MemoryInterface::get_trick_checkpoint_file(), jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported(), section_end, section_start, and trick_memory_interface.
operator=()
BasicJeodTrickSimInterface& jeod::BasicJeodTrickSimInterface::operator= (const BasicJeodTrickSimInterface &) private
Not implemented.
restore_allocations()
void jeod::BasicJeodTrickSimInterface::restore_allocations (void)
Restore the allocated data per the checkpoint file.
Definition at line 325 of file trick_sim_interface.cc.
References jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported(), memory_manager, jeod::JeodTrick10MemoryInterface::restore_allocations(), and trick_memory_interface.
restore_containers()
void jeod::BasicJeodTrickSimInterface::restore_containers (void)
Restore the container objects from the checkpoint file.
Definition at line 351 of file trick_sim_interface.cc.
References jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported(), jeod::JeodTrick10MemoryInterface::restore_containers(), and trick_memory_interface.
set_checkpoint_file_name()
void jeod::BasicJeodTrickSimInterface::set_checkpoint_file_name (const std::string & name) inline
Set the checkpoint file name.
Definition at line 104 of file trick_sim_interface.hh.
References checkpoint_file_name.
set_mode()
void jeod::BasicJeodTrickSimInterface::set_mode (JeodSimulationInterface::Mode new_mode) override virtual
Set the mode.
Assumptions and Limitations
See SimulationInterface::set_mode.
Parameters
[in] new_mode New mode.
Reimplemented from jeod::JeodSimulationInterface.
Definition at line 116 of file trick_sim_interface.cc.
References jeod::JeodSimulationInterface::get_mode(), memory_manager, jeod::JeodTrickMemoryInterface::set_mode(), jeod::JeodSimulationInterface::set_mode(), jeod::JeodMemoryManager::set_mode(), and trick_memory_interface.
Friends And Related Function Documentation
init_attrjeod__BasicJeodTrickSimInterface
void init_attrjeod__BasicJeodTrickSimInterface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file trick_sim_interface.hh.
Field Documentation
checkpoint_file_name
std::string jeod::BasicJeodTrickSimInterface::checkpoint_file_name protected
The name of the segmented checkpoint file used for the next checkpoint / restart action.
If the name is the empty string (default), the checkpoint / restart mechanisms will attempt to construct a name from the corresponding Trick checkpoint file name.trick_units(–)
Definition at line 200 of file trick_sim_interface.hh.
Referenced by get_checkpoint_file_name(), open_checkpoint_file(), open_restart_file(), and set_checkpoint_file_name().
checkpoint_reader
CheckPointInputManager* jeod::BasicJeodTrickSimInterface::checkpoint_reader protected
The object that manages reading from a checkpoint file.
trick_io(**)
Definition at line 215 of file trick_sim_interface.hh.
Referenced by close_restart_file(), get_checkpoint_reader_internal(), open_restart_file(), and ~BasicJeodTrickSimInterface().
checkpoint_writer
CheckPointOutputManager* jeod::BasicJeodTrickSimInterface::checkpoint_writer protected
The object that manages writing to a checkpoint file.
trick_io(**)
Definition at line 220 of file trick_sim_interface.hh.
Referenced by close_checkpoint_file(), get_checkpoint_writer_internal(), open_checkpoint_file(), and ~BasicJeodTrickSimInterface().
generic_message_handler
MessageHandler& jeod::BasicJeodTrickSimInterface::generic_message_handler protected
The global MessageHandler.
trick_units(–)
Definition at line 181 of file trick_sim_interface.hh.
Referenced by BasicJeodTrickSimInterface().
memory_manager
JeodMemoryManager jeod::BasicJeodTrickSimInterface::memory_manager protected
The global JEOD memory manager.
trick_units(–)
Definition at line 191 of file trick_sim_interface.hh.
Referenced by restore_allocations(), and set_mode().
section_end
std::string jeod::BasicJeodTrickSimInterface::section_end protected
String indicating the end of a checkpoint file section.
trick_io(*o) trick_units(–)
Definition at line 210 of file trick_sim_interface.hh.
Referenced by BasicJeodTrickSimInterface(), open_checkpoint_file(), and open_restart_file().
section_start
std::string jeod::BasicJeodTrickSimInterface::section_start protected
String indicating the start of a checkpoint file section.
trick_io(*o) trick_units(–)
Definition at line 205 of file trick_sim_interface.hh.
Referenced by BasicJeodTrickSimInterface(), open_checkpoint_file(), and open_restart_file().
trick_memory_interface
JeodTrick10MemoryInterface jeod::BasicJeodTrickSimInterface::trick_memory_interface protected
The interface between JEOD and Trick's memory management schemes.
trick_units(–)
Definition at line 186 of file trick_sim_interface.hh.
Referenced by checkpoint_allocations(), checkpoint_containers(), get_memory_interface_internal(), open_checkpoint_file(), open_restart_file(), restore_allocations(), restore_containers(), and set_mode().
The documentation for this class was generated from the following files:
trick_sim_interface.hh
trick_sim_interface.cc