JEOD: jeod::DynBodyInitLvlhState Class Reference
jeod::DynBodyInitLvlhState Class Reference
Initialize selected aspects of a vehicle's state with respect to some vehicle's LVLH frame.
#include <dyn_body_init_lvlh_state.hh>
Public Member Functions
DynBodyInitLvlhState ()
DynBodyInitLvlhState default constructor.
~DynBodyInitLvlhState () override=default
DynBodyInitLvlhState (const DynBodyInitLvlhState &)=delete
DynBodyInitLvlhState & operator= (const DynBodyInitLvlhState &)=delete
void set_lvlh_frame_object (LvlhFrame &lvh_frame_object)
Cache a pointer to a user-supplied LvlhFrame object.
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
void apply (DynManager &dyn_manager) override
Apply the initializer: Construct the reference LVLH frame so the parent initializer can compute the vehicle's state relative to the vehicle's inertial frame.
Public Member Functions inherited from jeod::DynBodyInitPlanetDerived
DynBodyInitPlanetDerived ()=default
~DynBodyInitPlanetDerived () override=default
DynBodyInitPlanetDerived (const DynBodyInitPlanetDerived &)=delete
DynBodyInitPlanetDerived & operator= (const DynBodyInitPlanetDerived &)=delete
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
bool is_ready () override
Indicate whether the initializer is ready to run.
void apply (DynManager &dyn_manager) override
Apply the initializer: This is just a pass through.
Public Member Functions inherited from jeod::DynBodyInitWrtPlanet
DynBodyInitWrtPlanet ()=default
~DynBodyInitWrtPlanet () override=default
DynBodyInitWrtPlanet (const DynBodyInitWrtPlanet &)=delete
DynBodyInitWrtPlanet & operator= (const DynBodyInitWrtPlanet &)=delete
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
RefFrameItems::Items initializes_what () override
Indicate what parts of the vehicle state this object initializes.
bool is_ready () override
Indicate whether the initializer is ready to run.
void apply (DynManager &dyn_manager) override
Apply the initializer.
Public Member Functions inherited from jeod::DynBodyInit
DynBodyInit ()=default
~DynBodyInit () override=default
DynBodyInit (const DynBodyInit &)=delete
DynBodyInit & operator= (const DynBodyInit &)=delete
virtual void report_failure ()
Report on an initializer that could not be processed.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
Data Fields
LvlhType::Type lvlh_type {LvlhType::Rectilinear}
Indicates type of LVLH coordinates desired.
Data Fields inherited from jeod::DynBodyInitPlanetDerived
std::string ref_body_name {""}
The name of the vehicle whose composite body frame is used to build the derived state with respect to which the vehicle initialization data are referenced.
Data Fields inherited from jeod::DynBodyInitWrtPlanet
std::string planet_name {""}
The name of the planet about which the reference body's LVLH frame is to be computed.
RefFrameItems::Items set_items {RefFrameItems::Pos_Vel_Att_Rate}
The state elements to be set by this initializer.
Data Fields inherited from jeod::DynBodyInit
std::string body_frame_id {""}
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
std::string reference_ref_frame_name {""}
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
RefFrameState state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
double position [3] {}
Relative position between the subject and reference reference frame origins.
double velocity [3] {}
Relative velocity between the subject and reference reference frame origins.
Orientation orientation
Relative orientation between the subject and reference reference frame axes.
double ang_velocity [3] {}
Relative angular velocity between the subject and reference axes.
bool reverse_sense {}
Indicates how the user input state items are to be interpreted.
bool rate_in_parent {}
Indicates how the user input angular velocity is to be interpreted.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Private Attributes
LvlhFrame * lvlh_object_ptr {}
A pointer to an LvlhFrame which can be supplied by the user.
Friends
class InputProcessor
void init_attrjeod__DynBodyInitLvlhState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyInit
void apply_user_inputs ()
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
void compute_rotational_state ()
This method is obsolete.
void compute_translational_state ()
This method is obsolete.
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
DynBody * find_dyn_body (const DynManager &dyn_manager, const std::string &dyn_body_name, const std::string &variable_name)
Find the DynBody with the given name, failing if not found.
RefFrame * find_ref_frame (const DynManager &dyn_manager, const std::string &ref_frame_name, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
BodyRefFrame * find_body_frame (DynBody &frame_container, const std::string &body_frame_identifier, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::DynBodyInitPlanetDerived
DynBody * ref_body {}
The vehicle corresponding to the ref_body_name.
RefFrameItems::Items required_items {RefFrameItems::Pos_Vel_Att_Rate}
The state elements in the reference body's composite body frame that must be set before this initializer can proceed.
bool body_is_required {true}
If true (default), the ref_body cannot be NULL.
Protected Attributes inherited from jeod::DynBodyInitWrtPlanet
Planet * planet {}
The planet corresponding to the planet_name.
Protected Attributes inherited from jeod::DynBodyInit
BodyRefFrame * body_ref_frame {}
The reference frame whose name is vehicle_name.body_frame_id.
RefFrame * reference_ref_frame {}
The reference frame whose name is reference_ref_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Initialize selected aspects of a vehicle's state with respect to some vehicle's LVLH frame.
Definition at line 84 of file dyn_body_init_lvlh_state.hh.
Constructor & Destructor Documentation
DynBodyInitLvlhState() [1/2]
jeod::DynBodyInitLvlhState::DynBodyInitLvlhState ()
DynBodyInitLvlhState default constructor.
Definition at line 47 of file dyn_body_init_lvlh_state.cc.
References jeod::RefFrameItems::Pos_Vel, and jeod::DynBodyInitPlanetDerived::required_items.
~DynBodyInitLvlhState()
jeod::DynBodyInitLvlhState::~DynBodyInitLvlhState () override default
DynBodyInitLvlhState() [2/2]
jeod::DynBodyInitLvlhState::DynBodyInitLvlhState (const DynBodyInitLvlhState &) delete
Member Function Documentation
apply()
void jeod::DynBodyInitLvlhState::apply (DynManager & dyn_manager) override virtual
Apply the initializer: Construct the reference LVLH frame so the parent initializer can compute the vehicle's state relative to the vehicle's inertial frame.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 88 of file dyn_body_init_lvlh_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::DynBodyInit::ang_velocity, jeod::DynBodyInitPlanetDerived::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::LvlhType::CircularCurvilinear, jeod::DynBody::composite_body, jeod::RefFrameRot::compute_ang_vel_products(), jeod::Orientation::compute_eigen_rotation_from_matrix(), jeod::Orientation::compute_euler_angles_from_matrix(), jeod::RefFrameRot::compute_quaternion(), jeod::Orientation::compute_transform(), jeod::RelativeDerivedState::ComputeSubjectStateinTarget, jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::RelativeDerivedState::direction_sense, jeod::Orientation::eigen_angle, jeod::Orientation::eigen_axis, jeod::LvlhType::EllipticalCurvilinear, jeod::Orientation::euler_angles, jeod::Orientation::euler_sequence, jeod::MessageHandler::fail(), jeod::LvlhFrame::frame, jeod::BodyActionMessages::illegal_value, jeod::LvlhFrame::initialize(), lvlh_object_ptr, lvlh_type, jeod::Orientation::NoSequence, jeod::DynBodyInit::orientation, jeod::DynBodyInitWrtPlanet::planet, jeod::RefFrameTrans::position, jeod::DynBodyInit::position, jeod::RefFrameRot::Q_parent_this, jeod::Orientation::quat, jeod::LvlhType::Rectilinear, jeod::DynBodyInitPlanetDerived::ref_body, jeod::DynBodyInit::reference_ref_frame, jeod::RelativeDerivedState::rel_state, jeod::Orientation::Roll_Pitch_Yaw, jeod::RefFrameState::rot, jeod::LvlhFrame::set_planet(), jeod::LvlhFrame::set_subject_frame(), jeod::RelativeDerivedState::set_target_frame(), jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Orientation::trans, jeod::LvlhFrame::update(), jeod::RefFrameTrans::velocity, and jeod::DynBodyInit::velocity.
initialize()
void jeod::DynBodyInitLvlhState::initialize (DynManager & dyn_manager) override virtual
Initialize the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Reimplemented in jeod::DynBodyInitLvlhTransState.
Definition at line 65 of file dyn_body_init_lvlh_state.cc.
References jeod::DynBodyInitPlanetDerived::body_is_required, jeod::DynBodyInitPlanetDerived::initialize(), and lvlh_object_ptr.
Referenced by jeod::DynBodyInitLvlhRotState::initialize(), and jeod::DynBodyInitLvlhTransState::initialize().
operator=()
DynBodyInitLvlhState& jeod::DynBodyInitLvlhState::operator= (const DynBodyInitLvlhState &) delete
set_lvlh_frame_object()
void jeod::DynBodyInitLvlhState::set_lvlh_frame_object (LvlhFrame & lvlh_frame_object)
Cache a pointer to a user-supplied LvlhFrame object.
Parameters
[in] lvlh_frame_object LVLH frame object
Definition at line 56 of file dyn_body_init_lvlh_state.cc.
References lvlh_object_ptr.
Friends And Related Function Documentation
init_attrjeod__DynBodyInitLvlhState
void init_attrjeod__DynBodyInitLvlhState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file dyn_body_init_lvlh_state.hh.
Field Documentation
lvlh_object_ptr
LvlhFrame* jeod::DynBodyInitLvlhState::lvlh_object_ptr {} private
A pointer to an LvlhFrame which can be supplied by the user.
trick_units(–)
Definition at line 98 of file dyn_body_init_lvlh_state.hh.
Referenced by apply(), initialize(), and set_lvlh_frame_object().
lvlh_type
LvlhType::Type jeod::DynBodyInitLvlhState::lvlh_type {LvlhType::Rectilinear}
Indicates type of LVLH coordinates desired.
Default is rectilinear.trick_units(–)
Definition at line 92 of file dyn_body_init_lvlh_state.hh.
Referenced by apply().
The documentation for this class was generated from the following files:
dyn_body_init_lvlh_state.hh
dyn_body_init_lvlh_state.cc