JEOD: jeod::JeodMemoryTable< ValueType > Class Template Reference
jeod::JeodMemoryTable< ValueType > Class Template Reference abstract
A JeodMemoryTable maps strings to values with a coordinated map/vector pair.
#include <memory_table.hh>
Public Types
typedef std::map< const std::string, unsigned int > NameIndex
Maps strings to an index number.
typedef std::vector< const ValueType * > ValueList
Maps index numbers to key values.
typedef ValueList::const_iterator const_value_iterator
Const iterator over values.
Public Member Functions
JeodMemoryTable ()
Default constructor.
virtual ~JeodMemoryTable ()
Destructor.
unsigned int find (const std::string &key) const
Find the index number at which key/value pair is stored in the table.
const_value_iterator begin (void) const
Returns a const iterator that points to the first element of the list.
const_value_iterator end (void) const
Returns a const iterator that points past the last element of the list.
unsigned int add (const std::string &key, const ValueType &val)
Add a key/value pair to the table.
void del (const std::string &key)
Delete the key and associated data from the table.
const ValueType * get (unsigned int idx) const
Retrieve the value for the specified index from the list.
Protected Member Functions
virtual const ValueType * clone (const ValueType &value) const =0
(Somehow) clone the input value.
Private Member Functions
JeodMemoryTable (const JeodMemoryTable &)
Not implemented.
JeodMemoryTable & operator= (const JeodMemoryTable &)
Not implemented.
Private Attributes
NameIndex string_to_index
Maps keys to indices in the value_list.
ValueList value_list
Vector of values.
Detailed Description
template<typename ValueType>
class jeod::JeodMemoryTable< ValueType >
A JeodMemoryTable maps strings to values with a coordinated map/vector pair.
Template Parameters
ValueType The underlying type of the values maintained in the table. The stored values are pointers to this underlying type.
A JeodMemoryTable contains two data members: a std::map and a std::vector. The map data member maps keys to integers. The integer mapped by a key is the index into the vector where the value associated with the key is stored.
So why not just use a map? The reason is that storing an integer requires less memory than storing a string or a pointer to a string, particularly on 64 bit machines. In the application at hand, keeping track of memory allocations, the number of data types is relatively small compared to the to the number of allocated chunks of data. The extra overhead of maintaining a map and a vector is small compared to the savings that results from storing thousands of integers rather than pointers or strings.
Principal Operations
add()
Returns the integer value associated with a key in the table's map. In the case of a new key/value pair, a new key/vector size entry is added to the map and the value is added to the end of the vector. Note well: The value is ignored when the key is already in the map.
del()
Deletes the key from the table's map and deletes the cloned value at the corresponding index. The vector itself is modified (truncated) only in the special case of deleting the last-added entry. This ensures that stored indices will remain valid.
get()
Returns the value in the table's vector at the specified index.
Assumptions and Limitations
The value is ignored for duplicate key entries. The underlying assumption is that all of the values for those duplicate entries are somehow equal to one another.
As-is, the table is not thread-safe. Calls to add() and get() made in a multi-threaded environment should be protected by a mutex. This protection is the responsibility of the (programmatic) users.
JEOD reserves index 0 for internal use. Valid indices are positive.
The del() method should be used only if the (programmatic) user knows that no other references to the to-be-deleted entry exist.
Definition at line 124 of file memory_table.hh.
Member Typedef Documentation
const_value_iterator
template<typename ValueType> typedef ValueList::const_iterator jeod::JeodMemoryTable< ValueType >::const_value_iterator
Const iterator over values.
Definition at line 142 of file memory_table.hh.
NameIndex
template<typename ValueType> typedef std::map<const std::string, unsigned int> jeod::JeodMemoryTable< ValueType >::NameIndex
Maps strings to an index number.
Definition at line 132 of file memory_table.hh.
ValueList
template<typename ValueType> typedef std::vector<const ValueType *> jeod::JeodMemoryTable< ValueType >::ValueList
Maps index numbers to key values.
Definition at line 137 of file memory_table.hh.
Constructor & Destructor Documentation
JeodMemoryTable() [1/2]
template<typename ValueType> jeod::JeodMemoryTable< ValueType >::JeodMemoryTable () inline
Default constructor.
Note that JEOD reserves table index 0 as meaning nothing.
Definition at line 153 of file memory_table.hh.
~JeodMemoryTable()
template<typename ValueType> virtual jeod::JeodMemoryTable< ValueType >::~JeodMemoryTable () inline virtual
Destructor.
The contents of the vector are clones created by add() and hence must be deleted to avoid a leak.
Definition at line 167 of file memory_table.hh.
JeodMemoryTable() [2/2]
template<typename ValueType> jeod::JeodMemoryTable< ValueType >::JeodMemoryTable (const JeodMemoryTable< ValueType > &) explicit private
Not implemented.
Member Function Documentation
add()
template<typename ValueType> unsigned int jeod::JeodMemoryTable< ValueType >::add (const std::string & key, const ValueType & val) inline
Add a key/value pair to the table.
Returns
Index number mapped by the key
Parameters
[in] key Key
[in] val Value
Definition at line 248 of file memory_table.hh.
Referenced by jeod::JeodMemoryReflectiveTable::add(), jeod::JeodMemoryManager::get_type_entry_atomic(), and jeod::JeodMemoryManager::get_type_index_nolock().
begin()
template<typename ValueType> const_value_iterator jeod::JeodMemoryTable< ValueType >::begin (void) const inline
Returns a const iterator that points to the first element of the list.
Definition at line 227 of file memory_table.hh.
Referenced by jeod::JeodMemoryManager::get_type_entry_atomic().
clone()
template<typename ValueType> virtual const ValueType* jeod::JeodMemoryTable< ValueType >::clone (const ValueType & value) const protected pure virtual
(Somehow) clone the input value.
Returns
Clone of input value.
Parameters
[in] value Value to be cloned.
Implemented in jeod::JeodMemoryTableCopyable< ValueType >, jeod::JeodMemoryTableCopyable< std::string >, jeod::JeodMemoryTableClonable< ValueType >, and jeod::JeodMemoryTableClonable< JeodMemoryTypeDescriptor >.
Referenced by jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::add().
del()
template<typename ValueType> void jeod::JeodMemoryTable< ValueType >::del (const std::string & key) inline
Delete the key and associated data from the table.
Use with care.
Parameters
[in] key Key
Exceptions
std::invalid_argument on attempting to delete an element that is not in the table.
Definition at line 277 of file memory_table.hh.
end()
template<typename ValueType> const_value_iterator jeod::JeodMemoryTable< ValueType >::end (void) const inline
Returns a const iterator that points past the last element of the list.
Definition at line 236 of file memory_table.hh.
Referenced by jeod::JeodMemoryManager::get_type_entry_atomic().
find()
template<typename ValueType> unsigned int jeod::JeodMemoryTable< ValueType >::find (const std::string & key) const inline
Find the index number at which key/value pair is stored in the table.
Returns
Index number mapped by the key
Parameters
[in] key Key
Definition at line 202 of file memory_table.hh.
Referenced by jeod::JeodMemoryManager::get_type_descriptor_atomic(), jeod::JeodMemoryManager::get_type_entry_atomic(), and jeod::JeodMemoryManager::get_type_index_nolock().
get()
template<typename ValueType> const ValueType* jeod::JeodMemoryTable< ValueType >::get (unsigned int idx) const inline
Retrieve the value for the specified index from the list.
Returns
Value for specified index.
Parameters
[in] idx Table index whose value is to be retrieved.
Exceptions
std::out_of_range for an index of zero or for an index beyond the range of the vector.
std::invalid_argument when the index is in range but the value is null. This only happens when the item in question has previously been deleted.
Definition at line 313 of file memory_table.hh.
Referenced by jeod::JeodMemoryManager::generate_shutdown_report(), jeod::JeodMemoryManager::get_string_atomic(), jeod::JeodMemoryManager::get_type_descriptor_atomic(), jeod::JeodMemoryManager::get_type_descriptor_nolock(), and jeod::JeodMemoryManager::get_type_entry_atomic().
operator=()
template<typename ValueType> JeodMemoryTable& jeod::JeodMemoryTable< ValueType >::operator= (const JeodMemoryTable< ValueType > &) private
Not implemented.
Field Documentation
string_to_index
template<typename ValueType> NameIndex jeod::JeodMemoryTable< ValueType >::string_to_index private
Maps keys to indices in the value_list.
trick_io(**)
Definition at line 348 of file memory_table.hh.
Referenced by jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::add(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::del(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::find(), and jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::~JeodMemoryTable().
value_list
template<typename ValueType> ValueList jeod::JeodMemoryTable< ValueType >::value_list private
Vector of values.
trick_io(**)
Definition at line 353 of file memory_table.hh.
Referenced by jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::add(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::begin(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::del(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::end(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::get(), jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::JeodMemoryTable(), and jeod::JeodMemoryTable< JeodMemoryTypeDescriptor >::~JeodMemoryTable().
The documentation for this class was generated from the following file:
memory_table.hh