JEOD: jeod::JeodPointerContainer< ContainerType, ElemType > Class Template Reference
jeod::JeodPointerContainer< ContainerType, ElemType > Class Template Reference
A JeodPointerContainer is a JeodContainer that contains pointers to objects of type ElemType.
#include <pointer_container.hh>
Public Member Functions
JeodPointerContainer (void)
Construct a JeodPointerContainer.
JeodPointerContainer (const JeodPointerContainer &source)
Copy-construct a JeodPointerContainer.
JeodPointerContainer (const typename ContainerType::stl_container_type &source)
Copy-construct a JeodPointerContainer.
JeodPointerContainer & operator= (const JeodPointerContainer &source)
Copy from a JeodPointerContainer.
JeodPointerContainer & operator= (const typename ContainerType::stl_container_type &source)
Copy from an STL container.
virtual ~JeodPointerContainer (void)
Destruct a JeodPointerContainer.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
const std::string get_item_value (void) override
Return the value of the item to be written to the checkpoint file.
void perform_insert_action (const std::string &value) override
Interpret the provided value and add it to the list.
Public Member Functions inherited from jeod::JeodContainer< ContainerType, ElemType *>
JeodContainer (void)
Default constructor.
JeodContainer (const this_container_type &source)
Copy constructor.
JeodContainer (const stl_container_type &source)
Copy constructor.
JeodContainer & operator= (const this_container_type &source)
Assignment operator.
JeodContainer & operator= (const stl_container_type &source)
Assignment operator.
~JeodContainer (void) override
Destructor.
void swap_contents (this_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
void swap_contents (stl_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
virtual void perform_cleanup_action (const std::string &value)
Cleanup detritus created during the restore process.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
void start_checkpoint (void) override
Prepare to checkpoint the object.
void advance_checkpoint (void) override
Advance to the next item to be checkpointed.
bool is_checkpoint_finished (void) override
Indicate whether the checkpoint dump of this object is finished.
const std::string get_init_name (void) override
Names the action to be performed prior to performing any of the restore actions.
const std::string get_item_name (void) override
Return the name of the action to be printed along with the current value.
const std::string get_final_name (void) override
Names the action to be performed after to performing any of the restore actions.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
Protected Attributes
const JeodMemoryTypeDescriptor * base_type_descriptor
Memory model descriptor of the type of data stored in the container.
Protected Attributes inherited from jeod::JeodContainer< ContainerType, ElemType *>
ContainerType::iterator checkpoint_iter
Iterator for walking through the container during checkpoint.
const JeodMemoryTypeDescriptor * elem_type_descriptor
Memory model descriptor of the type of data stored in the container.
Additional Inherited Members
Public Types inherited from jeod::JeodContainer< ContainerType, ElemType *>
typedef JeodContainer< ContainerType, ElemType * > this_container_type
This particular JeodContainer type.
typedef ContainerType::stl_container_type stl_container_type
Import the ContainerType's container type.
Detailed Description
template<typename ContainerType, typename ElemType>
class jeod::JeodPointerContainer< ContainerType, ElemType >
A JeodPointerContainer is a JeodContainer that contains pointers to objects of type ElemType.
Definition at line 81 of file pointer_container.hh.
Constructor & Destructor Documentation
JeodPointerContainer() [1/3]
template<typename ContainerType , typename ElemType > jeod::JeodPointerContainer< ContainerType, ElemType >::JeodPointerContainer (void) inline
Construct a JeodPointerContainer.
Definition at line 87 of file pointer_container.hh.
JeodPointerContainer() [2/3]
template<typename ContainerType , typename ElemType > jeod::JeodPointerContainer< ContainerType, ElemType >::JeodPointerContainer (const JeodPointerContainer< ContainerType, ElemType > & source) inline
Copy-construct a JeodPointerContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Pointer container to be copied.
Definition at line 99 of file pointer_container.hh.
JeodPointerContainer() [3/3]
template<typename ContainerType , typename ElemType > jeod::JeodPointerContainer< ContainerType, ElemType >::JeodPointerContainer (const typename ContainerType::stl_container_type & source) inline explicit
Copy-construct a JeodPointerContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Pointer container to be copied.
Definition at line 111 of file pointer_container.hh.
~JeodPointerContainer()
template<typename ContainerType , typename ElemType > virtual jeod::JeodPointerContainer< ContainerType, ElemType >::~JeodPointerContainer (void) inline virtual
Destruct a JeodPointerContainer.
Definition at line 147 of file pointer_container.hh.
Member Function Documentation
get_item_value()
template<typename ContainerType , typename ElemType > const std::string jeod::JeodPointerContainer< ContainerType, ElemType >::get_item_value (void) inline override virtual
Return the value of the item to be written to the checkpoint file.
For a JeodPointerContainer, the value names the pointed-to object.
Implements jeod::JeodCheckpointable.
Definition at line 175 of file pointer_container.hh.
References jeod::JeodPointerContainer< ContainerType, ElemType >::base_type_descriptor, jeod::JeodContainer< ContainerType, ElemType *>::checkpoint_iter, and jeod::JeodSimulationInterface::get_name_at_address().
initialize_checkpointable()
template<typename ContainerType , typename ElemType > void jeod::JeodPointerContainer< ContainerType, ElemType >::initialize_checkpointable (const void * container, const std::type_info & container_type, const std::string & elem_name) inline override virtual
Initialize a checkpointable object, called by the checkpoint manager.
In the case of a JeodPointerContainer, this method gets the descriptor for the type of data pointed to members of the container.
Reimplemented from jeod::JeodCheckpointable.
Definition at line 155 of file pointer_container.hh.
References jeod::JeodPointerContainer< ContainerType, ElemType >::base_type_descriptor, jeod::JeodMemoryManager::get_type_descriptor(), and jeod::JeodContainer< ContainerType, ElemType >::initialize_checkpointable().
operator=() [1/2]
template<typename ContainerType , typename ElemType > JeodPointerContainer& jeod::JeodPointerContainer< ContainerType, ElemType >::operator= (const JeodPointerContainer< ContainerType, ElemType > & source) inline
Copy from a JeodPointerContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Pointer container to be copied.
Definition at line 125 of file pointer_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::operator=().
operator=() [2/2]
template<typename ContainerType , typename ElemType > JeodPointerContainer& jeod::JeodPointerContainer< ContainerType, ElemType >::operator= (const typename ContainerType::stl_container_type & source) inline
Copy from an STL container.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Pointer container to be copied.
Definition at line 138 of file pointer_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::operator=().
perform_insert_action()
template<typename ContainerType , typename ElemType > void jeod::JeodPointerContainer< ContainerType, ElemType >::perform_insert_action (const std::string & value) inline override virtual
Interpret the provided value and add it to the list.
For a JeodPointerContainer, the value should specify (in string form) the address of some object in active memory.
Implements jeod::JeodContainer< ContainerType, ElemType *>.
Definition at line 189 of file pointer_container.hh.
References jeod::JeodSimulationInterface::get_address_at_name().
Field Documentation
base_type_descriptor
template<typename ContainerType , typename ElemType > const JeodMemoryTypeDescriptor* jeod::JeodPointerContainer< ContainerType, ElemType >::base_type_descriptor protected
Memory model descriptor of the type of data stored in the container.
trick_io(**)
Definition at line 205 of file pointer_container.hh.
Referenced by jeod::JeodPointerContainer< ContainerType, ElemType >::get_item_value(), and jeod::JeodPointerContainer< ContainerType, ElemType >::initialize_checkpointable().
The documentation for this class was generated from the following file:
pointer_container.hh