JEOD: jeod::BodyWrenchCollect Class Reference
jeod::BodyWrenchCollect Class Reference
Serves as the collection point for wrenches that act on a vehicle.
#include <body_wrench_collect.hh>
Public Member Functions
BodyWrenchCollect ()
Default constructor.
~BodyWrenchCollect ()
Destructor.
BodyWrenchCollect (const BodyWrenchCollect &)=delete
BodyWrenchCollect & operator= (const BodyWrenchCollect &)=delete
Wrench & accumulate (Wrench &sum) const
Accumulate the collected wrenches.
Wrench & accumulate (const double point[3], Wrench &sum) const
Accumulate the collected wrenches.
Data Fields
JeodPointerVector< Wrench >::type collect_wrench
Vector of effector wrenches.
Detailed Description
Serves as the collection point for wrenches that act on a vehicle.
This is a simple class that is tightly coupled with the StructureIntegratedDynBody class. This latter class contains (has-a) a BodyWrenchCollect data member.
The Trick vcollect mechanism (or a similar mechanism in a non-Trick sim) pushes pointers to the individual wrenches onto the various collection member of a BodyWrenchCollect. StructureIntegratedDynBody members cumulate these collected wrenches to form the total wrench acting on the vehicle.
Definition at line 80 of file body_wrench_collect.hh.
Constructor & Destructor Documentation
BodyWrenchCollect() [1/2]
jeod::BodyWrenchCollect::BodyWrenchCollect ()
Default constructor.
Definition at line 26 of file body_wrench_collect.cc.
References collect_wrench, JEOD_REGISTER_CHECKPOINTABLE, and JEOD_REGISTER_CLASS.
~BodyWrenchCollect()
jeod::BodyWrenchCollect::~BodyWrenchCollect ()
Destructor.
Definition at line 35 of file body_wrench_collect.cc.
References collect_wrench, and JEOD_DEREGISTER_CHECKPOINTABLE.
BodyWrenchCollect() [2/2]
jeod::BodyWrenchCollect::BodyWrenchCollect (const BodyWrenchCollect &) delete
Member Function Documentation
accumulate() [1/2]
Wrench& jeod::BodyWrenchCollect::accumulate (Wrench & sum) const inline
Accumulate the collected wrenches.
Parameters
sum Wrench into which the accumulated sum is to be placed. The summation is about sum.point.
Returns
Reference to the input wrench.
Definition at line 131 of file body_wrench_collect.hh.
References jeod::Wrench::accumulate(), and collect_wrench.
Referenced by accumulate(), and jeod::StructureIntegratedDynBody::collect_local_forces_and_torques().
accumulate() [2/2]
Wrench& jeod::BodyWrenchCollect::accumulate (const double point[3], Wrench & sum) const inline
Accumulate the collected wrenches.
Parameters
point Point about which summation is to be performed.
sum Wrench into which the accumulated sum is to be placed.
Returns
Reference to the input wrench.
Definition at line 143 of file body_wrench_collect.hh.
References accumulate(), and jeod::Wrench::set_point().
operator=()
BodyWrenchCollect& jeod::BodyWrenchCollect::operator= (const BodyWrenchCollect &) delete
Field Documentation
collect_wrench
JeodPointerVector<Wrench>::type jeod::BodyWrenchCollect::collect_wrench
Vector of effector wrenches.
The effector wrenches are collected into the vector at the S_define level via & vcollect containing_body.effector_wrench_collection.collect_wrench { pointer_to_wrench1, ... pointer_to_wrench_n };
The vector of collected wrenches are processed by the containing body's collect_forces_and_torques member function.trick_io(**)
Definition at line 100 of file body_wrench_collect.hh.
Referenced by accumulate(), BodyWrenchCollect(), and ~BodyWrenchCollect().
The documentation for this class was generated from the following files:
body_wrench_collect.hh
body_wrench_collect.cc