JEOD: jeod::TimeConverter_Dyn_TDB Class Reference
jeod::TimeConverter_Dyn_TDB Class Reference
Define class TimeConverter_Dyn_TDB, which converts from simulation dynamic time to Barycentric Dynamic Time.
#include <time_converter_dyn_tdb.hh>
Public Member Functions
TimeConverter_Dyn_TDB ()
Construct a TimeConverter_Dyn_TDB.
~TimeConverter_Dyn_TDB () override
Destroy a TimeConverter_Dyn_TDB.
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void convert_a_to_b (void) override
Convert from TimeDyn to TimeTDB.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()
Destroy a TimeConverter.
virtual bool is_initialized (void)
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void convert_b_to_a (void)
Default converter from time 'b' to time 'a'.
virtual void reset_a_to_b_offset (void)
Resets the offset between type a and type b mid-sim.
virtual void verify_table_lookup_ends (void)
This function does absolutely nothing.
double get_a_to_b_offset (void)
Return the offset from the parent time object to this object.
Private Member Functions
TimeConverter_Dyn_TDB (const TimeConverter_Dyn_TDB &)
TimeConverter_Dyn_TDB & operator= (const TimeConverter_Dyn_TDB &)
Private Attributes
TimeDyn * dyn_ptr
Converter parent time, always a TimeDyn for this converter.
TimeTDB * tdb_ptr
Converter child time, always a TimeTDB for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_Dyn_TDB ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name
name of time-type "a".
std::string b_name
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()
Construct a TimeConverter.
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized
whether converter has been initialized.
double a_to_b_offset
Difference between the two time-types.
Direction valid_directions
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Define class TimeConverter_Dyn_TDB, which converts from simulation dynamic time to Barycentric Dynamic Time.
Definition at line 91 of file time_converter_dyn_tdb.hh.
Constructor & Destructor Documentation
TimeConverter_Dyn_TDB() [1/2]
jeod::TimeConverter_Dyn_TDB::TimeConverter_Dyn_TDB (void)
Construct a TimeConverter_Dyn_TDB.
Definition at line 59 of file time_converter_dyn_tdb.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::A_TO_B, jeod::TimeConverter::b_name, dyn_ptr, tdb_ptr, and jeod::TimeConverter::valid_directions.
~TimeConverter_Dyn_TDB()
jeod::TimeConverter_Dyn_TDB::~TimeConverter_Dyn_TDB (void) override
Destroy a TimeConverter_Dyn_TDB.
Definition at line 151 of file time_converter_dyn_tdb.cc.
TimeConverter_Dyn_TDB() [2/2]
jeod::TimeConverter_Dyn_TDB::TimeConverter_Dyn_TDB (const TimeConverter_Dyn_TDB &) private
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_Dyn_TDB::convert_a_to_b (void) override virtual
Convert from TimeDyn to TimeTDB.
Reimplemented from jeod::TimeConverter.
Definition at line 139 of file time_converter_dyn_tdb.cc.
References jeod::TimeConverter::a_to_b_offset, dyn_ptr, jeod::JeodBaseTime::seconds, jeod::TimeStandard::set_time_by_seconds(), and tdb_ptr.
initialize()
void jeod::TimeConverter_Dyn_TDB::initialize (JeodBaseTime * parent_ptr, JeodBaseTime * child_ptr, const int int_dir) override virtual
Initialize the converter.
Parameters
[in] parent_ptr Time used to initialize the converter
[in] child_ptr Other Time used to initialize the converter
[in] int_dir Conversion direction: +1 a=parent; -1 b=parent; 0 error
Implements jeod::TimeConverter.
Definition at line 77 of file time_converter_dyn_tdb.cc.
References jeod::TimeConverter::a_to_b_offset, dyn_ptr, jeod::MessageHandler::fail(), jeod::TimeMessages::initialization_error, jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::seconds, tdb_ptr, and jeod::TimeConverter::verify_setup().
operator=()
TimeConverter_Dyn_TDB& jeod::TimeConverter_Dyn_TDB::operator= (const TimeConverter_Dyn_TDB &) private
Friends And Related Function Documentation
init_attrjeod__TimeConverter_Dyn_TDB
void init_attrjeod__TimeConverter_Dyn_TDB () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file time_converter_dyn_tdb.hh.
Field Documentation
dyn_ptr
TimeDyn* jeod::TimeConverter_Dyn_TDB::dyn_ptr private
Converter parent time, always a TimeDyn for this converter.
trick_units(–)
Definition at line 99 of file time_converter_dyn_tdb.hh.
Referenced by convert_a_to_b(), initialize(), and TimeConverter_Dyn_TDB().
tdb_ptr
TimeTDB* jeod::TimeConverter_Dyn_TDB::tdb_ptr private
Converter child time, always a TimeTDB for this converter.
trick_units(–)
Definition at line 104 of file time_converter_dyn_tdb.hh.
Referenced by convert_a_to_b(), initialize(), and TimeConverter_Dyn_TDB().
The documentation for this class was generated from the following files:
time_converter_dyn_tdb.hh
time_converter_dyn_tdb.cc