JEOD: jeod::CheckPointOutputManager Class Reference
jeod::CheckPointOutputManager Class Reference
A CheckPointOutputManager provides the basic tools for writing a checkpoint file.
#include <checkpoint_output_manager.hh>
Public Member Functions
CheckPointOutputManager (const std::string &fname, const std::string &start_marker, const std::string &end_marker)
Construct a CheckPointOutputManager object.
SectionedOutputStream create_section_writer (const std::string &tag)
Create a C++ output stream that writes a checkpoint file section.
bool operator! () const
Conversion to boolean.
bool have_active_writer () const
Is there an active checkpoint section writer?
bool register_writer (SectionedOutputStream *writer)
Register the supplied section writer as the currently-active writer.
bool deregister_writer (const SectionedOutputStream *writer)
Deregister the supplied section writer as the currently-active writer.
Private Member Functions
SectionedOutputStream create_section_writer (bool trick, const std::string &tag)
Create a C++ output stream that writes to a checkpoint file section.
SectionedOutputStream create_trick_section_writer ()
Create a C++ output stream that writes a Trick checkpoint file section.
CheckPointOutputManager (const CheckPointOutputManager &)
Not implemented.
CheckPointOutputManager & operator= (const CheckPointOutputManager &)
Not implemented.
Private Attributes
std::ofstream stream
The C++ file stream that writes to the checkpoint file.
SectionedOutputStream * current_writer
The writer that currently is active.
const std::string filename
The name of the checkpoint file.
const std::string & section_start
The string that indicates the start of a checkpoint file section.
const std::string & section_end
The string that indicates the start of a checkpoint file section.
bool is_open
Is the checkpoint file open?
Friends
class MemoryManagerWrapper
Detailed Description
A CheckPointOutputManager provides the basic tools for writing a checkpoint file.
Section markers split a Trick 10 checkpoint file into multiple parts. This class generates C++ output streams that write the section markers and that other objects can use to write checkpoint file section data.
Definition at line 279 of file checkpoint_output_manager.hh.
Constructor & Destructor Documentation
CheckPointOutputManager() [1/2]
jeod::CheckPointOutputManager::CheckPointOutputManager (const std::string & fname, const std::string & start_marker, const std::string & end_marker)
Construct a CheckPointOutputManager object.
Parameters
[in] fname Name of file to be opened
[in] start_marker Start of section marker
[in] end_marker End of section marker
Definition at line 318 of file checkpoint_output_manager.cc.
References jeod::MessageHandler::error(), filename, jeod::SimInterfaceMessages::implementation_error, is_open, and stream.
CheckPointOutputManager() [2/2]
jeod::CheckPointOutputManager::CheckPointOutputManager (const CheckPointOutputManager &) private
Not implemented.
Member Function Documentation
create_section_writer() [1/2]
SectionedOutputStream jeod::CheckPointOutputManager::create_section_writer (const std::string & tag) inline
Create a C++ output stream that writes a checkpoint file section.
Returns
Constructed SectionedOutputStream.
Definition at line 293 of file checkpoint_output_manager.hh.
Referenced by create_trick_section_writer(), and jeod::BasicJeodTrickSimInterface::get_checkpoint_writer_internal().
create_section_writer() [2/2]
SectionedOutputStream jeod::CheckPointOutputManager::create_section_writer (bool trick, const std::string & tag) private
Create a C++ output stream that writes to a checkpoint file section.
Usage
Use this function as the initializer of a section writer variable.
Error handling
A null SectionedOutputStream is created when the CheckPointOutputManager itself is invalid or the designated section is invalid.
Returns
A SectionedOutputStream object.
Parameters
[in] trick OK to create the Trick section writer?
[in] tag Tag identifying the section to be written.
Definition at line 352 of file checkpoint_output_manager.cc.
References jeod::MessageHandler::error(), filename, jeod::SimInterfaceMessages::implementation_error, is_open, section_end, section_start, and stream.
create_trick_section_writer()
SectionedOutputStream jeod::CheckPointOutputManager::create_trick_section_writer (void) private
Create a C++ output stream that writes a Trick checkpoint file section.
Create a C++ output stream that writes to the Trick checkpoint file section.
Returns
A SectionedOutputStream object, which must be used to initialize a local SectionedOutputStream variable.
Trick SectionedOutputStream object.
Definition at line 385 of file checkpoint_output_manager.cc.
References create_section_writer(), current_writer, and jeod::SectionedOutputStream::deactivate().
deregister_writer()
bool jeod::CheckPointOutputManager::deregister_writer (const SectionedOutputStream * writer)
Deregister the supplied section writer as the currently-active writer.
Returns
True => success.
Parameters
[in] writer Writer to be deregistered
Definition at line 422 of file checkpoint_output_manager.cc.
References current_writer.
Referenced by jeod::SectionedOutputStream::deactivate().
have_active_writer()
bool jeod::CheckPointOutputManager::have_active_writer () const inline
Is there an active checkpoint section writer?
Returns
True if there is an active writer, false otherwise.
Definition at line 309 of file checkpoint_output_manager.hh.
References current_writer.
Referenced by jeod::SectionedOutputStream::is_activatable().
operator!()
bool jeod::CheckPointOutputManager::operator! () const inline
Conversion to boolean.
Returns
False if object is OK.
Definition at line 301 of file checkpoint_output_manager.hh.
References is_open, and stream.
operator=()
CheckPointOutputManager& jeod::CheckPointOutputManager::operator= (const CheckPointOutputManager &) private
Not implemented.
register_writer()
bool jeod::CheckPointOutputManager::register_writer (SectionedOutputStream * writer)
Register the supplied section writer as the currently-active writer.
Returns
True => success.
Parameters
[in] writer Writer to be Registered
Definition at line 403 of file checkpoint_output_manager.cc.
References current_writer.
Referenced by jeod::SectionedOutputStream::activate().
Friends And Related Function Documentation
MemoryManagerWrapper
friend class MemoryManagerWrapper friend
Definition at line 280 of file checkpoint_output_manager.hh.
Field Documentation
current_writer
SectionedOutputStream* jeod::CheckPointOutputManager::current_writer private
The writer that currently is active.
trick_io(**)
Definition at line 345 of file checkpoint_output_manager.hh.
Referenced by create_trick_section_writer(), deregister_writer(), have_active_writer(), and register_writer().
filename
const std::string jeod::CheckPointOutputManager::filename private
The name of the checkpoint file.
Definition at line 350 of file checkpoint_output_manager.hh.
Referenced by CheckPointOutputManager(), and create_section_writer().
is_open
bool jeod::CheckPointOutputManager::is_open private
Is the checkpoint file open?
trick_io(**)
Definition at line 365 of file checkpoint_output_manager.hh.
Referenced by CheckPointOutputManager(), create_section_writer(), and operator!().
section_end
const std::string& jeod::CheckPointOutputManager::section_end private
The string that indicates the start of a checkpoint file section.
Definition at line 360 of file checkpoint_output_manager.hh.
Referenced by create_section_writer().
section_start
const std::string& jeod::CheckPointOutputManager::section_start private
The string that indicates the start of a checkpoint file section.
Definition at line 355 of file checkpoint_output_manager.hh.
Referenced by create_section_writer().
stream
std::ofstream jeod::CheckPointOutputManager::stream private
The C++ file stream that writes to the checkpoint file.
trick_io(**)
Definition at line 340 of file checkpoint_output_manager.hh.
Referenced by CheckPointOutputManager(), create_section_writer(), and operator!().
The documentation for this class was generated from the following files:
checkpoint_output_manager.hh
checkpoint_output_manager.cc