JEOD: jeod::DynBodyGenericFrameAttachment Class Reference
jeod::DynBodyGenericFrameAttachment Class Reference
A wrench comprises a torque and a force applied at a point on a DynBody.
#include <dyn_body_generic_rigid_attach.hh>
Public Member Functions
DynBodyGenericFrameAttachment ()=default
Default constructor.
void initialize_attachment (RefFrame &parent_frame, const RefFrameState &attach_state)
void clear_attachment ()
bool isAttached () const
RefFrame * get_parent_frame () const
const RefFrameState & get_attach_offset () const
Private Attributes
bool active {}
trick_units(–)
RefFrame * rigid_attach_parent {}
trick_units(–)
RefFrameState rigid_attach_state
trick_units(–)
Friends
class InputProcessor
void init_attrjeod__DynBodyGenericFrameAttachment ()
Detailed Description
A wrench comprises a torque and a force applied at a point on a DynBody.
The torque should not include the torque due to the application of the force.
A Trick simulation issues vcollect statements such as
 vcollect vehicle.dyn_body.collect_wrench.collection
 {
     wrench_model1.wrench,
     wrench_model2.wrench
 };
Definition at line 77 of file dyn_body_generic_rigid_attach.hh.
Constructor & Destructor Documentation
DynBodyGenericFrameAttachment()
jeod::DynBodyGenericFrameAttachment::DynBodyGenericFrameAttachment () default
Default constructor.
Member Function Documentation
clear_attachment()
void jeod::DynBodyGenericFrameAttachment::clear_attachment () inline
Definition at line 97 of file dyn_body_generic_rigid_attach.hh.
Referenced by jeod::DynBody::detach().
get_attach_offset()
const RefFrameState& jeod::DynBodyGenericFrameAttachment::get_attach_offset () const inline
Definition at line 112 of file dyn_body_generic_rigid_attach.hh.
Referenced by jeod::DynBody::integrate().
get_parent_frame()
RefFrame* jeod::DynBodyGenericFrameAttachment::get_parent_frame () const inline
Definition at line 107 of file dyn_body_generic_rigid_attach.hh.
Referenced by jeod::DynBody::integrate().
initialize_attachment()
void jeod::DynBodyGenericFrameAttachment::initialize_attachment (RefFrame & parent_frame, const RefFrameState & attach_state) inline
Definition at line 88 of file dyn_body_generic_rigid_attach.hh.
References active, jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, rigid_attach_parent, rigid_attach_state, jeod::RefFrameState::rot, jeod::RefFrameRot::T_parent_this, and jeod::RefFrameState::trans.
Referenced by jeod::DynBody::attach_to_frame().
isAttached()
bool jeod::DynBodyGenericFrameAttachment::isAttached () const inline
Definition at line 102 of file dyn_body_generic_rigid_attach.hh.
Referenced by jeod::DynBody::detach(), and jeod::DynBody::integrate().
Friends And Related Function Documentation
init_attrjeod__DynBodyGenericFrameAttachment
void init_attrjeod__DynBodyGenericFrameAttachment () friend
InputProcessor
friend class InputProcessor friend
Definition at line 79 of file dyn_body_generic_rigid_attach.hh.
Field Documentation
active
bool jeod::DynBodyGenericFrameAttachment::active {} private
trick_units(–)
Definition at line 120 of file dyn_body_generic_rigid_attach.hh.
Referenced by initialize_attachment().
rigid_attach_parent
RefFrame* jeod::DynBodyGenericFrameAttachment::rigid_attach_parent {} private
trick_units(–)
Definition at line 122 of file dyn_body_generic_rigid_attach.hh.
Referenced by initialize_attachment().
rigid_attach_state
RefFrameState jeod::DynBodyGenericFrameAttachment::rigid_attach_state private
trick_units(–)
Definition at line 124 of file dyn_body_generic_rigid_attach.hh.
Referenced by initialize_attachment().
The documentation for this class was generated from the following file:
dyn_body_generic_rigid_attach.hh