JEOD: jeod::MassPoint Class Reference
jeod::MassPoint Class Reference
Adds tree linkages and a name to a MassPointState.
#include <mass_point.hh>
Public Member Functions
MassPoint ()
Default constructor.
~MassPoint () override
Destroy a MassPoint object.
void initialize_mass_point () override
Initialize a mass point.
void set_name (std::string name_in)
const char * get_name () const
virtual void compute_relative_state (const MassPoint &ref_point, MassPointState &rel_state) const
Compute the state of this point with respect to some reference point, which may be any point in the same tree as this point.
virtual void compute_state_wrt_pred (const MassPoint &ref_point, MassPointState &rel_state) const
Compute the state of this point with respect to some reference point, which must be at or above this point via the parent links.
virtual void compute_state_wrt_pred (unsigned int ref_point_index, MassPointState &rel_state) const
Compute the state of this point with respect to some reference point, which must be at or above this point via the parent links.
virtual void compute_pred_rel_state (const MassPoint &ref_point, MassPointState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_pred_rel_state (unsigned int ref_point_index, MassPointState &rel_state) const
Compute the state of some reference point with respect to this point.
const MassPoint * find_last_common_node (const MassPoint &ref_point) const
Each mass point has a path from the root of the mass point tree to the point in question.
Public Member Functions inherited from jeod::MassPointState
MassPointState ()
Default constructor; constructs a MassPointState object.
virtual ~MassPointState ()=default
Destructor.
void update_point (const double pt_location[3])
Update the mass point's structure-to-point vector.
void update_orientation (const double transformation[3][3])
Update the mass point's structure-to-point frame transformation matrix and items derived from it.
void update_orientation (const Quaternion &left_quat)
Update the mass point's structure-to-point frame transformation matrix and items derived from it.
void compute_quaternion ()
Compute quaternion.
void compute_transformation ()
Compute matrix.
void copy_state (const MassPointState &source)
Copy the provided state to this.
void negate (const MassPointState &source)
Copy a mass point state, negated.
void incr_left (const MassPointState &s_ab)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_B:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
void incr_right (const MassPointState &s_bc)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_A:B, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
void decr_left (const MassPointState &s_ab)
Compute S_B:C = (-S_A:B) + S_A:C, with this initially containing S_A:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
void decr_right (const MassPointState &s_bc)
Compute S_A:B = S_A:C + (-S_B:C) with this initially containing S_A:C, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Protected Member Functions
int find_last_common_index (const MassPoint &ref_point) const
Each mass point has a path from the root of the mass point tree to the point in question.
Protected Attributes
NamedItem name
The name of the mass point.
MassPointLinks links
Linkage to rest of mass tree.
Private Member Functions
void attach (MassPoint &parent)
Attach a mass point to another.
void detach ()
Detach a mass point from its parent.
MassPoint (const MassPoint &)
MassPoint & operator= (const MassPoint &)
Friends
class InputProcessor
class MassPointLinks
class MassBody
void init_attrjeod__MassPoint ()
Additional Inherited Members
Data Fields inherited from jeod::MassPointState
double position [3]
Mass point location with respect to the origin of some parent frame and expressed in the parent frame's coordinates.
Quaternion Q_parent_this
Left transformation quaternion from the parent frame to the frame associated with the mass point.
double T_parent_this [3][3]
transformation matrix from the parent frame to the frame associated with the mass point.
Detailed Description
Adds tree linkages and a name to a MassPointState.
Definition at line 87 of file mass_point.hh.
Constructor & Destructor Documentation
MassPoint() [1/2]
jeod::MassPoint::MassPoint () inline
Default constructor.
Definition at line 121 of file mass_point.hh.
~MassPoint()
jeod::MassPoint::~MassPoint () override
Destroy a MassPoint object.
Definition at line 59 of file mass_point.cc.
References jeod::TreeLinks< Links, Container, Messages >::child_tail(), jeod::TreeLinks< Links, Container, Messages >::detach(), jeod::TreeLinks< Links, Container, Messages >::has_children(), and links.
MassPoint() [2/2]
jeod::MassPoint::MassPoint (const MassPoint &) private
Member Function Documentation
attach()
void jeod::MassPoint::attach (MassPoint & parent) inline private
Attach a mass point to another.
Assumptions and Limitations
This method only addresses the linkages. Some external agent must address the physical relation.
Parameters
[in,out] parent parent node
Definition at line 252 of file mass_point.hh.
References jeod::TreeLinks< Links, Container, Messages >::attach(), and links.
Referenced by jeod::MassBody::add_mass_point(), jeod::MassBody::attach_establish_links(), jeod::MassBody::attach_to(), and jeod::MassBody::MassBody().
compute_pred_rel_state() [1/2]
void jeod::MassPoint::compute_pred_rel_state (const MassPoint & ref_point, MassPointState & rel_state) const virtual
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
Assumptions and Limitations
The predecessor frame is a predecessor.
Parameters
[in] ref_point The point with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 247 of file mass_point.cc.
References jeod::MessageHandler::fail(), jeod::TreeLinks< Links, Container, Messages >::find_path_index(), jeod::MassBodyMessages::invalid_node, links, and jeod::TreeLinks< Links, Container, Messages >::path_length().
Referenced by compute_relative_state().
compute_pred_rel_state() [2/2]
void jeod::MassPoint::compute_pred_rel_state (unsigned int ref_point_index, MassPointState & rel_state) const virtual
Compute the state of some reference point with respect to this point.
The reference point must be at or above this point via the parent links.
Parameters
[in] ref_point_index Reference point index
[out] rel_state Relative state
Definition at line 278 of file mass_point.cc.
References jeod::Quaternion::conjugate(), jeod::MassPointState::initialize_mass_point(), jeod::Quaternion::left_quat_to_transformation(), links, jeod::Quaternion::multiply_left_conjugate(), jeod::Vector3::negate(), jeod::Quaternion::normalize(), jeod::TreeLinks< Links, Container, Messages >::path_length(), jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::MassPointState::T_parent_this, jeod::Vector3::transform(), jeod::Vector3::transform_transpose_decr(), and jeod::Matrix3x3::transpose().
compute_relative_state()
void jeod::MassPoint::compute_relative_state (const MassPoint & ref_point, MassPointState & rel_state) const virtual
Compute the state of this point with respect to some reference point, which may be any point in the same tree as this point.
Parameters
[in] ref_point The point with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 92 of file mass_point.cc.
References compute_pred_rel_state(), compute_state_wrt_pred(), jeod::MassPointState::decr_left(), jeod::MessageHandler::fail(), find_last_common_index(), jeod::MassPointState::initialize_mass_point(), jeod::MassBodyMessages::invalid_node, links, and jeod::TreeLinks< Links, Container, Messages >::nth_from_root().
Referenced by jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), and jeod::SurfaceModel::update_articulation().
compute_state_wrt_pred() [1/2]
void jeod::MassPoint::compute_state_wrt_pred (const MassPoint & ref_point, MassPointState & rel_state) const virtual
Compute the state of this point with respect to some reference point, which must be at or above this point via the parent links.
Parameters
[in] ref_point Reference point
[out] rel_state Point state wrt ref. pt.
Definition at line 162 of file mass_point.cc.
References jeod::MessageHandler::fail(), jeod::TreeLinks< Links, Container, Messages >::find_path_index(), jeod::MassBodyMessages::invalid_node, links, and jeod::TreeLinks< Links, Container, Messages >::path_length().
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::DynBody::compute_ref_point_transform(), and compute_relative_state().
compute_state_wrt_pred() [2/2]
void jeod::MassPoint::compute_state_wrt_pred (unsigned int ref_point_index, MassPointState & rel_state) const virtual
Compute the state of this point with respect to some reference point, which must be at or above this point via the parent links.
Parameters
[in] ref_point_index Reference point index
[out] rel_state Point state wrt ref. pt.
Definition at line 192 of file mass_point.cc.
References jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::MassPointState::initialize_mass_point(), jeod::Quaternion::left_quat_to_transformation(), links, jeod::Quaternion::multiply(), jeod::Quaternion::normalize(), jeod::TreeLinks< Links, Container, Messages >::path_length(), jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::Vector3::sum(), jeod::MassPointState::T_parent_this, and jeod::Vector3::transform_transpose().
detach()
void jeod::MassPoint::detach (void) inline private
Detach a mass point from its parent.
Assumptions and Limitations
This method only addresses the linkages. Some external agent must address the physical relation.
Definition at line 267 of file mass_point.hh.
References jeod::TreeLinks< Links, Container, Messages >::detach(), and links.
Referenced by jeod::MassBody::attach_to(), initialize_mass_point(), and jeod::MassBody::~MassBody().
find_last_common_index()
int jeod::MassPoint::find_last_common_index (const MassPoint & ref_point) const inline protected
Each mass point has a path from the root of the mass point tree to the point in question.
The paths for two mass points will have some initial sequence of common nodes. Find the index number of this last element in this sequence.
Returns
Last common node
Parameters
[in] ref_point Other point
Definition at line 211 of file mass_point.hh.
References jeod::TreeLinks< Links, Container, Messages >::find_last_common_index(), and links.
Referenced by compute_relative_state().
find_last_common_node()
const MassPoint * jeod::MassPoint::find_last_common_node (const MassPoint & frame) const inline
Each mass point has a path from the root of the mass point tree to the point in question.
The paths for two mass points will have some initial sequence of common nodes. Find the last element in this sequence.
Returns
Last common node
Parameters
[in] frame Other point
Definition at line 228 of file mass_point.hh.
References jeod::TreeLinks< Links, Container, Messages >::container(), jeod::TreeLinks< Links, Container, Messages >::find_last_common_node(), and links.
get_name()
const char* jeod::MassPoint::get_name () const inline
Definition at line 140 of file mass_point.hh.
References jeod::NamedItem::c_str(), and name.
Referenced by jeod::DynBody::add_mass_point().
initialize_mass_point()
void jeod::MassPoint::initialize_mass_point (void) override virtual
Initialize a mass point.
Reimplemented from jeod::MassPointState.
Definition at line 78 of file mass_point.cc.
References detach(), and jeod::MassPointState::initialize_mass_point().
Referenced by jeod::MassBody::detach_update_properties().
operator=()
MassPoint& jeod::MassPoint::operator= (const MassPoint &) private
set_name()
void jeod::MassPoint::set_name (std::string name_in) inline
Definition at line 134 of file mass_point.hh.
References name.
Friends And Related Function Documentation
init_attrjeod__MassPoint
void init_attrjeod__MassPoint () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file mass_point.hh.
MassBody
friend class MassBody friend
Definition at line 92 of file mass_point.hh.
MassPointLinks
friend class MassPointLinks friend
Definition at line 91 of file mass_point.hh.
Field Documentation
links
MassPointLinks jeod::MassPoint::links protected
Linkage to rest of mass tree.
Programmatic interfaces:
MassPointLinks provides accessors to the parent and root and provides methods to attach, detach links (and hence bodies).
This class provides accessors to the same.
Various iterators provide the ability to iterate over child bodies and up the parent chain.trick_units(–)
Definition at line 112 of file mass_point.hh.
Referenced by attach(), compute_pred_rel_state(), compute_relative_state(), compute_state_wrt_pred(), detach(), find_last_common_index(), find_last_common_node(), and ~MassPoint().
name
NamedItem jeod::MassPoint::name protected
The name of the mass point.
trick_units(–)
Definition at line 101 of file mass_point.hh.
Referenced by jeod::MassBody::add_mass_point(), get_name(), and set_name().
The documentation for this class was generated from the following files:
mass_point.hh
mass_point.cc