JEOD: jeod::PlanetaryDerivedState Class Reference
jeod::PlanetaryDerivedState Class Reference
The class used for deriving the planet-fixed representations of a subject DynBody's position.
#include <planetary_derived_state.hh>
Public Member Functions
PlanetaryDerivedState ()
Construct a PlanetaryDerivedState object.
~PlanetaryDerivedState () override
Destruct a PlanetaryDerivedState object.
void set_use_alt_pfix (const bool use_alt_pfix_in)
Setter for use_alt_pfix.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a PlanetaryDerivedState.
void update (void) override
Update the state.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
PlanetFixedPosition state
The planet-fixed state of the subject body's composite CoM.
Planet * planet
The planet, the name of which is specified by the inherited reference_name data member.
Data Fields inherited from jeod::DerivedState
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Attributes
bool use_alt_pfix
Use pfix or alt_pfix flag.
EphemerisRefFrame * pfix_ptr
Pointer to planet fixed frame to be used, either pfix or alt_pfix.
Protected Attributes inherited from jeod::DerivedState
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
PlanetaryDerivedState (const PlanetaryDerivedState &)
PlanetaryDerivedState & operator= (const PlanetaryDerivedState &)
Friends
class InputProcessor
void init_attrjeod__PlanetaryDerivedState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Detailed Description
The class used for deriving the planet-fixed representations of a subject DynBody's position.
Definition at line 86 of file planetary_derived_state.hh.
Constructor & Destructor Documentation
PlanetaryDerivedState() [1/2]
jeod::PlanetaryDerivedState::PlanetaryDerivedState (void)
Construct a PlanetaryDerivedState object.
Definition at line 48 of file planetary_derived_state.cc.
~PlanetaryDerivedState()
jeod::PlanetaryDerivedState::~PlanetaryDerivedState (void) override
Destruct a PlanetaryDerivedState object.
Definition at line 61 of file planetary_derived_state.cc.
References pfix_ptr, and jeod::Subscription::unsubscribe().
PlanetaryDerivedState() [2/2]
jeod::PlanetaryDerivedState::PlanetaryDerivedState (const PlanetaryDerivedState &) private
Member Function Documentation
initialize()
void jeod::PlanetaryDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of a PlanetaryDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DerivedState.
Definition at line 90 of file planetary_derived_state.cc.
References jeod::BasePlanet::alt_pfix, jeod::DerivedState::find_planet(), jeod::DerivedState::initialize(), jeod::PlanetFixedPosition::initialize(), jeod::BasePlanet::pfix, pfix_ptr, planet, jeod::DerivedState::reference_name, state, jeod::Subscription::subscribe(), and use_alt_pfix.
operator=()
PlanetaryDerivedState& jeod::PlanetaryDerivedState::operator= (const PlanetaryDerivedState &) private
set_use_alt_pfix()
void jeod::PlanetaryDerivedState::set_use_alt_pfix (const bool use_alt_pfix_in)
Setter for use_alt_pfix.
Definition at line 74 of file planetary_derived_state.cc.
References use_alt_pfix.
update()
void jeod::PlanetaryDerivedState::update (void) override virtual
Update the state.
Reimplemented from jeod::DerivedState.
Definition at line 121 of file planetary_derived_state.cc.
References jeod::DynBody::composite_body, jeod::RefFrame::compute_position_from(), pfix_ptr, state, jeod::DerivedState::subject, and jeod::PlanetFixedPosition::update_from_cart().
Friends And Related Function Documentation
init_attrjeod__PlanetaryDerivedState
void init_attrjeod__PlanetaryDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file planetary_derived_state.hh.
Field Documentation
pfix_ptr
EphemerisRefFrame* jeod::PlanetaryDerivedState::pfix_ptr protected
Pointer to planet fixed frame to be used, either pfix or alt_pfix.
Definition at line 117 of file planetary_derived_state.hh.
Referenced by initialize(), update(), and ~PlanetaryDerivedState().
planet
Planet* jeod::PlanetaryDerivedState::planet
The planet, the name of which is specified by the inherited reference_name data member.
trick_units(–)
Definition at line 104 of file planetary_derived_state.hh.
Referenced by initialize().
state
PlanetFixedPosition jeod::PlanetaryDerivedState::state
The planet-fixed state of the subject body's composite CoM.
trick_units(–)
Definition at line 98 of file planetary_derived_state.hh.
Referenced by initialize(), and update().
use_alt_pfix
bool jeod::PlanetaryDerivedState::use_alt_pfix protected
Use pfix or alt_pfix flag.
Definition at line 111 of file planetary_derived_state.hh.
Referenced by initialize(), and set_use_alt_pfix().
The documentation for this class was generated from the following files:
planetary_derived_state.hh
planetary_derived_state.cc