## MODEL_TYPE  = environment
## MODEL_NAME  = ephemerides
## MODEL_TITLE = 'Ephemerides Model'

DOT_FILES = $(wildcard *.dot)

# Figures generated by dot
DOT_PDF_FILES = $(subst .dot,.pdf,$(DOT_FILES))

EXTRA_DEPENDS = $(DOT_PDF_FILES)
