JEOD: jeod::TimeConverter_UT1_GMST Class Reference
jeod::TimeConverter_UT1_GMST Class Reference
Converts between Universal Time and Greenwich Mean Sidereal Time.
#include <time_converter_ut1_gmst.hh>
Public Member Functions
TimeConverter_UT1_GMST ()
Construct a TimeConverter_UT1_GMST.
~TimeConverter_UT1_GMST () override=default
TimeConverter_UT1_GMST (const TimeConverter_UT1_GMST &)=delete
TimeConverter_UT1_GMST & operator= (const TimeConverter_UT1_GMST &)=delete
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void convert_a_to_b () override
Convert from TimeUT1 to TimeGMST.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()=default
TimeConverter (const TimeConverter &)=delete
TimeConverter & operator= (const TimeConverter &)=delete
virtual bool is_initialized ()
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void convert_b_to_a ()
Default converter from time 'b' to time 'a'.
virtual void reset_a_to_b_offset ()
Resets the offset between type a and type b mid-sim.
virtual void verify_table_lookup_ends ()
This function does absolutely nothing.
double get_a_to_b_offset ()
Return the offset from the parent time object to this object.
Private Attributes
TimeUT1 * ut1_ptr {}
Converter parent time, always a TimeUT1 for this converter.
TimeGMST * gmst_ptr {}
Converter parent time, always a TimeGMST for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_UT1_GMST ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name {""}
name of time-type "a".
std::string b_name {""}
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()=default
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized {}
whether converter has been initialized.
double a_to_b_offset {}
Difference between the two time-types.
Direction valid_directions {NO_DIRECTION}
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Converts between Universal Time and Greenwich Mean Sidereal Time.
Definition at line 86 of file time_converter_ut1_gmst.hh.
Constructor & Destructor Documentation
TimeConverter_UT1_GMST() [1/2]
jeod::TimeConverter_UT1_GMST::TimeConverter_UT1_GMST ()
Construct a TimeConverter_UT1_GMST.
Definition at line 57 of file time_converter_ut1_gmst.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::A_TO_B, jeod::TimeConverter::b_name, and jeod::TimeConverter::valid_directions.
~TimeConverter_UT1_GMST()
jeod::TimeConverter_UT1_GMST::~TimeConverter_UT1_GMST () override default
TimeConverter_UT1_GMST() [2/2]
jeod::TimeConverter_UT1_GMST::TimeConverter_UT1_GMST (const TimeConverter_UT1_GMST &) delete
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_UT1_GMST::convert_a_to_b () override virtual
Convert from TimeUT1 to TimeGMST.
Assumptions and Limitations
None
Reimplemented from jeod::TimeConverter.
Definition at line 104 of file time_converter_ut1_gmst.cc.
References jeod::TimeUT1::get_days(), gmst_ptr, jeod::TimeStandard::set_time_by_days(), and ut1_ptr.
initialize()
void jeod::TimeConverter_UT1_GMST::initialize (JeodBaseTime * parent_ptr, JeodBaseTime * child_ptr, const int int_dir) override virtual
Initialize the converter.
Assumptions and Limitations
None
Parameters
[in] parent_ptr Time used to initialize the converter
[in] child_ptr Other Time used to initialize the converter
[in] int_dir Conversion direction: +1 a=parent; -1 b=parent; 0 error
Implements jeod::TimeConverter.
Definition at line 73 of file time_converter_ut1_gmst.cc.
References jeod::MessageHandler::fail(), gmst_ptr, jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, ut1_ptr, and jeod::TimeConverter::verify_setup().
operator=()
TimeConverter_UT1_GMST& jeod::TimeConverter_UT1_GMST::operator= (const TimeConverter_UT1_GMST &) delete
Friends And Related Function Documentation
init_attrjeod__TimeConverter_UT1_GMST
void init_attrjeod__TimeConverter_UT1_GMST () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file time_converter_ut1_gmst.hh.
Field Documentation
gmst_ptr
TimeGMST* jeod::TimeConverter_UT1_GMST::gmst_ptr {} private
Converter parent time, always a TimeGMST for this converter.
trick_units(–)
Definition at line 98 of file time_converter_ut1_gmst.hh.
Referenced by convert_a_to_b(), and initialize().
ut1_ptr
TimeUT1* jeod::TimeConverter_UT1_GMST::ut1_ptr {} private
Converter parent time, always a TimeUT1 for this converter.
trick_units(–)
Definition at line 93 of file time_converter_ut1_gmst.hh.
Referenced by convert_a_to_b(), and initialize().
The documentation for this class was generated from the following files:
time_converter_ut1_gmst.hh
time_converter_ut1_gmst.cc