JEOD: jeod::PlanetFixedPosition Class Reference
jeod::PlanetFixedPosition Class Reference
Contains various representations of position with respect to a planet.
#include <planet_fixed_posn.hh>
Public Member Functions
PlanetFixedPosition ()
Construct a PlanetFixedPosition object.
virtual ~PlanetFixedPosition ()
Destructor.
virtual void initialize (Planet *planet_in)
Initialize a PlanetFixedPosition object.
virtual void update_from_cart (const double cart[3])
Update from Cartesian position input.
virtual void update_from_spher (const AltLatLongState &spher)
Update from Spherical position input.
virtual void update_from_ellip (const AltLatLongState &ellip)
Update from Elliptical position input.
Data Fields
AltLatLongState ellip_coords
An object's current position in elliptical coordinates.
AltLatLongState sphere_coords
The same object's current position in spherical coordinates.
double cart_coords [3]
The planet-centered, planet-fixed position of the object.
Planet * planet
The planet currently associated with this.
Static Public Attributes
static const double Small_radius_limit = 1e-60
Limit of ratio of radial distance to planet equatorial radius below which planetary coordinates are deemed to be invalid.
Protected Member Functions
void cart_to_spher ()
Convert from cartesian to spherical position.
void cart_to_ellip ()
Convert from cartesian to elliptical position.
void spher_to_cart ()
Convert from spherical to cartesian position.
void ellip_to_cart ()
Convert from elliptical to cartesian position.
int get_elliptic_parameters (double r, double z, double &f, double &h, int maxIters=10)
Friends
class InputProcessor
void init_attrjeod__PlanetFixedPosition ()
Detailed Description
Contains various representations of position with respect to a planet.
Definition at line 91 of file planet_fixed_posn.hh.
Constructor & Destructor Documentation
PlanetFixedPosition()
jeod::PlanetFixedPosition::PlanetFixedPosition (void)
Construct a PlanetFixedPosition object.
Definition at line 57 of file planet_fixed_posn.cc.
References cart_coords, jeod::Vector3::initialize(), and planet.
~PlanetFixedPosition()
virtual jeod::PlanetFixedPosition::~PlanetFixedPosition () inline virtual
Destructor.
Definition at line 147 of file planet_fixed_posn.hh.
Member Function Documentation
cart_to_ellip()
void jeod::PlanetFixedPosition::cart_to_ellip (void) protected
Convert from cartesian to elliptical position.
Definition at line 172 of file planet_fixed_posn.cc.
References jeod::AltLatLongState::altitude, cart_coords, jeod::PlanetFixedMessages::domain_error, ellip_coords, jeod::MessageHandler::fail(), get_elliptic_parameters(), jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, and Small_radius_limit.
Referenced by update_from_cart(), and update_from_spher().
cart_to_spher()
void jeod::PlanetFixedPosition::cart_to_spher (void) protected
Convert from cartesian to spherical position.
Definition at line 131 of file planet_fixed_posn.cc.
References jeod::AltLatLongState::altitude, cart_coords, jeod::PlanetFixedMessages::domain_error, jeod::MessageHandler::fail(), jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, planet, jeod::Planet::r_eq, Small_radius_limit, sphere_coords, and jeod::Vector3::vmag().
Referenced by update_from_cart(), and update_from_ellip().
ellip_to_cart()
void jeod::PlanetFixedPosition::ellip_to_cart (void) protected
Convert from elliptical to cartesian position.
Definition at line 250 of file planet_fixed_posn.cc.
References jeod::AltLatLongState::altitude, cart_coords, jeod::Planet::e_ellipsoid, ellip_coords, jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, planet, and jeod::Planet::r_eq.
Referenced by update_from_ellip().
get_elliptic_parameters()
int jeod::PlanetFixedPosition::get_elliptic_parameters (double r, double z, double & f, double & h, int maxIters = 10) protected
Definition at line 286 of file planet_fixed_posn.cc.
References planet, jeod::Planet::r_eq, and jeod::Planet::r_pol.
Referenced by cart_to_ellip().
initialize()
void jeod::PlanetFixedPosition::initialize (Planet * planet_in) virtual
Initialize a PlanetFixedPosition object.
Parameters
[in] planet_in Associated planet
Definition at line 69 of file planet_fixed_posn.cc.
References planet.
Referenced by jeod::DynBodyInitNedState::apply(), jeod::PlanetaryDerivedState::initialize(), and jeod::NedDerivedState::initialize().
spher_to_cart()
void jeod::PlanetFixedPosition::spher_to_cart (void) protected
Convert from spherical to cartesian position.
Definition at line 225 of file planet_fixed_posn.cc.
References jeod::AltLatLongState::altitude, cart_coords, jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, planet, jeod::Planet::r_eq, and sphere_coords.
Referenced by update_from_spher().
update_from_cart()
void jeod::PlanetFixedPosition::update_from_cart (const double cart[3]) virtual
Update from Cartesian position input.
Parameters
[in] cart Cartesian coords, PCPF
Units: M
Definition at line 82 of file planet_fixed_posn.cc.
References cart_coords, cart_to_ellip(), cart_to_spher(), and jeod::Vector3::copy().
Referenced by jeod::NorthEastDown::set_ned_trans_states(), jeod::PlanetaryDerivedState::update(), and jeod::NorthEastDown::update_from_cart().
update_from_ellip()
void jeod::PlanetFixedPosition::update_from_ellip (const AltLatLongState & ellip) virtual
Update from Elliptical position input.
Parameters
[in] ellip Elliptical AltLatLong position
Reimplemented in jeod::NorthEastDown.
Definition at line 115 of file planet_fixed_posn.cc.
References jeod::AltLatLongState::altitude, cart_to_spher(), ellip_coords, ellip_to_cart(), jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, and jeod::AltLatLongState::set_data().
Referenced by jeod::NorthEastDown::update_from_ellip().
update_from_spher()
void jeod::PlanetFixedPosition::update_from_spher (const AltLatLongState & spher) virtual
Update from Spherical position input.
Parameters
[in] spher Spherical AltLatLong position
Reimplemented in jeod::NorthEastDown.
Definition at line 98 of file planet_fixed_posn.cc.
References jeod::AltLatLongState::altitude, cart_to_ellip(), jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, jeod::AltLatLongState::set_data(), spher_to_cart(), and sphere_coords.
Referenced by jeod::NorthEastDown::update_from_spher().
Friends And Related Function Documentation
init_attrjeod__PlanetFixedPosition
void init_attrjeod__PlanetFixedPosition () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file planet_fixed_posn.hh.
Field Documentation
cart_coords
double jeod::PlanetFixedPosition::cart_coords[3]
The planet-centered, planet-fixed position of the object.
trick_units(m)
Definition at line 130 of file planet_fixed_posn.hh.
Referenced by cart_to_ellip(), cart_to_spher(), ellip_to_cart(), PlanetFixedPosition(), spher_to_cart(), jeod::NorthEastDown::update_from_cart(), update_from_cart(), jeod::NorthEastDown::update_from_ellip(), and jeod::NorthEastDown::update_from_spher().
ellip_coords
AltLatLongState jeod::PlanetFixedPosition::ellip_coords
An object's current position in elliptical coordinates.
Per Vallado p. 140, elliptical latitude is the angle between the equatorial plane and the surface normal on the ellipsoid at the point of interest. Similarly, elliptical longitude is assumed to be the angle between the reference meridian and the surface normal on the ellipsoid at the point of interest.trick_units(–)
Definition at line 116 of file planet_fixed_posn.hh.
Referenced by jeod::NorthEastDown::build_ned_orientation(), cart_to_ellip(), ellip_to_cart(), jeod::METAtmosphere::update_atmosphere(), and update_from_ellip().
planet
Planet* jeod::PlanetFixedPosition::planet
The planet currently associated with this.
trick_units(–)
Definition at line 135 of file planet_fixed_posn.hh.
Referenced by cart_to_spher(), ellip_to_cart(), get_elliptic_parameters(), initialize(), PlanetFixedPosition(), and spher_to_cart().
Small_radius_limit
const double jeod::PlanetFixedPosition::Small_radius_limit = 1e-60 static
Limit of ratio of radial distance to planet equatorial radius below which planetary coordinates are deemed to be invalid.
trick_io(*o) trick_units(–)
Definition at line 102 of file planet_fixed_posn.hh.
Referenced by cart_to_ellip(), and cart_to_spher().
sphere_coords
AltLatLongState jeod::PlanetFixedPosition::sphere_coords
The same object's current position in spherical coordinates.
Per Vallado p. 140, spherical latitude is the angle measured at the planet's center from the equatorial plane to the point of interest. Similarly, spherical longitude is also assumed to be the angle measured at the planet's center from the reference meridian to the point of interest.trick_units(–)
Definition at line 125 of file planet_fixed_posn.hh.
Referenced by jeod::NorthEastDown::build_ned_orientation(), cart_to_spher(), spher_to_cart(), and update_from_spher().
The documentation for this class was generated from the following files:
planet_fixed_posn.hh
planet_fixed_posn.cc