JEOD: jeod::DynBodyConstraint Class Reference
jeod::DynBodyConstraint Class Reference abstract
Represents a constrained object, which comprises one or more scalar constraints on a vehicle.
#include <dyn_body_constraint.hh>
Public Member Functions
DynBodyConstraint ()=default
virtual ~DynBodyConstraint ()
Destructor.
DynBodyConstraint (const DynBodyConstraint &)=delete
DynBodyConstraint & operator= (const DynBodyConstraint &)=delete
virtual void activate ()
Activate the constraint.
virtual void deactivate ()
Deactivate the constraint.
bool is_active () const
Is the constraint active?
virtual const DynBodyConstraintsSolver * get_solver () const
Get the solver for this constrained object.
virtual void set_struct_to_constraint_frame (SolverTypes::ConstDecayedMatrix3x3T transform_in, SolverTypes::ConstDecayedVector3T offset_in)
Set the relationship between the constraint frame and the immediate structural frame.
virtual void update_attachment (const VehicleProperties &vehicle_properties)
Update information about the relation between this constraint and the root DynBody.
void update_component_attachment (const VehicleProperties &vehicle_properties)
Send update_attachment to each component.
virtual void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)=0
Prepare this object for solving a constraint problem.
void setup_component_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Send setup_constraint to each component.
virtual const Wrench & get_effector_wrench () const =0
Get the known wrench for this constrained object.
virtual ConstraintComponent * get_component (unsigned index)=0
Get the indexed component constraint for this composite constraint.
virtual const ConstraintComponent * get_component (unsigned index) const
Const version of get_component().
virtual void set_r_h_s (jeod::VectorView< double > &rhs_slice) const
Set the sum of the terms in the constraint equation that don't involve other constrained objects, expressed as the right hand side of the constraint equation.
virtual void set_r_h_s (jeod::VectorView< double > &&rhs_slice) const
So one can use set_r_h_s with a temporary.
virtual void set_cross_coeff (const VehicleProperties &vehicle_properties, const DynBodyConstraint &other, jeod::MatrixView< double > &a_slice) const
Set the constraint matrix elements that pertain to this constrained object with respect to some other constrained object.
virtual void set_cross_coeff (const VehicleProperties &vehicle_properties, const DynBodyConstraint &other, jeod::MatrixView< double > &&a_slice) const
So one can call set_cross_coeff with a temporary.
virtual void set_self_coeff (const VehicleProperties &vehicle_properties, jeod::MatrixView< double > &a_slice) const
Set the constraint matrix elements for this constraint object with respect to itself.
virtual void set_self_coeff (const VehicleProperties &vehicle_properties, jeod::MatrixView< double > &&a_slice) const
So one can call set_self_coeff with a temporary.
virtual void set_constraint_values (const jeod::VectorView< double, double > &solution_slice)
Set this constrained object's constraint values.
virtual const Wrench & get_constraint_wrench () const =0
Get the wrench this constrained object exerts on the vehicle.
virtual void compute_constraint_response (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
virtual const Wrench & get_nonlinear_response_wrench () const =0
Get the residual nonlinear wrench for this constrained object.
Protected Member Functions
virtual void attach_to_solver ()
Perform actions related to the just-performed addition of this constraint to a constraints solver.
virtual void detach_from_solver ()
Perform actions related to the just-performed removal of this constraint from a constraints solver.
virtual DynBody * get_dyn_body ()
Get the dyn_body object associated with this constrained object.
Protected Attributes
ConstraintFrame constraint_frame
The reference frame associated with this constraint.
DynBodyConstraintsSolver * solver {}
The solver to which this constraint is assigned.
unsigned n_dimensions {}
The number of active components associated with this constraint.
bool inactive {}
Is the constraint inactive? Note: This is expressed in the negative sense to support reduced Trick checkpointing.
Private Member Functions
void set_solver (DynBodyConstraintsSolver *solver_in)
Set the solver for this constraint.
void reset_solver ()
Clear the solver for this constraint.
Friends
class InputProcessor
class DynBodyConstraintsSolver
void init_attrjeod__DynBodyConstraint ()
Detailed Description
Represents a constrained object, which comprises one or more scalar constraints on a vehicle.
Definition at line 82 of file dyn_body_constraint.hh.
Constructor & Destructor Documentation
DynBodyConstraint() [1/2]
jeod::DynBodyConstraint::DynBodyConstraint () default
~DynBodyConstraint()
jeod::DynBodyConstraint::~DynBodyConstraint () virtual
Destructor.
Destruction removes a constraint from the solver.
Definition at line 38 of file dyn_body_constraint.cc.
References jeod::DynBodyConstraintsSolver::remove_constraint(), and solver.
DynBodyConstraint() [2/2]
jeod::DynBodyConstraint::DynBodyConstraint (const DynBodyConstraint &) delete
Member Function Documentation
activate()
void jeod::DynBodyConstraint::activate () virtual
Activate the constraint.
Reimplemented in jeod::DynBodyPendulumConstraint.
Definition at line 47 of file dyn_body_constraint.cc.
References jeod::DynBodyConstraintsSolver::activate_constraint(), inactive, and solver.
Referenced by jeod::DynBodyPendulumConstraint::activate().
attach_to_solver()
void jeod::DynBodyConstraint::attach_to_solver () protected virtual
Perform actions related to the just-performed addition of this constraint to a constraints solver.
The default implementation tells each component to perform such actions.
Definition at line 74 of file dyn_body_constraint.cc.
References jeod::ConstraintComponent::attach_to_solver(), get_component(), jeod::DynBodyConstraintsSolver::get_dyn_body(), n_dimensions, and solver.
Referenced by set_solver().
compute_constraint_response()
void jeod::DynBodyConstraint::compute_constraint_response (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) virtual
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to external forces and torques, including the constraints.
Definition at line 146 of file dyn_body_constraint.cc.
References jeod::ConstraintComponent::compute_constraint_response(), get_component(), and n_dimensions.
deactivate()
void jeod::DynBodyConstraint::deactivate () virtual
Deactivate the constraint.
Reimplemented in jeod::DynBodyPendulumConstraint.
Definition at line 61 of file dyn_body_constraint.cc.
References jeod::DynBodyConstraintsSolver::deactivate_constraint(), inactive, and solver.
Referenced by jeod::DynBodyPendulumConstraint::deactivate().
detach_from_solver()
void jeod::DynBodyConstraint::detach_from_solver () protected virtual
Perform actions related to the just-performed removal of this constraint from a constraints solver.
The default implementation tells each component to perform such actions.
Definition at line 82 of file dyn_body_constraint.cc.
References jeod::ConstraintComponent::detach_from_solver(), get_component(), jeod::DynBodyConstraintsSolver::get_dyn_body(), n_dimensions, and solver.
Referenced by reset_solver().
get_component() [1/2]
virtual ConstraintComponent* jeod::DynBodyConstraint::get_component (unsigned index) pure virtual
Get the indexed component constraint for this composite constraint.
Parameters
index Index of the component constraint to be retrieved. This is not bounds-checked.
Returns
The indexed component constraint.
Implemented in jeod::DynBodyPendulumConstraint, and jeod::DynBodyAttachedBodyConstraint.
Referenced by attach_to_solver(), compute_constraint_response(), detach_from_solver(), get_component(), set_constraint_values(), set_cross_coeff(), set_r_h_s(), setup_component_constraint(), and update_component_attachment().
get_component() [2/2]
virtual const ConstraintComponent* jeod::DynBodyConstraint::get_component (unsigned index) const inline virtual
Const version of get_component().
Definition at line 203 of file dyn_body_constraint.hh.
References get_component().
get_constraint_wrench()
virtual const Wrench& jeod::DynBodyConstraint::get_constraint_wrench () const pure virtual
Get the wrench this constrained object exerts on the vehicle.
Returns
A const reference to the constraint wrench for this object.
Note
This function is called after the constraint values have been set.
Implemented in jeod::DynBodyPendulumConstraint, and jeod::DynBodyAttachedBodyConstraint.
Referenced by jeod::DynBodyConstraintsSolver::solve().
get_dyn_body()
DynBody * jeod::DynBodyConstraint::get_dyn_body () protected virtual
Get the dyn_body object associated with this constrained object.
Returns
The dyn_body object for this constraint.
Definition at line 155 of file dyn_body_constraint.cc.
References jeod::DynBodyConstraintsSolver::get_dyn_body(), and solver.
get_effector_wrench()
virtual const Wrench& jeod::DynBodyConstraint::get_effector_wrench () const pure virtual
Get the known wrench for this constrained object.
Returns
A const reference to the effector wrench for this object.
Note
This function is called prior to any calls to setup_constraint(), with the effects of all of the pre-constraint wrenches incorporated into the non_grav_state argument to that function.
Implemented in jeod::DynBodyPendulumConstraint, and jeod::DynBodyAttachedBodyConstraint.
Referenced by jeod::DynBodyConstraintsSolver::solve().
get_nonlinear_response_wrench()
virtual const Wrench& jeod::DynBodyConstraint::get_nonlinear_response_wrench () const pure virtual
Get the residual nonlinear wrench for this constrained object.
Returns
A const reference to the nonlinear wrench for this object.
Note
This function is called after calls to compute_constraint_response. The nonlinear aspects are assumed to be small; they are not taken into account while solving the constraints equation.
Implemented in jeod::DynBodyPendulumConstraint, and jeod::DynBodyAttachedBodyConstraint.
Referenced by jeod::DynBodyConstraintsSolver::solve().
get_solver()
virtual const DynBodyConstraintsSolver* jeod::DynBodyConstraint::get_solver () const inline virtual
Get the solver for this constrained object.
Returns
The solver for this constraint.
Definition at line 122 of file dyn_body_constraint.hh.
References solver.
is_active()
bool jeod::DynBodyConstraint::is_active () const inline
Is the constraint active?
Returns
True if the constraint is active.
Definition at line 113 of file dyn_body_constraint.hh.
References inactive.
Referenced by jeod::DynBodyConstraintsSolver::add_child_constraint(), and jeod::DynBodyConstraintsSolver::remove_child_constraint().
operator=()
DynBodyConstraint& jeod::DynBodyConstraint::operator= (const DynBodyConstraint &) delete
reset_solver()
void jeod::DynBodyConstraint::reset_solver () inline private
Clear the solver for this constraint.
Definition at line 378 of file dyn_body_constraint.hh.
References constraint_frame, detach_from_solver(), jeod::ConstraintFrame::solver, and solver.
set_constraint_values()
void jeod::DynBodyConstraint::set_constraint_values (const jeod::VectorView< double, double > & solution_slice) virtual
Set this constrained object's constraint values.
Parameters
solution_slice The solution to the matrix constraint equation for this constrained object, such that solution_slice[0] contains the constraint value for the zeroth component, etc.
Note
This function is called after the matrix constraint equation has been formulated and solved.
Reimplemented in jeod::DynBodyAttachedBodyConstraint.
Definition at line 138 of file dyn_body_constraint.cc.
References get_component(), n_dimensions, and jeod::ConstraintComponent::set_constraint_value().
Referenced by jeod::DynBodyAttachedBodyConstraint::set_constraint_values().
set_cross_coeff() [1/2]
void jeod::DynBodyConstraint::set_cross_coeff (const VehicleProperties & vehicle_properties, const DynBodyConstraint & other, jeod::MatrixView< double > & a_slice) const virtual
Set the constraint matrix elements that pertain to this constrained object with respect to some other constrained object.
Parameters
vehicle_properties Various vehicle properties.
other The other constrained object.
a_slice A view into the overall A matrix of the constraint equation, such that a_slice(0:n,0:m) represents the NxM submatrix that pertains to this constraint with respect to the other.
Definition at line 115 of file dyn_body_constraint.cc.
References get_component(), and n_dimensions.
Referenced by set_cross_coeff(), and set_self_coeff().
set_cross_coeff() [2/2]
virtual void jeod::DynBodyConstraint::set_cross_coeff (const VehicleProperties & vehicle_properties, const DynBodyConstraint & other, jeod::MatrixView< double > && a_slice) const inline virtual
So one can call set_cross_coeff with a temporary.
Parameters
vehicle_properties Various vehicle properties.
other The other constrained object.
a_slice See the lvalue reference version of this function.
Definition at line 247 of file dyn_body_constraint.hh.
References set_cross_coeff().
set_r_h_s() [1/2]
void jeod::DynBodyConstraint::set_r_h_s (jeod::VectorView< double > & rhs_slice) const virtual
Set the sum of the terms in the constraint equation that don't involve other constrained objects, expressed as the right hand side of the constraint equation.
Parameters
rhs_slice A view into the overall right hand side vector of the constraint equation, such that rhs_slice[0] corresponds to this composite constraint's first scalar constraint, etc.
Definition at line 107 of file dyn_body_constraint.cc.
References get_component(), jeod::ConstraintComponent::get_right_hand_side(), and n_dimensions.
Referenced by set_r_h_s().
set_r_h_s() [2/2]
virtual void jeod::DynBodyConstraint::set_r_h_s (jeod::VectorView< double > && rhs_slice) const inline virtual
So one can use set_r_h_s with a temporary.
Parameters
rhs_slice A temporary view into the overall right hand side vector of the constraint equation,
Definition at line 223 of file dyn_body_constraint.hh.
References set_r_h_s().
set_self_coeff() [1/2]
void jeod::DynBodyConstraint::set_self_coeff (const VehicleProperties & vehicle_properties, jeod::MatrixView< double > & a_slice) const virtual
Set the constraint matrix elements for this constraint object with respect to itself.
This oftentimes is set_cross_coeff(*this) plus the identity matrix, which is the default implementation.
Parameters
vehicle_properties Various vehicle properties.
a_slice A view into the overall A matrix of the constraint equation, such that a_slice(0:n,0:n) represents the NxN submatrix that pertains to this constraint with respect to itself.
Definition at line 129 of file dyn_body_constraint.cc.
References n_dimensions, and set_cross_coeff().
Referenced by set_self_coeff().
set_self_coeff() [2/2]
virtual void jeod::DynBodyConstraint::set_self_coeff (const VehicleProperties & vehicle_properties, jeod::MatrixView< double > && a_slice) const inline virtual
So one can call set_self_coeff with a temporary.
Parameters
vehicle_properties Various vehicle properties.
a_slice See the lvalue reference version of this function.
Definition at line 271 of file dyn_body_constraint.hh.
References set_self_coeff().
set_solver()
void jeod::DynBodyConstraint::set_solver (DynBodyConstraintsSolver * solver_in) inline private
Set the solver for this constraint.
Parameters
solver_in The solver.
Definition at line 368 of file dyn_body_constraint.hh.
References attach_to_solver(), constraint_frame, jeod::ConstraintFrame::solver, and solver.
Referenced by jeod::DynBodyConstraintsSolver::add_constraint().
set_struct_to_constraint_frame()
virtual void jeod::DynBodyConstraint::set_struct_to_constraint_frame (SolverTypes::ConstDecayedMatrix3x3T transform_in, SolverTypes::ConstDecayedVector3T offset_in) inline virtual
Set the relationship between the constraint frame and the immediate structural frame.
Parameters
transform_in The structure-to-constraint frame transform.
offset_in The position of the constraint frame origin, in structural frame coordinates.
Definition at line 135 of file dyn_body_constraint.hh.
References constraint_frame, and jeod::ConstraintFrame::set_struct_to_constraint_frame().
setup_component_constraint()
void jeod::DynBodyConstraint::setup_component_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state)
Send setup_constraint to each component.
Note
Instantiable derived classes should override setup_constraint. In that override, the derived class should call parent class(es) setup_constraint methods (in the proper order), and then call this function.
Definition at line 98 of file dyn_body_constraint.cc.
References get_component(), n_dimensions, and jeod::ConstraintComponent::setup_constraint().
Referenced by jeod::DynBodyAttachedBodyConstraint::setup_constraint().
setup_constraint()
virtual void jeod::DynBodyConstraint::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) pure virtual
Prepare this object for solving a constraint problem.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to non-constraint forces and torques, including the pre-constraint wrenches.
Note
This function is called prior to the calls to set_self_coeff(), set_cross_coeff(), and set_r_h_s().
Implemented in jeod::DynBodyPendulumConstraint, and jeod::DynBodyAttachedBodyConstraint.
update_attachment()
virtual void jeod::DynBodyConstraint::update_attachment (const VehicleProperties & vehicle_properties) inline virtual
Update information about the relation between this constraint and the root DynBody.
Parameters
vehicle_properties Various vehicle properties.
Reimplemented in jeod::DynBodyPendulumConstraint, and jeod::DynBodyAttachedBodyConstraint.
Definition at line 147 of file dyn_body_constraint.hh.
References constraint_frame, and jeod::ConstraintFrame::update_attachment().
Referenced by jeod::DynBodyAttachedBodyConstraint::update_attachment(), and jeod::DynBodyPendulumConstraint::update_attachment().
update_component_attachment()
void jeod::DynBodyConstraint::update_component_attachment (const VehicleProperties & vehicle_properties)
Send update_attachment to each component.
Note
Instantiable derived classes should override update_attachment. In that override, the derived class should call parent class(es) update_attachment methods (in the proper order), and then call this function.
Definition at line 90 of file dyn_body_constraint.cc.
References get_component(), n_dimensions, and jeod::ConstraintComponent::update_attachment().
Referenced by jeod::DynBodyAttachedBodyConstraint::update_attachment().
Friends And Related Function Documentation
DynBodyConstraintsSolver
friend class DynBodyConstraintsSolver friend
Definition at line 84 of file dyn_body_constraint.hh.
init_attrjeod__DynBodyConstraint
void init_attrjeod__DynBodyConstraint () friend
InputProcessor
friend class InputProcessor friend
Definition at line 84 of file dyn_body_constraint.hh.
Field Documentation
constraint_frame
ConstraintFrame jeod::DynBodyConstraint::constraint_frame protected
The reference frame associated with this constraint.
trick_units(–)
Definition at line 318 of file dyn_body_constraint.hh.
Referenced by jeod::DynBodyAttachedBodyConstraint::DynBodyAttachedBodyConstraint(), reset_solver(), set_solver(), set_struct_to_constraint_frame(), and update_attachment().
inactive
bool jeod::DynBodyConstraint::inactive {} protected
Is the constraint inactive? Note: This is expressed in the negative sense to support reduced Trick checkpointing.
trick_units(–)
Definition at line 335 of file dyn_body_constraint.hh.
Referenced by jeod::DynBodyPendulumConstraint::activate(), activate(), jeod::DynBodyPendulumConstraint::deactivate(), deactivate(), and is_active().
n_dimensions
unsigned jeod::DynBodyConstraint::n_dimensions {} protected
The number of active components associated with this constraint.
trick_units(–)
Definition at line 328 of file dyn_body_constraint.hh.
Referenced by attach_to_solver(), compute_constraint_response(), detach_from_solver(), jeod::DynBodyPendulumConstraint::DynBodyPendulumConstraint(), set_constraint_values(), set_cross_coeff(), set_r_h_s(), set_self_coeff(), setup_component_constraint(), and update_component_attachment().
solver
DynBodyConstraintsSolver* jeod::DynBodyConstraint::solver {} protected
The solver to which this constraint is assigned.
trick_units(–)
Definition at line 323 of file dyn_body_constraint.hh.
Referenced by activate(), attach_to_solver(), deactivate(), detach_from_solver(), get_dyn_body(), get_solver(), reset_solver(), set_solver(), and ~DynBodyConstraint().
The documentation for this class was generated from the following files:
dyn_body_constraint.hh
dyn_body_constraint.cc