JEOD: jeod::TreeLinks< Links, Container, Messages > Class Template Reference
jeod::TreeLinks< Links, Container, Messages > Class Template Reference
Encapsulates links (parent, children, siblings) between objects, in the form of a tree.
#include <tree_links.hh>
Public Member Functions
TreeLinks (Container &container_in, unsigned int path_size)
Non-default constructor.
virtual ~TreeLinks ()=default
Destructor.
TreeLinks ()=delete
TreeLinks (const TreeLinks &)=delete
TreeLinks & operator= (const TreeLinks &)=delete
Links * child_head ()
Iterator that points to the first child.
Links * child_tail ()
Iterator that points to the last child.
bool is_atomic ()
Is the body atomic – in other words, is it a leaf node?
bool has_children ()
Is the body non-atomic – in other words, does it have children?
bool is_root ()
Is the body a root node?
Container & container ()
Accessor for the container, non-const version.
const Container & container () const
Accessor for the container, const version.
Links * links_parent ()
Accessor for the parent links, non-const version.
const Links * links_parent () const
Accessor for the parent links, const version.
Container * parent ()
Accessor for the parent container, non-const version.
const Container * parent () const
Accessor for the parent container, const version.
Links * links_root ()
Accessor for the root links object, non-const version.
const Links * links_root () const
Accessor for the root links object, const version.
Container * root ()
Accessor for the root container object, non-const version.
const Container * root () const
Accessor for the root container object, const version.
unsigned int path_length () const
Return the length of the path_to_node_ vector.
unsigned int find_path_index (const Links &link) const
Find the index of the specified link in the path_to_node_.
Container * nth_from_root (unsigned int index)
Accessor for the nth_from_root frame, non-const version.
const Container * nth_from_root (unsigned int index) const
Accessor for the nth_from_root frame, const version.
void make_root ()
Make the links object a root object.
void attach (Links &new_parent)
Add this object as a child of the frame containing these links.
void detach ()
Detach a node from its parent.
void reattach (Links &new_parent)
Attach a node somewhere else.
bool is_progeny_of (const Links &target) const
Determine if a node is the progeny of another.
int find_last_common_index (const Links &target) const
Find the index of the node that represents the point of departure in the tree containing two nodes.
const Links * find_last_common_node (const Links &target) const
Find the node that represents the point of departure in the tree containing two nodes.
Protected Member Functions
void construct_path_to_node ()
Recursively construct the path_to_node.
Private Member Functions
void attach_internal (Links &new_parent)
Add a frame as a child of the frame containing these links.
void detach_internal ()
Detach a node from its parent.
void set_path_size (unsigned int new_size)
Ensures the path size is at least as large as specified, resizing the path_to_node array if needed.
Private Attributes
Container & container_
The object to which this set of links pertains; the container.
Links * parent_
The TreeLinks object that is the immediate parent of this TreeLinks object in the directed tree that contains this TreeLinks object.
std::vector< Links * > children_
The TreeLinks object's children.
std::vector< Links * > path_to_node_
Vector of pointers to TreeLinks nodes containing the sequence of links from the root node of the tree to this TreeLinks object.
Friends
class InputProcessor
template<class RLinks >
class TreeLinksAscendRange
template<class RLinks >
class TreeLinksDescentRange
template<class RLinks >
class TreeLinksChildrenRange
void init_attrjeod__TreeLinks ()
Detailed Description
template<class Links, class Container, class Messages>
class jeod::TreeLinks< Links, Container, Messages >
Encapsulates links (parent, children, siblings) between objects, in the form of a tree.
Template Parameters
Links The class being template-instantiated.
Container The class that contains a TreeLinks object.
Messages A message class; must contain a invalid_node element. This class must inherit from TreeLinks.
Usage
This template class is designed for use with the "curiously recurring template pattern". The template parameter Links must be a class that derives from TreeLinks: class DerivedClass : public TreeLinks<DerivedClass, Container, Messages>
Definition at line 100 of file tree_links.hh.
Constructor & Destructor Documentation
TreeLinks() [1/3]
template<class Links, class Container, class Messages> jeod::TreeLinks< Links, Container, Messages >::TreeLinks (Container & container_in, unsigned int path_size) inline
Non-default constructor.
Parameters
[in,out] container_in Object that contains this object
[in] path_size Initial size to reserve for the path
Definition at line 119 of file tree_links.hh.
~TreeLinks()
template<class Links, class Container, class Messages> virtual jeod::TreeLinks< Links, Container, Messages >::~TreeLinks () virtual default
Destructor.
TreeLinks() [2/3]
template<class Links, class Container, class Messages> jeod::TreeLinks< Links, Container, Messages >::TreeLinks () delete
TreeLinks() [3/3]
template<class Links, class Container, class Messages> jeod::TreeLinks< Links, Container, Messages >::TreeLinks (const TreeLinks< Links, Container, Messages > &) delete
Member Function Documentation
attach()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::attach (Links & new_parent) inline
Add this object as a child of the frame containing these links.
This object must have no parent, no siblings.
Parameters
new_parent Links object that is to be the parent of this object.
Definition at line 352 of file tree_links.hh.
Referenced by jeod::RefFrame::add_child(), jeod::JeodBaseTime::add_parent(), jeod::MassPoint::attach(), and jeod::MassBody::attach_establish_links().
attach_internal()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::attach_internal (Links & new_parent) inline private
Add a frame as a child of the frame containing these links.
Parameters
new_parent The node to which this object is to be attached.
Definition at line 524 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::attach(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::reattach().
child_head()
template<class Links, class Container, class Messages> Links* jeod::TreeLinks< Links, Container, Messages >::child_head () inline
Iterator that points to the first child.
Definition at line 149 of file tree_links.hh.
Referenced by jeod::DynBody::add_mass_body_frames(), and jeod::DynBody::detach_mass_body_frames().
child_tail()
template<class Links, class Container, class Messages> Links* jeod::TreeLinks< Links, Container, Messages >::child_tail () inline
Iterator that points to the last child.
Definition at line 157 of file tree_links.hh.
Referenced by jeod::DynBody::add_mass_body_frames(), jeod::DynBody::detach_mass_body_frames(), jeod::JeodBaseTime::~JeodBaseTime(), jeod::MassBody::~MassBody(), jeod::MassPoint::~MassPoint(), and jeod::RefFrame::~RefFrame().
construct_path_to_node()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::construct_path_to_node () inline protected
Recursively construct the path_to_node.
Definition at line 492 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::attach(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::detach(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::make_root(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::reattach().
container() [1/2]
template<class Links, class Container, class Messages> Container& jeod::TreeLinks< Links, Container, Messages >::container () inline
Accessor for the container, non-const version.
Returns
Object that contains this object.
Definition at line 196 of file tree_links.hh.
Referenced by jeod::DynBody::add_mass_body_frames(), jeod::DynBody::detach_mass_body_frames(), jeod::MassPoint::find_last_common_node(), jeod::RefFrame::find_last_common_node(), and jeod::MassBody::~MassBody().
container() [2/2]
template<class Links, class Container, class Messages> const Container& jeod::TreeLinks< Links, Container, Messages >::container () const inline
Accessor for the container, const version.
Returns
Object that contains this object.
Definition at line 205 of file tree_links.hh.
detach()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::detach (void) inline
Detach a node from its parent.
Definition at line 383 of file tree_links.hh.
Referenced by jeod::MassPoint::detach(), jeod::MassBody::detach_sever_links(), jeod::RefFrame::remove_from_parent(), jeod::JeodBaseTime::~JeodBaseTime(), jeod::MassPoint::~MassPoint(), and jeod::RefFrame::~RefFrame().
detach_internal()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::detach_internal () inline private
Detach a node from its parent.
Definition at line 537 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::detach(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::reattach().
find_last_common_index()
template<class Links, class Container, class Messages> int jeod::TreeLinks< Links, Container, Messages >::find_last_common_index (const Links & target) const inline
Find the index of the node that represents the point of departure in the tree containing two nodes.
Parameters
target Some other node in the tree
Returns
Index of the last common node
Definition at line 435 of file tree_links.hh.
Referenced by jeod::MassPoint::find_last_common_index(), jeod::RefFrame::find_last_common_index(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::find_last_common_node().
find_last_common_node()
template<class Links, class Container, class Messages> const Links* jeod::TreeLinks< Links, Container, Messages >::find_last_common_node (const Links & target) const inline
Find the node that represents the point of departure in the tree containing two nodes.
Parameters
target Some other node in the tree
Returns
Pointer to last common node
Definition at line 478 of file tree_links.hh.
Referenced by jeod::MassPoint::find_last_common_node(), and jeod::RefFrame::find_last_common_node().
find_path_index()
template<class Links, class Container, class Messages> unsigned int jeod::TreeLinks< Links, Container, Messages >::find_path_index (const Links & link) const inline
Find the index of the specified link in the path_to_node_.
Definition at line 299 of file tree_links.hh.
Referenced by jeod::MassPoint::compute_pred_rel_state(), jeod::RefFrame::compute_pred_rel_state(), jeod::MassPoint::compute_state_wrt_pred(), and jeod::RefFrame::compute_state_wrt_pred().
has_children()
template<class Links, class Container, class Messages> bool jeod::TreeLinks< Links, Container, Messages >::has_children () inline
Is the body non-atomic – in other words, does it have children?
Returns
True if the body has children, false otherwise.
Definition at line 176 of file tree_links.hh.
Referenced by jeod::DynBody::add_mass_body_frames(), jeod::DynBody::detach_mass_body_frames(), jeod::JeodBaseTime::~JeodBaseTime(), jeod::MassBody::~MassBody(), jeod::MassPoint::~MassPoint(), and jeod::RefFrame::~RefFrame().
is_atomic()
template<class Links, class Container, class Messages> bool jeod::TreeLinks< Links, Container, Messages >::is_atomic () inline
Is the body atomic – in other words, is it a leaf node?
Returns
True if the body has no children, false otherwise.
Definition at line 167 of file tree_links.hh.
Referenced by jeod::MassBody::update_mass_properties().
is_progeny_of()
template<class Links, class Container, class Messages> bool jeod::TreeLinks< Links, Container, Messages >::is_progeny_of (const Links & target) const inline
Determine if a node is the progeny of another.
Parameters
target Target links object
Returns
True if target is an ancestor of this node, false otherwise.
Definition at line 417 of file tree_links.hh.
Referenced by jeod::RefFrame::is_progeny_of().
is_root()
template<class Links, class Container, class Messages> bool jeod::TreeLinks< Links, Container, Messages >::is_root () inline
Is the body a root node?
Returns
True if the parent is null, false otherwise.
Definition at line 186 of file tree_links.hh.
Referenced by jeod::MassBody::attach_root_body(), jeod::MassBody::reattach(), jeod::MassBody::update_mass_properties(), and jeod::MassBody::~MassBody().
links_parent() [1/2]
template<class Links, class Container, class Messages> Links* jeod::TreeLinks< Links, Container, Messages >::links_parent () inline
Accessor for the parent links, non-const version.
Returns
Pointer to this object's parent TreeLinks object.
Definition at line 215 of file tree_links.hh.
links_parent() [2/2]
template<class Links, class Container, class Messages> const Links* jeod::TreeLinks< Links, Container, Messages >::links_parent () const inline
Accessor for the parent links, const version.
Returns
Pointer to this object's parent TreeLinks object.
Definition at line 224 of file tree_links.hh.
links_root() [1/2]
template<class Links, class Container, class Messages> Links* jeod::TreeLinks< Links, Container, Messages >::links_root () inline
Accessor for the root links object, non-const version.
Returns
Root links object
Definition at line 253 of file tree_links.hh.
links_root() [2/2]
template<class Links, class Container, class Messages> const Links* jeod::TreeLinks< Links, Container, Messages >::links_root () const inline
Accessor for the root links object, const version.
Returns
Root links object
Definition at line 262 of file tree_links.hh.
make_root()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::make_root (void) inline
Make the links object a root object.
Definition at line 332 of file tree_links.hh.
Referenced by jeod::RefFrame::make_root(), and jeod::TimeDyn::TimeDyn().
nth_from_root() [1/2]
template<class Links, class Container, class Messages> Container* jeod::TreeLinks< Links, Container, Messages >::nth_from_root (unsigned int index) inline
Accessor for the nth_from_root frame, non-const version.
Parameters
index Path index (root=0)
Returns
Nth links container
Definition at line 311 of file tree_links.hh.
Referenced by jeod::MassPoint::compute_relative_state(), and jeod::RefFrame::compute_relative_state().
nth_from_root() [2/2]
template<class Links, class Container, class Messages> const Container* jeod::TreeLinks< Links, Container, Messages >::nth_from_root (unsigned int index) const inline
Accessor for the nth_from_root frame, const version.
Parameters
index Path index (root=0)
Returns
Nth links container
Definition at line 322 of file tree_links.hh.
operator=()
template<class Links, class Container, class Messages> TreeLinks& jeod::TreeLinks< Links, Container, Messages >::operator= (const TreeLinks< Links, Container, Messages > &) delete
parent() [1/2]
template<class Links, class Container, class Messages> Container* jeod::TreeLinks< Links, Container, Messages >::parent () inline
Accessor for the parent container, non-const version.
Returns
Pointer to this object's parent Container object.
Definition at line 234 of file tree_links.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::JeodBaseTime::add_type_update(), jeod::MassBody::attach_to(), jeod::MassBody::detach(), jeod::RefFrame::get_parent(), jeod::MassBody::get_parent_body(), jeod::MassBody::get_parent_body_internal(), and jeod::MassBody::reattach().
parent() [2/2]
template<class Links, class Container, class Messages> const Container* jeod::TreeLinks< Links, Container, Messages >::parent () const inline
Accessor for the parent container, const version.
Returns
Pointer to this object's parent Container object.
Definition at line 243 of file tree_links.hh.
path_length()
template<class Links, class Container, class Messages> unsigned int jeod::TreeLinks< Links, Container, Messages >::path_length () const inline
Return the length of the path_to_node_ vector.
Definition at line 290 of file tree_links.hh.
Referenced by jeod::RefFrame::compute_position_from(), jeod::MassPoint::compute_pred_rel_state(), jeod::RefFrame::compute_pred_rel_state(), jeod::MassPoint::compute_state_wrt_pred(), jeod::RefFrame::compute_state_wrt_pred(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::find_last_common_index(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::nth_from_root().
reattach()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::reattach (Links & new_parent) inline
Attach a node somewhere else.
Parameters
new_parent Links object that is to be the parent of this object.
Definition at line 397 of file tree_links.hh.
Referenced by jeod::RefFrame::reset_parent(), and jeod::RefFrame::transplant_node().
root() [1/2]
template<class Links, class Container, class Messages> Container* jeod::TreeLinks< Links, Container, Messages >::root () inline
Accessor for the root container object, non-const version.
Returns
Root container object
Definition at line 272 of file tree_links.hh.
Referenced by jeod::RefFrame::get_root(), jeod::MassBody::get_root_body(), and jeod::MassBody::get_root_body_internal().
root() [2/2]
template<class Links, class Container, class Messages> const Container* jeod::TreeLinks< Links, Container, Messages >::root () const inline
Accessor for the root container object, const version.
Returns
Root container object
Definition at line 281 of file tree_links.hh.
set_path_size()
template<class Links, class Container, class Messages> void jeod::TreeLinks< Links, Container, Messages >::set_path_size (unsigned int new_size) inline private
Ensures the path size is at least as large as specified, resizing the path_to_node array if needed.
Parameters
new_size Requested size
Definition at line 556 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::construct_path_to_node(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::TreeLinks().
Friends And Related Function Documentation
init_attrjeod__TreeLinks
template<class Links, class Container, class Messages> void init_attrjeod__TreeLinks () friend
InputProcessor
template<class Links, class Container, class Messages> friend class InputProcessor friend
Definition at line 102 of file tree_links.hh.
TreeLinksAscendRange
template<class Links, class Container, class Messages> template<class RLinks > friend class TreeLinksAscendRange friend
Definition at line 106 of file tree_links.hh.
TreeLinksChildrenRange
template<class Links, class Container, class Messages> template<class RLinks > friend class TreeLinksChildrenRange friend
Definition at line 108 of file tree_links.hh.
TreeLinksDescentRange
template<class Links, class Container, class Messages> template<class RLinks > friend class TreeLinksDescentRange friend
Definition at line 107 of file tree_links.hh.
Field Documentation
children_
template<class Links, class Container, class Messages> std::vector<Links*> jeod::TreeLinks< Links, Container, Messages >::children_ private
The TreeLinks object's children.
trick_units(–)
Definition at line 581 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::child_head(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::child_tail(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::construct_path_to_node(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::has_children(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::is_atomic().
container_
template<class Links, class Container, class Messages> Container& jeod::TreeLinks< Links, Container, Messages >::container_ private
The object to which this set of links pertains; the container.
trick_units(–)
Definition at line 569 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::container().
parent_
template<class Links, class Container, class Messages> Links* jeod::TreeLinks< Links, Container, Messages >::parent_ private
The TreeLinks object that is the immediate parent of this TreeLinks object in the directed tree that contains this TreeLinks object.
This pointer is null for all root objects.trick_units(–)
Definition at line 576 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::attach(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::attach_internal(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::construct_path_to_node(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::detach_internal(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::is_root(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::links_parent(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::make_root(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::parent().
path_to_node_
template<class Links, class Container, class Messages> std::vector<Links*> jeod::TreeLinks< Links, Container, Messages >::path_to_node_ private
Vector of pointers to TreeLinks nodes containing the sequence of links from the root node of the tree to this TreeLinks object.
The path_to_node_ remains empty until the links object is made viable by either a call to attach() or to make_root(). The zeroth element of this array is the root object. The last element is this node.trick_units(–)
Definition at line 591 of file tree_links.hh.
Referenced by jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::attach(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::construct_path_to_node(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::find_last_common_index(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::find_last_common_node(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::find_path_index(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::is_progeny_of(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::links_root(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::nth_from_root(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::path_length(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::root(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::set_path_size(), and jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::TreeLinks().
The documentation for this class was generated from the following file:
tree_links.hh