JEOD: jeod::DynamicsIntegrationGroup Class Reference
jeod::DynamicsIntegrationGroup Class Reference
A DynamicsIntegrationGroup integrates the state of a set of DynBoby objects over time.
#include <dynamics_integration_group.hh>
Public Member Functions
DynamicsIntegrationGroup ()
DynamicsIntegrationGroup default constructor, needed for checkpoint/restart.
DynamicsIntegrationGroup (JeodIntegrationGroupOwner &owner, er7_utils::IntegratorConstructor &integ_cotr, JeodIntegratorInterface &integ_inter, JeodIntegrationTime &time_mngr)
DynamicsIntegrationGroup non-default constructor, used to create the default integration group.
~DynamicsIntegrationGroup () override
DynamicsIntegrationGroup destructor.
bool is_empty (void) const
Query whether the group is void of registered bodies.
virtual DynamicsIntegrationGroup * create_group (JeodIntegrationGroupOwner &owner, er7_utils::IntegratorConstructor &integ_cotr, JeodIntegratorInterface &integ_inter, JeodIntegrationTime &time_mngr) const
Create an integration group object that can be used as the dynamic manager's default integration group.
virtual void register_group (DynManager &dyn_manager)
Pre-initialize the group and register it with the dynamics manager.
virtual void initialize_group (DynManager &dyn_manager)
Complete the initialization of the group.
virtual void prepare_for_integ_loop (double sim_endtime)
Perform actions that need to be taken before entering the derivative / integration loop.
virtual void gravitation (DynManager &dyn_manager, GravityManager &gravity_manager)
Compute the gravitational acceleration of each root dynamic body.
virtual void collect_derivatives (void)
Collect the forces and torques acting on each root dynamic body.
er7_utils::IntegratorResult integrate_bodies (double cycle_dyndt, unsigned int target_stage) override
Integrate the states of the DynBody objects that comprise the group.
virtual void add_dyn_body (DynBody &body)
Add a DynBody to the set of bodies whose states are integrated by this group.
virtual void delete_dyn_body (DynBody &body)
Remove a DynBody from the set of bodies whose states are integrated by this group.
void initialize_group () override
Initialize the integration group.
Public Member Functions inherited from jeod::JeodIntegrationGroup
JeodIntegrationGroup ()
JeodIntegrationGroup default constructor, needed for checkpoint/restart, and to support derived classes' default constructors.
JeodIntegrationGroup (JeodIntegrationGroupOwner &owner, er7_utils::IntegratorConstructor &integ_cotr, JeodIntegratorInterface &integ_inter, JeodIntegrationTime &time_mngr)
JeodIntegrationGroup non-default constructor.
~JeodIntegrationGroup () override
JeodIntegrationGroup destructor.
bool need_first_step_derivatives (void) const
Indicate whether derivatives need to be calculated on the initial step of an integration cycle.
void update_from_owner (void)
Update the group via its owner.
bool merge_integrator_result (const er7_utils::IntegratorResult &new_result, er7_utils::IntegratorResult &merged_result) const
Merge an IntegratorResult into another.
void respond_to_time_change () override
Respond to a change in the nature of time.
void initialize_group () override
Initialize the integration group.
void reset_body_integrators (void) override
Reset the integrators for the integrable objects managed by this group.
er7_utils::IntegratorResult integrate_bodies (double cycle_dyndt, unsigned int target_stage) override
Integrate the states of the integrable objects managed by this group.
virtual void add_integrable_object (er7_utils::IntegrableObject &integrable_object)
Add an integrable object to the vector of such.
virtual void remove_integrable_object (er7_utils::IntegrableObject &integrable_object)
Remove an integrable object from the vector of such.
Public Member Functions inherited from jeod::TimeChangeSubscriber
virtual ~TimeChangeSubscriber ()
Destructor.
Data Fields
bool deriv_ephem_update
Update ephemerides at the derivative rate?
Protected Member Functions
void reset_body_integrators (void) override
Force all integrators to reset themselves.
Protected Member Functions inherited from jeod::JeodIntegrationGroup
template<typename T >
void reset_container (const T &container)
Issue a reset to each member of a container.
template<typename T >
er7_utils::IntegratorResult integrate_container (double dyn_dt, unsigned int target_stage, const T &container)
Integrate each member of a collection.
Protected Attributes
JeodPointerVector< DynBody >::type dyn_bodies
List of vehicles whose state is integrated by this group.
bool bodies_integrated_separately
This flag is always true for JEOD integration groups.
Protected Attributes inherited from jeod::JeodIntegrationGroup
JeodIntegrationGroupOwner *const group_owner
The object that owns this integration group, typically by containment.
er7_utils::IntegratorResultMergerContainer integ_merger
The object that merges results from multiple integrators.
JeodIntegratorInterface *const jeod_integ_interface
The interface between the integration module and the simulation engine's integration structure.
JeodIntegrationTime *const jeod_time_manager
The interface between the integration module and the object that represents time.
JeodPointerVector< er7_utils::IntegrableObject >::type integrable_objects
The objects whose states are integrated by this integration group.
Private Member Functions
void register_base_contents (void)
Register types and containers.
DynamicsIntegrationGroup (const DynamicsIntegrationGroup &)
Not implemented.
DynamicsIntegrationGroup & operator= (const DynamicsIntegrationGroup &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__DynamicsIntegrationGroup ()
Additional Inherited Members
Static Public Member Functions inherited from jeod::JeodIntegrationGroup
static void register_classes ()
Register classes associated with integration.
Detailed Description
A DynamicsIntegrationGroup integrates the state of a set of DynBoby objects over time.
The class provides implementations of all virtual functions listed below and the pure virtuals defined in the base class. This class is designed for extensibility. Authors of derived classes should follow the extension notes in the source file.
Definition at line 91 of file dynamics_integration_group.hh.
Constructor & Destructor Documentation
DynamicsIntegrationGroup() [1/3]
jeod::DynamicsIntegrationGroup::DynamicsIntegrationGroup ()
DynamicsIntegrationGroup default constructor, needed for checkpoint/restart.
Definition at line 55 of file dynamics_integration_group.cc.
References register_base_contents().
DynamicsIntegrationGroup() [2/3]
jeod::DynamicsIntegrationGroup::DynamicsIntegrationGroup (JeodIntegrationGroupOwner & owner, er7_utils::IntegratorConstructor & integ_cotr, JeodIntegratorInterface & integ_inter, JeodIntegrationTime & time_mngr) explicit
DynamicsIntegrationGroup non-default constructor, used to create the default integration group.
Parameters
[in] owner The new group's owner
[in] integ_cotr Integrator constructor
[in] integ_inter Simulation engine integration interface
[in] time_mngr Time manager
Definition at line 74 of file dynamics_integration_group.cc.
References register_base_contents().
~DynamicsIntegrationGroup()
jeod::DynamicsIntegrationGroup::~DynamicsIntegrationGroup () override
DynamicsIntegrationGroup destructor.
Definition at line 103 of file dynamics_integration_group.cc.
References dyn_bodies, and JEOD_DEREGISTER_CHECKPOINTABLE.
DynamicsIntegrationGroup() [3/3]
jeod::DynamicsIntegrationGroup::DynamicsIntegrationGroup (const DynamicsIntegrationGroup &) private
Not implemented.
Member Function Documentation
add_dyn_body()
void jeod::DynamicsIntegrationGroup::add_dyn_body (DynBody & dyn_body) virtual
Add a DynBody to the set of bodies whose states are integrated by this group.
Parameters
dyn_body DynBody to be added to the group.
Definition at line 191 of file dynamics_integration_group.cc.
References jeod::JeodIntegrationGroup::add_integrable_object(), bodies_integrated_separately, jeod::NamedItem::c_str(), jeod::DynBody::create_body_integrators(), jeod::DynManagerMessages::duplicate_entry, dyn_bodies, jeod::MessageHandler::error(), jeod::DynBody::get_integrable_objects(), jeod::JeodIntegrationGroup::jeod_time_manager, and jeod::DynBody::name.
Referenced by jeod::JeodDynbodyIntegrationLoop::add_sim_object_bodies(), and jeod::DynManager::update_integration_group().
collect_derivatives()
void jeod::DynamicsIntegrationGroup::collect_derivatives (void) virtual
Collect the forces and torques acting on each root dynamic body.
Definition at line 334 of file dynamics_integration_group.cc.
References jeod::DynBody::collect_forces_and_torques(), dyn_bodies, and jeod::DynBody::is_root_body().
Referenced by jeod::JeodDynbodyIntegrationLoop::collect_derivatives(), and jeod::DynManager::compute_derivatives().
create_group()
DynamicsIntegrationGroup * jeod::DynamicsIntegrationGroup::create_group (JeodIntegrationGroupOwner & owner, er7_utils::IntegratorConstructor & integ_cotr, JeodIntegratorInterface & integ_inter, JeodIntegrationTime & time_mngr) const virtual
Create an integration group object that can be used as the dynamic manager's default integration group.
Parameters
[in] owner The new group's owner
[in] integ_cotr Integrator constructor
[in] integ_inter Simulation engine integration interface
[in] time_mngr Time manager
Returns
Created DynamicsIntegrationGroup.
Definition at line 119 of file dynamics_integration_group.cc.
References JEOD_ALLOC_CLASS_OBJECT.
Referenced by jeod::JeodDynbodyIntegrationLoop::initialize_integ_loop(), and jeod::DynManager::initialize_model_internal().
delete_dyn_body()
void jeod::DynamicsIntegrationGroup::delete_dyn_body (DynBody & dyn_body) virtual
Remove a DynBody from the set of bodies whose states are integrated by this group.
Parameters
dyn_body DynBody to be removed from the group.
Definition at line 250 of file dynamics_integration_group.cc.
References jeod::NamedItem::c_str(), dyn_bodies, jeod::MessageHandler::error(), jeod::DynManagerMessages::inconsistent_setup, and jeod::DynBody::name.
Referenced by jeod::JeodDynbodyIntegrationLoop::remove_sim_object_bodies().
gravitation()
void jeod::DynamicsIntegrationGroup::gravitation (DynManager & dyn_manager, GravityManager & gravity_manager) virtual
Compute the gravitational acceleration of each root dynamic body.
Parameters
dyn_manager Dynamics manager.
gravity_manager Gravity Manager.
Definition at line 301 of file dynamics_integration_group.cc.
References jeod::DynBody::composite_body, deriv_ephem_update, dyn_bodies, jeod::DynBody::grav_interaction, jeod::GravityManager::gravitation(), jeod::DynBody::is_root_body(), jeod::EphemeridesManager::ref_frame_tree_needs_rebuild(), and jeod::EphemeridesManager::update_ephemerides().
Referenced by jeod::DynManager::gravitation(), and jeod::JeodDynbodyIntegrationLoop::gravitation().
initialize_group() [1/2]
void jeod::DynamicsIntegrationGroup::initialize_group (DynManager & dyn_manager) virtual
Complete the initialization of the group.
For overriders: This function is called by DynManager::initialize_simulation. At the point of this call, the dyn_bodies vector is populated with the bodies that are to be integrated by this group. Note well: That vector can still be empty.
Definition at line 158 of file dynamics_integration_group.cc.
References bodies_integrated_separately, jeod::DynBody::create_body_integrators(), dyn_bodies, jeod::MessageHandler::fail(), jeod::JeodIntegrationGroup::initialize_group(), jeod::JeodIntegrationGroup::jeod_time_manager, jeod::DynManagerMessages::null_pointer, and jeod::JeodIntegrationGroup::update_from_owner().
Referenced by jeod::DynManager::initialize_integ_groups().
initialize_group() [2/2]
void jeod::JeodIntegrationGroup::initialize_group override
Initialize the integration group.
Some integration techniques are configurable by user input, and thus the creation of the controls and integrators needs to be delayed a bit.
Definition at line 176 of file jeod_integration_group.cc.
integrate_bodies()
er7_utils::IntegratorResult jeod::DynamicsIntegrationGroup::integrate_bodies (double cycle_dyndt, unsigned int target_stage) override
Integrate the states of the DynBody objects that comprise the group.
Parameters
[in] cycle_dyndt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 381 of file dynamics_integration_group.cc.
References bodies_integrated_separately, dyn_bodies, jeod::MessageHandler::fail(), jeod::DynManagerMessages::inconsistent_setup, jeod::JeodIntegrationGroup::integ_merger, jeod::JeodIntegrationGroup::integrable_objects, jeod::DynBody::integrate(), jeod::JeodIntegrationGroup::integrate_container(), and jeod::DynBody::is_root_body().
is_empty()
bool jeod::DynamicsIntegrationGroup::is_empty (void) const inline
Query whether the group is void of registered bodies.
Returns
True if group is empty, false otherwise.
Definition at line 132 of file dynamics_integration_group.hh.
References dyn_bodies.
operator=()
DynamicsIntegrationGroup& jeod::DynamicsIntegrationGroup::operator= (const DynamicsIntegrationGroup &) private
Not implemented.
prepare_for_integ_loop()
void jeod::DynamicsIntegrationGroup::prepare_for_integ_loop (double sim_endtime) virtual
Perform actions that need to be taken before entering the derivative / integration loop.
The base action is to set the time model to the time at the start of the integration loop.
Parameters
sim_endtime End time of integration loop.
Definition at line 288 of file dynamics_integration_group.cc.
References jeod::JeodIntegrationGroup::jeod_time_manager.
register_base_contents()
void jeod::DynamicsIntegrationGroup::register_base_contents (void) private
Register types and containers.
Definition at line 93 of file dynamics_integration_group.cc.
References dyn_bodies, JEOD_REGISTER_CHECKPOINTABLE, and JEOD_REGISTER_CLASS.
Referenced by DynamicsIntegrationGroup().
register_group()
void jeod::DynamicsIntegrationGroup::register_group (DynManager & dyn_manager) virtual
Pre-initialize the group and register it with the dynamics manager.
This function is to be called early in the initialization process. Overrides should not depend on the dyn_bodies vector having any members.
Parameters
[in] dyn_manager Dynamics manager.
Definition at line 139 of file dynamics_integration_group.cc.
References jeod::DynManager::add_integ_group(), and jeod::DynManager::is_integ_group_registered().
reset_body_integrators()
void jeod::DynamicsIntegrationGroup::reset_body_integrators (void) override protected
Force all integrators to reset themselves.
Definition at line 358 of file dynamics_integration_group.cc.
References dyn_bodies, jeod::JeodIntegrationGroup::reset_body_integrators(), and jeod::DynBody::reset_integrators().
Friends And Related Function Documentation
init_attrjeod__DynamicsIntegrationGroup
void init_attrjeod__DynamicsIntegrationGroup () friend
InputProcessor
friend class InputProcessor friend
Definition at line 92 of file dynamics_integration_group.hh.
Field Documentation
bodies_integrated_separately
bool jeod::DynamicsIntegrationGroup::bodies_integrated_separately protected
This flag is always true for JEOD integration groups.
Setting this flag to false results in bypassing the call in DynamicsIntegrationGroup::add_dyn_body to DynBody::create_body_integrators. This hook exists for derived classes that override DynamicsIntegrationGroup::integrate_bodies in a way that does not involve calling DynBody::integrate.trick_units(–)
Definition at line 238 of file dynamics_integration_group.hh.
Referenced by add_dyn_body(), initialize_group(), and integrate_bodies().
deriv_ephem_update
bool jeod::DynamicsIntegrationGroup::deriv_ephem_update
Update ephemerides at the derivative rate?
trick_units(–)
Definition at line 207 of file dynamics_integration_group.hh.
Referenced by jeod::DynManager::gravitation(), gravitation(), jeod::JeodDynbodyIntegrationLoop::initialize_integ_loop(), and jeod::JeodDynbodyIntegrationLoop::set_deriv_ephem_update().
dyn_bodies
JeodPointerVector<DynBody>::type jeod::DynamicsIntegrationGroup::dyn_bodies protected
List of vehicles whose state is integrated by this group.
trick_io(**)
Definition at line 228 of file dynamics_integration_group.hh.
Referenced by add_dyn_body(), collect_derivatives(), delete_dyn_body(), gravitation(), initialize_group(), integrate_bodies(), is_empty(), register_base_contents(), reset_body_integrators(), and ~DynamicsIntegrationGroup().
The documentation for this class was generated from the following files:
dynamics_integration_group.hh
dynamics_integration_group.cc