JEOD: jeod::Orientation Class Reference
jeod::Orientation Class Reference
Specifies the orientiation of one reference frame with respect to another.
#include <orientation.hh>
Public Types
enum DataSource {
InputNone = -1, InputMatrix = 0, InputQuaternion = 1, InputEigenRotation = 2,
InputEulerRotation = 3
}
Specifies which representation has been input by the user.
enum EulerSequence {
NoSequence = -1, EulerXYZ = 0, EulerXZY = 1, EulerYZX = 2,
EulerYXZ = 3, EulerZXY = 4, EulerZYX = 5, EulerXYX = 6,
EulerXZX = 7, EulerYZY = 8, EulerYXY = 9, EulerZXZ = 10,
EulerZYZ = 11, Roll_Pitch_Yaw = 0, Roll_Yaw_Pitch = 1, Pitch_Yaw_Roll = 2,
Pitch_Roll_Yaw = 3, Yaw_Roll_Pitch = 4, Yaw_Pitch_Roll = 5, RollPitchYaw = 0,
RollYawPitch = 1, PitchYawRoll = 2, PitchRollYaw = 3, YawRollPitch = 4,
YawPitchRoll = 5
}
Identifies which type of Euler sequence has been specified.
Public Member Functions
Orientation (void)
Construct an Orientation instance.
Orientation (const double trans_in[3][3])
Construct an Orientation instance from a transformation matrix.
Orientation (const Quaternion &quat_in)
Construct an Orientation instance from a Quaternion.
Orientation (double eigen_angle_in, const double eigen_axis[3])
Construct an Orientation instance from an eigen rotation.
Orientation (EulerSequence sequence_in, const double angles_in[3])
Construct an Orientation instance from an Euler rotation.
virtual ~Orientation (void)
Destruct an Orientation instance.
virtual void reset (void)
Forget that we have any data.
virtual void compute_transform (void)
Compute the transformation matrix from the source.
virtual void compute_quaternion (void)
Compute the left transformation quaternion from the source.
virtual void compute_eigen_rotation (void)
Compute the eigen rotation from the source.
virtual void compute_euler_angles (void)
Compute the eigen rotation from the source.
virtual void compute_all_products (void)
Compute all represented charts on SO3 from the specified source.
virtual void compute_transformation_and_quaternion (void)
Compute the transformation matrix and quaternion.
void set_quaternion (const Quaternion &quat)
Reset the instance with a new quaternion.
void get_quaternion (Quaternion &quat)
Accessor for the left transformation quaternion.
void set_transform (const double trans[3][3])
Reset the instance with a new matrix.
void get_transform (double trans[3][3])
Accessor for the transformation matrix.
void set_eigen_rotation (double eigen_angle, const double eigen_axis[3])
Reset the instance with a new eigen rotation.
void get_eigen_rotation (double *eigen_angle, double eigen_axis[3])
Accessor for the eigen rotation.
void set_euler_angles (EulerSequence sequence, const double angles[3])
Reset the instance with a new Euler rotation.
void set_euler_angles (const double angles[3])
Reset the instance with a new Euler rotation.
void get_euler_angles (EulerSequence *sequence, double angles[3])
Accessor for the Euler angles.
void get_euler_angles (double angles[3])
Accessor for the Euler angles.
EulerSequence get_euler_sequence (void)
Accessor for the Euler sequence data member.
void set_euler_sequence (EulerSequence sequence)
Set the euler_sequence data member.
void clear_euler_sequence (void)
Reset the euler_sequence data member.
Static Public Member Functions
static void compute_quaternion_from_euler_angles (EulerSequence sequence, const double angles[3], Quaternion &quat)
Compute the left transformation quaternion from the Euler sequence.
static void compute_matrix_from_euler_angles (EulerSequence sequence, const double angles[3], double trans[3][3])
Compute the transformation matrix from the Euler sequence.
static void compute_euler_angles_from_matrix (const double trans[3][3], EulerSequence sequence, double angles[3])
Extract an Euler sequence from the transformation matrix.
static void compute_matrix_from_eigen_rotation (double eigen_angle, const double eigen_axis[3], double trans[3][3])
Compute the transformation matrix from the eigen rotation.
static void compute_eigen_rotation_from_matrix (const double trans[3][3], double *eigen_angle, double eigen_axis[3])
Compute the eigen rotation from the transformation matrix.
Data Fields
DataSource data_source
Orientation data source – specifies whether the user has provided as input an Euler rotation, a transformation matrix, or a left transformation quaternion.
EulerSequence euler_sequence
The Euler rotation sequence corresponding to euler_angles.
double euler_angles [3]
Euler angles corresponding to rotation sequence euler_sequence.
double trans [3][3]
Transformation matrix.
Quaternion quat
Left transformation unit quaternion.
double eigen_angle
Single axis rotation angle.
double eigen_axis [3]
Single axis rotation axis unit vector.
Protected Member Functions
void mark_input_as_available ()
Mark the item specified by the data_source as available.
void compute_quaternion_from_euler_angles (void)
Compute the left transformation quaternion that corresponds to the provided Euler rotation sequence.
void compute_matrix_from_euler_angles (void)
Compute the transformation matrix that corresponds to the provided Euler rotation sequence.
void compute_euler_angles_from_matrix (void)
Compute an Euler rotation sequence that corresponds to the provided transformation matrix.
void compute_matrix_from_eigen_rotation (void)
Compute the transformation matrix that corresponds to the provided eigen rotation.
void compute_eigen_rotation_from_matrix (void)
Compute a eigen rotation that corresponds to the provided transformation matrix.
Protected Attributes
bool have_transformation_
True if transformation matrix has been set/computed.
bool have_quaternion_
True if quaternion has been set/computed.
bool have_eigen_rotation_
True if eigen rotation has been set/computed.
bool have_euler_angles_
True if an Euler rotation has been set/computed.
Static Protected Attributes
static double gimbal_lock_threshold = 1e-13
Threshold for detecting gimbal lock in compute_euler_angles_from_matrix.
Friends
class InputProcessor
void init_attrjeod__Orientation ()
Detailed Description
Specifies the orientiation of one reference frame with respect to another.
There are many competing charts on the rotation group. This class provides means for representing rotations as Euler rotations, transformation matrices, left transformation quaternions, and eigen rotations. The class also provides mechanisms for converting these representations into the alternative representations.
Definition at line 81 of file orientation.hh.
Member Enumeration Documentation
DataSource
enum jeod::Orientation::DataSource
Specifies which representation has been input by the user.
Enumerator
InputNone
No source specified.
InputMatrix
Transformation matrices supplied by user.
InputQuaternion
Quaternions supplied by user.
InputEigenRotation
Single axis rotation supplied by user.
InputEulerRotation
Euler sequence and angles supplied by user.
Definition at line 91 of file orientation.hh.
EulerSequence
enum jeod::Orientation::EulerSequence
Identifies which type of Euler sequence has been specified.
Enumerator
NoSequence
No sequence specified.
EulerXYZ
XYX sequence (roll pitch yaw)
EulerXZY
XZY sequence (roll yaw pitch)
EulerYZX
YZX sequence (pitch yaw roll)
EulerYXZ
YXZ sequence (pitch roll yaw)
EulerZXY
ZXY sequence (yaw roll pitch)
EulerZYX
ZYX sequence (yaw pitch roll)
EulerXYX
XYX sequence.
EulerXZX
XZX sequence.
EulerYZY
YZY sequence.
EulerYXY
YXY sequence.
EulerZXZ
The canonical ZXZ Euler sequence.
EulerZYZ
ZYZ sequence.
Roll_Pitch_Yaw
XYX sequence (roll pitch yaw)
Roll_Yaw_Pitch
XZY sequence (roll yaw pitch)
Pitch_Yaw_Roll
YZX sequence (pitch yaw roll)
Pitch_Roll_Yaw
YXZ sequence (pitch roll yaw)
Yaw_Roll_Pitch
ZXY sequence (yaw roll pitch)
Yaw_Pitch_Roll
ZYX sequence (yaw pitch roll)
RollPitchYaw
XYX sequence (roll pitch yaw)
RollYawPitch
XZY sequence (roll yaw pitch)
PitchYawRoll
YZX sequence (pitch yaw roll)
PitchRollYaw
YXZ sequence (pitch roll yaw)
YawRollPitch
ZXY sequence (yaw roll pitch)
YawPitchRoll
ZYX sequence (yaw pitch roll)
Definition at line 103 of file orientation.hh.
Constructor & Destructor Documentation
Orientation() [1/5]
jeod::Orientation::Orientation (void)
Construct an Orientation instance.
All data products are marked as unavailable, the two enum values are set to invalid values, and the composite elements are set to their default values.
Definition at line 69 of file orientation.cc.
References eigen_axis, euler_angles, jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), and trans.
Orientation() [2/5]
jeod::Orientation::Orientation (const double trans_in[3][3]) explicit
Construct an Orientation instance from a transformation matrix.
Parameters
[in] trans_in Transformation matrix
Definition at line 94 of file orientation.cc.
References jeod::Matrix3x3::copy(), eigen_axis, euler_angles, jeod::Vector3::initialize(), and trans.
Orientation() [3/5]
jeod::Orientation::Orientation (const Quaternion & quat_in) explicit
Construct an Orientation instance from a Quaternion.
Parameters
[in] quat_in Quaternion
Definition at line 120 of file orientation.cc.
References eigen_axis, euler_angles, jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), and trans.
Orientation() [4/5]
jeod::Orientation::Orientation (double eigen_angle_in, const double eigen_axis_in[3]) explicit
Construct an Orientation instance from an eigen rotation.
Parameters
[in] eigen_angle_in Rotation angle
Units: r
[in] eigen_axis_in Rotation axis, unit vector
Definition at line 146 of file orientation.cc.
References jeod::Vector3::copy(), eigen_axis, euler_angles, jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), and trans.
Orientation() [5/5]
jeod::Orientation::Orientation (EulerSequence sequence_in, const double angles_in[3]) explicit
Construct an Orientation instance from an Euler rotation.
Parameters
[in] sequence_in Euler sequence
[in] angles_in Euler angles
Units: r
Definition at line 174 of file orientation.cc.
References jeod::Vector3::copy(), eigen_axis, euler_angles, jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), and trans.
~Orientation()
jeod::Orientation::~Orientation (void) virtual
Destruct an Orientation instance.
This is intentionally null; this class doesn't allocate resources.
Definition at line 201 of file orientation.cc.
Member Function Documentation
clear_euler_sequence()
void jeod::Orientation::clear_euler_sequence (void)
Reset the euler_sequence data member.
Issues arise if the data source is the Euler rotation sequence. The resolution is to preserve the existing input elsewhere.
Definition at line 906 of file orientation.cc.
References compute_matrix_from_euler_angles(), compute_quaternion_from_euler_angles(), data_source, euler_sequence, have_euler_angles_, have_quaternion_, have_transformation_, InputEulerRotation, InputMatrix, and NoSequence.
Referenced by set_euler_sequence().
compute_all_products()
void jeod::Orientation::compute_all_products (void) virtual
Compute all represented charts on SO3 from the specified source.
Definition at line 552 of file orientation.cc.
References compute_eigen_rotation(), compute_euler_angles(), compute_quaternion(), and compute_transform().
compute_eigen_rotation()
void jeod::Orientation::compute_eigen_rotation (void) virtual
Compute the eigen rotation from the source.
Definition at line 425 of file orientation.cc.
References compute_eigen_rotation_from_matrix(), compute_matrix_from_euler_angles(), data_source, eigen_angle, eigen_axis, have_eigen_rotation_, have_transformation_, InputEigenRotation, InputEulerRotation, InputMatrix, InputNone, InputQuaternion, jeod::Quaternion::left_quat_to_eigen_rotation(), mark_input_as_available(), and quat.
Referenced by compute_all_products(), and get_eigen_rotation().
compute_eigen_rotation_from_matrix() [1/2]
void jeod::Orientation::compute_eigen_rotation_from_matrix (const double trans[3][3], double * eigen_angle, double eigen_axis[3]) static
Compute the eigen rotation from the transformation matrix.
There are several alternate expressions for computing the eigen rotation from a matrix, all of which are equivalent in infinite precision arithmetic. The use of finite precision arithmetic means that care must be taken in choosing the algorithm to be used. The starting point is the generic expression
From this, the trace of the matrix and the difference between and sum of pairs of off-diagonal elements are
Method 1
One approach to determining the eigen rotation involves the construction of a vector of differences between pairs of off-diagonal elements of the transformation matrix,
where (i,j,k) is an even permutation of (0,1,2). With this,
Note that the above of the inverse sine will restrict the rotation angle to be between 0 and 90 degrees. Special processing is needed when the rotation angle is between 90 and 180 degrees. Note also that the symmetric difference vector will be identically zero if the rotation angle is 0 or 180 degrees and will be very small for rotation angles close to 0 or 180 degrees. The precision loss for rotation angles near 0 and 180 degrees means the individual components of the eigen axis will not be as precise with this approach compared to alternatives.
Method 2
The diagonal elements of the matrix yields another method for determining the single axis rotation angle and the rotation axis:
Note that this approach determines the magnitudes but not the signs of the components of the eigen axis vector. Because this method is based on the inverse cosine, the calculated phi angle will be less precise than that obtained by method 1 for angles near 0 or 180 degrees. The unit vector however will be more accurate than that obtained from method 1 for small rotation angles.
Method 3
Yet another alternative for computing components of the eigen axis is to use the sum of pairs of off-diagonal elements of the transformation metrix,
This enables the calculation of two components of the unit vector. One component needs to be computed by one of the two previous methods.
Assumptions and Limitations
The matrix is a proper transformation matrix.
Parameters
[in] trans Transformation matrix
[out] eigen_angle Resultant rotation angle
Units: r
[out] eigen_axis Resultant rotation axis
Definition at line 203 of file eigen_rotation.cc.
References eigen_angle, eigen_axis, jeod::Vector3::scale(), trans, and jeod::Vector3::vmag().
compute_eigen_rotation_from_matrix() [2/2]
void jeod::Orientation::compute_eigen_rotation_from_matrix (void) inline protected
Compute a eigen rotation that corresponds to the provided transformation matrix.
Definition at line 358 of file orientation.hh.
References eigen_angle, eigen_axis, and trans.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_eigen_rotation(), and jeod::CheckItem::within_eigen_tolerance().
compute_euler_angles()
void jeod::Orientation::compute_euler_angles (void) virtual
Compute the eigen rotation from the source.
Definition at line 481 of file orientation.cc.
References compute_euler_angles_from_matrix(), compute_matrix_from_eigen_rotation(), data_source, jeod::MessageHandler::error(), euler_sequence, EulerXYZ, EulerZYZ, have_euler_angles_, have_transformation_, InputEigenRotation, InputEulerRotation, InputMatrix, InputNone, InputQuaternion, jeod::OrientationMessages::invalid_enum, jeod::Quaternion::left_quat_to_transformation(), mark_input_as_available(), quat, and trans.
Referenced by compute_all_products(), and get_euler_angles().
compute_euler_angles_from_matrix() [1/2]
void jeod::Orientation::compute_euler_angles_from_matrix (const double trans[3][3], EulerSequence euler_sequence, double euler_angles[3]) static
Extract an Euler sequence from the transformation matrix.
A transformation matrix constructed from an XYZ Euler sequence is of the form
Note that the [2][0] element of the matrix depends on theta only. The other two elements of the leftmost column are simple terms that depend on theta and psi only, and the other two elements of the bottommost row are simple terms that depend on theta and phi only. Those five elements are the key to extracting an XYZ Euler sequence from a transformation matrix. The same principle applies to all twelve of the Euler sequences: Five key elements contain all of the information needed to extract the desired sequence. The location and form of those key elements of course depends on the sequence.
A problem arises in the above when cos(theta) is zero, or nearly so. This siutation is called 'gimbal lock'. Those four elements used to determine phi and psi are zero or nearly so. Fortunately That ugly stuff isn't so ugly in the case of gimbal lock. Once again looking at the matrix generated from an XYZ Euler sequence, when theta=pi/2 the matrix becomes
In this case there no way to determine both phi and psi; all that can be determined is their sum. One way to overcome this problem is to arbitrarily set one of those angles to an arbitrary value such as zero. That is the approach used in this method. This arbitrary setting enables an XYZ Euler sequence to be extracted from the matrix even in the case of gimbal lock. The same principle once again applies to all twelve sequences.
In summary, for a transformation matrix corresponding to an XYZ sequence,
The [2][0] element of the matrix specifies theta.
The [1][0] and [0][0] elements of the matrix specify psi.
The [2][1] and [2][2] elements of the matrix specify phi. These psi and phi values are valid only when gimbal lock is not present.
The [1][2] and [1][1] elements of the matrix specify phi in the case of gimbal lock.
Extending this analysis to the remaining eleven sequences provides the essential information needed to extract the desired Euler angles from a transformation matrix. This information is captured in the EulerInfo array Euler_info defined at the head of this file. With a reference info to the appropriate element of this array,
The [info.indices[2]][info.indices[0]] element of the matrix specifies the angle theta.
The [info.indices[1]][info.indices[0]] and [info.alternate_x][info.indices[0]] elements of the matrix specify the angle psi when gimbal lock is not present.
The [info.indices[2]][info.indices[1]] and [info.indices[2]][info.alternate_z] elements of the matrix specify the angle phi when gimbal lock is not present.
The [info.indices[1]][info.alternate_z] and [info.indices[1]][info.indices[1]] elements of the matrix specify angle phi when gimbal lock is present.
Assumptions and Limitations
To within numerical accuracy, the transformation matrix in the Orientation object is a proper transformation matrix:
The magnitude of each row and column vector is nearly one.
The inner product of any two different rows / two different columns of the matrix nearly zero.
The determinant of the matrix is nearly one.
An element whose value is outside the range [-1,1] is only slightly outside that range and the deviation is numerical.
Parameters
[in] trans Transformation matrix
[in] euler_sequence Euler sequence
[out] euler_angles Resultant Euler angles
Units: r
Definition at line 305 of file euler_angles.cc.
References jeod::EulerInfo::alternate_x, jeod::EulerInfo::alternate_z, jeod::MessageHandler::error(), euler_angles, jeod::Euler_info, euler_sequence, EulerXYZ, EulerZYZ, gimbal_lock_threshold, jeod::EulerInfo::indices, jeod::OrientationMessages::invalid_enum, jeod::EulerInfo::is_aerodynamics_sequence, jeod::EulerInfo::is_even_permutation, and trans.
compute_euler_angles_from_matrix() [2/2]
void jeod::Orientation::compute_euler_angles_from_matrix (void) inline protected
Compute an Euler rotation sequence that corresponds to the provided transformation matrix.
Definition at line 330 of file orientation.hh.
References euler_angles, euler_sequence, and trans.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_euler_angles(), and jeod::EulerDerivedState::update().
compute_matrix_from_eigen_rotation() [1/2]
void jeod::Orientation::compute_matrix_from_eigen_rotation (double eigen_angle, const double eigen_axis[3], double trans[3][3]) static
Compute the transformation matrix from the eigen rotation.
Given a rotation by an angle about an axis , the [i][j] element of the transformation matrix is given by
where
is the Kronecker delta,
k is , and
is the Levi-Civita symbol taken with respect to (0,1,2).
Assumptions and Limitations
The eigen axis is a unit vector.
Parameters
[in] eigen_angle Rotation angle
Units: r
[in] eigen_axis Rotation axis, unit vector
[out] trans Resultant transformation matrix
Definition at line 82 of file eigen_rotation.cc.
References eigen_angle, eigen_axis, and trans.
compute_matrix_from_eigen_rotation() [2/2]
void jeod::Orientation::compute_matrix_from_eigen_rotation (void) inline protected
Compute the transformation matrix that corresponds to the provided eigen rotation.
Definition at line 344 of file orientation.hh.
References eigen_angle, eigen_axis, and trans.
Referenced by compute_euler_angles(), and compute_transform().
compute_matrix_from_euler_angles() [1/2]
void jeod::Orientation::compute_matrix_from_euler_angles (EulerSequence euler_sequence, const double euler_angles[3], double trans[3][3]) static
Compute the transformation matrix from the Euler sequence.
The matrix is formed by generating a sequence of three simple transformation matrices corresponding to the three rotations. The composite transformation matrix is the reverse-order product of these three simple matrices.
Parameters
[in] euler_sequence Euler sequence
[in] euler_angles Euler angles
Units: r
[out] trans Resultant transformation matrix
Definition at line 171 of file euler_angles.cc.
References jeod::MessageHandler::error(), euler_angles, jeod::Euler_info, euler_sequence, EulerXYZ, EulerZYZ, jeod::EulerInfo::indices, jeod::Matrix3x3::initialize(), jeod::OrientationMessages::invalid_enum, jeod::Matrix3x3::product(), and trans.
compute_matrix_from_euler_angles() [2/2]
void jeod::Orientation::compute_matrix_from_euler_angles (void) inline protected
Compute the transformation matrix that corresponds to the provided Euler rotation sequence.
Definition at line 316 of file orientation.hh.
References euler_angles, euler_sequence, and trans.
Referenced by clear_euler_sequence(), compute_eigen_rotation(), and compute_transform().
compute_quaternion()
void jeod::Orientation::compute_quaternion (void) virtual
Compute the left transformation quaternion from the source.
Definition at line 373 of file orientation.cc.
References compute_quaternion_from_euler_angles(), data_source, eigen_angle, eigen_axis, have_quaternion_, InputEigenRotation, InputEulerRotation, InputMatrix, InputNone, InputQuaternion, jeod::Quaternion::left_quat_from_eigen_rotation(), jeod::Quaternion::left_quat_from_transformation(), mark_input_as_available(), quat, and trans.
Referenced by compute_all_products(), compute_transformation_and_quaternion(), and get_quaternion().
compute_quaternion_from_euler_angles() [1/2]
void jeod::Orientation::compute_quaternion_from_euler_angles (EulerSequence euler_sequence, const double euler_angles[3], Quaternion & quat) static
Compute the left transformation quaternion from the Euler sequence.
The quaternion is formed by generating a sequence of three simple quaternions corresponding to the three rotations. The composite quaternion is the reverse-order product of these three simple quaternions.
Parameters
[in] euler_sequence Euler sequence
[in] euler_angles Euler angles
Units: r
[out] quat Resultant quaternion
Definition at line 126 of file euler_angles.cc.
References jeod::MessageHandler::error(), euler_angles, jeod::Euler_info, euler_sequence, EulerXYZ, EulerZYZ, jeod::EulerInfo::indices, jeod::OrientationMessages::invalid_enum, jeod::Quaternion::multiply(), jeod::Quaternion::normalize(), quat, jeod::Quaternion::scalar, and jeod::Quaternion::vector.
compute_quaternion_from_euler_angles() [2/2]
void jeod::Orientation::compute_quaternion_from_euler_angles (void) inline protected
Compute the left transformation quaternion that corresponds to the provided Euler rotation sequence.
Definition at line 302 of file orientation.hh.
References euler_angles, euler_sequence, and quat.
Referenced by clear_euler_sequence(), and compute_quaternion().
compute_transform()
void jeod::Orientation::compute_transform (void) virtual
Compute the transformation matrix from the source.
Definition at line 321 of file orientation.cc.
References compute_matrix_from_eigen_rotation(), compute_matrix_from_euler_angles(), data_source, have_transformation_, InputEigenRotation, InputEulerRotation, InputMatrix, InputNone, InputQuaternion, jeod::Quaternion::left_quat_to_transformation(), mark_input_as_available(), quat, and trans.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::DynBodyInitLvlhState::apply(), jeod::BodyReattach::apply(), jeod::DynBodyInit::apply_user_inputs(), compute_all_products(), compute_transformation_and_quaternion(), get_transform(), and jeod::MassPropertiesInit::initialize_mass_properties().
compute_transformation_and_quaternion()
void jeod::Orientation::compute_transformation_and_quaternion (void) virtual
Compute the transformation matrix and quaternion.
Definition at line 569 of file orientation.cc.
References compute_quaternion(), and compute_transform().
Referenced by jeod::MassPointInit::initialize_mass_point().
get_eigen_rotation()
void jeod::Orientation::get_eigen_rotation (double * eigen_angle_out, double eigen_axis_out[3])
Accessor for the eigen rotation.
Parameters
[out] eigen_angle_out Copy of the single axis rotation angle
Units: r
[out] eigen_axis_out Copy of the single axis rotation axis
Definition at line 647 of file orientation.cc.
References compute_eigen_rotation(), jeod::Vector3::copy(), eigen_angle, eigen_axis, and have_eigen_rotation_.
get_euler_angles() [1/2]
void jeod::Orientation::get_euler_angles (EulerSequence * sequence, double angles[3])
Accessor for the Euler angles.
Parameters
[out] sequence Copy of the Euler sequence
[out] angles Copy of the Euler angles
Units: r
Definition at line 673 of file orientation.cc.
References compute_euler_angles(), jeod::Vector3::copy(), euler_angles, euler_sequence, and have_euler_angles_.
get_euler_angles() [2/2]
void jeod::Orientation::get_euler_angles (double angles[3])
Accessor for the Euler angles.
Parameters
[out] angles Copy of the Euler angles
Units: r
Definition at line 698 of file orientation.cc.
References compute_euler_angles(), jeod::Vector3::copy(), euler_angles, and have_euler_angles_.
get_euler_sequence()
Orientation::EulerSequence jeod::Orientation::get_euler_sequence (void)
Accessor for the Euler sequence data member.
Returns
Euler sequence data member
Definition at line 721 of file orientation.cc.
References euler_sequence.
get_quaternion()
void jeod::Orientation::get_quaternion (Quaternion & quat_out)
Accessor for the left transformation quaternion.
Parameters
[out] quat_out Copy of the quaternion
Definition at line 623 of file orientation.cc.
References compute_quaternion(), have_quaternion_, and quat.
get_transform()
void jeod::Orientation::get_transform (double trans_out[3][3])
Accessor for the transformation matrix.
Parameters
[out] trans_out Copy of the transformation matrix
Definition at line 600 of file orientation.cc.
References compute_transform(), jeod::Matrix3x3::copy(), have_transformation_, and trans.
mark_input_as_available()
void jeod::Orientation::mark_input_as_available (void) protected
Mark the item specified by the data_source as available.
Note that this method doesn't compute any products.
Assumptions and Limitations
The data_source member datum is valid.
Definition at line 246 of file orientation.cc.
References data_source, jeod::MessageHandler::error(), have_eigen_rotation_, have_euler_angles_, have_quaternion_, have_transformation_, InputEigenRotation, InputEulerRotation, InputMatrix, InputNone, InputQuaternion, and jeod::OrientationMessages::invalid_enum.
Referenced by compute_eigen_rotation(), compute_euler_angles(), compute_quaternion(), and compute_transform().
reset()
void jeod::Orientation::reset (void) virtual
Forget that we have any data.
Note that this method does not reset the euler_sequence member; that is intentional.
Definition at line 227 of file orientation.cc.
References data_source, have_eigen_rotation_, have_euler_angles_, have_quaternion_, have_transformation_, and InputNone.
Referenced by set_eigen_rotation(), set_euler_angles(), set_quaternion(), and set_transform().
set_eigen_rotation()
void jeod::Orientation::set_eigen_rotation (double eigen_angle_in, const double eigen_axis_in[3])
Reset the instance with a new eigen rotation.
Parameters
[in] eigen_angle_in New single axis rotation angle
[in] eigen_axis_in New single axis rotation axis
Definition at line 783 of file orientation.cc.
References jeod::Vector3::copy(), data_source, eigen_angle, eigen_axis, have_eigen_rotation_, InputEigenRotation, and reset().
set_euler_angles() [1/2]
void jeod::Orientation::set_euler_angles (EulerSequence sequence, const double angles[3])
Reset the instance with a new Euler rotation.
Parameters
[in] sequence New Euler sequence
[in] angles New Euler angles
Units: r
Definition at line 804 of file orientation.cc.
References jeod::Vector3::copy(), data_source, jeod::MessageHandler::error(), euler_angles, euler_sequence, EulerXYZ, EulerZYZ, have_euler_angles_, InputEulerRotation, jeod::OrientationMessages::invalid_enum, and reset().
set_euler_angles() [2/2]
void jeod::Orientation::set_euler_angles (const double angles[3])
Reset the instance with a new Euler rotation.
Assumptions and Limitations
The euler_sequence data member must have previously been set to a valid value.
Parameters
[in] angles New Euler angles
Units: r
Definition at line 840 of file orientation.cc.
References jeod::Vector3::copy(), data_source, jeod::MessageHandler::error(), euler_angles, euler_sequence, EulerXYZ, EulerZYZ, have_euler_angles_, InputEulerRotation, jeod::OrientationMessages::invalid_enum, and reset().
set_euler_sequence()
void jeod::Orientation::set_euler_sequence (EulerSequence sequence)
Set the euler_sequence data member.
Parameters
[in] sequence New Euler sequence
Definition at line 872 of file orientation.cc.
References clear_euler_sequence(), jeod::MessageHandler::error(), euler_sequence, EulerXYZ, EulerZYZ, have_euler_angles_, and jeod::OrientationMessages::invalid_enum.
set_quaternion()
void jeod::Orientation::set_quaternion (const Quaternion & quat_in)
Reset the instance with a new quaternion.
Parameters
[in] quat_in New quaternion
Definition at line 764 of file orientation.cc.
References data_source, have_quaternion_, InputQuaternion, quat, and reset().
set_transform()
void jeod::Orientation::set_transform (const double trans_in[3][3])
Reset the instance with a new matrix.
Parameters
[in] trans_in New transformation matrix
Definition at line 746 of file orientation.cc.
References jeod::Matrix3x3::copy(), data_source, have_transformation_, InputMatrix, reset(), and trans.
Friends And Related Function Documentation
init_attrjeod__Orientation
void init_attrjeod__Orientation () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file orientation.hh.
Field Documentation
data_source
DataSource jeod::Orientation::data_source
Orientation data source – specifies whether the user has provided as input an Euler rotation, a transformation matrix, or a left transformation quaternion.
trick_units(–)
Definition at line 239 of file orientation.hh.
Referenced by clear_euler_sequence(), compute_eigen_rotation(), compute_euler_angles(), compute_quaternion(), compute_transform(), jeod::ContactFacet::create_vehicle_point(), mark_input_as_available(), reset(), set_eigen_rotation(), set_euler_angles(), set_quaternion(), and set_transform().
eigen_angle
double jeod::Orientation::eigen_angle
Single axis rotation angle.
trick_units(rad)
Definition at line 265 of file orientation.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_eigen_rotation(), compute_eigen_rotation_from_matrix(), compute_matrix_from_eigen_rotation(), compute_quaternion(), get_eigen_rotation(), and set_eigen_rotation().
eigen_axis
double jeod::Orientation::eigen_axis[3]
Single axis rotation axis unit vector.
trick_units(–)
Definition at line 270 of file orientation.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_eigen_rotation(), compute_eigen_rotation_from_matrix(), compute_matrix_from_eigen_rotation(), compute_quaternion(), get_eigen_rotation(), Orientation(), and set_eigen_rotation().
euler_angles
double jeod::Orientation::euler_angles[3]
Euler angles corresponding to rotation sequence euler_sequence.
The elements are stored in the order specified by that sequence.trick_units(rad)
Definition at line 250 of file orientation.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_euler_angles_from_matrix(), compute_matrix_from_euler_angles(), compute_quaternion_from_euler_angles(), get_euler_angles(), Orientation(), and set_euler_angles().
euler_sequence
EulerSequence jeod::Orientation::euler_sequence
The Euler rotation sequence corresponding to euler_angles.
trick_units(–)
Definition at line 244 of file orientation.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), clear_euler_sequence(), compute_euler_angles(), compute_euler_angles_from_matrix(), compute_matrix_from_euler_angles(), compute_quaternion_from_euler_angles(), get_euler_angles(), get_euler_sequence(), set_euler_angles(), and set_euler_sequence().
gimbal_lock_threshold
double jeod::Orientation::gimbal_lock_threshold = 1e-13 static protected
Threshold for detecting gimbal lock in compute_euler_angles_from_matrix.
The threshold for determining whether a gimbal lock condition exists.
trick_units(–)
Gimbal lock occurs when sin(theta) (aerodynamics Euler sequences) or cos(theta) (astronomical sequences) is very close to -1 or +1. This static variable quantifies the meaning of 'very close'.
Definition at line 144 of file orientation.hh.
Referenced by compute_euler_angles_from_matrix().
have_eigen_rotation_
bool jeod::Orientation::have_eigen_rotation_ protected
True if eigen rotation has been set/computed.
trick_units(–)
Definition at line 287 of file orientation.hh.
Referenced by compute_eigen_rotation(), get_eigen_rotation(), mark_input_as_available(), reset(), and set_eigen_rotation().
have_euler_angles_
bool jeod::Orientation::have_euler_angles_ protected
True if an Euler rotation has been set/computed.
trick_units(–)
Definition at line 292 of file orientation.hh.
Referenced by clear_euler_sequence(), compute_euler_angles(), get_euler_angles(), mark_input_as_available(), reset(), set_euler_angles(), and set_euler_sequence().
have_quaternion_
bool jeod::Orientation::have_quaternion_ protected
True if quaternion has been set/computed.
trick_units(–)
Definition at line 282 of file orientation.hh.
Referenced by clear_euler_sequence(), compute_quaternion(), get_quaternion(), mark_input_as_available(), reset(), and set_quaternion().
have_transformation_
bool jeod::Orientation::have_transformation_ protected
True if transformation matrix has been set/computed.
trick_units(–)
Definition at line 277 of file orientation.hh.
Referenced by clear_euler_sequence(), compute_eigen_rotation(), compute_euler_angles(), compute_transform(), get_transform(), mark_input_as_available(), reset(), and set_transform().
quat
Quaternion jeod::Orientation::quat
Left transformation unit quaternion.
trick_units(–)
Definition at line 260 of file orientation.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), compute_eigen_rotation(), compute_euler_angles(), compute_quaternion(), compute_quaternion_from_euler_angles(), compute_transform(), get_quaternion(), jeod::MassPointInit::initialize_mass_point(), and set_quaternion().
trans
double jeod::Orientation::trans[3][3]
Transformation matrix.
trick_units(–)
Definition at line 255 of file orientation.hh.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::DynBodyInitLvlhState::apply(), jeod::BodyReattach::apply(), jeod::DynBodyInit::apply_user_inputs(), compute_eigen_rotation_from_matrix(), compute_euler_angles(), compute_euler_angles_from_matrix(), compute_matrix_from_eigen_rotation(), compute_matrix_from_euler_angles(), compute_quaternion(), compute_transform(), jeod::ContactFacet::create_vehicle_point(), get_transform(), jeod::MassPointInit::initialize_mass_point(), jeod::MassPropertiesInit::initialize_mass_properties(), Orientation(), and set_transform().
The documentation for this class was generated from the following files:
orientation.hh
eigen_rotation.cc
euler_angles.cc
orientation.cc