JEOD: jeod::BodyAttachMatrix Class Reference
jeod::BodyAttachMatrix Class Reference
Attaches a pair of MassBody objects using the offset+matrix attach mechanism.
#include <body_attach_matrix.hh>
Public Member Functions
BodyAttachMatrix ()=default
~BodyAttachMatrix () override=default
BodyAttachMatrix (const BodyAttachMatrix &)=delete
BodyAttachMatrix & operator= (const BodyAttachMatrix &)=delete
void apply (DynManager &dyn_manager) override
Initialize the core mass properties of the subject MassBody.
Public Member Functions inherited from jeod::BodyAttach
void set_parent_body (MassBody &mass_body_in)
Set the parent mass body of this action.
void set_parent_body (DynBody &dyn_body_in)
Set the parent dyn body of this action.
void set_parent_frame (RefFrame &ref_parent_in)
Set the parent ref frame of this action.
BodyAttach ()=default
~BodyAttach () override=default
BodyAttach (const BodyAttach &)=delete
BodyAttach & operator= (const BodyAttach &)=delete
void initialize (DynManager &dyn_manager) override
Initialize a MassBodyAttach.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
virtual bool is_ready ()
In general, determine if the initializer is ready to be applied.
Data Fields
double offset_pstr_cstr_pstr [3] {}
Location of this body's structural origin with respect to the new parent body's structural origin (or generic reference frame), specified in structural coordinates of the new parent body.
Orientation pstr_cstr
Orientation of child's structural frame with respect to that of the new parent; sense is parent-to-child.
Data Fields inherited from jeod::BodyAttach
bool succeeded {}
Did the attachment succeed?
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Friends
class InputProcessor
void init_attrjeod__BodyAttachMatrix ()
Additional Inherited Members
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::BodyAttach
MassBody * mass_parent {}
The MassBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
DynBody * dyn_parent {}
The DynBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
RefFrame * ref_parent {}
The RefFrame corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent RefFrame otherwise.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Attaches a pair of MassBody objects using the offset+matrix attach mechanism.
When the action is ready, the attachment is made such that:
The displacement between the origins of the parent and subject bodies' structural frames is that given by the offset_pstr_cstr_pstr data member.
The orientation between these two reference frames's axes is that given by the pstr_cstr data member.
Definition at line 86 of file body_attach_matrix.hh.
Constructor & Destructor Documentation
BodyAttachMatrix() [1/2]
jeod::BodyAttachMatrix::BodyAttachMatrix () default
~BodyAttachMatrix()
jeod::BodyAttachMatrix::~BodyAttachMatrix () override default
BodyAttachMatrix() [2/2]
jeod::BodyAttachMatrix::BodyAttachMatrix (const BodyAttachMatrix &) delete
Member Function Documentation
apply()
void jeod::BodyAttachMatrix::apply (DynManager & dyn_manager) override virtual
Initialize the core mass properties of the subject MassBody.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAttach.
Definition at line 50 of file body_attach_matrix.cc.
References jeod::DynBody::add_mass_body(), jeod::BodyAttach::apply(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::Orientation::compute_transform(), jeod::BodyAttach::dyn_parent, jeod::BodyAction::dyn_subject, jeod::BodyAttach::mass_parent, jeod::BodyAction::mass_subject, offset_pstr_cstr_pstr, pstr_cstr, jeod::BodyAttach::ref_parent, jeod::BodyAttach::succeeded, and jeod::Orientation::trans.
operator=()
BodyAttachMatrix& jeod::BodyAttachMatrix::operator= (const BodyAttachMatrix &) delete
Friends And Related Function Documentation
init_attrjeod__BodyAttachMatrix
void init_attrjeod__BodyAttachMatrix () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file body_attach_matrix.hh.
Field Documentation
offset_pstr_cstr_pstr
double jeod::BodyAttachMatrix::offset_pstr_cstr_pstr[3] {}
Location of this body's structural origin with respect to the new parent body's structural origin (or generic reference frame), specified in structural coordinates of the new parent body.
trick_units(m)
Definition at line 96 of file body_attach_matrix.hh.
Referenced by apply().
pstr_cstr
Orientation jeod::BodyAttachMatrix::pstr_cstr
Orientation of child's structural frame with respect to that of the new parent; sense is parent-to-child.
trick_units(–)
Definition at line 102 of file body_attach_matrix.hh.
Referenced by apply().
The documentation for this class was generated from the following files:
body_attach_matrix.hh
body_attach_matrix.cc