JEOD: jeod::EmptySpaceEphemeris Class Reference
jeod::EmptySpaceEphemeris Class Reference
Empty space has one ephemeris point.
#include <simple_ephemerides.hh>
Public Member Functions
EmptySpaceEphemeris (void)
Construct an EmptySpaceEphemeris object.
~EmptySpaceEphemeris (void) override
Destruct an EmptySpaceEphemeris object.
void set_name (const char *frame_name) override
Set the name of an EmptySpaceEphemeris object.
void initialize_model (EphemeridesManager &ephem_manager) override
Initialize an EmptySpaceEphemeris object.
void ephem_initialize (EphemeridesManager &ephem_manager) override
Initialize an EmptySpaceEphemeris object.
void ephem_activate (EphemeridesManager &ephem_manager) override
Activate an EmptySpaceEphemeris object.
void ephem_build_tree (EphemeridesManager &ephem_manager) override
Build the reference frame tree with the central frame as the root.
Public Member Functions inherited from jeod::SinglePointEphemeris
SinglePointEphemeris (void)
Construct a SinglePointEphemeris object.
~SinglePointEphemeris (void) override
Destruct a SinglePointEphemeris object.
void activate (void) override
Nominally, activate the model.
void deactivate (void) override
Deactivate the model.
double timestamp (void) const override
Retrieve the timestamp.
const char * get_name (void) const override
Retrieve the identifier.
void ephem_update (void) override
Update the ephemerides, which in this case is a no-op.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
Protected Attributes
EphemerisPoint central_point
The EphemerisPoint that represents the center of an empty universe.
EphemerisRefFrame central_frame
The sole ephemeris frame for this model.
Protected Attributes inherited from jeod::SinglePointEphemeris
char * identifier
Identifier for this model.
double update_time
Time of last update, dynamic time seconds.
bool active
Is the model active?
Private Member Functions
EmptySpaceEphemeris (const EmptySpaceEphemeris &)
Not implemented.
EmptySpaceEphemeris & operator= (const EmptySpaceEphemeris &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EmptySpaceEphemeris ()
Detailed Description
Empty space has one ephemeris point.
Definition at line 203 of file simple_ephemerides.hh.
Constructor & Destructor Documentation
EmptySpaceEphemeris() [1/2]
jeod::EmptySpaceEphemeris::EmptySpaceEphemeris (void)
Construct an EmptySpaceEphemeris object.
Definition at line 152 of file simple_ephemerides.cc.
References central_point, jeod::EphemerisItem::enable(), and jeod::EphemerisItem::set_owner().
~EmptySpaceEphemeris()
jeod::EmptySpaceEphemeris::~EmptySpaceEphemeris (void) override
Destruct an EmptySpaceEphemeris object.
Definition at line 163 of file simple_ephemerides.cc.
EmptySpaceEphemeris() [2/2]
jeod::EmptySpaceEphemeris::EmptySpaceEphemeris (const EmptySpaceEphemeris &) private
Not implemented.
Member Function Documentation
ephem_activate()
void jeod::EmptySpaceEphemeris::ephem_activate (EphemeridesManager & ephem_manager) override virtual
Activate an EmptySpaceEphemeris object.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 247 of file simple_ephemerides.cc.
ephem_build_tree()
void jeod::EmptySpaceEphemeris::ephem_build_tree (EphemeridesManager & ephem_manager) override virtual
Build the reference frame tree with the central frame as the root.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 259 of file simple_ephemerides.cc.
References jeod::SinglePointEphemeris::active, jeod::RefFrameManager::add_frame_to_tree(), and central_frame.
ephem_initialize()
void jeod::EmptySpaceEphemeris::ephem_initialize (EphemeridesManager & ephem_manager) override virtual
Initialize an EmptySpaceEphemeris object.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 224 of file simple_ephemerides.cc.
References central_point, jeod::SinglePointEphemeris::deactivate(), jeod::EphemerisItem::disable(), jeod::MessageHandler::error(), jeod::EphemerisItem::get_target_frame(), jeod::SinglePointEphemeris::identifier, and jeod::EphemeridesMessages::inconsistent_setup.
initialize_model()
void jeod::EmptySpaceEphemeris::initialize_model (EphemeridesManager & ephem_manager) override virtual
Initialize an EmptySpaceEphemeris object.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 204 of file simple_ephemerides.cc.
References jeod::SinglePointEphemeris::active, jeod::EphemeridesManager::add_ephem_item(), jeod::EphemeridesManager::add_ephemeris(), jeod::EphemeridesManager::add_integ_frame(), central_frame, and central_point.
operator=()
EmptySpaceEphemeris& jeod::EmptySpaceEphemeris::operator= (const EmptySpaceEphemeris &) private
Not implemented.
set_name()
void jeod::EmptySpaceEphemeris::set_name (const char * new_name) override virtual
Set the name of an EmptySpaceEphemeris object.
Parameters
[in,out] new_name Ephemeris name
Reimplemented from jeod::SinglePointEphemeris.
Definition at line 175 of file simple_ephemerides.cc.
References central_frame, central_point, jeod::SinglePointEphemeris::set_name(), jeod::EphemerisItem::set_name(), and jeod::RefFrame::set_name().
Friends And Related Function Documentation
init_attrjeod__EmptySpaceEphemeris
void init_attrjeod__EmptySpaceEphemeris () friend
InputProcessor
friend class InputProcessor friend
Definition at line 205 of file simple_ephemerides.hh.
Field Documentation
central_frame
EphemerisRefFrame jeod::EmptySpaceEphemeris::central_frame protected
The sole ephemeris frame for this model.
trick_units(–)
Definition at line 239 of file simple_ephemerides.hh.
Referenced by ephem_build_tree(), initialize_model(), and set_name().
central_point
EphemerisPoint jeod::EmptySpaceEphemeris::central_point protected
The EphemerisPoint that represents the center of an empty universe.
trick_units(–)
Definition at line 234 of file simple_ephemerides.hh.
Referenced by EmptySpaceEphemeris(), ephem_initialize(), initialize_model(), and set_name().
The documentation for this class was generated from the following files:
simple_ephemerides.hh
simple_ephemerides.cc