JEOD: jeod::GravityTorque Class Reference
jeod::GravityTorque Class Reference
Computes the torque on an object due to gravitation.
#include <gravity_torque.hh>
Public Member Functions
GravityTorque ()
Construct a GravityTorque object.
~GravityTorque ()
Destruct a GravityTorque object.
void initialize (DynBody &subject)
Initialize a GravityTorque object.
void update ()
Perform GravityTorque updates.
Data Fields
double torque [3]
The output torque, in the structural frame.
bool active
Is the model active?
Protected Attributes
DynBody * subject_body
The subject body for the gradient torque.
Private Member Functions
GravityTorque & operator= (const GravityTorque &rhs)
GravityTorque (const GravityTorque &rhs)
Friends
class InputProcessor
void init_attrjeod__GravityTorque ()
Detailed Description
Computes the torque on an object due to gravitation.
Definition at line 85 of file gravity_torque.hh.
Constructor & Destructor Documentation
GravityTorque() [1/2]
jeod::GravityTorque::GravityTorque (void)
Construct a GravityTorque object.
Definition at line 53 of file gravity_torque.cc.
References active, jeod::Vector3::initialize(), subject_body, and torque.
~GravityTorque()
jeod::GravityTorque::~GravityTorque (void)
Destruct a GravityTorque object.
Definition at line 65 of file gravity_torque.cc.
GravityTorque() [2/2]
jeod::GravityTorque::GravityTorque (const GravityTorque & rhs) private
Member Function Documentation
initialize()
void jeod::GravityTorque::initialize (DynBody & subject)
Initialize a GravityTorque object.
Parameters
[in,out] subject DynBody object subject to the torque
Definition at line 77 of file gravity_torque.cc.
References subject_body.
operator=()
GravityTorque& jeod::GravityTorque::operator= (const GravityTorque & rhs) private
update()
void jeod::GravityTorque::update (void)
Perform GravityTorque updates.
Definition at line 90 of file gravity_torque.cc.
References active, jeod::DynBody::composite_body, jeod::MassBody::composite_properties, jeod::Matrix3x3::copy(), jeod::MessageHandler::fail(), jeod::GravityInteraction::grav_grad, jeod::DynBody::grav_interaction, jeod::MassProperties::inertia, jeod::GravityTorqueMessages::initialization_error, jeod::DynBody::mass, jeod::RefFrameState::rot, jeod::RefFrame::state, subject_body, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, torque, jeod::Matrix3x3::transform_matrix(), and jeod::Vector3::transform_transpose().
Friends And Related Function Documentation
init_attrjeod__GravityTorque
void init_attrjeod__GravityTorque () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file gravity_torque.hh.
Field Documentation
active
bool jeod::GravityTorque::active
Is the model active?
trick_units(–)
Definition at line 109 of file gravity_torque.hh.
Referenced by GravityTorque(), and update().
subject_body
DynBody* jeod::GravityTorque::subject_body protected
The subject body for the gradient torque.
trick_units(–)
Definition at line 118 of file gravity_torque.hh.
Referenced by GravityTorque(), initialize(), and update().
torque
double jeod::GravityTorque::torque[3]
The output torque, in the structural frame.
trick_units(N*m)
Definition at line 104 of file gravity_torque.hh.
Referenced by GravityTorque(), and update().
The documentation for this class was generated from the following files:
gravity_torque.hh
gravity_torque.cc