JEOD: jeod::Restartable2DSecondOrderIntegrator Class Reference
jeod::Restartable2DSecondOrderIntegrator Class Reference
Integrates a second order ODE in two dimensional space, d^2x/dt^2 = a(x,t), where x is a two-vector.
#include <restartable_2d_second_order_integrator.hh>
Public Member Functions
Restartable2DSecondOrderIntegrator ()
Default constructor.
~Restartable2DSecondOrderIntegrator () override
Destructor.
void create_integrator (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls)
Create the integrator to be managed.
void destroy_integrator ()
Destroy the integrator.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage, double const *accel, double *velocity, double *position)
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
void reset_integrator ()
Tell the integrator to reset itself.
void simple_restore () override
Restore the integrator on restart.
Public Member Functions inherited from jeod::SimpleCheckpointable
SimpleCheckpointable ()
Construct a SimpleCheckpointable object.
~SimpleCheckpointable (void) override
Destruct a SimpleCheckpointable object.
const std::string get_init_name (void) override
Return the name of the initial restart action, in this case "restore".
const std::string get_item_name (void) override
Return the name of the current restart action, in this case "".
const std::string get_item_value (void) override
Return the value of the current restart action, in this case "".
void start_checkpoint (void) override
In general, start the checkpoint process.
void advance_checkpoint (void) override
In general, advance to the next checkpoint item; in this case, do nothing.
bool is_checkpoint_finished (void) override
In general, indicate when checkpointing is complete.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
In general, respond to the actions recorded in the checkpoint file.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_name (void)
In general, return the name of the finalization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
Private Member Functions
Restartable2DSecondOrderIntegrator (const Restartable2DSecondOrderIntegrator &)
Not implemented.
Restartable2DSecondOrderIntegrator & operator= (const Restartable2DSecondOrderIntegrator &)
Not implemented.
Private Attributes
er7_utils::SecondOrderODEIntegrator * integrator
The pointer to the object that performs integration.
RestartableSimpleSecondOrderODEIntegrator< 2 > integrator_manager
The object that creates and manages the integrator object.
Friends
class InputProcessor
void init_attrjeod__Restartable2DSecondOrderIntegrator ()
Additional Inherited Members
Detailed Description
Integrates a second order ODE in two dimensional space, d^2x/dt^2 = a(x,t), where x is a two-vector.
Definition at line 84 of file restartable_2d_second_order_integrator.hh.
Constructor & Destructor Documentation
Restartable2DSecondOrderIntegrator() [1/2]
jeod::Restartable2DSecondOrderIntegrator::Restartable2DSecondOrderIntegrator () inline
Default constructor.
Definition at line 93 of file restartable_2d_second_order_integrator.hh.
References JEOD_REGISTER_CLASS.
~Restartable2DSecondOrderIntegrator()
jeod::Restartable2DSecondOrderIntegrator::~Restartable2DSecondOrderIntegrator () inline override
Destructor.
Definition at line 105 of file restartable_2d_second_order_integrator.hh.
References destroy_integrator().
Restartable2DSecondOrderIntegrator() [2/2]
jeod::Restartable2DSecondOrderIntegrator::Restartable2DSecondOrderIntegrator (const Restartable2DSecondOrderIntegrator &) private
Not implemented.
Member Function Documentation
create_integrator()
void jeod::Restartable2DSecondOrderIntegrator::create_integrator (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls) inline
Create the integrator to be managed.
Parameters
[in] generator Generator used to create the integrator.
[in,out] controls Controls to be passed to the generator.
Definition at line 116 of file restartable_2d_second_order_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::create_integrator(), and integrator_manager.
Referenced by jeod::PendulumConstraintComponent::create_integrators().
destroy_integrator()
void jeod::Restartable2DSecondOrderIntegrator::destroy_integrator () inline
Destroy the integrator.
Definition at line 126 of file restartable_2d_second_order_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::destroy_integrator(), integrator, integrator_manager, and jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference().
Referenced by jeod::PendulumConstraintComponent::destroy_integrators(), and ~Restartable2DSecondOrderIntegrator().
integrate()
er7_utils::IntegratorResult jeod::Restartable2DSecondOrderIntegrator::integrate (double dyn_dt, unsigned int target_stage, double const * accel, double * velocity, double * position) inline
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
Note that this is a pass-through to the encapsulated integrator object. See er7_utils::SecondOrderODEIntegrator::integrate for details.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] accel Time derivative of the generalized velocity.
[in,out] velocity Generalized velocity vector.
[in,out] position Generalized position vector.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 148 of file restartable_2d_second_order_integrator.hh.
References integrator.
Referenced by jeod::PendulumConstraintComponent::integrate_cartesian(), and jeod::PendulumConstraintComponent::integrate_spherical().
operator=()
Restartable2DSecondOrderIntegrator& jeod::Restartable2DSecondOrderIntegrator::operator= (const Restartable2DSecondOrderIntegrator &) private
Not implemented.
reset_integrator()
void jeod::Restartable2DSecondOrderIntegrator::reset_integrator () inline
Tell the integrator to reset itself.
This should be called when the time step or time direction changes or upon a discrete change in state such docking/undocking. Such events invalidate saved state (if any). The integrator needs to restart from scratch when such events occur.
Definition at line 166 of file restartable_2d_second_order_integrator.hh.
References integrator.
Referenced by jeod::PendulumConstraintComponent::reset_integrators().
simple_restore()
void jeod::Restartable2DSecondOrderIntegrator::simple_restore (void) inline override virtual
Restore the integrator on restart.
Implements jeod::SimpleCheckpointable.
Definition at line 174 of file restartable_2d_second_order_integrator.hh.
References integrator, integrator_manager, jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference(), and jeod::RestartableStateIntegrator< IntegratorType >::simple_restore().
Friends And Related Function Documentation
init_attrjeod__Restartable2DSecondOrderIntegrator
void init_attrjeod__Restartable2DSecondOrderIntegrator () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file restartable_2d_second_order_integrator.hh.
Field Documentation
integrator
er7_utils::SecondOrderODEIntegrator* jeod::Restartable2DSecondOrderIntegrator::integrator private
The pointer to the object that performs integration.
This object is created managed by the integrator manager.trick_units(–)
Definition at line 187 of file restartable_2d_second_order_integrator.hh.
Referenced by destroy_integrator(), integrate(), reset_integrator(), and simple_restore().
integrator_manager
RestartableSimpleSecondOrderODEIntegrator<2> jeod::Restartable2DSecondOrderIntegrator::integrator_manager private
The object that creates and manages the integrator object.
trick_io(**)
Definition at line 193 of file restartable_2d_second_order_integrator.hh.
Referenced by create_integrator(), destroy_integrator(), and simple_restore().
The documentation for this class was generated from the following file:
restartable_2d_second_order_integrator.hh