JEOD: jeod::SinglePlanetEphemeris Class Reference
jeod::SinglePlanetEphemeris Class Reference
A space with one gravitation body has one ephemeris point.
#include <simple_ephemerides.hh>
Public Member Functions
SinglePlanetEphemeris (void)
Construct an SinglePlanetEphemeris object.
~SinglePlanetEphemeris (void) override
Destruct an SinglePlanetEphemeris object.
void set_name (const char *frame_name) override
Set the name of a SinglePlanetEphemeris object.
void initialize_model (EphemeridesManager &ephem_manager) override
Initialize a SinglePlanetEphemeris object.
void ephem_initialize (EphemeridesManager &ephem_manager) override
Initialize a SinglePlanetEphemeris object.
void ephem_activate (EphemeridesManager &ephem_manager) override
Activate a SinglePlanetEphemeris object.
void ephem_build_tree (EphemeridesManager &ephem_manager) override
Build the reference frame tree with the central frame as the root.
Public Member Functions inherited from jeod::SinglePointEphemeris
SinglePointEphemeris (void)
Construct a SinglePointEphemeris object.
~SinglePointEphemeris (void) override
Destruct a SinglePointEphemeris object.
void activate (void) override
Nominally, activate the model.
void deactivate (void) override
Deactivate the model.
double timestamp (void) const override
Retrieve the timestamp.
const char * get_name (void) const override
Retrieve the identifier.
void ephem_update (void) override
Update the ephemerides, which in this case is a no-op.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
Protected Attributes
EphemerisPoint central_point
The EphemerisPoint that represents the center of a simple universe.
Protected Attributes inherited from jeod::SinglePointEphemeris
char * identifier
Identifier for this model.
double update_time
Time of last update, dynamic time seconds.
bool active
Is the model active?
Private Member Functions
SinglePlanetEphemeris (const SinglePlanetEphemeris &)
Not implemented.
SinglePlanetEphemeris & operator= (const SinglePlanetEphemeris &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__SinglePlanetEphemeris ()
Detailed Description
A space with one gravitation body has one ephemeris point.
Note well: A SinglePlanetEphemeris does not contain a Planet object. The planet must be specified elsewhere.
Definition at line 257 of file simple_ephemerides.hh.
Constructor & Destructor Documentation
SinglePlanetEphemeris() [1/2]
jeod::SinglePlanetEphemeris::SinglePlanetEphemeris (void)
Construct an SinglePlanetEphemeris object.
Definition at line 286 of file simple_ephemerides.cc.
References central_point, jeod::EphemerisItem::enable(), and jeod::EphemerisItem::set_owner().
~SinglePlanetEphemeris()
jeod::SinglePlanetEphemeris::~SinglePlanetEphemeris (void) override
Destruct an SinglePlanetEphemeris object.
Definition at line 297 of file simple_ephemerides.cc.
SinglePlanetEphemeris() [2/2]
jeod::SinglePlanetEphemeris::SinglePlanetEphemeris (const SinglePlanetEphemeris &) private
Not implemented.
Member Function Documentation
ephem_activate()
void jeod::SinglePlanetEphemeris::ephem_activate (EphemeridesManager & ephem_manager) override virtual
Activate a SinglePlanetEphemeris object.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 400 of file simple_ephemerides.cc.
ephem_build_tree()
void jeod::SinglePlanetEphemeris::ephem_build_tree (EphemeridesManager & ephem_manager) override virtual
Build the reference frame tree with the central frame as the root.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 412 of file simple_ephemerides.cc.
References jeod::SinglePointEphemeris::active, jeod::RefFrameManager::add_frame_to_tree(), central_point, and jeod::EphemerisItem::get_target_frame().
ephem_initialize()
void jeod::SinglePlanetEphemeris::ephem_initialize (EphemeridesManager & ephem_manager) override virtual
Initialize a SinglePlanetEphemeris object.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 355 of file simple_ephemerides.cc.
References jeod::SinglePointEphemeris::active, central_point, jeod::SinglePointEphemeris::deactivate(), jeod::EphemerisItem::disable(), jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_base_planet(), jeod::EphemeridesManager::get_num_planets(), jeod::EphemerisItem::get_target_frame(), jeod::SinglePointEphemeris::identifier, and jeod::EphemeridesMessages::inconsistent_setup.
initialize_model()
void jeod::SinglePlanetEphemeris::initialize_model (EphemeridesManager & ephem_manager) override virtual
Initialize a SinglePlanetEphemeris object.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::SinglePointEphemeris.
Definition at line 336 of file simple_ephemerides.cc.
References jeod::SinglePointEphemeris::active, jeod::EphemeridesManager::add_ephem_item(), jeod::EphemeridesManager::add_ephemeris(), and central_point.
operator=()
SinglePlanetEphemeris& jeod::SinglePlanetEphemeris::operator= (const SinglePlanetEphemeris &) private
Not implemented.
set_name()
void jeod::SinglePlanetEphemeris::set_name (const char * new_name) override virtual
Set the name of a SinglePlanetEphemeris object.
Parameters
[in,out] new_name Central point name
Reimplemented from jeod::SinglePointEphemeris.
Definition at line 309 of file simple_ephemerides.cc.
References central_point, jeod::SinglePointEphemeris::set_name(), and jeod::EphemerisItem::set_name().
Friends And Related Function Documentation
init_attrjeod__SinglePlanetEphemeris
void init_attrjeod__SinglePlanetEphemeris () friend
InputProcessor
friend class InputProcessor friend
Definition at line 259 of file simple_ephemerides.hh.
Field Documentation
central_point
EphemerisPoint jeod::SinglePlanetEphemeris::central_point protected
The EphemerisPoint that represents the center of a simple universe.
trick_units(–)
Definition at line 288 of file simple_ephemerides.hh.
Referenced by ephem_build_tree(), ephem_initialize(), initialize_model(), set_name(), and SinglePlanetEphemeris().
The documentation for this class was generated from the following files:
simple_ephemerides.hh
simple_ephemerides.cc