JEOD: jeod::JeodMemoryManager Class Reference
jeod::JeodMemoryManager Class Reference
This class provides the interface between the macros in jeod_alloc.hh and the rest of the JEOD memory model.
#include <memory_manager.hh>
Data Structures
struct TypeEntry
The type table is indexed by an integer and contains type descriptors.
Public Types
enum DebugLevel { Debug_off = 0, Summary_only = 1, Error_details = 2, Full_details = 3 }
The memory manager as a whole and individual operations have a debug level.
enum NameType { Typeid_type_name = 0, Demangled_type_name = 1 }
The type lookup by type name needs to know whether the provided name is a typeid name or a demangled name.
Public Member Functions
JeodMemoryManager (JeodMemoryInterface &)
Construct a MemoryManager object.
virtual ~JeodMemoryManager ()
Destruct a MemoryManager object.
void restart_clear_memory ()
Wipe out all allocated memory in anticipation of restoring the memory in some previously recording checkpoint file.
void restart_reallocate (const std::string &mangled_type_name, uint32_t unique_id, uint32_t nelements, bool is_array)
Restore one chunk of allocated memory per a checkpoint file entry.
Static Public Member Functions
static const TypeEntry register_class (JeodMemoryTypePreDescriptor &tdesc)
Register a class with the memory manager.
static const JeodMemoryTypeDescriptor * get_type_descriptor (const std::type_info &typeid_info)
Get a type descriptor from the memory manager's type table.
static const JeodMemoryTypeDescriptor * get_type_descriptor (NameType name_type, const std::string &name)
Get a type descriptor from the memory manager's type table.
static void * create_memory (bool is_array, unsigned int nelems, int fill, const TypeEntry &tentry, const char *file, unsigned int line)
Allocate memory and register the allocated memory with JEOD.
static bool is_allocated (const void *addr, const char *file, unsigned int line)
Query whether some address was allocated by JEOD.
static void destroy_memory (void *addr, bool delete_array, const char *file, unsigned int line)
Destroy memory previously registered with JEOD.
static void register_container (const void *container, const std::type_info &container_type, const char *elem_name, JeodCheckpointable &checkpointable)
Register a checkpointable object with the memory manager.
static void deregister_container (const void *container, const std::type_info &container_type, const char *elem_name, JeodCheckpointable &checkpointable)
Deregister all checkpointable object contained within some object.
static void set_mode (JeodSimulationInterface::Mode new_mode)
Set the memory manager's simulation interface mode.
static void set_debug_level (unsigned int level)
Set the debug level.
static void set_debug_level (DebugLevel level)
Set the debug level.
static void set_guard_enabled (bool value)
Set the guard_enabled flag.
static bool is_table_empty ()
Query whether all allocated memory has been freed.
Private Types
typedef std::map< const void *, JeodMemoryItem > AllocTable
An AllocTable maps memory addresses to memory descriptions.
typedef JeodMemoryTableClonable< JeodMemoryTypeDescriptor > TypeTable
The type type itself is a memory table with copy implemented by clone().
Private Member Functions
void generate_shutdown_report (void)
Generate a shutdown report.
void * create_memory_internal (bool is_array, unsigned int nelems, int fill, const TypeEntry &tentry, const char *file, unsigned int line)
Allocate memory for use with placement new and register that memory with with the memory manager and with the simulation engine.
void register_memory_internal (const void *addr, uint32_t unique_id, bool placement_new, bool is_array, unsigned int nelems, const TypeEntry &tentry, const char *file, unsigned int line)
Allocate memory if that was not already done by the caller and register the memory with JEOD and with an external agent.
bool is_allocated_internal (const void *addr, const char *file, unsigned int line)
Query whether some address was allocated by JEOD.
void destroy_memory_internal (void *addr, bool delete_array, const char *file, unsigned int line)
Destroy a chunk of memory and knowledge about it.
void set_mode_internal (JeodSimulationInterface::Mode new_mode)
Set the mode and perform mode transitions.
void begin_atomic_block (void) const
Prepare for a set of operations that must be done atomically.
void end_atomic_block (bool ignore_errors) const
End an atomic set of operations.
const TypeEntry get_type_entry_atomic (JeodMemoryTypePreDescriptor &tdesc)
Return the type entry for the input type descriptor, adding the descriptor to the type table if the type has not yet been registered.
const TypeEntry get_type_entry_atomic (NameType name_type, const std::string &type_name) const
Retrieve the descriptor for the specified type from the type table.
bool get_type_index_nolock (const JeodMemoryTypeDescriptor &tdesc, uint32_t *idx)
Retrieve the index for the specified type from the type table, adding an entry if needed.
const JeodMemoryTypeDescriptor * get_type_descriptor_atomic (const std::type_info &typeid_info) const
Retrieve the descriptor for the specified type from the type table.
const JeodMemoryTypeDescriptor & get_type_descriptor_atomic (unsigned int idx) const
Retrieve the descriptor for the specified type from the type table.
const JeodMemoryTypeDescriptor & get_type_descriptor_nolock (const JeodMemoryItem &item) const
Retrieve the descriptor for the specified type from the type table.
const std::string & get_string_atomic (unsigned int idx) const
Retrieve the specified string from the string table.
unsigned int add_string_atomic (const std::string &str)
Add a location identifier string to the string table.
uint32_t get_alloc_id_atomic (const char *file, unsigned int line)
Create a unique identifier for an allocation.
void reset_alloc_id_atomic (uint32_t unique_id)
Reset the unique identifier for a restart.
void find_alloc_entry_atomic (const void *addr, bool delete_entry, const char *file, unsigned int line, void *&found_addr, JeodMemoryItem &found_item, const JeodMemoryTypeDescriptor *&found_type)
Find the allocation table entry that matches the input address, and delete it if delete_entry is true.
void add_allocation_atomic (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line)
Add the specified addr/item pair to the table.
void delete_oldest_alloc_entry_atomic (void *&addr, JeodMemoryItem &item, const JeodMemoryTypeDescriptor *&type)
Find and delete the alloc table entry with the smallest unique id, setting the provided references with info about the deleted item.
void * allocate_memory (std::size_t nelems, std::size_t elem_size, bool guard, int fill) const
Allocate memory.
void free_memory (void *addr, std::size_t length, bool guard, unsigned int alloc_idx, const char *file, unsigned int line) const
Release memory.
JeodMemoryManager ()
Not implemented.
JeodMemoryManager (const JeodMemoryManager &)
Not implemented.
JeodMemoryManager & operator= (const JeodMemoryManager &)
Not implemented.
Static Private Member Functions
static bool check_master (bool error_is_fatal, int line)
Many of the static methods are a pass-through to a private non-static method, with the static method testing that the pass-through is valid.
Private Attributes
JeodMemoryInterface & sim_interface
The interface to the simulation engine's memory manager.
DebugLevel debug_level
Debugging level.
size_t cur_data_size
Number of allocated user bytes (excludes management overhead).
size_t max_data_size
Maximum value attained by cur_data_size.
unsigned int max_table_size
Maximum value attained by alloc_table.size().
unsigned int allocation_number
Number of allocations.
AllocTable alloc_table
Maps memory addresses to the descriptions of those addresses.
TypeTable type_table
Maps typeid names to type descriptors.
JeodMemoryReflectiveTable string_table
Maps unique strings to themselves.
pthread_mutex_t mutex
Mutex that synchronizes access to the tables.
JeodSimulationInterface::Mode mode
Simulation interface mode.
bool guard_enabled
Data can be guarded if this is set.
Static Private Attributes
static JeodMemoryManager * Master = nullptr
The singleton instance of the JeodMemoryManager class.
Friends
class InputProcessor
void init_attrjeod__JeodMemoryManager ()
Detailed Description
This class provides the interface between the macros in jeod_alloc.hh and the rest of the JEOD memory model.
The public interface is via the publicly visible static methods. All nonstatic member functions are private. Each public static method relays the method call to the singleton memory manager via a correspondingly named private member function.
Singleton
The class is intended to be a singleton. The private static member JeodMemoryManager::Master points to this singular instance. The constructor sets that static member if it is null. The constructor issues a non-fatal error when multiple instances of the class are created.
Thread Safety
This class contains objects that must be accessed and updated in a thread-safe manner. The member data that must be used atomically are
JeodMemoryManager::alloc_table - Maps memory addresses to memory items
JeodMemoryManager::type_table - Maps RTTI names to type descriptors
JeodMemoryManager::string_table - Maps unique strings to themselves.
JeodMemoryManager::cur_data_size - Current size of allocated data.
JeodMemoryManager::max_data_size - Maximum of the above.
JeodMemoryManager::max_table_size - Maximum allocation table size.
JeodMemoryManager::allocation_number - Number of allocations made.
To ensure the constraint is satisfied, access to the these elements is protected by means of a mutex and is limited to a small number of methods. A pair of methods, JeodMemoryManager::begin_atomic_block and JeodMemoryManager::end_atomic_block systematize the use of the mutex. The methods that operate on the protected data are
Constructor and destructor.
The constructor operates on the protected data before it creates the mutex and marks the JeodMemoryManager object as usable. The destructor marks the object as unusable and destroys the mutex before operating on the protected data.
JeodMemoryManager::generate_shutdown_report, which is called by the destructor after it has destroyed the mutex.
Methods whose names end with _atomic. These methods use the begin_atomic_block / end_atomic_block paradigm to ensure that the operations are carried out atomically.
Methods whose names end with _nolock. These methods operate on protected data but do so without atomic protection. These methods are called only by _atomic methods from within their atomic protection block.
Forbidden Word - Mutable
The data member JeodMemoryManager::mutex is mutable, a forbidden word per the JEOD coding standards. The coding standards allow for waivers to the standards if the exception is justified. This section provides the explanation needed to enable the use of that word in this case.
The mutable keyword tells the compiler to ignore modifications to mutable elements in an otherwise const method. The mutex is mutable because, athough its value does change with a successful lock, it is restored to its prelock value with an unlock. A method that could otherwise qualify as a const method can still be a const method by marking the mutex as mutable. Mutexes are one of the well-accepted types of data that typically marked as mutable.
Assumptions and Constraints on the Simulation Developer
This class places restrictions on the simulation developer.
The simulation's MessageHandler object must be constructed prior to constructing the simulation's JeodMemoryManager object.
The simulation's MessageHandler object must not be destroyed prior to constructing the simulation's JeodMemoryManager object.
The simulation's JeodMemoryManager object must be constructed prior to invoking any of the JEOD_ALLOC_xxx macros in other models.
The simulation's JeodMemoryManager object must not be destroyed before other models release their allocated memory.
The recommended solution is to create an instance of a compliant SimulationInterface before creating any other models and to destroy that SimulationInterface object after destroying all other models. A simple way to achieve this in a Trick-07 simulation is to define a Trick sim object that contains a TrickSimulationInterface element and to place this sim object immediately after the sys sim object.
Assumptions and Constraints on the Simulation Engine
This class makes certain assumptions of the behavior of the simulation engine.
The simulation engine will not spawn threads that use the JEOD memory model to allocate memory until after the SimulationInterface object has been constructed.
The simulation engine will join all threads that use the JEOD memory model prior to destroying the SimulationInterface object.
The Trick-07 and Trick-10 simulation engines satisfies these constraints.
Assumptions and Constraints on the Simulation Developer
This class places certain limitations on the architecture of a JEOD-based simulation.
The JeodMemoryManager destructor uses the simulation's message handler to report errors discovered during destruction and may eventually use the simulation's simulation engine memory interface to revoke the registration of memory allocated by JEOD that has not been freed. This in turn means that: – The simulation's message handler and simulation engine memory interface must be destructed after destructing the memory manager. – The destructors for those objects cannot use the memory manager.
The JEOD memory allocation and deallocation macros expand into calls to memory manager methods. The memory manager must be viable (post construction, pre destruction) for these calls to function properly. This in turn means that the memory manager must be constructed very early in the overall construction process and destructed very late in in the overall destruction process.
The supported solution to both of these issues is to use a compliant derived class of the JeodSimulationInterface class and to ensure that this composite object created early and destroyed late. In a Trick-07 simulation, this can be accomplished simply by placing a declaration of an object of type JeodTrickSimInterface near the top of an S_define file. The recommended placement is just after the Trick system sim object.
Definition at line 213 of file memory_manager.hh.
Member Typedef Documentation
AllocTable
typedef std::map<const void *, JeodMemoryItem> jeod::JeodMemoryManager::AllocTable private
An AllocTable maps memory addresses to memory descriptions.
Definition at line 369 of file memory_manager.hh.
TypeTable
typedef JeodMemoryTableClonable<JeodMemoryTypeDescriptor> jeod::JeodMemoryManager::TypeTable private
The type type itself is a memory table with copy implemented by clone().
Definition at line 374 of file memory_manager.hh.
Member Enumeration Documentation
DebugLevel
enum jeod::JeodMemoryManager::DebugLevel
The memory manager as a whole and individual operations have a debug level.
The debug levels and the message handler must be set to a sufficiently high level to enable and see the debugging output.
Enumerator
Debug_off
Debugging is off.
Summary_only
Summary information; Allocation data are not stored.
Error_details
Allocation data stored and used with error messages.
Full_details
Blow-by-blow accounting of all transactions.
Definition at line 225 of file memory_manager.hh.
NameType
enum jeod::JeodMemoryManager::NameType
The type lookup by type name needs to know whether the provided name is a typeid name or a demangled name.
Enumerator
Typeid_type_name
Name is from a std::type_info.name()
Demangled_type_name
Name is what people might use.
Definition at line 236 of file memory_manager.hh.
Constructor & Destructor Documentation
JeodMemoryManager() [1/3]
jeod::JeodMemoryManager::JeodMemoryManager (JeodMemoryInterface & interface) explicit
Construct a MemoryManager object.
Parameters
[in,out] interface The memory interface with the simulation engine
Definition at line 64 of file memory_manager.cc.
References jeod::MessageHandler::error(), MAKE_DESCRIPTOR, Master, mutex, and jeod::MemoryMessages::singleton_error.
~JeodMemoryManager()
jeod::JeodMemoryManager::~JeodMemoryManager (void) virtual
Destruct a MemoryManager object.
Assumptions and Limitations
In a multi-threaded environment,
This destructor shall be called once and once only to destroy the singleton JeodMemoryManager object.
The thread that calls this destructor shall wait until all other threads that access JEOD memory have finished, either by default or by force.
Note that this is a constraint on the simulation engine, not on JEOD.
Definition at line 150 of file memory_manager.cc.
References alloc_table, jeod::JeodMemoryInterface::deregister_allocation(), generate_shutdown_report(), jeod::JeodMemoryItem::get_is_registered(), get_type_descriptor_nolock(), Master, mutex, and sim_interface.
JeodMemoryManager() [2/3]
jeod::JeodMemoryManager::JeodMemoryManager () private
Not implemented.
JeodMemoryManager() [3/3]
jeod::JeodMemoryManager::JeodMemoryManager (const JeodMemoryManager &) explicit private
Not implemented.
Member Function Documentation
add_allocation_atomic()
void jeod::JeodMemoryManager::add_allocation_atomic (const void * addr, const JeodMemoryItem & item, const JeodMemoryTypeDescriptor & tdesc, const char * file, unsigned int line) private
Add the specified addr/item pair to the table.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
The specified address must not already be in the table.
Parameters
[in] addr Newly allocated memory
[in] item Description of that memory
[in] tdesc Description of the type
[in] file Source file containing JEOD_ALLOC
[in] line Line number containing JEOD_ALLOC
Definition at line 712 of file memory_manager_protected.cc.
References alloc_table, begin_atomic_block(), jeod::JeodMemoryTypeDescriptor::buffer_end(), jeod::JeodMemoryTypeDescriptor::buffer_size(), jeod::MemoryMessages::corrupted_memory, cur_data_size, end_atomic_block(), jeod::MessageHandler::fail(), jeod::JeodMemoryItem::get_nelems(), get_type_descriptor_nolock(), max_data_size, and max_table_size.
Referenced by register_memory_internal().
add_string_atomic()
unsigned int jeod::JeodMemoryManager::add_string_atomic (const std::string & str) private
Add a location identifier string to the string table.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Returns
String table index
Parameters
[in] str String to add
Definition at line 201 of file memory_manager_protected.cc.
References jeod::JeodMemoryReflectiveTable::add(), begin_atomic_block(), end_atomic_block(), and string_table.
Referenced by register_memory_internal().
allocate_memory()
void * jeod::JeodMemoryManager::allocate_memory (std::size_t nelems, std::size_t elem_size, bool guard, int fill) const private
Allocate memory.
Assumptions and Limitations
This is a low-level allocation function. It does not
Register the allocated memory with JEOD or with an external agent.
Construct the newly-allocated memory.
The returned address should not be released using the C free function or C++ delete operator.
Failure to obey this restriction will result in big problems.
Returns
Allocated memory
Parameters
[in] nelems Number of elements
[in] elem_size Size of each element
[in] guard Allocate guard bytes if set
[in] fill Fill pattern (ref. memset)
Definition at line 733 of file memory_manager.cc.
References jeod::MessageHandler::fail(), MAGIC0, MAGIC1, and jeod::MemoryMessages::out_of_memory.
Referenced by create_memory_internal(), and restart_reallocate().
begin_atomic_block()
void jeod::JeodMemoryManager::begin_atomic_block (void) const private
Prepare for a set of operations that must be done atomically.
Assumptions and Limitations
This method must be used in conjunction with end_atomic_block.
try {
   begin_atomic_block ();
   operate_on_protected_members();
   end_atomic_block (false);
}
catch (...) {
   end_atomic_block (true);
   throw;
}
See the class header for a detailed description. Purpose: (Prepare for a set of operations that must be done atomically.) Assumptions and limitations: This method must be used in conjunction with end_atomic_block.
try {
   begin_atomic_block ();
   operate_on_protected_members();
   end_atomic_block (false);
}
catch (...) {
   end_atomic_block (true);
   throw;
}
(See the class header for a detailed description.))
Definition at line 102 of file memory_manager_protected.cc.
References jeod::MessageHandler::fail(), jeod::MemoryMessages::lock_error, and mutex.
Referenced by add_allocation_atomic(), add_string_atomic(), delete_oldest_alloc_entry_atomic(), find_alloc_entry_atomic(), get_alloc_id_atomic(), get_string_atomic(), get_type_descriptor_atomic(), get_type_entry_atomic(), and reset_alloc_id_atomic().
check_master()
bool jeod::JeodMemoryManager::check_master (bool error_is_fatal, int line) static private
Many of the static methods are a pass-through to a private non-static method, with the static method testing that the pass-through is valid.
This method performs that test and handles the failure response.
Returns
True if Master is not null
Parameters
[in] error_is_fatal True => call fail
[in] line LINE
Definition at line 62 of file memory_manager_static.cc.
References jeod::MessageHandler::error(), jeod::MessageHandler::fail(), Master, and jeod::MemoryMessages::singleton_error.
Referenced by create_memory(), deregister_container(), destroy_memory(), get_type_descriptor(), is_allocated(), is_table_empty(), register_class(), register_container(), set_debug_level(), set_guard_enabled(), and set_mode().
create_memory()
void * jeod::JeodMemoryManager::create_memory (bool is_array, unsigned int nelems, int fill, const TypeEntry & tentry, const char * file, unsigned int line) static
Allocate memory and register the allocated memory with JEOD.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
The allocated memory is not constructed by this method. The calling routine should initialize the memory with placement new.
Access to this method is through the JEOD memory allocation macros. Use in any other context is caveat emptor.
Returns
Allocated memory
Parameters
[in] is_array Memory constructed by new[] if set
[in] nelems Number of elements to be allocated
[in] fill Byte fill pattern
[in] tentry Type entry
[in] file Source file containing JEOD_ALLOC
[in] line Line number containing JEOD_ALLOC
Definition at line 269 of file memory_manager_static.cc.
References check_master(), create_memory_internal(), and Master.
create_memory_internal()
void * jeod::JeodMemoryManager::create_memory_internal (bool is_array, unsigned int nelems, int fill, const TypeEntry & tentry, const char * file, unsigned int line) private
Allocate memory for use with placement new and register that memory with with the memory manager and with the simulation engine.
Assumptions and Limitations
This method will be invoked via the JEOD memory allocation macros. Use in any other context is a case of caveat emptor.
The type descriptor index must index the type descriptor that describes the type to be created.
The memory is allocated but not constructed. Construction is the responsibility of the caller. The JEOD memory allocation macros construct the allocated memory via placement new.
Returns
Allocated memory
Parameters
[in] is_array Memory constructed by new[] if set
[in] nelems Number of elements to be allocated
[in] fill Byte fill pattern
[in] tentry Type entry
[in] file Source file containing JEOD_ALLOC
[in] line Line number containing JEOD_ALLOC
Definition at line 411 of file memory_manager.cc.
References allocate_memory(), jeod::JeodMemoryTypeDescriptor::get_size(), guard_enabled, register_memory_internal(), and jeod::JeodMemoryManager::TypeEntry::tdesc.
Referenced by create_memory().
delete_oldest_alloc_entry_atomic()
void jeod::JeodMemoryManager::delete_oldest_alloc_entry_atomic (void *& addr, JeodMemoryItem & item, const JeodMemoryTypeDescriptor *& type) private
Find and delete the alloc table entry with the smallest unique id, setting the provided references with info about the deleted item.
The addr and type are set to NULL if the table is empty.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
If the restore doesn't work the sim will be knee deep in alligators.
Parameters
[out] addr Address found in table
[out] item Descriptor for above
[out] type Type descriptor
Definition at line 810 of file memory_manager_protected.cc.
References alloc_table, allocation_number, begin_atomic_block(), jeod::JeodMemoryTypeDescriptor::buffer_size(), cur_data_size, end_atomic_block(), and get_type_descriptor_nolock().
Referenced by restart_clear_memory().
deregister_container()
void jeod::JeodMemoryManager::deregister_container (const void * container, const std::type_info & container_type, const char * elem_name, JeodCheckpointable & checkpointable) static
Deregister all checkpointable object contained within some object.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Parameters
[in] container Object container
[in] container_type Container type info
[in] elem_name Element name
[in,out] checkpointable Checkpointable object
Definition at line 417 of file memory_manager_static.cc.
References check_master(), jeod::NamedItem::demangle(), jeod::JeodMemoryInterface::deregister_container(), jeod::MessageHandler::fail(), get_type_descriptor_atomic(), Master, jeod::MemoryMessages::null_pointer, sim_interface, and jeod::JeodCheckpointable::undo_initialize_checkpointable().
destroy_memory()
void jeod::JeodMemoryManager::destroy_memory (void * addr, bool delete_array, const char * file, unsigned int line) static
Destroy memory previously registered with JEOD.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
The provided memory shall not be used in any way after calling this method. This method destructs and frees that memory.
Access to this method is through the JEOD memory allocation macros. Use in any other context is caveat emptor.
Parameters
[in,out] addr Memory to be destroyed
[in] delete_array DELETE_ARRAY (true) vs. DELETE_OBJECT
[in] file Source file containing delete
[in] line Line number containing delete
Definition at line 339 of file memory_manager_static.cc.
References check_master(), destroy_memory_internal(), and Master.
Referenced by jeod::collect_insert(), and jeod::collect_push_back().
destroy_memory_internal()
void jeod::JeodMemoryManager::destroy_memory_internal (void * addr, bool delete_array, const char * file, unsigned int line) private
Destroy a chunk of memory and knowledge about it.
This includes
De-registering the memory with JEOD and with an external agent.
Invoking the destructor in the case of a structured type.
Releasing the memory to the system.
Parameters
[in,out] addr Memory to be destroyed
[in] delete_array DELETE_ARRAY (true) vs. DELETE_OBJECT
[in] file Source file containing delete
[in] line Line number containing delete
Definition at line 587 of file memory_manager.cc.
References jeod::JeodMemoryTypeDescriptor::buffer_size(), jeod::MemoryMessages::debug, jeod::MessageHandler::debug(), debug_level, jeod::JeodMemoryInterface::deregister_allocation(), jeod::JeodMemoryTypeDescriptor::destroy_memory(), jeod::MessageHandler::error(), find_alloc_entry_atomic(), free_memory(), jeod::JeodMemoryItem::get_alloc_index(), jeod::JeodMemoryItem::get_is_array(), jeod::JeodMemoryItem::get_is_guarded(), jeod::JeodMemoryItem::get_is_registered(), jeod::JeodMemoryItem::get_nelems(), jeod::JeodMemoryItem::get_placement_new(), get_string_atomic(), jeod::MemoryMessages::null_pointer, sim_interface, jeod::MemoryMessages::suspect_pointer, jeod::JeodMemoryTypeDescriptor::type_spec(), and jeod::MessageHandler::warn().
Referenced by destroy_memory().
end_atomic_block()
void jeod::JeodMemoryManager::end_atomic_block (bool ignore_errors) const private
End an atomic set of operations.
Parameters
[in] ignore_errors Ignore errors from unlock?
Definition at line 126 of file memory_manager_protected.cc.
References jeod::MessageHandler::fail(), jeod::MemoryMessages::lock_error, and mutex.
Referenced by add_allocation_atomic(), add_string_atomic(), delete_oldest_alloc_entry_atomic(), find_alloc_entry_atomic(), get_alloc_id_atomic(), get_string_atomic(), get_type_descriptor_atomic(), get_type_entry_atomic(), and reset_alloc_id_atomic().
find_alloc_entry_atomic()
void jeod::JeodMemoryManager::find_alloc_entry_atomic (const void * addr, bool delete_entry, const char * file, unsigned int line, void *& found_addr, JeodMemoryItem & found_item, const JeodMemoryTypeDescriptor *& found_type) private
Find the allocation table entry that matches the input address, and delete it if delete_entry is true.
The matching is strict. A match occurs only if the input address is a key in the allocation table. An error is reported if the input address is inside the allocated space corresponding to one of the allocation table entries.
Output values:
Entry not found:
The found_addr and found_type are set to NULL.
The found_item is not touched.
Entry found:
The found_addr is set to the key of the found entry.
The found_item is copied from the value of the found entry.
The found_type points to the type_descriptor entry for the found item's type.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Parameters
[in] addr Address
[in] delete_entry Indicates entry is to be deleted
[in] file Source file containing JEOD_XXX
[in] line Line number containing JEOD_XXX
[out] found_addr Address found in table
[out] found_item Descriptor for above
[out] found_type Type descriptor
Definition at line 607 of file memory_manager_protected.cc.
References alloc_table, begin_atomic_block(), jeod::JeodMemoryTypeDescriptor::buffer_size(), cur_data_size, end_atomic_block(), jeod::JeodMemoryTypeDescriptor::get_name(), get_type_descriptor_nolock(), jeod::MemoryMessages::suspect_pointer, and jeod::MessageHandler::warn().
Referenced by destroy_memory_internal(), and is_allocated_internal().
free_memory()
void jeod::JeodMemoryManager::free_memory (void * addr, std::size_t length, bool guard, unsigned int alloc_idx, const char * file, unsigned int line) const private
Release memory.
Assumptions and Limitations
This is a low-level de-allocation function. It does not
De-register the memory with JEOD or with an external agent.
Destruct the memory.
Parameters
[in,out] addr Memory to be freed
[in] length Buffer size
[in] guard Memory was guarded if set
[in] alloc_idx Allocation index
[in] file Source file containing delete
[in] line Line number containing delete
Definition at line 813 of file memory_manager.cc.
References jeod::MemoryMessages::corrupted_memory, get_string_atomic(), MAGIC0, MAGIC1, and jeod::MessageHandler::warn().
Referenced by destroy_memory_internal(), and restart_clear_memory().
generate_shutdown_report()
void jeod::JeodMemoryManager::generate_shutdown_report (void) private
Generate a shutdown report.
Assumptions and Limitations
This method is to be called by the destructor only. It freely accesses tabular data, the assumption being that the mutex and flags that protect that data are now gone.
Definition at line 199 of file memory_manager.cc.
References alloc_table, jeod::MemoryMessages::corrupted_memory, jeod::MemoryMessages::debug, debug_level, jeod::JeodMemoryTable< ValueType >::get(), jeod::JeodMemoryItem::get_alloc_index(), get_type_descriptor_nolock(), jeod::MessageHandler::inform(), max_data_size, max_table_size, string_table, jeod::JeodMemoryTypeDescriptor::type_spec(), and jeod::MessageHandler::warn().
Referenced by ~JeodMemoryManager().
get_alloc_id_atomic()
uint32_t jeod::JeodMemoryManager::get_alloc_id_atomic (const char * file, unsigned int line) private
Create a unique identifier for an allocation.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Returns
Allocation ID
Parameters
[in] file Source file containing JEOD_ALLOC
[in] line Line number containing JEOD_ALLOC
Definition at line 509 of file memory_manager_protected.cc.
References allocation_number, begin_atomic_block(), jeod::MemoryMessages::corrupted_memory, end_atomic_block(), and jeod::MessageHandler::fail().
Referenced by register_memory_internal().
get_string_atomic()
const std::string & jeod::JeodMemoryManager::get_string_atomic (unsigned int idx) const private
Retrieve the specified string from the string table.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Returns
String table index
Parameters
[in] idx Class index
Definition at line 167 of file memory_manager_protected.cc.
References begin_atomic_block(), end_atomic_block(), jeod::MessageHandler::fail(), jeod::JeodMemoryTable< ValueType >::get(), jeod::MemoryMessages::internal_error, and string_table.
Referenced by destroy_memory_internal(), and free_memory().
get_type_descriptor() [1/2]
const JeodMemoryTypeDescriptor * jeod::JeodMemoryManager::get_type_descriptor (const std::type_info & typeid_info) static
Get a type descriptor from the memory manager's type table.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Returns
Type descriptor
Parameters
[in] typeid_info C++ type descriptor
Definition at line 204 of file memory_manager_static.cc.
References check_master(), get_type_descriptor_atomic(), and Master.
Referenced by jeod::JeodMemoryTypeDescriptor::base_type(), jeod::JeodTrick10MemoryInterface::checkpoint_allocations(), jeod::JeodDynbodyIntegrationLoop::find_containing_sim_object(), jeod::JeodPointerContainer< ContainerType, ElemType >::initialize_checkpointable(), and jeod::JeodContainer< ContainerType, ElemType *>::initialize_checkpointable().
get_type_descriptor() [2/2]
const JeodMemoryTypeDescriptor * jeod::JeodMemoryManager::get_type_descriptor (JeodMemoryManager::NameType name_type, const std::string & type_name) static
Get a type descriptor from the memory manager's type table.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Returns
Type descriptor
Parameters
[in] name_type Typeid or demangled name
[in] type_name Type name
Definition at line 232 of file memory_manager_static.cc.
References check_master(), get_type_entry_atomic(), Master, and jeod::JeodMemoryManager::TypeEntry::tdesc.
get_type_descriptor_atomic() [1/2]
const JeodMemoryTypeDescriptor * jeod::JeodMemoryManager::get_type_descriptor_atomic (const std::type_info & typeid_info) const private
Retrieve the descriptor for the specified type from the type table.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Returns
Type descriptor
Parameters
[in] typeid_info Type info
Definition at line 349 of file memory_manager_protected.cc.
References begin_atomic_block(), end_atomic_block(), jeod::JeodMemoryTable< ValueType >::find(), jeod::JeodMemoryTable< ValueType >::get(), and type_table.
Referenced by deregister_container(), get_type_descriptor(), and register_container().
get_type_descriptor_atomic() [2/2]
const JeodMemoryTypeDescriptor & jeod::JeodMemoryManager::get_type_descriptor_atomic (unsigned int idx) const private
Retrieve the descriptor for the specified type from the type table.
Assumptions and Limitations
The input index is non-zero. This assumption is enforced.
Operations on the map must be atomic. This method satisfies that requirement.
Returns
Type descriptor
Parameters
[in] idx Type index
Definition at line 459 of file memory_manager_protected.cc.
References begin_atomic_block(), end_atomic_block(), jeod::MessageHandler::fail(), jeod::JeodMemoryTable< ValueType >::get(), jeod::MemoryMessages::internal_error, and type_table.
get_type_descriptor_nolock()
const JeodMemoryTypeDescriptor & jeod::JeodMemoryManager::get_type_descriptor_nolock (const JeodMemoryItem & item) const inline private
Retrieve the descriptor for the specified type from the type table.
Assumptions and Limitations
The type is in the table. A core dump will result if it is not.
Operations on the type table must be atomic. This method does not satisfy that requirement.
Returns
Type descriptor
Parameters
[in] item Memory descriptor
Definition at line 643 of file memory_manager.hh.
References jeod::JeodMemoryTable< ValueType >::get(), jeod::JeodMemoryItem::get_descriptor_index(), and type_table.
Referenced by add_allocation_atomic(), delete_oldest_alloc_entry_atomic(), find_alloc_entry_atomic(), generate_shutdown_report(), and ~JeodMemoryManager().
get_type_entry_atomic() [1/2]
const JeodMemoryManager::TypeEntry jeod::JeodMemoryManager::get_type_entry_atomic (JeodMemoryTypePreDescriptor & tdesc) private
Return the type entry for the input type descriptor, adding the descriptor to the type table if the type has not yet been registered.
Assumptions and Limitations
The mangled name returned by the std::type_info name method is unique across all allocatable types and is invariant.
Operations on the map must be atomic. This method satisfies that requirement.
Returns
Type descriptor index
Parameters
[in] tdesc Type pre-descriptor
Definition at line 291 of file memory_manager_protected.cc.
References jeod::JeodMemoryTable< ValueType >::add(), begin_atomic_block(), jeod::MemoryMessages::debug, jeod::MessageHandler::debug(), debug_level, end_atomic_block(), jeod::JeodMemoryTable< ValueType >::find(), jeod::JeodMemoryTable< ValueType >::get(), jeod::JeodMemoryTypePreDescriptor::get_descriptor(), jeod::JeodMemoryTypeDescriptor::get_name(), jeod::JeodMemoryTypePreDescriptor::get_typeid(), and type_table.
Referenced by get_type_descriptor(), register_class(), and restart_reallocate().
get_type_entry_atomic() [2/2]
const JeodMemoryManager::TypeEntry jeod::JeodMemoryManager::get_type_entry_atomic (JeodMemoryManager::NameType name_type, const std::string & type_name) const private
Retrieve the descriptor for the specified type from the type table.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Returns
Type entry
Parameters
[in] name_type Name type spec
[in] type_name Type name
Definition at line 390 of file memory_manager_protected.cc.
References jeod::JeodMemoryTable< ValueType >::begin(), begin_atomic_block(), jeod::JeodMemoryTable< ValueType >::end(), end_atomic_block(), jeod::JeodMemoryTable< ValueType >::find(), jeod::JeodMemoryTable< ValueType >::get(), jeod::JeodMemoryTypeDescriptor::get_name(), type_table, and Typeid_type_name.
get_type_index_nolock()
bool jeod::JeodMemoryManager::get_type_index_nolock (const JeodMemoryTypeDescriptor & tdesc, uint32_t * idx) private
Retrieve the index for the specified type from the type table, adding an entry if needed.
Assumptions and Limitations
Operations on the type table must be atomic. This method does not satisfy that requirement.
Returns
True => table updated
Parameters
[in] tdesc Descriptor
[out] idx Type descriptor index
Definition at line 251 of file memory_manager_protected.cc.
References jeod::JeodMemoryTable< ValueType >::add(), jeod::JeodMemoryTable< ValueType >::find(), jeod::JeodMemoryTypeDescriptor::get_typeid(), and type_table.
is_allocated()
bool jeod::JeodMemoryManager::is_allocated (const void * addr, const char * file, unsigned int line) static
Query whether some address was allocated by JEOD.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Returns
True if allocated by JEOD
Parameters
[in] addr Memory to be queried
[in] file Source file containing query
[in] line Line number containing query
Definition at line 304 of file memory_manager_static.cc.
References check_master(), is_allocated_internal(), and Master.
is_allocated_internal()
bool jeod::JeodMemoryManager::is_allocated_internal (const void * addr, const char * file, unsigned int line) private
Query whether some address was allocated by JEOD.
Returns
True if the address in question was allocated by JEOD
Parameters
[in] addr Memory to be queried
[in] file Source file containing query
[in] line Line number containing query
Definition at line 552 of file memory_manager.cc.
References find_alloc_entry_atomic().
Referenced by is_allocated().
is_table_empty()
bool jeod::JeodMemoryManager::is_table_empty (void) static
Query whether all allocated memory has been freed.
Assumptions and Limitations
Intended for testing use only. This method does not use a thread-safe query.
Returns
Has all memory been freed?
Definition at line 146 of file memory_manager_static.cc.
References alloc_table, check_master(), and Master.
operator=()
JeodMemoryManager& jeod::JeodMemoryManager::operator= (const JeodMemoryManager &) private
Not implemented.
register_class()
const JeodMemoryManager::TypeEntry jeod::JeodMemoryManager::register_class (JeodMemoryTypePreDescriptor & tdesc) static
Register a class with the memory manager.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Access to this method is through the JEOD memory allocation macros. Use in any other context is caveat emptor.
Returns
Type entry for the class
Parameters
[in] tdesc Type pre-descriptor
Definition at line 175 of file memory_manager_static.cc.
References check_master(), get_type_entry_atomic(), and Master.
register_container()
void jeod::JeodMemoryManager::register_container (const void * container, const std::type_info & container_type, const char * elem_name, JeodCheckpointable & checkpointable) static
Register a checkpointable object with the memory manager.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Parameters
[in] container Object container
[in] container_type Container type info
[in] elem_name Element name
[in,out] checkpointable Checkpointable object
Definition at line 369 of file memory_manager_static.cc.
References check_master(), jeod::NamedItem::demangle(), jeod::MessageHandler::fail(), get_type_descriptor_atomic(), jeod::JeodCheckpointable::initialize_checkpointable(), Master, jeod::MemoryMessages::null_pointer, jeod::JeodMemoryInterface::register_container(), and sim_interface.
register_memory_internal()
void jeod::JeodMemoryManager::register_memory_internal (const void * addr, uint32_t unique_id, bool placement_new, bool is_array, unsigned int nelems, const TypeEntry & tentry, const char * file, unsigned int line) private
Allocate memory if that was not already done by the caller and register the memory with JEOD and with an external agent.
Assumptions and Limitations
This method will be invoked via the JEOD memory allocation macros. Use in any other context is caveat emptor.
The corresponding delete macro will be used to delete the memory. Using the C free function or the C++ delete operator can cause big problems.
The delete macro will be expanded with the same placement new option as was used in the allocation macro that resulted in this call.
The memory is not constructed. That is the job of the expansion of the JEOD_ALLOC macro.
Parameters
[in] addr Memory to be registered
[in] unique_id Unique id
[in] placement_new Was memory allocated by this model?
[in] is_array Was memory allocated as an array?
[in] nelems Array size
[in] tentry Type entry
[in] file Source file containing JEOD_ALLOC
[in] line Line number containing JEOD_ALLOC
Definition at line 453 of file memory_manager.cc.
References add_allocation_atomic(), add_string_atomic(), jeod::JeodMemoryTypeDescriptor::buffer_size(), jeod::MemoryMessages::debug, jeod::MessageHandler::debug(), debug_level, jeod::MessageHandler::error(), get_alloc_id_atomic(), jeod::JeodMemoryTypeDescriptor::get_register_instances(), jeod::JeodMemoryManager::TypeEntry::index, jeod::MemoryMessages::invalid_size, jeod::JeodMemoryTypeDescriptor::is_structured(), jeod::JeodMemoryInterface::register_allocation(), reset_alloc_id_atomic(), jeod::JeodMemoryItem::set_unique_id(), sim_interface, jeod::JeodMemoryManager::TypeEntry::tdesc, and jeod::JeodMemoryTypeDescriptor::type_spec().
Referenced by create_memory_internal(), and restart_reallocate().
reset_alloc_id_atomic()
void jeod::JeodMemoryManager::reset_alloc_id_atomic (uint32_t unique_id) private
Reset the unique identifier for a restart.
Assumptions and Limitations
Operations on the map must be atomic. This method satisfies that requirement.
Parameters
[in] unique_id Unique id of a restored allocation
Definition at line 556 of file memory_manager_protected.cc.
References allocation_number, begin_atomic_block(), and end_atomic_block().
Referenced by register_memory_internal().
restart_clear_memory()
void jeod::JeodMemoryManager::restart_clear_memory (void)
Wipe out all allocated memory in anticipation of restoring the memory in some previously recording checkpoint file.
Assumptions and Limitations
If the restore doesn't work the sim will be knee deep in alligators.
Definition at line 286 of file memory_manager.cc.
References allocation_number, jeod::JeodMemoryTypeDescriptor::buffer_size(), cur_data_size, delete_oldest_alloc_entry_atomic(), jeod::JeodMemoryInterface::deregister_allocation(), jeod::JeodMemoryTypeDescriptor::destroy_memory(), free_memory(), jeod::JeodMemoryItem::get_alloc_index(), jeod::JeodMemoryItem::get_is_array(), jeod::JeodMemoryItem::get_is_guarded(), jeod::JeodMemoryItem::get_is_registered(), jeod::JeodMemoryItem::get_nelems(), jeod::JeodMemoryItem::get_placement_new(), max_data_size, max_table_size, and sim_interface.
Referenced by jeod::JeodTrick10MemoryInterface::restore_allocations().
restart_reallocate()
void jeod::JeodMemoryManager::restart_reallocate (const std::string & mangled_type_name, uint32_t unique_id, uint32_t nelements, bool is_array)
Restore one chunk of allocated memory per a checkpoint file entry.
Assumptions and Limitations
This restores the allocation, but not the contents. The contents will soon be restored by the simulation engine.
Parameters
[in] mangled_type_name Mangled type name
[in] unique_id Unique id
[in] nelements Number of elements
[in] is_array True => an array
Definition at line 339 of file memory_manager.cc.
References allocate_memory(), jeod::JeodMemoryTypeDescriptor::construct_array(), jeod::MessageHandler::error(), jeod::JeodMemoryTypeDescriptor::get_size(), get_type_entry_atomic(), guard_enabled, register_memory_internal(), jeod::MemoryMessages::suspect_pointer, jeod::JeodMemoryManager::TypeEntry::tdesc, and Typeid_type_name.
Referenced by jeod::JeodTrick10MemoryInterface::restore_allocations().
set_debug_level() [1/2]
void jeod::JeodMemoryManager::set_debug_level (unsigned int level) static
Set the debug level.
Parameters
[in] level New debug level
Definition at line 107 of file memory_manager_static.cc.
References Full_details.
Referenced by jeod::JeodSimulationInterface::configure().
set_debug_level() [2/2]
void jeod::JeodMemoryManager::set_debug_level (DebugLevel level) static
Set the debug level.
Parameters
[in] level New debug level
Definition at line 89 of file memory_manager_static.cc.
References check_master(), debug_level, and Master.
set_guard_enabled()
void jeod::JeodMemoryManager::set_guard_enabled (bool value) static
Set the guard_enabled flag.
Parameters
[in] value New value
Definition at line 124 of file memory_manager_static.cc.
References check_master(), guard_enabled, and Master.
set_mode()
void jeod::JeodMemoryManager::set_mode (JeodSimulationInterface::Mode new_mode) static
Set the memory manager's simulation interface mode.
Assumptions and Limitations
This method must not be called before the singleton memory manager has been created or after it has been destroyed. A fatal error results when this is not true.
Parameters
[in] new_mode New mode
Definition at line 462 of file memory_manager_static.cc.
References check_master(), Master, and set_mode_internal().
Referenced by jeod::BasicJeodTrickSimInterface::set_mode().
set_mode_internal()
void jeod::JeodMemoryManager::set_mode_internal (JeodSimulationInterface::Mode new_mode) private
Set the mode and perform mode transitions.
Parameters
[in] new_mode New mode
Definition at line 693 of file memory_manager.cc.
References mode.
Referenced by set_mode().
Friends And Related Function Documentation
init_attrjeod__JeodMemoryManager
void init_attrjeod__JeodMemoryManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 214 of file memory_manager.hh.
Field Documentation
alloc_table
AllocTable jeod::JeodMemoryManager::alloc_table private
Maps memory addresses to the descriptions of those addresses.
trick_io(**)
Definition at line 585 of file memory_manager.hh.
Referenced by add_allocation_atomic(), delete_oldest_alloc_entry_atomic(), find_alloc_entry_atomic(), generate_shutdown_report(), is_table_empty(), and ~JeodMemoryManager().
allocation_number
unsigned int jeod::JeodMemoryManager::allocation_number private
Number of allocations.
This always increments and can be adjusted upward on restarts.trick_io(*o) trick_units(–)
Definition at line 575 of file memory_manager.hh.
Referenced by delete_oldest_alloc_entry_atomic(), get_alloc_id_atomic(), reset_alloc_id_atomic(), and restart_clear_memory().
cur_data_size
size_t jeod::JeodMemoryManager::cur_data_size private
Number of allocated user bytes (excludes management overhead).
trick_io(*o) trick_units(–)
Definition at line 559 of file memory_manager.hh.
Referenced by add_allocation_atomic(), delete_oldest_alloc_entry_atomic(), find_alloc_entry_atomic(), and restart_clear_memory().
debug_level
DebugLevel jeod::JeodMemoryManager::debug_level private
Debugging level.
0 = Minimal output, errors only.
1 = Summary report, generated just before exit(0).
2 = Report unfreed memory as well.
3 = Blow-by-blow report of each allocation and deallocation.trick_units(–)
Definition at line 554 of file memory_manager.hh.
Referenced by destroy_memory_internal(), generate_shutdown_report(), get_type_entry_atomic(), register_memory_internal(), and set_debug_level().
guard_enabled
bool jeod::JeodMemoryManager::guard_enabled private
Data can be guarded if this is set.
If not set, guards will never be established.trick_units(–)
Definition at line 612 of file memory_manager.hh.
Referenced by create_memory_internal(), restart_reallocate(), and set_guard_enabled().
Master
JeodMemoryManager * jeod::JeodMemoryManager::Master = nullptr static private
The singleton instance of the JeodMemoryManager class.
The constructor sets this pointer.trick_io(*o) trick_units(–)
Definition at line 389 of file memory_manager.hh.
Referenced by check_master(), create_memory(), deregister_container(), destroy_memory(), get_type_descriptor(), is_allocated(), is_table_empty(), JeodMemoryManager(), register_class(), register_container(), set_debug_level(), set_guard_enabled(), set_mode(), and ~JeodMemoryManager().
max_data_size
size_t jeod::JeodMemoryManager::max_data_size private
Maximum value attained by cur_data_size.
trick_io(*o) trick_units(–)
Definition at line 564 of file memory_manager.hh.
Referenced by add_allocation_atomic(), generate_shutdown_report(), and restart_clear_memory().
max_table_size
unsigned int jeod::JeodMemoryManager::max_table_size private
Maximum value attained by alloc_table.size().
trick_io(*o) trick_units(–)
Definition at line 569 of file memory_manager.hh.
Referenced by add_allocation_atomic(), generate_shutdown_report(), and restart_clear_memory().
mode
JeodSimulationInterface::Mode jeod::JeodMemoryManager::mode private
Simulation interface mode.
trick_units(–)
Definition at line 606 of file memory_manager.hh.
Referenced by set_mode_internal().
mutex
pthread_mutex_t jeod::JeodMemoryManager::mutex mutable private
Mutex that synchronizes access to the tables.
trick_io(**)
Definition at line 601 of file memory_manager.hh.
Referenced by begin_atomic_block(), end_atomic_block(), JeodMemoryManager(), and ~JeodMemoryManager().
sim_interface
JeodMemoryInterface& jeod::JeodMemoryManager::sim_interface private
The interface to the simulation engine's memory manager.
trick_io(*o) trick_units(–)
Definition at line 545 of file memory_manager.hh.
Referenced by deregister_container(), destroy_memory_internal(), register_container(), register_memory_internal(), restart_clear_memory(), and ~JeodMemoryManager().
string_table
JeodMemoryReflectiveTable jeod::JeodMemoryManager::string_table private
Maps unique strings to themselves.
trick_io(**)
Definition at line 595 of file memory_manager.hh.
Referenced by add_string_atomic(), generate_shutdown_report(), and get_string_atomic().
type_table
TypeTable jeod::JeodMemoryManager::type_table private
Maps typeid names to type descriptors.
trick_io(**)
Definition at line 590 of file memory_manager.hh.
Referenced by get_type_descriptor_atomic(), get_type_descriptor_nolock(), get_type_entry_atomic(), and get_type_index_nolock().
The documentation for this class was generated from the following files:
memory_manager.hh
memory_manager.cc
memory_manager_protected.cc
memory_manager_static.cc