JEOD: jeod::ContactSurfaceFactory Class Reference
jeod::ContactSurfaceFactory Class Reference
The surface factory that creates an contact specific surface from a general surface.
#include <contact_surface_factory.hh>
Public Member Functions
ContactSurfaceFactory ()
Default Constructor.
~ContactSurfaceFactory () override=default
ContactSurfaceFactory & operator= (const ContactSurfaceFactory &)=delete
ContactSurfaceFactory (const ContactSurfaceFactory &)=delete
void create_surface (SurfaceModel *surface, InteractionSurface *inter_surface) override
Creates an interaction surface, in the inter_surface parameter, from the given SurfaceModel.
void add_facet_params (FacetParams *to_add) override
Add a named set of facet params to the surface factory.
Public Member Functions inherited from jeod::InteractionSurfaceFactory
InteractionSurfaceFactory ()
Default Constructor.
virtual ~InteractionSurfaceFactory ()
Destructor.
InteractionSurfaceFactory & operator= (const InteractionSurfaceFactory &)=delete
InteractionSurfaceFactory (const InteractionSurfaceFactory &)=delete
void create_surface (SurfaceModel &surface, InteractionSurface &inter_surface)
Convenience version of create_surface which can be called from the input file.
virtual void add_facet_factory (InteractionFacetFactory *to_add)
Used to add an interaction facet factory for use in the surface factory.
Protected Attributes
PointContactFacetFactory point_contact_facet_factory
A factory that can create a point contact facet from a circular flat plate.
LineContactFacetFactory line_contact_facet_factory
A factory that can create a line contact facet from a cylinder.
Friends
class InputProcessor
void init_attrjeod__ContactSurfaceFactory ()
Additional Inherited Members
Data Fields inherited from jeod::InteractionSurfaceFactory
JeodPointerVector< InteractionFacetFactory >::type factories
A vector of interaction facet factories to be used.
JeodPointerVector< FacetParams >::type params
A vector of FacetParams to be used.
Detailed Description
The surface factory that creates an contact specific surface from a general surface.
Used with the surface model.
Definition at line 86 of file contact_surface_factory.hh.
Constructor & Destructor Documentation
ContactSurfaceFactory() [1/2]
jeod::ContactSurfaceFactory::ContactSurfaceFactory ()
Default Constructor.
Definition at line 48 of file contact_surface_factory.cc.
References jeod::InteractionSurfaceFactory::factories, line_contact_facet_factory, and point_contact_facet_factory.
~ContactSurfaceFactory()
jeod::ContactSurfaceFactory::~ContactSurfaceFactory () override default
ContactSurfaceFactory() [2/2]
jeod::ContactSurfaceFactory::ContactSurfaceFactory (const ContactSurfaceFactory &) delete
Member Function Documentation
add_facet_params()
void jeod::ContactSurfaceFactory::add_facet_params (FacetParams * to_add) override virtual
Add a named set of facet params to the surface factory.
Intended to be used when an contact specific surface is created, to convert a basic facet to an contact interaction facet. This MUST be a parameter inheriting from ContactParam, or the function will fail and send a failure message
Parameters
[in] to_add The facet parameters to add
Reimplemented from jeod::InteractionSurfaceFactory.
Definition at line 176 of file contact_surface_factory.cc.
References jeod::InteractionSurfaceFactory::add_facet_params(), jeod::MessageHandler::fail(), jeod::FacetParams::name, and jeod::ContactMessages::pre_initialization_error.
create_surface()
void jeod::ContactSurfaceFactory::create_surface (SurfaceModel * surface, InteractionSurface * inter_surface) override virtual
Creates an interaction surface, in the inter_surface parameter, from the given SurfaceModel.
The InteractionSurfaceFactory should contain all necessary InteractionFacetFactories and FacetParams already
Parameters
[in] surface The surface model used to create the interaction surface
[out] inter_surface Where the interaction surface will be produced
Reimplemented from jeod::InteractionSurfaceFactory.
Definition at line 65 of file contact_surface_factory.cc.
References jeod::InteractionSurface::allocate_array(), jeod::InteractionSurface::allocate_interaction_facet(), jeod::SurfaceModel::facets, jeod::InteractionSurfaceFactory::factories, jeod::MessageHandler::fail(), jeod::ContactMessages::initialization_error, and jeod::InteractionSurfaceFactory::params.
operator=()
ContactSurfaceFactory& jeod::ContactSurfaceFactory::operator= (const ContactSurfaceFactory &) delete
Friends And Related Function Documentation
init_attrjeod__ContactSurfaceFactory
void init_attrjeod__ContactSurfaceFactory () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file contact_surface_factory.hh.
Field Documentation
line_contact_facet_factory
LineContactFacetFactory jeod::ContactSurfaceFactory::line_contact_facet_factory protected
A factory that can create a line contact facet from a cylinder.
trick_units(–)
Definition at line 115 of file contact_surface_factory.hh.
Referenced by ContactSurfaceFactory().
point_contact_facet_factory
PointContactFacetFactory jeod::ContactSurfaceFactory::point_contact_facet_factory protected
A factory that can create a point contact facet from a circular flat plate.
trick_units(–)
Definition at line 110 of file contact_surface_factory.hh.
Referenced by ContactSurfaceFactory().
The documentation for this class was generated from the following files:
contact_surface_factory.hh
contact_surface_factory.cc