JEOD: jeod::SectionedInputStream Class Reference
jeod::SectionedInputStream Class Reference
A SectionedInputStream is a std::istream that reads from a section in a checkpoint file.
#include <checkpoint_input_manager.hh>
Public Member Functions
SectionedInputStream ()
Construct a SectionedInputStream object.
SectionedInputStream (const SectionedInputStream &)
Construct a SectionedInputStream object by copying from another.
~SectionedInputStream () override
Destruct a SectionedInputStream object.
bool is_activatable () const
Determine if the stream is able to be activated.
bool activate ()
Activate the object.
void deactivate (void)
Deactivate the object.
bool operator! () const
Conversion to boolean.
operator void * () const
Conversion to void*.
Private Member Functions
SectionedInputStream (CheckPointInputManager *mngr, std::ifstream &fstream, std::size_t spos, std::size_t epos)
Construct a SectionedInputStream object that is connected to a file stream and to a CheckPointInputManager.
SectionedInputStream & operator= (const SectionedInputStream &)
Not implemented.
Private Attributes
SectionedInputBuffer sectbuf
The std::streambuf that does the reading from the file.
CheckPointInputManager * manager
The input manager that created this object.
std::ifstream * stream
The C++ file stream that reads from the checkpoint file.
size_t start_pos
The position of the start of the contents of the checkpoint file section being read by this object.
size_t end_pos
The position just after the end of the contents of the checkpoint file section being read by this object.
bool is_copy
Is this a copy of some other SectionedInputStream? Copies of copies are verboten.
bool is_active
Is this an active object? In the end, there can be only one.
Friends
class CheckPointInputManager
Detailed Description
A SectionedInputStream is a std::istream that reads from a section in a checkpoint file.
This class will indicate EOF when the input pointer in the checkpoint file file buffer goes beyond the end of the section.
This is a barebones implementation. It does not provide buffering, it does not support seek and tell, and it does not support putback or unget.
Usage
A SectionedInputStream object is used in a preload_checkpoint or restart job to read and then act on contents stored in a checkpoint file.
return_type function_name (
   SomeStructureType & stuff_to_restore)
{
   std::string section_name;
   double number;
   char c_style_line[256];
   std::string cpp_line;
   char character;
   int char_as_int;
   std::string section_name;
   // Set to name of the checkpoint section
   // Construct a checkpoint input stream.
   // Notes:
   // - This object must go out of scope by the end of the job.
   // - DO NOT make a copy of this object.
   // - DO NOT save a pointer to this object in a permanent structure.
   // - The code below assumes that function_name is called as a
   //   preload_checkpoint or a restart job.
  SectionedInputStream reader (
     JeodSimulationInterface::get_checkpoint_reader(section_name));
  // Activate the reader.
  // Fail to do so and you'll get EOF on the first read.
  reader.activate();
  // You can use the C++ operator >> to read various kinds of data ...
  reader >> number;
  // ... even data structures if the structure has a deserializer.
  reader >> stuff_to_restore;
  // Lines can be read with the getline member or std::getline global.
  reader.getline (c_style_line, 255);
  std::getline (reader, cpp_line);
  // Individual characters can be read in a variety of ways.
  reader >> std::noskipws >> character;
  reader.get (character);
  char_as_int = reader.rdbuf()->sbumpc();
  // A bunch of numbers can be read using operator >>:
  while (!! (reader >> number)) {
     stuff_to_restore.add_number (number);
  }
  // An alternative is to implicitly use operator void*:
  while (reader >> number) {
     stuff_to_restore.add_number (number);
  }
  // The file can be scanned via getline, here using the bang-bang trick:
  while (!! std::getline (reader, cpp_string)) {
     process_line (cpp_string);
  }
  // Same as the above, but implicitly using operator void*:
  while (std::getline (reader, cpp_string)) {
     process_line (cpp_string);
  }
  // The file can be processed a character at a time.
  // Once again, either the bang-bang trick or operator void* can be
  // used to check for EOF.
  while (!! std::get (reader, character)) {
     stuff_to_restore.add_char (character);
  }
  // Yet another alternative is to test for EOF using sbumpc:
  while ((char_as_int = rdbuf->sbumpc()) != EOF) {
     stuff_to_restore.add_char ((char)char_as_int);
  }
  // Or use sgetc/sbumpc if the above grates too much:
  while (reader.rdbuf->sgetc()) != EOF) {
     stuff_to_restore.add_char ((char)reader.rdbuf()->sbumpc());
  }
}
Diagnosing problems
Nothing is being read. This can be caused by several problems, described below.
Is the JEOD checkpoint file open for input?
Checkpoint file sections can only be read from a JEOD checkpoint file that is open for input. In a Trick context, the checkpoint file is only open for preload_checkpoint and restart jobs. Reading from a checkpoint file in other contexts won't work.
Are multiple threads trying to read from the same checkpoint file?
Don't do that. This package is not thread-safe.
Have you cached some another active checkpoint reader somewhere?
Don't do that, either. Only one reader can be active at a time.
Is the checkpoint file section in the checkpoint file?
You will get a diagnostic message if the section doesn't exist.
Is the checkpoint reader viable?
The above problems will result in a non-viable checkpoint reader. The method is_activatable() can be called prior to calling activate() to check whether the stream is viable.
Did you call reader.activate()?
Whether compilers make two different objects in the construction of the SectionedInputStream or just one object depends on the compiler and on the optimization level. Making the package robustly handle the complexities of RVO (return value optimization) was too much for the author of the package. The call to reader.activate() is essential.
Did the call to reader.activate() work?
The method activate() returns true or false to indicate success or failure. While the above code did not check status, doing so is a good idea.
Did you call reader.deactivate()?
Don't do that until you are done reading. The call to deactivate() is irreversible.
Did you mix scanned input with line reading?
As with any other stream, operator >> will mark the stream as failed if the operator fails to parse.
Definition at line 309 of file checkpoint_input_manager.hh.
Constructor & Destructor Documentation
SectionedInputStream() [1/3]
jeod::SectionedInputStream::SectionedInputStream ()
Construct a SectionedInputStream object.
Note
This default constructor creates a disconnected and hence unusable stream. Usable streams are created by the non-default constructor.
Definition at line 130 of file checkpoint_input_manager.cc.
SectionedInputStream() [2/3]
jeod::SectionedInputStream::SectionedInputStream (const SectionedInputStream & source)
Construct a SectionedInputStream object by copying from another.
Parameters
[in] source Source object
Definition at line 176 of file checkpoint_input_manager.cc.
References jeod::MessageHandler::error(), jeod::SimInterfaceMessages::implementation_error, is_active, is_copy, manager, and stream.
~SectionedInputStream()
jeod::SectionedInputStream::~SectionedInputStream (void) override
Destruct a SectionedInputStream object.
Definition at line 204 of file checkpoint_input_manager.cc.
References jeod::CheckPointInputManager::deregister_reader(), is_active, and manager.
SectionedInputStream() [3/3]
jeod::SectionedInputStream::SectionedInputStream (CheckPointInputManager * mngr, std::ifstream & ifstream, std::size_t spos, std::size_t epos) private
Construct a SectionedInputStream object that is connected to a file stream and to a CheckPointInputManager.
Parameters
[in] mngr The stream manager
[in] ifstream The input file stream
[in] spos Start position of section data
[in] epos End position of section data
Definition at line 153 of file checkpoint_input_manager.cc.
Member Function Documentation
activate()
bool jeod::SectionedInputStream::activate (void)
Activate the object.
Note
Using the object for reading prior to activation will result in EOF.
Returns
True if activated.
Definition at line 244 of file checkpoint_input_manager.cc.
References jeod::SectionedInputBuffer::activate(), end_pos, jeod::MessageHandler::error(), jeod::SimInterfaceMessages::implementation_error, is_active, manager, jeod::CheckPointInputManager::register_reader(), sectbuf, start_pos, and stream.
Referenced by jeod::JeodTrick10MemoryInterface::restore_allocations(), and jeod::JeodTrick10MemoryInterface::restore_containers().
deactivate()
void jeod::SectionedInputStream::deactivate (void)
Deactivate the object.
Note
Deactivation is undoable.
Definition at line 289 of file checkpoint_input_manager.cc.
References jeod::SectionedInputBuffer::deactivate(), jeod::CheckPointInputManager::deregister_reader(), is_active, manager, sectbuf, and stream.
Referenced by jeod::CheckPointInputManager::create_trick_section_reader(), and jeod::JeodTrick10MemoryInterface::restore_containers().
is_activatable()
bool jeod::SectionedInputStream::is_activatable (void) const
Determine if the stream is able to be activated.
Returns
True if object can be activated.
Definition at line 219 of file checkpoint_input_manager.cc.
References jeod::CheckPointInputManager::have_active_reader(), is_active, manager, and stream.
operator void *()
jeod::SectionedInputStream::operator void * () const inline
Conversion to void*.
This method provides an alternative to the bang-bang trick to determine if the object is OK.
Returns
this pointer (cast to void*) if object is OK, NULL otherwise.
Definition at line 346 of file checkpoint_input_manager.hh.
operator!()
bool jeod::SectionedInputStream::operator! () const inline
Conversion to boolean.
Use the bang-bang trick to determine if the object is OK.
Returns
False if object is OK, true if something is wrong.
Definition at line 337 of file checkpoint_input_manager.hh.
References is_active, sectbuf, and stream.
operator=()
SectionedInputStream& jeod::SectionedInputStream::operator= (const SectionedInputStream &) private
Not implemented.
Friends And Related Function Documentation
CheckPointInputManager
friend class CheckPointInputManager friend
Definition at line 310 of file checkpoint_input_manager.hh.
Field Documentation
end_pos
size_t jeod::SectionedInputStream::end_pos private
The position just after the end of the contents of the checkpoint file section being read by this object.
trick_io(**)
Definition at line 387 of file checkpoint_input_manager.hh.
Referenced by activate().
is_active
bool jeod::SectionedInputStream::is_active private
Is this an active object? In the end, there can be only one.
trick_io(**)
Definition at line 399 of file checkpoint_input_manager.hh.
Referenced by activate(), deactivate(), is_activatable(), operator!(), SectionedInputStream(), and ~SectionedInputStream().
is_copy
bool jeod::SectionedInputStream::is_copy private
Is this a copy of some other SectionedInputStream? Copies of copies are verboten.
trick_io(**)
Definition at line 393 of file checkpoint_input_manager.hh.
Referenced by SectionedInputStream().
manager
CheckPointInputManager* jeod::SectionedInputStream::manager private
The input manager that created this object.
trick_io(**)
Definition at line 370 of file checkpoint_input_manager.hh.
Referenced by activate(), deactivate(), is_activatable(), SectionedInputStream(), and ~SectionedInputStream().
sectbuf
SectionedInputBuffer jeod::SectionedInputStream::sectbuf private
The std::streambuf that does the reading from the file.
trick_io(**)
Definition at line 365 of file checkpoint_input_manager.hh.
Referenced by activate(), deactivate(), and operator!().
start_pos
size_t jeod::SectionedInputStream::start_pos private
The position of the start of the contents of the checkpoint file section being read by this object.
trick_io(**)
Definition at line 381 of file checkpoint_input_manager.hh.
Referenced by activate().
stream
std::ifstream* jeod::SectionedInputStream::stream private
The C++ file stream that reads from the checkpoint file.
trick_io(**)
Definition at line 375 of file checkpoint_input_manager.hh.
Referenced by activate(), deactivate(), is_activatable(), operator!(), and SectionedInputStream().
The documentation for this class was generated from the following files:
checkpoint_input_manager.hh
checkpoint_input_manager.cc