JEOD: jeod::EphemerisZXZOrientation Class Reference
jeod::EphemerisZXZOrientation Class Reference
The EphemerisZXZOrientation is an EphemerisOrientation subclass that updates orientation based on an Z-X-Z Euler sequence and the time derivatives of this sequence.
#include <ephem_orient_zxz.hh>
Public Member Functions
EphemerisZXZOrientation ()
Construct an ephemeris angle.
~EphemerisZXZOrientation () override
Destroy an ephemeris angle.
const double * get_euler_angles () const
Return the Euler angles.
void get_euler_angles (double *angles) const
Return the Euler angles.
const double * get_euler_rates () const
Return the Euler rates.
void get_euler_rates (double *rates) const
Return the Euler angles.
virtual void update (const double *angles, const double *derivs, double time)
Compute a JEOD rotational state given a 3-1-3 inertial-to-planet-fixed Euler sequence and the time derivatives of the Euler angles.
virtual void propagate (double to_time)
Propagate the orientation to the current time.
Public Member Functions inherited from jeod::EphemerisOrientation
EphemerisOrientation ()
Construct an ephemeris angle.
~EphemerisOrientation () override
Destroy an ephemeris angle.
TargetAspect updates_what (void) const override
Specify the aspect of the target frame updated by the object.
void enable () override
Enable a EphemerisItem object.
void note_frame_status_change (RefFrame *frame) override
Null implementation.
const char * default_suffix () const override
Return the default suffix for this item class, i.e., "pfix".
void disconnect_from_tree () override
Disconnect the item from the tree; this is a no-op for an EphemerisOrientation.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()
Construct an ephemeris item.
~EphemerisItem () override
Destroy an ephemeris item.
virtual void set_name (const char *new_name)
Name an ephemeris item.
virtual void set_name (const char *pname, const char *fname)
Name an ephemeris item.
const char * get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp (void) const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item (void) const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const char *new_value, const char *old_value, const char *variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
Protected Attributes
double euler_angle_313 [3]
Astronomical (zxz) Euler angles.
double euler_rate_313 [3]
Time derivatives of the zyz Euler angles.
Protected Attributes inherited from jeod::EphemerisOrientation
bool subscribed_to_inertial
A subscription to the planet's inertial frame is issued whenever the planet's planet-fixed frame is active to ensure that the the planet-fixed frame is a part of the ref frame tree.
Protected Attributes inherited from jeod::EphemerisItem
char * name
The name of the item.
EphemerisInterface * owner
The ephemeris model that owns this object.
BaseEphemeridesManager * manager
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame
The reference frame whose non-constant state is set by this object.
EphemerisItem * head
The first ephemeris item with the same name as this item.
EphemerisItem * next
The next ephemeris item with the same name as this item.
double update_time
Time of last update, dynamic time seconds.
bool enabled
Is the item enabled?
bool active
Is the item active?
Private Member Functions
EphemerisZXZOrientation (const EphemerisZXZOrientation &)
Not implemented.
EphemerisZXZOrientation & operator= (const EphemerisZXZOrientation &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EphemerisZXZOrientation ()
Additional Inherited Members
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (char *new_name)
Name an ephemeris item.
Detailed Description
The EphemerisZXZOrientation is an EphemerisOrientation subclass that updates orientation based on an Z-X-Z Euler sequence and the time derivatives of this sequence.
Definition at line 90 of file ephem_orient_zxz.hh.
Constructor & Destructor Documentation
EphemerisZXZOrientation() [1/2]
jeod::EphemerisZXZOrientation::EphemerisZXZOrientation (void)
Construct an ephemeris angle.
Definition at line 80 of file ephem_orient_zxz.cc.
References euler_angle_313, euler_rate_313, and jeod::Vector3::initialize().
~EphemerisZXZOrientation()
jeod::EphemerisZXZOrientation::~EphemerisZXZOrientation (void) override
Destroy an ephemeris angle.
Definition at line 93 of file ephem_orient_zxz.cc.
EphemerisZXZOrientation() [2/2]
jeod::EphemerisZXZOrientation::EphemerisZXZOrientation (const EphemerisZXZOrientation &) private
Not implemented.
Member Function Documentation
get_euler_angles() [1/2]
const double * jeod::EphemerisZXZOrientation::get_euler_angles (void) const
Return the Euler angles.
Returns
Euler angles
Definition at line 105 of file ephem_orient_zxz.cc.
References euler_angle_313.
get_euler_angles() [2/2]
void jeod::EphemerisZXZOrientation::get_euler_angles (double * angles) const
Return the Euler angles.
Parameters
[out] angles Euler angles
Units: r
Definition at line 118 of file ephem_orient_zxz.cc.
References euler_angle_313.
get_euler_rates() [1/2]
const double * jeod::EphemerisZXZOrientation::get_euler_rates (void) const
Return the Euler rates.
Returns
Euler rates
Definition at line 135 of file ephem_orient_zxz.cc.
References euler_rate_313.
get_euler_rates() [2/2]
void jeod::EphemerisZXZOrientation::get_euler_rates (double * rates) const
Return the Euler angles.
Parameters
[out] rates Euler rates
Units: r/s
Definition at line 148 of file ephem_orient_zxz.cc.
References euler_rate_313.
operator=()
EphemerisZXZOrientation& jeod::EphemerisZXZOrientation::operator= (const EphemerisZXZOrientation &) private
Not implemented.
propagate()
void jeod::EphemerisZXZOrientation::propagate (double to_time) virtual
Propagate the orientation to the current time.
Assumptions and Limitations
The orientation has been computed.
Rotation is constant during the update interval.
Parameters
[in] to_time Target dynamic time
Units: s
Definition at line 167 of file ephem_orient_zxz.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_unit, jeod::RefFrameRot::compute_transformation(), jeod::Quaternion::conjugate_multiply(), EPSILON_TIME, jeod::Quaternion::normalize_integ(), jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, jeod::Quaternion::scalar, jeod::Vector3::scale(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::EphemerisItem::target_frame, TAYLOR_CUTOFF, jeod::EphemerisItem::update_time, and jeod::Quaternion::vector.
Referenced by jeod::De4xxEphemeris::propagate_lunar_rnp().
update()
void jeod::EphemerisZXZOrientation::update (const double * angles, const double * derivs, double time) virtual
Compute a JEOD rotational state given a 3-1-3 inertial-to-planet-fixed Euler sequence and the time derivatives of the Euler angles.
Parameters
[in] angles zxz Euler angles
Units: r
[in] derivs zxz Euler angle time derivatives
Units: r/s
[in] time Update time
Units: s
Definition at line 230 of file ephem_orient_zxz.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::ang_vel_unit, euler_angle_313, euler_rate_313, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, jeod::Quaternion::scalar, jeod::Vector3::scale(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::EphemerisItem::target_frame, jeod::EphemerisItem::update_time, jeod::Quaternion::vector, and jeod::Vector3::vmag().
Referenced by jeod::De4xxEphemeris::ephem_update().
Friends And Related Function Documentation
init_attrjeod__EphemerisZXZOrientation
void init_attrjeod__EphemerisZXZOrientation () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file ephem_orient_zxz.hh.
Field Documentation
euler_angle_313
double jeod::EphemerisZXZOrientation::euler_angle_313[3] protected
Astronomical (zxz) Euler angles.
trick_units(rad)
Definition at line 130 of file ephem_orient_zxz.hh.
Referenced by EphemerisZXZOrientation(), get_euler_angles(), and update().
euler_rate_313
double jeod::EphemerisZXZOrientation::euler_rate_313[3] protected
Time derivatives of the zyz Euler angles.
trick_units(rad/s)
Definition at line 135 of file ephem_orient_zxz.hh.
Referenced by EphemerisZXZOrientation(), get_euler_rates(), and update().
The documentation for this class was generated from the following files:
ephem_orient_zxz.hh
ephem_orient_zxz.cc