JEOD: jeod::LineContactFacet Class Reference
jeod::LineContactFacet Class Reference
The contact facet based on the distance to a single point, specifically the vehicle point.
#include <line_contact_facet.hh>
Public Member Functions
LineContactFacet ()
Default constructor.
~LineContactFacet () override=default
LineContactFacet & operator= (const LineContactFacet &)=delete
LineContactFacet (const LineContactFacet &)=delete
ContactPair * create_pair () override
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
ContactPair * create_pair (ContactFacet *target, Contact *contact) override
Overloaded functions that creates a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
void set_max_dimension () override
calculate the max dimension of the facet for range limit determination.
void calculate_torque (double *tmp_force) override
Calculate the torque generated on the vehicle by the facet.
void calculate_contact_point (double nvec[3]) override
Find the point on the surface that coorisponds to the closest point on line segments using the radius value.
Public Member Functions inherited from jeod::PointContactFacet
PointContactFacet ()
Default constructor.
~PointContactFacet () override=default
PointContactFacet & operator= (const PointContactFacet &)=delete
PointContactFacet (const PointContactFacet &)=delete
ContactPair * create_pair () override
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
ContactPair * create_pair (ContactFacet *target, Contact *contact) override
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
void set_max_dimension () override
calculate the max dimension of the facet for range limit determination.
void calculate_torque (double *tmp_force) override
Calculate the torque generated on the vehicle by the facet.
Public Member Functions inherited from jeod::ContactFacet
ContactFacet ()=default
~ContactFacet () override=default
ContactFacet & operator= (const ContactFacet &)=delete
ContactFacet (const ContactFacet &)=delete
void create_vehicle_point ()
Create a vehicle point to track the state information of the contact facet.
std::string get_name () const
Accessor for name.
Public Member Functions inherited from jeod::InteractionFacet
InteractionFacet ()=default
virtual ~InteractionFacet ()=default
InteractionFacet & operator= (const InteractionFacet &)=delete
InteractionFacet (const InteractionFacet &)=delete
Data Fields
double length {}
length of the line along the vehicle point x axis.
Data Fields inherited from jeod::PointContactFacet
double radius {}
radius from the point at which contact takes place.
double contact_point [3] {}
Contact point given in facet vehicle point frame, representing point on the point on the surface of a sphere of radius "radius" where contact has occured.
Data Fields inherited from jeod::ContactFacet
bool active {true}
toggles this contact facet on and off, true=on false=off
ContactParams * surface_type {}
Stores the name of surface material that the facet is constructed of.
DynBody * vehicle_body {}
DynBody associated with this facet for structural frame information.
double max_dimension {}
maximum dimension of the contact facet for use in limiting pair in_contact calls
double position [3] {}
position of the facet in vehicle structural frame.
double normal [3] {}
normal of the facet relative to the vehicle structural frame.
const BodyRefFrame * vehicle_point {}
Vehicle point for relstate calculations.
Data Fields inherited from jeod::InteractionFacet
double force [3] {}
The force on the facet caused by the environment interaction.
double torque [3] {}
The torque on the facet caused by the environment interaction.
Facet * base_facet {}
The original facet from which this interaction facet was created.
Friends
class InputProcessor
void init_attrjeod__LineContactFacet ()
Detailed Description
The contact facet based on the distance to a single point, specifically the vehicle point.
In effect this represents a sphere.
Definition at line 87 of file line_contact_facet.hh.
Constructor & Destructor Documentation
LineContactFacet() [1/2]
jeod::LineContactFacet::LineContactFacet ()
Default constructor.
Definition at line 52 of file line_contact_facet.cc.
References JEOD_REGISTER_CLASS.
~LineContactFacet()
jeod::LineContactFacet::~LineContactFacet () override default
LineContactFacet() [2/2]
jeod::LineContactFacet::LineContactFacet (const LineContactFacet &) delete
Member Function Documentation
calculate_contact_point()
void jeod::LineContactFacet::calculate_contact_point (double nvec[3]) override virtual
Find the point on the surface that coorisponds to the closest point on line segments using the radius value.
Parameters
[in] nvec vector between line points
Reimplemented from jeod::PointContactFacet.
Definition at line 159 of file line_contact_facet.cc.
References jeod::Numerical::compare_exact(), jeod::PointContactFacet::contact_point, jeod::Vector3::diff(), jeod::Numerical::fabs(), jeod::Vector3::initialize(), length, jeod::Vector3::normalize(), jeod::PointContactFacet::radius, jeod::Vector3::scale(), jeod::Numerical::square(), jeod::Vector3::sum(), and jeod::Vector3::vmag().
Referenced by jeod::LineContactPair::in_contact(), and jeod::LinePointContactPair::in_contact().
calculate_torque()
void jeod::LineContactFacet::calculate_torque (double * tmp_force) override virtual
Calculate the torque generated on the vehicle by the facet.
Assumes that the force is in the vehicle structural frame, but that close_point is not.
Parameters
[in] tmp_force force from one contact interaction.
Units: N
Implements jeod::ContactFacet.
Definition at line 212 of file line_contact_facet.cc.
References jeod::MassBody::composite_properties, jeod::PointContactFacet::contact_point, jeod::Vector3::cross(), jeod::Vector3::diff(), jeod::DynBody::mass, jeod::BodyRefFrame::mass_point, jeod::MassPointState::position, jeod::RefFrameState::rot, jeod::RefFrame::state, jeod::DynBody::structure, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::InteractionFacet::torque, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::ContactFacet::vehicle_body, and jeod::ContactFacet::vehicle_point.
create_pair() [1/2]
ContactPair * jeod::LineContactFacet::create_pair () override virtual
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
This function is called to create a pair that only contains a subject.
Returns
ContactPair that was created
Implements jeod::ContactFacet.
Definition at line 64 of file line_contact_facet.cc.
References jeod::LineContactPair::initialize_pair(), and JEOD_ALLOC_CLASS_OBJECT.
create_pair() [2/2]
ContactPair * jeod::LineContactFacet::create_pair (ContactFacet * target, Contact * contact) override virtual
Overloaded functions that creates a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
This function is called when a subject and target are known.
Returns
ContactPair that was created
Parameters
[in,out] target target ContactFacet
[in] contact Contact object used to find the pair interaction
Implements jeod::ContactFacet.
Definition at line 83 of file line_contact_facet.cc.
References jeod::Contact::contact_limit_factor, jeod::Contact::find_interaction(), jeod::ContactMessages::initialization_warns, jeod::LineContactPair::initialize_pair(), jeod::LinePointContactPair::initialize_pair(), jeod::ContactPair::interaction, jeod::ContactPair::interaction_distance, JEOD_ALLOC_CLASS_OBJECT, JEOD_DELETE_OBJECT, jeod::ContactFacet::max_dimension, jeod::ContactFacet::surface_type, and jeod::MessageHandler::warn().
operator=()
LineContactFacet& jeod::LineContactFacet::operator= (const LineContactFacet &) delete
set_max_dimension()
void jeod::LineContactFacet::set_max_dimension () override virtual
calculate the max dimension of the facet for range limit determination.
Implements jeod::ContactFacet.
Definition at line 202 of file line_contact_facet.cc.
References length, jeod::ContactFacet::max_dimension, and jeod::PointContactFacet::radius.
Referenced by jeod::LineContactFacetFactory::create_facet().
Friends And Related Function Documentation
init_attrjeod__LineContactFacet
void init_attrjeod__LineContactFacet () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file line_contact_facet.hh.
Field Documentation
length
double jeod::LineContactFacet::length {}
length of the line along the vehicle point x axis.
trick_units(m)
Definition at line 93 of file line_contact_facet.hh.
Referenced by calculate_contact_point(), jeod::LineContactFacetFactory::create_facet(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), and set_max_dimension().
The documentation for this class was generated from the following files:
line_contact_facet.hh
line_contact_facet.cc