JEOD: jeod::RefFrameState Class Reference
jeod::RefFrameState Class Reference
Represent a reference frame's state.
#include <ref_frame_state.hh>
Public Member Functions
RefFrameState ()
RefFrameState default constructor.
~RefFrameState ()=default
RefFrameState (const RefFrameState &source)
RefFrameState copy constructor.
RefFrameState & operator= (const RefFrameState &source)
Assignment operator; copies state from the source.
void initialize ()
Initialize a RefFrameState to a null offset.
void copy (const RefFrameState &source)
Initialize a RefFrameState from a source state.
void negate (const RefFrameState &source)
Copy a reference frame state, negated.
void incr_left (const RefFrameState &s_ab)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_B:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
void incr_right (const RefFrameState &s_bc)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_A:B, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
void decr_left (const RefFrameState &s_ab)
Compute S_B:C = (-S_A:B) + S_A:C, with this initially containing S_A:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
void decr_right (const RefFrameState &s_bc)
Compute S_A:B = S_A:C + (-S_B:C) with this initially containing S_A:C, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Data Fields
RefFrameTrans trans
Translation state.
RefFrameRot rot
Rotational state.
Friends
class InputProcessor
void init_attrjeod__RefFrameState ()
Detailed Description
Represent a reference frame's state.
Definition at line 182 of file ref_frame_state.hh.
Constructor & Destructor Documentation
RefFrameState() [1/2]
jeod::RefFrameState::RefFrameState ()
RefFrameState default constructor.
Definition at line 146 of file ref_frame_state.cc.
References initialize().
~RefFrameState()
jeod::RefFrameState::~RefFrameState () default
RefFrameState() [2/2]
jeod::RefFrameState::RefFrameState (const RefFrameState & source)
RefFrameState copy constructor.
Parameters
[in] source Source state
Definition at line 155 of file ref_frame_state.cc.
References copy().
Member Function Documentation
copy()
void jeod::RefFrameState::copy (const RefFrameState & source) inline
Initialize a RefFrameState from a source state.
Parameters
[in] source Source state
Definition at line 212 of file ref_frame_state_inline.hh.
References jeod::RefFrameTrans::copy(), jeod::RefFrameRot::copy(), rot, and trans.
Referenced by jeod::RefFrame::compute_state_wrt_pred(), operator=(), RefFrameState(), and jeod::EulerDerivedState::update().
decr_left()
void jeod::RefFrameState::decr_left (const RefFrameState & s_ab)
Compute S_B:C = (-S_A:B) + S_A:C, with this initially containing S_A:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
Parameters
[in] s_ab Left addend
Definition at line 390 of file ref_frame_state.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::Numerical::compare_exact(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Vector3::cross_decr(), jeod::Vector3::decr(), jeod::Quaternion::multiply_conjugate(), jeod::Quaternion::normalize(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, rot, jeod::Quaternion::scalar, jeod::RefFrameRot::T_parent_this, trans, jeod::Vector3::transform(), jeod::Vector3::transform_decr(), and jeod::RefFrameTrans::velocity.
Referenced by jeod::RefFrame::compute_relative_state().
decr_right()
void jeod::RefFrameState::decr_right (const RefFrameState & s_bc)
Compute S_A:B = S_A:C + (-S_B:C) with this initially containing S_A:C, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Parameters
[in] s_bc Left addend
Definition at line 453 of file ref_frame_state.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::Numerical::compare_exact(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Vector3::copy(), jeod::Vector3::cross_incr(), jeod::Vector3::decr(), jeod::Quaternion::multiply_left_conjugate(), jeod::Quaternion::normalize(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, rot, jeod::Quaternion::scalar, jeod::RefFrameRot::T_parent_this, trans, jeod::Vector3::transform_transpose(), jeod::Vector3::transform_transpose_decr(), and jeod::RefFrameTrans::velocity.
Referenced by jeod::DynBody::attach_to_frame(), and jeod::RefFrame::compute_pred_rel_state().
incr_left()
void jeod::RefFrameState::incr_left (const RefFrameState & s_ab)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_B:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
Parameters
[in] s_ab Left addend
Definition at line 234 of file ref_frame_state.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::Numerical::compare_exact(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Vector3::cross_incr(), jeod::Vector3::incr(), jeod::Quaternion::multiply(), jeod::Quaternion::normalize(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, rot, jeod::Quaternion::scalar, jeod::RefFrameRot::T_parent_this, trans, jeod::Vector3::transform_incr(), jeod::Vector3::transform_transpose(), and jeod::RefFrameTrans::velocity.
Referenced by jeod::RefFrame::compute_state_wrt_pred().
incr_right()
void jeod::RefFrameState::incr_right (const RefFrameState & s_bc)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_A:B, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Note that this function is untested, as it is not used in the Reference Frame Model at any point, and is only given here as a utility function.
Parameters
[in] s_bc Right addend
Definition at line 313 of file ref_frame_state.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::Numerical::compare_exact(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Vector3::copy(), jeod::RefFrameRot::copy(), jeod::Vector3::cross_incr(), jeod::Vector3::incr(), jeod::Quaternion::multiply_left(), jeod::Quaternion::normalize(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, rot, jeod::Quaternion::scalar, jeod::RefFrameRot::T_parent_this, trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose_incr(), and jeod::RefFrameTrans::velocity.
Referenced by jeod::DynBody::integrate().
initialize()
void jeod::RefFrameState::initialize () inline
Initialize a RefFrameState to a null offset.
Definition at line 202 of file ref_frame_state_inline.hh.
References jeod::RefFrameTrans::initialize(), jeod::RefFrameRot::initialize(), rot, and trans.
Referenced by jeod::RefFrame::compute_relative_state(), and RefFrameState().
negate()
void jeod::RefFrameState::negate (const RefFrameState & source)
Copy a reference frame state, negated.
Parameters
[in] source Source state
Definition at line 178 of file ref_frame_state.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::ang_vel_unit, jeod::Numerical::compare_exact(), jeod::Quaternion::conjugate(), jeod::Vector3::copy(), jeod::Vector3::cross_decr(), jeod::Vector3::initialize(), jeod::RefFrameRot::initialize(), jeod::Vector3::negate(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, rot, jeod::Quaternion::scalar, jeod::RefFrameRot::T_parent_this, trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::Matrix3x3::transpose(), and jeod::RefFrameTrans::velocity.
Referenced by jeod::DynBodyInit::apply_user_inputs(), and jeod::RefFrame::compute_pred_rel_state().
operator=()
RefFrameState & jeod::RefFrameState::operator= (const RefFrameState & source)
Assignment operator; copies state from the source.
Returns
Pointer to this
Parameters
[in] source Source state
Definition at line 165 of file ref_frame_state.cc.
References copy().
Friends And Related Function Documentation
init_attrjeod__RefFrameState
void init_attrjeod__RefFrameState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 184 of file ref_frame_state.hh.
Field Documentation
rot
RefFrameRot jeod::RefFrameState::rot
Rotational state.
trick_units(–)
Definition at line 194 of file ref_frame_state.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitOrbit::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::attach_to_frame(), jeod::NorthEastDown::build_ned_orientation(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::BasePlanet::calculate_alt_pfix(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::RefFrame::compute_position_from(), jeod::RefFrame::compute_relative_state(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), copy(), decr_left(), decr_right(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::LineContactPair::in_contact(), jeod::PointContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), incr_left(), incr_right(), jeod::PlanetOrientation::initialize(), jeod::LvlhFrame::initialize(), initialize(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), negate(), jeod::DynBody::process_dynamic_attachment(), jeod::EphemerisZXZOrientation::propagate(), jeod::StructureIntegratedDynBody::rot_integ(), jeod::DynBody::rot_integ(), jeod::BasePlanet::set_alt_inertial(), jeod::DynBody::set_attitude_left_quaternion(), jeod::DynBody::set_attitude_matrix(), jeod::DynBody::set_attitude_rate(), jeod::DynBody::set_attitude_right_quaternion(), jeod::DynBody::set_state(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::SpiceEphemOrientation::update(), jeod::GravityTorque::update(), jeod::EphemerisZXZOrientation::update(), jeod::EulerDerivedState::update(), jeod::PropagatedEphemerisOrientation::update(), and jeod::DynBody::update_integrated_state().
trans
RefFrameTrans jeod::RefFrameState::trans
Translation state.
trick_units(–)
Definition at line 189 of file ref_frame_state.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitNedState::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::attach_to_frame(), jeod::GravityControls::calc_relativistic(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::RefFrame::compute_position_from(), jeod::RefFrame::compute_relative_state(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), copy(), decr_left(), decr_right(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::GravityControls::gravitation(), jeod::PointContactPair::in_contact(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::ContactPair::in_range(), incr_left(), incr_right(), initialize(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), jeod::EphemerisPoint::initialize_state(), jeod::DynBodyFrameSwitch::is_ready(), negate(), jeod::DynBody::process_dynamic_attachment(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::NorthEastDown::set_ned_trans_states(), jeod::DynBody::set_position(), jeod::DynBody::set_state(), jeod::DynBody::set_velocity(), jeod::StructureIntegratedDynBody::trans_integ(), jeod::DynBody::trans_integ(), jeod::EphemerisPoint::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::LvlhFrame::update(), jeod::OrbElemDerivedState::update(), jeod::NedDerivedState::update(), jeod::SolarBetaDerivedState::update(), jeod::NorthEastDown::update_from_cart(), jeod::NorthEastDown::update_from_ellip(), jeod::NorthEastDown::update_from_spher(), jeod::DynBody::update_integrated_state(), and jeod::EphemerisPoint::update_scaled().
The documentation for this class was generated from the following files:
ref_frame_state.hh
ref_frame_state_inline.hh
ref_frame_state.cc