JEOD: jeod::ForceConstraintComponent Class Reference
jeod::ForceConstraintComponent Class Reference
Models one component of a constrained object whose constraints dictate the application of a force at some constraint position.
#include <force_constraint_component.hh>
Public Member Functions
ForceConstraintComponent (ConstraintFrame *constraint_frame_in=nullptr, ConstrainedPointMass *constrained_mass_in=nullptr)
Default constructor.
~ForceConstraintComponent () override=default
Destructor.
ForceConstraintComponent (const ForceConstraintComponent &)=default
ForceConstraintComponent (ForceConstraintComponent &&)=default
ForceConstraintComponent & operator= (const ForceConstraintComponent &)=default
ForceConstraintComponent & operator= (ForceConstraintComponent &&)=default
void attach_to_solver (DynBodyConstraintsSolver *, DynBody *) override
Perform actions related to the just-performed addition of this constraint to a constraints solver.
void detach_from_solver (DynBodyConstraintsSolver *, DynBody *) override
Perform actions related to the just-performed removal of this constraint from a constraints solver.
void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state) override
Prepare this object for solving a constraint problem.
double get_cross_coeff (const VehicleProperties &vehicle_properties, const ConstraintComponent &other) const override
Computes the coefficient of the solver A matrix that represents the interaction of some other constrained object and this constrained object.
SolverTypes::DecayedVector3T get_translational_response (const VehicleProperties &vehicle_properties, SolverTypes::ConstVector3T point, SolverTypes::Vector3T response) const override
Get the translational response by the vehicle to this constraint at a specified point in root body structural coordinates.
void set_constraint_value (double constraint_value) override
Set this constrained object's scalar constraint value.
void compute_constraint_response (const VehicleProperties &, const VehicleNonGravState &) override
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
Public Member Functions inherited from jeod::ConstraintComponent
ConstraintComponent (ConstraintFrame *constraint_frame_in=nullptr)
Default constructor.
virtual ~ConstraintComponent ()=default
Destructor.
ConstraintComponent (const ConstraintComponent &)=default
ConstraintComponent & operator= (const ConstraintComponent &)=default
ConstraintComponent (ConstraintComponent &&)=default
ConstraintComponent & operator= (ConstraintComponent &&)=default
virtual void update_attachment (const VehicleProperties &)
Update information about the relation between this constraint and the root DynBody.
void set_constraint_direction (SolverTypes::ConstVector3T constraint_direction)
Set the direction in which the constraint acts on the vehicle.
void compute_root_direction ()
Compute the constraint direction in root structural coordinates.
virtual SolverTypes::ConstDecayedVector3T get_rotational_response (const VehicleProperties &vehicle_properties) const
Get the vehicle's unit rotational response to this constraint.
virtual SolverTypes::DecayedVector3T get_rotational_response (const VehicleProperties &vehicle_properties, SolverTypes::Vector3T response) const
Get the vehicle's unit rotational response to this constraint.
virtual void set_right_hand_side (double rhs_value)
Set the right hand side of the constraint equation for this constraint.
virtual double get_right_hand_side () const
Get the right hand side of the constraint equation for this constraint.
virtual double get_self_coeff (const VehicleProperties &vehicle_properties) const
Computes the coefficient of the solver A matrix that represents the interaction of this constrained object with itself.
virtual const Wrench & get_constraint_wrench () const
Get the wrench this constrained object exerts on the vehicle.
Protected Attributes
ConstrainedPointMass * constrained_mass
The constrained mass, as a point mass, for this component.
double constraint_com_accel_root [3] {}
The contribution of this constraint to the translational acceleration of the root body center of mass, in root structural components.
double constraint_force {}
The unitless constraint value.
Protected Attributes inherited from jeod::ConstraintComponent
ConstraintFrame * constraint_frame
The reference frame associated with this constraint.
Wrench constraint_wrench
The indeterminate part of the wrench due to this constraint.
double constraint_direction_constraint_frame [3] {}
The direction in which the constraint acts on the vehicle, in constraint frame coordinates.
double constraint_direction_root [3] {}
The direction in which the constraint acts on the vehicle, in root body structural coordinates.
double constraint_omega_dot_root [3] {}
The contribution of this constraint to the rotational acceleration of the root body, in root structural components.
double right_hand_side {}
The right hand side of the constraint equation pertaining to this constraint.
Friends
class InputProcessor
void init_attrjeod__ForceConstraintComponent ()
Additional Inherited Members
Protected Member Functions inherited from jeod::ConstraintComponent
void compute_rotational_response (const VehicleProperties &vehicle_properties, const double torque[3])
Compute the vehicle's rotational response to a torque.
Detailed Description
Models one component of a constrained object whose constraints dictate the application of a force at some constraint position.
The constraint force is applied at the constraint position and is the product of a one newton force in the constraint direction with a unitless constraint value, the latter of which is determined by a constraints solver.
Definition at line 74 of file force_constraint_component.hh.
Constructor & Destructor Documentation
ForceConstraintComponent() [1/3]
jeod::ForceConstraintComponent::ForceConstraintComponent (ConstraintFrame * constraint_frame_in = nullptr, ConstrainedPointMass * constrained_mass_in = nullptr)
Default constructor.
Definition at line 30 of file force_constraint_component.cc.
~ForceConstraintComponent()
jeod::ForceConstraintComponent::~ForceConstraintComponent () override default
Destructor.
ForceConstraintComponent() [2/3]
jeod::ForceConstraintComponent::ForceConstraintComponent (const ForceConstraintComponent &) default
ForceConstraintComponent() [3/3]
jeod::ForceConstraintComponent::ForceConstraintComponent (ForceConstraintComponent &&) default
Member Function Documentation
attach_to_solver()
void jeod::ForceConstraintComponent::attach_to_solver (DynBodyConstraintsSolver * , DynBody *) inline override virtual
Perform actions related to the just-performed addition of this constraint to a constraints solver.
In this case, do nothing.
Implements jeod::ConstraintComponent.
Reimplemented in jeod::PendulumConstraintComponent.
Definition at line 101 of file force_constraint_component.hh.
compute_constraint_response()
void jeod::ForceConstraintComponent::compute_constraint_response (const VehicleProperties & , const VehicleNonGravState &) inline override virtual
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
In this case, do nothing.
Implements jeod::ConstraintComponent.
Reimplemented in jeod::PendulumConstraintComponent.
Definition at line 165 of file force_constraint_component.hh.
detach_from_solver()
void jeod::ForceConstraintComponent::detach_from_solver (DynBodyConstraintsSolver * , DynBody *) inline override virtual
Perform actions related to the just-performed removal of this constraint from a constraints solver.
In this case, do nothing.
Implements jeod::ConstraintComponent.
Reimplemented in jeod::PendulumConstraintComponent.
Definition at line 107 of file force_constraint_component.hh.
get_cross_coeff()
double jeod::ForceConstraintComponent::get_cross_coeff (const VehicleProperties & vehicle_properties, const ConstraintComponent & other) const override virtual
Computes the coefficient of the solver A matrix that represents the interaction of some other constrained object and this constrained object.
Parameters
vehicle_properties Various vehicle properties.
other The other constrained object.
Returns
Interaction coefficient.
Implements jeod::ConstraintComponent.
Definition at line 60 of file force_constraint_component.cc.
References constrained_mass, jeod::ConstraintComponent::constraint_direction_root, jeod::ConstrainedPointMass::constraint_position_com, jeod::Vector3::dot(), jeod::ConstraintComponent::get_translational_response(), and jeod::ConstrainedPointMass::mass.
get_translational_response()
SolverTypes::DecayedVector3T jeod::ForceConstraintComponent::get_translational_response (const VehicleProperties & vehicle_properties, SolverTypes::ConstVector3T point, SolverTypes::Vector3T response) const override virtual
Get the translational response by the vehicle to this constraint at a specified point in root body structural coordinates.
Parameters
vehicle_properties Various vehicle properties.
point The point at with the translational response is to be computed, in root body structural components.
response The response vector, which is filled with the translational acceleration at the specified point on the vehicle due to a unitary value of the specified component of this constraint.
Returns
The response vector.
Implements jeod::ConstraintComponent.
Definition at line 70 of file force_constraint_component.cc.
References constraint_com_accel_root, jeod::ConstraintComponent::constraint_omega_dot_root, jeod::Vector3::cross(), and jeod::Vector3::incr().
operator=() [1/2]
ForceConstraintComponent& jeod::ForceConstraintComponent::operator= (const ForceConstraintComponent &) default
operator=() [2/2]
ForceConstraintComponent& jeod::ForceConstraintComponent::operator= (ForceConstraintComponent &&) default
set_constraint_value()
void jeod::ForceConstraintComponent::set_constraint_value (double constraint_value) override virtual
Set this constrained object's scalar constraint value.
Parameters
constraint_value The solution to the matrix constraint equation for this constrained object.
Implements jeod::ConstraintComponent.
Definition at line 79 of file force_constraint_component.cc.
References constraint_force, jeod::ConstraintComponent::constraint_wrench, and jeod::Wrench::scale_force().
setup_constraint()
void jeod::ForceConstraintComponent::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) override virtual
Prepare this object for solving a constraint problem.
The direction in which the constraint force acts is known at this point, but the magnitude is not. This function sets the force to a unit force in the known constraint direction. This enables the computation of interactions with other constraints (the A matrix in A*x=b) and the computation of the constraint response (the b vector in A*x=b). The solver subsequently solves A*x=b, which yields the force magnitude.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to non-constraint forces and torques, including the pre-constraint wrenches.
Implements jeod::ConstraintComponent.
Reimplemented in jeod::PendulumConstraintComponent.
Definition at line 40 of file force_constraint_component.cc.
References jeod::ConstraintComponent::compute_rotational_response(), constrained_mass, constraint_com_accel_root, jeod::ConstraintComponent::constraint_direction_root, jeod::ConstrainedPointMass::constraint_position_com, jeod::ConstrainedPointMass::constraint_position_root, jeod::ConstraintComponent::constraint_wrench, jeod::Vector3::cross(), jeod::VehicleProperties::get_inverse_mass(), jeod::Vector3::scale(), and jeod::Wrench::set_force().
Referenced by jeod::PendulumConstraintComponent::setup_constraint().
Friends And Related Function Documentation
init_attrjeod__ForceConstraintComponent
void init_attrjeod__ForceConstraintComponent () friend
InputProcessor
friend class InputProcessor friend
Definition at line 76 of file force_constraint_component.hh.
Field Documentation
constrained_mass
ConstrainedPointMass* jeod::ForceConstraintComponent::constrained_mass protected
The constrained mass, as a point mass, for this component.
trick_units(–)
Definition at line 173 of file force_constraint_component.hh.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), get_cross_coeff(), jeod::PendulumConstraintComponent::reset_integrators(), setup_constraint(), and jeod::PendulumConstraintComponent::setup_constraint().
constraint_com_accel_root
double jeod::ForceConstraintComponent::constraint_com_accel_root[3] {} protected
The contribution of this constraint to the translational acceleration of the root body center of mass, in root structural components.
trick_units(m/s^2)
Definition at line 179 of file force_constraint_component.hh.
Referenced by get_translational_response(), and setup_constraint().
constraint_force
double jeod::ForceConstraintComponent::constraint_force {} protected
The unitless constraint value.
trick_units(–)
Definition at line 184 of file force_constraint_component.hh.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), and set_constraint_value().
The documentation for this class was generated from the following files:
force_constraint_component.hh
force_constraint_component.cc