JEOD: jeod::SphericalHarmonicsGravityControls Class Reference
jeod::SphericalHarmonicsGravityControls Class Reference
Specifies whether and how a SphericalHarmonicsGravitySource affects a vehicle.
#include <spherical_harmonics_gravity_controls.hh>
Public Member Functions
SphericalHarmonicsGravityControls ()
SphericalHarmonicsGravityControls constructor.
~SphericalHarmonicsGravityControls () override
SphericalHarmonicsGravityControls destructor.
void initialize_control (GravityManager &grav_manager) override
Initialize this GravityControl.
virtual void add_deltacontrol (SphericalHarmonicsDeltaControls *delta_control)
Add a new GravityDeltaControls to the var_effects list.
unsigned int get_degree (void)
Output the current functional degree.
unsigned int get_order (void)
Output the current functional order.
void get_degree_order (unsigned int &current_degree, unsigned int &current_order)
Output the current functional degree and order.
unsigned int get_grad_degree (void)
Output the current functional gradient degree.
unsigned int get_grad_order (void)
Output the current functional gradient order.
void get_grad_degree_order (unsigned int &curr_grad_degree, unsigned int &curr_grad_order)
Output the current functional gradient degree and order.
void set_degree (unsigned int new_degree)
Update the functional degree.
void set_order (unsigned int new_order)
Update the functional order.
void set_degree_order (unsigned int new_degree, unsigned int new_order)
Update the functional degree and order.
void set_grad_degree (unsigned int new_grad_degree)
Update the functional gradient degree.
void set_grad_order (unsigned int new_grad_order)
Update the functional gradient order.
void set_grad_degree_order (unsigned int new_grad_degree, unsigned int new_grad_order)
Update the functional gradient degree and order.
void disable_min_radius_warnings ()
Disable minimum radius warnings for this spherical harmonics gravity control.
Public Member Functions inherited from jeod::GravityControls
GravityControls ()
GravityControls constructor.
virtual ~GravityControls ()
GravityControls destructor.
virtual void reset_control (BaseDynManager &dyn_manager)
Reset subscriptions for this GravityControl.
virtual void gravitation (const double integ_pos[3], unsigned int integ_frame_idx, double body_grav_accel[3], double dgdx[3][3], double Pot[1])
Compute the gravitation at a given position toward a gravity body.
virtual void gravitation (const RefFrame &point_of_interest, unsigned int integ_frame_idx, double body_grav_accel[3], double dgdx[3][3], double &pot)
Compute the gravitation at a given position toward a gravity body.
Data Fields
SphericalHarmonicsGravitySource * harmonics_source
The GravitySource pointer from the base class, recast.
double ** Pnm
LeGendre polynomials used to calculate non-spherical attraction.
unsigned int delta_degree
Coefficient degree to be used for totaling up all active delta_coeffs.
unsigned int delta_order
Coefficient order to be used for totaling up all active delta_coeffs.
double ** delta_Cnm
Array for collecting all active normalized real (cosine) variational spherical harmonic coefficients.
double ** delta_Snm
Array for collecting all active normalized real (sine) variational spherical harmonic coefficients.
double total_dC20
delta C20 coefficient for collecting first order effects of all active delta_coeffs.
unsigned int degree
Non-spherical degree to be used.
unsigned int order
Non-spherical order to be used.
unsigned int gradient_degree
Non-spherical degree to be used for computing gradient.
unsigned int gradient_order
Non-spherical order to be used for computing gradient.
JeodPointerVector< SphericalHarmonicsDeltaControls >::type var_effects
List of controls for variational gravity effects like solid-body tides.
Data Fields inherited from jeod::GravityControls
std::string source_name
Planet name.
bool active
Gravity for this body active?
bool spherical
Ignore non-spherical effects?
bool gradient
Compute gravity gradient matrix?
bool perturbing_only
Compute only the perturbing gravity?
bool battin_method
Compute third body gravity using Battin's method (Battin, Mathematics and Methods of Astrodynamics)?
bool relativistic
Indicates that the relativistic correction to Newtonian gravitation is to be computed.
GravitySource * body
Pointer to the GravitySource object named by planet_name.
double grav_accel [3]
Gravitational acceleration toward the GravitySource at the location of the DynBody, including third body effects.
double grav_grad [3][3]
Gradient of the gravitational acceleration.
double grav_pot
Gravitational potential.
double grav_accel_magsq
Square of the magnitude of grav_accel.
Protected Member Functions
void calc_nonspherical (const double integ_pos[3], const double posn[3], const GravityIntegFrame &grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double &pot) override
Compute the gravitational acceleration at a given position toward a gravitational body assuming the body has a non-spherical mass distribution.
virtual void check_validity (void)
Check the validity of the gravity controls.
virtual void update_deltacoeffs (void)
Command all of the gravitational variation effects to update themselves.
virtual void sum_deltacoeffs (void)
Loop over all of the active gravitational variation effects models and aggregate their changes to the gravity coefficients into the top-level delta-coeffs "bin" for this gravity body.
Protected Member Functions inherited from jeod::GravityControls
void calc_relativistic (const RefFrame &point_of_interest, const double rel_pos[3], const double rel_vel[3], double perturbing_accel[3])
Calculates the relativistic correction to gravitational acceleration.
void calc_spherical (const double integ_pos[3], const double posn[3], const GravityIntegFrame &grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double &pot)
Calculate the spherical gravitational acceleration, either directly or as a third body acceleration.
Protected Attributes
bool min_radius_warn
Indicates that the minimum radius threshold has been crossed and that a warning has been issued for such.
Protected Attributes inherited from jeod::GravityControls
GravityManager * grav_manager
Pointer to the simulation-wide GravityManager object.
bool subscribed_to_inertial
Indicates that a subscription to the planet-centered inertial frame of the planet associated with the gravity_source been issued.
bool subscribed_to_pfix
Indicates that a subscription to the planet-centered, planet-fixed frame of the planet associated with the gravity_source been issued.
bool skip_spherical
Some derived classes' calc_nonspherical method computes all contributions to gravitation, including spherical.
Private Member Functions
SphericalHarmonicsGravityControls (const SphericalHarmonicsGravityControls &)
Not implemented.
SphericalHarmonicsGravityControls & operator= (const SphericalHarmonicsGravityControls &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__SphericalHarmonicsGravityControls ()
Additional Inherited Members
Static Public Member Functions inherited from jeod::GravityControls
static bool accel_mag_less_ptr (const GravityControls *a, const GravityControls *b)
Compares the magnitude of the two input gravity controls, returning true if a->grav_accel_magsq is less than b->grav_accel_magsq, false otherwise.
Detailed Description
Specifies whether and how a SphericalHarmonicsGravitySource affects a vehicle.
Definition at line 89 of file spherical_harmonics_gravity_controls.hh.
Constructor & Destructor Documentation
SphericalHarmonicsGravityControls() [1/2]
jeod::SphericalHarmonicsGravityControls::SphericalHarmonicsGravityControls (const SphericalHarmonicsGravityControls &) private
Not implemented.
SphericalHarmonicsGravityControls() [2/2]
jeod::SphericalHarmonicsGravityControls::SphericalHarmonicsGravityControls (void)
SphericalHarmonicsGravityControls constructor.
Definition at line 56 of file spherical_harmonics_gravity_controls.cc.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and var_effects.
~SphericalHarmonicsGravityControls()
jeod::SphericalHarmonicsGravityControls::~SphericalHarmonicsGravityControls (void) override
SphericalHarmonicsGravityControls destructor.
Definition at line 83 of file spherical_harmonics_gravity_controls.cc.
References jeod::SphericalHarmonicsGravitySource::degree, delta_Cnm, delta_degree, delta_Snm, harmonics_source, JEOD_DELETE_ARRAY, JEOD_DEREGISTER_CHECKPOINTABLE, Pnm, and var_effects.
Member Function Documentation
add_deltacontrol()
void jeod::SphericalHarmonicsGravityControls::add_deltacontrol (SphericalHarmonicsDeltaControls * delta_control) virtual
Add a new GravityDeltaControls to the var_effects list.
Parameters
[in] delta_control Control to be added
Definition at line 186 of file spherical_harmonics_gravity_controls.cc.
References jeod::SphericalHarmonicsDeltaCoeffs::degree, delta_Cnm, delta_degree, delta_order, delta_Snm, jeod::SphericalHarmonicsDeltaControls::grav_effect, JEOD_ALLOC_PRIM_ARRAY, JEOD_DELETE_ARRAY, jeod::SphericalHarmonicsDeltaCoeffs::order, and var_effects.
calc_nonspherical()
void jeod::SphericalHarmonicsGravityControls::calc_nonspherical (const double integ_pos [3], const double posn[3], const GravityIntegFrame & grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double & pot) override protected virtual
Compute the gravitational acceleration at a given position toward a gravitational body assuming the body has a non-spherical mass distribution.
Parameters
[in] posn Point of interest, inrtl coords
Units: M
[out] body_grav_accel Accel for given grav body
Units: M/s2
[out] dgdx Gradient for given grav body
Units: 1/s2
[out] Pot Potential
Implements jeod::GravityControls.
Definition at line 56 of file spherical_harmonics_calc_nonspherical.cc.
References jeod::SphericalHarmonicsGravitySource::alpha, jeod::SphericalHarmonicsGravitySource::beta, jeod::SphericalHarmonicsGravitySource::Cnm, degree, jeod::GravityMessages::domain_error, jeod::SphericalHarmonicsGravitySource::eta, jeod::GravityControls::gradient, gradient_degree, gradient_order, GSL_SQRT_DBL_MIN, harmonics_source, jeod::Matrix3x3::initialize(), jeod::SphericalHarmonicsGravitySource::int_to_double, min_radius_warn, jeod::GravitySource::mu, jeod::GravitySource::name, jeod::SphericalHarmonicsGravitySource::nrdiag, order, jeod::GravitySource::pfix, Pnm, jeod::SphericalHarmonicsGravitySource::radius, jeod::RefFrameState::rot, jeod::SphericalHarmonicsGravitySource::Snm, jeod::RefFrame::state, sum_deltacoeffs(), jeod::RefFrameRot::T_parent_this, jeod::SphericalHarmonicsGravitySource::tide_free, jeod::SphericalHarmonicsGravitySource::tide_free_delta, total_dC20, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::Matrix3x3::transpose_transform_matrix(), update_deltacoeffs(), jeod::SphericalHarmonicsGravitySource::upsilon, var_effects, jeod::Vector3::vmag(), jeod::MessageHandler::warn(), jeod::SphericalHarmonicsGravitySource::xi, and jeod::SphericalHarmonicsGravitySource::zeta.
check_validity()
void jeod::SphericalHarmonicsGravityControls::check_validity (void) protected virtual
Check the validity of the gravity controls.
Definition at line 427 of file spherical_harmonics_gravity_controls.cc.
References jeod::SphericalHarmonicsGravitySource::degree, degree, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::GravityControls::gradient, gradient_degree, gradient_order, harmonics_source, jeod::GravityMessages::invalid_limit, jeod::GravityMessages::invalid_object, jeod::GravitySource::name, jeod::SphericalHarmonicsGravitySource::order, order, jeod::GravityControls::source_name, and jeod::GravityControls::spherical.
Referenced by initialize_control(), set_degree(), set_degree_order(), set_grad_degree(), set_grad_degree_order(), set_grad_order(), and set_order().
disable_min_radius_warnings()
void jeod::SphericalHarmonicsGravityControls::disable_min_radius_warnings () inline
Disable minimum radius warnings for this spherical harmonics gravity control.
Definition at line 265 of file spherical_harmonics_gravity_controls.hh.
References min_radius_warn.
get_degree()
unsigned int jeod::SphericalHarmonicsGravityControls::get_degree (void)
Output the current functional degree.
Returns
Current degree
Definition at line 238 of file spherical_harmonics_gravity_controls.cc.
References degree.
get_degree_order()
void jeod::SphericalHarmonicsGravityControls::get_degree_order (unsigned int & current_degree, unsigned int & current_order)
Output the current functional degree and order.
Parameters
[out] current_degree Current degree
[out] current_order Current order
Definition at line 263 of file spherical_harmonics_gravity_controls.cc.
References degree, and order.
get_grad_degree()
unsigned int jeod::SphericalHarmonicsGravityControls::get_grad_degree (void)
Output the current functional gradient degree.
Returns
Current gradient degree
Definition at line 279 of file spherical_harmonics_gravity_controls.cc.
References gradient_degree.
get_grad_degree_order()
void jeod::SphericalHarmonicsGravityControls::get_grad_degree_order (unsigned int & curr_grad_degree, unsigned int & curr_grad_order)
Output the current functional gradient degree and order.
Parameters
[out] curr_grad_degree Current gradient degree
[out] curr_grad_order Current gradient order
Definition at line 304 of file spherical_harmonics_gravity_controls.cc.
References gradient_degree, and gradient_order.
get_grad_order()
unsigned int jeod::SphericalHarmonicsGravityControls::get_grad_order (void)
Output the current functional gradient order.
Returns
Current gradient order
Definition at line 291 of file spherical_harmonics_gravity_controls.cc.
References gradient_order.
get_order()
unsigned int jeod::SphericalHarmonicsGravityControls::get_order (void)
Output the current functional order.
Returns
Current order
Definition at line 250 of file spherical_harmonics_gravity_controls.cc.
References order.
initialize_control()
void jeod::SphericalHarmonicsGravityControls::initialize_control (GravityManager & grav_manager) override virtual
Initialize this GravityControl.
Parameters
[in] grav_manager Ref to Gravity Manager
Reimplemented from jeod::GravityControls.
Definition at line 121 of file spherical_harmonics_gravity_controls.cc.
References jeod::GravityControls::body, check_validity(), jeod::SphericalHarmonicsGravitySource::degree, jeod::GravityControls::grav_manager, harmonics_source, jeod::GravityControls::initialize_control(), JEOD_ALLOC_PRIM_ARRAY, JEOD_DELETE_ARRAY, and Pnm.
operator=()
SphericalHarmonicsGravityControls& jeod::SphericalHarmonicsGravityControls::operator= (const SphericalHarmonicsGravityControls &) private
Not implemented.
set_degree()
void jeod::SphericalHarmonicsGravityControls::set_degree (unsigned int new_degree)
Update the functional degree.
Parameters
[in] new_degree New desired degree
Definition at line 320 of file spherical_harmonics_gravity_controls.cc.
References check_validity(), and degree.
set_degree_order()
void jeod::SphericalHarmonicsGravityControls::set_degree_order (unsigned int new_degree, unsigned int new_order)
Update the functional degree and order.
Parameters
[in] new_degree New desired degree
[in] new_order New desired order
Definition at line 355 of file spherical_harmonics_gravity_controls.cc.
References check_validity(), degree, and order.
set_grad_degree()
void jeod::SphericalHarmonicsGravityControls::set_grad_degree (unsigned int new_grad_degree)
Update the functional gradient degree.
Parameters
[in] new_grad_degree New desired degree
Definition at line 374 of file spherical_harmonics_gravity_controls.cc.
References check_validity(), and gradient_degree.
set_grad_degree_order()
void jeod::SphericalHarmonicsGravityControls::set_grad_degree_order (unsigned int new_grad_degree, unsigned int new_grad_order)
Update the functional gradient degree and order.
Parameters
[in] new_grad_degree New desired degree
[in] new_grad_order New desired order
Definition at line 409 of file spherical_harmonics_gravity_controls.cc.
References check_validity(), gradient_degree, and gradient_order.
set_grad_order()
void jeod::SphericalHarmonicsGravityControls::set_grad_order (unsigned int new_grad_order)
Update the functional gradient order.
Parameters
[in] new_grad_order New desired order
Definition at line 391 of file spherical_harmonics_gravity_controls.cc.
References check_validity(), and gradient_order.
set_order()
void jeod::SphericalHarmonicsGravityControls::set_order (unsigned int new_order)
Update the functional order.
Parameters
[in] new_order New desired order
Definition at line 337 of file spherical_harmonics_gravity_controls.cc.
References check_validity(), and order.
sum_deltacoeffs()
void jeod::SphericalHarmonicsGravityControls::sum_deltacoeffs (void) protected virtual
Loop over all of the active gravitational variation effects models and aggregate their changes to the gravity coefficients into the top-level delta-coeffs "bin" for this gravity body.
Definition at line 556 of file spherical_harmonics_gravity_controls.cc.
References jeod::SphericalHarmonicsDeltaControls::active, jeod::SphericalHarmonicsDeltaCoeffs::dC20, jeod::SphericalHarmonicsDeltaControls::degree, jeod::SphericalHarmonicsDeltaCoeffs::delta_Cnm, delta_Cnm, jeod::SphericalHarmonicsGravitySource::delta_coeffs, delta_degree, delta_order, jeod::SphericalHarmonicsDeltaCoeffs::delta_Snm, delta_Snm, jeod::SphericalHarmonicsDeltaControls::first_order_only, jeod::SphericalHarmonicsDeltaControls::grav_effect, harmonics_source, jeod::SphericalHarmonicsDeltaControls::order, total_dC20, and var_effects.
Referenced by calc_nonspherical().
update_deltacoeffs()
void jeod::SphericalHarmonicsGravityControls::update_deltacoeffs (void) protected virtual
Command all of the gravitational variation effects to update themselves.
Definition at line 534 of file spherical_harmonics_gravity_controls.cc.
References jeod::GravityControls::active, jeod::SphericalHarmonicsGravitySource::delta_coeffs, harmonics_source, and var_effects.
Referenced by calc_nonspherical().
Friends And Related Function Documentation
init_attrjeod__SphericalHarmonicsGravityControls
void init_attrjeod__SphericalHarmonicsGravityControls () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file spherical_harmonics_gravity_controls.hh.
Field Documentation
degree
unsigned int jeod::SphericalHarmonicsGravityControls::degree
Non-spherical degree to be used.
NOTE: this data being public is deprecated and should not be relied upon in future releases. Use the provided accessor methods instead.trick_units(–)
Definition at line 152 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), check_validity(), get_degree(), get_degree_order(), set_degree(), and set_degree_order().
delta_Cnm
double** jeod::SphericalHarmonicsGravityControls::delta_Cnm
Array for collecting all active normalized real (cosine) variational spherical harmonic coefficients.
trick_units(–)
Definition at line 132 of file spherical_harmonics_gravity_controls.hh.
Referenced by add_deltacontrol(), sum_deltacoeffs(), and ~SphericalHarmonicsGravityControls().
delta_degree
unsigned int jeod::SphericalHarmonicsGravityControls::delta_degree
Coefficient degree to be used for totaling up all active delta_coeffs.
trick_units(–)
Definition at line 121 of file spherical_harmonics_gravity_controls.hh.
Referenced by add_deltacontrol(), sum_deltacoeffs(), and ~SphericalHarmonicsGravityControls().
delta_order
unsigned int jeod::SphericalHarmonicsGravityControls::delta_order
Coefficient order to be used for totaling up all active delta_coeffs.
trick_units(–)
Definition at line 126 of file spherical_harmonics_gravity_controls.hh.
Referenced by add_deltacontrol(), and sum_deltacoeffs().
delta_Snm
double** jeod::SphericalHarmonicsGravityControls::delta_Snm
Array for collecting all active normalized real (sine) variational spherical harmonic coefficients.
trick_units(–)
Definition at line 138 of file spherical_harmonics_gravity_controls.hh.
Referenced by add_deltacontrol(), sum_deltacoeffs(), and ~SphericalHarmonicsGravityControls().
gradient_degree
unsigned int jeod::SphericalHarmonicsGravityControls::gradient_degree
Non-spherical degree to be used for computing gradient.
NOTE: this data being public is deprecated and should not be relied upon in future releases. Use the provided accessor methods instead.trick_units(–)
Definition at line 166 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), check_validity(), get_grad_degree(), get_grad_degree_order(), set_grad_degree(), and set_grad_degree_order().
gradient_order
unsigned int jeod::SphericalHarmonicsGravityControls::gradient_order
Non-spherical order to be used for computing gradient.
NOTE: this data being public is deprecated and should not be relied upon in future releases. Use the provided accessor methods instead.trick_units(–)
Definition at line 173 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), check_validity(), get_grad_degree_order(), get_grad_order(), set_grad_degree_order(), and set_grad_order().
harmonics_source
SphericalHarmonicsGravitySource* jeod::SphericalHarmonicsGravityControls::harmonics_source
The GravitySource pointer from the base class, recast.
Note
Users should not set this data member in the input file.trick_units(–)
Definition at line 110 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), check_validity(), initialize_control(), sum_deltacoeffs(), update_deltacoeffs(), and ~SphericalHarmonicsGravityControls().
min_radius_warn
bool jeod::SphericalHarmonicsGravityControls::min_radius_warn protected
Indicates that the minimum radius threshold has been crossed and that a warning has been issued for such.
This prevents a spew of messages regarding such under-threshold conditions.
Note
Users should not set this data member in the input file unless you wish to disable all such messages.trick_units(–)
Definition at line 103 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), and disable_min_radius_warnings().
order
unsigned int jeod::SphericalHarmonicsGravityControls::order
Non-spherical order to be used.
NOTE: this data being public is deprecated and should not be relied upon in future releases. Use the provided accessor methods instead.trick_units(–)
Definition at line 159 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), check_validity(), get_degree_order(), get_order(), set_degree_order(), and set_order().
Pnm
double** jeod::SphericalHarmonicsGravityControls::Pnm
LeGendre polynomials used to calculate non-spherical attraction.
trick_units(–)
Definition at line 115 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), initialize_control(), and ~SphericalHarmonicsGravityControls().
total_dC20
double jeod::SphericalHarmonicsGravityControls::total_dC20
delta C20 coefficient for collecting first order effects of all active delta_coeffs.
trick_units(–)
Definition at line 144 of file spherical_harmonics_gravity_controls.hh.
Referenced by calc_nonspherical(), and sum_deltacoeffs().
var_effects
JeodPointerVector<SphericalHarmonicsDeltaControls>::type jeod::SphericalHarmonicsGravityControls::var_effects
List of controls for variational gravity effects like solid-body tides.
trick_io(**)
Definition at line 178 of file spherical_harmonics_gravity_controls.hh.
Referenced by add_deltacontrol(), calc_nonspherical(), SphericalHarmonicsGravityControls(), sum_deltacoeffs(), update_deltacoeffs(), and ~SphericalHarmonicsGravityControls().
The documentation for this class was generated from the following files:
spherical_harmonics_gravity_controls.hh
spherical_harmonics_calc_nonspherical.cc
spherical_harmonics_gravity_controls.cc