JEOD: jeod::LvlhDerivedState Class Reference
jeod::LvlhDerivedState Class Reference
The class used for deriving the rectilinear LVLH representations of a subject DynBody's state.
#include <lvlh_derived_state.hh>
Public Member Functions
LvlhDerivedState ()
Construct a LvlhDerivedState object.
~LvlhDerivedState () override
Destruct a LvlhDerivedState object.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a LvlhDerivedState.
void update (void) override
Update the state.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
bool register_frame
If set (default), the LVLH frame will be registered with the dynamics manager at initialization time.
RefFrame lvlh_frame
The LVLH frame of the subject body with respect to the planet specified by the reference name.
LvlhFrame lvlh_state
The LvlhFrame object responsible for maintaining the lvlh_frame.
Data Fields inherited from jeod::DerivedState
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Attributes
RefFrame * planet_centered_inertial
The inertial frame with origin at the center of the specified planet.
Protected Attributes inherited from jeod::DerivedState
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
LvlhDerivedState (const LvlhDerivedState &)
LvlhDerivedState & operator= (const LvlhDerivedState &)
Private Attributes
DynManager * local_dm
Friends
class InputProcessor
void init_attrjeod__LvlhDerivedState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Detailed Description
The class used for deriving the rectilinear LVLH representations of a subject DynBody's state.
Definition at line 85 of file lvlh_derived_state.hh.
Constructor & Destructor Documentation
LvlhDerivedState() [1/2]
jeod::LvlhDerivedState::LvlhDerivedState (void)
Construct a LvlhDerivedState object.
Definition at line 51 of file lvlh_derived_state.cc.
~LvlhDerivedState()
jeod::LvlhDerivedState::~LvlhDerivedState (void) override
Destruct a LvlhDerivedState object.
Definition at line 69 of file lvlh_derived_state.cc.
References local_dm, lvlh_frame, jeod::RefFrame::remove_from_parent(), and jeod::RefFrameManager::remove_ref_frame().
LvlhDerivedState() [2/2]
jeod::LvlhDerivedState::LvlhDerivedState (const LvlhDerivedState &) private
Member Function Documentation
initialize()
void jeod::LvlhDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of a LvlhDerivedState.
The initialize method for all subclasses of DerivedState nust pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DerivedState.
Definition at line 92 of file lvlh_derived_state.cc.
References jeod::EphemeridesManager::add_ref_frame(), jeod::NamedItem::c_str(), jeod::DynBody::composite_body, jeod::LvlhFrame::frame, jeod::RefFrame::get_parent(), jeod::LvlhFrame::initialize(), jeod::DerivedState::initialize(), local_dm, lvlh_frame, lvlh_state, jeod::DynBody::name, planet_centered_inertial, jeod::DerivedState::reference_name, register_frame, jeod::RefFrame::set_name(), jeod::LvlhFrame::set_planet_name(), jeod::LvlhFrame::set_subject_frame(), and jeod::DerivedState::subject.
operator=()
LvlhDerivedState& jeod::LvlhDerivedState::operator= (const LvlhDerivedState &) private
update()
void jeod::LvlhDerivedState::update (void) override virtual
Update the state.
Reimplemented from jeod::DerivedState.
Definition at line 119 of file lvlh_derived_state.cc.
References jeod::LvlhFrame::frame, lvlh_frame, lvlh_state, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::RefFrame::timestamp(), and jeod::LvlhFrame::update().
Friends And Related Function Documentation
init_attrjeod__LvlhDerivedState
void init_attrjeod__LvlhDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file lvlh_derived_state.hh.
Field Documentation
local_dm
DynManager* jeod::LvlhDerivedState::local_dm private
Definition at line 123 of file lvlh_derived_state.hh.
Referenced by initialize(), and ~LvlhDerivedState().
lvlh_frame
RefFrame jeod::LvlhDerivedState::lvlh_frame
The LVLH frame of the subject body with respect to the planet specified by the reference name.
trick_units(–)
Definition at line 105 of file lvlh_derived_state.hh.
Referenced by initialize(), update(), and ~LvlhDerivedState().
lvlh_state
LvlhFrame jeod::LvlhDerivedState::lvlh_state
The LvlhFrame object responsible for maintaining the lvlh_frame.
trick_units(–)
Definition at line 110 of file lvlh_derived_state.hh.
Referenced by initialize(), and update().
planet_centered_inertial
RefFrame* jeod::LvlhDerivedState::planet_centered_inertial protected
The inertial frame with origin at the center of the specified planet.
trick_units(–)
Definition at line 118 of file lvlh_derived_state.hh.
Referenced by initialize().
register_frame
bool jeod::LvlhDerivedState::register_frame
If set (default), the LVLH frame will be registered with the dynamics manager at initialization time.
This will make the frame accessible through the dynamic manager via its find_ref_frame method.trick_units(–)
Definition at line 99 of file lvlh_derived_state.hh.
Referenced by initialize().
The documentation for this class was generated from the following files:
lvlh_derived_state.hh
lvlh_derived_state.cc