JEOD: jeod::GravityInteraction Class Reference
jeod::GravityInteraction Class Reference
Specifies interactions between a vehicle and a set of gravitational bodies.
#include <gravity_interaction.hh>
Public Member Functions
GravityInteraction ()
Construct a GravityInteraction instance.
virtual ~GravityInteraction ()
Destruct a GravityInteraction instance.
GravityInteraction (const GravityInteraction &frame)=delete
GravityInteraction & operator= (const GravityInteraction &frame)=delete
virtual void set_integ_frame (const EphemerisRefFrame &ref_frame_in, const BaseDynManager &dyn_manager)
Set the integration frame and associated integration frame index.
virtual void add_control (GravityControls *control)
Add a new GravityControls to the grav_controls list.
virtual void remove_control (GravityControls *control)
Remove a GravityControls from the grav_controls list.
virtual void initialize_controls (BaseDynManager &dyn_manager, GravityManager &grav_manager)
Initialize all GravityControls in the grav_controls list.
virtual void reset_controls (BaseDynManager &dyn_manager)
Reset all GravityControls in the grav_controls list.
virtual void sort_controls ()
Sort the GravityControls in the grav_controls list in increasing acceleration magnitude order.
Data Fields
unsigned int integ_frame_index {9999}
The integration frame index number of the DynBody's integration frame.
double grav_accel [3] {}
The total gravitational acceleration of the DynBody toward all planetary with which the vehicle interacts gravitationally.
double grav_grad [3][3] {}
The gradient of the gravitational acceleration vector evaluated at the DynBody's position, expressed in the vehicle's integration frame.
double grav_pot {}
The total gravitational potential at the location of the DynBody due to the gravity fields of all "active" gravitational bodies (i.e., planets).
JeodPointerVector< GravityControls >::type grav_controls
The gravity controls list for a DynBody specifies the planetary bodies with which the DynBody interacts and specifies the nature of those interactions.
Friends
class InputProcessor
void init_attrjeod__GravityInteraction ()
Detailed Description
Specifies interactions between a vehicle and a set of gravitational bodies.
Definition at line 96 of file gravity_interaction.hh.
Constructor & Destructor Documentation
GravityInteraction() [1/2]
jeod::GravityInteraction::GravityInteraction ()
Construct a GravityInteraction instance.
Definition at line 58 of file gravity_interaction.cc.
References grav_controls, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and JEOD_REGISTER_INCOMPLETE_CLASS.
~GravityInteraction()
jeod::GravityInteraction::~GravityInteraction () virtual
Destruct a GravityInteraction instance.
Definition at line 68 of file gravity_interaction.cc.
References grav_controls, and JEOD_DEREGISTER_CHECKPOINTABLE.
GravityInteraction() [2/2]
jeod::GravityInteraction::GravityInteraction (const GravityInteraction & frame) delete
Member Function Documentation
add_control()
void jeod::GravityInteraction::add_control (GravityControls * control) virtual
Add a new GravityControls to the grav_controls list.
Parameters
[in] control Control to be added
Definition at line 91 of file gravity_interaction.cc.
References jeod::GravityMessages::duplicate_entry, grav_controls, and jeod::MessageHandler::warn().
Referenced by jeod::DynBody::add_control().
initialize_controls()
void jeod::GravityInteraction::initialize_controls (BaseDynManager & dyn_manager, GravityManager & grav_manager) virtual
Initialize all GravityControls in the grav_controls list.
Parameters
[in] dyn_manager Ref to Dyn Manager
[in] grav_manager Ref to Gravity Manager
Definition at line 135 of file gravity_interaction.cc.
References grav_controls, and reset_controls().
Referenced by jeod::DynBody::initialize_controls().
operator=()
GravityInteraction& jeod::GravityInteraction::operator= (const GravityInteraction & frame) delete
remove_control()
void jeod::GravityInteraction::remove_control (GravityControls * control) virtual
Remove a GravityControls from the grav_controls list.
Parameters
[in] control GravityControls to be removed.
Definition at line 113 of file gravity_interaction.cc.
References grav_controls, jeod::GravityMessages::missing_entry, and jeod::MessageHandler::warn().
reset_controls()
void jeod::GravityInteraction::reset_controls (BaseDynManager & dyn_manager) virtual
Reset all GravityControls in the grav_controls list.
Definition at line 150 of file gravity_interaction.cc.
References grav_controls.
Referenced by initialize_controls(), and jeod::DynBody::reset_controls().
set_integ_frame()
void jeod::GravityInteraction::set_integ_frame (const EphemerisRefFrame & ref_frame, const BaseDynManager & dyn_manager) virtual
Set the integration frame and associated integration frame index.
Assumptions and Limitations
Provided frame is a valid integration frame.
Parameters
[in] ref_frame Integration frame
[in] dyn_manager Dynamics manager
Definition at line 82 of file gravity_interaction.cc.
References jeod::BaseEphemeridesManager::find_integ_frame_index(), and integ_frame_index.
Referenced by jeod::DynBody::set_integ_frame().
sort_controls()
void jeod::GravityInteraction::sort_controls () virtual
Sort the GravityControls in the grav_controls list in increasing acceleration magnitude order.
Definition at line 163 of file gravity_interaction.cc.
References jeod::GravityControls::accel_mag_less_ptr(), jeod::GravityControls::active, jeod::GravityControls::grav_accel, jeod::GravityControls::grav_accel_magsq, grav_controls, and jeod::Vector3::vmagsq().
Referenced by jeod::DynBodyFrameSwitch::apply(), and jeod::DynBody::sort_controls().
Friends And Related Function Documentation
init_attrjeod__GravityInteraction
void init_attrjeod__GravityInteraction () friend
InputProcessor
friend class InputProcessor friend
Definition at line 98 of file gravity_interaction.hh.
Field Documentation
grav_accel
double jeod::GravityInteraction::grav_accel[3] {}
The total gravitational acceleration of the DynBody toward all planetary with which the vehicle interacts gravitationally.
The acceleration is expressed in the DynBody's integration frame. The gravitational acceleration of the integration frame itself toward the planetary bodies is excluded from this total acceleration. For example, for a vehicle integrated in Earth-centered inertial, the Sun component of the total gravitational acceleration is the Newtonian gravitation acceleration of the vehicle toward the Sun less the Newtonian gravitational acceleration of the Earth toward the Sun.trick_units(m/s2)
Definition at line 118 of file gravity_interaction.hh.
Referenced by jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), and jeod::GravityManager::gravitation().
grav_controls
JeodPointerVector<GravityControls>::type jeod::GravityInteraction::grav_controls
The gravity controls list for a DynBody specifies the planetary bodies with which the DynBody interacts and specifies the nature of those interactions.
trick_io(**)
Definition at line 138 of file gravity_interaction.hh.
Referenced by add_control(), jeod::DynBodyFrameSwitch::apply(), jeod::GravityManager::gravitation(), GravityInteraction(), initialize_controls(), remove_control(), reset_controls(), sort_controls(), and ~GravityInteraction().
grav_grad
double jeod::GravityInteraction::grav_grad[3][3] {}
The gradient of the gravitational acceleration vector evaluated at the DynBody's position, expressed in the vehicle's integration frame.
trick_units(1/s2)
Definition at line 124 of file gravity_interaction.hh.
Referenced by jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::GravityManager::gravitation(), and jeod::GravityTorque::update().
grav_pot
double jeod::GravityInteraction::grav_pot {}
The total gravitational potential at the location of the DynBody due to the gravity fields of all "active" gravitational bodies (i.e., planets).
trick_units(m2/s2)
Definition at line 131 of file gravity_interaction.hh.
Referenced by jeod::GravityManager::gravitation().
integ_frame_index
unsigned int jeod::GravityInteraction::integ_frame_index {9999}
The integration frame index number of the DynBody's integration frame.
This data member must be kept in strict synchronization with the DynBody's integration frame.trick_units(–)
Definition at line 105 of file gravity_interaction.hh.
Referenced by jeod::DynBodyFrameSwitch::apply(), jeod::GravityManager::gravitation(), and set_integ_frame().
The documentation for this class was generated from the following files:
gravity_interaction.hh
gravity_interaction.cc