JEOD: jeod::TestMessageHandler Class Reference
jeod::TestMessageHandler Class Reference
The MessageHandler class designed for use in unit tests.
#include <test_message_handler.hh>
Public Member Functions
TestMessageHandler (TestSimInterface &)
Non-default constructor.
~TestMessageHandler ()
Destruct a TestMessageHandler.
void add_allowed_code (const std::string &)
Add a code to the allowed codes list; see TestSimInterface::add_allowed_code for a detailed description.
void add_verboten_code (const std::string &)
Add a code to the verboten codes list; see TestSimInterface::add_verboten_code for a detailed description.
virtual void process_add_suppressed_code (const char *)
Add a code to the suppressed codes list; see MessageHandler::add_suppressed_code for a detailed description.
virtual void process_delete_suppressed_code (const char *)
Delete a code from the suppressed codes list.
void set_failure_threshold (int level)
Set the failure threshold used in determining whether a non-fatal error needs to undergo accepted/verboten code examination.
Public Member Functions inherited from jeod::MessageHandler
MessageHandler ()
Construct a MessageHandler.
virtual ~MessageHandler ()
Destruct a MessageHandler.
virtual void register_contents ()
Register the checkpointable contents of the handler with the simulation interface.
virtual void deregister_contents ()
Deregister the checkpointable contents of the handler with the simulation interface.
Protected Member Functions
virtual void process_message (int severity, const char *prefix, const char *file, unsigned int line, const char *msg_code, const char *format, va_list args) const
Handle a message.
Protected Member Functions inherited from jeod::MessageHandler
virtual void process_clear_suppressed_codes ()
Clear the set of suppressed message codes.
Private Types
typedef std::set< std::string > CodeList
Maps message handler codes to an integer.
Private Member Functions
TestMessageHandler (const TestMessageHandler &)
Not implemented.
TestMessageHandler & operator= (const TestMessageHandler &)
Not implemented.
Private Attributes
TestSimInterface & sim_interface
process_message() calls sim_interface.set_failed() when a msg_code that is not in the allowed_codes list (exact match) but is in the verboten_codes list (initial match).
CodeList allowed_codes
The list of message codes (e.g.
CodeList verboten_codes
The list of message code prefixes that indicate a test has failed.
CodeList suppressed_codes
The list of message code that are to be suppressed.
int failure_threshold
The message severity level that indicates a failed test.
Friends
class InputProcessor
void init_attrjeod__TestMessageHandler ()
Additional Inherited Members
Static Public Member Functions inherited from jeod::MessageHandler
static void fail (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with negative severity, MessageHandler::Failure, and terminate the simulation.
static void error (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with severity MessageHandler::Error.
static void warn (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with severity MessageHandler::Warning.
static void inform (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generates a message with severity MessageHandler::Notice.
static void debug (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with severity MessageHandler::Debug.
static void send_message (int severity, const char *prefix, const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generic variable arguments message interface.
static void va_send_message (int severity, const char *prefix, const char *file, unsigned int line, const char *msg_code, const char *format, va_list args)
Generic variable arguments message interface.
static void set_suppression_level (unsigned int suppression_level)
Set the suppression level in the global message handler.
static unsigned int get_suppression_level ()
Get the suppress_id of the global massage handler.
static void add_suppressed_code (const char *msg_code)
Add a message code to the set of messages that are to be suppressed for messages with positive severity level.
static void delete_suppressed_code (const char *msg_code)
Delete a message code from the set of suppressed message codes.
static void clear_suppressed_codes ()
Clear the set of suppressed message codes.
static void set_suppress_id (bool suppress_id)
Set the suppress_id flag in the global message handler.
static bool get_suppress_id ()
Get the suppress_id of the global massage handler.
static void set_suppress_location (bool suppress_location)
Set the suppress_location in the global message handler.
static bool get_suppress_location ()
Get the suppress_location of the global massage handler.
Static Public Attributes inherited from jeod::MessageHandler
static const int Failure = -1
The severity value passed by the static public MessageHandler::fail method to the derived class process_message method.
static const int Error = 0
The severity value passed by the static public MessageHandler::error method to the derived class process_message method.
static const int Warning = 9
The severity value passed by the static public MessageHandler::warn method to the derived class process_message method.
static const int Notice = 99
The severity value passed by the static public MessageHandler::inform method to the derived class process_message method.
static const int Debug = 999
The severity value passed by the static public MessageHandler::debug method to the derived class process_message method.
Static Protected Member Functions inherited from jeod::MessageHandler
static void no_handler_error (void)
Handle the error condition where there is no global handler.
Protected Attributes inherited from jeod::MessageHandler
unsigned int suppression_level
All messages have an associated severity level, with increasingly positive values indicating warnings of decreasing severity.
bool suppress_id
This flag indicates whether the message ID is printed for unsuppressed messages.
bool suppress_location
This flag indicates whether the message source file and line number printed for unsuppressed messages.
Static Protected Attributes inherited from jeod::MessageHandler
static MessageHandler * handler = nullptr
The MessageHandler instance that generates messages.
Detailed Description
The MessageHandler class designed for use in unit tests.
Definition at line 104 of file test_message_handler.hh.
Member Typedef Documentation
CodeList
typedef std::set<std::string> jeod::TestMessageHandler::CodeList private
Maps message handler codes to an integer.
Definition at line 151 of file test_message_handler.hh.
Constructor & Destructor Documentation
TestMessageHandler() [1/2]
jeod::TestMessageHandler::TestMessageHandler (TestSimInterface & interface)
Non-default constructor.
Parameters
[in,out] interface The simulation interface
Definition at line 110 of file test_message_handler.cc.
~TestMessageHandler()
jeod::TestMessageHandler::~TestMessageHandler (void)
Destruct a TestMessageHandler.
Definition at line 125 of file test_message_handler.cc.
References allowed_codes, and verboten_codes.
TestMessageHandler() [2/2]
jeod::TestMessageHandler::TestMessageHandler (const TestMessageHandler &) private
Not implemented.
Member Function Documentation
add_allowed_code()
void jeod::TestMessageHandler::add_allowed_code (const std::string & code)
Add a code to the allowed codes list; see TestSimInterface::add_allowed_code for a detailed description.
Parameters
[in] code The message code to be marked as allowed
Definition at line 139 of file test_message_handler.cc.
References allowed_codes.
Referenced by jeod::TestSimInterface::add_allowed_code().
add_verboten_code()
void jeod::TestMessageHandler::add_verboten_code (const std::string & code)
Add a code to the verboten codes list; see TestSimInterface::add_verboten_code for a detailed description.
Parameters
[in] code The message code to be marked as verboten
Definition at line 152 of file test_message_handler.cc.
References verboten_codes.
Referenced by jeod::TestSimInterface::add_verboten_code().
operator=()
TestMessageHandler& jeod::TestMessageHandler::operator= (const TestMessageHandler &) private
Not implemented.
process_add_suppressed_code()
void jeod::TestMessageHandler::process_add_suppressed_code (const char * msg_code) virtual
Add a code to the suppressed codes list; see MessageHandler::add_suppressed_code for a detailed description.
Parameters
[in] msg_code The message code to be suppressed
Reimplemented from jeod::MessageHandler.
Definition at line 165 of file test_message_handler.cc.
References suppressed_codes.
process_delete_suppressed_code()
void jeod::TestMessageHandler::process_delete_suppressed_code (const char * msg_code) virtual
Delete a code from the suppressed codes list.
Parameters
[in] msg_code The message code to be unsuppressed
Reimplemented from jeod::MessageHandler.
Definition at line 177 of file test_message_handler.cc.
References suppressed_codes.
process_message()
void jeod::TestMessageHandler::process_message (int severity, const char * prefix, const char * file, unsigned int line, const char * msg_code, const char * format, va_list args) const protected virtual
Handle a message.
All calls to the message-generating MessageHandler methods eventually result in a call to this method. This method thus intercepts all message handler calls. The message processing in this method is limited to test harness issues; the bulk of the processing is done by the TrickMessageHandler.
Parameters
[in] severity Severity level
[in] prefix Message prefix (e.g., Error)
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] args Arguments
Implements jeod::MessageHandler.
Definition at line 212 of file test_message_handler.cc.
References allowed_codes, jeod::TestSimInterface::bump_allowed_count(), failure_threshold, JEOD_SEND_HS_LEVEL, jeod::print_message_and_exit(), jeod::print_nonfatal_message(), sim_interface, jeod::MessageHandler::suppress_id, jeod::MessageHandler::suppress_location, suppressed_codes, jeod::MessageHandler::suppression_level, and verboten_codes.
set_failure_threshold()
void jeod::TestMessageHandler::set_failure_threshold (int threshold)
Set the failure threshold used in determining whether a non-fatal error needs to undergo accepted/verboten code examination.
Parameters
[in] threshold New threshold
Definition at line 190 of file test_message_handler.cc.
References failure_threshold.
Referenced by jeod::TestSimInterface::set_failure_threshold().
Friends And Related Function Documentation
init_attrjeod__TestMessageHandler
void init_attrjeod__TestMessageHandler () friend
InputProcessor
friend class InputProcessor friend
Definition at line 105 of file test_message_handler.hh.
Field Documentation
allowed_codes
CodeList jeod::TestMessageHandler::allowed_codes private
The list of message codes (e.g.
utils/memory/debug) that partially match one of the verboten_codes but are nonetheless acceptable. Items are added to this list via TestMessageHandler::add_allowed_code.trick_io(**) trick_units(–)
Definition at line 167 of file test_message_handler.hh.
Referenced by add_allowed_code(), process_message(), and ~TestMessageHandler().
failure_threshold
int jeod::TestMessageHandler::failure_threshold private
The message severity level that indicates a failed test.
The test is marked failed if a message with a verboten code and a severity level at or below this threshold is generated.trick_units(–)
Definition at line 193 of file test_message_handler.hh.
Referenced by process_message(), and set_failure_threshold().
sim_interface
TestSimInterface& jeod::TestMessageHandler::sim_interface private
process_message() calls sim_interface.set_failed() when a msg_code that is not in the allowed_codes list (exact match) but is in the verboten_codes list (initial match).
trick_io(**) trick_units(–)
Definition at line 160 of file test_message_handler.hh.
Referenced by process_message().
suppressed_codes
CodeList jeod::TestMessageHandler::suppressed_codes private
The list of message code that are to be suppressed.
trick_io(**) trick_units(–)
Definition at line 186 of file test_message_handler.hh.
Referenced by process_add_suppressed_code(), process_delete_suppressed_code(), and process_message().
verboten_codes
CodeList jeod::TestMessageHandler::verboten_codes private
The list of message code prefixes that indicate a test has failed.
Items are added to this list via TestMessageHandler::add_verboten_code.
An incoming message code to TestMessageHandler::process_message() that matches (prefix match) one of the items in the verboten_codes list and is not in the allowed_codes list will result in the simulation interface being informed the test has failed. For example, to make all message codes from the memory model except for debug messages indicative of a failed test, add "/utils/memory" to the verboten_codes list and "/utils/memory/debug" to the allowed_codes.trick_io(**) trick_units(–)
Definition at line 181 of file test_message_handler.hh.
Referenced by add_verboten_code(), process_message(), and ~TestMessageHandler().
The documentation for this class was generated from the following files:
test_message_handler.hh
test_message_handler.cc