JEOD: jeod::JPVCollectTorque Class Reference
jeod::JPVCollectTorque Class Reference
This is a derived version of the template class JeodPointerVector<CollectTorque>::type with an implementation of the method perform_cleanup_action which frees and clears stale data following a restore.
#include <body_force_collect.hh>
Public Member Functions
void perform_insert_action (const std::string &value) override
Interpret the provided value and add it to the list.
void push_back (CollectTorque *const &elem)
Add an element to the end of the contents.
Public Member Functions inherited from jeod::JeodPointerContainer< ContainerType, ElemType >
JeodPointerContainer ()
Construct a JeodPointerContainer.
JeodPointerContainer (const JeodPointerContainer &source)
Copy-construct a JeodPointerContainer.
JeodPointerContainer (const typename ContainerType::stl_container_type &source)
Copy-construct a JeodPointerContainer.
JeodPointerContainer & operator= (const JeodPointerContainer &source)
Copy from a JeodPointerContainer.
JeodPointerContainer & operator= (const typename ContainerType::stl_container_type &source)
Copy from an STL container.
virtual ~JeodPointerContainer ()=default
Destruct a JeodPointerContainer.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
const std::string get_item_value () override
Return the value of the item to be written to the checkpoint file.
void perform_insert_action (const std::string &value) override
Interpret the provided value and add it to the list.
Public Member Functions inherited from jeod::JeodContainer< ContainerType, ElemType *>
JeodContainer ()
Default constructor.
JeodContainer (const this_container_type &source)
Copy constructor.
JeodContainer (const stl_container_type &source)
Copy constructor.
JeodContainer & operator= (const this_container_type &source)
Assignment operator.
JeodContainer & operator= (const stl_container_type &source)
Assignment operator.
~JeodContainer () override=default
Destructor.
void swap_contents (this_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
void swap_contents (stl_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
virtual void perform_cleanup_action (const std::string &value)
Cleanup detritus created during the restore process.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
void start_checkpoint () override
Prepare to checkpoint the object.
void advance_checkpoint () override
Advance to the next item to be checkpointed.
bool is_checkpoint_finished () override
Indicate whether the checkpoint dump of this object is finished.
const std::string get_init_name () override
Names the action to be performed prior to performing any of the restore actions.
const std::string get_item_name () override
Return the name of the action to be printed along with the current value.
const std::string get_final_name () override
Names the action to be performed after to performing any of the restore actions.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()=default
virtual ~JeodCheckpointable ()=default
JeodCheckpointable (const JeodCheckpointable &)=delete
JeodCheckpointable & operator= (const JeodCheckpointable &)=delete
virtual void pre_checkpoint ()
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint ()
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart ()
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart ()
In general, perform object-specific operations that need to be performed after restart completion.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value ()
In general, return the value of the initialization action.
virtual const std::string get_final_value ()
In general, return the value of the finalization action.
Friends
template<typename CollectType , typename value_type >
void collect_insert (CollectType &collect_in, value_type &elem)
template<typename CollectType , typename value_type >
void collect_push_back (CollectType &collect_in, value_type &elem)
Additional Inherited Members
Public Types inherited from jeod::JeodContainer< ContainerType, ElemType *>
using this_container_type = JeodContainer< ContainerType, ElemType * >
This particular JeodContainer type.
using stl_container_type = typename ContainerType::stl_container_type
Import the ContainerType's container type.
Protected Attributes inherited from jeod::JeodPointerContainer< ContainerType, ElemType >
const JeodMemoryTypeDescriptor * base_type_descriptor {}
Memory model descriptor of the type of data stored in the container.
Protected Attributes inherited from jeod::JeodContainer< ContainerType, ElemType *>
ContainerType::iterator checkpoint_iter
Iterator for walking through the container during checkpoint.
const JeodMemoryTypeDescriptor * elem_type_descriptor
Memory model descriptor of the type of data stored in the container.
Detailed Description
This is a derived version of the template class JeodPointerVector<CollectTorque>::type with an implementation of the method perform_cleanup_action which frees and clears stale data following a restore.
Definition at line 217 of file body_force_collect.hh.
Member Function Documentation
perform_insert_action()
void jeod::JPVCollectTorque::perform_insert_action (const std::string & value) inline override virtual
Interpret the provided value and add it to the list.
For a JPVCollectTorque, the value should specify (in string form) the address of a unique torque vector pointer in active memory. If the entry already exists, check and delete the "restored" CollectTorque
Implements jeod::JeodContainer< ContainerType, ElemType *>.
Definition at line 232 of file body_force_collect.hh.
References collect_insert, jeod::JeodSimulationInterface::get_address_at_name(), and jeod::MessageHandler::warn().
push_back()
void jeod::JPVCollectTorque::push_back (CollectTorque *const & elem) inline
Add an element to the end of the contents.
Parameters
elem Element to be added.
Definition at line 254 of file body_force_collect.hh.
References collect_push_back.
Friends And Related Function Documentation
collect_insert
template<typename CollectType , typename value_type > void collect_insert (CollectType & collect_in, value_type & elem) friend
Definition at line 92 of file body_force_collect.hh.
Referenced by perform_insert_action().
collect_push_back
template<typename CollectType , typename value_type > void collect_push_back (CollectType & collect_in, value_type & elem) friend
Definition at line 128 of file body_force_collect.hh.
Referenced by push_back().
The documentation for this class was generated from the following file:
body_force_collect.hh