JEOD: jeod::DynBodyInitPlanetDerived Class Reference
jeod::DynBodyInitPlanetDerived Class Reference
(Initialize selected aspects of a vehicle's state with respect to some state that is derived from some vehicle's state in conjunction with a planet.
#include <dyn_body_init_planet_derived.hh>
Public Member Functions
DynBodyInitPlanetDerived ()=default
~DynBodyInitPlanetDerived () override=default
DynBodyInitPlanetDerived (const DynBodyInitPlanetDerived &)=delete
DynBodyInitPlanetDerived & operator= (const DynBodyInitPlanetDerived &)=delete
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
bool is_ready () override
Indicate whether the initializer is ready to run.
void apply (DynManager &dyn_manager) override
Apply the initializer: This is just a pass through.
Public Member Functions inherited from jeod::DynBodyInitWrtPlanet
DynBodyInitWrtPlanet ()=default
~DynBodyInitWrtPlanet () override=default
DynBodyInitWrtPlanet (const DynBodyInitWrtPlanet &)=delete
DynBodyInitWrtPlanet & operator= (const DynBodyInitWrtPlanet &)=delete
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
RefFrameItems::Items initializes_what () override
Indicate what parts of the vehicle state this object initializes.
bool is_ready () override
Indicate whether the initializer is ready to run.
void apply (DynManager &dyn_manager) override
Apply the initializer.
Public Member Functions inherited from jeod::DynBodyInit
DynBodyInit ()=default
~DynBodyInit () override=default
DynBodyInit (const DynBodyInit &)=delete
DynBodyInit & operator= (const DynBodyInit &)=delete
virtual void report_failure ()
Report on an initializer that could not be processed.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
Data Fields
std::string ref_body_name {""}
The name of the vehicle whose composite body frame is used to build the derived state with respect to which the vehicle initialization data are referenced.
Data Fields inherited from jeod::DynBodyInitWrtPlanet
std::string planet_name {""}
The name of the planet about which the reference body's LVLH frame is to be computed.
RefFrameItems::Items set_items {RefFrameItems::Pos_Vel_Att_Rate}
The state elements to be set by this initializer.
Data Fields inherited from jeod::DynBodyInit
std::string body_frame_id {""}
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
std::string reference_ref_frame_name {""}
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
RefFrameState state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
double position [3] {}
Relative position between the subject and reference reference frame origins.
double velocity [3] {}
Relative velocity between the subject and reference reference frame origins.
Orientation orientation
Relative orientation between the subject and reference reference frame axes.
double ang_velocity [3] {}
Relative angular velocity between the subject and reference axes.
bool reverse_sense {}
Indicates how the user input state items are to be interpreted.
bool rate_in_parent {}
Indicates how the user input angular velocity is to be interpreted.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Attributes
DynBody * ref_body {}
The vehicle corresponding to the ref_body_name.
RefFrameItems::Items required_items {RefFrameItems::Pos_Vel_Att_Rate}
The state elements in the reference body's composite body frame that must be set before this initializer can proceed.
bool body_is_required {true}
If true (default), the ref_body cannot be NULL.
Protected Attributes inherited from jeod::DynBodyInitWrtPlanet
Planet * planet {}
The planet corresponding to the planet_name.
Protected Attributes inherited from jeod::DynBodyInit
BodyRefFrame * body_ref_frame {}
The reference frame whose name is vehicle_name.body_frame_id.
RefFrame * reference_ref_frame {}
The reference frame whose name is reference_ref_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Friends
class InputProcessor
void init_attrjeod__DynBodyInitPlanetDerived ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyInit
void apply_user_inputs ()
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
void compute_rotational_state ()
This method is obsolete.
void compute_translational_state ()
This method is obsolete.
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
DynBody * find_dyn_body (const DynManager &dyn_manager, const std::string &dyn_body_name, const std::string &variable_name)
Find the DynBody with the given name, failing if not found.
RefFrame * find_ref_frame (const DynManager &dyn_manager, const std::string &ref_frame_name, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
BodyRefFrame * find_body_frame (DynBody &frame_container, const std::string &body_frame_identifier, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Detailed Description
(Initialize selected aspects of a vehicle's state with respect to some state that is derived from some vehicle's state in conjunction with a planet.
Definition at line 85 of file dyn_body_init_planet_derived.hh.
Constructor & Destructor Documentation
DynBodyInitPlanetDerived() [1/2]
jeod::DynBodyInitPlanetDerived::DynBodyInitPlanetDerived () default
~DynBodyInitPlanetDerived()
jeod::DynBodyInitPlanetDerived::~DynBodyInitPlanetDerived () override default
DynBodyInitPlanetDerived() [2/2]
jeod::DynBodyInitPlanetDerived::DynBodyInitPlanetDerived (const DynBodyInitPlanetDerived &) delete
Member Function Documentation
apply()
void jeod::DynBodyInitPlanetDerived::apply (DynManager & dyn_manager) override virtual
Apply the initializer: This is just a pass through.
A derived class is responsible for setting the state that the DynBodyInit uses to initialize the state.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 90 of file dyn_body_init_planet_derived.cc.
References jeod::DynBodyInitWrtPlanet::apply().
Referenced by jeod::DynBodyInitLvlhState::apply(), and jeod::DynBodyInitNedState::apply().
initialize()
void jeod::DynBodyInitPlanetDerived::initialize (DynManager & dyn_manager) override virtual
Initialize the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 51 of file dyn_body_init_planet_derived.cc.
References body_is_required, jeod::DynBodyInit::find_dyn_body(), jeod::DynBodyInitWrtPlanet::initialize(), ref_body, and ref_body_name.
Referenced by jeod::DynBodyInitLvlhState::initialize(), and jeod::DynBodyInitNedState::initialize().
is_ready()
bool jeod::DynBodyInitPlanetDerived::is_ready () override virtual
Indicate whether the initializer is ready to run.
When the state is based on some reference body, that reference vehicle's composite body frame must contain the specified required items before the initializer can run.
Returns
Is initializer ready?
Reimplemented from jeod::DynBodyInit.
Definition at line 73 of file dyn_body_init_planet_derived.cc.
References jeod::DynBody::composite_body, jeod::RefFrameItems::contains(), jeod::BodyRefFrame::initialized_items, jeod::DynBodyInitWrtPlanet::is_ready(), ref_body, and required_items.
operator=()
DynBodyInitPlanetDerived& jeod::DynBodyInitPlanetDerived::operator= (const DynBodyInitPlanetDerived &) delete
Friends And Related Function Documentation
init_attrjeod__DynBodyInitPlanetDerived
void init_attrjeod__DynBodyInitPlanetDerived () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file dyn_body_init_planet_derived.hh.
Field Documentation
body_is_required
bool jeod::DynBodyInitPlanetDerived::body_is_required {true} protected
If true (default), the ref_body cannot be NULL.
If false, the derived class must provide some means other than using a derived state to set the reference RefFrame.trick_io(**)
Definition at line 117 of file dyn_body_init_planet_derived.hh.
Referenced by jeod::DynBodyInitNedState::DynBodyInitNedState(), jeod::DynBodyInitLvlhState::initialize(), jeod::DynBodyInitNedState::initialize(), and initialize().
ref_body
DynBody* jeod::DynBodyInitPlanetDerived::ref_body {} protected
The vehicle corresponding to the ref_body_name.
Note that this is not a user-inputtable item.trick_io(**)
Definition at line 102 of file dyn_body_init_planet_derived.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitNedState::apply(), jeod::DynBodyInitLvlhRotState::initialize(), initialize(), and is_ready().
ref_body_name
std::string jeod::DynBodyInitPlanetDerived::ref_body_name {""}
The name of the vehicle whose composite body frame is used to build the derived state with respect to which the vehicle initialization data are referenced.
trick_units(–)
Definition at line 95 of file dyn_body_init_planet_derived.hh.
Referenced by jeod::DynBodyInitLvlhRotState::initialize(), jeod::DynBodyInitNedState::initialize(), and initialize().
required_items
RefFrameItems::Items jeod::DynBodyInitPlanetDerived::required_items {RefFrameItems::Pos_Vel_Att_Rate} protected
The state elements in the reference body's composite body frame that must be set before this initializer can proceed.
This is not user-inputtable; derived classes should set this item. The default is to require the full state to be set.trick_io(**)
Definition at line 110 of file dyn_body_init_planet_derived.hh.
Referenced by jeod::DynBodyInitLvlhState::DynBodyInitLvlhState(), jeod::DynBodyInitNedState::DynBodyInitNedState(), and is_ready().
The documentation for this class was generated from the following files:
dyn_body_init_planet_derived.hh
dyn_body_init_planet_derived.cc