JEOD: jeod::DynBodyInit Class Reference
jeod::DynBodyInit Class Reference
Base class for initialize the state of a DynBody.
#include <dyn_body_init.hh>
Public Member Functions
DynBodyInit ()=default
~DynBodyInit () override=default
DynBodyInit (const DynBodyInit &)=delete
DynBodyInit & operator= (const DynBodyInit &)=delete
virtual void report_failure ()
Report on an initializer that could not be processed.
void initialize (DynManager &dyn_manager) override
Complete initialization of a DynBodyInit.
virtual RefFrameItems::Items initializes_what ()
In general, specify what state elements are to be initialized.
bool is_ready () override
In general, determine if the initializer is ready to be applied.
void apply (DynManager &dyn_manager) override
Complete initialization of the subject DynBody.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
Data Fields
std::string body_frame_id {""}
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
std::string reference_ref_frame_name {""}
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
RefFrameState state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
double position [3] {}
Relative position between the subject and reference reference frame origins.
double velocity [3] {}
Relative velocity between the subject and reference reference frame origins.
Orientation orientation
Relative orientation between the subject and reference reference frame axes.
double ang_velocity [3] {}
Relative angular velocity between the subject and reference axes.
bool reverse_sense {}
Indicates how the user input state items are to be interpreted.
bool rate_in_parent {}
Indicates how the user input angular velocity is to be interpreted.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Member Functions
void apply_user_inputs ()
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
void compute_rotational_state ()
This method is obsolete.
void compute_translational_state ()
This method is obsolete.
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
DynBody * find_dyn_body (const DynManager &dyn_manager, const std::string &dyn_body_name, const std::string &variable_name)
Find the DynBody with the given name, failing if not found.
RefFrame * find_ref_frame (const DynManager &dyn_manager, const std::string &ref_frame_name, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
BodyRefFrame * find_body_frame (DynBody &frame_container, const std::string &body_frame_identifier, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes
BodyRefFrame * body_ref_frame {}
The reference frame whose name is vehicle_name.body_frame_id.
RefFrame * reference_ref_frame {}
The reference frame whose name is reference_ref_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Private Attributes
RefFrame * subscribed_frame {}
The subscribed-to frame (the reference_ref_frame at initialization time), cached so that this frame will be unsubscribed at application time.
Friends
class InputProcessor
void init_attrjeod__DynBodyInit ()
Detailed Description
Base class for initialize the state of a DynBody.
Definition at line 88 of file dyn_body_init.hh.
Constructor & Destructor Documentation
DynBodyInit() [1/2]
jeod::DynBodyInit::DynBodyInit () default
~DynBodyInit()
jeod::DynBodyInit::~DynBodyInit () override default
DynBodyInit() [2/2]
jeod::DynBodyInit::DynBodyInit (const DynBodyInit &) delete
Member Function Documentation
apply()
void jeod::DynBodyInit::apply (DynManager & dyn_manager) override virtual
Complete initialization of the subject DynBody.
The apply method for all subclasses of DynBodyInit nust pass the apply call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAction.
Reimplemented in jeod::DynBodyInitOrbit, jeod::DynBodyInitPlanetDerived, jeod::DynBodyInitNedState, jeod::DynBodyInitWrtPlanet, jeod::DynBodyInitLvlhState, jeod::DynBodyInitRotState, and jeod::DynBodyInitTransState.
Definition at line 210 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, jeod::BodyAction::apply(), jeod::DynBody::autoupdate_vehicle_points, body_ref_frame, jeod::MessageHandler::debug(), jeod::BodyAction::dyn_subject, jeod::RefFrame::get_name(), initializes_what(), jeod::DynBody::propagate_state(), reference_ref_frame, jeod::DynBody::set_state(), state, subscribed_frame, jeod::RefFrameItems::to_string(), jeod::BodyActionMessages::trace, and jeod::RefFrameManager::unsubscribe_to_frame().
Referenced by jeod::DynBodyInitRotState::apply(), jeod::DynBodyInitTransState::apply(), and jeod::DynBodyInitWrtPlanet::apply().
apply_user_inputs()
void jeod::DynBodyInit::apply_user_inputs () protected
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
Definition at line 273 of file dyn_body_init.cc.
References jeod::RefFrame::add_child(), jeod::RefFrameRot::ang_vel_this, ang_velocity, jeod::RefFrameItems::Att, body_ref_frame, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_quaternion(), jeod::RefFrame::compute_relative_state(), jeod::Orientation::compute_transform(), jeod::RefFrameItems::contains(), jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::BodyAction::dyn_subject, jeod::DynBody::get_integ_frame(), initializes_what(), jeod::RefFrameState::negate(), orientation, jeod::RefFrameItems::Pos, jeod::RefFrameTrans::position, position, jeod::RefFrameItems::Rate, rate_in_parent, reference_ref_frame, jeod::RefFrame::remove_from_parent(), reverse_sense, jeod::RefFrameState::rot, jeod::RefFrame::state, state, jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Orientation::trans, jeod::Vector3::transform(), jeod::RefFrameItems::Vel, jeod::RefFrameTrans::velocity, and velocity.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitRotState::apply(), jeod::DynBodyInitTransState::apply(), jeod::DynBodyInitNedState::apply(), compute_rotational_state(), and compute_translational_state().
compute_rotational_state()
void jeod::DynBodyInit::compute_rotational_state () protected
This method is obsolete.
Use apply_user_inputs instead.
Definition at line 333 of file dyn_body_init.cc.
References apply_user_inputs(), jeod::MessageHandler::error(), and jeod::BodyActionMessages::invalid_name.
compute_translational_state()
void jeod::DynBodyInit::compute_translational_state () protected
This method is obsolete.
Use apply_user_inputs instead.
Definition at line 353 of file dyn_body_init.cc.
References apply_user_inputs(), jeod::MessageHandler::error(), and jeod::BodyActionMessages::invalid_name.
find_body_frame()
BodyRefFrame * jeod::DynBodyInit::find_body_frame (DynBody & frame_container, const std::string & body_frame_identifier, const std::string & variable_name) protected
Find the RefFrame with the given name, failing if not found.
Returns
Found BodyRefFrame
Parameters
[in] frame_container Body containing frame
[in] body_frame_identifier BodyRefFrame identifier
[in] variable_name For error reporting
Definition at line 491 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, jeod::NamedItem::c_str(), jeod::MessageHandler::fail(), jeod::DynBody::find_body_frame(), jeod::BodyActionMessages::invalid_name, jeod::DynBody::name, and jeod::BodyAction::validate_name().
Referenced by initialize().
find_dyn_body()
DynBody * jeod::DynBodyInit::find_dyn_body (const DynManager & dyn_manager, const std::string & dyn_body_name, const std::string & variable_name) protected
Find the DynBody with the given name, failing if not found.
Returns
Found DynBody
Parameters
[in] dyn_manager Dynamics manager
[in] dyn_body_name DynBody name
[in] variable_name For error reporting
Definition at line 415 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, jeod::MessageHandler::fail(), jeod::DynManager::find_dyn_body(), jeod::BodyActionMessages::invalid_name, and jeod::BodyAction::validate_name().
Referenced by jeod::DynBodyInitPlanetDerived::initialize().
find_planet()
Planet * jeod::DynBodyInit::find_planet (const DynManager & dyn_manager, const std::string & planet_name, const std::string & variable_name) protected
Find the Planet with the given name, failing if not found.
Returns
Found Planet
Parameters
[in] dyn_manager Dynamics manager
[in] planet_name Planet name
[in] variable_name For error reporting
Definition at line 377 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_planet(), jeod::BodyActionMessages::invalid_name, and jeod::BodyAction::validate_name().
Referenced by jeod::DynBodyInitWrtPlanet::initialize(), and jeod::DynBodyInitOrbit::initialize().
find_ref_frame()
RefFrame * jeod::DynBodyInit::find_ref_frame (const DynManager & dyn_manager, const std::string & ref_frame_name, const std::string & variable_name) protected
Find the RefFrame with the given name, failing if not found.
Returns
Found ref_frame
Parameters
[in] dyn_manager Dynamics manager
[in] ref_frame_name RefFrame name
[in] variable_name For error reporting
Definition at line 453 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, jeod::MessageHandler::fail(), jeod::RefFrameManager::find_ref_frame(), jeod::BodyActionMessages::invalid_name, and jeod::BodyAction::validate_name().
Referenced by initialize().
initialize()
void jeod::DynBodyInit::initialize (DynManager & dyn_manager) override virtual
Complete initialization of a DynBodyInit.
The initialize method for all subclasses of DynBodyInit nust pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::BodyAction.
Reimplemented in jeod::DynBodyInitOrbit, jeod::DynBodyInitPlanetDerived, jeod::DynBodyInitNedState, jeod::DynBodyInitWrtPlanet, jeod::DynBodyInitLvlhState, jeod::DynBodyInitRotState, jeod::DynBodyInitTransState, jeod::DynBodyInitLvlhRotState, jeod::DynBodyInitLvlhTransState, jeod::DynBodyInitNedRotState, and jeod::DynBodyInitNedTransState.
Definition at line 63 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, body_frame_id, body_ref_frame, jeod::NamedItem::c_str(), jeod::BodyAction::dyn_subject, jeod::MessageHandler::fail(), find_body_frame(), find_ref_frame(), jeod::BodyAction::initialize(), jeod::BodyActionMessages::invalid_object, jeod::DynManager::is_dyn_body_registered(), jeod::BodyAction::mass_subject, jeod::MassBody::name, jeod::DynBody::name, reference_ref_frame, reference_ref_frame_name, jeod::RefFrameManager::subscribe_to_frame(), subscribed_frame, and jeod::MessageHandler::warn().
Referenced by jeod::DynBodyInitRotState::initialize(), jeod::DynBodyInitTransState::initialize(), and jeod::DynBodyInitWrtPlanet::initialize().
initializes_what()
RefFrameItems::Items jeod::DynBodyInit::initializes_what () virtual
In general, specify what state elements are to be initialized.
This method indicates that no such elements are initialized. A subclass that does something must override this default method.
Returns
Initialized states
Reimplemented in jeod::DynBodyInitRotState, jeod::DynBodyInitTransState, and jeod::DynBodyInitWrtPlanet.
Definition at line 135 of file dyn_body_init.cc.
References jeod::RefFrameItems::No_Items.
Referenced by apply(), apply_user_inputs(), is_ready(), and report_failure().
is_ready()
bool jeod::DynBodyInit::is_ready () override virtual
In general, determine if the initializer is ready to be applied.
This method determines whether the self-dependencies are satisfied. Dependencies on the reference reference frame are the responsibility of derived classes.
Returns
Can initializer run?
Reimplemented from jeod::BodyAction.
Reimplemented in jeod::DynBodyInitPlanetDerived, jeod::DynBodyInitRotState, jeod::DynBodyInitTransState, and jeod::DynBodyInitWrtPlanet.
Definition at line 147 of file dyn_body_init.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameItems::Att, body_ref_frame, jeod::RefFrameItems::contains(), jeod::RefFrameItems::get(), jeod::BodyRefFrame::initialized_items, initializes_what(), jeod::BodyAction::is_ready(), jeod::RefFrameItems::Pos, jeod::RefFrameItems::Pos_Rate, jeod::RefFrameItems::Rate, rate_in_parent, jeod::RefFrameItems::remove(), reverse_sense, and jeod::RefFrameItems::Vel.
Referenced by jeod::DynBodyInitWrtPlanet::is_ready(), jeod::DynBodyInitRotState::is_ready(), and jeod::DynBodyInitTransState::is_ready().
operator=()
DynBodyInit& jeod::DynBodyInit::operator= (const DynBodyInit &) delete
report_failure()
void jeod::DynBodyInit::report_failure () virtual
Report on an initializer that could not be processed.
Definition at line 246 of file dyn_body_init.cc.
References jeod::BodyAction::action_identifier, body_ref_frame, jeod::MessageHandler::error(), jeod::RefFrame::get_name(), initializes_what(), jeod::BodyActionMessages::not_performed, reference_ref_frame, and jeod::RefFrameItems::to_string().
Referenced by jeod::DynManager::perform_dyn_body_initializations().
Friends And Related Function Documentation
init_attrjeod__DynBodyInit
void init_attrjeod__DynBodyInit () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file dyn_body_init.hh.
Field Documentation
ang_velocity
double jeod::DynBodyInit::ang_velocity[3] {}
Relative angular velocity between the subject and reference axes.
The flags reverse_sense and rate_in_parent give four interpretations:
Default (both reverse_sense and rate_in_parent are false):
Angular velocity of the subject frame with respect to the reference frame, expressed in subject frame coordinates.
reverse_sense is clear, rate_in_parent is set:
Angular velocity of the subject frame with respect to the reference frame, expressed in reference frame coordinates.
reverse_sense is set, rate_in_parent is clear:
Angular velocity of the reference frame with respect to the subject frame, expressed in reference frame coordinates.
Both reverse_sense and rate_in_parent are set:
Angular velocity of the reference frame with respect to the subject frame, expressed in subject frame coordinates.trick_units(rad/s)
Definition at line 157 of file dyn_body_init.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), and apply_user_inputs().
body_frame_id
std::string jeod::DynBodyInit::body_frame_id {""}
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
trick_units(–)
Definition at line 96 of file dyn_body_init.hh.
Referenced by initialize().
body_ref_frame
BodyRefFrame* jeod::DynBodyInit::body_ref_frame {} protected
The reference frame whose name is vehicle_name.body_frame_id.
This is the frame to which the state is applied.trick_io(**)
Definition at line 181 of file dyn_body_init.hh.
Referenced by apply(), apply_user_inputs(), initialize(), is_ready(), and report_failure().
orientation
Orientation jeod::DynBodyInit::orientation
Relative orientation between the subject and reference reference frame axes.
The normal sense (reverse_sense is not set) is the transformation from reference to subject. The reverse meaning (reverse_sense set) is the transformation from subject to reference.trick_units(–)
Definition at line 139 of file dyn_body_init.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), and apply_user_inputs().
position
double jeod::DynBodyInit::position[3] {}
Relative position between the subject and reference reference frame origins.
The normal sense (reverse_sense is not set) is the position of the subject origin with respect to the reference origin, expressed in reference coordinates. The reverse meaning (reverse_sense set) is the position of the reference origin with respect to the subject origin, expressed in subject coordinates.trick_units(m)
Definition at line 121 of file dyn_body_init.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitOrbit::apply(), and apply_user_inputs().
rate_in_parent
bool jeod::DynBodyInit::rate_in_parent {}
Indicates how the user input angular velocity is to be interpreted.
This item works in conjunction with reverse_sense. See ang_velocity for a complete description.trick_units(–)
Definition at line 174 of file dyn_body_init.hh.
Referenced by apply_user_inputs(), and is_ready().
reference_ref_frame
RefFrame* jeod::DynBodyInit::reference_ref_frame {} protected
The reference frame whose name is reference_ref_frame_name.
This is the frame against which the user state is reference.trick_io(**)
Definition at line 187 of file dyn_body_init.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitNedState::apply(), apply(), apply_user_inputs(), jeod::DynBodyInitWrtPlanet::initialize(), initialize(), jeod::DynBodyInitOrbit::initialize(), jeod::DynBodyInitRotState::is_ready(), jeod::DynBodyInitTransState::is_ready(), and report_failure().
reference_ref_frame_name
std::string jeod::DynBodyInit::reference_ref_frame_name {""}
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
trick_units(–)
Definition at line 102 of file dyn_body_init.hh.
Referenced by initialize().
reverse_sense
bool jeod::DynBodyInit::reverse_sense {}
Indicates how the user input state items are to be interpreted.
If clear (default setting), indicates that the user input position, velocity, orientation, and angular velocity are to be interpreted in the standard JEOD parent to child sense. The meaning is reversed when this flag is set. See the descriptions of the individual state items for details.trick_units(–)
Definition at line 167 of file dyn_body_init.hh.
Referenced by apply_user_inputs(), and is_ready().
state
RefFrameState jeod::DynBodyInit::state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
The DynBodyInit apply method copies the state elements indicated by the initializer's initializes_what method to the frame indicated by the frame_id and then propagates the initialized states up/down the vehicle attachment tree.trick_units(–)
Definition at line 111 of file dyn_body_init.hh.
Referenced by apply(), and apply_user_inputs().
subscribed_frame
RefFrame* jeod::DynBodyInit::subscribed_frame {} private
The subscribed-to frame (the reference_ref_frame at initialization time), cached so that this frame will be unsubscribed at application time.
trick_io(**)
Definition at line 195 of file dyn_body_init.hh.
Referenced by apply(), and initialize().
velocity
double jeod::DynBodyInit::velocity[3] {}
Relative velocity between the subject and reference reference frame origins.
The normal sense (reverse_sense is not set) is the velocity of the subject origin with respect to the reference origin, expressed in and observed in reference coordinates. The reverse meaning (reverse_sense set) is the velocity of the reference origin with respect to the subject origin, expressed in and observed in subject coordinates.trick_units(m/s)
Definition at line 131 of file dyn_body_init.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitOrbit::apply(), and apply_user_inputs().
The documentation for this class was generated from the following files:
dyn_body_init.hh
dyn_body_init.cc