JEOD: jeod::SpiceEphemPoint Class Reference
jeod::SpiceEphemPoint Class Reference
A SpiceEphemPoint minimally extends EphemerisPoint, primarily in order to contain the ID of the SPICE object that will be used to update the state of the target ephemeris reference frame.
#include <spice_ephem_point.hh>
Public Types
enum Status { IsRoot = 0, InTree = 1, Active = 2 }
Enumerates the status values of a SpiceEphemPoint.
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Public Member Functions
SpiceEphemPoint ()
SpiceEphemPoint default constructor.
~SpiceEphemPoint () override=default
SpiceEphemPoint (const SpiceEphemPoint &)=delete
SpiceEphemPoint & operator= (const SpiceEphemPoint &)=delete
virtual void set_status (SpiceEphemPoint::Status new_status)
Set the active status.
virtual SpiceEphemPoint::Status get_status () const
Return current status.
virtual void set_spice_id (int new_id)
Set ID of associated SPICE kernel object.
virtual int get_spice_id () const
Return ID of associated SPICE kernel object.
virtual void set_parent_id (int new_id)
Set ID of associated parent SPICE kernel object.
virtual int get_parent_id () const
Return ID of associated parent SPICE kernel object.
Public Member Functions inherited from jeod::EphemerisPoint
EphemerisPoint ()=default
~EphemerisPoint () override=default
EphemerisPoint (const EphemerisPoint &)=delete
EphemerisPoint & operator= (const EphemerisPoint &)=delete
TargetAspect updates_what () const override
Specify the aspect of the target frame updated by the object.
std::string default_suffix () const override
Return the default suffix for this item class, i.e., "inertial".
void disconnect_from_tree () override
Disconnect the associated inertial frame from the tree.
void note_frame_status_change (RefFrame *frame) override
Set active status to correspond with that of the inertial frame.
virtual void initialize_state ()
Zero-out the inertial frame's translational state.
virtual void update (const double *pos, const double *vel, double time)
Update the inertial frame's translational state.
virtual void update_scaled (const double *pos, const double *vel, double scale, double time)
Update the inertial frame's translational state.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()=default
~EphemerisItem () override=default
EphemerisItem (const EphemerisItem &)=delete
EphemerisItem & operator= (const EphemerisItem &)=delete
virtual void set_name (const std::string &new_name)
Name an ephemeris item.
virtual void set_name (const std::string &pname, const std::string &fname)
Name an ephemeris item.
std::string get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp () const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void enable ()
Enable an EphemerisItem object.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item () const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const std::string &new_value, const std::string &old_value, const std::string &variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
Protected Attributes
Status status {Active}
The status for the ephemeris reference frame associated with this item.
int spice_id {32767}
The SPICE kernel object to be used to maintain the target frame's state.
int parent_id {32767}
The SPICE ID of the parent to this object.
Protected Attributes inherited from jeod::EphemerisItem
std::string name
The name of the item.
EphemerisInterface * owner {}
The ephemeris model that owns this object.
BaseEphemeridesManager * manager {}
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame {}
The reference frame whose non-constant state is set by this object.
EphemerisItem * head {}
The first ephemeris item with the same name as this item.
EphemerisItem * next {}
The next ephemeris item with the same name as this item.
double update_time {}
Time of last update, dynamic time seconds.
bool enabled {}
Is the item enabled?
bool active {}
Is the item active?
Friends
class InputProcessor
void init_attrjeod__SpiceEphemPoint ()
Additional Inherited Members
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (const std::string &new_name)
Name an ephemeris item.
Detailed Description
A SpiceEphemPoint minimally extends EphemerisPoint, primarily in order to contain the ID of the SPICE object that will be used to update the state of the target ephemeris reference frame.
Definition at line 82 of file spice_ephem_point.hh.
Member Enumeration Documentation
Status
enum jeod::SpiceEphemPoint::Status
Enumerates the status values of a SpiceEphemPoint.
Enumerator
IsRoot
The target reference frame is extant, active, and is the root of the reference frame tree.
Hence its state is the trivial state.
InTree
The target reference frame is extant and active.
However, present responsibility for updating the frame lies with some other ephemeris model.
Active
The target reference frame is extant, active, and is to be updated by this ephemeris model.
Definition at line 90 of file spice_ephem_point.hh.
Constructor & Destructor Documentation
SpiceEphemPoint() [1/2]
jeod::SpiceEphemPoint::SpiceEphemPoint ()
SpiceEphemPoint default constructor.
Definition at line 40 of file spice_ephem_point.cc.
References JEOD_REGISTER_CLASS.
~SpiceEphemPoint()
jeod::SpiceEphemPoint::~SpiceEphemPoint () override default
SpiceEphemPoint() [2/2]
jeod::SpiceEphemPoint::SpiceEphemPoint (const SpiceEphemPoint &) delete
Member Function Documentation
get_parent_id()
int jeod::SpiceEphemPoint::get_parent_id () const virtual
Return ID of associated parent SPICE kernel object.
Returns
Name
Definition at line 94 of file spice_ephem_point.cc.
References parent_id.
get_spice_id()
int jeod::SpiceEphemPoint::get_spice_id () const virtual
Return ID of associated SPICE kernel object.
Returns
Name
Definition at line 76 of file spice_ephem_point.cc.
References spice_id.
Referenced by jeod::SpiceEphemeris::add_descendants_r().
get_status()
SpiceEphemPoint::Status jeod::SpiceEphemPoint::get_status () const virtual
Return current status.
Returns
Current object status
Definition at line 58 of file spice_ephem_point.cc.
References status.
operator=()
SpiceEphemPoint& jeod::SpiceEphemPoint::operator= (const SpiceEphemPoint &) delete
set_parent_id()
void jeod::SpiceEphemPoint::set_parent_id (int new_id) virtual
Set ID of associated parent SPICE kernel object.
Parameters
[in] new_id New SPICE ID
Definition at line 85 of file spice_ephem_point.cc.
References parent_id.
Referenced by jeod::SpiceEphemeris::create_new_ephem_point().
set_spice_id()
void jeod::SpiceEphemPoint::set_spice_id (int new_id) virtual
Set ID of associated SPICE kernel object.
Parameters
[in] new_id New SPICE ID
Definition at line 67 of file spice_ephem_point.cc.
References spice_id.
Referenced by jeod::SpiceEphemeris::create_new_ephem_point().
set_status()
void jeod::SpiceEphemPoint::set_status (SpiceEphemPoint::Status new_status) virtual
Set the active status.
Parameters
[in] new_status New status value
Definition at line 49 of file spice_ephem_point.cc.
References status.
Friends And Related Function Documentation
init_attrjeod__SpiceEphemPoint
void init_attrjeod__SpiceEphemPoint () friend
InputProcessor
friend class InputProcessor friend
Definition at line 84 of file spice_ephem_point.hh.
Field Documentation
parent_id
int jeod::SpiceEphemPoint::parent_id {32767} protected
The SPICE ID of the parent to this object.
trick_units(–)
Definition at line 134 of file spice_ephem_point.hh.
Referenced by get_parent_id(), and set_parent_id().
spice_id
int jeod::SpiceEphemPoint::spice_id {32767} protected
The SPICE kernel object to be used to maintain the target frame's state.
trick_units(–)
Definition at line 129 of file spice_ephem_point.hh.
Referenced by get_spice_id(), and set_spice_id().
status
Status jeod::SpiceEphemPoint::status {Active} protected
The status for the ephemeris reference frame associated with this item.
trick_units(–)
Definition at line 124 of file spice_ephem_point.hh.
Referenced by get_status(), and set_status().
The documentation for this class was generated from the following files:
spice_ephem_point.hh
spice_ephem_point.cc