JEOD: jeod::ConstraintFrame Class Reference
jeod::ConstraintFrame Class Reference
A constraint frame is directly connected to a vehicle structural frame, which in turn is connected to a root vehicle structural frame.
#include <constraint_frame.hh>
Public Member Functions
ConstraintFrame ()
Default constructor.
virtual ~ConstraintFrame ()=default
Destructor.
ConstraintFrame (const ConstraintFrame &)=default
ConstraintFrame (ConstraintFrame &&)=default
ConstraintFrame & operator= (const ConstraintFrame &)=default
ConstraintFrame & operator= (ConstraintFrame &&)=default
virtual void set_struct_to_constraint_frame (SolverTypes::ConstDecayedMatrix3x3T transform_in, SolverTypes::ConstDecayedVector3T offset_in)
Set the relationship between the constraint frame and the immediate structural frame.
virtual SolverTypes::ConstMatrix3x3RefT get_struct_to_constraint_transform () const
Get the structure to constraint frame transform.
virtual SolverTypes::ConstDecayedVector3T get_struct_to_constraint_offset () const
Get the structure to constrame frame offset.
virtual SolverTypes::ConstMatrix3x3RefT get_root_to_constraint_transform () const
Get the root structure to constraint frame transform.
virtual SolverTypes::ConstDecayedVector3T get_root_to_constraint_offset () const
Get the root structure to constraint frame offset.
virtual void update_attachment (const VehicleProperties &vehicle_properties)
Update information about the relation between this constraint and the root DynBody.
void update_root_to_constraint_frame ()
Update the root to constraint frame transformation matrix and offset.
Data Fields
DynBodyConstraintsSolver * solver
The solver associated with the root DynBody object.
double T_struct_constraint [3][3]
The transformation from the immediate structural frame to the preferred frame for this constraint.
double origin_position_struct [3]
The offset from the origin of the immediate structural frame to the origin of the preferred frame for this constraint, in immediate structure frame coordinates.
double T_root_constraint [3][3]
The transformation from the root body's structural frame to the preferred frame for this constraint.
double origin_position_root [3]
The offset from the origin of the root body's structural frame to the origin of the preferred frame for this constraint, in root body structure frame coordinates.
Friends
class InputProcessor
void init_attrjeod__ConstraintFrame ()
Detailed Description
A constraint frame is directly connected to a vehicle structural frame, which in turn is connected to a root vehicle structural frame.
A ConstraintFrame object contains both the connection to the immediate structural frame and to the root vehicle structural frame.
Definition at line 80 of file constraint_frame.hh.
Constructor & Destructor Documentation
ConstraintFrame() [1/3]
jeod::ConstraintFrame::ConstraintFrame ()
Default constructor.
Definition at line 29 of file constraint_frame.cc.
References jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), origin_position_root, origin_position_struct, T_root_constraint, and T_struct_constraint.
~ConstraintFrame()
virtual jeod::ConstraintFrame::~ConstraintFrame () virtual default
Destructor.
ConstraintFrame() [2/3]
jeod::ConstraintFrame::ConstraintFrame (const ConstraintFrame &) default
ConstraintFrame() [3/3]
jeod::ConstraintFrame::ConstraintFrame (ConstraintFrame &&) default
Member Function Documentation
get_root_to_constraint_offset()
virtual SolverTypes::ConstDecayedVector3T jeod::ConstraintFrame::get_root_to_constraint_offset () const inline virtual
Get the root structure to constraint frame offset.
Definition at line 184 of file constraint_frame.hh.
References origin_position_root.
get_root_to_constraint_transform()
virtual SolverTypes::ConstMatrix3x3RefT jeod::ConstraintFrame::get_root_to_constraint_transform () const inline virtual
Get the root structure to constraint frame transform.
Definition at line 175 of file constraint_frame.hh.
References T_root_constraint.
get_struct_to_constraint_offset()
virtual SolverTypes::ConstDecayedVector3T jeod::ConstraintFrame::get_struct_to_constraint_offset () const inline virtual
Get the structure to constrame frame offset.
Definition at line 166 of file constraint_frame.hh.
References origin_position_struct.
get_struct_to_constraint_transform()
virtual SolverTypes::ConstMatrix3x3RefT jeod::ConstraintFrame::get_struct_to_constraint_transform () const inline virtual
Get the structure to constraint frame transform.
Definition at line 157 of file constraint_frame.hh.
References T_struct_constraint.
operator=() [1/2]
ConstraintFrame& jeod::ConstraintFrame::operator= (const ConstraintFrame &) default
operator=() [2/2]
ConstraintFrame& jeod::ConstraintFrame::operator= (ConstraintFrame &&) default
set_struct_to_constraint_frame()
void jeod::ConstraintFrame::set_struct_to_constraint_frame (SolverTypes::ConstDecayedMatrix3x3T transform_in, SolverTypes::ConstDecayedVector3T offset_in) virtual
Set the relationship between the constraint frame and the immediate structural frame.
Parameters
transform_in The structure-to-constraint frame transform.
offset_in The position of the constraint frame origin, in structural frame coordinates.
Definition at line 39 of file constraint_frame.cc.
References jeod::Vector3::copy(), jeod::Matrix3x3::copy(), origin_position_struct, solver, T_struct_constraint, and update_root_to_constraint_frame().
Referenced by jeod::DynBodyConstraint::set_struct_to_constraint_frame().
update_attachment()
virtual void jeod::ConstraintFrame::update_attachment (const VehicleProperties & vehicle_properties) inline virtual
Update information about the relation between this constraint and the root DynBody.
Parameters
vehicle_properties Various vehicle properties (not used).
Definition at line 196 of file constraint_frame.hh.
References update_root_to_constraint_frame().
Referenced by jeod::DynBodyConstraint::update_attachment().
update_root_to_constraint_frame()
void jeod::ConstraintFrame::update_root_to_constraint_frame ()
Update the root to constraint frame transformation matrix and offset.
Definition at line 57 of file constraint_frame.cc.
References jeod::DynBodyConstraintsSolver::get_root_to_struct_offset(), jeod::DynBodyConstraintsSolver::get_root_to_struct_transform(), jeod::Vector3::incr(), origin_position_root, origin_position_struct, jeod::Matrix3x3::product(), solver, T_root_constraint, T_struct_constraint, and jeod::Vector3::transform_transpose().
Referenced by set_struct_to_constraint_frame(), and update_attachment().
Friends And Related Function Documentation
init_attrjeod__ConstraintFrame
void init_attrjeod__ConstraintFrame () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file constraint_frame.hh.
Field Documentation
origin_position_root
double jeod::ConstraintFrame::origin_position_root[3]
The offset from the origin of the root body's structural frame to the origin of the preferred frame for this constraint, in root body structure frame coordinates.
trick_units(m)
Definition at line 119 of file constraint_frame.hh.
Referenced by jeod::ConstrainedPointMass::compute_constraint_position_root(), ConstraintFrame(), get_root_to_constraint_offset(), and update_root_to_constraint_frame().
origin_position_struct
double jeod::ConstraintFrame::origin_position_struct[3]
The offset from the origin of the immediate structural frame to the origin of the preferred frame for this constraint, in immediate structure frame coordinates.
trick_units(m)
Definition at line 106 of file constraint_frame.hh.
Referenced by ConstraintFrame(), get_struct_to_constraint_offset(), set_struct_to_constraint_frame(), and update_root_to_constraint_frame().
solver
DynBodyConstraintsSolver* jeod::ConstraintFrame::solver
The solver associated with the root DynBody object.
trick_units(–)
Definition at line 93 of file constraint_frame.hh.
Referenced by jeod::DynBodyConstraint::reset_solver(), jeod::DynBodyConstraint::set_solver(), set_struct_to_constraint_frame(), and update_root_to_constraint_frame().
T_root_constraint
double jeod::ConstraintFrame::T_root_constraint[3][3]
The transformation from the root body's structural frame to the preferred frame for this constraint.
trick_units(–)
Definition at line 112 of file constraint_frame.hh.
Referenced by jeod::ConstrainedPointMass::compute_constraint_position_root(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::ConstraintComponent::compute_root_direction(), ConstraintFrame(), jeod::TorqueConstraintComponent::get_cross_coeff(), get_root_to_constraint_transform(), jeod::ConstrainedRigidMass::setup_constraint(), jeod::PendulumConstraintComponent::setup_constraint(), and update_root_to_constraint_frame().
T_struct_constraint
double jeod::ConstraintFrame::T_struct_constraint[3][3]
The transformation from the immediate structural frame to the preferred frame for this constraint.
trick_units(–)
Definition at line 99 of file constraint_frame.hh.
Referenced by ConstraintFrame(), get_struct_to_constraint_transform(), set_struct_to_constraint_frame(), and update_root_to_constraint_frame().
The documentation for this class was generated from the following files:
constraint_frame.hh
constraint_frame.cc