/* Autogenerated from environment/planet/data/saturn.d */

/*******************************************************************************
Purpose:
   (Default data to model Saturn's planetary parameters.)

References:
   ((None))

Assumptions and Limitations:
   ((None))


*******************************************************************************/

class Planet;
#define JEOD_FRIEND_CLASS Planet_saturn_default_data

// JEOD includes
#include "environment/planet/include/base_planet.hh"
#include "environment/planet/include/planet.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/saturn_planet.hh"

//! Namespace jeod
namespace jeod
{

void Planet_saturn_default_data::initialize(Planet * Planet_ptr)
{
    Planet_ptr->name = "Saturn";
    Planet_ptr->flat_coeff = 0.09796;
    Planet_ptr->r_eq = 1000 * (60268);
}

} // namespace jeod
