/* Autogenerated from /Users/dhammen/work/jeod/2.0/trunk/trunk/models/environment/gravity/data/saturn_spherical.d */

/*******************************************************************************

PURPOSE:
  (Default data to model Saturn's gravity.)

REFERENCE:
   (((DE405)))

ASSUMPTIONS AND LIMITATIONS:
   ((1. Vehicles are sufficiently far from Saturn))



*******************************************************************************/


class SphericalHarmonicsGravitySource;
#define JEOD_FRIEND_CLASS SphericalHarmonicsGravitySource_saturn_spherical_default_data

// JEOD includes
#include "environment/gravity/include/spherical_harmonics_gravity_source.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/saturn_spherical_gravity.hh"



//! Namespace jeod
namespace jeod {

void
SphericalHarmonicsGravitySource_saturn_spherical_default_data::initialize (
   SphericalHarmonicsGravitySource * sphericalHarmonicsGravitySource_ptr)
{
   sphericalHarmonicsGravitySource_ptr->name = "Saturn";
   sphericalHarmonicsGravitySource_ptr->mu = 3.7931187e+16;
   sphericalHarmonicsGravitySource_ptr->radius = 1000 * (60268);
}

} // End JEOD namespace
