JEOD: jeod::DynBodyInitTransState Class Reference
jeod::DynBodyInitTransState Class Reference
Initialize aspects of a vehicle's translational state.
#include <dyn_body_init_trans_state.hh>
Public Types
enum StateItems { Both = 0, Position = 1, Velocity = 2 }
Identify which of position/velocity is to be initialized.
Public Member Functions
DynBodyInitTransState ()
Construct a DynBodyInitTransState object.
~DynBodyInitTransState () override
Destructor.
void initialize (DynManager &dyn_manager) override
Initialize aspects of this object and forward the initializer to the immediate parent class.
void apply (DynManager &dyn_manager) override
Apply the initializer.
RefFrameItems::Items initializes_what (void) override
Indicate what parts of the vehicle state this object initializes.
bool is_ready (void) override
Indicate whether this initializer is ready to be applied.
Public Member Functions inherited from jeod::DynBodyInit
DynBodyInit ()
Construct a DynBodyInit.
~DynBodyInit () override
Destruct a DynBodyInit.
virtual void report_failure (void)
Report on an initializer that could not be processed.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()
Construct a BodyAction.
virtual ~BodyAction ()
Destruct a BodyAction.
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier (void) const
Accessor for action_identifier.
Data Fields
StateItems state_items
State items to be initialized – position, velocity, or both.
Data Fields inherited from jeod::DynBodyInit
std::string body_frame_id
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
std::string reference_ref_frame_name
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
RefFrameState state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
double position [3]
Relative position between the subject and reference reference frame origins.
double velocity [3]
Relative velocity between the subject and reference reference frame origins.
Orientation orientation
Relative orientation between the subject and reference reference frame axes.
double ang_velocity [3]
Relative angular velocity between the subject and reference axes.
bool reverse_sense
Indicates how the user input state items are to be interpreted.
bool rate_in_parent
Indicates how the user input angular velocity is to be interpreted.
Data Fields inherited from jeod::BodyAction
bool active
Controls when the action is performed.
bool terminate_on_error
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name
An identifier for this action.
Private Member Functions
DynBodyInitTransState (const DynBodyInitTransState &)
DynBodyInitTransState & operator= (const DynBodyInitTransState &)
Friends
class InputProcessor
void init_attrjeod__DynBodyInitTransState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyInit
void apply_user_inputs (void)
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
void compute_rotational_state (void)
This method is obsolete.
void compute_translational_state (void)
This method is obsolete.
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
DynBody * find_dyn_body (const DynManager &dyn_manager, const std::string &dyn_body_name, const std::string &variable_name)
Find the DynBody with the given name, failing if not found.
RefFrame * find_ref_frame (const DynManager &dyn_manager, const std::string &ref_frame_name, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
BodyRefFrame * find_body_frame (DynBody &frame_container, const std::string &body_frame_identifier, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::DynBodyInit
BodyRefFrame * body_ref_frame
The reference frame whose name is vehicle_name.body_frame_id.
RefFrame * reference_ref_frame
The reference frame whose name is reference_ref_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject
The DynBody of the body that is the subject of this action.
std::string action_identifier
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Initialize aspects of a vehicle's translational state.
Definition at line 83 of file dyn_body_init_trans_state.hh.
Member Enumeration Documentation
StateItems
enum jeod::DynBodyInitTransState::StateItems
Identify which of position/velocity is to be initialized.
Enumerator
Both
Initialize both position and velocity.
Position
Initialize position only.
Velocity
Initialize velocity only.
Definition at line 93 of file dyn_body_init_trans_state.hh.
Constructor & Destructor Documentation
DynBodyInitTransState() [1/2]
jeod::DynBodyInitTransState::DynBodyInitTransState (void)
Construct a DynBodyInitTransState object.
Definition at line 53 of file dyn_body_init_trans_state.cc.
~DynBodyInitTransState()
jeod::DynBodyInitTransState::~DynBodyInitTransState (void) inline override
Destructor.
Definition at line 147 of file dyn_body_init_trans_state.hh.
DynBodyInitTransState() [2/2]
jeod::DynBodyInitTransState::DynBodyInitTransState (const DynBodyInitTransState &) private
Member Function Documentation
apply()
void jeod::DynBodyInitTransState::apply (DynManager & dyn_manager) override virtual
Apply the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 177 of file dyn_body_init_trans_state.cc.
References jeod::DynBodyInit::apply(), and jeod::DynBodyInit::apply_user_inputs().
Referenced by jeod::DynBodyInitOrbit::apply().
initialize()
void jeod::DynBodyInitTransState::initialize (DynManager & dyn_manager) override virtual
Initialize aspects of this object and forward the initializer to the immediate parent class.
This class needs no initialization per se.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 152 of file dyn_body_init_trans_state.cc.
References jeod::BodyAction::action_identifier, Both, jeod::MessageHandler::fail(), jeod::BodyActionMessages::illegal_value, jeod::DynBodyInit::initialize(), Position, state_items, and Velocity.
Referenced by jeod::DynBodyInitOrbit::initialize().
initializes_what()
RefFrameItems::Items jeod::DynBodyInitTransState::initializes_what (void) override virtual
Indicate what parts of the vehicle state this object initializes.
This is depends on the state specified by the user: Both=position and velocity, Position=position, Velocity=velocity.
Returns
States initialized
Reimplemented from jeod::DynBodyInit.
Definition at line 70 of file dyn_body_init_trans_state.cc.
References Both, jeod::RefFrameItems::No_Items, jeod::RefFrameItems::Pos, jeod::RefFrameItems::Pos_Vel, Position, state_items, jeod::RefFrameItems::Vel, and Velocity.
Referenced by is_ready().
is_ready()
bool jeod::DynBodyInitTransState::is_ready (void) override virtual
Indicate whether this initializer is ready to be applied.
The full state of the reference reference frame must be known to compute the position and velocity of the subject reference frame.
Returns
Is initializer ready?
Reimplemented from jeod::DynBodyInit.
Definition at line 98 of file dyn_body_init_trans_state.cc.
References jeod::BodyAction::action_identifier, jeod::RefFrameItems::add(), jeod::RefFrameItems::Att, jeod::RefFrameItems::contains(), jeod::MessageHandler::error(), jeod::RefFrameItems::get(), jeod::RefFrame::get_name(), jeod::BodyRefFrame::initialized_items, initializes_what(), jeod::BodyActionMessages::invalid_object, jeod::DynBodyInit::is_ready(), jeod::RefFrameItems::Rate, jeod::DynBodyInit::reference_ref_frame, jeod::RefFrameItems::set(), and jeod::RefFrameItems::Vel.
operator=()
DynBodyInitTransState& jeod::DynBodyInitTransState::operator= (const DynBodyInitTransState &) private
Friends And Related Function Documentation
init_attrjeod__DynBodyInitTransState
void init_attrjeod__DynBodyInitTransState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 85 of file dyn_body_init_trans_state.hh.
Field Documentation
state_items
StateItems jeod::DynBodyInitTransState::state_items
State items to be initialized – position, velocity, or both.
trick_units(–)
Definition at line 107 of file dyn_body_init_trans_state.hh.
Referenced by initialize(), and initializes_what().
The documentation for this class was generated from the following files:
dyn_body_init_trans_state.hh
dyn_body_init_trans_state.cc