JEOD: jeod::RadiationFacet Class Reference
jeod::RadiationFacet Class Reference abstract
Generic type of facet for radiation pressure.
#include <radiation_facet.hh>
Public Member Functions
RadiationFacet ()=default
~RadiationFacet () override=default
RadiationFacet & operator= (const RadiationFacet &)=delete
RadiationFacet (const RadiationFacet &)=delete
virtual void radiation_pressure ()=0
Calculates the effect of radiation pressure on the facet.
virtual void initialize_geom (double cg[3])=0
Initialize the facet geometry.
void initialize () override
Run sanity checks on input variables.
void define_facet_core (Facet *facet, const ThermalFacetRider &facet_thermal, RadiationParams *params)
Defines the inherent facet values.
ThermalIntegrableObject & get_thermal_integrator ()
Get the integrator for thermal characteristics.
Public Member Functions inherited from jeod::InteractionFacet
InteractionFacet ()=default
virtual ~InteractionFacet ()=default
InteractionFacet & operator= (const InteractionFacet &)=delete
InteractionFacet (const InteractionFacet &)=delete
Public Member Functions inherited from jeod::RadiationBaseFacet
RadiationBaseFacet ()=default
virtual ~RadiationBaseFacet ()=default
RadiationBaseFacet & operator= (const RadiationBaseFacet &)=delete
RadiationBaseFacet (const RadiationBaseFacet &)=delete
virtual void interact_with_third_body (RadiationThirdBody *third_body, const bool calc_forces)
Calculation of force, torques and irradiance due to ThirdBody flux.
virtual void initialize_runtime_values ()
To initialize the values during each update run.
virtual void incident_radiation (const double flux_mag, const double flux_hat[3], const bool calc_forc)=0
Calculates the effect on the facet of the incident radiation.
Data Fields
double crot_to_cp [3] {}
position of center of pressure w.r.t.
double * center_pressure {}
Center of pressure (in structural frame).
Data Fields inherited from jeod::InteractionFacet
double force [3] {}
The force on the facet caused by the environment interaction.
double torque [3] {}
The torque on the facet caused by the environment interaction.
Facet * base_facet {}
The original facet from which this interaction facet was created.
Data Fields inherited from jeod::RadiationBaseFacet
double albedo {-1.0}
Usable value of albedo, set to either albedo_IR or albedo_vis, depending on situation.
double albedo_vis {-1.0}
Fraction of incident visible radiation that is immediately reflected.
double albedo_IR {-1.0}
Fraction of incident IR radiation that is immediately reflected.
double diffuse {-1.0}
Fraction of reflected radiation that is reflected diffusely (balance reflected specularly)
ThermalFacetRider thermal
thermal characteristics of the facet.
double cx_area {}
cross-sectional area projected perpendicular to the radiation vector.
double areaxflux {}
product of momentum flux and cross-sectional area (cx_area).
double areaxflux_e {}
product of energy flux and cross-sectional area
double F_absorption [3] {}
Force due to photon absorption from ONLY ONE source.
double F_specular [3] {}
Force due to photon specular reflection from ONLY ONE source.
double F_diffuse [3] {}
Force due to photon diffuse reflection from ONLY ONE source.
double F_emission [3] {}
Force due to photon (thermal) emission.
Static Protected Attributes
static const double two_thirds = 2.0 / 3.0
quite literally, 2/3.
Static Protected Attributes inherited from jeod::RadiationBaseFacet
static constexpr double speed_of_light {299792458.0}
Speed of light in vacuum.
Friends
class InputProcessor
void init_attrjeod__RadiationFacet ()
Detailed Description
Generic type of facet for radiation pressure.
Definition at line 87 of file radiation_facet.hh.
Constructor & Destructor Documentation
RadiationFacet() [1/2]
jeod::RadiationFacet::RadiationFacet () default
~RadiationFacet()
jeod::RadiationFacet::~RadiationFacet () override default
RadiationFacet() [2/2]
jeod::RadiationFacet::RadiationFacet (const RadiationFacet &) delete
Member Function Documentation
define_facet_core()
void jeod::RadiationFacet::define_facet_core (Facet * facet, const ThermalFacetRider & facet_thermal, RadiationParams * params)
Defines the inherent facet values.
Parameters
[in] facet pointer to the facet
[in] facet_thermal reference to the thermal components of the facet.
[in] params pointer to the list of material parameters for the facet.
Definition at line 86 of file radiation_facet.cc.
References jeod::ThermalFacetRider::active, jeod::RadiationParams::albedo, jeod::RadiationBaseFacet::albedo, jeod::Facet::area, jeod::InteractionFacet::base_facet, jeod::RadiationParams::diffuse, jeod::RadiationBaseFacet::diffuse, jeod::ThermalParams::emissivity, jeod::ThermalFacetRider::emissivity, jeod::ThermalFacetRider::heat_capacity, jeod::ThermalParams::heat_capacity_per_area, jeod::RadiationParams::thermal, jeod::RadiationBaseFacet::thermal, and jeod::ThermalFacetRider::thermal_power_dump.
get_thermal_integrator()
ThermalIntegrableObject& jeod::RadiationFacet::get_thermal_integrator () inline
Get the integrator for thermal characteristics.
Returns
Integrable object that integrates temperature.
Definition at line 144 of file radiation_facet.hh.
References jeod::ThermalFacetRider::integrable_object, and jeod::RadiationBaseFacet::thermal.
initialize()
void jeod::RadiationFacet::initialize () override virtual
Run sanity checks on input variables.
Reimplemented from jeod::RadiationBaseFacet.
Definition at line 56 of file radiation_facet.cc.
References jeod::RadiationBaseFacet::albedo, jeod::RadiationBaseFacet::albedo_IR, jeod::RadiationBaseFacet::albedo_vis, jeod::RadiationBaseFacet::diffuse, jeod::ThermalFacetRider::facet, jeod::MessageHandler::fail(), jeod::RadiationBaseFacet::initialize(), jeod::RadiationMessages::invalid_setup_error, and jeod::RadiationBaseFacet::thermal.
Referenced by jeod::FlatPlateRadiationFacet::initialize_geom().
initialize_geom()
virtual void jeod::RadiationFacet::initialize_geom (double cg[3]) pure virtual
Initialize the facet geometry.
Parameters
cg Center of mass.
Implemented in jeod::FlatPlateRadiationFacet.
Referenced by jeod::RadiationSurface::initialize().
operator=()
RadiationFacet& jeod::RadiationFacet::operator= (const RadiationFacet &) delete
radiation_pressure()
virtual void jeod::RadiationFacet::radiation_pressure () pure virtual
Calculates the effect of radiation pressure on the facet.
Implemented in jeod::FlatPlateRadiationFacet.
Referenced by jeod::RadiationSurface::radiation_pressure().
Friends And Related Function Documentation
init_attrjeod__RadiationFacet
void init_attrjeod__RadiationFacet () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file radiation_facet.hh.
Field Documentation
center_pressure
double* jeod::RadiationFacet::center_pressure {}
Center of pressure (in structural frame).
Potentially variable, depending on the topology of the facet. For a flat plate facet, this just points to the position found in FlatPlatetrick_units(m)
Definition at line 106 of file radiation_facet.hh.
Referenced by jeod::FlatPlateRadiationFacet::define_facet(), and jeod::FlatPlateRadiationFacet::initialize_geom().
crot_to_cp
double jeod::RadiationFacet::crot_to_cp[3] {}
position of center of pressure w.r.t.
center of rotation (usually center of mass, or center of gravity), expressed in structural reference frame. Potentially variable, depending on the topology of the facet and the configuration of the vehicle.trick_units(m)
Definition at line 99 of file radiation_facet.hh.
Referenced by jeod::FlatPlateRadiationFacet::initialize_geom(), and jeod::FlatPlateRadiationFacet::radiation_pressure().
two_thirds
const double jeod::RadiationFacet::two_thirds = 2.0 / 3.0 static protected
quite literally, 2/3.
Occurs frequently with diffuse reflection and emission, so it is calculated once.trick_io(*o) trick_units(–)
Definition at line 115 of file radiation_facet.hh.
Referenced by jeod::FlatPlateRadiationFacet::incident_radiation(), and jeod::FlatPlateRadiationFacet::radiation_pressure().
The documentation for this class was generated from the following files:
radiation_facet.hh
radiation_facet.cc