JEOD: jeod::PlanetRNP Class Reference
jeod::PlanetRNP Class Reference abstract
The generic framework for orientation models based on the RNP paradigm.
#include <planet_rnp.hh>
Public Types
enum RNPFidelity { FullRNP = 0, RotationOnly = 1, ConstantNP = 2 }
Specifies the initialization fidelity of the RNP model.
Public Member Functions
PlanetRNP ()
Default constructor; constructs a PlanetRNP object.
~PlanetRNP () override
Class destructor.
void update_rnp ()
Invokes the calculation for all rotation models contained in the RNP, used on the last time set in each model through PlanetRotation::set_time.
void update_axial_rotation ()
Same as update_rnp, but only the axial_rotation will be updated.
void propagate_rnp ()
Multiples out the (up to) four planet rotation models (nutation, precession, polar motion and rotation), leaving out models whose pointers are NULL, and feeds it to the planet attitude found in the dyn manager given in initialize.
const char * get_name () const override=0
A re-declaration of the pure virtual function in order to convince trick that yes, this is a pure virtual class.
Public Member Functions inherited from jeod::PlanetOrientation
PlanetOrientation ()
Default constructor; constructs a PlanetOrientation object.
~PlanetOrientation () override
Class destructor.
virtual void initialize (DynManager &dyn_manager)
Goes to the dyn manager given and searches for the planet indicated by the user inputted name, in the given dyn manager.
void activate () override
Activates the PlanetOrientation model.
void deactivate () override
Deactivates the PlanetOrientation model.
void ephem_initialize (EphemeridesManager &manager) override
Implements the EphemInterface pure virtual function ephem_initialize.
void ephem_activate (EphemeridesManager &manager) override
Mark the model as being activate or inactive.
void ephem_build_tree (EphemeridesManager &manager) override
Function, for a particular ephemeris model, nominally builds the particular models portions of the reference frame tree.
void set_name (std::string name_in)
Setter for the name.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
virtual double timestamp (void) const =0
Indicates when class was last updated.
virtual void ephem_update (void)=0
Update the model.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Data Fields
PlanetRotation * nutation
Pointer to the nutation model.
PlanetRotation * precession
Pointer to the precession model.
PlanetRotation * polar_motion
Pointer to the polar_motion model.
PlanetRotation * rotation
Pointer to the rotation model.
RNPFidelity rnp_type
The fidelity of the RNP model.
bool enable_polar
Gives the option of turning on or off polar motion.
double NP_matrix [3][3]
Rotation Matrix representing: transpose(nutation->rotation) * transpose(precession->rotation)
Data Fields inherited from jeod::PlanetOrientation
bool active
Is the orientation model actively updating? Defaults to true.
Planet * planet
The planet the attitude model will be working on.
std::string name
Name of the planet the attitude model will be working on.
RefFrameRot * planet_rot_state
The current rotational state of the planet.
double planet_omega
Nominal axial velocity of the earth.
EphemerisOrientation orient_interface
The ephemeris interface to the in question orientation.
Protected Attributes
double scratch_matrix [3][3]
A transformation matrix used for intermediate math steps.
Private Member Functions
PlanetRNP & operator= (const PlanetRNP &rhs)
Not implemented.
PlanetRNP (const PlanetRNP &rhs)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__PlanetRNP ()
Detailed Description
The generic framework for orientation models based on the RNP paradigm.
Definition at line 104 of file planet_rnp.hh.
Member Enumeration Documentation
RNPFidelity
enum jeod::PlanetRNP::RNPFidelity
Specifies the initialization fidelity of the RNP model.
Enumerator
FullRNP
Full fidelity RNP matrix. Formerly Full_Term_RNP.
RotationOnly
Identity NP matrix, then rotation calculates linearly.
ConstantNP
Once calculated NP matrix (at the start), then rotation.
Definition at line 115 of file planet_rnp.hh.
Constructor & Destructor Documentation
PlanetRNP() [1/2]
jeod::PlanetRNP::PlanetRNP (void)
Default constructor; constructs a PlanetRNP object.
Definition at line 72 of file planet_rnp.cc.
References jeod::Matrix3x3::initialize(), and NP_matrix.
~PlanetRNP()
jeod::PlanetRNP::~PlanetRNP (void) override
Class destructor.
Definition at line 88 of file planet_rnp.cc.
PlanetRNP() [2/2]
jeod::PlanetRNP::PlanetRNP (const PlanetRNP & rhs) private
Not implemented.
Member Function Documentation
get_name()
const char* jeod::PlanetRNP::get_name () const override pure virtual
A re-declaration of the pure virtual function in order to convince trick that yes, this is a pure virtual class.
Returns
Planet name.
Implements jeod::PlanetOrientation.
Implemented in jeod::RNPMars, and jeod::RNPJ2000.
operator=()
PlanetRNP& jeod::PlanetRNP::operator= (const PlanetRNP & rhs) private
Not implemented.
propagate_rnp()
void jeod::PlanetRNP::propagate_rnp (void)
Multiples out the (up to) four planet rotation models (nutation, precession, polar motion and rotation), leaving out models whose pointers are NULL, and feeds it to the planet attitude found in the dyn manager given in initialize.
Definition at line 201 of file planet_rnp.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_quaternion(), ConstantNP, enable_polar, jeod::MessageHandler::fail(), jeod::RNPMessages::fidelity_error, FullRNP, NP_matrix, jeod::PlanetOrientation::planet_omega, jeod::PlanetOrientation::planet_rot_state, polar_motion, jeod::Matrix3x3::product(), jeod::Matrix3x3::product_transpose_transpose(), rnp_type, jeod::PlanetRotation::rotation, rotation, RotationOnly, scratch_matrix, jeod::RNPMessages::setup_error, jeod::RefFrameRot::T_parent_this, and jeod::Matrix3x3::transpose().
Referenced by update_axial_rotation(), and update_rnp().
update_axial_rotation()
void jeod::PlanetRNP::update_axial_rotation (void)
Same as update_rnp, but only the axial_rotation will be updated.
Definition at line 173 of file planet_rnp.cc.
References jeod::MessageHandler::fail(), propagate_rnp(), rotation, jeod::RNPMessages::setup_error, and jeod::PlanetRotation::update_rotation().
Referenced by jeod::RNPJ2000::ephem_update(), jeod::RNPMars::ephem_update(), jeod::RNPJ2000::update_axial_rotation(), and jeod::RNPMars::update_axial_rotation().
update_rnp()
void jeod::PlanetRNP::update_rnp (void)
Invokes the calculation for all rotation models contained in the RNP, used on the last time set in each model through PlanetRotation::set_time.
Then multiplies out and updates the attitude of the planet found during initialization.
Definition at line 102 of file planet_rnp.cc.
References enable_polar, jeod::MessageHandler::fail(), jeod::RNPMessages::fidelity_error, FullRNP, NP_matrix, nutation, polar_motion, precession, jeod::Matrix3x3::product_transpose_transpose(), propagate_rnp(), rnp_type, jeod::PlanetRotation::rotation, rotation, jeod::RNPMessages::setup_error, and jeod::PlanetRotation::update_rotation().
Referenced by jeod::RNPJ2000::update_rnp(), and jeod::RNPMars::update_rnp().
Friends And Related Function Documentation
init_attrjeod__PlanetRNP
void init_attrjeod__PlanetRNP () friend
InputProcessor
friend class InputProcessor friend
Definition at line 106 of file planet_rnp.hh.
Field Documentation
enable_polar
bool jeod::PlanetRNP::enable_polar
Gives the option of turning on or off polar motion.
trick_units(–)
Definition at line 153 of file planet_rnp.hh.
Referenced by propagate_rnp(), jeod::RNPMars::RNPMars(), jeod::RNPJ2000::update_rnp(), and update_rnp().
NP_matrix
double jeod::PlanetRNP::NP_matrix[3][3]
Rotation Matrix representing: transpose(nutation->rotation) * transpose(precession->rotation)
trick_units(–)
Definition at line 159 of file planet_rnp.hh.
Referenced by PlanetRNP(), propagate_rnp(), and update_rnp().
nutation
PlanetRotation* jeod::PlanetRNP::nutation
Pointer to the nutation model.
trick_units(–)
Definition at line 132 of file planet_rnp.hh.
Referenced by jeod::RNPJ2000::RNPJ2000(), jeod::RNPMars::RNPMars(), jeod::RNPJ2000::update_rnp(), update_rnp(), and jeod::RNPMars::update_rnp().
polar_motion
PlanetRotation* jeod::PlanetRNP::polar_motion
Pointer to the polar_motion model.
trick_units(–)
Definition at line 140 of file planet_rnp.hh.
Referenced by propagate_rnp(), jeod::RNPJ2000::RNPJ2000(), jeod::RNPMars::RNPMars(), jeod::RNPJ2000::update_rnp(), and update_rnp().
precession
PlanetRotation* jeod::PlanetRNP::precession
Pointer to the precession model.
trick_units(–)
Definition at line 136 of file planet_rnp.hh.
Referenced by jeod::RNPJ2000::RNPJ2000(), jeod::RNPMars::RNPMars(), jeod::RNPJ2000::update_rnp(), update_rnp(), and jeod::RNPMars::update_rnp().
rnp_type
RNPFidelity jeod::PlanetRNP::rnp_type
The fidelity of the RNP model.
trick_units(–)
Definition at line 149 of file planet_rnp.hh.
Referenced by jeod::RNPJ2000::initialize(), jeod::RNPMars::initialize(), propagate_rnp(), jeod::RNPJ2000::update_axial_rotation(), jeod::RNPMars::update_axial_rotation(), jeod::RNPJ2000::update_rnp(), update_rnp(), and jeod::RNPMars::update_rnp().
rotation
PlanetRotation* jeod::PlanetRNP::rotation
Pointer to the rotation model.
trick_units(–)
Definition at line 144 of file planet_rnp.hh.
Referenced by propagate_rnp(), jeod::RNPJ2000::RNPJ2000(), jeod::RNPMars::RNPMars(), jeod::RNPJ2000::update_axial_rotation(), update_axial_rotation(), jeod::RNPMars::update_axial_rotation(), jeod::RNPJ2000::update_rnp(), update_rnp(), and jeod::RNPMars::update_rnp().
scratch_matrix
double jeod::PlanetRNP::scratch_matrix[3][3] protected
A transformation matrix used for intermediate math steps.
trick_units(–)
Definition at line 166 of file planet_rnp.hh.
Referenced by propagate_rnp().
The documentation for this class was generated from the following files:
planet_rnp.hh
planet_rnp.cc