JEOD: jeod::BaseDynManager Class Reference
jeod::BaseDynManager Class Reference abstract
The DynManager class augments the EphemManager with dynamics-related items.
#include <base_dyn_manager.hh>
Public Member Functions
~BaseDynManager () override=default
virtual void set_gravity_manager (GravityManager &gravity)=0
Set the Gravity Manager.
virtual void initialize_gravity_controls ()=0
Initialize the gravity model controls.
virtual void reset_gravity_controls ()=0
Reset the gravity model controls.
virtual void add_mass_body (MassBody &mass_body)=0
Add a mass body to the list of such.
virtual void add_mass_body (MassBody *mass_body)=0
Add a mass body to the list of such.
virtual MassBody * find_mass_body (const std::string &name) const =0
Find a mass body.
virtual bool is_mass_body_registered (const MassBody *mass_body) const =0
Check if a mass body has been registered with the dynamics manager.
virtual void add_dyn_body (DynBody &dyn_body)=0
Add a dynamic body to the list of such.
virtual DynBody * find_dyn_body (const std::string &name) const =0
Find a dynamic body.
virtual std::vector< DynBody * > get_dyn_bodies () const =0
Return a copy of the list of registered dynamic bodies.
virtual bool is_dyn_body_registered (const DynBody *dyn_body) const =0
Check if a dynamic body has been registered with the dynamics manager.
virtual void add_integ_group (DynamicsIntegrationGroup &integ_group)=0
Add an integration group to the list of such.
virtual bool is_integ_group_registered (const DynamicsIntegrationGroup *integ_group) const =0
Check if an integration group has been registered.
virtual void reset_integrators ()=0
Force all integrators to reset themselves.
virtual void reset_integrators (DynamicsIntegrationGroup &integ_group)=0
Instruct specific integration group to reset its integrators.
virtual double timestamp () const =0
Get the time at which the manager was last updated.
Public Member Functions inherited from jeod::BaseEphemeridesManager
~BaseEphemeridesManager () override=default
Destructor.
virtual void ephem_note_tree_status_change ()=0
Denote that the tree needs to be rebuilt.
virtual void add_planet (BasePlanet &planet)=0
Add a planet to the list of such.
virtual void add_planet (Planet &planet)=0
Add a planet to the list of such.
virtual BasePlanet * find_base_planet (const std::string &name) const =0
Find a planet.
virtual Planet * find_planet (const std::string &name) const =0
Find a planet.
virtual unsigned int get_num_planets () const =0
Return number of registered planets.
virtual void add_ephemeris (EphemerisInterface &ephem_if)=0
Add an ephemeris model to the list of such.
virtual void clear_added_ephemerides ()=0
Deactivate all registered ephemeris models.
virtual void disable_add_ephemeris ()=0
Disable registration of new ephemeris models.
virtual void add_ephem_item (EphemerisItem &ephem_item)=0
Add an ephemeris item to the list of such.
virtual EphemerisItem * find_ephem_item (const std::string &name) const =0
Find an ephemeris item.
virtual EphemerisOrientation * find_ephem_angle (const std::string &name) const =0
Find an ephemeris orientation.
virtual EphemerisPoint * find_ephem_point (const std::string &name) const =0
Find an ephemeris point.
virtual void add_integ_frame (EphemerisRefFrame &ref_frame)=0
Add an integration frame to the list of such.
virtual EphemerisRefFrame * find_integ_frame (const std::string &name) const =0
Find an integration frame.
virtual bool is_integ_frame (const RefFrame &ref_frame) const =0
Check whether a reference frame is an integration frame.
virtual unsigned int find_integ_frame_index (const EphemerisRefFrame &ref_frame) const =0
Find a reference frame's index in the list of integration frames.
virtual const std::vector< EphemerisRefFrame * > & get_integ_frames () const =0
Get the vector of integration frames.
Public Member Functions inherited from jeod::BaseRefFrameManager
virtual ~BaseRefFrameManager ()=default
Destructor.
virtual void add_ref_frame (RefFrame &ref_frame)=0
Add a reference frame to the list of such.
virtual void remove_ref_frame (RefFrame &ref_frame)=0
Remove a reference frame from the list of such.
virtual RefFrame * find_ref_frame (const std::string &name) const =0
Find a reference frame.
virtual RefFrame * find_ref_frame (const std::string &prefix, const std::string &suffix) const =0
Find a reference frame.
virtual void check_ref_frame_ownership () const =0
Check whether each reference frame has an owner.
virtual void reset_tree_root_node ()=0
Reset the root node in anticipation of rebuilding the entire tree.
virtual void add_frame_to_tree (RefFrame &ref_frame, RefFrame *parent)=0
Add a reference frame to the reference frame tree.
virtual void subscribe_to_frame (const std::string &frame_name)=0
Add a subscription to a reference frame.
virtual void subscribe_to_frame (RefFrame &frame)=0
Add a subscription to a reference frame.
virtual void unsubscribe_to_frame (const std::string &frame_name)=0
Remove a subscription from a reference frame.
virtual void unsubscribe_to_frame (RefFrame &frame)=0
Remove a subscription from a reference frame.
virtual bool frame_is_subscribed (const std::string &frame_name)=0
Check whether a reference frame has subscriptions.
virtual bool frame_is_subscribed (RefFrame &frame)=0
Check whether a reference frame has subscriptions.
Friends
class InputProcessor
void init_attrjeod__BaseDynManager ()
Detailed Description
The DynManager class augments the EphemManager with dynamics-related items.
This class defines the external interfaces to that class.
Definition at line 81 of file base_dyn_manager.hh.
Constructor & Destructor Documentation
~BaseDynManager()
jeod::BaseDynManager::~BaseDynManager () override default
Member Function Documentation
add_dyn_body()
virtual void jeod::BaseDynManager::add_dyn_body (DynBody & dyn_body) pure virtual
Add a dynamic body to the list of such.
Parameters
dyn_body Body to be added to the list of dynamic bodies.
Implemented in jeod::DynManager.
Referenced by jeod::DynBody::initialize_model().
add_integ_group()
virtual void jeod::BaseDynManager::add_integ_group (DynamicsIntegrationGroup & integ_group) pure virtual
Add an integration group to the list of such.
Parameters
integ_group Group to be added to the list of integration groups.
Implemented in jeod::DynManager.
add_mass_body() [1/2]
virtual void jeod::BaseDynManager::add_mass_body (MassBody & mass_body) pure virtual
Add a mass body to the list of such.
Parameters
mass_body Body to be added to the list of mass bodies.
Implemented in jeod::DynManager.
add_mass_body() [2/2]
virtual void jeod::BaseDynManager::add_mass_body (MassBody * mass_body) pure virtual
Add a mass body to the list of such.
Parameters
mass_body Body to be added to the list of mass bodies.
Implemented in jeod::DynManager.
find_dyn_body()
virtual DynBody* jeod::BaseDynManager::find_dyn_body (const std::string & name) const pure virtual
Find a dynamic body.
Parameters
name Dynamic body name.
Returns
Pointer to the dynamic body with the given name.
Implemented in jeod::DynManager.
Referenced by jeod::DynBody::add_mass_body_validate(), jeod::MassBody::attach_validate_child(), jeod::MassBody::attach_validate_parent(), jeod::MassBody::detach_validate_child(), and jeod::MassBody::detach_validate_parent().
find_mass_body()
virtual MassBody* jeod::BaseDynManager::find_mass_body (const std::string & name) const pure virtual
Find a mass body.
Parameters
name Mass body name.
Returns
Pointer to the mass body with the given name.
Implemented in jeod::DynManager.
Referenced by jeod::Facet::initialize_mass_connection(), and jeod::SurfaceModel::initialize_mass_connections().
get_dyn_bodies()
virtual std::vector<DynBody *> jeod::BaseDynManager::get_dyn_bodies () const pure virtual
Return a copy of the list of registered dynamic bodies.
Returns
Copy of dyn_bodies data member
Implemented in jeod::DynManager.
initialize_gravity_controls()
virtual void jeod::BaseDynManager::initialize_gravity_controls () pure virtual
Initialize the gravity model controls.
Implemented in jeod::DynManager.
is_dyn_body_registered()
virtual bool jeod::BaseDynManager::is_dyn_body_registered (const DynBody * dyn_body) const pure virtual
Check if a dynamic body has been registered with the dynamics manager.
Parameters
dyn_body Dynamic body to be checked.
Returns
True if the body is registered, false otherwise.
Implemented in jeod::DynManager.
Referenced by jeod::DynBody::add_mass_point(), and jeod::DynBody::attach_validate_parent().
is_integ_group_registered()
virtual bool jeod::BaseDynManager::is_integ_group_registered (const DynamicsIntegrationGroup * integ_group) const pure virtual
Check if an integration group has been registered.
Parameters
integ_group Integration group to be checked.
Returns
True if the group is registered, false otherwise.
Implemented in jeod::DynManager.
is_mass_body_registered()
virtual bool jeod::BaseDynManager::is_mass_body_registered (const MassBody * mass_body) const pure virtual
Check if a mass body has been registered with the dynamics manager.
Parameters
mass_body Mass body to be checked.
Returns
True if the body is registered, false otherwise.
Implemented in jeod::DynManager.
reset_gravity_controls()
virtual void jeod::BaseDynManager::reset_gravity_controls () pure virtual
Reset the gravity model controls.
Implemented in jeod::DynManager.
reset_integrators() [1/2]
virtual void jeod::BaseDynManager::reset_integrators () pure virtual
Force all integrators to reset themselves.
Implemented in jeod::DynManager.
reset_integrators() [2/2]
virtual void jeod::BaseDynManager::reset_integrators (DynamicsIntegrationGroup & integ_group) pure virtual
Instruct specific integration group to reset its integrators.
Parameters
integ_group Integration group to be reset.
Implemented in jeod::DynManager.
set_gravity_manager()
virtual void jeod::BaseDynManager::set_gravity_manager (GravityManager & gravity) pure virtual
Set the Gravity Manager.
Parameters
gravity link to the manager of gravity model.
Implemented in jeod::DynManager.
Referenced by jeod::GravityManager::initialize_model().
timestamp()
virtual double jeod::BaseDynManager::timestamp () const pure virtual
Get the time at which the manager was last updated.
Returns
Time at which the manager was last updated.
Implemented in jeod::DynManager.
Friends And Related Function Documentation
init_attrjeod__BaseDynManager
void init_attrjeod__BaseDynManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file base_dyn_manager.hh.
The documentation for this class was generated from the following file:
base_dyn_manager.hh