JEOD: jeod::DynBodyPendulumConstraint Class Reference
jeod::DynBodyPendulumConstraint Class Reference
#include <dyn_body_pendulum_constraint.hh>
Public Member Functions
DynBodyPendulumConstraint (BasePendulumModel *pendulum_model=nullptr)
Default constructor.
~DynBodyPendulumConstraint () override=default
Destructor.
void activate () override
Activate the constraint.
void deactivate () override
Deactivate the constraint.
const Wrench & get_effector_wrench () const override
Get the known wrench for this constrained object.
const Wrench & get_constraint_wrench () const override
Get the wrench this constrained object exerts on the vehicle.
const Wrench & get_nonlinear_response_wrench () const override
Get the residual nonlinear wrench for this constrained object.
ConstraintComponent * get_component (unsigned index) override
Get the indexed component constraint for this composite constraint.
void update_attachment (const VehicleProperties &vehicle_properties) override
Update information about the relation between this constraint and the root DynBody.
void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state) override
Prepare this object for solving a constraint problem.
bool check_for_reset ()
Determine whether the integrator needs to be reset, which occurs on transition between modes.
void reset_quiescent ()
Trigger that the pendulum should be set to its quiescent vertical state,.
void set_transition_points (double new_cos_sq_theta_angular, double new_cos_sq_theta_cartesian)
Set the points at which the transitions from Cartesian to angular and angular to Cartesian representations occur.
const double * get_bob_position () const
Getter for the bob position.
Public Member Functions inherited from jeod::DynBodyConstraint
DynBodyConstraint ()=default
virtual ~DynBodyConstraint ()
Destructor.
DynBodyConstraint (const DynBodyConstraint &)=delete
DynBodyConstraint & operator= (const DynBodyConstraint &)=delete
bool is_active () const
Is the constraint active?
virtual const DynBodyConstraintsSolver * get_solver () const
Get the solver for this constrained object.
virtual void set_struct_to_constraint_frame (SolverTypes::ConstDecayedMatrix3x3T transform_in, SolverTypes::ConstDecayedVector3T offset_in)
Set the relationship between the constraint frame and the immediate structural frame.
void update_component_attachment (const VehicleProperties &vehicle_properties)
Send update_attachment to each component.
void setup_component_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Send setup_constraint to each component.
virtual const ConstraintComponent * get_component (unsigned index) const
Const version of get_component().
virtual void set_r_h_s (jeod::VectorView< double > &rhs_slice) const
Set the sum of the terms in the constraint equation that don't involve other constrained objects, expressed as the right hand side of the constraint equation.
virtual void set_r_h_s (jeod::VectorView< double > &&rhs_slice) const
So one can use set_r_h_s with a temporary.
virtual void set_cross_coeff (const VehicleProperties &vehicle_properties, const DynBodyConstraint &other, jeod::MatrixView< double > &a_slice) const
Set the constraint matrix elements that pertain to this constrained object with respect to some other constrained object.
virtual void set_cross_coeff (const VehicleProperties &vehicle_properties, const DynBodyConstraint &other, jeod::MatrixView< double > &&a_slice) const
So one can call set_cross_coeff with a temporary.
virtual void set_self_coeff (const VehicleProperties &vehicle_properties, jeod::MatrixView< double > &a_slice) const
Set the constraint matrix elements for this constraint object with respect to itself.
virtual void set_self_coeff (const VehicleProperties &vehicle_properties, jeod::MatrixView< double > &&a_slice) const
So one can call set_self_coeff with a temporary.
virtual void set_constraint_values (const jeod::VectorView< double, double > &solution_slice)
Set this constrained object's constraint values.
virtual void compute_constraint_response (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
Protected Attributes
ConstrainedPointMass constrained_mass
The pendulum as a constrained mass.
PendulumConstraintComponent pendulum_component
The pendulum as a component of this constraint.
Protected Attributes inherited from jeod::DynBodyConstraint
ConstraintFrame constraint_frame
The reference frame associated with this constraint.
DynBodyConstraintsSolver * solver {}
The solver to which this constraint is assigned.
unsigned n_dimensions {}
The number of active components associated with this constraint.
bool inactive {}
Is the constraint inactive? Note: This is expressed in the negative sense to support reduced Trick checkpointing.
Friends
class InputProcessor
void init_attrjeod__DynBodyPendulumConstraint ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyConstraint
virtual void attach_to_solver ()
Perform actions related to the just-performed addition of this constraint to a constraints solver.
virtual void detach_from_solver ()
Perform actions related to the just-performed removal of this constraint from a constraints solver.
virtual DynBody * get_dyn_body ()
Get the dyn_body object associated with this constrained object.
Detailed Description
Definition at line 72 of file dyn_body_pendulum_constraint.hh.
Constructor & Destructor Documentation
DynBodyPendulumConstraint()
jeod::DynBodyPendulumConstraint::DynBodyPendulumConstraint (BasePendulumModel * pendulum_model = nullptr) inline
Default constructor.
Constructs a DynBodyPendulumConstraint modeled by the supplied model.
Parameters
pendulum_model Pointer to the object that models pendulum parameters. The default null pointer should only be used for for simulation checkpoint/restart.
Definition at line 82 of file dyn_body_pendulum_constraint.hh.
References jeod::DynBodyConstraint::n_dimensions.
~DynBodyPendulumConstraint()
jeod::DynBodyPendulumConstraint::~DynBodyPendulumConstraint () override default
Destructor.
Member Function Documentation
activate()
void jeod::DynBodyPendulumConstraint::activate () override virtual
Activate the constraint.
Reimplemented from jeod::DynBodyConstraint.
Definition at line 23 of file dyn_body_pendulum_constraint.cc.
References jeod::DynBodyConstraint::activate(), jeod::PendulumConstraintComponent::activate(), jeod::DynBodyConstraint::inactive, and pendulum_component.
check_for_reset()
bool jeod::DynBodyPendulumConstraint::check_for_reset () inline
Determine whether the integrator needs to be reset, which occurs on transition between modes.
This should be called as a scheduled job at the dynamics rate.
Definition at line 184 of file dyn_body_pendulum_constraint.hh.
References jeod::PendulumConstraintComponent::check_for_reset(), and pendulum_component.
deactivate()
void jeod::DynBodyPendulumConstraint::deactivate () override virtual
Deactivate the constraint.
Reimplemented from jeod::DynBodyConstraint.
Definition at line 33 of file dyn_body_pendulum_constraint.cc.
References jeod::DynBodyConstraint::deactivate(), jeod::PendulumConstraintComponent::deactivate(), jeod::DynBodyConstraint::inactive, and pendulum_component.
get_bob_position()
const double* jeod::DynBodyPendulumConstraint::get_bob_position () const inline
Getter for the bob position.
Definition at line 209 of file dyn_body_pendulum_constraint.hh.
References jeod::PendulumConstraintComponent::get_bob_position(), and pendulum_component.
get_component()
ConstraintComponent* jeod::DynBodyPendulumConstraint::get_component (unsigned index) inline override virtual
Get the indexed component constraint for this composite constraint.
Parameters
index Index of the component constraint to be retrieved. This is not bounds-checked.
Returns
The indexed component constraint.
Implements jeod::DynBodyConstraint.
Definition at line 145 of file dyn_body_pendulum_constraint.hh.
References pendulum_component.
get_constraint_wrench()
const Wrench& jeod::DynBodyPendulumConstraint::get_constraint_wrench () const inline override virtual
Get the wrench this constrained object exerts on the vehicle.
Returns
A const reference to the constraint wrench for this object.
Note
This function is called after the constraint values have been set.
Implements jeod::DynBodyConstraint.
Definition at line 122 of file dyn_body_pendulum_constraint.hh.
References jeod::ConstraintComponent::get_constraint_wrench(), and pendulum_component.
get_effector_wrench()
const Wrench& jeod::DynBodyPendulumConstraint::get_effector_wrench () const inline override virtual
Get the known wrench for this constrained object.
Returns
A const reference to the effector wrench for this object.
Note
This function is called prior to any calls to setup_constraint(), with the effects of all of the pre-constraint wrenches incorporated into the non_grav_state argument to that function.
Implements jeod::DynBodyConstraint.
Definition at line 112 of file dyn_body_pendulum_constraint.hh.
References jeod::PendulumConstraintComponent::get_effector_wrench(), and pendulum_component.
get_nonlinear_response_wrench()
const Wrench& jeod::DynBodyPendulumConstraint::get_nonlinear_response_wrench () const inline override virtual
Get the residual nonlinear wrench for this constrained object.
Returns
A const reference to the nonlinear wrench for this object.
Note
This function is called after calls to compute_constraint_response. The nonlinear aspects are assumed to be small; they are not taken into account while solving the constraints equation.
Implements jeod::DynBodyConstraint.
Definition at line 134 of file dyn_body_pendulum_constraint.hh.
References jeod::PendulumConstraintComponent::get_nonlinear_response_wrench(), and pendulum_component.
reset_quiescent()
void jeod::DynBodyPendulumConstraint::reset_quiescent () inline
Trigger that the pendulum should be set to its quiescent vertical state,.
Definition at line 192 of file dyn_body_pendulum_constraint.hh.
References pendulum_component, and jeod::PendulumConstraintComponent::reset_quiescent().
set_transition_points()
void jeod::DynBodyPendulumConstraint::set_transition_points (double new_cos_sq_theta_angular, double new_cos_sq_theta_cartesian) inline
Set the points at which the transitions from Cartesian to angular and angular to Cartesian representations occur.
Definition at line 201 of file dyn_body_pendulum_constraint.hh.
References pendulum_component, and jeod::PendulumConstraintComponent::set_transition_points().
setup_constraint()
void jeod::DynBodyPendulumConstraint::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) inline override virtual
Prepare this object for solving a constraint problem.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to non-constraint forces and torques, including the pre-constraint wrenches.
Note
This function is called prior to the calls to set_self_coeff(), set_cross_coeff(), and set_r_h_s().
Implements jeod::DynBodyConstraint.
Definition at line 172 of file dyn_body_pendulum_constraint.hh.
References constrained_mass, pendulum_component, jeod::PendulumConstraintComponent::setup_constraint(), and jeod::ConstrainedPointMass::setup_constraint().
update_attachment()
void jeod::DynBodyPendulumConstraint::update_attachment (const VehicleProperties & vehicle_properties) inline override virtual
Update information about the relation between this constraint and the root DynBody.
Parameters
vehicle_properties Various vehicle properties.
Reimplemented from jeod::DynBodyConstraint.
Definition at line 156 of file dyn_body_pendulum_constraint.hh.
References constrained_mass, pendulum_component, jeod::ConstraintComponent::update_attachment(), jeod::ConstrainedPointMass::update_attachment(), and jeod::DynBodyConstraint::update_attachment().
Friends And Related Function Documentation
init_attrjeod__DynBodyPendulumConstraint
void init_attrjeod__DynBodyPendulumConstraint () friend
InputProcessor
friend class InputProcessor friend
Definition at line 74 of file dyn_body_pendulum_constraint.hh.
Field Documentation
constrained_mass
ConstrainedPointMass jeod::DynBodyPendulumConstraint::constrained_mass protected
The pendulum as a constrained mass.
Definition at line 218 of file dyn_body_pendulum_constraint.hh.
Referenced by setup_constraint(), and update_attachment().
pendulum_component
PendulumConstraintComponent jeod::DynBodyPendulumConstraint::pendulum_component protected
The pendulum as a component of this constraint.
Definition at line 223 of file dyn_body_pendulum_constraint.hh.
Referenced by activate(), check_for_reset(), deactivate(), get_bob_position(), get_component(), get_constraint_wrench(), get_effector_wrench(), get_nonlinear_response_wrench(), reset_quiescent(), set_transition_points(), setup_constraint(), and update_attachment().
The documentation for this class was generated from the following files:
dyn_body_pendulum_constraint.hh
dyn_body_pendulum_constraint.cc