JEOD: jeod::RadiationSurface Class Reference
jeod::RadiationSurface Class Reference
The surface of the vehicle that interacts with the incident flux.
#include <radiation_surface.hh>
Public Member Functions
RadiationSurface ()
Constructor for RadiationSurface.
~RadiationSurface () override
Destructor for RadiationSurface.
RadiationSurface & operator= (const RadiationSurface &)=delete
RadiationSurface (const RadiationSurface &)=delete
void initialize (double center_grav[3])
Initializes the radiation surface.
void allocate_array (unsigned int size) override
Allocates memory for an array of radiation facets.
void allocate_interaction_facet (Facet *facet, InteractionFacetFactory *factory, FacetParams *params, unsigned int index) override
Turns facet memory into radiaiton facet memory.
void initialize_runtime_values ()
To initialize the values during each update run.
void incident_radiation (double flux_mag, const double flux_struc_hat[3], bool calculate_forces)
systematically calls the method to calculate the interaction on each facet.
void interact_with_third_body (RadiationThirdBody *third_body_ptr, const bool calculate_forces)
systematically calls the method to calculate the interaction of each facet with ThirdBody flux.
void accumulate_thermal_sources () override
systematically calls the method to accumulate thermal sources on each facet.
void thermal_integrator () override
systematically calls the method to integrate the temperature variation for each facet.
void equalize_absorption_emission ()
systematically calls the method to ensure that the same for each facet.
void radiation_pressure ()
systematically calls the method to wrap up the radiation pressure calculation on each facet and accumulate forces and torques over all facets.
void add_thermal_integrators_to (DynBody *dyn_body)
To attach thermal integrators from each facet to the integration group of a DynBody.
Public Member Functions inherited from jeod::InteractionSurface
InteractionSurface ()=default
virtual ~InteractionSurface ()=default
InteractionSurface & operator= (const InteractionSurface &)=delete
InteractionSurface (const InteractionSurface &)=delete
Data Fields
RadiationFacet ** facets {}
Array of pointers to the Radiation Facets.
unsigned int num_facets {}
number of facets in this surface.
bool include_conduction {}
Flag to instruct model to include conduction between plates in the thermal calculation.
double ** thermal_conduction {}
Conductivity values (Watts per Kelvin) between facets.
double force [3] {}
Force resulting from all radiative interactions.
double torque [3] {}
Torque resulting from all radiative interactions.
unsigned int ii_facet {}
Simple counter, used repeatedly.
Friends
class InputProcessor
void init_attrjeod__RadiationSurface ()
Detailed Description
The surface of the vehicle that interacts with the incident flux.
Definition at line 88 of file radiation_surface.hh.
Constructor & Destructor Documentation
RadiationSurface() [1/2]
jeod::RadiationSurface::RadiationSurface ()
Constructor for RadiationSurface.
Definition at line 60 of file radiation_surface.cc.
References JEOD_REGISTER_INCOMPLETE_CLASS.
~RadiationSurface()
jeod::RadiationSurface::~RadiationSurface () override
Destructor for RadiationSurface.
Definition at line 337 of file radiation_surface.cc.
References facets, JEOD_DELETE_2D, and num_facets.
RadiationSurface() [2/2]
jeod::RadiationSurface::RadiationSurface (const RadiationSurface &) delete
Member Function Documentation
accumulate_thermal_sources()
void jeod::RadiationSurface::accumulate_thermal_sources () override virtual
systematically calls the method to accumulate thermal sources on each facet.
Reimplemented from jeod::InteractionSurface.
Definition at line 255 of file radiation_surface.cc.
References jeod::ThermalFacetRider::accumulate_thermal_sources(), facets, ii_facet, num_facets, and jeod::RadiationBaseFacet::thermal.
add_thermal_integrators_to()
void jeod::RadiationSurface::add_thermal_integrators_to (DynBody * dyn_body)
To attach thermal integrators from each facet to the integration group of a DynBody.
Parameters
[in,out] dyn_body Body to which integrators are to be added.
Definition at line 325 of file radiation_surface.cc.
References jeod::ThermalIntegrableObject::active, jeod::DynBody::add_integrable_object(), facets, jeod::ThermalFacetRider::integrable_object, num_facets, and jeod::RadiationBaseFacet::thermal.
allocate_array()
void jeod::RadiationSurface::allocate_array (unsigned int size) override virtual
Allocates memory for an array of radiation facets.
Parameters
[in] size Size of array
Implements jeod::InteractionSurface.
Definition at line 134 of file radiation_surface.cc.
References facets, jeod::MessageHandler::fail(), ii_facet, JEOD_ALLOC_CLASS_POINTER_ARRAY, num_facets, and jeod::RadiationMessages::operational_setup_error.
allocate_interaction_facet()
void jeod::RadiationSurface::allocate_interaction_facet (Facet * facet, InteractionFacetFactory * factory, FacetParams * params, unsigned int index) override virtual
Turns facet memory into radiaiton facet memory.
Parameters
[in] facet pointer to the facet
[in] factory pointer to the facet factory
[in] params pointer to the generic facet parameter.
[in] index index value in the facet list.
Implements jeod::InteractionSurface.
Definition at line 166 of file radiation_surface.cc.
References jeod::InteractionFacetFactory::create_facet(), facets, jeod::MessageHandler::fail(), jeod::RadiationMessages::invalid_setup_error, JEOD_DELETE_OBJECT, num_facets, and jeod::RadiationMessages::operational_setup_error.
equalize_absorption_emission()
void jeod::RadiationSurface::equalize_absorption_emission ()
systematically calls the method to ensure that the same for each facet.
Definition at line 284 of file radiation_surface.cc.
References facets, ii_facet, num_facets, jeod::ThermalFacetRider::power_absorb, jeod::ThermalFacetRider::power_emit, and jeod::RadiationBaseFacet::thermal.
Referenced by jeod::RadiationPressure::update_facet_surface().
incident_radiation()
void jeod::RadiationSurface::incident_radiation (double flux_mag, const double flux_struc_hat[3], bool calculate_forces)
systematically calls the method to calculate the interaction on each facet.
Parameters
[in] flux_mag Magnitude of incident flux
[in] flux_struc_hat unit vector of incident flux
[in] calculate_forces boolean indicating whether to calculate forces.
Definition at line 230 of file radiation_surface.cc.
References facets, ii_facet, jeod::RadiationBaseFacet::incident_radiation(), and num_facets.
Referenced by jeod::RadiationPressure::update_facet_surface().
initialize()
void jeod::RadiationSurface::initialize (double center_grav[3])
Initializes the radiation surface.
Parameters
[in] center_grav position of center of mass
Units: M
Definition at line 69 of file radiation_surface.cc.
References jeod::ThermalFacetRider::emissivity, facets, jeod::MessageHandler::fail(), ii_facet, jeod::RadiationFacet::initialize_geom(), jeod::RadiationMessages::invalid_setup_error, num_facets, jeod::RadiationMessages::operational_setup_error, and jeod::RadiationBaseFacet::thermal.
Referenced by jeod::RadiationPressure::initialize().
initialize_runtime_values()
void jeod::RadiationSurface::initialize_runtime_values ()
To initialize the values during each update run.
Definition at line 312 of file radiation_surface.cc.
References facets, ii_facet, jeod::RadiationBaseFacet::initialize_runtime_values(), and num_facets.
Referenced by jeod::RadiationPressure::update_facet_surface().
interact_with_third_body()
void jeod::RadiationSurface::interact_with_third_body (RadiationThirdBody * third_body_ptr, const bool calculate_forces)
systematically calls the method to calculate the interaction of each facet with ThirdBody flux.
Parameters
[in,out] third_body_ptr Third body that emits radiation.
[in] calculate_forces Calculate forces on the surface if true.
Definition at line 244 of file radiation_surface.cc.
References facets, ii_facet, jeod::RadiationBaseFacet::interact_with_third_body(), and num_facets.
Referenced by jeod::RadiationPressure::update_facet_surface().
operator=()
RadiationSurface& jeod::RadiationSurface::operator= (const RadiationSurface &) delete
radiation_pressure()
void jeod::RadiationSurface::radiation_pressure ()
systematically calls the method to wrap up the radiation pressure calculation on each facet and accumulate forces and torques over all facets.
Definition at line 296 of file radiation_surface.cc.
References facets, force, ii_facet, jeod::Vector3::incr(), jeod::Vector3::initialize(), num_facets, jeod::RadiationFacet::radiation_pressure(), and torque.
Referenced by jeod::RadiationPressure::update_facet_surface().
thermal_integrator()
void jeod::RadiationSurface::thermal_integrator () override virtual
systematically calls the method to integrate the temperature variation for each facet.
Reimplemented from jeod::InteractionSurface.
Definition at line 266 of file radiation_surface.cc.
References jeod::InteractionFacet::base_facet, facets, jeod::ThermalIntegrableObject::get_temp(), ii_facet, jeod::ThermalFacetRider::integrable_object, jeod::ThermalFacetRider::integrate(), num_facets, jeod::Facet::temperature, and jeod::RadiationBaseFacet::thermal.
Friends And Related Function Documentation
init_attrjeod__RadiationSurface
void init_attrjeod__RadiationSurface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file radiation_surface.hh.
Field Documentation
facets
RadiationFacet** jeod::RadiationSurface::facets {}
Array of pointers to the Radiation Facets.
trick_units(–)
Definition at line 94 of file radiation_surface.hh.
Referenced by accumulate_thermal_sources(), add_thermal_integrators_to(), allocate_array(), allocate_interaction_facet(), equalize_absorption_emission(), incident_radiation(), initialize(), initialize_runtime_values(), interact_with_third_body(), radiation_pressure(), thermal_integrator(), and ~RadiationSurface().
force
double jeod::RadiationSurface::force[3] {}
Force resulting from all radiative interactions.
trick_units(–)
Definition at line 118 of file radiation_surface.hh.
Referenced by radiation_pressure(), and jeod::RadiationPressure::update_facet_surface().
ii_facet
unsigned int jeod::RadiationSurface::ii_facet {}
Simple counter, used repeatedly.
trick_units(–)
Definition at line 128 of file radiation_surface.hh.
Referenced by accumulate_thermal_sources(), allocate_array(), equalize_absorption_emission(), incident_radiation(), initialize(), initialize_runtime_values(), interact_with_third_body(), radiation_pressure(), and thermal_integrator().
include_conduction
bool jeod::RadiationSurface::include_conduction {}
Flag to instruct model to include conduction between plates in the thermal calculation.
Requires a thermal_conduction matrix.trick_units(–)
Definition at line 105 of file radiation_surface.hh.
num_facets
unsigned int jeod::RadiationSurface::num_facets {}
number of facets in this surface.
trick_units(–)
Definition at line 99 of file radiation_surface.hh.
Referenced by accumulate_thermal_sources(), add_thermal_integrators_to(), allocate_array(), allocate_interaction_facet(), equalize_absorption_emission(), incident_radiation(), initialize(), initialize_runtime_values(), interact_with_third_body(), radiation_pressure(), thermal_integrator(), and ~RadiationSurface().
thermal_conduction
double** jeod::RadiationSurface::thermal_conduction {}
Conductivity values (Watts per Kelvin) between facets.
Assumed symmetric, only the values [small][large] will be considered (e.g. thermal_conduction[2][3] gives the conduction between facets 2 and 3, whereas thermal_conduction[3][2] will never be seen.trick_units(–)
Definition at line 113 of file radiation_surface.hh.
torque
double jeod::RadiationSurface::torque[3] {}
Torque resulting from all radiative interactions.
trick_units(–)
Definition at line 123 of file radiation_surface.hh.
Referenced by radiation_pressure(), and jeod::RadiationPressure::update_facet_surface().
The documentation for this class was generated from the following files:
radiation_surface.hh
radiation_surface.cc