JEOD: jeod::JeodDynbodyIntegrationLoop Class Reference
jeod::JeodDynbodyIntegrationLoop Class Reference
A Trick::IntegLoopScheduler that provides the ability to integrate a collection of Trick::SimObject instances over time, with the sim objects capable of being moved from one integration loop to another during run time.
#include <trick_dynbody_integ_loop.hh>
Public Member Functions
JeodDynbodyIntegrationLoop ()
JeodDynbodyIntegrationLoop default constructor.
JeodDynbodyIntegrationLoop (double cycle, Trick::SimObject &sim_object_in, TimeManager &time_manager_in, DynManager &dyn_manager_in, GravityManager &grav_manager_in, er7_utils::IntegratorConstructor *&integ_cotr_in, DynamicsIntegrationGroup &integ_group_factory)
JeodDynbodyIntegrationLoop non-default constructor.
~JeodDynbodyIntegrationLoop () override
JeodDynbodyIntegrationLoop destructor.
JeodDynbodyIntegrationLoop (const JeodDynbodyIntegrationLoop &)=delete
JeodDynbodyIntegrationLoop & operator= (const JeodDynbodyIntegrationLoop &)=delete
void initialize_integ_loop ()
S_define-level function to initialize the integration loop.
void set_time_to_loop_start ()
S_define-level function to reset JEOD time to the time at the start of the current integration loop.
void update_integration_group (JeodIntegrationGroup &group) override
Update the provided integration group, which must be the integration group contained within this integration loop object.
int add_sim_object (Trick::SimObject &sim_obj) override
Add a sim object to the set of objects to be integrated by this integration loop object.
virtual void add_integrable_object (er7_utils::IntegrableObject &integrable_object)
Add the specified integrable object, which should not be a DynBody, to the integration group's set of integrable objects.
int remove_sim_object (Trick::SimObject &sim_obj) override
Remove a sim object from the set of objects to be integrated by this integration loop object.
virtual void remove_integrable_object (er7_utils::IntegrableObject &integrable_object)
Remove the specified integrable object from the integration group's set of integrable objects.
virtual void gravitation ()
Compute the gravitational accelerations of each dynamic body that is integrated by this integration loop.
virtual void collect_derivatives ()
Collect the derivatives for each dynamic body that is integrated by this integration loop.
virtual void set_deriv_ephem_update (bool val)
Set the deriv_ephem_update flag for the integration group.
Public Member Functions inherited from jeod::JeodIntegrationGroupOwner
virtual ~JeodIntegrationGroupOwner ()=default
Destructor.
Protected Member Functions
Trick::SimObject * find_containing_sim_object (er7_utils::IntegrableObject &integrable_object)
Find the sim object that contains the specified integrable object.
virtual void add_sim_object_bodies (Trick::SimObject &sim_obj)
Add the DynBody objects contained in the specified sim object to the set of DynBody objects integrated by this integration loop.
virtual void add_sim_object_bodies ()
Add the dyn bodies contained in all the sim objects integrated by this integration loop to the loop's integration group.
virtual void remove_sim_object_bodies (Trick::SimObject &sim_obj)
Remove the DynBody objects contained in the specified sim object from the set of DynBody objects integrated by this integration loop.
int integrate_dt (double beg_sim_time, double del_sim_time) override
Integrate sim objects over the specified time span.
Protected Attributes
Trick::SimObject * loop_sim_object {}
The simulation object that contains this integration loop object.
DynManager * dyn_manager {}
The JEOD dynamics manager.
TimeManager * time_manager {}
The JEOD time manager.
GravityManager * gravity_manager {}
The gravity model manager.
JeodTrickIntegrator integ_interface
Dummy integration interface; needed by the integ_group.
er7_utils::IntegratorConstructor ** integ_constructor {}
Handle to the integration constructor used to create integrators.
const DynamicsIntegrationGroup * integ_group_factory {}
The externally-supplied integration group used as a template for creating this integration loop's integration group.
DynamicsIntegrationGroup * integ_group {}
The integration group that performs the integration.
bool deriv_ephem_update {}
If set, ephemerides will be updated at the derivative rate.
Friends
class InputProcessor
void init_attrjeod__JeodDynbodyIntegrationLoop ()
Detailed Description
A Trick::IntegLoopScheduler that provides the ability to integrate a collection of Trick::SimObject instances over time, with the sim objects capable of being moved from one integration loop to another during run time.
A JeodDynbodyIntegrationLoop augments this capability in a number of regards:
All DynBody objects contained in the sim objects integrated by a JeodDynbodyIntegrationLoop object are integrated using JEOD integration.
The DynBody objects to be integrated by a JeodDynbodyIntegrationLoop object are automatically collected as a member of the DynamicsIntegrationGroup object contained within a JeodDynbodyIntegrationLoop object.
Non-DynBody integrable objects can also be integrated using JEOD integration.
Non-DynBody integrable objects that are elsewhere identified as being associated with a DynBody object are automatically collected along with the DynBody objects with which they are associated.
The DynBody and associated integrable objects are integrated using the DynamicsIntegrationGroup object contained in the loop object.
Users of this class are strongly encouraged to do so via a JeodIntegLoopSimObject. See $JEOD_HOME/lib/jeod/JEOD_S_modules/integ_loop.sm.
Definition at line 134 of file trick_dynbody_integ_loop.hh.
Constructor & Destructor Documentation
JeodDynbodyIntegrationLoop() [1/3]
jeod::JeodDynbodyIntegrationLoop::JeodDynbodyIntegrationLoop ()
JeodDynbodyIntegrationLoop default constructor.
Note
This exists only for the purpose of automated checkpoint/restart.
Warning
Do not use the default constructor outside of this context.
Definition at line 54 of file trick_dynbody_integ_loop.cc.
JeodDynbodyIntegrationLoop() [2/3]
jeod::JeodDynbodyIntegrationLoop::JeodDynbodyIntegrationLoop (double cycle, Trick::SimObject & sim_object_in, TimeManager & time_manager_in, DynManager & dyn_manager_in, GravityManager & grav_manager_in, er7_utils::IntegratorConstructor *& integ_cotr_in, DynamicsIntegrationGroup & integ_group_factory)
JeodDynbodyIntegrationLoop non-default constructor.
This is the constructor that should be used in the S_define file. The SimObject that contains this JeodDynbodyIntegrationLoop instance must register an "integ_loop" class job that calls the loop's integrate method.
Parameters
cycle The integration interval in simulation seconds. This must be the same interval as specified in the integ_loop job specification.
sim_object_in The SimObject that contains this JeodDynbodyIntegrationLoop instance.
time_manager_in The simulation's time manager object.
dyn_manager_in The simulation's dynamics manager object.
grav_manager_in The simulation's gravity manager object.
integ_cotr_in The integrator constructor used to create integration artifacts.
integ_group_factory The integration group object used to create this loop's integ group.
Definition at line 60 of file trick_dynbody_integ_loop.cc.
References add_sim_object(), jeod::MessageHandler::fail(), jeod::SimInterfaceMessages::integration_error, and loop_sim_object.
~JeodDynbodyIntegrationLoop()
jeod::JeodDynbodyIntegrationLoop::~JeodDynbodyIntegrationLoop () override
JeodDynbodyIntegrationLoop destructor.
Definition at line 91 of file trick_dynbody_integ_loop.cc.
References integ_group, and JEOD_DELETE_OBJECT.
JeodDynbodyIntegrationLoop() [3/3]
jeod::JeodDynbodyIntegrationLoop::JeodDynbodyIntegrationLoop (const JeodDynbodyIntegrationLoop &) delete
Member Function Documentation
add_integrable_object()
void jeod::JeodDynbodyIntegrationLoop::add_integrable_object (er7_utils::IntegrableObject & integrable_object) virtual
Add the specified integrable object, which should not be a DynBody, to the integration group's set of integrable objects.
Parameters
integrable_object Object to be added.
Definition at line 159 of file trick_dynbody_integ_loop.cc.
References jeod::JeodIntegrationGroup::add_integrable_object(), add_sim_object(), find_containing_sim_object(), and integ_group.
add_sim_object()
int jeod::JeodDynbodyIntegrationLoop::add_sim_object (Trick::SimObject & sim_obj) override
Add a sim object to the set of objects to be integrated by this integration loop object.
The job queues for this loop are rebuilt after adding the sim object.
Parameters
sim_obj The SimObject to be added to this loop object.
Returns
Zero => success, non-zero => error.
Definition at line 250 of file trick_dynbody_integ_loop.cc.
References add_sim_object_bodies(), dyn_manager, and jeod::DynManager::is_initialized().
Referenced by add_integrable_object(), and JeodDynbodyIntegrationLoop().
add_sim_object_bodies() [1/2]
void jeod::JeodDynbodyIntegrationLoop::add_sim_object_bodies (Trick::SimObject & sim_obj) protected virtual
Add the DynBody objects contained in the specified sim object to the set of DynBody objects integrated by this integration loop.
Parameters
sim_obj The SimObject being added to this loop object.
Definition at line 292 of file trick_dynbody_integ_loop.cc.
References jeod::DynamicsIntegrationGroup::add_dyn_body(), dyn_manager, find_containing_sim_object(), jeod::DynManager::get_dyn_bodies(), and integ_group.
add_sim_object_bodies() [2/2]
void jeod::JeodDynbodyIntegrationLoop::add_sim_object_bodies () protected virtual
Add the dyn bodies contained in all the sim objects integrated by this integration loop to the loop's integration group.
Definition at line 307 of file trick_dynbody_integ_loop.cc.
References jeod::DynamicsIntegrationGroup::add_dyn_body(), dyn_manager, find_containing_sim_object(), jeod::DynManager::get_dyn_bodies(), and integ_group.
Referenced by add_sim_object(), and update_integration_group().
collect_derivatives()
virtual void jeod::JeodDynbodyIntegrationLoop::collect_derivatives () inline virtual
Collect the derivatives for each dynamic body that is integrated by this integration loop.
Definition at line 268 of file trick_dynbody_integ_loop.hh.
References jeod::DynamicsIntegrationGroup::collect_derivatives(), and integ_group.
find_containing_sim_object()
Trick::SimObject * jeod::JeodDynbodyIntegrationLoop::find_containing_sim_object (er7_utils::IntegrableObject & integrable_object) protected
Find the sim object that contains the specified integrable object.
Parameters
integrable_object Object to be found.
Returns
Sim object that contains the specified object, or null if none.
Definition at line 126 of file trick_dynbody_integ_loop.cc.
References jeod::JeodSimulationInterface::get_address_at_name(), jeod::JeodSimulationInterface::get_name_at_address(), and jeod::JeodMemoryManager::get_type_descriptor().
Referenced by add_integrable_object(), add_sim_object_bodies(), and remove_sim_object_bodies().
gravitation()
virtual void jeod::JeodDynbodyIntegrationLoop::gravitation () inline virtual
Compute the gravitational accelerations of each dynamic body that is integrated by this integration loop.
Definition at line 259 of file trick_dynbody_integ_loop.hh.
References dyn_manager, jeod::DynamicsIntegrationGroup::gravitation(), gravity_manager, and integ_group.
initialize_integ_loop()
void jeod::JeodDynbodyIntegrationLoop::initialize_integ_loop ()
S_define-level function to initialize the integration loop.
This function should be called as a very low phase integration class job.
Definition at line 97 of file trick_dynbody_integ_loop.cc.
References jeod::DynManager::add_integ_group(), jeod::DynamicsIntegrationGroup::create_group(), jeod::DynamicsIntegrationGroup::deriv_ephem_update, deriv_ephem_update, dyn_manager, jeod::MessageHandler::fail(), jeod::TimeManager::get_jeod_integration_time(), integ_constructor, integ_group, integ_group_factory, integ_interface, jeod::SimInterfaceMessages::integration_error, and time_manager.
integrate_dt()
int jeod::JeodDynbodyIntegrationLoop::integrate_dt (double beg_sim_time, double del_sim_time) override protected
Integrate sim objects over the specified time span.
This is an overridable internal integration function and is called by the externally-visible integrate method and by call_dynamic_event_jobs.
Returns
Zero/non-zero success indicator. Out-of-sync integrators cause a non-zero return.
Parameters
beg_sim_time The time at the start of the integration interval.
del_sim_time The time span of the integration interval.
Definition at line 187 of file trick_dynbody_integ_loop.cc.
References jeod::MessageHandler::error(), integ_group, jeod::SimInterfaceMessages::integration_error, and trick_curr_integ.
operator=()
JeodDynbodyIntegrationLoop& jeod::JeodDynbodyIntegrationLoop::operator= (const JeodDynbodyIntegrationLoop &) delete
remove_integrable_object()
void jeod::JeodDynbodyIntegrationLoop::remove_integrable_object (er7_utils::IntegrableObject & integrable_object) virtual
Remove the specified integrable object from the integration group's set of integrable objects.
Parameters
integrable_object Object to be removed.
Definition at line 175 of file trick_dynbody_integ_loop.cc.
References integ_group, and jeod::JeodIntegrationGroup::remove_integrable_object().
remove_sim_object()
int jeod::JeodDynbodyIntegrationLoop::remove_sim_object (Trick::SimObject & sim_obj) override
Remove a sim object from the set of objects to be integrated by this integration loop object.
The job queues for this loop are rebuilt after removing the sim object.
Parameters
sim_obj The SimObject to be removed from this loop object.
Returns
Zero => success, non-zero => error.
Definition at line 271 of file trick_dynbody_integ_loop.cc.
References dyn_manager, jeod::DynManager::is_initialized(), and remove_sim_object_bodies().
remove_sim_object_bodies()
void jeod::JeodDynbodyIntegrationLoop::remove_sim_object_bodies (Trick::SimObject & sim_obj) protected virtual
Remove the DynBody objects contained in the specified sim object from the set of DynBody objects integrated by this integration loop.
Parameters
sim_obj The SimObject being removed from this loop object.
Definition at line 323 of file trick_dynbody_integ_loop.cc.
References jeod::DynamicsIntegrationGroup::delete_dyn_body(), dyn_manager, find_containing_sim_object(), jeod::DynManager::get_dyn_bodies(), and integ_group.
Referenced by remove_sim_object().
set_deriv_ephem_update()
virtual void jeod::JeodDynbodyIntegrationLoop::set_deriv_ephem_update (bool val) inline virtual
Set the deriv_ephem_update flag for the integration group.
Parameters
val New value for deriv_ephem_update.
Definition at line 277 of file trick_dynbody_integ_loop.hh.
References jeod::DynamicsIntegrationGroup::deriv_ephem_update, deriv_ephem_update, and integ_group.
set_time_to_loop_start()
void jeod::JeodDynbodyIntegrationLoop::set_time_to_loop_start ()
S_define-level function to reset JEOD time to the time at the start of the current integration loop.
This function should be called as a very low phase pre-integration class job in simulations that have multiple integration loops.
Definition at line 181 of file trick_dynbody_integ_loop.cc.
References time_manager, and jeod::TimeManager::update().
update_integration_group()
void jeod::JeodDynbodyIntegrationLoop::update_integration_group (JeodIntegrationGroup & group) override virtual
Update the provided integration group, which must be the integration group contained within this integration loop object.
Note
This function is public because it is called (indirectly) from DynManager::initialize_simulation. It should otherwise be viewed as a protected or private function.
Parameters
group The IntegrationGroup to be updated, which must be the integration loop's integration group object.
Implements jeod::JeodIntegrationGroupOwner.
Definition at line 338 of file trick_dynbody_integ_loop.cc.
References add_sim_object_bodies(), jeod::MessageHandler::fail(), integ_group, and jeod::SimInterfaceMessages::integration_error.
Friends And Related Function Documentation
init_attrjeod__JeodDynbodyIntegrationLoop
void init_attrjeod__JeodDynbodyIntegrationLoop () friend
InputProcessor
friend class InputProcessor friend
Definition at line 137 of file trick_dynbody_integ_loop.hh.
Field Documentation
deriv_ephem_update
bool jeod::JeodDynbodyIntegrationLoop::deriv_ephem_update {} protected
If set, ephemerides will be updated at the derivative rate.
If clear, ephemerides will not be updated at the derivative rate by the ephemerides manager. Derivative-rate updates can still be attained by explicitly calling the various ephemerides model's update functions as derivative class jobs.trick_units(–)
Definition at line 380 of file trick_dynbody_integ_loop.hh.
Referenced by initialize_integ_loop(), and set_deriv_ephem_update().
dyn_manager
DynManager* jeod::JeodDynbodyIntegrationLoop::dyn_manager {} protected
The JEOD dynamics manager.
trick_units(–)
Definition at line 340 of file trick_dynbody_integ_loop.hh.
Referenced by add_sim_object(), add_sim_object_bodies(), gravitation(), initialize_integ_loop(), remove_sim_object(), and remove_sim_object_bodies().
gravity_manager
GravityManager* jeod::JeodDynbodyIntegrationLoop::gravity_manager {} protected
The gravity model manager.
trick_units(–)
Definition at line 350 of file trick_dynbody_integ_loop.hh.
Referenced by gravitation().
integ_constructor
er7_utils::IntegratorConstructor** jeod::JeodDynbodyIntegrationLoop::integ_constructor {} protected
Handle to the integration constructor used to create integrators.
trick_units(–)
Definition at line 360 of file trick_dynbody_integ_loop.hh.
Referenced by initialize_integ_loop().
integ_group
DynamicsIntegrationGroup* jeod::JeodDynbodyIntegrationLoop::integ_group {} protected
The integration group that performs the integration.
trick_units(–)
Definition at line 371 of file trick_dynbody_integ_loop.hh.
Referenced by add_integrable_object(), add_sim_object_bodies(), collect_derivatives(), gravitation(), initialize_integ_loop(), integrate_dt(), remove_integrable_object(), remove_sim_object_bodies(), set_deriv_ephem_update(), update_integration_group(), and ~JeodDynbodyIntegrationLoop().
integ_group_factory
const DynamicsIntegrationGroup* jeod::JeodDynbodyIntegrationLoop::integ_group_factory {} protected
The externally-supplied integration group used as a template for creating this integration loop's integration group.
trick_units(–)
Definition at line 366 of file trick_dynbody_integ_loop.hh.
Referenced by initialize_integ_loop().
integ_interface
JeodTrickIntegrator jeod::JeodDynbodyIntegrationLoop::integ_interface protected
Dummy integration interface; needed by the integ_group.
trick_units(–)
Definition at line 355 of file trick_dynbody_integ_loop.hh.
Referenced by initialize_integ_loop().
loop_sim_object
Trick::SimObject* jeod::JeodDynbodyIntegrationLoop::loop_sim_object {} protected
The simulation object that contains this integration loop object.
trick_units(–)
Definition at line 335 of file trick_dynbody_integ_loop.hh.
Referenced by JeodDynbodyIntegrationLoop().
time_manager
TimeManager* jeod::JeodDynbodyIntegrationLoop::time_manager {} protected
The JEOD time manager.
trick_units(–)
Definition at line 345 of file trick_dynbody_integ_loop.hh.
Referenced by initialize_integ_loop(), and set_time_to_loop_start().
The documentation for this class was generated from the following files:
trick_dynbody_integ_loop.hh
trick_dynbody_integ_loop.cc