JEOD: jeod::ContactSurface Class Reference
jeod::ContactSurface Class Reference
The contact specific interaction surface, for use with the surface model.
#include <contact_surface.hh>
Public Member Functions
ContactSurface ()
Default Constructor.
~ContactSurface () override
Destructor.
ContactSurface & operator= (const ContactSurface &)=delete
ContactSurface (const ContactSurface &)=delete
void allocate_array (unsigned int size) override
Allocates an array of ContactFacet pointers, of the size indicated by the input variable.
void allocate_interaction_facet (Facet *facet, InteractionFacetFactory *factory, FacetParams *params, unsigned int index) override
Creates an interaction facet or more accurately a contact facet from a basic facet and set of parameters.
virtual void collect_forces_torques ()
collect the forces and torques from all the facets in this contact surface
Public Member Functions inherited from jeod::InteractionSurface
InteractionSurface ()=default
virtual ~InteractionSurface ()=default
InteractionSurface & operator= (const InteractionSurface &)=delete
InteractionSurface (const InteractionSurface &)=delete
virtual void accumulate_thermal_sources ()
Adds all thermal sources together.
virtual void thermal_integrator ()
Integrates thermal sources to get temperature.
Data Fields
ContactFacet ** contact_facets {}
An array of pointers to contact interaction facets.
unsigned int facets_size {}
Size of the contact_facets array.
double contact_force [3] {}
Total Force due to contact, resulting from all plates combined.
double contact_torque [3] {}
Total Torque due to contact, resulting from all plates combined.
Friends
class InputProcessor
void init_attrjeod__ContactSurface ()
Detailed Description
The contact specific interaction surface, for use with the surface model.
Definition at line 84 of file contact_surface.hh.
Constructor & Destructor Documentation
ContactSurface() [1/2]
jeod::ContactSurface::ContactSurface ()
Default Constructor.
Definition at line 56 of file contact_surface.cc.
References JEOD_REGISTER_CLASS.
~ContactSurface()
jeod::ContactSurface::~ContactSurface () override
Destructor.
Definition at line 64 of file contact_surface.cc.
References contact_facets, facets_size, and JEOD_DELETE_2D.
ContactSurface() [2/2]
jeod::ContactSurface::ContactSurface (const ContactSurface &) delete
Member Function Documentation
allocate_array()
void jeod::ContactSurface::allocate_array (unsigned int size) override virtual
Allocates an array of ContactFacet pointers, of the size indicated by the input variable.
Parameters
[in] size The size of the needed array
Units: cnt:
Implements jeod::InteractionSurface.
Definition at line 75 of file contact_surface.cc.
References contact_facets, facets_size, jeod::MessageHandler::fail(), jeod::ContactMessages::initialization_error, and JEOD_ALLOC_CLASS_POINTER_ARRAY.
allocate_interaction_facet()
void jeod::ContactSurface::allocate_interaction_facet (Facet * facet, InteractionFacetFactory * factory, FacetParams * params, unsigned int index) override virtual
Creates an interaction facet or more accurately a contact facet from a basic facet and set of parameters.
Parameters
[in] facet The basic facet used to create the interaction facet
[in] factory The factory used to create the interaction facet
[in] params The contact params used to create the interaction facet
[in] index Where the new interaction facet will be placed in the contact_facets array
Units: cnt
Implements jeod::InteractionSurface.
Definition at line 108 of file contact_surface.cc.
References contact_facets, jeod::InteractionFacetFactory::create_facet(), facets_size, jeod::MessageHandler::fail(), jeod::ContactMessages::initialization_error, and JEOD_DELETE_OBJECT.
collect_forces_torques()
void jeod::ContactSurface::collect_forces_torques () virtual
collect the forces and torques from all the facets in this contact surface
Definition at line 177 of file contact_surface.cc.
References contact_facets, contact_force, contact_torque, facets_size, jeod::Vector3::initialize(), jeod::Vector3::sum(), and jeod::Vector3::zero_small().
operator=()
ContactSurface& jeod::ContactSurface::operator= (const ContactSurface &) delete
Friends And Related Function Documentation
init_attrjeod__ContactSurface
void init_attrjeod__ContactSurface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file contact_surface.hh.
Field Documentation
contact_facets
ContactFacet** jeod::ContactSurface::contact_facets {}
An array of pointers to contact interaction facets.
trick_units(–)
Definition at line 95 of file contact_surface.hh.
Referenced by allocate_array(), allocate_interaction_facet(), collect_forces_torques(), and ~ContactSurface().
contact_force
double jeod::ContactSurface::contact_force[3] {}
Total Force due to contact, resulting from all plates combined.
trick_units(N)
Definition at line 105 of file contact_surface.hh.
Referenced by collect_forces_torques().
contact_torque
double jeod::ContactSurface::contact_torque[3] {}
Total Torque due to contact, resulting from all plates combined.
trick_units(N/m)
Definition at line 110 of file contact_surface.hh.
Referenced by collect_forces_torques().
facets_size
unsigned int jeod::ContactSurface::facets_size {}
Size of the contact_facets array.
trick_units(count)
Definition at line 100 of file contact_surface.hh.
Referenced by allocate_array(), allocate_interaction_facet(), collect_forces_torques(), and ~ContactSurface().
The documentation for this class was generated from the following files:
contact_surface.hh
contact_surface.cc