JEOD: jeod::EphemerisInterface Class Reference
jeod::EphemerisInterface Class Reference abstract
Interface class that specifies minimal functionality of an ephemeris model.
#include <ephem_interface.hh>
Public Member Functions
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
virtual double timestamp (void) const =0
Indicates when class was last updated.
virtual const char * get_name (void) const =0
Identify the model.
virtual void ephem_initialize (EphemeridesManager &manager)=0
Initialize the model.
virtual void ephem_activate (EphemeridesManager &manager)=0
Activate the model.
virtual void ephem_build_tree (EphemeridesManager &manager)=0
Build the model's contribution to the reference frame tree.
virtual void ephem_update (void)=0
Update the model.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
virtual void activate (void)=0
Mark the object as active.
virtual void deactivate (void)=0
Mark the object as inactive.
Friends
class InputProcessor
void init_attrjeod__EphemerisInterface ()
Detailed Description
Interface class that specifies minimal functionality of an ephemeris model.
Definition at line 81 of file ephem_interface.hh.
Constructor & Destructor Documentation
~EphemerisInterface()
jeod::EphemerisInterface::~EphemerisInterface (void) inline override
Destructor; there is nothing to destroy here.
Definition at line 163 of file ephem_interface.hh.
Member Function Documentation
ephem_activate()
virtual void jeod::EphemerisInterface::ephem_activate (EphemeridesManager & manager) pure virtual
Activate the model.
Parameters
[in,out] manager Ephemerides manager
Implemented in jeod::PropagatedPlanet, jeod::SinglePlanetEphemeris, jeod::De4xxEphemeris, jeod::EmptySpaceEphemeris, jeod::SinglePointEphemeris, jeod::PlanetOrientation, and jeod::SpiceEphemeris.
Referenced by jeod::EphemeridesManager::activate_ephemerides().
ephem_build_tree()
virtual void jeod::EphemerisInterface::ephem_build_tree (EphemeridesManager & manager) pure virtual
Build the model's contribution to the reference frame tree.
Parameters
[in,out] manager Ephemerides manager
Implemented in jeod::PropagatedPlanet, jeod::SinglePlanetEphemeris, jeod::De4xxEphemeris, jeod::EmptySpaceEphemeris, jeod::SinglePointEphemeris, jeod::PlanetOrientation, and jeod::SpiceEphemeris.
Referenced by jeod::EphemeridesManager::activate_ephemerides().
ephem_initialize()
virtual void jeod::EphemerisInterface::ephem_initialize (EphemeridesManager & manager) pure virtual
Initialize the model.
Parameters
[in,out] manager Ephemerides manager
Implemented in jeod::PropagatedPlanet, jeod::SinglePlanetEphemeris, jeod::De4xxEphemeris, jeod::EmptySpaceEphemeris, jeod::PlanetOrientation, jeod::SinglePointEphemeris, and jeod::SpiceEphemeris.
Referenced by jeod::EphemeridesManager::initialize_ephemerides().
ephem_update()
virtual void jeod::EphemerisInterface::ephem_update (void) pure virtual
Update the model.
Implemented in jeod::PropagatedPlanet, jeod::De4xxEphemeris, jeod::RNPMars, jeod::RNPJ2000, jeod::SpiceEphemeris, and jeod::SinglePointEphemeris.
Referenced by jeod::EphemeridesManager::update_ephemerides().
get_name()
virtual const char* jeod::EphemerisInterface::get_name (void) const pure virtual
Identify the model.
Returns
Model name
Implemented in jeod::PropagatedPlanet, jeod::De4xxEphemeris, jeod::PlanetRNP, jeod::RNPMars, jeod::PlanetOrientation, jeod::RNPJ2000, jeod::SpiceEphemeris, and jeod::SinglePointEphemeris.
Referenced by jeod::EphemeridesManager::add_ephem_item().
timestamp()
virtual double jeod::EphemerisInterface::timestamp (void) const pure virtual
Indicates when class was last updated.
Returns
Time of last update
Units: s
Implemented in jeod::PropagatedPlanet, jeod::De4xxEphemeris, jeod::RNPMars, jeod::RNPJ2000, jeod::SpiceEphemeris, and jeod::SinglePointEphemeris.
Friends And Related Function Documentation
init_attrjeod__EphemerisInterface
void init_attrjeod__EphemerisInterface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 82 of file ephem_interface.hh.
The documentation for this class was generated from the following file:
ephem_interface.hh