JEOD: jeod::TimeConverter_TAI_TDB Class Reference
jeod::TimeConverter_TAI_TDB Class Reference
Define class TimeConverter_TAI_TDB, which converts from International Atomic Time to Barycentric Dynamic Time.
#include <time_converter_tai_tdb.hh>
Public Member Functions
TimeConverter_TAI_TDB ()
~TimeConverter_TAI_TDB () override=default
TimeConverter_TAI_TDB (const TimeConverter_TAI_TDB &)=delete
TimeConverter_TAI_TDB & operator= (const TimeConverter_TAI_TDB &)=delete
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void set_a_to_b_offset ()
void convert_a_to_b () override
Default converter from time 'a' to time 'b'.
void convert_b_to_a () override
Default converter from time 'b' to time 'a'.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()=default
TimeConverter (const TimeConverter &)=delete
TimeConverter & operator= (const TimeConverter &)=delete
virtual bool is_initialized ()
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void reset_a_to_b_offset ()
Resets the offset between type a and type b mid-sim.
virtual void verify_table_lookup_ends ()
This function does absolutely nothing.
double get_a_to_b_offset ()
Return the offset from the parent time object to this object.
Private Attributes
double TAI_to_TT_offset {32.184}
The offset from TAI to TT.
double a_to_b_offset_epoch {}
The epoch value of a_to_b_offset.
double prev_tai_seconds {}
TAI seconds from previous loop iteration.
double prev_tdb_seconds {}
TDB seconds from previous loop iteration.
int nSteps {}
Counter for number of steps in iteration.
int nIter {}
Counter for number of iterations.
TimeTAI * tai_ptr {}
Converter parent time, always a TimeTAI for this converter.
TimeTDB * tdb_ptr {}
Converter parent time, always a TimeTDB for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_TAI_TDB ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name {""}
name of time-type "a".
std::string b_name {""}
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()=default
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized {}
whether converter has been initialized.
double a_to_b_offset {}
Difference between the two time-types.
Direction valid_directions {NO_DIRECTION}
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Define class TimeConverter_TAI_TDB, which converts from International Atomic Time to Barycentric Dynamic Time.
Definition at line 89 of file time_converter_tai_tdb.hh.
Constructor & Destructor Documentation
TimeConverter_TAI_TDB() [1/2]
jeod::TimeConverter_TAI_TDB::TimeConverter_TAI_TDB ()
Definition at line 67 of file time_converter_tai_tdb.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::ANY_DIRECTION, jeod::TimeConverter::b_name, and jeod::TimeConverter::valid_directions.
~TimeConverter_TAI_TDB()
jeod::TimeConverter_TAI_TDB::~TimeConverter_TAI_TDB () override default
TimeConverter_TAI_TDB() [2/2]
jeod::TimeConverter_TAI_TDB::TimeConverter_TAI_TDB (const TimeConverter_TAI_TDB &) delete
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_TAI_TDB::convert_a_to_b () override virtual
Default converter from time 'a' to time 'b'.
This default converter simply terminates the program. A subclass must override this default.
Reimplemented from jeod::TimeConverter.
Definition at line 129 of file time_converter_tai_tdb.cc.
References jeod::TimeConverter::a_to_b_offset, a_to_b_offset_epoch, jeod::JeodBaseTime::seconds, set_a_to_b_offset(), jeod::TimeStandard::set_time_by_seconds(), tai_ptr, and tdb_ptr.
convert_b_to_a()
void jeod::TimeConverter_TAI_TDB::convert_b_to_a () override virtual
Default converter from time 'b' to time 'a'.
This default converter simply terminates the program. A subclass must override this default.
Reimplemented from jeod::TimeConverter.
Definition at line 139 of file time_converter_tai_tdb.cc.
References jeod::TimeConverter::a_to_b_offset, a_to_b_offset_epoch, nIter, nSteps, prev_tai_seconds, prev_tdb_seconds, jeod::JeodBaseTime::seconds, set_a_to_b_offset(), jeod::TimeStandard::set_time_by_seconds(), tai_ptr, and tdb_ptr.
initialize()
void jeod::TimeConverter_TAI_TDB::initialize (JeodBaseTime * parent, JeodBaseTime * child, const int direction) override virtual
Initialize the converter.
Parameters
[in] parent parent-type
[in] child child-type
[in] direction L-R, or R-L
Implements jeod::TimeConverter.
Definition at line 81 of file time_converter_tai_tdb.cc.
References a_to_b_offset_epoch, jeod::MessageHandler::fail(), jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, set_a_to_b_offset(), tai_ptr, TAI_to_TT_offset, tdb_ptr, jeod::TimeStandard::tjt_at_epoch, and jeod::TimeConverter::verify_setup().
operator=()
TimeConverter_TAI_TDB& jeod::TimeConverter_TAI_TDB::operator= (const TimeConverter_TAI_TDB &) delete
set_a_to_b_offset()
void jeod::TimeConverter_TAI_TDB::set_a_to_b_offset ()
Definition at line 114 of file time_converter_tai_tdb.cc.
References jeod::TimeConverter::a_to_b_offset, tai_ptr, jeod::TimeStandard::tjt_at_epoch, and jeod::TimeStandard::trunc_julian_time.
Referenced by convert_a_to_b(), convert_b_to_a(), and initialize().
Friends And Related Function Documentation
init_attrjeod__TimeConverter_TAI_TDB
void init_attrjeod__TimeConverter_TAI_TDB () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file time_converter_tai_tdb.hh.
Field Documentation
a_to_b_offset_epoch
double jeod::TimeConverter_TAI_TDB::a_to_b_offset_epoch {} private
The epoch value of a_to_b_offset.
trick_units(s)
Definition at line 102 of file time_converter_tai_tdb.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), and initialize().
nIter
int jeod::TimeConverter_TAI_TDB::nIter {} private
Counter for number of iterations.
trick_units(–)
Definition at line 122 of file time_converter_tai_tdb.hh.
Referenced by convert_b_to_a().
nSteps
int jeod::TimeConverter_TAI_TDB::nSteps {} private
Counter for number of steps in iteration.
trick_units(–)
Definition at line 117 of file time_converter_tai_tdb.hh.
Referenced by convert_b_to_a().
prev_tai_seconds
double jeod::TimeConverter_TAI_TDB::prev_tai_seconds {} private
TAI seconds from previous loop iteration.
trick_units(s)
Definition at line 107 of file time_converter_tai_tdb.hh.
Referenced by convert_b_to_a().
prev_tdb_seconds
double jeod::TimeConverter_TAI_TDB::prev_tdb_seconds {} private
TDB seconds from previous loop iteration.
trick_units(s)
Definition at line 112 of file time_converter_tai_tdb.hh.
Referenced by convert_b_to_a().
tai_ptr
TimeTAI* jeod::TimeConverter_TAI_TDB::tai_ptr {} private
Converter parent time, always a TimeTAI for this converter.
trick_units(–)
Definition at line 127 of file time_converter_tai_tdb.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), initialize(), and set_a_to_b_offset().
TAI_to_TT_offset
double jeod::TimeConverter_TAI_TDB::TAI_to_TT_offset {32.184} private
The offset from TAI to TT.
This is needed because first TAI must convert to TT before applying the periodic corrections.trick_units(s)
Definition at line 97 of file time_converter_tai_tdb.hh.
Referenced by initialize().
tdb_ptr
TimeTDB* jeod::TimeConverter_TAI_TDB::tdb_ptr {} private
Converter parent time, always a TimeTDB for this converter.
trick_units(–)
Definition at line 132 of file time_converter_tai_tdb.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), and initialize().
The documentation for this class was generated from the following files:
time_converter_tai_tdb.hh
time_converter_tai_tdb.cc