JEOD: jeod::RestartableScalarFirstOrderODEIntegrator Class Reference
jeod::RestartableScalarFirstOrderODEIntegrator Class Reference
A RestartableScalarFirstOrderODEIntegrator integrates a first order ODE, dx/dt = v(x,t), where x is a scalar.
#include <restartable_state_integrator.hh>
Public Member Functions
RestartableScalarFirstOrderODEIntegrator ()
Default constructor.
~RestartableScalarFirstOrderODEIntegrator () override
Destructor.
void create_integrator (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls)
Create the integrator to be managed.
void destroy_integrator ()
Destroy the integrator.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage, double *xdot, double *x)
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
void reset_integrator ()
Tell the integrator to reset itself.
void simple_restore () override
Restore the integrator on restart.
Public Member Functions inherited from jeod::SimpleCheckpointable
SimpleCheckpointable ()
Construct a SimpleCheckpointable object.
~SimpleCheckpointable (void) override
Destruct a SimpleCheckpointable object.
const std::string get_init_name (void) override
Return the name of the initial restart action, in this case "restore".
const std::string get_item_name (void) override
Return the name of the current restart action, in this case "".
const std::string get_item_value (void) override
Return the value of the current restart action, in this case "".
void start_checkpoint (void) override
In general, start the checkpoint process.
void advance_checkpoint (void) override
In general, advance to the next checkpoint item; in this case, do nothing.
bool is_checkpoint_finished (void) override
In general, indicate when checkpointing is complete.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
In general, respond to the actions recorded in the checkpoint file.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_name (void)
In general, return the name of the finalization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
Private Member Functions
RestartableScalarFirstOrderODEIntegrator (const RestartableScalarFirstOrderODEIntegrator &)
Not implemented.
RestartableScalarFirstOrderODEIntegrator & operator= (const RestartableScalarFirstOrderODEIntegrator &)
Not implemented.
Private Attributes
er7_utils::FirstOrderODEIntegrator * integrator
Pointer to the object that performs integration.
RestartableFirstOrderODEIntegrator< 1 > integrator_manager
Object that creates and manages the integrator object.
Friends
class InputProcessor
void init_attrjeod__RestartableScalarFirstOrderODEIntegrator ()
Additional Inherited Members
Detailed Description
A RestartableScalarFirstOrderODEIntegrator integrates a first order ODE, dx/dt = v(x,t), where x is a scalar.
Definition at line 90 of file restartable_state_integrator.hh.
Constructor & Destructor Documentation
RestartableScalarFirstOrderODEIntegrator() [1/2]
jeod::RestartableScalarFirstOrderODEIntegrator::RestartableScalarFirstOrderODEIntegrator () inline
Default constructor.
Definition at line 98 of file restartable_state_integrator.hh.
References JEOD_REGISTER_CLASS.
~RestartableScalarFirstOrderODEIntegrator()
jeod::RestartableScalarFirstOrderODEIntegrator::~RestartableScalarFirstOrderODEIntegrator () inline override
Destructor.
Definition at line 110 of file restartable_state_integrator.hh.
RestartableScalarFirstOrderODEIntegrator() [2/2]
jeod::RestartableScalarFirstOrderODEIntegrator::RestartableScalarFirstOrderODEIntegrator (const RestartableScalarFirstOrderODEIntegrator &) private
Not implemented.
Member Function Documentation
create_integrator()
void jeod::RestartableScalarFirstOrderODEIntegrator::create_integrator (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls) inline
Create the integrator to be managed.
Parameters
[in] generator Integrator constructor used to create the integrator.
[in,out] controls Integration controls to be passed to the generator.
Definition at line 117 of file restartable_state_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::create_integrator(), and integrator_manager.
Referenced by jeod::ThermalIntegrableObject::create_integrators().
destroy_integrator()
void jeod::RestartableScalarFirstOrderODEIntegrator::destroy_integrator () inline
Destroy the integrator.
Definition at line 127 of file restartable_state_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::destroy_integrator(), and integrator_manager.
integrate()
er7_utils::IntegratorResult jeod::RestartableScalarFirstOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, double * xdot, double * x) inline
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
Note that this is a pass-through to the encapsulated integrator object. See er7_utils::FirstOrderODEIntegrator::integrate for details.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] xdot Time derivative of x.
[in,out] x Item to be integrated.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 147 of file restartable_state_integrator.hh.
References integrator.
Referenced by jeod::ThermalIntegrableObject::integrate().
operator=()
RestartableScalarFirstOrderODEIntegrator& jeod::RestartableScalarFirstOrderODEIntegrator::operator= (const RestartableScalarFirstOrderODEIntegrator &) private
Not implemented.
reset_integrator()
void jeod::RestartableScalarFirstOrderODEIntegrator::reset_integrator () inline
Tell the integrator to reset itself.
This should be called when the time step or time direction changes or upon a discrete change in state such docking/undocking. Such events invalidate saved state (if any). The integrator needs to restart from scratch when such events occur.
Definition at line 163 of file restartable_state_integrator.hh.
References integrator.
Referenced by jeod::ThermalIntegrableObject::reset_integrators().
simple_restore()
void jeod::RestartableScalarFirstOrderODEIntegrator::simple_restore (void) inline override virtual
Restore the integrator on restart.
Implements jeod::SimpleCheckpointable.
Definition at line 171 of file restartable_state_integrator.hh.
References integrator, integrator_manager, jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference(), and jeod::RestartableStateIntegrator< IntegratorType >::simple_restore().
Friends And Related Function Documentation
init_attrjeod__RestartableScalarFirstOrderODEIntegrator
void init_attrjeod__RestartableScalarFirstOrderODEIntegrator () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file restartable_state_integrator.hh.
Field Documentation
integrator
er7_utils::FirstOrderODEIntegrator* jeod::RestartableScalarFirstOrderODEIntegrator::integrator private
Pointer to the object that performs integration.
The object is created managed by the integrator manager.trick_units(–)
Definition at line 184 of file restartable_state_integrator.hh.
Referenced by integrate(), reset_integrator(), and simple_restore().
integrator_manager
RestartableFirstOrderODEIntegrator<1> jeod::RestartableScalarFirstOrderODEIntegrator::integrator_manager private
Object that creates and manages the integrator object.
trick_io(**)
Definition at line 189 of file restartable_state_integrator.hh.
Referenced by create_integrator(), destroy_integrator(), and simple_restore().
The documentation for this class was generated from the following file:
restartable_state_integrator.hh