JEOD: jeod::Quaternion Class Reference
jeod::Quaternion Class Reference
Implement quaternions to the extent needed to represent orientations.
#include <quat.hh>
Public Member Functions
Quaternion (void)
Construct a quaternion; default constructor.
Quaternion (const double s)
Construct a pure real quaternion.
Quaternion (const double s, const double v[3])
Construct from a scalar and a vector.
Quaternion (const double arr[4])
Construct from a double array.
Quaternion (const double T[3][3])
Construct a left transformation unit quaternion.
void set_to_zero (void)
Set all components of the quaternion to zero.
void make_identity (void)
Make the quaternion represent an identity transform.
operator double * (void)
Make a quaternion look like a double array.
void copy_to (double arr[4]) const
Copy a quaternion to a four vector, with the scalar part copied to arr[0] and the vector part to arr[1] to arr[3].
void copy_from (const double arr[4])
Copy a quaternion from a four vector, with the scalar part of the quaternion in arr[0] and the vector part in arr[1] to arr[3].
void scale (const double scale)
Scale the quaternion by a real.
void scale (const double scale, Quaternion &quat) const
Scale the quaternion by a real, leaving original intact.
double norm_sq (void) const
Compute the square of the norm of the quaternion.
void normalize (void)
Normalize the quaternion, making the scalar part of the quaternion non-negative.
void normalize (Quaternion &quat) const
Form the normalized quaternion, leaving original intact.
void normalize_integ (void)
Normalize the quaternion, but do not make the scalar part non-negative.
void normalize_integ (Quaternion &quat) const
Form the normalized quaternion, leaving original intact.
void conjugate (void)
Replace the quaternion with its conjugate.
void conjugate (Quaternion &quat) const
Form the conjugate of a quaternion, leaving original intact.
void multiply (const Quaternion &quat, Quaternion &prod) const
Post-multiply this quaternion by another quaternion: prod = this * quat.
void multiply (const Quaternion &quat)
Post-multiply this quaternion by another quaternion: this = this * quat.
void conjugate_multiply (const Quaternion &quat, Quaternion &prod) const
Post-multiply this quaternion's conjugate by another quaternion: prod = conj(this) * quat.
void conjugate_multiply (const Quaternion &quat)
Post-multiply this quaternion's conjugate by another quaternion: this = conj(this) * quat.
void multiply_conjugate (const Quaternion &quat, Quaternion &prod) const
Post-multiply this quaternion by another's conjugate: prod = this * conj(quat).
void multiply_conjugate (const Quaternion &quat)
Post-multiply this quaternion by another's conjugate: this = this * conj(quat).
void multiply_left (const Quaternion &quat, Quaternion &prod) const
Pre-multiply this quaternion by another quaternion: prod = quat * this.
void multiply_left (const Quaternion &quat)
Pre-multiply this quaternion by another quaternion: this = quat * this.
void multiply_left_conjugate (const Quaternion &quat, Quaternion &prod) const
Pre-multiply this quaternion by another's conjugate: prod = conj(quat) * this.
void multiply_left_conjugate (const Quaternion &quat)
Pre-multiply this quaternion by another's conjugate: this = conj(quat) * this.
void multiply_vector_left (const double vec[3], Quaternion &prod) const
Pre-multiply this quaternion by a pure imaginary quaternion, the latter represented by a vector: prod = [0, vec] * quat.
void multiply_vector_right (const double vec[3], Quaternion &prod) const
Post-multiply this quaternion by a pure imaginary quaternion, the latter represented by a vector: prod = quat * [0, vec].
void left_quat_from_transformation (const double T[3][3])
Compute the parent-to-child left quaternion from the input transformation matrix.
void left_quat_to_transformation (double T[3][3]) const
Compute the parent-to-child transformation matrix from the parent-to-child left quaternion.
void left_quat_from_eigen_rotation (double eigen_angle, const double eigen_axis[3])
Construct the quaternion corresponding to an eigen rotation.
void left_quat_to_eigen_rotation (double *eigen_angle, double eigen_axis[3]) const
Compute the eigen rotation corresponding to a quaternion.
void eigen_compare (const Quaternion &compare_to, double *eigen_angle, double eigen_axis[3]) const
Compute eigen decomposition of this*conj(quat).
void left_quat_transform (const double vec_in[3], double vec_out[3]) const
Transform a vector.
void compute_left_quat_deriv (const double ang_vel[3], Quaternion &qdot) const
Compute the time derivative of a left quaternion.
void compute_left_quat_second_deriv (const double ang_vel[3], const double ang_acc[3], Quaternion &qdot) const
Compute the time derivative of a left quaternion.
Static Public Member Functions
static void normalize_integ (double arr[4])
Normalize the quaternion, but do not make the scalar part non-negative.
static void compute_left_quat_deriv (const double quat[4], const double ang_vel[3], double qdot[4])
Compute the time derivative of a left quaternion.
static void compute_left_quat_second_deriv (const double quat[4], const double ang_vel[3], const double ang_acc[3], double qddot[4])
Compute the second time derivative of a left quaternion.
static Quaternion compute_slerp (Quaternion &q1, Quaternion &q2, const double T)
Compute the minimum interpolation quaternion between a start quarternion and end quaternion.
Data Fields
double scalar
The scalar, or real, part of the quaternion.
double vector [3]
The vectorial, or imaginary, part of the quaternion.
Friends
class InputProcessor
void init_attrjeod__Quaternion ()
Detailed Description
Implement quaternions to the extent needed to represent orientations.
Definition at line 87 of file quat.hh.
Constructor & Destructor Documentation
Quaternion() [1/5]
jeod::Quaternion::Quaternion (void)
Construct a quaternion; default constructor.
Definition at line 52 of file quat.cc.
References jeod::Vector3::initialize(), scalar, and vector.
Quaternion() [2/5]
jeod::Quaternion::Quaternion (const double real_part) explicit
Construct a pure real quaternion.
Parameters
[in] real_part Scalar
Definition at line 68 of file quat.cc.
References jeod::Vector3::initialize(), and vector.
Quaternion() [3/5]
jeod::Quaternion::Quaternion (const double s, const double v[3]) inline
Construct from a scalar and a vector.
Parameters
[in] s Scalar part
[in] v Vector part
Definition at line 84 of file quat_inline.hh.
References vector.
Quaternion() [4/5]
jeod::Quaternion::Quaternion (const double arr[4]) inline explicit
Construct from a double array.
Parameters
[in] arr Quaternion source
Definition at line 101 of file quat_inline.hh.
References copy_from().
Quaternion() [5/5]
jeod::Quaternion::Quaternion (const double T[3][3]) explicit
Construct a left transformation unit quaternion.
Parameters
[in] T Transformation matrix
Definition at line 81 of file quat.cc.
References left_quat_from_transformation().
Member Function Documentation
compute_left_quat_deriv() [1/2]
void jeod::Quaternion::compute_left_quat_deriv (const double ang_vel[3], Quaternion & qdot) const inline
Compute the time derivative of a left quaternion.
Parameters
[in] ang_vel Angular velocity
Units: r/s
[out] qdot Quaternion derivative
Definition at line 581 of file quat_inline.hh.
References multiply_vector_left(), and jeod::Vector3::scale().
Referenced by jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::StructureIntegratedDynBody::rot_integ(), and jeod::DynBody::rot_integ().
compute_left_quat_deriv() [2/2]
void jeod::Quaternion::compute_left_quat_deriv (const double quat[4], const double ang_vel[3], double qdot[4]) inline static
Compute the time derivative of a left quaternion.
Parameters
[in] quat Quaternion as 4-vector
[in] ang_vel Angular velocity
Units: r/s
[out] qdot Derivative as 4-vector
Definition at line 619 of file quat_inline.hh.
References jeod::Vector3::cross_incr(), jeod::Vector3::dot(), and jeod::Vector3::scale().
compute_left_quat_second_deriv() [1/2]
void jeod::Quaternion::compute_left_quat_second_deriv (const double ang_vel[3], const double ang_acc[3], Quaternion & qddot) const inline
Compute the time derivative of a left quaternion.
Parameters
[in] ang_vel Angular velocity
Units: r/s
[in] ang_acc Angular acceleration
Units: r/s2
[out] qddot Quaternion 2nd deriv
Definition at line 599 of file quat_inline.hh.
References multiply_left(), jeod::Vector3::scale(), and jeod::Vector3::vmagsq().
compute_left_quat_second_deriv() [2/2]
void jeod::Quaternion::compute_left_quat_second_deriv (const double quat[4], const double ang_vel[3], const double ang_acc[3], double qddot[4]) inline static
Compute the second time derivative of a left quaternion.
Parameters
[in] quat Quaternion as 4-vector
[in] ang_vel Angular velocity
Units: r/s
[in] ang_acc Angular acceleration
Units: r/s2
[out] qddot 2nd derivative as 4-vector
Definition at line 640 of file quat_inline.hh.
References jeod::Vector3::cross_incr(), jeod::Vector3::dot(), jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and jeod::Vector3::vmagsq().
compute_slerp()
Quaternion jeod::Quaternion::compute_slerp (Quaternion & q1, Quaternion & q2, const double T) static
Compute the minimum interpolation quaternion between a start quarternion and end quaternion.
Parameters
[in] q1 Starting quaternion
[in] q2 Ending quaternion
[in] T Interpolation coefficient between 0.0 and 1.0 representing a rotational scale factor between the intial and final quaternion. When the compute_slerp method is used in a loop to rotate an object from a start and end orientation, a smaller step or change in T results in a smoother object rotation
Definition at line 99 of file quat.cc.
References jeod::Numerical::compare_exact(), jeod::Vector3::dot(), jeod::MessageHandler::fail(), normalize(), scalar, QuatMessages::undefined, and vector.
conjugate() [1/2]
void jeod::Quaternion::conjugate (void) inline
Replace the quaternion with its conjugate.
Definition at line 261 of file quat_inline.hh.
References jeod::Vector3::negate(), and vector.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::MassPoint::compute_pred_rel_state(), jeod::RefFrame::compute_relative_state(), jeod::MassPointInit::initialize_mass_point(), jeod::MassPointState::negate(), jeod::RefFrameState::negate(), and jeod::DynBody::set_attitude_right_quaternion().
conjugate() [2/2]
void jeod::Quaternion::conjugate (Quaternion & quat) const inline
Form the conjugate of a quaternion, leaving original intact.
Parameters
[out] quat Conjugated quaternion
Definition at line 273 of file quat_inline.hh.
References jeod::Vector3::negate(), scalar, and vector.
conjugate_multiply() [1/2]
void jeod::Quaternion::conjugate_multiply (const Quaternion & quat, Quaternion & prod) const inline
Post-multiply this quaternion's conjugate by another quaternion: prod = conj(this) * quat.
Parameters
[in] quat Right multiplicand
[out] prod Quaternion product
Definition at line 331 of file quat_inline.hh.
References jeod::Vector3::cross_decr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_decr(), and vector.
Referenced by jeod::DynBody::compute_derived_state_reverse(), jeod::DynBody::compute_state_elements_reverse(), jeod::EphemerisZXZOrientation::propagate(), and jeod::DynBody::update_integrated_state().
conjugate_multiply() [2/2]
void jeod::Quaternion::conjugate_multiply (const Quaternion & quat) inline
Post-multiply this quaternion's conjugate by another quaternion: this = conj(this) * quat.
Parameters
[in] quat Right multiplicand
Definition at line 349 of file quat_inline.hh.
References jeod::Vector3::cross(), jeod::Vector3::decr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and vector.
copy_from()
void jeod::Quaternion::copy_from (const double arr[4]) inline
Copy a quaternion from a four vector, with the scalar part of the quaternion in arr[0] and the vector part in arr[1] to arr[3].
Parameters
[in] arr Quaternion source
Definition at line 155 of file quat_inline.hh.
References scalar, and vector.
Referenced by Quaternion().
copy_to()
void jeod::Quaternion::copy_to (double arr[4]) const inline
Copy a quaternion to a four vector, with the scalar part copied to arr[0] and the vector part to arr[1] to arr[3].
Parameters
[out] arr Copy of quaternion
Definition at line 138 of file quat_inline.hh.
References scalar, and vector.
eigen_compare()
void jeod::Quaternion::eigen_compare (const Quaternion & quat, double * eigen_angle, double eigen_axis[3]) const inline
Compute eigen decomposition of this*conj(quat).
Parameters
[in] quat Quaternion to compare to
[out] eigen_angle Eigen angle
Units: r
[out] eigen_axis Eigen axis
Definition at line 563 of file quat_inline.hh.
References left_quat_to_eigen_rotation(), and multiply_conjugate().
Referenced by jeod::CheckItem::within_eigen_tolerance().
left_quat_from_eigen_rotation()
void jeod::Quaternion::left_quat_from_eigen_rotation (double eigen_angle, const double eigen_axis[3]) inline
Construct the quaternion corresponding to an eigen rotation.
Parameters
[in] eigen_angle Eigen angle
Units: r
[in] eigen_axis Eigen axis
Definition at line 171 of file quat_inline.hh.
References scalar, jeod::Vector3::scale(), and vector.
Referenced by jeod::Orientation::compute_quaternion().
left_quat_from_transformation()
void jeod::Quaternion::left_quat_from_transformation (const double T[3][3])
Compute the parent-to-child left quaternion from the input transformation matrix.
Assumptions and Limitations
Matrix is orthonormal.
Parameters
[in] T Transformation matrix
Definition at line 118 of file quat_from_mat.cc.
References scalar, and vector.
Referenced by jeod::DynBody::attach_to_frame(), jeod::MassPointState::compute_quaternion(), jeod::RefFrameRot::compute_quaternion(), jeod::Orientation::compute_quaternion(), Quaternion(), jeod::DynBody::set_attitude_matrix(), and jeod::MassPointState::update_orientation().
left_quat_to_eigen_rotation()
void jeod::Quaternion::left_quat_to_eigen_rotation (double * eigen_angle, double eigen_axis[3]) const
Compute the eigen rotation corresponding to a quaternion.
Assumptions and Limitations
Quaternion is normalized.
Parameters
[out] eigen_angle Eigen angle
Units: r
[out] eigen_axis Eigen axis
Definition at line 49 of file quat_to_eigenrot.cc.
References jeod::Vector3::copy(), jeod::Vector3::initialize(), jeod::Vector3::negate(), scalar, jeod::Vector3::scale(), vector, and jeod::Vector3::vmag().
Referenced by jeod::Orientation::compute_eigen_rotation(), and eigen_compare().
left_quat_to_transformation()
void jeod::Quaternion::left_quat_to_transformation (double T[3][3]) const
Compute the parent-to-child transformation matrix from the parent-to-child left quaternion.
Assumptions and Limitations
Quaternion is normalized.
Parameters
[out] T Transformation matrix
Definition at line 84 of file quat_to_mat.cc.
References scalar, jeod::Vector3::scale(), jeod::Vector3::sum(), and vector.
Referenced by jeod::Orientation::compute_euler_angles(), jeod::MassPoint::compute_pred_rel_state(), jeod::DynBody::compute_ref_point_transform(), jeod::MassPoint::compute_state_wrt_pred(), jeod::Orientation::compute_transform(), jeod::MassPointState::compute_transformation(), jeod::RefFrameRot::compute_transformation(), jeod::StructureIntegratedDynBody::rot_integ(), jeod::DynBody::rot_integ(), jeod::DynBody::set_attitude_left_quaternion(), jeod::DynBody::set_attitude_right_quaternion(), jeod::DynBody::set_state(), and jeod::MassPointState::update_orientation().
left_quat_transform()
void jeod::Quaternion::left_quat_transform (const double vec_in[3], double vec_out[3]) const inline
Transform a vector.
Parameters
[in] vec_in Vector to be transformed
[out] vec_out Transformed vector
Definition at line 536 of file quat_inline.hh.
References jeod::Vector3::cross(), jeod::Vector3::dot(), jeod::Vector3::incr(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and vector.
make_identity()
void jeod::Quaternion::make_identity (void) inline
Make the quaternion represent an identity transform.
Definition at line 124 of file quat_inline.hh.
References jeod::Vector3::initialize(), scalar, and vector.
Referenced by jeod::RefFrameRot::initialize(), jeod::MassPointState::initialize_mass_point(), and jeod::MassPointState::negate().
multiply() [1/2]
void jeod::Quaternion::multiply (const Quaternion & quat, Quaternion & prod) const inline
Post-multiply this quaternion by another quaternion: prod = this * quat.
Parameters
[in] quat Right multiplicand
[out] prod Quaternion product
Definition at line 289 of file quat_inline.hh.
References jeod::Vector3::cross_incr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and vector.
Referenced by jeod::MassBody::attach_update_properties(), jeod::DynBody::compute_derived_state_forward(), jeod::Orientation::compute_quaternion_from_euler_angles(), jeod::DynBody::compute_state_elements_forward(), jeod::MassPoint::compute_state_wrt_pred(), jeod::MassPointState::incr_left(), jeod::RefFrameState::incr_left(), and jeod::MassBody::reattach().
multiply() [2/2]
void jeod::Quaternion::multiply (const Quaternion & quat) inline
Post-multiply this quaternion by another quaternion: this = this * quat.
Parameters
[in] quat Right multiplicand
Definition at line 307 of file quat_inline.hh.
References jeod::Vector3::cross(), jeod::Vector3::dot(), jeod::Vector3::incr(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and vector.
multiply_conjugate() [1/2]
void jeod::Quaternion::multiply_conjugate (const Quaternion & quat, Quaternion & prod) const inline
Post-multiply this quaternion by another's conjugate: prod = this * conj(quat).
Parameters
[in] quat Right multiplicand
[out] prod Quaternion product
Definition at line 373 of file quat_inline.hh.
References jeod::Vector3::cross_decr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_decr(), and vector.
Referenced by jeod::MassBody::attach_update_properties(), jeod::DynBody::compute_ref_point_transform(), jeod::MassPointState::decr_left(), jeod::RefFrameState::decr_left(), eigen_compare(), and jeod::MassBody::reattach().
multiply_conjugate() [2/2]
void jeod::Quaternion::multiply_conjugate (const Quaternion & quat) inline
Post-multiply this quaternion by another's conjugate: this = this * conj(quat).
Parameters
[in] quat Right multiplicand
Definition at line 391 of file quat_inline.hh.
References jeod::Vector3::cross(), jeod::Vector3::decr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_decr(), and vector.
multiply_left() [1/2]
void jeod::Quaternion::multiply_left (const Quaternion & quat, Quaternion & prod) const inline
Pre-multiply this quaternion by another quaternion: prod = quat * this.
Parameters
[in] quat Left multiplicand
[out] prod Quaternion product
Definition at line 415 of file quat_inline.hh.
References jeod::Vector3::cross_incr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and vector.
Referenced by compute_left_quat_second_deriv(), jeod::MassPointState::incr_right(), and jeod::RefFrameState::incr_right().
multiply_left() [2/2]
void jeod::Quaternion::multiply_left (const Quaternion & quat) inline
Pre-multiply this quaternion by another quaternion: this = quat * this.
Parameters
[in] quat Left multiplicand
Definition at line 433 of file quat_inline.hh.
References jeod::Vector3::cross(), jeod::Vector3::dot(), jeod::Vector3::incr(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), and vector.
multiply_left_conjugate() [1/2]
void jeod::Quaternion::multiply_left_conjugate (const Quaternion & quat, Quaternion & prod) const inline
Pre-multiply this quaternion by another's conjugate: prod = conj(quat) * this.
Parameters
[in] quat Left multiplicand
[out] prod Quaternion product
Definition at line 457 of file quat_inline.hh.
References jeod::Vector3::cross_decr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_decr(), and vector.
Referenced by jeod::MassPoint::compute_pred_rel_state(), jeod::MassPointState::decr_right(), and jeod::RefFrameState::decr_right().
multiply_left_conjugate() [2/2]
void jeod::Quaternion::multiply_left_conjugate (const Quaternion & quat) inline
Pre-multiply this quaternion by another's conjugate: this = conj(quat) * this.
Parameters
[in] quat Left multiplicand
Definition at line 475 of file quat_inline.hh.
References jeod::Vector3::cross(), jeod::Vector3::decr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), jeod::Vector3::scale_decr(), and vector.
multiply_vector_left()
void jeod::Quaternion::multiply_vector_left (const double vec[3], Quaternion & prod) const inline
Pre-multiply this quaternion by a pure imaginary quaternion, the latter represented by a vector: prod = [0, vec] * quat.
Parameters
[in] vec Right multiplicand
[out] prod Quaternion product
Definition at line 500 of file quat_inline.hh.
References jeod::Vector3::cross_incr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), and vector.
Referenced by compute_left_quat_deriv().
multiply_vector_right()
void jeod::Quaternion::multiply_vector_right (const double vec[3], Quaternion & prod) const inline
Post-multiply this quaternion by a pure imaginary quaternion, the latter represented by a vector: prod = quat * [0, vec].
Parameters
[in] vec Right multiplicand
[out] prod Quaternion product
Definition at line 519 of file quat_inline.hh.
References jeod::Vector3::cross_incr(), jeod::Vector3::dot(), scalar, jeod::Vector3::scale(), and vector.
norm_sq()
double jeod::Quaternion::norm_sq (void) const inline
Compute the square of the norm of the quaternion.
Returns
Square of the norm of the quaternion
Definition at line 221 of file quat_inline.hh.
References scalar, vector, and jeod::Vector3::vmagsq().
Referenced by jeod::CheckItem::is_unit(), normalize(), and normalize_integ().
normalize() [1/2]
void jeod::Quaternion::normalize (void)
Normalize the quaternion, making the scalar part of the quaternion non-negative.
Definition at line 48 of file quat_norm.cc.
References norm_sq(), scalar, and scale().
Referenced by jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::MassPoint::compute_pred_rel_state(), jeod::Orientation::compute_quaternion_from_euler_angles(), jeod::DynBody::compute_ref_point_transform(), compute_slerp(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPoint::compute_state_wrt_pred(), jeod::MassPointState::decr_left(), jeod::RefFrameState::decr_left(), jeod::MassPointState::decr_right(), jeod::RefFrameState::decr_right(), jeod::MassPointState::incr_left(), jeod::RefFrameState::incr_left(), jeod::MassPointState::incr_right(), jeod::RefFrameState::incr_right(), normalize(), and jeod::DynBody::update_integrated_state().
normalize() [2/2]
void jeod::Quaternion::normalize (Quaternion & quat) const inline
Form the normalized quaternion, leaving original intact.
Parameters
[out] quat Normalized quaternion
Definition at line 234 of file quat_inline.hh.
References normalize().
normalize_integ() [1/3]
void jeod::Quaternion::normalize_integ (void)
Normalize the quaternion, but do not make the scalar part non-negative.
Definition at line 82 of file quat_norm.cc.
References norm_sq(), and scale().
Referenced by normalize_integ(), jeod::EphemerisZXZOrientation::propagate(), jeod::StructureIntegratedDynBody::rot_integ(), and jeod::DynBody::rot_integ().
normalize_integ() [2/3]
void jeod::Quaternion::normalize_integ (Quaternion & quat) const inline
Form the normalized quaternion, leaving original intact.
Parameters
[out] quat Normalized quaternion
Definition at line 248 of file quat_inline.hh.
References normalize_integ().
normalize_integ() [3/3]
void jeod::Quaternion::normalize_integ (double quat[4]) static
Normalize the quaternion, but do not make the scalar part non-negative.
Parameters
quat Quaternion to be normalized.
Definition at line 106 of file quat_norm.cc.
References jeod::Numerical::square(), and jeod::Vector3::vmagsq().
operator double *()
jeod::Quaternion::operator double * (void) inline
Make a quaternion look like a double array.
Definition at line 134 of file quat.hh.
References scalar.
scale() [1/2]
void jeod::Quaternion::scale (const double fact) inline
Scale the quaternion by a real.
Parameters
[in] fact Scale factor
Definition at line 192 of file quat_inline.hh.
References scalar, jeod::Vector3::scale(), and vector.
Referenced by normalize(), and normalize_integ().
scale() [2/2]
void jeod::Quaternion::scale (const double fact, Quaternion & quat) const inline
Scale the quaternion by a real, leaving original intact.
Parameters
[in] fact Scale factor
[out] quat Scaled quaternion
Definition at line 206 of file quat_inline.hh.
References scalar, jeod::Vector3::scale(), and vector.
set_to_zero()
void jeod::Quaternion::set_to_zero (void) inline
Set all components of the quaternion to zero.
Definition at line 112 of file quat_inline.hh.
References jeod::Vector3::initialize(), scalar, and vector.
Friends And Related Function Documentation
init_attrjeod__Quaternion
void init_attrjeod__Quaternion () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file quat.hh.
Field Documentation
scalar
double jeod::Quaternion::scalar
The scalar, or real, part of the quaternion.
trick_units(–)
Definition at line 97 of file quat.hh.
Referenced by jeod::MassBody::attach_to(), jeod::RefFrame::compute_position_from(), jeod::Orientation::compute_quaternion_from_euler_angles(), compute_slerp(), conjugate(), conjugate_multiply(), copy_from(), copy_to(), jeod::MassPointState::decr_left(), jeod::RefFrameState::decr_left(), jeod::MassPointState::decr_right(), jeod::RefFrameState::decr_right(), jeod::MassPointState::incr_left(), jeod::RefFrameState::incr_left(), jeod::MassPointState::incr_right(), jeod::RefFrameState::incr_right(), jeod::CheckItem::is_identity(), left_quat_from_eigen_rotation(), left_quat_from_transformation(), left_quat_to_eigen_rotation(), left_quat_to_transformation(), left_quat_transform(), make_identity(), multiply(), multiply_conjugate(), multiply_left(), multiply_left_conjugate(), multiply_vector_left(), multiply_vector_right(), jeod::MassPointState::negate(), jeod::RefFrameState::negate(), norm_sq(), normalize(), operator double *(), jeod::EphemerisZXZOrientation::propagate(), Quaternion(), scale(), set_to_zero(), and jeod::EphemerisZXZOrientation::update().
vector
double jeod::Quaternion::vector[3]
The vectorial, or imaginary, part of the quaternion.
trick_units(–)
Definition at line 102 of file quat.hh.
Referenced by jeod::MassBody::attach_to(), jeod::Orientation::compute_quaternion_from_euler_angles(), compute_slerp(), conjugate(), conjugate_multiply(), copy_from(), copy_to(), jeod::CheckItem::is_identity(), left_quat_from_eigen_rotation(), left_quat_from_transformation(), left_quat_to_eigen_rotation(), left_quat_to_transformation(), left_quat_transform(), make_identity(), multiply(), multiply_conjugate(), multiply_left(), multiply_left_conjugate(), multiply_vector_left(), multiply_vector_right(), norm_sq(), jeod::EphemerisZXZOrientation::propagate(), Quaternion(), scale(), set_to_zero(), and jeod::EphemerisZXZOrientation::update().
The documentation for this class was generated from the following files:
quat.hh
quat_inline.hh
quat.cc
quat_from_mat.cc
quat_norm.cc
quat_to_eigenrot.cc
quat_to_mat.cc