JEOD: jeod::EulerDerivedState Class Reference
jeod::EulerDerivedState Class Reference
The class used for deriving the Euler angle representation of a subject DynBody's attitude.
#include <euler_derived_state.hh>
Public Member Functions
EulerDerivedState ()
Construct a EulerDerivedState object.
~EulerDerivedState () override
Destruct a EulerDerivedState object.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a EulerDerivedState.
virtual void initialize (RefFrame &ref_frame, DynBody &subject_body, DynManager &dyn_manager)
Begin initialization of a EulerDerivedState.
void update (void) override
Compute the Euler angles.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
Orientation::EulerSequence sequence
Euler angle sequence specification.
double ref_body_angles [3]
Euler angles from reference frame.
double body_ref_angles [3]
Euler angles to reference frame.
RefFrameState rel_state
The relative state of the body.
Data Fields inherited from jeod::DerivedState
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Attributes
RefFrame * rel_frame
Reference frame from which to compute the Euler angle attitude.
Protected Attributes inherited from jeod::DerivedState
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
EulerDerivedState (const EulerDerivedState &)
EulerDerivedState & operator= (const EulerDerivedState &)
Friends
class InputProcessor
void init_attrjeod__EulerDerivedState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Detailed Description
The class used for deriving the Euler angle representation of a subject DynBody's attitude.
Definition at line 89 of file euler_derived_state.hh.
Constructor & Destructor Documentation
EulerDerivedState() [1/2]
jeod::EulerDerivedState::EulerDerivedState (void)
Construct a EulerDerivedState object.
Definition at line 48 of file euler_derived_state.cc.
References body_ref_angles, and ref_body_angles.
~EulerDerivedState()
jeod::EulerDerivedState::~EulerDerivedState (void) override
Destruct a EulerDerivedState object.
Definition at line 67 of file euler_derived_state.cc.
References rel_frame, and jeod::Subscription::unsubscribe().
EulerDerivedState() [2/2]
jeod::EulerDerivedState::EulerDerivedState (const EulerDerivedState &) private
Member Function Documentation
initialize() [1/2]
void jeod::EulerDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of a EulerDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] subject_body Subject body.
[in,out] dyn_manager Dynamics manager.
Reimplemented from jeod::DerivedState.
Definition at line 87 of file euler_derived_state.cc.
References jeod::DerivedState::initialize().
initialize() [2/2]
void jeod::EulerDerivedState::initialize (RefFrame & ref_frame, DynBody & subject_body, DynManager & dyn_manager) virtual
Begin initialization of a EulerDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in] ref_frame Reference frame for angles.
[in,out] subject_body Subject body.
[in,out] dyn_manager Dynamics manager.
Definition at line 107 of file euler_derived_state.cc.
References jeod::DerivedState::initialize(), rel_frame, and jeod::Subscription::subscribe().
operator=()
EulerDerivedState& jeod::EulerDerivedState::operator= (const EulerDerivedState &) private
update()
void jeod::EulerDerivedState::update (void) override virtual
Compute the Euler angles.
Assumptions and Limitations
Depends upon the Trick Euler angle math macros and routines.
Reimplemented from jeod::DerivedState.
Definition at line 130 of file euler_derived_state.cc.
References body_ref_angles, jeod::DynBody::composite_body, jeod::Orientation::compute_euler_angles_from_matrix(), jeod::RefFrame::compute_relative_state(), jeod::RefFrameState::copy(), jeod::RefFrame::get_parent(), ref_body_angles, rel_frame, rel_state, jeod::RefFrameState::rot, sequence, jeod::RefFrame::state, jeod::DerivedState::subject, jeod::RefFrameRot::T_parent_this, jeod::Matrix3x3::transpose(), and jeod::DerivedState::update().
Friends And Related Function Documentation
init_attrjeod__EulerDerivedState
void init_attrjeod__EulerDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file euler_derived_state.hh.
Field Documentation
body_ref_angles
double jeod::EulerDerivedState::body_ref_angles[3]
Euler angles to reference frame.
trick_units(rad)
Definition at line 111 of file euler_derived_state.hh.
Referenced by EulerDerivedState(), and update().
ref_body_angles
double jeod::EulerDerivedState::ref_body_angles[3]
Euler angles from reference frame.
trick_units(rad)
Definition at line 106 of file euler_derived_state.hh.
Referenced by EulerDerivedState(), and update().
rel_frame
RefFrame* jeod::EulerDerivedState::rel_frame protected
Reference frame from which to compute the Euler angle attitude.
If this is NULL then the body's parent frame is used.trick_units(–)
Definition at line 127 of file euler_derived_state.hh.
Referenced by initialize(), update(), and ~EulerDerivedState().
rel_state
RefFrameState jeod::EulerDerivedState::rel_state
The relative state of the body.
This is just a copy of the body's state when the relative frame is the parent frame. This is a computed relative state when the relative frame is not the parent frame.trick_units(–)
Definition at line 118 of file euler_derived_state.hh.
Referenced by update().
sequence
Orientation::EulerSequence jeod::EulerDerivedState::sequence
Euler angle sequence specification.
trick_units(–)
Definition at line 101 of file euler_derived_state.hh.
Referenced by update().
The documentation for this class was generated from the following files:
euler_derived_state.hh
euler_derived_state.cc