JEOD: jeod::GaussJacksonFirstOrderODEIntegrator Class Reference
jeod::GaussJacksonFirstOrderODEIntegrator Class Reference
Integrates a first order ODE using the summed Adams technique that is embedded within the Gauss-Jackson technique.
#include <gauss_jackson_first_order_ode_integrator.hh>
Private Member Functions
JEOD_MAKE_SIM_INTERFACES(jeod, GaussJacksonFirstOrderODEIntegrator) public ~GaussJacksonFirstOrderODEIntegrator () override=default
GaussJacksonFirstOrderODEIntegrator (const er7_utils::IntegratorConstructor &priming_constructor, GaussJacksonIntegrationControls &controls, unsigned int size_in, er7_utils::IntegrationControls &priming_controls)
Non-default constructor.
GaussJacksonFirstOrderODEIntegrator (const GaussJacksonFirstOrderODEIntegrator &src)
Copy constructor.
GaussJacksonFirstOrderODEIntegrator & operator= (GaussJacksonFirstOrderODEIntegrator src)
Assignment operator.
void swap (GaussJacksonFirstOrderODEIntegrator &other)
Non-throwing swap.
er7_utils::FirstOrderODEIntegrator * create_copy () const override
Replicate this.
void reset_integrator () override
Reset the integrator.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage, const double *ER7_UTILS_RESTRICT deriv, double *ER7_UTILS_RESTRICT state) override
Integrate.
void swap (GaussJacksonIntegratorBase &other)
Non-throwing swap.
Additional Inherited Members
Public Member Functions inherited from jeod::GaussJacksonIntegratorBase< State, Primer >
GaussJacksonIntegratorBase ()=default
Default constructor.
GaussJacksonIntegratorBase (const er7_utils::IntegratorConstructor &priming_constructor, const GaussJacksonIntegrationControls &controls, unsigned int size_in, er7_utils::IntegrationControls &priming_controls)
Non-default constructor.
GaussJacksonIntegratorBase (const GaussJacksonIntegratorBase &src)
Copy constructor.
~GaussJacksonIntegratorBase ()
Destructor.
GaussJacksonIntegratorBase & operator= (const GaussJacksonIntegratorBase &)=delete
Data Fields inherited from jeod::GaussJacksonIntegratorBase< State, Primer >
const GaussJacksonCoeffs * coeff {}
The summed Adams and Gauss-Jackson coefficients, in ordinate form.
const GaussJacksonStateMachine * state_machine {}
The Gauss-Jackson state machine.
Primer * primer {}
The integrator used to prime the Gauss-Jackson integration process.
State init_state
The state at the time of the last reset.
State delinv
Inverse backward differences.
State corrector_sum
Speed hack for the corrector.
er7_utils::DoubleTwoDArray acc_hist
Acceleration history.
er7_utils::DoubleTwoDArray pos_hist
Position history (or velocity history in case of a first order ODE).
double relative_tolerance {}
Number that indicates the allowable relative difference for two states to be considered converged.
double absolute_tolerance {}
Number that indicates the allowable absolute difference for two states to be considered converged.
double velocity_corrector {}
Correction coefficient for the first integral (velocity).
double position_corrector {}
Correction coefficient for the second integral (position).
GaussJacksonStateMachine::FsmState fsm_state {GaussJacksonStateMachine::Reset}
Finite state machine state.
unsigned int max_history_size {}
Maximum history size.
unsigned int initial_order {}
Initial order.
unsigned int order {}
Current order.
unsigned int size {}
State size.
unsigned int history_length {}
Current history length.
Protected Member Functions inherited from jeod::GaussJacksonIntegratorBase< State, Primer >
void base_reset ()
Reset the integrator.
er7_utils::IntegratorResult base_integrate (double dyn_dt, unsigned int target_stage, const double *deriv, State state)
Propagate state to the specified target_stage.
void swap (GaussJacksonIntegratorBase &other)
Non-throwing swap.
Detailed Description
Integrates a first order ODE using the summed Adams technique that is embedded within the Gauss-Jackson technique.
Definition at line 79 of file gauss_jackson_first_order_ode_integrator.hh.
Constructor & Destructor Documentation
~GaussJacksonFirstOrderODEIntegrator()
JEOD_MAKE_SIM_INTERFACES (jeod, GaussJacksonFirstOrderODEIntegrator) public jeod::GaussJacksonFirstOrderODEIntegrator::~GaussJacksonFirstOrderODEIntegrator () override private default
GaussJacksonFirstOrderODEIntegrator() [1/2]
jeod::GaussJacksonFirstOrderODEIntegrator::GaussJacksonFirstOrderODEIntegrator (const er7_utils::IntegratorConstructor & priming_constructor, GaussJacksonIntegrationControls & controls, unsigned int size_in, er7_utils::IntegrationControls & priming_controls) inline private
Non-default constructor.
Parameters
priming_constructor Integrator constructor for the technique used during priming.
controls The Gauss-Jackson integration controls that drives this state integrator.
size_in State size.
priming_controls Integration controls used during priming.
Definition at line 98 of file gauss_jackson_first_order_ode_integrator.hh.
GaussJacksonFirstOrderODEIntegrator() [2/2]
jeod::GaussJacksonFirstOrderODEIntegrator::GaussJacksonFirstOrderODEIntegrator (const GaussJacksonFirstOrderODEIntegrator & src) inline private
Copy constructor.
Definition at line 110 of file gauss_jackson_first_order_ode_integrator.hh.
Member Function Documentation
create_copy()
er7_utils::FirstOrderODEIntegrator* jeod::GaussJacksonFirstOrderODEIntegrator::create_copy () const inline override private
Replicate this.
Definition at line 137 of file gauss_jackson_first_order_ode_integrator.hh.
integrate()
er7_utils::IntegratorResult jeod::GaussJacksonFirstOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double *ER7_UTILS_RESTRICT deriv, double *ER7_UTILS_RESTRICT state) inline override private
Integrate.
Definition at line 153 of file gauss_jackson_first_order_ode_integrator.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate().
Referenced by jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::integrate().
operator=()
GaussJacksonFirstOrderODEIntegrator& jeod::GaussJacksonFirstOrderODEIntegrator::operator= (GaussJacksonFirstOrderODEIntegrator src) inline private
Assignment operator.
Definition at line 119 of file gauss_jackson_first_order_ode_integrator.hh.
References swap().
reset_integrator()
void jeod::GaussJacksonFirstOrderODEIntegrator::reset_integrator () inline override private
Reset the integrator.
Definition at line 145 of file gauss_jackson_first_order_ode_integrator.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::base_reset().
Referenced by jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::reset_integrator().
swap() [1/2]
void jeod::GaussJacksonFirstOrderODEIntegrator::swap (GaussJacksonFirstOrderODEIntegrator & other) inline private
Non-throwing swap.
Definition at line 128 of file gauss_jackson_first_order_ode_integrator.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
Referenced by operator=(), and jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::swap().
swap() [2/2]
void jeod::GaussJacksonIntegratorBase< State, Primer >::swap inline private
Non-throwing swap.
Parameters
other Item whose contents are to be swapped with this.
Definition at line 397 of file gauss_jackson_integrator_base.hh.
The documentation for this class was generated from the following file:
gauss_jackson_first_order_ode_integrator.hh