JEOD: jeod::GaussJacksonRationalCoefficients Class Reference
jeod::GaussJacksonRationalCoefficients Class Reference
Contains a set of Adams or Stormer-Cowell coefficients.
#include <gauss_jackson_rational_coeffs.hh>
Public Member Functions
GaussJacksonRationalCoefficients ()=default
Default constructor.
void configure_adams_corrector (unsigned int nelem)
Configure the coefficients as an Adams corrector in difference form.
GaussJacksonRationalCoefficients construct_stormer_cowell_corrector () const
Construct a GaussJacksonRationalCoefficients that contains the Stormer-Cowell corrector coefficients.
GaussJacksonRationalCoefficients construct_predictor () const
Construct a GaussJacksonRationalCoefficients that contains a set of predictor coefficients.
void convert_to_ordinate_form (er7_utils::NChooseM &n_choose_m, double *result) const
Convert the coefficients to ordinate form.
void discard_extra_terms (unsigned int nfront, unsigned int nback)
Discard the specified number of terms from the front and back of the coefficients array.
void displace_back ()
Displace the corrector coefficients back one time step.
Data Fields
std::vector< er7_utils::Ratio128 > coefficients
The coefficients.
Friends
class InputProcessor
void init_attrjeod__GaussJacksonRationalCoefficients ()
Detailed Description
Contains a set of Adams or Stormer-Cowell coefficients.
Definition at line 87 of file gauss_jackson_rational_coeffs.hh.
Constructor & Destructor Documentation
GaussJacksonRationalCoefficients()
jeod::GaussJacksonRationalCoefficients::GaussJacksonRationalCoefficients () default
Default constructor.
Member Function Documentation
configure_adams_corrector()
void jeod::GaussJacksonRationalCoefficients::configure_adams_corrector (unsigned int nelem)
Configure the coefficients as an Adams corrector in difference form.
Parameters
nelem The number of elements in the coefficients vector.
Definition at line 36 of file gauss_jackson_rational_coeffs.cc.
References coefficients.
Referenced by jeod::GaussJacksonCoeffs::compute_coeffs().
construct_predictor()
GaussJacksonRationalCoefficients jeod::GaussJacksonRationalCoefficients::construct_predictor () const
Construct a GaussJacksonRationalCoefficients that contains a set of predictor coefficients.
The coefficients are assumed to be configured as either Adams or Stormer-Cowell corrector coefficients.
Returns
A GaussJacksonRationalCoefficients object with the coefficients configured as Adams or Stormer-Cowell predictor coefficients.
Definition at line 82 of file gauss_jackson_rational_coeffs.cc.
References coefficients.
Referenced by jeod::GaussJacksonCoeffs::compute_coeffs().
construct_stormer_cowell_corrector()
GaussJacksonRationalCoefficients jeod::GaussJacksonRationalCoefficients::construct_stormer_cowell_corrector () const
Construct a GaussJacksonRationalCoefficients that contains the Stormer-Cowell corrector coefficients.
The coefficients are assumed to be configured as Adams coefficients in difference form.
Returns
A GaussJacksonRationalCoefficients object with the coefficients configured as Stormer-Cowell corrector coefficients.
Definition at line 58 of file gauss_jackson_rational_coeffs.cc.
References coefficients.
Referenced by jeod::GaussJacksonCoeffs::compute_coeffs().
convert_to_ordinate_form()
void jeod::GaussJacksonRationalCoefficients::convert_to_ordinate_form (er7_utils::NChooseM & n_choose_m, double * result) const
Convert the coefficients to ordinate form.
Parameters
n_choose_m An NChooseM object that computes N choose M.
result The output ordinate form coefficients.
Definition at line 105 of file gauss_jackson_rational_coeffs.cc.
References coefficients.
Referenced by jeod::GaussJacksonCoeffs::compute_coeffs().
discard_extra_terms()
void jeod::GaussJacksonRationalCoefficients::discard_extra_terms (unsigned int nfront, unsigned int nback)
Discard the specified number of terms from the front and back of the coefficients array.
Parameters
nfront The number of terms to be discarded from the front of the coefficients vector.
nback The number of terms to be discarded from the back of the coefficients vector.
Definition at line 137 of file gauss_jackson_rational_coeffs.cc.
References coefficients.
Referenced by jeod::GaussJacksonCoeffs::compute_coeffs().
displace_back()
void jeod::GaussJacksonRationalCoefficients::displace_back ()
Displace the corrector coefficients back one time step.
Definition at line 150 of file gauss_jackson_rational_coeffs.cc.
References coefficients.
Referenced by jeod::GaussJacksonCoeffs::compute_coeffs().
Friends And Related Function Documentation
init_attrjeod__GaussJacksonRationalCoefficients
void init_attrjeod__GaussJacksonRationalCoefficients () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file gauss_jackson_rational_coeffs.hh.
Field Documentation
coefficients
std::vector<er7_utils::Ratio128> jeod::GaussJacksonRationalCoefficients::coefficients
The coefficients.
trick_units(–)
Definition at line 93 of file gauss_jackson_rational_coeffs.hh.
Referenced by configure_adams_corrector(), construct_predictor(), construct_stormer_cowell_corrector(), convert_to_ordinate_form(), discard_extra_terms(), and displace_back().
The documentation for this class was generated from the following files:
gauss_jackson_rational_coeffs.hh
gauss_jackson_rational_coeffs.cc