JEOD: jeod::PairInteraction Class Reference
jeod::PairInteraction Class Reference abstract
Simple spring contact parameters.
#include <pair_interaction.hh>
Public Member Functions
PairInteraction ()
Default Constructor.
virtual ~PairInteraction ()
Destructor.
bool is_correct_interaction (ContactParams *subject_params, ContactParams *target_params)
Check a pair of contact params for a match to the ones defined for this pair_interaction.
virtual void calculate_forces (ContactFacet *subject, ContactFacet *target, RelativeDerivedState *rel_state, double *penetration_vector, double *rel_velocity)=0
Pure virtual function that is defined to calculate forces on facets in contact.
Data Fields
char * params_1
contact param type that defines this pair interaction.
char * params_2
contact param type that defines this pair interaction.
double friction_mag
magnitude of the friction force on the contact surfaces.
Private Member Functions
PairInteraction & operator= (const PairInteraction &rhs)
PairInteraction (const PairInteraction &rhs)
Friends
class InputProcessor
void init_attrjeod__PairInteraction ()
Detailed Description
Simple spring contact parameters.
Definition at line 85 of file pair_interaction.hh.
Constructor & Destructor Documentation
PairInteraction() [1/2]
jeod::PairInteraction::PairInteraction (void)
Default Constructor.
Definition at line 46 of file pair_interaction.cc.
~PairInteraction()
jeod::PairInteraction::~PairInteraction (void) virtual
Destructor.
Definition at line 60 of file pair_interaction.cc.
PairInteraction() [2/2]
jeod::PairInteraction::PairInteraction (const PairInteraction & rhs) private
Member Function Documentation
calculate_forces()
virtual void jeod::PairInteraction::calculate_forces (ContactFacet * subject, ContactFacet * target, RelativeDerivedState * rel_state, double * penetration_vector, double * rel_velocity) pure virtual
Pure virtual function that is defined to calculate forces on facets in contact.
Parameters
[in,out] subject subject of the relative state
[in,out] target target of the relative state
[in] rel_state relative state between subject and target in subject frame
[in] penetration_vector vector that characterises the interpenetration of the subject and the target
[in] rel_velocity relative velocity of the subject and the target in the subject frame
Implemented in jeod::SpringPairInteraction.
Referenced by jeod::LineContactPair::in_contact(), jeod::PointContactPair::in_contact(), and jeod::LinePointContactPair::in_contact().
is_correct_interaction()
bool jeod::PairInteraction::is_correct_interaction (ContactParams * subject_params, ContactParams * target_params)
Check a pair of contact params for a match to the ones defined for this pair_interaction.
Returns
bool
Parameters
[in] subject_params parameters of the subject
[in] target_params parameters of the target
Definition at line 74 of file pair_interaction.cc.
References jeod::FacetParams::name, params_1, and params_2.
operator=()
PairInteraction& jeod::PairInteraction::operator= (const PairInteraction & rhs) private
Friends And Related Function Documentation
init_attrjeod__PairInteraction
void init_attrjeod__PairInteraction () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file pair_interaction.hh.
Field Documentation
friction_mag
double jeod::PairInteraction::friction_mag
magnitude of the friction force on the contact surfaces.
trick_units(N)
Definition at line 103 of file pair_interaction.hh.
Referenced by jeod::SpringPairInteraction::calculate_forces().
params_1
char* jeod::PairInteraction::params_1
contact param type that defines this pair interaction.
trick_units(–)
Definition at line 94 of file pair_interaction.hh.
Referenced by is_correct_interaction().
params_2
char* jeod::PairInteraction::params_2
contact param type that defines this pair interaction.
trick_units(–)
Definition at line 98 of file pair_interaction.hh.
Referenced by is_correct_interaction().
The documentation for this class was generated from the following files:
pair_interaction.hh
pair_interaction.cc