JEOD: jeod Namespace Reference
jeod Namespace Reference
Models » Dynamics » Body ActionModels » Dynamics » | Derived StateModels » Dynamics » | Dynamic BodyModels » Dynamics » | Dynamics ManagerModels » Dynamics » | MassModels » Dynamics » | Relative KinematicsModels » Environment » Atmosphere » | Base AtmosphereModels » Environment » | AtmosphereModels » Environment » | Earth LightingModels » Environment » Ephemerides » | De4xxEphemModels » Environment » Ephemerides » | EphemInterfaceModels » Environment » Ephemerides » | EphemItemModels » Environment » Ephemerides » | EphemManagerModels » Environment » Ephemerides » | PropagatedPlanetModels » Environment » | GravityModels » Environment » | PlanetModels » Environment » RNP » | Generic RNPModels » Environment » RNP » | RNP J2000Models » Environment » RNP » | RNP MarsModels » Environment » | SpiceModels » Environment » | TimeModels » Experimental » | ConstraintsModels » Experimental » | MathModels » Experimental » | MessageModels » Interactions » | AerodynamicsModels » Interactions » | ContactModels » Interactions » | Gravity TorqueModels » Interactions » | Radiation PressureModels » Interactions » | Thermal RiderModels » Utilities » | ContainerModels » Utilities » Integration » | Gauss JacksonModels » Utilities » | IntegrationModels » Utilities » Integration » | LSODEModels » Utilities » | LVLH FrameModels » Utilities » | MathModels » Utilities » | MemoryModels » Utilities » Memory » | Support classesModels » Utilities » | MessageModels » Utilities » | Model TemplateModels » Utilities » | Named ItemModels » Utilities » | Orbital ElementsModels » Utilities » | OrientationModels » Utilities » Planet Fixed » | North East DownModels » Utilities » Planet Fixed » | Planet Fixed PositionModels » Utilities » | QuaternionModels » Utilities » | Reference FramesModels » Utilities » | Simulation InterfaceModels » Utilities » | Surface ModelTools » | TestHarness
Namespace jeod.
Namespaces
De4xxBase
Defines enumerations used in the DE4xx ephemeris model.
Data Structures
class ActivateInterface
A class that inherits from the ActivateInterface class must provide activate and deactivate methods.
class AeroDragEnum
Contains enumerations associated with aerodynamic drag.
class AeroDragParameters
Contains parameters associated with aerodynamic drag.
class AerodynamicDrag
The main class for calculating aerodynamic drag.
class AerodynamicsMessages
Messages associated with use of the aerodynamics model.
class AeroFacet
An aerodynamic interaction specific facet for use in the surface model.
class AeroParams
A base class for all aerodynamic parameters used in the surface model.
class AeroSurface
The aerodynamic specific interaction surface, for use with the surface model.
class AeroSurfaceFactory
The surface factory that creates an aerodynamic specific surface from a general surface.
class AltLatLongState
Specifies positional state in planetary altitude, latitude, and longitude.
class Atmosphere
A generic base class for atmospheres.
class AtmosphereMessages
Describes messages used in the Atmosphere model.
class AtmosphereState
A generic base class for atmosphere state, containing common atmosphere state parameters, i.e.
class BaseDynManager
The DynManager class augments the EphemManager with dynamics-related items.
class BaseEphemeridesManager
The EphemManager class augments the RefFrameManager with ephemeris-related items.
class BasePendulumModel
Abstract base class that defines interfaces needed to model a spherical pendulum as a constrained object.
class BasePlanet
A BasePlanet contains the base data needed to model a planet in JEOD.
class BaseRefFrameManager
The RefFrameManager class manages the reference frames in a simulation.
class BaseRotationalConstraint
Abstract base class that prescribes behaviors of a constraint related to transfer of angular momentum between a vehicle and a constrained object.
class BaseTranslationalConstraint
Abstract base class that prescribes behaviors of a constraint related to transfer of linear momentum between a vehicle and a constrained object.
class BasicJeodTrickSimInterface
The BasicJeodTrickSimInterface implements the required capabilities of the generic JeodSimulationInterface in a Trick simulation environment.
class BodyAction
BodyAction is the base class for the BodyAction model.
class BodyActionMessages
Specifies the message IDs used in the BodyAction model.
class BodyAttach
Provides the basic ability to attach one MassBody to another.
class BodyAttachAligned
Attaches a pair of MassBody objects at a pair of MassPoints.
class BodyAttachMatrix
Attaches a pair of MassBody objects using the offset+matrix attach mechanism.
class BodyDetach
Provides the basic ability to detach one MassBody from another.
class BodyDetachSpecific
Causes the subject body to detach from a specific body by severing the link immediately spawning from the detach_from body.
class BodyForceCollect
Serves as the collection point for forces and torques that act on a vehicle.
class BodyReattach
Alters the nature of an existing attachment.
class BodyRefFrame
Extend RefFrame to add coupling between the reference frame tree and the mass tree and to keep track of which state items have been set.
class BodyWrenchCollect
Serves as the collection point for wrenches that act on a vehicle.
class CheckItem
Provides several static methods for checking whether a computed value agrees with an expected value to within some tolerance.
class CheckPointInputManager
A CheckPointInputManager provides tools for reading a checkpoint file.
class CheckPointOutputManager
A CheckPointOutputManager provides the basic tools for writing a checkpoint file.
class CInterfaceForce
This class is deprecated.
class CInterfaceTorque
This class is deprecated.
class CmdlineParser
A CmdlineParser parses command line options.
class CollectForce
A CollectForce represents a collected force that acts on a vehicle.
class CollectTorque
A CollectTorque represents a collected torque that acts on a vehicle.
class ColorText
Defines methods that highlight key outputs from a unit test run.
class ColumnView
Represents a view into a column of an array.
class ConstrainedPointMass
A constrained point mass is a point mass that is constrained to more or less move with a DynBody object.
class ConstrainedRigidMass
A constrained rigid mass is a rigid body that is constrained to more or less move with a DynBody object.
class ConstraintComponent
Represents a single scalar constraint, either a pure force in a specific direction at a specific point or a pure torque in a specific direction, that acts on some vehicle.
class ConstraintFrame
A constraint frame is directly connected to a vehicle structural frame, which in turn is connected to a root vehicle structural frame.
class Contact
An base contact class for use in the surface model.
class ContactFacet
An contact interaction specific facet for use in the surface model.
class ContactMessages
Messages associated with use of the contact model.
class ContactPair
An base contact pair class for use in the contact model.
class ContactParams
A base class for all contact parameters used in the surface model.
class ContactSurface
The contact specific interaction surface, for use with the surface model.
class ContactSurfaceFactory
The surface factory that creates an contact specific surface from a general surface.
class ContactUtils
Utility string and math functions for the contact model.
class Cylinder
An cylinder implementation of Facet.
class De4xxEphemeris
The S_define-level class that provides planetary ephemerides.
class De4xxEphemItem
Describes a point modeled in a DE4xx ephemeris file.
class De4xxFile
Provides the ability to read and interpret a DE4xx ephemeris file.
class De4xxFileCoef
Contains Chebychev polynomial coefficients and terms.
class De4xxFileHeader
Contains data extracted from the ephemeris file header.
class De4xxFileIO
Contains data used directly for reading the ephemeris file.
class De4xxFileItem
Contains data regarding one of the items in a DE ephemeris file.
class De4xxFileRefTime
Contains timing reference data.
class De4xxFileRestart
The FILE pointer in a De4xxFileIO cannot be restored by Trick.
class De4xxFileSpec
Specifies which file to use (user input initialization-time data).
class DefaultAero
The simple, default, aerodynamic drag model, including coefficient of drag, ballistic coefficient, etc.
class DerivedState
The base class used for deriving a state representation of some subject DynBody.
class DerivedStateMessages
The class that specifies the message IDs used in the DerivedState model.
class DynamicsIntegrationGroup
A DynamicsIntegrationGroup integrates the state of a set of DynBoby objects over time.
class DynBody
Class DynBody is the base class for all dynamic bodies.
class DynBodyAttachedBodyConstraint
class DynBodyConstraint
Represents a constrained object, which comprises one or more scalar constraints on a vehicle.
class DynBodyConstraintsSolver
Builds and then solves a system of linear equations that describe the linear constraint forces and torques that act on a vehicle.
class DynBodyFrameSwitch
Switch a DynBody's integration frame to a specified frame when the body switches to that integration frame's sphere of influence.
class DynBodyGenericFrameAttachment
A wrench comprises a torque and a force applied at a point on a DynBody.
class DynBodyInit
Base class for initialize the state of a DynBody.
class DynBodyInitLvlhRotState
Initialize a vehicle's rotational state with respect to some vehicle's LVLH frame.
class DynBodyInitLvlhState
Initialize selected aspects of a vehicle's state with respect to some vehicle's LVLH frame.
class DynBodyInitLvlhTransState
initialize a vehicle's translational state with respect to some other vehicle's LVLH frame.
class DynBodyInitNedRotState
Initialize a vehicle's rotational state wrt some vehicle's North-East-Down frame.
class DynBodyInitNedState
Initialize selected aspects of a vehicle's state with respect to eithers some vehicle's North-East-Down frame or the North-East-Down frame for a specified location on the planet.
class DynBodyInitNedTransState
Initialize a vehicle's translational state wrt some vehicle's North-East-Down frame.
class DynBodyInitOrbit
Initialize a vehicle's translational state given an orbital specification.
class DynBodyInitPlanetDerived
(Initialize selected aspects of a vehicle's state with respect to some state that is derived from some vehicle's state in conjunction with a planet.
class DynBodyInitRotState
Initialize aspects of a vehicle's rotational state.
class DynBodyInitTransState
Initialize aspects of a vehicle's translational state.
class DynBodyInitWrtPlanet
Initialize selected aspects of a vehicle's state with respect to some frame based on the planet.
class DynBodyMessages
Specify the message IDs used in the DynBody model.
class DynBodyPendulumConstraint
class DynManager
The DynManager class manages the dynamic elements of a simulation.
class DynManagerInit
This class contains data used to initialize a DynManager object.
class DynManagerMessages
Specifies the message IDs used in the DynManager model.
class EarthLighting
A class for calculating lighting effects in low Earth orbit.
class EarthLightingMessages
Describes messages used in the earth lighting model.
class EmptySpaceEphemeris
Empty space has one ephemeris point.
class EphemeridesManager
The EphemeridesManager class manages the ephemeris models in a simulation.
class EphemeridesMessages
Specifies the message IDs used in the Ephemerides model.
struct EphemerisDataItemMeta
Structure containing the header metadata for sizing/locating the data entries with the data segments.
struct EphemerisDataSegmentMeta
Metadata implied from each data segment.
struct EphemerisDataSetMeta
Container for the metadata from the DE model header.
class EphemerisInterface
Interface class that specifies minimal functionality of an ephemeris model.
class EphemerisItem
The EphemerisItem class is the base class for representing an item that is modeled in an ephemeris model.
class EphemerisOrientation
An EphemerisOrientation object updates the rotational state of an ephemeris reference frame.
class EphemerisPoint
An EphemerisPoint object updates the translational state of an ephemeris reference frame.
class EphemerisRefFrame
An EphemerisRefFrame is a RefFrame whose state is set by an ephemeris model.
class EphemerisZXZOrientation
The EphemerisZXZOrientation is an EphemerisOrientation subclass that updates orientation based on an Z-X-Z Euler sequence and the time derivatives of this sequence.
class EulerDerivedState
The class used for deriving the Euler angle representation of a subject DynBody's attitude.
struct EulerInfo
Contains data needed to construct a transformation matrix given a sequence of Euler angles and to extract a sequence of Euler angles from a matrix.
class Facet
A general base class for all surface model facets.
class FacetParams
General base class for all parameters associated with facets in the surface model.
struct FacetStateInfo
This is a structure used only in the surface model to aid in relative state calculations for articulation.
class FlatPlate
A FlatPlate implementation of Facet.
class FlatPlateAeroFacet
The aerdynamic specific version of a flat plate.
class FlatPlateAeroFactory
Creates a FlatPlateAeroFacet from a FlatPlate.
class FlatPlateAeroParams
used in the FlatPlateAeroFactory to create a FlatPlateAeroFacet.
class FlatPlateCircular
An circular flat plate implementation of Facet.
class FlatPlateRadiationFacet
A flat plate facet to be used for radiation interaction.
class FlatPlateRadiationFactory
The factory for building flat plate radiation facets.
class FlatPlateThermal
A FlatPlate implementation of Facet, with thermal information.
class FlatPlateThermalAeroFactory
Creates a FlatPlateAeroFacet from a FlatPlate.
class Foo
All JEOD classes should have a doxygen-style header that describes the class.
class Force
A Force represents a Newtonian force that acts on a DynBody.
class ForceConstraintComponent
Models one component of a constrained object whose constraints dictate the application of a force at some constraint position.
class FrameDerivs
Contains translational and rotational second derivatives.
class GaussJacksonCoefficientsPair
Contains a summed Adams and Gauss-Jackson coefficient pair.
class GaussJacksonCoeffs
Contains the Gauss-Jackson predictor and corrector coefficients.
class GaussJacksonConfig
Contains Gauss-Jackson configuration data.
class GaussJacksonFirstOrderODEIntegrator
Integrates a first order ODE using the summed Adams technique that is embedded within the Gauss-Jackson technique.
class GaussJacksonGeneralizedDerivSecondOrderODEIntegrator
Integrates a generalized derivative second order ODE using Gauss-Jackson.
class GaussJacksonIntegrationControls
IntegrationControls specialized for Gauss-Jackson integration.
class GaussJacksonIntegratorBase
Base template class for integrating state via the Gauss-Jackson technique.
class GaussJacksonIntegratorConstructor
Create state and time integrators that propagate using Gauss-Jackson.
class GaussJacksonOneState
Essentially just a double*.
class GaussJacksonRationalCoefficients
Contains a set of Adams or Stormer-Cowell coefficients.
class GaussJacksonSimpleSecondOrderODEIntegrator
Integrates a simple second order ODE using the Gauss-Jackson technique.
class GaussJacksonStateMachine
Guides the behavior of the Gauss-Jackson integration process via a finite state machine.
class GaussJacksonTwoState
Essentially just std::pair<double*>.
class GaussJordanSolver
Solves a linear system of equations using Gauss-Jordan elimination.
class GaussQuadrature
class GeneralizedSecondOrderODETechnique
Enumerates the integration schemes, generalized Cartesian or Lie group integration, and provides simple utilities that work with this.
class GravityControls
Specifies whether and how a GravitySource affects a vehicle.
class GravityIntegFrame
Class that aids in determining whether gravity should be applied as a direct effect or a third body effect.
class GravityInteraction
Specifies interactions between a vehicle and a set of gravitational bodies.
class GravityManager
The master gravitational model for a simulation.
class GravityMessages
Specifies the message IDs used in the gravity model.
class GravitySource
Models the gravity for a specific planet; pure virtual.
class GravityTorque
Computes the torque on an object due to gravitation.
class GravityTorqueMessages
Specifies the message IDs used in the gravity torque model.
class IntegrationMessages
Declares messages associated with the integration test model.
class InteractionFacet
A base class for an interaction specific facet.
class InteractionFacetFactory
A factory to create a specific interaction facet from a general facet.
class InteractionSurface
A base class for interaction specific surfaces.
class InteractionSurfaceFactory
A base class for creating specific interaction surfaces from general surfaces.
class JeodAllocHelperAllocatedPointer
Class template that provides a static function cast that casts a pointer to an object of type T to a void* pointer.
class JeodAllocHelperAllocatedPointer< T, true >
Partial instantiation of JeodAllocHelperAllocatedPointer for polymorphic classes.
class JeodAllocHelperConstructDestruct
Class template that provides static functions construct and destruct that construct an array of objects.
class JeodAllocHelperConstructDestruct< T, false, is_abstract >
Partial instantiation for non-classes.
class JeodAllocHelperConstructDestruct< T, true, false >
Partial instantiation for non-abstract classes.
class JeodAssociativeContainer
This is the base class for the JEOD replacements of the STL associative containers.
class JeodBaseTime
JeodBaseTime is an abstract class, containing the basic structure of all clocks that run in JEOD.
class JeodCheckpointable
A JeodCheckpointable is an object whose contents are opaque to Trick, and presumably other simulation engines, whose contents can nonetheless be checkpointed and restarted by using the methods defined herein.
class JeodContainer
A JeodContainer is a JEOD STL sequence container replacement whose contents are checkpointable and restorable.
class JeodDynbodyIntegrationLoop
A Trick::IntegLoopScheduler that provides the ability to integrate a collection of Trick::SimObject instances over time, with the sim objects capable of being moved from one integration loop to another during run time.
class JeodIntegrationGroup
A JeodIntegrationGroup integrates the state of a set of objects over time.
class JeodIntegrationGroupOwner
The abstract class IntegrationGroupOwner contains an IntegrationGroup.
class JeodIntegrationTime
The class JeodIntegrationTime adds the concepts of timestamping and notification of changes in the nature of time to the ER7 numerical utilities TimeInterface class.
class JeodIntegratorInterface
A JeodIntegratorInterface extends the ER7 IntegratorInterface with the concept of a pointer to the simulation engine's integration object.
struct JeodLinksIterators
Class template that defines member types ForwardIterator and ReverseIterator for walking over a std::vector of pointers to Links objects.
struct JeodLinksIterators< const Links >
Partial specialization of JeodLinksIterators for const Links types.
class JeodList
The JEOD replacement for std::list.
class JeodMemoryInterface
Abstract interface between the JEOD memory manager and the simulation engine.
class JeodMemoryItem
A JeodMemoryItem contains metadata about some chunk of allocated memory.
class JeodMemoryManager
This class provides the interface between the macros in jeod_alloc.hh and the rest of the JEOD memory model.
class JeodMemoryReflectiveTable
A JeodMemoryReflectiveTable maps strings to themselves.
class JeodMemoryTable
A JeodMemoryTable maps strings to values with a coordinated map/vector pair.
class JeodMemoryTableClonable
A JeodMemoryTableClonable is a JeodMemoryTable that implements the required clone() functionality by invoking the ValueType's clone() method to create a clone of the input value.
class JeodMemoryTableCopyable
A JeodMemoryTableCopyable is a JeodMemoryTable that implements the required clone() functionality by invoking the ValueType's copy constructor to create a clone of the input value.
class JeodMemoryTypeDescriptor
Abstract class for managing data allocated as some specific type.
class JeodMemoryTypeDescriptorDerived
Extends JeodMemoryTypeDescriptor to describe a specific type.
class JeodMemoryTypePreDescriptor
Abstract class for describing a type without necessarily needing to create a JeodMemoryTypeDescriptor of that type.
class JeodMemoryTypePreDescriptorDerived
A JeodMemoryTypePreDescriptorDerived describes a Type.
class JeodObjectContainer
A JeodObjectContainer is a JeodContainer that contains objects of type ElemType.
class JeodObjectList
Defines a registry for defining a checkpointable list of objects.
class JeodObjectSet
Defines a registry for defining a checkpointable set of objects.
class JeodObjectVector
Defines a registry for defining a checkpointable vector of objects.
class JeodPointerContainer
A JeodPointerContainer is a JeodContainer that contains pointers to objects of type ElemType.
class JeodPointerList
Defines a registry for defining a checkpointable list of pointers.
class JeodPointerSet
Defines a registry for defining a checkpointable set of pointers.
class JeodPointerVector
Defines a registry for defining a checkpointable vector of pointers.
class JeodPrimitiveContainer
A JeodPrimitiveContainer is a JeodContainer that contains primitive data of type ElemType.
class JeodPrimitiveList
Defines a registry for defining a checkpointable list of primitives.
class JeodPrimitiveSerializer
Serializer / deserializer for primitive data.
class JeodPrimitiveSerializerBase
Base class for serializing / deserializing primitive data.
class JeodPrimitiveSet
Defines a registry for defining a checkpointable set of primitives.
class JeodPrimitiveVector
Defines a registry for defining a checkpointable vector of primitives.
class JeodSequenceContainer
This is the base class for the JEOD replacements of the STL sequence containers.
class JeodSet
The JEOD replacement for std::set.
class JeodSimEngineAttributes
Class template to construct a simulation engine attributes object that represents some type.
class JeodSimEngineAttributes< Type *, false >
Partial template instantiation of JeodSimEngineAttributes for a pointer type.
class JeodSimEngineAttributes< Type, true >
Partial template instantiation of JeodSimEngineAttributes for a class.
class JeodSimEngineAttributes< void *, false >
Template specialization of JeodSimEngineAttributes for void*.
class JeodSimulationInterface
This abstract class defines the basis for the interface between JEOD and a simulation engine.
class JeodSimulationInterfaceInit
Define configuration data needed to configure the dynamically-created message handler and memory manager.
class JeodSTLContainer
This is the base class for the JEOD replacements of the STL containers.
class JeodTrick10MemoryInterface
A TrickMemoryInterface implements the two required methods needed to register and deregister memory with the simulation engine, Trick in this case.
class JeodTrickIntegrator
A JeodTrickIntegrator specializes the JeodIntegratorInterface for use with Trick as the simulation engine.
class JeodTrickMemoryInterface
A TrickMemoryInterface implements the two required methods needed to register and deregister memory with the simulation engine, Trick in this case.
class JeodTrickSimInterface
A JEODTrickSimInterface implements the required capabilities of the generic JeodSimulationInterface in a Trick simulation environment.
class JeodVector
The JEOD replacement for std::vector.
class JPVCollectForce
This is a derived version of the template class JeodPointerVector<CollectForce>::type with an implementation of the method perform_cleanup_action which frees and clears stale data following a restore.
class JPVCollectTorque
This is a derived version of the template class JeodPointerVector<CollectTorque>::type with an implementation of the method perform_cleanup_action which frees and clears stale data following a restore.
class LightingBody
Represents a major source of light in a space environment, such as the sun, the Earth, the moon, etc.
class LightingParams
Contains important parameters for lighting information.
class LinearSystemSolver
Represents a linear system of equations, A*x = b, where A is conceptually an NxN matrix, and x and b are conceptually N-vectors.
class LineContactFacet
The contact facet based on the distance to a single point, specifically the vehicle point.
class LineContactFacetFactory
Creates a PointContactFacet from an InteractionFacet.
class LineContactPair
An point to point contact pair for use in the contact model.
class LinePointContactPair
An point to point contact pair for use in the contact model.
class LsodeControlDataInterface
Specifies controls for an LSODE integrator.
class LsodeDataArrays
The data arrays.
class LsodeDataJacobianPrep
Data associated with the method DPREPJ.
class LsodeDataStode
The data associated with method Dstode.
class LsodeFirstOrderODEIntegrator
Jeod-compatible version of the Livermore ODE solver, LSODE.
class LsodeGeneralizedDerivSecondOrderODEIntegrator
JEOD-compatible version of the Livermore ODE solver, LSODE, capable of integrating second-order ODEs.
class LsodeIntegrationControls
Contains controls for an LSODE integrator.
class LsodeIntegratorConstructor
Create state and time integrators that propagate using standard Lsode.
class LsodeSecondOrderODEIntegrator
JEOD-compatible version of the Livermore ODE solver, LSODE, capable of integrating second-order ODEs.
class LsodeSimpleSecondOrderODEIntegrator
JEOD-compatible version of the Livermore ODE solver, LSODE, capable of integrating second-order ODEs.
class LvlhDerivedState
The class used for deriving the rectilinear LVLH representations of a subject DynBody's state.
class LvlhFrame
The class used to represent an LVLH reference frame associated with a subject DynBody.
class LvlhFrameMessages
The class that specifies the message IDs used in the LvlhFrame model.
class LvlhRelativeDerivedState
The class used for calculating the LVLH state of a subject DynBody relative to some LVLH reference frame.
class LvlhType
The class used to identify the type of LVLH desired.
class MassBody
Represent both an atomic chunk of mass and an interconnected set of masses.
class MassBodyInit
Base class for initializing a MassBody.
class MassBodyLinks
Encapsulates the links between mass bodies.
class MassBodyMessages
Specify the message IDs used in the MassBody model.
class MassPoint
Adds tree linkages and a name to a MassPointState.
class MassPointInit
Contains data used to initialize a MassPoint.
class MassPointLinks
Encapsulates the links between mass points.
class MassPointState
Defines the state – position and orientation – of a MassPoint.
class MassProperties
Defines mass properties – mass and inertia tensor.
class MassPropertiesInit
Contains data used to initialize a mass model object.
class MathMessages
Specifies the message IDs used in the math model.
class Matrix3x3
Provides static methods for operations that involve 3x3 matrices.
class MatrixView
Encapsulates a collection of values of the underlying type that can conceptually be indexed by a pair of integers (unsigned).
class MemoryMessages
Declares messages associated with the integration test model.
class MessageHandler
The base class for generating JEOD messages.
class MessageMessages
Specifies the message IDs used in the message handler model.
class METAtmosphere
class METAtmosphereChemical
The chemical composition of the MET Atmosphere.
class METAtmosphereState
The MET specific implementation of AtmosphereState.
class METAtmosphereStateVars
The data variables component of the MET specific implementation of AtmosphereState.
class METAtmosphereThermal
The Thermal aspect of the computation.
class NamedItem
Provides a set of static methods for constructing dot-conjoined names.
class NamedItemMessages
Specifies the message IDs used in the named_item model.
class NedDerivedState
The class used for deriving the North-East-Down representations of a subject DynBody's state.
class NorthEastDown
Defines a local North-East-Down reference frame.
class NullMemoryInterface
A NullMemoryInterface extends the JeodMemoryInterface, providing the required functionality of the parent class in a null manner.
class Numerical
Provides miscellaneous numerical functions.
class NutationJ2000
Implements the nutation portion of the J2000 RNP.
class NutationJ2000Init
The NutationJ2000Init contains coefficients and other data used to initalize a NutationJ2000 object.
class NutationMars
Implements the nutation portion of the "Pathfinder" Mars RNP model.
class OrbElemDerivedState
The class used for deriving the orbital elements representation of a subject DynBody's position.
class OrbitalElements
Represents state in terms of Keplerian orbital elements.
class OrbitalElementsMessages
Specifies the message IDs used in the orbital elements model.
class Orientation
Specifies the orientiation of one reference frame with respect to another.
class OrientationMessages
Declares messages associated with the orientation model.
class PairInteraction
Simple spring contact parameters.
class PendulumConstraintComponent
Models a spherical pendulum as a constrained object, with the constraint force acting at the hinge point.
class Planet
Describes a planet with mass and shape.
class PlanetaryDerivedState
The class used for deriving the planet-fixed representations of a subject DynBody's position.
class PlanetFixedMessages
Specifies the message IDs used in the gravity model.
class PlanetFixedPosition
Contains various representations of position with respect to a planet.
class PlanetMessages
Specifies the message IDs used in the planet model.
class PlanetOrientation
The generic framework for orientation models to interact with a DynManager object.
class PlanetRNP
The generic framework for orientation models based on the RNP paradigm.
class PlanetRotation
The generic base class for all planet transformations.
class PlanetRotationInit
The generic base class for all initializing classes for PlanetRotation derived classes.
class PointContactFacet
The contact facet based on the distance to a single point, specifically the vehicle point.
class PointContactFacetFactory
Creates a PointContactFacet from an InteractionFacet.
class PointContactPair
An point to point contact pair for use in the contact model.
class PolarMotionJ2000
Implements the polar motion portion of the J2000 RNP.
class PolarMotionJ2000Init
Initializes the PolarMotionJ2000 object.
class PrecessionJ2000
Implements the precession portion of the J2000 RNP.
class PrecessionMars
Implements the axial rotation portion of the "Pathfinder" Mars RNP model.
class PropagatedEphemerisOrientation
A PropagatedEphemerisOrientation is an EphemerisOrientation whose state is coupled with the rotational state of a DynBody reference frame.
class PropagatedEphemerisPlanet
A PropagatedEphemerisPlanet is an EphemerisPoint whose state is coupled with the translational state of a DynBody reference frame.
class PropagatedPlanet
The PropagatedPlanet ephemeris model provides planetary state via a DynBody object whose state is propagated using the JEOD state integration techniques.
class Quaternion
Implement quaternions to the extent needed to represent orientations.
class RadiationBaseFacet
Generic type of facet for radiation pressure.
class RadiationDefaultSurface
The default spherical surface for radiation pressure.
class RadiationFacet
Generic type of facet for radiation pressure.
class RadiationMessages
Provides error messages.
class RadiationParams
Provides a parameter list to each facet, based on the facet material properties.
class RadiationPressure
Radiation pressure top-level definition.
class RadiationSource
Provides information on the source of the incident radiation.
class RadiationSurface
The surface of the vehicle that interacts with the incident flux.
class RadiationSurfaceFactory
The factory for creating Radiation Surfaces.
class RadiationThirdBody
Provide information on bodies that may cause shadowing or reflected illumination.
class RefFrame
Describe a frame of reference and define operations on reference frames.
class RefFrameItems
Identify which aspects of a reference frame's state have been set.
class RefFrameLinks
Encapsulates the links between reference frames.
class RefFrameManager
The RefFrameManager class manages the reference frames in a simulation.
class RefFrameMessages
Declares messages associated with the reference frames model.
class RefFrameOwner
Identify an object as an "owner" of a reference frame.
class RefFrameRot
Represent the rotational aspects of a reference frame's state.
class RefFrameState
Represent a reference frame's state.
class RefFrameTrans
Represent the translational aspects of a reference frame's state.
class RelativeDerivedState
The class used for deriving the state of some frame associated with the subject DynBody relative to some other target frame.
class RelativeKinematics
Encapsulates functionality for computing relative states.
class RelKinMessages
Specifies the message IDs used in the orbital elements model.
class Restartable2DSecondOrderIntegrator
Integrates a second order ODE in two dimensional space, d^2x/dt^2 = a(x,t), where x is a two-vector.
class RestartableFirstOrderODEIntegrator
A RestartableFirstOrderODEIntegrator is-a RestartableStateIntegrator that manages an er7_utils::FirstOrderODEIntegrator.
class RestartableGeneralizedDerivSecondOrderODEIntegrator
A RestartableGeneralizedDerivSecondOrderODEIntegrator is-a RestartableStateIntegrator that manages the integrator for a generalized second order ODE problem, one in which the time derivative of the generalized position is some function of the generalized position and the generalized velocity.
class RestartableGeneralizedStepSecondOrderODEIntegrator
A RestartableGeneralizedStepSecondOrderODEIntegrator is-a RestartableStateIntegrator that manages the integrator for a generalized second order ODE problem, one in which the time derivative of the generalized position is some function of the generalized position and the generalized velocity.
class RestartableScalarFirstOrderODEIntegrator
A RestartableScalarFirstOrderODEIntegrator integrates a first order ODE, dx/dt = v(x,t), where x is a scalar.
class RestartableSecondOrderODEIntegrator
A RestartableSecondOrderODEIntegrator is-a RestartableStateIntegrator that manages the integrator for a second order ODE problem.
class RestartableSimpleSecondOrderODEIntegrator
A RestartableSimpleSecondOrderODEIntegrator is-a RestartableSecondOrderODEIntegrator that manages the integrator for a simple second order ODE problem, one in which the time derivative of the generalized position is the generalized velocity.
class RestartableSO3SecondOrderODEIntegrator
A RestartableSO3SecondOrderODEIntegrator integrates a generalized second order ODE that describes rotation in three space.
class RestartableStateIntegrator
A RestartableStateIntegrator establishes the basic capabilities needed to make a state integrator a managed resource.
class RestartableT3SecondOrderODEIntegrator
A RestartableT3SecondOrderODEIntegrator integrates a second order ODE in three space, d^2x/dt^2 = a(x,t), where x is a three-vector.
class RNPJ2000
Implements the J2000 RNP model using the generic RNP framework.
class RNPMars
Implements the "Pathfinder" Mars RNP model using the generic RNP framework.
class RNPMessages
Describes messages used in the RNP model.
class RotationJ2000
Implements the axial rotation portion of J2000 RNP.
class RotationMars
Implements the axial rotation portion of the "Pathfinder" Mars RNP model.
class RowView
Represents a view into a row of an array.
class SectionedInputBuffer
A SectionedInputBuffer is a std::streambuf that reads from a section in a checkpoint file.
class SectionedInputStream
A SectionedInputStream is a std::istream that reads from a section in a checkpoint file.
class SectionedOutputBuffer
A SectionedOutputBuffer is a std::streambuf that writes a section of a checkpoint file.
class SectionedOutputStream
A SectionedOutputStream is a std::ostream that writes a section of a checkpoint file.
class SimInterfaceMessages
Specifies the message IDs used in the sim_interface model.
class SimpleCheckpointable
The SimpleCheckpointable class provides a simple checkpoint/restart interface by which an object can complete the restart process.
class SinglePlanetEphemeris
A space with one gravitation body has one ephemeris point.
class SinglePointEphemeris
A SinglePointEphemeris has one ephemeris point.
class SolarBetaDerivedState
The class for calculating the solar beta of a vehicle.
class SolverTypes
Define various types used in the constraints concept.
class SphericalHarmonicsDeltaCoeffs
Base class for tidal and temporal gravity models.
class SphericalHarmonicsDeltaCoeffsInit
Initialization data for a SphericalHarmonicsDeltaCoeffs instance.
class SphericalHarmonicsDeltaControls
Provides controls for how a variational model affects a vehicle.
class SphericalHarmonicsGravityControls
Specifies whether and how a SphericalHarmonicsGravitySource affects a vehicle.
class SphericalHarmonicsGravitySource
Models the gravity for a specific planet using spherical harmonics.
class SphericalHarmonicsSolidBodyTides
Models solid body tidal effects.
class SphericalHarmonicsSolidBodyTidesInit
Initializes a solid body tides model.
class SphericalHarmonicsTidalEffects
Models tidal effects as a delta on top of a gravity model.
class SphericalHarmonicsTidalEffectsInit
Initializes a tidal gravity model.
class SpiceEphemeris
The S_define-level class that provides planetary ephemerides.
class SpiceEphemOrientation
A SpiceEphemOrientation minimally extends EphemerisOrientation to include the JEOD and SPICE names and an update method for the target ephemeris reference frame.
class SpiceEphemPoint
A SpiceEphemPoint minimally extends EphemerisPoint, primarily in order to contain the ID of the SPICE object that will be used to update the state of the target ephemeris reference frame.
class SpringPairInteraction
Simple spring contact parameters.
class StructureIntegratedDynBody
Extends DynBody to integrate an object's structural reference frame as opposed to its center of mass.
class SubArrayView
Represents a subarray view into an array.
class SubscribeInterface
A class that inherits from the SubscribeInterface class must provide subscribe and unsubscribe methods.
class Subscription
A Subscription object provides two approaches of marking something as being active or inactive: The activate and deactivate methods versus the subscribe and unsubscribe methods.
class SubVectorView
Provides a view into a part of a vector.
class SuppressedCodeMessageHandler
Adds the capability to suppress messages by their message code to the base MessageHandler class.
class SurfaceModel
A general, non-interaction specific surface that can be used to create surfaces suitable for specific interactions.
class SurfaceModelMessages
Messages associated with the use of the surface model.
class TemplateMessages
Declares messages associated with the model template model.
class TestHarnessMessages
Specifies the message IDs used in the test harness model.
class TestMessageHandler
The MessageHandler class designed for use in unit tests.
class TestSimInterface
The TestSimInterface class is a JeodSimulationInterface that checks for failures by means of message handler messages whose message code is deemed indicative of a failure.
class ThermalFacetRider
Defining the thermal characteristics of surface facets.
class ThermalIntegrableObject
Encapsulates a thermal integrator for a facet.
class ThermalMessages
Specifying the message IDs used in the model.
class ThermalModelRider
Defining the thermal functionality.
class ThermalParams
A virtual base class for thermal facet parameters, used to add to the parameter lists for specific-model facets in their respective InteractionSurfaceFactorys.
class TimeChangeSubscriber
A TimeChangeSubscriber is some object that wants to be notified of changes in the nature of time.
class TimeConverter
The Time Converter is an abstract class that defines the basic structure of all the methods used by the converter objects; converters are the objects that specify the conversion algorithms between time-types.
class TimeConverter_Dyn_TAI
Define class TimeConverter_Dyn_TAI, which converts from simulation dynamic time to International Atomic Time.
class TimeConverter_Dyn_TDB
Define class TimeConverter_Dyn_TDB, which converts from simulation dynamic time to Barycentric Dynamic Time.
class TimeConverter_Dyn_UDE
Define class TimeConverter_Dyn_UDE, which converts from simulation dynamic time to any specific instance of the generic User-Defined-Epoch Time.
class TimeConverter_STD_UDE
Define class TimeConverter_STD_UDE, which converts from any specific example of the generic Standard Time to any specific example of the generic User-Defined-Epoch Time.
class TimeConverter_TAI_GPS
Define class TimeConverter_TAI_GPS, which converts between International Atomic Time and the clock associated with the Global Positioning System.
class TimeConverter_TAI_TDB
Define class TimeConverter_TAI_TDB, which converts from International Atomic Time to Barycentric Dynamic Time.
class TimeConverter_TAI_TT
Converts between International Atomic Time and Terrestrial Time.
class TimeConverter_TAI_UT1
Define class TimeConverter_TAI_UT1, which converts between International Atomic Time and Universal Time.
class TimeConverter_TAI_UTC
Converts between International Atomic Time and Coordinated Universal Time.
class TimeConverter_UT1_GMST
Converts between Universal Time and Greenwich Mean Sidereal Time.
class TimeDyn
Represents the Dynamic Time in the simulation.
class TimeEnum
Contains an enumeration of the formats in which time can be represented.
class TimeGMST
To represent the clock known as Greenwich Mean Sidereal Time.
class TimeGPS
To represent the time associated with the Global Positioning System.
class TimeLinks
class TimeManager
To manage the various time representations and the converters between them throughout the simulation.
class TimeManagerInit
To initialize the Time Manager.
class TimeMessages
Specify the message IDs used in the Time model.
class TimeMET
A type of UDE time that allows for deliberate holds, or pauses.
class TimeStandard
A class that serves as the base for all time representations that are well defined outside the simulation.
class TimeTAI
Represents International Atomic Time.
class TimeTDB
Represents Barycentric Dynamic Time.
class TimeTT
Represents Terrestrial Time.
class TimeUDE
Represents all instances of times with a user-defined epoch, accepting that Mission Elapsed Time requires some further definition.
class TimeUT1
Represents Universal Time.
class TimeUTC
Represents Coordinated Universal Time.
class Torque
A Torque represents a Newtonian torque that acts on a DynBody.
class TorqueConstraintComponent
Models one component of a constrained object whose constraints dictate the application of a torque.
class TreeLinks
Encapsulates links (parent, children, siblings) between objects, in the form of a tree.
class TreeLinksAscendRange
A TreeLinksAscendRange walks up a Links object's path_to_node_ data member, starting at the start node and ending just before the end node.
class TreeLinksChildIterator
class TreeLinksChildrenRange
A TreeLinksChildrenRange walks over a Links object's children_.
class TreeLinksDescentIterator
class TreeLinksDescentRange
A TreeLinksDescentRange walks down a Links object's path_to_node_ data member, starting at the start node and ending just before the end node.
class TreeLinksIterator
class TreeLinksParentIterator
class TreeLinksRange
Base class template for all tree links range types.
class TrickJeodIntegrator
A TrickJeodIntegrator specializes the Trick::Integrator to provide the Trick side of the integration interface between Trick and JEOD.
class TrickMessageHandler
The MessageHandler class for designed for use in Trick-based simulations.
class TrickMessageHandlerMixin
The TrickMessageHandlerMixin implements the required capabilities of the generic JeodSimulationInterface in a Trick simulation environment.
class TwoDArray
Represents a two dimensional array, implemented as a vector that is indexed as a row major two dimensional array.
class Vector3
Provides static methods for operations that involve 3-vectors.
class VectorView
Provides a view into an object that can conceptually be indexed by a single integer (currently unsigned).
class VehicleNonGravState
Encapsulates various aspects of a vehicle's state with respect to inertial.
class VehicleProperties
Captures pointers to various vehicle properties that are commonly used in the constraint concept.
class WindVelocity
A generic wind velocity implementation.
class WindVelocityBase
The generic base class for wind velocity classes.
class Wrench
A wrench comprises a torque and a force applied at a point on a DynBody.
Typedefs
typedef GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator > GaussJacksonIntegratorBaseFirst
Alias for a first order Gauss Jackson integrator.
typedef GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator > GaussJacksonIntegratorBaseSecond
Alias for a second order Gauss Jackson integrator.
typedef std::map< const void *, JeodMemoryItem > AllocTable
An AllocTable maps memory addresses to memory descriptions.
typedef JeodMemoryTableClonable< JeodMemoryTypeDescriptor > TypeTable
The type type itself is a memory table with copy implemented by clone().
Enumerations
enum PendulumConstraintMode {
PendulumConstraintMode::Inactive, PendulumConstraintMode::Vertical, PendulumConstraintMode::Horizontal, PendulumConstraintMode::Inverted,
PendulumConstraintMode::Reset
}
Describes the modes in which a PendulumConstraint can operate.
Functions
template<class CollectType >
void release_vector (CollectType &vec)
Release JEOD-allocated memory in the collect vector.
template<typename CollectType , typename value_type >
void collect_insert (CollectType &collect_in, value_type &elem)
template<typename CollectType , typename value_type >
void collect_push_back (CollectType &collect_in, value_type &elem)
static void accumulate_forces (const JeodPointerVector< CollectForce >::type &vec, double *cumulation)
Accumulate forces acting on a vehicle.
static void accumulate_torques (const JeodPointerVector< CollectTorque >::type &vec, double *cumulation)
Accumulate torques acting on a vehicle.
static void check_frame_ownership (const BodyRefFrame &frame, const DynBody *dyn_body, const char *file, unsigned int line)
Check that the dyn_body 'owns' the subject frame.
static void accumulate_forces (const JeodPointerVector< CollectForce >::type &vec, double *cumulation)
Accumulate forces acting on a vehicle.
static void accumulate_torques (const JeodPointerVector< CollectTorque >::type &vec, double *cumulation)
Accumulate torques acting on a vehicle.
static void generate_bad_point_message (const char *file, unsigned int line, const char *child_body_name, const char *child_point_name, const MassPoint *child_point, const char *parent_body_name, const char *parent_point_name, const MassPoint *parent_point)
Generate a message regarding failure to find mass points on a vehicle.
void process_mem_usage (double &vm_usage, double &resident_set)
static double l1_point (double b1b2_mass_ratio)
Calculate the location of the L1 point as a ratio.
TimeConverter::Direction operator| (TimeConverter::Direction a, TimeConverter::Direction b)
Bitwise or operator for combining multiple converter direction flags.
static bool is_zero_vector (const double vec[3])
template<typename ContainerT , typename ElemT >
std::conditional< std::is_const< ContainerT >::value, typename ContainerT::const_iterator, typename ContainerT::iterator >::type find_iterator (ContainerT &container, const ElemT *elem)
Find the provided element in the container.
template<typename ContainerT , typename ElemT >
void remove_element (ContainerT &container, const ElemT *elem, const char *err_msg)
Remove the provided element from the container.
template<typename ContainerT , typename ElemT >
bool is_in_container (const ContainerT &container, const ElemT *elem)
Check whether the provided element is in the container.
template<typename T >
bool accumulate_wrenches (const Wrench &(T::*get_wrench)() const, const DynBodyConstraintsSolver::ConstraintsVectorT &active_constraints, const double point[3], Wrench &sum)
Accumulate the total of the get_wrench calls to the active constraints.
void fail_simulation (const char *file, int lineno, const char *msg)
void fail_simulation (const char *file, int lineno)
void fail_simulation (const char *file, int lineno, const std::string &msg)
void fail_simulation (const char *file, int lineno, const std::stringstream &msgbuf)
void fail_simulation_helper_ (const char *file, int lineno, const std::stringstream &msgbuf)
template<typename T >
void fail_simulation_helper_ (const char *file, int lineno, std::stringstream &msgbuf, T &&arg)
template<typename T , typename... Args>
void fail_simulation_helper_ (const char *file, int lineno, std::stringstream &msgbuf, T &&arg, Args &&... rest)
template<typename... Args>
void fail_simulation (const char *file, int lineno, Args &&... args)
std::ostream & operator<< (std::ostream &stream, const GaussJacksonCoeffs &coeff)
static GaussJacksonConfig set_default_config_values (const GaussJacksonConfig &config)
Swap the negative ones in the supplied config with the default values, some of which are computed.
static unsigned int validate_config (const GaussJacksonConfig &config)
Check for invalid values in the supplied config.
static GaussJacksonIntegrationControls * cast_to_gj_controls (er7_utils::IntegrationControls &controls)
Cast the provided integration controls to a GaussJacksonIntegrationControls.
template<typename T >
void * jeod_alloc_construct_array (std::size_t nelem, void *addr)
Construct an array of objects of type T.
template<typename T >
void jeod_alloc_destruct_array (std::size_t nelem, void *addr)
Destruct an array of objects of type T.
template<typename T >
void * jeod_alloc_get_allocated_pointer (T *pointer)
Cast a pointer to some object to a pointer to void* such that a pointer to a polymorphic object, downcast to a base class pointer, becomes a pointer to the original object, but also such that a pointer to an instance of a non-polymorphic class or a pointer to a non-class type is handled correctly.
void print_debug (unsigned int level, FILE *file, const char *format,...)
Variable arguments debug print function.
static void print_nonfatal_message (FILE *file, unsigned int level, const char *format,...)
Variable arguments debug print function.
static void print_message_and_exit (const char *file, const char *error, int exit_status)
Emulates Trick's exec_terminate function.
Variables
static constexpr double speed_of_light_sq = 89875517873681764.0
The speed of light squared, in m^2/s^2.
static const EulerInfo Euler_info [12]
Contains twelve EulerInfo objects, one per each of the JEOD Euler sequences.
static const unsigned int Trick_stubs_debug_level = 0
Detailed Description
Namespace jeod.
Purpose: ()
Construct a Time_MET.
Namespace jeod
Typedef Documentation
AllocTable
typedef std::map<const void *, JeodMemoryItem> jeod::AllocTable
An AllocTable maps memory addresses to memory descriptions.
Definition at line 71 of file memory_manager_hide_from_trick.hh.
GaussJacksonIntegratorBaseFirst
typedef GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator> jeod::GaussJacksonIntegratorBaseFirst
Alias for a first order Gauss Jackson integrator.
Definition at line 84 of file gauss_jackson_integrator_base_first.hh.
GaussJacksonIntegratorBaseSecond
typedef GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator> jeod::GaussJacksonIntegratorBaseSecond
Alias for a second order Gauss Jackson integrator.
Definition at line 84 of file gauss_jackson_integrator_base_second.hh.
TypeTable
typedef JeodMemoryTableClonable<JeodMemoryTypeDescriptor> jeod::TypeTable
The type type itself is a memory table with copy implemented by clone().
Definition at line 76 of file memory_manager_hide_from_trick.hh.
Enumeration Type Documentation
PendulumConstraintMode
enum jeod::PendulumConstraintMode strong
Describes the modes in which a PendulumConstraint can operate.
Enumerator
Inactive
Pendulum is inactive.
Vertical
Pendulum is more or less oriented vertically: The z component is positive and larger than the horizontal components.
Horizontal
Pendulum is more or less oriented horizontally: The z component is smaller than are the horizontal components.
Inverted
Pendulum is more or less inverted: The z component is negative and larger than the horizontal components.
Reset
Pendulum state is to be reset to its quiescent vertical state, with the bob oriented vertically and zero velocity.
Definition at line 64 of file pendulum_constraint_mode.hh.
Function Documentation
accumulate_forces() [1/2]
static void jeod::accumulate_forces (const JeodPointerVector< CollectForce >::type & vec, double * cumulation) inline static
Accumulate forces acting on a vehicle.
Parameters
[in] vec Forces
[out] cumulation Accumulated force
Definition at line 40 of file structure_integrated_dyn_body_collect.cc.
References jeod::Vector3::incr(), and jeod::Vector3::initialize().
accumulate_forces() [2/2]
static void jeod::accumulate_forces (const JeodPointerVector< CollectForce >::type & vec, double * cumulation) inline static
Accumulate forces acting on a vehicle.
Parameters
[in] vec Forces
[out] cumulation Accumulated force
Definition at line 59 of file dyn_body_collect.cc.
References jeod::Vector3::incr(), and jeod::Vector3::initialize().
Referenced by jeod::DynBody::collect_forces_and_torques(), and jeod::StructureIntegratedDynBody::collect_local_forces_and_torques().
accumulate_torques() [1/2]
static void jeod::accumulate_torques (const JeodPointerVector< CollectTorque >::type & vec, double * cumulation) inline static
Accumulate torques acting on a vehicle.
Parameters
[in] vec Torques
[out] cumulation Accumulated torque
Definition at line 61 of file structure_integrated_dyn_body_collect.cc.
References jeod::Vector3::incr(), and jeod::Vector3::initialize().
accumulate_torques() [2/2]
static void jeod::accumulate_torques (const JeodPointerVector< CollectTorque >::type & vec, double * cumulation) inline static
Accumulate torques acting on a vehicle.
Parameters
[in] vec Torques
[out] cumulation Accumulated torque
Definition at line 81 of file dyn_body_collect.cc.
References jeod::Vector3::incr(), and jeod::Vector3::initialize().
Referenced by jeod::DynBody::collect_forces_and_torques(), and jeod::StructureIntegratedDynBody::collect_local_forces_and_torques().
accumulate_wrenches()
template<typename T > bool jeod::accumulate_wrenches (const Wrench &(T::*)() const get_wrench, const DynBodyConstraintsSolver::ConstraintsVectorT & active_constraints, const double point[3], Wrench & sum)
Accumulate the total of the get_wrench calls to the active constraints.
Returns
True if the sum is non-zero.
Template Parameters
T The class that defines the get_wrench call. &
Parameters
get_wrench Pointer to member function that returns a Wrench.
active_constraints Vector of active constraints.
point The vector offset for computing the wrenching torque.
sum The sum to be accumulated.
Definition at line 125 of file dyn_body_constraints_solver.cc.
References jeod::Wrench::get_force(), jeod::Wrench::get_torque(), jeod::Wrench::is_active(), is_zero_vector(), jeod::Wrench::reset_force_and_torque(), and jeod::Wrench::set_point().
cast_to_gj_controls()
static GaussJacksonIntegrationControls* jeod::cast_to_gj_controls (er7_utils::IntegrationControls & controls) static
Cast the provided integration controls to a GaussJacksonIntegrationControls.
Parameters
controls Generic controls to be cast.
Returns
GaussJacksonIntegrationControls pointer, guaranteed to be non-null.
Definition at line 52 of file gauss_jackson_integrator_constructor.cc.
Referenced by jeod::GaussJacksonIntegratorConstructor::create_first_order_ode_integrator(), jeod::GaussJacksonIntegratorConstructor::create_generalized_deriv_second_order_ode_integrator(), and jeod::GaussJacksonIntegratorConstructor::create_second_order_ode_integrator().
check_frame_ownership()
static void jeod::check_frame_ownership (const BodyRefFrame & frame, const DynBody * dyn_body, const char * file, unsigned int line) inline static
Check that the dyn_body 'owns' the subject frame.
Parameters
[in] frame Frame to test
[in] dyn_body Typically this
[in] file Typically FILE
[in] line Typically LINE
Definition at line 62 of file dyn_body_set_state.cc.
References jeod::NamedItem::c_str(), jeod::MessageHandler::fail(), jeod::RefFrame::get_name(), jeod::RefFrame::get_owner(), jeod::DynBodyMessages::invalid_frame, and jeod::DynBody::name.
Referenced by jeod::DynBody::set_attitude_left_quaternion(), jeod::DynBody::set_attitude_matrix(), jeod::DynBody::set_attitude_rate(), jeod::DynBody::set_attitude_right_quaternion(), jeod::DynBody::set_position(), jeod::DynBody::set_state(), and jeod::DynBody::set_velocity().
collect_insert()
template<typename CollectType , typename value_type > void jeod::collect_insert (CollectType & collect_in, value_type & elem)
Definition at line 99 of file body_force_collect.hh.
References jeod::JeodMemoryManager::destroy_memory(), jeod::MessageHandler::inform(), jeod_alloc_get_allocated_pointer(), and JEOD_IS_ALLOCATED.
collect_push_back()
template<typename CollectType , typename value_type > void jeod::collect_push_back (CollectType & collect_in, value_type & elem)
Definition at line 131 of file body_force_collect.hh.
References jeod::JeodMemoryManager::destroy_memory(), jeod::MessageHandler::inform(), jeod_alloc_get_allocated_pointer(), and JEOD_IS_ALLOCATED.
fail_simulation() [1/5]
void jeod::fail_simulation (const char * file, int lineno, const char * msg) inline
Definition at line 80 of file fail_simulation.hh.
References jeod::MessageHandler::fail().
Referenced by fail_simulation(), and fail_simulation_helper_().
fail_simulation() [2/5]
void jeod::fail_simulation (const char * file, int lineno) inline
Definition at line 92 of file fail_simulation.hh.
References fail_simulation().
fail_simulation() [3/5]
void jeod::fail_simulation (const char * file, int lineno, const std::string & msg) inline
Definition at line 101 of file fail_simulation.hh.
References fail_simulation().
fail_simulation() [4/5]
void jeod::fail_simulation (const char * file, int lineno, const std::stringstream & msgbuf) inline
Definition at line 111 of file fail_simulation.hh.
References fail_simulation().
fail_simulation() [5/5]
template<typename... Args> void jeod::fail_simulation (const char * file, int lineno, Args &&... args) inline
Definition at line 159 of file fail_simulation.hh.
References fail_simulation_helper_().
fail_simulation_helper_() [1/3]
void jeod::fail_simulation_helper_ (const char * file, int lineno, const std::stringstream & msgbuf) inline
Definition at line 121 of file fail_simulation.hh.
References fail_simulation().
Referenced by fail_simulation(), and fail_simulation_helper_().
fail_simulation_helper_() [2/3]
template<typename T > void jeod::fail_simulation_helper_ (const char * file, int lineno, std::stringstream & msgbuf, T && arg) inline
Definition at line 132 of file fail_simulation.hh.
References fail_simulation().
fail_simulation_helper_() [3/3]
template<typename T , typename... Args> void jeod::fail_simulation_helper_ (const char * file, int lineno, std::stringstream & msgbuf, T && arg, Args &&... rest) inline
Definition at line 145 of file fail_simulation.hh.
References fail_simulation_helper_().
find_iterator()
template<typename ContainerT , typename ElemT > std::conditional< std::is_const<ContainerT>::value, typename ContainerT::const_iterator, typename ContainerT::iterator>::type jeod::find_iterator (ContainerT & container, const ElemT * elem)
Find the provided element in the container.
Returns
Iterator the points to the provided element, or container.end(), as a ContainerT::const_iterator if the container is const, otherwise as a ContainerT::iterator.
Template Parameters
ContainerT The type of the container, typically inferred.
ElemT The type of the element, typically inferred.
Parameters
container The container to be searched.
elem The element to be found.
Definition at line 60 of file dyn_body_constraints_solver.cc.
Referenced by is_in_container(), and remove_element().
generate_bad_point_message()
static void jeod::generate_bad_point_message (const char * file, unsigned int line, const char * child_body_name, const char * child_point_name, const MassPoint * child_point, const char * parent_body_name, const char * parent_point_name, const MassPoint * parent_point) static
Generate a message regarding failure to find mass points on a vehicle.
Assumptions and Limitations
One or both of the input MassPoint pointers is null.
Parameters
[in] file File name
[in] line Line number
[in] child_body_name Name of child body
[in] child_point_name Name of child mass point
[in] child_point Child mass point
[in] parent_body_name Name of parent body
[in] parent_point_name Name of parent mass point
[in] parent_point Parent mass point
Definition at line 591 of file mass_attach.cc.
References jeod::MessageHandler::error(), and jeod::MassBodyMessages::invalid_attach.
Referenced by jeod::MassBody::attach_to().
is_in_container()
template<typename ContainerT , typename ElemT > bool jeod::is_in_container (const ContainerT & container, const ElemT * elem)
Check whether the provided element is in the container.
Returns
True if elem is in container, false otherwise.
Template Parameters
ContainerT The type of the container, typically inferred.
ElemT The type of the element, typically inferred.
Parameters
container The container to be searched.
elem The element to be found.
Definition at line 106 of file dyn_body_constraints_solver.cc.
References find_iterator().
Referenced by jeod::DynBodyConstraintsSolver::is_active(), jeod::DynBodyConstraintsSolver::is_ours(), and jeod::DynBodyConstraintsSolver::is_registered().
is_zero_vector()
static bool jeod::is_zero_vector (const double vec[3]) inline static
Definition at line 37 of file dyn_body_constraints_solver.cc.
Referenced by accumulate_wrenches().
jeod_alloc_construct_array()
template<typename T > void* jeod::jeod_alloc_construct_array (std::size_t nelem, void * addr) inline
Construct an array of objects of type T.
Template Parameters
T Pointed-to type.
Parameters
nelem Number of elements in the array
addr Address to be constructed
Returns
Constructed array.
Definition at line 223 of file jeod_alloc_construct_destruct.hh.
jeod_alloc_destruct_array()
template<typename T > void jeod::jeod_alloc_destruct_array (std::size_t nelem, void * addr) inline
Destruct an array of objects of type T.
Template Parameters
T Pointed-to type.
Parameters
nelem Number of elements in the array
addr Address to be destructed
Definition at line 244 of file jeod_alloc_construct_destruct.hh.
jeod_alloc_get_allocated_pointer()
template<typename T > void* jeod::jeod_alloc_get_allocated_pointer (T * pointer) inline
Cast a pointer to some object to a pointer to void* such that a pointer to a polymorphic object, downcast to a base class pointer, becomes a pointer to the original object, but also such that a pointer to an instance of a non-polymorphic class or a pointer to a non-class type is handled correctly.
Template Parameters
T Pointed-to type.
Parameters
pointer Pointer to be cast to void*.
Usage:
jeod_alloc_get_allocated_pointer(pointer)
Note that the template parameter does not need to be specified. The compiler automagically determines the type.
Assumptions and limitations:
The function argument pointer is a pointer.
The pointer is not cv qualified (i.e., neither const nor volatile).
Inheritance is public for polymorphic classes.
jeod_alloc_get_allocated_pointer(&array[1])
does not return a pointer to
&array[0]
.
Definition at line 161 of file jeod_alloc_get_allocated_pointer.hh.
References jeod::JeodAllocHelperAllocatedPointer< T, is_poly >::cast().
Referenced by collect_insert(), collect_push_back(), and jeod::JeodMemoryTypeDescriptorDerived< Type >::most_derived_pointer().
l1_point()
static double jeod::l1_point (double b1b2_mass_ratio) static
Calculate the location of the L1 point as a ratio.
Returns
Ratio of body1 to L1-point distance to body1 to body2 distance
Parameters
[in] b1b2_mass_ratio Body1 to body2 mass ratio
Definition at line 276 of file de4xx_file_init.cc.
Referenced by jeod::De4xxFile::initialize().
operator<<()
std::ostream& jeod::operator<< (std::ostream & stream, const GaussJacksonCoeffs & coeff)
Parameters
stream The stream to be printed to.
coeff The coefficients to be printed.
Definition at line 143 of file gauss_jackson_coeffs.cc.
References jeod::GaussJacksonCoeffs::corrector, jeod::GaussJacksonCoeffs::order, jeod::GaussJacksonCoeffs::predictor, and jeod::GaussJacksonCoefficientsPair::print().
operator|()
TimeConverter::Direction jeod::operator| (TimeConverter::Direction a, TimeConverter::Direction b) inline
Bitwise or operator for combining multiple converter direction flags.
Definition at line 206 of file time_converter.hh.
print_message_and_exit()
static void jeod::print_message_and_exit (const char * file, const char * error, int exit_status) static
Emulates Trick's exec_terminate function.
Parameters
[in,out] file File
[in] error Error message
[in] exit_status Exit status
Definition at line 95 of file test_message_handler.cc.
Referenced by jeod::TestMessageHandler::process_message().
print_nonfatal_message()
static void jeod::print_nonfatal_message (FILE * file, unsigned int level, const char * format, ...) static
Variable arguments debug print function.
Parameters
[in,out] file File
[in] level Print level
[in] format Format
[in] ... Items to be printed
Definition at line 73 of file test_message_handler.cc.
References Trick_stubs_debug_level.
Referenced by jeod::TestMessageHandler::process_message().
process_mem_usage()
void jeod::process_mem_usage (double & vm_usage, double & resident_set)
Definition at line 495 of file de4xx_file.cc.
Referenced by jeod::De4xxFile::capture_mem_stats().
release_vector()
template<class CollectType > void jeod::release_vector (CollectType & vec)
Release JEOD-allocated memory in the collect vector.
Parameters
[in,out] vec Collected vectors
Definition at line 84 of file body_force_collect.hh.
References JEOD_DELETE_OBJECT, and JEOD_IS_ALLOCATED.
Referenced by jeod::BodyForceCollect::~BodyForceCollect().
remove_element()
template<typename ContainerT , typename ElemT > void jeod::remove_element (ContainerT & container, const ElemT * elem, const char * err_msg)
Remove the provided element from the container.
Template Parameters
ContainerT The type of the container, typically inferred.
ElemT The type of the element, typically inferred.
Parameters
container The container to be searched.
elem The element to be removed.
err_msg Message to be sent if elem is not in container.
Definition at line 79 of file dyn_body_constraints_solver.cc.
References FAIL_SIMULATION, and find_iterator().
Referenced by jeod::DynBodyConstraintsSolver::deactivate_constraint(), jeod::DynBodyConstraintsSolver::detach(), jeod::DynBodyConstraintsSolver::remove_child_constraint(), and jeod::DynBodyConstraintsSolver::remove_constraint().
set_default_config_values()
static GaussJacksonConfig jeod::set_default_config_values (const GaussJacksonConfig & config) static
Swap the negative ones in the supplied config with the default values, some of which are computed.
Definition at line 77 of file gauss_jackson_config.cc.
References jeod::GaussJacksonConfig::absolute_tolerance, jeod::Numerical::compare_exact(), jeod::GaussJacksonConfig::final_order, jeod::GaussJacksonConfig::initial_order, jeod::GaussJacksonConfig::max_correction_iterations, jeod::GaussJacksonConfig::ndoubling_steps, jeod::GaussJacksonConfig::priming_technique, and jeod::GaussJacksonConfig::relative_tolerance.
Referenced by jeod::GaussJacksonConfig::validate_configuration().
validate_config()
static unsigned int jeod::validate_config (const GaussJacksonConfig & config) static
Check for invalid values in the supplied config.
Definition at line 163 of file gauss_jackson_config.cc.
References jeod::GaussJacksonConfig::absolute_tolerance, jeod::GaussJacksonConfig::final_order, jeod::GaussJacksonConfig::initial_order, jeod::GaussJacksonConfig::ndoubling_steps, and jeod::GaussJacksonConfig::relative_tolerance.
Referenced by jeod::GaussJacksonConfig::validate_configuration().
Variable Documentation
Euler_info
const EulerInfo jeod::Euler_info[12] static
Initial value:
= {
   { {0, 1, 2},   0,    2,    true,   true },
   { {0, 2, 1},   0,    1,   false,   true },
   { {1, 2, 0},   1,    0,    true,   true },
   { {1, 0, 2},   1,    2,   false,   true },
   { {2, 0, 1},   2,    1,    true,   true },
   { {2, 1, 0},   2,    0,   false,   true },
   { {0, 1, 0},   2,    2,    true,  false },
   { {0, 2, 0},   1,    1,   false,  false },
   { {1, 2, 1},   0,    0,    true,  false },
   { {1, 0, 1},   2,    2,   false,  false },
   { {2, 0, 2},   1,    1,    true,  false },
   { {2, 1, 2},   0,    0,   false,  false }
}
Contains twelve EulerInfo objects, one per each of the JEOD Euler sequences.
The elements are arranged per the values of the Orientation::EulerSequence enumeration items.
Definition at line 98 of file euler_angles.cc.
Referenced by jeod::Orientation::compute_euler_angles_from_matrix(), jeod::Orientation::compute_matrix_from_euler_angles(), and jeod::Orientation::compute_quaternion_from_euler_angles().
speed_of_light_sq
constexpr double jeod::speed_of_light_sq = 89875517873681764.0 static
The speed of light squared, in m^2/s^2.
Definition at line 58 of file gravity_controls.cc.
Referenced by jeod::GravityControls::calc_relativistic().
Trick_stubs_debug_level
const unsigned int jeod::Trick_stubs_debug_level = 0 static
Definition at line 39 of file test_message_handler.cc.
Referenced by print_debug(), and print_nonfatal_message().