JEOD: jeod::NamedItem Class Reference
jeod::NamedItem Class Reference
Provides a set of static methods for constructing dot-conjoined names.
#include <named_item.hh>
Public Types
using size_type = std::string::size_type
The size type used in std::string.
Public Member Functions
NamedItem (std::string name_in=std::string(), bool frozen_in=false)
Default constructor.
NamedItem (const NamedItem &)=default
Copy constructor.
NamedItem (NamedItem &&)=default
Move constructor.
virtual ~NamedItem ()=default
Destructor.
NamedItem & operator= (const NamedItem &src)
Copy assignment.
NamedItem & operator= (NamedItem &&src)
Move assignment.
NamedItem & operator= (const std::string &name_in)
Assignment from a string.
bool operator== (const NamedItem &rhs)
Comparison of names.
const std::string & get_name () const
Getter for name.
const char * c_str () const
Getter for name, as a C-style string.
size_type size () const
Getter for the length of the name.
bool get_is_frozen () const
Getter for is_frozen.
bool ends_with (size_type pos1, const char *other) const
Compare the end of this string to a C-style string.
const char * suffix (const char *test_name) const
Given a dot-conjoined test name, find the part of the test name that follows this name, as a prefix.
template<typename Arg >
void set_name (Arg &&arg)
Set the name from the given input, as a string.
template<typename First , typename... Rest>
void set_name (First &&first, Rest &&... rest)
Set the name as a dot-conjoined string of the given inputs.
void verify_unfrozen_name () const
Verify that the name is not frozen.
void validate_name (const char *file, unsigned int line, const char *variable_type, const char *variable_name)
Checks whether a name is trivially invalid, failing if it is.
void freeze_name ()
Freeze the name – i.e., denote that the name as no longer settable.
Static Public Member Functions
static char * construct_name (const char *name_item1)
Create a copy of the provided name.
static char * construct_name (const char *name_item1, const char *name_item2)
Construct a name as a dot-conjoined string.
static char * construct_name (const char *name_item1, const char *name_item2, const char *name_item3)
Construct a name as a dot-conjoined string.
static char * construct_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4)
Construct a name as a dot-conjoined string.
static char * construct_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5)
Construct a name as a dot-conjoined string.
static char * construct_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5, const char *name_item6)
Construct a name as a dot-conjoined string.
static char * construct_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5, const char *name_item6, const char *name_item7)
Construct a name as a dot-conjoined string.
static char * vconstruct_name (const char *name_item,...)
Construct a name as a dot-conjoined string.
static char * va_construct_name (const char *name_item, va_list args)
Construct a name as a dot-conjoined string.
static const char * suffix (const char *prefix, const char *name)
Given a prefix and a dot-conjoined name, find the part of the name that follows the prefix.
static const std::string demangle (const std::type_info &info)
Demangle a C++ name.
static void validate_name (const char *file, unsigned int line, const char *variable_value, const char *variable_type, const char *variable_name)
Checks whether a name is trivially invalid, failing if it is.
template<typename Arg >
static std::string construct_name_string (Arg &&arg)
Construct a name from the given input, as a string.
template<typename First , typename... Rest>
static std::string construct_name_string (First &&first, Rest &&... rest)
Construct a name as a dot-conjoined string of the given inputs.
Protected Member Functions
void unfreeze_name ()
Unfreeze the name – i.e., denote that the name is now settable.
Private Attributes
std::string name
The item's name.
bool is_frozen
Indicates whether the name is frozen.
Friends
class InputProcessor
void init_attrjeod__NamedItem ()
Detailed Description
Provides a set of static methods for constructing dot-conjoined names.
The methods defined in this class allocate memory and do not release it. Releasing that memory is the responsibility of the calling function. Use the macro JEOD_DELETE_ARRAY to release this memory.
Prior to JEOD 4.0, the NamedItem class was not instantiable. It is in JEOD 4.0. The NamedItem class forms the basis of a thing with a name, with the name being a std::string. The construct_name functions and & related functions that allocate a C-style string are deprecated.
Definition at line 90 of file named_item.hh.
Member Typedef Documentation
size_type
using jeod::NamedItem::size_type = std::string::size_type
The size type used in std::string.
Definition at line 99 of file named_item.hh.
Constructor & Destructor Documentation
NamedItem() [1/3]
jeod::NamedItem::NamedItem (std::string name_in = std::string(), bool frozen_in = false) inline
Default constructor.
This is the default constructor by virtue of the defaults.
Parameters
name_in Initial value of the name, defaults to the empty string.
frozen_in Initial value of is_frozen, defaults to false.
Definition at line 361 of file named_item.hh.
NamedItem() [2/3]
jeod::NamedItem::NamedItem (const NamedItem &) default
Copy constructor.
The default implementation works fine.
NamedItem() [3/3]
jeod::NamedItem::NamedItem (NamedItem &&) default
Move constructor.
The default implementation works fine.
~NamedItem()
virtual jeod::NamedItem::~NamedItem () virtual default
Destructor.
The default implementation virtually works fine.
Member Function Documentation
c_str()
const char* jeod::NamedItem::c_str () const inline
Getter for name, as a C-style string.
Definition at line 439 of file named_item.hh.
References name.
Referenced by jeod::DynManager::add_dyn_body(), jeod::DynamicsIntegrationGroup::add_dyn_body(), jeod::DynManager::add_mass_body(), jeod::DynBody::add_mass_body(), jeod::DynBody::add_mass_body_frames(), jeod::DynBody::add_mass_body_validate(), jeod::MassBody::add_mass_point(), jeod::DynBody::add_mass_point(), jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), jeod::JeodBaseTime::add_type_update(), jeod::BodyDetach::apply(), jeod::BodyReattach::apply(), jeod::MassBodyInit::apply(), jeod::DynBodyInitNedState::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBody::attach_child(), jeod::MassBody::attach_root_body(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::StructureIntegratedDynBody::attach_update_properties(), jeod::MassBody::attach_validate_child(), jeod::DynBody::attach_validate_child(), jeod::MassBody::attach_validate_parent(), jeod::DynBody::attach_validate_parent(), jeod::DynManager::check_for_uninitialized_states(), jeod::check_frame_ownership(), jeod::DynBody::compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::TimeUDE::convert_epoch_to_update(), jeod::DynBody::create_body_integrators(), jeod::DynamicsIntegrationGroup::delete_dyn_body(), jeod::StructureIntegratedDynBody::detach(), jeod::MassBody::detach(), jeod::DynBody::detach(), jeod::MassBody::detach_validate_child(), jeod::MassBody::detach_validate_parent(), jeod::DynBodyInit::find_body_frame(), jeod::DynBody::find_body_frame(), jeod::MassPoint::get_name(), jeod::TimeConverter_Dyn_TAI::initialize(), jeod::TimeConverter_Dyn_UDE::initialize(), jeod::TimeConverter_STD_UDE::initialize(), jeod::LvlhDerivedState::initialize(), jeod::DerivedState::initialize(), jeod::OrbElemDerivedState::initialize(), jeod::NedDerivedState::initialize(), jeod::DynBodyFrameSwitch::initialize(), jeod::DynBodyInit::initialize(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), jeod::TimeStandard::initialize_initializer_time(), jeod::TimeUDE::initialize_initializer_time(), jeod::DynBody::initialize_model(), jeod::DynBody::migrate_integrable_objects(), jeod::MassBody::print_body(), jeod::DynBody::propagate_state(), jeod::MassBody::reattach(), jeod::TimeManager::register_time(), jeod::TimeManager::register_time_named(), jeod::DynBody::remove_mass_body(), jeod::TimeUDE::set_epoch_dyn(), jeod::TimeUDE::set_epoch_initializing_value(), jeod::TimeUDE::set_epoch_std(), jeod::TimeUDE::set_epoch_ude(), jeod::TimeUDE::set_initial_times(), jeod::DynBody::set_integ_frame(), jeod::StructureIntegratedDynBody::set_solver(), jeod::DynBody::set_state_source(), jeod::DynBody::switch_integration_frames(), jeod::JeodBaseTime::update(), jeod::SurfaceModel::update_articulation(), jeod::TimeUDE::verify_epoch(), jeod::TimeUDE::verify_init(), jeod::TimeConverter::verify_setup(), and jeod::MassBody::~MassBody().
construct_name() [1/7]
static char* jeod::NamedItem::construct_name (const char * name_item1) inline static
Create a copy of the provided name.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
Definition at line 107 of file named_item.hh.
References vconstruct_name().
Referenced by jeod::DerivedState::initialize(), jeod::DynBodyInitOrbit::initialize(), jeod::De4xxEphemeris::initialize_file(), jeod::PropagatedPlanet::initialize_model(), and jeod::EphemerisItem::set_name().
construct_name() [2/7]
static char* jeod::NamedItem::construct_name (const char * name_item1, const char * name_item2) inline static
Construct a name as a dot-conjoined string.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
Definition at line 119 of file named_item.hh.
References vconstruct_name().
construct_name() [3/7]
static char* jeod::NamedItem::construct_name (const char * name_item1, const char * name_item2, const char * name_item3) inline static
Construct a name as a dot-conjoined string.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
Definition at line 135 of file named_item.hh.
References vconstruct_name().
construct_name() [4/7]
static char* jeod::NamedItem::construct_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4) inline static
Construct a name as a dot-conjoined string.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
Definition at line 154 of file named_item.hh.
References vconstruct_name().
construct_name() [5/7]
static char* jeod::NamedItem::construct_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4, const char * name_item5) inline static
Construct a name as a dot-conjoined string.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
[in] name_item5 Fifth part of the name
Definition at line 176 of file named_item.hh.
References vconstruct_name().
construct_name() [6/7]
static char* jeod::NamedItem::construct_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4, const char * name_item5, const char * name_item6) inline static
Construct a name as a dot-conjoined string.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
[in] name_item5 Fifth part of the name
[in] name_item6 Sixth part of the name
Definition at line 201 of file named_item.hh.
References vconstruct_name().
construct_name() [7/7]
static char* jeod::NamedItem::construct_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4, const char * name_item5, const char * name_item6, const char * name_item7) inline static
Construct a name as a dot-conjoined string.
Returns
The constructed name
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
[in] name_item5 Fifth part of the name
[in] name_item6 Sixth part of the name
[in] name_item7 Seventh part of the name
Definition at line 229 of file named_item.hh.
References vconstruct_name().
construct_name_string() [1/2]
template<typename Arg > static std::string jeod::NamedItem::construct_name_string (Arg && arg) inline static
Construct a name from the given input, as a string.
The input must not be the empty string or the null pointer.
Template Parameters
Arg Type of the argument to construct_name_string.
Parameters
arg Argument to construct_name_string.
Returns
std::string that is conceptually equal to (==) arg.
Definition at line 323 of file named_item.hh.
References validate_name().
Referenced by jeod::LineContactPair::initialize_pair(), jeod::PointContactPair::initialize_pair(), jeod::LinePointContactPair::initialize_pair(), jeod::RefFrame::set_name(), and set_name().
construct_name_string() [2/2]
template<typename First , typename... Rest> static std::string jeod::NamedItem::construct_name_string (First && first, Rest &&... rest) inline static
Construct a name as a dot-conjoined string of the given inputs.
Each input must not be the empty string or the null pointer.
Template Parameters
First Type of the first argument to construct_name_string.
Rest Types of the remaining arguments to construct_name_string.
Parameters
first First argument to construct_name_string.
rest Remaining arguments to construct_name_string.
Returns
The given inputs as a dot-conjoined string.
Definition at line 340 of file named_item.hh.
References validate_name().
demangle()
const std::string jeod::NamedItem::demangle (const std::type_info & info) static
Demangle a C++ name.
Returns
Demangled name
Parameters
[in] info Typeinfo to be demangled
Definition at line 60 of file named_item_demangle.cc.
Referenced by jeod::JeodMemoryManager::deregister_container(), jeod::JeodTrickMemoryInterface::find_attributes(), jeod::DerivedState::initialize(), jeod::BodyAction::initialize(), jeod::JeodMemoryManager::register_container(), and jeod::JeodMemoryTypeDescriptor::type_spec().
ends_with()
bool jeod::NamedItem::ends_with (size_type pos1, const char * other) const inline
Compare the end of this string to a C-style string.
See std::string::compare.
Parameters
pos1 The start index in the name.
other The C-style null-terminated string.
Returns
True if the end part of the name equals the given C-style string.
Definition at line 467 of file named_item.hh.
References name.
Referenced by jeod::DynManager::find_dyn_body(), and jeod::DynManager::find_mass_body().
freeze_name()
void jeod::NamedItem::freeze_name () inline
Freeze the name – i.e., denote that the name as no longer settable.
Definition at line 538 of file named_item.hh.
References is_frozen.
Referenced by jeod::MassBody::add_mass_point().
get_is_frozen()
bool jeod::NamedItem::get_is_frozen () const inline
Getter for is_frozen.
Definition at line 455 of file named_item.hh.
References is_frozen.
get_name()
const std::string& jeod::NamedItem::get_name (void) const inline
Getter for name.
Definition at line 431 of file named_item.hh.
References name.
Referenced by jeod::DynBody::add_mass_body_validate(), jeod::TimeStandard::add_type_initialize(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), operator==(), operator==(), and jeod::TimeManager::register_time_named().
operator=() [1/3]
NamedItem& jeod::NamedItem::operator= (const NamedItem & src) inline
Copy assignment.
Only the name is copied, and only if the name isn't frozen.
Definition at line 392 of file named_item.hh.
References name, and verify_unfrozen_name().
operator=() [2/3]
NamedItem& jeod::NamedItem::operator= (NamedItem && src) inline
Move assignment.
The default implementation works fine.
Definition at line 402 of file named_item.hh.
References name, and verify_unfrozen_name().
operator=() [3/3]
NamedItem& jeod::NamedItem::operator= (const std::string & name_in) inline
Assignment from a string.
Definition at line 413 of file named_item.hh.
References name, and verify_unfrozen_name().
operator==()
bool jeod::NamedItem::operator== (const NamedItem & rhs) inline
Comparison of names.
Definition at line 423 of file named_item.hh.
References get_name(), and name.
set_name() [1/2]
template<typename Arg > void jeod::NamedItem::set_name (Arg && arg) inline
Set the name from the given input, as a string.
The input must not be the empty string or the null pointer.
Template Parameters
Arg Type of the argument to construct_name_string.
Parameters
arg Argument to construct_name_string.
Definition at line 492 of file named_item.hh.
References construct_name_string(), name, and verify_unfrozen_name().
Referenced by jeod::MassBody::add_mass_point(), and jeod::PropagatedPlanet::initialize_model().
set_name() [2/2]
template<typename First , typename... Rest> void jeod::NamedItem::set_name (First && first, Rest &&... rest) inline
Set the name as a dot-conjoined string of the given inputs.
Each input must not be the empty string or the null pointer.
Template Parameters
First Type of the first argument to construct_name_string.
Rest Types of the remaining arguments to construct_name_string.
Parameters
first First argument to construct_name_string.
rest Remaining arguments to construct_name_string.
Definition at line 507 of file named_item.hh.
References construct_name_string(), name, and verify_unfrozen_name().
size()
size_type jeod::NamedItem::size (void) const inline
Getter for the length of the name.
Definition at line 447 of file named_item.hh.
References name.
Referenced by jeod::MassBody::find_mass_point(), jeod::DynBody::find_vehicle_point(), jeod::DynBody::initialize_model(), and jeod::PropagatedPlanet::initialize_model().
suffix() [1/2]
const char * jeod::NamedItem::suffix (const char * prefix, const char * name) static
Given a prefix and a dot-conjoined name, find the part of the name that follows the prefix.
For names of the form "prefix.suffix", this function returns a pointer to "suffix". The function returns the input name if the name does not start with "prefix.".
Returns
Suffix
Parameters
[in] prefix Prefix
[in] name Name, possibly prefixed
Definition at line 143 of file named_item.cc.
References name.
Referenced by jeod::MassBody::add_mass_point(), jeod::DynBody::find_body_frame(), jeod::MassBody::find_mass_point(), jeod::DynBody::find_vehicle_point(), jeod::DynBodyInitOrbit::initialize(), and suffix().
suffix() [2/2]
const char* jeod::NamedItem::suffix (const char * test_name) const inline
Given a dot-conjoined test name, find the part of the test name that follows this name, as a prefix.
For names of the form "prefix.suffix", this function returns a pointer to "suffix". The function returns the input name if the name does not start with "prefix.".
Returns
Suffix
Parameters
[in] test_name Test name, possibly prefixed
Definition at line 480 of file named_item.hh.
References name, and suffix().
unfreeze_name()
void jeod::NamedItem::unfreeze_name () inline protected
Unfreeze the name – i.e., denote that the name is now settable.
This exists solely to parallel freeze_name().
Definition at line 550 of file named_item.hh.
References is_frozen.
va_construct_name()
char * jeod::NamedItem::va_construct_name (const char * name_item, va_list args) static
Construct a name as a dot-conjoined string.
Notes –
This function takes a va_list argument that contains any additional strings to be appended.
The calling function must form the args argument by invoking va_start().
The calling function should not invoke va_end(); this is done inside va_construct_name().
The last argument embodied in the args argument must be a NULL to signal the end of the argument list.
Returns
The constructed name
Parameters
[in] name_item First part of the name
[in] args Rest of the name
Definition at line 75 of file named_item.cc.
References jeod::NamedItemMessages::bad_args, jeod::MessageHandler::fail(), JEOD_ALLOC_PRIM_ARRAY, MAX_NAME_ITEMS, and name.
Referenced by vconstruct_name().
validate_name() [1/2]
void jeod::NamedItem::validate_name (const char * file, unsigned int line, const char * variable_value, const char * variable_type, const char * variable_name) static
Checks whether a name is trivially invalid, failing if it is.
Parameters
[in] file Usually FILE
[in] line Usually LINE
[in] variable_value Value to check
[in] variable_type Variable description
[in] variable_name Variable name
Definition at line 169 of file named_item.cc.
References jeod::MessageHandler::fail(), and jeod::NamedItemMessages::invalid_name.
Referenced by jeod::InteractionSurfaceFactory::add_facet_params(), jeod::RelativeKinematics::add_relstate(), construct_name_string(), jeod::DerivedState::find_planet(), jeod::Facet::initialize_mass_connection(), jeod::SurfaceModel::initialize_mass_connections(), jeod::EphemerisItem::validate_name(), and validate_name().
validate_name() [2/2]
void jeod::NamedItem::validate_name (const char * file, unsigned int line, const char * variable_type, const char * variable_name) inline
Checks whether a name is trivially invalid, failing if it is.
Parameters
[in] file Usually FILE
[in] line Usually LINE
[in] variable_type Variable description
[in] variable_name Variable name
Definition at line 526 of file named_item.hh.
References name, and validate_name().
vconstruct_name()
char * jeod::NamedItem::vconstruct_name (const char * name_item, ...) static
Construct a name as a dot-conjoined string.
Note that this is a varargs function. The last argument must be (const char *)NULL to signal the end of the argument list.
Returns
The constructed name
Parameters
[in] name_item First part of the name
[in] ... Rest of the name
Definition at line 55 of file named_item.cc.
References name, and va_construct_name().
Referenced by construct_name().
verify_unfrozen_name()
void jeod::NamedItem::verify_unfrozen_name () const
Verify that the name is not frozen.
Definition at line 197 of file named_item.cc.
References jeod::MessageHandler::fail(), jeod::NamedItemMessages::frozen_name, is_frozen, and name.
Referenced by operator=(), and set_name().
Friends And Related Function Documentation
init_attrjeod__NamedItem
void init_attrjeod__NamedItem () friend
InputProcessor
friend class InputProcessor friend
Definition at line 92 of file named_item.hh.
Field Documentation
is_frozen
bool jeod::NamedItem::is_frozen private
Indicates whether the name is frozen.
trick_units(–)
Definition at line 566 of file named_item.hh.
Referenced by freeze_name(), get_is_frozen(), unfreeze_name(), and verify_unfrozen_name().
name
std::string jeod::NamedItem::name private
The item's name.
trick_units(–)
Definition at line 561 of file named_item.hh.
Referenced by c_str(), ends_with(), get_name(), operator=(), operator==(), set_name(), size(), suffix(), va_construct_name(), validate_name(), vconstruct_name(), and verify_unfrozen_name().
The documentation for this class was generated from the following files:
named_item.hh
named_item.cc
named_item_demangle.cc