JEOD: jeod::NedDerivedState Class Reference
jeod::NedDerivedState Class Reference
The class used for deriving the North-East-Down representations of a subject DynBody's state.
#include <ned_derived_state.hh>
Public Member Functions
NedDerivedState ()
NedDerivedState default constructor.
~NedDerivedState () override
NedDerivedState destructor.
void set_use_alt_pfix (const bool use_alt_pfix_in)
Setter for use_alt_pfix.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a LvlhDerivedState.
void update (void) override
Update the state.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
bool register_frame
If set (default), the NED frame will be registered with the dynamics manager at initialization time.
NorthEastDown ned_state
The NorthEastDown frame plus spherical/elliptical selector.
Planet * planet
The planet, the name of which is specified by the inherited reference_name data member.
Data Fields inherited from jeod::DerivedState
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Member Functions
void compute_ned_frame (const RefFrameTrans &rel_trans)
Update the state.
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Protected Attributes
bool use_alt_pfix
Use pfix or alt_pfix flag.
EphemerisRefFrame * pfix_ptr
Pointer to planet fixed frame to be used, either pfix or alt_pfix.
RefFrameState pfix_rel_state
Vehicle state relative to the planet-center, planet-fixed frame.
Protected Attributes inherited from jeod::DerivedState
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
NedDerivedState (const NedDerivedState &)
NedDerivedState & operator= (const NedDerivedState &)
Friends
class InputProcessor
void init_attrjeod__NedDerivedState ()
Detailed Description
The class used for deriving the North-East-Down representations of a subject DynBody's state.
Definition at line 87 of file ned_derived_state.hh.
Constructor & Destructor Documentation
NedDerivedState() [1/2]
jeod::NedDerivedState::NedDerivedState (void)
NedDerivedState default constructor.
Definition at line 53 of file ned_derived_state.cc.
~NedDerivedState()
jeod::NedDerivedState::~NedDerivedState (void) override
NedDerivedState destructor.
Definition at line 71 of file ned_derived_state.cc.
References jeod::NorthEastDown::ned_frame, ned_state, pfix_ptr, register_frame, jeod::RefFrame::remove_from_parent(), and jeod::Subscription::unsubscribe().
NedDerivedState() [2/2]
jeod::NedDerivedState::NedDerivedState (const NedDerivedState &) private
Member Function Documentation
compute_ned_frame()
void jeod::NedDerivedState::compute_ned_frame (const RefFrameTrans & rel_trans) protected
Update the state.
Parameters
[in] rel_trans Planet relative state
Definition at line 169 of file ned_derived_state.cc.
References jeod::NorthEastDown::build_ned_orientation(), ned_state, jeod::RefFrameTrans::position, jeod::NorthEastDown::set_ned_trans_states(), and jeod::RefFrameTrans::velocity.
Referenced by update().
initialize()
void jeod::NedDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of a LvlhDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DerivedState.
Definition at line 111 of file ned_derived_state.cc.
References jeod::RefFrame::add_child(), jeod::EphemeridesManager::add_ref_frame(), jeod::BasePlanet::alt_pfix, jeod::NamedItem::c_str(), jeod::DerivedState::find_planet(), jeod::DerivedState::initialize(), jeod::PlanetFixedPosition::initialize(), jeod::DynBody::name, jeod::NorthEastDown::ned_frame, ned_state, jeod::BasePlanet::pfix, pfix_ptr, planet, jeod::DerivedState::reference_name, register_frame, jeod::RefFrame::set_name(), jeod::Subscription::subscribe(), and use_alt_pfix.
operator=()
NedDerivedState& jeod::NedDerivedState::operator= (const NedDerivedState &) private
set_use_alt_pfix()
void jeod::NedDerivedState::set_use_alt_pfix (const bool use_alt_pfix_in)
Setter for use_alt_pfix.
Definition at line 95 of file ned_derived_state.cc.
References use_alt_pfix.
update()
void jeod::NedDerivedState::update (void) override virtual
Update the state.
Reimplemented from jeod::DerivedState.
Definition at line 151 of file ned_derived_state.cc.
References jeod::DynBody::composite_body, compute_ned_frame(), jeod::RefFrame::compute_relative_state(), jeod::NorthEastDown::ned_frame, ned_state, pfix_ptr, pfix_rel_state, jeod::RefFrame::set_timestamp(), jeod::DerivedState::subject, jeod::RefFrame::timestamp(), and jeod::RefFrameState::trans.
Friends And Related Function Documentation
init_attrjeod__NedDerivedState
void init_attrjeod__NedDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file ned_derived_state.hh.
Field Documentation
ned_state
NorthEastDown jeod::NedDerivedState::ned_state
The NorthEastDown frame plus spherical/elliptical selector.
trick_units(–)
Definition at line 106 of file ned_derived_state.hh.
Referenced by compute_ned_frame(), initialize(), update(), and ~NedDerivedState().
pfix_ptr
EphemerisRefFrame* jeod::NedDerivedState::pfix_ptr protected
Pointer to planet fixed frame to be used, either pfix or alt_pfix.
Definition at line 126 of file ned_derived_state.hh.
Referenced by initialize(), update(), and ~NedDerivedState().
pfix_rel_state
RefFrameState jeod::NedDerivedState::pfix_rel_state protected
Vehicle state relative to the planet-center, planet-fixed frame.
trick_units(–)
Definition at line 131 of file ned_derived_state.hh.
Referenced by update().
planet
Planet* jeod::NedDerivedState::planet
The planet, the name of which is specified by the inherited reference_name data member.
trick_units(–)
Definition at line 112 of file ned_derived_state.hh.
Referenced by initialize().
register_frame
bool jeod::NedDerivedState::register_frame
If set (default), the NED frame will be registered with the dynamics manager at initialization time.
This will make the frame accessible through the dynamic manager via its find_ref_frame method.trick_units(–)
Definition at line 101 of file ned_derived_state.hh.
Referenced by initialize(), and ~NedDerivedState().
use_alt_pfix
bool jeod::NedDerivedState::use_alt_pfix protected
Use pfix or alt_pfix flag.
Definition at line 120 of file ned_derived_state.hh.
Referenced by initialize(), and set_use_alt_pfix().
The documentation for this class was generated from the following files:
ned_derived_state.hh
ned_derived_state.cc