JEOD: jeod::GaussJacksonIntegratorBase< State, Primer > Class Template Reference
jeod::GaussJacksonIntegratorBase< State, Primer > Class Template Reference
Base template class for integrating state via the Gauss-Jackson technique.
#include <gauss_jackson_integrator_base.hh>
Public Member Functions
GaussJacksonIntegratorBase ()
Default constructor.
GaussJacksonIntegratorBase (const er7_utils::IntegratorConstructor &priming_constructor, const GaussJacksonIntegrationControls &controls, unsigned int size_in, er7_utils::IntegrationControls &priming_controls)
Non-default constructor.
GaussJacksonIntegratorBase (const GaussJacksonIntegratorBase &src)
Copy constructor.
~GaussJacksonIntegratorBase ()
Destructor.
Data Fields
const GaussJacksonCoeffs * coeff
The summed Adams and Gauss-Jackson coefficients, in ordinate form.
const GaussJacksonStateMachine * state_machine
The Gauss-Jackson state machine.
Primer * primer
The integrator used to prime the Gauss-Jackson integration process.
State init_state
The state at the time of the last reset.
State delinv
Inverse backward differences.
State corrector_sum
Speed hack for the corrector.
er7_utils::DoubleTwoDArray acc_hist
Acceleration history.
er7_utils::DoubleTwoDArray pos_hist
Position history (or velocity history in case of a first order ODE).
double relative_tolerance
Number that indicates the allowable relative difference for two states to be considered converged.
double absolute_tolerance
Number that indicates the allowable absolute difference for two states to be considered converged.
double velocity_corrector
Correction coefficient for the first integral (velocity).
double position_corrector
Correction coefficient for the second integral (position).
GaussJacksonStateMachine::FsmState fsm_state
Finite state machine state.
unsigned int max_history_size
Maximum history size.
unsigned int initial_order
Initial order.
unsigned int order
Current order.
unsigned int size
State size.
unsigned int history_length
Current history length.
Protected Member Functions
void base_reset ()
Reset the integrator.
er7_utils::IntegratorResult base_integrate (double dyn_dt, unsigned int target_stage, double const *deriv, State state)
Propagate state to the specified target_stage.
void swap (GaussJacksonIntegratorBase &other)
Non-throwing swap.
Private Member Functions
void start_cycle (double dt, const double *acc, const State &state)
Start an integration cycle.
bool edit_point (double dt, const double *acc, State &state)
Edit the specified point using the mid-corrector that pertains to the point being edited, which is that at history_length.
bool integrate_gj (double dt, unsigned int target_stage, int advance_index, int target_index, const double *acc, const double *const *ahist, State &state)
Integrate using the Gauss-Jackson predictor and corrector.
void downsample_hist ()
Downsample the acceleration and position histories.
void rotate_acc_hist ()
Rotate the acceleration history.
er7_utils::IntegratorResult integrate_primer (double dyn_dt, unsigned int target_stage, double const *deriv, State &state)
Integrate state using the primer.
void save_epoch_data (const double *acc, const State &state)
Save epoch data.
void save_comparison_data (const State &state, double *pos_hist_elem)
Save comparison data.
void initialize_edit_integration_constants (double dt)
Initialize the integration constants (i.e., delinv).
void initialize_predictor_integration_constants (double dt)
Initialize the integration constants (i.e., delinv).
void advance_edit_integration_constants (unsigned int index)
Advance the integration constants by one cycle.
void advance_predictor_integration_constants (unsigned int index)
Advance the integration constants by one cycle.
void mid_correct (unsigned int coeff_idx, double dt, State &state)
Apply a mid-corrector.
void predict (double dt, double const *const *ahist, State &state)
Apply the predictor.
void correct (double dt, const double *acc, State &state)
Apply the corrector.
bool test_for_convergence (const State &state, double *hist_data)
Test for convergence.
void swap_state (State &item, State &other_item)
Swap state data with another of the same.
void replicate_state (const State &source, State &target)
Replicate state data.
void allocate_state_contents (State &item)
Allocate memory for a state item.
void deallocate_state_contents (State &item)
Deallocate state item memory.
GaussJacksonIntegratorBase & operator= (const GaussJacksonIntegratorBase &)
Not implemented.
template<>
er7_utils::FirstOrderODEIntegrator * create_primer (const er7_utils::IntegratorConstructor &priming_constructor, unsigned int size, er7_utils::IntegrationControls &priming_controls)
Create the priming integrator.
template<>
er7_utils::FirstOrderODEIntegrator * replicate_primer (const er7_utils::FirstOrderODEIntegrator *src)
Replicate the priming integrator.
template<>
er7_utils::IntegratorResult integrate_primer (double dyn_dt, unsigned int target_stage, double const *deriv, GaussJacksonOneState &state)
Integrate with the primer.
template<>
void save_epoch_data (const double *acc, const GaussJacksonOneState &state)
Save epoch data.
template<>
void save_comparison_data (const GaussJacksonOneState &state, double *pos_hist_elem)
Save comparison data.
template<>
void initialize_edit_integration_constants (double dt)
Initialize the integration constants (i.e., delinv).
template<>
void advance_edit_integration_constants (unsigned int index)
Advance the integration constants by one cycle.
template<>
void initialize_predictor_integration_constants (double dt)
Initialize the integration constants (i.e., delinv).
template<>
void advance_predictor_integration_constants (unsigned int index)
Advance the integration constants by one cycle.
template<>
void mid_correct (unsigned int coeff_idx, double dt, GaussJacksonOneState &state)
Apply a mid-corrector.
template<>
void predict (double dt, double const *const *ahist, GaussJacksonOneState &state)
Apply the predictor.
template<>
void correct (double dt, const double *acc, GaussJacksonOneState &state)
Apply the corrector.
template<>
bool test_for_convergence (const GaussJacksonOneState &state, double *hist_data)
Test for convergence.
template<>
void swap_state (GaussJacksonOneState &item, GaussJacksonOneState &other_item)
Swap state data with another of the same.
template<>
void replicate_state (GaussJacksonOneState const &source, GaussJacksonOneState &target)
Replicate state data.
template<>
void allocate_state_contents (GaussJacksonOneState &item)
Allocate memory for a state item.
template<>
void deallocate_state_contents (GaussJacksonOneState &item)
Deallocate state item memory.
template<>
er7_utils::SecondOrderODEIntegrator * create_primer (const er7_utils::IntegratorConstructor &priming_constructor, unsigned int size, er7_utils::IntegrationControls &priming_controls)
template<>
er7_utils::SecondOrderODEIntegrator * replicate_primer (const er7_utils::SecondOrderODEIntegrator *src)
template<>
er7_utils::IntegratorResult integrate_primer (double dyn_dt, unsigned int target_stage, double const *deriv, GaussJacksonTwoState &state)
Integrate with the primer.
template<>
void save_epoch_data (const double *acc, const GaussJacksonTwoState &state)
Save epoch data.
template<>
void save_comparison_data (const GaussJacksonTwoState &state, double *pos_hist_elem)
Save comparison data.
template<>
void initialize_edit_integration_constants (double dt)
Initialize the integration constants (i.e., delinv).
template<>
void advance_edit_integration_constants (unsigned int index)
Advance the integration constants by one cycle.
template<>
void initialize_predictor_integration_constants (double dt)
Initialize the integration constants (i.e., delinv).
template<>
void advance_predictor_integration_constants (unsigned int index)
Advance the integration constants by one cycle.
template<>
void mid_correct (unsigned int coeff_idx, double dt, GaussJacksonTwoState &state)
Apply a mid-corrector.
template<>
void predict (double dt, double const *const *ahist, GaussJacksonTwoState &state)
Apply the predictor.
template<>
void correct (double dt, const double *acc, GaussJacksonTwoState &state)
Apply the corrector.
template<>
bool test_for_convergence (const GaussJacksonTwoState &state, double *hist_data)
Test for convergence.
template<>
void swap_state (GaussJacksonTwoState &item, GaussJacksonTwoState &other_item)
Swap state data with another of the same.
template<>
void replicate_state (GaussJacksonTwoState const &source, GaussJacksonTwoState &target)
Replicate state data.
template<>
void allocate_state_contents (GaussJacksonTwoState &item)
Allocate memory for a state item.
template<>
void deallocate_state_contents (GaussJacksonTwoState &item)
Deallocate state item memory.
Static Private Member Functions
static Primer * create_primer (const er7_utils::IntegratorConstructor &priming_constructor, unsigned int size_in, er7_utils::IntegrationControls &priming_controls)
Create the integrator to be used during priming.
static Primer * replicate_primer (const Primer *src)
Create a replica of the provided primer.
Detailed Description
template<typename State, typename Primer>
class jeod::GaussJacksonIntegratorBase< State, Primer >
Base template class for integrating state via the Gauss-Jackson technique.
Template Parameters
State Structure that contains the state.
Primer Class for priming the Gauss-Jackson integrator.
Definition at line 91 of file gauss_jackson_integrator_base.hh.
Constructor & Destructor Documentation
GaussJacksonIntegratorBase() [1/3]
template<typename State , typename Primer > jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase () inline
Default constructor.
Definition at line 196 of file gauss_jackson_integrator_base.hh.
GaussJacksonIntegratorBase() [2/3]
template<typename State , typename Primer > jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase (const er7_utils::IntegratorConstructor & priming_constructor, const GaussJacksonIntegrationControls & controls, unsigned int size_in, er7_utils::IntegrationControls & priming_controls) inline
Non-default constructor.
Parameters
priming_constructor Integrator constructor for the technique used during priming.
controls The Gauss-Jackson integration controls that drives this state integrator.
size_in State size.
priming_controls Integration controls used during priming.
Definition at line 232 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist, er7_utils::TwoDArray< T >::allocate(), jeod::GaussJacksonIntegratorBase< State, Primer >::allocate_state_contents(), jeod::GaussJacksonIntegratorBase< State, Primer >::corrector_sum, jeod::GaussJacksonIntegratorBase< State, Primer >::create_primer(), jeod::GaussJacksonIntegratorBase< State, Primer >::delinv, jeod::GaussJacksonIntegratorBase< State, Primer >::init_state, jeod::GaussJacksonIntegratorBase< State, Primer >::max_history_size, jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist, jeod::GaussJacksonIntegratorBase< State, Primer >::primer, and jeod::GaussJacksonIntegratorBase< State, Primer >::size.
GaussJacksonIntegratorBase() [3/3]
template<typename State , typename Primer > jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase (const GaussJacksonIntegratorBase< State, Primer > & src) inline
Copy constructor.
Parameters
src Item to be copied.
Definition at line 280 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::corrector_sum, jeod::GaussJacksonIntegratorBase< State, Primer >::delinv, jeod::GaussJacksonIntegratorBase< State, Primer >::init_state, jeod::GaussJacksonIntegratorBase< State, Primer >::primer, jeod::GaussJacksonIntegratorBase< State, Primer >::replicate_primer(), and jeod::GaussJacksonIntegratorBase< State, Primer >::replicate_state().
~GaussJacksonIntegratorBase()
template<typename State , typename Primer > jeod::GaussJacksonIntegratorBase< State, Primer >::~GaussJacksonIntegratorBase () inline
Destructor.
Definition at line 317 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::corrector_sum, jeod::GaussJacksonIntegratorBase< State, Primer >::deallocate_state_contents(), jeod::GaussJacksonIntegratorBase< State, Primer >::delinv, jeod::GaussJacksonIntegratorBase< State, Primer >::init_state, and jeod::GaussJacksonIntegratorBase< State, Primer >::primer.
Member Function Documentation
advance_edit_integration_constants() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::advance_edit_integration_constants (unsigned int index) inline private
Advance the integration constants by one cycle.
Definition at line 203 of file gauss_jackson_integrator_base_first.hh.
References ER7_UTILS_RESTRICT.
advance_edit_integration_constants() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::advance_edit_integration_constants (unsigned int index) inline private
Advance the integration constants by one cycle.
Definition at line 203 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::second.
advance_edit_integration_constants() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::advance_edit_integration_constants (unsigned int index) private
Advance the integration constants by one cycle.
Parameters
index Coefficient index.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point().
advance_predictor_integration_constants() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::advance_predictor_integration_constants (unsigned int index) inline private
Advance the integration constants by one cycle.
Definition at line 240 of file gauss_jackson_integrator_base_first.hh.
References ER7_UTILS_RESTRICT.
advance_predictor_integration_constants() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::advance_predictor_integration_constants (unsigned int index) inline private
Advance the integration constants by one cycle.
Definition at line 240 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first.
advance_predictor_integration_constants() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::advance_predictor_integration_constants (unsigned int index) private
Advance the integration constants by one cycle.
Parameters
index Coefficient index.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj().
allocate_state_contents() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::allocate_state_contents (GaussJacksonOneState & item) inline private
Allocate memory for a state item.
Definition at line 385 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
allocate_state_contents() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::allocate_state_contents (GaussJacksonTwoState & item) inline private
Allocate memory for a state item.
Definition at line 390 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
allocate_state_contents() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::allocate_state_contents (State & item) private
Allocate memory for a state item.
Parameters
item State item to be allocated.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase().
base_integrate()
template<typename State , typename Primer > er7_utils::IntegratorResult jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate (double dyn_dt, unsigned int target_stage, double const * deriv, State state) inline protected
Propagate state to the specified target_stage.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] deriv Acceleration vector.
[in,out] state State vector(s).
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 350 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist, jeod::GaussJacksonStateMachine::BootstrapEdit, jeod::GaussJacksonStateMachine::BootstrapStep, jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point(), jeod::GaussJacksonIntegratorBase< State, Primer >::fsm_state, jeod::GaussJacksonIntegratorBase< State, Primer >::history_length, jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_primer(), jeod::GaussJacksonStateMachine::Operational, jeod::GaussJacksonIntegratorBase< State, Primer >::order, jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist, jeod::GaussJacksonStateMachine::Priming, jeod::GaussJacksonStateMachine::Reset, jeod::GaussJacksonIntegratorBase< State, Primer >::rotate_acc_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::save_comparison_data(), jeod::GaussJacksonIntegratorBase< State, Primer >::size, and jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle().
Referenced by jeod::GaussJacksonFirstOrderODEIntegrator::integrate(), and jeod::GaussJacksonSimpleSecondOrderODEIntegrator::integrate().
base_reset()
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::base_reset () inline protected
Reset the integrator.
Definition at line 333 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::fsm_state, jeod::GaussJacksonIntegratorBase< State, Primer >::history_length, jeod::GaussJacksonIntegratorBase< State, Primer >::initial_order, jeod::GaussJacksonIntegratorBase< State, Primer >::order, and jeod::GaussJacksonStateMachine::Reset.
Referenced by jeod::GaussJacksonFirstOrderODEIntegrator::reset_integrator(), and jeod::GaussJacksonSimpleSecondOrderODEIntegrator::reset_integrator().
correct() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::correct (double dt, const double * acc, GaussJacksonTwoState & state) inline private
Apply the corrector.
Definition at line 304 of file gauss_jackson_integrator_base_second.hh.
References ER7_UTILS_RESTRICT, jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
correct() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::correct (double dt, const double * acc, GaussJacksonOneState & state) inline private
Apply the corrector.
Definition at line 305 of file gauss_jackson_integrator_base_first.hh.
References ER7_UTILS_RESTRICT, and jeod::GaussJacksonOneState::first.
correct() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::correct (double dt, const double * acc, State & state) private
Apply the corrector.
Parameters
dt Dynamic time step.
acc Acceleration data.
state Corrected state.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj().
create_primer() [1/3]
template<> er7_utils::SecondOrderODEIntegrator * jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::create_primer (const er7_utils::IntegratorConstructor & priming_constructor, unsigned int size, er7_utils::IntegrationControls & priming_controls) inline private
Definition at line 99 of file gauss_jackson_integrator_base_second.hh.
create_primer() [2/3]
template<> er7_utils::FirstOrderODEIntegrator * jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::create_primer (const er7_utils::IntegratorConstructor & priming_constructor, unsigned int size, er7_utils::IntegrationControls & priming_controls) inline private
Create the priming integrator.
Definition at line 100 of file gauss_jackson_integrator_base_first.hh.
create_primer() [3/3]
template<typename State , typename Primer > static Primer* jeod::GaussJacksonIntegratorBase< State, Primer >::create_primer (const er7_utils::IntegratorConstructor & priming_constructor, unsigned int size_in, er7_utils::IntegrationControls & priming_controls) static private
Create the integrator to be used during priming.
Parameters
priming_constructor Integrator constructor for the technique used during priming.
size_in State size.
priming_controls Integration controls used during priming.
Returns
Constructed primer.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase().
deallocate_state_contents() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::deallocate_state_contents (GaussJacksonOneState & item) inline private
Deallocate state item memory.
Definition at line 399 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
deallocate_state_contents() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::deallocate_state_contents (GaussJacksonTwoState & item) inline private
Deallocate state item memory.
Definition at line 404 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
deallocate_state_contents() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::deallocate_state_contents (State & item) private
Deallocate state item memory.
Parameters
item State item to be deallocated.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::~GaussJacksonIntegratorBase().
downsample_hist()
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::downsample_hist () inline private
Downsample the acceleration and position histories.
Definition at line 629 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist, er7_utils::TwoDArray< T >::downsample(), jeod::GaussJacksonIntegratorBase< State, Primer >::history_length, and jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle().
edit_point()
template<typename State , typename Primer > bool jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point (double dt, const double * acc, State & state) inline private
Edit the specified point using the mid-corrector that pertains to the point being edited, which is that at history_length.
Parameters
[in] dt Dynamic time step, in dynamic time seconds.
[in] acc Acceleration vector.
[out] state State vector(s).
Definition at line 579 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::advance_edit_integration_constants(), jeod::GaussJacksonIntegratorBase< State, Primer >::history_length, jeod::GaussJacksonIntegratorBase< State, Primer >::mid_correct(), jeod::GaussJacksonIntegratorBase< State, Primer >::order, jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist, and jeod::GaussJacksonIntegratorBase< State, Primer >::test_for_convergence().
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate().
initialize_edit_integration_constants() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::initialize_edit_integration_constants (double dt) inline private
Initialize the integration constants (i.e., delinv).
Definition at line 183 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first.
initialize_edit_integration_constants() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::initialize_edit_integration_constants (double dt) inline private
Initialize the integration constants (i.e., delinv).
Definition at line 185 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
initialize_edit_integration_constants() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::initialize_edit_integration_constants (double dt) private
Initialize the integration constants (i.e., delinv).
Parameters
dt Dynamic time step.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle().
initialize_predictor_integration_constants() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::initialize_predictor_integration_constants (double dt) inline private
Initialize the integration constants (i.e., delinv).
Definition at line 219 of file gauss_jackson_integrator_base_second.hh.
initialize_predictor_integration_constants() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::initialize_predictor_integration_constants (double dt) inline private
Initialize the integration constants (i.e., delinv).
Definition at line 222 of file gauss_jackson_integrator_base_first.hh.
initialize_predictor_integration_constants() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::initialize_predictor_integration_constants (double dt) private
Initialize the integration constants (i.e., delinv).
Parameters
dt Dynamic time step.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle().
integrate_gj()
template<typename State , typename Primer > bool jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj (double dt, unsigned int target_stage, int advance_index, int target_index, const double * acc, const double *const * ahist, State & state) inline private
Integrate using the Gauss-Jackson predictor and corrector.
Parameters
[in] dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] advance_index Acceleration history index.
[in] target_index Position history index.
[in] acc Acceleration vector.
[in] ahist Acceleration vector history.
[out] state State vector(s).
Returns
True if step was successful, false otherwise.
Definition at line 603 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::advance_predictor_integration_constants(), jeod::GaussJacksonCoefficientsPair::apply(), jeod::GaussJacksonIntegratorBase< State, Primer >::coeff, jeod::GaussJacksonIntegratorBase< State, Primer >::correct(), jeod::GaussJacksonCoeffs::corrector, jeod::GaussJacksonIntegratorBase< State, Primer >::corrector_sum, jeod::GaussJacksonIntegratorBase< State, Primer >::order, jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist, jeod::GaussJacksonIntegratorBase< State, Primer >::predict(), jeod::GaussJacksonIntegratorBase< State, Primer >::save_comparison_data(), jeod::GaussJacksonIntegratorBase< State, Primer >::size, and jeod::GaussJacksonIntegratorBase< State, Primer >::test_for_convergence().
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate().
integrate_primer() [1/3]
template<> er7_utils::IntegratorResult jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::integrate_primer (double dyn_dt, unsigned int target_stage, double const * deriv, GaussJacksonTwoState & state) inline private
Integrate with the primer.
Definition at line 134 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
integrate_primer() [2/3]
template<> er7_utils::IntegratorResult jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::integrate_primer (double dyn_dt, unsigned int target_stage, double const * deriv, GaussJacksonOneState & state) inline private
Integrate with the primer.
Definition at line 136 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
integrate_primer() [3/3]
template<typename State , typename Primer > er7_utils::IntegratorResult jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_primer (double dyn_dt, unsigned int target_stage, double const * deriv, State & state) private
Integrate state using the primer.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] deriv Acceleration vector.
[in,out] state State vector(s).
Returns
The status (time advance, pass/fail status) of the integration.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate().
mid_correct() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::mid_correct (unsigned int coeff_idx, double dt, GaussJacksonTwoState & state) inline private
Apply a mid-corrector.
Definition at line 256 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
mid_correct() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::mid_correct (unsigned int coeff_idx, double dt, GaussJacksonOneState & state) inline private
Apply a mid-corrector.
Definition at line 259 of file gauss_jackson_integrator_base_first.hh.
References ER7_UTILS_RESTRICT, and jeod::GaussJacksonOneState::first.
mid_correct() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::mid_correct (unsigned int coeff_idx, double dt, State & state) private
Apply a mid-corrector.
Parameters
coeff_idx Coefficient index; item to be corrected.
dt Dynamic time step.
state Corrected state.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point().
operator=()
template<typename State , typename Primer > GaussJacksonIntegratorBase& jeod::GaussJacksonIntegratorBase< State, Primer >::operator= (const GaussJacksonIntegratorBase< State, Primer > &) private
Not implemented.
predict() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::predict (double dt, double const *const * ahist, GaussJacksonTwoState & state) inline private
Apply the predictor.
Definition at line 278 of file gauss_jackson_integrator_base_second.hh.
References ER7_UTILS_RESTRICT, jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
predict() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::predict (double dt, double const *const * ahist, GaussJacksonOneState & state) inline private
Apply the predictor.
Definition at line 282 of file gauss_jackson_integrator_base_first.hh.
References ER7_UTILS_RESTRICT, and jeod::GaussJacksonOneState::first.
predict() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::predict (double dt, double const *const * ahist, State & state) private
Apply the predictor.
Parameters
dt Dynamic time step.
ahist Acceleration history.
state Corrected state.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj().
replicate_primer() [1/3]
template<> er7_utils::SecondOrderODEIntegrator * jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::replicate_primer (const er7_utils::SecondOrderODEIntegrator * src) inline private
Definition at line 115 of file gauss_jackson_integrator_base_second.hh.
replicate_primer() [2/3]
template<> er7_utils::FirstOrderODEIntegrator * jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::replicate_primer (const er7_utils::FirstOrderODEIntegrator * src) inline private
Replicate the priming integrator.
Definition at line 117 of file gauss_jackson_integrator_base_first.hh.
replicate_primer() [3/3]
template<typename State , typename Primer > static Primer* jeod::GaussJacksonIntegratorBase< State, Primer >::replicate_primer (const Primer * src) static private
Create a replica of the provided primer.
Parameters
src Primer to be replicated.
Returns
Constructed primer.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase().
replicate_state() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::replicate_state (GaussJacksonOneState const & source, GaussJacksonOneState & target) inline private
Replicate state data.
Definition at line 370 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
replicate_state() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::replicate_state (GaussJacksonTwoState const & source, GaussJacksonTwoState & target) inline private
Replicate state data.
Definition at line 375 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
replicate_state() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::replicate_state (const State & source, State & target) private
Replicate state data.
Parameters
source State item to be copied.
target Replicated state item.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase().
rotate_acc_hist()
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::rotate_acc_hist () inline private
Rotate the acceleration history.
Definition at line 641 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist, jeod::GaussJacksonIntegratorBase< State, Primer >::order, and er7_utils::TwoDArray< T >::rotate_down().
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate().
save_comparison_data() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::save_comparison_data (const GaussJacksonTwoState & state, double * pos_hist_elem) inline private
Save comparison data.
Definition at line 169 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::second.
save_comparison_data() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::save_comparison_data (const GaussJacksonOneState & state, double * pos_hist_elem) inline private
Save comparison data.
Definition at line 170 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
save_comparison_data() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::save_comparison_data (const State & state, double * pos_hist_elem) private
Save comparison data.
Parameters
state State to be saved.
pos_hist_elem Element of the position history to be updated.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), and jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj().
save_epoch_data() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::save_epoch_data (const double * acc, const GaussJacksonTwoState & state) inline private
Save epoch data.
Definition at line 152 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
save_epoch_data() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::save_epoch_data (const double * acc, const GaussJacksonOneState & state) inline private
Save epoch data.
Definition at line 153 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
save_epoch_data() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::save_epoch_data (const double * acc, const State & state) private
Save epoch data.
Parameters
acc Acceleration to be saved.
state State to be saved.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle().
start_cycle()
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle (double dt, const double * acc, const State & state) inline private
Start an integration cycle.
Parameters
[in] dt Dynamic time step, in dynamic time seconds.
[in] acc Acceleration vector.
[in] state State vector(s).
Definition at line 526 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist, jeod::GaussJacksonStateMachine::BootstrapEdit, jeod::GaussJacksonIntegratorBase< State, Primer >::coeff, jeod::GaussJacksonCoeffs::corrector, jeod::GaussJacksonIntegratorBase< State, Primer >::downsample_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::fsm_state, jeod::GaussJacksonStateMachine::get_at_downsample(), jeod::GaussJacksonStateMachine::get_at_order_change(), jeod::GaussJacksonStateMachine::get_at_reinitialize(), jeod::GaussJacksonStateMachine::get_current_order(), jeod::GaussJacksonStateMachine::get_fsm_state(), jeod::GaussJacksonCoefficientsPair::gj_coefs, jeod::GaussJacksonIntegratorBase< State, Primer >::history_length, jeod::GaussJacksonIntegratorBase< State, Primer >::initialize_edit_integration_constants(), jeod::GaussJacksonIntegratorBase< State, Primer >::initialize_predictor_integration_constants(), jeod::GaussJacksonIntegratorBase< State, Primer >::order, jeod::GaussJacksonIntegratorBase< State, Primer >::position_corrector, jeod::GaussJacksonStateMachine::Reset, jeod::GaussJacksonCoefficientsPair::sa_coefs, jeod::GaussJacksonIntegratorBase< State, Primer >::save_epoch_data(), jeod::GaussJacksonIntegratorBase< State, Primer >::size, jeod::GaussJacksonIntegratorBase< State, Primer >::state_machine, and jeod::GaussJacksonIntegratorBase< State, Primer >::velocity_corrector.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate().
swap()
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::swap (GaussJacksonIntegratorBase< State, Primer > & other) inline protected
Non-throwing swap.
Parameters
other Item whose contents are to be swapped with this.
Definition at line 461 of file gauss_jackson_integrator_base.hh.
References jeod::GaussJacksonIntegratorBase< State, Primer >::absolute_tolerance, jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist, jeod::GaussJacksonIntegratorBase< State, Primer >::coeff, jeod::GaussJacksonIntegratorBase< State, Primer >::corrector_sum, jeod::GaussJacksonIntegratorBase< State, Primer >::delinv, jeod::GaussJacksonIntegratorBase< State, Primer >::fsm_state, jeod::GaussJacksonIntegratorBase< State, Primer >::history_length, jeod::GaussJacksonIntegratorBase< State, Primer >::init_state, jeod::GaussJacksonIntegratorBase< State, Primer >::initial_order, jeod::GaussJacksonIntegratorBase< State, Primer >::max_history_size, jeod::GaussJacksonIntegratorBase< State, Primer >::order, jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist, jeod::GaussJacksonIntegratorBase< State, Primer >::position_corrector, jeod::GaussJacksonIntegratorBase< State, Primer >::primer, jeod::GaussJacksonIntegratorBase< State, Primer >::relative_tolerance, jeod::GaussJacksonIntegratorBase< State, Primer >::size, jeod::GaussJacksonIntegratorBase< State, Primer >::state_machine, er7_utils::TwoDArray< T >::swap(), jeod::GaussJacksonIntegratorBase< State, Primer >::swap_state(), and jeod::GaussJacksonIntegratorBase< State, Primer >::velocity_corrector.
Referenced by jeod::GaussJacksonFirstOrderODEIntegrator::swap(), and jeod::GaussJacksonSimpleSecondOrderODEIntegrator::swap().
swap_state() [1/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::swap_state (GaussJacksonOneState & item, GaussJacksonOneState & other_item) inline private
Swap state data with another of the same.
Definition at line 355 of file gauss_jackson_integrator_base_first.hh.
References jeod::GaussJacksonOneState::first.
swap_state() [2/3]
template<> void jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::swap_state (GaussJacksonTwoState & item, GaussJacksonTwoState & other_item) inline private
Swap state data with another of the same.
Definition at line 360 of file gauss_jackson_integrator_base_second.hh.
References jeod::GaussJacksonTwoState::first, and jeod::GaussJacksonTwoState::second.
swap_state() [3/3]
template<typename State , typename Primer > void jeod::GaussJacksonIntegratorBase< State, Primer >::swap_state (State & item, State & other_item) private
Swap state data with another of the same.
Parameters
item State item.
other_item The other state item.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
test_for_convergence() [1/3]
template<> bool jeod::GaussJacksonIntegratorBase< GaussJacksonOneState, er7_utils::FirstOrderODEIntegrator >::test_for_convergence (const GaussJacksonOneState & state, double * hist_data) inline private
Test for convergence.
Definition at line 329 of file gauss_jackson_integrator_base_first.hh.
References ER7_UTILS_RESTRICT, and jeod::GaussJacksonOneState::first.
test_for_convergence() [2/3]
template<> bool jeod::GaussJacksonIntegratorBase< GaussJacksonTwoState, er7_utils::SecondOrderODEIntegrator >::test_for_convergence (const GaussJacksonTwoState & state, double * hist_data) inline private
Test for convergence.
Definition at line 336 of file gauss_jackson_integrator_base_second.hh.
References ER7_UTILS_RESTRICT, and jeod::GaussJacksonTwoState::second.
test_for_convergence() [3/3]
template<typename State , typename Primer > bool jeod::GaussJacksonIntegratorBase< State, Primer >::test_for_convergence (const State & state, double * hist_data) private
Test for convergence.
Parameters
state Item to be compared.
hist_data Previous state value.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point(), and jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj().
Field Documentation
absolute_tolerance
template<typename State , typename Primer > double jeod::GaussJacksonIntegratorBase< State, Primer >::absolute_tolerance
Number that indicates the allowable absolute difference for two states to be considered converged.
trick_units(–)
Definition at line 148 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
acc_hist
template<typename State , typename Primer > er7_utils::DoubleTwoDArray jeod::GaussJacksonIntegratorBase< State, Primer >::acc_hist
Acceleration history.
trick_units(–)
Definition at line 131 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), jeod::GaussJacksonIntegratorBase< State, Primer >::downsample_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::rotate_acc_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
coeff
template<typename State , typename Primer > const GaussJacksonCoeffs* jeod::GaussJacksonIntegratorBase< State, Primer >::coeff
The summed Adams and Gauss-Jackson coefficients, in ordinate form.
trick_units(–)
Definition at line 101 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
corrector_sum
template<typename State , typename Primer > State jeod::GaussJacksonIntegratorBase< State, Primer >::corrector_sum
Speed hack for the corrector.
trick_units(–)
Definition at line 126 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), jeod::GaussJacksonIntegratorBase< State, Primer >::swap(), and jeod::GaussJacksonIntegratorBase< State, Primer >::~GaussJacksonIntegratorBase().
delinv
template<typename State , typename Primer > State jeod::GaussJacksonIntegratorBase< State, Primer >::delinv
Inverse backward differences.
trick_units(–)
Definition at line 121 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::swap(), and jeod::GaussJacksonIntegratorBase< State, Primer >::~GaussJacksonIntegratorBase().
fsm_state
template<typename State , typename Primer > GaussJacksonStateMachine::FsmState jeod::GaussJacksonIntegratorBase< State, Primer >::fsm_state
Finite state machine state.
trick_units(–)
Definition at line 163 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), jeod::GaussJacksonIntegratorBase< State, Primer >::base_reset(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
history_length
template<typename State , typename Primer > unsigned int jeod::GaussJacksonIntegratorBase< State, Primer >::history_length
Current history length.
trick_units(–)
Definition at line 188 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), jeod::GaussJacksonIntegratorBase< State, Primer >::base_reset(), jeod::GaussJacksonIntegratorBase< State, Primer >::downsample_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
init_state
template<typename State , typename Primer > State jeod::GaussJacksonIntegratorBase< State, Primer >::init_state
The state at the time of the last reset.
trick_units(–)
Definition at line 116 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::swap(), and jeod::GaussJacksonIntegratorBase< State, Primer >::~GaussJacksonIntegratorBase().
initial_order
template<typename State , typename Primer > unsigned int jeod::GaussJacksonIntegratorBase< State, Primer >::initial_order
Initial order.
trick_units(–)
Definition at line 173 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_reset(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
max_history_size
template<typename State , typename Primer > unsigned int jeod::GaussJacksonIntegratorBase< State, Primer >::max_history_size
Maximum history size.
trick_units(–)
Definition at line 168 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
order
template<typename State , typename Primer > unsigned int jeod::GaussJacksonIntegratorBase< State, Primer >::order
Current order.
trick_units(–)
Definition at line 178 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), jeod::GaussJacksonIntegratorBase< State, Primer >::base_reset(), jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point(), jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), jeod::GaussJacksonIntegratorBase< State, Primer >::rotate_acc_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
pos_hist
template<typename State , typename Primer > er7_utils::DoubleTwoDArray jeod::GaussJacksonIntegratorBase< State, Primer >::pos_hist
Position history (or velocity history in case of a first order ODE).
trick_units(–)
Definition at line 136 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), jeod::GaussJacksonIntegratorBase< State, Primer >::downsample_hist(), jeod::GaussJacksonIntegratorBase< State, Primer >::edit_point(), jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
position_corrector
template<typename State , typename Primer > double jeod::GaussJacksonIntegratorBase< State, Primer >::position_corrector
Correction coefficient for the second integral (position).
trick_units(–)
Definition at line 158 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
primer
template<typename State , typename Primer > Primer* jeod::GaussJacksonIntegratorBase< State, Primer >::primer
The integrator used to prime the Gauss-Jackson integration process.
trick_units(–)
Definition at line 111 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::swap(), and jeod::GaussJacksonIntegratorBase< State, Primer >::~GaussJacksonIntegratorBase().
relative_tolerance
template<typename State , typename Primer > double jeod::GaussJacksonIntegratorBase< State, Primer >::relative_tolerance
Number that indicates the allowable relative difference for two states to be considered converged.
trick_units(–)
Definition at line 142 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
size
template<typename State , typename Primer > unsigned int jeod::GaussJacksonIntegratorBase< State, Primer >::size
State size.
trick_units(–)
Definition at line 183 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::base_integrate(), jeod::GaussJacksonIntegratorBase< State, Primer >::GaussJacksonIntegratorBase(), jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
state_machine
template<typename State , typename Primer > const GaussJacksonStateMachine* jeod::GaussJacksonIntegratorBase< State, Primer >::state_machine
The Gauss-Jackson state machine.
trick_units(–)
Definition at line 106 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
velocity_corrector
template<typename State , typename Primer > double jeod::GaussJacksonIntegratorBase< State, Primer >::velocity_corrector
Correction coefficient for the first integral (velocity).
trick_units(–)
Definition at line 153 of file gauss_jackson_integrator_base.hh.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and jeod::GaussJacksonIntegratorBase< State, Primer >::swap().
The documentation for this class was generated from the following file:
gauss_jackson_integrator_base.hh