JEOD: jeod::Numerical Class Reference
jeod::Numerical Class Reference
Provides miscellaneous numerical functions.
#include <numerical.hh>
Static Public Member Functions
static double fabs (double x)
Absolute value.
static double square (double value)
Compute the square of a number, protecting against undeflow.
static double square_incr (double value, double &sum)
Add number squared to accumulator, protecting against undeflow.
static bool compare_exact (double x, double y)
Compare two doubles for exact equality.
Detailed Description
Provides miscellaneous numerical functions.
Definition at line 66 of file numerical.hh.
Member Function Documentation
compare_exact()
bool jeod::Numerical::compare_exact (double x, double y) inline static
Compare two doubles for exact equality.
Returns
whether inputs are exactly the same
Parameters
[in] x Value1
[in] y Value2
Definition at line 123 of file numerical_inline.hh.
Referenced by jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::LineContactFacet::calculate_contact_point(), jeod::LsodeFirstOrderODEIntegrator::calculate_epsilon(), jeod::TimeStandard::calendar_update(), jeod::RefFrame::compute_position_from(), jeod::Quaternion::compute_slerp(), jeod::ContactFacet::create_vehicle_point(), jeod::MassPointState::decr_left(), jeod::RefFrameState::decr_left(), jeod::MassPointState::decr_right(), jeod::RefFrameState::decr_right(), jeod::SpiceEphemeris::ephem_update(), jeod::De4xxEphemeris::ephem_update(), jeod::MassPointState::incr_left(), jeod::RefFrameState::incr_left(), jeod::MassPointState::incr_right(), jeod::RefFrameState::incr_right(), jeod::TimeStandard::initialize_initializer_time(), jeod::LsodeIntegrationControls::integrate(), jeod::GaussJacksonIntegrationControls::integrate(), jeod::GaussJacksonIntegrationControls::integrate_edit(), jeod::GaussJacksonIntegrationControls::integrate_gj(), jeod::LsodeFirstOrderODEIntegrator::integrator_core(), jeod::LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change(), jeod::De4xxFile::interpolate(), jeod::LsodeFirstOrderODEIntegrator::linear_chord_iteration(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2(), jeod::MassPointState::negate(), jeod::RefFrameState::negate(), jeod::TimeStandard::seconds_of_year(), jeod::set_default_config_values(), jeod::PendulumConstraintComponent::set_pendulum_length(), jeod::TimeManager::update(), jeod::RNPJ2000::update_axial_rotation(), jeod::RNPMars::update_axial_rotation(), jeod::TimeDyn::update_offset(), jeod::RNPJ2000::update_rnp(), jeod::RNPMars::update_rnp(), and jeod::TimeManager::update_time().
fabs()
double jeod::Numerical::fabs (double x) inline static
Absolute value.
Returns
Absolute value of x
Parameters
[in] x x
Definition at line 73 of file numerical_inline.hh.
Referenced by jeod::LineContactFacet::calculate_contact_point(), square(), square_incr(), and jeod::Vector3::zero_small().
square()
double jeod::Numerical::square (double value) inline static
Compute the square of a number, protecting against undeflow.
Returns
value^2 or zero if too small
Parameters
[in] value Value
Definition at line 90 of file numerical_inline.hh.
References fabs(), and jeod::SQRT_DBL_MIN.
Referenced by jeod::LineContactFacet::calculate_contact_point(), and jeod::Quaternion::normalize_integ().
square_incr()
double jeod::Numerical::square_incr (double value, double & sum) inline static
Add number squared to accumulator, protecting against undeflow.
Returns
Accumulated value
Parameters
[in] value Value
[in,out] sum Accumulator
Definition at line 108 of file numerical_inline.hh.
References fabs(), and jeod::SQRT_DBL_MIN.
The documentation for this class was generated from the following files:
numerical.hh
numerical_inline.hh