JEOD: jeod::SpiceEphemOrientation Class Reference
jeod::SpiceEphemOrientation Class Reference
A SpiceEphemOrientation minimally extends EphemerisOrientation to include the JEOD and SPICE names and an update method for the target ephemeris reference frame.
#include <spice_ephem_orient.hh>
Public Member Functions
SpiceEphemOrientation ()
SpiceEphemOrientation default constructor.
~SpiceEphemOrientation () override=default
SpiceEphemOrientation (const SpiceEphemOrientation &)=delete
SpiceEphemOrientation & operator= (const SpiceEphemOrientation &)=delete
void update (double time_tdb, double time_dyn)
Update the rotational state of the target frame.
void validate (double time_tdb)
Confirm that the target frame exists in the loaded SPICE kernels.
void get_spice_transformation (double time_tdb, double trans6x6[6][6])
Populate the SPICE 6 x 6 matrix via sxform_c().
void set_spice_frame_name (const std::string &new_name)
Setter for the name of the SPICE frame.
Public Member Functions inherited from jeod::EphemerisOrientation
EphemerisOrientation ()=default
~EphemerisOrientation () override=default
EphemerisOrientation (const EphemerisOrientation &)=delete
EphemerisOrientation & operator= (const EphemerisOrientation &)=delete
TargetAspect updates_what () const override
Specify the aspect of the target frame updated by the object.
void enable () override
Enable a EphemerisItem object.
void note_frame_status_change (RefFrame *frame) override
Null implementation.
std::string default_suffix () const override
Return the default suffix for this item class, i.e., "pfix".
void disconnect_from_tree () override
Disconnect the item from the tree; this is a no-op for an EphemerisOrientation.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()=default
~EphemerisItem () override=default
EphemerisItem (const EphemerisItem &)=delete
EphemerisItem & operator= (const EphemerisItem &)=delete
virtual void set_name (const std::string &new_name)
Name an ephemeris item.
virtual void set_name (const std::string &pname, const std::string &fname)
Name an ephemeris item.
std::string get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp () const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item () const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const std::string &new_value, const std::string &old_value, const std::string &variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
Private Attributes
std::string spice_frame_name
SPICE name of the target reference frame.
Friends
class InputProcessor
void init_attrjeod__SpiceEphemOrientation ()
Additional Inherited Members
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (const std::string &new_name)
Name an ephemeris item.
Protected Attributes inherited from jeod::EphemerisOrientation
bool subscribed_to_inertial {}
A subscription to the planet's inertial frame is issued whenever the planet's planet-fixed frame is active to ensure that the the planet-fixed frame is a part of the ref frame tree.
Protected Attributes inherited from jeod::EphemerisItem
std::string name
The name of the item.
EphemerisInterface * owner {}
The ephemeris model that owns this object.
BaseEphemeridesManager * manager {}
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame {}
The reference frame whose non-constant state is set by this object.
EphemerisItem * head {}
The first ephemeris item with the same name as this item.
EphemerisItem * next {}
The next ephemeris item with the same name as this item.
double update_time {}
Time of last update, dynamic time seconds.
bool enabled {}
Is the item enabled?
bool active {}
Is the item active?
Detailed Description
A SpiceEphemOrientation minimally extends EphemerisOrientation to include the JEOD and SPICE names and an update method for the target ephemeris reference frame.
Definition at line 83 of file spice_ephem_orient.hh.
Constructor & Destructor Documentation
SpiceEphemOrientation() [1/2]
jeod::SpiceEphemOrientation::SpiceEphemOrientation ()
SpiceEphemOrientation default constructor.
Definition at line 44 of file spice_ephem_orient.cc.
References JEOD_REGISTER_CLASS.
~SpiceEphemOrientation()
jeod::SpiceEphemOrientation::~SpiceEphemOrientation () override default
SpiceEphemOrientation() [2/2]
jeod::SpiceEphemOrientation::SpiceEphemOrientation (const SpiceEphemOrientation &) delete
Member Function Documentation
get_spice_transformation()
void jeod::SpiceEphemOrientation::get_spice_transformation (double time_tdb, double trans6x6[6][6])
Populate the SPICE 6 x 6 matrix via sxform_c().
Parameters
[in] time_tdb Ephem time (TDB)
[out] trans6x6 Spice matrix
Definition at line 115 of file spice_ephem_orient.cc.
References jeod::MessageHandler::fail(), jeod::EphemeridesMessages::item_not_in_file, and spice_frame_name.
Referenced by update(), and validate().
operator=()
SpiceEphemOrientation& jeod::SpiceEphemOrientation::operator= (const SpiceEphemOrientation &) delete
set_spice_frame_name()
void jeod::SpiceEphemOrientation::set_spice_frame_name (const std::string & new_name) inline
Setter for the name of the SPICE frame.
Parameters
new_name Name of the SPICE frame
Definition at line 105 of file spice_ephem_orient.hh.
References spice_frame_name.
Referenced by jeod::SpiceEphemeris::create_new_ephem_orientation().
update()
void jeod::SpiceEphemOrientation::update (double time_tdb, double time_dyn)
Update the rotational state of the target frame.
Parameters
[in] time_tdb Ephemeris time (TDB)
Units: s
[in] time_dyn dyn time for timestamp
Units: s
Definition at line 54 of file spice_ephem_orient.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_quaternion(), get_spice_transformation(), jeod::Matrix3x3::product_right_transpose(), jeod::RefFrameState::rot, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::EphemerisItem::target_frame, and jeod::EphemerisItem::update_time.
validate()
void jeod::SpiceEphemOrientation::validate (double time_tdb)
Confirm that the target frame exists in the loaded SPICE kernels.
Parameters
[in] time_tdb Ephemeris time (TDB)
Definition at line 99 of file spice_ephem_orient.cc.
References get_spice_transformation().
Referenced by jeod::SpiceEphemeris::create_new_ephem_orientation().
Friends And Related Function Documentation
init_attrjeod__SpiceEphemOrientation
void init_attrjeod__SpiceEphemOrientation () friend
InputProcessor
friend class InputProcessor friend
Definition at line 85 of file spice_ephem_orient.hh.
Field Documentation
spice_frame_name
std::string jeod::SpiceEphemOrientation::spice_frame_name private
SPICE name of the target reference frame.
trick_units(–)
Definition at line 115 of file spice_ephem_orient.hh.
Referenced by get_spice_transformation(), and set_spice_frame_name().
The documentation for this class was generated from the following files:
spice_ephem_orient.hh
spice_ephem_orient.cc