JEOD: jeod::BodyReattach Class Reference
jeod::BodyReattach Class Reference
Alters the nature of an existing attachment.
#include <body_reattach.hh>
Public Member Functions
BodyReattach ()
Construct a MassBodyReattach.
~BodyReattach () override=default
BodyReattach (const BodyReattach &)=delete
BodyReattach & operator= (const BodyReattach &)=delete
void apply (DynManager &dyn_manager) override
Initialize the core mass properties of the subject MassBody.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
virtual void initialize (DynManager &dyn_manager)
Begin initialization of a BodyAction.
virtual bool is_ready ()
In general, determine if the initializer is ready to be applied.
Data Fields
double offset_pstr_cstr_pstr [3] {}
Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
Orientation pstr_cstr
Orientation of child's structural frame with respect to that of the new parent; sense is parent-to-child.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Friends
class InputProcessor
void init_attrjeod__BodyReattach ()
Additional Inherited Members
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Alters the nature of an existing attachment.
When the action is ready, the attachment is altered such that:
The displacement between the origins of the parent and subject bodies' structural frames is that given by the offset_pstr_cstr_pstr data member.
The orientation between these two reference frames's axes is that given by the pstr_cstr data member. Note that no parent body is specified. Reattachment does not change the attachment tree. It instead alters the physical relationships between a pair of objects that are already attached.
Definition at line 90 of file body_reattach.hh.
Constructor & Destructor Documentation
BodyReattach() [1/2]
jeod::BodyReattach::BodyReattach ()
Construct a MassBodyReattach.
Definition at line 48 of file body_reattach.cc.
References jeod::BodyAction::active.
~BodyReattach()
jeod::BodyReattach::~BodyReattach () override default
BodyReattach() [2/2]
jeod::BodyReattach::BodyReattach (const BodyReattach &) delete
Member Function Documentation
apply()
void jeod::BodyReattach::apply (DynManager & dyn_manager) override virtual
Initialize the core mass properties of the subject MassBody.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAction.
Definition at line 57 of file body_reattach.cc.
References jeod::BodyAction::action_identifier, jeod::BodyAction::apply(), jeod::NamedItem::c_str(), jeod::Orientation::compute_transform(), jeod::MessageHandler::debug(), jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::BodyActionMessages::fatal_error, jeod::BodyActionMessages::invalid_object, jeod::BodyAction::mass_subject, jeod::MassBody::name, offset_pstr_cstr_pstr, pstr_cstr, jeod::MassBody::reattach(), jeod::BodyAction::terminate_on_error, jeod::BodyActionMessages::trace, and jeod::Orientation::trans.
operator=()
BodyReattach& jeod::BodyReattach::operator= (const BodyReattach &) delete
Friends And Related Function Documentation
init_attrjeod__BodyReattach
void init_attrjeod__BodyReattach () friend
InputProcessor
friend class InputProcessor friend
Definition at line 92 of file body_reattach.hh.
Field Documentation
offset_pstr_cstr_pstr
double jeod::BodyReattach::offset_pstr_cstr_pstr[3] {}
Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
trick_units(m)
Definition at line 100 of file body_reattach.hh.
Referenced by apply().
pstr_cstr
Orientation jeod::BodyReattach::pstr_cstr
Orientation of child's structural frame with respect to that of the new parent; sense is parent-to-child.
trick_units(–)
Definition at line 106 of file body_reattach.hh.
Referenced by apply().
The documentation for this class was generated from the following files:
body_reattach.hh
body_reattach.cc