JEOD: jeod::JeodObjectContainer< ContainerType, ElemType > Class Template Reference
jeod::JeodObjectContainer< ContainerType, ElemType > Class Template Reference
A JeodObjectContainer is a JeodContainer that contains objects of type ElemType.
#include <object_container.hh>
Public Member Functions
JeodObjectContainer (void)
Construct a JeodObjectContainer.
JeodObjectContainer (const JeodObjectContainer &source)
Copy-construct a JeodObjectContainer.
JeodObjectContainer (const typename ContainerType::stl_container_type &source)
Copy-construct a JeodObjectContainer.
JeodObjectContainer & operator= (const JeodObjectContainer &source)
Copy from a JeodObjectContainer.
JeodObjectContainer & operator= (const typename ContainerType::stl_container_type &source)
Copy from an STL container.
virtual ~JeodObjectContainer (void)
Destruct a JeodObjectContainer.
void pre_checkpoint (void) override
Prepare to checkpoint a JeodObjectContainer.
void post_checkpoint (void) override
Cleanup after performing a checkpoint.
void post_restart (void) override
Cleanup after performing a restart.
void start_checkpoint (void) override
Prepare to checkpoint the object in question.
void advance_checkpoint (void) override
Advance to the next item to be checkpointed.
const std::string get_item_value (void) override
Return the value of the item to be written to the checkpoint file.
void perform_insert_action (const std::string &value) override
Interpret the provided value and add it to the list.
const std::string get_final_value (void) override
Return the value of the item to be written to the checkpoint file.
void perform_cleanup_action (const std::string &value) override
Cleanup detritus created during the restore process.
Public Member Functions inherited from jeod::JeodContainer< ContainerType, ElemType >
JeodContainer (void)
Default constructor.
JeodContainer (const this_container_type &source)
Copy constructor.
JeodContainer (const stl_container_type &source)
Copy constructor.
JeodContainer & operator= (const this_container_type &source)
Assignment operator.
JeodContainer & operator= (const stl_container_type &source)
Assignment operator.
~JeodContainer (void) override
Destructor.
void swap_contents (this_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
void swap_contents (stl_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
bool is_checkpoint_finished (void) override
Indicate whether the checkpoint dump of this object is finished.
const std::string get_init_name (void) override
Names the action to be performed prior to performing any of the restore actions.
const std::string get_item_name (void) override
Return the name of the action to be printed along with the current value.
const std::string get_final_name (void) override
Names the action to be performed after to performing any of the restore actions.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
Protected Attributes
size_t index
Index number into the copy; used during checkpoint process.
ElemType * copy
C-style array copy of the object; used during checkpoint process.
Protected Attributes inherited from jeod::JeodContainer< ContainerType, ElemType >
ContainerType::iterator checkpoint_iter
Iterator for walking through the container during checkpoint.
const JeodMemoryTypeDescriptor * elem_type_descriptor
Memory model descriptor of the type of data stored in the container.
Friends
class InputProcessor
void init_attrjeod__JeodObjectContainer ()
Additional Inherited Members
Public Types inherited from jeod::JeodContainer< ContainerType, ElemType >
typedef JeodContainer< ContainerType, ElemType > this_container_type
This particular JeodContainer type.
typedef ContainerType::stl_container_type stl_container_type
Import the ContainerType's container type.
Detailed Description
template<typename ContainerType, typename ElemType>
class jeod::JeodObjectContainer< ContainerType, ElemType >
A JeodObjectContainer is a JeodContainer that contains objects of type ElemType.
Definition at line 84 of file object_container.hh.
Constructor & Destructor Documentation
JeodObjectContainer() [1/3]
template<typename ContainerType , typename ElemType > jeod::JeodObjectContainer< ContainerType, ElemType >::JeodObjectContainer (void) inline
Construct a JeodObjectContainer.
Definition at line 92 of file object_container.hh.
JeodObjectContainer() [2/3]
template<typename ContainerType , typename ElemType > jeod::JeodObjectContainer< ContainerType, ElemType >::JeodObjectContainer (const JeodObjectContainer< ContainerType, ElemType > & source) inline
Copy-construct a JeodObjectContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Object container to be copied.
Definition at line 104 of file object_container.hh.
JeodObjectContainer() [3/3]
template<typename ContainerType , typename ElemType > jeod::JeodObjectContainer< ContainerType, ElemType >::JeodObjectContainer (const typename ContainerType::stl_container_type & source) inline explicit
Copy-construct a JeodObjectContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Object container to be copied.
Definition at line 117 of file object_container.hh.
~JeodObjectContainer()
template<typename ContainerType , typename ElemType > virtual jeod::JeodObjectContainer< ContainerType, ElemType >::~JeodObjectContainer (void) inline virtual
Destruct a JeodObjectContainer.
Definition at line 154 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::post_checkpoint().
Member Function Documentation
advance_checkpoint()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::advance_checkpoint (void) inline override virtual
Advance to the next item to be checkpointed.
The local checkpoint index is advanced to keep in sync with the parent class' checkpoint iterator.
Reimplemented from jeod::JeodContainer< ContainerType, ElemType >.
Definition at line 214 of file object_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::advance_checkpoint(), and jeod::JeodObjectContainer< ContainerType, ElemType >::index.
get_final_value()
template<typename ContainerType , typename ElemType > const std::string jeod::JeodObjectContainer< ContainerType, ElemType >::get_final_value (void) inline override virtual
Return the value of the item to be written to the checkpoint file.
For a JeodObjectContainer, the value is the name of the corresponding object in the C-style copy of the object's contents.
Reimplemented from jeod::JeodCheckpointable.
Definition at line 253 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::copy, jeod::JeodContainer< ContainerType, ElemType >::elem_type_descriptor, and jeod::JeodSimulationInterface::get_name_at_address().
get_item_value()
template<typename ContainerType , typename ElemType > const std::string jeod::JeodObjectContainer< ContainerType, ElemType >::get_item_value (void) inline override virtual
Return the value of the item to be written to the checkpoint file.
For a JeodObjectContainer, the value is the name of the corresponding object in the C-style copy of the object's contents.
Implements jeod::JeodCheckpointable.
Definition at line 225 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::copy, jeod::JeodContainer< ContainerType, ElemType >::elem_type_descriptor, jeod::JeodSimulationInterface::get_name_at_address(), and jeod::JeodObjectContainer< ContainerType, ElemType >::index.
operator=() [1/2]
template<typename ContainerType , typename ElemType > JeodObjectContainer& jeod::JeodObjectContainer< ContainerType, ElemType >::operator= (const JeodObjectContainer< ContainerType, ElemType > & source) inline
Copy from a JeodObjectContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Object container to be copied.
Definition at line 132 of file object_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::operator=().
operator=() [2/2]
template<typename ContainerType , typename ElemType > JeodObjectContainer& jeod::JeodObjectContainer< ContainerType, ElemType >::operator= (const typename ContainerType::stl_container_type & source) inline
Copy from an STL container.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Object container to be copied.
Definition at line 145 of file object_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::operator=().
perform_cleanup_action()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::perform_cleanup_action (const std::string & value) inline override virtual
Cleanup detritus created during the restore process.
Here we delete the temporary array created during checkpoint.
Parameters
value String name of cleanup target.
Reimplemented from jeod::JeodContainer< ContainerType, ElemType >.
Definition at line 265 of file object_container.hh.
References jeod::JeodSimulationInterface::get_address_at_name(), and JEOD_DELETE_ARRAY.
perform_insert_action()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::perform_insert_action (const std::string & value) inline override virtual
Interpret the provided value and add it to the list.
For a JeodObjectContainer, the value should name an element of the C-style copy of the object's contents.
Implements jeod::JeodContainer< ContainerType, ElemType >.
Definition at line 237 of file object_container.hh.
References jeod::JeodSimulationInterface::get_address_at_name().
post_checkpoint()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::post_checkpoint (void) inline override virtual
Cleanup after performing a checkpoint.
Reimplemented from jeod::JeodCheckpointable.
Definition at line 182 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::copy, and JEOD_DELETE_ARRAY.
Referenced by jeod::JeodObjectContainer< ContainerType, ElemType >::post_restart(), and jeod::JeodObjectContainer< ContainerType, ElemType >::~JeodObjectContainer().
post_restart()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::post_restart (void) inline override virtual
Cleanup after performing a restart.
Reimplemented from jeod::JeodCheckpointable.
Definition at line 193 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::post_checkpoint().
pre_checkpoint()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::pre_checkpoint (void) inline override virtual
Prepare to checkpoint a JeodObjectContainer.
The contents of an object container is checkpointed by allocating a C-style array of the same size as the container and populating the array with copies of the container contents. The existing checkpoint capabilities will checkpoint this array, so all that remains to be done is to associate the array elements with the container.
Reimplemented from jeod::JeodCheckpointable.
Definition at line 165 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::copy, and JEOD_ALLOC_CLASS_ARRAY.
start_checkpoint()
template<typename ContainerType , typename ElemType > void jeod::JeodObjectContainer< ContainerType, ElemType >::start_checkpoint (void) inline override virtual
Prepare to checkpoint the object in question.
The local checkpoint index is initialized to zero to reflect that the parent class' checkpoint iterator starts at the zeroth element.
Reimplemented from jeod::JeodContainer< ContainerType, ElemType >.
Definition at line 203 of file object_container.hh.
References jeod::JeodObjectContainer< ContainerType, ElemType >::index, and jeod::JeodContainer< ContainerType, ElemType >::start_checkpoint().
Friends And Related Function Documentation
init_attrjeod__JeodObjectContainer
template<typename ContainerType , typename ElemType > void init_attrjeod__JeodObjectContainer () friend
InputProcessor
template<typename ContainerType , typename ElemType > friend class InputProcessor friend
Definition at line 86 of file object_container.hh.
Field Documentation
copy
template<typename ContainerType , typename ElemType > ElemType* jeod::JeodObjectContainer< ContainerType, ElemType >::copy protected
C-style array copy of the object; used during checkpoint process.
trick_io(**)
Definition at line 286 of file object_container.hh.
Referenced by jeod::JeodObjectContainer< ContainerType, ElemType >::get_final_value(), jeod::JeodObjectContainer< ContainerType, ElemType >::get_item_value(), jeod::JeodObjectContainer< ContainerType, ElemType >::post_checkpoint(), and jeod::JeodObjectContainer< ContainerType, ElemType >::pre_checkpoint().
index
template<typename ContainerType , typename ElemType > size_t jeod::JeodObjectContainer< ContainerType, ElemType >::index protected
Index number into the copy; used during checkpoint process.
trick_io(**)
Definition at line 281 of file object_container.hh.
Referenced by jeod::JeodObjectContainer< ContainerType, ElemType >::advance_checkpoint(), jeod::JeodObjectContainer< ContainerType, ElemType >::get_item_value(), and jeod::JeodObjectContainer< ContainerType, ElemType >::start_checkpoint().
The documentation for this class was generated from the following file:
object_container.hh