JEOD: jeod::BaseEphemeridesManager Class Reference
jeod::BaseEphemeridesManager Class Reference abstract
The EphemManager class augments the RefFrameManager with ephemeris-related items.
#include <base_ephem_manager.hh>
Public Member Functions
~BaseEphemeridesManager () override=default
Destructor.
virtual void ephem_note_tree_status_change ()=0
Denote that the tree needs to be rebuilt.
virtual void add_planet (BasePlanet &planet)=0
Add a planet to the list of such.
virtual void add_planet (Planet &planet)=0
Add a planet to the list of such.
virtual BasePlanet * find_base_planet (const std::string &name) const =0
Find a planet.
virtual Planet * find_planet (const std::string &name) const =0
Find a planet.
virtual unsigned int get_num_planets () const =0
Return number of registered planets.
virtual void add_ephemeris (EphemerisInterface &ephem_if)=0
Add an ephemeris model to the list of such.
virtual void clear_added_ephemerides ()=0
Deactivate all registered ephemeris models.
virtual void disable_add_ephemeris ()=0
Disable registration of new ephemeris models.
virtual void add_ephem_item (EphemerisItem &ephem_item)=0
Add an ephemeris item to the list of such.
virtual EphemerisItem * find_ephem_item (const std::string &name) const =0
Find an ephemeris item.
virtual EphemerisOrientation * find_ephem_angle (const std::string &name) const =0
Find an ephemeris orientation.
virtual EphemerisPoint * find_ephem_point (const std::string &name) const =0
Find an ephemeris point.
virtual void add_integ_frame (EphemerisRefFrame &ref_frame)=0
Add an integration frame to the list of such.
virtual EphemerisRefFrame * find_integ_frame (const std::string &name) const =0
Find an integration frame.
virtual bool is_integ_frame (const RefFrame &ref_frame) const =0
Check whether a reference frame is an integration frame.
virtual unsigned int find_integ_frame_index (const EphemerisRefFrame &ref_frame) const =0
Find a reference frame's index in the list of integration frames.
virtual const std::vector< EphemerisRefFrame * > & get_integ_frames () const =0
Get the vector of integration frames.
Public Member Functions inherited from jeod::BaseRefFrameManager
virtual ~BaseRefFrameManager ()=default
Destructor.
virtual void add_ref_frame (RefFrame &ref_frame)=0
Add a reference frame to the list of such.
virtual void remove_ref_frame (RefFrame &ref_frame)=0
Remove a reference frame from the list of such.
virtual RefFrame * find_ref_frame (const std::string &name) const =0
Find a reference frame.
virtual RefFrame * find_ref_frame (const std::string &prefix, const std::string &suffix) const =0
Find a reference frame.
virtual void check_ref_frame_ownership () const =0
Check whether each reference frame has an owner.
virtual void reset_tree_root_node ()=0
Reset the root node in anticipation of rebuilding the entire tree.
virtual void add_frame_to_tree (RefFrame &ref_frame, RefFrame *parent)=0
Add a reference frame to the reference frame tree.
virtual void subscribe_to_frame (const std::string &frame_name)=0
Add a subscription to a reference frame.
virtual void subscribe_to_frame (RefFrame &frame)=0
Add a subscription to a reference frame.
virtual void unsubscribe_to_frame (const std::string &frame_name)=0
Remove a subscription from a reference frame.
virtual void unsubscribe_to_frame (RefFrame &frame)=0
Remove a subscription from a reference frame.
virtual bool frame_is_subscribed (const std::string &frame_name)=0
Check whether a reference frame has subscriptions.
virtual bool frame_is_subscribed (RefFrame &frame)=0
Check whether a reference frame has subscriptions.
Friends
class InputProcessor
void init_attrjeod__BaseEphemeridesManager ()
Detailed Description
The EphemManager class augments the RefFrameManager with ephemeris-related items.
This class defines the external interfaces to that class.
Definition at line 88 of file base_ephem_manager.hh.
Constructor & Destructor Documentation
~BaseEphemeridesManager()
jeod::BaseEphemeridesManager::~BaseEphemeridesManager () override default
Destructor.
Member Function Documentation
add_ephem_item()
virtual void jeod::BaseEphemeridesManager::add_ephem_item (EphemerisItem & ephem_item) pure virtual
Add an ephemeris item to the list of such.
Parameters
ephem_item Item to be added.
Implemented in jeod::EphemeridesManager.
add_ephemeris()
virtual void jeod::BaseEphemeridesManager::add_ephemeris (EphemerisInterface & ephem_if) pure virtual
Add an ephemeris model to the list of such.
Parameters
ephem_if Ephemeris model to be added.
Implemented in jeod::EphemeridesManager.
add_integ_frame()
virtual void jeod::BaseEphemeridesManager::add_integ_frame (EphemerisRefFrame & ref_frame) pure virtual
Add an integration frame to the list of such.
Parameters
ref_frame Frame to be added.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::BasePlanet::register_planet().
add_planet() [1/2]
virtual void jeod::BaseEphemeridesManager::add_planet (BasePlanet & planet) pure virtual
Add a planet to the list of such.
Parameters
planet Planet to be added.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::BasePlanet::register_planet().
add_planet() [2/2]
virtual void jeod::BaseEphemeridesManager::add_planet (Planet & planet) pure virtual
Add a planet to the list of such.
Parameters
planet Planet to be added.
Implemented in jeod::EphemeridesManager.
clear_added_ephemerides()
virtual void jeod::BaseEphemeridesManager::clear_added_ephemerides () pure virtual
Deactivate all registered ephemeris models.
Implemented in jeod::EphemeridesManager.
disable_add_ephemeris()
virtual void jeod::BaseEphemeridesManager::disable_add_ephemeris () pure virtual
Disable registration of new ephemeris models.
Implemented in jeod::EphemeridesManager.
ephem_note_tree_status_change()
virtual void jeod::BaseEphemeridesManager::ephem_note_tree_status_change () pure virtual
Denote that the tree needs to be rebuilt.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::EphemerisItem::disable(), jeod::EphemerisItem::enable(), and jeod::EphemerisRefFrame::set_active_status().
find_base_planet()
virtual BasePlanet* jeod::BaseEphemeridesManager::find_base_planet (const std::string & name) const pure virtual
Find a planet.
Parameters
name Planet name.
Returns
Pointer to found planet.
Implemented in jeod::EphemeridesManager.
find_ephem_angle()
virtual EphemerisOrientation* jeod::BaseEphemeridesManager::find_ephem_angle (const std::string & name) const pure virtual
Find an ephemeris orientation.
Parameters
name Item to be found.
Returns
Found item.
Implemented in jeod::EphemeridesManager.
find_ephem_item()
virtual EphemerisItem* jeod::BaseEphemeridesManager::find_ephem_item (const std::string & name) const pure virtual
Find an ephemeris item.
Parameters
name Item to be found.
Returns
Found item.
Implemented in jeod::EphemeridesManager.
find_ephem_point()
virtual EphemerisPoint* jeod::BaseEphemeridesManager::find_ephem_point (const std::string & name) const pure virtual
Find an ephemeris point.
Parameters
name Item to be found.
Returns
Found item.
Implemented in jeod::EphemeridesManager.
find_integ_frame()
virtual EphemerisRefFrame* jeod::BaseEphemeridesManager::find_integ_frame (const std::string & name) const pure virtual
Find an integration frame.
Parameters
name Frame to be found.
Returns
Found frame.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::DynBody::set_integ_frame(), and jeod::DynBody::switch_integration_frames().
find_integ_frame_index()
virtual unsigned int jeod::BaseEphemeridesManager::find_integ_frame_index (const EphemerisRefFrame & ref_frame) const pure virtual
Find a reference frame's index in the list of integration frames.
Parameters
ref_frame Frame to be checked.
Returns
Frame index.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::GravityInteraction::set_integ_frame().
find_planet()
virtual Planet* jeod::BaseEphemeridesManager::find_planet (const std::string & name) const pure virtual
Find a planet.
Parameters
name Planet name.
Returns
Pointer to found planet.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::SphericalHarmonicsTidalEffects::initialize().
get_integ_frames()
virtual const std::vector<EphemerisRefFrame *>& jeod::BaseEphemeridesManager::get_integ_frames () const pure virtual
Get the vector of integration frames.
Returns
Vector of reference frame pointers.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::GravityManager::initialize_state().
get_num_planets()
virtual unsigned int jeod::BaseEphemeridesManager::get_num_planets () const pure virtual
Return number of registered planets.
Returns
Number of planets.
Implemented in jeod::EphemeridesManager.
is_integ_frame()
virtual bool jeod::BaseEphemeridesManager::is_integ_frame (const RefFrame & ref_frame) const pure virtual
Check whether a reference frame is an integration frame.
Parameters
ref_frame Frame to be checked.
Returns
True if ref_frame is an integration frame, false otherwise.
Implemented in jeod::EphemeridesManager.
Referenced by jeod::EphemerisItem::set_target_frame(), and jeod::DynBody::switch_integration_frames().
Friends And Related Function Documentation
init_attrjeod__BaseEphemeridesManager
void init_attrjeod__BaseEphemeridesManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file base_ephem_manager.hh.
The documentation for this class was generated from the following file:
base_ephem_manager.hh