JEOD: jeod::SpiceEphemeris Class Reference
jeod::SpiceEphemeris Class Reference
The S_define-level class that provides planetary ephemerides.
#include <spice_ephem.hh>
Public Member Functions
SpiceEphemeris ()
SpiceEphemeris default constructor.
~SpiceEphemeris () override
SpiceEphemeris destructor.
SpiceEphemeris (const SpiceEphemeris &)=delete
SpiceEphemeris & operator= (const SpiceEphemeris &)=delete
void initialize_model (const TimeManager &time_manager, EphemeridesManager &ephem_manager)
Initialize the SpiceEphemeris model.
void activate () override
Nominally, activate the object.
void deactivate () override
Deactivate the SpiceEphemeris object.
double timestamp () const override
Return time of last update.
std::string get_name () const override
Return model name.
void ephem_initialize (EphemeridesManager &ephem_manager) override
Complete the initialization process.
void ephem_activate (EphemeridesManager &ephem_manager) override
Mark appropriate items in the model as active.
void ephem_build_tree (EphemeridesManager &ephem_manager) override
Construct the ephemeris model portions of the reference frame tree.
void ephem_update () override
Update ephemerides for subscribed items.
void simple_restore () override
Set the SPICE model for a restart.
void add_planet_name (std::string planet_name)
void add_orientation (std::string object_name)
SpiceEphemPoint * find_spice_id (int id_to_find)
Find a SPICE ID in the loaded list of SPICE objects.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface () override=default
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()=default
virtual ~ActivateInterface ()=default
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Public Member Functions inherited from jeod::SimpleCheckpointable
SimpleCheckpointable ()=default
Construct a SimpleCheckpointable object.
~SimpleCheckpointable () override=default
Destruct a SimpleCheckpointable object.
const std::string get_init_name () override
Return the name of the initial restart action, in this case "restore".
const std::string get_item_name () override
Return the name of the current restart action, in this case "".
const std::string get_item_value () override
Return the value of the current restart action, in this case "".
void start_checkpoint () override
In general, start the checkpoint process.
void advance_checkpoint () override
In general, advance to the next checkpoint item; in this case, do nothing.
bool is_checkpoint_finished () override
In general, indicate when checkpointing is complete.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
In general, respond to the actions recorded in the checkpoint file.
SimpleCheckpointable (const SimpleCheckpointable &)=delete
SimpleCheckpointable & operator= (const SimpleCheckpointable &)=delete
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()=default
virtual ~JeodCheckpointable ()=default
JeodCheckpointable (const JeodCheckpointable &)=delete
JeodCheckpointable & operator= (const JeodCheckpointable &)=delete
virtual void pre_checkpoint ()
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint ()
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart ()
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart ()
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value ()
In general, return the value of the initialization action.
virtual const std::string get_final_name ()
In general, return the name of the finalization action.
virtual const std::string get_final_value ()
In general, return the value of the finalization action.
Data Fields
std::string metakernel_filename
The name of a text file containing the list of SPICE files to be loaded.
Protected Attributes
bool inactive {}
If set to true, makes the model inactive.
Private Member Functions
void initialize_time (const TimeManager &time_manager)
Initialize SpiceEphemeris timing.
void load_spice_files ()
Load SPICE kernel files containing ephemeris data.
void process_spk ()
Process spk objects and store array of loaded spk IDs.
void process_orientations ()
Load and locate all planetary orientation frames.
void introduce_item (EphemerisItem &item)
Introduce an EphemerisItem to the EphemeridesManager.
void populate_item (EphemerisItem &item, const std::string &name)
Populate basic attributes of a new SpiceEphemPoint.
SpiceEphemPoint * create_new_ephem_point (std::string object_name, const std::string &spice_name)
Create a new SpiceEphemPoint.
SpiceEphemOrientation * create_new_ephem_orientation (std::string jeod_name)
Create a new SpiceEphemOrientation.
void initialize_items ()
Initialize the SpiceEphemeris item data.
std::string spice_2_jeod (std::string spice_name)
Convert SPICE names to JEOD nomenclature.
std::string jeod_2_spice_pfix (std::string jeod_name)
Convert JEOD body name to SPICE pfix frame name.
void name_barycenter_frames ()
Name all the planetary barycenters with their JEOD identifiers.
void add_barycenter (int spice_id)
Add a barycenter corresponding to the given SPICE ID.
void create_barycenters ()
Check what if any barycenters need creating and do so.
void determine_root_node ()
Determine which item should be the root of the ref frame tree.
void add_descendants_r (SpiceEphemPoint *parent)
Add all offspring from a given node of the ref frame tree.
int find_parent_id (int obj_id)
Find the ID of the parent of a given SPICE object.
void update_trans ()
Update ephemerides of inertial frames supplied by spk files.
void update_rot ()
Update planetary orientations.
void mute_spice_errors ()
Mute SPICE errors so that they can be handled by the MessageHandler.
Private Attributes
bool force_update {}
Is an update needed even if the time hasn't changed?
JeodObjectVector< std::string >::type planet_names
The names of all planets to load into the simulation.
JeodObjectVector< std::string >::type orientation_names
The names of all objects for which orientation is required.
JeodPointerVector< SpiceEphemPoint >::type loaded_spk
All the spk objects tracked by this ephemeris.
JeodPointerVector< SpiceEphemOrientation >::type planetary_orientations
Objects defining planet-fixed reference frames.
std::string ident {"SPICE"}
Identifier for this model, set by the constructor.
double update_time {-99e99}
Time of last update, dynamic time seconds.
EphemerisRefFrame barycenter_frames [10]
Array of barycenter frames corresponding to SSBary and the planets.
SpiceEphemPoint * root_item {}
The root point in the reference frame tree.
const double * tdb_seconds {}
The source of ephemeris time information.
const double * dyn_seconds {}
The source of dynamic time information.
EphemeridesManager * ephem_mngr_local {}
Local ephem manager pointer to eliminate cascading passes in methods where possible (note some in inherited methods must remain).
Friends
class InputProcessor
void init_attrjeod__SpiceEphemeris ()
Additional Inherited Members
Detailed Description
The S_define-level class that provides planetary ephemerides.
The SpiceEphemeris class constructs the ephemeris reference frame tree and updates the states of the planets based on data from a SPICE file or files.
Definition at line 91 of file spice_ephem.hh.
Constructor & Destructor Documentation
SpiceEphemeris() [1/2]
jeod::SpiceEphemeris::SpiceEphemeris ()
SpiceEphemeris default constructor.
Definition at line 64 of file spice_ephem.cc.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, loaded_spk, orientation_names, planet_names, and planetary_orientations.
~SpiceEphemeris()
jeod::SpiceEphemeris::~SpiceEphemeris () override
SpiceEphemeris destructor.
Definition at line 76 of file spice_ephem.cc.
References JEOD_DELETE_OBJECT, JEOD_DEREGISTER_CHECKPOINTABLE, loaded_spk, orientation_names, planet_names, and planetary_orientations.
SpiceEphemeris() [2/2]
jeod::SpiceEphemeris::SpiceEphemeris (const SpiceEphemeris &) delete
Member Function Documentation
activate()
void jeod::SpiceEphemeris::activate () override virtual
Nominally, activate the object.
In the case of a SpiceEphemeris object, an inactive object cannot be activated once the simulation starts. Note that a SpiceEphemeris is active by default.
Implements jeod::ActivateInterface.
Definition at line 106 of file spice_ephem.cc.
References jeod::MessageHandler::error(), inactive, and jeod::EphemeridesMessages::internal_error.
add_barycenter()
void jeod::SpiceEphemeris::add_barycenter (int id) private
Add a barycenter corresponding to the given SPICE ID.
Parameters
[in] id id of barycenter to add
Definition at line 601 of file spice_ephem.cc.
References jeod::EphemeridesManager::add_integ_frame(), barycenter_frames, create_new_ephem_point(), ephem_mngr_local, jeod::RefFrameManager::find_ref_frame(), jeod::RefFrame::get_name(), loaded_spk, and MAX_NAME_LENGTH.
Referenced by create_barycenters().
add_descendants_r()
void jeod::SpiceEphemeris::add_descendants_r (SpiceEphemPoint * parent) private
Add all offspring from a given node of the ref frame tree.
Parameters
[in,out] parent Frame to attach to
Definition at line 756 of file spice_ephem.cc.
References jeod::RefFrameManager::add_frame_to_tree(), jeod::MessageHandler::debug(), jeod::EphemeridesMessages::debug, ephem_mngr_local, get_name(), jeod::RefFrame::get_name(), jeod::SpiceEphemPoint::get_spice_id(), jeod::EphemerisItem::get_target_frame(), and loaded_spk.
Referenced by ephem_build_tree().
add_orientation()
void jeod::SpiceEphemeris::add_orientation (std::string object_name) inline
Definition at line 128 of file spice_ephem.hh.
References orientation_names.
add_planet_name()
void jeod::SpiceEphemeris::add_planet_name (std::string planet_name) inline
Definition at line 121 of file spice_ephem.hh.
References planet_names.
create_barycenters()
void jeod::SpiceEphemeris::create_barycenters () private
Check what if any barycenters need creating and do so.
Any new barycenters are added to the all_loaded_items list and registered with the dynamics manager.
Definition at line 628 of file spice_ephem.cc.
References add_barycenter(), and loaded_spk.
Referenced by initialize_items().
create_new_ephem_orientation()
SpiceEphemOrientation * jeod::SpiceEphemeris::create_new_ephem_orientation (std::string jeod_name) private
Create a new SpiceEphemOrientation.
Returns
Pointer to object
Parameters
[in] jeod_name Name of new object
Definition at line 468 of file spice_ephem.cc.
References jeod_2_spice_pfix(), JEOD_ALLOC_CLASS_OBJECT, populate_item(), jeod::SpiceEphemOrientation::set_spice_frame_name(), tdb_seconds, and jeod::SpiceEphemOrientation::validate().
Referenced by process_orientations().
create_new_ephem_point()
SpiceEphemPoint * jeod::SpiceEphemeris::create_new_ephem_point (std::string object_name, const std::string & spice_name) private
Create a new SpiceEphemPoint.
Returns
Pointer to object
Parameters
[in] object_name Name of new object
[in] spice_name SPICE lookup name
Definition at line 432 of file spice_ephem.cc.
References jeod::MessageHandler::fail(), find_parent_id(), jeod::EphemeridesMessages::invalid_name, JEOD_ALLOC_CLASS_OBJECT, populate_item(), jeod::SpiceEphemPoint::set_parent_id(), and jeod::SpiceEphemPoint::set_spice_id().
Referenced by add_barycenter(), and process_spk().
deactivate()
void jeod::SpiceEphemeris::deactivate () override virtual
Deactivate the SpiceEphemeris object.
Implements jeod::ActivateInterface.
Definition at line 120 of file spice_ephem.cc.
References inactive.
determine_root_node()
void jeod::SpiceEphemeris::determine_root_node () private
Determine which item should be the root of the ref frame tree.
Definition at line 673 of file spice_ephem.cc.
References jeod::MessageHandler::debug(), jeod::EphemeridesMessages::debug, find_spice_id(), jeod::EphemerisItem::get_name(), jeod::EphemerisPoint::initialize_state(), loaded_spk, and root_item.
Referenced by ephem_build_tree(), and initialize_items().
ephem_activate()
void jeod::SpiceEphemeris::ephem_activate (EphemeridesManager & ephem_manager) override virtual
Mark appropriate items in the model as active.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 744 of file spice_ephem.cc.
ephem_build_tree()
void jeod::SpiceEphemeris::ephem_build_tree (EphemeridesManager & ephem_manager) override virtual
Construct the ephemeris model portions of the reference frame tree.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 788 of file spice_ephem.cc.
References add_descendants_r(), jeod::RefFrameManager::add_frame_to_tree(), jeod::MessageHandler::debug(), jeod::EphemeridesMessages::debug, determine_root_node(), jeod::MessageHandler::fail(), jeod::RefFrame::get_name(), jeod::EphemerisItem::get_target_frame(), inactive, loaded_spk, jeod::EphemeridesMessages::null_pointer, jeod::RefFrame::remove_from_parent(), and root_item.
ephem_initialize()
void jeod::SpiceEphemeris::ephem_initialize (EphemeridesManager & ephem_manager) override virtual
Complete the initialization process.
This method should be called after all other ephemeris models have completed their basic initialization and after all planets have registered themselves with the ephemeris manager.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 732 of file spice_ephem.cc.
ephem_update()
void jeod::SpiceEphemeris::ephem_update () override virtual
Update ephemerides for subscribed items.
Implements jeod::EphemerisInterface.
Definition at line 835 of file spice_ephem.cc.
References jeod::Numerical::compare_exact(), dyn_seconds, force_update, inactive, update_rot(), update_time, and update_trans().
find_parent_id()
int jeod::SpiceEphemeris::find_parent_id (int obj_id) private
Find the ID of the parent of a given SPICE object.
Here "parent" means both:
the frame to which the object is connected in the JEOD reference frame tree (the "parent" frame).
the object that will be used as the "observer" in the calls to SPICE to obtain the state of the given object.
Returns
of parent
Units: ID
Parameters
[in] obj_id child ID of which parent is to be found
Definition at line 881 of file spice_ephem.cc.
Referenced by create_new_ephem_point().
find_spice_id()
SpiceEphemPoint * jeod::SpiceEphemeris::find_spice_id (int id_to_find)
Find a SPICE ID in the loaded list of SPICE objects.
Returns
Pointer to object
Parameters
[in] id_to_find SPICE lookup name
Definition at line 857 of file spice_ephem.cc.
References loaded_spk.
Referenced by determine_root_node().
get_name()
std::string jeod::SpiceEphemeris::get_name () const override virtual
Return model name.
Returns
Name
Implements jeod::EphemerisInterface.
Definition at line 138 of file spice_ephem.cc.
References ident.
Referenced by add_descendants_r(), and update_trans().
initialize_items()
void jeod::SpiceEphemeris::initialize_items () private
Initialize the SpiceEphemeris item data.
Definition at line 482 of file spice_ephem.cc.
References create_barycenters(), determine_root_node(), jeod::MessageHandler::fail(), introduce_item(), loaded_spk, jeod::EphemeridesMessages::null_pointer, planetary_orientations, and root_item.
Referenced by initialize_model().
initialize_model()
void jeod::SpiceEphemeris::initialize_model (const TimeManager & time_manager, EphemeridesManager & ephem_manager)
Initialize the SpiceEphemeris model.
This method is called before the planets have been registered with the reference frame manager, so we don't know whether the ephemeris items should be enabled or disabled.
Parameters
[in] time_manager Time manager
[in] ephem_manager Incoming ephem manager
Definition at line 151 of file spice_ephem.cc.
References jeod::EphemeridesManager::add_ephemeris(), ephem_mngr_local, inactive, initialize_items(), initialize_time(), load_spice_files(), mute_spice_errors(), name_barycenter_frames(), process_orientations(), and process_spk().
initialize_time()
void jeod::SpiceEphemeris::initialize_time (const TimeManager & time_manager) private
Initialize SpiceEphemeris timing.
Parameters
[in] time_manager Time manager
Definition at line 200 of file spice_ephem.cc.
References dyn_seconds, jeod::TimeManager::dyn_time, jeod::MessageHandler::fail(), jeod::TimeManager::get_time_ptr(), jeod::EphemeridesMessages::inconsistent_setup, jeod::JeodBaseTime::seconds, and tdb_seconds.
Referenced by initialize_model().
introduce_item()
void jeod::SpiceEphemeris::introduce_item (EphemerisItem & item) private
Introduce an EphemerisItem to the EphemeridesManager.
Parameters
[in] item Item to introduce
Definition at line 518 of file spice_ephem.cc.
References jeod::EphemeridesManager::add_ephem_item(), ephem_mngr_local, jeod::MessageHandler::fail(), jeod::EphemerisItem::get_name(), jeod::EphemerisItem::get_target_frame(), and jeod::EphemeridesMessages::inconsistent_setup.
Referenced by initialize_items().
jeod_2_spice_pfix()
std::string jeod::SpiceEphemeris::jeod_2_spice_pfix (std::string jeod_name) private
Convert JEOD body name to SPICE pfix frame name.
Returns
name of pfix frame that SPICE associates with the given body. Handles high precision frames for Earth and Moon unless IAU is specified by user
Parameters
[in] jeod_name Name of the JEOD body.
Definition at line 557 of file spice_ephem.cc.
Referenced by create_new_ephem_orientation().
load_spice_files()
void jeod::SpiceEphemeris::load_spice_files () private
Load SPICE kernel files containing ephemeris data.
Definition at line 226 of file spice_ephem.cc.
References jeod::MessageHandler::fail(), jeod::EphemeridesMessages::file_error, MAX_MSG_LENGTH, and metakernel_filename.
Referenced by initialize_model().
mute_spice_errors()
void jeod::SpiceEphemeris::mute_spice_errors () private
Mute SPICE errors so that they can be handled by the MessageHandler.
Definition at line 978 of file spice_ephem.cc.
References MAX_NAME_LENGTH.
Referenced by initialize_model().
name_barycenter_frames()
void jeod::SpiceEphemeris::name_barycenter_frames () private
Name all the planetary barycenters with their JEOD identifiers.
Definition at line 575 of file spice_ephem.cc.
References barycenter_frames, MAX_NAME_LENGTH, jeod::RefFrame::set_name(), and spice_2_jeod().
Referenced by initialize_model().
operator=()
SpiceEphemeris& jeod::SpiceEphemeris::operator= (const SpiceEphemeris &) delete
populate_item()
void jeod::SpiceEphemeris::populate_item (EphemerisItem & item, const std::string & object_name) private
Populate basic attributes of a new SpiceEphemPoint.
Parameters
[in,out] item Pointer to item to populate
[in] object_name Name of the item
Definition at line 419 of file spice_ephem.cc.
References jeod::EphemerisItem::default_suffix(), jeod::EphemerisItem::enable(), jeod::EphemerisItem::set_name(), and jeod::EphemerisItem::set_owner().
Referenced by create_new_ephem_orientation(), and create_new_ephem_point().
process_orientations()
void jeod::SpiceEphemeris::process_orientations () private
Load and locate all planetary orientation frames.
Definition at line 401 of file spice_ephem.cc.
References create_new_ephem_orientation(), orientation_names, and planetary_orientations.
Referenced by initialize_model().
process_spk()
void jeod::SpiceEphemeris::process_spk () private
Process spk objects and store array of loaded spk IDs.
Definition at line 252 of file spice_ephem.cc.
References create_new_ephem_point(), jeod::MessageHandler::debug(), jeod::EphemeridesMessages::debug, jeod::MessageHandler::fail(), jeod::EphemeridesMessages::item_not_in_file, loaded_spk, MAX_IDS, MAX_NAME_LENGTH, MAX_PATH_LENGTH, and planet_names.
Referenced by initialize_model().
simple_restore()
void jeod::SpiceEphemeris::simple_restore () override virtual
Set the SPICE model for a restart.
Implements jeod::SimpleCheckpointable.
Definition at line 191 of file spice_ephem.cc.
spice_2_jeod()
std::string jeod::SpiceEphemeris::spice_2_jeod (std::string spice_name) private
Convert SPICE names to JEOD nomenclature.
Returns
JEOD-friendly name of a SPICE name
Parameters
[in] spice_name Name of a SPICE object.
Definition at line 542 of file spice_ephem.cc.
Referenced by name_barycenter_frames().
timestamp()
double jeod::SpiceEphemeris::timestamp () const override virtual
Return time of last update.
Returns
Timestamp
Units: day
Implements jeod::EphemerisInterface.
Definition at line 129 of file spice_ephem.cc.
References update_time.
update_rot()
void jeod::SpiceEphemeris::update_rot () private
Update planetary orientations.
Definition at line 967 of file spice_ephem.cc.
References dyn_seconds, planetary_orientations, and tdb_seconds.
Referenced by ephem_update().
update_trans()
void jeod::SpiceEphemeris::update_trans () private
Update ephemerides of inertial frames supplied by spk files.
Definition at line 906 of file spice_ephem.cc.
References jeod::MessageHandler::fail(), get_name(), jeod::EphemeridesMessages::item_not_in_file, loaded_spk, MAX_MSG_LENGTH, root_item, tdb_seconds, jeod::EphemerisPoint::update(), and update_time.
Referenced by ephem_update().
Friends And Related Function Documentation
init_attrjeod__SpiceEphemeris
void init_attrjeod__SpiceEphemeris () friend
InputProcessor
friend class InputProcessor friend
Definition at line 95 of file spice_ephem.hh.
Field Documentation
barycenter_frames
EphemerisRefFrame jeod::SpiceEphemeris::barycenter_frames[10] private
Array of barycenter frames corresponding to SSBary and the planets.
trick_units(–)
Definition at line 197 of file spice_ephem.hh.
Referenced by add_barycenter(), and name_barycenter_frames().
dyn_seconds
const double* jeod::SpiceEphemeris::dyn_seconds {} private
The source of dynamic time information.
trick_units(–)
Definition at line 212 of file spice_ephem.hh.
Referenced by ephem_update(), initialize_time(), and update_rot().
ephem_mngr_local
EphemeridesManager* jeod::SpiceEphemeris::ephem_mngr_local {} private
Local ephem manager pointer to eliminate cascading passes in methods where possible (note some in inherited methods must remain).
trick_units(–)
Definition at line 218 of file spice_ephem.hh.
Referenced by add_barycenter(), add_descendants_r(), initialize_model(), and introduce_item().
force_update
bool jeod::SpiceEphemeris::force_update {} private
Is an update needed even if the time hasn't changed?
trick_units(–)
Definition at line 162 of file spice_ephem.hh.
Referenced by ephem_update().
ident
std::string jeod::SpiceEphemeris::ident {"SPICE"} private
Identifier for this model, set by the constructor.
trick_units(–)
Definition at line 187 of file spice_ephem.hh.
Referenced by get_name().
inactive
bool jeod::SpiceEphemeris::inactive {} protected
If set to true, makes the model inactive.
This is set to false (i.e., model is active) by the constructor. Setting this flag to true prior to initialization time will result in the model never doing anything. Setting this flag to true after the model has been active for some time turns it off from that point forward. Turning on the model after it has been inactive for some time is not supported.trick_units(–)
Definition at line 154 of file spice_ephem.hh.
Referenced by activate(), deactivate(), ephem_build_tree(), ephem_update(), and initialize_model().
loaded_spk
JeodPointerVector<SpiceEphemPoint>::type jeod::SpiceEphemeris::loaded_spk private
All the spk objects tracked by this ephemeris.
trick_io(**)
Definition at line 177 of file spice_ephem.hh.
Referenced by add_barycenter(), add_descendants_r(), create_barycenters(), determine_root_node(), ephem_build_tree(), find_spice_id(), initialize_items(), process_spk(), SpiceEphemeris(), update_trans(), and ~SpiceEphemeris().
metakernel_filename
std::string jeod::SpiceEphemeris::metakernel_filename
The name of a text file containing the list of SPICE files to be loaded.
Must be in format needed by SPICE furnsh_c() function. See comments for method load_spice_files() in spice_ephem.cc for format details.trick_units(–)
Definition at line 143 of file spice_ephem.hh.
Referenced by load_spice_files().
orientation_names
JeodObjectVector<std::string>::type jeod::SpiceEphemeris::orientation_names private
The names of all objects for which orientation is required.
trick_io(**)
Definition at line 172 of file spice_ephem.hh.
Referenced by add_orientation(), process_orientations(), SpiceEphemeris(), and ~SpiceEphemeris().
planet_names
JeodObjectVector<std::string>::type jeod::SpiceEphemeris::planet_names private
The names of all planets to load into the simulation.
trick_io(**)
Definition at line 167 of file spice_ephem.hh.
Referenced by add_planet_name(), process_spk(), SpiceEphemeris(), and ~SpiceEphemeris().
planetary_orientations
JeodPointerVector<SpiceEphemOrientation>::type jeod::SpiceEphemeris::planetary_orientations private
Objects defining planet-fixed reference frames.
trick_io(**)
Definition at line 182 of file spice_ephem.hh.
Referenced by initialize_items(), process_orientations(), SpiceEphemeris(), update_rot(), and ~SpiceEphemeris().
root_item
SpiceEphemPoint* jeod::SpiceEphemeris::root_item {} private
The root point in the reference frame tree.
trick_units(–)
Definition at line 202 of file spice_ephem.hh.
Referenced by determine_root_node(), ephem_build_tree(), initialize_items(), and update_trans().
tdb_seconds
const double* jeod::SpiceEphemeris::tdb_seconds {} private
The source of ephemeris time information.
trick_units(–)
Definition at line 207 of file spice_ephem.hh.
Referenced by create_new_ephem_orientation(), initialize_time(), update_rot(), and update_trans().
update_time
double jeod::SpiceEphemeris::update_time {-99e99} private
Time of last update, dynamic time seconds.
trick_units(s)
Definition at line 192 of file spice_ephem.hh.
Referenced by ephem_update(), timestamp(), and update_trans().
The documentation for this class was generated from the following files:
spice_ephem.hh
spice_ephem.cc