JEOD: jeod::MassBody Class Reference
jeod::MassBody Class Reference
Represent both an atomic chunk of mass and an interconnected set of masses.
#include <mass.hh>
Public Member Functions
MassBody (void)
Default constructor; constructs a MassBody object.
virtual ~MassBody (void)
Destroy a MassBody object.
void initialize_mass (const MassPropertiesInit &properties, const MassPointInit *points, unsigned int num_points)
Initialize a MassBody object.
bool get_mass_properties_initialized ()
void set_name (std::string name_in)
virtual bool attach_to (const char *this_point_name, const char *parent_point_name, MassBody &parent)
Attach this mass body's root body as a child of the specified mass body such that the specified mass points on the two bodies are coincident and the frames associated with those mass points are related by a 180 degree yaw.
virtual bool attach_to (double offset_pstr_cstr_pstr[3], double T_pstr_cstr[3][3], MassBody &parent)
Attach this mass body's root body as a child of the specified mass body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with respect to the parent body's structural axes as specified.
virtual bool attach_child (const char *this_point_name, const char *child_point_name, MassBody &child)
Attach a child MassBody by point specification.
virtual bool attach_child (double offset_pstr_cstr_pstr[3], double T_pstr_cstr[3][3], MassBody &child)
Attach a child MassBody by location specification.
virtual bool attach_validate (const MassBody &parent, bool generate_message) const
Validate whether the pending attachment is legal.
virtual bool detach (MassBody &from_body)
Detach the two bodies, 'this' and the argument body, from each other such such that the detachment occurs between the superior body and the immediate child along the path from the inferior body to the superior body.
virtual bool detach (void)
Detach a mass body from its immediate parent.
virtual bool detach_validate (const MassBody *parent, bool generate_message) const
Validate whether the pending detachment is legal.
void reattach (double offset[3], double T_pstr_cstr[3][3])
Re-attach a child MassBody to a parent MassBody.
const MassPoint * find_mass_point (const char *pt_name) const
Find the mass point with the given name.
virtual void add_mass_point (const MassPointInit &mass_point_init)
Add a mass point to the list of such.
std::size_t mass_points_size (void) const
Return the number of mass points for this body.
bool is_progeny_of (const MassBody &test_body) const
Return true if this MassBody is an offspring of provided one, false if not.
virtual const MassBody * get_parent_body (void) const
Returns the MassBody's parent body, as a const pointer.
virtual const MassBody * get_root_body (void) const
Finds & returns root of current MassBody's tree.
void set_update_flag (void)
Flag mass bodies from the current body on up the mass tree as in need of mass property updates.
virtual void update_mass_properties (void)
Update composite mass properties for a mass tree marked for update.
void print_body (FILE *file_ptr, int levels) const
Recursively print out the data in this and its children to given file.
void print_tree (const char *file_name, int levels) const
Print out the MassTree members' data to a given file.
Static Public Member Functions
static void compute_point_mass_inertia (double mass, const double r_pt[3], double inertia[3][3])
Compute the inertia tensor of a point mass.
Data Fields
NamedItem name
Body name.
MassProperties core_properties
The mass properties of this body alone, excluding child bodies.
MassProperties composite_properties
The mass properties of this body, including child bodies.
bool compute_inverse_inertia
When clear, the inverse of the inertia tensor is not calculated.
MassPoint structure_point
The location and orientation of the structural frame with respect to the parent body's structural frame.
DynBody *const dyn_owner
Indicates this body belongs to a DynBody.
Protected Member Functions
MassBody (DynBody &owner)
Create a MassBody, marking is_dynamic as true.
virtual bool attach_root_body (double offset_pstr_cstr_pstr[3], double T_pstr_cstr[3][3], MassBody &parent)
Attach this mass body, which must be a root body, as a child of the specified mass body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with repect to the parent body's structural axes as specified.
virtual bool attach_validate_parent (const MassBody &parent, bool generate_message) const
Validate whether the pending attachment is legal from a connectivity point of view.
virtual bool attach_validate_child (const MassBody &child, bool generate_message) const
Validate whether the pending attachment is legal from a physical point of view.
virtual void attach_establish_links (MassBody &parent)
Establish the logical connectivity between parent and child.
virtual void attach_update_properties (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], MassBody &child)
Set the relation between parent and child and update the mass properties.
virtual bool detach_validate_parent (const MassBody *parent, bool generate_message) const
Validate whether the pending detachment is legal from a connectivity point of view.
virtual bool detach_validate_child (const MassBody &child, bool generate_message) const
Validate whether the pending detachment is legal from a mass tree point of view.
virtual void detach_sever_links (MassBody &parent)
Break the logical connectivity between parent and child.
virtual void detach_update_properties (MassBody &child)
Update parent and child properties to reflect that they are detached.
virtual MassBody * get_parent_body_internal (void)
Returns the MassBody's parent body, as a non-const pointer.
virtual MassBody * get_root_body_internal (void)
Finds & returns root of current MassBody's tree.
void calc_composite_cm (void)
Calculate the aggregate cm for a composite MassBody.
void calc_composite_inertia (void)
Calculate the aggregate inertia matrix for a composite MassBody.
Protected Attributes
BaseDynManager * dyn_manager
The dynamics manager for the simulation.
bool mass_properties_initialized
Initialized flag.
MassBodyLinks links
Linkage to rest of mass tree.
bool needs_update
When set, indicates that an update to the composite mass is needed.
std::list< MassPoint * > mass_points
List of points associated with this mass body.
MassPoint core_wrt_composite
The location and orientation of the composite CoM and body frame with respect to the parent body's composite CoM and body frame.
MassPoint composite_wrt_pstr
The location and orientation of the composite CoM and body frame with respect to the parent body's structural frame.
MassPoint composite_wrt_pbdy
The location and orientation of the composite CoM and body frame with respect to the parent body's composite CoM and body frame.
Private Member Functions
MassBody (const MassBody &rhs)
Not implemented.
void operator= (const MassBody &rhs)
Not implemented.
Friends
class InputProcessor
class MassBodyLinks
class DynBody
void init_attrjeod__MassBody ()
Detailed Description
Represent both an atomic chunk of mass and an interconnected set of masses.
Multiple MassBody objects can be attached to one another in a tree structure. This connected sets of bodies has a composite set of mass properties. Sans these connections, a body will have some core mass proprties.
The MassBody class is one of the key classes in JEOD 2.0. In addition to representing masses, it is also the parent of the DynBody class, which is used in JEOD 2.0 to represent vehicles.
Assumptions and Limitations
Rigid Bodies
Tree attachment Structure
Definition at line 113 of file mass.hh.
Constructor & Destructor Documentation
MassBody() [1/3]
jeod::MassBody::MassBody (void)
Default constructor; constructs a MassBody object.
Definition at line 79 of file mass.cc.
References jeod::Matrix3x3::identity(), and JEOD_REGISTER_CLASS.
~MassBody()
jeod::MassBody::~MassBody (void) virtual
Destroy a MassBody object.
Definition at line 159 of file mass.cc.
References jeod::NamedItem::c_str(), jeod::TreeLinks< Links, Container, Messages >::child_tail(), jeod::TreeLinks< Links, Container, Messages >::container(), detach(), jeod::MassPoint::detach(), jeod::MessageHandler::fail(), jeod::TreeLinks< Links, Container, Messages >::has_children(), jeod::MassBodyMessages::invalid_detach, jeod::TreeLinks< Links, Container, Messages >::is_root(), JEOD_DELETE_OBJECT, JEOD_IS_ALLOCATED, links, mass_points, name, and set_update_flag().
MassBody() [2/3]
jeod::MassBody::MassBody (DynBody & owner) explicit protected
Create a MassBody, marking is_dynamic as true.
Default constructor; constructs a MassBody object.
Utilized by DynBody via friendship.
Definition at line 118 of file mass.cc.
References jeod::MassPoint::attach(), composite_properties, composite_wrt_pbdy, core_properties, core_wrt_composite, jeod::Matrix3x3::identity(), JEOD_REGISTER_CLASS, structure_point, and jeod::MassPointState::T_parent_this.
MassBody() [3/3]
jeod::MassBody::MassBody (const MassBody & rhs) private
Not implemented.
Member Function Documentation
add_mass_point()
void jeod::MassBody::add_mass_point (const MassPointInit & mass_point_init) virtual
Add a mass point to the list of such.
Parameters
[in] mass_point_init Mass point spec
Definition at line 391 of file mass.cc.
References jeod::MassPoint::attach(), jeod::NamedItem::c_str(), jeod::MessageHandler::fail(), find_mass_point(), jeod::NamedItem::freeze_name(), jeod::MassPointInit::initialize_mass_point(), jeod::MassBodyMessages::invalid_name, JEOD_ALLOC_CLASS_OBJECT, mass_points, jeod::MassPoint::name, jeod::MassPointInit::name, name, jeod::NamedItem::set_name(), structure_point, and jeod::NamedItem::suffix().
Referenced by jeod::DynBody::add_mass_point(), and initialize_mass().
attach_child() [1/2]
bool jeod::MassBody::attach_child (const char * this_point_name, const char * child_point_name, MassBody & child) virtual
Attach a child MassBody by point specification.
See corresponding MassBody::attach_to() method for more information.
Definition at line 243 of file mass_attach.cc.
References attach_to().
attach_child() [2/2]
bool jeod::MassBody::attach_child (double offset_pstr_cstr_pstr[3], double T_pstr_cstr[3][3], MassBody & child) virtual
Attach a child MassBody by location specification.
See corresponding MassBody::attach_to() method for more information. Note that the offset and transformation are specified w.r.t. the parent in both attach_to() and attach_child()
Definition at line 262 of file mass_attach.cc.
References attach_to().
attach_establish_links()
void jeod::MassBody::attach_establish_links (MassBody & parent) protected virtual
Establish the logical connectivity between parent and child.
Extensibility comments –
This method is invoked before the computing the physical relation between parent and child.
The generic purpose of this method is to establish the logical connectivity between parent and child in terms of the child class.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The attachment is valid; not checked.
Parameters
[in,out] parent The new parent body; the body to which this body is to be attached.
Definition at line 493 of file mass_attach.cc.
References jeod::MassPoint::attach(), jeod::TreeLinks< Links, Container, Messages >::attach(), composite_wrt_pbdy, composite_wrt_pstr, links, and structure_point.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_establish_links(), and attach_root_body().
attach_root_body()
bool jeod::MassBody::attach_root_body (double offset_pstr_cstr_pstr[3], double T_pstr_cstr[3][3], MassBody & parent) protected virtual
Attach this mass body, which must be a root body, as a child of the specified mass body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with repect to the parent body's structural axes as specified.
Assumptions and Limitations
The subject body, this, must be a root body.
Returns
Success indicator: true=success, false=attachment not performed.
Parameters
[in] offset_pstr_cstr_pstr Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
Units: M
[in] T_pstr_cstr Transformation matrix from the new parent body's structural frame to this body's structural frame.
[in,out] parent The new parent body; the body to which this body is to be attached.
Definition at line 290 of file mass_attach.cc.
References attach_establish_links(), attach_update_properties(), attach_validate(), jeod::NamedItem::c_str(), jeod::MessageHandler::error(), jeod::MassBodyMessages::invalid_attach, jeod::TreeLinks< Links, Container, Messages >::is_root(), links, and name.
Referenced by attach_to().
attach_to() [1/2]
bool jeod::MassBody::attach_to (const char * this_point_name, const char * parent_point_name, MassBody & parent) virtual
Attach this mass body's root body as a child of the specified mass body such that the specified mass points on the two bodies are coincident and the frames associated with those mass points are related by a 180 degree yaw.
Returns
Success indicator: true=success, false=attachment not performed.
Parameters
[in] this_point_name The name of a mass point contained in this mass body's list of mass points.
[in] parent_point_name The name of a mass point contained in the new parent body's list of mass points.
[in,out] parent The new parent body; the body to which this body's root body is to be attached.
Definition at line 71 of file mass_attach.cc.
References jeod::MassPoint::attach(), attach_validate(), jeod::NamedItem::c_str(), jeod::MassPoint::compute_state_wrt_pred(), jeod::Quaternion::conjugate(), jeod::MassPoint::detach(), find_mass_point(), jeod::generate_bad_point_message(), name, jeod::Vector3::negate(), jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::Quaternion::scalar, structure_point, jeod::MassPointState::T_parent_this, jeod::Vector3::transform(), jeod::Matrix3x3::transpose(), and jeod::Quaternion::vector.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), and attach_child().
attach_to() [2/2]
bool jeod::MassBody::attach_to (double offset_pstr_cstr_pstr[3], double T_pstr_cstr[3][3], MassBody & parent) virtual
Attach this mass body's root body as a child of the specified mass body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with respect to the parent body's structural axes as specified.
Returns
Success indicator: true=success, false=attachment not performed.
Parameters
[in] offset_pstr_cstr_pstr Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
Units: M
[in] T_pstr_cstr Transformation matrix from the new parent body's structural frame to this body's structural frame.
[in,out] parent The new parent body; the body to which this body's root body is to be attached.
Definition at line 165 of file mass_attach.cc.
References jeod::MassBodyMessages::attach_info, attach_root_body(), attach_validate(), jeod::NamedItem::c_str(), jeod::MassPoint::compute_state_wrt_pred(), jeod::Vector3::copy(), jeod::MessageHandler::error(), get_root_body(), get_root_body_internal(), jeod::MessageHandler::inform(), jeod::MassBodyMessages::invalid_attach, links, name, jeod::TreeLinks< Links, Container, Messages >::parent(), jeod::MassPointState::position, jeod::Matrix3x3::product_left_transpose(), structure_point, jeod::MassPointState::T_parent_this, and jeod::Vector3::transform_transpose_decr().
attach_update_properties()
void jeod::MassBody::attach_update_properties (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], MassBody & child) protected virtual
Set the relation between parent and child and update the mass properties.
Extensibility comments –
This method is sent to the parent body of the attachment after the child body has established the logical connectivity between the parent body and child body.
The generic purpose of this method is to establish the physical relation between parent and child and to update any physical properties that change as a result of the attachment.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The attachment is valid and logical connectivity has been established. Neither assumption is checked.
Parameters
[in] offset_pstr_cstr_pstr Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
Units: M
[in] T_pstr_cstr Transformation matrix from the new parent body's structural frame to this body's structural frame.
[in,out] child The child body; the body newly attached to this body.
Definition at line 531 of file mass_attach.cc.
References composite_properties, composite_wrt_pbdy, composite_wrt_pstr, jeod::MassPointState::compute_transformation(), get_root_body_internal(), jeod::Vector3::incr(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_conjugate(), jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, set_update_flag(), structure_point, jeod::MassPointState::T_parent_this, jeod::Vector3::transform_transpose(), update_mass_properties(), jeod::MassPointState::update_orientation(), and jeod::MassPointState::update_point().
Referenced by jeod::DynBody::add_mass_body(), attach_root_body(), jeod::DynBody::attach_update_properties(), and jeod::DynBody::process_dynamic_attachment().
attach_validate()
bool jeod::MassBody::attach_validate (const MassBody & parent, bool generate_message) const virtual
Validate whether the pending attachment is legal.
Extensibility comments –
Overriding this method doesn't make a whole lot of sense.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The subject body, this, must be a root body. This is not checked.
Returns
Validity indicator
Parameters
[in] parent The new parent body; the body to which this body is to be attached.
[in] generate_message Generate message if invalid?
Definition at line 348 of file mass_attach.cc.
References attach_validate_child(), and attach_validate_parent().
Referenced by attach_root_body(), and attach_to().
attach_validate_child()
bool jeod::MassBody::attach_validate_child (const MassBody & child, bool generate_message) const protected virtual
Validate whether the pending attachment is legal from a physical point of view.
Extensibility comments –
This method determines whether invoking attach_update_properties makes sense.
This is a free pass for a MassBody.
Returns
Validity indicator
Parameters
[in] child The child body; the body to be attached to this body.
[in] generate_message Generate message if invalid?
Definition at line 436 of file mass_attach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::error(), jeod::BaseDynManager::find_dyn_body(), get_root_body(), jeod::MassBodyMessages::invalid_attach, and name.
Referenced by attach_validate().
attach_validate_parent()
bool jeod::MassBody::attach_validate_parent (const MassBody & parent, bool generate_message) const protected virtual
Validate whether the pending attachment is legal from a connectivity point of view.
Extensibility comments –
This method determines whether invoking attach_establish_links makes sense.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The subject body, this, must be a root body. This is not checked.
Returns
Validity indicator
Parameters
[in] parent The new parent body; the body to which this body is to be attached.
[in] generate_message Generate message if invalid?
Definition at line 382 of file mass_attach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::error(), jeod::BaseDynManager::find_dyn_body(), get_root_body(), jeod::MassBodyMessages::invalid_attach, and name.
Referenced by attach_validate().
calc_composite_cm()
void jeod::MassBody::calc_composite_cm (void) protected
Calculate the aggregate cm for a composite MassBody.
Assumptions and Limitations
Rigid bodies
Must calculate from bottom to top of tree for meaningful results
Definition at line 48 of file mass_calc_composite_cm.cc.
References composite_properties, composite_wrt_pstr, core_properties, jeod::Vector3::initialize(), jeod::MassProperties::inverse_mass, links, jeod::MassProperties::mass, jeod::MassPointState::position, jeod::Vector3::scale(), and jeod::Vector3::scale_incr().
Referenced by update_mass_properties().
calc_composite_inertia()
void jeod::MassBody::calc_composite_inertia (void) protected
Calculate the aggregate inertia matrix for a composite MassBody.
Assumptions and Limitations
Rigid Bodies
Tree attachment structure
Must calculate from bottom to top of tree for meaningful results
Definition at line 47 of file mass_calc_composite_inertia.cc.
References jeod::Matrix3x3::add(), composite_properties, composite_wrt_pbdy, compute_point_mass_inertia(), core_properties, core_wrt_composite, jeod::Matrix3x3::incr(), jeod::MassProperties::inertia, links, jeod::MassProperties::mass, jeod::MassPointState::position, jeod::MassPointState::T_parent_this, and jeod::Matrix3x3::transpose_transform_matrix().
Referenced by update_mass_properties().
compute_point_mass_inertia()
void jeod::MassBody::compute_point_mass_inertia (double mass, const double r_pt[3], double inertia[3][3]) static
Compute the inertia tensor of a point mass.
Parameters
[in] mass Mass of point mass
Units: kg
[in] r_pt Vector to point mass
Units: M
[out] inertia Inertia tensor
Units: kgM2
Definition at line 43 of file mass_point_mass_inertia.cc.
Referenced by calc_composite_inertia(), and jeod::MassPropertiesInit::initialize_mass_properties().
detach() [1/2]
bool jeod::MassBody::detach (MassBody & mass_body) virtual
Detach the two bodies, 'this' and the argument body, from each other such such that the detachment occurs between the superior body and the immediate child along the path from the inferior body to the superior body.
Returns true to indicate success, false to indicate failure.
Assumptions and Limitations
Instances of more derived classes, with presumably more involved dynamics, are situated higher in the mass tree than are more basic instances. For example, a simple MassBody can be a child of a DynBody, but not the other way around.
The attachment in the mass tree between the immediate child and the superior body is assumed to reflect a real physical attachment.
Returns
Success flag
Parameters
[in,out] mass_body The other body
Definition at line 66 of file mass_detach.cc.
References jeod::NamedItem::c_str(), detach(), jeod::MessageHandler::inform(), jeod::MassBodyMessages::invalid_detach, links, and name.
Referenced by jeod::BodyDetach::apply(), jeod::BodyDetachSpecific::apply(), detach(), and ~MassBody().
detach() [2/2]
bool jeod::MassBody::detach (void) virtual
Detach a mass body from its immediate parent.
Returns true to indicate success, false to indicate failure.
Assumptions and Limitations
Instances of more derived classes, with presumably more involved dynamics, are situated higher in the mass tree than are more basic instances. For example, a simple MassBody can be a child of a DynBody, but not the other way around.
The attachment in the mass tree between the immediate child and the superior body is assumed to reflect a real physical attachment.
Returns
Success flag
Definition at line 134 of file mass_detach.cc.
References detach_sever_links(), detach_update_properties(), detach_validate(), dyn_owner, links, jeod::TreeLinks< Links, Container, Messages >::parent(), and jeod::DynBody::remove_mass_body().
Referenced by ~MassBody().
detach_sever_links()
void jeod::MassBody::detach_sever_links (MassBody & parent) protected virtual
Break the logical connectivity between parent and child.
Extensibility comments –
This method is invoked before the updating the parent/child states.
The generic purpose of this method is to sever all connectivity links between parent and child, in terms of the child class.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The detachment is valid; not checked.
Parameters
[in,out] parent The parent body; the body from which this body is to be detached.
Definition at line 305 of file mass_detach.cc.
References jeod::TreeLinks< Links, Container, Messages >::detach(), and links.
Referenced by detach(), and jeod::DynBody::detach_mass_internal().
detach_update_properties()
void jeod::MassBody::detach_update_properties (MassBody & child) protected virtual
Update parent and child properties to reflect that they are detached.
Extensibility comments –
This method is sent to the parent body of the detachment after the child body has severed the logical connectivity between the parent body and child body.
The generic purpose of this method is to update any physical properties that change as a result of the detachment.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The detachment is valid and logical connectivity has been severed. Neither assumption is checked.
Parameters
[in,out] child The child body; the body newly detached from this body.
Definition at line 334 of file mass_detach.cc.
References composite_properties, composite_wrt_pbdy, composite_wrt_pstr, compute_inverse_inertia, get_root_body_internal(), jeod::MassProperties::inertia, jeod::Matrix3x3::initialize(), jeod::MassPoint::initialize_mass_point(), jeod::MassProperties::inverse_inertia, jeod::Matrix3x3::invert_symmetric(), jeod::MassProperties::mass, set_update_flag(), structure_point, and update_mass_properties().
Referenced by detach(), and jeod::DynBody::detach_mass_internal().
detach_validate()
bool jeod::MassBody::detach_validate (const MassBody * parent, bool generate_message) const virtual
Validate whether the pending detachment is legal.
Extensibility comments –
Overriding this method doesn't make a whole lot of sense.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Assumptions and Limitations
The subject body, this, must be a root body. This is not checked.
Returns
Validity indicator
Parameters
[in] parent The parent body; the body from which this body is to be detached.
[in] generate_message Generate message if invalid?
Definition at line 186 of file mass_detach.cc.
References detach_validate_child(), and detach_validate_parent().
Referenced by detach().
detach_validate_child()
bool jeod::MassBody::detach_validate_child (const MassBody & child, bool generate_message) const protected virtual
Validate whether the pending detachment is legal from a mass tree point of view.
Extensibility comments –
This method determines whether invoking detach_update_properties makes sense.
Returns
Validity indicator
Parameters
[in] child The child body; the body to be detached from this body.
[in] generate_message Generate message if invalid?
Definition at line 266 of file mass_detach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::BaseDynManager::find_dyn_body(), jeod::MessageHandler::inform(), jeod::MassBodyMessages::invalid_detach, and name.
Referenced by detach_validate().
detach_validate_parent()
bool jeod::MassBody::detach_validate_parent (const MassBody * parent, bool generate_message) const protected virtual
Validate whether the pending detachment is legal from a connectivity point of view.
Extensibility comments –
This method determines whether invoking detach_sever_links makes sense.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Returns
Validity indicator
Parameters
[in] parent The parent body; the body from which this body is to be detached.
[in] generate_message Generate message if invalid?
Definition at line 217 of file mass_detach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::BaseDynManager::find_dyn_body(), jeod::MessageHandler::inform(), jeod::MassBodyMessages::invalid_detach, name, and jeod::MessageHandler::warn().
Referenced by detach_validate().
find_mass_point()
const MassPoint * jeod::MassBody::find_mass_point (const char * pt_name) const
Find the mass point with the given name.
Returns
Mass point
Parameters
[in] pt_name mass point name
Definition at line 361 of file mass.cc.
References mass_points, name, jeod::NamedItem::size(), and jeod::NamedItem::suffix().
Referenced by jeod::DynBody::add_mass_body(), add_mass_point(), jeod::DynBody::attach_child(), attach_to(), and jeod::DynBody::attach_to_frame().
get_mass_properties_initialized()
bool jeod::MassBody::get_mass_properties_initialized () inline
Definition at line 146 of file mass.hh.
References mass_properties_initialized.
get_parent_body()
const MassBody * jeod::MassBody::get_parent_body (void) const virtual
Returns the MassBody's parent body, as a const pointer.
Returns
Pointer to parent body
Definition at line 252 of file mass.cc.
References links, and jeod::TreeLinks< Links, Container, Messages >::parent().
Referenced by jeod::DynBody::remove_mass_body().
get_parent_body_internal()
MassBody * jeod::MassBody::get_parent_body_internal (void) protected virtual
Returns the MassBody's parent body, as a non-const pointer.
Returns
Pointer to parent body
Definition at line 266 of file mass.cc.
References links, and jeod::TreeLinks< Links, Container, Messages >::parent().
get_root_body()
const MassBody * jeod::MassBody::get_root_body (void) const virtual
Finds & returns root of current MassBody's tree.
Returns
Pointer to root body
Definition at line 279 of file mass.cc.
References links, and jeod::TreeLinks< Links, Container, Messages >::root().
Referenced by jeod::DynBody::add_mass_body_validate(), attach_to(), attach_validate_child(), attach_validate_parent(), jeod::ContactPair::check_tree(), print_tree(), and jeod::SurfaceModel::update_articulation().
get_root_body_internal()
MassBody * jeod::MassBody::get_root_body_internal (void) protected virtual
Finds & returns root of current MassBody's tree.
Returns
Pointer to root body
Definition at line 292 of file mass.cc.
References links, and jeod::TreeLinks< Links, Container, Messages >::root().
Referenced by jeod::DynBody::add_mass_body(), attach_to(), attach_update_properties(), detach_update_properties(), and reattach().
initialize_mass()
void jeod::MassBody::initialize_mass (const MassPropertiesInit & properties, const MassPointInit * points, unsigned int num_points)
Initialize a MassBody object.
Parameters
[in] properties Core mass ppty specs
[in] points Mass point specs
[in] num_points Size of the points array
Definition at line 213 of file mass.cc.
References add_mass_point(), jeod::DynBody::add_mass_point(), composite_properties, jeod::Matrix3x3::copy(), core_properties, dyn_owner, jeod::MassPropertiesInit::initialize_mass_properties(), mass_properties_initialized, jeod::MassPointState::Q_parent_this, set_update_flag(), and jeod::MassPointState::T_parent_this.
Referenced by jeod::MassBodyInit::apply().
is_progeny_of()
bool jeod::MassBody::is_progeny_of (const MassBody & test_body) const
Return true if this MassBody is an offspring of provided one, false if not.
Returns
Is this offspring of test_body?
Parameters
[in] test_body Other MassBody
Definition at line 306 of file mass.cc.
References links.
mass_points_size()
size_t jeod::MassBody::mass_points_size (void) const
Return the number of mass points for this body.
Returns
Mass point
Definition at line 347 of file mass.cc.
References mass_points.
operator=()
void jeod::MassBody::operator= (const MassBody & rhs) private
Not implemented.
print_body()
void jeod::MassBody::print_body (FILE * file_ptr, int levels) const
Recursively print out the data in this and its children to given file.
Parameters
[in,out] file_ptr Output file stream
[in,out] levels Max desired recursion level
Definition at line 47 of file mass_print_body.cc.
References jeod::NamedItem::c_str(), composite_properties, core_properties, jeod::MassProperties::inertia, jeod::MassProperties::inverse_inertia, jeod::MassProperties::inverse_mass, links, jeod::MassProperties::mass, name, jeod::MassPointState::position, print_body(), structure_point, and jeod::MassPointState::T_parent_this.
Referenced by print_body(), and print_tree().
print_tree()
void jeod::MassBody::print_tree (const char * file_name, int levels) const
Print out the MassTree members' data to a given file.
Parameters
[in] file_name Desired output file name
[in,out] levels Max desired recursion level
Definition at line 49 of file mass_print_tree.cc.
References jeod::MessageHandler::fail(), get_root_body(), jeod::MassBodyMessages::io_error, and print_body().
reattach()
void jeod::MassBody::reattach (double offset[3], double T_pstr_cstr[3][3])
Re-attach a child MassBody to a parent MassBody.
Assumptions and Limitations
Rigid Bodies
Tree attachment structure
Child is known to be a root or atomic body
Re-establishing an attachment that previously existed
Parameters
[in] offset Desired offset from parent struct frame to attached child's struct frame, expressed in parent struct frame
Units: M
[in] T_pstr_cstr Desired transformation matrix from parent struct frame to attached child's struct frame
Definition at line 52 of file mass_reattach.cc.
References jeod::NamedItem::c_str(), composite_properties, composite_wrt_pbdy, composite_wrt_pstr, jeod::MassPointState::compute_transformation(), jeod::MessageHandler::fail(), get_root_body_internal(), jeod::Vector3::incr(), jeod::MassBodyMessages::invalid_node, jeod::TreeLinks< Links, Container, Messages >::is_root(), links, jeod::Quaternion::multiply(), jeod::Quaternion::multiply_conjugate(), name, jeod::TreeLinks< Links, Container, Messages >::parent(), jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, set_update_flag(), structure_point, jeod::MassPointState::T_parent_this, jeod::Vector3::transform_transpose(), update_mass_properties(), jeod::MassPointState::update_orientation(), and jeod::MassPointState::update_point().
Referenced by jeod::BodyReattach::apply().
set_name()
void jeod::MassBody::set_name (std::string name_in) inline
Definition at line 149 of file mass.hh.
References name.
Referenced by jeod::DynBody::set_name().
set_update_flag()
void jeod::MassBody::set_update_flag (void)
Flag mass bodies from the current body on up the mass tree as in need of mass property updates.
Definition at line 331 of file mass.cc.
References links.
Referenced by attach_update_properties(), detach_update_properties(), initialize_mass(), reattach(), and ~MassBody().
update_mass_properties()
void jeod::MassBody::update_mass_properties (void) virtual
Update composite mass properties for a mass tree marked for update.
The properties are updated from the bottom up to generate correct results.
Assumptions and Limitations
Rigid bodies
Tree attachment structure
Definition at line 52 of file mass_update.cc.
References calc_composite_cm(), calc_composite_inertia(), composite_properties, composite_wrt_pbdy, composite_wrt_pstr, compute_inverse_inertia, jeod::Vector3::copy(), jeod::Matrix3x3::copy(), core_properties, core_wrt_composite, jeod::Vector3::diff(), jeod::Vector3::incr(), jeod::MassProperties::inertia, jeod::Vector3::initialize(), jeod::Matrix3x3::initialize(), jeod::MassProperties::inverse_inertia, jeod::MassProperties::inverse_mass, jeod::Matrix3x3::invert_symmetric(), jeod::TreeLinks< Links, Container, Messages >::is_atomic(), jeod::TreeLinks< Links, Container, Messages >::is_root(), links, jeod::MassProperties::mass, needs_update, jeod::MassPointState::position, structure_point, jeod::MassPointState::T_parent_this, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), and update_mass_properties().
Referenced by attach_update_properties(), detach_update_properties(), jeod::DynManager::initialize_dyn_bodies(), jeod::DynManager::initialize_dyn_body(), reattach(), and update_mass_properties().
Friends And Related Function Documentation
DynBody
friend class DynBody friend
Definition at line 118 of file mass.hh.
init_attrjeod__MassBody
void init_attrjeod__MassBody () friend
InputProcessor
friend class InputProcessor friend
Definition at line 115 of file mass.hh.
MassBodyLinks
friend class MassBodyLinks friend
Definition at line 117 of file mass.hh.
Field Documentation
composite_properties
MassProperties jeod::MassBody::composite_properties
The mass properties of this body, including child bodies.
The composite_properties are core_properties are synonymous for atomic bodies. The composite_properties is a child of the structure_point.trick_units(–)
Definition at line 253 of file mass.hh.
Referenced by attach_update_properties(), calc_composite_cm(), calc_composite_inertia(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::DynBody::compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::DynBody::compute_vehicle_point_derivatives(), detach_update_properties(), jeod::DynBody::DynBody(), initialize_mass(), MassBody(), print_body(), jeod::DynBody::process_dynamic_attachment(), jeod::DynBody::propagate_state_from_composite(), jeod::DynBody::propagate_state_from_structure(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), reattach(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::GravityTorque::update(), and update_mass_properties().
composite_wrt_pbdy
MassPoint jeod::MassBody::composite_wrt_pbdy protected
The location and orientation of the composite CoM and body frame with respect to the parent body's composite CoM and body frame.
trick_units(–)
Definition at line 397 of file mass.hh.
Referenced by attach_establish_links(), attach_update_properties(), calc_composite_inertia(), jeod::DynBody::compute_ref_point_transform(), detach_update_properties(), MassBody(), jeod::DynBody::propagate_state_from_composite(), reattach(), and update_mass_properties().
composite_wrt_pstr
MassPoint jeod::MassBody::composite_wrt_pstr protected
The location and orientation of the composite CoM and body frame with respect to the parent body's structural frame.
trick_units(–)
Definition at line 391 of file mass.hh.
Referenced by attach_establish_links(), attach_update_properties(), calc_composite_cm(), jeod::DynBody::collect_forces_and_torques(), detach_update_properties(), reattach(), and update_mass_properties().
compute_inverse_inertia
bool jeod::MassBody::compute_inverse_inertia
When clear, the inverse of the inertia tensor is not calculated.
The inverse of the inertia tensor is only calculated if this flag is set and the composite mass is positive.trick_units(–)
Definition at line 260 of file mass.hh.
Referenced by detach_update_properties(), jeod::DynBody::DynBody(), jeod::DynManager::initialize_dyn_bodies(), and update_mass_properties().
core_properties
MassProperties jeod::MassBody::core_properties
The mass properties of this body alone, excluding child bodies.
The core_properties object is a child of the structure_point.trick_units(–)
Definition at line 246 of file mass.hh.
Referenced by calc_composite_cm(), calc_composite_inertia(), jeod::DynBody::DynBody(), initialize_mass(), MassBody(), print_body(), jeod::DynBody::propagate_state_from_structure(), and update_mass_properties().
core_wrt_composite
MassPoint jeod::MassBody::core_wrt_composite protected
The location and orientation of the composite CoM and body frame with respect to the parent body's composite CoM and body frame.
trick_units(–)
Definition at line 385 of file mass.hh.
Referenced by calc_composite_inertia(), jeod::DynBody::compute_ref_point_transform(), MassBody(), jeod::DynBody::propagate_state_from_composite(), and update_mass_properties().
dyn_manager
BaseDynManager* jeod::MassBody::dyn_manager protected
The dynamics manager for the simulation.
trick_units(–)
Definition at line 349 of file mass.hh.
Referenced by attach_validate_child(), attach_validate_parent(), detach_validate_child(), and detach_validate_parent().
dyn_owner
DynBody* const jeod::MassBody::dyn_owner
Indicates this body belongs to a DynBody.
Many JEOD functions manipulate MassBody properties with the implementation depending/varying upon whether the MassBody refers to a dynamic body.trick_units(–)
Definition at line 276 of file mass.hh.
Referenced by jeod::LineContactFacetFactory::create_facet(), jeod::PointContactFacetFactory::create_facet(), detach(), jeod::DynBody::detach(), jeod::BodyAction::get_subject_dyn_body(), initialize_mass(), jeod::BodyAction::is_subject_dyn_body(), jeod::DynBody::remove_mass_body(), and jeod::BodyAction::validate_body_inputs().
links
MassBodyLinks jeod::MassBody::links protected
Linkage to rest of mass tree.
Programmatic interfaces:
MassBodyLinks provides accessors to the parent and root and provides methods to attach, detach links (and hence bodies).
This class provides accessors to the same.
Various iterators provide the ability to iterate over child bodies and up the parent chain.trick_units(–)
Definition at line 367 of file mass.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::add_mass_body_frames(), attach_establish_links(), attach_root_body(), attach_to(), calc_composite_cm(), calc_composite_inertia(), detach(), jeod::DynBody::detach(), jeod::DynBody::detach_mass_body_frames(), detach_sever_links(), get_parent_body(), get_parent_body_internal(), get_root_body(), get_root_body_internal(), is_progeny_of(), print_body(), reattach(), jeod::DynBody::remove_mass_body(), set_update_flag(), update_mass_properties(), and ~MassBody().
mass_points
std::list<MassPoint*> jeod::MassBody::mass_points protected
List of points associated with this mass body.
NOTE WELL: The MassBody manages the memory associated with the contents of this list.
Definition at line 379 of file mass.hh.
Referenced by jeod::DynBody::add_mass_body_frames(), add_mass_point(), jeod::DynBody::add_mass_point(), jeod::DynBody::detach_mass_body_frames(), find_mass_point(), mass_points_size(), and ~MassBody().
mass_properties_initialized
bool jeod::MassBody::mass_properties_initialized protected
Initialized flag.
Indicates whether the initialize_mass method has been executed, specifically the initialize_mass_properties method from the initialize_mass method.trick_units(–)
Definition at line 356 of file mass.hh.
Referenced by get_mass_properties_initialized(), and initialize_mass().
name
NamedItem jeod::MassBody::name
Body name.
trick_units(–)
Definition at line 240 of file mass.hh.
Referenced by jeod::DynManager::add_mass_body(), jeod::DynBody::add_mass_body(), jeod::DynBody::add_mass_body_validate(), add_mass_point(), jeod::BodyDetach::apply(), jeod::BodyReattach::apply(), jeod::MassBodyInit::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), attach_root_body(), attach_to(), jeod::DynBody::attach_to_frame(), attach_validate_child(), attach_validate_parent(), detach(), detach_validate_child(), detach_validate_parent(), jeod::DynManager::find_mass_body(), find_mass_point(), jeod::DynBodyFrameSwitch::initialize(), jeod::DynBodyInit::initialize(), print_body(), reattach(), jeod::DynBody::remove_mass_body(), set_name(), jeod::SurfaceModel::update_articulation(), and ~MassBody().
needs_update
bool jeod::MassBody::needs_update protected
When set, indicates that an update to the composite mass is needed.
trick_units(–)
Definition at line 372 of file mass.hh.
Referenced by jeod::DynBody::initialize_model(), and update_mass_properties().
structure_point
MassPoint jeod::MassBody::structure_point
The location and orientation of the structural frame with respect to the parent body's structural frame.
Attaching one MassBody to some other MassBody makes the attaching MassBody's structure_point a child of the attachee's structure_point.trick_units(–)
Definition at line 269 of file mass.hh.
Referenced by jeod::DynBody::add_mass_body(), add_mass_point(), jeod::DynBody::attach_child(), attach_establish_links(), attach_to(), attach_update_properties(), jeod::DynBody::collect_forces_and_torques(), jeod::DynBody::compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), detach_update_properties(), jeod::DynBody::DynBody(), MassBody(), print_body(), jeod::DynBody::propagate_state_from_structure(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), reattach(), jeod::SurfaceModel::update_articulation(), and update_mass_properties().
The documentation for this class was generated from the following files:
mass.hh
mass.cc
mass_attach.cc
mass_calc_composite_cm.cc
mass_calc_composite_inertia.cc
mass_detach.cc
mass_point_mass_inertia.cc
mass_print_body.cc
mass_print_tree.cc
mass_reattach.cc
mass_update.cc