JEOD: jeod::PendulumConstraintComponent Class Reference
jeod::PendulumConstraintComponent Class Reference
Models a spherical pendulum as a constrained object, with the constraint force acting at the hinge point.
#include <pendulum_constraint_component.hh>
Public Member Functions
PendulumConstraintComponent (ConstraintFrame *constraint_frame_in=nullptr, ConstrainedPointMass *constrained_mass_in=nullptr, BasePendulumModel *pendulum_model_in=nullptr)
Default constructor.
~PendulumConstraintComponent () override=default
Destructor.
void create_integrators (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls, const er7_utils::TimeInterface &) override
Create the integrator that integrates the pendulum bob state.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage) override
Advance bob state by the specified dynamic time interval.
void reset_integrators () override
Reset the integrator that integrates the pendulum bob state.
void destroy_integrators () override
Destroy the integrator that integrates the pendulum bob state.
void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state) override
Prepare this object for solving a constraint problem.
void compute_constraint_response (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state) override
Compute the response of the constrained object to the overall behavior of the vehicle.
void attach_to_solver (DynBodyConstraintsSolver *solver, DynBody *dyn_body_in) override
Add this object as an integrator for the DynBody associated with the constraints solver associated with the parent of this component.
void detach_from_solver (DynBodyConstraintsSolver *solver, DynBody *dyn_body_in) override
Remove this object as an integrator for the DynBody associated with the constraints solver associated with the parent of this component.
virtual void activate ()
Activate the constraint.
virtual void deactivate ()
Deactivate the constraint.
virtual const Wrench & get_effector_wrench () const
Get the known wrench for this constrained object.
virtual const Wrench & get_nonlinear_response_wrench () const
Get the residual nonlinear wrench for this constrained object.
bool check_for_reset ()
Determine whether the integrator needs to be reset, which occurs on transition between modes.
void reset_quiescent ()
Trigger that the pendulum should be set to its quiescent vertical state,.
void set_transition_points (double new_cos_sq_theta_angular, double new_cos_sq_theta_cartesian)
Set the points at which the transitions from Cartesian to angular and angular to Cartesian representations occur.
const double * get_bob_position () const
Getter for the bob position.
Public Member Functions inherited from jeod::ForceConstraintComponent
ForceConstraintComponent (ConstraintFrame *constraint_frame_in=nullptr, ConstrainedPointMass *constrained_mass_in=nullptr)
Default constructor.
~ForceConstraintComponent () override=default
Destructor.
ForceConstraintComponent (const ForceConstraintComponent &)=default
ForceConstraintComponent (ForceConstraintComponent &&)=default
ForceConstraintComponent & operator= (const ForceConstraintComponent &)=default
ForceConstraintComponent & operator= (ForceConstraintComponent &&)=default
double get_cross_coeff (const VehicleProperties &vehicle_properties, const ConstraintComponent &other) const override
Computes the coefficient of the solver A matrix that represents the interaction of some other constrained object and this constrained object.
SolverTypes::DecayedVector3T get_translational_response (const VehicleProperties &vehicle_properties, SolverTypes::ConstVector3T point, SolverTypes::Vector3T response) const override
Get the translational response by the vehicle to this constraint at a specified point in root body structural coordinates.
void set_constraint_value (double constraint_value) override
Set this constrained object's scalar constraint value.
Public Member Functions inherited from jeod::ConstraintComponent
ConstraintComponent (ConstraintFrame *constraint_frame_in=nullptr)
Default constructor.
virtual ~ConstraintComponent ()=default
Destructor.
ConstraintComponent (const ConstraintComponent &)=default
ConstraintComponent & operator= (const ConstraintComponent &)=default
ConstraintComponent (ConstraintComponent &&)=default
ConstraintComponent & operator= (ConstraintComponent &&)=default
virtual void update_attachment (const VehicleProperties &)
Update information about the relation between this constraint and the root DynBody.
void set_constraint_direction (SolverTypes::ConstVector3T constraint_direction)
Set the direction in which the constraint acts on the vehicle.
void compute_root_direction ()
Compute the constraint direction in root structural coordinates.
virtual SolverTypes::ConstDecayedVector3T get_rotational_response (const VehicleProperties &vehicle_properties) const
Get the vehicle's unit rotational response to this constraint.
virtual SolverTypes::DecayedVector3T get_rotational_response (const VehicleProperties &vehicle_properties, SolverTypes::Vector3T response) const
Get the vehicle's unit rotational response to this constraint.
virtual void set_right_hand_side (double rhs_value)
Set the right hand side of the constraint equation for this constraint.
virtual double get_right_hand_side () const
Get the right hand side of the constraint equation for this constraint.
virtual double get_self_coeff (const VehicleProperties &vehicle_properties) const
Computes the coefficient of the solver A matrix that represents the interaction of this constrained object with itself.
virtual const Wrench & get_constraint_wrench () const
Get the wrench this constrained object exerts on the vehicle.
Protected Member Functions
void set_pendulum_length (double new_length)
Set the length of the pendulum.
Protected Member Functions inherited from jeod::ConstraintComponent
void compute_rotational_response (const VehicleProperties &vehicle_properties, const double torque[3])
Compute the vehicle's rotational response to a torque.
Protected Attributes
BasePendulumModel * pendulum_model
The object that provides pendulum parameters.
DynBody * dyn_body {}
The DynBody object on which this pendulum acts.
Restartable2DSecondOrderIntegrator bob_integrator
Bob state checkpointable/restartable integrator generator.
er7_utils::IntegratorResultMergerContainer integ_results_merger
The object that merges integration results.
double cos_sq_theta_angular {0.45}
Value of cos(theta)^2 below which the model switchs from cartesian to angular integration.
double cos_sq_theta_cartesian {0.55}
Value of cos(theta)^2 above which the model switchs from angular to cartesian integration.
double pendulum_length {}
The pendulum length; vmag(bob_position).
double bob_position [3] {}
The pendulum bob position, in tank coordinates.
double bob_velocity [3] {}
Time derivative of the pendulum bob position, in tank coordinates.
double bob_accel [3] {}
Second time derivative of the pendulum bob position, in tank coordinates.
double theta {}
Polar bob angle.
double phi {}
Azimuthal bob angle.
double theta_dot {}
Time derivative of theta.
double phi_dot {}
Time derivative of phi.
double theta_dot_dot {}
Second time derivative of theta.
double phi_dot_dot {}
Second time derivative of phi.
double sin_theta {}
sin(theta).
double cos_theta {}
cos(theta).
double sin_phi {}
sin(phi).
double cos_phi {}
cos(phi).
double cos_sq_theta {}
cos^2(theta).
double constraint_to_spherical_transform [3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } }
Local spherical transformation matrix.
double omega_constraint_frame [3] {}
Vehicle angular velocity expressed in the constraint frame.
double omega_dot_constraint_frame [3] {}
Vehicle angular acceleration expressed in the constraint frame.
double omega_cross_pos [3] {}
Cross product of angular velocity and bob position.
double omega_cross_vel [3] {}
Cross product of angular velocity and bob velocity.
double rho_hat_dot [3] {}
Time derivative of the bob direction unit vector.
Wrench null_wrench {true}
A wrench that is always zero and inactive.
Wrench damping_wrench
The damping torque as a wrench, which is hopefully small.
PendulumConstraintMode mode
The mode in which the pendulum's state is integrated.
PendulumConstraintMode new_mode
The mode to which the model is to transition.
Protected Attributes inherited from jeod::ForceConstraintComponent
ConstrainedPointMass * constrained_mass
The constrained mass, as a point mass, for this component.
double constraint_com_accel_root [3] {}
The contribution of this constraint to the translational acceleration of the root body center of mass, in root structural components.
double constraint_force {}
The unitless constraint value.
Protected Attributes inherited from jeod::ConstraintComponent
ConstraintFrame * constraint_frame
The reference frame associated with this constraint.
Wrench constraint_wrench
The indeterminate part of the wrench due to this constraint.
double constraint_direction_constraint_frame [3] {}
The direction in which the constraint acts on the vehicle, in constraint frame coordinates.
double constraint_direction_root [3] {}
The direction in which the constraint acts on the vehicle, in root body structural coordinates.
double constraint_omega_dot_root [3] {}
The contribution of this constraint to the rotational acceleration of the root body, in root structural components.
double right_hand_side {}
The right hand side of the constraint equation pertaining to this constraint.
Private Member Functions
void transition_to_horizontal ()
Compute bob angles in preparation for integrating in horizontal mode.
void construct_constraint_to_spherical_transform ()
Construct the transformation matrix from the constraint frame to the local spherical frame.
void compute_rho_hat_dot ()
Compute the time derivative of the unit vector in the direction of the pendulum bob.
void compute_bob_state_spherical ()
Compute the bob position and velocity given its spherical coordinates.
void compute_bob_state_cartesian ()
Compute the bob z position and velocity given its x and y position and velocity.
virtual er7_utils::IntegratorResult integrate_spherical (double dyn_dt, unsigned int target_stage)
Integrate spherical state by the specified dynamic time interval.
virtual er7_utils::IntegratorResult integrate_cartesian (double dyn_dt, unsigned int target_stage)
Integrate Cartesian state by the specified dynamic time interval.
Friends
class InputProcessor
void init_attrjeod__PendulumConstraintComponent ()
Detailed Description
Models a spherical pendulum as a constrained object, with the constraint force acting at the hinge point.
Definition at line 84 of file pendulum_constraint_component.hh.
Constructor & Destructor Documentation
PendulumConstraintComponent()
jeod::PendulumConstraintComponent::PendulumConstraintComponent (ConstraintFrame * constraint_frame_in = nullptr, ConstrainedPointMass * constrained_mass_in = nullptr, BasePendulumModel * pendulum_model_in = nullptr)
Default constructor.
Definition at line 37 of file pendulum_constraint_component.cc.
References jeod::Inactive.
~PendulumConstraintComponent()
jeod::PendulumConstraintComponent::~PendulumConstraintComponent () override default
Destructor.
Member Function Documentation
activate()
void jeod::PendulumConstraintComponent::activate () virtual
Activate the constraint.
Definition at line 115 of file pendulum_constraint_component.cc.
References bob_position, bob_velocity, cos_sq_theta, cos_theta, jeod::Vector3::initialize(), mode, new_mode, and jeod::Vertical.
Referenced by jeod::DynBodyPendulumConstraint::activate().
attach_to_solver()
void jeod::PendulumConstraintComponent::attach_to_solver (DynBodyConstraintsSolver * solver, DynBody * dyn_body_in) override virtual
Add this object as an integrator for the DynBody associated with the constraints solver associated with the parent of this component.
Reimplemented from jeod::ForceConstraintComponent.
Definition at line 100 of file pendulum_constraint_component.cc.
References jeod::DynBody::add_integrable_object(), and dyn_body.
check_for_reset()
bool jeod::PendulumConstraintComponent::check_for_reset ()
Determine whether the integrator needs to be reset, which occurs on transition between modes.
This should be called as a scheduled job at the dynamics rate.
Definition at line 129 of file pendulum_constraint_component.cc.
References bob_position, cos_sq_theta, cos_sq_theta_angular, cos_sq_theta_cartesian, jeod::Horizontal, jeod::Inverted, mode, new_mode, jeod::Reset, and jeod::Vertical.
Referenced by jeod::DynBodyPendulumConstraint::check_for_reset().
compute_bob_state_cartesian()
void jeod::PendulumConstraintComponent::compute_bob_state_cartesian () private
Compute the bob z position and velocity given its x and y position and velocity.
Definition at line 307 of file pendulum_constraint_component.cc.
References bob_position, bob_velocity, cos_sq_theta, cos_theta, jeod::Inverted, mode, pendulum_length, jeod::Vector3::scale(), and jeod::ConstraintComponent::set_constraint_direction().
Referenced by integrate_cartesian(), reset_integrators(), and set_pendulum_length().
compute_bob_state_spherical()
void jeod::PendulumConstraintComponent::compute_bob_state_spherical () private
Compute the bob position and velocity given its spherical coordinates.
Definition at line 299 of file pendulum_constraint_component.cc.
References bob_position, bob_velocity, constraint_to_spherical_transform, pendulum_length, rho_hat_dot, jeod::Vector3::scale(), and jeod::ConstraintComponent::set_constraint_direction().
Referenced by integrate_spherical(), and set_pendulum_length().
compute_constraint_response()
void jeod::PendulumConstraintComponent::compute_constraint_response (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) override virtual
Compute the response of the constrained object to the overall behavior of the vehicle.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to external forces and torques, including the constraints.
Reimplemented from jeod::ForceConstraintComponent.
Definition at line 333 of file pendulum_constraint_component.cc.
References bob_accel, bob_position, bob_velocity, jeod::BasePendulumModel::compute_damping_factor(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::ForceConstraintComponent::constrained_mass, jeod::ForceConstraintComponent::constraint_force, jeod::ConstraintComponent::constraint_frame, constraint_to_spherical_transform, cos_theta, jeod::Vector3::cross(), damping_wrench, jeod::Vector3::dot(), jeod::Horizontal, jeod::ConstrainedPointMass::mass, mode, jeod::ConstrainedPointMass::non_grav_accel_constraint_frame, jeod::ConstrainedPointMass::non_grav_accel_root, omega_constraint_frame, omega_cross_pos, omega_cross_vel, omega_dot_constraint_frame, jeod::VehicleNonGravState::omega_dot_struct, jeod::VehicleNonGravState::omega_struct, pendulum_length, pendulum_model, phi_dot, phi_dot_dot, jeod::Vector3::scale(), jeod::Wrench::set_torque(), sin_theta, jeod::ConstraintFrame::T_root_constraint, theta_dot, theta_dot_dot, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), and jeod::Vector3::vmag().
compute_rho_hat_dot()
void jeod::PendulumConstraintComponent::compute_rho_hat_dot () private
Compute the time derivative of the unit vector in the direction of the pendulum bob.
Definition at line 290 of file pendulum_constraint_component.cc.
References constraint_to_spherical_transform, phi_dot, rho_hat_dot, sin_theta, and theta_dot.
Referenced by integrate_spherical(), and transition_to_horizontal().
construct_constraint_to_spherical_transform()
void jeod::PendulumConstraintComponent::construct_constraint_to_spherical_transform () private
Construct the transformation matrix from the constraint frame to the local spherical frame.
Definition at line 240 of file pendulum_constraint_component.cc.
References constraint_to_spherical_transform, cos_phi, cos_theta, sin_phi, and sin_theta.
Referenced by integrate_spherical(), and transition_to_horizontal().
create_integrators()
void jeod::PendulumConstraintComponent::create_integrators (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls, const er7_utils::TimeInterface &) override
Create the integrator that integrates the pendulum bob state.
Parameters
generator Integrator constructor to be used to create state integrators.
controls The integration controls created the integrator constructor's create_integration_controls method.
Definition at line 51 of file pendulum_constraint_component.cc.
References bob_integrator, jeod::Restartable2DSecondOrderIntegrator::create_integrator(), dyn_body, FAIL_SIMULATION, and integ_results_merger.
deactivate()
void jeod::PendulumConstraintComponent::deactivate () virtual
Deactivate the constraint.
Definition at line 124 of file pendulum_constraint_component.cc.
References jeod::Inactive, and mode.
Referenced by jeod::DynBodyPendulumConstraint::deactivate().
destroy_integrators()
void jeod::PendulumConstraintComponent::destroy_integrators () inline override
Destroy the integrator that integrates the pendulum bob state.
Definition at line 131 of file pendulum_constraint_component.hh.
References bob_integrator, and jeod::Restartable2DSecondOrderIntegrator::destroy_integrator().
detach_from_solver()
void jeod::PendulumConstraintComponent::detach_from_solver (DynBodyConstraintsSolver * solver, DynBody * dyn_body_in) override virtual
Remove this object as an integrator for the DynBody associated with the constraints solver associated with the parent of this component.
Reimplemented from jeod::ForceConstraintComponent.
Definition at line 106 of file pendulum_constraint_component.cc.
References dyn_body, and jeod::DynBody::remove_integrable_object().
get_bob_position()
const double* jeod::PendulumConstraintComponent::get_bob_position () const inline
Getter for the bob position.
Definition at line 232 of file pendulum_constraint_component.hh.
References bob_position.
Referenced by jeod::DynBodyPendulumConstraint::get_bob_position().
get_effector_wrench()
virtual const Wrench& jeod::PendulumConstraintComponent::get_effector_wrench () const inline virtual
Get the known wrench for this constrained object.
In this case, there is none.
Returns
A null wrench.
Definition at line 185 of file pendulum_constraint_component.hh.
References null_wrench.
Referenced by jeod::DynBodyPendulumConstraint::get_effector_wrench().
get_nonlinear_response_wrench()
virtual const Wrench& jeod::PendulumConstraintComponent::get_nonlinear_response_wrench () const inline virtual
Get the residual nonlinear wrench for this constrained object.
Returns
A const reference to the nonlinear wrench for this object.
Definition at line 194 of file pendulum_constraint_component.hh.
References damping_wrench.
Referenced by jeod::DynBodyPendulumConstraint::get_nonlinear_response_wrench().
integrate()
er7_utils::IntegratorResult jeod::PendulumConstraintComponent::integrate (double dyn_dt, unsigned int target_stage) override
Advance bob state by the specified dynamic time interval.
Parameters
dyn_dt Dynamic time step, in dynamic time seconds.
target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status of the integration step.
Definition at line 222 of file pendulum_constraint_component.cc.
References jeod::Horizontal, jeod::Inactive, integrate_cartesian(), integrate_spherical(), and mode.
integrate_cartesian()
er7_utils::IntegratorResult jeod::PendulumConstraintComponent::integrate_cartesian (double dyn_dt, unsigned int target_stage) private virtual
Integrate Cartesian state by the specified dynamic time interval.
Parameters
dyn_dt Dynamic time step, in dynamic time seconds.
target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status of the integration step.
Definition at line 275 of file pendulum_constraint_component.cc.
References bob_accel, bob_integrator, bob_position, bob_velocity, compute_bob_state_cartesian(), cos_sq_theta, cos_theta, jeod::Restartable2DSecondOrderIntegrator::integrate(), and pendulum_length.
Referenced by integrate().
integrate_spherical()
er7_utils::IntegratorResult jeod::PendulumConstraintComponent::integrate_spherical (double dyn_dt, unsigned int target_stage) private virtual
Integrate spherical state by the specified dynamic time interval.
Parameters
dyn_dt Dynamic time step, in dynamic time seconds.
target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status of the integration step.
Definition at line 253 of file pendulum_constraint_component.cc.
References bob_integrator, compute_bob_state_spherical(), compute_rho_hat_dot(), construct_constraint_to_spherical_transform(), cos_phi, cos_sq_theta, cos_theta, jeod::Restartable2DSecondOrderIntegrator::integrate(), phi, sin_phi, sin_theta, theta, theta_dot, and theta_dot_dot.
Referenced by integrate().
reset_integrators()
void jeod::PendulumConstraintComponent::reset_integrators () override
Reset the integrator that integrates the pendulum bob state.
Definition at line 73 of file pendulum_constraint_component.cc.
References bob_accel, bob_integrator, bob_position, bob_velocity, compute_bob_state_cartesian(), jeod::ForceConstraintComponent::constrained_mass, jeod::ConstrainedPointMass::constraint_position_constraint_frame, jeod::BasePendulumModel::get_hinge_point(), jeod::BasePendulumModel::get_pendulum_length(), jeod::BasePendulumModel::get_pendulum_mass(), jeod::Horizontal, jeod::Vector3::initialize(), jeod::ConstrainedPointMass::mass, mode, new_mode, pendulum_model, jeod::Reset, jeod::Restartable2DSecondOrderIntegrator::reset_integrator(), set_pendulum_length(), transition_to_horizontal(), jeod::BasePendulumModel::update_pendulum_model(), and jeod::Vertical.
reset_quiescent()
void jeod::PendulumConstraintComponent::reset_quiescent () inline
Trigger that the pendulum should be set to its quiescent vertical state,.
Definition at line 211 of file pendulum_constraint_component.hh.
References jeod::Inactive, mode, new_mode, and jeod::Reset.
Referenced by jeod::DynBodyPendulumConstraint::reset_quiescent().
set_pendulum_length()
void jeod::PendulumConstraintComponent::set_pendulum_length (double new_length) protected
Set the length of the pendulum.
Parameters
new_length New pendulum length.
Definition at line 184 of file pendulum_constraint_component.cc.
References jeod::Numerical::compare_exact(), compute_bob_state_cartesian(), compute_bob_state_spherical(), jeod::Horizontal, mode, and pendulum_length.
Referenced by reset_integrators(), and setup_constraint().
set_transition_points()
void jeod::PendulumConstraintComponent::set_transition_points (double new_cos_sq_theta_angular, double new_cos_sq_theta_cartesian) inline
Set the points at which the transitions from Cartesian to angular and angular to Cartesian representations occur.
Definition at line 223 of file pendulum_constraint_component.hh.
References cos_sq_theta_angular, and cos_sq_theta_cartesian.
Referenced by jeod::DynBodyPendulumConstraint::set_transition_points().
setup_constraint()
void jeod::PendulumConstraintComponent::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) override virtual
Prepare this object for solving a constraint problem.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to non-constraint forces and torques, including the pre-constraint wrenches.
Reimplemented from jeod::ForceConstraintComponent.
Definition at line 200 of file pendulum_constraint_component.cc.
References bob_position, bob_velocity, jeod::ForceConstraintComponent::constrained_mass, jeod::ConstraintComponent::constraint_direction_constraint_frame, jeod::ConstraintComponent::constraint_frame, jeod::ConstrainedPointMass::constraint_position_constraint_frame, jeod::Vector3::cross(), jeod::Vector3::dot(), jeod::ConstrainedPointMass::force_constraint_frame, jeod::BasePendulumModel::get_hinge_point(), jeod::BasePendulumModel::get_pendulum_length(), jeod::BasePendulumModel::get_pendulum_mass(), jeod::ConstrainedPointMass::mass, omega_constraint_frame, omega_cross_pos, omega_cross_vel, jeod::VehicleNonGravState::omega_struct, pendulum_length, pendulum_model, jeod::ConstraintComponent::right_hand_side, set_pendulum_length(), jeod::ForceConstraintComponent::setup_constraint(), jeod::ConstrainedPointMass::setup_constraint(), jeod::ConstraintFrame::T_root_constraint, jeod::Vector3::transform(), and jeod::Vector3::vmagsq().
Referenced by jeod::DynBodyPendulumConstraint::setup_constraint().
transition_to_horizontal()
void jeod::PendulumConstraintComponent::transition_to_horizontal () private
Compute bob angles in preparation for integrating in horizontal mode.
Definition at line 168 of file pendulum_constraint_component.cc.
References bob_position, bob_velocity, compute_rho_hat_dot(), constraint_to_spherical_transform, construct_constraint_to_spherical_transform(), cos_phi, cos_theta, jeod::Vector3::dot(), pendulum_length, phi, phi_dot, sin_phi, sin_theta, theta, and theta_dot.
Referenced by reset_integrators().
Friends And Related Function Documentation
init_attrjeod__PendulumConstraintComponent
void init_attrjeod__PendulumConstraintComponent () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file pendulum_constraint_component.hh.
Field Documentation
bob_accel
double jeod::PendulumConstraintComponent::bob_accel[3] {} protected
Second time derivative of the pendulum bob position, in tank coordinates.
Note: Size is three even though only x and y are integrated. The z accel is not computed.trick_units(m/s^2)
Definition at line 292 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), integrate_cartesian(), and reset_integrators().
bob_integrator
Restartable2DSecondOrderIntegrator jeod::PendulumConstraintComponent::bob_integrator protected
Bob state checkpointable/restartable integrator generator.
trick_units(–)
Definition at line 253 of file pendulum_constraint_component.hh.
Referenced by create_integrators(), destroy_integrators(), integrate_cartesian(), integrate_spherical(), and reset_integrators().
bob_position
double jeod::PendulumConstraintComponent::bob_position[3] {} protected
The pendulum bob position, in tank coordinates.
trick_units(m)
Definition at line 280 of file pendulum_constraint_component.hh.
Referenced by activate(), check_for_reset(), compute_bob_state_cartesian(), compute_bob_state_spherical(), compute_constraint_response(), get_bob_position(), integrate_cartesian(), reset_integrators(), setup_constraint(), and transition_to_horizontal().
bob_velocity
double jeod::PendulumConstraintComponent::bob_velocity[3] {} protected
Time derivative of the pendulum bob position, in tank coordinates.
trick_units(m/s)
Definition at line 285 of file pendulum_constraint_component.hh.
Referenced by activate(), compute_bob_state_cartesian(), compute_bob_state_spherical(), compute_constraint_response(), integrate_cartesian(), reset_integrators(), setup_constraint(), and transition_to_horizontal().
constraint_to_spherical_transform
double jeod::PendulumConstraintComponent::constraint_to_spherical_transform[3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } } protected
Local spherical transformation matrix.
trick_units(–)
Definition at line 352 of file pendulum_constraint_component.hh.
Referenced by compute_bob_state_spherical(), compute_constraint_response(), compute_rho_hat_dot(), construct_constraint_to_spherical_transform(), and transition_to_horizontal().
cos_phi
double jeod::PendulumConstraintComponent::cos_phi {} protected
cos(phi).
trick_units(–)
Definition at line 342 of file pendulum_constraint_component.hh.
Referenced by construct_constraint_to_spherical_transform(), integrate_spherical(), and transition_to_horizontal().
cos_sq_theta
double jeod::PendulumConstraintComponent::cos_sq_theta {} protected
cos^2(theta).
trick_units(–)
Definition at line 347 of file pendulum_constraint_component.hh.
Referenced by activate(), check_for_reset(), compute_bob_state_cartesian(), integrate_cartesian(), and integrate_spherical().
cos_sq_theta_angular
double jeod::PendulumConstraintComponent::cos_sq_theta_angular {0.45} protected
Value of cos(theta)^2 below which the model switchs from cartesian to angular integration.
trick_units(–)
Definition at line 264 of file pendulum_constraint_component.hh.
Referenced by check_for_reset(), and set_transition_points().
cos_sq_theta_cartesian
double jeod::PendulumConstraintComponent::cos_sq_theta_cartesian {0.55} protected
Value of cos(theta)^2 above which the model switchs from angular to cartesian integration.
trick_units(–)
Definition at line 270 of file pendulum_constraint_component.hh.
Referenced by check_for_reset(), and set_transition_points().
cos_theta
double jeod::PendulumConstraintComponent::cos_theta {} protected
cos(theta).
trick_units(–)
Definition at line 332 of file pendulum_constraint_component.hh.
Referenced by activate(), compute_bob_state_cartesian(), compute_constraint_response(), construct_constraint_to_spherical_transform(), integrate_cartesian(), integrate_spherical(), and transition_to_horizontal().
damping_wrench
Wrench jeod::PendulumConstraintComponent::damping_wrench protected
The damping torque as a wrench, which is hopefully small.
trick_units(–)
Definition at line 387 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), and get_nonlinear_response_wrench().
dyn_body
DynBody* jeod::PendulumConstraintComponent::dyn_body {} protected
The DynBody object on which this pendulum acts.
trick_units(–)
Definition at line 248 of file pendulum_constraint_component.hh.
Referenced by attach_to_solver(), create_integrators(), and detach_from_solver().
integ_results_merger
er7_utils::IntegratorResultMergerContainer jeod::PendulumConstraintComponent::integ_results_merger protected
The object that merges integration results.
trick_units(–)
Definition at line 258 of file pendulum_constraint_component.hh.
Referenced by create_integrators().
mode
PendulumConstraintMode jeod::PendulumConstraintComponent::mode protected
The mode in which the pendulum's state is integrated.
trick_units(–)
Definition at line 392 of file pendulum_constraint_component.hh.
Referenced by activate(), check_for_reset(), compute_bob_state_cartesian(), compute_constraint_response(), deactivate(), integrate(), reset_integrators(), reset_quiescent(), and set_pendulum_length().
new_mode
PendulumConstraintMode jeod::PendulumConstraintComponent::new_mode protected
The mode to which the model is to transition.
trick_units(–)
Definition at line 397 of file pendulum_constraint_component.hh.
Referenced by activate(), check_for_reset(), reset_integrators(), and reset_quiescent().
null_wrench
Wrench jeod::PendulumConstraintComponent::null_wrench {true} protected
A wrench that is always zero and inactive.
trick_units(–)
Definition at line 382 of file pendulum_constraint_component.hh.
Referenced by get_effector_wrench().
omega_constraint_frame
double jeod::PendulumConstraintComponent::omega_constraint_frame[3] {} protected
Vehicle angular velocity expressed in the constraint frame.
trick_units(rad/s)
Definition at line 357 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), and setup_constraint().
omega_cross_pos
double jeod::PendulumConstraintComponent::omega_cross_pos[3] {} protected
Cross product of angular velocity and bob position.
trick_units(rad*m/s)
Definition at line 367 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), and setup_constraint().
omega_cross_vel
double jeod::PendulumConstraintComponent::omega_cross_vel[3] {} protected
Cross product of angular velocity and bob velocity.
trick_units(rad*m/s^2)
Definition at line 372 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), and setup_constraint().
omega_dot_constraint_frame
double jeod::PendulumConstraintComponent::omega_dot_constraint_frame[3] {} protected
Vehicle angular acceleration expressed in the constraint frame.
trick_units(rad/s^2)
Definition at line 362 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response().
pendulum_length
double jeod::PendulumConstraintComponent::pendulum_length {} protected
The pendulum length; vmag(bob_position).
trick_units(m)
Definition at line 275 of file pendulum_constraint_component.hh.
Referenced by compute_bob_state_cartesian(), compute_bob_state_spherical(), compute_constraint_response(), integrate_cartesian(), set_pendulum_length(), setup_constraint(), and transition_to_horizontal().
pendulum_model
BasePendulumModel* jeod::PendulumConstraintComponent::pendulum_model protected
The object that provides pendulum parameters.
trick_units(–)
Definition at line 243 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), reset_integrators(), and setup_constraint().
phi
double jeod::PendulumConstraintComponent::phi {} protected
Azimuthal bob angle.
trick_units(rad)
Definition at line 302 of file pendulum_constraint_component.hh.
Referenced by integrate_spherical(), and transition_to_horizontal().
phi_dot
double jeod::PendulumConstraintComponent::phi_dot {} protected
Time derivative of phi.
trick_units(rad/s)
Definition at line 312 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), compute_rho_hat_dot(), and transition_to_horizontal().
phi_dot_dot
double jeod::PendulumConstraintComponent::phi_dot_dot {} protected
Second time derivative of phi.
trick_units(rad/s^2)
Definition at line 322 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response().
rho_hat_dot
double jeod::PendulumConstraintComponent::rho_hat_dot[3] {} protected
Time derivative of the bob direction unit vector.
trick_units(1/s)
Definition at line 377 of file pendulum_constraint_component.hh.
Referenced by compute_bob_state_spherical(), and compute_rho_hat_dot().
sin_phi
double jeod::PendulumConstraintComponent::sin_phi {} protected
sin(phi).
trick_units(–)
Definition at line 337 of file pendulum_constraint_component.hh.
Referenced by construct_constraint_to_spherical_transform(), integrate_spherical(), and transition_to_horizontal().
sin_theta
double jeod::PendulumConstraintComponent::sin_theta {} protected
sin(theta).
trick_units(–)
Definition at line 327 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), compute_rho_hat_dot(), construct_constraint_to_spherical_transform(), integrate_spherical(), and transition_to_horizontal().
theta
double jeod::PendulumConstraintComponent::theta {} protected
Polar bob angle.
trick_units(rad)
Definition at line 297 of file pendulum_constraint_component.hh.
Referenced by integrate_spherical(), and transition_to_horizontal().
theta_dot
double jeod::PendulumConstraintComponent::theta_dot {} protected
Time derivative of theta.
trick_units(rad/s)
Definition at line 307 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), compute_rho_hat_dot(), integrate_spherical(), and transition_to_horizontal().
theta_dot_dot
double jeod::PendulumConstraintComponent::theta_dot_dot {} protected
Second time derivative of theta.
trick_units(rad/s^2)
Definition at line 317 of file pendulum_constraint_component.hh.
Referenced by compute_constraint_response(), and integrate_spherical().
The documentation for this class was generated from the following files:
pendulum_constraint_component.hh
pendulum_constraint_component.cc