JEOD: jeod::GaussJacksonCoefficientsPair Class Reference
jeod::GaussJacksonCoefficientsPair Class Reference
Contains a summed Adams and Gauss-Jackson coefficient pair.
#include <gauss_jackson_coefficients_pair.hh>
Public Member Functions
GaussJacksonCoefficientsPair ()
Default constructor.
~GaussJacksonCoefficientsPair ()
Destructor.
void configure (int max_order)
Allocate (re-allocate) memory for the coefficients.
void swap (GaussJacksonCoefficientsPair &other)
Non-throwing swap.
void allocate_arrays (int size)
Allocate space for the coefficients.
void deallocate_arrays ()
Release allocated memory.
void apply (int nelem, int ncoeff, double const *const *acc_hist, const GaussJacksonTwoState &state_sum) const
Apply both sets of coefficients to the supplied history data.
void apply (int nelem, int ncoeff, double const *const *acc_hist, const GaussJacksonOneState &state_sum) const
Apply just the Adams coefficients to the supplied history data.
void print (int order, std::ostream &stream) const
Print the coefficients.
Data Fields
double * sa_coefs
Summed Adams coefficients, in ordinate form.
double * gj_coefs
Gauss Jackson coefficients, in ordinate form.
Private Member Functions
GaussJacksonCoefficientsPair (const GaussJacksonCoefficientsPair &)
Not implemented.
GaussJacksonCoefficientsPair & operator= (const GaussJacksonCoefficientsPair &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__GaussJacksonCoefficientsPair ()
Detailed Description
Contains a summed Adams and Gauss-Jackson coefficient pair.
Definition at line 85 of file gauss_jackson_coefficients_pair.hh.
Constructor & Destructor Documentation
GaussJacksonCoefficientsPair() [1/2]
jeod::GaussJacksonCoefficientsPair::GaussJacksonCoefficientsPair () inline
Default constructor.
Definition at line 109 of file gauss_jackson_coefficients_pair.hh.
~GaussJacksonCoefficientsPair()
jeod::GaussJacksonCoefficientsPair::~GaussJacksonCoefficientsPair () inline
Destructor.
Definition at line 118 of file gauss_jackson_coefficients_pair.hh.
References deallocate_arrays().
GaussJacksonCoefficientsPair() [2/2]
jeod::GaussJacksonCoefficientsPair::GaussJacksonCoefficientsPair (const GaussJacksonCoefficientsPair &) private
Not implemented.
Member Function Documentation
allocate_arrays()
void jeod::GaussJacksonCoefficientsPair::allocate_arrays (int size)
Allocate space for the coefficients.
Parameters
size Array size.
Definition at line 37 of file gauss_jackson_coefficients_pair.cc.
References gj_coefs, and sa_coefs.
Referenced by configure().
apply() [1/2]
void jeod::GaussJacksonCoefficientsPair::apply (int nelem, int ncoeff, double const *const * acc_hist, const GaussJacksonTwoState & state_sum) const
Apply both sets of coefficients to the supplied history data.
The first element of the output state_sum is calculated as the inner products of the acceleration history with the summed Adams coefficients. The second element is calculated as the inner product with the Gauss-Jackson coefficients. (First = first integral; second = second integral.)
Parameters
nelem Dimensionality of each acceleration history element
ncoeff Number of elements in the acceleration history
acc_hist Acceleration history
state_sum Output inner products
Definition at line 63 of file gauss_jackson_coefficients_pair.cc.
References ER7_UTILS_RESTRICT.
Referenced by jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj().
apply() [2/2]
void jeod::GaussJacksonCoefficientsPair::apply (int nelem, int ncoeff, double const *const * acc_hist, const GaussJacksonOneState & state_sum) const
Apply just the Adams coefficients to the supplied history data.
Parameters
nelem Dimensionality of each acceleration history element
ncoeff Number of elements in the acceleration history
acc_hist Acceleration history
state_sum Output inner products
Definition at line 96 of file gauss_jackson_coefficients_pair.cc.
References ER7_UTILS_RESTRICT.
configure()
void jeod::GaussJacksonCoefficientsPair::configure (int max_order) inline
Allocate (re-allocate) memory for the coefficients.
Arrays are size & to contain max_order+1 elements.
Parameters
max_order Maximum order that will be used.
Definition at line 128 of file gauss_jackson_coefficients_pair.hh.
References allocate_arrays(), and deallocate_arrays().
Referenced by jeod::GaussJacksonCoeffs::configure().
deallocate_arrays()
void jeod::GaussJacksonCoefficientsPair::deallocate_arrays ()
Release allocated memory.
Definition at line 46 of file gauss_jackson_coefficients_pair.cc.
References gj_coefs, and sa_coefs.
Referenced by configure(), and ~GaussJacksonCoefficientsPair().
operator=()
GaussJacksonCoefficientsPair& jeod::GaussJacksonCoefficientsPair::operator= (const GaussJacksonCoefficientsPair &) private
Not implemented.
print()
void jeod::GaussJacksonCoefficientsPair::print (int order, std::ostream & stream) const
Print the coefficients.
Parameters
order Coefficients order
stream Output stream
Definition at line 123 of file gauss_jackson_coefficients_pair.cc.
References gj_coefs, and sa_coefs.
Referenced by jeod::operator<<().
swap()
void jeod::GaussJacksonCoefficientsPair::swap (GaussJacksonCoefficientsPair & other)
Non-throwing swap.
Parameters
other Coeffs pair with which contents are to be swapped.
Definition at line 54 of file gauss_jackson_coefficients_pair.cc.
References gj_coefs, and sa_coefs.
Referenced by jeod::GaussJacksonCoeffs::swap().
Friends And Related Function Documentation
init_attrjeod__GaussJacksonCoefficientsPair
void init_attrjeod__GaussJacksonCoefficientsPair () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file gauss_jackson_coefficients_pair.hh.
Field Documentation
gj_coefs
double* jeod::GaussJacksonCoefficientsPair::gj_coefs
Gauss Jackson coefficients, in ordinate form.
trick_units(–)
Definition at line 101 of file gauss_jackson_coefficients_pair.hh.
Referenced by allocate_arrays(), jeod::GaussJacksonCoeffs::compute_coeffs(), deallocate_arrays(), print(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and swap().
sa_coefs
double* jeod::GaussJacksonCoefficientsPair::sa_coefs
Summed Adams coefficients, in ordinate form.
trick_units(–)
Definition at line 96 of file gauss_jackson_coefficients_pair.hh.
Referenced by allocate_arrays(), jeod::GaussJacksonCoeffs::compute_coeffs(), deallocate_arrays(), print(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), and swap().
The documentation for this class was generated from the following files:
gauss_jackson_coefficients_pair.hh
gauss_jackson_coefficients_pair.cc