JEOD: jeod::MessageHandler Class Reference
jeod::MessageHandler Class Reference abstract
The base class for generating JEOD messages.
#include <message_handler.hh>
Public Member Functions
MessageHandler ()
Construct a MessageHandler.
virtual ~MessageHandler ()
Destruct a MessageHandler.
MessageHandler (const MessageHandler &)=delete
MessageHandler & operator= (const MessageHandler &)=delete
virtual void register_contents ()
Register the checkpointable contents of the handler with the simulation interface.
virtual void deregister_contents ()
Deregister the checkpointable contents of the handler with the simulation interface.
Static Public Member Functions
static void fail (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with negative severity, MessageHandler::Failure, and terminate the simulation.
static void error (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with severity MessageHandler::Error.
static void warn (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with severity MessageHandler::Warning.
static void inform (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generates a message with severity MessageHandler::Notice.
static void debug (const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generate a message with severity MessageHandler::Debug.
static void send_message (int severity, const char *prefix, const char *file, unsigned int line, const char *msg_code, const char *format,...)
Generic variable arguments message interface.
static void va_send_message (int severity, const char *prefix, const char *file, unsigned int line, const char *msg_code, const char *format, va_list args)
Generic variable arguments message interface.
static void set_suppression_level (unsigned int suppression_level)
Set the suppression level in the global message handler.
static unsigned int get_suppression_level ()
Get the suppress_id of the global massage handler.
static void add_suppressed_code (const char *msg_code)
Add a message code to the set of messages that are to be suppressed for messages with positive severity level.
static void delete_suppressed_code (const char *msg_code)
Delete a message code from the set of suppressed message codes.
static void clear_suppressed_codes ()
Clear the set of suppressed message codes.
static void set_suppress_id (bool suppress_id)
Set the suppress_id flag in the global message handler.
static bool get_suppress_id ()
Get the suppress_id of the global massage handler.
static void set_suppress_location (bool suppress_location)
Set the suppress_location in the global message handler.
static bool get_suppress_location ()
Get the suppress_location of the global massage handler.
static void set_mode (JeodSimulationInterface::Mode new_mode)
Set the message handler's simulation interface mode.
Static Public Attributes
static const int Failure = -1
The severity value passed by the static public MessageHandler::fail method to the derived class process_message method.
static const int Error = 0
The severity value passed by the static public MessageHandler::error method to the derived class process_message method.
static const int Warning = 9
The severity value passed by the static public MessageHandler::warn method to the derived class process_message method.
static const int Notice = 99
The severity value passed by the static public MessageHandler::inform method to the derived class process_message method.
static const int Debug = 999
The severity value passed by the static public MessageHandler::debug method to the derived class process_message method.
Protected Member Functions
virtual void process_message (int severity, const char *prefix, const char *file, unsigned int line, const char *msg_code, const char *format, va_list args) const =0
Generate the message.
virtual void process_add_suppressed_code (const char *msg_code)
Add a message code to the set of messages that are to be suppressed.
virtual void process_delete_suppressed_code (const char *msg_code)
Delete a message code from the set of suppressed message codes.
virtual void process_clear_suppressed_codes ()
Clear the set of suppressed message codes.
Static Protected Member Functions
static void no_handler_error ()
Handle the error condition where there is no global handler.
Protected Attributes
unsigned int suppression_level
All messages have an associated severity level, with increasingly positive values indicating warnings of decreasing severity.
bool suppress_id {}
This flag indicates whether the message ID is printed for unsuppressed messages.
bool suppress_location {}
This flag indicates whether the message source file and line number printed for unsuppressed messages.
Static Protected Attributes
static MessageHandler * handler = nullptr
The MessageHandler instance that generates messages.
Private Member Functions
void set_mode_internal (JeodSimulationInterface::Mode new_mode)
Set the mode and perform mode transitions.
Private Attributes
JeodSimulationInterface::Mode mode
Simulation interface mode.
Friends
class InputProcessor
void init_attrjeod__MessageHandler ()
Detailed Description
The base class for generating JEOD messages.
This class provides:
A suite of public static message generation and message control functions. The message generation functions provide the mechanism to generate and present messages of various levels of severity to the simulation user. The message control functions provide the user the ability to control which messages will be presented and to control their presentation.
A set of defined constants that denote the severity levels used by JEOD.
Failure (-1): Any negative severity level value indicates an irrecoverable error. The simulation will terminate immediately.
Error (0): Errors almost certainly invalidate the simulation output. All severity zero messages are printed; they cannot be disabled. The difference between failures and errors is that there is some recovery from an error that lets the simulation limp on and find the next error.
Warning (9): Warnings represent conditions that a model deems to be suspect but not necessarily dangerous. Warning messages are printed by default, but they can be disabled.
Notice (99): Notices represent condiitions that a model deems to be suspicious, but not necessarily in error. Notifications are not printed by default, but they can be enabled.
Debug (999): Debug messages typically demonstrate progress of some sort. Enabling them may well result in spew.
A public default constructor and destructor. The constructor ensures that the created object is indeed a singleton.
Definition at line 107 of file message_handler.hh.
Constructor & Destructor Documentation
MessageHandler() [1/2]
jeod::MessageHandler::MessageHandler ()
Construct a MessageHandler.
This default constructor sets the suppression level to MessageHandler::Warning, which means that messages of that severity and lower will be printed. The suppress_id and suppress_location flags are set to false; auxiliary information is not suppressed.
Definition at line 538 of file message_handler.cc.
References error(), handler, and jeod::MessageMessages::singleton_error.
~MessageHandler()
jeod::MessageHandler::~MessageHandler () virtual
Destruct a MessageHandler.
Definition at line 561 of file message_handler.cc.
References handler.
MessageHandler() [2/2]
jeod::MessageHandler::MessageHandler (const MessageHandler &) delete
Member Function Documentation
add_suppressed_code()
void jeod::MessageHandler::add_suppressed_code (const char * msg_code) static
Add a message code to the set of messages that are to be suppressed for messages with positive severity level.
Note: Fatal errors and serious errors cannot be suppressed.
Parameters
[in] msg_code Message code to be suppressed
Definition at line 338 of file message_handler.cc.
References handler, no_handler_error(), and process_add_suppressed_code().
clear_suppressed_codes()
void jeod::MessageHandler::clear_suppressed_codes () static
Clear the set of suppressed message codes.
Definition at line 377 of file message_handler.cc.
References handler, no_handler_error(), and process_clear_suppressed_codes().
debug()
void jeod::MessageHandler::debug (const char * file, unsigned int line, const char * msg_code, const char * format, ...) static
Generate a message with severity MessageHandler::Debug.
Debug messages should never be used for erroneous conditions. They should instead be used for describing nominal behavior. Note that debug messages are nominally suppressed.
Parameters
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] ... sprintf arguments
Definition at line 199 of file message_handler.cc.
References Debug, handler, no_handler_error(), and process_message().
Referenced by jeod::SpiceEphemeris::add_descendants_r(), jeod::BodyDetach::apply(), jeod::MassBodyInit::apply(), jeod::BodyReattach::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBodyInit::apply(), jeod::NullMemoryInterface::deregister_allocation(), jeod::JeodMemoryManager::destroy_memory_internal(), jeod::SpiceEphemeris::determine_root_node(), jeod::SpiceEphemeris::ephem_build_tree(), jeod::JeodMemoryManager::get_type_entry_atomic(), jeod::De4xxFile::open(), jeod::SpiceEphemeris::process_spk(), jeod::NullMemoryInterface::register_allocation(), and jeod::JeodMemoryManager::register_memory_internal().
delete_suppressed_code()
void jeod::MessageHandler::delete_suppressed_code (const char * msg_code) static
Delete a message code from the set of suppressed message codes.
Parameters
[in] msg_code Message code to be unsuppressed
Definition at line 358 of file message_handler.cc.
References handler, no_handler_error(), and process_delete_suppressed_code().
deregister_contents()
virtual void jeod::MessageHandler::deregister_contents () inline virtual
Deregister the checkpointable contents of the handler with the simulation interface.
The base MessageHandler has not such content.
Reimplemented in jeod::SuppressedCodeMessageHandler.
Definition at line 218 of file message_handler.hh.
error()
void jeod::MessageHandler::error (const char * file, unsigned int line, const char * msg_code, const char * format, ...) static
Generate a message with severity MessageHandler::Error.
An error represents a very serious problem. The intent is to represent errors that invalidate simulation results but for which a recovery path does exist. Using MessageHandler::error rather than MessageHandler::fail enables the user to address multiple errors at a time.
A conforming implementation of a class that derives MessageHandler will always report error messages. Errors should not be suppressed.
Parameters
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] ... sprintf arguments
Definition at line 112 of file message_handler.cc.
References Error, handler, no_handler_error(), and process_message().
Referenced by jeod::SinglePointEphemeris::activate(), jeod::SpiceEphemeris::activate(), jeod::Subscription::activate(), jeod::SectionedOutputStream::activate(), jeod::De4xxEphemeris::activate(), jeod::PropagatedPlanet::activate(), jeod::SectionedInputStream::activate(), jeod::DynManager::add_body_action(), jeod::DynManager::add_dyn_body(), jeod::DynamicsIntegrationGroup::add_dyn_body(), jeod::EphemeridesManager::add_ephem_item(), jeod::DynManager::add_integ_group(), jeod::DynManager::add_mass_body(), jeod::DynBody::add_mass_body_validate(), jeod::EphemeridesManager::add_planet(), jeod::RefFrameManager::add_ref_frame(), jeod::RadiationPressure::add_third_body(), jeod::JeodIntegrationTime::add_time_change_subscriber(), jeod::BodyDetach::apply(), jeod::BodyReattach::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), jeod::METAtmosphere::apply_gauss_quadrature(), jeod::MassBody::attach_root_body(), jeod::MassBody::attach_to(), jeod::MassBody::attach_validate_child(), jeod::MassBody::attach_validate_parent(), jeod::DynBody::attach_validate_parent(), jeod::RadiationThirdBody::calculate_shadow(), jeod::DynManager::check_for_uninitialized_states(), jeod::JeodMemoryManager::check_master(), jeod::CmdlineParser::check_registration(), jeod::SphericalHarmonicsGravityControls::check_validity(), jeod::JeodTrick10MemoryInterface::checkpoint_allocations(), jeod::JeodTrick10MemoryInterface::checkpoint_containers(), jeod::CheckPointInputManager::CheckPointInputManager(), jeod::CheckPointOutputManager::CheckPointOutputManager(), jeod::Orientation::compute_euler_angles(), jeod::Orientation::compute_euler_angles_from_matrix(), jeod::Orientation::compute_matrix_from_euler_angles(), jeod::METAtmosphere::compute_mol_wt(), jeod::Orientation::compute_quaternion_from_euler_angles(), jeod::DynBodyInit::compute_rotational_state(), jeod::DynBodyInit::compute_translational_state(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::CheckPointInputManager::create_section_reader(), jeod::CheckPointOutputManager::create_section_writer(), jeod::Subscription::deactivate(), jeod::DynamicsIntegrationGroup::delete_dyn_body(), jeod::JeodTrickMemoryInterface::deregister_allocation(), jeod::JeodTrick10MemoryInterface::deregister_container(), jeod::JeodMemoryManager::destroy_memory_internal(), jeod::EmptySpaceEphemeris::ephem_initialize(), jeod::SinglePlanetEphemeris::ephem_initialize(), jeod::EphemeridesManager::find_ephem_angle(), jeod::EphemeridesManager::find_ephem_point(), jeod::GravityManager::find_grav_source(), jeod::RadiationPressure::find_third_body(), jeod::RefFrameManager::frame_is_subscribed(), jeod::generate_bad_point_message(), jeod::BasicJeodTrickSimInterface::get_checkpoint_reader_internal(), jeod::BasicJeodTrickSimInterface::get_checkpoint_writer_internal(), jeod::JeodTrick10MemoryInterface::get_name_at_address(), jeod::DynManager::gravitation(), jeod::SphericalHarmonicsTidalEffects::initialize(), jeod::CheckPointInputManager::initialize(), jeod::GravityControls::initialize_control(), jeod::DynManager::initialize_gravity_controls(), jeod::DynBody::initialize_model(), jeod::JeodDynbodyIntegrationLoop::integrate_dt(), jeod::Matrix3x3::invert(), jeod::Matrix3x3::invert_symmetric(), jeod::GeneralizedSecondOrderODETechnique::is_provided_by(), jeod::DynBodyInitRotState::is_ready(), jeod::DynBodyInitTransState::is_ready(), jeod::JeodMemoryManager::JeodMemoryManager(), jeod::JeodSimulationInterface::JeodSimulationInterface(), jeod::Orientation::mark_input_as_available(), MessageHandler(), jeod::DynBody::migrate_integrable_objects(), jeod::EphemerisOrientation::note_frame_status_change(), jeod::EphemerisPoint::note_frame_status_change(), jeod::CmdlineParser::parse(), jeod::DynManager::perform_dyn_body_initializations(), jeod::JeodTrickMemoryInterface::primitive_attributes(), jeod::RadiationThirdBody::process_third_body(), jeod::JeodTrickMemoryInterface::register_allocation(), jeod::JeodTrick10MemoryInterface::register_container(), jeod::JeodMemoryManager::register_memory_internal(), jeod::JeodIntegrationGroup::remove_integrable_object(), jeod::RefFrameManager::remove_ref_frame(), jeod::RelativeKinematics::remove_relstate(), jeod::DynBodyInit::report_failure(), jeod::DynManager::reset_gravity_controls(), jeod::JeodMemoryManager::restart_reallocate(), jeod::JeodTrick10MemoryInterface::restore_allocations(), jeod::JeodTrick10MemoryInterface::restore_containers(), jeod::SectionedInputStream::SectionedInputStream(), jeod::SectionedOutputStream::SectionedOutputStream(), jeod::EphemerisRefFrame::set_active_status(), jeod::Orientation::set_euler_angles(), jeod::Orientation::set_euler_sequence(), jeod::DynManager::set_gravity_manager(), jeod::SinglePointEphemeris::set_name(), jeod::Foo::set_num(), jeod::WindVelocity::set_omega_scale_table(), jeod::RadiationPressure::set_third_body_active(), jeod::RadiationPressure::set_third_body_inactive(), jeod::JeodMemoryItem::set_unique_id(), jeod::Subscription::subscribe(), jeod::RefFrameManager::subscribe_to_frame(), jeod::JeodTrick10MemoryInterface::translate_addr_to_name(), jeod::JeodTrick10MemoryInterface::translate_name_to_addr(), jeod::Subscription::unsubscribe(), jeod::RefFrameManager::unsubscribe_to_frame(), jeod::METAtmosphere::update_atmosphere(), jeod::RadiationThirdBody::update_third_body_state(), jeod::WindVelocity::update_wind(), and jeod::RefFrameManager::validate_name().
fail()
void jeod::MessageHandler::fail (const char * file, unsigned int line, const char * msg_code, const char * format, ...) static
Generate a message with negative severity, MessageHandler::Failure, and terminate the simulation.
The intent of this method is to handle erroneous situations for which no recovery path exists. If a recovery path does exist, even if very suspect, callers of this method should consider calling MessageHandler::error as an alternative.
A conforming implementation of a class that derives MessageHandler will force the simulation to terminate upon receipt of a message with negative severity.
Parameters
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] ... sprintf arguments
Definition at line 78 of file message_handler.cc.
References Failure, handler, no_handler_error(), and process_message().
Referenced by jeod::EphemerisItem::activate(), jeod::De4xxEphemeris::activate_em_nodes(), jeod::RelativeKinematics::activate_relstate(), jeod::JeodMemoryManager::add_allocation_atomic(), jeod::StructureIntegratedDynBody::add_constraint(), jeod::SphericalHarmonicsGravitySource::add_deltacoeff(), jeod::EphemeridesManager::add_ephem_item(), jeod::SurfaceModel::add_facet(), jeod::InteractionSurfaceFactory::add_facet_factory(), jeod::RadiationSurfaceFactory::add_facet_params(), jeod::AeroSurfaceFactory::add_facet_params(), jeod::ContactSurfaceFactory::add_facet_params(), jeod::InteractionSurfaceFactory::add_facet_params(), jeod::GravityManager::add_grav_source(), jeod::MassBody::add_mass_point(), jeod::DynBody::add_mass_point(), jeod::RelativeKinematics::add_relstate(), jeod::RadiationPressure::add_third_body(), jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), jeod::JeodBaseTime::add_type_initialize(), jeod::JeodBaseTime::add_type_update(), jeod::AerodynamicDrag::aero_drag(), jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::DefaultAero::aerodrag_force(), jeod::AeroSurface::allocate_array(), jeod::ContactSurface::allocate_array(), jeod::RadiationSurface::allocate_array(), jeod::AeroSurface::allocate_interaction_facet(), jeod::ContactSurface::allocate_interaction_facet(), jeod::RadiationSurface::allocate_interaction_facet(), jeod::JeodMemoryManager::allocate_memory(), jeod::BodyDetach::apply(), jeod::DynBodyInitLvlhState::apply(), jeod::BodyReattach::apply(), jeod::DynBodyInitNedState::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), jeod::DynBodyInitOrbit::apply(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::attach(), jeod::StructureIntegratedDynBody::attach_update_properties(), jeod::DynBody::attach_validate_parent(), jeod::JeodMemoryManager::begin_atomic_block(), jeod::NorthEastDown::build_ned_orientation(), jeod::TimeGMST::calculate_calendar_values(), jeod::TimeGPS::calculate_calendar_values(), jeod::PlanetFixedPosition::cart_to_ellip(), jeod::PlanetFixedPosition::cart_to_spher(), jeod::DynManager::check_for_uninitialized_states(), jeod::check_frame_ownership(), jeod::JeodMemoryManager::check_master(), jeod::CmdlineParser::check_timing(), jeod::SphericalHarmonicsGravityControls::check_validity(), jeod::RefFrame::compute_position_from(), jeod::MassPoint::compute_pred_rel_state(), jeod::RefFrame::compute_pred_rel_state(), jeod::DynBody::compute_ref_point_transform(), jeod::MassPoint::compute_relative_state(), jeod::RefFrame::compute_relative_state(), jeod::Quaternion::compute_slerp(), jeod::MassPoint::compute_state_wrt_pred(), jeod::RefFrame::compute_state_wrt_pred(), jeod::TimeConverter::convert_a_to_b(), jeod::TimeConverter::convert_b_to_a(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::TimeUDE::convert_epoch_to_update(), jeod::TimeGPS::convert_from_calendar(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), jeod::FlatPlateAeroFactory::create_facet(), jeod::FlatPlateRadiationFactory::create_facet(), jeod::LineContactFacetFactory::create_facet(), jeod::PointContactFacetFactory::create_facet(), jeod::TimeManagerInit::create_init_tree(), jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::create_integrator(), jeod::RestartableSO3SecondOrderODEIntegrator::create_integrator(), jeod::JeodSimulationInterface::create_integrator_interface(), jeod::DynBody::create_integrators(), jeod::SpiceEphemeris::create_new_ephem_point(), jeod::ContactSurfaceFactory::create_surface(), jeod::InteractionSurfaceFactory::create_surface(), jeod::TimeManagerInit::create_update_tree(), jeod::JeodMemoryManager::deregister_container(), jeod::StructureIntegratedDynBody::detach(), jeod::DynBody::detach(), jeod::JeodMemoryManager::end_atomic_block(), jeod::SpiceEphemeris::ephem_build_tree(), jeod::De4xxEphemeris::ephem_build_tree(), jeod::SinglePlanetEphemeris::ephem_initialize(), jeod::PropagatedPlanet::ephem_initialize(), jeod::fail_simulation(), jeod::DynBodyInit::find_body_frame(), jeod::DynBody::find_body_frame(), jeod::DynBodyInit::find_dyn_body(), jeod::EphemeridesManager::find_integ_frame_index(), jeod::DerivedState::find_planet(), jeod::DynBodyInit::find_planet(), jeod::DynBodyInit::find_ref_frame(), jeod::JeodSimulationInterface::get_address_at_name(), jeod::JeodMemoryManager::get_alloc_id_atomic(), jeod::JeodSimulationInterface::get_checkpoint_reader(), jeod::JeodSimulationInterface::get_checkpoint_writer(), jeod::RNPJ2000::get_dyn_time_ptr(), jeod::RNPMars::get_dyn_time_ptr(), jeod::DynBody::get_dynamics_integration_group(), jeod::JeodSimulationInterface::get_job_cycle(), jeod::JeodSimulationInterface::get_memory_interface(), jeod::JeodSimulationInterface::get_name_at_address(), jeod::SpiceEphemOrientation::get_spice_transformation(), jeod::JeodMemoryManager::get_string_atomic(), jeod::JeodMemoryManager::get_type_descriptor_atomic(), jeod::DynBodyInitLvlhRotState::initialize(), jeod::TimeConverter_TAI_TT::initialize(), jeod::TimeConverter_UT1_GMST::initialize(), jeod::TimeConverter_TAI_GPS::initialize(), jeod::PlanetOrientation::initialize(), jeod::TimeConverter_Dyn_TAI::initialize(), jeod::DynBodyInitRotState::initialize(), jeod::DynBodyInitTransState::initialize(), jeod::TimeConverter_Dyn_TDB::initialize(), jeod::BodyAttachAligned::initialize(), jeod::TimeConverter_Dyn_UDE::initialize(), jeod::TimeConverter_STD_UDE::initialize(), jeod::LvlhFrame::initialize(), jeod::RadiationDefaultSurface::initialize(), jeod::Planet::initialize(), jeod::RadiationFacet::initialize(), jeod::RadiationSurface::initialize(), jeod::TimeConverter_TAI_TDB::initialize(), jeod::SphericalHarmonicsTidalEffects::initialize(), jeod::PolarMotionJ2000::initialize(), jeod::BodyAttach::initialize(), jeod::DynBodyFrameSwitch::initialize(), jeod::EarthLighting::initialize(), jeod::TimeConverter_TAI_UTC::initialize(), jeod::TimeConverter_TAI_UT1::initialize(), jeod::RadiationBaseFacet::initialize(), jeod::ThermalFacetRider::initialize(), jeod::RelativeDerivedState::initialize(), jeod::DynBodyInit::initialize(), jeod::NutationJ2000::initialize(), jeod::RadiationSource::initialize(), jeod::RadiationThirdBody::initialize(), jeod::DynBodyInitOrbit::initialize(), jeod::De4xxFile::initialize(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), jeod::JeodBaseTime::initialize_from_parent(), jeod::DynamicsIntegrationGroup::initialize_group(), jeod::TimeDyn::initialize_initializer_time(), jeod::TimeStandard::initialize_initializer_time(), jeod::TimeUDE::initialize_initializer_time(), jeod::JeodDynbodyIntegrationLoop::initialize_integ_loop(), jeod::SpiceEphemeris::initialize_items(), jeod::De4xxEphemeris::initialize_items(), jeod::TimeConverter_TAI_UTC::initialize_leap_second(), jeod::Facet::initialize_mass_connection(), jeod::SurfaceModel::initialize_mass_connections(), jeod::MassPointInit::initialize_mass_point(), jeod::MassPropertiesInit::initialize_mass_properties(), jeod::DynBody::initialize_model(), jeod::PropagatedPlanet::initialize_model(), jeod::DynManager::initialize_model_internal(), jeod::TimeConverter_TAI_UT1::initialize_tai_to_ut1(), jeod::SpiceEphemeris::initialize_time(), jeod::De4xxEphemeris::initialize_time(), jeod::DynamicsIntegrationGroup::integrate_bodies(), jeod::SpiceEphemeris::introduce_item(), jeod::JeodDynbodyIntegrationLoop::JeodDynbodyIntegrationLoop(), jeod::JeodTrick10MemoryInterface::JeodTrick10MemoryInterface(), jeod::JeodTrickMemoryInterface::JeodTrickMemoryInterface(), jeod::SpiceEphemeris::load_spice_files(), jeod::TreeLinks< MassBodyLinks, MassBody, MassBodyMessages >::make_root(), jeod::OrbitalElements::mean_anom_to_nu(), jeod::De4xxFile::open(), jeod::TimeManagerInit::populate_converter_registry(), jeod::De4xxFile::pre_initialize(), jeod::MassBody::print_tree(), jeod::SpiceEphemeris::process_spk(), jeod::PlanetRNP::propagate_rnp(), jeod::DynBody::propagate_state(), jeod::FlatPlateRadiationFacet::radiation_pressure(), jeod::MassBody::reattach(), jeod::JeodMemoryManager::register_container(), jeod::TimeManager::register_converter(), jeod::Planet::register_model(), jeod::BasePlanet::register_planet(), jeod::TimeUDE::set_epoch_dyn(), jeod::TimeUDE::set_epoch_std(), jeod::TimeUDE::set_epoch_times(), jeod::TimeUDE::set_epoch_ude(), jeod::TimeUDE::set_initial_times(), jeod::DynBody::set_integ_frame(), jeod::JeodSimulationInterface::set_mode(), jeod::PropagatedPlanet::set_mode(), jeod::StructureIntegratedDynBody::set_solver(), jeod::DynBody::set_state_source(), jeod::EphemerisItem::set_target_frame(), jeod::EphemeridesManager::set_target_frame(), jeod::TimeGMST::set_time_by_trunc_julian(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::DynBody::switch_integration_frames(), jeod::TimeManager::time_lookup(), jeod::OrbitalElements::to_cartesian(), jeod::GravityTorque::update(), jeod::LvlhRelativeDerivedState::update(), jeod::SolarBetaDerivedState::update(), jeod::RelativeDerivedState::update(), jeod::JeodBaseTime::update(), jeod::De4xxFile::update(), jeod::Facet::update_articulation(), jeod::SurfaceModel::update_articulation(), jeod::PlanetRNP::update_axial_rotation(), jeod::DynManager::update_integration_group(), jeod::JeodDynbodyIntegrationLoop::update_integration_group(), jeod::PlanetRNP::update_rnp(), jeod::RotationJ2000::update_rotation(), jeod::RotationMars::update_rotation(), jeod::PrecessionMars::update_rotation(), jeod::SpiceEphemeris::update_trans(), jeod::BodyAction::validate_body_inputs(), jeod::NamedItem::validate_name(), jeod::EphemerisItem::validate_name(), jeod::BodyAction::validate_name(), jeod::GeneralizedSecondOrderODETechnique::validate_technique(), jeod::TimeManagerInit::verify_converter_setup(), jeod::TimeUDE::verify_epoch(), jeod::TimeConverter::verify_setup(), jeod::TimeManagerInit::verify_times_setup(), jeod::NamedItem::verify_unfrozen_name(), jeod::TimeUDE::verify_update(), and jeod::MassBody::~MassBody().
get_suppress_id()
bool jeod::MessageHandler::get_suppress_id () static
Get the suppress_id of the global massage handler.
Returns
ID value
Units: Suppress
Definition at line 415 of file message_handler.cc.
References handler, no_handler_error(), and suppress_id.
get_suppress_location()
bool jeod::MessageHandler::get_suppress_location () static
Get the suppress_location of the global massage handler.
Returns
Suppress location value
Definition at line 457 of file message_handler.cc.
References handler, no_handler_error(), and suppress_location.
get_suppression_level()
unsigned int jeod::MessageHandler::get_suppression_level () static
Get the suppress_id of the global massage handler.
Returns
Suppression level value
Definition at line 312 of file message_handler.cc.
References handler, no_handler_error(), and suppression_level.
inform()
void jeod::MessageHandler::inform (const char * file, unsigned int line, const char * msg_code, const char * format, ...) static
Generates a message with severity MessageHandler::Notice.
Informational notices should not represent problems of any significance as the default behavior is to suppress such messages.
Parameters
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] ... sprintf arguments
Definition at line 170 of file message_handler.cc.
References handler, no_handler_error(), Notice, and process_message().
Referenced by jeod::EphemeridesManager::add_ephem_item(), jeod::DynBody::add_mass_body(), jeod::TimeStandard::add_type_initialize(), jeod::JeodBaseTime::add_type_update(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::collect_insert(), jeod::collect_push_back(), jeod::TimeConverter_TAI_UTC::convert_a_to_b(), jeod::TimeConverter_TAI_UT1::convert_a_to_b(), jeod::TimeConverter_TAI_UTC::convert_b_to_a(), jeod::TimeConverter_TAI_UT1::convert_b_to_a(), jeod::RadiationThirdBody::convert_shadow_from_int(), jeod::MassBody::detach(), jeod::DynBody::detach(), jeod::MassBody::detach_validate_child(), jeod::MassBody::detach_validate_parent(), jeod::RNPJ2000::ephem_update(), jeod::RNPMars::ephem_update(), jeod::JeodTrickMemoryInterface::find_attributes(), jeod::JeodMemoryManager::generate_shutdown_report(), jeod::TimeStandard::initialize_initializer_time(), jeod::TimeUDE::initialize_initializer_time(), jeod::TimeConverter_TAI_UTC::initialize_leap_second(), jeod::TimeConverter_TAI_UT1::initialize_tai_to_ut1(), jeod::ThermalIntegrableObject::integrate(), jeod::ThermalFacetRider::integrate(), jeod::TimeManagerInit::populate_converter_registry(), jeod::TimeManager::register_converter(), jeod::TimeManager::register_time(), jeod::DynBody::remove_mass_body(), jeod::GravityControls::reset_control(), jeod::JeodSimulationInterface::set_mode(), jeod::EphemerisItem::set_name(), and jeod::GeneralizedSecondOrderODETechnique::validate_technique().
no_handler_error()
void jeod::MessageHandler::no_handler_error () static protected
Handle the error condition where there is no global handler.
Note
That this condition exists means the simulation is non-compliant.
Assumptions and Limitations
All JEOD-based simulations must have a message handler and memory handler that at instantiated prior to instantiating any other JEOD-based model and destroyed after all those other models have been destroyed.
That no message handler exists means the simulation is not a compliant with the above restrictions.
The handling of this condition is intentionally simplistic. An error message is printed and the simulation is terminated via a system call to exit.
Definition at line 523 of file message_handler.cc.
Referenced by add_suppressed_code(), clear_suppressed_codes(), debug(), delete_suppressed_code(), error(), fail(), get_suppress_id(), get_suppress_location(), get_suppression_level(), inform(), send_message(), set_mode(), set_suppress_id(), set_suppress_location(), set_suppression_level(), va_send_message(), and warn().
operator=()
MessageHandler& jeod::MessageHandler::operator= (const MessageHandler &) delete
process_add_suppressed_code()
virtual void jeod::MessageHandler::process_add_suppressed_code (const char * msg_code) inline protected virtual
Add a message code to the set of messages that are to be suppressed.
The method add_suppressed_code relays the call to the message handler as a call to process_add_suppressed_code.
The default behavior is a no-op. Suppressing messages by the message code is an optional capability.
Parameters
msg_code Message code to be suppressed
Reimplemented in jeod::TestMessageHandler, and jeod::SuppressedCodeMessageHandler.
Definition at line 313 of file message_handler.hh.
Referenced by add_suppressed_code().
process_clear_suppressed_codes()
virtual void jeod::MessageHandler::process_clear_suppressed_codes () inline protected virtual
Clear the set of suppressed message codes.
The method clear_suppressed_codes relays the call to the message handler as a call to process_clear_suppressed_codes.
As with process_add_suppressed_code, the default for this function is a no-op; suppressed codes are an optional capability.
Definition at line 335 of file message_handler.hh.
Referenced by clear_suppressed_codes().
process_delete_suppressed_code()
virtual void jeod::MessageHandler::process_delete_suppressed_code (const char * msg_code) inline protected virtual
Delete a message code from the set of suppressed message codes.
The method delete_suppressed_code relays the call to the message handler as a call to process_delete_suppressed_code.
As with process_add_suppressed_code, the default for this function is a no-op; suppressed codes are an optional capability.
Parameters
msg_code Message code to be suppressed
Reimplemented in jeod::TestMessageHandler, and jeod::SuppressedCodeMessageHandler.
Definition at line 325 of file message_handler.hh.
Referenced by delete_suppressed_code().
process_message()
virtual void jeod::MessageHandler::process_message (int severity, const char * prefix, const char * file, unsigned int line, const char * msg_code, const char * format, va_list args) const protected pure virtual
Generate the message.
All of the send_message() methods relay the message to the message handler in the form of a call to process_message().
An instantiable derived MessageHandler class must supply this function.
Parameters
severity Severity level
prefix Message prefix (e.g., Error)
file Typically FILE
line Typically LINE
msg_code Message code
format sprintf format
args Arguments
Implemented in jeod::TestMessageHandler, and jeod::TrickMessageHandler.
Referenced by debug(), error(), fail(), inform(), send_message(), va_send_message(), and warn().
register_contents()
virtual void jeod::MessageHandler::register_contents () inline virtual
Register the checkpointable contents of the handler with the simulation interface.
The base MessageHandler has not such content.
Reimplemented in jeod::TrickMessageHandler, and jeod::SuppressedCodeMessageHandler.
Definition at line 211 of file message_handler.hh.
Referenced by jeod::BasicJeodTrickSimInterface::BasicJeodTrickSimInterface().
send_message()
void jeod::MessageHandler::send_message (int severity, const char * prefix, const char * file, unsigned int line, const char * msg_code, const char * format, ...) static
Generic variable arguments message interface.
This method gives the caller control over the severity level and over the message prefix. These are automatically generated in the standard set of MessageHandler interface methods.
Parameters
[in] severity Severity level
[in] prefix Message prefix (e.g., Error)
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] ... sprintf arguments
Definition at line 230 of file message_handler.cc.
References handler, no_handler_error(), and process_message().
set_mode()
void jeod::MessageHandler::set_mode (JeodSimulationInterface::Mode new_mode) static
Set the message handler's simulation interface mode.
Assumptions and Limitations
This method must not be called before the singleton message handler has been created or after it has been destroyed. A fatal error results when this is not true.
Parameters
[in] new_mode New mode
Definition at line 485 of file message_handler.cc.
References handler, no_handler_error(), and set_mode_internal().
Referenced by jeod::BasicJeodTrickSimInterface::set_mode().
set_mode_internal()
void jeod::MessageHandler::set_mode_internal (JeodSimulationInterface::Mode new_mode) private
Set the mode and perform mode transitions.
Parameters
[in] new_mode New mode
Definition at line 504 of file message_handler.cc.
References mode.
Referenced by set_mode().
set_suppress_id()
void jeod::MessageHandler::set_suppress_id (bool suppress_id) static
Set the suppress_id flag in the global message handler.
Parameters
[in] suppress_id New suppress id value
Definition at line 396 of file message_handler.cc.
References handler, no_handler_error(), and suppress_id.
Referenced by jeod::JeodSimulationInterface::configure().
set_suppress_location()
void jeod::MessageHandler::set_suppress_location (bool suppress_location) static
Set the suppress_location in the global message handler.
Parameters
[in] suppress_location New suppress_loc value
Definition at line 438 of file message_handler.cc.
References handler, no_handler_error(), and suppress_location.
Referenced by jeod::JeodSimulationInterface::configure().
set_suppression_level()
void jeod::MessageHandler::set_suppression_level (unsigned int suppression_level) static
Set the suppression level in the global message handler.
Parameters
[in] suppression_level New suppression level
Definition at line 293 of file message_handler.cc.
References handler, no_handler_error(), and suppression_level.
Referenced by jeod::JeodSimulationInterface::configure().
va_send_message()
void jeod::MessageHandler::va_send_message (int severity, const char * prefix, const char * file, unsigned int line, const char * msg_code, const char * format, va_list args) static
Generic variable arguments message interface.
This method behaves similarly to MessageHandler::send_message except that the caller has already captured the variable arguments in the form of a va_list. Note that MessageHandler::va_send_message does not call va_end macro.
Parameters
[in] severity Severity level
[in] prefix Message prefix (e.g., Error)
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in,out] args Varargs stack
Definition at line 268 of file message_handler.cc.
References handler, no_handler_error(), and process_message().
warn()
void jeod::MessageHandler::warn (const char * file, unsigned int line, const char * msg_code, const char * format, ...) static
Generate a message with severity MessageHandler::Warning.
Warnings represent situations where the model developer had to make some assumptions to recover from what would otherwise be an erroneous condition. The recovery based on those assumptions does not necessarily invalidate invalidate the simulation results.
Parameters
[in] file Typically FILE
[in] line Typically LINE
[in] msg_code Message code
[in] format sprintf format
[in] ... sprintf arguments
Definition at line 142 of file message_handler.cc.
References handler, no_handler_error(), process_message(), and Warning.
Referenced by jeod::GravityInteraction::add_control(), jeod::DynManager::add_dyn_body(), jeod::EphemeridesManager::add_ephem_item(), jeod::SurfaceModel::add_facets(), jeod::DynBody::add_integrable_object(), jeod::DynBody::add_mass_body(), jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::DefaultAero::aerodrag_force(), jeod::AeroSurface::allocate_array(), jeod::DynBody::attach_child(), jeod::DynBody::attach_to_frame(), jeod::DynBody::attach_validate_child(), jeod::DynBody::attach_validate_parent(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::RefFrameManager::check_ref_frame_ownership(), jeod::EphemeridesManager::clear_added_ephemerides(), jeod::De4xxFile::close(), jeod::METAtmosphere::compute_exospheric_temperature(), jeod::LineContactFacet::create_pair(), jeod::PointContactFacet::create_pair(), jeod::JeodMemoryManager::destroy_memory_internal(), jeod::MassBody::detach_validate_parent(), jeod::JeodMemoryManager::find_alloc_entry_atomic(), jeod::EphemeridesManager::find_planet(), jeod::JeodMemoryManager::free_memory(), jeod::JeodMemoryManager::generate_shutdown_report(), jeod::DynBodyInitLvlhRotState::initialize(), jeod::DynBodyInitLvlhTransState::initialize(), jeod::DynBodyInitNedRotState::initialize(), jeod::DynBodyInitNedTransState::initialize(), jeod::TimeConverter_STD_UDE::initialize(), jeod::RadiationDefaultSurface::initialize(), jeod::ThermalFacetRider::initialize(), jeod::DynBodyInit::initialize(), jeod::TimeUDE::initialize_from_parent(), jeod::TimeStandard::initialize_initializer_time(), jeod::TimeUDE::initialize_initializer_time(), jeod::DynManager::initialize_simulation(), jeod::De4xxEphemeris::initialize_time(), jeod::ThermalFacetRider::integrate(), jeod::CmdlineParser::parse(), jeod::JPVCollectForce::perform_insert_action(), jeod::JPVCollectTorque::perform_insert_action(), jeod::TimeManager::register_time_named(), jeod::GravityInteraction::remove_control(), jeod::DynBody::remove_integrable_object(), jeod::JeodIntegrationTime::remove_time_change_subscriber(), jeod::TimeUDE::set_epoch_dyn(), jeod::TimeUDE::set_epoch_initializing_value(), jeod::TimeUDE::set_epoch_std(), jeod::TimeUDE::set_epoch_ude(), jeod::RadiationPressure::set_third_body_active(), jeod::RadiationPressure::set_third_body_inactive(), jeod::PolarMotionJ2000::update_rotation(), jeod::WindVelocityBase::update_wind(), and jeod::TimeUDE::verify_init().
Friends And Related Function Documentation
init_attrjeod__MessageHandler
void init_attrjeod__MessageHandler () friend
InputProcessor
friend class InputProcessor friend
Definition at line 109 of file message_handler.hh.
Field Documentation
Debug
const int jeod::MessageHandler::Debug = 999 static
The severity value passed by the static public MessageHandler::debug method to the derived class process_message method.
This is set to 999 in the implementation. The intent is to summarize to the user of some event that the user requested did indeed transpire. Ideally, JEOD code, particularly initialization code, will be peppered with calls to MessageHandler::debug.trick_io(*o) trick_units(–)
Definition at line 269 of file message_handler.hh.
Referenced by debug(), and jeod::JeodSimulationInterfaceInit::JeodSimulationInterfaceInit().
Error
const int jeod::MessageHandler::Error = 0 static
The severity value passed by the static public MessageHandler::error method to the derived class process_message method.
This is set to 0 in the implementation, representing the most severe non-fatal error.
Non-negative severity levels indicate non-fatal conditions for which messages might nonetheless need to be generated, depending on the value of the user-settable suppression_level.trick_io(*o) trick_units(–)
Definition at line 243 of file message_handler.hh.
Referenced by error().
Failure
const int jeod::MessageHandler::Failure = -1 static
The severity value passed by the static public MessageHandler::fail method to the derived class process_message method.
This is set to -1 in the implementation, representing a fatal error.
A valid implementation of the process_message method must treat negative severity levels as fatal; they must not return to the calling procedure. In other words, failures eventually result in a call to exit.trick_io(*o) trick_units(–)
Definition at line 231 of file message_handler.hh.
Referenced by fail().
handler
MessageHandler * jeod::MessageHandler::handler = nullptr static protected
The MessageHandler instance that generates messages.
The static MessageHandler functions invoked by various models pass the message on to this instance in the form of a call to process_message.trick_io(*o) trick_units(–)
Definition at line 344 of file message_handler.hh.
Referenced by add_suppressed_code(), clear_suppressed_codes(), debug(), delete_suppressed_code(), error(), fail(), get_suppress_id(), get_suppress_location(), get_suppression_level(), inform(), MessageHandler(), send_message(), set_mode(), set_suppress_id(), set_suppress_location(), set_suppression_level(), va_send_message(), warn(), and ~MessageHandler().
mode
JeodSimulationInterface::Mode jeod::MessageHandler::mode private
Simulation interface mode.
trick_units(–)
Definition at line 378 of file message_handler.hh.
Referenced by set_mode_internal().
Notice
const int jeod::MessageHandler::Notice = 99 static
The severity value passed by the static public MessageHandler::inform method to the derived class process_message method.
This is set to 99 in the implementation. The intent is to indicate a non-error condition that might be worthy of a user notification.trick_io(*o) trick_units(–)
Definition at line 259 of file message_handler.hh.
Referenced by inform().
suppress_id
bool jeod::MessageHandler::suppress_id {} protected
This flag indicates whether the message ID is printed for unsuppressed messages.
The ID is not printed if this flag is set to true. The message ID is always printed for fatal errors.trick_units(–)
Definition at line 364 of file message_handler.hh.
Referenced by get_suppress_id(), jeod::TrickMessageHandler::process_message(), jeod::TestMessageHandler::process_message(), and set_suppress_id().
suppress_location
bool jeod::MessageHandler::suppress_location {} protected
This flag indicates whether the message source file and line number printed for unsuppressed messages.
The location is not printed if this flag is set to true. The message location is always printed for fatal errors.trick_units(–)
Definition at line 372 of file message_handler.hh.
Referenced by get_suppress_location(), jeod::TrickMessageHandler::process_message(), jeod::TestMessageHandler::process_message(), and set_suppress_location().
suppression_level
unsigned int jeod::MessageHandler::suppression_level protected
All messages have an associated severity level, with increasingly positive values indicating warnings of decreasing severity.
Fatal errors have a negative severity level. Messages whose severity exceeds the value of the global message handler's suppression_level are suppressed. Note that fatal errors and severe errors cannot be suppressed.
Default value: MessageHandler::Warning (warnings and non-fatal errors).trick_units(–)
Definition at line 357 of file message_handler.hh.
Referenced by get_suppression_level(), jeod::SuppressedCodeMessageHandler::message_is_to_be_printed(), jeod::TrickMessageHandler::process_message(), jeod::TestMessageHandler::process_message(), and set_suppression_level().
Warning
const int jeod::MessageHandler::Warning = 9 static
The severity value passed by the static public MessageHandler::warn method to the derived class process_message method.
This is set to 9 in the implementation. The intent is to indicate a condition that might indicate that results are suspect.trick_io(*o) trick_units(–)
Definition at line 251 of file message_handler.hh.
Referenced by warn().
The documentation for this class was generated from the following files:
message_handler.hh
message_handler.cc