JEOD: jeod::EphemeridesManager Class Reference
jeod::EphemeridesManager Class Reference
The EphemeridesManager class manages the ephemeris models in a simulation.
#include <ephem_manager.hh>
Public Member Functions
EphemeridesManager ()
EphemeridesManager default constructor.
~EphemeridesManager () override
EphemeridesManager destructor.
bool ref_frame_tree_needs_rebuild () const
Query if the reference frame tree needs to be rebuilt.
void ephem_note_tree_status_change () override
Denote that the reference frame tree needs to be rebuilt.
void add_planet (BasePlanet &planet) override
Add a planet to the planets registry.
void add_planet (Planet &planet) override
Add a planet to the registry.
BasePlanet * find_base_planet (const char *name) const override
Find the planet with the given name.
Planet * find_planet (const char *name) const override
Find the planet with the given name.
unsigned int get_num_planets (void) const override
Return number of registered planets.
void add_ephemeris (EphemerisInterface &ephem_if) override
Add an ephemeris model to the list of managed models.
void clear_added_ephemerides (void) override
Deactivate any registered ephemeris items and remove them from the list.
void disable_add_ephemeris (void) override
Make subsequent calls to add_ephemeris deactivate the specified ephemeris model instead of adding it to the list of managed models.
void add_ephem_item (EphemerisItem &ephem_item) override
Add an ephemeris item to the set of ephemeris items known to the ephemerides manager.
EphemerisItem * find_ephem_item (const char *name) const override
Find the first registered EphemerisItem with the given name.
EphemerisOrientation * find_ephem_angle (const char *name) const override
Find the EphemerisOrientation with the given name.
EphemerisPoint * find_ephem_point (const char *name) const override
Find the EphemerisPoint with the given name.
void add_integ_frame (EphemerisRefFrame &ref_frame) override
Add a frame to the reference frame and integration frame lists.
EphemerisRefFrame * find_integ_frame (const char *name) const override
Find the integration frame with the given name.
bool is_integ_frame (const RefFrame &ref_frame) const override
Determine if supplied frame is an integration frame.
unsigned int find_integ_frame_index (const EphemerisRefFrame &ref_frame) const override
Find the index of provided frame in the integration frames vector.
const std::vector< EphemerisRefFrame * > & get_integ_frames (void) const override
Get a copy of the vector of integration frames.
void add_ref_frame (RefFrame &ref_frame) override
Add a reference frame to the reference frame registry.
void set_target_frame (RefFrame &ref_frame)
Set the target-frame reference for the ref-frame and all known EphemItems with similar target-frame names.
void initialize_ephemerides (void)
Initialize the ephemeris models.
void activate_ephemerides (void)
Activate ephemeris items based on frame subscription status, activate ephemeris models, and build the reference frame tree.
void update_ephemerides (void)
Update each ephemeris model.
Public Member Functions inherited from jeod::BaseEphemeridesManager
~BaseEphemeridesManager () override
Destructor.
Public Member Functions inherited from jeod::BaseRefFrameManager
virtual ~BaseRefFrameManager ()
Destructor.
Public Member Functions inherited from jeod::RefFrameManager
RefFrameManager ()
RefFrameManager default constructor.
~RefFrameManager () override
RefFrameManager destructor.
void add_ref_frame (RefFrame &ref_frame) override
Add a reference frame to the reference frame registry.
void remove_ref_frame (RefFrame &ref_frame) override
Remove a reference frame from the reference frame registry.
RefFrame * find_ref_frame (const char *name) const override
Find the reference frame with the given name.
RefFrame * find_ref_frame (const char *prefix, const char *suffix) const override
Find the reference frame with the dot-conjoined name "${prefix}.${suffix}".
void check_ref_frame_ownership (void) const override
Check that each active reference frame has an owner.
void reset_tree_root_node () override
Reset the root node in anticipation of rebuilding the entire tree.
void add_frame_to_tree (RefFrame &ref_frame, RefFrame *parent) override
Insert a reference frame in the reference frame tree.
void subscribe_to_frame (const char *frame_name) override
Subscribe to a reference frame, with the frame specified by name.
void subscribe_to_frame (RefFrame &frame) override
Subscribe to a reference frame, with the frame specified as an argument.
void unsubscribe_to_frame (const char *frame_name) override
Remove subscription to a reference frame, with the frame specified by name.
void unsubscribe_to_frame (RefFrame &frame) override
Remove subscription to a reference frame, with the frame specified as an argument.
bool frame_is_subscribed (const char *frame_name) override
Checks whether frame has subscribers; frame specified by name.
bool frame_is_subscribed (RefFrame &frame) override
Checks whether frame has subscribers; frame provided as an argument.
Protected Attributes
bool single_ephem_mode
Set via a call to disable_add_ephemeris, typically to allow a simple ephemeris model to be active with all other models made inactive.
bool regenerate_ref_frame_tree
Set when the reference frame tree needs to be regenerated.
double update_time
Time of last update.
JeodPointerVector< BasePlanet >::type planets
The planets in a simulation, typically defined at the S_define level.
JeodPointerVector< EphemerisInterface >::type ephemerides
The ephemerides models managed by this EphemeridesManager.
JeodPointerVector< EphemerisItem >::type ephem_items
The heads of the ephemeris item lists.
JeodPointerVector< EphemerisRefFrame >::type integ_frames
List of reference frames that are not rotating with respect to the root node of the reference frame tree.
Protected Attributes inherited from jeod::RefFrameManager
RefFrame * root_node
The root node of the reference frame tree.
JeodPointerVector< RefFrame >::type ref_frames
List of reference frames.
Private Member Functions
EphemeridesManager (const EphemeridesManager &)
Not implemented.
EphemeridesManager & operator= (const EphemeridesManager &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EphemeridesManager ()
Additional Inherited Members
Protected Member Functions inherited from jeod::RefFrameManager
bool validate_name (const char *file, unsigned int line, const char *variable_value, const char *variable_type, const char *variable_name) const
Check whether a name is trivially valid/invalid.
Detailed Description
The EphemeridesManager class manages the ephemeris models in a simulation.
The primary functions of a EphemeridesManager are to:
Maintain lists of planets, ephemeris models, ephemeris items, and integration frames, and to provide lookup methods for these lists.
Dynamically determine which ephemerides are needed in a simulation.
Initialize ephemeris models and keep them in sync with the rest of the simulation.
Definition at line 91 of file ephem_manager.hh.
Constructor & Destructor Documentation
EphemeridesManager() [1/2]
jeod::EphemeridesManager::EphemeridesManager (void)
EphemeridesManager default constructor.
Definition at line 59 of file ephem_manager.cc.
References ephem_items, ephemerides, integ_frames, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and planets.
~EphemeridesManager()
jeod::EphemeridesManager::~EphemeridesManager (void) override
EphemeridesManager destructor.
Definition at line 83 of file ephem_manager.cc.
References ephem_items, ephemerides, integ_frames, JEOD_DEREGISTER_CHECKPOINTABLE, and planets.
EphemeridesManager() [2/2]
jeod::EphemeridesManager::EphemeridesManager (const EphemeridesManager &) private
Not implemented.
Member Function Documentation
activate_ephemerides()
void jeod::EphemeridesManager::activate_ephemerides (void)
Activate ephemeris items based on frame subscription status, activate ephemeris models, and build the reference frame tree.
Definition at line 707 of file ephem_manager.cc.
References jeod::EphemerisItem::disconnect_from_tree(), jeod::EphemerisInterface::ephem_activate(), jeod::EphemerisInterface::ephem_build_tree(), ephem_items, ephemerides, regenerate_ref_frame_tree, and jeod::RefFrameManager::reset_tree_root_node().
Referenced by jeod::DynManager::initialize_simulation(), and update_ephemerides().
add_ephem_item()
void jeod::EphemeridesManager::add_ephem_item (EphemerisItem & ephem_item) override virtual
Add an ephemeris item to the set of ephemeris items known to the ephemerides manager.
Each ephemeris model calls this method for each ephemeris item represented by that ephemeris model. The provided item is added to
The ephem_items list if the provided item's name is unique or
The tail of the list of items with the same name if an item with the provided item's name is already in the ephem_items list.
Multiple ephemerides models might represent the same conceptual item. The ephem_items list contains only items with unique names. These head items link to other items with the same name via the items' next data members, which form a singly-linked list of commonly-named items.
Assumptions and limitations:
The item must have a valid name.
Only one item with a given name can be enabled.
Parameters
ephem_item Ephemeris item to be added to the registry.
Implements jeod::BaseEphemeridesManager.
Definition at line 296 of file ephem_manager.cc.
References jeod::EphemerisItem::disable(), jeod::EphemeridesMessages::duplicate_entry, ephem_items, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), find_ephem_item(), jeod::RefFrameManager::find_ref_frame(), jeod::EphemerisItem::get_enabled_item(), jeod::EphemerisInterface::get_name(), jeod::EphemerisItem::get_name(), jeod::RefFrame::get_name(), jeod::EphemerisItem::get_next(), jeod::EphemerisItem::get_owner(), jeod::EphemeridesMessages::inconsistent_setup, jeod::MessageHandler::inform(), jeod::EphemeridesMessages::internal_error, jeod::EphemerisItem::is_enabled(), jeod::EphemerisItem::set_head(), jeod::EphemerisItem::set_manager(), jeod::EphemerisItem::set_next(), jeod::EphemerisItem::set_target_frame(), jeod::EphemeridesMessages::single_ephem_mode, single_ephem_mode, jeod::EphemerisItem::Translation, jeod::EphemerisItem::updates_what(), jeod::RefFrameManager::validate_name(), and jeod::MessageHandler::warn().
Referenced by jeod::PlanetOrientation::initialize(), jeod::De4xxEphemeris::initialize_items(), jeod::EmptySpaceEphemeris::initialize_model(), jeod::SinglePlanetEphemeris::initialize_model(), jeod::PropagatedPlanet::initialize_model(), and jeod::SpiceEphemeris::introduce_item().
add_ephemeris()
void jeod::EphemeridesManager::add_ephemeris (EphemerisInterface & ephem_if) override virtual
Add an ephemeris model to the list of managed models.
Assumptions and limitations:
Ephemeris models must be registered with the ephemerides manager in dependency order: Models with no dependencies are registered first, followed by models that depend on these base models, and so on.
Parameters
ephem_if Ephemeris model to be added to the registry.
Implements jeod::BaseEphemeridesManager.
Definition at line 232 of file ephem_manager.cc.
References ephemerides.
Referenced by jeod::PlanetOrientation::initialize(), jeod::SpiceEphemeris::initialize_model(), jeod::De4xxEphemeris::initialize_model(), jeod::EmptySpaceEphemeris::initialize_model(), jeod::SinglePlanetEphemeris::initialize_model(), and jeod::PropagatedPlanet::initialize_model().
add_integ_frame()
void jeod::EphemeridesManager::add_integ_frame (EphemerisRefFrame & ref_frame) override virtual
Add a frame to the reference frame and integration frame lists.
Parameters
ref_frame Integration frame to be added to the registries
Implements jeod::BaseEphemeridesManager.
Definition at line 467 of file ephem_manager.cc.
References add_ref_frame(), and integ_frames.
Referenced by jeod::SpiceEphemeris::add_barycenter(), jeod::De4xxEphemeris::initialize_items(), and jeod::EmptySpaceEphemeris::initialize_model().
add_planet() [1/2]
void jeod::EphemeridesManager::add_planet (BasePlanet & planet) override virtual
Add a planet to the planets registry.
Parameters
planet Planet to be added to the registry.
Implements jeod::BaseEphemeridesManager.
Definition at line 120 of file ephem_manager.cc.
References jeod::EphemeridesMessages::duplicate_entry, jeod::MessageHandler::error(), find_base_planet(), jeod::BasePlanet::name, planets, and jeod::RefFrameManager::validate_name().
Referenced by add_planet().
add_planet() [2/2]
void jeod::EphemeridesManager::add_planet (Planet & planet) override virtual
Add a planet to the registry.
Parameters
planet Planet to be added to the registry.
Implements jeod::BaseEphemeridesManager.
Definition at line 87 of file find_planet.cc.
References add_planet().
add_ref_frame()
void jeod::EphemeridesManager::add_ref_frame (RefFrame & ref_frame) override virtual
Add a reference frame to the reference frame registry.
Parameters
ref_frame Reference frame to be added to the registry
Implements jeod::BaseRefFrameManager.
Definition at line 594 of file ephem_manager.cc.
References jeod::RefFrameManager::add_ref_frame(), and set_target_frame().
Referenced by add_integ_frame(), jeod::LvlhFrame::initialize(), jeod::LvlhDerivedState::initialize(), and jeod::NedDerivedState::initialize().
clear_added_ephemerides()
void jeod::EphemeridesManager::clear_added_ephemerides (void) override virtual
Deactivate any registered ephemeris items and remove them from the list.
Implements jeod::BaseEphemeridesManager.
Definition at line 245 of file ephem_manager.cc.
References jeod::EphemerisItem::disable(), ephem_items, ephemerides, jeod::EphemeridesMessages::single_ephem_mode, and jeod::MessageHandler::warn().
Referenced by jeod::DynManager::initialize_model_internal().
disable_add_ephemeris()
void jeod::EphemeridesManager::disable_add_ephemeris (void) override virtual
Make subsequent calls to add_ephemeris deactivate the specified ephemeris model instead of adding it to the list of managed models.
Note
This is an irrevocable act.
Assumptions and limitations:
This method is typically used after clearing the ephemerides model list and then adding the one allowed ephermides model:
EphemeridesManager::clear_added_ephemerides();
EphemeridesManager::add_ephemeris (model);
EphemeridesManager::add_ephem_item (item);
EphemeridesManager::disable_add_ephemeris ();
Implements jeod::BaseEphemeridesManager.
Definition at line 214 of file ephem_manager.cc.
References single_ephem_mode.
Referenced by jeod::DynManager::initialize_model_internal().
ephem_note_tree_status_change()
void jeod::EphemeridesManager::ephem_note_tree_status_change (void) override virtual
Denote that the reference frame tree needs to be rebuilt.
Implements jeod::BaseEphemeridesManager.
Definition at line 102 of file ephem_manager.cc.
References regenerate_ref_frame_tree.
Referenced by jeod::PropagatedPlanet::set_mode().
find_base_planet()
BasePlanet * jeod::EphemeridesManager::find_base_planet (const char * name) const override virtual
Find the planet with the given name.
Parameters
name Planet name.
Returns
Found planet; NULL if not found.
Implements jeod::BaseEphemeridesManager.
Definition at line 159 of file ephem_manager.cc.
References jeod::BasePlanet::name, and planets.
Referenced by add_planet(), jeod::SinglePlanetEphemeris::ephem_initialize(), jeod::PropagatedPlanet::ephem_initialize(), find_planet(), and jeod::LvlhFrame::initialize().
find_ephem_angle()
EphemerisOrientation * jeod::EphemeridesManager::find_ephem_angle (const char * name) const override virtual
Find the EphemerisOrientation with the given name.
Parameters
name Ephemeris angle name
Returns
Found ephemeris angle
Implements jeod::BaseEphemeridesManager.
Definition at line 413 of file ephem_manager.cc.
References jeod::MessageHandler::error(), find_ephem_item(), and jeod::EphemeridesMessages::invalid_item.
find_ephem_item()
EphemerisItem * jeod::EphemeridesManager::find_ephem_item (const char * name) const override virtual
Find the first registered EphemerisItem with the given name.
Parameters
name Ephemeris item name
Returns
Found ephemeris item
Implements jeod::BaseEphemeridesManager.
Definition at line 388 of file ephem_manager.cc.
References ephem_items, and jeod::EphemerisItem::get_name().
Referenced by add_ephem_item(), find_ephem_angle(), find_ephem_point(), and set_target_frame().
find_ephem_point()
EphemerisPoint * jeod::EphemeridesManager::find_ephem_point (const char * name) const override virtual
Find the EphemerisPoint with the given name.
Parameters
name Ephemeris point name
Returns
Found ephemeris point
Implements jeod::BaseEphemeridesManager.
Definition at line 438 of file ephem_manager.cc.
References jeod::MessageHandler::error(), find_ephem_item(), and jeod::EphemeridesMessages::invalid_item.
find_integ_frame()
EphemerisRefFrame * jeod::EphemeridesManager::find_integ_frame (const char * name) const override virtual
Find the integration frame with the given name.
Parameters
name Integration frame name
Returns
Found integration frame
Implements jeod::BaseEphemeridesManager.
Definition at line 486 of file ephem_manager.cc.
References jeod::RefFrame::get_name(), and integ_frames.
Referenced by jeod::DynBodyFrameSwitch::initialize(), and jeod::PropagatedPlanet::initialize_model().
find_integ_frame_index()
unsigned int jeod::EphemeridesManager::find_integ_frame_index (const EphemerisRefFrame & ref_frame) const override virtual
Find the index of provided frame in the integration frames vector.
Parameters
ref_frame Reference to be found
Returns
Index of found frame
Implements jeod::BaseEphemeridesManager.
Definition at line 551 of file ephem_manager.cc.
References jeod::MessageHandler::fail(), jeod::RefFrame::get_name(), integ_frames, and jeod::EphemeridesMessages::invalid_item.
find_planet()
Planet * jeod::EphemeridesManager::find_planet (const char * name) const override virtual
Find the planet with the given name.
Parameters
name Planet name
Returns
Found planet, as a Planet rather than a BasePlanet
Implements jeod::BaseEphemeridesManager.
Definition at line 51 of file find_planet.cc.
References find_base_planet(), jeod::EphemeridesMessages::invalid_item, and jeod::MessageHandler::warn().
Referenced by jeod::DerivedState::find_planet(), jeod::DynBodyInit::find_planet(), jeod::PlanetOrientation::initialize(), jeod::EarthLighting::initialize(), jeod::RadiationSource::initialize(), and jeod::RadiationThirdBody::initialize().
get_integ_frames()
const std::vector< EphemerisRefFrame * > & jeod::EphemeridesManager::get_integ_frames (void) const override virtual
Get a copy of the vector of integration frames.
Returns
Copy of integration frames vector
Implements jeod::BaseEphemeridesManager.
Definition at line 511 of file ephem_manager.cc.
References integ_frames.
get_num_planets()
unsigned int jeod::EphemeridesManager::get_num_planets (void) const override virtual
Return number of registered planets.
Returns
: Number of registered planets.
Implements jeod::BaseEphemeridesManager.
Definition at line 186 of file ephem_manager.cc.
References planets.
Referenced by jeod::SinglePlanetEphemeris::ephem_initialize().
initialize_ephemerides()
void jeod::EphemeridesManager::initialize_ephemerides (void)
Initialize the ephemeris models.
Definition at line 660 of file ephem_manager.cc.
References jeod::EphemerisInterface::ephem_initialize(), ephemerides, and regenerate_ref_frame_tree.
Referenced by jeod::DynManager::initialize_simulation().
is_integ_frame()
bool jeod::EphemeridesManager::is_integ_frame (const RefFrame & ref_frame) const override virtual
Determine if supplied frame is an integration frame.
Parameters
ref_frame Reference frame to test
Returns
True if the frame is a registered integration frame, false otherwise
Implements jeod::BaseEphemeridesManager.
Definition at line 525 of file ephem_manager.cc.
References integ_frames.
operator=()
EphemeridesManager& jeod::EphemeridesManager::operator= (const EphemeridesManager &) private
Not implemented.
ref_frame_tree_needs_rebuild()
bool jeod::EphemeridesManager::ref_frame_tree_needs_rebuild () const inline
Query if the reference frame tree needs to be rebuilt.
Returns
regenerate_ref_frame_tree data member.
Definition at line 116 of file ephem_manager.hh.
References regenerate_ref_frame_tree.
Referenced by jeod::DynamicsIntegrationGroup::gravitation().
set_target_frame()
void jeod::EphemeridesManager::set_target_frame (RefFrame & ref_frame)
Set the target-frame reference for the ref-frame and all known EphemItems with similar target-frame names.
Parameters
ref_frame Reference frame to be used as the target-frame.
Definition at line 609 of file ephem_manager.cc.
References jeod::MessageHandler::fail(), find_ephem_item(), jeod::RefFrame::get_name(), jeod::EphemeridesMessages::inconsistent_setup, jeod::EphemerisRefFrame::set_ephem_manager(), and jeod::EphemerisItem::set_target_frame().
Referenced by add_ref_frame(), and jeod::PropagatedPlanet::ephem_initialize().
update_ephemerides()
void jeod::EphemeridesManager::update_ephemerides (void)
Update each ephemeris model.
Definition at line 681 of file ephem_manager.cc.
References activate_ephemerides(), jeod::EphemerisInterface::ephem_update(), ephemerides, and regenerate_ref_frame_tree.
Referenced by jeod::DynamicsIntegrationGroup::gravitation(), jeod::DynManager::initialize_simulation(), and jeod::DynManager::perform_dyn_body_initializations().
Friends And Related Function Documentation
init_attrjeod__EphemeridesManager
void init_attrjeod__EphemeridesManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 95 of file ephem_manager.hh.
Field Documentation
ephem_items
JeodPointerVector<EphemerisItem>::type jeod::EphemeridesManager::ephem_items protected
The heads of the ephemeris item lists.
All items in one of these sublists share the same name. The members of the ephem_items list have distinct names.trick_io(**)
Definition at line 246 of file ephem_manager.hh.
Referenced by activate_ephemerides(), add_ephem_item(), clear_added_ephemerides(), EphemeridesManager(), find_ephem_item(), and ~EphemeridesManager().
ephemerides
JeodPointerVector<EphemerisInterface>::type jeod::EphemeridesManager::ephemerides protected
The ephemerides models managed by this EphemeridesManager.
trick_io(**)
Definition at line 239 of file ephem_manager.hh.
Referenced by activate_ephemerides(), add_ephemeris(), clear_added_ephemerides(), EphemeridesManager(), initialize_ephemerides(), update_ephemerides(), and ~EphemeridesManager().
integ_frames
JeodPointerVector<EphemerisRefFrame>::type jeod::EphemeridesManager::integ_frames protected
List of reference frames that are not rotating with respect to the root node of the reference frame tree.
trick_io(**)
Definition at line 252 of file ephem_manager.hh.
Referenced by add_integ_frame(), EphemeridesManager(), find_integ_frame(), find_integ_frame_index(), get_integ_frames(), is_integ_frame(), and ~EphemeridesManager().
planets
JeodPointerVector<BasePlanet>::type jeod::EphemeridesManager::planets protected
The planets in a simulation, typically defined at the S_define level.
trick_io(**)
Definition at line 234 of file ephem_manager.hh.
Referenced by add_planet(), EphemeridesManager(), find_base_planet(), get_num_planets(), and ~EphemeridesManager().
regenerate_ref_frame_tree
bool jeod::EphemeridesManager::regenerate_ref_frame_tree protected
Set when the reference frame tree needs to be regenerated.
trick_units(–)
Definition at line 224 of file ephem_manager.hh.
Referenced by activate_ephemerides(), ephem_note_tree_status_change(), initialize_ephemerides(), jeod::DynManager::perform_dyn_body_initializations(), ref_frame_tree_needs_rebuild(), and update_ephemerides().
single_ephem_mode
bool jeod::EphemeridesManager::single_ephem_mode protected
Set via a call to disable_add_ephemeris, typically to allow a simple ephemeris model to be active with all other models made inactive.
trick_units(–)
Definition at line 219 of file ephem_manager.hh.
Referenced by add_ephem_item(), and disable_add_ephemeris().
update_time
double jeod::EphemeridesManager::update_time protected
Time of last update.
trick_units(s)
Definition at line 229 of file ephem_manager.hh.
Referenced by jeod::DynManager::timestamp().
The documentation for this class was generated from the following files:
ephem_manager.hh
ephem_manager.cc
find_planet.cc