JEOD: jeod::InteractionSurface Class Reference
jeod::InteractionSurface Class Reference abstract
A base class for interaction specific surfaces.
#include <interaction_surface.hh>
Public Member Functions
InteractionSurface ()
Default Constructor.
virtual ~InteractionSurface ()
Destructor.
virtual void accumulate_thermal_sources (void)
Adds all thermal sources together.
virtual void thermal_integrator (void)
Integrates thermal sources to get temperature.
virtual void allocate_array (unsigned int size)=0
A pure virtual function that will allocate the array of pointers to the correct interaction facet type, of the given size.
virtual void allocate_interaction_facet (Facet *facet, InteractionFacetFactory *factory, FacetParams *params, unsigned int index)=0
A pure virtual function that will allocate the interaction facet, from the given facet, using the given facet parameters, and place it in the allocated array of interaction facets at the given index.
Private Member Functions
InteractionSurface & operator= (const InteractionSurface &rhs)
InteractionSurface (const InteractionSurface &rhs)
Friends
class InputProcessor
void init_attrjeod__InteractionSurface ()
Detailed Description
A base class for interaction specific surfaces.
Definition at line 88 of file interaction_surface.hh.
Constructor & Destructor Documentation
InteractionSurface() [1/2]
jeod::InteractionSurface::InteractionSurface (void)
Default Constructor.
Definition at line 39 of file interaction_surface.cc.
~InteractionSurface()
jeod::InteractionSurface::~InteractionSurface (void) virtual
Destructor.
Definition at line 51 of file interaction_surface.cc.
InteractionSurface() [2/2]
jeod::InteractionSurface::InteractionSurface (const InteractionSurface & rhs) private
Member Function Documentation
accumulate_thermal_sources()
virtual void jeod::InteractionSurface::accumulate_thermal_sources (void) inline virtual
Adds all thermal sources together.
Reimplemented in jeod::RadiationSurface.
Definition at line 109 of file interaction_surface.hh.
Referenced by jeod::ThermalModelRider::update().
allocate_array()
virtual void jeod::InteractionSurface::allocate_array (unsigned int size) pure virtual
A pure virtual function that will allocate the array of pointers to the correct interaction facet type, of the given size.
Parameters
[in] size Size of the array to be allocated
Units: cnt
Implemented in jeod::RadiationSurface, jeod::ContactSurface, and jeod::AeroSurface.
Referenced by jeod::ContactSurfaceFactory::create_surface(), and jeod::InteractionSurfaceFactory::create_surface().
allocate_interaction_facet()
virtual void jeod::InteractionSurface::allocate_interaction_facet (Facet * facet, InteractionFacetFactory * factory, FacetParams * params, unsigned int index) pure virtual
A pure virtual function that will allocate the interaction facet, from the given facet, using the given facet parameters, and place it in the allocated array of interaction facets at the given index.
Parameters
[in] facet The facet used to create the interaction facet
[in] factory The factory used to create the interaction facet
[in] params The parameters used to create the interaction facet
[in] index Where in the interaction facet array the interaction facet will be placed
Units: cnt
Implemented in jeod::RadiationSurface, jeod::ContactSurface, and jeod::AeroSurface.
Referenced by jeod::ContactSurfaceFactory::create_surface(), and jeod::InteractionSurfaceFactory::create_surface().
operator=()
InteractionSurface& jeod::InteractionSurface::operator= (const InteractionSurface & rhs) private
thermal_integrator()
virtual void jeod::InteractionSurface::thermal_integrator (void) inline virtual
Integrates thermal sources to get temperature.
Reimplemented in jeod::RadiationSurface.
Definition at line 121 of file interaction_surface.hh.
Referenced by jeod::ThermalModelRider::update().
Friends And Related Function Documentation
init_attrjeod__InteractionSurface
void init_attrjeod__InteractionSurface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file interaction_surface.hh.
The documentation for this class was generated from the following files:
interaction_surface.hh
interaction_surface.cc