JEOD: jeod::EphemerisItem Class Reference
jeod::EphemerisItem Class Reference abstract
The EphemerisItem class is the base class for representing an item that is modeled in an ephemeris model.
#include <ephem_item.hh>
Public Types
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Public Member Functions
EphemerisItem ()
Construct an ephemeris item.
~EphemerisItem () override
Destroy an ephemeris item.
virtual void set_name (const char *new_name)
Name an ephemeris item.
virtual void set_name (const char *pname, const char *fname)
Name an ephemeris item.
const char * get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp (void) const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void enable ()
Enable an EphemerisItem object.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item (void) const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const char *new_value, const char *old_value, const char *variable_name)
Name an ephemeris item.
virtual TargetAspect updates_what (void) const =0
Identifies which part of the target frame does the object updates.
virtual const char * default_suffix (void) const =0
The default suffix for the item.
virtual void disconnect_from_tree (void)=0
Disconnect the item from the reference frame tree.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Protected Member Functions
virtual void set_name_internal (char *new_name)
Name an ephemeris item.
Protected Attributes
char * name
The name of the item.
EphemerisInterface * owner
The ephemeris model that owns this object.
BaseEphemeridesManager * manager
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame
The reference frame whose non-constant state is set by this object.
EphemerisItem * head
The first ephemeris item with the same name as this item.
EphemerisItem * next
The next ephemeris item with the same name as this item.
double update_time
Time of last update, dynamic time seconds.
bool enabled
Is the item enabled?
bool active
Is the item active?
Private Member Functions
EphemerisItem (const EphemerisItem &)
Not implemented.
EphemerisItem & operator= (const EphemerisItem &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EphemerisItem ()
Detailed Description
The EphemerisItem class is the base class for representing an item that is modeled in an ephemeris model.
Ephemeris items form the bridge between the reference frame model and the ephemeris models. An EphemerisItem
Has a name, which is not necessarily unique. Ephemeris items with the same name are linked to one another to form a linked list.
Has a target reference frame. This is the ephemeris reference frame which has the same name as the ephemeris item.
Can be enabled or disabled. At most one item of a set of commonly-named items can be enabled, and only if a correspondingly-named ephemeris reference frame exists. Ownership of the correspondingly-named ephemeris reference frame transfers to the enabled ephemeris item. When an ephemeris item is disabled, the ephemeris model that owns the ephemeris item should not operate on the correspondingly-named reference frame.
Can be active or inactive. Disabled items must always be inactive. The activity level of the enabled item for a set of commonly-named items is automatically maintained to be the same as that of the target frame.
The ephemeris model that owns an active ephemeris item is responsible for ensuring that the correspondingly-named ephemeris reference frame is a part of the active reference frame tree and for updating that reference frame's state.
Definition at line 106 of file ephem_item.hh.
Member Enumeration Documentation
TargetAspect
enum jeod::EphemerisItem::TargetAspect
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Enumerator
Translation
Rotation
Definition at line 117 of file ephem_item.hh.
Constructor & Destructor Documentation
EphemerisItem() [1/2]
jeod::EphemerisItem::EphemerisItem (void)
Construct an ephemeris item.
Definition at line 62 of file ephem_item.cc.
~EphemerisItem()
jeod::EphemerisItem::~EphemerisItem (void) override
Destroy an ephemeris item.
Definition at line 83 of file ephem_item.cc.
References JEOD_DELETE_ARRAY, JEOD_IS_ALLOCATED, and name.
EphemerisItem() [2/2]
jeod::EphemerisItem::EphemerisItem (const EphemerisItem &) private
Not implemented.
Member Function Documentation
activate()
void jeod::EphemerisItem::activate (void) virtual
Activate a EphemerisItem object.
Definition at line 345 of file ephem_item.cc.
References active, jeod::MessageHandler::fail(), jeod::EphemeridesMessages::invalid_item, is_activatable(), and name.
Referenced by jeod::De4xxEphemeris::activate_em_nodes(), jeod::EphemerisOrientation::note_frame_status_change(), jeod::EphemerisPoint::note_frame_status_change(), and set_target_frame().
deactivate()
void jeod::EphemerisItem::deactivate (void) inline virtual
Deactivate a EphemerisItem object.
Definition at line 130 of file ephem_item_inline.hh.
References active.
Referenced by jeod::EphemerisOrientation::note_frame_status_change(), and jeod::EphemerisPoint::note_frame_status_change().
default_suffix()
virtual const char* jeod::EphemerisItem::default_suffix (void) const pure virtual
The default suffix for the item.
Implemented in jeod::EphemerisOrientation, and jeod::EphemerisPoint.
Referenced by jeod::SpiceEphemeris::populate_item(), and set_name().
disable()
void jeod::EphemerisItem::disable (void) inline virtual
Disable an EphemerisItem object.
Definition at line 316 of file ephem_item.cc.
References active, enabled, jeod::BaseEphemeridesManager::ephem_note_tree_status_change(), manager, jeod::RefFrame::set_owner(), and target_frame.
Referenced by jeod::EphemeridesManager::add_ephem_item(), jeod::EphemeridesManager::clear_added_ephemerides(), enable(), jeod::EmptySpaceEphemeris::ephem_initialize(), jeod::SinglePlanetEphemeris::ephem_initialize(), jeod::De4xxEphemeris::initialize_items(), and jeod::PropagatedPlanet::set_mode().
disconnect_from_tree()
virtual void jeod::EphemerisItem::disconnect_from_tree (void) pure virtual
Disconnect the item from the reference frame tree.
Implemented in jeod::EphemerisOrientation, and jeod::EphemerisPoint.
Referenced by jeod::EphemeridesManager::activate_ephemerides().
enable()
void jeod::EphemerisItem::enable (void) virtual
Enable an EphemerisItem object.
Reimplemented in jeod::EphemerisOrientation.
Definition at line 279 of file ephem_item.cc.
References active, disable(), enabled, jeod::BaseEphemeridesManager::ephem_note_tree_status_change(), get_enabled_item(), manager, jeod::RefFrame::set_owner(), and target_frame.
Referenced by jeod::De4xxEphemeris::activate_em_nodes(), jeod::De4xxEphemeris::De4xxEphemeris(), jeod::EmptySpaceEphemeris::EmptySpaceEphemeris(), jeod::EphemerisOrientation::enable(), jeod::SpiceEphemeris::populate_item(), jeod::PropagatedPlanet::set_mode(), and jeod::SinglePlanetEphemeris::SinglePlanetEphemeris().
get_enabled_item()
EphemerisItem * jeod::EphemerisItem::get_enabled_item (void) const inline
Get the item marked as enabled, if any.
Returns
Enabled item
Definition at line 272 of file ephem_item_inline.hh.
References enabled, head, and next.
Referenced by jeod::De4xxEphemeris::activate_nodes(), jeod::EphemeridesManager::add_ephem_item(), jeod::EphemerisOrientation::enable(), enable(), and set_target_frame().
get_head()
EphemerisItem * jeod::EphemerisItem::get_head (void) const inline
Get the head item.
Returns
Root item
Definition at line 220 of file ephem_item_inline.hh.
References head.
get_manager()
BaseEphemeridesManager * jeod::EphemerisItem::get_manager (void) const inline
Return the manager of this item.
Returns
Object manager
Definition at line 194 of file ephem_item_inline.hh.
References manager.
get_name()
const char * jeod::EphemerisItem::get_name (void) const inline
Return the name.
Returns
Void
Definition at line 79 of file ephem_item_inline.hh.
References name.
Referenced by jeod::EphemeridesManager::add_ephem_item(), jeod::De4xxEphemeris::De4xxEphemeris(), jeod::SpiceEphemeris::determine_root_node(), jeod::EphemeridesManager::find_ephem_item(), and jeod::SpiceEphemeris::introduce_item().
get_next()
EphemerisItem * jeod::EphemerisItem::get_next (void) const inline
Get the next item.
Returns
Next item
Definition at line 246 of file ephem_item_inline.hh.
References next.
Referenced by jeod::EphemeridesManager::add_ephem_item().
get_owner()
EphemerisInterface * jeod::EphemerisItem::get_owner (void) const inline
Return the owner of this item.
Returns
Frame owner
Definition at line 168 of file ephem_item_inline.hh.
References owner.
Referenced by jeod::EphemeridesManager::add_ephem_item().
get_target_frame()
EphemerisRefFrame * jeod::EphemerisItem::get_target_frame (void) const inline
Get the target frame.
Returns
Target frame
Definition at line 259 of file ephem_item_inline.hh.
References target_frame.
Referenced by jeod::SpiceEphemeris::add_descendants_r(), jeod::SpiceEphemeris::ephem_build_tree(), jeod::SinglePlanetEphemeris::ephem_build_tree(), jeod::EmptySpaceEphemeris::ephem_initialize(), jeod::De4xxEphemeris::ephem_initialize(), jeod::SinglePlanetEphemeris::ephem_initialize(), jeod::PropagatedPlanet::ephem_initialize(), and jeod::SpiceEphemeris::introduce_item().
is_activatable()
bool jeod::EphemerisItem::is_activatable (void) const
Is the item activatable?
Returns
True if item can be activated.
Definition at line 365 of file ephem_item.cc.
References active, enabled, head, and next.
Referenced by activate().
is_active()
bool jeod::EphemerisItem::is_active (void) const inline
Return activity status.
Returns
Is item active?
Definition at line 143 of file ephem_item_inline.hh.
References active.
Referenced by jeod::De4xxEphemeris::activate_nodes(), jeod::RNPJ2000::ephem_update(), and jeod::RNPMars::ephem_update().
is_enabled()
bool jeod::EphemerisItem::is_enabled (void) const inline
Return enabled status.
Returns
Is item enabled?
Definition at line 118 of file ephem_item_inline.hh.
References enabled.
Referenced by jeod::EphemeridesManager::add_ephem_item().
operator=()
EphemerisItem& jeod::EphemerisItem::operator= (const EphemerisItem &) private
Not implemented.
set_head()
void jeod::EphemerisItem::set_head (EphemerisItem * head_item) inline virtual
Set the head item.
Parameters
[in,out] head_item Root item
Definition at line 207 of file ephem_item_inline.hh.
References head.
Referenced by jeod::EphemeridesManager::add_ephem_item().
set_manager()
void jeod::EphemerisItem::set_manager (BaseEphemeridesManager * new_manager) inline virtual
Set the manager of this item.
Parameters
[in] new_manager New owner
Definition at line 181 of file ephem_item_inline.hh.
References manager.
Referenced by jeod::EphemeridesManager::add_ephem_item().
set_name() [1/2]
void jeod::EphemerisItem::set_name (const char * new_name) virtual
Name an ephemeris item.
Parameters
[in] new_name New name
Definition at line 151 of file ephem_item.cc.
References default_suffix(), jeod::MessageHandler::inform(), jeod::EphemeridesMessages::invalid_name, JEOD_STRDUP, name, set_name_internal(), and validate_name().
Referenced by jeod::De4xxEphemeris::De4xxEphemeris(), jeod::PlanetOrientation::initialize(), jeod::PropagatedPlanet::initialize_model(), jeod::SpiceEphemeris::populate_item(), jeod::EmptySpaceEphemeris::set_name(), and jeod::SinglePlanetEphemeris::set_name().
set_name() [2/2]
void jeod::EphemerisItem::set_name (const char * pname, const char * fname) virtual
Name an ephemeris item.
Parameters
[in] pname Planet name
[in] fname Frame name
Definition at line 132 of file ephem_item.cc.
References jeod::NamedItem::construct_name(), name, set_name_internal(), and validate_name().
set_name_internal()
void jeod::EphemerisItem::set_name_internal (char * new_name) protected virtual
Name an ephemeris item.
Parameters
[in] new_name New name
Definition at line 183 of file ephem_item.cc.
References JEOD_DELETE_ARRAY, JEOD_IS_ALLOCATED, and name.
Referenced by set_name().
set_next()
void jeod::EphemerisItem::set_next (EphemerisItem * next_item) inline virtual
Set the next item.
Parameters
[in,out] next_item Next item
Definition at line 233 of file ephem_item_inline.hh.
References next.
Referenced by jeod::EphemeridesManager::add_ephem_item().
set_owner()
void jeod::EphemerisItem::set_owner (EphemerisInterface * new_owner) inline virtual
Set the owner of this item.
Parameters
[in] new_owner New owner
Definition at line 156 of file ephem_item_inline.hh.
References owner.
Referenced by jeod::De4xxEphemeris::De4xxEphemeris(), jeod::EmptySpaceEphemeris::EmptySpaceEphemeris(), jeod::PlanetOrientation::initialize(), jeod::SpiceEphemeris::populate_item(), jeod::PropagatedPlanet::PropagatedPlanet(), and jeod::SinglePlanetEphemeris::SinglePlanetEphemeris().
set_target_frame()
void jeod::EphemerisItem::set_target_frame (EphemerisRefFrame & frame) virtual
Set the target frame.
All ephemeris items that share a common name must point to the same target frame.
Parameters
[in] frame Target frame
Definition at line 204 of file ephem_item.cc.
References activate(), jeod::MessageHandler::fail(), get_enabled_item(), head, jeod::EphemeridesMessages::invalid_item, jeod::Subscription::is_active(), jeod::BaseEphemeridesManager::is_integ_frame(), manager, name, next, jeod::RefFrame::set_owner(), set_target_frame(), target_frame, Translation, and updates_what().
Referenced by jeod::EphemeridesManager::add_ephem_item(), set_target_frame(), and jeod::EphemeridesManager::set_target_frame().
set_timestamp()
void jeod::EphemerisItem::set_timestamp (double time) inline virtual
Set the update time of this item.
Parameters
[in] time Time
Units: s
Definition at line 92 of file ephem_item_inline.hh.
References update_time.
timestamp()
double jeod::EphemerisItem::timestamp (void) const inline
Return the update time of this item.
Returns
Time of last update
Units: s
Definition at line 105 of file ephem_item_inline.hh.
References update_time.
updates_what()
virtual TargetAspect jeod::EphemerisItem::updates_what (void) const pure virtual
Identifies which part of the target frame does the object updates.
Implemented in jeod::EphemerisOrientation, and jeod::EphemerisPoint.
Referenced by jeod::EphemeridesManager::add_ephem_item(), and set_target_frame().
validate_name()
void jeod::EphemerisItem::validate_name (const char * file, unsigned int line, const char * new_value, const char * old_value, const char * variable_name)
Name an ephemeris item.
Parameters
[in] file Usually FILE
[in] line Usually LINE
[in] new_value Value to check
[in] old_value Current value
[in] variable_name Variable name
Definition at line 102 of file ephem_item.cc.
References jeod::MessageHandler::fail(), jeod::EphemeridesMessages::invalid_name, manager, and jeod::NamedItem::validate_name().
Referenced by set_name().
Friends And Related Function Documentation
init_attrjeod__EphemerisItem
void init_attrjeod__EphemerisItem () friend
InputProcessor
friend class InputProcessor friend
Definition at line 107 of file ephem_item.hh.
Field Documentation
active
bool jeod::EphemerisItem::active protected
Is the item active?
An item can be activated only if it is enabled. The enable and activate methods assure that this is the case.
Activity is determined by the activity of the target frame, which is in turn determined by the reference frame subscription model.trick_units(–)
Definition at line 272 of file ephem_item.hh.
Referenced by activate(), deactivate(), disable(), jeod::EphemerisPoint::disconnect_from_tree(), enable(), is_activatable(), and is_active().
enabled
bool jeod::EphemerisItem::enabled protected
Is the item enabled?
An item can be enabled only if the data associated with the item such as the translational state of a planet exist somewhere in the simulation.
Only one of a set of ephemeris items that share the same name can be enabled. The enable method ensures that this is the case.
Exactly one of a set of ephemeris items that share same name should be enabled if some other simulation agent depends on the data associated with an ephemeris item. Ensuring that this is the case is the responsibility of the ephemeris models and the users of those models.trick_units(–)
Definition at line 263 of file ephem_item.hh.
Referenced by disable(), jeod::EphemerisOrientation::enable(), enable(), get_enabled_item(), is_activatable(), is_enabled(), jeod::PropagatedEphemerisPlanet::update(), and jeod::PropagatedEphemerisOrientation::update().
head
EphemerisItem* jeod::EphemerisItem::head protected
The first ephemeris item with the same name as this item.
trick_units(–)
Definition at line 240 of file ephem_item.hh.
Referenced by get_enabled_item(), get_head(), is_activatable(), set_head(), and set_target_frame().
manager
BaseEphemeridesManager* jeod::EphemerisItem::manager protected
The ephemeris manager that manages this object.
trick_units(–)
Definition at line 230 of file ephem_item.hh.
Referenced by disable(), enable(), get_manager(), set_manager(), set_target_frame(), and validate_name().
name
char* jeod::EphemerisItem::name protected
The name of the item.
trick_units(–)
Definition at line 220 of file ephem_item.hh.
Referenced by activate(), get_name(), set_name(), set_name_internal(), set_target_frame(), and ~EphemerisItem().
next
EphemerisItem* jeod::EphemerisItem::next protected
The next ephemeris item with the same name as this item.
trick_units(–)
Definition at line 245 of file ephem_item.hh.
Referenced by get_enabled_item(), get_next(), is_activatable(), set_next(), and set_target_frame().
owner
EphemerisInterface* jeod::EphemerisItem::owner protected
The ephemeris model that owns this object.
trick_units(–)
Definition at line 225 of file ephem_item.hh.
Referenced by get_owner(), and set_owner().
target_frame
EphemerisRefFrame* jeod::EphemerisItem::target_frame protected
The reference frame whose non-constant state is set by this object.
trick_units(–)
Definition at line 235 of file ephem_item.hh.
Referenced by disable(), jeod::EphemerisPoint::disconnect_from_tree(), enable(), get_target_frame(), jeod::EphemerisPoint::initialize_state(), jeod::EphemerisOrientation::note_frame_status_change(), jeod::EphemerisPoint::note_frame_status_change(), jeod::EphemerisZXZOrientation::propagate(), set_target_frame(), jeod::SpiceEphemOrientation::update(), jeod::EphemerisPoint::update(), jeod::EphemerisZXZOrientation::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::PropagatedEphemerisOrientation::update(), and jeod::EphemerisPoint::update_scaled().
update_time
double jeod::EphemerisItem::update_time protected
Time of last update, dynamic time seconds.
trick_units(s)
Definition at line 250 of file ephem_item.hh.
Referenced by jeod::EphemerisZXZOrientation::propagate(), set_timestamp(), timestamp(), jeod::SpiceEphemOrientation::update(), jeod::EphemerisPoint::update(), jeod::EphemerisZXZOrientation::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::PropagatedEphemerisOrientation::update(), and jeod::EphemerisPoint::update_scaled().
The documentation for this class was generated from the following files:
ephem_item.hh
ephem_item_inline.hh
ephem_item.cc