JEOD: LSODE
LSODE
Models » Utilities » Integration
Implements the LSODE integration technique, which is suitable for long arc integration.
Files
file lsode_control_data_interface.hh
Define the class LsodeControlDataInterface.
file lsode_data_classes.hh
Define LSODE classes that contain just data members.
file lsode_first_order_ode_integrator.hh
Define the class LsodeFirstOrderODEIntegrator, the Jeod-compatible version of the Livermore ODE solver, LSODE.
file lsode_generalized_second_order_ode_integrator.hh
Define the class LsodeGeneralizedDerivSecondOrderODEIntegrator.
file lsode_integration_controls.hh
Define the class LsodeIntegrationControls.
file lsode_integrator_constructor.hh
Define the class LsodeIntegratorConstructor, the class that constructs the integration controls and the integrators for the LSODE method.
file lsode_second_order_ode_integrator.hh
Define the class LsodeSecondOrderODEIntegrator.
file lsode_simple_second_order_ode_integrator.hh
Define the class LsodeSimpleSecondOrderODEIntegrator.
file lsode_control_data_interface.cc
Define member functions for the class LsodeControlDataInterface.
file lsode_data_classes.cc
Define member functions for the data-grouping classes specified in lsode_data_classes.
file lsode_first_order_ode_integrator__integrator.cc
Define member functions for the class LsodeFirstOrderODEIntegrator.
file lsode_first_order_ode_integrator__manager.cc
Define member functions for the class LsodeFirstOrderODEIntegrator.
file lsode_first_order_ode_integrator__support.cc
Define member functions for the class LsodeFirstOrderODEIntegrator.
file lsode_first_order_ode_integrator__utility.cc
Define member functions for the class LsodeFirstOrderODEIntegrator.
file lsode_generalized_second_order_ode_integrator.cc
Define member functions for the class LsodeGeneralizedDerivSecondOrderODEIntegrator.
file lsode_integration_controls.cc
Define the methods for the class LsodeIntegrationControls.
file lsode_integrator_constructor.cc
Define the methods in the class LsodeIntegratorConstructor.
file lsode_second_order_ode_integrator.cc
Define member functions for the class LsodeSecondOrderODEIntegrator.
file lsode_simple_second_order_ode_integrator.cc
Define member functions for the class LsodeSimpleSecondOrderODEIntegrator.
Namespaces
jeod
Namespace jeod.
Functions
jeod::LsodeControlDataInterface::LsodeControlDataInterface ()
constructor
void jeod::LsodeControlDataInterface::check_interface_data ()
verifies that the input data has legal values.
void jeod::LsodeControlDataInterface::allocate_arrays ()
allocates space for vector-populated data to allow for restart
void jeod::LsodeControlDataInterface::destroy_allocated_arrays ()
De-allocates allocated array.
void jeod::LsodeControlDataInterface::set_rel_tol (int index, double value)
set values from external
void jeod::LsodeControlDataInterface::set_abs_tol (int index, double value)
void jeod::LsodeDataArrays::allocate_arrays (unsigned int num_odes, LsodeControlDataInterface::CorrectorMethod corrector_method)
Allocates memory for the variable size arrays.
void jeod::LsodeDataArrays::destroy_allocated_arrays ()
Allows for refactoring and reallocation of newly sized arrays.
void jeod::LsodeFirstOrderODEIntegrator::integrator_core ()
integrator_core provides the front-end to all of the integrator_*i methods, which together perform one step of the integration of an initial value problem for a system of ordinary differential equations.
void jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs ()
Sets/resets the method_coeffs_current array.
void jeod::LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change ()
Tests h against old h.
void jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh ()
Resets history arrays and time-step.
void jeod::LsodeFirstOrderODEIntegrator::integrator_predict ()
This section computes the predicted values by multiplying the history array by the Pascal Triangle matrix.
void jeod::LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part1 ()
This method resets the iteration loop to the values generated by the integrator_predict method, which populated history[*][0].
void jeod::LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part2 ()
This code follows part 1 after the break-out to get to the external calls, and completes the reset of the integration iteration loop.
void jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_iteration ()
Keeps looping through the iterations until convergence or failure.
void jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part1 ()
The corrector iteration failed to converge.
void jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part2 ()
Retracts the history array in the case that the correction iteration failed to converge with either functional iteration or with an up-to-date Jacobian.
void jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_converged ()
Starts the processing of a converged iteration.
void jeod::LsodeFirstOrderODEIntegrator::integrator_error_test_failed ()
Restores the history array following the failure of the corrector for exceeding local error bounds.
void jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_prep ()
The first steps in computing whether the order of the integrator should be changed.
void jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order ()
Computes the step-size scaling factors that will result once it is determined what happens to the order at the next step.
void jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_check_step_error ()
void jeod::LsodeFirstOrderODEIntegrator::integrator_set_new_order ()
Sets the new order and the step-ratio for the next step - or the current step if redoing it.
void jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part1 ()
Repopulates the y-array from history, recomputes the original first derivatives, sets the order back to 1, and reduces the step size by a factor of 10.
void jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part2 ()
Continue reset, with derivatives now at hand.
void jeod::LsodeFirstOrderODEIntegrator::integrator_wrapup ()
Wraps up the completion of the integrator.
void jeod::LsodeFirstOrderODEIntegrator::integrator_terminate ()
this is the only succesful path back from integrator to manager.
er7_utils::IntegratorResult jeod::LsodeFirstOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double *y_dot, double *y) override
Propagate state via Lsode's method.
void jeod::LsodeFirstOrderODEIntegrator::process_entry_point_cycle_start ()
The code block from the main integrate routine for re_entry_point=CycleStartFinish.
void jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part1 ()
Sets the values for the case with calculation_phase = 1.
void jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part2 ()
int jeod::LsodeFirstOrderODEIntegrator::manager_check_stop_conditions ()
verifies whether the convergence conditions have been met to end the cycle.
void jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part1 ()
The iteration loop for the integration process.
void jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2 ()
void jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part3 ()
void jeod::LsodeFirstOrderODEIntegrator::reset_integrator () override
Resets the integrator when the timestep changes or when identified as needing a reset.
void jeod::LsodeFirstOrderODEIntegrator::manager_set_calculation_phase_eq_2_reload ()
void jeod::LsodeFirstOrderODEIntegrator::calculate_epsilon ()
Identify the smallest double precision value, epsilon, such that the computer can distinguish (1+epsilon) from 1.
void jeod::LsodeFirstOrderODEIntegrator::calculate_integration_coefficients ()
Modified from original DCFODE subroutine.
void jeod::LsodeFirstOrderODEIntegrator::interpolate_y ()
Interpolates the zeroth-derivative of y Adapted from subroutine DINTDY, which was a general method for interpolating the K-th derivative of the dependent variable vector, y.
void jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_init ()
Modified from DPREPJ.
bool jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_loop ()
bool jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_wrap_up ()
void jeod::LsodeFirstOrderODEIntegrator::linear_chord_iteration ()
Modified from DSOLSY.
void jeod::LsodeFirstOrderODEIntegrator::load_ew_values ()
jeod::LsodeFirstOrderODEIntegrator::LsodeFirstOrderODEIntegrator ()
LsodeFirstOrderODEIntegrator default constructor.
jeod::LsodeFirstOrderODEIntegrator::LsodeFirstOrderODEIntegrator (const LsodeControlDataInterface &data_in, er7_utils::IntegrationControls &controls, unsigned int size)
LsodeFirstOrderODEIntegrator non-default constructor.
jeod::LsodeFirstOrderODEIntegrator::~LsodeFirstOrderODEIntegrator () override
LsodeFirstOrderODEIntegrator destructor.
void jeod::LsodeFirstOrderODEIntegrator::update_control_data ()
Gets the control data from where it can be populated in the constructor and verifies that the input control parameters are not out of sensible range.
LsodeFirstOrderODEIntegrator * jeod::LsodeFirstOrderODEIntegrator::create_copy () const override
Create a copy of 'this' LsodeFirstOrderODEIntegrator object.
double jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array (const double *v)
returns the RMS value of {V dot W}, where V and W are N-vectors.
double jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array (unsigned int ix, double **v)
returns RMS value of v[*][index]
int jeod::LsodeFirstOrderODEIntegrator::gauss_elim_factor ()
Factors a double array (arrays.lin_alg) by Gaussian elimination.
void jeod::LsodeFirstOrderODEIntegrator::linear_solver ()
Solves the equation Y' = A Y, with A = arrays.lin_alg.
unsigned int jeod::LsodeFirstOrderODEIntegrator::index_of_max_magnitude (unsigned int num_points, double **mx, int starting_ix)
Modified version of IDAMAX.
void jeod::LsodeFirstOrderODEIntegrator::load_derivatives (double *derivs)
Load the externally generated derivative values (incoming as y_dot)i into the array derivs.
jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::LsodeGeneralizedDerivSecondOrderODEIntegrator (const LsodeControlDataInterface &data_in, er7_utils::IntegrationControls &controls, const er7_utils::GeneralizedPositionDerivativeFunctions &deriv_funs, unsigned int position_size, unsigned int velocity_size)
non-default constructor
jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::LsodeGeneralizedDerivSecondOrderODEIntegrator (const LsodeGeneralizedDerivSecondOrderODEIntegrator &src)
LsodeGeneralizedDerivSecondOrderODEIntegrator copy constructor.
LsodeGeneralizedDerivSecondOrderODEIntegrator * jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::create_copy () const override
Clone a LsodeGeneralizedDerivSecondOrderODEIntegrator.
jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::~LsodeGeneralizedDerivSecondOrderODEIntegrator () override
LsodeGeneralizedDerivSecondOrderODEIntegrator destructor.
er7_utils::IntegratorResult jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double *accel, double *velocity, double *position) override
Propagate state via Lsode's method.
jeod::LsodeIntegrationControls::LsodeIntegrationControls (unsigned int num_stages)
LsodeIntegrationControls * jeod::LsodeIntegrationControls::create_copy () const override
Create a copy of 'this' StandardIntegrationControls object.
unsigned int jeod::LsodeIntegrationControls::integrate (double start_time, double sim_dt, er7_utils::TimeInterface &time_interface, er7_utils::IntegratorInterface &integ_interface, er7_utils::BaseIntegrationGroup &integ_group) override
Perform one step of the integration process.
jeod::LsodeIntegratorConstructor::LsodeIntegratorConstructor (const LsodeIntegratorConstructor &src)
static er7_utils::IntegratorConstructor * jeod::LsodeIntegratorConstructor::create_constructor ()
Named constructor; create an LsodeIntegratorConstructor instance.
er7_utils::IntegratorConstructor * jeod::LsodeIntegratorConstructor::create_copy () const override
Create a duplicate of the constructor.
er7_utils::IntegrationControls * jeod::LsodeIntegratorConstructor::create_integration_controls () const override
Create an integration controls that guides the Lsode integration process.
er7_utils::FirstOrderODEIntegrator * jeod::LsodeIntegratorConstructor::create_first_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls &controls) const override
Create an Lsode state integrator for a first order ODE.
er7_utils::SecondOrderODEIntegrator * jeod::LsodeIntegratorConstructor::create_second_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls &controls) const override
Create an Lsode state integrator for a simple second order ODE.
er7_utils::SecondOrderODEIntegrator * jeod::LsodeIntegratorConstructor::create_generalized_deriv_second_order_ode_integrator (unsigned int position_size, unsigned int velocity_size, const er7_utils::GeneralizedPositionDerivativeFunctions &deriv_funs, er7_utils::IntegrationControls &controls) const override
Create an Lsode state integrator for a generalized second order ODE where generalized position is advanced with the use of the position derivative function.
jeod::LsodeSecondOrderODEIntegrator::LsodeSecondOrderODEIntegrator (const LsodeControlDataInterface &data_in, er7_utils::IntegrationControls &controls, unsigned int size)
LsodeSecondOrderODEIntegrator non-default constructor.
jeod::LsodeSecondOrderODEIntegrator::LsodeSecondOrderODEIntegrator (const LsodeControlDataInterface &data_in, er7_utils::IntegrationControls &controls, const er7_utils::GeneralizedPositionDerivativeFunctions &deriv_funs, unsigned int position_size, unsigned int velocity_size)
jeod::LsodeSecondOrderODEIntegrator::~LsodeSecondOrderODEIntegrator () override
LsodeSecondOrderODEIntegrator destructor.
jeod::LsodeSimpleSecondOrderODEIntegrator::LsodeSimpleSecondOrderODEIntegrator (const LsodeControlDataInterface &data_in, er7_utils::IntegrationControls &controls, unsigned int size)
LsodeSimpleSecondOrderODEIntegrator non-default constructor.
LsodeSimpleSecondOrderODEIntegrator * jeod::LsodeSimpleSecondOrderODEIntegrator::create_copy () const override
er7_utils::IntegratorResult jeod::LsodeSimpleSecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double *accel, double *velocity, double *position) override
Propagate state via Lsode's method.
Detailed Description
Implements the LSODE integration technique, which is suitable for long arc integration.
Function Documentation
allocate_arrays() [1/2]
void LsodeDataArrays::allocate_arrays (unsigned int num_odes, LsodeControlDataInterface::CorrectorMethod corrector_method)
Allocates memory for the variable size arrays.
Definition at line 52 of file lsode_data_classes.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeDataArrays::allocated, jeod::LsodeDataArrays::error_weight, jeod::LsodeControlDataInterface::FunctionalIteration, jeod::LsodeDataArrays::history, jeod::LsodeControlDataInterface::JacobiNewtonInternalJac, jeod::LsodeDataArrays::lin_alg, jeod::LsodeDataArrays::lin_alg_index1, jeod::LsodeControlDataInterface::NewtonIterInternalJac, jeod::LsodeControlDataInterface::NewtonIterUserJac, jeod::LsodeDataArrays::num_odes, jeod::LsodeDataArrays::pivots, and jeod::LsodeDataArrays::save.
Referenced by jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part1().
allocate_arrays() [2/2]
void LsodeControlDataInterface::allocate_arrays ()
allocates space for vector-populated data to allow for restart
Definition at line 260 of file lsode_control_data_interface.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control, jeod::LsodeControlDataInterface::abs_tolerance_error_control_vec, jeod::LsodeControlDataInterface::error_control_vector_copied_over, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeControlDataInterface::num_odes_at_alloc, jeod::LsodeControlDataInterface::rel_tolerance_error_control, and jeod::LsodeControlDataInterface::rel_tolerance_error_control_vec.
Referenced by jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part1().
calculate_epsilon()
void LsodeFirstOrderODEIntegrator::calculate_epsilon () protected
Identify the smallest double precision value, epsilon, such that the computer can distinguish (1+epsilon) from 1.
Definition at line 58 of file lsode_first_order_ode_integrator__support.cc.
References jeod::Numerical::compare_exact(), jeod::LsodeFirstOrderODEIntegrator::epsilon, and jeod::LsodeFirstOrderODEIntegrator::sqrt_epsilon.
Referenced by jeod::LsodeFirstOrderODEIntegrator::LsodeFirstOrderODEIntegrator().
calculate_integration_coefficients()
void LsodeFirstOrderODEIntegrator::calculate_integration_coefficients () protected
Modified from original DCFODE subroutine.
calculate_integration_coefficients is called by dstode to set coefficients needed there. The coefficients for the current method, as given by the value of integration_method, are set for all orders and saved. The maximum order assumed here is 12 if integration_method = ImplicitAdamsNonStiff and 5 if integration_method = ImplicitBackDiffStiff.
NOTE - A smaller value of the maximum order is also allowed and may be set by the user with the value control_data.max_order, which gets copied to the protected value max_order_internal.
calculate_integration_coefficients is called once at the beginning of the problem, and again only if integration_method is changed.
The coefficients are stored in two arrays: method_coeffs_complete is a 13x12 array that contains a complete set of coefficients for the method test_coeffs_complete is a 3x12 array that contains the coefficients for local error tests and selection of the step size and/or order. The 1st set of 12 coeffs is for order method_order_current - 1 The 2nd set of 12 coeffs is for order method_order_current The 3rd set of 12 coeffs is for order method_order_current + 1
The coefficients in method_coeffs_complete are computed by a genetrating polynomial. For a given order (note that order changes during the integration process up to the maximum allowable, and is identified in the integrator as the variable method_order_current), abbreviate method_coeffs_complete[i][order-1] to mcc[i]
Then l(x) = mcc[0] + (mcc[1] * x) + (mcc[2] * x^2) + ... + mcc[order] * (x^order) For the implicit Adams methods, l(x) is given by dl/dx = (x+1)*(x+2)*...*(x+order-1)/(order-1)!, l(-1) = 0.; For the BDF methods, l(x) is given by l(x) = (x+1)*(x+2)* ... *(x+order) / ((order)! * (1 + 1/2 + ... + 1/order))
(! represents factorial)
Note that while method_coeffs_compelte is a rectangular array for convenience, it is effectively a triangular array since method_coeffs_complete[i][order-1] has no meaning for i >= (order + 2) order=1: method_coeffs_complete[0-1][0] order=2: method_coeffs_complete[0-2][1] ... order=12: method_coeffs_complete[0-12][11] Hence a 13x12 array.
Definition at line 119 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::ImplicitAdamsNonStiff, jeod::LsodeControlDataInterface::ImplicitBackDiffStiff, jeod::LsodeControlDataInterface::integration_method, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_complete, and jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_core().
check_interface_data()
void LsodeControlDataInterface::check_interface_data ()
verifies that the input data has legal values.
Definition at line 59 of file lsode_control_data_interface.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control_vec, jeod::LsodeControlDataInterface::CommonAbsSpecificRel, jeod::LsodeControlDataInterface::corrector_method, jeod::LsodeControlDataInterface::error_control_indicator, jeod::LsodeControlDataInterface::error_control_vector_copied_over, jeod::LsodeControlDataInterface::integration_method, jeod::LsodeControlDataInterface::max_num_small_step_warnings, jeod::LsodeControlDataInterface::max_num_steps, jeod::LsodeControlDataInterface::max_order, jeod::LsodeControlDataInterface::max_step_size, jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeControlDataInterface::rel_tolerance_error_control_vec, jeod::LsodeControlDataInterface::SpecificAbsCommonRel, and jeod::LsodeControlDataInterface::SpecificAbsSpecificRel.
Referenced by jeod::LsodeFirstOrderODEIntegrator::update_control_data().
create_constructor()
er7_utils::IntegratorConstructor * LsodeIntegratorConstructor::create_constructor () static
Named constructor; create an LsodeIntegratorConstructor instance.
The caller is responsible for deleting the returned object.
Returns
Newly created LsodeIntegratorConstructor instance.
Definition at line 64 of file lsode_integrator_constructor.cc.
create_copy() [1/5]
LsodeIntegrationControls * LsodeIntegrationControls::create_copy () const override
Create a copy of 'this' StandardIntegrationControls object.
Returns
Clone of 'this'.
Definition at line 56 of file lsode_integration_controls.cc.
create_copy() [2/5]
LsodeSimpleSecondOrderODEIntegrator * LsodeSimpleSecondOrderODEIntegrator::create_copy () const override
Definition at line 57 of file lsode_simple_second_order_ode_integrator.cc.
create_copy() [3/5]
LsodeGeneralizedDerivSecondOrderODEIntegrator * LsodeGeneralizedDerivSecondOrderODEIntegrator::create_copy () const override
Clone a LsodeGeneralizedDerivSecondOrderODEIntegrator.
Definition at line 81 of file lsode_generalized_second_order_ode_integrator.cc.
create_copy() [4/5]
er7_utils::IntegratorConstructor * LsodeIntegratorConstructor::create_copy () const override
Create a duplicate of the constructor.
The caller is responsible for deleting the returned object.
Returns
Duplicated constructor.
Definition at line 70 of file lsode_integrator_constructor.cc.
create_copy() [5/5]
LsodeFirstOrderODEIntegrator * LsodeFirstOrderODEIntegrator::create_copy () const override
Create a copy of 'this' LsodeFirstOrderODEIntegrator object.
Returns
Clone of 'this'.
Definition at line 119 of file lsode_first_order_ode_integrator__utility.cc.
create_first_order_ode_integrator()
er7_utils::FirstOrderODEIntegrator * LsodeIntegratorConstructor::create_first_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls & controls) const override
Create an Lsode state integrator for a first order ODE.
The caller is responsible for deleting the created object.
Returns
State integrator
Parameters
[in] size State size
[in,out] controls Integration controls
Definition at line 82 of file lsode_integrator_constructor.cc.
References jeod::LsodeIntegratorConstructor::data_interface.
create_generalized_deriv_second_order_ode_integrator()
er7_utils::SecondOrderODEIntegrator * LsodeIntegratorConstructor::create_generalized_deriv_second_order_ode_integrator (unsigned int position_size, unsigned int velocity_size, const er7_utils::GeneralizedPositionDerivativeFunctions & deriv_funs, er7_utils::IntegrationControls & controls) const override
Create an Lsode state integrator for a generalized second order ODE where generalized position is advanced with the use of the position derivative function.
The caller is responsible for deleting the created object.
Returns
State integrator
Parameters
[in] position_size Size of the generalized position
[in] velocity_size Size of the generalized velocity
[in] deriv_funs Position derivative functions container
[in,out] controls Integration controls
Definition at line 102 of file lsode_integrator_constructor.cc.
References jeod::LsodeIntegratorConstructor::data_interface.
create_integration_controls()
er7_utils::IntegrationControls * LsodeIntegratorConstructor::create_integration_controls () const override
Create an integration controls that guides the Lsode integration process.
The caller is responsible for deleting the created object.
Returns
Integration controls object
Definition at line 76 of file lsode_integrator_constructor.cc.
create_second_order_ode_integrator()
er7_utils::SecondOrderODEIntegrator * LsodeIntegratorConstructor::create_second_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls & controls) const override
Create an Lsode state integrator for a simple second order ODE.
The caller is responsible for deleting the created object.
Returns
State integrator
Parameters
[in] size State size
[in,out] controls Integration controls
Definition at line 92 of file lsode_integrator_constructor.cc.
References jeod::LsodeIntegratorConstructor::data_interface.
destroy_allocated_arrays() [1/2]
void LsodeDataArrays::destroy_allocated_arrays ()
Allows for refactoring and reallocation of newly sized arrays.
Definition at line 148 of file lsode_data_classes.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeDataArrays::allocated, jeod::LsodeDataArrays::error_weight, jeod::LsodeDataArrays::history, jeod::LsodeDataArrays::lin_alg, jeod::LsodeDataArrays::lin_alg_index1, jeod::LsodeDataArrays::num_odes, jeod::LsodeDataArrays::pivots, and jeod::LsodeDataArrays::save.
Referenced by jeod::LsodeDataArrays::~LsodeDataArrays(), and jeod::LsodeFirstOrderODEIntegrator::~LsodeFirstOrderODEIntegrator().
destroy_allocated_arrays() [2/2]
void LsodeControlDataInterface::destroy_allocated_arrays ()
De-allocates allocated array.
Definition at line 312 of file lsode_control_data_interface.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control, jeod::LsodeControlDataInterface::error_control_vector_copied_over, and jeod::LsodeControlDataInterface::rel_tolerance_error_control.
Referenced by jeod::LsodeFirstOrderODEIntegrator::~LsodeFirstOrderODEIntegrator().
gauss_elim_factor()
int LsodeFirstOrderODEIntegrator::gauss_elim_factor () protected
Factors a double array (arrays.lin_alg) by Gaussian elimination.
Modified version of DGEFA.
Definition at line 175 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::index_of_max_magnitude(), jeod::LsodeDataArrays::lin_alg, jeod::LsodeControlDataInterface::num_odes, and jeod::LsodeDataArrays::pivots.
Referenced by jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_wrap_up().
index_of_max_magnitude()
unsigned int LsodeFirstOrderODEIntegrator::index_of_max_magnitude (unsigned int num_points, double ** array, int start_ix) protected
Modified version of IDAMAX.
IDAMAX has 2 operations, one for situations in which the index increments by 1, and another for the converse. Since all instances in LSODE use the unit-increment method, that is the only one represented here. Search through matrix "array", starting at array[start_ix_1][start_ix_2] for the next "num_points" elements. The boolean search_ix_1 controls whether to increment index#1 (true), or index#2 (false). Method returns the searched index that corresponds to the largest magnitude.
Note
The only call to this method passed "k" in for both indices, so I stripped the second argument. If DGBFA gets implemented, it will have to be added back in; the call from DGBFA is for array starting at (M,K)
Definition at line 338 of file lsode_first_order_ode_integrator__utility.cc.
Referenced by jeod::LsodeFirstOrderODEIntegrator::gauss_elim_factor().
integrate() [1/4]
unsigned int LsodeIntegrationControls::integrate (double start_time, double sim_dt, er7_utils::TimeInterface & time_interface, er7_utils::IntegratorInterface & integ_interface, er7_utils::BaseIntegrationGroup & integ_group) override
Perform one step of the integration process.
Definition at line 69 of file lsode_integration_controls.cc.
References jeod::Numerical::compare_exact().
integrate() [2/4]
er7_utils::IntegratorResult LsodeSimpleSecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double * accel, double * velocity, double * position) override
Propagate state via Lsode's method.
Parameters
[in] dyn_dt Integration interval step, dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] accel Generalized acceleration vector.
[in,out] velocity Generalized velocity vector.
[in,out] position Generalized position vector.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 67 of file lsode_simple_second_order_ode_integrator.cc.
References jeod::LsodeSecondOrderODEIntegrator::first_order_integrator, jeod::LsodeFirstOrderODEIntegrator::integrate(), jeod::LsodeSecondOrderODEIntegrator::y, jeod::LsodeSecondOrderODEIntegrator::y_dot, and jeod::LsodeSecondOrderODEIntegrator::zeroth_derivative_size.
integrate() [3/4]
er7_utils::IntegratorResult LsodeGeneralizedDerivSecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double * accel, double * velocity, double * position) override
Propagate state via Lsode's method.
Parameters
[in] dyn_dt Integration interval step, dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] accel Generalized acceleration vector.
[in,out] velocity Generalized velocity vector.
[in,out] position Generalized position vector.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 101 of file lsode_generalized_second_order_ode_integrator.cc.
References jeod::LsodeSecondOrderODEIntegrator::first_derivative_size, jeod::LsodeSecondOrderODEIntegrator::first_order_integrator, jeod::LsodeFirstOrderODEIntegrator::integrate(), jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::posdot, jeod::LsodeSecondOrderODEIntegrator::y, jeod::LsodeSecondOrderODEIntegrator::y_dot, and jeod::LsodeSecondOrderODEIntegrator::zeroth_derivative_size.
integrate() [4/4]
er7_utils::IntegratorResult LsodeFirstOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double * y_dot, double * y) override
Propagate state via Lsode's method.
Propagate state via the LSODE method.
Parameters
[in] dyn_dt Integration interval step, dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in,out] y_dot Generalized velocity vector.
[in,out] y Generalized position vector.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 60 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::CycleStartFinish, jeod::LsodeFirstOrderODEIntegrator::DstodeResetStep, jeod::LsodeFirstOrderODEIntegrator::InitCalc, jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_iteration(), jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part2(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part2(), jeod::LsodeFirstOrderODEIntegrator::IterationLoop, jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_init(), jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_loop(), jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_wrap_up(), jeod::LsodeFirstOrderODEIntegrator::JacobianPrep, jeod::LsodeFirstOrderODEIntegrator::load_derivatives(), jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part2(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part3(), jeod::LsodeFirstOrderODEIntegrator::process_entry_point_cycle_start(), jeod::LsodeFirstOrderODEIntegrator::re_entry_point, jeod::LsodeFirstOrderODEIntegrator::ResetIterLoop, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_error, jeod::LsodeFirstOrderODEIntegrator::update_jacobian, jeod::LsodeFirstOrderODEIntegrator::y, and jeod::LsodeFirstOrderODEIntegrator::y_dot.
Referenced by jeod::LsodeSimpleSecondOrderODEIntegrator::integrate(), and jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::integrate().
integrator_compute_new_order()
void LsodeFirstOrderODEIntegrator::integrator_compute_new_order () protected
Computes the step-size scaling factors that will result once it is determined what happens to the order at the next step.
Definition at line 747 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataStode::dsm, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_check_step_error(), jeod::LsodeFirstOrderODEIntegrator::integrator_set_new_order(), jeod::LsodeFirstOrderODEIntegrator::integrator_wrapup(), jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::method_coeffs_current, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeDataStode::new_method_order, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::order_select_para, jeod::LsodeDataStode::step_ratio, jeod::LsodeDataStode::step_ratio_order_inc, and jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_prep(), and jeod::LsodeFirstOrderODEIntegrator::integrator_error_test_failed().
integrator_compute_new_order_check_step_error()
void LsodeFirstOrderODEIntegrator::integrator_compute_new_order_check_step_error () protected
Definition at line 817 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeFirstOrderODEIntegrator::integrator_set_new_order(), jeod::LsodeFirstOrderODEIntegrator::integrator_wrapup(), jeod::LsodeFirstOrderODEIntegrator::order_select_para, jeod::LsodeFirstOrderODEIntegrator::step_error, and jeod::LsodeDataStode::step_ratio.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order().
integrator_compute_new_order_prep()
void LsodeFirstOrderODEIntegrator::integrator_compute_new_order_prep () protected
The first steps in computing whether the order of the integrator should be changed.
Regardless of the success or failure of the step, the step-ratio factors for an increase, decrease, or retention of the integrator order are computed. In the case of failure, the increase ratio (data_stode.step_ratio_order_inc) has already been set to 0.0 to prevent an order increase. The largest of these factors is determined and the new order chosen accordingly. In the unusual case of equality, the priority is given to:
retain the order
increase the order (if inc = dec > same)
If the order is to be increased, we compute one additional scaled derivative.
This process is spread over four methods - integrator_compute_new_order_prep integrator_compute_new_order integrator_compute_new_order_check_step_error integrator_set_new_order
extracted from lines 520-540
Definition at line 725 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order(), jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::max_history_size, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeDataArrays::save, jeod::LsodeDataStode::step_ratio_order_inc, and jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_converged().
integrator_core()
void LsodeFirstOrderODEIntegrator::integrator_core () protected
integrator_core provides the front-end to all of the integrator_*i methods, which together perform one step of the integration of an initial value problem for a system of ordinary differential equations.
Modified from DSTODE
NOTES: The entire integrator_* suite is independent of the value of the iteration method indicator, corrector_method, when said is != 0, and hence is independent of the type of chord method used, or the Jacobian structure.
The value internal_state (JSTART) controls the direction that this method takes.
By commenting out substantial parts of the package that are not useful to the ER7 / JEOD / Trick implementation, the only viable values for internal_state are now 0 or 1. internal_state = 0 : take the first step. internal_state = 1 : take another step, continuing from the last. internal_state = -1 was associated with externally driven changes to the input aprameters, something we do not allow. internal_state = -2 is associated with the critical / singularity time avoidance, something we have not implemented.
Definition at line 78 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::calculate_integration_coefficients(), jeod::Numerical::compare_exact(), jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::convergence_factor, jeod::LsodeFirstOrderODEIntegrator::convergence_jacobian_flag, jeod::LsodeFirstOrderODEIntegrator::convergence_rate, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeControlDataInterface::integration_method, jeod::LsodeFirstOrderODEIntegrator::integrator_predict(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh(), jeod::LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change(), jeod::LsodeFirstOrderODEIntegrator::internal_state, jeod::LsodeDataStode::iredo, jeod::LsodeDataStode::iret, jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeFirstOrderODEIntegrator::iteration_matrix_singular, jeod::LsodeFirstOrderODEIntegrator::jacobian_current, jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::max_history_size, jeod::LsodeFirstOrderODEIntegrator::max_order_internal, jeod::LsodeFirstOrderODEIntegrator::max_step_increase_ratio, jeod::LsodeFirstOrderODEIntegrator::method_coeff_first, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_complete, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_current, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeFirstOrderODEIntegrator::modified_iteration_matrix_singular, jeod::LsodeDataStode::ncf, jeod::LsodeFirstOrderODEIntegrator::num_equations, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeFirstOrderODEIntegrator::num_predictor_elements, jeod::LsodeFirstOrderODEIntegrator::order_select_para, jeod::LsodeFirstOrderODEIntegrator::prev_integration_method, jeod::LsodeFirstOrderODEIntegrator::prev_step_size, jeod::LsodeFirstOrderODEIntegrator::rel_change_since_jacobian, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_at_last_jacobian_update, jeod::LsodeFirstOrderODEIntegrator::step_error, jeod::LsodeDataStode::step_ratio, jeod::LsodeFirstOrderODEIntegrator::step_size, jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete, jeod::LsodeDataStode::told, and jeod::LsodeFirstOrderODEIntegrator::update_jacobian.
Referenced by jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2().
integrator_corrector_converged()
void LsodeFirstOrderODEIntegrator::integrator_corrector_converged () protected
Starts the processing of a converged iteration.
Definition at line 588 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataStode::dsm, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_prep(), jeod::LsodeFirstOrderODEIntegrator::integrator_error_test_failed(), jeod::LsodeFirstOrderODEIntegrator::integrator_wrapup(), jeod::LsodeDataStode::iredo, jeod::LsodeFirstOrderODEIntegrator::iter_delta, jeod::LsodeFirstOrderODEIntegrator::iteration_count, jeod::LsodeFirstOrderODEIntegrator::jacobian_current, jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::max_history_size, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_current, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::num_steps_taken, jeod::LsodeFirstOrderODEIntegrator::order_select_para, jeod::LsodeFirstOrderODEIntegrator::prev_good_step_size, jeod::LsodeFirstOrderODEIntegrator::prev_method_order, jeod::LsodeFirstOrderODEIntegrator::step_error, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_iteration().
integrator_corrector_failed_part1()
void LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part1 () protected
The corrector iteration failed to converge.
If corrector_method != FunctionalIteration and the Jacobian is out of date, exit so that the Jacobian method can be called (externally) for the next try. Otherwise, try changing the step-size in part 2 of the failure recovery.
Extracted from DSTODE lines 410-430
Definition at line 516 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::convergence_jacobian_flag, jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part2(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part1(), jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeFirstOrderODEIntegrator::jacobian_current, and jeod::LsodeFirstOrderODEIntegrator::update_jacobian.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_iteration().
integrator_corrector_failed_part2()
void LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part2 () protected
Retracts the history array in the case that the correction iteration failed to converge with either functional iteration or with an up-to-date Jacobian.
If there are problems, the associated flags are set.
Definition at line 542 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::convergence_jacobian_flag, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh(), jeod::LsodeFirstOrderODEIntegrator::integrator_terminate(), jeod::LsodeDataStode::iredo, jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeControlDataInterface::max_num_conv_failure, jeod::LsodeFirstOrderODEIntegrator::max_step_increase_ratio, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeDataStode::ncf, jeod::LsodeFirstOrderODEIntegrator::num_equations, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_error, jeod::LsodeDataStode::step_ratio, jeod::LsodeFirstOrderODEIntegrator::step_size, jeod::LsodeDataStode::told, and jeod::LsodeFirstOrderODEIntegrator::update_jacobian.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part1(), and jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_wrap_up().
integrator_corrector_iteration()
void LsodeFirstOrderODEIntegrator::integrator_corrector_iteration () protected
Keeps looping through the iterations until convergence or failure.
Definition at line 411 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::convergence_factor, jeod::LsodeFirstOrderODEIntegrator::convergence_rate, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_converged(), jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part1(), jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeFirstOrderODEIntegrator::iter_delta, jeod::LsodeFirstOrderODEIntegrator::iteration_count, jeod::LsodeFirstOrderODEIntegrator::IterationLoop, jeod::LsodeFirstOrderODEIntegrator::linear_chord_iteration(), jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeControlDataInterface::max_correction_iters, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_current, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeFirstOrderODEIntegrator::modified_iteration_matrix_singular, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::prev_iter_delta, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::step_size, jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete, and jeod::LsodeFirstOrderODEIntegrator::y.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
integrator_error_test_failed()
void LsodeFirstOrderODEIntegrator::integrator_error_test_failed () protected
Restores the history array following the failure of the corrector for exceeding local error bounds.
Definition at line 663 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order(), jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part1(), jeod::LsodeFirstOrderODEIntegrator::integrator_terminate(), jeod::LsodeDataStode::iredo, jeod::LsodeFirstOrderODEIntegrator::max_step_increase_ratio, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeFirstOrderODEIntegrator::num_equations, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_error, jeod::LsodeDataStode::step_ratio_order_inc, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeDataStode::told.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_converged().
integrator_fail_reset_order_1_part1()
void LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part1 () protected
Repopulates the y-array from history, recomputes the original first derivatives, sets the order back to 1, and reduces the step size by a factor of 10.
Called when 3 or more failures have occured. It is assumed that the derivatives that have accumulated in the history array have errors of the wrong order. Hence the first derivative is recomputed, and the order is set to 1. Then the step-size is reduced by a factor of 10, and the step is retried. Repeat until successful, or the step reaches the minimum step-size.
If 10 failures occur, exit with step_error = -1.
This method is divided in two by a call to calculate the derivatives. Part1 precedes that call, the execution exits from the integrator back to the sim control engine; then on return to the integrator, execution immediately proceeds with part2.
extracted from lines 640-
Definition at line 878 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeFirstOrderODEIntegrator::DstodeResetStep, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_terminate(), jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, jeod::LsodeFirstOrderODEIntegrator::step_error, jeod::LsodeDataStode::step_ratio, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::y.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_error_test_failed().
integrator_fail_reset_order_1_part2()
void LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part2 () protected
Continue reset, with derivatives now at hand.
See integrator_fail_reset_order_1_part1 for details.
Definition at line 902 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_predict(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs(), jeod::LsodeDataStode::iret, jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::order_select_para, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::update_jacobian.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
integrator_predict()
void LsodeFirstOrderODEIntegrator::integrator_predict () protected
This section computes the predicted values by multiplying the history array by the Pascal Triangle matrix.
Extracted from DSTODE lines 200-215
Definition at line 343 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part1(), jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeControlDataInterface::max_num_steps_jacobian, jeod::LsodeFirstOrderODEIntegrator::max_rel_change_without_jacobian, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeFirstOrderODEIntegrator::num_equations, jeod::LsodeFirstOrderODEIntegrator::num_steps_taken, jeod::LsodeFirstOrderODEIntegrator::rel_change_since_jacobian, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_at_last_jacobian_update, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::update_jacobian.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_core(), jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part2(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh(), and jeod::LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change().
integrator_reset_iteration_loop_part1()
void LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part1 () protected
This method resets the iteration loop to the values generated by the integrator_predict method, which populated history[*][0].
Definition at line 378 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::iteration_count, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, jeod::LsodeFirstOrderODEIntegrator::ResetIterLoop, and jeod::LsodeFirstOrderODEIntegrator::y.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part1(), and jeod::LsodeFirstOrderODEIntegrator::integrator_predict().
integrator_reset_iteration_loop_part2()
void LsodeFirstOrderODEIntegrator::integrator_reset_iteration_loop_part2 () protected
This code follows part 1 after the break-out to get to the external calls, and completes the reset of the integration iteration loop.
Definition at line 395 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::iter_delta, jeod::LsodeControlDataInterface::num_odes, and jeod::LsodeFirstOrderODEIntegrator::prev_iter_delta.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
integrator_reset_method_coeffs()
void LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs () protected
Sets/resets the method_coeffs_current array.
Definition at line 238 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::convergence_factor, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeFirstOrderODEIntegrator::integrator_predict(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh(), jeod::LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change(), jeod::LsodeDataStode::iret, jeod::LsodeFirstOrderODEIntegrator::method_coeff_first, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_complete, jeod::LsodeFirstOrderODEIntegrator::method_coeffs_current, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeFirstOrderODEIntegrator::num_equations, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeFirstOrderODEIntegrator::num_predictor_elements, jeod::LsodeFirstOrderODEIntegrator::rel_change_since_jacobian, jeod::LsodeDataStode::step_ratio, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_core(), jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part2(), and jeod::LsodeFirstOrderODEIntegrator::integrator_set_new_order().
integrator_reset_yh()
void LsodeFirstOrderODEIntegrator::integrator_reset_yh () protected
Resets history arrays and time-step.
Definition at line 303 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_predict(), jeod::LsodeFirstOrderODEIntegrator::integrator_wrapup(), jeod::LsodeDataStode::iredo, jeod::LsodeFirstOrderODEIntegrator::max_step_increase_ratio, jeod::LsodeFirstOrderODEIntegrator::max_step_size_inv, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::order_select_para, jeod::LsodeFirstOrderODEIntegrator::rel_change_since_jacobian, jeod::LsodeDataStode::step_ratio, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_core(), jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part2(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs(), jeod::LsodeFirstOrderODEIntegrator::integrator_set_new_order(), and jeod::LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change().
integrator_set_new_order()
void LsodeFirstOrderODEIntegrator::integrator_set_new_order () protected
Sets the new order and the step-ratio for the next step - or the current step if redoing it.
Definition at line 840 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh(), jeod::LsodeDataStode::iret, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeDataStode::new_method_order, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeDataStode::step_ratio, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order(), and jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_check_step_error().
integrator_terminate()
void LsodeFirstOrderODEIntegrator::integrator_terminate () protected
this is the only succesful path back from integrator to manager.
All other returns from integrator_* back to manager_* are in response to a need for new derivatives and carry with them a modified re_entry_point to provide access back to the integrator on reentry. All returns with re_entry_point = CycleStartFinish should go through this method.
Definition at line 945 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeFirstOrderODEIntegrator::internal_state, jeod::LsodeFirstOrderODEIntegrator::prev_step_size, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part2(), jeod::LsodeFirstOrderODEIntegrator::integrator_error_test_failed(), jeod::LsodeFirstOrderODEIntegrator::integrator_fail_reset_order_1_part1(), and jeod::LsodeFirstOrderODEIntegrator::integrator_wrapup().
integrator_test_stepsize_change()
void LsodeFirstOrderODEIntegrator::integrator_test_stepsize_change () protected
Tests h against old h.
Definition at line 280 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::Numerical::compare_exact(), jeod::LsodeFirstOrderODEIntegrator::data_stode, jeod::LsodeFirstOrderODEIntegrator::integrator_predict(), jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh(), jeod::LsodeDataStode::iredo, jeod::LsodeFirstOrderODEIntegrator::prev_step_size, jeod::LsodeDataStode::step_ratio, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_core(), and jeod::LsodeFirstOrderODEIntegrator::integrator_reset_method_coeffs().
integrator_wrapup()
void LsodeFirstOrderODEIntegrator::integrator_wrapup () protected
Wraps up the completion of the integrator.
Definition at line 925 of file lsode_first_order_ode_integrator__integrator.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::integrator_terminate(), jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::prev_method_order, and jeod::LsodeFirstOrderODEIntegrator::test_coeffs_complete.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order(), jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_check_step_error(), jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_converged(), and jeod::LsodeFirstOrderODEIntegrator::integrator_reset_yh().
interpolate_y()
void LsodeFirstOrderODEIntegrator::interpolate_y () protected
Interpolates the zeroth-derivative of y Adapted from subroutine DINTDY, which was a general method for interpolating the K-th derivative of the dependent variable vector, y.
Implementation notes - DINTDY was called exclusively with three input values that always matched.
Argument #1 T (time). Calls to DINTDY always passed TOUT (now cycle_target_time) in for T
Argument #2 K (order). Calls to DINTDY always passed 0 in for K
Argument #5 DKY (value). DKY is the value that DINTDY interpolates.i Calls to DINTDY always passed Y in for DKY. This routine uses y directly in place of DKY, so can only interpolate the 0-th derivative (since that is y), and always evaluates at cycle_target_time. replaced accordingly.
The computed values are gotten by interpolation using the Nordsieck history array, arrays.history. The formula for Y is:
Y[i] = sum {j=0 to method_order_current} { (cycle_target_time - stage_target_time)^(j) * arrays.history[i-1][j] / h^j}
Definition at line 263 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::epsilon, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeFirstOrderODEIntegrator::num_nordsiek_cols, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::prev_good_step_size, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::y.
Referenced by jeod::LsodeFirstOrderODEIntegrator::manager_check_stop_conditions(), and jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part3().
jacobian_prep_init()
void LsodeFirstOrderODEIntegrator::jacobian_prep_init () protected
Modified from DPREPJ.
DPREPJ was called by DSTODE to compute and process the matrix P = I - h*el(1)*J , where J is an approximation to the Jacobian.
NOTES
DPREPJ has been split into 3 parts, book-ended by the external-calls. jacobian_prep_init contains the code that precededs the first external-call jacobian_prep_loop contains the code that continues to loop according to the limits as written is DPREPJ. jacobian_prep_wrap_up contains the code that follows successful completion of the looping section of DPREPJ.
Note that the division in this implementation is not linear with that in the original Fortran. The external calls within the original fortran are embedded within switch-blocks and for loops; the return points - to go to the next routine will pick up from one of several locations in the Fortran code, depending on the configuration at the time the external call was made.
For the ER7_Utils / JEOD / Trick implementation, the derivative/jac calls must be external to the integrate call, so we must fully back out and then reenter. Rentry goes to jacobian_prep_loop.
Some variables that were local have been moved to the class so that their value is not lost in going from jacobian_prep_init to jacobian_prep_loop. These are typically identified with ***_dprepj to indicate that their sole purpose is within dprepj (the original name of the jacobian_prep_* routines).
Here the jacobian is computed by the user-supplied routine JAC if corrector_method = NewtonIterUserJac or NewtonIterUserBandJac, or by finite differencing if corrector_method = NewtonIterInternalJac, JacobiNewtonInternalJac, or NewtonIterInternalBandJac.
If corrector_method = JacobiNewtonInternalJac, a diagonal approximation to the Jacobian is used. The Jacobian is stored in arrays lin_alg
If corrector_method != JacobiNewtonInternalJac, P is subjected to LU decomposition in preparation for later solution of linear systems with P as coefficient matrix. This is done by gauss_elim_factor (DGEFA) if corrector_method = NewtonIterUserJac or NewtonIterInternalJac, and by linear_solver (DGBFA) if corrector_method = NewtonIterUserBandJac or NewtonIterInternalBandJac.
Note that the corrector_method using the banded Jacobians is not supported in this release, so linear_solver is not used.
FTEM and ACOR were effectively the same, now arrays.accum_correction. SAVF is now arrays.save. WM is now arrays.lin_alg
Definition at line 374 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::corrector_method, jeod::LsodeFirstOrderODEIntegrator::data_prepj, jeod::LsodeFirstOrderODEIntegrator::epsilon, jeod::LsodeDataArrays::error_weight, jeod::LsodeDataJacobianPrep::fac, jeod::LsodeControlDataInterface::FunctionalIteration, jeod::LsodeDataArrays::history, jeod::LsodeDataJacobianPrep::hl0, jeod::LsodeDataJacobianPrep::index, jeod::LsodeDataJacobianPrep::index_max, jeod::LsodeFirstOrderODEIntegrator::iteration_matrix_singular, jeod::LsodeFirstOrderODEIntegrator::jacobian_current, jeod::LsodeFirstOrderODEIntegrator::JacobianPrep, jeod::LsodeControlDataInterface::JacobiNewtonInternalJac, jeod::LsodeDataArrays::lin_alg, jeod::LsodeDataArrays::lin_alg_1, jeod::LsodeDataArrays::lin_alg_2, jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::method_coeff_first, jeod::LsodeControlDataInterface::NewtonIterInternalBandJac, jeod::LsodeControlDataInterface::NewtonIterInternalJac, jeod::LsodeControlDataInterface::NewtonIterUserBandJac, jeod::LsodeControlDataInterface::NewtonIterUserJac, jeod::LsodeFirstOrderODEIntegrator::num_jacobian_evals, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeDataJacobianPrep::r0, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::step_size, jeod::LsodeFirstOrderODEIntegrator::y, and jeod::LsodeDataJacobianPrep::yj.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
jacobian_prep_loop()
bool LsodeFirstOrderODEIntegrator::jacobian_prep_loop () protected
Definition at line 515 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeDataArrays::accum_correction, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::corrector_method, jeod::LsodeFirstOrderODEIntegrator::data_prepj, jeod::LsodeDataArrays::error_weight, jeod::LsodeDataJacobianPrep::fac, jeod::LsodeControlDataInterface::FunctionalIteration, jeod::LsodeDataJacobianPrep::hl0, jeod::LsodeDataJacobianPrep::index, jeod::LsodeDataJacobianPrep::index_max, jeod::LsodeControlDataInterface::JacobiNewtonInternalJac, jeod::LsodeDataArrays::lin_alg, jeod::LsodeDataArrays::lin_alg_1, jeod::LsodeFirstOrderODEIntegrator::load_derivatives(), jeod::LsodeControlDataInterface::NewtonIterInternalBandJac, jeod::LsodeControlDataInterface::NewtonIterInternalJac, jeod::LsodeControlDataInterface::NewtonIterUserBandJac, jeod::LsodeControlDataInterface::NewtonIterUserJac, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeDataJacobianPrep::r0, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::y, and jeod::LsodeDataJacobianPrep::yj.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
jacobian_prep_wrap_up()
bool LsodeFirstOrderODEIntegrator::jacobian_prep_wrap_up () protected
Definition at line 612 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::convergence_rate, jeod::LsodeControlDataInterface::corrector_method, jeod::LsodeFirstOrderODEIntegrator::data_prepj, jeod::LsodeFirstOrderODEIntegrator::epsilon, jeod::LsodeDataArrays::error_weight, jeod::LsodeControlDataInterface::FunctionalIteration, jeod::LsodeFirstOrderODEIntegrator::gauss_elim_factor(), jeod::LsodeDataArrays::history, jeod::LsodeDataJacobianPrep::hl0, jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_failed_part2(), jeod::LsodeFirstOrderODEIntegrator::iteration_matrix_singular, jeod::LsodeControlDataInterface::JacobiNewtonInternalJac, jeod::LsodeDataArrays::lin_alg, jeod::LsodeFirstOrderODEIntegrator::load_derivatives(), jeod::LsodeControlDataInterface::NewtonIterInternalBandJac, jeod::LsodeControlDataInterface::NewtonIterInternalJac, jeod::LsodeControlDataInterface::NewtonIterUserBandJac, jeod::LsodeControlDataInterface::NewtonIterUserJac, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::num_steps_taken, jeod::LsodeFirstOrderODEIntegrator::rel_change_since_jacobian, jeod::LsodeDataArrays::save, jeod::LsodeFirstOrderODEIntegrator::step_at_last_jacobian_update, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::update_jacobian.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
linear_chord_iteration()
void LsodeFirstOrderODEIntegrator::linear_chord_iteration () protected
Modified from DSOLSY.
This routine manages the solution of the linear system arising from a chord iteration. It is called if corrector_method != FunctionalIteration.
If corrector_method == NewtonIterUserJac || NewtonIterInternalJac, it calls linear_solver (was DGESL). If corrector_method = JacobiNewtonInternalJac it updates the coefficient hl0 = step_size * method_coeff_first (previously H*EL0) in the diagonal matrix, and then computes the solution.
Definition at line 736 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::Numerical::compare_exact(), jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::corrector_method, jeod::LsodeControlDataInterface::FunctionalIteration, jeod::LsodeControlDataInterface::JacobiNewtonInternalJac, jeod::LsodeDataArrays::lin_alg, jeod::LsodeDataArrays::lin_alg_2, jeod::LsodeFirstOrderODEIntegrator::linear_solver(), jeod::LsodeFirstOrderODEIntegrator::method_coeff_first, jeod::LsodeFirstOrderODEIntegrator::modified_iteration_matrix_singular, jeod::LsodeControlDataInterface::NewtonIterInternalBandJac, jeod::LsodeControlDataInterface::NewtonIterInternalJac, jeod::LsodeControlDataInterface::NewtonIterUserBandJac, jeod::LsodeControlDataInterface::NewtonIterUserJac, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::step_size, and jeod::LsodeFirstOrderODEIntegrator::y.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_iteration().
linear_solver()
void LsodeFirstOrderODEIntegrator::linear_solver () protected
Solves the equation Y' = A Y, with A = arrays.lin_alg.
Definition at line 254 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::lin_alg, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeDataArrays::pivots, and jeod::LsodeFirstOrderODEIntegrator::y.
Referenced by jeod::LsodeFirstOrderODEIntegrator::linear_chord_iteration().
load_derivatives()
void LsodeFirstOrderODEIntegrator::load_derivatives (double * derivs) protected
Load the externally generated derivative values (incoming as y_dot)i into the array derivs.
Definition at line 361 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::num_odes, and jeod::LsodeFirstOrderODEIntegrator::y_dot.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate(), jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_loop(), and jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_wrap_up().
load_ew_values()
void LsodeFirstOrderODEIntegrator::load_ew_values () protected
Definition at line 800 of file lsode_first_order_ode_integrator__support.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeControlDataInterface::CommonAbsCommonRel, jeod::LsodeControlDataInterface::CommonAbsSpecificRel, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::error_control_indicator, jeod::LsodeDataArrays::error_weight, jeod::LsodeDataArrays::history, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeControlDataInterface::rel_tolerance_error_control, jeod::LsodeControlDataInterface::SpecificAbsCommonRel, and jeod::LsodeControlDataInterface::SpecificAbsSpecificRel.
Referenced by jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part2(), and jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part1().
LsodeControlDataInterface()
LsodeControlDataInterface::LsodeControlDataInterface ()
constructor
Definition at line 50 of file lsode_control_data_interface.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control_vec, and jeod::LsodeControlDataInterface::rel_tolerance_error_control_vec.
LsodeFirstOrderODEIntegrator() [1/2]
LsodeFirstOrderODEIntegrator::LsodeFirstOrderODEIntegrator ()
LsodeFirstOrderODEIntegrator default constructor.
Definition at line 52 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::calculate_epsilon().
LsodeFirstOrderODEIntegrator() [2/2]
LsodeFirstOrderODEIntegrator::LsodeFirstOrderODEIntegrator (const LsodeControlDataInterface & data_in, er7_utils::IntegrationControls & controls, unsigned int size)
LsodeFirstOrderODEIntegrator non-default constructor.
Parameters
[in] data_in state variable data
[in] size State size
[in,out] controls Integration controls
Definition at line 59 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::calculate_epsilon(), jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::num_odes, and jeod::LsodeFirstOrderODEIntegrator::update_control_data().
LsodeGeneralizedDerivSecondOrderODEIntegrator() [1/2]
LsodeGeneralizedDerivSecondOrderODEIntegrator::LsodeGeneralizedDerivSecondOrderODEIntegrator (const LsodeGeneralizedDerivSecondOrderODEIntegrator & src)
LsodeGeneralizedDerivSecondOrderODEIntegrator copy constructor.
Copy Constructor.
Parameters
[in] src Item to be copied.
Definition at line 67 of file lsode_generalized_second_order_ode_integrator.cc.
LsodeGeneralizedDerivSecondOrderODEIntegrator() [2/2]
LsodeGeneralizedDerivSecondOrderODEIntegrator::LsodeGeneralizedDerivSecondOrderODEIntegrator (const LsodeControlDataInterface & data_in, er7_utils::IntegrationControls & controls, const er7_utils::GeneralizedPositionDerivativeFunctions & deriv_funs, unsigned int position_size, unsigned int velocity_size)
non-default constructor
Definition at line 53 of file lsode_generalized_second_order_ode_integrator.cc.
References jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::posdot.
LsodeIntegrationControls()
LsodeIntegrationControls::LsodeIntegrationControls (unsigned int num_stages) explicit
Definition at line 51 of file lsode_integration_controls.cc.
LsodeIntegratorConstructor()
LsodeIntegratorConstructor::LsodeIntegratorConstructor (const LsodeIntegratorConstructor & src)
Definition at line 57 of file lsode_integrator_constructor.cc.
LsodeSecondOrderODEIntegrator() [1/2]
LsodeSecondOrderODEIntegrator::LsodeSecondOrderODEIntegrator (const LsodeControlDataInterface & data_in, er7_utils::IntegrationControls & controls, unsigned int size) protected
LsodeSecondOrderODEIntegrator non-default constructor.
Parameters
[in] data_in LSODE-specific control data.
[in,out] controls Integration controls.
[in] size State size.
Definition at line 52 of file lsode_second_order_ode_integrator.cc.
References jeod::LsodeSecondOrderODEIntegrator::arrays_allocated, jeod::LsodeSecondOrderODEIntegrator::y, and jeod::LsodeSecondOrderODEIntegrator::y_dot.
LsodeSecondOrderODEIntegrator() [2/2]
LsodeSecondOrderODEIntegrator::LsodeSecondOrderODEIntegrator (const LsodeControlDataInterface & data_in, er7_utils::IntegrationControls & controls, const er7_utils::GeneralizedPositionDerivativeFunctions & deriv_funs, unsigned int position_size, unsigned int velocity_size) protected
Definition at line 68 of file lsode_second_order_ode_integrator.cc.
References jeod::LsodeSecondOrderODEIntegrator::arrays_allocated, jeod::LsodeSecondOrderODEIntegrator::y, and jeod::LsodeSecondOrderODEIntegrator::y_dot.
LsodeSimpleSecondOrderODEIntegrator()
LsodeSimpleSecondOrderODEIntegrator::LsodeSimpleSecondOrderODEIntegrator (const LsodeControlDataInterface & data_in, er7_utils::IntegrationControls & controls, unsigned int size)
LsodeSimpleSecondOrderODEIntegrator non-default constructor.
Parameters
[in] data_in State Variable Data
[in] size State size
[in,out] controls Integration controls
Definition at line 49 of file lsode_simple_second_order_ode_integrator.cc.
magnitude_of_weighted_array() [1/2]
double LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array (const double * v) protected
returns the RMS value of {V dot W}, where V and W are N-vectors.
Modified version of DVNORM
The only places DVNORM is used, it is multiplying some array by the error_weight array (arrays.error_weight) across control_data.num_odes terms. These values are fixed for our application, and do not need to be passed in.
We provide two implementations, one for a one-dimensional array, and one for a two-dimensional array in which the first index is the variable.
Parameters
v array
Definition at line 141 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::error_weight, and jeod::LsodeControlDataInterface::num_odes.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order(), jeod::LsodeFirstOrderODEIntegrator::integrator_compute_new_order_prep(), jeod::LsodeFirstOrderODEIntegrator::integrator_core(), jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_converged(), jeod::LsodeFirstOrderODEIntegrator::integrator_corrector_iteration(), jeod::LsodeFirstOrderODEIntegrator::jacobian_prep_init(), jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part2(), and jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2().
magnitude_of_weighted_array() [2/2]
double LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array (unsigned int index, double ** v) protected
returns RMS value of v[*][index]
Modified version of DVNORM, second implementation.
Parameters
index use this index
v array
Definition at line 159 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::error_weight, and jeod::LsodeControlDataInterface::num_odes.
manager_check_stop_conditions()
int LsodeFirstOrderODEIntegrator::manager_check_stop_conditions () protected
verifies whether the convergence conditions have been met to end the cycle.
Definition at line 528 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::calculation_task, jeod::LsodeFirstOrderODEIntegrator::CompleteCycle, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::interpolate_y(), jeod::LsodeFirstOrderODEIntegrator::Normal, jeod::LsodeFirstOrderODEIntegrator::NormalWithSingularity, jeod::LsodeFirstOrderODEIntegrator::num_steps_taken, jeod::LsodeFirstOrderODEIntegrator::OneStep, jeod::LsodeFirstOrderODEIntegrator::OneStepWithSingularity, jeod::LsodeFirstOrderODEIntegrator::prior_num_steps, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::process_entry_point_cycle_start().
manager_initialize_calculation_part1()
void LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part1 () protected
Sets the values for the case with calculation_phase = 1.
Definition at line 342 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeDataArrays::allocate_arrays(), jeod::LsodeControlDataInterface::allocate_arrays(), jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::corrector_method, jeod::LsodeFirstOrderODEIntegrator::InitCalc, jeod::LsodeFirstOrderODEIntegrator::internal_state, jeod::LsodeControlDataInterface::is_corrector_method_functional_iteration(), jeod::LsodeDataArrays::lin_alg_1, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, and jeod::LsodeFirstOrderODEIntegrator::sqrt_epsilon.
Referenced by jeod::LsodeFirstOrderODEIntegrator::process_entry_point_cycle_start().
manager_initialize_calculation_part2()
void LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part2 () protected
Definition at line 389 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control, jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeControlDataInterface::CommonAbsSpecificRel, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::epsilon, jeod::LsodeControlDataInterface::error_control_indicator, jeod::LsodeDataArrays::error_weight, jeod::LsodeDataArrays::history, jeod::LsodeControlDataInterface::initial_step_size, jeod::LsodeFirstOrderODEIntegrator::load_ew_values(), jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::max_step_size_inv, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeControlDataInterface::rel_tolerance_error_control, jeod::LsodeControlDataInterface::SpecificAbsCommonRel, jeod::LsodeControlDataInterface::SpecificAbsSpecificRel, jeod::LsodeFirstOrderODEIntegrator::step_size, jeod::LsodeFirstOrderODEIntegrator::y, and jeod::LsodeFirstOrderODEIntegrator::y_dot.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
manager_integration_loop_part1()
void LsodeFirstOrderODEIntegrator::manager_integration_loop_part1 () protected
The iteration loop for the integration process.
Definition at line 644 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::error_weight, jeod::LsodeFirstOrderODEIntegrator::load_ew_values(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2(), jeod::LsodeControlDataInterface::max_num_steps, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::num_steps_taken, jeod::LsodeFirstOrderODEIntegrator::prior_num_steps, and jeod::LsodeFirstOrderODEIntegrator::stage_target_time.
Referenced by jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part3(), and jeod::LsodeFirstOrderODEIntegrator::process_entry_point_cycle_start().
manager_integration_loop_part2()
void LsodeFirstOrderODEIntegrator::manager_integration_loop_part2 () protected
Definition at line 700 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::Numerical::compare_exact(), jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::CycleStartFinish, jeod::LsodeFirstOrderODEIntegrator::epsilon, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::integrator_core(), jeod::LsodeFirstOrderODEIntegrator::magnitude_of_weighted_array(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part3(), jeod::LsodeControlDataInterface::max_num_small_step_warnings, jeod::LsodeFirstOrderODEIntegrator::num_small_step_warnings, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate(), and jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part1().
manager_integration_loop_part3()
void LsodeFirstOrderODEIntegrator::manager_integration_loop_part3 () protected
Definition at line 765 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::calculation_task, jeod::LsodeFirstOrderODEIntegrator::CompleteCycle, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::initialized, jeod::LsodeFirstOrderODEIntegrator::interpolate_y(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part1(), jeod::LsodeControlDataInterface::min_step_size, jeod::LsodeFirstOrderODEIntegrator::Normal, jeod::LsodeFirstOrderODEIntegrator::NormalWithSingularity, jeod::LsodeFirstOrderODEIntegrator::OneStep, jeod::LsodeFirstOrderODEIntegrator::OneStepWithSingularity, jeod::LsodeFirstOrderODEIntegrator::stage_target_time, jeod::LsodeFirstOrderODEIntegrator::step_error, and jeod::LsodeFirstOrderODEIntegrator::step_size.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate(), and jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part2().
manager_set_calculation_phase_eq_2_reload()
void LsodeFirstOrderODEIntegrator::manager_set_calculation_phase_eq_2_reload () protected
Definition at line 917 of file lsode_first_order_ode_integrator__manager.cc.
process_entry_point_cycle_start()
void LsodeFirstOrderODEIntegrator::process_entry_point_cycle_start () protected
The code block from the main integrate routine for re_entry_point=CycleStartFinish.
Definition at line 269 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::first_pass, jeod::LsodeControlDataInterface::initial_step_size, jeod::LsodeFirstOrderODEIntegrator::initialized, jeod::LsodeFirstOrderODEIntegrator::manager_check_stop_conditions(), jeod::LsodeFirstOrderODEIntegrator::manager_initialize_calculation_part1(), jeod::LsodeFirstOrderODEIntegrator::manager_integration_loop_part1(), jeod::LsodeFirstOrderODEIntegrator::num_equations, jeod::LsodeControlDataInterface::num_odes, and jeod::LsodeFirstOrderODEIntegrator::stage_target_time.
Referenced by jeod::LsodeFirstOrderODEIntegrator::integrate().
reset_integrator()
void LsodeFirstOrderODEIntegrator::reset_integrator () override
Resets the integrator when the timestep changes or when identified as needing a reset.
Definition at line 893 of file lsode_first_order_ode_integrator__manager.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeFirstOrderODEIntegrator::cycle_target_time, jeod::LsodeFirstOrderODEIntegrator::first_pass, jeod::LsodeDataArrays::history, jeod::LsodeFirstOrderODEIntegrator::InitCalc, jeod::LsodeControlDataInterface::initial_step_size, jeod::LsodeFirstOrderODEIntegrator::method_order_current, jeod::LsodeControlDataInterface::num_odes, jeod::LsodeFirstOrderODEIntegrator::prev_good_step_size, jeod::LsodeFirstOrderODEIntegrator::re_entry_point, and jeod::LsodeFirstOrderODEIntegrator::stage_target_time.
Referenced by jeod::LsodeSecondOrderODEIntegrator::reset_integrator().
set_abs_tol()
void LsodeControlDataInterface::set_abs_tol (int index, double value)
Definition at line 382 of file lsode_control_data_interface.cc.
References jeod::LsodeControlDataInterface::abs_tolerance_error_control, jeod::LsodeControlDataInterface::abs_tolerance_error_control_vec, jeod::LsodeControlDataInterface::error_control_vector_copied_over, and jeod::LsodeControlDataInterface::num_odes_at_alloc.
set_rel_tol()
void LsodeControlDataInterface::set_rel_tol (int index, double value)
set values from external
Definition at line 325 of file lsode_control_data_interface.cc.
References jeod::LsodeControlDataInterface::error_control_vector_copied_over, jeod::LsodeControlDataInterface::num_odes_at_alloc, jeod::LsodeControlDataInterface::rel_tolerance_error_control, and jeod::LsodeControlDataInterface::rel_tolerance_error_control_vec.
update_control_data()
void LsodeFirstOrderODEIntegrator::update_control_data ()
Gets the control data from where it can be populated in the constructor and verifies that the input control parameters are not out of sensible range.
Definition at line 88 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeControlDataInterface::check_interface_data(), jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeControlDataInterface::ImplicitAdamsNonStiff, jeod::LsodeControlDataInterface::integration_method, jeod::LsodeControlDataInterface::max_order, jeod::LsodeFirstOrderODEIntegrator::max_order_internal, jeod::LsodeControlDataInterface::max_step_size, and jeod::LsodeFirstOrderODEIntegrator::max_step_size_inv.
Referenced by jeod::LsodeFirstOrderODEIntegrator::LsodeFirstOrderODEIntegrator().
~LsodeFirstOrderODEIntegrator()
LsodeFirstOrderODEIntegrator::~LsodeFirstOrderODEIntegrator () override
LsodeFirstOrderODEIntegrator destructor.
Definition at line 74 of file lsode_first_order_ode_integrator__utility.cc.
References jeod::LsodeFirstOrderODEIntegrator::arrays, jeod::LsodeFirstOrderODEIntegrator::control_data, jeod::LsodeDataArrays::destroy_allocated_arrays(), jeod::LsodeControlDataInterface::destroy_allocated_arrays(), and jeod::LsodeFirstOrderODEIntegrator::first_pass.
~LsodeGeneralizedDerivSecondOrderODEIntegrator()
LsodeGeneralizedDerivSecondOrderODEIntegrator::~LsodeGeneralizedDerivSecondOrderODEIntegrator () override
LsodeGeneralizedDerivSecondOrderODEIntegrator destructor.
Destructor.
Definition at line 95 of file lsode_generalized_second_order_ode_integrator.cc.
References jeod::LsodeGeneralizedDerivSecondOrderODEIntegrator::posdot.
~LsodeSecondOrderODEIntegrator()
LsodeSecondOrderODEIntegrator::~LsodeSecondOrderODEIntegrator () override
LsodeSecondOrderODEIntegrator destructor.
Definition at line 86 of file lsode_second_order_ode_integrator.cc.
References jeod::LsodeSecondOrderODEIntegrator::arrays_allocated, jeod::LsodeSecondOrderODEIntegrator::y, and jeod::LsodeSecondOrderODEIntegrator::y_dot.