JEOD: jeod::JeodMemoryTypeDescriptorDerived< Type > Class Template Reference
jeod::JeodMemoryTypeDescriptorDerived< Type > Class Template Reference
Extends JeodMemoryTypeDescriptor to describe a specific type.
#include <memory_type.hh>
Public Types
typedef JeodMemoryTypeDescriptorDerived< Type > TypeDescriptor
This class.
typedef JeodSimEngineAttributes< Type, std::is_class< Type >::value > Attributes
Attributes for the Type.
Public Member Functions
JeodMemoryTypeDescriptorDerived (bool is_exportable=true)
Default constructor.
JeodMemoryTypeDescriptorDerived (const JeodMemoryTypeDescriptorDerived &src)
Copy constructor; pass-through to the parent class equivalent.
~JeodMemoryTypeDescriptorDerived () override
Destructor.
JeodMemoryTypeDescriptor * clone () const override
Create a copy of the descriptor.
bool is_structured (void) const override
Indicate whether the type associated with the descriptor is a structured (non-primitive, non-pointer) type.
void * construct_array (std::size_t nelem, void *addr) const override
Construct an array of objects of the type.
const void * most_derived_pointer (const void *addr) const override
Find the most-derived object corresponding to the input pointer.
void * most_derived_pointer (void *addr) const override
Find the most-derived object corresponding to the input pointer.
Public Member Functions inherited from jeod::JeodMemoryTypeDescriptor
JeodMemoryTypeDescriptor (const std::type_info &obj_typeid, const struct ATTRIBUTES_tag &type_attr, std::size_t type_size, bool is_exportable=true)
Non-default constructor.
JeodMemoryTypeDescriptor (const JeodMemoryTypeDescriptor &src)
Copy constructor.
virtual ~JeodMemoryTypeDescriptor ()
Destructor.
const std::type_info & get_typeid (void) const
Get the type info for the type.
const std::string & get_name (void) const
Get the name of the type.
std::size_t get_size (void) const
Get the size of the type.
const struct ATTRIBUTES_tag & get_attr (void) const
Get the simulation engine attributes for the type.
bool get_register_instances (void) const
Get the simulation engine attributes for the type.
std::size_t dimensionality (void) const
Determine the dimensionality of the type.
std::size_t buffer_size (unsigned int nelems) const
Compute the size of a buffer.
std::size_t buffer_size (const JeodMemoryItem &item) const
Compute the size of a buffer.
const void * buffer_end (const void *addr, unsigned int nelems) const
Compute the address of the byte just past the end a buffer.
const void * buffer_end (const void *addr, const JeodMemoryItem &item) const
Compute the address of the byte just past the end a buffer.
const std::string type_spec (const JeodMemoryItem &item) const
Construct a type specification string.
void destroy_memory (bool placement_new, bool is_array, unsigned int nelem, void *addr) const
Destroy memory.
Protected Member Functions
void delete_array (void *addr) const override
Delete an array of instances of type Type.
void delete_object (void *addr) const override
Delete a single instance of type Type.
void destruct_array (std::size_t nelem, void *addr) const override
Destroy an array of nelem instances of type Type.
Private Member Functions
JeodMemoryTypeDescriptorDerived & operator= (const JeodMemoryTypeDescriptorDerived &)
Not implemented.
Additional Inherited Members
Static Public Member Functions inherited from jeod::JeodMemoryTypeDescriptor
static void set_check_for_registration_errors (bool val)
Enable/disable registration error messages.
Static Protected Member Functions inherited from jeod::JeodMemoryTypeDescriptor
static std::string initialize_type_name (const char *type_name)
The jeod_alloc.hh macros insert a space between the type name and the asterisks.
static std::size_t pointer_dimension (const std::string &demangled_name)
Get the pointer dimensionality of the type.
static const JeodMemoryTypeDescriptor * base_type (const std::string &demangled_name)
Get the descriptor for the base (non-pointer) of some pointer type.
Protected Attributes inherited from jeod::JeodMemoryTypeDescriptor
const std::type_info & obj_id
The RTTI descriptor of the type.
const std::string name
The name of the type in code.
const struct ATTRIBUTES_tag attr
The simulation engine attributes that describe the type.
const std::size_t size
The size of an instance of the type.
bool register_instances
Should instances be registered with the simulation engine? If true (default value), instances of the type will be registered with the simulation engine; the simulation engine is responsible for checkpointing and restoring the contents of such instances.
Static Protected Attributes inherited from jeod::JeodMemoryTypeDescriptor
static bool check_for_registration_errors = false
When set, suspect memory interface results will be reported as a warnings.
Detailed Description
template<typename Type>
class jeod::JeodMemoryTypeDescriptorDerived< Type >
Extends JeodMemoryTypeDescriptor to describe a specific type.
tparam Type The type to be described.
Definition at line 427 of file memory_type.hh.
Member Typedef Documentation
Attributes
template<typename Type > typedef JeodSimEngineAttributes<Type, std::is_class<Type>::value> jeod::JeodMemoryTypeDescriptorDerived< Type >::Attributes
Attributes for the Type.
Definition at line 441 of file memory_type.hh.
TypeDescriptor
template<typename Type > typedef JeodMemoryTypeDescriptorDerived<Type> jeod::JeodMemoryTypeDescriptorDerived< Type >::TypeDescriptor
This class.
Definition at line 435 of file memory_type.hh.
Constructor & Destructor Documentation
JeodMemoryTypeDescriptorDerived() [1/2]
template<typename Type > jeod::JeodMemoryTypeDescriptorDerived< Type >::JeodMemoryTypeDescriptorDerived (bool is_exportable = true) inline
Default constructor.
Invoke the parent class non-default constructor with type, attributes, and size information.
Definition at line 451 of file memory_type.hh.
Referenced by jeod::JeodMemoryTypeDescriptorDerived< Type >::clone().
JeodMemoryTypeDescriptorDerived() [2/2]
template<typename Type > jeod::JeodMemoryTypeDescriptorDerived< Type >::JeodMemoryTypeDescriptorDerived (const JeodMemoryTypeDescriptorDerived< Type > & src) inline
Copy constructor; pass-through to the parent class equivalent.
Parameters
[in] src Item to be copied
Definition at line 464 of file memory_type.hh.
~JeodMemoryTypeDescriptorDerived()
template<typename Type > jeod::JeodMemoryTypeDescriptorDerived< Type >::~JeodMemoryTypeDescriptorDerived () inline override
Destructor.
Definition at line 472 of file memory_type.hh.
Member Function Documentation
clone()
template<typename Type > JeodMemoryTypeDescriptor* jeod::JeodMemoryTypeDescriptorDerived< Type >::clone () const inline override virtual
Create a copy of the descriptor.
Returns
Copy.
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 482 of file memory_type.hh.
References jeod::JeodMemoryTypeDescriptorDerived< Type >::JeodMemoryTypeDescriptorDerived().
construct_array()
template<typename Type > void* jeod::JeodMemoryTypeDescriptorDerived< Type >::construct_array (std::size_t nelem, void * addr) const inline override virtual
Construct an array of objects of the type.
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 501 of file memory_type.hh.
delete_array()
template<typename Type > void jeod::JeodMemoryTypeDescriptorDerived< Type >::delete_array (void * addr) const inline override protected virtual
Delete an array of instances of type Type.
In other words, delete[] addr.
Parameters
[in,out] addr Address to be deleted
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 534 of file memory_type.hh.
delete_object()
template<typename Type > void jeod::JeodMemoryTypeDescriptorDerived< Type >::delete_object (void * addr) const inline override protected virtual
Delete a single instance of type Type.
In other words, delete addr.
Parameters
[in,out] addr Address to be deleted
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 545 of file memory_type.hh.
destruct_array()
template<typename Type > void jeod::JeodMemoryTypeDescriptorDerived< Type >::destruct_array (std::size_t nelem, void * addr) const inline override protected virtual
Destroy an array of nelem instances of type Type.
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 554 of file memory_type.hh.
is_structured()
template<typename Type > bool jeod::JeodMemoryTypeDescriptorDerived< Type >::is_structured (void) const inline override virtual
Indicate whether the type associated with the descriptor is a structured (non-primitive, non-pointer) type.
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 493 of file memory_type.hh.
most_derived_pointer() [1/2]
template<typename Type > const void* jeod::JeodMemoryTypeDescriptorDerived< Type >::most_derived_pointer (const void * addr) const inline override virtual
Find the most-derived object corresponding to the input pointer.
Parameters
[in] addr Pointer to be examined
Returns
Pointer to most-derived object.
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 511 of file memory_type.hh.
most_derived_pointer() [2/2]
template<typename Type > void* jeod::JeodMemoryTypeDescriptorDerived< Type >::most_derived_pointer (void * addr) const inline override virtual
Find the most-derived object corresponding to the input pointer.
Parameters
[in] addr Pointer to be examined
Returns
Pointer to most-derived object.
Implements jeod::JeodMemoryTypeDescriptor.
Definition at line 521 of file memory_type.hh.
References jeod::jeod_alloc_get_allocated_pointer().
operator=()
template<typename Type > JeodMemoryTypeDescriptorDerived& jeod::JeodMemoryTypeDescriptorDerived< Type >::operator= (const JeodMemoryTypeDescriptorDerived< Type > &) private
Not implemented.
The documentation for this class was generated from the following file:
memory_type.hh