JEOD: jeod::BodyDetachSpecific Class Reference
jeod::BodyDetachSpecific Class Reference
Causes the subject body to detach from a specific body by severing the link immediately spawning from the detach_from body.
#include <body_detach_specific.hh>
Public Member Functions
void set_detach_from_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_detach_from_body (DynBody &dyn_body_in)
Set the subject mass body of this action.
BodyDetachSpecific ()
Construct a BodyDetachSpecific.
~BodyDetachSpecific () override=default
BodyDetachSpecific (const BodyDetachSpecific &)=delete
BodyDetachSpecific & operator= (const BodyDetachSpecific &)=delete
void initialize (DynManager &dyn_manager) override
Initialize a BodyDetachSpecific.
void apply (DynManager &dyn_manager) override
Detach the body from its parent.
bool is_ready () override
Queries whether the "active" flag has been set.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
Protected Attributes
MassBody * mass_detach_from {}
The mass body from the subject of this action is to detach.
DynBody * dyn_detach_from {}
The dynamic body from the subject of this action is to detach.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Friends
class InputProcessor
void init_attrjeod__BodyDetachSpecific ()
Additional Inherited Members
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Detailed Description
Causes the subject body to detach from a specific body by severing the link immediately spawning from the detach_from body.
This method works between two dynamic bodies (DynBody) or mass bodies (MassBody), but not mixtures of the two classes. The subject body itself is detached from its parent if and only if the specified detach_from body is the subject body's immediate parent. In the case that the detach_from body is some indirect parent, the body that detaches is the the immediate child body of the detach_from body that is along the connectivity path from the subject body to the detach_from * body. Specifing a detach_from body that is not a parent (direct or indirect) body of the subject body is an error.
Definition at line 92 of file body_detach_specific.hh.
Constructor & Destructor Documentation
BodyDetachSpecific() [1/2]
jeod::BodyDetachSpecific::BodyDetachSpecific ()
Construct a BodyDetachSpecific.
Definition at line 51 of file body_detach_specific.cc.
References jeod::BodyAction::active.
~BodyDetachSpecific()
jeod::BodyDetachSpecific::~BodyDetachSpecific () override default
BodyDetachSpecific() [2/2]
jeod::BodyDetachSpecific::BodyDetachSpecific (const BodyDetachSpecific &) delete
Member Function Documentation
apply()
void jeod::BodyDetachSpecific::apply (DynManager & dyn_manager) override virtual
Detach the body from its parent.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::BodyAction.
Definition at line 72 of file body_detach_specific.cc.
References jeod::BodyAction::action_identifier, jeod::BodyAction::apply(), jeod::MessageHandler::debug(), jeod::MassBody::detach(), jeod::DynBody::detach(), dyn_detach_from, jeod::BodyAction::dyn_subject, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::BodyActionMessages::fatal_error, jeod::NamedItem::get_name(), mass_detach_from, jeod::BodyAction::mass_subject, jeod::MassBody::name, jeod::DynBody::name, jeod::BodyActionMessages::not_performed, jeod::DynBody::remove_mass_body(), jeod::BodyAction::terminate_on_error, and jeod::BodyActionMessages::trace.
initialize()
void jeod::BodyDetachSpecific::initialize (DynManager & dyn_manager) override virtual
Initialize a BodyDetachSpecific.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::BodyAction.
Definition at line 60 of file body_detach_specific.cc.
References dyn_detach_from, jeod::BodyAction::initialize(), mass_detach_from, and jeod::BodyAction::validate_body_inputs().
is_ready()
bool jeod::BodyDetachSpecific::is_ready () override virtual
Queries whether the "active" flag has been set.
Returns
Can detach process run?
Reimplemented from jeod::BodyAction.
Definition at line 163 of file body_detach_specific.cc.
References jeod::BodyAction::active.
operator=()
BodyDetachSpecific& jeod::BodyDetachSpecific::operator= (const BodyDetachSpecific &) delete
set_detach_from_body() [1/2]
void jeod::BodyDetachSpecific::set_detach_from_body (MassBody & mass_body_in)
Set the subject mass body of this action.
Resets dyn_subject to null
Definition at line 147 of file body_detach_specific.cc.
References dyn_detach_from, and mass_detach_from.
set_detach_from_body() [2/2]
void jeod::BodyDetachSpecific::set_detach_from_body (DynBody & dyn_body_in)
Set the subject mass body of this action.
Resets dyn_subject to null
Definition at line 153 of file body_detach_specific.cc.
References dyn_detach_from, and mass_detach_from.
Friends And Related Function Documentation
init_attrjeod__BodyDetachSpecific
void init_attrjeod__BodyDetachSpecific () friend
InputProcessor
friend class InputProcessor friend
Definition at line 94 of file body_detach_specific.hh.
Field Documentation
dyn_detach_from
DynBody* jeod::BodyDetachSpecific::dyn_detach_from {} protected
The dynamic body from the subject of this action is to detach.
This pointer or the detach_from member must be supplied for dynamic body detachment. The detachment is performed between the mass_detach_from object and the direct descendant of the mass_detach_from object that is in the parental lineage from the subject body to the mass_detach_from body.trick_units(–)
Definition at line 126 of file body_detach_specific.hh.
Referenced by apply(), initialize(), and set_detach_from_body().
mass_detach_from
MassBody* jeod::BodyDetachSpecific::mass_detach_from {} protected
The mass body from the subject of this action is to detach.
This pointer must be supplied for pure MassBody detachments. The initialize method will attempt to determine if this MassBody refers to a DynBody. The detachment is performed between the mass_detach_from object and the direct descendant of the detach_from object that is in the parental lineage from the subject body to the detach_from body.trick_units(–)
Definition at line 116 of file body_detach_specific.hh.
Referenced by apply(), initialize(), and set_detach_from_body().
The documentation for this class was generated from the following files:
body_detach_specific.hh
body_detach_specific.cc