JEOD: jeod::DynBodyInitOrbit Class Reference
jeod::DynBodyInitOrbit Class Reference
Initialize a vehicle's translational state given an orbital specification.
#include <dyn_body_init_orbit.hh>
Public Types
enum OrbitalSet {
InvalidSet = 0, SmaEccIncAscnodeArgperTimeperi = 1, SmaEccIncAscnodeArgperManom = 2, SlrEccIncAscnodeArgperTanom = 3,
IncAscnodeAltperAltapoArgperTanom = 4, IncAscnodeAltperAltapoArgperTimeperi = 5, SmaIncAscnodeArglatRadRadvel = 6, SmaEccIncAscnodeArgperTanom = 10,
CaseEleven = 11
}
Identifies which orbital elements define the orbit.
Public Types inherited from jeod::DynBodyInitTransState
enum StateItems { Both = 0, Position = 1, Velocity = 2 }
Identify which of position/velocity is to be initialized.
Public Member Functions
DynBodyInitOrbit ()=default
~DynBodyInitOrbit () override=default
DynBodyInitOrbit (const DynBodyInitOrbit &)=delete
DynBodyInitOrbit & operator= (const DynBodyInitOrbit &)=delete
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
void apply (DynManager &dyn_manager) override
Apply the initializer.
Public Member Functions inherited from jeod::DynBodyInitTransState
DynBodyInitTransState ()=default
~DynBodyInitTransState () override=default
DynBodyInitTransState (const DynBodyInitTransState &)=delete
DynBodyInitTransState & operator= (const DynBodyInitTransState &)=delete
void initialize (DynManager &dyn_manager) override
Initialize aspects of this object and forward the initializer to the immediate parent class.
void apply (DynManager &dyn_manager) override
Apply the initializer.
RefFrameItems::Items initializes_what () override
Indicate what parts of the vehicle state this object initializes.
bool is_ready () override
Indicate whether this initializer is ready to be applied.
Public Member Functions inherited from jeod::DynBodyInit
DynBodyInit ()=default
~DynBodyInit () override=default
DynBodyInit (const DynBodyInit &)=delete
DynBodyInit & operator= (const DynBodyInit &)=delete
virtual void report_failure ()
Report on an initializer that could not be processed.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
Data Fields
std::string planet_name
The name of the planet around which the orbit is to be established.
std::string orbit_frame_name
Planet reference frame name, optionally dot-prefixed with the planet name.
OrbitalSet set {InvalidSet}
Specifies which set of orbital elements specify the orbit.
double semi_major_axis {}
Semi-major axis.
double semi_latus_rectum {}
Semi-latus rectum.
double alt_periapsis {}
Periapsis altitude.
double alt_apoapsis {}
Apoapsis altitude.
double orb_radius {}
Distance from center of planet.
double radial_vel {}
Time derivative of the orbital radius.
double eccentricity {}
Eccentricity.
double inclination {}
Inclination.
double ascending_node {}
Longitude (or right ascension) of ascending node.
double arg_periapsis {}
Argument of periapsis.
double arg_latitude {}
Argument of latitude.
double time_periapsis {}
Time since periapsis passage.
double mean_anomaly {}
Mean anomaly.
double true_anomaly {}
True anomaly.
Data Fields inherited from jeod::DynBodyInitTransState
StateItems state_items {Both}
State items to be initialized – position, velocity, or both.
Data Fields inherited from jeod::DynBodyInit
std::string body_frame_id {""}
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
std::string reference_ref_frame_name {""}
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
RefFrameState state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
double position [3] {}
Relative position between the subject and reference reference frame origins.
double velocity [3] {}
Relative velocity between the subject and reference reference frame origins.
Orientation orientation
Relative orientation between the subject and reference reference frame axes.
double ang_velocity [3] {}
Relative angular velocity between the subject and reference axes.
bool reverse_sense {}
Indicates how the user input state items are to be interpreted.
bool rate_in_parent {}
Indicates how the user input angular velocity is to be interpreted.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Attributes
Planet * planet {}
The planet.
EphemerisRefFrame * orbit_frame {}
The orbit reference frame (ignoring rotation)
Protected Attributes inherited from jeod::DynBodyInit
BodyRefFrame * body_ref_frame {}
The reference frame whose name is vehicle_name.body_frame_id.
RefFrame * reference_ref_frame {}
The reference frame whose name is reference_ref_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Friends
class InputProcessor
void init_attrjeod__DynBodyInitOrbit ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyInit
void apply_user_inputs ()
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
void compute_rotational_state ()
This method is obsolete.
void compute_translational_state ()
This method is obsolete.
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
DynBody * find_dyn_body (const DynManager &dyn_manager, const std::string &dyn_body_name, const std::string &variable_name)
Find the DynBody with the given name, failing if not found.
RefFrame * find_ref_frame (const DynManager &dyn_manager, const std::string &ref_frame_name, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
BodyRefFrame * find_body_frame (DynBody &frame_container, const std::string &body_frame_identifier, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Detailed Description
Initialize a vehicle's translational state given an orbital specification.
Definition at line 82 of file dyn_body_init_orbit.hh.
Member Enumeration Documentation
OrbitalSet
enum jeod::DynBodyInitOrbit::OrbitalSet
Identifies which orbital elements define the orbit.
The goofy numbering scheme here is intentional. The numbers map directly to the corresponding orbital_set number in JEOD 1.4 / 1.5. NOTE: Orbital sets 4 and 11 are the same options.
Enumerator
InvalidSet
SmaEccIncAscnodeArgperTimeperi
SmaEccIncAscnodeArgperManom
SlrEccIncAscnodeArgperTanom
IncAscnodeAltperAltapoArgperTanom
IncAscnodeAltperAltapoArgperTimeperi
SmaIncAscnodeArglatRadRadvel
SmaEccIncAscnodeArgperTanom
CaseEleven
Definition at line 94 of file dyn_body_init_orbit.hh.
Constructor & Destructor Documentation
DynBodyInitOrbit() [1/2]
jeod::DynBodyInitOrbit::DynBodyInitOrbit () default
~DynBodyInitOrbit()
jeod::DynBodyInitOrbit::~DynBodyInitOrbit () override default
DynBodyInitOrbit() [2/2]
jeod::DynBodyInitOrbit::DynBodyInitOrbit (const DynBodyInitOrbit &) delete
Member Function Documentation
apply()
void jeod::DynBodyInitOrbit::apply (DynManager & dyn_manager) override virtual
Apply the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 157 of file dyn_body_init_orbit.cc.
References jeod::BodyAction::action_identifier, alt_apoapsis, alt_periapsis, jeod::DynBodyInitTransState::apply(), arg_latitude, jeod::OrbitalElements::arg_periapsis, arg_periapsis, ascending_node, CaseEleven, jeod::RefFrame::compute_relative_state(), jeod::OrbitalElements::e_mag, eccentricity, jeod::MessageHandler::fail(), jeod::BasePlanet::grav_source, jeod::BodyActionMessages::illegal_value, IncAscnodeAltperAltapoArgperTanom, IncAscnodeAltperAltapoArgperTimeperi, jeod::OrbitalElements::inclination, inclination, jeod::BasePlanet::inertial, InvalidSet, jeod::OrbitalElements::long_asc_node, jeod::OrbitalElements::mean_anom, jeod::OrbitalElements::mean_anom_to_nu(), mean_anomaly, jeod::GravitySource::mu, jeod::OrbitalElements::nu_to_anomalies(), orb_radius, orbit_frame, planet, jeod::DynBodyInit::position, jeod::Planet::r_eq, radial_vel, jeod::RefFrameState::rot, semi_latus_rectum, semi_major_axis, jeod::OrbitalElements::semiparam, SlrEccIncAscnodeArgperTanom, SmaEccIncAscnodeArgperManom, SmaEccIncAscnodeArgperTanom, SmaEccIncAscnodeArgperTimeperi, SmaIncAscnodeArglatRadRadvel, jeod::RefFrameRot::T_parent_this, time_periapsis, jeod::OrbitalElements::to_cartesian(), jeod::Vector3::transform_transpose(), jeod::OrbitalElements::true_anom, true_anomaly, and jeod::DynBodyInit::velocity.
initialize()
void jeod::DynBodyInitOrbit::initialize (DynManager & dyn_manager) override virtual
Initialize the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 60 of file dyn_body_init_orbit.cc.
References jeod::BodyAction::action_identifier, CaseEleven, jeod::NamedItem::construct_name(), jeod::MessageHandler::fail(), jeod::DynBodyInit::find_planet(), jeod::RefFrameManager::find_ref_frame(), jeod::BasePlanet::grav_source, jeod::BodyActionMessages::illegal_value, IncAscnodeAltperAltapoArgperTanom, IncAscnodeAltperAltapoArgperTimeperi, jeod::BasePlanet::inertial, jeod::DynBodyInitTransState::initialize(), jeod::BodyActionMessages::invalid_name, jeod::BodyActionMessages::invalid_object, InvalidSet, orbit_frame, orbit_frame_name, planet, planet_name, jeod::DynBodyInit::reference_ref_frame, SlrEccIncAscnodeArgperTanom, SmaEccIncAscnodeArgperManom, SmaEccIncAscnodeArgperTanom, SmaEccIncAscnodeArgperTimeperi, SmaIncAscnodeArglatRadRadvel, jeod::NamedItem::suffix(), and jeod::BodyAction::validate_name().
operator=()
DynBodyInitOrbit& jeod::DynBodyInitOrbit::operator= (const DynBodyInitOrbit &) delete
Friends And Related Function Documentation
init_attrjeod__DynBodyInitOrbit
void init_attrjeod__DynBodyInitOrbit () friend
InputProcessor
friend class InputProcessor friend
Definition at line 84 of file dyn_body_init_orbit.hh.
Field Documentation
alt_apoapsis
double jeod::DynBodyInitOrbit::alt_apoapsis {}
Apoapsis altitude.
trick_units(m)
Definition at line 204 of file dyn_body_init_orbit.hh.
Referenced by apply().
alt_periapsis
double jeod::DynBodyInitOrbit::alt_periapsis {}
Periapsis altitude.
trick_units(m)
Definition at line 199 of file dyn_body_init_orbit.hh.
Referenced by apply().
arg_latitude
double jeod::DynBodyInitOrbit::arg_latitude {}
Argument of latitude.
trick_units(rad)
Definition at line 239 of file dyn_body_init_orbit.hh.
Referenced by apply().
arg_periapsis
double jeod::DynBodyInitOrbit::arg_periapsis {}
Argument of periapsis.
trick_units(rad)
Definition at line 234 of file dyn_body_init_orbit.hh.
Referenced by apply().
ascending_node
double jeod::DynBodyInitOrbit::ascending_node {}
Longitude (or right ascension) of ascending node.
trick_units(rad)
Definition at line 229 of file dyn_body_init_orbit.hh.
Referenced by apply().
eccentricity
double jeod::DynBodyInitOrbit::eccentricity {}
Eccentricity.
trick_units(–)
Definition at line 219 of file dyn_body_init_orbit.hh.
Referenced by apply().
inclination
double jeod::DynBodyInitOrbit::inclination {}
Inclination.
trick_units(rad)
Definition at line 224 of file dyn_body_init_orbit.hh.
Referenced by apply().
mean_anomaly
double jeod::DynBodyInitOrbit::mean_anomaly {}
Mean anomaly.
trick_units(rad)
Definition at line 249 of file dyn_body_init_orbit.hh.
Referenced by apply().
orb_radius
double jeod::DynBodyInitOrbit::orb_radius {}
Distance from center of planet.
trick_units(m)
Definition at line 209 of file dyn_body_init_orbit.hh.
Referenced by apply().
orbit_frame
EphemerisRefFrame* jeod::DynBodyInitOrbit::orbit_frame {} protected
The orbit reference frame (ignoring rotation)
trick_io(**)
Definition at line 265 of file dyn_body_init_orbit.hh.
Referenced by apply(), and initialize().
orbit_frame_name
std::string jeod::DynBodyInitOrbit::orbit_frame_name
Planet reference frame name, optionally dot-prefixed with the planet name.
If this specifies a rotating frame, a non-rotating frame instantaneously co-aligned with the rotating frame is assumed.trick_units(–)
Definition at line 179 of file dyn_body_init_orbit.hh.
Referenced by initialize().
planet
Planet* jeod::DynBodyInitOrbit::planet {} protected
The planet.
trick_io(**)
Definition at line 260 of file dyn_body_init_orbit.hh.
Referenced by apply(), and initialize().
planet_name
std::string jeod::DynBodyInitOrbit::planet_name
The name of the planet around which the orbit is to be established.
This must be supplied, must name a planet, and the planet must have a gravity model.trick_units(–)
Definition at line 172 of file dyn_body_init_orbit.hh.
Referenced by initialize().
radial_vel
double jeod::DynBodyInitOrbit::radial_vel {}
Time derivative of the orbital radius.
trick_units(m/s)
Definition at line 214 of file dyn_body_init_orbit.hh.
Referenced by apply().
semi_latus_rectum
double jeod::DynBodyInitOrbit::semi_latus_rectum {}
Semi-latus rectum.
trick_units(m)
Definition at line 194 of file dyn_body_init_orbit.hh.
Referenced by apply().
semi_major_axis
double jeod::DynBodyInitOrbit::semi_major_axis {}
Semi-major axis.
trick_units(m)
Definition at line 189 of file dyn_body_init_orbit.hh.
Referenced by apply().
set
OrbitalSet jeod::DynBodyInitOrbit::set {InvalidSet}
Specifies which set of orbital elements specify the orbit.
trick_units(–)
Definition at line 184 of file dyn_body_init_orbit.hh.
time_periapsis
double jeod::DynBodyInitOrbit::time_periapsis {}
Time since periapsis passage.
trick_units(s)
Definition at line 244 of file dyn_body_init_orbit.hh.
Referenced by apply().
true_anomaly
double jeod::DynBodyInitOrbit::true_anomaly {}
True anomaly.
trick_units(rad)
Definition at line 254 of file dyn_body_init_orbit.hh.
Referenced by apply().
The documentation for this class was generated from the following files:
dyn_body_init_orbit.hh
dyn_body_init_orbit.cc