JEOD: jeod::BodyDetach Class Reference
jeod::BodyDetach Class Reference
Provides the basic ability to detach one MassBody from another.
#include <body_detach.hh>
Public Member Functions
BodyDetach ()
Construct a MassBodyDetach.
~BodyDetach () override=default
BodyDetach (const BodyDetach &)=delete
BodyDetach & operator= (const BodyDetach &)=delete
void apply (DynManager &dyn_manager) override
Detach the body from its parent.
bool is_ready () override
Queries whether the "active" flag has been set.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
virtual void initialize (DynManager &dyn_manager)
Begin initialization of a BodyAction.
Friends
class InputProcessor
void init_attrjeod__BodyDetach ()
Additional Inherited Members
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Provides the basic ability to detach one MassBody from another.
This is inherently an asynchronous BodyAction. The is_ready() method simply returns the action's active flag. The action will be performed when the sim user or some simulation job enables the active flag.
The basic detachment action is to cause a body to detach from its immediate parent body. Subclasses can cause bodies to detach elsewhere.
Definition at line 89 of file body_detach.hh.
Constructor & Destructor Documentation
BodyDetach() [1/2]
jeod::BodyDetach::BodyDetach ()
Construct a MassBodyDetach.
Definition at line 49 of file body_detach.cc.
References jeod::BodyAction::active.
~BodyDetach()
jeod::BodyDetach::~BodyDetach () override default
BodyDetach() [2/2]
jeod::BodyDetach::BodyDetach (const BodyDetach &) delete
Member Function Documentation
apply()
void jeod::BodyDetach::apply (DynManager & dyn_manager) override virtual
Detach the body from its parent.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAction.
Definition at line 58 of file body_detach.cc.
References jeod::BodyAction::action_identifier, jeod::BodyAction::apply(), jeod::NamedItem::c_str(), jeod::MessageHandler::debug(), jeod::MassBody::detach(), jeod::DynBody::detach(), jeod::BodyAction::dyn_subject, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::BodyActionMessages::fatal_error, jeod::BodyAction::mass_subject, jeod::MassBody::name, jeod::BodyActionMessages::not_performed, jeod::BodyAction::terminate_on_error, and jeod::BodyActionMessages::trace.
is_ready()
bool jeod::BodyDetach::is_ready () override virtual
Queries whether the "active" flag has been set.
Returns
Can detach process run?
Reimplemented from jeod::BodyAction.
Definition at line 115 of file body_detach.cc.
References jeod::BodyAction::active.
operator=()
BodyDetach& jeod::BodyDetach::operator= (const BodyDetach &) delete
Friends And Related Function Documentation
init_attrjeod__BodyDetach
void init_attrjeod__BodyDetach () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file body_detach.hh.
The documentation for this class was generated from the following files:
body_detach.hh
body_detach.cc