JEOD: jeod::JeodMemoryInterface Class Reference
jeod::JeodMemoryInterface Class Reference abstract
Abstract interface between the JEOD memory manager and the simulation engine.
#include <memory_interface.hh>
Public Member Functions
JeodMemoryInterface ()
Default constructor.
virtual ~JeodMemoryInterface ()
Destructor.
JeodMemoryInterface (const JeodMemoryInterface &)
Copy constructor.
JeodMemoryInterface & operator= (const JeodMemoryInterface &)
Assignment operator.
virtual const struct ATTRIBUTES_tag * find_attributes (const std::string &type_name) const =0
Find the attributes for a given class name.
virtual const struct ATTRIBUTES_tag * find_attributes (const std::type_info &data_type) const =0
Find the attributes for a given class.
virtual struct ATTRIBUTES_tag primitive_attributes (const std::type_info &data_type) const =0
Create an attributes structure that represents a primitive type.
virtual struct ATTRIBUTES_tag pointer_attributes (const struct ATTRIBUTES_tag &pointed_to_attr) const =0
Create an attributes structure that represents a pointer type.
virtual struct ATTRIBUTES_tag void_pointer_attributes (void) const =0
Create a simulation engine description of void*.
virtual struct ATTRIBUTES_tag structure_attributes (const struct ATTRIBUTES_tag *target_attr, std::size_t target_size) const =0
Create an attributes structure that represents a structured type.
virtual bool register_allocation (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line)=0
Register allocated memory with the simulation engine.
virtual void deregister_allocation (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line)=0
Revoke registation of memory that is about to be deleted.
virtual void register_container (const void *container, const JeodMemoryTypeDescriptor &container_type, const char *elem_name, JeodCheckpointable &checkpointable)=0
Register a JeodCheckpointable object with the simulation engine.
virtual void deregister_container (const void *container, const JeodMemoryTypeDescriptor &container_type, const char *elem_name, JeodCheckpointable &checkpointable)=0
Deregister a JeodCheckpointable object with the simulation engine.
virtual bool is_checkpoint_restart_supported (void) const =0
Indicates whether the checkpoint/restart methods are viable.
virtual const std::string get_name_at_address (const void *addr, const JeodMemoryTypeDescriptor *tdesc) const =0
Get the simulation engine's name (if any) of the address.
virtual void * get_address_at_name (const std::string &name) const =0
Get the address (if any) identified by the given name.
Friends
class InputProcessor
void init_attrjeod__JeodMemoryInterface ()
Detailed Description
Abstract interface between the JEOD memory manager and the simulation engine.
Definition at line 90 of file memory_interface.hh.
Constructor & Destructor Documentation
JeodMemoryInterface() [1/2]
jeod::JeodMemoryInterface::JeodMemoryInterface (void)
Default constructor.
Definition at line 41 of file memory_interface.cc.
~JeodMemoryInterface()
jeod::JeodMemoryInterface::~JeodMemoryInterface (void) virtual
Destructor.
Definition at line 51 of file memory_interface.cc.
JeodMemoryInterface() [2/2]
jeod::JeodMemoryInterface::JeodMemoryInterface (const JeodMemoryInterface & src) explicit
Copy constructor.
Parameters
[in] src Item to be copied
Definition at line 62 of file memory_interface.cc.
Member Function Documentation
deregister_allocation()
virtual void jeod::JeodMemoryInterface::deregister_allocation (const void * addr, const JeodMemoryItem & item, const JeodMemoryTypeDescriptor & tdesc, const char * file, unsigned int line) pure virtual
Revoke registation of memory that is about to be deleted.
Parameters
[in] addr Address of allocated memory to be de-registered.
[in] item JEOD descriptor of the memory
[in] tdesc JEOD descriptor of the type of the allocated memory
[in] file File in which allocation was performed
[in] line Line number in that file
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodMemoryManager::restart_clear_memory(), and jeod::JeodMemoryManager::~JeodMemoryManager().
deregister_container()
virtual void jeod::JeodMemoryInterface::deregister_container (const void * container, const JeodMemoryTypeDescriptor & container_type, const char * elem_name, JeodCheckpointable & checkpointable) pure virtual
Deregister a JeodCheckpointable object with the simulation engine.
Parameters
[in] container Object that contains the checkpointable
[in] container_type Checkpointable container type info
[in] elem_name Element name of checkpointable object
[in,out] checkpointable The checkpointable object itself
Implemented in jeod::NullMemoryInterface, jeod::JeodTrickMemoryInterface, and jeod::JeodTrick10MemoryInterface.
Referenced by jeod::JeodMemoryManager::deregister_container().
find_attributes() [1/2]
virtual const struct ATTRIBUTES_tag* jeod::JeodMemoryInterface::find_attributes (const std::string & type_name) const pure virtual
Find the attributes for a given class name.
Parameters
[in] type_name Name of the class.
Returns
Attributes pointer. Note: This is not an allocated pointer.
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodSimEngineAttributes< Type, true >::attributes().
find_attributes() [2/2]
virtual const struct ATTRIBUTES_tag* jeod::JeodMemoryInterface::find_attributes (const std::type_info & data_type) const pure virtual
Find the attributes for a given class.
Parameters
[in] data_type RTTI descriptor of the type.
Returns
Attributes pointer. Note: This is not an allocated pointer.
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
get_address_at_name()
virtual void* jeod::JeodMemoryInterface::get_address_at_name (const std::string & name) const pure virtual
Get the address (if any) identified by the given name.
Note
An implementation that does not support name translation will return the null pointer.
A stubbed implementation should have its is_checkpoint_restart_supported method return false.
Returns
Address corresponding to the given name, if any
Parameters
[in] name Value previously constructed by get_name_at_address()
Implemented in jeod::JeodTrickMemoryInterface, jeod::JeodTrick10MemoryInterface, and jeod::NullMemoryInterface.
get_name_at_address()
virtual const std::string jeod::JeodMemoryInterface::get_name_at_address (const void * addr, const JeodMemoryTypeDescriptor * tdesc) const pure virtual
Get the simulation engine's name (if any) of the address.
A derived class associated with a simulation engine that does not support this translation should return an empty string for all calls. When the underlying simulation engine does support this translation, the implementation should return values as follows:
The string "NULL" if the input address is the null pointer.
The empty string to indicate an invalid input address or an input address that is unknown to the simulation engine.
A non-empty, non-"NULL" string to indicate a valid address. Applying the get_address_at_name method to this result must yield the input address.
Note
A stubbed implementation should have its is_checkpoint_restart_supported method return false.
Returns
Name of the address, if any
Parameters
[in] addr Address of memory to identified by name
[in] tdesc Type context in which to interpret the address
Implemented in jeod::JeodTrickMemoryInterface, jeod::JeodTrick10MemoryInterface, and jeod::NullMemoryInterface.
is_checkpoint_restart_supported()
virtual bool jeod::JeodMemoryInterface::is_checkpoint_restart_supported (void) const pure virtual
Indicates whether the checkpoint/restart methods are viable.
Checkpoint/restart can be used only in an environment that provides viable checkpoint/restart methods.
Returns
True if the checkpoint / restart is supported, false otherwise.
Implemented in jeod::JeodTrickMemoryInterface, jeod::JeodTrick10MemoryInterface, and jeod::NullMemoryInterface.
operator=()
JeodMemoryInterface & jeod::JeodMemoryInterface::operator= (const JeodMemoryInterface & src)
Assignment operator.
Returns
*this
Parameters
[in] src Item to be copied
Definition at line 75 of file memory_interface.cc.
pointer_attributes()
virtual struct ATTRIBUTES_tag jeod::JeodMemoryInterface::pointer_attributes (const struct ATTRIBUTES_tag & pointed_to_attr) const pure virtual
Create an attributes structure that represents a pointer type.
Parameters
[in] pointed_to_attr Attributes of the pointed-to type.
Returns
Attribute structure.
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodSimEngineAttributes< Type *, false >::attributes().
primitive_attributes()
virtual struct ATTRIBUTES_tag jeod::JeodMemoryInterface::primitive_attributes (const std::type_info & data_type) const pure virtual
Create an attributes structure that represents a primitive type.
Parameters
[in] data_type RTTI descriptor of the type.
Returns
Attributes structure.
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodSimEngineAttributes< Type, is_class >::attributes().
register_allocation()
virtual bool jeod::JeodMemoryInterface::register_allocation (const void * addr, const JeodMemoryItem & item, const JeodMemoryTypeDescriptor & tdesc, const char * file, unsigned int line) pure virtual
Register allocated memory with the simulation engine.
Parameters
[in] addr Address of allocated memory to be registered.
[in] item JEOD descriptor of the allocated memory
[in] tdesc JEOD descriptor of the type of the allocated memory
[in] file File in which allocation was performed
[in] line Line number in that file
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodMemoryManager::register_memory_internal().
register_container()
virtual void jeod::JeodMemoryInterface::register_container (const void * container, const JeodMemoryTypeDescriptor & container_type, const char * elem_name, JeodCheckpointable & checkpointable) pure virtual
Register a JeodCheckpointable object with the simulation engine.
Parameters
[in] container Object that contains the checkpointable
[in] container_type Checkpointable container type info
[in] elem_name Element name of checkpointable object
[in,out] checkpointable The checkpointable object itself
Implemented in jeod::NullMemoryInterface, jeod::JeodTrickMemoryInterface, and jeod::JeodTrick10MemoryInterface.
Referenced by jeod::JeodMemoryManager::register_container().
structure_attributes()
virtual struct ATTRIBUTES_tag jeod::JeodMemoryInterface::structure_attributes (const struct ATTRIBUTES_tag * target_attr, std::size_t target_size) const pure virtual
Create an attributes structure that represents a structured type.
Parameters
[in] target_attr Attributes from find_attributes
[in] target_size Size of the underlying type
Returns
Attribute structure.
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodSimEngineAttributes< Type, true >::attributes().
void_pointer_attributes()
virtual struct ATTRIBUTES_tag jeod::JeodMemoryInterface::void_pointer_attributes (void) const pure virtual
Create a simulation engine description of void*.
Returns
Attribute structure.
Implemented in jeod::NullMemoryInterface, and jeod::JeodTrickMemoryInterface.
Referenced by jeod::JeodSimEngineAttributes< void *, false >::attributes().
Friends And Related Function Documentation
init_attrjeod__JeodMemoryInterface
void init_attrjeod__JeodMemoryInterface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 92 of file memory_interface.hh.
The documentation for this class was generated from the following files:
memory_interface.hh
memory_interface.cc