JEOD: jeod::Contact Class Reference
jeod::Contact Class Reference
An base contact class for use in the surface model.
#include <contact.hh>
Public Member Functions
Contact ()
Default Constructor.
virtual ~Contact ()
Destructor.
Contact & operator= (const Contact &)=delete
Contact (const Contact &)=delete
void register_contact (ContactFacet *facet)
Register one ContactFacet with all inclusive interactions with other registered ContactFacets.
void register_contact (ContactFacet **facets, unsigned int n_facets)
Register an array of ContactFacets with all inclusive interactions with other registered ContactFacets.
void register_contact (ContactFacet *facet1, ContactFacet *facet2)
Register two facets as a pair.
void register_contact (ContactFacet **facets1, unsigned int n_facets1, ContactFacet **facets2, unsigned int n_facets2)
Regiser to arrays of facets and create specific pairs between all of them.
void register_interaction (PairInteraction *interaction)
Register a pair interaction.
virtual PairInteraction * find_interaction (ContactParams *params_1, ContactParams *params_2)
find a PairInteraction baced on a set of ContactParams.
void initialize_contact (DynManager *manager)
Initialize ContactFacets and the mananger by cleaning up the pair list.
bool unique_pair (const ContactFacet *facet_1, const ContactFacet *facet_2)
Check to see if a pair of facets already exists.
void check_contact ()
iterate through contact pairs list then call the appropriate contact resolution functions
Data Fields
bool active {true}
toggles contact on and off, true=on false=off
double contact_limit_factor {}
factor determines if contact is limited by a muliple of the maximum dimensions of the facets in a pair.
Protected Attributes
DynManager * dyn_manager {}
Pointer to the dyn_manager so relstates and be successfully initialized.
JeodPointerList< ContactPair >::type contact_pairs
list of all possible pairings of contact facets registered with this contact class or derived class
JeodPointerList< PairInteraction >::type pair_interactions
list of all possible pair interaction types
Friends
class InputProcessor
void init_attrjeod__Contact ()
Detailed Description
An base contact class for use in the surface model.
Definition at line 91 of file contact.hh.
Constructor & Destructor Documentation
Contact() [1/2]
jeod::Contact::Contact ()
Default Constructor.
Definition at line 50 of file contact.cc.
References contact_pairs, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and pair_interactions.
~Contact()
jeod::Contact::~Contact () virtual
Destructor.
Definition at line 62 of file contact.cc.
References contact_pairs, JEOD_DELETE_OBJECT, JEOD_DEREGISTER_CHECKPOINTABLE, and pair_interactions.
Contact() [2/2]
jeod::Contact::Contact (const Contact &) delete
Member Function Documentation
check_contact()
void jeod::Contact::check_contact ()
iterate through contact pairs list then call the appropriate contact resolution functions
Definition at line 86 of file contact.cc.
References active, and contact_pairs.
find_interaction()
PairInteraction * jeod::Contact::find_interaction (ContactParams * params_1, ContactParams * params_2) virtual
find a PairInteraction baced on a set of ContactParams.
Returns
pointer to a PairInteraction
Parameters
[in] params_1 ContactParams from a ContactFacet
[in] params_2 ContactParams from a ContactFacet
Definition at line 251 of file contact.cc.
References pair_interactions.
Referenced by jeod::LineContactFacet::create_pair(), and jeod::PointContactFacet::create_pair().
initialize_contact()
void jeod::Contact::initialize_contact (DynManager * manager)
Initialize ContactFacets and the mananger by cleaning up the pair list.
Parameters
[in,out] manager Dynamics Manager
Definition at line 106 of file contact.cc.
References contact_pairs, jeod::ContactFacet::create_pair(), dyn_manager, jeod::ContactPair::get_subject(), jeod::ContactPair::initialize_relstate(), and unique_pair().
operator=()
Contact& jeod::Contact::operator= (const Contact &) delete
register_contact() [1/4]
void jeod::Contact::register_contact (ContactFacet * facet)
Register one ContactFacet with all inclusive interactions with other registered ContactFacets.
Parameters
[in,out] facet ContactFacet
Definition at line 167 of file contact.cc.
References contact_pairs, and jeod::ContactFacet::create_pair().
Referenced by register_contact().
register_contact() [2/4]
void jeod::Contact::register_contact (ContactFacet ** facets, unsigned int nFacets)
Register an array of ContactFacets with all inclusive interactions with other registered ContactFacets.
Parameters
[in,out] facets array of ContactFacets
[in] nFacets number of ContactFacets in array
Definition at line 184 of file contact.cc.
References register_contact().
register_contact() [3/4]
void jeod::Contact::register_contact (ContactFacet * facet1, ContactFacet * facet2)
Register two facets as a pair.
Parameters
[in,out] facet1 Contact Facet 1
[in,out] facet2 Contact Facet 2
Definition at line 197 of file contact.cc.
References contact_pairs, jeod::ContactFacet::create_pair(), and dyn_manager.
register_contact() [4/4]
void jeod::Contact::register_contact (ContactFacet ** facets1, unsigned int nFacets1, ContactFacet ** facets2, unsigned int nFacets2)
Regiser to arrays of facets and create specific pairs between all of them.
Parameters
[in,out] facets1 array of ContactFacets
[in] nFacets1 number of ContactFacets in array
[in,out] facets2 array of ContactFacets
[in] nFacets2 number of ContactFacets in array
Definition at line 220 of file contact.cc.
References register_contact().
register_interaction()
void jeod::Contact::register_interaction (PairInteraction * interaction)
Register a pair interaction.
Parameters
[in] interaction PairInteraction to add to list
Definition at line 240 of file contact.cc.
References pair_interactions.
unique_pair()
bool jeod::Contact::unique_pair (const ContactFacet * facet_1, const ContactFacet * facet_2)
Check to see if a pair of facets already exists.
Returns
bool
Parameters
[in,out] facet_1 ContactFacet
[in,out] facet_2 ContactFacet
Definition at line 146 of file contact.cc.
References contact_pairs.
Referenced by initialize_contact().
Friends And Related Function Documentation
init_attrjeod__Contact
void init_attrjeod__Contact () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file contact.hh.
Field Documentation
active
bool jeod::Contact::active {true}
toggles contact on and off, true=on false=off
trick_units(–)
Definition at line 97 of file contact.hh.
Referenced by check_contact().
contact_limit_factor
double jeod::Contact::contact_limit_factor {}
factor determines if contact is limited by a muliple of the maximum dimensions of the facets in a pair.
trick_units(–)
Definition at line 103 of file contact.hh.
Referenced by jeod::LineContactFacet::create_pair(), and jeod::PointContactFacet::create_pair().
contact_pairs
JeodPointerList<ContactPair>::type jeod::Contact::contact_pairs protected
list of all possible pairings of contact facets registered with this contact class or derived class
trick_io(**)
Definition at line 158 of file contact.hh.
Referenced by check_contact(), Contact(), initialize_contact(), register_contact(), unique_pair(), and ~Contact().
dyn_manager
DynManager* jeod::Contact::dyn_manager {} protected
Pointer to the dyn_manager so relstates and be successfully initialized.
trick_units(–)
Definition at line 152 of file contact.hh.
Referenced by initialize_contact(), and register_contact().
pair_interactions
JeodPointerList<PairInteraction>::type jeod::Contact::pair_interactions protected
list of all possible pair interaction types
trick_io(**)
Definition at line 163 of file contact.hh.
Referenced by Contact(), find_interaction(), register_interaction(), and ~Contact().
The documentation for this class was generated from the following files:
contact.hh
contact.cc