JEOD: jeod::TimeManagerInit Class Reference
jeod::TimeManagerInit Class Reference
To initialize the Time Manager.
#include <time_manager_init.hh>
Public Member Functions
TimeManagerInit ()
Construct a TimeManagerInit.
~TimeManagerInit ()
Destroy a TimeManagerInit.
int get_conv_ptr_index (const int conv_index)
Takes a calculated converter index - calculated by combining the two time-type indices - and return the index in the time_manager's vector of converters that corresponds to those two time-types.
int get_conv_dir_init (const int conv_index)
Takes a calculated converter index - calculated by combining the indices of two time-types, a "from" and a "to" - and returns the direction needed to use the appropriate converter to go from "from" to "to".
int get_conv_dir_upd (const int conv_index)
Takes a calculated converter index - calculated by combining the indices of two time-types, a "from" and a "to" - and returns the direction needed to use the appropriate converter to go from "from" to "to".
int get_status (const int index)
Returns the status of a time-type.
void set_status (const int index, const int status_value)
Receives an updated value for the status of a time-type.
void increment_status (const int slave_index, const int master_index)
Modifies the status of one time-type to be one higher than that of another type for initialization purposes.
void initialize_manager (TimeManager *time_mgr)
The master program behind the initialization of the time types and the time converters.
void organize_update_list ()
Reorganizes the update list according to initialization status.
Data Fields
int num_added_total
Count of the total number of time-types placed in the update tree or in the initialization tree.
TimeEnum::TimeFormat sim_start_format
Calendar, truncated_julian, etc.
TimeManager * time_manager
Pointer to the Time Manager.
std::string initializer
Name of the time-type used for initialization.
Protected Attributes
int initializer_index
Index-value of the initializer.
int dyn_time_index
Index-value of the type dyn-time.
int num_added_pass
Count of number of time-types placed in the update tree or in the initialization tree in any given pass.
int * converter_ptrs_index
List of the indices (in the TimeManager->time_converter_ptrs vector) of all registered converters, sorted by the indices of the time-types the converters act upon (most pairs of time-types have no converter registered; the value of these indices is -1)
int * init_converter_dir_table
List of directions available for initialization for each of the converters listed in converter_class_ptrs.
int * update_converter_dir_table
List of directions available for run-time updates for each of the converters listed in converter_class_ptrs.
int * status
A running ledger of properly linked times during update tree and initialization tree construction.
Private Member Functions
void initialize (void)
The TimeManagerInit determines initialization and update paths for conversions between time-types.
void verify_times_setup (void)
A number of checks that the setup is self-consistent.
void populate_converter_registry (void)
The converter registry accounts for all of the converter functions that provide conversions between time types.
void verify_converter_setup (void)
To verify that there are no incompatibilities between specific converters.
void initialize_time_types (void)
Initialize each time type so that it has a starting value corresponding to dynamic_time = 0 and such that the starting values are consistent.
void create_init_tree (void)
Build and verify a "tree-like" structure to ensure that all time representations can be initialized from the single "initializer" representation.
void create_update_tree (void)
(To verify that the update procedures have a tree-like structure, and that all time representations can be updated from the dynamic time.) (Contains 3 functions - create_update_tree builds the tree, populated recursively by add_type_update.
TimeManagerInit (const TimeManagerInit &)
TimeManagerInit & operator= (const TimeManagerInit &)
Friends
class InputProcessor
void init_attrjeod__TimeManagerInit ()
Detailed Description
To initialize the Time Manager.
Definition at line 85 of file time_manager_init.hh.
Constructor & Destructor Documentation
TimeManagerInit() [1/2]
jeod::TimeManagerInit::TimeManagerInit (void)
Construct a TimeManagerInit.
Definition at line 64 of file time_manager_init.cc.
References converter_ptrs_index, dyn_time_index, init_converter_dir_table, initializer_index, num_added_pass, num_added_total, sim_start_format, status, jeod::TimeEnum::undefined, and update_converter_dir_table.
~TimeManagerInit()
jeod::TimeManagerInit::~TimeManagerInit (void)
Destroy a TimeManagerInit.
Definition at line 809 of file time_manager_init.cc.
References converter_ptrs_index, init_converter_dir_table, JEOD_DELETE_ARRAY, status, and update_converter_dir_table.
TimeManagerInit() [2/2]
jeod::TimeManagerInit::TimeManagerInit (const TimeManagerInit &) private
Member Function Documentation
create_init_tree()
void jeod::TimeManagerInit::create_init_tree (void) private
Build and verify a "tree-like" structure to ensure that all time representations can be initialized from the single "initializer" representation.
Create_init_tree builds the tree, using add_type_initialize to populate the tree recursively.
Assumptions and Limitations
This is vastly improved if the user defines the parent type "initialize_from" for each time representation, except the top-level initializer type
Otherwise, the code will build the tree automatically, but it takes longer and may be less than ideal
Definition at line 428 of file time_manager_init.cc.
References dyn_time_index, jeod::MessageHandler::fail(), jeod::TimeMessages::initialization_error, initializer_index, jeod::TimeMessages::invalid_setup_error, num_added_pass, num_added_total, jeod::TimeManager::num_types, status, jeod::TimeManager::time_lookup(), time_manager, jeod::TimeManager::time_vector, and jeod::JeodBaseTime::update_from_name.
Referenced by initialize_manager().
create_update_tree()
void jeod::TimeManagerInit::create_update_tree (void) private
(To verify that the update procedures have a tree-like structure, and that all time representations can be updated from the dynamic time.) (Contains 3 functions - create_update_tree builds the tree, populated recursively by add_type_update.
record_update records the update paths to facilitate runtime updates)
Assumptions and Limitations
None
Definition at line 571 of file time_manager_init.cc.
References dyn_time_index, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeMessages::initialization_error, num_added_pass, num_added_total, jeod::TimeManager::num_types, organize_update_list(), status, time_manager, and jeod::TimeManager::time_vector.
Referenced by initialize_manager().
get_conv_dir_init()
int jeod::TimeManagerInit::get_conv_dir_init (const int index)
Takes a calculated converter index - calculated by combining the indices of two time-types, a "from" and a "to" - and returns the direction needed to use the appropriate converter to go from "from" to "to".
Assumptions and Limitations
Returns 0 if no suitable converter available at initialization
Returns
Index corresponding to TimeConverter
Parameters
[in] index Index of object
Definition at line 710 of file time_manager_init.cc.
References init_converter_dir_table.
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), jeod::TimeUDE::convert_epoch_to_update(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), and jeod::TimeUDE::initialize_initializer_time().
get_conv_dir_upd()
int jeod::TimeManagerInit::get_conv_dir_upd (const int index)
Takes a calculated converter index - calculated by combining the indices of two time-types, a "from" and a "to" - and returns the direction needed to use the appropriate converter to go from "from" to "to".
Assumptions and Limitations
Returns 0 if no suitable converter available at update
Returns
Index corresponding to TimeConverter
Parameters
[in] index Index of object
Definition at line 736 of file time_manager_init.cc.
References update_converter_dir_table.
Referenced by jeod::JeodBaseTime::add_type_update().
get_conv_ptr_index()
int jeod::TimeManagerInit::get_conv_ptr_index (const int index_in)
Takes a calculated converter index - calculated by combining the two time-type indices - and return the index in the time_manager's vector of converters that corresponds to those two time-types.
Returns
Index corresponding to TimeConverter
Parameters
[in] index_in Index of object
Definition at line 684 of file time_manager_init.cc.
References converter_ptrs_index.
Referenced by jeod::JeodBaseTime::add_type_update(), jeod::TimeUDE::convert_epoch_to_update(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), and jeod::TimeUDE::initialize_initializer_time().
get_status()
int jeod::TimeManagerInit::get_status (const int index)
Returns the status of a time-type.
Returns
Integer corresponding to Status
Parameters
[in] index Index of object
Definition at line 758 of file time_manager_init.cc.
References status.
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), and jeod::JeodBaseTime::add_type_update().
increment_status()
void jeod::TimeManagerInit::increment_status (const int index_slave, const int index_master)
Modifies the status of one time-type to be one higher than that of another type for initialization purposes.
Parameters
[in] index_slave Index of object
[in] index_master Index of object
Definition at line 795 of file time_manager_init.cc.
References num_added_pass, and status.
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), and jeod::JeodBaseTime::add_type_update().
initialize()
void jeod::TimeManagerInit::initialize (void) private
The TimeManagerInit determines initialization and update paths for conversions between time-types.
This function creates and initializes the data structures necessary for these determinations
Assumptions and Limitations
None
Definition at line 139 of file time_manager_init.cc.
References converter_ptrs_index, jeod::TimeManager::dyn_time, dyn_time_index, jeod::JeodBaseTime::index, init_converter_dir_table, jeod::JeodBaseTime::initialized, initializer, initializer_index, JEOD_ALLOC_PRIM_ARRAY, jeod::JeodBaseTime::seconds, status, jeod::TimeManager::time_lookup(), time_manager, jeod::TimeManager::time_vector, update_converter_dir_table, and verify_times_setup().
Referenced by initialize_manager().
initialize_manager()
void jeod::TimeManagerInit::initialize_manager (TimeManager * time_mgr)
The master program behind the initialization of the time types and the time converters.
Assumptions and Limitations
None
Parameters
[in,out] time_mgr The time manager
Definition at line 94 of file time_manager_init.cc.
References create_init_tree(), create_update_tree(), initialize(), initialize_time_types(), populate_converter_registry(), time_manager, and verify_converter_setup().
Referenced by jeod::TimeManager::initialize().
initialize_time_types()
void jeod::TimeManagerInit::initialize_time_types (void) private
Initialize each time type so that it has a starting value corresponding to dynamic_time = 0 and such that the starting values are consistent.
Initialize_time_types repetitively calls initialize_from_parent for each time type; initialize_from_parent recursively adds types moving up the tree as necessary
Assumptions and Limitations
An initializer time defined by the user
Definition at line 538 of file time_manager_init.cc.
References jeod::TimeManager::get_time_ptr(), jeod::JeodBaseTime::initialize_from_parent(), jeod::JeodBaseTime::initialized, initializer_index, jeod::TimeManager::num_types, time_manager, and jeod::TimeManager::time_vector.
Referenced by initialize_manager().
operator=()
TimeManagerInit& jeod::TimeManagerInit::operator= (const TimeManagerInit &) private
organize_update_list()
void jeod::TimeManagerInit::organize_update_list ()
Reorganizes the update list according to initialization status.
Definition at line 634 of file time_manager_init.cc.
References jeod::TimeManager::num_types, status, time_manager, and jeod::TimeManager::time_vector.
Referenced by create_update_tree().
populate_converter_registry()
void jeod::TimeManagerInit::populate_converter_registry (void) private
The converter registry accounts for all of the converter functions that provide conversions between time types.
This function populates that registry so that the existence of functional converter functions can be tested efficiently.
Assumptions and Limitations
None
Definition at line 275 of file time_manager_init.cc.
References jeod::TimeConverter::A_TO_B_INIT, jeod::TimeConverter::A_TO_B_UPDATE, jeod::TimeConverter::B_TO_A_INIT, jeod::TimeConverter::B_TO_A_UPDATE, converter_ptrs_index, jeod::TimeManager::converter_vector, jeod::MessageHandler::fail(), jeod::MessageHandler::inform(), init_converter_dir_table, jeod::TimeManager::num_types, jeod::TimeMessages::redundancy_error, jeod::TimeManager::time_lookup(), time_manager, jeod::TimeManager::time_vector, and update_converter_dir_table.
Referenced by initialize_manager().
set_status()
void jeod::TimeManagerInit::set_status (const int index, const int new_status)
Receives an updated value for the status of a time-type.
Parameters
[in] index Index of object
[in] new_status New status value
Definition at line 779 of file time_manager_init.cc.
References status.
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), and jeod::JeodBaseTime::add_type_update().
verify_converter_setup()
void jeod::TimeManagerInit::verify_converter_setup (void) private
To verify that there are no incompatibilities between specific converters.
Assumptions and Limitations
The instance of TimeTAI, if it exists, has name "TAI"
The instance of TimeUTC, if it exists, has name "UTC"
The instance of TimeUT1, if it exists, has name "UT1"
Definition at line 365 of file time_manager_init.cc.
References converter_ptrs_index, jeod::MessageHandler::fail(), jeod::TimeMessages::invalid_setup_error, jeod::TimeManager::num_types, jeod::TimeConverter_TAI_UTC::override_data_table, jeod::TimeConverter_TAI_UT1::override_data_table, jeod::TimeManager::time_lookup(), and time_manager.
Referenced by initialize_manager().
verify_times_setup()
void jeod::TimeManagerInit::verify_times_setup (void) private
A number of checks that the setup is self-consistent.
Assumptions and Limitations
None
Definition at line 205 of file time_manager_init.cc.
References jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, initializer, initializer_index, jeod::TimeMessages::invalid_setup_error, jeod::TimeManager::num_types, jeod::TimeMessages::redundancy_error, time_manager, and jeod::TimeManager::time_vector.
Referenced by initialize().
Friends And Related Function Documentation
init_attrjeod__TimeManagerInit
void init_attrjeod__TimeManagerInit () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file time_manager_init.hh.
Field Documentation
converter_ptrs_index
int* jeod::TimeManagerInit::converter_ptrs_index protected
List of the indices (in the TimeManager->time_converter_ptrs vector) of all registered converters, sorted by the indices of the time-types the converters act upon (most pairs of time-types have no converter registered; the value of these indices is -1)
trick_units(–)
Definition at line 132 of file time_manager_init.hh.
Referenced by get_conv_ptr_index(), initialize(), populate_converter_registry(), TimeManagerInit(), verify_converter_setup(), and ~TimeManagerInit().
dyn_time_index
int jeod::TimeManagerInit::dyn_time_index protected
Index-value of the type dyn-time.
trick_units(–)
Definition at line 119 of file time_manager_init.hh.
Referenced by create_init_tree(), create_update_tree(), initialize(), and TimeManagerInit().
init_converter_dir_table
int* jeod::TimeManagerInit::init_converter_dir_table protected
List of directions available for initialization for each of the converters listed in converter_class_ptrs.
trick_units(–)
Definition at line 137 of file time_manager_init.hh.
Referenced by get_conv_dir_init(), initialize(), populate_converter_registry(), TimeManagerInit(), and ~TimeManagerInit().
initializer
std::string jeod::TimeManagerInit::initializer
Name of the time-type used for initialization.
trick_units(–)
Definition at line 109 of file time_manager_init.hh.
Referenced by initialize(), and verify_times_setup().
initializer_index
int jeod::TimeManagerInit::initializer_index protected
Index-value of the initializer.
trick_units(–)
Definition at line 114 of file time_manager_init.hh.
Referenced by create_init_tree(), initialize(), initialize_time_types(), TimeManagerInit(), and verify_times_setup().
num_added_pass
int jeod::TimeManagerInit::num_added_pass protected
Count of number of time-types placed in the update tree or in the initialization tree in any given pass.
trick_units(–)
Definition at line 124 of file time_manager_init.hh.
Referenced by create_init_tree(), create_update_tree(), increment_status(), and TimeManagerInit().
num_added_total
int jeod::TimeManagerInit::num_added_total
Count of the total number of time-types placed in the update tree or in the initialization tree.
trick_units(–)
Definition at line 96 of file time_manager_init.hh.
Referenced by jeod::JeodBaseTime::add_type_update(), create_init_tree(), create_update_tree(), and TimeManagerInit().
sim_start_format
TimeEnum::TimeFormat jeod::TimeManagerInit::sim_start_format
Calendar, truncated_julian, etc.
trick_units(–)
Definition at line 100 of file time_manager_init.hh.
Referenced by jeod::TimeStandard::initialize_initializer_time(), jeod::TimeUDE::initialize_initializer_time(), and TimeManagerInit().
status
int* jeod::TimeManagerInit::status protected
A running ledger of properly linked times during update tree and initialization tree construction.
Entries correspond to times of shared indexes in time_vector (e.g. status[2] : status of time_manager->time_vector[2]) Update tree encoding: -2: undefined. Requires auto-assignment or causes error. -1: definitive error. Process will terminate. 0: uninitialized 1: THE 1st generation (root) time. dyn_time for update tree. 2: a 2nd generation time, converted from root time. n: a nth gen time, converted from (n-1)th gen time.trick_units(–)
Definition at line 156 of file time_manager_init.hh.
Referenced by create_init_tree(), create_update_tree(), get_status(), increment_status(), initialize(), organize_update_list(), set_status(), TimeManagerInit(), and ~TimeManagerInit().
time_manager
TimeManager* jeod::TimeManagerInit::time_manager
Pointer to the Time Manager.
Automatically linked during init routines.trick_units(–)
Definition at line 104 of file time_manager_init.hh.
Referenced by create_init_tree(), create_update_tree(), initialize(), initialize_manager(), initialize_time_types(), organize_update_list(), populate_converter_registry(), verify_converter_setup(), and verify_times_setup().
update_converter_dir_table
int* jeod::TimeManagerInit::update_converter_dir_table protected
List of directions available for run-time updates for each of the converters listed in converter_class_ptrs.
trick_units(–)
Definition at line 142 of file time_manager_init.hh.
Referenced by get_conv_dir_upd(), initialize(), populate_converter_registry(), TimeManagerInit(), and ~TimeManagerInit().
The documentation for this class was generated from the following files:
time_manager_init.hh
time_manager_init.cc