JEOD: jeod::BasePendulumModel Class Reference
jeod::BasePendulumModel Class Reference abstract
Abstract base class that defines interfaces needed to model a spherical pendulum as a constrained object.
#include <base_pendulum_model.hh>
Public Member Functions
BasePendulumModel ()=default
Default constructor.
virtual ~BasePendulumModel ()=default
Destructor.
virtual void update_pendulum_model ()=0
Update the pendulum model.
virtual void get_hinge_point (double hinge_point[3]) const =0
Get the location of the hinge point in the constraint frame.
virtual double get_pendulum_mass () const =0
Get the mass of the pendulum bob.
virtual double get_pendulum_length () const =0
Get the length of the pendulum rod.
virtual double compute_damping_factor (double accel_mag)=0
Compute the damping factor based on the input acceleration.
Friends
class InputProcessor
void init_attrjeod__BasePendulumModel ()
Detailed Description
Abstract base class that defines interfaces needed to model a spherical pendulum as a constrained object.
Definition at line 68 of file base_pendulum_model.hh.
Constructor & Destructor Documentation
BasePendulumModel()
jeod::BasePendulumModel::BasePendulumModel () default
Default constructor.
~BasePendulumModel()
virtual jeod::BasePendulumModel::~BasePendulumModel () virtual default
Destructor.
Member Function Documentation
compute_damping_factor()
virtual double jeod::BasePendulumModel::compute_damping_factor (double accel_mag) pure virtual
Compute the damping factor based on the input acceleration.
Parameters
accel_mag Representative acceleration such as the magnitude of the non-gravitational acceleration, or the tension force divided by mass.
Returns
Damping factor, with units of inverse time.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response().
get_hinge_point()
virtual void jeod::BasePendulumModel::get_hinge_point (double hinge_point[3]) const pure virtual
Get the location of the hinge point in the constraint frame.
Parameters
hinge_point Vector to be populated with hinge point location, in meters relative to the origin of the constraint frame.
Referenced by jeod::PendulumConstraintComponent::reset_integrators(), and jeod::PendulumConstraintComponent::setup_constraint().
get_pendulum_length()
virtual double jeod::BasePendulumModel::get_pendulum_length () const pure virtual
Get the length of the pendulum rod.
Returns
Pendulum rod length, in meters.
Referenced by jeod::PendulumConstraintComponent::reset_integrators(), and jeod::PendulumConstraintComponent::setup_constraint().
get_pendulum_mass()
virtual double jeod::BasePendulumModel::get_pendulum_mass () const pure virtual
Get the mass of the pendulum bob.
Returns
Pendulum bob mass, in kilograms.
Referenced by jeod::PendulumConstraintComponent::reset_integrators(), and jeod::PendulumConstraintComponent::setup_constraint().
update_pendulum_model()
virtual void jeod::BasePendulumModel::update_pendulum_model () pure virtual
Update the pendulum model.
Referenced by jeod::PendulumConstraintComponent::reset_integrators().
Friends And Related Function Documentation
init_attrjeod__BasePendulumModel
void init_attrjeod__BasePendulumModel () friend
InputProcessor
friend class InputProcessor friend
Definition at line 71 of file base_pendulum_model.hh.
The documentation for this class was generated from the following file:
base_pendulum_model.hh