JEOD: jeod::MassPointInit Class Reference
jeod::MassPointInit Class Reference
Contains data used to initialize a MassPoint.
#include <mass_point_init.hh>
Public Types
enum FrameSpec {
StructToBody = 0, StructToCase = 0, StructToPoint = 0, StructToChild = 0,
BodyToStruct = 1, CaseToStruct = 1, PointToStruct = 1, ChildToStruct = 1
}
Specifies sense of the input point orientation data.
Public Member Functions
MassPointInit ()
Default constructor; constructs a MassPointInit object.
virtual ~MassPointInit ()=default
Destructor.
void initialize_mass_point (MassPoint &mass_point) const
Default constructor; constructs a MassPointInit object.
void set_name (std::string name_in)
Set the name.
Data Fields
double position [3]
Mass point location expressed in mass element structural coordinates.
Orientation pt_orientation
Mass point frame orientation specification.
FrameSpec pt_frame_spec
Indicates whether user orientation input defines the structure-to-body or body-to-structure transformation matrix.
std::string name
Item name, with the following semantics for items that have a name:
Friends
class InputProcessor
void init_attrjeod__MassPointInit ()
Detailed Description
Contains data used to initialize a MassPoint.
Definition at line 88 of file mass_point_init.hh.
Member Enumeration Documentation
FrameSpec
enum jeod::MassPointInit::FrameSpec
Specifies sense of the input point orientation data.
The overloading of names is intentional.
Enumerator
StructToBody
Orientation specifies structure-to-body transform.
StructToCase
Orientation specifies structure-to-case transform.
StructToPoint
Orientation specifies structure-to-point transform.
StructToChild
Orientation specifies structure-to-child transform.
BodyToStruct
Orientation specifies body-to-structure transform.
CaseToStruct
Orientation specifies case-to-structure transform.
PointToStruct
Orientation specifies point-to-structure transform.
ChildToStruct
Orientation specifies child-to-structure transform.
Definition at line 98 of file mass_point_init.hh.
Constructor & Destructor Documentation
MassPointInit()
jeod::MassPointInit::MassPointInit ()
Default constructor; constructs a MassPointInit object.
Definition at line 57 of file mass_point_init.cc.
References jeod::Vector3::initialize(), and position.
~MassPointInit()
virtual jeod::MassPointInit::~MassPointInit () virtual default
Destructor.
Member Function Documentation
initialize_mass_point()
void jeod::MassPointInit::initialize_mass_point (MassPoint & mass_point) const
Default constructor; constructs a MassPointInit object.
Parameters
[out] mass_point Point to initialize
Definition at line 73 of file mass_point_init.cc.
References jeod::Orientation::compute_transformation_and_quaternion(), jeod::Quaternion::conjugate(), jeod::Matrix3x3::copy(), jeod::MessageHandler::fail(), jeod::MassBodyMessages::invalid_enum, PointToStruct, position, pt_frame_spec, pt_orientation, jeod::MassPointState::Q_parent_this, jeod::Orientation::quat, StructToPoint, jeod::MassPointState::T_parent_this, jeod::Orientation::trans, jeod::Matrix3x3::transpose(), and jeod::MassPointState::update_point().
Referenced by jeod::MassBody::add_mass_point(), and jeod::MassPropertiesInit::initialize_mass_properties().
set_name()
void jeod::MassPointInit::set_name (std::string name_in) inline
Set the name.
Definition at line 155 of file mass_point_init.hh.
References name.
Friends And Related Function Documentation
init_attrjeod__MassPointInit
void init_attrjeod__MassPointInit () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file mass_point_init.hh.
Field Documentation
name
std::string jeod::MassPointInit::name
Item name, with the following semantics for items that have a name:
The mass point name will always be of the form "mass_name.point_name".
If the supplied name does not begin with "mass_name.", this prefix will be applied to the supplied name in naming the mass point.
This can be left as the empty string for items that don't have a name.trick_units(–)
Definition at line 136 of file mass_point_init.hh.
Referenced by jeod::MassBody::add_mass_point(), jeod::ContactFacet::create_vehicle_point(), and set_name().
position
double jeod::MassPointInit::position[3]
Mass point location expressed in mass element structural coordinates.
trick_units(m)
Definition at line 115 of file mass_point_init.hh.
Referenced by jeod::ContactFacet::create_vehicle_point(), initialize_mass_point(), MassPointInit(), and jeod::MassPropertiesInit::MassPropertiesInit().
pt_frame_spec
FrameSpec jeod::MassPointInit::pt_frame_spec
Indicates whether user orientation input defines the structure-to-body or body-to-structure transformation matrix.
trick_units(–)
Definition at line 126 of file mass_point_init.hh.
Referenced by jeod::ContactFacet::create_vehicle_point(), and initialize_mass_point().
pt_orientation
Orientation jeod::MassPointInit::pt_orientation
Mass point frame orientation specification.
trick_units(–)
Definition at line 120 of file mass_point_init.hh.
Referenced by jeod::ContactFacet::create_vehicle_point(), and initialize_mass_point().
The documentation for this class was generated from the following files:
mass_point_init.hh
mass_point_init.cc