JEOD: jeod::TimeUT1 Class Reference
jeod::TimeUT1 Class Reference
Represents Universal Time.
#include <time_ut1.hh>
Public Member Functions
TimeUT1 ()
Construct a Time_UT1.
~TimeUT1 () override=default
TimeUT1 (const TimeUT1 &)=delete
TimeUT1 & operator= (const TimeUT1 &)=delete
double get_days ()
Accesses days.
Public Member Functions inherited from jeod::TimeStandard
TimeStandard ()=default
~TimeStandard () override=default
TimeStandard (const TimeStandard &)=delete
TimeStandard & operator= (const TimeStandard &)=delete
void calendar_update (double simtime)
Calls the function that converts the Julian-type representation of time (dd.xxxx days) to a calendar representation.
void initialize_initializer_time (TimeManagerInit *tm_init) override
Each time type is initialized from its parent in the initialization tree, except one.
void add_type_initialize (const int seeking_status, TimeManagerInit *tm_init) override
Recursively adds elements to the initialization tree.
void initialize_from_parent (TimeManagerInit *tm_init) override
Initialize a time type from its parent on the initialization tree.
void set_time_by_seconds (const double new_seconds) override
Given a value of seconds, propagate to days and trunc_julian_time.
void set_time_by_days (const double new_days) override
Given a value of days, propagate to seconds and trunc_julian_time.
void set_time_by_trunc_julian (const double new_tjt)
Given a value of tjt, propagate to seconds and days.
double julian_date_at_epoch ()
Returns the full Julian date at epoch, rather than the Truncated Julian Time.
double seconds_of_year ()
Generate the number of seconds elapsed this year.
Public Member Functions inherited from jeod::JeodBaseTime
JeodBaseTime ()
Construct a JeodBaseTime.
virtual ~JeodBaseTime ()
Destroy a JeodBaseTime.
JeodBaseTime (const JeodBaseTime &)=delete
JeodBaseTime & operator= (const JeodBaseTime &)=delete
virtual bool must_be_singleton ()
Virtual function that indicates if class must be a singleton Defaults to yes.
void add_type_update (const int seeking_status, TimeManagerInit *tm_init)
Recursively adds elements to the update tree.
void set_name (std::string name_in)
Setter for the name.
void set_index (int idx)
Setter for the index (force user to be carefule)
int get_index ()
Getter for the index.
void override_initialized (bool init)
Force reset the initialization status.
bool is_initialized ()
Read the initialization status.
virtual void update ()
Updates each of the derived times from its parent time.
Data Fields
bool true_ut1 {true}
"False" for comparison with older versions of JEOD
Data Fields inherited from jeod::TimeStandard
double last_calendar_update {-100000.0}
The simtime when the calendar update was last run.
int prev_julian_day {-1000000000}
Used for determining whether to update the date in the calendar function.
double seconds_at_year_start {}
The value of "seconds" at the start of the year in which the last seconds_of_year calculation was made.
int year_of_last_soy {-1000000}
The year in which the last seconds_of_year calculation was made.
bool send_warning_pre_1968 {true}
This flag can be turned off by developers wanting to avoid warnings about a simulation being initialized pre-1968.
const double tjt_mjt_offset {40000.0}
Difference between Truncated Julian and Modified Julian.
const double tjt_jd_offset {2440000.5}
Difference between Julian and Truncated Julian.
double trunc_julian_time {}
Truncated Julian time for this time-type.
double julian_date {}
Conventional Julian Date.
double tjt_at_epoch {}
Truncated Julian Date at epoch.
int calendar_day {}
Gregorian calendar date day number.
int calendar_hour {}
24-hour clock hour number.
int calendar_minute {}
Clock minute number.
double calendar_second {}
Clock second number.
int calendar_year {}
Gregorian calendar year.
int calendar_month {}
Gregorian calendar month.
Data Fields inherited from jeod::JeodBaseTime
double initializing_value {}
Value used to define sim start time.
int update_converter_direction {}
Determines which converter function (a_to_b (+1) or b_to_a (-1)) to use.
double seconds {}
Elapsed time from epoch.
NamedItem name
Name of time-type.
std::string initialize_from_name {""}
Name of time-type from which initial value is derived.
std::string update_from_name {""}
Name of time-type from which update values are derived.
TimeManager * time_manager {}
Pointer to the TimeManager.
TimeConverter * update_converter_ptr {}
Pointer to the converter class needed to update the time.
Private Member Functions
void set_epoch () override
Sets the epoch for UT1 time.
Friends
class InputProcessor
void init_attrjeod__TimeUT1 ()
Additional Inherited Members
Protected Member Functions inherited from jeod::TimeStandard
virtual void convert_from_calendar ()
Calculate Truncated Julian date/time from Gregorian calendar date and 24-hour clock representation.
virtual void calculate_calendar_values ()
Calculate Gregorian calendar date and 24-hour clock representation from Truncated Julian date/time.
Protected Member Functions inherited from jeod::JeodBaseTime
void add_parent (JeodBaseTime &parent)
Link the argument time as the update source for this time.
Protected Attributes inherited from jeod::JeodBaseTime
int index {}
Index-value of time-type in the registry.
bool initialized {}
Whether time has been initialized to a real time.
double days {}
Elapsed time from epoch.
double initial_value {}
Value of "seconds" at the start of the sim.
double clock_resolution {0.0001}
The resolution limit when generating clock and calendar-clock values.
TimeLinks links
Linkage to the hierarchy of time conversions.
Detailed Description
Represents Universal Time.
Definition at line 82 of file time_ut1.hh.
Constructor & Destructor Documentation
TimeUT1() [1/2]
jeod::TimeUT1::TimeUT1 ()
Construct a Time_UT1.
Definition at line 49 of file time_ut1.cc.
References jeod::JeodBaseTime::name, and set_epoch().
~TimeUT1()
jeod::TimeUT1::~TimeUT1 () override default
TimeUT1() [2/2]
jeod::TimeUT1::TimeUT1 (const TimeUT1 &) delete
Member Function Documentation
get_days()
double jeod::TimeUT1::get_days ()
Accesses days.
Returns
days value
Units: d
Definition at line 67 of file time_ut1.cc.
References jeod::JeodBaseTime::days.
Referenced by jeod::TimeConverter_UT1_GMST::convert_a_to_b().
operator=()
TimeUT1& jeod::TimeUT1::operator= (const TimeUT1 &) delete
set_epoch()
void jeod::TimeUT1::set_epoch () override private virtual
Sets the epoch for UT1 time.
Implements jeod::TimeStandard.
Definition at line 58 of file time_ut1.cc.
References jeod::TimeStandard::tjt_at_epoch.
Referenced by TimeUT1().
Friends And Related Function Documentation
init_attrjeod__TimeUT1
void init_attrjeod__TimeUT1 () friend
InputProcessor
friend class InputProcessor friend
Definition at line 84 of file time_ut1.hh.
Field Documentation
true_ut1
bool jeod::TimeUT1::true_ut1 {true}
"False" for comparison with older versions of JEOD
trick_units(–)
Definition at line 89 of file time_ut1.hh.
Referenced by jeod::TimeConverter_TAI_UT1::convert_a_to_b(), jeod::TimeConverter_TAI_UT1::convert_b_to_a(), jeod::TimeConverter_TAI_UT1::initialize_tai_to_ut1(), and jeod::TimeConverter_TAI_UT1::verify_table_lookup_ends().
The documentation for this class was generated from the following files:
time_ut1.hh
time_ut1.cc