JEOD: jeod::GravityManager Class Reference
jeod::GravityManager Class Reference
The master gravitational model for a simulation.
#include <gravity_manager.hh>
Public Member Functions
GravityManager ()
GravityManager constructor.
~GravityManager ()
GravityManager destructor.
GravitySource * find_grav_source (const std::string &source_name) const
Find the gravitational body with the given name.
void add_grav_source (GravitySource &source)
Create a gravitational body, initialize it with the supplied gravity coefficients, and add it to the vector of bodies.
void initialize_model (BaseDynManager &manager)
Perform base initialization.
void initialize_state (const BaseDynManager &manager)
Pass the initialize_state method to each GravitySource object registered with the gravity manager.
void gravitation (const double integ_pos[3], GravityInteraction &grav)
Compute the gravitational attraction of gravitational bodies on the provided dynamic body.
void gravitation (const RefFrame &point, GravityInteraction &grav)
Compute the gravitational attraction of gravitational bodies on the provided dynamic body.
const std::vector< GravitySource * > & get_bodies () const
Get the vector of gravitational bodies.
Private Member Functions
GravityManager (const GravityManager &)
GravityManager & operator= (const GravityManager &)
Private Attributes
JeodPointerVector< GravitySource >::type sources
The gravitational bodies.
Friends
class InputProcessor
void init_attrjeod__GravityManager ()
Detailed Description
The master gravitational model for a simulation.
Definition at line 91 of file gravity_manager.hh.
Constructor & Destructor Documentation
GravityManager() [1/2]
jeod::GravityManager::GravityManager (const GravityManager &) private
GravityManager() [2/2]
jeod::GravityManager::GravityManager (void)
GravityManager constructor.
Definition at line 59 of file gravity_manager.cc.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and JEOD_REGISTER_INCOMPLETE_CLASS.
~GravityManager()
jeod::GravityManager::~GravityManager (void)
GravityManager destructor.
Definition at line 71 of file gravity_manager.cc.
References JEOD_DEREGISTER_CHECKPOINTABLE, and sources.
Member Function Documentation
add_grav_source()
void jeod::GravityManager::add_grav_source (GravitySource & source)
Create a gravitational body, initialize it with the supplied gravity coefficients, and add it to the vector of bodies.
Parameters
[in] source Gravity source to be added
Definition at line 118 of file gravity_manager.cc.
References jeod::GravityMessages::duplicate_entry, jeod::MessageHandler::fail(), find_grav_source(), jeod::GravityMessages::invalid_name, jeod::GravitySource::name, and sources.
find_grav_source()
GravitySource * jeod::GravityManager::find_grav_source (const std::string & source_name) const
Find the gravitational body with the given name.
Returns
Pointer to found body
Parameters
[in] source_name Name of gravity source to be found
Definition at line 85 of file gravity_manager.cc.
References jeod::MessageHandler::error(), jeod::GravityMessages::invalid_name, jeod::GravitySource::name, and sources.
Referenced by add_grav_source(), and jeod::GravityControls::initialize_control().
get_bodies()
const std::vector<GravitySource*>& jeod::GravityManager::get_bodies () const inline
Get the vector of gravitational bodies.
Warning
Do not modify the vector, or elements of it.
Definition at line 163 of file gravity_manager.hh.
References sources.
Referenced by jeod::GravityControls::calc_relativistic().
gravitation() [1/2]
void jeod::GravityManager::gravitation (const double integ_pos[3], GravityInteraction & grav)
Compute the gravitational attraction of gravitational bodies on the provided dynamic body.
Assumptions and Limitations
Only the gravitational bodies specified in the dynamic body's gravity controls have a bearing on the dynamic body's state.
Warning
This overload is deprecated.
Parameters
[in] integ_pos Dyn body location (integ frm)
Units: M
[in,out] grav Gravity interaction
Definition at line 193 of file gravity_manager.cc.
References jeod::GravityControls::active, jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::GravityInteraction::grav_accel, jeod::GravityControls::grav_accel, jeod::GravityInteraction::grav_controls, jeod::GravityInteraction::grav_grad, jeod::GravityControls::grav_grad, jeod::GravityInteraction::grav_pot, jeod::GravityControls::grav_pot, jeod::GravityControls::gravitation(), jeod::Matrix3x3::incr(), jeod::Vector3::incr(), and jeod::GravityInteraction::integ_frame_index.
Referenced by jeod::DynamicsIntegrationGroup::gravitation().
gravitation() [2/2]
void jeod::GravityManager::gravitation (const RefFrame & point, GravityInteraction & grav)
Compute the gravitational attraction of gravitational bodies on the provided dynamic body.
Assumptions and Limitations
Only the gravitational bodies specified in the dynamic body's gravity controls have a bearing on the dynamic body's state.
The supplied reference frame is assumed to be a direct child of the dynamic body's integration frame.
Parameters
[in] point Point of interest, as a reference frame.
[in,out] grav Gravity interaction
Definition at line 240 of file gravity_manager.cc.
References jeod::GravityControls::active, jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::GravityInteraction::grav_accel, jeod::GravityControls::grav_accel, jeod::GravityInteraction::grav_controls, jeod::GravityInteraction::grav_grad, jeod::GravityControls::grav_grad, jeod::GravityInteraction::grav_pot, jeod::GravityControls::grav_pot, jeod::GravityControls::gravitation(), jeod::Matrix3x3::incr(), jeod::Vector3::incr(), and jeod::GravityInteraction::integ_frame_index.
initialize_model()
void jeod::GravityManager::initialize_model (BaseDynManager & manager)
Perform base initialization.
Note
This method differs from the other initialize_models methods in that this method takes no coefficients as arguments. The S_define must call add_grav_source explicitly when this signature is used.
Parameters
[in,out] manager Dynamics manager
Definition at line 154 of file gravity_manager.cc.
References jeod::BaseDynManager::set_gravity_manager().
initialize_state()
void jeod::GravityManager::initialize_state (const BaseDynManager & manager)
Pass the initialize_state method to each GravitySource object registered with the gravity manager.
Assumptions and Limitations
Initialization phasing: The following must have been called prior to calling this method:
GravityManager::initialize_model to register the GravityManager object with the dynamics manager
GravityManager::add_grav_source to register all GravitySource objects in the simulation with the gravity manager.
Planet::register_model to associate the planet with a GravitySource.
DynamicsManager::activate_ephemerides to identify which reference frames can serve as integration frames.
Parameters
[in,out] manager Dynamics manager
Definition at line 178 of file gravity_manager.cc.
References jeod::BaseEphemeridesManager::get_integ_frames(), and sources.
Referenced by jeod::DynManager::initialize_simulation().
operator=()
GravityManager& jeod::GravityManager::operator= (const GravityManager &) private
Friends And Related Function Documentation
init_attrjeod__GravityManager
void init_attrjeod__GravityManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file gravity_manager.hh.
Field Documentation
sources
JeodPointerVector<GravitySource>::type jeod::GravityManager::sources private
The gravitational bodies.
trick_io(**)
Definition at line 105 of file gravity_manager.hh.
Referenced by add_grav_source(), find_grav_source(), get_bodies(), initialize_state(), and ~GravityManager().
The documentation for this class was generated from the following files:
gravity_manager.hh
gravity_manager.cc