JEOD: jeod::ContactUtils Class Reference
jeod::ContactUtils Class Reference
Utility string and math functions for the contact model.
#include <contact_utils.hh>
Static Public Member Functions
static int create_relstate_name (char *name1, char *name2, char **out_str)
create a name for a relstate out of two facet names
static int copy_const_char_to_char (const char *in_str, char **out_str)
create a name for a relstate out of two facet names
static int dist_line_segments (double p1[3], double p2[3], double p3[3], double p4[3], double *pa, double *pb)
calculate the closest points between two line segments
Detailed Description
Utility string and math functions for the contact model.
Definition at line 71 of file contact_utils.hh.
Member Function Documentation
copy_const_char_to_char()
int jeod::ContactUtils::copy_const_char_to_char (const char * in_str, char ** out_str) inline static
create a name for a relstate out of two facet names
Returns
int
Parameters
[in] in_str const char input
[in,out] out_str char output
Definition at line 121 of file contact_utils_inline.hh.
Referenced by jeod::LineContactPair::initialize_pair(), jeod::PointContactPair::initialize_pair(), and jeod::LinePointContactPair::initialize_pair().
create_relstate_name()
int jeod::ContactUtils::create_relstate_name (char * name1, char * name2, char ** out_str) inline static
create a name for a relstate out of two facet names
Returns
char**
Parameters
[in] name1 name of first contact facet
[in] name2 name of second contact facet
[in,out] out_str output name for the relstate
Definition at line 93 of file contact_utils_inline.hh.
dist_line_segments()
int jeod::ContactUtils::dist_line_segments (double p1[3], double p2[3], double p3[3], double p4[3], double * pa, double * pb) inline static
calculate the closest points between two line segments
Returns
success
Parameters
[in] p1 vector to one point of the first line seg
Units: M
[in] p2 vector to one point of the first line seg
Units: M
[in] p3 vector to one point of the second line seg
Units: M
[in] p4 vector to one point of the second line seg
Units: M
[out] pa vector to close_point on line 1
Units: M
[out] pb vector to close_point on line 2
Units: M
Definition at line 156 of file contact_utils_inline.hh.
References jeod::Vector3::copy(), jeod::Vector3::diff(), jeod::Vector3::dot(), jeod::Vector3::scale(), jeod::Vector3::sum(), and jeod::Vector3::vmag().
Referenced by jeod::LineContactPair::in_contact(), and jeod::LinePointContactPair::in_contact().
The documentation for this class was generated from the following files:
contact_utils.hh
contact_utils_inline.hh