JEOD: jeod::MassBodyInit Class Reference
jeod::MassBodyInit Class Reference
Base class for initializing a MassBody.
#include <mass_body_init.hh>
Public Member Functions
MassBodyInit ()=default
~MassBodyInit () override
Destructor.
MassBodyInit (const MassBodyInit &)=delete
MassBodyInit & operator= (const MassBodyInit &)=delete
void apply (DynManager &dyn_manager) override
Initialize the core mass properties of the subject MassBody.
void allocate_points (size_t num_points)
Allocate points.
MassPointInit * get_mass_point (size_t index)
Access a point in the vector.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
virtual void initialize (DynManager &dyn_manager)
Begin initialization of a BodyAction.
virtual bool is_ready ()
In general, determine if the initializer is ready to be applied.
Data Fields
MassPropertiesInit properties
Specifications for the subject mass body's core mass properties.
std::vector< MassPointInit * > points
Specifications for the subject mass body's mass points.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Friends
class InputProcessor
void init_attrjeod__MassBodyInit ()
Additional Inherited Members
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Base class for initializing a MassBody.
Items initialized by this action are
The body's core mass properties
The body's mass points.
Definition at line 88 of file mass_body_init.hh.
Constructor & Destructor Documentation
MassBodyInit() [1/2]
jeod::MassBodyInit::MassBodyInit () default
~MassBodyInit()
jeod::MassBodyInit::~MassBodyInit () override
Destructor.
Definition at line 87 of file mass_body_init.cc.
References JEOD_DELETE_OBJECT, and points.
MassBodyInit() [2/2]
jeod::MassBodyInit::MassBodyInit (const MassBodyInit &) delete
Member Function Documentation
allocate_points()
void jeod::MassBodyInit::allocate_points (size_t num_points)
Allocate points.
Parameters
[in] num_points number of additional points to be allocated.
Definition at line 76 of file mass_body_init.cc.
References JEOD_ALLOC_CLASS_OBJECT, and points.
apply()
void jeod::MassBodyInit::apply (DynManager & dyn_manager) override virtual
Initialize the core mass properties of the subject MassBody.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAction.
Definition at line 55 of file mass_body_init.cc.
References jeod::BodyAction::action_identifier, jeod::BodyAction::apply(), jeod::NamedItem::c_str(), jeod::MessageHandler::debug(), jeod::MassBody::initialize_mass(), jeod::BodyAction::mass_subject, jeod::MassBody::name, points, properties, and jeod::BodyActionMessages::trace.
get_mass_point()
MassPointInit * jeod::MassBodyInit::get_mass_point (size_t index)
Access a point in the vector.
Parameters
[in] index the index of the point in the vector.
Definition at line 100 of file mass_body_init.cc.
References points.
operator=()
MassBodyInit& jeod::MassBodyInit::operator= (const MassBodyInit &) delete
Friends And Related Function Documentation
init_attrjeod__MassBodyInit
void init_attrjeod__MassBodyInit () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file mass_body_init.hh.
Field Documentation
points
std::vector<MassPointInit *> jeod::MassBodyInit::points
Specifications for the subject mass body's mass points.
trick_units(–)
Definition at line 101 of file mass_body_init.hh.
Referenced by allocate_points(), apply(), get_mass_point(), and ~MassBodyInit().
properties
MassPropertiesInit jeod::MassBodyInit::properties
Specifications for the subject mass body's core mass properties.
trick_units(–)
Definition at line 96 of file mass_body_init.hh.
Referenced by apply().
The documentation for this class was generated from the following files:
mass_body_init.hh
mass_body_init.cc