JEOD: jeod::InteractionFacetFactory Class Reference
jeod::InteractionFacetFactory Class Reference abstract
A factory to create a specific interaction facet from a general facet.
#include <interaction_facet_factory.hh>
Public Member Functions
InteractionFacetFactory ()
Default Constructor.
virtual ~InteractionFacetFactory ()
Destructor.
virtual InteractionFacet * create_facet (Facet *facet, FacetParams *params)=0
A pure virtual function that creates a specific interaction facet from a base facet with the given FacetParams.
virtual bool is_correct_factory (Facet *facet)=0
A pure virtual function.
Protected Attributes
bool trick_bool
Unused data field to expedite dynamic allocation in Trick environment.
Private Member Functions
InteractionFacetFactory & operator= (const InteractionFacetFactory &rhs)
InteractionFacetFactory (const InteractionFacetFactory &rhs)
Friends
class InputProcessor
void init_attrjeod__InteractionFacetFactory ()
Detailed Description
A factory to create a specific interaction facet from a general facet.
Definition at line 92 of file interaction_facet_factory.hh.
Constructor & Destructor Documentation
InteractionFacetFactory() [1/2]
jeod::InteractionFacetFactory::InteractionFacetFactory (void)
Default Constructor.
Definition at line 43 of file interaction_facet_factory.cc.
~InteractionFacetFactory()
jeod::InteractionFacetFactory::~InteractionFacetFactory (void) virtual
Destructor.
Definition at line 57 of file interaction_facet_factory.cc.
InteractionFacetFactory() [2/2]
jeod::InteractionFacetFactory::InteractionFacetFactory (const InteractionFacetFactory & rhs) private
Member Function Documentation
create_facet()
virtual InteractionFacet* jeod::InteractionFacetFactory::create_facet (Facet * facet, FacetParams * params) pure virtual
A pure virtual function that creates a specific interaction facet from a base facet with the given FacetParams.
This defines interface for all classes that inherit from InteractionFacetFactory
Returns
The new interaction facet
Parameters
[in] facet The facet the InteractionFacet is created from
[in] params The parameter object to be added.
Implemented in jeod::LineContactFacetFactory, jeod::PointContactFacetFactory, jeod::FlatPlateRadiationFactory, and jeod::FlatPlateAeroFactory.
Referenced by jeod::AeroSurface::allocate_interaction_facet(), jeod::ContactSurface::allocate_interaction_facet(), and jeod::RadiationSurface::allocate_interaction_facet().
is_correct_factory()
virtual bool jeod::InteractionFacetFactory::is_correct_factory (Facet * facet) pure virtual
A pure virtual function.
Returns true or false: is the given facet the type this factory is meant to use?
Returns
true or false. Is the given facet the correct type for this factory?
Parameters
[in] facet The facet that is being checked
Implemented in jeod::LineContactFacetFactory, jeod::PointContactFacetFactory, jeod::FlatPlateAeroFactory, jeod::FlatPlateRadiationFactory, and jeod::FlatPlateThermalAeroFactory.
operator=()
InteractionFacetFactory& jeod::InteractionFacetFactory::operator= (const InteractionFacetFactory & rhs) private
Friends And Related Function Documentation
init_attrjeod__InteractionFacetFactory
void init_attrjeod__InteractionFacetFactory () friend
InputProcessor
friend class InputProcessor friend
Definition at line 94 of file interaction_facet_factory.hh.
Field Documentation
trick_bool
bool jeod::InteractionFacetFactory::trick_bool protected
Unused data field to expedite dynamic allocation in Trick environment.
trick_units(–)
Definition at line 136 of file interaction_facet_factory.hh.
The documentation for this class was generated from the following files:
interaction_facet_factory.hh
interaction_facet_factory.cc