JEOD: jeod::EphemerisRefFrame Class Reference
jeod::EphemerisRefFrame Class Reference
An EphemerisRefFrame is a RefFrame whose state is set by an ephemeris model.
#include <ephem_ref_frame.hh>
Public Member Functions
EphemerisRefFrame ()
Construct an EphemerisRefFrame.
~EphemerisRefFrame () override
Destruct an EphemerisRefFrame.
virtual void set_ephem_manager (BaseEphemeridesManager *manager)
Set the EphemerisRefFrame's owner.
Public Member Functions inherited from jeod::RefFrame
RefFrame (void)
Construct a RefFrame object.
~RefFrame (void) override
Destroy a RefFrame object.
void set_name (const char *name_item1)
Create a copy of the provided name.
void set_name (const char *name_item1, const char *name_item2)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5, const char *name_item6)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5, const char *name_item6, const char *name_item7)
Construct a name as a dot-conjoined string.
virtual const char * get_name (void) const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this frame.
virtual double timestamp (void) const
Return the update time of this frame.
virtual void set_owner (RefFrameOwner *new_owner)
Set the owner of this frame.
virtual RefFrameOwner * get_owner (void) const
Return the owner of this frame.
void set_active_status (bool value) override
Augment Subscription::set_active_status by telling the frame owner that the active/inactive state of this frame has changed.
const RefFrame * get_parent (void) const
Return the parent of this frame.
const RefFrame * get_root (void) const
Return the root of this frame's tree.
virtual void make_root (void)
Make this frame a root frame.
virtual void add_child (RefFrame &frame)
Add a child frame to this frame.
virtual void remove_from_parent (void)
Remove this node as a child of its parent node.
bool is_progeny_of (const RefFrame &frame) const
Return true if this frame is a progeny of the provided frame, false if not.
virtual void transplant_node (RefFrame &new_parent)
Move a node to a different place in the tree, keeping the state with respect to the root frame constant.
virtual void reset_parent (RefFrame &new_parent)
Reparent a node, without updating state.
virtual void compute_relative_state (const RefFrame &wrt_frame, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame (*this) with respect to the supplied wrt_frame reference frame.
virtual void compute_relative_state (const RefFrame &wrt_frame, bool reverse_sense, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame (*this) with respect to the supplied wrt_frame reference frame.
virtual void compute_state_wrt_pred (const RefFrame &wrt_frame, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_state_wrt_pred (unsigned int wrt_frame_index, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_pred_rel_state (const RefFrame &wrt_frame, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_pred_rel_state (unsigned int wrt_frame_index, RefFrameState &rel_state) const
Compute the complete state of the supplied reference frame wrt the invoking reference frame.
virtual void compute_position_from (const RefFrame &in_frame, double rel_pos[3]) const
Compute the relative position vector from the origin of the supplied reference frame to the origin of this reference frame, expressed in the coordinates of the supplied frame.
const RefFrame * find_last_common_node (const RefFrame &frame) const
Each reference frame has a path from the root of the reference frame tree to the frame in question.
Public Member Functions inherited from jeod::Subscription
Subscription ()
Subscription class default constructor.
Subscription (Mode)
Subscription class non-default constructor.
virtual ~Subscription ()
Subscription class destructor.
bool is_active (void) const
Return the value of the active data member.
unsigned int subscriptions (void) const
Return the value of the subscribers data member.
Mode get_subscription_mode (void) const
Return the value of the mode data member.
void activate (void)
Activate a Subscription object.
void deactivate (void)
Deactivate a Subscription object.
void subscribe (void)
Add a subscription to a Subscription object.
void unsubscribe (void)
Remove a subscription to a Subscription object.
Protected Member Functions
void set_active_status (bool new_status) override
Augment RefFrame::set_active_status by notifying the ephemerides manager that the tree might need to be rebuilt.
Protected Member Functions inherited from jeod::RefFrame
int find_last_common_index (const RefFrame &frame) const
Each reference frame has a path from the root of the reference frame tree to the frame in question.
Protected Member Functions inherited from jeod::Subscription
virtual void set_subscription_mode (Mode value)
Set the value of the mode data member.
Protected Attributes
BaseEphemeridesManager * ephem_manager
The ephemerides manager to which notifications of changes in ephemeris reference frame activity status are sent.
Protected Attributes inherited from jeod::RefFrame
std::string name
The identifier for this reference frame.
RefFrameOwner * owner
The object that "owns" this frame.
RefFrameLinks links
Specifies the parent/child/sibling linkages between frames.
double update_time
The time that the frame was lasted updated, dynamic time seconds.
Protected Attributes inherited from jeod::Subscription
Mode mode
The mode in which the object is operating.
unsigned int subscribers
Number of subscribers for this object.
bool active
Flag indicating whether the object is active.
Private Member Functions
EphemerisRefFrame (const EphemerisRefFrame &)
Not implemented.
EphemerisRefFrame & operator= (const EphemerisRefFrame &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EphemerisRefFrame ()
Additional Inherited Members
Public Types inherited from jeod::Subscription
enum Mode { Detect = 0, Subscribe = 1, Activate = 2, Freeform = 3 }
The Subscription::Mode enum specifies the mode in which a Subscription object is operating.
Data Fields inherited from jeod::RefFrame
RefFrameState state
The translational and rotational state of the reference frame with respect to its parent.
Detailed Description
An EphemerisRefFrame is a RefFrame whose state is set by an ephemeris model.
Ephemeris reference frames come in three basic flavors:
Planet-centered inertial frames. These are non-rotating frames whose origin is the center of mass of some planet (the Sun is a planet) and whose translational motion is (for now) assumed to be due to gravitation only. The orientation with respect to inertial is the identity transformation.
Barycenter inertial frames. These are non-rotating frames whose origin is the center of mass of two or more planets.
Planet-fixed frames. These are rotating frames whose origin is the center of mass of some planet (see ISSUE) and that rotate with the planet in question. The parent is always a planet-centered inertial frame with a zero translation offset between the planet-centered inertial and planet-fixed frames.
Only planet-centered inertial and barycenter inertial frames can serve as integration frames or as the root of the reference frame tree.
Definition at line 99 of file ephem_ref_frame.hh.
Constructor & Destructor Documentation
EphemerisRefFrame() [1/2]
jeod::EphemerisRefFrame::EphemerisRefFrame (void)
Construct an EphemerisRefFrame.
Definition at line 50 of file ephem_ref_frame.cc.
~EphemerisRefFrame()
jeod::EphemerisRefFrame::~EphemerisRefFrame (void) override
Destruct an EphemerisRefFrame.
Definition at line 60 of file ephem_ref_frame.cc.
EphemerisRefFrame() [2/2]
jeod::EphemerisRefFrame::EphemerisRefFrame (const EphemerisRefFrame &) private
Not implemented.
Member Function Documentation
operator=()
EphemerisRefFrame& jeod::EphemerisRefFrame::operator= (const EphemerisRefFrame &) private
Not implemented.
set_active_status()
void jeod::EphemerisRefFrame::set_active_status (bool new_status) override protected virtual
Augment RefFrame::set_active_status by notifying the ephemerides manager that the tree might need to be rebuilt.
Parameters
[in] new_status Active status
Reimplemented from jeod::Subscription.
Definition at line 83 of file ephem_ref_frame.cc.
References ephem_manager, jeod::BaseEphemeridesManager::ephem_note_tree_status_change(), jeod::MessageHandler::error(), jeod::EphemeridesMessages::inconsistent_setup, jeod::RefFrame::name, and jeod::RefFrame::set_active_status().
set_ephem_manager()
void jeod::EphemerisRefFrame::set_ephem_manager (BaseEphemeridesManager * manager) virtual
Set the EphemerisRefFrame's owner.
Parameters
[in,out] manager Ephemeris manager
Definition at line 70 of file ephem_ref_frame.cc.
References ephem_manager.
Referenced by jeod::EphemeridesManager::set_target_frame().
Friends And Related Function Documentation
init_attrjeod__EphemerisRefFrame
void init_attrjeod__EphemerisRefFrame () friend
InputProcessor
friend class InputProcessor friend
Definition at line 100 of file ephem_ref_frame.hh.
Field Documentation
ephem_manager
BaseEphemeridesManager* jeod::EphemerisRefFrame::ephem_manager protected
The ephemerides manager to which notifications of changes in ephemeris reference frame activity status are sent.
trick_units(–)
Definition at line 128 of file ephem_ref_frame.hh.
Referenced by set_active_status(), and set_ephem_manager().
The documentation for this class was generated from the following files:
ephem_ref_frame.hh
ephem_ref_frame.cc