JEOD: jeod::GaussJacksonIntegrationControls Class Reference
jeod::GaussJacksonIntegrationControls Class Reference
IntegrationControls specialized for Gauss-Jackson integration.
#include <gauss_jackson_integration_controls.hh>
Public Member Functions
GaussJacksonIntegrationControls ()
Default constructor.
GaussJacksonIntegrationControls (const er7_utils::IntegratorConstructor &priming_constructor, const GaussJacksonConfig &config_in)
Non-default constructor.
GaussJacksonIntegrationControls (const GaussJacksonIntegrationControls &src)
Copy constructor.
~GaussJacksonIntegrationControls () override
Destructor.
GaussJacksonIntegrationControls & operator= (GaussJacksonIntegrationControls src)
Copy and swap assignment operator.
er7_utils::IntegrationControls * create_copy () const override
Create a duplicate of this object.
er7_utils::IntegrationControls & get_priming_controls () const
Getter for the priming_controls data member.
const GaussJacksonCoeffs & get_coeff () const
Getter for the coeff data member.
const GaussJacksonConfig & get_config () const
Getter for the config data member.
const GaussJacksonStateMachine & get_state_machine () const
Getter for the state_machine data member.
void reset_integrator () override
Reset the integration controls object.
unsigned int integrate (double start_time, double sim_dt, er7_utils::TimeInterface &time_interface, er7_utils::IntegratorInterface &integ_interface, er7_utils::BaseIntegrationGroup &integ_group) override
Make one step in the process that eventually integrates state from the start_time to start_time+sim_dt.
Protected Member Functions
virtual void swap (GaussJacksonIntegrationControls &other)
Non-throwing swap function.
Private Member Functions
void start_cycle (double sim_dt)
Perform start of integration cycle actions.
void integrate_edit (er7_utils::TimeInterface &time_interface, er7_utils::BaseIntegrationGroup &integ_group)
Guide integration while in BootstrapEdit mode.
void integrate_gj (er7_utils::TimeInterface &time_interface, er7_utils::BaseIntegrationGroup &integ_group)
Guide integration while in BootstrapStep or Operational mode.
Private Attributes
er7_utils::IntegrationControls * priming_controls {}
The integration controls object used to prime the Gauss-Jackson integration process.
double cycle_starttime {}
The simulation time of the start of the current integration cycle.
double cycle_simdt {}
The simulation time span of the current integration cycle.
double cycle_dyndt {}
The dynamic time span corresponding to cycle_simdt.
double reset_time {}
The simulation time of the most recent reset.
GaussJacksonCoeffs coeff
The Gauss-Jackson corrector and predictor coefficients.
GaussJacksonConfig config
The Gauss-Jackson configuration data.
GaussJacksonStateMachine state_machine
The Gauss-Jackson state machine.
GaussJacksonStateMachine::FsmState fsm_state {GaussJacksonStateMachine::Reset}
The state machine's finite state.
unsigned int max_correction_iterations {}
Maximum number of correction iterations allowed.
unsigned int initial_order {}
The order of the Gauss Jackson integrator immediately after priming.
unsigned int order {}
The current order of the Gauss Jackson integrator.
unsigned int edit_count {}
Number of times that the current set of history have been edited.
bool at_end_of_tour {}
Flag indicating that the current integration cycle is the last one in an integration tour (i.e., that a major time step will be completed).
Friends
class InputProcessor
void init_attrjeod__GaussJacksonIntegrationControls ()
Detailed Description
IntegrationControls specialized for Gauss-Jackson integration.
Definition at line 87 of file gauss_jackson_integration_controls.hh.
Constructor & Destructor Documentation
GaussJacksonIntegrationControls() [1/3]
jeod::GaussJacksonIntegrationControls::GaussJacksonIntegrationControls ()
Default constructor.
Definition at line 40 of file gauss_jackson_integration_controls.cc.
GaussJacksonIntegrationControls() [2/3]
jeod::GaussJacksonIntegrationControls::GaussJacksonIntegrationControls (const er7_utils::IntegratorConstructor & priming_constructor, const GaussJacksonConfig & config_in)
Non-default constructor.
This is the constructor invoked by the GaussJacksonIntegratorConstructor.
Parameters
priming_constructor Integrator constructor for the technique used during priming.
config_in Gauss-Jackson configuration data.
Definition at line 46 of file gauss_jackson_integration_controls.cc.
References coeff, jeod::GaussJacksonCoeffs::compute_coeffs(), config, jeod::GaussJacksonCoeffs::configure(), jeod::GaussJacksonStateMachine::configure(), jeod::GaussJacksonConfig::final_order, initial_order, priming_controls, and state_machine.
GaussJacksonIntegrationControls() [3/3]
jeod::GaussJacksonIntegrationControls::GaussJacksonIntegrationControls (const GaussJacksonIntegrationControls & src)
Copy constructor.
Parameters
src Object to be copied.
Definition at line 62 of file gauss_jackson_integration_controls.cc.
References priming_controls.
~GaussJacksonIntegrationControls()
jeod::GaussJacksonIntegrationControls::~GaussJacksonIntegrationControls () override
Destructor.
Definition at line 85 of file gauss_jackson_integration_controls.cc.
References priming_controls.
Member Function Documentation
create_copy()
er7_utils::IntegrationControls * jeod::GaussJacksonIntegrationControls::create_copy () const override
Create a duplicate of this object.
Returns
Replicated GaussJacksonIntegrationControls.
Definition at line 90 of file gauss_jackson_integration_controls.cc.
get_coeff()
const GaussJacksonCoeffs& jeod::GaussJacksonIntegrationControls::get_coeff () const inline
Getter for the coeff data member.
Returns
Reference to the Gauss-Jackson coefficients object.
Definition at line 145 of file gauss_jackson_integration_controls.hh.
References coeff.
get_config()
const GaussJacksonConfig& jeod::GaussJacksonIntegrationControls::get_config () const inline
Getter for the config data member.
Returns
Reference to the Gauss-Jackson configuration object.
Definition at line 154 of file gauss_jackson_integration_controls.hh.
References config.
get_priming_controls()
er7_utils::IntegrationControls& jeod::GaussJacksonIntegrationControls::get_priming_controls () const inline
Getter for the priming_controls data member.
Returns
Reference to the integration controls used during priming.
Definition at line 136 of file gauss_jackson_integration_controls.hh.
References priming_controls.
Referenced by jeod::GaussJacksonIntegratorConstructor::create_first_order_ode_integrator(), jeod::GaussJacksonIntegratorConstructor::create_generalized_deriv_second_order_ode_integrator(), and jeod::GaussJacksonIntegratorConstructor::create_second_order_ode_integrator().
get_state_machine()
const GaussJacksonStateMachine& jeod::GaussJacksonIntegrationControls::get_state_machine () const inline
Getter for the state_machine data member.
Returns
Reference to the Gauss-Jackson state_machine object.
Definition at line 163 of file gauss_jackson_integration_controls.hh.
References state_machine.
integrate()
unsigned int jeod::GaussJacksonIntegrationControls::integrate (double start_time, double sim_dt, er7_utils::TimeInterface & time_interface, er7_utils::IntegratorInterface & integ_interface, er7_utils::BaseIntegrationGroup & integ_group) override
Make one step in the process that eventually integrates state from the start_time to start_time+sim_dt.
Returns
Step number; zero when finished.
Parameters
[in] start_time The simulation engine time at the start of the integration tour.
[in] sim_dt The difference between the simulation time at the end and start of the integration tour.
[in,out] time_interface Object external to the ER7 utilities suite that represents time.
[in,out] integ_interface Interface with the simulation engine for this integration controls.
[in,out] integ_group The integration group that contains this integration controls.
Definition at line 126 of file gauss_jackson_integration_controls.cc.
References at_end_of_tour, jeod::GaussJacksonStateMachine::BootstrapEdit, jeod::GaussJacksonStateMachine::BootstrapStep, jeod::Numerical::compare_exact(), cycle_dyndt, cycle_simdt, cycle_starttime, fsm_state, jeod::GaussJacksonStateMachine::get_cycle_scale(), integrate_edit(), integrate_gj(), jeod::GaussJacksonStateMachine::Operational, jeod::GaussJacksonStateMachine::Priming, priming_controls, jeod::GaussJacksonStateMachine::Reset, reset_integrator(), reset_time, start_cycle(), and state_machine.
integrate_edit()
void jeod::GaussJacksonIntegrationControls::integrate_edit (er7_utils::TimeInterface & time_interface, er7_utils::BaseIntegrationGroup & integ_group) private
Guide integration while in BootstrapEdit mode.
Definition at line 222 of file gauss_jackson_integration_controls.cc.
References jeod::Numerical::compare_exact(), cycle_dyndt, cycle_starttime, edit_count, jeod::GaussJacksonStateMachine::get_history_length(), max_correction_iterations, order, jeod::GaussJacksonStateMachine::set_bootstrap_edit_redo_needed(), and state_machine.
Referenced by integrate().
integrate_gj()
void jeod::GaussJacksonIntegrationControls::integrate_gj (er7_utils::TimeInterface & time_interface, er7_utils::BaseIntegrationGroup & integ_group) private
Guide integration while in BootstrapStep or Operational mode.
Definition at line 255 of file gauss_jackson_integration_controls.cc.
References jeod::Numerical::compare_exact(), cycle_dyndt, cycle_simdt, cycle_starttime, edit_count, and max_correction_iterations.
Referenced by integrate().
operator=()
GaussJacksonIntegrationControls& jeod::GaussJacksonIntegrationControls::operator= (GaussJacksonIntegrationControls src) inline
Copy and swap assignment operator.
Parameters
src Object to be copied.
Definition at line 120 of file gauss_jackson_integration_controls.hh.
References swap().
reset_integrator()
void jeod::GaussJacksonIntegrationControls::reset_integrator () override
Reset the integration controls object.
Definition at line 116 of file gauss_jackson_integration_controls.cc.
References at_end_of_tour, edit_count, fsm_state, initial_order, order, jeod::GaussJacksonStateMachine::Reset, jeod::GaussJacksonStateMachine::reset(), and state_machine.
Referenced by integrate().
start_cycle()
void jeod::GaussJacksonIntegrationControls::start_cycle (double sim_dt) private
Perform start of integration cycle actions.
Definition at line 288 of file gauss_jackson_integration_controls.cc.
References at_end_of_tour, jeod::GaussJacksonStateMachine::BootstrapEdit, coeff, jeod::GaussJacksonCoeffs::compute_coeffs(), cycle_dyndt, cycle_simdt, cycle_starttime, edit_count, fsm_state, jeod::GaussJacksonStateMachine::get_at_downsample(), jeod::GaussJacksonStateMachine::get_at_end_of_tour(), jeod::GaussJacksonStateMachine::get_at_order_change(), jeod::GaussJacksonStateMachine::get_at_reinitialize(), jeod::GaussJacksonStateMachine::get_current_order(), jeod::GaussJacksonStateMachine::get_cycle_scale(), jeod::GaussJacksonStateMachine::get_cycle_start_time(), jeod::GaussJacksonStateMachine::get_fsm_state(), order, jeod::GaussJacksonStateMachine::perform_step(), reset_time, and state_machine.
Referenced by integrate().
swap()
void jeod::GaussJacksonIntegrationControls::swap (GaussJacksonIntegrationControls & other) protected virtual
Non-throwing swap function.
Swap contents of 'this' with that of the other.
Parameters
[in] other Item with which contents are to be swapped.
Definition at line 96 of file gauss_jackson_integration_controls.cc.
References at_end_of_tour, coeff, config, cycle_dyndt, cycle_simdt, cycle_starttime, edit_count, fsm_state, initial_order, max_correction_iterations, order, priming_controls, reset_time, and state_machine.
Referenced by operator=().
Friends And Related Function Documentation
init_attrjeod__GaussJacksonIntegrationControls
void init_attrjeod__GaussJacksonIntegrationControls () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file gauss_jackson_integration_controls.hh.
Field Documentation
at_end_of_tour
bool jeod::GaussJacksonIntegrationControls::at_end_of_tour {} private
Flag indicating that the current integration cycle is the last one in an integration tour (i.e., that a major time step will be completed).
trick_units(–)
Definition at line 278 of file gauss_jackson_integration_controls.hh.
Referenced by integrate(), reset_integrator(), start_cycle(), and swap().
coeff
GaussJacksonCoeffs jeod::GaussJacksonIntegrationControls::coeff private
The Gauss-Jackson corrector and predictor coefficients.
trick_units(–)
Definition at line 237 of file gauss_jackson_integration_controls.hh.
Referenced by GaussJacksonIntegrationControls(), get_coeff(), start_cycle(), and swap().
config
GaussJacksonConfig jeod::GaussJacksonIntegrationControls::config private
The Gauss-Jackson configuration data.
trick_units(–)
Definition at line 242 of file gauss_jackson_integration_controls.hh.
Referenced by GaussJacksonIntegrationControls(), get_config(), and swap().
cycle_dyndt
double jeod::GaussJacksonIntegrationControls::cycle_dyndt {} private
The dynamic time span corresponding to cycle_simdt.
trick_units(s)
Definition at line 227 of file gauss_jackson_integration_controls.hh.
Referenced by integrate(), integrate_edit(), integrate_gj(), start_cycle(), and swap().
cycle_simdt
double jeod::GaussJacksonIntegrationControls::cycle_simdt {} private
The simulation time span of the current integration cycle.
trick_units(–)
Definition at line 222 of file gauss_jackson_integration_controls.hh.
Referenced by integrate(), integrate_gj(), start_cycle(), and swap().
cycle_starttime
double jeod::GaussJacksonIntegrationControls::cycle_starttime {} private
The simulation time of the start of the current integration cycle.
An integration cycle starts when cycle_stage is zero and ends when it reaches zero once again.trick_units(–)
Definition at line 217 of file gauss_jackson_integration_controls.hh.
Referenced by integrate(), integrate_edit(), integrate_gj(), start_cycle(), and swap().
edit_count
unsigned int jeod::GaussJacksonIntegrationControls::edit_count {} private
Number of times that the current set of history have been edited.
trick_units(–)
Definition at line 272 of file gauss_jackson_integration_controls.hh.
Referenced by integrate_edit(), integrate_gj(), reset_integrator(), start_cycle(), and swap().
fsm_state
GaussJacksonStateMachine::FsmState jeod::GaussJacksonIntegrationControls::fsm_state {GaussJacksonStateMachine::Reset} private
The state machine's finite state.
trick_units(–)
Definition at line 252 of file gauss_jackson_integration_controls.hh.
Referenced by integrate(), reset_integrator(), start_cycle(), and swap().
initial_order
unsigned int jeod::GaussJacksonIntegrationControls::initial_order {} private
The order of the Gauss Jackson integrator immediately after priming.
trick_units(–)
Definition at line 262 of file gauss_jackson_integration_controls.hh.
Referenced by GaussJacksonIntegrationControls(), reset_integrator(), and swap().
max_correction_iterations
unsigned int jeod::GaussJacksonIntegrationControls::max_correction_iterations {} private
Maximum number of correction iterations allowed.
trick_units(–)
Definition at line 257 of file gauss_jackson_integration_controls.hh.
Referenced by integrate_edit(), integrate_gj(), and swap().
order
unsigned int jeod::GaussJacksonIntegrationControls::order {} private
The current order of the Gauss Jackson integrator.
trick_units(–)
Definition at line 267 of file gauss_jackson_integration_controls.hh.
Referenced by integrate_edit(), reset_integrator(), start_cycle(), and swap().
priming_controls
er7_utils::IntegrationControls* jeod::GaussJacksonIntegrationControls::priming_controls {} private
The integration controls object used to prime the Gauss-Jackson integration process.
trick_units(–)
Definition at line 210 of file gauss_jackson_integration_controls.hh.
Referenced by GaussJacksonIntegrationControls(), get_priming_controls(), integrate(), swap(), and ~GaussJacksonIntegrationControls().
reset_time
double jeod::GaussJacksonIntegrationControls::reset_time {} private
The simulation time of the most recent reset.
trick_units(–)
Definition at line 232 of file gauss_jackson_integration_controls.hh.
Referenced by integrate(), start_cycle(), and swap().
state_machine
GaussJacksonStateMachine jeod::GaussJacksonIntegrationControls::state_machine private
The Gauss-Jackson state machine.
trick_units(–)
Definition at line 247 of file gauss_jackson_integration_controls.hh.
Referenced by GaussJacksonIntegrationControls(), get_state_machine(), integrate(), integrate_edit(), reset_integrator(), start_cycle(), and swap().
The documentation for this class was generated from the following files:
gauss_jackson_integration_controls.hh
gauss_jackson_integration_controls.cc