JEOD: jeod::AeroSurface Class Reference
jeod::AeroSurface Class Reference
The aerodynamic specific interaction surface, for use with the surface model.
#include <aero_surface.hh>
Public Member Functions
AeroSurface ()
Default Constructor.
~AeroSurface () override
Destructor.
AeroSurface & operator= (const AeroSurface &)=delete
AeroSurface (const AeroSurface &)=delete
void allocate_array (unsigned int size) override
Allocates an array of AeroFacet pointers, of the size indicated by the input variable.
void allocate_interaction_facet (Facet *facet, InteractionFacetFactory *factory, FacetParams *params, unsigned int index) override
Allocates a particular interaction facet, from an inputted general facet, using the inputted parameters and interaction facet factory.
Public Member Functions inherited from jeod::InteractionSurface
InteractionSurface ()=default
virtual ~InteractionSurface ()=default
InteractionSurface & operator= (const InteractionSurface &)=delete
InteractionSurface (const InteractionSurface &)=delete
virtual void accumulate_thermal_sources ()
Adds all thermal sources together.
virtual void thermal_integrator ()
Integrates thermal sources to get temperature.
Data Fields
AeroFacet ** aero_facets {}
An array of pointers to aerodynamic interaction facets.
unsigned int facets_size {}
Size of the aero_facets array.
Friends
class InputProcessor
void init_attrjeod__AeroSurface ()
Detailed Description
The aerodynamic specific interaction surface, for use with the surface model.
Definition at line 85 of file aero_surface.hh.
Constructor & Destructor Documentation
AeroSurface() [1/2]
jeod::AeroSurface::AeroSurface ()
Default Constructor.
Definition at line 53 of file aero_surface.cc.
References JEOD_REGISTER_CLASS, and JEOD_REGISTER_INCOMPLETE_CLASS.
~AeroSurface()
jeod::AeroSurface::~AeroSurface () override
Destructor.
Definition at line 63 of file aero_surface.cc.
References aero_facets, facets_size, and JEOD_DELETE_2D.
AeroSurface() [2/2]
jeod::AeroSurface::AeroSurface (const AeroSurface &) delete
Member Function Documentation
allocate_array()
void jeod::AeroSurface::allocate_array (unsigned int size) override virtual
Allocates an array of AeroFacet pointers, of the size indicated by the input variable.
Parameters
[in] size The size of the needed array
Units: cnt:
Implements jeod::InteractionSurface.
Definition at line 74 of file aero_surface.cc.
References aero_facets, facets_size, jeod::MessageHandler::fail(), jeod::AerodynamicsMessages::initialization_error, JEOD_ALLOC_CLASS_POINTER_ARRAY, and jeod::MessageHandler::warn().
allocate_interaction_facet()
void jeod::AeroSurface::allocate_interaction_facet (Facet * facet, InteractionFacetFactory * factory, FacetParams * params, unsigned int index) override virtual
Allocates a particular interaction facet, from an inputted general facet, using the inputted parameters and interaction facet factory.
This facet is then placed at the index given. If the correct InteractionFacetFactory and Facet Params are not given for the aerodynamic interaction or for the type of facet given, a fail message will be sent
Parameters
[in] facet The basic facet used to create the interaction facet
[in] factory The factory used to create the interaction facet
[in] params The aero params used to create the interaction facet
[in] index Where the new interaction facet will be placed in the aero_facets array
Units: cnt
Implements jeod::InteractionSurface.
Definition at line 123 of file aero_surface.cc.
References aero_facets, jeod::InteractionFacetFactory::create_facet(), facets_size, jeod::MessageHandler::fail(), jeod::AerodynamicsMessages::initialization_error, and JEOD_DELETE_OBJECT.
operator=()
AeroSurface& jeod::AeroSurface::operator= (const AeroSurface &) delete
Friends And Related Function Documentation
init_attrjeod__AeroSurface
void init_attrjeod__AeroSurface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file aero_surface.hh.
Field Documentation
aero_facets
AeroFacet** jeod::AeroSurface::aero_facets {}
An array of pointers to aerodynamic interaction facets.
AeroFacets is a pure virtual, so these will all be pointed to inheriting classes through polymorphismtrick_units(–)
Definition at line 98 of file aero_surface.hh.
Referenced by jeod::AerodynamicDrag::aero_drag(), allocate_array(), allocate_interaction_facet(), and ~AeroSurface().
facets_size
unsigned int jeod::AeroSurface::facets_size {}
Size of the aero_facets array.
trick_units(count)
Definition at line 103 of file aero_surface.hh.
Referenced by jeod::AerodynamicDrag::aero_drag(), allocate_array(), allocate_interaction_facet(), and ~AeroSurface().
The documentation for this class was generated from the following files:
aero_surface.hh
aero_surface.cc