JEOD: jeod::ThermalModelRider Class Reference
jeod::ThermalModelRider Class Reference
Defining the thermal functionality.
#include <thermal_model_rider.hh>
Public Member Functions
ThermalModelRider ()
Constructor.
virtual ~ThermalModelRider ()
Destructor.
void update (InteractionSurface *surface_ptr)
update the thermal aspects of all facets
Data Fields
bool active
Flag to allow thermal variation of facets.
bool include_internal_thermal_effects
Flag to include facet-to-facet conduction, and vehicle-to-facet thermal sources and sinks.
Private Member Functions
ThermalModelRider & operator= (const ThermalModelRider &rhs)
ThermalModelRider (const ThermalModelRider &rhs)
Friends
class InputProcessor
void init_attrjeod__ThermalModelRider ()
Detailed Description
Defining the thermal functionality.
Definition at line 84 of file thermal_model_rider.hh.
Constructor & Destructor Documentation
ThermalModelRider() [1/2]
jeod::ThermalModelRider::ThermalModelRider (void)
Constructor.
Definition at line 53 of file thermal_model_rider.cc.
References active, and include_internal_thermal_effects.
~ThermalModelRider()
jeod::ThermalModelRider::~ThermalModelRider (void) virtual
Destructor.
Definition at line 83 of file thermal_model_rider.cc.
ThermalModelRider() [2/2]
jeod::ThermalModelRider::ThermalModelRider (const ThermalModelRider & rhs) private
Member Function Documentation
operator=()
ThermalModelRider& jeod::ThermalModelRider::operator= (const ThermalModelRider & rhs) private
update()
void jeod::ThermalModelRider::update (InteractionSurface * surface_ptr)
update the thermal aspects of all facets
Parameters
[in] surface_ptr pointer the surface.
Definition at line 65 of file thermal_model_rider.cc.
References jeod::InteractionSurface::accumulate_thermal_sources(), active, jeod::ThermalFacetRider::cycle_time, include_internal_thermal_effects, and jeod::InteractionSurface::thermal_integrator().
Referenced by jeod::RadiationPressure::update_facet_surface().
Friends And Related Function Documentation
init_attrjeod__ThermalModelRider
void init_attrjeod__ThermalModelRider () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file thermal_model_rider.hh.
Field Documentation
active
bool jeod::ThermalModelRider::active
Flag to allow thermal variation of facets.
trick_units(–)
Definition at line 92 of file thermal_model_rider.hh.
Referenced by jeod::RadiationPressure::initialize(), ThermalModelRider(), update(), and jeod::RadiationPressure::update_facet_surface().
include_internal_thermal_effects
bool jeod::ThermalModelRider::include_internal_thermal_effects
Flag to include facet-to-facet conduction, and vehicle-to-facet thermal sources and sinks.
trick_units(–)
Definition at line 98 of file thermal_model_rider.hh.
Referenced by ThermalModelRider(), and update().
The documentation for this class was generated from the following files:
thermal_model_rider.hh
thermal_model_rider.cc