JEOD: jeod::OrbElemDerivedState Class Reference
jeod::OrbElemDerivedState Class Reference
The class used for deriving the orbital elements representation of a subject DynBody's position.
#include <orb_elem_derived_state.hh>
Public Member Functions
OrbElemDerivedState ()
Construct a OrbElemDerivedState object.
~OrbElemDerivedState () override
Destruct a OrbElemDerivedState object.
void set_use_alt_inertial (const bool use_alt_inertial_in)
Setter for use_alt_inertial.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a OrbElemDerivedState.
void update (void) override
Update the state.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
OrbitalElements elements
The orbital elements of the subject body with respect to the planet specified by the reference name.
Planet * planet
The planet, the name of which is specified by the inherited reference_name data member.
Data Fields inherited from jeod::DerivedState
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Member Functions
void compute_orbital_elements (const RefFrameTrans &rel_trans)
Compute the orbital elements for the current state.
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Protected Attributes
bool use_alt_inertial
Use inertial or alt_inertial flag.
EphemerisRefFrame * inertial_ptr
Pointer to planet inertial frame to be used, either inertial or alt_inertial.
RefFrameState rel_state
Relative state; only used when the vehicle integration from is not the planet-centered inertial frame.
Protected Attributes inherited from jeod::DerivedState
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
OrbElemDerivedState (const OrbElemDerivedState &)
OrbElemDerivedState & operator= (const OrbElemDerivedState &)
Friends
class InputProcessor
void init_attrjeod__OrbElemDerivedState ()
Detailed Description
The class used for deriving the orbital elements representation of a subject DynBody's position.
Definition at line 87 of file orb_elem_derived_state.hh.
Constructor & Destructor Documentation
OrbElemDerivedState() [1/2]
jeod::OrbElemDerivedState::OrbElemDerivedState (void)
Construct a OrbElemDerivedState object.
Definition at line 49 of file orb_elem_derived_state.cc.
~OrbElemDerivedState()
jeod::OrbElemDerivedState::~OrbElemDerivedState (void) override
Destruct a OrbElemDerivedState object.
Definition at line 63 of file orb_elem_derived_state.cc.
References inertial_ptr, and jeod::Subscription::unsubscribe().
OrbElemDerivedState() [2/2]
jeod::OrbElemDerivedState::OrbElemDerivedState (const OrbElemDerivedState &) private
Member Function Documentation
compute_orbital_elements()
void jeod::OrbElemDerivedState::compute_orbital_elements (const RefFrameTrans & rel_trans) protected
Compute the orbital elements for the current state.
Parameters
[in] rel_trans Planet relative state.
Definition at line 152 of file orb_elem_derived_state.cc.
References elements, jeod::OrbitalElements::from_cartesian(), jeod::BasePlanet::grav_source, jeod::GravitySource::mu, planet, jeod::RefFrameTrans::position, and jeod::RefFrameTrans::velocity.
Referenced by update().
initialize()
void jeod::OrbElemDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of a OrbElemDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DerivedState.
Definition at line 92 of file orb_elem_derived_state.cc.
References jeod::BasePlanet::alt_inertial, jeod::NamedItem::c_str(), elements, jeod::DerivedState::find_planet(), jeod::BasePlanet::inertial, inertial_ptr, jeod::DerivedState::initialize(), jeod::BasePlanet::name, jeod::DynBody::name, planet, jeod::DerivedState::reference_name, jeod::OrbitalElements::set_object_name(), jeod::OrbitalElements::set_planet_name(), jeod::Subscription::subscribe(), and use_alt_inertial.
operator=()
OrbElemDerivedState& jeod::OrbElemDerivedState::operator= (const OrbElemDerivedState &) private
set_use_alt_inertial()
void jeod::OrbElemDerivedState::set_use_alt_inertial (const bool use_alt_inertial_in)
Setter for use_alt_inertial.
Definition at line 76 of file orb_elem_derived_state.cc.
References use_alt_inertial.
update()
void jeod::OrbElemDerivedState::update (void) override virtual
Update the state.
Reimplemented from jeod::DerivedState.
Definition at line 126 of file orb_elem_derived_state.cc.
References jeod::DynBody::composite_body, compute_orbital_elements(), jeod::RefFrame::compute_relative_state(), jeod::RefFrame::get_parent(), inertial_ptr, rel_state, jeod::RefFrame::state, jeod::DerivedState::subject, jeod::RefFrameState::trans, and jeod::DerivedState::update().
Friends And Related Function Documentation
init_attrjeod__OrbElemDerivedState
void init_attrjeod__OrbElemDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file orb_elem_derived_state.hh.
Field Documentation
elements
OrbitalElements jeod::OrbElemDerivedState::elements
The orbital elements of the subject body with respect to the planet specified by the reference name.
trick_units(–)
Definition at line 100 of file orb_elem_derived_state.hh.
Referenced by compute_orbital_elements(), and initialize().
inertial_ptr
EphemerisRefFrame* jeod::OrbElemDerivedState::inertial_ptr protected
Pointer to planet inertial frame to be used, either inertial or alt_inertial.
Definition at line 119 of file orb_elem_derived_state.hh.
Referenced by initialize(), update(), and ~OrbElemDerivedState().
planet
Planet* jeod::OrbElemDerivedState::planet
The planet, the name of which is specified by the inherited reference_name data member.
trick_units(–)
Definition at line 106 of file orb_elem_derived_state.hh.
Referenced by compute_orbital_elements(), and initialize().
rel_state
RefFrameState jeod::OrbElemDerivedState::rel_state protected
Relative state; only used when the vehicle integration from is not the planet-centered inertial frame.
trick_units(–)
Definition at line 125 of file orb_elem_derived_state.hh.
Referenced by update().
use_alt_inertial
bool jeod::OrbElemDerivedState::use_alt_inertial protected
Use inertial or alt_inertial flag.
Definition at line 113 of file orb_elem_derived_state.hh.
Referenced by initialize(), and set_use_alt_inertial().
The documentation for this class was generated from the following files:
orb_elem_derived_state.hh
orb_elem_derived_state.cc