JEOD: jeod::TimeConverter_STD_UDE Class Reference
jeod::TimeConverter_STD_UDE Class Reference
Define class TimeConverter_STD_UDE, which converts from any specific example of the generic Standard Time to any specific example of the generic User-Defined-Epoch Time.
#include <time_converter_std_ude.hh>
Public Member Functions
TimeConverter_STD_UDE ()
Construct a TimeConverter_STD_UDE.
~TimeConverter_STD_UDE () override
Destroy a TimeConverter_STD_UDE.
void reset_a_to_b_offset (void) override
Resets the value of a_to_b_offset.
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void convert_a_to_b (void) override
Convert from TimeSTD to TimeUDE.
void convert_b_to_a (void) override
Convert from TimeUDE to TimeSTD.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()
Destroy a TimeConverter.
virtual bool is_initialized (void)
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void verify_table_lookup_ends (void)
This function does absolutely nothing.
double get_a_to_b_offset (void)
Return the offset from the parent time object to this object.
Private Member Functions
TimeConverter_STD_UDE (const TimeConverter_STD_UDE &)
TimeConverter_STD_UDE & operator= (const TimeConverter_STD_UDE &)
Private Attributes
bool failed_null_test
Initializing converter could be done in one of two ways.
TimeStandard * std_ptr
Converter parent time, always a TimeSTD for this converter.
TimeUDE * ude_ptr
Converter parent time, always a TimeUDE for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_STD_UDE ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name
name of time-type "a".
std::string b_name
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()
Construct a TimeConverter.
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized
whether converter has been initialized.
double a_to_b_offset
Difference between the two time-types.
Direction valid_directions
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Define class TimeConverter_STD_UDE, which converts from any specific example of the generic Standard Time to any specific example of the generic User-Defined-Epoch Time.
Definition at line 91 of file time_converter_std_ude.hh.
Constructor & Destructor Documentation
TimeConverter_STD_UDE() [1/2]
jeod::TimeConverter_STD_UDE::TimeConverter_STD_UDE (void)
Construct a TimeConverter_STD_UDE.
Definition at line 58 of file time_converter_std_ude.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::ANY_DIRECTION, jeod::TimeConverter::b_name, failed_null_test, std_ptr, ude_ptr, and jeod::TimeConverter::valid_directions.
~TimeConverter_STD_UDE()
jeod::TimeConverter_STD_UDE::~TimeConverter_STD_UDE (void) override
Destroy a TimeConverter_STD_UDE.
Definition at line 194 of file time_converter_std_ude.cc.
TimeConverter_STD_UDE() [2/2]
jeod::TimeConverter_STD_UDE::TimeConverter_STD_UDE (const TimeConverter_STD_UDE &) private
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_STD_UDE::convert_a_to_b (void) override virtual
Convert from TimeSTD to TimeUDE.
Assumptions and Limitations
Time class UDE is based on time class STD, and counts the elapsed STD time only
Reimplemented from jeod::TimeConverter.
Definition at line 151 of file time_converter_std_ude.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::JeodBaseTime::seconds, jeod::TimeUDE::set_time_by_seconds(), std_ptr, and ude_ptr.
convert_b_to_a()
void jeod::TimeConverter_STD_UDE::convert_b_to_a (void) override virtual
Convert from TimeUDE to TimeSTD.
Assumptions and Limitations
Time class UDE is based on time class STD, and counts the elapsed STD time only
Reimplemented from jeod::TimeConverter.
Definition at line 168 of file time_converter_std_ude.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::JeodBaseTime::seconds, jeod::TimeStandard::set_time_by_seconds(), std_ptr, and ude_ptr.
initialize()
void jeod::TimeConverter_STD_UDE::initialize (JeodBaseTime * parent_ptr, JeodBaseTime * child_ptr, const int int_dir) override virtual
Initialize the converter.
Assumptions and Limitations
This class converts from TimeDyn to TimeUDE only
Parameters
[in] parent_ptr Time used to initialize the converter
[in] child_ptr Other Time used to initialize the converter
[in] int_dir Conversion direction: +1 a=parent; -1 b=parent; 0 error
Implements jeod::TimeConverter.
Definition at line 80 of file time_converter_std_ude.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::NamedItem::c_str(), jeod::MessageHandler::fail(), failed_null_test, jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, jeod::JeodBaseTime::seconds, std_ptr, ude_ptr, jeod::TimeConverter::verify_setup(), and jeod::MessageHandler::warn().
operator=()
TimeConverter_STD_UDE& jeod::TimeConverter_STD_UDE::operator= (const TimeConverter_STD_UDE &) private
reset_a_to_b_offset()
void jeod::TimeConverter_STD_UDE::reset_a_to_b_offset (void) override virtual
Resets the value of a_to_b_offset.
Reimplemented from jeod::TimeConverter.
Definition at line 181 of file time_converter_std_ude.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::JeodBaseTime::seconds, std_ptr, and ude_ptr.
Friends And Related Function Documentation
init_attrjeod__TimeConverter_STD_UDE
void init_attrjeod__TimeConverter_STD_UDE () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file time_converter_std_ude.hh.
Field Documentation
failed_null_test
bool jeod::TimeConverter_STD_UDE::failed_null_test private
Initializing converter could be done in one of two ways.
If it fails the first time, this flag is set. If it fails a second time, it terminates.trick_units(–)
Definition at line 101 of file time_converter_std_ude.hh.
Referenced by initialize(), and TimeConverter_STD_UDE().
std_ptr
TimeStandard* jeod::TimeConverter_STD_UDE::std_ptr private
Converter parent time, always a TimeSTD for this converter.
trick_units(–)
Definition at line 105 of file time_converter_std_ude.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), initialize(), reset_a_to_b_offset(), and TimeConverter_STD_UDE().
ude_ptr
TimeUDE* jeod::TimeConverter_STD_UDE::ude_ptr private
Converter parent time, always a TimeUDE for this converter.
trick_units(–)
Definition at line 110 of file time_converter_std_ude.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), initialize(), reset_a_to_b_offset(), and TimeConverter_STD_UDE().
The documentation for this class was generated from the following files:
time_converter_std_ude.hh
time_converter_std_ude.cc