JEOD: jeod::SinglePointEphemeris Class Reference
jeod::SinglePointEphemeris Class Reference abstract
A SinglePointEphemeris has one ephemeris point.
#include <simple_ephemerides.hh>
Public Member Functions
SinglePointEphemeris (void)
Construct a SinglePointEphemeris object.
~SinglePointEphemeris (void) override
Destruct a SinglePointEphemeris object.
virtual void set_name (const char *new_name)
Set the name of a SinglePointEphemeris object.
void activate (void) override
Nominally, activate the model.
void deactivate (void) override
Deactivate the model.
double timestamp (void) const override
Retrieve the timestamp.
const char * get_name (void) const override
Retrieve the identifier.
void ephem_update (void) override
Update the ephemerides, which in this case is a no-op.
virtual void initialize_model (EphemeridesManager &manager)=0
Register the model and its ephemeris points.
void ephem_initialize (EphemeridesManager &manager) override=0
Initialize the ephemerides.
void ephem_activate (EphemeridesManager &manager) override=0
Activate the model.
void ephem_build_tree (EphemeridesManager &manager) override=0
Build the model's contribution to the reference frame tree.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
Protected Attributes
char * identifier
Identifier for this model.
double update_time
Time of last update, dynamic time seconds.
bool active
Is the model active?
Private Member Functions
SinglePointEphemeris (const SinglePointEphemeris &)
Not implemented.
SinglePointEphemeris & operator= (const SinglePointEphemeris &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__SinglePointEphemeris ()
Detailed Description
A SinglePointEphemeris has one ephemeris point.
Definition at line 85 of file simple_ephemerides.hh.
Constructor & Destructor Documentation
SinglePointEphemeris() [1/2]
jeod::SinglePointEphemeris::SinglePointEphemeris (void)
Construct a SinglePointEphemeris object.
Definition at line 63 of file simple_ephemerides.cc.
~SinglePointEphemeris()
jeod::SinglePointEphemeris::~SinglePointEphemeris (void) override
Destruct a SinglePointEphemeris object.
Definition at line 77 of file simple_ephemerides.cc.
References identifier, JEOD_DELETE_ARRAY, and JEOD_IS_ALLOCATED.
SinglePointEphemeris() [2/2]
jeod::SinglePointEphemeris::SinglePointEphemeris (const SinglePointEphemeris &) private
Not implemented.
Member Function Documentation
activate()
void jeod::SinglePointEphemeris::activate (void) override virtual
Nominally, activate the model.
Here, reject the request.
Implements jeod::ActivateInterface.
Definition at line 90 of file simple_ephemerides.cc.
References active, jeod::MessageHandler::error(), and jeod::EphemeridesMessages::internal_error.
deactivate()
void jeod::SinglePointEphemeris::deactivate (void) override virtual
Deactivate the model.
Implements jeod::ActivateInterface.
Definition at line 105 of file simple_ephemerides.cc.
References active.
Referenced by jeod::EmptySpaceEphemeris::ephem_initialize(), and jeod::SinglePlanetEphemeris::ephem_initialize().
ephem_activate()
void jeod::SinglePointEphemeris::ephem_activate (EphemeridesManager & manager) override pure virtual
Activate the model.
Parameters
[in,out] manager Ephemerides manager
Implements jeod::EphemerisInterface.
Implemented in jeod::SinglePlanetEphemeris, and jeod::EmptySpaceEphemeris.
ephem_build_tree()
void jeod::SinglePointEphemeris::ephem_build_tree (EphemeridesManager & manager) override pure virtual
Build the model's contribution to the reference frame tree.
Parameters
[in,out] manager Ephemerides manager
Implements jeod::EphemerisInterface.
Implemented in jeod::SinglePlanetEphemeris, and jeod::EmptySpaceEphemeris.
ephem_initialize()
void jeod::SinglePointEphemeris::ephem_initialize (EphemeridesManager & manager) override pure virtual
Initialize the ephemerides.
Parameters
[in,out] manager Ephemerides manager
Implements jeod::EphemerisInterface.
Implemented in jeod::SinglePlanetEphemeris, and jeod::EmptySpaceEphemeris.
ephem_update()
void jeod::SinglePointEphemeris::ephem_update (void) inline override virtual
Update the ephemerides, which in this case is a no-op.
Implements jeod::EphemerisInterface.
Definition at line 331 of file simple_ephemerides.hh.
get_name()
const char * jeod::SinglePointEphemeris::get_name (void) const inline override virtual
Retrieve the identifier.
Returns
Identifier
Implements jeod::EphemerisInterface.
Definition at line 319 of file simple_ephemerides.hh.
References identifier.
initialize_model()
virtual void jeod::SinglePointEphemeris::initialize_model (EphemeridesManager & manager) pure virtual
Register the model and its ephemeris points.
Parameters
[in,out] manager Ephemerides manager
Implemented in jeod::SinglePlanetEphemeris, and jeod::EmptySpaceEphemeris.
Referenced by jeod::DynManager::initialize_model_internal().
operator=()
SinglePointEphemeris& jeod::SinglePointEphemeris::operator= (const SinglePointEphemeris &) private
Not implemented.
set_name()
void jeod::SinglePointEphemeris::set_name (const char * new_name) virtual
Set the name of a SinglePointEphemeris object.
Parameters
[in,out] new_name Central point name
Reimplemented in jeod::SinglePlanetEphemeris, and jeod::EmptySpaceEphemeris.
Definition at line 118 of file simple_ephemerides.cc.
References jeod::MessageHandler::error(), identifier, jeod::EphemeridesMessages::inconsistent_setup, and JEOD_STRDUP.
Referenced by jeod::DynManager::initialize_model_internal(), jeod::EmptySpaceEphemeris::set_name(), and jeod::SinglePlanetEphemeris::set_name().
timestamp()
double jeod::SinglePointEphemeris::timestamp (void) const inline override virtual
Retrieve the timestamp.
Returns
Timestamp
Units: s
Implements jeod::EphemerisInterface.
Definition at line 306 of file simple_ephemerides.hh.
References update_time.
Friends And Related Function Documentation
init_attrjeod__SinglePointEphemeris
void init_attrjeod__SinglePointEphemeris () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file simple_ephemerides.hh.
Field Documentation
active
bool jeod::SinglePointEphemeris::active protected
Is the model active?
trick_units(–)
Definition at line 187 of file simple_ephemerides.hh.
Referenced by activate(), deactivate(), jeod::EmptySpaceEphemeris::ephem_build_tree(), jeod::SinglePlanetEphemeris::ephem_build_tree(), jeod::SinglePlanetEphemeris::ephem_initialize(), jeod::EmptySpaceEphemeris::initialize_model(), and jeod::SinglePlanetEphemeris::initialize_model().
identifier
char* jeod::SinglePointEphemeris::identifier protected
Identifier for this model.
trick_units(–)
Definition at line 177 of file simple_ephemerides.hh.
Referenced by jeod::EmptySpaceEphemeris::ephem_initialize(), jeod::SinglePlanetEphemeris::ephem_initialize(), get_name(), set_name(), and ~SinglePointEphemeris().
update_time
double jeod::SinglePointEphemeris::update_time protected
Time of last update, dynamic time seconds.
trick_units(s)
Definition at line 182 of file simple_ephemerides.hh.
Referenced by timestamp().
The documentation for this class was generated from the following files:
simple_ephemerides.hh
simple_ephemerides.cc