JEOD: jeod::Subscription Class Reference
jeod::Subscription Class Reference
A Subscription object provides two approaches of marking something as being active or inactive: The activate and deactivate methods versus the subscribe and unsubscribe methods.
#include <subscription.hh>
Public Types
enum Mode { Detect = 0, Subscribe = 1, Activate = 2, Freeform = 3 }
The Subscription::Mode enum specifies the mode in which a Subscription object is operating.
Public Member Functions
Subscription ()
Subscription class default constructor.
Subscription (Mode)
Subscription class non-default constructor.
virtual ~Subscription ()
Subscription class destructor.
bool is_active (void) const
Return the value of the active data member.
unsigned int subscriptions (void) const
Return the value of the subscribers data member.
Mode get_subscription_mode (void) const
Return the value of the mode data member.
void activate (void)
Activate a Subscription object.
void deactivate (void)
Deactivate a Subscription object.
void subscribe (void)
Add a subscription to a Subscription object.
void unsubscribe (void)
Remove a subscription to a Subscription object.
Protected Member Functions
virtual void set_subscription_mode (Mode value)
Set the value of the mode data member.
virtual void set_active_status (bool value)
Set the active data member to the provided value.
Protected Attributes
Mode mode
The mode in which the object is operating.
unsigned int subscribers
Number of subscribers for this object.
bool active
Flag indicating whether the object is active.
Friends
class InputProcessor
void init_attrjeod__Subscription ()
Detailed Description
A Subscription object provides two approaches of marking something as being active or inactive: The activate and deactivate methods versus the subscribe and unsubscribe methods.
The class also provides a mean for selecting only one of these two approaches as valid.
This class uses the non-virtual interface design pattern. Derived classes should not override the non-virtual public interfaces. They should instead override the private set_active_state method.
Definition at line 155 of file subscription.hh.
Member Enumeration Documentation
Mode
enum jeod::Subscription::Mode
The Subscription::Mode enum specifies the mode in which a Subscription object is operating.
Enumerator
Detect
First scheme used wins.
Subscribe
Activation is via subscribe/unsubscribe only.
Activate
Activation is via activate/deactivate only.
Freeform
Users can use either scheme; conflicts may arise.
Definition at line 166 of file subscription.hh.
Constructor & Destructor Documentation
Subscription() [1/2]
jeod::Subscription::Subscription (void) inline
Subscription class default constructor.
Definition at line 263 of file subscription.hh.
Subscription() [2/2]
jeod::Subscription::Subscription (Mode init_mode) inline explicit
Subscription class non-default constructor.
Parameters
[in] init_mode Initial mode
Definition at line 279 of file subscription.hh.
~Subscription()
jeod::Subscription::~Subscription (void) inline virtual
Subscription class destructor.
There are no resources to destruct.
Definition at line 294 of file subscription.hh.
Member Function Documentation
activate()
void jeod::Subscription::activate (void)
Activate a Subscription object.
Assumptions and Limitations
Activation is valid for this object.
Definition at line 39 of file subscription.cc.
References Activate, active, Detect, jeod::MessageHandler::error(), mode, set_active_status(), Subscribe, and jeod::RefFrameMessages::subscription_error.
deactivate()
void jeod::Subscription::deactivate (void)
Deactivate a Subscription object.
Assumptions and Limitations
Activation is valid for this object.
Definition at line 69 of file subscription.cc.
References Activate, active, Detect, jeod::MessageHandler::error(), mode, set_active_status(), Subscribe, and jeod::RefFrameMessages::subscription_error.
get_subscription_mode()
Subscription::Mode jeod::Subscription::get_subscription_mode (void) const inline
Return the value of the mode data member.
Returns
Operating mode.
Definition at line 345 of file subscription.hh.
References mode.
is_active()
bool jeod::Subscription::is_active (void) const inline
Return the value of the active data member.
Returns
Is the object active?
Definition at line 306 of file subscription.hh.
References active.
Referenced by jeod::RefFrameManager::check_ref_frame_ownership(), jeod::EphemerisOrientation::note_frame_status_change(), jeod::EphemerisPoint::note_frame_status_change(), and jeod::EphemerisItem::set_target_frame().
set_active_status()
void jeod::Subscription::set_active_status (bool value) protected virtual
Set the active data member to the provided value.
Parameters
[in] value New active value
Reimplemented in jeod::RefFrame, and jeod::EphemerisRefFrame.
Definition at line 169 of file subscription.cc.
References active.
Referenced by activate(), deactivate(), jeod::RefFrame::set_active_status(), subscribe(), and unsubscribe().
set_subscription_mode()
void jeod::Subscription::set_subscription_mode (Mode value) inline protected virtual
Set the value of the mode data member.
Parameters
[in] value Subscription mode
Definition at line 333 of file subscription.hh.
References mode.
Referenced by jeod::RefFrame::RefFrame().
subscribe()
void jeod::Subscription::subscribe (void)
Add a subscription to a Subscription object.
Assumptions and Limitations
Subscription is valid for this object.
Definition at line 99 of file subscription.cc.
References Activate, active, Detect, jeod::MessageHandler::error(), mode, set_active_status(), Subscribe, subscribers, and jeod::RefFrameMessages::subscription_error.
Referenced by jeod::PropagatedPlanet::ephem_initialize(), jeod::LvlhFrame::initialize(), jeod::PlanetaryDerivedState::initialize(), jeod::OrbElemDerivedState::initialize(), jeod::EulerDerivedState::initialize(), jeod::NedDerivedState::initialize(), jeod::SolarBetaDerivedState::initialize(), jeod::RelativeDerivedState::initialize(), jeod::DynBody::initialize_model(), jeod::EphemerisOrientation::note_frame_status_change(), jeod::RelativeDerivedState::set_activation_flag(), and jeod::RefFrameManager::subscribe_to_frame().
subscriptions()
unsigned int jeod::Subscription::subscriptions (void) const inline
Return the value of the subscribers data member.
Returns
Number of subscriptions.
Definition at line 320 of file subscription.hh.
References subscribers.
Referenced by jeod::RefFrameManager::frame_is_subscribed(), jeod::RefFrameManager::unsubscribe_to_frame(), and jeod::RelativeDerivedState::~RelativeDerivedState().
unsubscribe()
void jeod::Subscription::unsubscribe (void)
Remove a subscription to a Subscription object.
Assumptions and Limitations
Subscription is valid for this object.
Definition at line 131 of file subscription.cc.
References Activate, active, Detect, jeod::MessageHandler::error(), mode, set_active_status(), Subscribe, subscribers, and jeod::RefFrameMessages::subscription_error.
Referenced by jeod::EphemerisOrientation::note_frame_status_change(), jeod::RelativeDerivedState::set_activation_flag(), jeod::RefFrameManager::unsubscribe_to_frame(), jeod::EulerDerivedState::~EulerDerivedState(), jeod::LvlhFrame::~LvlhFrame(), jeod::NedDerivedState::~NedDerivedState(), jeod::OrbElemDerivedState::~OrbElemDerivedState(), jeod::PlanetaryDerivedState::~PlanetaryDerivedState(), jeod::RelativeDerivedState::~RelativeDerivedState(), and jeod::SolarBetaDerivedState::~SolarBetaDerivedState().
Friends And Related Function Documentation
init_attrjeod__Subscription
void init_attrjeod__Subscription () friend
InputProcessor
friend class InputProcessor friend
Definition at line 157 of file subscription.hh.
Field Documentation
active
bool jeod::Subscription::active protected
Flag indicating whether the object is active.
trick_units(–)
Definition at line 254 of file subscription.hh.
Referenced by activate(), deactivate(), is_active(), set_active_status(), subscribe(), and unsubscribe().
mode
Mode jeod::Subscription::mode protected
The mode in which the object is operating.
trick_units(–)
Definition at line 244 of file subscription.hh.
Referenced by activate(), deactivate(), get_subscription_mode(), set_subscription_mode(), subscribe(), and unsubscribe().
subscribers
unsigned int jeod::Subscription::subscribers protected
Number of subscribers for this object.
trick_units(–)
Definition at line 249 of file subscription.hh.
Referenced by subscribe(), subscriptions(), and unsubscribe().
The documentation for this class was generated from the following files:
subscription.hh
subscription.cc