JEOD: jeod::PropagatedEphemerisPlanet Class Reference
jeod::PropagatedEphemerisPlanet Class Reference
A PropagatedEphemerisPlanet is an EphemerisPoint whose state is coupled with the translational state of a DynBody reference frame.
#include <propagated_planet.hh>
Public Member Functions
PropagatedEphemerisPlanet (DynBody &dyn_body, BodyRefFrame &frame)
PropagatedEphemerisPlanet non-default constructor.
~PropagatedEphemerisPlanet () override=default
PropagatedEphemerisPlanet (const PropagatedEphemerisPlanet &)=delete
PropagatedEphemerisPlanet & operator= (const PropagatedEphemerisPlanet &)=delete
virtual void update (double time)
Copy rotational state from/to the body reference frame.
virtual void update (const double *pos, const double *vel, double time)
Update the inertial frame's translational state.
Public Member Functions inherited from jeod::EphemerisPoint
EphemerisPoint ()=default
~EphemerisPoint () override=default
EphemerisPoint (const EphemerisPoint &)=delete
EphemerisPoint & operator= (const EphemerisPoint &)=delete
TargetAspect updates_what () const override
Specify the aspect of the target frame updated by the object.
std::string default_suffix () const override
Return the default suffix for this item class, i.e., "inertial".
void disconnect_from_tree () override
Disconnect the associated inertial frame from the tree.
void note_frame_status_change (RefFrame *frame) override
Set active status to correspond with that of the inertial frame.
virtual void initialize_state ()
Zero-out the inertial frame's translational state.
virtual void update (const double *pos, const double *vel, double time)
Update the inertial frame's translational state.
virtual void update_scaled (const double *pos, const double *vel, double scale, double time)
Update the inertial frame's translational state.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()=default
~EphemerisItem () override=default
EphemerisItem (const EphemerisItem &)=delete
EphemerisItem & operator= (const EphemerisItem &)=delete
virtual void set_name (const std::string &new_name)
Name an ephemeris item.
virtual void set_name (const std::string &pname, const std::string &fname)
Name an ephemeris item.
std::string get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp () const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void enable ()
Enable an EphemerisItem object.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item () const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const std::string &new_value, const std::string &old_value, const std::string &variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
Protected Attributes
DynBody & body
The dynamic body whose state is tied to that of the planet.
BodyRefFrame & body_ref_frame
The body reference frame whose translational state is coupled with that of the planet's inertial frame.
Protected Attributes inherited from jeod::EphemerisItem
std::string name
The name of the item.
EphemerisInterface * owner {}
The ephemeris model that owns this object.
BaseEphemeridesManager * manager {}
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame {}
The reference frame whose non-constant state is set by this object.
EphemerisItem * head {}
The first ephemeris item with the same name as this item.
EphemerisItem * next {}
The next ephemeris item with the same name as this item.
double update_time {}
Time of last update, dynamic time seconds.
bool enabled {}
Is the item enabled?
bool active {}
Is the item active?
Friends
class InputProcessor
void init_attrjeod__PropagatedEphemerisPlanet ()
Additional Inherited Members
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (const std::string &new_name)
Name an ephemeris item.
Detailed Description
A PropagatedEphemerisPlanet is an EphemerisPoint whose state is coupled with the translational state of a DynBody reference frame.
This class is intended for use by the PropagatedPlanet class. Use outside of the PropagatedPlanet is not sanctioned.
The inherited enabled flag takes on an additional meaning in this derived class. The base class meaning of this flag is that the ephemeris item, or the ephemeris model that owns the item, is responsible for maintaining the translational state of the target frame when the item is enabled but not when the item is disabled.
For this class, when the enabled flag is set still means that the item is responsible for maintaining the translational state of the target ephemeris reference frame. The dynamic body serves as the source of this state. When the enabled flag is clear, some other model is assumed to be responsible for maintaining the target frame state. The target frame state serves as the source of the dynamic body's state when the enabled flag is clear. A PropagatedEphemerisPlanet is an EphemerisPoint whose state is coupled with the translational state of a DynBody reference frame.
This class is intended for use by the PropagatedPlanet class. Use outside of the PropagatedPlanet is not sanctioned.
The class acts analogously to the class PropagatedEphemerisOrientation, but for translation rather than rotation. See PropagatedEphemerisOrientation for a description of the behavior of the class.
Definition at line 117 of file propagated_planet.hh.
Constructor & Destructor Documentation
PropagatedEphemerisPlanet() [1/2]
jeod::PropagatedEphemerisPlanet::PropagatedEphemerisPlanet (DynBody & dyn_body, BodyRefFrame & frame)
PropagatedEphemerisPlanet non-default constructor.
Parameters
[in,out] dyn_body The DynBody that represents the planet
[in,out] frame The body reference frame
Definition at line 155 of file propagated_planet.cc.
~PropagatedEphemerisPlanet()
jeod::PropagatedEphemerisPlanet::~PropagatedEphemerisPlanet () override default
PropagatedEphemerisPlanet() [2/2]
jeod::PropagatedEphemerisPlanet::PropagatedEphemerisPlanet (const PropagatedEphemerisPlanet &) delete
Member Function Documentation
operator=()
PropagatedEphemerisPlanet& jeod::PropagatedEphemerisPlanet::operator= (const PropagatedEphemerisPlanet &) delete
update() [1/2]
void jeod::EphemerisPoint::update
Update the inertial frame's translational state.
Parameters
[in] position Position wrt parent
Units: M
[in] velocity Velocity wrt parent
Units: M/s
[in] time Timestamp
Units: s
Definition at line 122 of file ephem_point.cc.
update() [2/2]
void jeod::PropagatedEphemerisPlanet::update (double dyn_time) virtual
Copy rotational state from/to the body reference frame.
Parameters
[in] dyn_time Dynamic time seconds
Units: s
Definition at line 80 of file propagated_planet.cc.
References body, body_ref_frame, jeod::RefFrame::compute_relative_state(), jeod::EphemerisItem::enabled, jeod::RefFrame::get_parent(), jeod::RefFrameItems::Pos_Vel, jeod::DynBody::set_state(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::EphemerisItem::target_frame, jeod::RefFrameState::trans, and jeod::EphemerisItem::update_time.
Referenced by jeod::PropagatedPlanet::ephem_update().
Friends And Related Function Documentation
init_attrjeod__PropagatedEphemerisPlanet
void init_attrjeod__PropagatedEphemerisPlanet () friend
InputProcessor
friend class InputProcessor friend
Definition at line 119 of file propagated_planet.hh.
Field Documentation
body
DynBody& jeod::PropagatedEphemerisPlanet::body protected
The dynamic body whose state is tied to that of the planet.
trick_units(–)
Definition at line 135 of file propagated_planet.hh.
Referenced by update().
body_ref_frame
BodyRefFrame& jeod::PropagatedEphemerisPlanet::body_ref_frame protected
The body reference frame whose translational state is coupled with that of the planet's inertial frame.
trick_units(–)
Definition at line 141 of file propagated_planet.hh.
Referenced by update().
The documentation for this class was generated from the following files:
propagated_planet.hh
propagated_planet.cc