JEOD: jeod::JeodContainer< ContainerType, ElemType > Class Template Reference
jeod::JeodContainer< ContainerType, ElemType > Class Template Reference abstract
A JeodContainer is a JEOD STL sequence container replacement whose contents are checkpointable and restorable.
#include <container.hh>
Public Types
typedef JeodContainer< ContainerType, ElemType > this_container_type
This particular JeodContainer type.
typedef ContainerType::stl_container_type stl_container_type
Import the ContainerType's container type.
Public Member Functions
JeodContainer (void)
Default constructor.
JeodContainer (const this_container_type &source)
Copy constructor.
JeodContainer (const stl_container_type &source)
Copy constructor.
JeodContainer & operator= (const this_container_type &source)
Assignment operator.
JeodContainer & operator= (const stl_container_type &source)
Assignment operator.
~JeodContainer (void) override
Destructor.
void swap_contents (this_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
void swap_contents (stl_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
virtual void perform_insert_action (const std::string &value)=0
Push a value onto the end of the contents.
virtual void perform_cleanup_action (const std::string &value)
Cleanup detritus created during the restore process.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
void start_checkpoint (void) override
Prepare to checkpoint the object.
void advance_checkpoint (void) override
Advance to the next item to be checkpointed.
bool is_checkpoint_finished (void) override
Indicate whether the checkpoint dump of this object is finished.
const std::string get_init_name (void) override
Names the action to be performed prior to performing any of the restore actions.
const std::string get_item_name (void) override
Return the name of the action to be printed along with the current value.
const std::string get_final_name (void) override
Names the action to be performed after to performing any of the restore actions.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
virtual const std::string get_item_value (void)=0
Return the value of the item to be written to the checkpoint file.
Protected Attributes
ContainerType::iterator checkpoint_iter
Iterator for walking through the container during checkpoint.
const JeodMemoryTypeDescriptor * elem_type_descriptor
Memory model descriptor of the type of data stored in the container.
Friends
class InputProcessor
void init_attrjeod__JeodContainer ()
Detailed Description
template<typename ContainerType, typename ElemType>
class jeod::JeodContainer< ContainerType, ElemType >
A JeodContainer is a JEOD STL sequence container replacement whose contents are checkpointable and restorable.
Definition at line 82 of file container.hh.
Member Typedef Documentation
stl_container_type
template<typename ContainerType, typename ElemType> typedef ContainerType::stl_container_type jeod::JeodContainer< ContainerType, ElemType >::stl_container_type
Import the ContainerType's container type.
Definition at line 101 of file container.hh.
this_container_type
template<typename ContainerType, typename ElemType> typedef JeodContainer<ContainerType, ElemType> jeod::JeodContainer< ContainerType, ElemType >::this_container_type
This particular JeodContainer type.
Definition at line 95 of file container.hh.
Constructor & Destructor Documentation
JeodContainer() [1/3]
template<typename ContainerType, typename ElemType> jeod::JeodContainer< ContainerType, ElemType >::JeodContainer (void) inline
Default constructor.
Definition at line 109 of file container.hh.
JeodContainer() [2/3]
template<typename ContainerType, typename ElemType> jeod::JeodContainer< ContainerType, ElemType >::JeodContainer (const this_container_type & source) inline
Copy constructor.
Note
This copies the source's ContainerType contents only. The Checkpointable contents and the added checkpoint members are not copied.
Parameters
source Container to be copied.
Definition at line 125 of file container.hh.
JeodContainer() [3/3]
template<typename ContainerType, typename ElemType> jeod::JeodContainer< ContainerType, ElemType >::JeodContainer (const stl_container_type & source) inline
Copy constructor.
Note
This copies the source's ContainerType contents only. The Checkpointable contents and the added checkpoint members are not copied.
Parameters
source Container to be copied.
Definition at line 141 of file container.hh.
~JeodContainer()
template<typename ContainerType, typename ElemType> jeod::JeodContainer< ContainerType, ElemType >::~JeodContainer (void) inline override
Destructor.
Definition at line 182 of file container.hh.
Member Function Documentation
advance_checkpoint()
template<typename ContainerType, typename ElemType> void jeod::JeodContainer< ContainerType, ElemType >::advance_checkpoint (void) inline override virtual
Advance to the next item to be checkpointed.
In the case of a JeodContainer, this method simply advances the checkpoint iterator to point to the next item in the contents.
Implements jeod::JeodCheckpointable.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 267 of file container.hh.
Referenced by jeod::JeodObjectContainer< ContainerType, ElemType >::advance_checkpoint().
get_final_name()
template<typename ContainerType, typename ElemType> const std::string jeod::JeodContainer< ContainerType, ElemType >::get_final_name (void) inline override virtual
Names the action to be performed after to performing any of the restore actions.
In the case of a JeodContainer, the init name is always "cleanup".
Reimplemented from jeod::JeodCheckpointable.
Definition at line 310 of file container.hh.
get_init_name()
template<typename ContainerType, typename ElemType> const std::string jeod::JeodContainer< ContainerType, ElemType >::get_init_name (void) inline override virtual
Names the action to be performed prior to performing any of the restore actions.
In the case of a JeodContainer, the init name is always "clear".
Implements jeod::JeodCheckpointable.
Definition at line 289 of file container.hh.
get_item_name()
template<typename ContainerType, typename ElemType> const std::string jeod::JeodContainer< ContainerType, ElemType >::get_item_name (void) inline override virtual
Return the name of the action to be printed along with the current value.
In the case of a JeodContainer, the action name is always "insert".
Implements jeod::JeodCheckpointable.
Definition at line 299 of file container.hh.
initialize_checkpointable()
template<typename ContainerType, typename ElemType> void jeod::JeodContainer< ContainerType, ElemType >::initialize_checkpointable (const void * container, const std::type_info & container_type, const std::string & elem_name) inline override virtual
Initialize a checkpointable object, called by the checkpoint manager.
In the case of a JeodContainer, this method gets the descriptor for the type of data stored in the container.
Reimplemented from jeod::JeodCheckpointable.
Definition at line 237 of file container.hh.
Referenced by jeod::JeodPointerContainer< ContainerType, ElemType >::initialize_checkpointable().
is_checkpoint_finished()
template<typename ContainerType, typename ElemType> bool jeod::JeodContainer< ContainerType, ElemType >::is_checkpoint_finished (void) inline override virtual
Indicate whether the checkpoint dump of this object is finished.
In the case of a JeodContainer, the dump is finished when the internal checkpoint iterator points beyond the last item in the contents.
Implements jeod::JeodCheckpointable.
Definition at line 278 of file container.hh.
operator=() [1/2]
template<typename ContainerType, typename ElemType> JeodContainer& jeod::JeodContainer< ContainerType, ElemType >::operator= (const this_container_type & source) inline
Assignment operator.
Note
This copies the source's ContainerType contents only. The Checkpointable contents and the added checkpoint members are not copied.
Parameters
source Container to be copied.
Definition at line 157 of file container.hh.
Referenced by jeod::JeodPrimitiveContainer< ContainerType, ElemType >::operator=(), jeod::JeodPointerContainer< ContainerType, ElemType >::operator=(), and jeod::JeodObjectContainer< ContainerType, ElemType >::operator=().
operator=() [2/2]
template<typename ContainerType, typename ElemType> JeodContainer& jeod::JeodContainer< ContainerType, ElemType >::operator= (const stl_container_type & source) inline
Assignment operator.
Note
This copies the source's ContainerType contents only. The Checkpointable contents and the added checkpoint members are not copied.
Parameters
source Container to be copied.
Definition at line 173 of file container.hh.
perform_cleanup_action()
template<typename ContainerType, typename ElemType> virtual void jeod::JeodContainer< ContainerType, ElemType >::perform_cleanup_action (const std::string & value) inline virtual
Cleanup detritus created during the restore process.
The default action is to do nothing.
Parameters
value String name of cleanup target. This member should be protected or (even better) private. It is marked as public to avoid problems with Trick and SWIG.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 226 of file container.hh.
Referenced by jeod::JeodContainer< ContainerType, ElemType *>::perform_restore_action().
perform_insert_action()
template<typename ContainerType, typename ElemType> virtual void jeod::JeodContainer< ContainerType, ElemType >::perform_insert_action (const std::string & value) pure virtual
Push a value onto the end of the contents.
This method is pure virtual because the value provided to the method is a string. Translating the input string to the appropriate element type is the responsibility of template instantiations.
Parameters
value Value, in string form, to be added to the contents.
Note
This member should be protected or (even better) private. It is marked as public to avoid problems with Trick and SWIG.
Implemented in jeod::JeodObjectContainer< ContainerType, ElemType >, jeod::JPVCollectTorque, jeod::JeodPointerContainer< ContainerType, ElemType >, jeod::JPVCollectForce, and jeod::JeodPrimitiveContainer< ContainerType, ElemType >.
Referenced by jeod::JeodContainer< ContainerType, ElemType *>::perform_restore_action().
perform_restore_action()
template<typename ContainerType, typename ElemType> int jeod::JeodContainer< ContainerType, ElemType >::perform_restore_action (const std::string & action_name, const std::string & action_value) inline override virtual
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
In the case of a JeodContainer, the actions are "clear", "insert", and "cleanup". The checkpoint writer automatically creates an initial "clear" entry as the first entry in the checkpoint file for a JeodCheckpointable object and a "cleanup" entry as the final entry. An "insert" entry is created for each element in the container's contents.
Implements jeod::JeodCheckpointable.
Definition at line 326 of file container.hh.
start_checkpoint()
template<typename ContainerType, typename ElemType> void jeod::JeodContainer< ContainerType, ElemType >::start_checkpoint (void) inline override virtual
Prepare to checkpoint the object.
In the case of a JeodContainer, this method initializes a checkpoint iterator, data member checkpoint_iter, to the start of the contents.
Implements jeod::JeodCheckpointable.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 255 of file container.hh.
Referenced by jeod::JeodObjectContainer< ContainerType, ElemType >::start_checkpoint().
swap_contents() [1/2]
template<typename ContainerType, typename ElemType> void jeod::JeodContainer< ContainerType, ElemType >::swap_contents (this_container_type & other) inline
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
Definition at line 189 of file container.hh.
swap_contents() [2/2]
template<typename ContainerType, typename ElemType> void jeod::JeodContainer< ContainerType, ElemType >::swap_contents (stl_container_type & other) inline
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
Definition at line 199 of file container.hh.
Friends And Related Function Documentation
init_attrjeod__JeodContainer
template<typename ContainerType, typename ElemType> void init_attrjeod__JeodContainer () friend
InputProcessor
template<typename ContainerType, typename ElemType> friend class InputProcessor friend
Definition at line 85 of file container.hh.
Field Documentation
checkpoint_iter
template<typename ContainerType, typename ElemType> ContainerType::iterator jeod::JeodContainer< ContainerType, ElemType >::checkpoint_iter protected
Iterator for walking through the container during checkpoint.
trick_io(**)
Definition at line 364 of file container.hh.
Referenced by jeod::JeodContainer< ContainerType, ElemType *>::advance_checkpoint(), jeod::JeodPrimitiveContainer< ContainerType, ElemType >::get_item_value(), jeod::JeodContainer< ContainerType, ElemType *>::is_checkpoint_finished(), and jeod::JeodContainer< ContainerType, ElemType *>::start_checkpoint().
elem_type_descriptor
template<typename ContainerType, typename ElemType> const JeodMemoryTypeDescriptor* jeod::JeodContainer< ContainerType, ElemType >::elem_type_descriptor protected
Memory model descriptor of the type of data stored in the container.
trick_io(**)
Definition at line 369 of file container.hh.
Referenced by jeod::JeodObjectContainer< ContainerType, ElemType >::get_final_value(), jeod::JeodObjectContainer< ContainerType, ElemType >::get_item_value(), and jeod::JeodContainer< ContainerType, ElemType *>::initialize_checkpointable().
The documentation for this class was generated from the following file:
container.hh