JEOD: jeod::NorthEastDown Class Reference
jeod::NorthEastDown Class Reference
Defines a local North-East-Down reference frame.
#include <north_east_down.hh>
Public Types
enum AltLatLongType { undefined = -1, spherical, elliptical }
Specifies whether the latitude is spherical or elliptical.
Public Member Functions
NorthEastDown ()
NorthEastDown constructor.
~NorthEastDown () override
NorthEastDown destructor.
void update_from_cart (double const cart[3]) override
Update from Cartesian position input.
void update_from_spher (const AltLatLongState &spher) override
Update from Spherical position input.
void update_from_ellip (const AltLatLongState &ellip) override
Update from Elliptical position input.
virtual void build_ned_orientation ()
Build NED frame state based on current reference point information.
virtual void set_ned_trans_states (const double pos[3], const double vel[3])
Build NED frame state based on current reference point information.
Public Member Functions inherited from jeod::PlanetFixedPosition
PlanetFixedPosition ()
Construct a PlanetFixedPosition object.
virtual ~PlanetFixedPosition ()
Destructor.
virtual void initialize (Planet *planet_in)
Initialize a PlanetFixedPosition object.
virtual void update_from_cart (const double cart[3])
Update from Cartesian position input.
Data Fields
RefFrame ned_frame
The local North-East-Down reference frame, centered at the reference point stored in the ellip_coords, sphere_coords, and cart_coords data fields inherited from PlanetFixedPosition.
AltLatLongType altlatlong_type
Is reference point specified in spherical or elliptical coords?
Data Fields inherited from jeod::PlanetFixedPosition
AltLatLongState ellip_coords
An object's current position in elliptical coordinates.
AltLatLongState sphere_coords
The same object's current position in spherical coordinates.
double cart_coords [3]
The planet-centered, planet-fixed position of the object.
Planet * planet
The planet currently associated with this.
Private Member Functions
NorthEastDown (const NorthEastDown &rhs)
NorthEastDown & operator= (const NorthEastDown &)
Friends
class InputProcessor
void init_attrjeod__NorthEastDown ()
Additional Inherited Members
Static Public Attributes inherited from jeod::PlanetFixedPosition
static const double Small_radius_limit = 1e-60
Limit of ratio of radial distance to planet equatorial radius below which planetary coordinates are deemed to be invalid.
Protected Member Functions inherited from jeod::PlanetFixedPosition
void cart_to_spher ()
Convert from cartesian to spherical position.
void cart_to_ellip ()
Convert from cartesian to elliptical position.
void spher_to_cart ()
Convert from spherical to cartesian position.
void ellip_to_cart ()
Convert from elliptical to cartesian position.
int get_elliptic_parameters (double r, double z, double &f, double &h, int maxIters=10)
Detailed Description
Defines a local North-East-Down reference frame.
Definition at line 81 of file north_east_down.hh.
Member Enumeration Documentation
AltLatLongType
enum jeod::NorthEastDown::AltLatLongType
Specifies whether the latitude is spherical or elliptical.
Enumerator
undefined
spherical
elliptical
Definition at line 100 of file north_east_down.hh.
Constructor & Destructor Documentation
NorthEastDown() [1/2]
jeod::NorthEastDown::NorthEastDown (void)
NorthEastDown constructor.
Definition at line 50 of file north_east_down.cc.
References altlatlong_type, and undefined.
~NorthEastDown()
jeod::NorthEastDown::~NorthEastDown (void) override
NorthEastDown destructor.
Definition at line 60 of file north_east_down.cc.
NorthEastDown() [2/2]
jeod::NorthEastDown::NorthEastDown (const NorthEastDown & rhs) private
Member Function Documentation
build_ned_orientation()
void jeod::NorthEastDown::build_ned_orientation (void) virtual
Build NED frame state based on current reference point information.
Definition at line 115 of file north_east_down.cc.
References altlatlong_type, jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_quaternion(), jeod::PlanetFixedPosition::ellip_coords, elliptical, jeod::MessageHandler::fail(), jeod::Vector3::initialize(), jeod::PlanetFixedMessages::invalid_request, jeod::AltLatLongState::latitude, jeod::AltLatLongState::longitude, ned_frame, jeod::RefFrameState::rot, jeod::PlanetFixedPosition::sphere_coords, spherical, jeod::RefFrame::state, and jeod::RefFrameRot::T_parent_this.
Referenced by jeod::DynBodyInitNedState::apply(), and jeod::NedDerivedState::compute_ned_frame().
operator=()
NorthEastDown& jeod::NorthEastDown::operator= (const NorthEastDown &) private
set_ned_trans_states()
void jeod::NorthEastDown::set_ned_trans_states (const double pos[3], const double vel[3]) virtual
Build NED frame state based on current reference point information.
Parameters
[in] pos Cartesian position, PCPF
Units: M
[in] vel Cartesian velocity, PCPF
Units: M/s
Definition at line 168 of file north_east_down.cc.
References jeod::Vector3::copy(), ned_frame, jeod::RefFrameTrans::position, jeod::RefFrame::state, jeod::RefFrameState::trans, jeod::PlanetFixedPosition::update_from_cart(), and jeod::RefFrameTrans::velocity.
Referenced by jeod::DynBodyInitNedState::apply(), and jeod::NedDerivedState::compute_ned_frame().
update_from_cart()
void jeod::NorthEastDown::update_from_cart (double const cart[3]) override
Update from Cartesian position input.
Parameters
[in] cart Cartesian coords, PCPF
Units: M
Definition at line 71 of file north_east_down.cc.
References jeod::PlanetFixedPosition::cart_coords, jeod::Vector3::copy(), ned_frame, jeod::RefFrameTrans::position, jeod::RefFrame::state, jeod::RefFrameState::trans, and jeod::PlanetFixedPosition::update_from_cart().
update_from_ellip()
void jeod::NorthEastDown::update_from_ellip (const AltLatLongState & ellip) override virtual
Update from Elliptical position input.
Parameters
[in] ellip Elliptical AltLatLong position
Reimplemented from jeod::PlanetFixedPosition.
Definition at line 101 of file north_east_down.cc.
References jeod::PlanetFixedPosition::cart_coords, jeod::Vector3::copy(), ned_frame, jeod::RefFrameTrans::position, jeod::RefFrame::state, jeod::RefFrameState::trans, and jeod::PlanetFixedPosition::update_from_ellip().
Referenced by jeod::DynBodyInitNedState::apply().
update_from_spher()
void jeod::NorthEastDown::update_from_spher (const AltLatLongState & spher) override virtual
Update from Spherical position input.
Parameters
[in] spher Spherical AltLatLong position
Reimplemented from jeod::PlanetFixedPosition.
Definition at line 86 of file north_east_down.cc.
References jeod::PlanetFixedPosition::cart_coords, jeod::Vector3::copy(), ned_frame, jeod::RefFrameTrans::position, jeod::RefFrame::state, jeod::RefFrameState::trans, and jeod::PlanetFixedPosition::update_from_spher().
Referenced by jeod::DynBodyInitNedState::apply().
Friends And Related Function Documentation
init_attrjeod__NorthEastDown
void init_attrjeod__NorthEastDown () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file north_east_down.hh.
Field Documentation
altlatlong_type
AltLatLongType jeod::NorthEastDown::altlatlong_type
Is reference point specified in spherical or elliptical coords?
trick_units(–)
Definition at line 117 of file north_east_down.hh.
Referenced by jeod::DynBodyInitNedState::apply(), build_ned_orientation(), and NorthEastDown().
ned_frame
RefFrame jeod::NorthEastDown::ned_frame
The local North-East-Down reference frame, centered at the reference point stored in the ellip_coords, sphere_coords, and cart_coords data fields inherited from PlanetFixedPosition.
trick_units(–)
Definition at line 94 of file north_east_down.hh.
Referenced by jeod::DynBodyInitNedState::apply(), build_ned_orientation(), jeod::NedDerivedState::initialize(), set_ned_trans_states(), jeod::NedDerivedState::update(), update_from_cart(), update_from_ellip(), update_from_spher(), and jeod::NedDerivedState::~NedDerivedState().
The documentation for this class was generated from the following files:
north_east_down.hh
north_east_down.cc