JEOD: jeod::DefaultAero Class Reference
jeod::DefaultAero Class Reference
The simple, default, aerodynamic drag model, including coefficient of drag, ballistic coefficient, etc.
#include <default_aero.hh>
Public Types
enum DragOption { DRAG_OPT_CD = 0, DRAG_OPT_BC = 1, DRAG_OPT_CONST = 2 }
Specifies how drag is to be computed.
Public Member Functions
DefaultAero ()=default
virtual ~DefaultAero ()=default
DefaultAero & operator= (const DefaultAero &)=delete
DefaultAero (const DefaultAero &)=delete
virtual void aerodrag_force (const double velocity_mag, const double rel_vel_hat[3], AeroDragParameters *aero_drag_param_ptr, double mass, double force[3], double torque[3])
The implementation for this aerodynamic drags force and torque calculations.
Data Fields
double Cd {}
Coefficient of drag.
double BC {}
Ballistic Coefficient.
double area {}
Vehicle aerodynamic area.
double drag {}
Drag calculated during use.
DragOption option {DRAG_OPT_CONST}
The type of simple drag to use.
Friends
class InputProcessor
void init_attrjeod__DefaultAero ()
Detailed Description
The simple, default, aerodynamic drag model, including coefficient of drag, ballistic coefficient, etc.
This can be overriden with a user defined model in the AerodynamicDrag class.
Definition at line 86 of file default_aero.hh.
Member Enumeration Documentation
DragOption
enum jeod::DefaultAero::DragOption
Specifies how drag is to be computed.
Enumerator
DRAG_OPT_CD
Use Coefficient of drag for drag computations.
DRAG_OPT_BC
Use Ballistic Coefficient for drag computations.
DRAG_OPT_CONST
Use specified constant drag.
Definition at line 92 of file default_aero.hh.
Constructor & Destructor Documentation
DefaultAero() [1/2]
jeod::DefaultAero::DefaultAero () default
~DefaultAero()
virtual jeod::DefaultAero::~DefaultAero () virtual default
DefaultAero() [2/2]
jeod::DefaultAero::DefaultAero (const DefaultAero &) delete
Member Function Documentation
aerodrag_force()
void jeod::DefaultAero::aerodrag_force (const double velocity_mag, const double rel_vel_hat[3], AeroDragParameters * aero_drag_param_ptr, double mass, double force[3], double torque[3]) virtual
The implementation for this aerodynamic drags force and torque calculations.
Can be overriden by an inheriting class to create extensibility
Parameters
[in] velocity_mag The magnitude of the relative velocity of the vehicle; not used here but some child classes need it
Units: M/s
[in] rel_vel_hat The unit vector of the relative velocity of the vehicle, in the structural frame
[in] aero_drag_param_ptr The aerodynamic drag parameters used to calculate drag
[in] mass The current mass of the vehicle
Units: kg
[out] force The aerodynamic force, in the structural frame
Units: N
[out] torque The aerodynamic torque, in the structural frame
Units: N*M
Definition at line 59 of file default_aero.cc.
References area, BC, Cd, drag, DRAG_OPT_BC, DRAG_OPT_CD, DRAG_OPT_CONST, jeod::AeroDragParameters::dynamic_pressure, jeod::MessageHandler::fail(), jeod::Vector3::initialize(), option, jeod::AerodynamicsMessages::runtime_error, jeod::AerodynamicsMessages::runtime_warns, jeod::Vector3::scale(), and jeod::MessageHandler::warn().
Referenced by jeod::AerodynamicDrag::aero_drag().
operator=()
DefaultAero& jeod::DefaultAero::operator= (const DefaultAero &) delete
Friends And Related Function Documentation
init_attrjeod__DefaultAero
void init_attrjeod__DefaultAero () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file default_aero.hh.
Field Documentation
area
double jeod::DefaultAero::area {}
Vehicle aerodynamic area.
trick_units(m2)
Definition at line 124 of file default_aero.hh.
Referenced by aerodrag_force().
BC
double jeod::DefaultAero::BC {}
Ballistic Coefficient.
trick_units(kg/m2)
Definition at line 120 of file default_aero.hh.
Referenced by aerodrag_force().
Cd
double jeod::DefaultAero::Cd {}
Coefficient of drag.
trick_units(–)
Definition at line 116 of file default_aero.hh.
Referenced by aerodrag_force().
drag
double jeod::DefaultAero::drag {}
Drag calculated during use.
Can be set by user and will then never be changed with a DRAG_OPT_CONSTtrick_units(N)
Definition at line 130 of file default_aero.hh.
Referenced by aerodrag_force().
option
DragOption jeod::DefaultAero::option {DRAG_OPT_CONST}
The type of simple drag to use.
trick_units(–)
Definition at line 135 of file default_aero.hh.
Referenced by aerodrag_force().
The documentation for this class was generated from the following files:
default_aero.hh
default_aero.cc