JEOD: jeod::EphemerisPoint Class Reference
jeod::EphemerisPoint Class Reference
An EphemerisPoint object updates the translational state of an ephemeris reference frame.
#include <ephem_point.hh>
Public Member Functions
EphemerisPoint ()
Construct an ephemeris point.
~EphemerisPoint () override
Destroy an ephemeris point.
TargetAspect updates_what (void) const override
Specify the aspect of the target frame updated by the object.
const char * default_suffix () const override
Return the default suffix for this item class, i.e., "inertial".
void disconnect_from_tree () override
Disconnect the associated inertial frame from the tree.
void note_frame_status_change (RefFrame *frame) override
Set active status to correspond with that of the inertial frame.
virtual void initialize_state ()
Zero-out the inertial frame's translational state.
virtual void update (const double *pos, const double *vel, double time)
Update the inertial frame's translational state.
virtual void update_scaled (const double *pos, const double *vel, double scale, double time)
Update the inertial frame's translational state.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()
Construct an ephemeris item.
~EphemerisItem () override
Destroy an ephemeris item.
virtual void set_name (const char *new_name)
Name an ephemeris item.
virtual void set_name (const char *pname, const char *fname)
Name an ephemeris item.
const char * get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp (void) const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void enable ()
Enable an EphemerisItem object.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item (void) const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const char *new_value, const char *old_value, const char *variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
Private Member Functions
EphemerisPoint (const EphemerisPoint &)
Not implemented.
EphemerisPoint & operator= (const EphemerisPoint &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EphemerisPoint ()
Additional Inherited Members
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (char *new_name)
Name an ephemeris item.
Protected Attributes inherited from jeod::EphemerisItem
char * name
The name of the item.
EphemerisInterface * owner
The ephemeris model that owns this object.
BaseEphemeridesManager * manager
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame
The reference frame whose non-constant state is set by this object.
EphemerisItem * head
The first ephemeris item with the same name as this item.
EphemerisItem * next
The next ephemeris item with the same name as this item.
double update_time
Time of last update, dynamic time seconds.
bool enabled
Is the item enabled?
bool active
Is the item active?
Detailed Description
An EphemerisPoint object updates the translational state of an ephemeris reference frame.
Definition at line 86 of file ephem_point.hh.
Constructor & Destructor Documentation
EphemerisPoint() [1/2]
jeod::EphemerisPoint::EphemerisPoint (void)
Construct an ephemeris point.
Definition at line 59 of file ephem_point.cc.
~EphemerisPoint()
jeod::EphemerisPoint::~EphemerisPoint (void) override
Destroy an ephemeris point.
Definition at line 71 of file ephem_point.cc.
EphemerisPoint() [2/2]
jeod::EphemerisPoint::EphemerisPoint (const EphemerisPoint &) private
Not implemented.
Member Function Documentation
default_suffix()
const char * jeod::EphemerisPoint::default_suffix (void) const override virtual
Return the default suffix for this item class, i.e., "inertial".
Returns
Default suffix
Implements jeod::EphemerisItem.
Definition at line 110 of file ephem_point.cc.
disconnect_from_tree()
void jeod::EphemerisPoint::disconnect_from_tree (void) override virtual
Disconnect the associated inertial frame from the tree.
Implements jeod::EphemerisItem.
Definition at line 122 of file ephem_point.cc.
References jeod::EphemerisItem::active, jeod::RefFrame::remove_from_parent(), and jeod::EphemerisItem::target_frame.
initialize_state()
void jeod::EphemerisPoint::initialize_state (void) inline virtual
Zero-out the inertial frame's translational state.
Definition at line 137 of file ephem_point.cc.
References jeod::Vector3::initialize(), jeod::RefFrameTrans::position, jeod::RefFrame::state, jeod::EphemerisItem::target_frame, jeod::RefFrameState::trans, and jeod::RefFrameTrans::velocity.
Referenced by jeod::SpiceEphemeris::determine_root_node().
note_frame_status_change()
void jeod::EphemerisPoint::note_frame_status_change (RefFrame * frame) override virtual
Set active status to correspond with that of the inertial frame.
Parameters
[in] frame Frame whose status has changed
Reimplemented from jeod::RefFrameOwner.
Definition at line 83 of file ephem_point.cc.
References jeod::EphemerisItem::activate(), jeod::EphemerisItem::deactivate(), jeod::MessageHandler::error(), jeod::EphemeridesMessages::internal_error, jeod::Subscription::is_active(), and jeod::EphemerisItem::target_frame.
operator=()
EphemerisPoint& jeod::EphemerisPoint::operator= (const EphemerisPoint &) private
Not implemented.
update()
void jeod::EphemerisPoint::update (const double * position, const double * velocity, double time) virtual
Update the inertial frame's translational state.
Parameters
[in] position Position wrt parent
Units: M
[in] velocity Velocity wrt parent
Units: M/s
[in] time Timestamp
Units: s
Definition at line 154 of file ephem_point.cc.
References jeod::Vector3::copy(), jeod::RefFrameTrans::position, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::EphemerisItem::target_frame, jeod::RefFrameState::trans, jeod::EphemerisItem::update_time, and jeod::RefFrameTrans::velocity.
Referenced by jeod::De4xxEphemeris::ephem_update(), and jeod::SpiceEphemeris::update_trans().
update_scaled()
void jeod::EphemerisPoint::update_scaled (const double * position, const double * velocity, double scale, double time) virtual
Update the inertial frame's translational state.
Parameters
[in] position Position wrt parent
Units: M
[in] velocity Velocity wrt parent
Units: M/s
[in] scale Scale factor
[in] time Timestamp
Units: s
Definition at line 176 of file ephem_point.cc.
References jeod::RefFrameTrans::position, jeod::Vector3::scale(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::EphemerisItem::target_frame, jeod::RefFrameState::trans, jeod::EphemerisItem::update_time, and jeod::RefFrameTrans::velocity.
Referenced by jeod::De4xxEphemeris::ephem_update().
updates_what()
EphemerisItem::TargetAspect jeod::EphemerisPoint::updates_what (void) const override virtual
Specify the aspect of the target frame updated by the object.
EphemerisPoint objects update the translational state.
Returns
Target of object
Implements jeod::EphemerisItem.
Definition at line 197 of file ephem_point.cc.
References jeod::EphemerisItem::Translation.
Friends And Related Function Documentation
init_attrjeod__EphemerisPoint
void init_attrjeod__EphemerisPoint () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file ephem_point.hh.
The documentation for this class was generated from the following files:
ephem_point.hh
ephem_point.cc