JEOD: jeod::SectionedOutputStream Class Reference
jeod::SectionedOutputStream Class Reference
A SectionedOutputStream is a std::ostream that writes a section of a checkpoint file.
#include <checkpoint_output_manager.hh>
Public Member Functions
SectionedOutputStream ()
Construct a SectionedOutputStream object.
SectionedOutputStream (const SectionedOutputStream &)
Construct a SectionedOutputStream object by copying from another.
~SectionedOutputStream () override
Destruct a SectionedOutputStream object.
SectionedOutputStream & operator= (const SectionedOutputStream &)=delete
bool is_activatable () const
Determine if the stream is able to be activated.
bool activate ()
Activate the object.
void deactivate ()
Deactivate the object.
bool operator! () const
Conversion to boolean.
operator void * () const
Conversion to void*.
Private Member Functions
SectionedOutputStream (CheckPointOutputManager *mngr, std::ofstream &ofstream, const std::string &start_marker, const std::string &end_marker, const std::string &section_name)
Construct a SectionedOutputStream object that is connected to a file stream and to a CheckPointOutputManager.
Private Attributes
SectionedOutputBuffer sectbuf
The std::streambuf that does the writing to the file.
CheckPointOutputManager * manager {}
The input manager that created this object.
std::ofstream * stream {}
The C++ file stream that writes to the checkpoint file.
const std::string * section_start {}
The string that indicates the start of a checkpoint file section.
const std::string * section_end {}
The string that indicates the start of a checkpoint file section.
const std::string tag {""}
The name of the checkpoint file section.
bool is_copy {}
Is this a copy of some other SectionedOutputStream? Copies of copies are verboten.
bool is_active {}
Is this an active object? In the end, there can be only one.
Friends
class CheckPointOutputManager
Detailed Description
A SectionedOutputStream is a std::ostream that writes a section of a checkpoint file.
This class automatically writes the start and end markers. Standard C++ output mechanisms can be used to write the contents of the section.
This is a barebones implementation. It does not provide buffering, it does not support seek and tell, and it does not support putback or unget.
Note that most of the content of this class is private. This class is not extensible and is intended to be used within the context of a CheckPointOutputManager.
Definition at line 156 of file checkpoint_output_manager.hh.
Constructor & Destructor Documentation
SectionedOutputStream() [1/3]
jeod::SectionedOutputStream::SectionedOutputStream ()
Construct a SectionedOutputStream object.
Note
This default constructor creates a disconnected and hence unusable stream. Usable streams are created by the non-default constructor.
Definition at line 113 of file checkpoint_output_manager.cc.
SectionedOutputStream() [2/3]
jeod::SectionedOutputStream::SectionedOutputStream (const SectionedOutputStream & source)
Construct a SectionedOutputStream object by copying from another.
Parameters
[in] source Source object
Definition at line 145 of file checkpoint_output_manager.cc.
References jeod::MessageHandler::error(), jeod::SimInterfaceMessages::implementation_error, is_active, is_copy, manager, and stream.
~SectionedOutputStream()
jeod::SectionedOutputStream::~SectionedOutputStream () override
Destruct a SectionedOutputStream object.
Definition at line 171 of file checkpoint_output_manager.cc.
References deactivate().
SectionedOutputStream() [3/3]
jeod::SectionedOutputStream::SectionedOutputStream (CheckPointOutputManager * mngr, std::ofstream & ofstream, const std::string & start_marker, const std::string & end_marker, const std::string & section_name) private
Construct a SectionedOutputStream object that is connected to a file stream and to a CheckPointOutputManager.
Parameters
[in] mngr The stream manager
[in] ofstream The output file stream
[in] start_marker Start of section marker
[in] end_marker End of section marker
[in] section_name Name of the section
Definition at line 127 of file checkpoint_output_manager.cc.
Member Function Documentation
activate()
bool jeod::SectionedOutputStream::activate ()
Activate the object.
Note
Using the object for writing prior to activation will write nothing.
Returns
True if activated.
Definition at line 203 of file checkpoint_output_manager.cc.
References jeod::SectionedOutputBuffer::activate(), jeod::MessageHandler::error(), jeod::SimInterfaceMessages::implementation_error, is_active, manager, jeod::CheckPointOutputManager::register_writer(), sectbuf, section_start, stream, and tag.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_allocations(), and jeod::JeodTrick10MemoryInterface::checkpoint_containers().
deactivate()
void jeod::SectionedOutputStream::deactivate ()
Deactivate the object.
Note
Deactivation is undoable.
Definition at line 260 of file checkpoint_output_manager.cc.
References jeod::SectionedOutputBuffer::deactivate(), jeod::CheckPointOutputManager::deregister_writer(), is_active, manager, sectbuf, section_end, stream, and tag.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers(), jeod::CheckPointOutputManager::create_trick_section_writer(), and ~SectionedOutputStream().
is_activatable()
bool jeod::SectionedOutputStream::is_activatable () const
Determine if the stream is able to be activated.
Returns
True if object can be activated.
Definition at line 181 of file checkpoint_output_manager.cc.
References jeod::CheckPointOutputManager::have_active_writer(), is_active, manager, and stream.
operator void *()
jeod::SectionedOutputStream::operator void * () const inline
Conversion to void*.
This method provides an alternative to the bang-bang trick to determine if the object is OK.
Returns
this pointer (cast to void*) if object is OK, NULL otherwise.
Definition at line 197 of file checkpoint_output_manager.hh.
operator!()
bool jeod::SectionedOutputStream::operator! () const inline
Conversion to boolean.
Returns
False if object is OK.
Definition at line 186 of file checkpoint_output_manager.hh.
References is_active, sectbuf, and stream.
operator=()
SectionedOutputStream& jeod::SectionedOutputStream::operator= (const SectionedOutputStream &) delete
Friends And Related Function Documentation
CheckPointOutputManager
friend class CheckPointOutputManager friend
Definition at line 158 of file checkpoint_output_manager.hh.
Field Documentation
is_active
bool jeod::SectionedOutputStream::is_active {} private
Is this an active object? In the end, there can be only one.
trick_io(**)
Definition at line 260 of file checkpoint_output_manager.hh.
Referenced by activate(), deactivate(), is_activatable(), operator!(), and SectionedOutputStream().
is_copy
bool jeod::SectionedOutputStream::is_copy {} private
Is this a copy of some other SectionedOutputStream? Copies of copies are verboten.
trick_io(**)
Definition at line 254 of file checkpoint_output_manager.hh.
Referenced by SectionedOutputStream().
manager
CheckPointOutputManager* jeod::SectionedOutputStream::manager {} private
The input manager that created this object.
trick_io(**)
Definition at line 228 of file checkpoint_output_manager.hh.
Referenced by activate(), deactivate(), is_activatable(), and SectionedOutputStream().
sectbuf
SectionedOutputBuffer jeod::SectionedOutputStream::sectbuf private
The std::streambuf that does the writing to the file.
trick_io(**)
Definition at line 223 of file checkpoint_output_manager.hh.
Referenced by activate(), deactivate(), and operator!().
section_end
const std::string* jeod::SectionedOutputStream::section_end {} private
The string that indicates the start of a checkpoint file section.
Definition at line 243 of file checkpoint_output_manager.hh.
Referenced by deactivate().
section_start
const std::string* jeod::SectionedOutputStream::section_start {} private
The string that indicates the start of a checkpoint file section.
Definition at line 238 of file checkpoint_output_manager.hh.
Referenced by activate().
stream
std::ofstream* jeod::SectionedOutputStream::stream {} private
The C++ file stream that writes to the checkpoint file.
trick_io(**)
Definition at line 233 of file checkpoint_output_manager.hh.
Referenced by activate(), deactivate(), is_activatable(), operator!(), and SectionedOutputStream().
tag
const std::string jeod::SectionedOutputStream::tag {""} private
The name of the checkpoint file section.
Definition at line 248 of file checkpoint_output_manager.hh.
Referenced by activate(), and deactivate().
The documentation for this class was generated from the following files:
checkpoint_output_manager.hh
checkpoint_output_manager.cc