JEOD: jeod::JeodCheckpointable Class Reference
jeod::JeodCheckpointable Class Reference abstract
A JeodCheckpointable is an object whose contents are opaque to Trick, and presumably other simulation engines, whose contents can nonetheless be checkpointed and restarted by using the methods defined herein.
#include <checkpointable.hh>
Public Member Functions
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_name (void)
In general, return the name of the finalization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
virtual void start_checkpoint (void)=0
Prepare to checkpoint the object in question.
virtual void advance_checkpoint (void)=0
Advance to the next item to be checkpointed.
virtual bool is_checkpoint_finished (void)=0
Return true if all contents have been checkpointed, false otherwise.
virtual const std::string get_init_name (void)=0
Return the name of the action, if any, that will be performed prior to performing the individual actions.
virtual const std::string get_item_name (void)=0
Return the name of the action that will restore the value at the current checkpoint position.
virtual const std::string get_item_value (void)=0
Return the value of the item to be written to the checkpoint file.
virtual int perform_restore_action (const std::string &action_name, const std::string &action_value)=0
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
Private Member Functions
JeodCheckpointable (const JeodCheckpointable &)
Not implemented.
JeodCheckpointable & operator= (const JeodCheckpointable &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__JeodCheckpointable ()
Detailed Description
A JeodCheckpointable is an object whose contents are opaque to Trick, and presumably other simulation engines, whose contents can nonetheless be checkpointed and restarted by using the methods defined herein.
Definition at line 81 of file checkpointable.hh.
Constructor & Destructor Documentation
JeodCheckpointable() [1/2]
jeod::JeodCheckpointable::JeodCheckpointable (void) inline
Default constructor; does nothing.
Definition at line 200 of file checkpointable.hh.
~JeodCheckpointable()
jeod::JeodCheckpointable::~JeodCheckpointable (void) inline virtual
Destructor; does nothing.
Definition at line 211 of file checkpointable.hh.
JeodCheckpointable() [2/2]
jeod::JeodCheckpointable::JeodCheckpointable (const JeodCheckpointable &) private
Not implemented.
Member Function Documentation
advance_checkpoint()
virtual void jeod::JeodCheckpointable::advance_checkpoint (void) pure virtual
Advance to the next item to be checkpointed.
Implemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, jeod::JeodObjectContainer< ContainerType, ElemType >, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_final_name()
const std::string jeod::JeodCheckpointable::get_final_name (void) inline virtual
In general, return the name of the finalization action.
The returned value is written to the checkpoint file as the name of the final action, but only if this name is not empty.
The default implementation is the empty string.
Reimplemented in jeod::JeodContainer< ContainerType, ElemType >, and jeod::JeodContainer< ContainerType, ElemType *>.
Definition at line 241 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_final_value()
const std::string jeod::JeodCheckpointable::get_final_value (void) inline virtual
In general, return the value of the finalization action.
The returned value is written to the checkpoint file as the argument of the final action, but only if the finalization action is not empty.
The default implementation is the empty string.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 256 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_init_name()
virtual const std::string jeod::JeodCheckpointable::get_init_name (void) pure virtual
Return the name of the action, if any, that will be performed prior to performing the individual actions.
Note: The init name must be alphanumeric or empty.
Implemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_init_value()
const std::string jeod::JeodCheckpointable::get_init_value (void) inline virtual
In general, return the value of the initialization action.
The returned value is written to the checkpoint file as the argument of the init action, but only if the initialization action is not empty.
The default implementation is the empty string.
Definition at line 226 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_item_name()
virtual const std::string jeod::JeodCheckpointable::get_item_name (void) pure virtual
Return the name of the action that will restore the value at the current checkpoint position.
This action name and the corresponding value will be written to the checkpoint file in the form "owner.action(value);". Note: The item name must be alphanumeric.
Implemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_item_value()
virtual const std::string jeod::JeodCheckpointable::get_item_value (void) pure virtual
Return the value of the item to be written to the checkpoint file.
Translation of the true value to a string is up to the implementation. The string value must be something that the restore_perform_action method can translate back to the true value and should also be human-readable; people as well as the Memory Manager read checkpoint files.
Implemented in jeod::JeodObjectContainer< ContainerType, ElemType >, jeod::JeodPointerContainer< ContainerType, ElemType >, jeod::JeodPrimitiveContainer< ContainerType, ElemType >, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
initialize_checkpointable()
void jeod::JeodCheckpointable::initialize_checkpointable (const void * container, const std::type_info & container_type, const std::string & elem_name) inline virtual
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
The default implementation is to do nothing.
Parameters
container The object that contains this object.
container_type The type of the containing object.
elem_name The name of the this object in the containing object.
Reimplemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, and jeod::JeodPointerContainer< ContainerType, ElemType >.
Definition at line 334 of file checkpointable.hh.
Referenced by jeod::JeodMemoryManager::register_container().
is_checkpoint_finished()
virtual bool jeod::JeodCheckpointable::is_checkpoint_finished (void) pure virtual
Return true if all contents have been checkpointed, false otherwise.
Implemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
operator=()
JeodCheckpointable& jeod::JeodCheckpointable::operator= (const JeodCheckpointable &) private
Not implemented.
perform_restore_action()
virtual int jeod::JeodCheckpointable::perform_restore_action (const std::string & action_name, const std::string & action_value) pure virtual
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
The method is called for each entry in the checkpoint file that pertains to this object.
Parameters
action_name The name of the action.
action_value The value of the action.
Returns
Success (zero) / failure (non-zero).
Implemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::restore_containers().
post_checkpoint()
void jeod::JeodCheckpointable::post_checkpoint (void) inline virtual
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
The simulation engine calls this method after checkpoint-proper completion.
The default implementation is to do nothing.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 286 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
post_restart()
void jeod::JeodCheckpointable::post_restart (void) inline virtual
In general, perform object-specific operations that need to be performed after restart completion.
The default implementation is to do nothing.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 315 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::restore_containers().
pre_checkpoint()
void jeod::JeodCheckpointable::pre_checkpoint (void) inline virtual
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
The simulation engine calls this method prior to checkpointing allocations.
The default implementation is to do nothing.
Reimplemented in jeod::JeodObjectContainer< ContainerType, ElemType >.
Definition at line 271 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_allocations().
pre_restart()
void jeod::JeodCheckpointable::pre_restart (void) inline virtual
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
The simulation engine calls this method prior to restoring allocated data.
The default implementation is to do nothing.
Definition at line 301 of file checkpointable.hh.
Referenced by jeod::JeodTrick10MemoryInterface::restore_allocations().
start_checkpoint()
virtual void jeod::JeodCheckpointable::start_checkpoint (void) pure virtual
Prepare to checkpoint the object in question.
Implemented in jeod::JeodContainer< ContainerType, ElemType >, jeod::JeodContainer< ContainerType, ElemType *>, jeod::JeodObjectContainer< ContainerType, ElemType >, and jeod::SimpleCheckpointable.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_containers().
undo_initialize_checkpointable()
void jeod::JeodCheckpointable::undo_initialize_checkpointable (const void * container, const std::type_info & container_type, const std::string & elem_name) inline virtual
In general, undo external actions performed by initialize_checkpointable.
The default implementation is to do nothing.
Parameters
container The object that contains this object.
container_type The type of the containing object.
elem_name The name of the this object in the containing object.
Definition at line 353 of file checkpointable.hh.
Referenced by jeod::JeodMemoryManager::deregister_container().
Friends And Related Function Documentation
init_attrjeod__JeodCheckpointable
void init_attrjeod__JeodCheckpointable () friend
InputProcessor
friend class InputProcessor friend
Definition at line 82 of file checkpointable.hh.
The documentation for this class was generated from the following file:
checkpointable.hh