JEOD: jeod::JeodSimulationInterface Class Reference
jeod::JeodSimulationInterface Class Reference abstract
This abstract class defines the basis for the interface between JEOD and a simulation engine.
#include <simulation_interface.hh>
Public Types
enum Mode {
Construction = 0, PreCheckpoint = 1, Checkpoint = 2, PostCheckpoint = 3,
Restart = 4, Restore = 5, Initialization = 6, Operational = 7,
Shutdown = 8, Dead = 9, NumModes = 10
}
Defines the states of the JeodSimulationInterface state machine.
Public Member Functions
JeodSimulationInterface ()
Construct a JeodSimulationInterface object.
virtual ~JeodSimulationInterface ()
Destruct a JeodSimulationInterface object.
JeodSimulationInterface (const JeodSimulationInterface &)=delete
JeodSimulationInterface & operator= (const JeodSimulationInterface &)=delete
virtual void configure (const JeodSimulationInterfaceInit &config)
Configure a JeodSimulationInterface object.
Mode get_mode () const
Get the current mode.
virtual void set_mode (Mode new_mode)
Set the mode, but only if allowed per the mode state transition diagram.
Static Public Member Functions
static JeodIntegratorInterface * create_integrator_interface ()
Create a simulation integrator interface object.
static double get_job_cycle ()
Get the cycle time of the currently executing job.
static std::string get_name_at_address (const void *addr, const JeodMemoryTypeDescriptor *tdesc)
Translate the given address to a symbolic name.
static void * get_address_at_name (const std::string &name)
Translate the given symbolic name to an address.
static JeodMemoryInterface & get_memory_interface ()
Get the interface with the simulation memory model.
static SectionedInputStream get_checkpoint_reader (const std::string &section_id)
Get a reader of a section of the currently open checkpoint file.
static SectionedOutputStream get_checkpoint_writer (const std::string &section_id)
Get a writer to a section of the currently open checkpoint file.
Protected Member Functions
virtual JeodIntegratorInterface * create_integrator_internal ()=0
Create an integration interface object.
virtual double get_job_cycle_internal ()=0
Get the simulation cycle time of the currently executing function.
virtual JeodMemoryInterface & get_memory_interface_internal ()=0
Get the interface with the simulation memory manager.
virtual SectionedInputStream get_checkpoint_reader_internal (const std::string &section_id)=0
Get a checkpoint section reader.
virtual SectionedOutputStream get_checkpoint_writer_internal (const std::string &section_id)=0
Get a checkpoint section writer.
Protected Attributes
Mode mode {Construction}
The mode in which the simulation interface is operating.
Mode saved_mode {Construction}
The mode prior to a checkpoint or restart process.
Static Protected Attributes
static JeodSimulationInterface * sim_interface = nullptr
The singleton instance of a SimulationInterface object that must be created by a conforming JEOD simulation before any call can be made to one of the three static methods declared above.
Friends
class InputProcessor
void init_attrjeod__JeodSimulationInterface ()
Detailed Description
This abstract class defines the basis for the interface between JEOD and a simulation engine.
A compliant derived class must contain one instance each of a class that derives from MessageHandler and a class that derives from JeodMemoryManager. The MessageHandler object must be constructed before the JeodMemoryManager object; destruction must be performed in reverse order.
Definition at line 129 of file simulation_interface.hh.
Member Enumeration Documentation
Mode
enum jeod::JeodSimulationInterface::Mode
Defines the states of the JeodSimulationInterface state machine.
Enumerator
Construction
PreCheckpoint
Checkpoint
PostCheckpoint
Restart
Restore
Initialization
Operational
Shutdown
Dead
NumModes
Definition at line 137 of file simulation_interface.hh.
Constructor & Destructor Documentation
JeodSimulationInterface() [1/2]
jeod::JeodSimulationInterface::JeodSimulationInterface ()
Construct a JeodSimulationInterface object.
Definition at line 65 of file simulation_interface.cc.
References jeod::MessageHandler::error(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
~JeodSimulationInterface()
jeod::JeodSimulationInterface::~JeodSimulationInterface () virtual
Destruct a JeodSimulationInterface object.
Definition at line 83 of file simulation_interface.cc.
References sim_interface.
JeodSimulationInterface() [2/2]
jeod::JeodSimulationInterface::JeodSimulationInterface (const JeodSimulationInterface &) delete
Member Function Documentation
configure()
void jeod::JeodSimulationInterface::configure (const JeodSimulationInterfaceInit & config) virtual
Configure a JeodSimulationInterface object.
Parameters
[in] config Configuration spec
Definition at line 95 of file simulation_interface.cc.
References jeod::JeodSimulationInterfaceInit::memory_debug_level, jeod::JeodSimulationInterfaceInit::message_suppress_id, jeod::JeodSimulationInterfaceInit::message_suppress_location, jeod::JeodSimulationInterfaceInit::message_suppression_level, jeod::JeodMemoryManager::set_debug_level(), jeod::MessageHandler::set_suppress_id(), jeod::MessageHandler::set_suppress_location(), and jeod::MessageHandler::set_suppression_level().
create_integrator_interface()
JeodIntegratorInterface * jeod::JeodSimulationInterface::create_integrator_interface () static
Create a simulation integrator interface object.
Returns
Constructed IntegratorInterface object.
Definition at line 110 of file simulation_interface.cc.
References create_integrator_internal(), jeod::MessageHandler::fail(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::DynManager::initialize_model().
create_integrator_internal()
virtual JeodIntegratorInterface* jeod::JeodSimulationInterface::create_integrator_internal () protected pure virtual
Create an integration interface object.
The calling object is responsible for destroying the created object.
Returns
Created integration interface object.
Implemented in jeod::TestSimInterface, and jeod::BasicJeodTrickSimInterface.
Referenced by create_integrator_interface().
get_address_at_name()
void * jeod::JeodSimulationInterface::get_address_at_name (const std::string & name) static
Translate the given symbolic name to an address.
Returns
Address
Parameters
[in] name Symbolic name
Definition at line 201 of file simulation_interface.cc.
References jeod::MessageHandler::fail(), jeod::JeodMemoryInterface::get_address_at_name(), get_memory_interface_internal(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::JeodDynbodyIntegrationLoop::find_containing_sim_object(), jeod::JeodObjectContainer< ContainerType, ElemType >::perform_cleanup_action(), jeod::JeodPointerContainer< ContainerType, ElemType >::perform_insert_action(), jeod::JPVCollectForce::perform_insert_action(), jeod::JPVCollectTorque::perform_insert_action(), and jeod::JeodObjectContainer< ContainerType, ElemType >::perform_insert_action().
get_checkpoint_reader()
SectionedInputStream jeod::JeodSimulationInterface::get_checkpoint_reader (const std::string & section_id) static
Get a reader of a section of the currently open checkpoint file.
Returns
Checkpoint reader
Parameters
[in] section_id Section ID
Definition at line 225 of file simulation_interface.cc.
References jeod::MessageHandler::fail(), get_checkpoint_reader_internal(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::JeodTrick10MemoryInterface::restore_allocations(), and jeod::JeodTrick10MemoryInterface::restore_containers().
get_checkpoint_reader_internal()
virtual SectionedInputStream jeod::JeodSimulationInterface::get_checkpoint_reader_internal (const std::string & section_id) protected pure virtual
Get a checkpoint section reader.
Implemented in jeod::TestSimInterface, and jeod::BasicJeodTrickSimInterface.
Referenced by get_checkpoint_reader().
get_checkpoint_writer()
SectionedOutputStream jeod::JeodSimulationInterface::get_checkpoint_writer (const std::string & section_id) static
Get a writer to a section of the currently open checkpoint file.
Returns
Checkpoint writer
Parameters
[in] section_id Section ID
Definition at line 245 of file simulation_interface.cc.
References jeod::MessageHandler::fail(), get_checkpoint_writer_internal(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_allocations(), and jeod::JeodTrick10MemoryInterface::checkpoint_containers().
get_checkpoint_writer_internal()
virtual SectionedOutputStream jeod::JeodSimulationInterface::get_checkpoint_writer_internal (const std::string & section_id) protected pure virtual
Get a checkpoint section writer.
Implemented in jeod::TestSimInterface, and jeod::BasicJeodTrickSimInterface.
Referenced by get_checkpoint_writer().
get_job_cycle()
double jeod::JeodSimulationInterface::get_job_cycle () static
Get the cycle time of the currently executing job.
Returns
Cycle time in simulation engine seconds of the currently executing job.
Units: s
Definition at line 133 of file simulation_interface.cc.
References jeod::MessageHandler::fail(), get_job_cycle_internal(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::RadiationPressure::update().
get_job_cycle_internal()
virtual double jeod::JeodSimulationInterface::get_job_cycle_internal () protected pure virtual
Get the simulation cycle time of the currently executing function.
Returns
Cycle time in simulation engine seconds
Implemented in jeod::TestSimInterface, and jeod::BasicJeodTrickSimInterface.
Referenced by get_job_cycle().
get_memory_interface()
JeodMemoryInterface & jeod::JeodSimulationInterface::get_memory_interface () static
Get the interface with the simulation memory model.
Returns
Memory interface
Definition at line 156 of file simulation_interface.cc.
References jeod::MessageHandler::fail(), get_memory_interface_internal(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::JeodSimEngineAttributes< Type, is_class >::attributes(), jeod::JeodSimEngineAttributes< Type, true >::attributes(), jeod::JeodSimEngineAttributes< void *, false >::attributes(), and jeod::JeodSimEngineAttributes< Type *, false >::attributes().
get_memory_interface_internal()
virtual JeodMemoryInterface& jeod::JeodSimulationInterface::get_memory_interface_internal () protected pure virtual
Get the interface with the simulation memory manager.
Returns
JEOD/simulation engine memory interface.
Implemented in jeod::TestSimInterface, and jeod::BasicJeodTrickSimInterface.
Referenced by get_address_at_name(), get_memory_interface(), and get_name_at_address().
get_mode()
Mode jeod::JeodSimulationInterface::get_mode () const inline
Get the current mode.
Definition at line 235 of file simulation_interface.hh.
References mode.
Referenced by jeod::BasicJeodTrickSimInterface::set_mode().
get_name_at_address()
std::string jeod::JeodSimulationInterface::get_name_at_address (const void * addr, const JeodMemoryTypeDescriptor * tdesc) static
Translate the given address to a symbolic name.
Returns
Symbolic name
Parameters
[in] addr Address
[in] tdesc Descriptor
Definition at line 177 of file simulation_interface.cc.
References jeod::MessageHandler::fail(), get_memory_interface_internal(), jeod::JeodMemoryInterface::get_name_at_address(), sim_interface, and jeod::SimInterfaceMessages::singleton_error.
Referenced by jeod::JeodDynbodyIntegrationLoop::find_containing_sim_object(), jeod::JeodObjectContainer< ContainerType, ElemType >::get_final_value(), jeod::JeodPointerContainer< ContainerType, ElemType >::get_item_value(), and jeod::JeodObjectContainer< ContainerType, ElemType >::get_item_value().
operator=()
JeodSimulationInterface& jeod::JeodSimulationInterface::operator= (const JeodSimulationInterface &) delete
set_mode()
void jeod::JeodSimulationInterface::set_mode (Mode new_mode) virtual
Set the mode, but only if allowed per the mode state transition diagram.
Assumptions and Limitations
The standard JEODSys Trick sim object follows the correct state transition diagram. A similar sequence must be implemented when JEOD is used outside of the Trick environment. In a Trick environment, nobody should call this function except the Trick scheduler, and these calls must conform with the sequence in the standard JEODSys Trick sim object.
Parameters
[in] new_mode New mode
Reimplemented in jeod::BasicJeodTrickSimInterface.
Definition at line 271 of file simulation_interface.cc.
References Checkpoint, Construction, Dead, jeod::MessageHandler::fail(), jeod::SimInterfaceMessages::implementation_error, jeod::MessageHandler::inform(), Initialization, mode, NumModes, Operational, jeod::SimInterfaceMessages::phasing_error, PostCheckpoint, PreCheckpoint, Restart, Restore, saved_mode, and Shutdown.
Referenced by jeod::BasicJeodTrickSimInterface::set_mode().
Friends And Related Function Documentation
init_attrjeod__JeodSimulationInterface
void init_attrjeod__JeodSimulationInterface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 131 of file simulation_interface.hh.
Field Documentation
mode
Mode jeod::JeodSimulationInterface::mode {Construction} protected
The mode in which the simulation interface is operating.
trick_units(–)
Definition at line 294 of file simulation_interface.hh.
Referenced by get_mode(), and set_mode().
saved_mode
Mode jeod::JeodSimulationInterface::saved_mode {Construction} protected
The mode prior to a checkpoint or restart process.
set_mode(Restore) restores the mode to this saved value.trick_units(–)
Definition at line 300 of file simulation_interface.hh.
Referenced by set_mode().
sim_interface
JeodSimulationInterface * jeod::JeodSimulationInterface::sim_interface = nullptr static protected
The singleton instance of a SimulationInterface object that must be created by a conforming JEOD simulation before any call can be made to one of the three static methods declared above.
The first created instance of a class that derives from this base class becomes the SimulationInterface object used during the course of the simulation. Creation of more than one SimulationInteface objects is a non-fatal error. Attempts to allocate memory or generate a message prior creating a SimulationInteface object is a fatal error.trick_io(*o) trick_units(–)
Definition at line 256 of file simulation_interface.hh.
Referenced by create_integrator_interface(), get_address_at_name(), get_checkpoint_reader(), get_checkpoint_writer(), get_job_cycle(), get_memory_interface(), get_name_at_address(), JeodSimulationInterface(), and ~JeodSimulationInterface().
The documentation for this class was generated from the following files:
simulation_interface.hh
simulation_interface.cc