JEOD: jeod::JeodMemoryTypeDescriptor Class Reference
jeod::JeodMemoryTypeDescriptor Class Reference abstract
Abstract class for managing data allocated as some specific type.
#include <memory_type.hh>
Public Member Functions
JeodMemoryTypeDescriptor (const std::type_info &obj_typeid, const struct ATTRIBUTES_tag &type_attr, std::size_t type_size, bool is_exportable=true)
Non-default constructor.
JeodMemoryTypeDescriptor (const JeodMemoryTypeDescriptor &src)
Copy constructor.
virtual ~JeodMemoryTypeDescriptor ()
Destructor.
const std::type_info & get_typeid (void) const
Get the type info for the type.
const std::string & get_name (void) const
Get the name of the type.
std::size_t get_size (void) const
Get the size of the type.
const struct ATTRIBUTES_tag & get_attr (void) const
Get the simulation engine attributes for the type.
bool get_register_instances (void) const
Get the simulation engine attributes for the type.
std::size_t dimensionality (void) const
Determine the dimensionality of the type.
std::size_t buffer_size (unsigned int nelems) const
Compute the size of a buffer.
std::size_t buffer_size (const JeodMemoryItem &item) const
Compute the size of a buffer.
const void * buffer_end (const void *addr, unsigned int nelems) const
Compute the address of the byte just past the end a buffer.
const void * buffer_end (const void *addr, const JeodMemoryItem &item) const
Compute the address of the byte just past the end a buffer.
const std::string type_spec (const JeodMemoryItem &item) const
Construct a type specification string.
void destroy_memory (bool placement_new, bool is_array, unsigned int nelem, void *addr) const
Destroy memory.
virtual JeodMemoryTypeDescriptor * clone () const =0
Create a copy of the descriptor.
virtual bool is_structured (void) const =0
Indicate whether the type associated with the descriptor is a structured (non-primitive, non-pointer) type.
virtual void * construct_array (std::size_t nelem, void *addr) const =0
Construct an array of objects of the type.
virtual const void * most_derived_pointer (const void *addr) const =0
Find the most-derived object corresponding to the input pointer.
virtual void * most_derived_pointer (void *addr) const =0
Find the most-derived object corresponding to the input pointer.
Static Public Member Functions
static void set_check_for_registration_errors (bool val)
Enable/disable registration error messages.
Protected Member Functions
virtual void delete_array (void *addr) const =0
Delete an array of instances of the type associated with the descriptor.
virtual void delete_object (void *addr) const =0
Delete a single instance of the type associated with the descriptor.
virtual void destruct_array (std::size_t nelem, void *addr) const =0
Destruct (but do not delete) an array of nelem instances of the type associated with the descriptor.
Static Protected Member Functions
static std::string initialize_type_name (const char *type_name)
The jeod_alloc.hh macros insert a space between the type name and the asterisks.
static std::size_t pointer_dimension (const std::string &demangled_name)
Get the pointer dimensionality of the type.
static const JeodMemoryTypeDescriptor * base_type (const std::string &demangled_name)
Get the descriptor for the base (non-pointer) of some pointer type.
Protected Attributes
const std::type_info & obj_id
The RTTI descriptor of the type.
const std::string name
The name of the type in code.
const struct ATTRIBUTES_tag attr
The simulation engine attributes that describe the type.
const std::size_t size
The size of an instance of the type.
bool register_instances
Should instances be registered with the simulation engine? If true (default value), instances of the type will be registered with the simulation engine; the simulation engine is responsible for checkpointing and restoring the contents of such instances.
Static Protected Attributes
static bool check_for_registration_errors = false
When set, suspect memory interface results will be reported as a warnings.
Private Member Functions
JeodMemoryTypeDescriptor & operator= (const JeodMemoryTypeDescriptor &)
Not implemented.
Detailed Description
Abstract class for managing data allocated as some specific type.
A JeodMemoryTypeDescriptor is a clonable object that contains the name and size of a specific data type. Instantiable subclasses of this class are created by the class templates that derive from this base class.
Definition at line 97 of file memory_type.hh.
Constructor & Destructor Documentation
JeodMemoryTypeDescriptor() [1/2]
jeod::JeodMemoryTypeDescriptor::JeodMemoryTypeDescriptor (const std::type_info & obj_typeid, const struct ATTRIBUTES_tag & type_attr, std::size_t type_size, bool is_exportable = true)
Non-default constructor.
Note that construction is via a char* as that is what the C preprocessor creates when it stringifies a token.
Parameters
[in] obj_typeid Type ID for type
[in] type_attr Type attributes
[in] type_size Type size
[in] is_exportable Register instances?
Definition at line 176 of file memory_type.cc.
JeodMemoryTypeDescriptor() [2/2]
jeod::JeodMemoryTypeDescriptor::JeodMemoryTypeDescriptor (const JeodMemoryTypeDescriptor & src)
Copy constructor.
Parameters
[in] src Item to be copied
Definition at line 194 of file memory_type.cc.
~JeodMemoryTypeDescriptor()
jeod::JeodMemoryTypeDescriptor::~JeodMemoryTypeDescriptor (void) virtual
Destructor.
Definition at line 209 of file memory_type.cc.
Member Function Documentation
base_type()
const JeodMemoryTypeDescriptor * jeod::JeodMemoryTypeDescriptor::base_type (const std::string & demangled_name) static protected
Get the descriptor for the base (non-pointer) of some pointer type.
Note
Assumes GNU c++ name mangling, where 'const' is always preceded by a space.
Definition at line 103 of file memory_type.cc.
References jeod::JeodMemoryManager::Demangled_type_name, and jeod::JeodMemoryManager::get_type_descriptor().
buffer_end() [1/2]
const void* jeod::JeodMemoryTypeDescriptor::buffer_end (const void * addr, unsigned int nelems) const inline
Compute the address of the byte just past the end a buffer.
Parameters
[in] addr Start of buffer
[in] nelems Size of the array
Definition at line 248 of file memory_type.hh.
References buffer_size().
Referenced by jeod::JeodMemoryManager::add_allocation_atomic(), and buffer_end().
buffer_end() [2/2]
const void* jeod::JeodMemoryTypeDescriptor::buffer_end (const void * addr, const JeodMemoryItem & item) const inline
Compute the address of the byte just past the end a buffer.
Parameters
[in] addr Start of buffer
[in] item Buffer descriptor
Definition at line 263 of file memory_type.hh.
References buffer_end(), and jeod::JeodMemoryItem::get_nelems().
buffer_size() [1/2]
std::size_t jeod::JeodMemoryTypeDescriptor::buffer_size (unsigned int nelems) const inline
Compute the size of a buffer.
Parameters
[in] nelems Size of the array
Returns
: Buffer size
Definition at line 222 of file memory_type.hh.
References size.
Referenced by jeod::JeodMemoryManager::add_allocation_atomic(), buffer_end(), buffer_size(), jeod::JeodMemoryManager::delete_oldest_alloc_entry_atomic(), jeod::NullMemoryInterface::deregister_allocation(), jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodMemoryManager::find_alloc_entry_atomic(), jeod::NullMemoryInterface::register_allocation(), jeod::JeodMemoryManager::register_memory_internal(), and jeod::JeodMemoryManager::restart_clear_memory().
buffer_size() [2/2]
std::size_t jeod::JeodMemoryTypeDescriptor::buffer_size (const JeodMemoryItem & item) const inline
Compute the size of a buffer.
Parameters
[in] item Buffer descriptor
Returns
: Buffer size
Definition at line 235 of file memory_type.hh.
References buffer_size(), and jeod::JeodMemoryItem::get_nelems().
clone()
virtual JeodMemoryTypeDescriptor* jeod::JeodMemoryTypeDescriptor::clone () const pure virtual
Create a copy of the descriptor.
Returns
Copy.
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by jeod::JeodMemoryTableClonable< JeodMemoryTypeDescriptor >::clone().
construct_array()
virtual void* jeod::JeodMemoryTypeDescriptor::construct_array (std::size_t nelem, void * addr) const pure virtual
Construct an array of objects of the type.
The default implementation does nothing, which is the right thing to do for primitive types, pointers, and abstract classes.
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by jeod::JeodMemoryManager::restart_reallocate().
delete_array()
virtual void jeod::JeodMemoryTypeDescriptor::delete_array (void * addr) const protected pure virtual
Delete an array of instances of the type associated with the descriptor.
In other words, delete[] addr.
Parameters
[in,out] addr Address to be deleted
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by destroy_memory().
delete_object()
virtual void jeod::JeodMemoryTypeDescriptor::delete_object (void * addr) const protected pure virtual
Delete a single instance of the type associated with the descriptor.
In other words, delete addr.
Parameters
[in,out] addr Address to be deleted
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by destroy_memory().
destroy_memory()
void jeod::JeodMemoryTypeDescriptor::destroy_memory (bool placement_new, bool is_array, unsigned int nelem, void * addr) const inline
Destroy memory.
Parameters
[in] placement_new Constructed with placement new?
[in] is_array Allocated as an array?
[in] nelem Number of elements
[in,out] addr Address to destroy
Definition at line 282 of file memory_type.hh.
References delete_array(), delete_object(), and destruct_array().
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), and jeod::JeodMemoryManager::restart_clear_memory().
destruct_array()
virtual void jeod::JeodMemoryTypeDescriptor::destruct_array (std::size_t nelem, void * addr) const protected pure virtual
Destruct (but do not delete) an array of nelem instances of the type associated with the descriptor.
Parameters
[in] nelem Number of elements in addr
[in,out] addr Address to be destructed
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by destroy_memory().
dimensionality()
std::size_t jeod::JeodMemoryTypeDescriptor::dimensionality (void) const inline
Determine the dimensionality of the type.
Returns
: Type dimensionality
Definition at line 209 of file memory_type.hh.
References name, and pointer_dimension().
get_attr()
const struct ATTRIBUTES_tag& jeod::JeodMemoryTypeDescriptor::get_attr (void) const inline
Get the simulation engine attributes for the type.
Returns
Type attributes
Definition at line 183 of file memory_type.hh.
References attr.
Referenced by jeod::JeodTrick10MemoryInterface::get_container_id(), and jeod::JeodTrick10MemoryInterface::get_name_at_address().
get_name()
const std::string& jeod::JeodMemoryTypeDescriptor::get_name (void) const inline
Get the name of the type.
Returns
Type name
Definition at line 159 of file memory_type.hh.
References name.
Referenced by jeod::JeodTrick10MemoryInterface::checkpoint_allocations(), jeod::JeodMemoryManager::find_alloc_entry_atomic(), jeod::JeodMemoryManager::get_type_entry_atomic(), and jeod::JeodTrickMemoryInterface::register_allocation().
get_register_instances()
bool jeod::JeodMemoryTypeDescriptor::get_register_instances (void) const inline
Get the simulation engine attributes for the type.
Returns
Type attributes
Definition at line 195 of file memory_type.hh.
References register_instances.
Referenced by jeod::JeodMemoryManager::register_memory_internal().
get_size()
std::size_t jeod::JeodMemoryTypeDescriptor::get_size (void) const inline
Get the size of the type.
Returns
Type size
Definition at line 171 of file memory_type.hh.
References size.
Referenced by jeod::JeodMemoryManager::create_memory_internal(), and jeod::JeodMemoryManager::restart_reallocate().
get_typeid()
const std::type_info& jeod::JeodMemoryTypeDescriptor::get_typeid (void) const inline
Get the type info for the type.
Returns
Type info
Definition at line 147 of file memory_type.hh.
References obj_id.
Referenced by jeod::JeodMemoryManager::get_type_index_nolock(), and jeod::JeodTrickMemoryInterface::register_allocation().
initialize_type_name()
std::string jeod::JeodMemoryTypeDescriptor::initialize_type_name (const char * type_name) static protected
The jeod_alloc.hh macros insert a space between the type name and the asterisks.
Delete that space.
Returns
Name, as c++ string
Parameters
[in] type_name Name, as C string
Definition at line 59 of file memory_type.cc.
is_structured()
virtual bool jeod::JeodMemoryTypeDescriptor::is_structured (void) const pure virtual
Indicate whether the type associated with the descriptor is a structured (non-primitive, non-pointer) type.
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by jeod::JeodMemoryManager::register_memory_internal().
most_derived_pointer() [1/2]
virtual const void* jeod::JeodMemoryTypeDescriptor::most_derived_pointer (const void * addr) const pure virtual
Find the most-derived object corresponding to the input pointer.
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
Referenced by jeod::JeodTrick10MemoryInterface::deregister_container(), and jeod::JeodTrick10MemoryInterface::register_container().
most_derived_pointer() [2/2]
virtual void* jeod::JeodMemoryTypeDescriptor::most_derived_pointer (void * addr) const pure virtual
Find the most-derived object corresponding to the input pointer.
Implemented in jeod::JeodMemoryTypeDescriptorDerived< Type >.
operator=()
JeodMemoryTypeDescriptor& jeod::JeodMemoryTypeDescriptor::operator= (const JeodMemoryTypeDescriptor &) private
Not implemented.
pointer_dimension()
size_t jeod::JeodMemoryTypeDescriptor::pointer_dimension (const std::string & demangled_name) static protected
Get the pointer dimensionality of the type.
Definition at line 77 of file memory_type.cc.
Referenced by dimensionality().
set_check_for_registration_errors()
static void jeod::JeodMemoryTypeDescriptor::set_check_for_registration_errors (bool val) inline static
Enable/disable registration error messages.
Parameters
[in] val New value for check_for_registration_errors
Definition at line 107 of file memory_type.hh.
References check_for_registration_errors.
type_spec()
const std::string jeod::JeodMemoryTypeDescriptor::type_spec (const JeodMemoryItem & item) const
Construct a type specification string.
Returns
Type string
Parameters
[in] item Item descriptor
Definition at line 220 of file memory_type.cc.
References jeod::NamedItem::demangle(), jeod::JeodMemoryItem::get_is_array(), jeod::JeodMemoryItem::get_nelems(), and obj_id.
Referenced by jeod::NullMemoryInterface::deregister_allocation(), jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodMemoryManager::generate_shutdown_report(), jeod::NullMemoryInterface::register_allocation(), and jeod::JeodMemoryManager::register_memory_internal().
Field Documentation
attr
const struct ATTRIBUTES_tag jeod::JeodMemoryTypeDescriptor::attr protected
The simulation engine attributes that describe the type.
trick_io(**)
Definition at line 394 of file memory_type.hh.
Referenced by get_attr().
check_for_registration_errors
bool jeod::JeodMemoryTypeDescriptor::check_for_registration_errors = false static protected
When set, suspect memory interface results will be reported as a warnings.
No messages are issued when this flag is clear.trick_units(–)
Definition at line 376 of file memory_type.hh.
Referenced by set_check_for_registration_errors().
name
const std::string jeod::JeodMemoryTypeDescriptor::name protected
The name of the type in code.
trick_io(**)
Definition at line 389 of file memory_type.hh.
Referenced by dimensionality(), and get_name().
obj_id
const std::type_info& jeod::JeodMemoryTypeDescriptor::obj_id protected
The RTTI descriptor of the type.
trick_io(**)
Definition at line 384 of file memory_type.hh.
Referenced by get_typeid(), and type_spec().
register_instances
bool jeod::JeodMemoryTypeDescriptor::register_instances protected
Should instances be registered with the simulation engine? If true (default value), instances of the type will be registered with the simulation engine; the simulation engine is responsible for checkpointing and restoring the contents of such instances.
If false, instances will not be registered with the simulation engine; the simulation engine is not responsible for checkpointing/restarting such instances.trick_io(**)
Definition at line 411 of file memory_type.hh.
Referenced by get_register_instances().
size
const std::size_t jeod::JeodMemoryTypeDescriptor::size protected
The size of an instance of the type.
trick_io(**)
Definition at line 399 of file memory_type.hh.
Referenced by buffer_size(), and get_size().
The documentation for this class was generated from the following files:
memory_type.hh
memory_type.cc