JEOD: jeod::JeodTrick10MemoryInterface Class Reference
jeod::JeodTrick10MemoryInterface Class Reference
A TrickMemoryInterface implements the two required methods needed to register and deregister memory with the simulation engine, Trick in this case.
#include <trick10_memory_interface.hh>
Public Member Functions
JeodTrick10MemoryInterface ()
Construct a JeodTrick10MemoryInterface object.
~JeodTrick10MemoryInterface () override
Destruct a JeodTrick10MemoryInterface object.
void register_container (const void *owner, const JeodMemoryTypeDescriptor &owner_type, const char *elem_name, JeodCheckpointable &container) override
Register the checkpointable object with Trick.
void deregister_container (const void *owner, const JeodMemoryTypeDescriptor &owner_type, const char *elem_name, JeodCheckpointable &container) override
Revoke the registrations performed by register_container.
const std::string get_name_at_address (const void *addr, const JeodMemoryTypeDescriptor *tdesc) const override
Get the simulation name, if any, associated with the address.
void * get_address_at_name (const std::string &name) const override
Get the address, if any, that corresponds to the given name.
bool is_checkpoint_restart_supported (void) const override
The Trick10 memory interface supports checkpoint/restart.
const std::string get_trick_checkpoint_file (bool checkpoint) override
Get the name of the current Trick checkpoint file.
void checkpoint_containers (void) override
Dump the checkpointable objects to the checkpoint file.
void restore_containers (void) override
Restore the checkpointable objects from the checkpoint file.
void checkpoint_allocations (void) override
Dump the allocation information to the checkpoint file.
void restore_allocations (JeodMemoryManager &memory_manager) override
Restore the allocated data per the checkpoint file.
Public Member Functions inherited from jeod::JeodTrickMemoryInterface
JeodTrickMemoryInterface ()
JeodTrickMemoryInterface default constructor.
~JeodTrickMemoryInterface () override
JeodTrickMemoryInterface destructor.
void set_mode (JeodSimulationInterface::Mode new_mode)
Set the mode and perform mode transitions.
std::string construct_identifier (uint32_t unique_id_number)
Construct an identifier for a chunk of JEOD-allocated memory.
const struct ATTRIBUTES_tag * find_attributes (const std::string &type_name) const override
Find the attributes for a class in the symbol table.
const struct ATTRIBUTES_tag * find_attributes (const std::type_info &data_type) const override
Find the attributes for a class in the symbol table.
struct ATTRIBUTES_tag primitive_attributes (const std::type_info &data_type) const override
Create an attributes structure that represents a primitive type.
struct ATTRIBUTES_tag pointer_attributes (const struct ATTRIBUTES_tag &target_attr) const override
Create an attributes structure that represents a pointer type.
struct ATTRIBUTES_tag void_pointer_attributes () const override
Create an attributes structure that represents a void* pointer.
struct ATTRIBUTES_tag structure_attributes (const struct ATTRIBUTES_tag *target_attr, std::size_t target_size) const override
Create an attributes structure that represents a structured type.
bool register_allocation (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line) override
Register newly allocated memory with Trick.
void deregister_allocation (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line) override
Delete Trick information about some pointer – but not the pointer itself.
void register_container (const void *owner, const JeodMemoryTypeDescriptor &owner_type, const char *elem_name, JeodCheckpointable &container) override
Register the checkpointable object with Trick.
void deregister_container (const void *owner, const JeodMemoryTypeDescriptor &owner_type, const char *elem_name, JeodCheckpointable &container) override
Revoke the registrations performed by register_container.
const std::string get_name_at_address (const void *addr, const JeodMemoryTypeDescriptor *tdesc) const override
Stubbed-out implementation of get_name_at_address for Trick implementations that do not fully support JEOD checkpoint/restart requirements.
void * get_address_at_name (const std::string &name) const override
Stubbed-out implementation of get_address_at_name for Trick implementations that do not fully support JEOD checkpoint/restart requirements.
bool is_checkpoint_restart_supported () const override
The generic Trick memory interface does not support checkpoint/restart.
Public Member Functions inherited from jeod::JeodMemoryInterface
JeodMemoryInterface ()
Default constructor.
virtual ~JeodMemoryInterface ()
Destructor.
JeodMemoryInterface (const JeodMemoryInterface &)
Copy constructor.
JeodMemoryInterface & operator= (const JeodMemoryInterface &)
Assignment operator.
Protected Member Functions
std::string get_container_id (const ContainerListEntry &entry) const
Construct the identifier for a checkpointable object.
std::string translate_addr_to_name (const void *addr, const ATTRIBUTES *attr) const
Translate the given address to an address specification string, with the address interpreted in the context of the supplied attributes.
void * translate_name_to_addr (const std::string &spec) const
Translate the given address specification string to an address.
Protected Attributes
Trick::ClassicCheckPointAgent * trick_checkpoint_agent
Trick checkpoint agent.
Protected Attributes inherited from jeod::JeodTrickMemoryInterface
void * dlhandle
dlhandle, from dlopen.
AllocationMap allocation_map
Map of allocated names to type info.
ContainerList container_list
List of container checkpointables.
const std::string id_prefix
Prefix used for constructing a unique name for JEOD-allocated memory.
const uint32_t id_length
Number of digits in the numeric part of the unique identifier.
JeodSimulationInterface::Mode mode
Simulation interface mode.
Private Member Functions
JeodTrick10MemoryInterface (const JeodTrick10MemoryInterface &)
Not implemented.
JeodTrick10MemoryInterface & operator= (const JeodTrick10MemoryInterface &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__JeodTrick10MemoryInterface ()
Additional Inherited Members
Protected Types inherited from jeod::JeodTrickMemoryInterface
typedef std::map< uint32_t, AllocationMapEntry > AllocationMap
Maps JEOD-allocated data names to (type, size) pairs.
typedef std::list< ContainerListEntry > ContainerList
Container of a list of ContainerListEntry objects.
Detailed Description
A TrickMemoryInterface implements the two required methods needed to register and deregister memory with the simulation engine, Trick in this case.
Definition at line 109 of file trick10_memory_interface.hh.
Constructor & Destructor Documentation
JeodTrick10MemoryInterface() [1/2]
jeod::JeodTrick10MemoryInterface::JeodTrick10MemoryInterface (void)
Construct a JeodTrick10MemoryInterface object.
Definition at line 62 of file trick10_memory_interface.cc.
References jeod::MessageHandler::fail(), jeod::SimInterfaceMessages::interface_error, trick_checkpoint_agent, and trick_MM.
~JeodTrick10MemoryInterface()
jeod::JeodTrick10MemoryInterface::~JeodTrick10MemoryInterface (void) override
Destruct a JeodTrick10MemoryInterface object.
Definition at line 84 of file trick10_memory_interface.cc.
JeodTrick10MemoryInterface() [2/2]
jeod::JeodTrick10MemoryInterface::JeodTrick10MemoryInterface (const JeodTrick10MemoryInterface &) private
Not implemented.
Member Function Documentation
checkpoint_allocations()
void jeod::JeodTrick10MemoryInterface::checkpoint_allocations (void) override virtual
Dump the allocation information to the checkpoint file.
Reimplemented from jeod::JeodTrickMemoryInterface.
Definition at line 431 of file trick_memory_interface_chkpnt.cc.
References jeod::SectionedOutputStream::activate(), jeod::JeodTrickMemoryInterface::allocation_map, jeod::JeodTrickMemoryInterface::construct_identifier(), jeod::JeodTrickMemoryInterface::container_list, jeod::MessageHandler::error(), jeod::JeodSimulationInterface::get_checkpoint_writer(), jeod::JeodMemoryTypeDescriptor::get_name(), jeod::JeodMemoryManager::get_type_descriptor(), jeod::SimInterfaceMessages::interface_error, jeod::JeodTrickMemoryInterface::AllocationMapEntry::is_array, jeod::JeodTrickMemoryInterface::AllocationMapEntry::nelements, jeod::JeodCheckpointable::pre_checkpoint(), and jeod::JeodTrickMemoryInterface::AllocationMapEntry::typeid_info.
Referenced by jeod::BasicJeodTrickSimInterface::checkpoint_allocations().
checkpoint_containers()
void jeod::JeodTrick10MemoryInterface::checkpoint_containers (void) override virtual
Dump the checkpointable objects to the checkpoint file.
Reimplemented from jeod::JeodTrickMemoryInterface.
Definition at line 243 of file trick_memory_interface_chkpnt.cc.
References jeod::SectionedOutputStream::activate(), jeod::JeodCheckpointable::advance_checkpoint(), jeod::JeodTrickMemoryInterface::container_list, jeod::SectionedOutputStream::deactivate(), jeod::MessageHandler::error(), jeod::JeodSimulationInterface::get_checkpoint_writer(), get_container_id(), jeod::JeodCheckpointable::get_final_name(), jeod::JeodCheckpointable::get_final_value(), jeod::JeodCheckpointable::get_init_name(), jeod::JeodCheckpointable::get_init_value(), jeod::JeodCheckpointable::get_item_name(), jeod::JeodCheckpointable::get_item_value(), jeod::SimInterfaceMessages::interface_error, jeod::JeodCheckpointable::is_checkpoint_finished(), jeod::JeodCheckpointable::post_checkpoint(), and jeod::JeodCheckpointable::start_checkpoint().
Referenced by jeod::BasicJeodTrickSimInterface::checkpoint_containers().
deregister_container()
void jeod::JeodTrick10MemoryInterface::deregister_container (const void * owner, const JeodMemoryTypeDescriptor & owner_type, const char * elem_name, JeodCheckpointable & container) override virtual
Revoke the registrations performed by register_container.
This function is typically called at destruction time via JEOD_DEREGISTER_CHECKPOINTABLE.
Assumptions and Limitations
The following unenforced assumptions are made:
A corresponding register_container was previously made.
Trick has been pre-initialized.
Enforcement of the above is the responsibility the simulation developer, the JEOD memory manager, and the simulation interface.
Parameters
[in] owner Owner of the container
[in] owner_type Owner type descriptor
[in] elem_name Container element
[in,out] container The container
Implements jeod::JeodMemoryInterface.
Definition at line 145 of file trick_memory_interface_chkpnt.cc.
References jeod::JeodTrickMemoryInterface::container_list, jeod::JeodTrickMemoryInterface::ContainerListEntry::elem_name, jeod::MessageHandler::error(), jeod::SimInterfaceMessages::interface_error, jeod::JeodMemoryTypeDescriptor::most_derived_pointer(), jeod::JeodTrickMemoryInterface::ContainerListEntry::owner, and jeod::JeodTrickMemoryInterface::ContainerListEntry::owner_type.
get_address_at_name()
void * jeod::JeodTrick10MemoryInterface::get_address_at_name (const std::string & name) const override virtual
Get the address, if any, that corresponds to the given name.
Returns
Name of the address, if any
Parameters
[in] name of an address
Units: Name
Implements jeod::JeodMemoryInterface.
Definition at line 124 of file trick_memory_interface_xlate.cc.
References translate_name_to_addr().
get_container_id()
std::string jeod::JeodTrick10MemoryInterface::get_container_id (const ContainerListEntry & entry) const protected
Construct the identifier for a checkpointable object.
Returns
Container ID
Parameters
[in] entry Container list entry
Definition at line 200 of file trick_memory_interface_chkpnt.cc.
References jeod::JeodTrickMemoryInterface::ContainerListEntry::elem_name, jeod::JeodMemoryTypeDescriptor::get_attr(), jeod::JeodTrickMemoryInterface::ContainerListEntry::owner, jeod::JeodTrickMemoryInterface::ContainerListEntry::owner_type, translate_addr_to_name(), and translate_name_to_addr().
Referenced by checkpoint_containers(), register_container(), and restore_containers().
get_name_at_address()
const std::string jeod::JeodTrick10MemoryInterface::get_name_at_address (const void * addr, const JeodMemoryTypeDescriptor * tdesc) const override virtual
Get the simulation name, if any, associated with the address.
Returns
Name of the address, if any
Parameters
[in] addr Address of memory whose name is to be found
[in] tdesc How to interpret address
Implements jeod::JeodMemoryInterface.
Definition at line 88 of file trick_memory_interface_xlate.cc.
References jeod::JeodMemoryTypeDescriptor::get_attr(), translate_addr_to_name(), and translate_name_to_addr().
get_trick_checkpoint_file()
const std::string jeod::JeodTrick10MemoryInterface::get_trick_checkpoint_file (bool checkpoint) override virtual
Get the name of the current Trick checkpoint file.
Returns
Name of the current Trick checkpoint file.
Units:
Parameters
[in] checkpoint True for checkpoint, false for restart
Reimplemented from jeod::JeodTrickMemoryInterface.
Definition at line 67 of file trick_memory_interface_xlate.cc.
Referenced by jeod::BasicJeodTrickSimInterface::open_checkpoint_file(), and jeod::BasicJeodTrickSimInterface::open_restart_file().
is_checkpoint_restart_supported()
bool jeod::JeodTrick10MemoryInterface::is_checkpoint_restart_supported (void) const inline override virtual
The Trick10 memory interface supports checkpoint/restart.
Implements jeod::JeodMemoryInterface.
Definition at line 149 of file trick10_memory_interface.hh.
Referenced by jeod::BasicJeodTrickSimInterface::checkpoint_allocations(), jeod::BasicJeodTrickSimInterface::checkpoint_containers(), jeod::BasicJeodTrickSimInterface::open_checkpoint_file(), jeod::BasicJeodTrickSimInterface::open_restart_file(), jeod::BasicJeodTrickSimInterface::restore_allocations(), and jeod::BasicJeodTrickSimInterface::restore_containers().
operator=()
JeodTrick10MemoryInterface& jeod::JeodTrick10MemoryInterface::operator= (const JeodTrick10MemoryInterface &) private
Not implemented.
register_container()
void jeod::JeodTrick10MemoryInterface::register_container (const void * owner, const JeodMemoryTypeDescriptor & owner_type, const char * elem_name, JeodCheckpointable & container) override virtual
Register the checkpointable object with Trick.
This function is typically called at construction or initialization time via JEOD_REGISTER_CHECKPOINTABLE.
Assumptions and Limitations
The following unenforced assumptions are made:
Sim objects have been constructed and registered with Trick.
Checkpointable objects are unique.
Trick has been pre-initialized.
Not in shutdown mode.
Enforcement of the above is the responsibility the simulation developer, the JEOD memory manager, and the simulation interface.
Parameters
[in] owner Owner of the container
[in] owner_type Owner type descriptor
[in] elem_name Container element
[in,out] container The container
Implements jeod::JeodMemoryInterface.
Definition at line 82 of file trick_memory_interface_chkpnt.cc.
References jeod::JeodTrickMemoryInterface::container_list, jeod::JeodTrickMemoryInterface::ContainerListEntry::elem_name, jeod::MessageHandler::error(), get_container_id(), jeod::SimInterfaceMessages::interface_error, jeod::JeodMemoryTypeDescriptor::most_derived_pointer(), jeod::JeodTrickMemoryInterface::ContainerListEntry::owner, and jeod::JeodTrickMemoryInterface::ContainerListEntry::owner_type.
restore_allocations()
void jeod::JeodTrick10MemoryInterface::restore_allocations (JeodMemoryManager & memory_manager) override virtual
Restore the allocated data per the checkpoint file.
Parameters
[in,out] memory_manager JEOD memory manager
Reimplemented from jeod::JeodTrickMemoryInterface.
Definition at line 501 of file trick_memory_interface_chkpnt.cc.
References jeod::SectionedInputStream::activate(), jeod::JeodTrickMemoryInterface::container_list, jeod::MessageHandler::error(), jeod::JeodSimulationInterface::get_checkpoint_reader(), jeod::SimInterfaceMessages::interface_error, jeod::JeodCheckpointable::pre_restart(), jeod::JeodMemoryManager::restart_clear_memory(), and jeod::JeodMemoryManager::restart_reallocate().
Referenced by jeod::BasicJeodTrickSimInterface::restore_allocations().
restore_containers()
void jeod::JeodTrick10MemoryInterface::restore_containers (void) override virtual
Restore the checkpointable objects from the checkpoint file.
Reimplemented from jeod::JeodTrickMemoryInterface.
Definition at line 312 of file trick_memory_interface_chkpnt.cc.
References jeod::SectionedInputStream::activate(), jeod::JeodTrickMemoryInterface::ContainerListEntry::container, jeod::JeodTrickMemoryInterface::container_list, jeod::SectionedInputStream::deactivate(), jeod::MessageHandler::error(), jeod::JeodSimulationInterface::get_checkpoint_reader(), get_container_id(), jeod::SimInterfaceMessages::interface_error, jeod::JeodCheckpointable::perform_restore_action(), and jeod::JeodCheckpointable::post_restart().
Referenced by jeod::BasicJeodTrickSimInterface::restore_containers().
translate_addr_to_name()
std::string jeod::JeodTrick10MemoryInterface::translate_addr_to_name (const void * addr, const ATTRIBUTES * attr) const protected
Translate the given address to an address specification string, with the address interpreted in the context of the supplied attributes.
It is the attributes structure that resolves the A versus A.B versus A.B.C ambiguity.
Note
The attributes structure must be that of a pointer type.
Parameters
addr The address to be translated.
attr The context in which to interpret the address.
Returns
Address specification string, e.g., &foo.bar.baz[42]
Definition at line 156 of file trick_memory_interface_xlate.cc.
References jeod::MessageHandler::error(), jeod::SimInterfaceMessages::interface_error, jeod::JeodTrickMemoryInterface::pointer_attributes(), and trick_checkpoint_agent.
Referenced by get_container_id(), and get_name_at_address().
translate_name_to_addr()
void * jeod::JeodTrick10MemoryInterface::translate_name_to_addr (const std::string & spec) const protected
Translate the given address specification string to an address.
This is the inverse of translate_addr_to_name.
Parameters
spec The address specification to be interpreted.
Returns
Address corresponding to the address specification.
Definition at line 196 of file trick_memory_interface_xlate.cc.
References jeod::MessageHandler::error(), and jeod::SimInterfaceMessages::interface_error.
Referenced by get_address_at_name(), get_container_id(), and get_name_at_address().
Friends And Related Function Documentation
init_attrjeod__JeodTrick10MemoryInterface
void init_attrjeod__JeodTrick10MemoryInterface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 111 of file trick10_memory_interface.hh.
Field Documentation
trick_checkpoint_agent
Trick::ClassicCheckPointAgent* jeod::JeodTrick10MemoryInterface::trick_checkpoint_agent protected
Trick checkpoint agent.
trick_io(**)
Definition at line 183 of file trick10_memory_interface.hh.
Referenced by JeodTrick10MemoryInterface(), and translate_addr_to_name().
The documentation for this class was generated from the following files:
trick10_memory_interface.hh
trick10_memory_interface.cc
trick_memory_interface_chkpnt.cc
trick_memory_interface_xlate.cc