JEOD: jeod::ColorText Class Reference
jeod::ColorText Class Reference
Defines methods that highlight key outputs from a unit test run.
#include <color_text.hh>
Public Types
enum TextColor {
Red = 31, Green = 32, Yellow = 33, Blue = 34,
Magenta = 35, Cyan = 36
}
Enumerates the standard ASCII text colors, sans black and white.
Public Member Functions
ColorText ()
Default constructor.
std::string color (const std::string &text, TextColor color)
Base method used by the other ColorText methods to wrap a chunk of text between an ASCII start color and ASCII restore pair of markers.
std::string pass_fail (bool passed)
Generate a string whose c_str() value is "Passed" or "Failed" sandwiched betweeen an ASCII start color / restore monitor pair.
std::string pass_fail (bool passed, const std::string &text)
Generate a string whose c_str() value is that of the provided text but sandwiched betweeen an ASCII color text/restore monitor pair.
std::string pass_fail (bool passed, const char *format, int number)
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
std::string pass_fail (bool passed, const char *format, double number)
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
std::string pass_fail (const bool passed[3], const char *format, unsigned int nsp1st, unsigned int nspmid, double number[3])
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
std::string pass_fail (const bool passed[3][3], const char *format, unsigned int nsp1st, unsigned int nspmid, double number[3][3])
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
Private Attributes
char ascii_color [7][6]
Array of ascii colors.
char buf [64]
Buffer for internal use.
Detailed Description
Defines methods that highlight key outputs from a unit test run.
Definition at line 64 of file color_text.hh.
Member Enumeration Documentation
TextColor
enum jeod::ColorText::TextColor
Enumerates the standard ASCII text colors, sans black and white.
Enumerator
Red
Red text.
Green
Green text.
Yellow
Yellow text.
Blue
Blue text.
Magenta
Magenta text.
Cyan
Cyan text.
Definition at line 71 of file color_text.hh.
Constructor & Destructor Documentation
ColorText()
jeod::ColorText::ColorText (void) inline
Default constructor.
Definition at line 111 of file color_text.hh.
References ascii_color.
Member Function Documentation
color()
std::string jeod::ColorText::color (const std::string & text, TextColor text_color) inline
Base method used by the other ColorText methods to wrap a chunk of text between an ASCII start color and ASCII restore pair of markers.
Returns
A std::string whose c_str() value is the input text sandwiched between an ASCII start color escape sequence and an ASCII restore color escape sequence
Parameters
[in] text The text to be processed
[in] text_color The color to be applied
Definition at line 134 of file color_text.hh.
References ascii_color.
Referenced by pass_fail().
pass_fail() [1/6]
std::string jeod::ColorText::pass_fail (bool passed) inline
Generate a string whose c_str() value is "Passed" or "Failed" sandwiched betweeen an ASCII start color / restore monitor pair.
The text is "Passed" and the color green if the value of the input flag is true, "Failed" colored red if the input flag is false.
Returns
An ASCII-colored Passed/Failed string
Parameters
[in] passed Pass/fail flag
Definition at line 153 of file color_text.hh.
References color(), Green, and Red.
Referenced by pass_fail().
pass_fail() [2/6]
std::string jeod::ColorText::pass_fail (bool passed, const std::string & text) inline
Generate a string whose c_str() value is that of the provided text but sandwiched betweeen an ASCII color text/restore monitor pair.
The text is colored green if the flag passed is true, red otherwise.
Returns
An ASCII-colored string
Parameters
[in] passed Pass/fail flag
[in] text String
Definition at line 174 of file color_text.hh.
References color(), Green, and Red.
pass_fail() [3/6]
std::string jeod::ColorText::pass_fail (bool passed, const char * format, int number) inline
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
The text is colored green if the passed flag is true, red otherwise.
Returns
An ASCII-colored, c-formatted string
Parameters
[in] passed Pass/fail flag
[in] format C-language sprintf format (e.g. "%d")
[in] number The number to be formatted and colored
Definition at line 192 of file color_text.hh.
References buf, color(), Green, and Red.
pass_fail() [4/6]
std::string jeod::ColorText::pass_fail (bool passed, const char * format, double number) inline
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
The text is colored green if the passed flag is true, red otherwise.
Returns
An ASCII-colored, c-formatted string
Parameters
[in] passed Pass/fail flag
[in] format C-language sprintf format (e.g. "%g" or "%.7f")
[in] number The number to be formatted and colored
Definition at line 212 of file color_text.hh.
References buf, color(), Green, and Red.
pass_fail() [5/6]
std::string jeod::ColorText::pass_fail (const bool passed[3], const char * format, unsigned int nsp1st, unsigned int nspmid, double number[3]) inline
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
The text is colored green if the passed flag is true, red otherwise.
Returns
An ASCII-colored, c-formatted string
Parameters
[in] passed Pass/fail flags
[in] format C-language sprintf format (e.g. "%g" or "%.7f")
[in] nsp1st Number of spaces before first item
[in] nspmid Number of spaces between items
[in] number The vector to be formatted and colored
Definition at line 234 of file color_text.hh.
References buf, color(), Green, and Red.
pass_fail() [6/6]
std::string jeod::ColorText::pass_fail (const bool passed[3][3], const char * format, unsigned int nsp1st, unsigned int nspmid, double number[3][3]) inline
Generate a string whose c_str() value is the number as formatted per the format string but sandwiched betweeen an ASCII color text/restore monitor pair.
The text is colored green if the passed flag is true, red otherwise.
Returns
An ASCII-colored, c-formatted string
Parameters
[in] passed Pass/fail flags
[in] format C-language sprintf format (e.g. "%g" or "%.7f")
[in] nsp1st Number of spaces before first item
[in] nspmid Number of spaces between items
[in] number The matrix to be formatted and colored
Definition at line 271 of file color_text.hh.
References pass_fail().
Field Documentation
ascii_color
char jeod::ColorText::ascii_color[7][6] private
Array of ascii colors.
trick_units(–)
Definition at line 99 of file color_text.hh.
Referenced by color(), and ColorText().
buf
char jeod::ColorText::buf[64] private
Buffer for internal use.
trick_units(–)
Definition at line 103 of file color_text.hh.
Referenced by pass_fail().
The documentation for this class was generated from the following file:
color_text.hh