JEOD: jeod::RefFrameManager Class Reference
jeod::RefFrameManager Class Reference
The RefFrameManager class manages the reference frames in a simulation.
#include <ref_frame_manager.hh>
Public Member Functions
RefFrameManager ()
RefFrameManager default constructor.
~RefFrameManager () override
RefFrameManager destructor.
void add_ref_frame (RefFrame &ref_frame) override
Add a reference frame to the reference frame registry.
void remove_ref_frame (RefFrame &ref_frame) override
Remove a reference frame from the reference frame registry.
RefFrame * find_ref_frame (const char *name) const override
Find the reference frame with the given name.
RefFrame * find_ref_frame (const char *prefix, const char *suffix) const override
Find the reference frame with the dot-conjoined name "${prefix}.${suffix}".
void check_ref_frame_ownership (void) const override
Check that each active reference frame has an owner.
void reset_tree_root_node () override
Reset the root node in anticipation of rebuilding the entire tree.
void add_frame_to_tree (RefFrame &ref_frame, RefFrame *parent) override
Insert a reference frame in the reference frame tree.
void subscribe_to_frame (const char *frame_name) override
Subscribe to a reference frame, with the frame specified by name.
void subscribe_to_frame (RefFrame &frame) override
Subscribe to a reference frame, with the frame specified as an argument.
void unsubscribe_to_frame (const char *frame_name) override
Remove subscription to a reference frame, with the frame specified by name.
void unsubscribe_to_frame (RefFrame &frame) override
Remove subscription to a reference frame, with the frame specified as an argument.
bool frame_is_subscribed (const char *frame_name) override
Checks whether frame has subscribers; frame specified by name.
bool frame_is_subscribed (RefFrame &frame) override
Checks whether frame has subscribers; frame provided as an argument.
Public Member Functions inherited from jeod::BaseRefFrameManager
virtual ~BaseRefFrameManager ()
Destructor.
Protected Member Functions
bool validate_name (const char *file, unsigned int line, const char *variable_value, const char *variable_type, const char *variable_name) const
Check whether a name is trivially valid/invalid.
Protected Attributes
RefFrame * root_node
The root node of the reference frame tree.
JeodPointerVector< RefFrame >::type ref_frames
List of reference frames.
Private Member Functions
RefFrameManager (const RefFrameManager &)
Not implemented.
RefFrameManager & operator= (const RefFrameManager &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__RefFrameManager ()
Detailed Description
The RefFrameManager class manages the reference frames in a simulation.
This class is the base class for the EphemeridesManager and DynManager classes. Those derived classes add functionality to this class.
Definition at line 88 of file ref_frame_manager.hh.
Constructor & Destructor Documentation
RefFrameManager() [1/2]
jeod::RefFrameManager::RefFrameManager (void)
RefFrameManager default constructor.
Definition at line 45 of file ref_frame_manager.cc.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and ref_frames.
~RefFrameManager()
jeod::RefFrameManager::~RefFrameManager (void) override
RefFrameManager destructor.
Definition at line 61 of file ref_frame_manager.cc.
References JEOD_DEREGISTER_CHECKPOINTABLE, and ref_frames.
RefFrameManager() [2/2]
jeod::RefFrameManager::RefFrameManager (const RefFrameManager &) private
Not implemented.
Member Function Documentation
add_frame_to_tree()
void jeod::RefFrameManager::add_frame_to_tree (RefFrame & ref_frame, RefFrame * parent) override virtual
Insert a reference frame in the reference frame tree.
Parameters
ref_frame Reference frame to be added to the ref frame tree.
parent Parent frame
Implements jeod::BaseRefFrameManager.
Definition at line 242 of file ref_frame_manager.cc.
References jeod::RefFrame::add_child(), jeod::RefFrame::make_root(), and root_node.
Referenced by jeod::SpiceEphemeris::add_descendants_r(), jeod::SpiceEphemeris::ephem_build_tree(), jeod::EmptySpaceEphemeris::ephem_build_tree(), jeod::De4xxEphemeris::ephem_build_tree(), jeod::SinglePlanetEphemeris::ephem_build_tree(), and jeod::PropagatedPlanet::ephem_build_tree().
add_ref_frame()
void jeod::RefFrameManager::add_ref_frame (RefFrame & ref_frame) override virtual
Add a reference frame to the reference frame registry.
Parameters
ref_frame Reference frame to be added.
Implements jeod::BaseRefFrameManager.
Definition at line 78 of file ref_frame_manager.cc.
References jeod::RefFrameMessages::duplicate_entry, jeod::MessageHandler::error(), find_ref_frame(), jeod::RefFrame::get_name(), ref_frames, and validate_name().
Referenced by jeod::EphemeridesManager::add_ref_frame().
check_ref_frame_ownership()
void jeod::RefFrameManager::check_ref_frame_ownership (void) const override virtual
Check that each active reference frame has an owner.
Implements jeod::BaseRefFrameManager.
Definition at line 206 of file ref_frame_manager.cc.
References jeod::RefFrame::get_name(), jeod::RefFrame::get_owner(), jeod::RefFrameMessages::inconsistent_setup, jeod::Subscription::is_active(), ref_frames, and jeod::MessageHandler::warn().
Referenced by jeod::DynManager::initialize_simulation().
find_ref_frame() [1/2]
RefFrame * jeod::RefFrameManager::find_ref_frame (const char * name) const override virtual
Find the reference frame with the given name.
Parameters
name Reference frame name
Returns
Found reference frame, or NULL if not found
Implements jeod::BaseRefFrameManager.
Definition at line 146 of file ref_frame_manager.cc.
References jeod::RefFrame::get_name(), and ref_frames.
Referenced by jeod::SpiceEphemeris::add_barycenter(), jeod::EphemeridesManager::add_ephem_item(), add_ref_frame(), jeod::DynBodyInit::find_ref_frame(), frame_is_subscribed(), jeod::LvlhFrame::initialize(), jeod::RelativeDerivedState::initialize(), jeod::DynBodyInitOrbit::initialize(), jeod::De4xxEphemeris::initialize_items(), subscribe_to_frame(), and unsubscribe_to_frame().
find_ref_frame() [2/2]
RefFrame * jeod::RefFrameManager::find_ref_frame (const char * prefix, const char * suffix) const override virtual
Find the reference frame with the dot-conjoined name "${prefix}.${suffix}".
Parameters
prefix Reference frame name prefix
suffix Reference frame name suffix
Returns
Found reference frame, or NULL if not found
Implements jeod::BaseRefFrameManager.
Definition at line 175 of file ref_frame_manager.cc.
References jeod::RefFrame::get_name(), and ref_frames.
frame_is_subscribed() [1/2]
bool jeod::RefFrameManager::frame_is_subscribed (const char * frame_name) override virtual
Checks whether frame has subscribers; frame specified by name.
Parameters
frame_name Name of reference frame
Returns
True if the frame has subscribers; false otherwise.
Implements jeod::BaseRefFrameManager.
Definition at line 381 of file ref_frame_manager.cc.
References jeod::MessageHandler::error(), find_ref_frame(), jeod::RefFrameMessages::invalid_name, and validate_name().
frame_is_subscribed() [2/2]
bool jeod::RefFrameManager::frame_is_subscribed (RefFrame & frame) override virtual
Checks whether frame has subscribers; frame provided as an argument.
Parameters
frame The reference frame
Returns
True if the frame has subscribers; false otherwise.
Implements jeod::BaseRefFrameManager.
Definition at line 412 of file ref_frame_manager.cc.
References jeod::Subscription::subscriptions().
operator=()
RefFrameManager& jeod::RefFrameManager::operator= (const RefFrameManager &) private
Not implemented.
remove_ref_frame()
void jeod::RefFrameManager::remove_ref_frame (RefFrame & ref_frame) override virtual
Remove a reference frame from the reference frame registry.
Parameters
ref_frame Reference frame to be removed.
Implements jeod::BaseRefFrameManager.
Definition at line 122 of file ref_frame_manager.cc.
References jeod::MessageHandler::error(), jeod::RefFrame::get_name(), ref_frames, and jeod::RefFrameMessages::removal_failed.
Referenced by jeod::LvlhDerivedState::~LvlhDerivedState(), and jeod::LvlhFrame::~LvlhFrame().
reset_tree_root_node()
void jeod::RefFrameManager::reset_tree_root_node (void) override virtual
Reset the root node in anticipation of rebuilding the entire tree.
Implements jeod::BaseRefFrameManager.
Definition at line 229 of file ref_frame_manager.cc.
References root_node.
Referenced by jeod::EphemeridesManager::activate_ephemerides().
subscribe_to_frame() [1/2]
void jeod::RefFrameManager::subscribe_to_frame (const char * frame_name) override virtual
Subscribe to a reference frame, with the frame specified by name.
Assumptions and limitations:
A subscriber should not double-subscribe to a frame.
Parameters
frame_name Name of reference frame
Implements jeod::BaseRefFrameManager.
Definition at line 275 of file ref_frame_manager.cc.
References jeod::MessageHandler::error(), find_ref_frame(), jeod::RefFrameMessages::invalid_name, and validate_name().
Referenced by jeod::DynBodyFrameSwitch::initialize(), jeod::EarthLighting::initialize(), jeod::RadiationSource::initialize(), jeod::DynBodyInit::initialize(), jeod::RadiationThirdBody::initialize(), and jeod::RadiationPressure::set_third_body_active().
subscribe_to_frame() [2/2]
void jeod::RefFrameManager::subscribe_to_frame (RefFrame & frame) override virtual
Subscribe to a reference frame, with the frame specified as an argument.
Assumptions and limitations:
A subscriber should not double-subscribe to a frame.
Parameters
frame The reference frame to be subscribed to.
Implements jeod::BaseRefFrameManager.
Definition at line 310 of file ref_frame_manager.cc.
References jeod::Subscription::subscribe().
unsubscribe_to_frame() [1/2]
void jeod::RefFrameManager::unsubscribe_to_frame (const char * frame_name) override virtual
Remove subscription to a reference frame, with the frame specified by name.
Assumptions and limitations:
The caller is subscribed to the frame.
Parameters
frame_name Name of reference frame
Implements jeod::BaseRefFrameManager.
Definition at line 326 of file ref_frame_manager.cc.
References jeod::MessageHandler::error(), find_ref_frame(), jeod::RefFrameMessages::invalid_name, and validate_name().
Referenced by jeod::DynBodyInit::apply(), and jeod::RadiationPressure::set_third_body_inactive().
unsubscribe_to_frame() [2/2]
void jeod::RefFrameManager::unsubscribe_to_frame (RefFrame & frame) override virtual
Remove subscription to a reference frame, with the frame specified as an argument.
Assumptions and limitations:
The caller is subscribed to the frame.
Parameters
frame The reference frame
Implements jeod::BaseRefFrameManager.
Definition at line 361 of file ref_frame_manager.cc.
References jeod::MessageHandler::error(), jeod::RefFrame::get_name(), jeod::RefFrameMessages::invalid_item, jeod::Subscription::subscriptions(), and jeod::Subscription::unsubscribe().
validate_name()
bool jeod::RefFrameManager::validate_name (const char * file, unsigned int line, const char * variable_value, const char * variable_type, const char * variable_name) const protected
Check whether a name is trivially valid/invalid.
Parameters
file Usually FILE
line Usually LINE
variable_value Value to check
variable_type Variable description
variable_name Variable name
Returns
True if the name is valid, false if invalid.
Definition at line 434 of file ref_frame_manager.cc.
References jeod::MessageHandler::error(), jeod::RefFrameMessages::invalid_name, and jeod::RefFrameMessages::null_pointer.
Referenced by jeod::DynManager::add_dyn_body(), jeod::EphemeridesManager::add_ephem_item(), jeod::DynManager::add_mass_body(), jeod::EphemeridesManager::add_planet(), add_ref_frame(), jeod::DynManager::find_dyn_body(), jeod::DynManager::find_mass_body(), frame_is_subscribed(), subscribe_to_frame(), and unsubscribe_to_frame().
Friends And Related Function Documentation
init_attrjeod__RefFrameManager
void init_attrjeod__RefFrameManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file ref_frame_manager.hh.
Field Documentation
ref_frames
JeodPointerVector<RefFrame>::type jeod::RefFrameManager::ref_frames protected
List of reference frames.
trick_io(**)
Definition at line 167 of file ref_frame_manager.hh.
Referenced by add_ref_frame(), check_ref_frame_ownership(), find_ref_frame(), RefFrameManager(), remove_ref_frame(), and ~RefFrameManager().
root_node
RefFrame* jeod::RefFrameManager::root_node protected
The root node of the reference frame tree.
This reference frame is the true inertial frame of the simulation.trick_units(–)
Definition at line 162 of file ref_frame_manager.hh.
Referenced by add_frame_to_tree(), and reset_tree_root_node().
The documentation for this class was generated from the following files:
ref_frame_manager.hh
ref_frame_manager.cc