/* Autogenerated from environment/RNP/RNPJ2000/data/rnp_j2000.d */

/*
PURPOSE:
    (Earth inertial to planet fixed, RNP, matrix parameter initialization.)

REFERENCE:
    (((Mulcihy, David D. and Bond, Victor R.)
      (The RNP Routine for the Standard Epoch J2000)
      (NASA:JSC-24574) (NASA Engineering Directorate, Navigation, Control,
       and Aeronautics Division) (September 1990) ())))

ASSUMPTIONS AND LIMITATIONS:
    ((Earth specific)
     (Earth rotation rate is taken from GEM-T1 gravity model))


*/

class RNPJ2000;
#define JEOD_FRIEND_CLASS RNPJ2000_rnp_j2000_default_data

// JEOD includes
#include "environment/RNP/GenericRNP/include/planet_rnp.hh"
#include "environment/RNP/RNPJ2000/include/rnp_j2000.hh"
#include "utils/named_item/include/named_item.hh"
#include "utils/ref_frames/include/ref_frame_interface.hh"

// Unsupported includes
#include "../include/rnp_j2000.hh"

//! Namespace jeod
namespace jeod
{

void RNPJ2000_rnp_j2000_default_data::initialize(RNPJ2000 * RNPJ2000_ptr)
{
    RNPJ2000_ptr->name = "Earth";
    RNPJ2000_ptr->rnp_type = PlanetRNP::FullRNP;
    RNPJ2000_ptr->enable_polar = true;
    RNPJ2000_ptr->planet_omega = 7.292115146706388e-5;
    /* FROM GEM-T1 Gravity model */
}
} // namespace jeod
