JEOD: jeod::LineContactPair Class Reference
jeod::LineContactPair Class Reference
An point to point contact pair for use in the contact model.
#include <line_contact_pair.hh>
Public Member Functions
LineContactPair ()
Default Constructor.
~LineContactPair () override
Destructor.
void in_contact () override
Determine if contact has occurred between the facets of the pair.
void initialize_pair (ContactFacet *subject_facet, ContactFacet *target_facet) override
Initialize the contact pair by setting the subject, target, and creating the relstate if possible.
Public Member Functions inherited from jeod::ContactPair
ContactPair ()
Default Constructor.
virtual ~ContactPair ()
Destructor.
bool in_range ()
test whether the pair is in range for interaction
bool is_active ()
Determine if contact can occur between the two facets.
bool is_complete (void)
Determine if the pair has a target facet.
ContactFacet * get_subject (void)
Determine if the pair has a target facet.
ContactFacet * get_target (void)
Determine if the pair has a target facet.
virtual void initialize_relstate (DynManager *dyn_manager)
Initialize the relative state between the facets and register with the dynamics manager.
virtual bool check_tree ()
Make sure the two contact facets are not on the same mass tree.
Data Fields
LineContactFacet * line_subject
pointer to the contact facet that is the subject of the associated relative states.
LineContactFacet * line_target
pointer to the contact facet that is the target of the associated relative states.
Data Fields inherited from jeod::ContactPair
PairInteraction * interaction
Parameters that define the force calculation function between the subjec and target.
double interaction_distance
rel_state distance at which in_contact should be called
Private Member Functions
LineContactPair & operator= (const LineContactPair &rhs)
LineContactPair (const LineContactPair &rhs)
Friends
class InputProcessor
void init_attrjeod__LineContactPair ()
Additional Inherited Members
Protected Attributes inherited from jeod::ContactPair
RelativeDerivedState rel_state
Current relative state between the subject and the target in the subject frame.
ContactFacet * subject
pointer to the contact facet that is the subject of the associated relative states.
ContactFacet * target
pointer to the contact facet that is the target of the associated relative states.
Detailed Description
An point to point contact pair for use in the contact model.
Definition at line 83 of file line_contact_pair.hh.
Constructor & Destructor Documentation
LineContactPair() [1/2]
jeod::LineContactPair::LineContactPair (void)
Default Constructor.
Definition at line 47 of file line_contact_pair.cc.
~LineContactPair()
jeod::LineContactPair::~LineContactPair (void) override
Destructor.
Definition at line 60 of file line_contact_pair.cc.
LineContactPair() [2/2]
jeod::LineContactPair::LineContactPair (const LineContactPair & rhs) private
Member Function Documentation
in_contact()
void jeod::LineContactPair::in_contact (void) override virtual
Determine if contact has occurred between the facets of the pair.
Implements jeod::ContactPair.
Definition at line 70 of file line_contact_pair.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::LineContactFacet::calculate_contact_point(), jeod::PairInteraction::calculate_forces(), jeod::PointContactFacet::contact_point, jeod::Vector3::copy(), jeod::Vector3::cross(), jeod::Vector3::diff(), jeod::ContactUtils::dist_line_segments(), jeod::Vector3::initialize(), jeod::ContactPair::interaction, jeod::LineContactFacet::length, line_subject, line_target, jeod::RefFrameTrans::position, jeod::RelativeDerivedState::rel_state, jeod::ContactPair::rel_state, jeod::RefFrameState::rot, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::RefFrameTrans::velocity, and jeod::Vector3::vmag().
initialize_pair()
void jeod::LineContactPair::initialize_pair (ContactFacet * subject_facet, ContactFacet * target_facet) override virtual
Initialize the contact pair by setting the subject, target, and creating the relstate if possible.
Parameters
[in,out] subject_facet subject ContactFacet
[in,out] target_facet target ContactFacet
Implements jeod::ContactPair.
Definition at line 172 of file line_contact_pair.cc.
References jeod::InteractionFacet::base_facet, jeod::RelativeDerivedState::ComputeTargetStateinSubject, jeod::NamedItem::construct_name_string(), jeod::ContactUtils::copy_const_char_to_char(), jeod::RelativeDerivedState::direction_sense, jeod::RefFrame::get_name(), line_subject, line_target, jeod::RelativeDerivedState::name, jeod::Facet::name, jeod::ContactPair::rel_state, jeod::ContactPair::subject, jeod::RelativeDerivedState::subject_frame_name, jeod::ContactPair::target, jeod::RelativeDerivedState::target_frame_name, and jeod::ContactFacet::vehicle_point.
Referenced by jeod::LineContactFacet::create_pair().
operator=()
LineContactPair& jeod::LineContactPair::operator= (const LineContactPair & rhs) private
Friends And Related Function Documentation
init_attrjeod__LineContactPair
void init_attrjeod__LineContactPair () friend
InputProcessor
friend class InputProcessor friend
Definition at line 85 of file line_contact_pair.hh.
Field Documentation
line_subject
LineContactFacet* jeod::LineContactPair::line_subject
pointer to the contact facet that is the subject of the associated relative states.
trick_units(–)
Definition at line 91 of file line_contact_pair.hh.
Referenced by in_contact(), and initialize_pair().
line_target
LineContactFacet* jeod::LineContactPair::line_target
pointer to the contact facet that is the target of the associated relative states.
trick_units(–)
Definition at line 96 of file line_contact_pair.hh.
Referenced by in_contact(), and initialize_pair().
The documentation for this class was generated from the following files:
line_contact_pair.hh
line_contact_pair.cc