JEOD: jeod::JeodIntegrationTime Class Reference
jeod::JeodIntegrationTime Class Reference abstract
The class JeodIntegrationTime adds the concepts of timestamping and notification of changes in the nature of time to the ER7 numerical utilities TimeInterface class.
#include <jeod_integration_time.hh>
Public Member Functions
JeodIntegrationTime ()
JeodIntegrationTime constructor.
~JeodIntegrationTime () override
JeodIntegrationTime destructor.
JeodIntegrationTime (const JeodIntegrationTime &)=delete
JeodIntegrationTime & operator= (const JeodIntegrationTime &)=delete
virtual double get_timestamp_time () const =0
Get the time used to timestamp some object.
void add_time_change_subscriber (TimeChangeSubscriber &subscriber)
Add a time change subscriber.
void remove_time_change_subscriber (TimeChangeSubscriber &subscriber)
Remove a time change subscriber.
Protected Member Functions
void notify_time_change_subscribers ()
Notify subscribers that the nature of time has changed.
Private Attributes
JeodPointerVector< TimeChangeSubscriber >::type time_change_subscribers
List of pointers to objects that wish to be notified of a change in the nature of time.
Friends
class InputProcessor
void init_attrjeod__JeodIntegrationTime ()
Detailed Description
The class JeodIntegrationTime adds the concepts of timestamping and notification of changes in the nature of time to the ER7 numerical utilities TimeInterface class.
Definition at line 84 of file jeod_integration_time.hh.
Constructor & Destructor Documentation
JeodIntegrationTime() [1/2]
jeod::JeodIntegrationTime::JeodIntegrationTime ()
JeodIntegrationTime constructor.
Definition at line 45 of file jeod_integration_time.cc.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and time_change_subscribers.
~JeodIntegrationTime()
jeod::JeodIntegrationTime::~JeodIntegrationTime () override
JeodIntegrationTime destructor.
Definition at line 57 of file jeod_integration_time.cc.
References JEOD_DEREGISTER_CHECKPOINTABLE, and time_change_subscribers.
JeodIntegrationTime() [2/2]
jeod::JeodIntegrationTime::JeodIntegrationTime (const JeodIntegrationTime &) delete
Member Function Documentation
add_time_change_subscriber()
void jeod::JeodIntegrationTime::add_time_change_subscriber (TimeChangeSubscriber & subscriber)
Add a time change subscriber.
Parameters
subscriber Object to be added to list of subscribers.
Definition at line 68 of file jeod_integration_time.cc.
References jeod::MessageHandler::error(), jeod::IntegrationMessages::invalid_request, and time_change_subscribers.
Referenced by jeod::JeodIntegrationGroup::JeodIntegrationGroup().
get_timestamp_time()
virtual double jeod::JeodIntegrationTime::get_timestamp_time () const pure virtual
Get the time used to timestamp some object.
Implemented in jeod::TimeManager.
Referenced by jeod::DynBody::update_integrated_state().
notify_time_change_subscribers()
void jeod::JeodIntegrationTime::notify_time_change_subscribers () protected
Notify subscribers that the nature of time has changed.
Definition at line 108 of file jeod_integration_time.cc.
References time_change_subscribers.
Referenced by jeod::TimeManager::update().
operator=()
JeodIntegrationTime& jeod::JeodIntegrationTime::operator= (const JeodIntegrationTime &) delete
remove_time_change_subscriber()
void jeod::JeodIntegrationTime::remove_time_change_subscriber (TimeChangeSubscriber & subscriber)
Remove a time change subscriber.
Parameters
subscriber Object to be removed from list of subscribers.
Definition at line 88 of file jeod_integration_time.cc.
References jeod::IntegrationMessages::invalid_request, time_change_subscribers, and jeod::MessageHandler::warn().
Referenced by jeod::JeodIntegrationGroup::~JeodIntegrationGroup().
Friends And Related Function Documentation
init_attrjeod__JeodIntegrationTime
void init_attrjeod__JeodIntegrationTime () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file jeod_integration_time.hh.
Field Documentation
time_change_subscribers
JeodPointerVector<TimeChangeSubscriber>::type jeod::JeodIntegrationTime::time_change_subscribers private
List of pointers to objects that wish to be notified of a change in the nature of time.
trick_io(**)
Definition at line 116 of file jeod_integration_time.hh.
Referenced by add_time_change_subscriber(), JeodIntegrationTime(), notify_time_change_subscribers(), remove_time_change_subscriber(), and ~JeodIntegrationTime().
The documentation for this class was generated from the following files:
jeod_integration_time.hh
jeod_integration_time.cc