JEOD: jeod::RestartableT3SecondOrderODEIntegrator Class Reference
jeod::RestartableT3SecondOrderODEIntegrator Class Reference
A RestartableT3SecondOrderODEIntegrator integrates a second order ODE in three space, d^2x/dt^2 = a(x,t), where x is a three-vector.
#include <restartable_state_integrator.hh>
Public Member Functions
RestartableT3SecondOrderODEIntegrator ()
Default constructor.
~RestartableT3SecondOrderODEIntegrator () override=default
RestartableT3SecondOrderODEIntegrator (const RestartableT3SecondOrderODEIntegrator &)=delete
RestartableT3SecondOrderODEIntegrator & operator= (const RestartableT3SecondOrderODEIntegrator &)=delete
void create_integrator (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls)
Create the integrator to be managed.
void destroy_integrator ()
Destroy the integrator.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage, const double *accel, double *velocity, double *position)
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
void reset_integrator ()
Tell the integrator to reset itself.
void simple_restore () override
Restore the integrator on restart.
Public Member Functions inherited from jeod::SimpleCheckpointable
SimpleCheckpointable ()=default
Construct a SimpleCheckpointable object.
~SimpleCheckpointable () override=default
Destruct a SimpleCheckpointable object.
const std::string get_init_name () override
Return the name of the initial restart action, in this case "restore".
const std::string get_item_name () override
Return the name of the current restart action, in this case "".
const std::string get_item_value () override
Return the value of the current restart action, in this case "".
void start_checkpoint () override
In general, start the checkpoint process.
void advance_checkpoint () override
In general, advance to the next checkpoint item; in this case, do nothing.
bool is_checkpoint_finished () override
In general, indicate when checkpointing is complete.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
In general, respond to the actions recorded in the checkpoint file.
SimpleCheckpointable (const SimpleCheckpointable &)=delete
SimpleCheckpointable & operator= (const SimpleCheckpointable &)=delete
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()=default
virtual ~JeodCheckpointable ()=default
JeodCheckpointable (const JeodCheckpointable &)=delete
JeodCheckpointable & operator= (const JeodCheckpointable &)=delete
virtual void pre_checkpoint ()
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint ()
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart ()
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart ()
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value ()
In general, return the value of the initialization action.
virtual const std::string get_final_name ()
In general, return the name of the finalization action.
virtual const std::string get_final_value ()
In general, return the value of the finalization action.
Private Attributes
er7_utils::SecondOrderODEIntegrator * integrator {}
Pointer to the object that performs integration.
RestartableSimpleSecondOrderODEIntegrator< 3 > integrator_manager
Object that creates and manages the integrator object.
Friends
class InputProcessor
void init_attrjeod__RestartableT3SecondOrderODEIntegrator ()
Additional Inherited Members
Detailed Description
A RestartableT3SecondOrderODEIntegrator integrates a second order ODE in three space, d^2x/dt^2 = a(x,t), where x is a three-vector.
Definition at line 184 of file restartable_state_integrator.hh.
Constructor & Destructor Documentation
RestartableT3SecondOrderODEIntegrator() [1/2]
jeod::RestartableT3SecondOrderODEIntegrator::RestartableT3SecondOrderODEIntegrator () inline
Default constructor.
Definition at line 190 of file restartable_state_integrator.hh.
References JEOD_REGISTER_CLASS.
~RestartableT3SecondOrderODEIntegrator()
jeod::RestartableT3SecondOrderODEIntegrator::~RestartableT3SecondOrderODEIntegrator () override default
RestartableT3SecondOrderODEIntegrator() [2/2]
jeod::RestartableT3SecondOrderODEIntegrator::RestartableT3SecondOrderODEIntegrator (const RestartableT3SecondOrderODEIntegrator &) delete
Member Function Documentation
create_integrator()
void jeod::RestartableT3SecondOrderODEIntegrator::create_integrator (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls) inline
Create the integrator to be managed.
Parameters
[in] generator Integrator constructor used to create the integrator.
[in,out] controls Integration controls to be passed to the generator.
Definition at line 205 of file restartable_state_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::create_integrator(), and integrator_manager.
Referenced by jeod::DynBody::create_body_integrators().
destroy_integrator()
void jeod::RestartableT3SecondOrderODEIntegrator::destroy_integrator () inline
Destroy the integrator.
Definition at line 214 of file restartable_state_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::destroy_integrator(), and integrator_manager.
integrate()
er7_utils::IntegratorResult jeod::RestartableT3SecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double * accel, double * velocity, double * position) inline
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
Note that this is a pass-through to the encapsulated integrator object. See er7_utils::SecondOrderODEIntegrator::integrate for details.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] accel Time derivative of the generalized velocity.
[in,out] velocity Generalized velocity vector.
[in,out] position Generalized position vector.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 235 of file restartable_state_integrator.hh.
References integrator.
Referenced by jeod::StructureIntegratedDynBody::trans_integ(), and jeod::DynBody::trans_integ().
operator=()
RestartableT3SecondOrderODEIntegrator& jeod::RestartableT3SecondOrderODEIntegrator::operator= (const RestartableT3SecondOrderODEIntegrator &) delete
reset_integrator()
void jeod::RestartableT3SecondOrderODEIntegrator::reset_integrator () inline
Tell the integrator to reset itself.
This should be called when the time step or time direction changes or upon a discrete change in state such docking/undocking. Such events invalidate saved state (if any). The integrator needs to restart from scratch when such events occur.
Definition at line 250 of file restartable_state_integrator.hh.
References integrator.
Referenced by jeod::DynBody::reset_integrators().
simple_restore()
void jeod::RestartableT3SecondOrderODEIntegrator::simple_restore () inline override virtual
Restore the integrator on restart.
Implements jeod::SimpleCheckpointable.
Definition at line 258 of file restartable_state_integrator.hh.
References integrator, integrator_manager, jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference(), and jeod::RestartableStateIntegrator< IntegratorType >::simple_restore().
Friends And Related Function Documentation
init_attrjeod__RestartableT3SecondOrderODEIntegrator
void init_attrjeod__RestartableT3SecondOrderODEIntegrator () friend
InputProcessor
friend class InputProcessor friend
Definition at line 186 of file restartable_state_integrator.hh.
Field Documentation
integrator
er7_utils::SecondOrderODEIntegrator* jeod::RestartableT3SecondOrderODEIntegrator::integrator {} private
Pointer to the object that performs integration.
The object is created managed by the integrator manager.trick_units(–)
Definition at line 269 of file restartable_state_integrator.hh.
Referenced by integrate(), reset_integrator(), and simple_restore().
integrator_manager
RestartableSimpleSecondOrderODEIntegrator<3> jeod::RestartableT3SecondOrderODEIntegrator::integrator_manager private
Object that creates and manages the integrator object.
trick_io(**)
Definition at line 274 of file restartable_state_integrator.hh.
Referenced by create_integrator(), destroy_integrator(), and simple_restore().
The documentation for this class was generated from the following file:
restartable_state_integrator.hh