JEOD: jeod::TimeManager Class Reference
jeod::TimeManager Class Reference
To manage the various time representations and the converters between them throughout the simulation.
#include <time_manager.hh>
Public Member Functions
TimeManager ()
Construct a TimeManager.
~TimeManager () override
Destroy a TimeManager.
void initialize (TimeManagerInit *time_manager_init)
initializes the time manager
int time_lookup (const std::string &name) const
Uses a string comparison to find where in the TimeManager record a time type of a particular name is located.
bool get_time_change_flag () const
Returns the boolean value time_change_flag.
JeodBaseTime * get_time_ptr (const std::string &name) const
Return a pointer to the Time object with the provided name, or NULL if no such Time object has been registered.
JeodBaseTime * get_time_ptr (const int index) const
Return a pointer to the Time object with the provided index, or NULL if no such Time object has been registered.
TimeConverter * get_converter_ptr (const int index) const
Return a pointer to the TimeConverter object with the provided index, or NULL if no such TimeConverter object has been registered.
bool time_standards_exist (void)
Tests for the existence in the registry of time types that inherit from TimeStandard.
virtual void update (double time)
This function manages the time update process.
void verify_table_lookup_ends (void)
This function is called when the simulation reverses direction (in time.
void register_time (JeodBaseTime &time_ref)
Registers the time representation with the Time Manager.
void register_time_named (JeodBaseTime &time_ref, const std::string &name)
Reassigns the name to the type; this is used when there are multiple instances of a time type such as a MET or UDE.
void register_converter (TimeConverter &converter_ref, const std::string &name_a="", const std::string &name_b="")
Registers the time converters with the Time Manager.
JeodIntegrationTime & get_jeod_integration_time ()
Expose the private inheritance from JeodIntegrationTime.
double get_time_scale_factor () const override
Returns the scale factor from sim time to dynamic time.
double get_timestamp_time () const override
Returns the time used to timestamp objects, currently dynamic time seconds.
void add_time_change_subscriber (TimeChangeSubscriber &subscriber)
Add a time change subscriber.
void remove_time_change_subscriber (TimeChangeSubscriber &subscriber)
Remove a time change subscriber.
Data Fields
double simtime
Simulation time (sys.exec.out.time).
TimeDyn dyn_time
The instance of TimeDyn, the dynamic time that is used as the integration time.
int num_types
Size of time_types_ptrs vector.
Private Member Functions
void update_time (double time) override
Update each of the representations of time, calling the update functions for each such representation in dependency order.
TimeManager (const TimeManager &)
TimeManager & operator= (const TimeManager &)
Private Member Functions inherited from jeod::JeodIntegrationTime
JeodIntegrationTime ()
JeodIntegrationTime constructor.
~JeodIntegrationTime () override
JeodIntegrationTime destructor.
void add_time_change_subscriber (TimeChangeSubscriber &subscriber)
Add a time change subscriber.
void remove_time_change_subscriber (TimeChangeSubscriber &subscriber)
Remove a time change subscriber.
void notify_time_change_subscribers ()
Notify subscribers that the nature of time has changed.
Private Attributes
bool time_change_flag
Indicates that the dynamic scale factor changed.
std::vector< JeodBaseTime * > time_vector
List of pointers to time-types.
std::vector< TimeConverter * > converter_vector
List of pointers to time-converters.
Friends
class InputProcessor
class TimeManagerInit
void init_attrjeod__TimeManager ()
Detailed Description
To manage the various time representations and the converters between them throughout the simulation.
Definition at line 94 of file time_manager.hh.
Constructor & Destructor Documentation
TimeManager() [1/2]
jeod::TimeManager::TimeManager (void)
Construct a TimeManager.
Definition at line 65 of file time_manager.cc.
References JEOD_REGISTER_CLASS.
~TimeManager()
jeod::TimeManager::~TimeManager (void) override
Destroy a TimeManager.
Definition at line 505 of file time_manager.cc.
References converter_vector, and time_vector.
TimeManager() [2/2]
jeod::TimeManager::TimeManager (const TimeManager &) private
Member Function Documentation
add_time_change_subscriber()
void jeod::JeodIntegrationTime::add_time_change_subscriber
Add a time change subscriber.
Parameters
subscriber Object to be added to list of subscribers.
Definition at line 74 of file jeod_integration_time.cc.
get_converter_ptr()
TimeConverter * jeod::TimeManager::get_converter_ptr (const int index) const
Return a pointer to the TimeConverter object with the provided index, or NULL if no such TimeConverter object has been registered.
Returns
TimeConverter object corresponding to index in the vector of such types.
Parameters
[in] index Index of object
Definition at line 88 of file time_manager.cc.
References converter_vector.
Referenced by jeod::JeodBaseTime::add_type_update(), jeod::TimeUDE::convert_epoch_to_update(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), and jeod::TimeUDE::initialize_initializer_time().
get_jeod_integration_time()
JeodIntegrationTime & jeod::TimeManager::get_jeod_integration_time (void)
Expose the private inheritance from JeodIntegrationTime.
Definition at line 108 of file time_manager.cc.
Referenced by jeod::JeodDynbodyIntegrationLoop::initialize_integ_loop(), and jeod::DynManager::initialize_model_internal().
get_time_change_flag()
bool jeod::TimeManager::get_time_change_flag (void) const
Returns the boolean value time_change_flag.
Returns
time_change_flag
Definition at line 120 of file time_manager.cc.
References time_change_flag.
get_time_ptr() [1/2]
JeodBaseTime * jeod::TimeManager::get_time_ptr (const std::string & name) const
Return a pointer to the Time object with the provided name, or NULL if no such Time object has been registered.
Returns
Time object corresponding to name
Parameters
[in] name Name of time object
Definition at line 162 of file time_manager.cc.
References time_lookup().
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), jeod::JeodBaseTime::add_type_update(), jeod::RNPJ2000::get_dyn_time_ptr(), jeod::RNPMars::get_dyn_time_ptr(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), jeod::TimeUDE::initialize_initializer_time(), jeod::PropagatedPlanet::initialize_model(), jeod::SpiceEphemeris::initialize_time(), jeod::De4xxEphemeris::initialize_time(), jeod::TimeManagerInit::initialize_time_types(), and jeod::TimeUDE::verify_update().
get_time_ptr() [2/2]
JeodBaseTime * jeod::TimeManager::get_time_ptr (const int index) const
Return a pointer to the Time object with the provided index, or NULL if no such Time object has been registered.
Returns
Time object corresponding to name
Parameters
[in] index Name of time object
Definition at line 177 of file time_manager.cc.
References time_vector.
get_time_scale_factor()
double jeod::TimeManager::get_time_scale_factor (void) const override
Returns the scale factor from sim time to dynamic time.
Returns
dyn_time.scale_factor
Definition at line 133 of file time_manager.cc.
References dyn_time, and jeod::TimeDyn::scale_factor.
get_timestamp_time()
double jeod::TimeManager::get_timestamp_time (void) const override virtual
Returns the time used to timestamp objects, currently dynamic time seconds.
Returns
dyn_time.seconds
Implements jeod::JeodIntegrationTime.
Definition at line 147 of file time_manager.cc.
References dyn_time, and jeod::JeodBaseTime::seconds.
initialize()
void jeod::TimeManager::initialize (TimeManagerInit * time_manager_init)
initializes the time manager
Parameters
[in] time_manager_init Initialization parameters
Definition at line 64 of file time_manager__initialize.cc.
References dyn_time, jeod::TimeManagerInit::initialize_manager(), JEOD_REGISTER_INCOMPLETE_CLASS, num_types, register_time(), time_vector, and update().
operator=()
TimeManager& jeod::TimeManager::operator= (const TimeManager &) private
register_converter()
void jeod::TimeManager::register_converter (TimeConverter & conv_ref, const std::string & name_a = "", const std::string & name_b = "")
Registers the time converters with the Time Manager.
Assumptions and Limitations
the input values name_a and name_b will only be used if the converter-type names have not already been set. So registering a Dyn_UDE converter will ignore name_a completely because it is already set.
Parameters
[in,out] conv_ref ref. to converter being registered
[in] name_a name of type-a in the converter
[in] name_b name of type-b in the converter
Definition at line 266 of file time_manager.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::b_name, converter_vector, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::MessageHandler::inform(), and jeod::TimeMessages::redundancy_error.
register_time()
void jeod::TimeManager::register_time (JeodBaseTime & time_ref)
Registers the time representation with the Time Manager.
Records the frequency at which the representation should be updated.
Assumptions and Limitations
None
Parameters
[in,out] time_ref reference to time-type being registered
Definition at line 200 of file time_manager.cc.
References jeod::NamedItem::c_str(), jeod::MessageHandler::inform(), jeod::JeodBaseTime::name, jeod::TimeMessages::redundancy_error, jeod::JeodBaseTime::set_index(), jeod::JeodBaseTime::time_manager, and time_vector.
Referenced by initialize(), and register_time_named().
register_time_named()
void jeod::TimeManager::register_time_named (JeodBaseTime & time_ref, const std::string & name)
Reassigns the name to the type; this is used when there are multiple instances of a time type such as a MET or UDE.
Registers the time representation with the Time Manager. Records the frequency at which the representation should be updated. TODO: check for duplicates
Assumptions and Limitations
None
Parameters
[in,out] time_ref reference to time-type being registered
[in] name name of the instance being registered.
Definition at line 234 of file time_manager.cc.
References jeod::NamedItem::c_str(), jeod::NamedItem::get_name(), jeod::JeodBaseTime::name, register_time(), and jeod::MessageHandler::warn().
remove_time_change_subscriber()
void jeod::JeodIntegrationTime::remove_time_change_subscriber
Remove a time change subscriber.
Parameters
subscriber Object to be removed from list of subscribers.
Definition at line 98 of file jeod_integration_time.cc.
time_lookup()
int jeod::TimeManager::time_lookup (const std::string & name) const
Uses a string comparison to find where in the TimeManager record a time type of a particular name is located.
Returns the integer corresponding to the time type's index in the TimeManager.
Assumptions and Limitations
Rarely used. If the time type address is known, it is easier to access its index "time_type.index" which returns the same result.
Returns
index value of time-type
Parameters
[in] name name of time-type
Definition at line 355 of file time_manager.cc.
References jeod::MessageHandler::fail(), jeod::TimeMessages::invalid_setup_error, and time_vector.
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::JeodBaseTime::add_type_update(), jeod::TimeManagerInit::create_init_tree(), get_time_ptr(), jeod::TimeManagerInit::initialize(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeManagerInit::populate_converter_registry(), jeod::TimeManagerInit::verify_converter_setup(), jeod::TimeUDE::verify_epoch(), jeod::TimeUDE::verify_init(), and jeod::TimeUDE::verify_update().
time_standards_exist()
bool jeod::TimeManager::time_standards_exist (void)
Tests for the existence in the registry of time types that inherit from TimeStandard.
Assumptions and Limitations
None
Returns
true/false
Definition at line 330 of file time_manager.cc.
References time_vector.
Referenced by jeod::TimeDyn::initialize_initializer_time(), and jeod::TimeUDE::initialize_initializer_time().
update()
void jeod::TimeManager::update (double current_simtime) virtual
This function manages the time update process.
It first updates each of the representations of time, calling the update functions for each time representation in dependency order. After updating the representations of time, the function then updates the dynamic time scale factor. Time change subscribers are notified if the scale factor has changed.
Note that by updating first and then checking for a change in the rate/direction of time means that these changes in rate/direction will first take affect on the next call to update_time or update.
Assumptions and Limitations
Derived times must have a parent; this should be defined by the user, or if not, already determined when the update_tree was built
Parameters
[in] current_simtime input time from simulation engine; it always runs forwards and allows for determination of what has and has not already been done.
Units: s
Definition at line 419 of file time_manager.cc.
References jeod::Numerical::compare_exact(), dyn_time, jeod::JeodIntegrationTime::notify_time_change_subscribers(), num_types, simtime, time_change_flag, time_vector, and jeod::TimeDyn::update_offset().
Referenced by jeod::TimeStandard::calendar_update(), initialize(), and jeod::JeodDynbodyIntegrationLoop::set_time_to_loop_start().
update_time()
void jeod::TimeManager::update_time (double current_simtime) override private
Update each of the representations of time, calling the update functions for each such representation in dependency order.
Note that this function only does the first part of the task performed by TimeManager::update. It does not check for changes in the rate/direction of time.
Assumptions and Limitations
Derived times must have a parent; this should be defined by the user, or if not, already determined when the update_tree was built
Parameters
[in] current_simtime input time from simulation engine; it always runs forwards and allows for determination of what has and has not already been done.
Units: s
Definition at line 461 of file time_manager.cc.
References jeod::Numerical::compare_exact(), num_types, simtime, and time_vector.
verify_table_lookup_ends()
void jeod::TimeManager::verify_table_lookup_ends (void)
This function is called when the simulation reverses direction (in time.
It calls each time converter that uses a table lookup to check whether the current time is off the end of the table. This is important because once the off-table-end flag is set, the only reason to unset it is when time reverses direction)
Assumptions and Limitations
None
Definition at line 492 of file time_manager.cc.
References converter_vector.
Referenced by jeod::TimeDyn::update_offset().
Friends And Related Function Documentation
init_attrjeod__TimeManager
void init_attrjeod__TimeManager () friend
InputProcessor
friend class InputProcessor friend
Definition at line 96 of file time_manager.hh.
TimeManagerInit
friend class TimeManagerInit friend
Definition at line 98 of file time_manager.hh.
Field Documentation
converter_vector
std::vector<TimeConverter*> jeod::TimeManager::converter_vector private
List of pointers to time-converters.
Definition at line 136 of file time_manager.hh.
Referenced by get_converter_ptr(), jeod::TimeManagerInit::populate_converter_registry(), register_converter(), verify_table_lookup_ends(), and ~TimeManager().
dyn_time
TimeDyn jeod::TimeManager::dyn_time
The instance of TimeDyn, the dynamic time that is used as the integration time.
trick_units(–)
Definition at line 113 of file time_manager.hh.
Referenced by jeod::TimeConverter_TAI_UTC::convert_a_to_b(), jeod::TimeConverter_TAI_UTC::convert_b_to_a(), get_time_scale_factor(), get_timestamp_time(), initialize(), jeod::TimeManagerInit::initialize(), jeod::TimeConverter_TAI_UTC::initialize_leap_second(), jeod::TimeConverter_TAI_UT1::initialize_tai_to_ut1(), jeod::SpiceEphemeris::initialize_time(), update(), jeod::RNPJ2000::update_axial_rotation(), jeod::RNPMars::update_axial_rotation(), jeod::RNPJ2000::update_rnp(), jeod::RNPMars::update_rnp(), jeod::TimeConverter_TAI_UTC::verify_table_lookup_ends(), and jeod::TimeConverter_TAI_UT1::verify_table_lookup_ends().
num_types
int jeod::TimeManager::num_types
Size of time_types_ptrs vector.
trick_units(–)
Definition at line 118 of file time_manager.hh.
Referenced by jeod::TimeStandard::add_type_initialize(), jeod::TimeUDE::add_type_initialize(), jeod::JeodBaseTime::add_type_update(), jeod::TimeUDE::convert_epoch_to_update(), jeod::TimeManagerInit::create_init_tree(), jeod::TimeManagerInit::create_update_tree(), initialize(), jeod::TimeStandard::initialize_from_parent(), jeod::TimeUDE::initialize_from_parent(), jeod::TimeUDE::initialize_initializer_time(), jeod::TimeManagerInit::initialize_time_types(), jeod::TimeManagerInit::organize_update_list(), jeod::TimeManagerInit::populate_converter_registry(), update(), update_time(), jeod::TimeManagerInit::verify_converter_setup(), and jeod::TimeManagerInit::verify_times_setup().
simtime
double jeod::TimeManager::simtime
Simulation time (sys.exec.out.time).
trick_units(–)
Definition at line 107 of file time_manager.hh.
Referenced by jeod::TimeStandard::calendar_update(), jeod::TimeStandard::seconds_of_year(), jeod::TimeDyn::update(), update(), jeod::TimeDyn::update_offset(), and update_time().
time_change_flag
bool jeod::TimeManager::time_change_flag private
Indicates that the dynamic scale factor changed.
trick_units(–)
Definition at line 126 of file time_manager.hh.
Referenced by get_time_change_flag(), and update().
time_vector
std::vector<JeodBaseTime*> jeod::TimeManager::time_vector private
List of pointers to time-types.
Definition at line 131 of file time_manager.hh.
Referenced by jeod::TimeManagerInit::create_init_tree(), jeod::TimeManagerInit::create_update_tree(), get_time_ptr(), initialize(), jeod::TimeManagerInit::initialize(), jeod::TimeManagerInit::initialize_time_types(), jeod::TimeManagerInit::organize_update_list(), jeod::TimeManagerInit::populate_converter_registry(), register_time(), time_lookup(), time_standards_exist(), update(), update_time(), jeod::TimeManagerInit::verify_times_setup(), and ~TimeManager().
The documentation for this class was generated from the following files:
time_manager.hh
time_manager.cc
time_manager__initialize.cc