JEOD: jeod::EphemerisOrientation Class Reference
jeod::EphemerisOrientation Class Reference
An EphemerisOrientation object updates the rotational state of an ephemeris reference frame.
#include <ephem_orient.hh>
Public Member Functions
EphemerisOrientation ()
Construct an ephemeris angle.
~EphemerisOrientation () override
Destroy an ephemeris angle.
TargetAspect updates_what (void) const override
Specify the aspect of the target frame updated by the object.
void enable () override
Enable a EphemerisItem object.
void note_frame_status_change (RefFrame *frame) override
Null implementation.
const char * default_suffix () const override
Return the default suffix for this item class, i.e., "pfix".
void disconnect_from_tree () override
Disconnect the item from the tree; this is a no-op for an EphemerisOrientation.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()
Construct an ephemeris item.
~EphemerisItem () override
Destroy an ephemeris item.
virtual void set_name (const char *new_name)
Name an ephemeris item.
virtual void set_name (const char *pname, const char *fname)
Name an ephemeris item.
const char * get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp (void) const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item (void) const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const char *new_value, const char *old_value, const char *variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
Protected Attributes
bool subscribed_to_inertial
A subscription to the planet's inertial frame is issued whenever the planet's planet-fixed frame is active to ensure that the the planet-fixed frame is a part of the ref frame tree.
Protected Attributes inherited from jeod::EphemerisItem
char * name
The name of the item.
EphemerisInterface * owner
The ephemeris model that owns this object.
BaseEphemeridesManager * manager
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame
The reference frame whose non-constant state is set by this object.
EphemerisItem * head
The first ephemeris item with the same name as this item.
EphemerisItem * next
The next ephemeris item with the same name as this item.
double update_time
Time of last update, dynamic time seconds.
bool enabled
Is the item enabled?
bool active
Is the item active?
Private Member Functions
EphemerisOrientation (const EphemerisOrientation &)
Not implemented.
EphemerisOrientation & operator= (const EphemerisOrientation &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__EphemerisOrientation ()
Additional Inherited Members
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (char *new_name)
Name an ephemeris item.
Detailed Description
An EphemerisOrientation object updates the rotational state of an ephemeris reference frame.
Definition at line 89 of file ephem_orient.hh.
Constructor & Destructor Documentation
EphemerisOrientation() [1/2]
jeod::EphemerisOrientation::EphemerisOrientation (void)
Construct an ephemeris angle.
Definition at line 59 of file ephem_orient.cc.
~EphemerisOrientation()
jeod::EphemerisOrientation::~EphemerisOrientation (void) override
Destroy an ephemeris angle.
Definition at line 71 of file ephem_orient.cc.
EphemerisOrientation() [2/2]
jeod::EphemerisOrientation::EphemerisOrientation (const EphemerisOrientation &) private
Not implemented.
Member Function Documentation
default_suffix()
const char * jeod::EphemerisOrientation::default_suffix (void) const override virtual
Return the default suffix for this item class, i.e., "pfix".
Returns
Default suffix
Implements jeod::EphemerisItem.
Definition at line 166 of file ephem_orient.cc.
disconnect_from_tree()
void jeod::EphemerisOrientation::disconnect_from_tree (void) override virtual
Disconnect the item from the tree; this is a no-op for an EphemerisOrientation.
Implements jeod::EphemerisItem.
Definition at line 179 of file ephem_orient.cc.
enable()
void jeod::EphemerisOrientation::enable (void) override virtual
Enable a EphemerisItem object.
Reimplemented from jeod::EphemerisItem.
Definition at line 96 of file ephem_orient.cc.
References jeod::EphemerisItem::enable(), jeod::EphemerisItem::enabled, jeod::EphemerisItem::get_enabled_item(), and subscribed_to_inertial.
Referenced by jeod::De4xxEphemeris::De4xxEphemeris(), jeod::PlanetOrientation::initialize(), and jeod::PropagatedPlanet::set_mode().
note_frame_status_change()
void jeod::EphemerisOrientation::note_frame_status_change (RefFrame * frame) override virtual
Null implementation.
Parameters
[in] frame Frame whose status has changed
Reimplemented from jeod::RefFrameOwner.
Definition at line 122 of file ephem_orient.cc.
References jeod::EphemerisItem::activate(), jeod::EphemerisItem::deactivate(), jeod::MessageHandler::error(), jeod::RefFrame::get_parent(), jeod::EphemeridesMessages::internal_error, jeod::Subscription::is_active(), jeod::Subscription::subscribe(), subscribed_to_inertial, jeod::EphemerisItem::target_frame, and jeod::Subscription::unsubscribe().
operator=()
EphemerisOrientation& jeod::EphemerisOrientation::operator= (const EphemerisOrientation &) private
Not implemented.
updates_what()
EphemerisItem::TargetAspect jeod::EphemerisOrientation::updates_what (void) const override virtual
Specify the aspect of the target frame updated by the object.
EphemerisOrientation objects update the rotational state.
Returns
Target of object
Implements jeod::EphemerisItem.
Definition at line 84 of file ephem_orient.cc.
References jeod::EphemerisItem::Rotation.
Friends And Related Function Documentation
init_attrjeod__EphemerisOrientation
void init_attrjeod__EphemerisOrientation () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file ephem_orient.hh.
Field Documentation
subscribed_to_inertial
bool jeod::EphemerisOrientation::subscribed_to_inertial protected
A subscription to the planet's inertial frame is issued whenever the planet's planet-fixed frame is active to ensure that the the planet-fixed frame is a part of the ref frame tree.
This flag is set when such a subscription is made.trick_units(–)
Definition at line 127 of file ephem_orient.hh.
Referenced by enable(), and note_frame_status_change().
The documentation for this class was generated from the following files:
ephem_orient.hh
ephem_orient.cc