JEOD: jeod::DerivedState Class Reference
jeod::DerivedState Class Reference
The base class used for deriving a state representation of some subject DynBody.
#include <derived_state.hh>
Public Member Functions
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
virtual void initialize (DynBody &subject_body, DynManager &dyn_manager)
Begin initialization of a DerivedState.
virtual void update (void)
Update the state.
Data Fields
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Member Functions
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Protected Attributes
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
DerivedState (const DerivedState &)
DerivedState & operator= (const DerivedState &)
Friends
class InputProcessor
void init_attrjeod__DerivedState ()
Detailed Description
The base class used for deriving a state representation of some subject DynBody.
Definition at line 85 of file derived_state.hh.
Constructor & Destructor Documentation
DerivedState() [1/2]
jeod::DerivedState::DerivedState (const DerivedState &) private
DerivedState() [2/2]
jeod::DerivedState::DerivedState (void)
Construct a DerivedState.
Definition at line 56 of file derived_state.cc.
~DerivedState()
jeod::DerivedState::~DerivedState (void) virtual
Destruct a DerivedState.
Definition at line 70 of file derived_state.cc.
References JEOD_DELETE_ARRAY, JEOD_IS_ALLOCATED, reference_name, and state_identifier.
Member Function Documentation
find_planet()
Planet * jeod::DerivedState::find_planet (const DynManager & dyn_manager, const char * planet_name, const char * variable_name) protected
Find the Planet with the given name, failing if not found.
Returns
Found Planet
Parameters
[in] dyn_manager Dynamics manager
[in] planet_name Planet name
[in] variable_name For error reporting
Definition at line 171 of file derived_state.cc.
References jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_planet(), jeod::DerivedStateMessages::invalid_name, state_identifier, and jeod::NamedItem::validate_name().
Referenced by jeod::PlanetaryDerivedState::initialize(), jeod::OrbElemDerivedState::initialize(), jeod::NedDerivedState::initialize(), and jeod::SolarBetaDerivedState::initialize().
initialize()
void jeod::DerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) virtual
Begin initialization of a DerivedState.
The initialize method for all subclasses of DerivedState nust pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Assumptions and Limitations
g++ is being used as the compiler
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented in jeod::RelativeDerivedState, jeod::SolarBetaDerivedState, jeod::NedDerivedState, jeod::OrbElemDerivedState, jeod::EulerDerivedState, jeod::LvlhDerivedState, jeod::PlanetaryDerivedState, and jeod::LvlhRelativeDerivedState.
Definition at line 121 of file derived_state.cc.
References jeod::NamedItem::c_str(), jeod::NamedItem::construct_name(), jeod::NamedItem::demangle(), JEOD_IS_ALLOCATED, JEOD_STRDUP, jeod::DynBody::name, reference_name, state_identifier, and subject.
Referenced by jeod::PlanetaryDerivedState::initialize(), jeod::LvlhDerivedState::initialize(), jeod::EulerDerivedState::initialize(), jeod::OrbElemDerivedState::initialize(), jeod::NedDerivedState::initialize(), jeod::SolarBetaDerivedState::initialize(), and jeod::RelativeDerivedState::initialize().
operator=()
DerivedState& jeod::DerivedState::operator= (const DerivedState &) private
set_reference_name()
void jeod::DerivedState::set_reference_name (const char * new_name)
Set the reference_name to a copy of the supplied value.
Parameters
[in] new_name new name of reference.
Definition at line 90 of file derived_state.cc.
References JEOD_DELETE_ARRAY, JEOD_IS_ALLOCATED, JEOD_STRDUP, and reference_name.
update()
void jeod::DerivedState::update (void) virtual
Update the state.
Reimplemented in jeod::RelativeDerivedState, jeod::SolarBetaDerivedState, jeod::NedDerivedState, jeod::EulerDerivedState, jeod::OrbElemDerivedState, jeod::LvlhDerivedState, jeod::PlanetaryDerivedState, and jeod::LvlhRelativeDerivedState.
Definition at line 148 of file derived_state.cc.
Referenced by jeod::OrbElemDerivedState::update(), and jeod::EulerDerivedState::update().
Friends And Related Function Documentation
init_attrjeod__DerivedState
void init_attrjeod__DerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file derived_state.hh.
Field Documentation
reference_name
char* jeod::DerivedState::reference_name
The name of the object with respect to which the subject state is assessed.
trick_units(–)
Definition at line 103 of file derived_state.hh.
Referenced by jeod::PlanetaryDerivedState::initialize(), jeod::LvlhDerivedState::initialize(), initialize(), jeod::OrbElemDerivedState::initialize(), jeod::NedDerivedState::initialize(), jeod::SolarBetaDerivedState::initialize(), set_reference_name(), and ~DerivedState().
state_identifier
char* jeod::DerivedState::state_identifier protected
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
This is used for generating error and debug messages.trick_units(–)
Definition at line 113 of file derived_state.hh.
Referenced by find_planet(), initialize(), jeod::RelativeDerivedState::initialize(), and ~DerivedState().
subject
DynBody* jeod::DerivedState::subject
The body that is the subject of the derived state.
trick_units(–)
Definition at line 97 of file derived_state.hh.
Referenced by jeod::LvlhDerivedState::initialize(), initialize(), jeod::RelativeDerivedState::initialize(), jeod::PlanetaryDerivedState::update(), jeod::OrbElemDerivedState::update(), jeod::EulerDerivedState::update(), jeod::NedDerivedState::update(), and jeod::SolarBetaDerivedState::update().
The documentation for this class was generated from the following files:
derived_state.hh
derived_state.cc