JEOD: jeod::BodyAction Class Reference
jeod::BodyAction Class Reference
BodyAction is the base class for the BodyAction model.
#include <body_action.hh>
Public Member Functions
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
virtual void initialize (DynManager &dyn_manager)
Begin initialization of a BodyAction.
virtual bool is_ready ()
In general, determine if the initializer is ready to be applied.
virtual void apply (DynManager &dyn_manager)
Complete initialization.
Data Fields
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Member Functions
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Friends
class InputProcessor
void init_attrjeod__BodyAction ()
Detailed Description
BodyAction is the base class for the BodyAction model.
A BodyAction instance that performs some operation on a MassBody object. The simulation Dynamics Manager object manages a collection of BodyAction objects for the purpose of initializing MassBody objects and later, for performing asynchronous actions on them.
The BodyAction model hinges on three methods:
initialize() The initialize() method initializes the BodyAction. This method does not and must not operate on the subject of the action. All derived classes must forward the initialize() call to the immediate parent class and then perform class-dependent object initializations.
is_ready() The is_ready method indicates whether the action is ready to be applied. For example, an action that initializes the translation state of a vehicle relative to some other vehicle cannot do its job until that other vehicle's translational state is set. The is_ready() method for such an action should return false until the other vehicle's translational state has been set.
apply() The apply() method applies the action – it does something to the subject of the action. All derived classes must perform class-dependent actions and then must forward the apply() call to the immediate parent class.
Definition at line 107 of file body_action.hh.
Constructor & Destructor Documentation
BodyAction() [1/2]
jeod::BodyAction::BodyAction () default
~BodyAction()
virtual jeod::BodyAction::~BodyAction () virtual default
BodyAction() [2/2]
jeod::BodyAction::BodyAction (const BodyAction &) delete
Member Function Documentation
apply()
void jeod::BodyAction::apply (DynManager & dyn_manager) virtual
Complete initialization.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented in jeod::DynBodyInitOrbit, jeod::DynBodyInit, jeod::DynBodyFrameSwitch, jeod::BodyAttach, jeod::BodyDetachSpecific, jeod::DynBodyInitPlanetDerived, jeod::DynBodyInitNedState, jeod::DynBodyInitWrtPlanet, jeod::BodyAttachAligned, jeod::BodyReattach, jeod::DynBodyInitLvlhState, jeod::DynBodyInitRotState, jeod::DynBodyInitTransState, jeod::BodyAttachMatrix, jeod::MassBodyInit, and jeod::BodyDetach.
Definition at line 87 of file body_action.cc.
References shutdown().
Referenced by jeod::BodyDetach::apply(), jeod::MassBodyInit::apply(), jeod::BodyReattach::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBodyInit::apply(), jeod::DynManager::perform_actions(), jeod::DynManager::perform_dyn_body_initializations(), jeod::DynManager::perform_mass_attach_initializations(), and jeod::DynManager::perform_mass_body_initializations().
get_identifier()
const std::string & jeod::BodyAction::get_identifier () const inline
Accessor for action_identifier.
Returns
Action identifier
Definition at line 241 of file body_action.hh.
References action_identifier.
get_subject_dyn_body()
DynBody * jeod::BodyAction::get_subject_dyn_body ()
Definition at line 209 of file body_action.cc.
References jeod::MassBody::dyn_owner, dyn_subject, and mass_subject.
Referenced by jeod::DynBodyInitLvlhRotState::initialize().
initialize()
void jeod::BodyAction::initialize (DynManager & dyn_manager) virtual
Begin initialization of a BodyAction.
The initialize method for all subclasses of BodyAction must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented in jeod::DynBodyInitOrbit, jeod::DynBodyInit, jeod::DynBodyFrameSwitch, jeod::BodyAttach, jeod::BodyDetachSpecific, jeod::DynBodyInitPlanetDerived, jeod::DynBodyInitNedState, jeod::DynBodyInitWrtPlanet, jeod::BodyAttachAligned, jeod::DynBodyInitLvlhState, jeod::DynBodyInitRotState, jeod::DynBodyInitTransState, jeod::DynBodyInitLvlhRotState, jeod::DynBodyInitLvlhTransState, jeod::DynBodyInitNedRotState, and jeod::DynBodyInitNedTransState.
Definition at line 66 of file body_action.cc.
References action_identifier, action_name, jeod::NamedItem::demangle(), dyn_subject, mass_subject, and validate_body_inputs().
Referenced by jeod::DynManager::add_body_action(), jeod::BodyDetachSpecific::initialize(), jeod::BodyAttach::initialize(), jeod::DynBodyFrameSwitch::initialize(), jeod::DynBodyInit::initialize(), jeod::DynManager::initialize_dyn_bodies(), jeod::DynManager::perform_mass_attach_initializations(), and jeod::DynManager::perform_mass_body_initializations().
is_ready()
bool jeod::BodyAction::is_ready () virtual
In general, determine if the initializer is ready to be applied.
This base class method simply queries the active flag. Subclasses should override this default method.
Returns
Can initializer run?
Reimplemented in jeod::DynBodyInit, jeod::DynBodyFrameSwitch, jeod::BodyDetachSpecific, jeod::DynBodyInitPlanetDerived, jeod::DynBodyInitRotState, jeod::DynBodyInitTransState, jeod::DynBodyInitWrtPlanet, and jeod::BodyDetach.
Definition at line 101 of file body_action.cc.
References active.
Referenced by jeod::DynBodyFrameSwitch::is_ready(), jeod::DynBodyInit::is_ready(), jeod::DynManager::perform_actions(), jeod::DynManager::perform_dyn_body_initializations(), jeod::DynManager::perform_mass_attach_initializations(), and jeod::DynManager::perform_mass_body_initializations().
is_same_subject_body()
bool jeod::BodyAction::is_same_subject_body (MassBody & mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
Definition at line 181 of file body_action.cc.
References dyn_subject, jeod::DynBody::mass, and mass_subject.
Referenced by jeod::DynManager::perform_dyn_body_initializations(), and jeod::DynManager::perform_mass_body_initializations().
is_subject_dyn_body()
bool jeod::BodyAction::is_subject_dyn_body ()
Check if the subject is a DynBody.
Definition at line 193 of file body_action.cc.
References jeod::MassBody::dyn_owner, dyn_subject, and mass_subject.
operator=()
BodyAction& jeod::BodyAction::operator= (const BodyAction &) delete
set_subject_body() [1/2]
void jeod::BodyAction::set_subject_body (MassBody & mass_body_in)
Set the subject mass body of this action.
Resets dyn_subject to null
Definition at line 106 of file body_action.cc.
References dyn_subject, and mass_subject.
set_subject_body() [2/2]
void jeod::BodyAction::set_subject_body (DynBody & dyn_body_in)
Set the subject dyn body of this action.
Resets mass_subject to null
Definition at line 112 of file body_action.cc.
References dyn_subject, and mass_subject.
shutdown()
void jeod::BodyAction::shutdown () virtual
Release resources allocated by a BodyAction object.
Definition at line 54 of file body_action.cc.
Referenced by apply(), and jeod::DynManager::remove_body_action().
validate_body_inputs()
bool jeod::BodyAction::validate_body_inputs (DynBody *& dyn_body_in, MassBody *& mass_body_in, const std::string & body_base_name, bool allow_failure = false) protected virtual
Definition at line 118 of file body_action.cc.
References action_identifier, jeod::MassBody::dyn_owner, jeod::MessageHandler::fail(), jeod::BodyActionMessages::fatal_error, jeod::DynBody::mass, and jeod::BodyActionMessages::null_pointer.
Referenced by jeod::BodyDetachSpecific::initialize(), jeod::BodyAttach::initialize(), and initialize().
validate_name()
void jeod::BodyAction::validate_name (const std::string & variable_value, const std::string & variable_name, const std::string & variable_type) protected
Ensure that a string is not trivially invalid.
Parameters
[in] variable_value String to be checked
[in] variable_name For error reporting
[in] variable_type For error reporting
Definition at line 231 of file body_action.cc.
References action_identifier, jeod::MessageHandler::fail(), and jeod::BodyActionMessages::invalid_name.
Referenced by jeod::DynBodyInit::find_body_frame(), jeod::DynBodyInit::find_dyn_body(), jeod::DynBodyInit::find_planet(), jeod::DynBodyInit::find_ref_frame(), and jeod::DynBodyInitOrbit::initialize().
Friends And Related Function Documentation
init_attrjeod__BodyAction
void init_attrjeod__BodyAction () friend
InputProcessor
friend class InputProcessor friend
Definition at line 109 of file body_action.hh.
Field Documentation
action_identifier
std::string jeod::BodyAction::action_identifier {""} protected
An identifier for this action, constructed from the class name and the action name at initialization time.
This is used for generating error and debug messages.trick_units(–)
Definition at line 187 of file body_action.hh.
Referenced by jeod::BodyDetach::apply(), jeod::MassBodyInit::apply(), jeod::BodyReattach::apply(), jeod::DynBodyInitNedState::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBodyInit::apply(), jeod::DynBodyInitOrbit::apply(), jeod::DynBodyInit::find_body_frame(), jeod::DynBodyInit::find_dyn_body(), jeod::DynBodyInit::find_planet(), jeod::DynBodyInit::find_ref_frame(), get_identifier(), jeod::DynBodyInitLvlhRotState::initialize(), jeod::DynBodyInitLvlhTransState::initialize(), jeod::DynBodyInitNedRotState::initialize(), jeod::DynBodyInitNedTransState::initialize(), jeod::DynBodyInitTransState::initialize(), jeod::DynBodyInitRotState::initialize(), jeod::BodyAttachAligned::initialize(), jeod::BodyAttach::initialize(), jeod::DynBodyFrameSwitch::initialize(), jeod::DynBodyInit::initialize(), initialize(), jeod::DynBodyInitOrbit::initialize(), jeod::DynBodyInitRotState::is_ready(), jeod::DynBodyInitTransState::is_ready(), jeod::DynBodyInit::report_failure(), validate_body_inputs(), and validate_name().
action_name
std::string jeod::BodyAction::action_name {""}
An identifier for this action.
This can be left as empty (default value). The action_name is used only when an error is detected. The generated error message identifies the action name if supplied. The intent is to generate an error message that helps the user pinpoint the source of the error.trick_units(–)
Definition at line 163 of file body_action.hh.
Referenced by initialize(), and jeod::DynManager::remove_body_action().
active
bool jeod::BodyAction::active {true}
Controls when the action is performed.
The action will be performed when the action is activated via this flag and when all other prerequisites for the action have been satisified. The default value for this flag is class-dependent, set in various constructors. The default is true for actions that can reasonably be performed during initialization time and false for actions that are most likely performed while the simulation is running.trick_units(–)
Definition at line 142 of file body_action.hh.
Referenced by jeod::BodyDetach::BodyDetach(), jeod::BodyDetachSpecific::BodyDetachSpecific(), jeod::BodyReattach::BodyReattach(), jeod::BodyDetach::is_ready(), jeod::BodyDetachSpecific::is_ready(), and is_ready().
dyn_subject
DynBody* jeod::BodyAction::dyn_subject {} protected
The DynBody of the body that is the subject of this action.
This or the subject pointer must be supplied. Actions on the body are performed by the apply methods of specific class derived from the BodyAction class.trick_units(–)
Definition at line 180 of file body_action.hh.
Referenced by jeod::BodyDetach::apply(), jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBodyInit::apply(), jeod::DynBodyInit::apply_user_inputs(), get_subject_dyn_body(), jeod::DynBodyFrameSwitch::initialize(), jeod::DynBodyInit::initialize(), initialize(), jeod::DynBodyFrameSwitch::is_ready(), is_same_subject_body(), is_subject_dyn_body(), and set_subject_body().
mass_subject
MassBody* jeod::BodyAction::mass_subject {} protected
The MassBody of the body that is the subject of this action.
This or the dyn_subject pointer must be supplied. Actions on the body are performed by the apply methods of specific class derived from the BodyAction class.trick_units(–)
Definition at line 172 of file body_action.hh.
Referenced by jeod::BodyDetach::apply(), jeod::MassBodyInit::apply(), jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), jeod::BodyReattach::apply(), jeod::BodyDetachSpecific::apply(), jeod::BodyAttach::apply(), get_subject_dyn_body(), jeod::DynBodyFrameSwitch::initialize(), jeod::DynBodyInit::initialize(), initialize(), is_same_subject_body(), is_subject_dyn_body(), and set_subject_body().
terminate_on_error
bool jeod::BodyAction::terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
Several of the low-level methods used to perform the action do not terminate the simulation on encountering an error condition. They instead leave states unchanged and return an error indicator. This flag, if set, causes the simulation to be terminated when such an error condition occurs. The default value for this flag is true, set in the constructor.trick_units(–)
Definition at line 154 of file body_action.hh.
Referenced by jeod::BodyDetach::apply(), jeod::BodyReattach::apply(), jeod::BodyDetachSpecific::apply(), and jeod::BodyAttach::apply().
The documentation for this class was generated from the following files:
body_action.hh
body_action.cc