JEOD: jeod::SurfaceModel Class Reference
jeod::SurfaceModel Class Reference
A general, non-interaction specific surface that can be used to create surfaces suitable for specific interactions.
#include <surface_model.hh>
Public Member Functions
SurfaceModel ()
Default constructor.
~SurfaceModel ()
Destructor.
void add_facets (Facet **new_facets, unsigned int num_new_facets)
void add_facet (Facet *new_facet)
void initialize_mass_connections (BaseDynManager &manager)
void update_articulation ()
Data Fields
bool articulation_active
Is the articulation active? If yes, facet information will be updated from the previously supplied mass tree.
char * struct_body_name
The name of the MassBody representing the overall structural frame of the vehicle associated with this surface model.
JeodPointerVector< Facet >::type facets
The facets that make up the surface.
Protected Attributes
MassBody * struct_body_ptr
A pointer to the MassBody named by struct_body_name.
JeodObjectList< FacetStateInfo >::type articulation_states
The set of states used to update the articulation of each facet.
Private Member Functions
SurfaceModel & operator= (const SurfaceModel &rhs)
SurfaceModel (const SurfaceModel &rhs)
Friends
class InputProcessor
void init_attrjeod__SurfaceModel ()
Detailed Description
A general, non-interaction specific surface that can be used to create surfaces suitable for specific interactions.
Definition at line 149 of file surface_model.hh.
Constructor & Destructor Documentation
SurfaceModel() [1/2]
jeod::SurfaceModel::SurfaceModel (void)
Default constructor.
Definition at line 56 of file surface_model.cc.
References articulation_states, facets, JEOD_REGISTER_CHECKPOINTABLE, and JEOD_REGISTER_CLASS.
~SurfaceModel()
jeod::SurfaceModel::~SurfaceModel (void)
Destructor.
Definition at line 76 of file surface_model.cc.
References articulation_states, facets, and JEOD_DEREGISTER_CHECKPOINTABLE.
SurfaceModel() [2/2]
jeod::SurfaceModel::SurfaceModel (const SurfaceModel & rhs) private
Member Function Documentation
add_facet()
void jeod::SurfaceModel::add_facet (Facet * new_facet)
Definition at line 124 of file surface_model.cc.
References facets, jeod::MessageHandler::fail(), and jeod::SurfaceModelMessages::setup_error.
add_facets()
void jeod::SurfaceModel::add_facets (Facet ** new_facets, unsigned int num_new_facets)
Definition at line 89 of file surface_model.cc.
References facets, jeod::SurfaceModelMessages::setup_error, and jeod::MessageHandler::warn().
initialize_mass_connections()
void jeod::SurfaceModel::initialize_mass_connections (BaseDynManager & manager)
Definition at line 149 of file surface_model.cc.
References articulation_states, facets, jeod::MessageHandler::fail(), jeod::BaseDynManager::find_mass_body(), jeod::SurfaceModelMessages::initialization_error, struct_body_name, struct_body_ptr, and jeod::NamedItem::validate_name().
operator=()
SurfaceModel& jeod::SurfaceModel::operator= (const SurfaceModel & rhs) private
update_articulation()
void jeod::SurfaceModel::update_articulation (void)
Definition at line 211 of file surface_model.cc.
References articulation_active, articulation_states, jeod::NamedItem::c_str(), jeod::MassPoint::compute_relative_state(), facets, jeod::MessageHandler::fail(), jeod::MassBody::get_root_body(), jeod::FacetStateInfo::mass_body, jeod::FacetStateInfo::mass_state, jeod::MassBody::name, jeod::SurfaceModelMessages::runtime_error, struct_body_name, struct_body_ptr, and jeod::MassBody::structure_point.
Friends And Related Function Documentation
init_attrjeod__SurfaceModel
void init_attrjeod__SurfaceModel () friend
InputProcessor
friend class InputProcessor friend
Definition at line 151 of file surface_model.hh.
Field Documentation
articulation_active
bool jeod::SurfaceModel::articulation_active
Is the articulation active? If yes, facet information will be updated from the previously supplied mass tree.
If not, nothing will update. This defaults to falsetrick_units(–)
Definition at line 166 of file surface_model.hh.
Referenced by update_articulation().
articulation_states
JeodObjectList<FacetStateInfo>::type jeod::SurfaceModel::articulation_states protected
The set of states used to update the articulation of each facet.
trick_io(**)
Definition at line 207 of file surface_model.hh.
Referenced by initialize_mass_connections(), SurfaceModel(), update_articulation(), and ~SurfaceModel().
facets
JeodPointerVector<Facet>::type jeod::SurfaceModel::facets
The facets that make up the surface.
trick_io(**)
Definition at line 189 of file surface_model.hh.
Referenced by add_facet(), add_facets(), jeod::ContactSurfaceFactory::create_surface(), jeod::InteractionSurfaceFactory::create_surface(), initialize_mass_connections(), SurfaceModel(), update_articulation(), and ~SurfaceModel().
struct_body_name
char* jeod::SurfaceModel::struct_body_name
The name of the MassBody representing the overall structural frame of the vehicle associated with this surface model.
All states of all contained facets will be relative to the structural frame of this MassBody. This name is only required for specific applications, such as contact and articulationtrick_units(–)
Definition at line 184 of file surface_model.hh.
Referenced by initialize_mass_connections(), and update_articulation().
struct_body_ptr
MassBody* jeod::SurfaceModel::struct_body_ptr protected
A pointer to the MassBody named by struct_body_name.
This pointer will be set, using struct_body_name, by searching the DynManager object supplied to the initialize_mass_connections function. This pointer is only used for specific applications, such as contact and articulationtrick_units(–)
Definition at line 201 of file surface_model.hh.
Referenced by initialize_mass_connections(), and update_articulation().
The documentation for this class was generated from the following files:
surface_model.hh
surface_model.cc