JEOD: jeod::ConstraintComponent Class Reference
jeod::ConstraintComponent Class Reference abstract
Represents a single scalar constraint, either a pure force in a specific direction at a specific point or a pure torque in a specific direction, that acts on some vehicle.
#include <constraint_component.hh>
Public Member Functions
ConstraintComponent (ConstraintFrame *constraint_frame_in=nullptr)
Default constructor.
virtual ~ConstraintComponent ()=default
Destructor.
ConstraintComponent (const ConstraintComponent &)=default
ConstraintComponent & operator= (const ConstraintComponent &)=default
ConstraintComponent (ConstraintComponent &&)=default
ConstraintComponent & operator= (ConstraintComponent &&)=default
virtual void attach_to_solver (DynBodyConstraintsSolver *solver, DynBody *dyn_body)=0
Perform actions related to the just-performed addition of this constraint to a constraints solver.
virtual void detach_from_solver (DynBodyConstraintsSolver *solver, DynBody *dyn_body)=0
Perform actions related to the just-performed removal of this constraint from a constraints solver.
virtual void update_attachment (const VehicleProperties &)
Update information about the relation between this constraint and the root DynBody.
virtual void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)=0
Prepare this object for solving a constraint problem.
void set_constraint_direction (SolverTypes::ConstVector3T constraint_direction)
Set the direction in which the constraint acts on the vehicle.
void compute_root_direction ()
Compute the constraint direction in root structural coordinates.
virtual SolverTypes::DecayedVector3T get_translational_response (const VehicleProperties &vehicle_properties, SolverTypes::ConstVector3T point, SolverTypes::Vector3T response) const =0
Get the vehicle's unit translational response to this constraint at a specified point in root body structural coordinates.
virtual SolverTypes::ConstDecayedVector3T get_rotational_response (const VehicleProperties &vehicle_properties) const
Get the vehicle's unit rotational response to this constraint.
virtual SolverTypes::DecayedVector3T get_rotational_response (const VehicleProperties &vehicle_properties, SolverTypes::Vector3T response) const
Get the vehicle's unit rotational response to this constraint.
virtual void set_right_hand_side (double rhs_value)
Set the right hand side of the constraint equation for this constraint.
virtual double get_right_hand_side () const
Get the right hand side of the constraint equation for this constraint.
virtual double get_cross_coeff (const VehicleProperties &vehicle_properties, const ConstraintComponent &other) const =0
Computes the coefficient of the solver A matrix that represents the interaction of some other constrained object and this constrained object.
virtual double get_self_coeff (const VehicleProperties &vehicle_properties) const
Computes the coefficient of the solver A matrix that represents the interaction of this constrained object with itself.
virtual void set_constraint_value (double value)=0
Set this constrained object's scalar constraint value.
virtual const Wrench & get_constraint_wrench () const
Get the wrench this constrained object exerts on the vehicle.
virtual void compute_constraint_response (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)=0
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
Protected Member Functions
void compute_rotational_response (const VehicleProperties &vehicle_properties, const double torque[3])
Compute the vehicle's rotational response to a torque.
Protected Attributes
ConstraintFrame * constraint_frame
The reference frame associated with this constraint.
Wrench constraint_wrench
The indeterminate part of the wrench due to this constraint.
double constraint_direction_constraint_frame [3]
The direction in which the constraint acts on the vehicle, in constraint frame coordinates.
double constraint_direction_root [3]
The direction in which the constraint acts on the vehicle, in root body structural coordinates.
double constraint_omega_dot_root [3]
The contribution of this constraint to the rotational acceleration of the root body, in root structural components.
double right_hand_side
The right hand side of the constraint equation pertaining to this constraint.
Friends
class InputProcessor
void init_attrjeod__ConstraintComponent ()
Detailed Description
Represents a single scalar constraint, either a pure force in a specific direction at a specific point or a pure torque in a specific direction, that acts on some vehicle.
The force or torque on the vehicle is some scalar value times the direction in which the force/torque acts. The force/torque the vehicle exerts on the constraint body in this direction is the additive inverse of the force/torque the constraint body exerts the vehicle. The behavior of the constraint body can also be described as some function of the total forces and torques on the vehicle (external and constraints), plus inertial effects. This leads to an equation for the scalar constraint force/torque value for each constraint.
The class DynBodyConstraintsSolver builds and then solves a system of equations for all of the constrained bodies. This yields values for each of the constraints, and hence for the total constraint forces and torques on the vehicle.
Definition at line 93 of file constraint_component.hh.
Constructor & Destructor Documentation
ConstraintComponent() [1/3]
jeod::ConstraintComponent::ConstraintComponent (ConstraintFrame * constraint_frame_in = nullptr)
Default constructor.
Definition at line 31 of file constraint_component.cc.
References constraint_direction_constraint_frame, constraint_direction_root, constraint_omega_dot_root, and jeod::Vector3::initialize().
~ConstraintComponent()
virtual jeod::ConstraintComponent::~ConstraintComponent () virtual default
Destructor.
ConstraintComponent() [2/3]
jeod::ConstraintComponent::ConstraintComponent (const ConstraintComponent &) default
ConstraintComponent() [3/3]
jeod::ConstraintComponent::ConstraintComponent (ConstraintComponent &&) default
Member Function Documentation
attach_to_solver()
virtual void jeod::ConstraintComponent::attach_to_solver (DynBodyConstraintsSolver * solver, DynBody * dyn_body) pure virtual
Perform actions related to the just-performed addition of this constraint to a constraints solver.
Implemented in jeod::PendulumConstraintComponent, jeod::ForceConstraintComponent, and jeod::TorqueConstraintComponent.
Referenced by jeod::DynBodyConstraint::attach_to_solver().
compute_constraint_response()
virtual void jeod::ConstraintComponent::compute_constraint_response (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) pure virtual
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to external forces and torques, including the constraints.
Implemented in jeod::ForceConstraintComponent, jeod::TorqueConstraintComponent, and jeod::PendulumConstraintComponent.
Referenced by jeod::DynBodyConstraint::compute_constraint_response().
compute_root_direction()
void jeod::ConstraintComponent::compute_root_direction ()
Compute the constraint direction in root structural coordinates.
Definition at line 72 of file constraint_component.cc.
References constraint_direction_constraint_frame, constraint_direction_root, constraint_frame, jeod::ConstraintFrame::T_root_constraint, and jeod::Vector3::transform_transpose().
Referenced by set_constraint_direction(), and update_attachment().
compute_rotational_response()
void jeod::ConstraintComponent::compute_rotational_response (const VehicleProperties & vehicle_properties, const double torque[3]) protected
Compute the vehicle's rotational response to a torque.
Parameters
vehicle_properties Various vehicle properties.
torque The torque for which the response is to be calculated.
Definition at line 83 of file constraint_component.cc.
References constraint_omega_dot_root, jeod::VehicleProperties::get_inverse_inertia(), jeod::VehicleProperties::get_structure_to_body_transform(), jeod::Vector3::transform(), and jeod::Vector3::transform_transpose().
Referenced by jeod::ForceConstraintComponent::setup_constraint(), and jeod::TorqueConstraintComponent::setup_constraint().
detach_from_solver()
virtual void jeod::ConstraintComponent::detach_from_solver (DynBodyConstraintsSolver * solver, DynBody * dyn_body) pure virtual
Perform actions related to the just-performed removal of this constraint from a constraints solver.
Implemented in jeod::PendulumConstraintComponent, jeod::ForceConstraintComponent, and jeod::TorqueConstraintComponent.
Referenced by jeod::DynBodyConstraint::detach_from_solver().
get_constraint_wrench()
virtual const Wrench& jeod::ConstraintComponent::get_constraint_wrench () const inline virtual
Get the wrench this constrained object exerts on the vehicle.
Returns
A const reference to the constraint wrench for this object.
Note
This function is called after the constraint values have been set.
Definition at line 265 of file constraint_component.hh.
References constraint_wrench.
Referenced by jeod::DynBodyPendulumConstraint::get_constraint_wrench(), and jeod::DynBodyAttachedBodyConstraint::set_constraint_values().
get_cross_coeff()
virtual double jeod::ConstraintComponent::get_cross_coeff (const VehicleProperties & vehicle_properties, const ConstraintComponent & other) const pure virtual
Computes the coefficient of the solver A matrix that represents the interaction of some other constrained object and this constrained object.
Parameters
vehicle_properties Various vehicle properties.
other The other constrained object.
Returns
Interaction coefficient.
Implemented in jeod::ForceConstraintComponent, and jeod::TorqueConstraintComponent.
Referenced by get_self_coeff().
get_right_hand_side()
virtual double jeod::ConstraintComponent::get_right_hand_side () const inline virtual
Get the right hand side of the constraint equation for this constraint.
Definition at line 225 of file constraint_component.hh.
References right_hand_side.
Referenced by jeod::DynBodyConstraint::set_r_h_s().
get_rotational_response() [1/2]
SolverTypes::ConstDecayedVector3T jeod::ConstraintComponent::get_rotational_response (const VehicleProperties & vehicle_properties) const virtual
Get the vehicle's unit rotational response to this constraint.
Parameters
vehicle_properties Various vehicle properties.
Returns
The rotational accleration by the vehicle due to a unit value of this constraint.
Definition at line 44 of file constraint_component.cc.
References constraint_omega_dot_root.
Referenced by jeod::TorqueConstraintComponent::get_cross_coeff(), and get_rotational_response().
get_rotational_response() [2/2]
SolverTypes::DecayedVector3T jeod::ConstraintComponent::get_rotational_response (const VehicleProperties & vehicle_properties, SolverTypes::Vector3T response) const virtual
Get the vehicle's unit rotational response to this constraint.
Parameters
vehicle_properties Various vehicle properties.
response The response vector, which is filled with the rotational acceleration by the vehicle due to a unit value of this constraint.
Returns
The response vector.
Definition at line 52 of file constraint_component.cc.
References jeod::Vector3::copy(), and get_rotational_response().
get_self_coeff()
virtual double jeod::ConstraintComponent::get_self_coeff (const VehicleProperties & vehicle_properties) const inline virtual
Computes the coefficient of the solver A matrix that represents the interaction of this constrained object with itself.
Parameters
vehicle_properties Various vehicle properties.
Returns
Interaction coefficient.
Definition at line 247 of file constraint_component.hh.
References get_cross_coeff().
get_translational_response()
virtual SolverTypes::DecayedVector3T jeod::ConstraintComponent::get_translational_response (const VehicleProperties & vehicle_properties, SolverTypes::ConstVector3T point, SolverTypes::Vector3T response) const pure virtual
Get the vehicle's unit translational response to this constraint at a specified point in root body structural coordinates.
Parameters
vehicle_properties Various vehicle properties.
point The point, relative to the root body center and expressed in root body structural coordinates, at with the translational response is to be computed.
response The response vector, which is filled with the translational acceleration at the specified point on the vehicle due to a unitary value of the specified component of this constraint.
Returns
The response vector.
Implemented in jeod::ForceConstraintComponent, and jeod::TorqueConstraintComponent.
Referenced by jeod::ForceConstraintComponent::get_cross_coeff().
operator=() [1/2]
ConstraintComponent& jeod::ConstraintComponent::operator= (const ConstraintComponent &) default
operator=() [2/2]
ConstraintComponent& jeod::ConstraintComponent::operator= (ConstraintComponent &&) default
set_constraint_direction()
void jeod::ConstraintComponent::set_constraint_direction (SolverTypes::ConstVector3T constraint_direction)
Set the direction in which the constraint acts on the vehicle.
Parameters
constraint_direction Constraint direction, in constraint frame coordinates.
Definition at line 62 of file constraint_component.cc.
References compute_root_direction(), constraint_direction_constraint_frame, and jeod::Vector3::copy().
Referenced by jeod::PendulumConstraintComponent::compute_bob_state_cartesian(), and jeod::PendulumConstraintComponent::compute_bob_state_spherical().
set_constraint_value()
virtual void jeod::ConstraintComponent::set_constraint_value (double value) pure virtual
Set this constrained object's scalar constraint value.
Parameters
value The solution to the matrix constraint equation for this constrained object.
Implemented in jeod::ForceConstraintComponent, and jeod::TorqueConstraintComponent.
Referenced by jeod::DynBodyConstraint::set_constraint_values().
set_right_hand_side()
virtual void jeod::ConstraintComponent::set_right_hand_side (double rhs_value) inline virtual
Set the right hand side of the constraint equation for this constraint.
Definition at line 217 of file constraint_component.hh.
References right_hand_side.
Referenced by jeod::DynBodyAttachedBodyConstraint::setup_constraint().
setup_constraint()
virtual void jeod::ConstraintComponent::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) pure virtual
Prepare this object for solving a constraint problem.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to non-constraint forces and torques, including the pre-constraint wrenches.
Implemented in jeod::PendulumConstraintComponent, jeod::ForceConstraintComponent, and jeod::TorqueConstraintComponent.
Referenced by jeod::DynBodyConstraint::setup_component_constraint().
update_attachment()
virtual void jeod::ConstraintComponent::update_attachment (const VehicleProperties &) inline virtual
Update information about the relation between this constraint and the root DynBody.
Note
This method needs to be called after the root structure frame to root constraint frame relationship has been updated.
Definition at line 143 of file constraint_component.hh.
References compute_root_direction().
Referenced by jeod::DynBodyPendulumConstraint::update_attachment(), and jeod::DynBodyConstraint::update_component_attachment().
Friends And Related Function Documentation
init_attrjeod__ConstraintComponent
void init_attrjeod__ConstraintComponent () friend
InputProcessor
friend class InputProcessor friend
Definition at line 96 of file constraint_component.hh.
Field Documentation
constraint_direction_constraint_frame
double jeod::ConstraintComponent::constraint_direction_constraint_frame[3] protected
The direction in which the constraint acts on the vehicle, in constraint frame coordinates.
trick_units(–)
Definition at line 298 of file constraint_component.hh.
Referenced by compute_root_direction(), ConstraintComponent(), jeod::TorqueConstraintComponent::get_cross_coeff(), set_constraint_direction(), and jeod::PendulumConstraintComponent::setup_constraint().
constraint_direction_root
double jeod::ConstraintComponent::constraint_direction_root[3] protected
The direction in which the constraint acts on the vehicle, in root body structural coordinates.
trick_units(–)
Definition at line 304 of file constraint_component.hh.
Referenced by compute_root_direction(), ConstraintComponent(), jeod::ForceConstraintComponent::get_cross_coeff(), jeod::ForceConstraintComponent::setup_constraint(), and jeod::TorqueConstraintComponent::setup_constraint().
constraint_frame
ConstraintFrame* jeod::ConstraintComponent::constraint_frame protected
The reference frame associated with this constraint.
trick_units(–)
Definition at line 287 of file constraint_component.hh.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), compute_root_direction(), jeod::TorqueConstraintComponent::get_cross_coeff(), and jeod::PendulumConstraintComponent::setup_constraint().
constraint_omega_dot_root
double jeod::ConstraintComponent::constraint_omega_dot_root[3] protected
The contribution of this constraint to the rotational acceleration of the root body, in root structural components.
trick_units(1/s^2)
Definition at line 310 of file constraint_component.hh.
Referenced by compute_rotational_response(), ConstraintComponent(), get_rotational_response(), jeod::TorqueConstraintComponent::get_translational_response(), and jeod::ForceConstraintComponent::get_translational_response().
constraint_wrench
Wrench jeod::ConstraintComponent::constraint_wrench protected
The indeterminate part of the wrench due to this constraint.
trick_units(–)
Definition at line 292 of file constraint_component.hh.
Referenced by get_constraint_wrench(), jeod::TorqueConstraintComponent::set_constraint_value(), jeod::ForceConstraintComponent::set_constraint_value(), jeod::TorqueConstraintComponent::setup_constraint(), and jeod::ForceConstraintComponent::setup_constraint().
right_hand_side
double jeod::ConstraintComponent::right_hand_side protected
The right hand side of the constraint equation pertaining to this constraint.
This has units of force for a force constraint, torque for a torque constraint, etc.trick_units(–)
Definition at line 317 of file constraint_component.hh.
Referenced by get_right_hand_side(), set_right_hand_side(), and jeod::PendulumConstraintComponent::setup_constraint().
The documentation for this class was generated from the following files:
constraint_component.hh
constraint_component.cc