JEOD: jeod::RestartableStateIntegrator< IntegratorType > Class Template Reference
jeod::RestartableStateIntegrator< IntegratorType > Class Template Reference abstract
A RestartableStateIntegrator establishes the basic capabilities needed to make a state integrator a managed resource.
#include <restartable_state_integrator_templates.hh>
Public Member Functions
~RestartableStateIntegrator () override
Destructor.
void create_integrator (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls)
Create the integrator to be managed.
void destroy_integrator ()
Destroy the integrator.
void clear_integrator_reference ()
Clear the pointer to the external integrator object.
void set_integrator_reference (IntegratorType *&integ_ptr)
Set the pointer to the external integrator object.
void simple_restore () override
Restore the integrator on restart.
Public Member Functions inherited from jeod::SimpleCheckpointable
SimpleCheckpointable ()
Construct a SimpleCheckpointable object.
~SimpleCheckpointable (void) override
Destruct a SimpleCheckpointable object.
const std::string get_init_name (void) override
Return the name of the initial restart action, in this case "restore".
const std::string get_item_name (void) override
Return the name of the current restart action, in this case "".
const std::string get_item_value (void) override
Return the value of the current restart action, in this case "".
void start_checkpoint (void) override
In general, start the checkpoint process.
void advance_checkpoint (void) override
In general, advance to the next checkpoint item; in this case, do nothing.
bool is_checkpoint_finished (void) override
In general, indicate when checkpointing is complete.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
In general, respond to the actions recorded in the checkpoint file.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_name (void)
In general, return the name of the finalization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
Protected Member Functions
RestartableStateIntegrator ()
Default constructor.
RestartableStateIntegrator (IntegratorType *&integ_ref)
Non-default constructor.
Private Member Functions
virtual IntegratorType * create_integrator_internal (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls)=0
Create the integrator to be managed.
virtual void simple_restore_internal (IntegratorType *integrator_ptr)
Perform technique-specific restart actions.
RestartableStateIntegrator (const RestartableStateIntegrator &)
Not implemented.
RestartableStateIntegrator & operator= (const RestartableStateIntegrator &)
Not implemented.
Private Attributes
IntegratorType ** integrator_handle
Pointer to the containing object's integrator pointer.
Detailed Description
template<typename IntegratorType>
class jeod::RestartableStateIntegrator< IntegratorType >
A RestartableStateIntegrator establishes the basic capabilities needed to make a state integrator a managed resource.
This includes
Creating the integrator object,
Restoring the integrator's derivative function on restart, and
Destroying the integrator when the RestartableStateIntegrator instance goes out of scope.
Template Parameters
IntegratorType The type of integrator to be managed, either er7_utils::FirstOrderODEIntegrator or er7_utils::SecondOrderODEIntegrator.
Usage:
This base class template is not directly usable. One must instead use one of the three class templates that derive from this class template:
RestartableFirstOrderODEIntegrator to manage an er7_utils::FirstOrderODEIntegrator pointer;
RestartableGeneralizedDerivSecondOrderODEIntegrator to manage an er7_utils::SecondOrderODEIntegrator pointer for a generalized second order ODE, one in which the time derivative of generalized position is a function of generalized position and generalized velocity; and
RestartableGeneralizedStepSecondOrderODEIntegrator to manage an er7_utils::SecondOrderODEIntegrator pointer for a generalized second order ODE, one in which the time derivative of generalized position is a function of generalized position and generalized velocity; and
RestartableSimpleSecondOrderODEIntegrator to manage an er7_utils::SecondOrderODEIntegrator pointer for a simple second order ODE, one in which the time derivative of generalized position is the generalized velocity.
Each state integrator to be used in some class needs a pair of data members declared in the definition of that class. The first of these pairs is a pointer to the appropriate state integrator type (either er7_utils::FirstOrderODEIntegrator or er7_utils::SecondOrderODEIntegrator). The second of the pairs of data members is an instance of the appropriate derived class of RestartableStateIntegrator that will manage the pointer. An example:
class MyClass {
   ...
   er7_utils::SecondOrderODEIntegrator * integrator;
   RestartableSimpleSecondOrderODEIntegrator\<3\> integ_manager;
   ...
};
The pointer itself must be exposed to Trick for checkpoint and restart. The RestartableStateIntegrator-derived object should be hidden from Trick.
The connection between the pointer and the manager for that pointer is made in the initializer lists of the constructors for the class. Use the RestartableStateIntegrator non-default constructor to tie the RestartableStateIntegrator object with the pointer it is to manage:
MyClass::MyClass ()
:
   ...
   integrator(NULL),
   integ_manager(integrator),
   ...
{
   // Body of MyClass constructor
}
Note that there the RestartableStateIntegrator default constructors exist only for the sake of the simulation engine. The default constructors do not create viable instances. One must use the non-default constructor to initialize RestartableStateIntegrator instances.
The integrator itself is not created at construction time. Creating the integrator is the job of the create_integrator method. This method should be called at initialization time after having created the integration constructor and the integration controls objects.
The counterpart to the create_integrator method is destroy_integrator. This method must be called prior to calling create_integrator if the integrator has already been created via a previous call to create_integrator. (For example, switching to a different integration technique). The destroy_integrator can be called at shutdown or destruction time, but this call is not essential. The RestartableStateIntegrator object will call this method internally when it goes out of scope.
Class Design
This class template uses the non-virtual interface (NVI) design pattern, aka the template method design pattern (no relation to C++ class templates). The public create_integrator and simple_restore member functions use the private virtual create_integrator_internal and simple_restore_internal functions to create and restore the integrators.
Definition at line 173 of file restartable_state_integrator_templates.hh.
Constructor & Destructor Documentation
~RestartableStateIntegrator()
template<typename IntegratorType> jeod::RestartableStateIntegrator< IntegratorType >::~RestartableStateIntegrator () inline override
Destructor.
Definition at line 182 of file restartable_state_integrator_templates.hh.
RestartableStateIntegrator() [1/3]
template<typename IntegratorType> jeod::RestartableStateIntegrator< IntegratorType >::RestartableStateIntegrator () inline protected
Default constructor.
Definition at line 263 of file restartable_state_integrator_templates.hh.
RestartableStateIntegrator() [2/3]
template<typename IntegratorType> jeod::RestartableStateIntegrator< IntegratorType >::RestartableStateIntegrator (IntegratorType *& integ_ref) inline explicit protected
Non-default constructor.
Parameters
[in,out] integ_ref Reference to the pointer to the integrator that is to be managed.
Definition at line 274 of file restartable_state_integrator_templates.hh.
RestartableStateIntegrator() [3/3]
template<typename IntegratorType> jeod::RestartableStateIntegrator< IntegratorType >::RestartableStateIntegrator (const RestartableStateIntegrator< IntegratorType > &) private
Not implemented.
Member Function Documentation
clear_integrator_reference()
template<typename IntegratorType> void jeod::RestartableStateIntegrator< IntegratorType >::clear_integrator_reference () inline
Clear the pointer to the external integrator object.
This currently (pre-Trick 13.0) needs to be called on restart because both pointers point to invalid objects.
Definition at line 226 of file restartable_state_integrator_templates.hh.
Referenced by jeod::RestartableSO3SecondOrderODEIntegrator::simple_restore().
create_integrator()
template<typename IntegratorType> void jeod::RestartableStateIntegrator< IntegratorType >::create_integrator (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls) inline
Create the integrator to be managed.
Parameters
[in] generator Integrator constructor used to create the integrator.
[in,out] controls Integration controls to be passed to the generator.
Definition at line 192 of file restartable_state_integrator_templates.hh.
Referenced by jeod::Restartable2DSecondOrderIntegrator::create_integrator(), jeod::RestartableScalarFirstOrderODEIntegrator::create_integrator(), jeod::RestartableT3SecondOrderODEIntegrator::create_integrator(), and jeod::RestartableSO3SecondOrderODEIntegrator::create_integrator().
create_integrator_internal()
template<typename IntegratorType> virtual IntegratorType* jeod::RestartableStateIntegrator< IntegratorType >::create_integrator_internal (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls) private pure virtual
Create the integrator to be managed.
Parameters
[in] generator Integrator constructor used to create the integrator.
[in,out] controls Integration controls to be passed to the generator.
Returns
The constructed integrator.
Implemented in jeod::RestartableGeneralizedStepSecondOrderODEIntegrator< position_size, velocity_size, StepFunctions >, jeod::RestartableGeneralizedStepSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions >, jeod::RestartableGeneralizedDerivSecondOrderODEIntegrator< position_size, velocity_size, DerivFunctions >, jeod::RestartableGeneralizedDerivSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions >, jeod::RestartableSimpleSecondOrderODEIntegrator< size >, jeod::RestartableSimpleSecondOrderODEIntegrator< 2 >, jeod::RestartableSimpleSecondOrderODEIntegrator< 3 >, jeod::RestartableFirstOrderODEIntegrator< size >, and jeod::RestartableFirstOrderODEIntegrator< 1 >.
Referenced by jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::create_integrator().
destroy_integrator()
template<typename IntegratorType> void jeod::RestartableStateIntegrator< IntegratorType >::destroy_integrator () inline
Destroy the integrator.
Definition at line 214 of file restartable_state_integrator_templates.hh.
Referenced by jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::create_integrator(), jeod::Restartable2DSecondOrderIntegrator::destroy_integrator(), jeod::RestartableScalarFirstOrderODEIntegrator::destroy_integrator(), jeod::RestartableT3SecondOrderODEIntegrator::destroy_integrator(), jeod::RestartableSO3SecondOrderODEIntegrator::destroy_integrator(), and jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::~RestartableStateIntegrator().
operator=()
template<typename IntegratorType> RestartableStateIntegrator& jeod::RestartableStateIntegrator< IntegratorType >::operator= (const RestartableStateIntegrator< IntegratorType > &) private
Not implemented.
set_integrator_reference()
template<typename IntegratorType> void jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference (IntegratorType *& integ_ptr) inline
Set the pointer to the external integrator object.
This currently (pre-Trick 13.0) needs to be called on restart because the integrator_handle is not properly restored by checkpoint.
Parameters
[in,out] integ_ptr Reference to the external integrator object.
Definition at line 237 of file restartable_state_integrator_templates.hh.
Referenced by jeod::RestartableSO3SecondOrderODEIntegrator::create_integrator(), jeod::Restartable2DSecondOrderIntegrator::destroy_integrator(), jeod::RestartableScalarFirstOrderODEIntegrator::simple_restore(), jeod::Restartable2DSecondOrderIntegrator::simple_restore(), jeod::RestartableT3SecondOrderODEIntegrator::simple_restore(), and jeod::RestartableSO3SecondOrderODEIntegrator::simple_restore().
simple_restore()
template<typename IntegratorType> void jeod::RestartableStateIntegrator< IntegratorType >::simple_restore (void) inline override virtual
Restore the integrator on restart.
This currently (pre-Trick 13.0) needs to be called after calling set_integrator_reference.
Implements jeod::SimpleCheckpointable.
Definition at line 248 of file restartable_state_integrator_templates.hh.
Referenced by jeod::RestartableScalarFirstOrderODEIntegrator::simple_restore(), jeod::Restartable2DSecondOrderIntegrator::simple_restore(), jeod::RestartableT3SecondOrderODEIntegrator::simple_restore(), and jeod::RestartableSO3SecondOrderODEIntegrator::simple_restore().
simple_restore_internal()
template<typename IntegratorType> virtual void jeod::RestartableStateIntegrator< IntegratorType >::simple_restore_internal (IntegratorType * integrator_ptr) inline private virtual
Perform technique-specific restart actions.
The default is to do nothing.
Parameters
[in,out] integrator_ptr The integrator object to be restored
Reimplemented in jeod::RestartableGeneralizedStepSecondOrderODEIntegrator< position_size, velocity_size, StepFunctions >, jeod::RestartableGeneralizedStepSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions >, jeod::RestartableGeneralizedDerivSecondOrderODEIntegrator< position_size, velocity_size, DerivFunctions >, and jeod::RestartableGeneralizedDerivSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions >.
Definition at line 301 of file restartable_state_integrator_templates.hh.
Referenced by jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::simple_restore().
Field Documentation
integrator_handle
template<typename IntegratorType> IntegratorType** jeod::RestartableStateIntegrator< IntegratorType >::integrator_handle private
Pointer to the containing object's integrator pointer.
trick_io(**)
Definition at line 311 of file restartable_state_integrator_templates.hh.
Referenced by jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::clear_integrator_reference(), jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::create_integrator(), jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::destroy_integrator(), jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::set_integrator_reference(), and jeod::RestartableStateIntegrator< er7_utils::SecondOrderODEIntegrator >::simple_restore().
The documentation for this class was generated from the following file:
restartable_state_integrator_templates.hh