JEOD: jeod::DynBodyAttachedBodyConstraint Class Reference
jeod::DynBodyAttachedBodyConstraint Class Reference
#include <dyn_body_attached_body_constraint.hh>
Public Member Functions
DynBodyAttachedBodyConstraint ()
Default constructor.
~DynBodyAttachedBodyConstraint () override=default
Destructor.
const Wrench & get_effector_wrench () const override
Get the known wrench for this constrained object.
const Wrench & get_constraint_wrench () const override
Get the wrench this constrained object exerts on the vehicle.
const Wrench & get_nonlinear_response_wrench () const override
Get the residual nonlinear wrench for this constrained object.
ConstraintComponent * get_component (unsigned index) override
Get the indexed component constraint for this composite constraint.
void update_attachment (const VehicleProperties &vehicle_properties) override
Update information about the relation between this constraint and the root DynBody.
void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state) override
Prepare this object for solving a constraint problem.
void set_constraint_values (const VectorView< double, double > &solution_slice) override
Set this constrained object's constraint values.
bool check_for_reset ()
Determine whether the integrator needs to be reset, which occurs on transition between modes.
Public Member Functions inherited from jeod::DynBodyConstraint
DynBodyConstraint ()=default
virtual ~DynBodyConstraint ()
Destructor.
DynBodyConstraint (const DynBodyConstraint &)=delete
DynBodyConstraint & operator= (const DynBodyConstraint &)=delete
virtual void activate ()
Activate the constraint.
virtual void deactivate ()
Deactivate the constraint.
bool is_active () const
Is the constraint active?
virtual const DynBodyConstraintsSolver * get_solver () const
Get the solver for this constrained object.
virtual void set_struct_to_constraint_frame (SolverTypes::ConstDecayedMatrix3x3T transform_in, SolverTypes::ConstDecayedVector3T offset_in)
Set the relationship between the constraint frame and the immediate structural frame.
void update_component_attachment (const VehicleProperties &vehicle_properties)
Send update_attachment to each component.
void setup_component_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Send setup_constraint to each component.
virtual const ConstraintComponent * get_component (unsigned index) const
Const version of get_component().
virtual void set_r_h_s (jeod::VectorView< double > &rhs_slice) const
Set the sum of the terms in the constraint equation that don't involve other constrained objects, expressed as the right hand side of the constraint equation.
virtual void set_r_h_s (jeod::VectorView< double > &&rhs_slice) const
So one can use set_r_h_s with a temporary.
virtual void set_cross_coeff (const VehicleProperties &vehicle_properties, const DynBodyConstraint &other, jeod::MatrixView< double > &a_slice) const
Set the constraint matrix elements that pertain to this constrained object with respect to some other constrained object.
virtual void set_cross_coeff (const VehicleProperties &vehicle_properties, const DynBodyConstraint &other, jeod::MatrixView< double > &&a_slice) const
So one can call set_cross_coeff with a temporary.
virtual void set_self_coeff (const VehicleProperties &vehicle_properties, jeod::MatrixView< double > &a_slice) const
Set the constraint matrix elements for this constraint object with respect to itself.
virtual void set_self_coeff (const VehicleProperties &vehicle_properties, jeod::MatrixView< double > &&a_slice) const
So one can call set_self_coeff with a temporary.
virtual void compute_constraint_response (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Compute the response (if any) of the constrained object to the overall behavior of the vehicle.
Protected Attributes
ConstrainedRigidMass constrained_mass
The body as a constrained mass.
ForceConstraintComponent force_constraints [3]
The force constraints that arise from this attached body.
TorqueConstraintComponent torque_constraints [3]
The torque constraints that arise from this attached body.
Wrench null_wrench {true}
A wrench that is always zero and inactive.
Wrench constraint_wrench
The total wrench on the vehicle from this constrained object.
Protected Attributes inherited from jeod::DynBodyConstraint
ConstraintFrame constraint_frame
The reference frame associated with this constraint.
DynBodyConstraintsSolver * solver {}
The solver to which this constraint is assigned.
unsigned n_dimensions {}
The number of active components associated with this constraint.
bool inactive {}
Is the constraint inactive? Note: This is expressed in the negative sense to support reduced Trick checkpointing.
Friends
class InputProcessor
void init_attrjeod__DynBodyAttachedBodyConstraint ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyConstraint
virtual void attach_to_solver ()
Perform actions related to the just-performed addition of this constraint to a constraints solver.
virtual void detach_from_solver ()
Perform actions related to the just-performed removal of this constraint from a constraints solver.
virtual DynBody * get_dyn_body ()
Get the dyn_body object associated with this constrained object.
Detailed Description
Definition at line 71 of file dyn_body_attached_body_constraint.hh.
Constructor & Destructor Documentation
DynBodyAttachedBodyConstraint()
jeod::DynBodyAttachedBodyConstraint::DynBodyAttachedBodyConstraint ()
Default constructor.
Definition at line 28 of file dyn_body_attached_body_constraint.cc.
References constrained_mass, and jeod::DynBodyConstraint::constraint_frame.
~DynBodyAttachedBodyConstraint()
jeod::DynBodyAttachedBodyConstraint::~DynBodyAttachedBodyConstraint () override default
Destructor.
Member Function Documentation
check_for_reset()
bool jeod::DynBodyAttachedBodyConstraint::check_for_reset () inline
Determine whether the integrator needs to be reset, which occurs on transition between modes.
This should be called as a scheduled job at the dynamics rate.
Definition at line 176 of file dyn_body_attached_body_constraint.hh.
get_component()
ConstraintComponent* jeod::DynBodyAttachedBodyConstraint::get_component (unsigned index) inline override virtual
Get the indexed component constraint for this composite constraint.
Parameters
index Index of the component constraint to be retrieved. This is not bounds-checked.
Returns
The indexed component constraint.
Implements jeod::DynBodyConstraint.
Definition at line 124 of file dyn_body_attached_body_constraint.hh.
References force_constraints, and torque_constraints.
get_constraint_wrench()
const Wrench& jeod::DynBodyAttachedBodyConstraint::get_constraint_wrench () const inline override virtual
Get the wrench this constrained object exerts on the vehicle.
Returns
A const reference to the constraint wrench for this object.
Note
This function is called after the constraint values have been set.
Implements jeod::DynBodyConstraint.
Definition at line 101 of file dyn_body_attached_body_constraint.hh.
References constraint_wrench.
get_effector_wrench()
const Wrench& jeod::DynBodyAttachedBodyConstraint::get_effector_wrench () const inline override virtual
Get the known wrench for this constrained object.
Returns
A const reference to the effector wrench for this object.
Note
This function is called prior to any calls to setup_constraint(), with the effects of all of the pre-constraint wrenches incorporated into the non_grav_state argument to that function.
Implements jeod::DynBodyConstraint.
Definition at line 91 of file dyn_body_attached_body_constraint.hh.
References null_wrench.
get_nonlinear_response_wrench()
const Wrench& jeod::DynBodyAttachedBodyConstraint::get_nonlinear_response_wrench () const inline override virtual
Get the residual nonlinear wrench for this constrained object.
Returns
A const reference to the nonlinear wrench for this object.
Note
This function is called after calls to compute_constraint_response. The nonlinear aspects are assumed to be small; they are not taken into account while solving the constraints equation.
Implements jeod::DynBodyConstraint.
Definition at line 113 of file dyn_body_attached_body_constraint.hh.
References null_wrench.
set_constraint_values()
void jeod::DynBodyAttachedBodyConstraint::set_constraint_values (const VectorView< double, double > & solution_slice) override virtual
Set this constrained object's constraint values.
Parameters
solution_slice The solution to the matrix constraint equation for this constrained object, such that solution_slice[0] contains the constraint value for the zeroth component, etc.
Note
This function is called after the matrix constraint equation has been formulated and solved.
Reimplemented from jeod::DynBodyConstraint.
Definition at line 62 of file dyn_body_attached_body_constraint.cc.
References constrained_mass, jeod::ConstrainedPointMass::constraint_position_root, constraint_wrench, force_constraints, jeod::ConstraintComponent::get_constraint_wrench(), jeod::Wrench::reset_force_and_torque(), jeod::DynBodyConstraint::set_constraint_values(), jeod::Wrench::set_point(), and torque_constraints.
setup_constraint()
void jeod::DynBodyAttachedBodyConstraint::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) override virtual
Prepare this object for solving a constraint problem.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state The non-gravitational response of the root body to non-constraint forces and torques, including the pre-constraint wrenches.
Note
This function is called prior to the calls to set_self_coeff(), set_cross_coeff(), and set_r_h_s().
Implements jeod::DynBodyConstraint.
Definition at line 49 of file dyn_body_attached_body_constraint.cc.
References constrained_mass, jeod::ConstrainedPointMass::force_constraint_frame, force_constraints, jeod::ConstraintComponent::set_right_hand_side(), jeod::DynBodyConstraint::setup_component_constraint(), jeod::ConstrainedRigidMass::setup_constraint(), jeod::ConstrainedRigidMass::torque_constraint_frame, and torque_constraints.
update_attachment()
void jeod::DynBodyAttachedBodyConstraint::update_attachment (const VehicleProperties & vehicle_properties) inline override virtual
Update information about the relation between this constraint and the root DynBody.
Parameters
vehicle_properties Various vehicle properties.
Reimplemented from jeod::DynBodyConstraint.
Definition at line 142 of file dyn_body_attached_body_constraint.hh.
References constrained_mass, jeod::ConstrainedPointMass::update_attachment(), jeod::DynBodyConstraint::update_attachment(), and jeod::DynBodyConstraint::update_component_attachment().
Friends And Related Function Documentation
init_attrjeod__DynBodyAttachedBodyConstraint
void init_attrjeod__DynBodyAttachedBodyConstraint () friend
InputProcessor
friend class InputProcessor friend
Definition at line 73 of file dyn_body_attached_body_constraint.hh.
Field Documentation
constrained_mass
ConstrainedRigidMass jeod::DynBodyAttachedBodyConstraint::constrained_mass protected
The body as a constrained mass.
Definition at line 185 of file dyn_body_attached_body_constraint.hh.
Referenced by DynBodyAttachedBodyConstraint(), set_constraint_values(), setup_constraint(), and update_attachment().
constraint_wrench
Wrench jeod::DynBodyAttachedBodyConstraint::constraint_wrench protected
The total wrench on the vehicle from this constrained object.
trick_units(–)
Definition at line 205 of file dyn_body_attached_body_constraint.hh.
Referenced by get_constraint_wrench(), and set_constraint_values().
force_constraints
ForceConstraintComponent jeod::DynBodyAttachedBodyConstraint::force_constraints[3] protected
The force constraints that arise from this attached body.
Definition at line 190 of file dyn_body_attached_body_constraint.hh.
Referenced by get_component(), set_constraint_values(), and setup_constraint().
null_wrench
Wrench jeod::DynBodyAttachedBodyConstraint::null_wrench {true} protected
A wrench that is always zero and inactive.
trick_units(–)
Definition at line 200 of file dyn_body_attached_body_constraint.hh.
Referenced by get_effector_wrench(), and get_nonlinear_response_wrench().
torque_constraints
TorqueConstraintComponent jeod::DynBodyAttachedBodyConstraint::torque_constraints[3] protected
The torque constraints that arise from this attached body.
Definition at line 195 of file dyn_body_attached_body_constraint.hh.
Referenced by get_component(), set_constraint_values(), and setup_constraint().
The documentation for this class was generated from the following files:
dyn_body_attached_body_constraint.hh
dyn_body_attached_body_constraint.cc