JEOD: jeod::InteractionSurfaceFactory Class Reference
jeod::InteractionSurfaceFactory Class Reference
A base class for creating specific interaction surfaces from general surfaces.
#include <interaction_surface_factory.hh>
Public Member Functions
InteractionSurfaceFactory ()
Default Constructor.
virtual ~InteractionSurfaceFactory ()
Destructor.
virtual void create_surface (SurfaceModel *surface, InteractionSurface *inter_surface)
Creates an interaction surface, in the inter_surface parameter, from the given SurfaceModel.
void create_surface (SurfaceModel &surface, InteractionSurface &inter_surface)
Convenience version of create_surface which can be called from the input file.
virtual void add_facet_factory (InteractionFacetFactory *to_add)
Used to add an interaction facet factory for use in the surface factory.
virtual void add_facet_params (FacetParams *to_add)
Add a set of facet parameters for use in the interaction surface factory.
Data Fields
JeodPointerVector< InteractionFacetFactory >::type factories
A vector of interaction facet factories to be used.
JeodPointerVector< FacetParams >::type params
A vector of FacetParams to be used.
Private Member Functions
InteractionSurfaceFactory & operator= (const InteractionSurfaceFactory &rhs)
InteractionSurfaceFactory (const InteractionSurfaceFactory &rhs)
Friends
class InputProcessor
void init_attrjeod__InteractionSurfaceFactory ()
Detailed Description
A base class for creating specific interaction surfaces from general surfaces.
Definition at line 89 of file interaction_surface_factory.hh.
Constructor & Destructor Documentation
InteractionSurfaceFactory() [1/2]
jeod::InteractionSurfaceFactory::InteractionSurfaceFactory (void)
Default Constructor.
Definition at line 60 of file interaction_surface_factory.cc.
References factories, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, JEOD_REGISTER_INCOMPLETE_CLASS, and params.
~InteractionSurfaceFactory()
jeod::InteractionSurfaceFactory::~InteractionSurfaceFactory (void) virtual
Destructor.
Definition at line 74 of file interaction_surface_factory.cc.
References factories, JEOD_DEREGISTER_CHECKPOINTABLE, and params.
InteractionSurfaceFactory() [2/2]
jeod::InteractionSurfaceFactory::InteractionSurfaceFactory (const InteractionSurfaceFactory & rhs) private
Member Function Documentation
add_facet_factory()
void jeod::InteractionSurfaceFactory::add_facet_factory (InteractionFacetFactory * to_add) virtual
Used to add an interaction facet factory for use in the surface factory.
Parameters
[in] to_add The interaction facet factory to add
Definition at line 199 of file interaction_surface_factory.cc.
References factories, jeod::MessageHandler::fail(), and jeod::SurfaceModelMessages::setup_error.
add_facet_params()
void jeod::InteractionSurfaceFactory::add_facet_params (FacetParams * to_add) virtual
Add a set of facet parameters for use in the interaction surface factory.
Parameters
[in] to_add The facet parameters to add
Reimplemented in jeod::ContactSurfaceFactory, jeod::AeroSurfaceFactory, and jeod::RadiationSurfaceFactory.
Definition at line 221 of file interaction_surface_factory.cc.
References jeod::MessageHandler::fail(), jeod::FacetParams::name, params, jeod::SurfaceModelMessages::setup_error, and jeod::NamedItem::validate_name().
Referenced by jeod::RadiationSurfaceFactory::add_facet_params(), jeod::AeroSurfaceFactory::add_facet_params(), and jeod::ContactSurfaceFactory::add_facet_params().
create_surface() [1/2]
void jeod::InteractionSurfaceFactory::create_surface (SurfaceModel * surface, InteractionSurface * inter_surface) virtual
Creates an interaction surface, in the inter_surface parameter, from the given SurfaceModel.
The InteractionSurfaceFactory should contain all necessary InteractionFacetFactories and FacetParams already
Parameters
[in] surface The surface model used to create the interaction surface
[out] inter_surface Where the interaction surface will be produced
Reimplemented in jeod::ContactSurfaceFactory.
Definition at line 92 of file interaction_surface_factory.cc.
References jeod::InteractionSurface::allocate_array(), jeod::InteractionSurface::allocate_interaction_facet(), jeod::SurfaceModel::facets, factories, jeod::MessageHandler::fail(), jeod::SurfaceModelMessages::initialization_error, and params.
Referenced by create_surface().
create_surface() [2/2]
void jeod::InteractionSurfaceFactory::create_surface (SurfaceModel & surface, InteractionSurface & inter_surface) inline
Convenience version of create_surface which can be called from the input file.
Parameters
surface Surface model.
inter_surface Reference to the interaction surface.
Definition at line 111 of file interaction_surface_factory.hh.
References create_surface().
operator=()
InteractionSurfaceFactory& jeod::InteractionSurfaceFactory::operator= (const InteractionSurfaceFactory & rhs) private
Friends And Related Function Documentation
init_attrjeod__InteractionSurfaceFactory
void init_attrjeod__InteractionSurfaceFactory () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file interaction_surface_factory.hh.
Field Documentation
factories
JeodPointerVector<InteractionFacetFactory>::type jeod::InteractionSurfaceFactory::factories
A vector of interaction facet factories to be used.
Matched to facets by typetrick_io(**)
Definition at line 120 of file interaction_surface_factory.hh.
Referenced by add_facet_factory(), jeod::AeroSurfaceFactory::AeroSurfaceFactory(), jeod::ContactSurfaceFactory::ContactSurfaceFactory(), jeod::ContactSurfaceFactory::create_surface(), create_surface(), InteractionSurfaceFactory(), jeod::RadiationSurfaceFactory::RadiationSurfaceFactory(), ~InteractionSurfaceFactory(), and jeod::RadiationSurfaceFactory::~RadiationSurfaceFactory().
params
JeodPointerVector<FacetParams>::type jeod::InteractionSurfaceFactory::params
A vector of FacetParams to be used.
trick_io(**)
Definition at line 125 of file interaction_surface_factory.hh.
Referenced by add_facet_params(), jeod::ContactSurfaceFactory::create_surface(), create_surface(), InteractionSurfaceFactory(), and ~InteractionSurfaceFactory().
The documentation for this class was generated from the following files:
interaction_surface_factory.hh
interaction_surface_factory.cc