JEOD: jeod::JeodIntegrationGroup Class Reference
jeod::JeodIntegrationGroup Class Reference
A JeodIntegrationGroup integrates the state of a set of objects over time.
#include <jeod_integration_group.hh>
Public Member Functions
JeodIntegrationGroup ()
JeodIntegrationGroup default constructor, needed for checkpoint/restart, and to support derived classes' default constructors.
JeodIntegrationGroup (JeodIntegrationGroupOwner &owner, er7_utils::IntegratorConstructor &integ_cotr, JeodIntegratorInterface &integ_inter, JeodIntegrationTime &time_mngr)
JeodIntegrationGroup non-default constructor.
~JeodIntegrationGroup () override
JeodIntegrationGroup destructor.
JeodIntegrationGroup (const JeodIntegrationGroup &)=delete
JeodIntegrationGroup & operator= (const JeodIntegrationGroup &)=delete
bool need_first_step_derivatives () const
Indicate whether derivatives need to be calculated on the initial step of an integration cycle.
void update_from_owner ()
Update the group via its owner.
bool merge_integrator_result (const er7_utils::IntegratorResult &new_result, er7_utils::IntegratorResult &merged_result) const
Merge an IntegratorResult into another.
void respond_to_time_change () override
Respond to a change in the nature of time.
void initialize_group () override
Initialize the integration group.
void reset_body_integrators () override
Reset the integrators for the integrable objects managed by this group.
er7_utils::IntegratorResult integrate_bodies (double cycle_dyndt, unsigned int target_stage) override
Integrate the states of the integrable objects managed by this group.
virtual void add_integrable_object (er7_utils::IntegrableObject &integrable_object)
Add an integrable object to the vector of such.
virtual void remove_integrable_object (er7_utils::IntegrableObject &integrable_object)
Remove an integrable object from the vector of such.
Public Member Functions inherited from jeod::TimeChangeSubscriber
TimeChangeSubscriber ()=default
virtual ~TimeChangeSubscriber ()=default
TimeChangeSubscriber (const TimeChangeSubscriber &)=default
TimeChangeSubscriber & operator= (const TimeChangeSubscriber &)=default
Static Public Member Functions
static void register_classes ()
Register classes associated with integration.
Protected Member Functions
template<typename T >
void reset_container (const T &container)
Issue a reset to each member of a container.
template<typename T >
er7_utils::IntegratorResult integrate_container (double dyn_dt, unsigned int target_stage, const T &container)
Integrate each member of a collection.
Protected Attributes
JeodIntegrationGroupOwner *const group_owner {}
The object that owns this integration group, typically by containment.
er7_utils::IntegratorResultMergerContainer integ_merger
The object that merges results from multiple integrators.
JeodIntegratorInterface *const jeod_integ_interface {}
The interface between the integration module and the simulation engine's integration structure.
JeodIntegrationTime *const jeod_time_manager {}
The interface between the integration module and the object that represents time.
JeodPointerVector< er7_utils::IntegrableObject >::type integrable_objects
The objects whose states are integrated by this integration group.
Friends
class InputProcessor
void init_attrjeod__JeodIntegrationGroup ()
Detailed Description
A JeodIntegrationGroup integrates the state of a set of objects over time.
This class is designed for extensibility. Authors of derived classes should follow the extension notes in the source file.
Definition at line 115 of file jeod_integration_group.hh.
Constructor & Destructor Documentation
JeodIntegrationGroup() [1/3]
jeod::JeodIntegrationGroup::JeodIntegrationGroup ()
JeodIntegrationGroup default constructor, needed for checkpoint/restart, and to support derived classes' default constructors.
Definition at line 60 of file jeod_integration_group.cc.
References integrable_objects, JEOD_REGISTER_CHECKPOINTABLE, and register_classes().
JeodIntegrationGroup() [2/3]
jeod::JeodIntegrationGroup::JeodIntegrationGroup (JeodIntegrationGroupOwner & owner, er7_utils::IntegratorConstructor & integ_cotr, JeodIntegratorInterface & integ_inter, JeodIntegrationTime & time_mngr)
JeodIntegrationGroup non-default constructor.
Parameters
[in] owner The object that contains this group.
[in] integ_cotr Integrator constructor
[in] integ_inter Integrator interface
[in] time_mngr Time manager
Definition at line 68 of file jeod_integration_group.cc.
References jeod::JeodIntegrationTime::add_time_change_subscriber(), integ_merger, integrable_objects, JEOD_REGISTER_CHECKPOINTABLE, and register_classes().
~JeodIntegrationGroup()
jeod::JeodIntegrationGroup::~JeodIntegrationGroup () override
JeodIntegrationGroup destructor.
Definition at line 86 of file jeod_integration_group.cc.
References integrable_objects, JEOD_DEREGISTER_CHECKPOINTABLE, jeod_time_manager, and jeod::JeodIntegrationTime::remove_time_change_subscriber().
JeodIntegrationGroup() [3/3]
jeod::JeodIntegrationGroup::JeodIntegrationGroup (const JeodIntegrationGroup &) delete
Member Function Documentation
add_integrable_object()
void jeod::JeodIntegrationGroup::add_integrable_object (er7_utils::IntegrableObject & integrable_object) virtual
Add an integrable object to the vector of such.
Parameters
[in] integrable_object Object to be added.
Definition at line 97 of file jeod_integration_group.cc.
References integrable_objects.
Referenced by jeod::DynamicsIntegrationGroup::add_dyn_body(), and jeod::JeodDynbodyIntegrationLoop::add_integrable_object().
initialize_group()
void jeod::JeodIntegrationGroup::initialize_group () override
Initialize the integration group.
Some integration techniques are configurable by user input, and thus the creation of the controls and integrators needs to be delayed a bit.
Definition at line 153 of file jeod_integration_group.cc.
References integrable_objects.
Referenced by jeod::DynamicsIntegrationGroup::initialize_group().
integrate_bodies()
er7_utils::IntegratorResult jeod::JeodIntegrationGroup::integrate_bodies (double cycle_dyndt, unsigned int target_stage) inline override
Integrate the states of the integrable objects managed by this group.
This function should only be called by IntegrationControls::integrate or by an override of that function. Derived classes are free to override this default implementation. However, those derived class overrides either must call this method to integrate the states of the registered integrable bodies or must somehow take on the burden of integrating those states.
Parameters
[in] cycle_dyndt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 234 of file jeod_integration_group.hh.
References integrable_objects, and integrate_container().
integrate_container()
template<typename T > er7_utils::IntegratorResult jeod::JeodIntegrationGroup::integrate_container (double dyn_dt, unsigned int target_stage, const T & container) inline protected
Integrate each member of a collection.
Template Parameters
T The container type.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in,out] container The container to be integrated.
Definition at line 277 of file jeod_integration_group.hh.
References integ_merger.
Referenced by jeod::DynamicsIntegrationGroup::integrate_bodies(), and integrate_bodies().
merge_integrator_result()
bool jeod::JeodIntegrationGroup::merge_integrator_result (const er7_utils::IntegratorResult & new_result, er7_utils::IntegratorResult & merged_result) const inline
Merge an IntegratorResult into another.
Returns
True if merger was successful, false if some error occurred.
Parameters
[in] new_result Size of the generalized position vector
[in,out] merged_result Size of the generalized position vector
Definition at line 182 of file jeod_integration_group.hh.
References integ_merger.
need_first_step_derivatives()
bool jeod::JeodIntegrationGroup::need_first_step_derivatives () const inline
Indicate whether derivatives need to be calculated on the initial step of an integration cycle.
Returns
Desired flag.
Definition at line 163 of file jeod_integration_group.hh.
operator=()
JeodIntegrationGroup& jeod::JeodIntegrationGroup::operator= (const JeodIntegrationGroup &) delete
register_classes()
void jeod::JeodIntegrationGroup::register_classes () static
Register classes associated with integration.
This is a static method, and is best called prior to initialization time.
Definition at line 51 of file jeod_integration_group.cc.
References JEOD_REGISTER_CLASS.
Referenced by jeod::DynManager::DynManager(), and JeodIntegrationGroup().
remove_integrable_object()
void jeod::JeodIntegrationGroup::remove_integrable_object (er7_utils::IntegrableObject & integrable_object) virtual
Remove an integrable object from the vector of such.
Parameters
[in] integrable_object Object to be removed.
Definition at line 125 of file jeod_integration_group.cc.
References jeod::MessageHandler::error(), integrable_objects, and jeod::IntegrationMessages::invalid_item.
Referenced by jeod::JeodDynbodyIntegrationLoop::remove_integrable_object().
reset_body_integrators()
void jeod::JeodIntegrationGroup::reset_body_integrators () inline override
Reset the integrators for the integrable objects managed by this group.
Resets can occur when time changes behavior (call is internal to the integration process) or when some external event would render an integrator's history invalid (call comes from outside). When either happens, integrators that depend on history need to reset their internal state to indicate that the saved data are invalid.)
Definition at line 216 of file jeod_integration_group.hh.
References integrable_objects, and reset_container().
Referenced by jeod::DynamicsIntegrationGroup::reset_body_integrators().
reset_container()
template<typename T > void jeod::JeodIntegrationGroup::reset_container (const T & container) inline protected
Issue a reset to each member of a container.
Template Parameters
T The container type.
Parameters
[in,out] container The container to be reset.
Definition at line 259 of file jeod_integration_group.hh.
Referenced by reset_body_integrators().
respond_to_time_change()
void jeod::JeodIntegrationGroup::respond_to_time_change () inline override virtual
Respond to a change in the nature of time.
Implements jeod::TimeChangeSubscriber.
Definition at line 193 of file jeod_integration_group.hh.
update_from_owner()
void jeod::JeodIntegrationGroup::update_from_owner () inline
Update the group via its owner.
Definition at line 171 of file jeod_integration_group.hh.
References group_owner, and jeod::JeodIntegrationGroupOwner::update_integration_group().
Referenced by jeod::DynamicsIntegrationGroup::initialize_group().
Friends And Related Function Documentation
init_attrjeod__JeodIntegrationGroup
void init_attrjeod__JeodIntegrationGroup () friend
InputProcessor
friend class InputProcessor friend
Definition at line 118 of file jeod_integration_group.hh.
Field Documentation
group_owner
JeodIntegrationGroupOwner* const jeod::JeodIntegrationGroup::group_owner {} protected
The object that owns this integration group, typically by containment.
trick_units(–)
Definition at line 298 of file jeod_integration_group.hh.
Referenced by update_from_owner().
integ_merger
er7_utils::IntegratorResultMergerContainer jeod::JeodIntegrationGroup::integ_merger protected
The object that merges results from multiple integrators.
trick_units(–)
Definition at line 303 of file jeod_integration_group.hh.
Referenced by jeod::DynamicsIntegrationGroup::integrate_bodies(), integrate_container(), JeodIntegrationGroup(), and merge_integrator_result().
integrable_objects
JeodPointerVector<er7_utils::IntegrableObject>::type jeod::JeodIntegrationGroup::integrable_objects protected
The objects whose states are integrated by this integration group.
trick_io(**)
Definition at line 320 of file jeod_integration_group.hh.
Referenced by add_integrable_object(), initialize_group(), jeod::DynamicsIntegrationGroup::integrate_bodies(), integrate_bodies(), JeodIntegrationGroup(), remove_integrable_object(), reset_body_integrators(), and ~JeodIntegrationGroup().
jeod_integ_interface
JeodIntegratorInterface* const jeod::JeodIntegrationGroup::jeod_integ_interface {} protected
The interface between the integration module and the simulation engine's integration structure.
trick_units(–)
Definition at line 309 of file jeod_integration_group.hh.
jeod_time_manager
JeodIntegrationTime* const jeod::JeodIntegrationGroup::jeod_time_manager {} protected
The interface between the integration module and the object that represents time.
trick_units(–)
Definition at line 315 of file jeod_integration_group.hh.
Referenced by jeod::DynamicsIntegrationGroup::add_dyn_body(), jeod::DynamicsIntegrationGroup::initialize_group(), jeod::DynamicsIntegrationGroup::prepare_for_integ_loop(), and ~JeodIntegrationGroup().
The documentation for this class was generated from the following files:
jeod_integration_group.hh
jeod_integration_group.cc