JEOD: jeod::PointContactFacet Class Reference
jeod::PointContactFacet Class Reference
The contact facet based on the distance to a single point, specifically the vehicle point.
#include <point_contact_facet.hh>
Public Member Functions
PointContactFacet ()
Default constructor.
~PointContactFacet () override=default
PointContactFacet & operator= (const PointContactFacet &)=delete
PointContactFacet (const PointContactFacet &)=delete
ContactPair * create_pair () override
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
ContactPair * create_pair (ContactFacet *target, Contact *contact) override
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
void set_max_dimension () override
calculate the max dimension of the facet for range limit determination.
virtual void calculate_contact_point (double nvec[3])
Use the relstate and radius of contact to calculate a contact point on this facet.
void calculate_torque (double *tmp_force) override
Calculate the torque generated on the vehicle by the facet.
Public Member Functions inherited from jeod::ContactFacet
ContactFacet ()=default
~ContactFacet () override=default
ContactFacet & operator= (const ContactFacet &)=delete
ContactFacet (const ContactFacet &)=delete
void create_vehicle_point ()
Create a vehicle point to track the state information of the contact facet.
std::string get_name () const
Accessor for name.
Public Member Functions inherited from jeod::InteractionFacet
InteractionFacet ()=default
virtual ~InteractionFacet ()=default
InteractionFacet & operator= (const InteractionFacet &)=delete
InteractionFacet (const InteractionFacet &)=delete
Data Fields
double radius {}
radius from the point at which contact takes place.
double contact_point [3] {}
Contact point given in facet vehicle point frame, representing point on the point on the surface of a sphere of radius "radius" where contact has occured.
Data Fields inherited from jeod::ContactFacet
bool active {true}
toggles this contact facet on and off, true=on false=off
ContactParams * surface_type {}
Stores the name of surface material that the facet is constructed of.
DynBody * vehicle_body {}
DynBody associated with this facet for structural frame information.
double max_dimension {}
maximum dimension of the contact facet for use in limiting pair in_contact calls
double position [3] {}
position of the facet in vehicle structural frame.
double normal [3] {}
normal of the facet relative to the vehicle structural frame.
const BodyRefFrame * vehicle_point {}
Vehicle point for relstate calculations.
Data Fields inherited from jeod::InteractionFacet
double force [3] {}
The force on the facet caused by the environment interaction.
double torque [3] {}
The torque on the facet caused by the environment interaction.
Facet * base_facet {}
The original facet from which this interaction facet was created.
Friends
class InputProcessor
void init_attrjeod__PointContactFacet ()
Detailed Description
The contact facet based on the distance to a single point, specifically the vehicle point.
In effect this represents a sphere.
Definition at line 87 of file point_contact_facet.hh.
Constructor & Destructor Documentation
PointContactFacet() [1/2]
jeod::PointContactFacet::PointContactFacet ()
Default constructor.
Definition at line 50 of file point_contact_facet.cc.
References JEOD_REGISTER_CLASS.
~PointContactFacet()
jeod::PointContactFacet::~PointContactFacet () override default
PointContactFacet() [2/2]
jeod::PointContactFacet::PointContactFacet (const PointContactFacet &) delete
Member Function Documentation
calculate_contact_point()
void jeod::PointContactFacet::calculate_contact_point (double nvec[3]) virtual
Use the relstate and radius of contact to calculate a contact point on this facet.
Parameters
[in] nvec direction vector between the two facets
Reimplemented in jeod::LineContactFacet.
Definition at line 119 of file point_contact_facet.cc.
References contact_point, jeod::Vector3::normalize(), radius, and jeod::Vector3::scale().
Referenced by jeod::PointContactPair::in_contact(), and jeod::LinePointContactPair::in_contact().
calculate_torque()
void jeod::PointContactFacet::calculate_torque (double * tmp_force) override virtual
Calculate the torque generated on the vehicle by the facet.
Assumes that the force is in the vehicle structural frame, but that close_point is not.
Parameters
[in] tmp_force force from one contact interaction.
Units: N
Implements jeod::ContactFacet.
Definition at line 141 of file point_contact_facet.cc.
References jeod::MassBody::composite_properties, contact_point, jeod::Vector3::cross(), jeod::Vector3::diff(), jeod::DynBody::mass, jeod::BodyRefFrame::mass_point, jeod::MassPointState::position, jeod::RefFrameState::rot, jeod::RefFrame::state, jeod::DynBody::structure, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::InteractionFacet::torque, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::ContactFacet::vehicle_body, and jeod::ContactFacet::vehicle_point.
create_pair() [1/2]
ContactPair * jeod::PointContactFacet::create_pair () override virtual
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
This function is called to create a pair that only contains a subject.
Returns
ContactPair that was created
Implements jeod::ContactFacet.
Definition at line 61 of file point_contact_facet.cc.
References jeod::PointContactPair::initialize_pair(), and JEOD_ALLOC_CLASS_OBJECT.
create_pair() [2/2]
ContactPair * jeod::PointContactFacet::create_pair (ContactFacet * target, Contact * contact) override virtual
Overloaded functions that create a ContactPair and pass the address of it to the Contact class for addition to the list of pairs.
This function is called when a subject and target are known.
Returns
ContactPair that was created
Parameters
[in,out] target target ContactFacet
[in] contact Contact object used to find the pair interaction
Implements jeod::ContactFacet.
Definition at line 80 of file point_contact_facet.cc.
References jeod::Contact::contact_limit_factor, jeod::Contact::find_interaction(), jeod::ContactMessages::initialization_warns, jeod::PointContactPair::initialize_pair(), jeod::ContactPair::interaction, jeod::ContactPair::interaction_distance, JEOD_ALLOC_CLASS_OBJECT, jeod::ContactFacet::max_dimension, jeod::ContactFacet::surface_type, and jeod::MessageHandler::warn().
operator=()
PointContactFacet& jeod::PointContactFacet::operator= (const PointContactFacet &) delete
set_max_dimension()
void jeod::PointContactFacet::set_max_dimension () override virtual
calculate the max dimension of the facet for range limit determination.
Implements jeod::ContactFacet.
Definition at line 131 of file point_contact_facet.cc.
References jeod::ContactFacet::max_dimension, and radius.
Referenced by jeod::PointContactFacetFactory::create_facet().
Friends And Related Function Documentation
init_attrjeod__PointContactFacet
void init_attrjeod__PointContactFacet () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file point_contact_facet.hh.
Field Documentation
contact_point
double jeod::PointContactFacet::contact_point[3] {}
Contact point given in facet vehicle point frame, representing point on the point on the surface of a sphere of radius "radius" where contact has occured.
trick_units(m)
Definition at line 100 of file point_contact_facet.hh.
Referenced by jeod::LineContactFacet::calculate_contact_point(), calculate_contact_point(), jeod::LineContactFacet::calculate_torque(), calculate_torque(), jeod::LineContactPair::in_contact(), jeod::PointContactPair::in_contact(), and jeod::LinePointContactPair::in_contact().
radius
double jeod::PointContactFacet::radius {}
radius from the point at which contact takes place.
trick_units(m)
Definition at line 93 of file point_contact_facet.hh.
Referenced by jeod::LineContactFacet::calculate_contact_point(), calculate_contact_point(), jeod::PointContactFacetFactory::create_facet(), jeod::LineContactFacetFactory::create_facet(), jeod::PointContactPair::in_contact(), jeod::LineContactFacet::set_max_dimension(), and set_max_dimension().
The documentation for this class was generated from the following files:
point_contact_facet.hh
point_contact_facet.cc