JEOD: jeod::JeodPrimitiveContainer< ContainerType, ElemType > Class Template Reference
jeod::JeodPrimitiveContainer< ContainerType, ElemType > Class Template Reference
A JeodPrimitiveContainer is a JeodContainer that contains primitive data of type ElemType.
#include <primitive_container.hh>
Public Member Functions
JeodPrimitiveContainer ()=default
Construct a JeodPrimitiveContainer.
JeodPrimitiveContainer (const JeodPrimitiveContainer &source)
Copy-construct a JeodPrimitiveContainer.
JeodPrimitiveContainer (const typename ContainerType::stl_container_type &source)
Copy-construct a JeodPrimitiveContainer.
JeodPrimitiveContainer & operator= (const JeodPrimitiveContainer &source)
Copy from a JeodPrimitiveContainer.
JeodPrimitiveContainer & operator= (const typename ContainerType::stl_container_type &source)
Copy from an STL container.
virtual ~JeodPrimitiveContainer ()=default
Destruct a JeodPrimitiveContainer.
const std::string get_item_value () override
Return the value of the item to be written to the checkpoint file.
void perform_insert_action (const std::string &value) override
Interpret the provided value and insert it at the end of the object.
Public Member Functions inherited from jeod::JeodContainer< ContainerType, ElemType >
JeodContainer ()
Default constructor.
JeodContainer (const this_container_type &source)
Copy constructor.
JeodContainer (const stl_container_type &source)
Copy constructor.
JeodContainer & operator= (const this_container_type &source)
Assignment operator.
JeodContainer & operator= (const stl_container_type &source)
Assignment operator.
~JeodContainer () override=default
Destructor.
void swap_contents (this_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
void swap_contents (stl_container_type &other)
Swap STL sequence container contents – but not the stuff related to checkpoint or restart.
virtual void perform_cleanup_action (const std::string &value)
Cleanup detritus created during the restore process.
void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name) override
Initialize a checkpointable object, called by the checkpoint manager.
void start_checkpoint () override
Prepare to checkpoint the object.
void advance_checkpoint () override
Advance to the next item to be checkpointed.
bool is_checkpoint_finished () override
Indicate whether the checkpoint dump of this object is finished.
const std::string get_init_name () override
Names the action to be performed prior to performing any of the restore actions.
const std::string get_item_name () override
Return the name of the action to be printed along with the current value.
const std::string get_final_name () override
Names the action to be performed after to performing any of the restore actions.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
Perform a checkpoint-restart action that will, in part, restore the object to its state at the time of the checkpoint.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()=default
virtual ~JeodCheckpointable ()=default
JeodCheckpointable (const JeodCheckpointable &)=delete
JeodCheckpointable & operator= (const JeodCheckpointable &)=delete
virtual void pre_checkpoint ()
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint ()
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart ()
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart ()
In general, perform object-specific operations that need to be performed after restart completion.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value ()
In general, return the value of the initialization action.
virtual const std::string get_final_value ()
In general, return the value of the finalization action.
Protected Attributes
JeodPrimitiveSerializer< ElemType > serializer
Serializer / deserializer.
Protected Attributes inherited from jeod::JeodContainer< ContainerType, ElemType >
ContainerType::iterator checkpoint_iter
Iterator for walking through the container during checkpoint.
const JeodMemoryTypeDescriptor * elem_type_descriptor {}
Memory model descriptor of the type of data stored in the container.
Additional Inherited Members
Public Types inherited from jeod::JeodContainer< ContainerType, ElemType >
using this_container_type = JeodContainer< ContainerType, ElemType >
This particular JeodContainer type.
using stl_container_type = typename ContainerType::stl_container_type
Import the ContainerType's container type.
Detailed Description
template<typename ContainerType, typename ElemType>
class jeod::JeodPrimitiveContainer< ContainerType, ElemType >
A JeodPrimitiveContainer is a JeodContainer that contains primitive data of type ElemType.
Definition at line 80 of file primitive_container.hh.
Constructor & Destructor Documentation
JeodPrimitiveContainer() [1/3]
template<typename ContainerType, typename ElemType> jeod::JeodPrimitiveContainer< ContainerType, ElemType >::JeodPrimitiveContainer () default
Construct a JeodPrimitiveContainer.
JeodPrimitiveContainer() [2/3]
template<typename ContainerType, typename ElemType> jeod::JeodPrimitiveContainer< ContainerType, ElemType >::JeodPrimitiveContainer (const JeodPrimitiveContainer< ContainerType, ElemType > & source) inline
Copy-construct a JeodPrimitiveContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Primitive container to be copied.
Definition at line 94 of file primitive_container.hh.
JeodPrimitiveContainer() [3/3]
template<typename ContainerType, typename ElemType> jeod::JeodPrimitiveContainer< ContainerType, ElemType >::JeodPrimitiveContainer (const typename ContainerType::stl_container_type & source) inline explicit
Copy-construct a JeodPrimitiveContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Primitive container to be copied.
Definition at line 105 of file primitive_container.hh.
~JeodPrimitiveContainer()
template<typename ContainerType, typename ElemType> virtual jeod::JeodPrimitiveContainer< ContainerType, ElemType >::~JeodPrimitiveContainer () virtual default
Destruct a JeodPrimitiveContainer.
Member Function Documentation
get_item_value()
template<typename ContainerType, typename ElemType> const std::string jeod::JeodPrimitiveContainer< ContainerType, ElemType >::get_item_value () inline override virtual
Return the value of the item to be written to the checkpoint file.
JeodPrimitiveContainer use the serializer to translate values to strings.
Implements jeod::JeodCheckpointable.
Definition at line 143 of file primitive_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::checkpoint_iter, jeod::JeodPrimitiveContainer< ContainerType, ElemType >::serializer, and jeod::JeodPrimitiveSerializer< Type >::to_string().
operator=() [1/2]
template<typename ContainerType, typename ElemType> JeodPrimitiveContainer& jeod::JeodPrimitiveContainer< ContainerType, ElemType >::operator= (const JeodPrimitiveContainer< ContainerType, ElemType > & source) inline
Copy from a JeodPrimitiveContainer.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Primitive container to be copied.
Definition at line 116 of file primitive_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::operator=().
operator=() [2/2]
template<typename ContainerType, typename ElemType> JeodPrimitiveContainer& jeod::JeodPrimitiveContainer< ContainerType, ElemType >::operator= (const typename ContainerType::stl_container_type & source) inline
Copy from an STL container.
Note
This copies the Container contents, but not the Checkpointable contents.
Parameters
source Primitive container to be copied.
Definition at line 128 of file primitive_container.hh.
References jeod::JeodContainer< ContainerType, ElemType >::operator=().
perform_insert_action()
template<typename ContainerType, typename ElemType> void jeod::JeodPrimitiveContainer< ContainerType, ElemType >::perform_insert_action (const std::string & value) inline override virtual
Interpret the provided value and insert it at the end of the object.
JeodPrimitiveContainer use the serializer to interpret the input value.
Implements jeod::JeodContainer< ContainerType, ElemType >.
Definition at line 152 of file primitive_container.hh.
References jeod::JeodPrimitiveSerializer< Type >::from_string(), and jeod::JeodPrimitiveContainer< ContainerType, ElemType >::serializer.
Field Documentation
serializer
template<typename ContainerType, typename ElemType> JeodPrimitiveSerializer<ElemType> jeod::JeodPrimitiveContainer< ContainerType, ElemType >::serializer protected
Serializer / deserializer.
trick_io(**)
Definition at line 163 of file primitive_container.hh.
Referenced by jeod::JeodPrimitiveContainer< ContainerType, ElemType >::get_item_value(), and jeod::JeodPrimitiveContainer< ContainerType, ElemType >::perform_insert_action().
The documentation for this class was generated from the following file:
primitive_container.hh