JEOD: jeod::RadiationPressure Class Reference
jeod::RadiationPressure Class Reference
Radiation pressure top-level definition.
#include <radiation_pressure.hh>
Public Member Functions
RadiationPressure ()
Constructor for RadiationPressure.
virtual ~RadiationPressure ()
Destructor for RadiationPressure.
void initialize (DynManager &dyn_manager, RadiationSurface *surf_ptr, double center_grav[3])
Initialize the radiation pressure model when using a RadiationSurface (i.e.
void initialize (DynManager &dyn_manager, RadiationDefaultSurface *surf_ptr)
Initialize the radiation pressure model when using a RadiationDefaultSurface (i.e.
void update (RefFrame &vehicle_structural_frame, double center_grav[3], double scale_factor, double time)
Updates the model at each time step.
void add_third_body (RadiationThirdBody *third_body_ptr)
Adds a third body to the vector storage of third bodies.
void set_third_body_active (const char *third_body_name)
Sets a Third Body to be active when it previously was not.
void set_third_body_inactive (const char *third_body_name)
Sets a Third Body to be inactive when it previously was not.
void set_calculate_forces (bool calc_forces)
Sets the value calculate_forces.
Data Fields
bool active
Is radiation pressure desired?
double force [3]
Net force due to radiation.
double torque [3]
Net torque due to radiation.
double illum_factor
fraction of primary flux that is not eclipsed
RadiationSource source
Collection of data for radiation source.
ThermalModelRider thermal
Rider to allow dynamic thermal variation on facets in this model.
Protected Member Functions
void update_default_surface (void)
Used to update the model when the surface is a default surface.
void update_facet_surface (void)
Used to update the model when the surface comprises facets.
void initialize_environment (DynManager *dyn_mgr_ptr)
Initializes the source and third bodies.
void third_body_adjustments (double time, RefFrame &vehicle_structural_frame)
Used to modify the flux for shadowing.
int find_third_body (const char *third_body_name)
Finds the index of a third body based on its name.
Protected Attributes
bool initialized
Has model been initialized?
bool calculate_forces
Flag to indicate whether forces and torques should be calculated.
bool third_bodies_active
Flag indicates whether there are any of the third bodies currently active.
unsigned int num_third_bodies
Number of ThirdBodies available.
JeodPointerVector< RadiationThirdBody >::type third_bodies
Planetary bodies that provide shadowing or indirect, reflected, illumination.
RadiationSurface * surface_ptr
The surface over which the radiation pressure will be collected.
RadiationDefaultSurface * default_surface_ptr
If no surface is defined, use a DefaultSurface; this is the pointer to that default surface,.
DynManager * dyn_manager_ptr
Pointer to the Dynamics Manager.
Private Member Functions
RadiationPressure (const RadiationPressure &)
RadiationPressure & operator= (const RadiationPressure &)
Friends
class InputProcessor
void init_attrjeod__RadiationPressure ()
Detailed Description
Radiation pressure top-level definition.
Definition at line 93 of file radiation_pressure.hh.
Constructor & Destructor Documentation
RadiationPressure() [1/2]
jeod::RadiationPressure::RadiationPressure (void)
Constructor for RadiationPressure.
Definition at line 68 of file radiation_pressure.cc.
References active, calculate_forces, default_surface_ptr, dyn_manager_ptr, force, illum_factor, jeod::Vector3::initialize(), initialized, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, num_third_bodies, surface_ptr, third_bodies, third_bodies_active, and torque.
~RadiationPressure()
jeod::RadiationPressure::~RadiationPressure (void) virtual
Destructor for RadiationPressure.
Definition at line 394 of file radiation_pressure.cc.
References JEOD_DEREGISTER_CHECKPOINTABLE, and third_bodies.
RadiationPressure() [2/2]
jeod::RadiationPressure::RadiationPressure (const RadiationPressure &) private
Member Function Documentation
add_third_body()
void jeod::RadiationPressure::add_third_body (RadiationThirdBody * third_body_ptr)
Adds a third body to the vector storage of third bodies.
Parameters
[in] third_body_ptr pointer to ThirdBody
Definition at line 183 of file radiation_pressure.cc.
References jeod::RadiationThirdBody::active, dyn_manager_ptr, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::RadiationThirdBody::get_added_to_model(), jeod::RadiationMessages::incomplete_setup_error, jeod::RadiationThirdBody::initialize(), initialized, jeod::RadiationMessages::invalid_setup_error, jeod::RadiationThirdBody::name, num_third_bodies, jeod::RadiationThirdBody::set_added_to_model(), third_bodies, and third_bodies_active.
Referenced by initialize().
find_third_body()
int jeod::RadiationPressure::find_third_body (const char * third_body_name) protected
Finds the index of a third body based on its name.
Returns
void
Parameters
[in] third_body_name Name of ThirdBody
Definition at line 358 of file radiation_pressure.cc.
References jeod::MessageHandler::error(), jeod::RadiationMessages::invalid_function_call, num_third_bodies, and third_bodies.
Referenced by set_third_body_active(), and set_third_body_inactive().
initialize() [1/2]
void jeod::RadiationPressure::initialize (DynManager & dyn_mgr, RadiationSurface * surf_ptr, double center_grav[3])
Initialize the radiation pressure model when using a RadiationSurface (i.e.
with facets).
Parameters
[in] dyn_mgr The dynamics manager
[in] surf_ptr pointer to the radiation surface
[in] center_grav position of center of mass
Units: M
Definition at line 75 of file radiation_pressure__surface_model.cc.
References jeod::ThermalModelRider::active, add_third_body(), dyn_manager_ptr, jeod::RadiationSurface::initialize(), initialize_environment(), jeod::RadiationSource::num_bodies, jeod::RadiationSource::shadow_geometry, source, surface_ptr, thermal, third_bodies, and jeod::RadiationSource::third_body.
initialize() [2/2]
void jeod::RadiationPressure::initialize (DynManager & dyn_mgr, RadiationDefaultSurface * surf_ptr)
Initialize the radiation pressure model when using a RadiationDefaultSurface (i.e.
spherical, uniform properties.)
Parameters
[in] dyn_mgr The dynamics manager
[in] surf_ptr pointer to the radiation surface
Definition at line 71 of file radiation_pressure__default_surface.cc.
References add_third_body(), default_surface_ptr, dyn_manager_ptr, jeod::RadiationDefaultSurface::initialize(), initialize_environment(), jeod::RadiationSource::num_bodies, jeod::RadiationSource::shadow_geometry, source, third_bodies, and jeod::RadiationSource::third_body.
initialize_environment()
void jeod::RadiationPressure::initialize_environment (DynManager * dyn_mgr_ptr) protected
Initializes the source and third bodies.
Parameters
[in] dyn_mgr_ptr The dynamics manager
Definition at line 93 of file radiation_pressure.cc.
References jeod::RadiationSource::initialize(), initialized, num_third_bodies, source, and third_bodies.
Referenced by initialize().
operator=()
RadiationPressure& jeod::RadiationPressure::operator= (const RadiationPressure &) private
set_calculate_forces()
void jeod::RadiationPressure::set_calculate_forces (bool value)
Sets the value calculate_forces.
Parameters
[in] value whether forces are needed
Definition at line 379 of file radiation_pressure.cc.
References calculate_forces, force, jeod::Vector3::initialize(), and torque.
set_third_body_active()
void jeod::RadiationPressure::set_third_body_active (const char * third_body_name)
Sets a Third Body to be active when it previously was not.
Parameters
[in] third_body_name Name of ThirdBody
Definition at line 280 of file radiation_pressure.cc.
References active, dyn_manager_ptr, jeod::MessageHandler::error(), find_third_body(), jeod::RadiationMessages::invalid_function_call, jeod::RefFrameManager::subscribe_to_frame(), third_bodies, third_bodies_active, and jeod::MessageHandler::warn().
set_third_body_inactive()
void jeod::RadiationPressure::set_third_body_inactive (const char * third_body_name)
Sets a Third Body to be inactive when it previously was not.
Parameters
[in] third_body_name Name of ThirdBody
Definition at line 317 of file radiation_pressure.cc.
References active, dyn_manager_ptr, jeod::MessageHandler::error(), find_third_body(), jeod::RadiationMessages::invalid_function_call, num_third_bodies, third_bodies, third_bodies_active, jeod::RefFrameManager::unsubscribe_to_frame(), and jeod::MessageHandler::warn().
third_body_adjustments()
void jeod::RadiationPressure::third_body_adjustments (double real_time, RefFrame & veh_struc_frame) protected
Used to modify the flux for shadowing.
Parameters
[in] real_time The current time, e.g. TAI or UT1.
Units: s
[in] veh_struc_frame Structure frame of vehicle
Definition at line 159 of file radiation_pressure.cc.
References active, jeod::RadiationSource::flux_inertial, jeod::RadiationSource::flux_mag, jeod::RadiationSource::flux_struc, illum_factor, num_third_bodies, jeod::Vector3::scale(), source, and third_bodies.
Referenced by update().
update()
void jeod::RadiationPressure::update (RefFrame & veh_struc_frame, double center_grav[3], double scale_factor, double real_time)
Updates the model at each time step.
Parameters
[in] veh_struc_frame The vehicle structural reference frame.
[in] center_grav position of center of mass
Units: M
[in] scale_factor the scale between the simulator time and the dynamic time.
[in] real_time The current time, e.g. TAI or UT1.
Units: s
Definition at line 114 of file radiation_pressure.cc.
References active, jeod::RadiationSource::calculate_flux(), jeod::ThermalFacetRider::cycle_time, jeod::JeodSimulationInterface::get_job_cycle(), source, surface_ptr, third_bodies_active, third_body_adjustments(), update_default_surface(), and update_facet_surface().
update_default_surface()
void jeod::RadiationPressure::update_default_surface (void) protected
Used to update the model when the surface is a default surface.
Definition at line 96 of file radiation_pressure__default_surface.cc.
References active, calculate_forces, default_surface_ptr, jeod::RadiationBaseFacet::F_absorption, jeod::RadiationBaseFacet::F_diffuse, jeod::RadiationBaseFacet::F_specular, jeod::RadiationSource::flux_mag, jeod::RadiationSource::flux_struc_hat, force, jeod::RadiationDefaultSurface::incident_radiation(), jeod::Vector3::initialize(), jeod::RadiationBaseFacet::initialize_runtime_values(), jeod::RadiationBaseFacet::interact_with_third_body(), num_third_bodies, source, jeod::Vector3::sum(), jeod::RadiationDefaultSurface::thermal_update(), third_bodies, and torque.
Referenced by update().
update_facet_surface()
void jeod::RadiationPressure::update_facet_surface (void) protected
Used to update the model when the surface comprises facets.
Definition at line 111 of file radiation_pressure__surface_model.cc.
References jeod::ThermalModelRider::active, active, calculate_forces, jeod::Vector3::copy(), jeod::RadiationSurface::equalize_absorption_emission(), jeod::RadiationSource::flux_mag, jeod::RadiationSource::flux_struc_hat, force, jeod::RadiationSurface::force, jeod::RadiationSurface::incident_radiation(), jeod::RadiationSurface::initialize_runtime_values(), jeod::RadiationSurface::interact_with_third_body(), num_third_bodies, jeod::RadiationSurface::radiation_pressure(), source, surface_ptr, thermal, third_bodies, torque, jeod::RadiationSurface::torque, and jeod::ThermalModelRider::update().
Referenced by update().
Friends And Related Function Documentation
init_attrjeod__RadiationPressure
void init_attrjeod__RadiationPressure () friend
InputProcessor
friend class InputProcessor friend
Definition at line 95 of file radiation_pressure.hh.
Field Documentation
active
bool jeod::RadiationPressure::active
Is radiation pressure desired?
trick_units(–)
Definition at line 103 of file radiation_pressure.hh.
Referenced by RadiationPressure(), set_third_body_active(), set_third_body_inactive(), third_body_adjustments(), update(), update_default_surface(), and update_facet_surface().
calculate_forces
bool jeod::RadiationPressure::calculate_forces protected
Flag to indicate whether forces and torques should be calculated.
trick_units(–)
Definition at line 140 of file radiation_pressure.hh.
Referenced by RadiationPressure(), set_calculate_forces(), update_default_surface(), and update_facet_surface().
default_surface_ptr
RadiationDefaultSurface* jeod::RadiationPressure::default_surface_ptr protected
If no surface is defined, use a DefaultSurface; this is the pointer to that default surface,.
trick_units(–)
Definition at line 170 of file radiation_pressure.hh.
Referenced by initialize(), RadiationPressure(), and update_default_surface().
dyn_manager_ptr
DynManager* jeod::RadiationPressure::dyn_manager_ptr protected
Pointer to the Dynamics Manager.
trick_units(–)
Definition at line 175 of file radiation_pressure.hh.
Referenced by add_third_body(), initialize(), RadiationPressure(), set_third_body_active(), and set_third_body_inactive().
force
double jeod::RadiationPressure::force[3]
Net force due to radiation.
trick_units(N)
Definition at line 108 of file radiation_pressure.hh.
Referenced by RadiationPressure(), set_calculate_forces(), update_default_surface(), and update_facet_surface().
illum_factor
double jeod::RadiationPressure::illum_factor
fraction of primary flux that is not eclipsed
trick_units(–)
Definition at line 118 of file radiation_pressure.hh.
Referenced by RadiationPressure(), and third_body_adjustments().
initialized
bool jeod::RadiationPressure::initialized protected
Has model been initialized?
trick_units(–)
Definition at line 135 of file radiation_pressure.hh.
Referenced by add_third_body(), initialize_environment(), and RadiationPressure().
num_third_bodies
unsigned int jeod::RadiationPressure::num_third_bodies protected
Number of ThirdBodies available.
trick_units(count)
Definition at line 151 of file radiation_pressure.hh.
Referenced by add_third_body(), find_third_body(), initialize_environment(), RadiationPressure(), set_third_body_inactive(), third_body_adjustments(), update_default_surface(), and update_facet_surface().
source
RadiationSource jeod::RadiationPressure::source
Collection of data for radiation source.
trick_units(–)
Definition at line 123 of file radiation_pressure.hh.
Referenced by initialize(), initialize_environment(), third_body_adjustments(), update(), update_default_surface(), and update_facet_surface().
surface_ptr
RadiationSurface* jeod::RadiationPressure::surface_ptr protected
The surface over which the radiation pressure will be collected.
If this is NULL, use the default radiation surface (which is a whole separate entity from a RadiationSurface.trick_units(–)
Definition at line 164 of file radiation_pressure.hh.
Referenced by initialize(), RadiationPressure(), update(), and update_facet_surface().
thermal
ThermalModelRider jeod::RadiationPressure::thermal
Rider to allow dynamic thermal variation on facets in this model.
trick_units(–)
Definition at line 128 of file radiation_pressure.hh.
Referenced by initialize(), and update_facet_surface().
third_bodies
JeodPointerVector<RadiationThirdBody>::type jeod::RadiationPressure::third_bodies protected
Planetary bodies that provide shadowing or indirect, reflected, illumination.
trick_io(**)
Definition at line 157 of file radiation_pressure.hh.
Referenced by add_third_body(), find_third_body(), initialize(), initialize_environment(), RadiationPressure(), set_third_body_active(), set_third_body_inactive(), third_body_adjustments(), update_default_surface(), update_facet_surface(), and ~RadiationPressure().
third_bodies_active
bool jeod::RadiationPressure::third_bodies_active protected
Flag indicates whether there are any of the third bodies currently active.
trick_units(–)
Definition at line 146 of file radiation_pressure.hh.
Referenced by add_third_body(), RadiationPressure(), set_third_body_active(), set_third_body_inactive(), and update().
torque
double jeod::RadiationPressure::torque[3]
Net torque due to radiation.
trick_units(N*m)
Definition at line 113 of file radiation_pressure.hh.
Referenced by RadiationPressure(), set_calculate_forces(), update_default_surface(), and update_facet_surface().
The documentation for this class was generated from the following files:
radiation_pressure.hh
radiation_pressure.cc
radiation_pressure__default_surface.cc
radiation_pressure__surface_model.cc