JEOD: jeod::RadiationThirdBody Class Reference
jeod::RadiationThirdBody Class Reference
Provide information on bodies that may cause shadowing or reflected illumination.
#include <radiation_third_body.hh>
Public Types
enum ShadowGeometry { Cylindrical = 0, Cyl = 1, Conical = 2, Con = 3 }
distinguishes between conical and cylindrical shadowing
Public Member Functions
RadiationThirdBody ()
Constructor.
virtual ~RadiationThirdBody ()
virtual void initialize (DynManager *dyn_mgr_ptr)
initializes the third body
void calculate_shadow (void)
Calculates the effect of shadowing by a third body.
void convert_shadow_from_int (int geometry)
convert from the old style framework in which the shadow geometry was owned by the RadiationSource (same for all third bodies) to the new style framework where the geometry is owned by each ThirdBody
virtual double process_third_body (double real_time, RefFrame &veh_struc_frame)
Primary executable for handling the Third Body effects.
void set_name (std::string name_in)
Setter for the name.
virtual void accumulate_refl_flux (RadiationBaseFacet *veh_surf_elem, bool calculate_forces)
To provide base class null implementation.
virtual void accumulate_rad_flux (RadiationBaseFacet *veh_surf_elem, bool calculate_forces)
To provide base class null implementation.
virtual bool is_interactive ()
Identifies this class as one that does not produce a radiaiton field.
bool get_added_to_model ()
Returns information on whether the body has already been used in one RadiationPressure model.
void set_added_to_model (bool value)
Sets the added_to_model value.
Data Fields
RadiationSource * primary_source_ptr
Pointer to the primary illumination source.
ShadowGeometry shadow_geometry
Flag indicating cylindrical / conical shadow geometry.
bool force_state_update
Flag to indicate whether to enforce an update to the third-body body-state.
std::string name
Name of planet.
bool active
Model on/off flag.
double update_interval
Time interval between third body state updates.
double radius
Radius of RadiationThirdBody.
double output_flux [3]
Calculated value.
RefFrame * local_frame_ptr
Pointer to the local reference frame, for determining position of this object.
Protected Member Functions
double generate_alpha (double rho_adj, double delta)
generate_alpha(rho_adj, delta: generates an approximate alpha-value given a relative disk size and fraction of maximum possible eclipse
bool test_for_state_update (double time)
Tests for necessity of updating third body state, and calls appropriate update method (polymorphic) if needed.
virtual bool update_third_body_state (void)
Updates the state of the Third Body.
Protected Attributes
bool added_to_model
Flag to indicate whether body has already been added to a model.
bool initialized
Flag to indicate that initialization has been complete.
double illum_factor
Value between 0 and 1 representing the fraction of possible flux that is actually incident after shadowing effects.
double last_update_time
Time at which the third body state was last updated.
Planet * planet_link
Pointer to the associated Planet object.
double r_plus
The value (radius + R_source)
double r_minus
The value (radius - R_source)
double r_ratio
The ratio (radius / R_source)
double r_par
Component of vector from RadiationThirdBody to vehicle that is parallel to vector from primary source to RadiationThirdBody.
double r_perp
Component of vector from RadiationThirdBody to vehicle that is perpendicular to vector from primary source to RadiationThirdBody.
double third_to_cg_inrtl [3]
Vector from RadiationThirdBody to vehicle center of gravity, in inertial RF.
double source_to_third_inrtl [3]
Vector from the primary source to the RadiationThirdBody in inertial RF.
double d_source_to_third
Magnitude of source_to_third.
double source_to_third_hat_inrtl [3]
Unit vector of source_to_third.
Private Member Functions
RadiationThirdBody (const RadiationThirdBody &)
RadiationThirdBody & operator= (const RadiationThirdBody &)
Friends
class InputProcessor
void init_attrjeod__RadiationThirdBody ()
Detailed Description
Provide information on bodies that may cause shadowing or reflected illumination.
Definition at line 84 of file radiation_third_body.hh.
Member Enumeration Documentation
ShadowGeometry
enum jeod::RadiationThirdBody::ShadowGeometry
distinguishes between conical and cylindrical shadowing
Enumerator
Cylindrical
planet casts a cylindrical shadow
Cyl
planet casts a cylindrical shadow
Conical
planet casts a conical shadow
Con
planet casts a conical shadow
Definition at line 92 of file radiation_third_body.hh.
Constructor & Destructor Documentation
RadiationThirdBody() [1/2]
jeod::RadiationThirdBody::RadiationThirdBody ()
Constructor.
Definition at line 57 of file radiation_third_body.cc.
References jeod::Vector3::initialize(), output_flux, source_to_third_hat_inrtl, source_to_third_inrtl, and third_to_cg_inrtl.
~RadiationThirdBody()
virtual jeod::RadiationThirdBody::~RadiationThirdBody () inline virtual
Definition at line 238 of file radiation_third_body.hh.
RadiationThirdBody() [2/2]
jeod::RadiationThirdBody::RadiationThirdBody (const RadiationThirdBody &) private
Member Function Documentation
accumulate_rad_flux()
virtual void jeod::RadiationThirdBody::accumulate_rad_flux (RadiationBaseFacet * veh_surf_elem, bool calculate_forces) inline virtual
To provide base class null implementation.
Parameters
veh_surf_elem The facet of the vehicle.
calculate_forces pass-through flag.
Definition at line 272 of file radiation_third_body.hh.
Referenced by jeod::RadiationBaseFacet::interact_with_third_body().
accumulate_refl_flux()
virtual void jeod::RadiationThirdBody::accumulate_refl_flux (RadiationBaseFacet * veh_surf_elem, bool calculate_forces) inline virtual
To provide base class null implementation.
Parameters
veh_surf_elem The facet of the vehicle.
calculate_forces pass-through flag.
Definition at line 264 of file radiation_third_body.hh.
Referenced by jeod::RadiationBaseFacet::interact_with_third_body().
calculate_shadow()
void jeod::RadiationThirdBody::calculate_shadow (void)
Calculates the effect of shadowing by a third body.
NOTE - This method is intended to be an internal call so should be protected However, doing so would be a change to the API. Delay for JEOD4.0.
Definition at line 210 of file radiation_third_body.cc.
References active, Con, Conical, Cyl, Cylindrical, jeod::RadiationSource::d_source_to_cg, d_source_to_third, jeod::Vector3::diff(), jeod::Vector3::dot(), jeod::MessageHandler::error(), generate_alpha(), illum_factor, initialized, jeod::RadiationMessages::invalid_setup_error, name, primary_source_ptr, r_minus, r_par, r_perp, r_plus, r_ratio, radius, jeod::RadiationSource::radius, shadow_geometry, jeod::RadiationSource::source_to_cg, source_to_third_hat_inrtl, source_to_third_inrtl, third_to_cg_inrtl, and jeod::Vector3::vmagsq().
Referenced by process_third_body().
convert_shadow_from_int()
void jeod::RadiationThirdBody::convert_shadow_from_int (int old_shadow_geometry)
convert from the old style framework in which the shadow geometry was owned by the RadiationSource (same for all third bodies) to the new style framework where the geometry is owned by each ThirdBody
Parameters
[in] old_shadow_geometry integer representation of the shadow geometry enumeration.
Definition at line 413 of file radiation_third_body.cc.
References jeod::MessageHandler::inform(), jeod::RadiationMessages::invalid_setup_error, and shadow_geometry.
generate_alpha()
double jeod::RadiationThirdBody::generate_alpha (double rho_adj, double delta) protected
generate_alpha(rho_adj, delta: generates an approximate alpha-value given a relative disk size and fraction of maximum possible eclipse
Parameters
[in] rho_adj relative disk size
[in] delta fraction of eclipse achieved.
Definition at line 380 of file radiation_third_body.cc.
Referenced by calculate_shadow().
get_added_to_model()
bool jeod::RadiationThirdBody::get_added_to_model () inline
Returns information on whether the body has already been used in one RadiationPressure model.
Protects against multiple use of one ThirdBody instance.
Returns
added_to_model
Definition at line 287 of file radiation_third_body.hh.
References added_to_model.
Referenced by jeod::RadiationPressure::add_third_body().
initialize()
void jeod::RadiationThirdBody::initialize (DynManager * dyn_mgr_ptr) virtual
initializes the third body
Parameters
[in] dyn_mgr_ptr pointer to the dynamics manager
Definition at line 92 of file radiation_third_body.cc.
References active, jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_planet(), jeod::BasePlanet::inertial, jeod::RadiationSource::inertial_frame_ptr, initialized, jeod::RadiationMessages::invalid_setup_error, local_frame_ptr, name, jeod::BasePlanet::pfix, planet_link, primary_source_ptr, jeod::Planet::r_eq, r_minus, r_plus, r_ratio, radius, jeod::RadiationSource::radius, and jeod::RefFrameManager::subscribe_to_frame().
Referenced by jeod::RadiationPressure::add_third_body().
is_interactive()
virtual bool jeod::RadiationThirdBody::is_interactive () inline virtual
Identifies this class as one that does not produce a radiaiton field.
Returns
false
Definition at line 279 of file radiation_third_body.hh.
operator=()
RadiationThirdBody& jeod::RadiationThirdBody::operator= (const RadiationThirdBody &) private
process_third_body()
double jeod::RadiationThirdBody::process_third_body (double real_time, RefFrame & veh_struc_frame) virtual
Primary executable for handling the Third Body effects.
Returns
shading fraction
Parameters
[in] real_time Current time.
Units: s
[in] veh_struc_frame Unused.
Definition at line 435 of file radiation_third_body.cc.
References active, calculate_shadow(), jeod::MessageHandler::error(), illum_factor, initialized, jeod::RadiationMessages::invalid_setup_error, name, jeod::RadiationMessages::operational_setup_error, and test_for_state_update().
set_added_to_model()
void jeod::RadiationThirdBody::set_added_to_model (bool value) inline
Sets the added_to_model value.
Parameters
value New value
Definition at line 293 of file radiation_third_body.hh.
References added_to_model.
Referenced by jeod::RadiationPressure::add_third_body().
set_name()
void jeod::RadiationThirdBody::set_name (std::string name_in) inline
Setter for the name.
Definition at line 254 of file radiation_third_body.hh.
References name.
test_for_state_update()
bool jeod::RadiationThirdBody::test_for_state_update (double real_time) protected
Tests for necessity of updating third body state, and calls appropriate update method (polymorphic) if needed.
Parameters
[in] real_time Current time
Units: s
Definition at line 478 of file radiation_third_body.cc.
References force_state_update, last_update_time, update_interval, and update_third_body_state().
Referenced by process_third_body().
update_third_body_state()
bool jeod::RadiationThirdBody::update_third_body_state (void) protected virtual
Updates the state of the Third Body.
Because the ThirdBody may be associated with multiple vehicles, and because its state typically changes much more slowly than the vehicle anyway, it is not always necessary to update the ThirdBodyState.
Definition at line 502 of file radiation_third_body.cc.
References active, jeod::RefFrame::compute_position_from(), d_source_to_third, jeod::MessageHandler::error(), jeod::RadiationSource::inertial_frame_ptr, jeod::RadiationMessages::invalid_setup_error, local_frame_ptr, name, primary_source_ptr, jeod::Vector3::scale(), source_to_third_hat_inrtl, source_to_third_inrtl, and jeod::Vector3::vmag().
Referenced by test_for_state_update().
Friends And Related Function Documentation
init_attrjeod__RadiationThirdBody
void init_attrjeod__RadiationThirdBody () friend
InputProcessor
friend class InputProcessor friend
Definition at line 86 of file radiation_third_body.hh.
Field Documentation
active
bool jeod::RadiationThirdBody::active
Model on/off flag.
trick_units(–)
Definition at line 124 of file radiation_third_body.hh.
Referenced by jeod::RadiationPressure::add_third_body(), calculate_shadow(), initialize(), process_third_body(), and update_third_body_state().
added_to_model
bool jeod::RadiationThirdBody::added_to_model protected
Flag to indicate whether body has already been added to a model.
trick_units(–)
Definition at line 156 of file radiation_third_body.hh.
Referenced by get_added_to_model(), and set_added_to_model().
d_source_to_third
double jeod::RadiationThirdBody::d_source_to_third protected
Magnitude of source_to_third.
trick_units(m)
Definition at line 226 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and update_third_body_state().
force_state_update
bool jeod::RadiationThirdBody::force_state_update
Flag to indicate whether to enforce an update to the third-body body-state.
Default: true Self-resets to false after each use.trick_units(–)
Definition at line 114 of file radiation_third_body.hh.
Referenced by test_for_state_update().
illum_factor
double jeod::RadiationThirdBody::illum_factor protected
Value between 0 and 1 representing the fraction of possible flux that is actually incident after shadowing effects.
trick_units(–)
Definition at line 167 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and process_third_body().
initialized
bool jeod::RadiationThirdBody::initialized protected
Flag to indicate that initialization has been complete.
trick_units(–)
Definition at line 161 of file radiation_third_body.hh.
Referenced by calculate_shadow(), initialize(), and process_third_body().
last_update_time
double jeod::RadiationThirdBody::last_update_time protected
Time at which the third body state was last updated.
trick_units(s)
Definition at line 172 of file radiation_third_body.hh.
Referenced by test_for_state_update().
local_frame_ptr
RefFrame* jeod::RadiationThirdBody::local_frame_ptr
Pointer to the local reference frame, for determining position of this object.
trick_units(–)
Definition at line 147 of file radiation_third_body.hh.
Referenced by initialize(), and update_third_body_state().
name
std::string jeod::RadiationThirdBody::name
Name of planet.
trick_units(–)
Definition at line 119 of file radiation_third_body.hh.
Referenced by jeod::RadiationPressure::add_third_body(), calculate_shadow(), initialize(), process_third_body(), set_name(), and update_third_body_state().
output_flux
double jeod::RadiationThirdBody::output_flux[3]
Calculated value.
Set only in derived class RadiationReflectingThirdBody.trick_units(–)
Definition at line 141 of file radiation_third_body.hh.
Referenced by RadiationThirdBody().
planet_link
Planet* jeod::RadiationThirdBody::planet_link protected
Pointer to the associated Planet object.
trick_units(–)
Definition at line 178 of file radiation_third_body.hh.
Referenced by initialize().
primary_source_ptr
RadiationSource* jeod::RadiationThirdBody::primary_source_ptr
Pointer to the primary illumination source.
trick_units(–)
Definition at line 102 of file radiation_third_body.hh.
Referenced by calculate_shadow(), initialize(), and update_third_body_state().
r_minus
double jeod::RadiationThirdBody::r_minus protected
The value (radius - R_source)
trick_units(–)
Definition at line 188 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and initialize().
r_par
double jeod::RadiationThirdBody::r_par protected
Component of vector from RadiationThirdBody to vehicle that is parallel to vector from primary source to RadiationThirdBody.
trick_units(m)
Definition at line 201 of file radiation_third_body.hh.
Referenced by calculate_shadow().
r_perp
double jeod::RadiationThirdBody::r_perp protected
Component of vector from RadiationThirdBody to vehicle that is perpendicular to vector from primary source to RadiationThirdBody.
trick_units(–)
Definition at line 207 of file radiation_third_body.hh.
Referenced by calculate_shadow().
r_plus
double jeod::RadiationThirdBody::r_plus protected
The value (radius + R_source)
trick_units(–)
Definition at line 183 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and initialize().
r_ratio
double jeod::RadiationThirdBody::r_ratio protected
The ratio (radius / R_source)
trick_units(–)
Definition at line 193 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and initialize().
radius
double jeod::RadiationThirdBody::radius
Radius of RadiationThirdBody.
Note - this is set automatically if RTB is a planet, but must be set manually if RTB is a DynBody.trick_units(m)
Definition at line 135 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and initialize().
shadow_geometry
ShadowGeometry jeod::RadiationThirdBody::shadow_geometry
Flag indicating cylindrical / conical shadow geometry.
trick_units(–)
Definition at line 107 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and convert_shadow_from_int().
source_to_third_hat_inrtl
double jeod::RadiationThirdBody::source_to_third_hat_inrtl[3] protected
Unit vector of source_to_third.
trick_units(–)
Definition at line 231 of file radiation_third_body.hh.
Referenced by calculate_shadow(), RadiationThirdBody(), and update_third_body_state().
source_to_third_inrtl
double jeod::RadiationThirdBody::source_to_third_inrtl[3] protected
Vector from the primary source to the RadiationThirdBody in inertial RF.
trick_units(m)
Definition at line 221 of file radiation_third_body.hh.
Referenced by calculate_shadow(), RadiationThirdBody(), and update_third_body_state().
third_to_cg_inrtl
double jeod::RadiationThirdBody::third_to_cg_inrtl[3] protected
Vector from RadiationThirdBody to vehicle center of gravity, in inertial RF.
trick_units(m)
Definition at line 213 of file radiation_third_body.hh.
Referenced by calculate_shadow(), and RadiationThirdBody().
update_interval
double jeod::RadiationThirdBody::update_interval
Time interval between third body state updates.
trick_units(s)
Definition at line 129 of file radiation_third_body.hh.
Referenced by test_for_state_update().
The documentation for this class was generated from the following files:
radiation_third_body.hh
radiation_third_body.cc