JEOD: jeod::De4xxEphemeris Class Reference
jeod::De4xxEphemeris Class Reference
The S_define-level class that provides planetary ephemerides.
#include <de4xx_ephem.hh>
Public Member Functions
De4xxEphemeris (void)
De4xxEphemeris default constructor.
~De4xxEphemeris (void) override
De4xxEphemeris destructor.
void initialize_model (const TimeManager &time_manager, DynManager &dyn_manager, const std::string &time_type="TT")
Initialize the De4xxEphemeris model.
void initialize_model (const TimeManager &time_manager, EphemeridesManager &ephem_manager, const std::string &time_type="TT")
Initialize the De4xxEphemeris model.
void propagate_lunar_rnp (void)
Propagate the lunar orientation to the current time.
void shutdown (void)
Free resources allocated by the De4xxEphemeris model.
void activate (void) override
Nominally, activate the object.
void deactivate (void) override
Deactivate the De4xxEphemeris object.
double timestamp (void) const override
Return time of last update.
const char * get_name (void) const override
Return model name.
void ephem_initialize (EphemeridesManager &ephem_manager) override
Complete the initialization process.
void ephem_activate (EphemeridesManager &ephem_manager) override
Mark appropriate items in the model as active.
void ephem_build_tree (EphemeridesManager &ephem_manager) override
Construct the ephemeris model portions of the reference frame tree.
void ephem_update (void) override
Update ephemerides for subscribed items.
bool time_is_in_range (void) const
Check whether the specified time is represented in the JPL ephemeris file.
void set_model_number (int denum_in)
Set ephemeris model number.
uint32_t get_model_number ()
Get Ephemeris model number.
const De4xxFileHeader & get_header_data ()
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Data Fields
bool active
Is the model active? This is set to true by the constructor.
bool * selected_items
Used at initialization time only to selectively enable/disable portions of the model.
Protected Attributes
De4xxFile file
The ephemeris file model.
bool force_update
Is an update needed even if the time hasn't changed?
unsigned int nactive_items
Number of items that are currently active.
De4xxEphemItem * item_data
Data pertaining to the points for which translational states are calculated.
char * ident
Identifier for this model, computed from the supplied file.
double update_time
Time of last update, dynamic time seconds.
EphemerisPoint * points
The planets and barycenter points, in De4xxEphemBodies FileBodies order.
EphemerisZXZOrientation lunar_orientation
Lunar orientation.
EphemerisRefFrame earth_moon_barycenter_frame
Earth-Moon barycenter reference frame.
EphemerisRefFrame solar_system_barycenter_frame
Solar system barycenter reference frame.
De4xxEphemItem * root_item
The root point in the reference frame tree.
const TimeStandard * time_tt
The source of ephemeris time information.
const TimeDyn * time_dyn
The source of dynamic time information.
int * body_to_file_idx
Mapping from De4xxEphemBodies numbers to De4xxFileBodies numbers.
Private Member Functions
void initialize_time (const TimeManager &time_manager, const std::string &time_type)
Initialize De4xxEphemeris timing.
void initialize_file (void)
Initialize the De4xxEphemeris file.
void initialize_items (EphemeridesManager &ephem_manager)
Initialize the De4xxEphemeris item data.
unsigned int activate_nodes (void)
Mark appropriate items in the model as active.
unsigned int activate_em_nodes (unsigned int tot_active)
Adjust Earth, Moon, and Earth-Moon barycenter activity.
void determine_root_node (void)
Determine which item should be the root of the ref frame tree.
De4xxEphemeris (const De4xxEphemeris &)
Not implemented.
De4xxEphemeris & operator= (const De4xxEphemeris &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__De4xxEphemeris ()
Detailed Description
The S_define-level class that provides planetary ephemerides.
The De4xxEphemeris class constructs the ephemeris reference frame tree and updates the states of the planets based on data from a DE4xx ephemeris model.
Definition at line 196 of file de4xx_ephem.hh.
Constructor & Destructor Documentation
De4xxEphemeris() [1/2]
jeod::De4xxEphemeris::De4xxEphemeris (void)
De4xxEphemeris default constructor.
Definition at line 120 of file de4xx_ephem.cc.
References body_to_file_idx, jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_EML1, jeod::De4xxBase::De4xx_Ephem_ENutation, jeod::De4xxBase::De4xx_Ephem_Jupiter, jeod::De4xxBase::De4xx_Ephem_LLibration, jeod::De4xxBase::De4xx_Ephem_Mars, jeod::De4xxBase::De4xx_Ephem_Mercury, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxBase::De4xx_Ephem_Neptune, jeod::De4xxBase::De4xx_Ephem_Pluto, jeod::De4xxBase::De4xx_Ephem_Saturn, jeod::De4xxBase::De4xx_Ephem_SSbary, jeod::De4xxBase::De4xx_Ephem_Sun, jeod::De4xxBase::De4xx_Ephem_Uranus, jeod::De4xxBase::De4xx_Ephem_Venus, jeod::De4xxBase::De4xx_File_EMbary, jeod::De4xxBase::De4xx_File_ENutation, jeod::De4xxBase::De4xx_File_Jupiter, jeod::De4xxBase::De4xx_File_LLibration, jeod::De4xxBase::De4xx_File_Mars, jeod::De4xxBase::De4xx_File_MaxEntries, jeod::De4xxBase::De4xx_File_Mercury, jeod::De4xxBase::De4xx_File_Moon, jeod::De4xxBase::De4xx_File_Neptune, jeod::De4xxBase::De4xx_File_Pluto, jeod::De4xxBase::De4xx_File_Saturn, jeod::De4xxBase::De4xx_File_Sun, jeod::De4xxBase::De4xx_File_Uranus, jeod::De4xxBase::De4xx_File_Venus, earth_moon_barycenter_frame, jeod::EphemerisOrientation::enable(), jeod::EphemerisItem::enable(), jeod::EphemerisItem::get_name(), jeod::De4xxEphemItem::index, jeod::De4xxEphemItem::item, item_data, JEOD_ALLOC_CLASS_ARRAY, JEOD_ALLOC_PRIM_ARRAY, lunar_orientation, jeod::De4xxEphemItem::name, jeod::De4xxBase::number_jeod_items(), jeod::De4xxBase::number_trans_points(), points, selected_items, jeod::EphemerisItem::set_name(), jeod::RefFrame::set_name(), jeod::EphemerisItem::set_owner(), and solar_system_barycenter_frame.
~De4xxEphemeris()
jeod::De4xxEphemeris::~De4xxEphemeris (void) override
De4xxEphemeris destructor.
Definition at line 219 of file de4xx_ephem.cc.
References body_to_file_idx, item_data, JEOD_DELETE_ARRAY, points, selected_items, and shutdown().
De4xxEphemeris() [2/2]
jeod::De4xxEphemeris::De4xxEphemeris (const De4xxEphemeris &) private
Not implemented.
Member Function Documentation
activate()
void jeod::De4xxEphemeris::activate (void) override virtual
Nominally, activate the object.
In the case of a De4xxEphemeris object, an inactive object cannot be activated.
Implements jeod::ActivateInterface.
Definition at line 252 of file de4xx_ephem.cc.
References active, jeod::MessageHandler::error(), and jeod::EphemeridesMessages::internal_error.
activate_em_nodes()
unsigned int jeod::De4xxEphemeris::activate_em_nodes (unsigned int tot_active) private
Adjust Earth, Moon, and Earth-Moon barycenter activity.
Returns
Void
Parameters
[in] tot_active Number active translation nodes
Definition at line 578 of file de4xx_ephem.cc.
References jeod::EphemerisItem::activate(), jeod::De4xxEphemItem::Active, jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxEphemItem::Deselected, jeod::EphemerisItem::enable(), jeod::De4xxEphemItem::enabled_item, jeod::MessageHandler::fail(), jeod::De4xxEphemItem::Inactive, jeod::EphemeridesMessages::inconsistent_setup, jeod::De4xxEphemItem::InTree, jeod::De4xxEphemItem::item, item_data, nactive_items, jeod::De4xxEphemItem::name, and jeod::De4xxEphemItem::status.
Referenced by ephem_activate().
activate_nodes()
unsigned int jeod::De4xxEphemeris::activate_nodes (void) private
Mark appropriate items in the model as active.
Returns
Void
Definition at line 534 of file de4xx_ephem.cc.
References jeod::De4xxEphemItem::Active, jeod::De4xxEphemItem::Deselected, jeod::De4xxEphemItem::enabled_item, file, jeod::De4xxFile::file_spec, jeod::EphemerisItem::get_enabled_item(), jeod::De4xxFileSpec::get_model_number(), jeod::De4xxEphemItem::Inactive, jeod::De4xxEphemItem::InTree, jeod::EphemerisItem::is_active(), jeod::De4xxEphemItem::item, item_data, nactive_items, jeod::De4xxBase::number_jeod_items(), jeod::De4xxBase::number_trans_points(), and jeod::De4xxEphemItem::status.
Referenced by ephem_activate().
deactivate()
void jeod::De4xxEphemeris::deactivate (void) override virtual
Deactivate the De4xxEphemeris object.
Implements jeod::ActivateInterface.
Definition at line 269 of file de4xx_ephem.cc.
References active.
determine_root_node()
void jeod::De4xxEphemeris::determine_root_node (void) private
Determine which item should be the root of the ref frame tree.
Definition at line 646 of file de4xx_ephem.cc.
References jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxBase::De4xx_Ephem_SSbary, jeod::De4xxEphemItem::enabled_item, file, jeod::De4xxFile::file_spec, jeod::De4xxFileSpec::get_model_number(), jeod::De4xxEphemItem::Inactive, jeod::De4xxEphemItem::IsRoot, jeod::De4xxEphemItem::item, item_data, nactive_items, jeod::De4xxBase::number_trans_points(), root_item, and jeod::De4xxEphemItem::status.
Referenced by ephem_activate().
ephem_activate()
void jeod::De4xxEphemeris::ephem_activate (EphemeridesManager & ephem_manager) override virtual
Mark appropriate items in the model as active.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 712 of file de4xx_ephem.cc.
References activate_em_nodes(), activate_nodes(), jeod::De4xxEphemItem::Active, active, jeod::De4xxFileItem::active, body_to_file_idx, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_LLibration, jeod::De4xxBase::De4xx_Ephem_Sun, jeod::De4xxBase::De4xx_File_ENutation, jeod::De4xxBase::De4xx_File_LLibration, determine_root_node(), file, jeod::De4xxFile::file_spec, force_update, jeod::De4xxFileSpec::get_model_number(), jeod::De4xxFile::item, item_data, nactive_items, jeod::De4xxBase::number_jeod_items(), and jeod::De4xxEphemItem::status.
ephem_build_tree()
void jeod::De4xxEphemeris::ephem_build_tree (EphemeridesManager & ephem_manager) override virtual
Construct the ephemeris model portions of the reference frame tree.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 771 of file de4xx_ephem.cc.
References jeod::De4xxEphemItem::Active, active, jeod::RefFrameManager::add_frame_to_tree(), jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxBase::De4xx_Ephem_SSbary, jeod::De4xxEphemItem::Deselected, jeod::De4xxEphemItem::enabled_item, jeod::MessageHandler::fail(), file, jeod::De4xxFile::file_spec, jeod::De4xxEphemItem::frame, jeod::De4xxFileSpec::get_model_number(), jeod::EphemeridesMessages::inconsistent_setup, jeod::De4xxEphemItem::item, item_data, jeod::De4xxEphemItem::name, jeod::De4xxBase::number_trans_points(), jeod::RefFrame::remove_from_parent(), root_item, and jeod::De4xxEphemItem::status.
ephem_initialize()
void jeod::De4xxEphemeris::ephem_initialize (EphemeridesManager & ephem_manager) override virtual
Complete the initialization process.
This method should be called after all other ephemeris models have completed their basic initialization and after all planets have registered themselves with the ephemeris manager.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 494 of file de4xx_ephem.cc.
References active, jeod::De4xxEphemItem::Deselected, file, jeod::De4xxFile::file_spec, jeod::De4xxEphemItem::frame, jeod::De4xxFileSpec::get_model_number(), jeod::EphemerisItem::get_target_frame(), jeod::De4xxEphemItem::item, item_data, jeod::De4xxBase::number_jeod_items(), and jeod::De4xxEphemItem::status.
ephem_update()
void jeod::De4xxEphemeris::ephem_update (void) override virtual
Update ephemerides for subscribed items.
Implements jeod::EphemerisInterface.
Definition at line 831 of file de4xx_ephem.cc.
References jeod::De4xxEphemItem::Active, active, jeod::De4xxFileHeader::be_em_dist_ratio, jeod::De4xxFileHeader::bm_em_dist_ratio, body_to_file_idx, jeod::Numerical::compare_exact(), jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_LLibration, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxBase::De4xx_Ephem_Sun, jeod::De4xxBase::De4xx_File_LLibration, jeod::De4xxEphemItem::enabled_item, file, force_update, jeod::De4xxFile::header, jeod::De4xxEphemItem::item, jeod::De4xxFile::item, item_data, lunar_orientation, nactive_items, points, root_item, jeod::JeodBaseTime::seconds, jeod::De4xxFileItem::state, time_dyn, time_tt, jeod::TimeStandard::trunc_julian_time, jeod::EphemerisPoint::update(), jeod::EphemerisZXZOrientation::update(), jeod::De4xxFile::update(), jeod::EphemerisPoint::update_scaled(), and update_time.
get_header_data()
const De4xxFileHeader& jeod::De4xxEphemeris::get_header_data () inline
Definition at line 268 of file de4xx_ephem.hh.
References file, and jeod::De4xxFile::header.
get_model_number()
uint32_t jeod::De4xxEphemeris::get_model_number () inline
Get Ephemeris model number.
This number is used to specify the de file to use the pathname is of the form PWD/build/de4xx_lib/libde<denumIn>.so
Definition at line 264 of file de4xx_ephem.hh.
References file, jeod::De4xxFile::file_spec, and jeod::De4xxFileSpec::get_model_number().
get_name()
const char * jeod::De4xxEphemeris::get_name (void) const override virtual
Return model name.
Returns
Name
Implements jeod::EphemerisInterface.
Definition at line 296 of file de4xx_ephem.cc.
References ident.
initialize_file()
void jeod::De4xxEphemeris::initialize_file (void) private
Initialize the De4xxEphemeris file.
Definition at line 384 of file de4xx_ephem.cc.
References jeod::NamedItem::construct_name(), jeod::De4xxBase::De4xx_Const_DENUM, jeod::De4xxBase::De4xx_Const_LENUM, jeod::EphemerisDataSetMeta::de_constants, file, ident, jeod::De4xxFile::initialize(), jeod::De4xxFile::io, jeod::De4xxFileIO::metaData, time_tt, jeod::TimeStandard::tjt_jd_offset, and jeod::TimeStandard::trunc_julian_time.
Referenced by initialize_model().
initialize_items()
void jeod::De4xxEphemeris::initialize_items (EphemeridesManager & ephem_manager) private
Initialize the De4xxEphemeris item data.
Parameters
[in,out] ephem_manager Ephemerides manager
Definition at line 419 of file de4xx_ephem.cc.
References jeod::EphemeridesManager::add_ephem_item(), jeod::EphemeridesManager::add_integ_frame(), jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_LLibration, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxBase::De4xx_Ephem_SSbary, jeod::De4xxEphemItem::Deselected, jeod::EphemerisItem::disable(), earth_moon_barycenter_frame, jeod::MessageHandler::fail(), file, jeod::De4xxFile::file_spec, jeod::RefFrameManager::find_ref_frame(), jeod::De4xxFileSpec::get_model_number(), jeod::RefFrame::get_name(), jeod::De4xxEphemItem::Inactive, jeod::EphemeridesMessages::inconsistent_setup, jeod::De4xxEphemItem::item, item_data, lunar_orientation, jeod::De4xxBase::number_jeod_items(), jeod::De4xxBase::number_trans_points(), points, selected_items, solar_system_barycenter_frame, and jeod::De4xxEphemItem::status.
Referenced by initialize_model().
initialize_model() [1/2]
void jeod::De4xxEphemeris::initialize_model (const TimeManager & time_manager, DynManager & dyn_manager, const std::string & time_type = "TT")
Initialize the De4xxEphemeris model.
Parameters
[in] time_manager Time manager
[in,out] dyn_manager Dynamics manager
[in] time_type time type
Definition at line 50 of file de4xx_ephem_dynmanager.cc.
initialize_model() [2/2]
void jeod::De4xxEphemeris::initialize_model (const TimeManager & time_manager, EphemeridesManager & ephem_manager, const std::string & time_type = "TT")
Initialize the De4xxEphemeris model.
This method is called before the planets have been registered with the reference frame manager, so we don't know whether the ephemeris items should be enabled or disabled.
Parameters
[in] time_manager Time manager
[in,out] ephem_manager Ephemerides manager
[in] time_type optional "tt"||"tdb" "tt" default manager
Definition at line 314 of file de4xx_ephem.cc.
References active, jeod::EphemeridesManager::add_ephemeris(), initialize_file(), initialize_items(), and initialize_time().
initialize_time()
void jeod::De4xxEphemeris::initialize_time (const TimeManager & time_manager, const std::string & time_type) private
Initialize De4xxEphemeris timing.
Parameters
[in] time_manager Time manager
[in] time_type time type
Definition at line 345 of file de4xx_ephem.cc.
References jeod::MessageHandler::fail(), jeod::TimeManager::get_time_ptr(), jeod::EphemeridesMessages::inconsistent_setup, time_dyn, time_tt, and jeod::MessageHandler::warn().
Referenced by initialize_model().
operator=()
De4xxEphemeris& jeod::De4xxEphemeris::operator= (const De4xxEphemeris &) private
Not implemented.
propagate_lunar_rnp()
void jeod::De4xxEphemeris::propagate_lunar_rnp (void)
Propagate the lunar orientation to the current time.
Definition at line 933 of file de4xx_ephem.cc.
References jeod::De4xxEphemItem::Active, active, jeod::De4xxBase::De4xx_Ephem_LLibration, item_data, lunar_orientation, jeod::EphemerisZXZOrientation::propagate(), jeod::JeodBaseTime::seconds, and time_dyn.
set_model_number()
void jeod::De4xxEphemeris::set_model_number (int denum_in) inline
Set ephemeris model number.
This number is used to specify the de file to use the pathname is of the form PWD/build/de4xx_lib/libde<denumIn>.so
Definition at line 255 of file de4xx_ephem.hh.
References file, jeod::De4xxFile::file_spec, and jeod::De4xxFileSpec::set_model_number().
shutdown()
void jeod::De4xxEphemeris::shutdown (void)
Free resources allocated by the De4xxEphemeris model.
Definition at line 234 of file de4xx_ephem.cc.
References file, ident, JEOD_DELETE_ARRAY, and jeod::De4xxFile::shutdown().
Referenced by ~De4xxEphemeris().
time_is_in_range()
bool jeod::De4xxEphemeris::time_is_in_range (void) const
Check whether the specified time is represented in the JPL ephemeris file.
Assumptions and Limitations
Ephemeris file is open for input
Ephemeris file is blocked per value set in the ephem_file structure
Returns
True if time is in file
Definition at line 921 of file de4xx_ephem.cc.
References file, jeod::De4xxFile::time_is_in_range(), time_tt, and jeod::TimeStandard::trunc_julian_time.
timestamp()
double jeod::De4xxEphemeris::timestamp (void) const override virtual
Return time of last update.
Returns
Timestamp
Units: day
Implements jeod::EphemerisInterface.
Definition at line 283 of file de4xx_ephem.cc.
References update_time.
Friends And Related Function Documentation
init_attrjeod__De4xxEphemeris
void init_attrjeod__De4xxEphemeris () friend
InputProcessor
friend class InputProcessor friend
Definition at line 198 of file de4xx_ephem.hh.
Field Documentation
active
bool jeod::De4xxEphemeris::active
Is the model active? This is set to true by the constructor.
Setting this flag to false prior to initialization time will result in the model never doing anything. Setting this flag to false after the model has been active for some time is not supported.trick_units(–)
Definition at line 282 of file de4xx_ephem.hh.
Referenced by activate(), deactivate(), ephem_activate(), ephem_build_tree(), ephem_initialize(), ephem_update(), initialize_model(), and propagate_lunar_rnp().
body_to_file_idx
int* jeod::De4xxEphemeris::body_to_file_idx protected
Mapping from De4xxEphemBodies numbers to De4xxFileBodies numbers.
trick_units(–)
Definition at line 376 of file de4xx_ephem.hh.
Referenced by De4xxEphemeris(), ephem_activate(), ephem_update(), and ~De4xxEphemeris().
earth_moon_barycenter_frame
EphemerisRefFrame jeod::De4xxEphemeris::earth_moon_barycenter_frame protected
Earth-Moon barycenter reference frame.
trick_units(–)
Definition at line 351 of file de4xx_ephem.hh.
Referenced by De4xxEphemeris(), and initialize_items().
file
De4xxFile jeod::De4xxEphemeris::file protected
The ephemeris file model.
The items of interest to the typical user are the data members file.file_spec.ephem_file_name and file.file_spec.denum. The former specifies the name of the file while the latter serves as a sanity check that the right file is being read.trick_units(–)
Definition at line 310 of file de4xx_ephem.hh.
Referenced by activate_nodes(), determine_root_node(), ephem_activate(), ephem_build_tree(), ephem_initialize(), ephem_update(), get_header_data(), get_model_number(), initialize_file(), initialize_items(), set_model_number(), shutdown(), and time_is_in_range().
force_update
bool jeod::De4xxEphemeris::force_update protected
Is an update needed even if the time hasn't changed?
trick_units(–)
Definition at line 315 of file de4xx_ephem.hh.
Referenced by ephem_activate(), and ephem_update().
ident
char* jeod::De4xxEphemeris::ident protected
Identifier for this model, computed from the supplied file.
trick_units(–)
Definition at line 331 of file de4xx_ephem.hh.
Referenced by get_name(), initialize_file(), and shutdown().
item_data
De4xxEphemItem* jeod::De4xxEphemeris::item_data protected
Data pertaining to the points for which translational states are calculated.
trick_units(–)
Definition at line 326 of file de4xx_ephem.hh.
Referenced by activate_em_nodes(), activate_nodes(), De4xxEphemeris(), determine_root_node(), ephem_activate(), ephem_build_tree(), ephem_initialize(), ephem_update(), initialize_items(), propagate_lunar_rnp(), and ~De4xxEphemeris().
lunar_orientation
EphemerisZXZOrientation jeod::De4xxEphemeris::lunar_orientation protected
Lunar orientation.
trick_units(–)
Definition at line 346 of file de4xx_ephem.hh.
Referenced by De4xxEphemeris(), ephem_update(), initialize_items(), and propagate_lunar_rnp().
nactive_items
unsigned int jeod::De4xxEphemeris::nactive_items protected
Number of items that are currently active.
trick_units(–)
Definition at line 320 of file de4xx_ephem.hh.
Referenced by activate_em_nodes(), activate_nodes(), determine_root_node(), ephem_activate(), and ephem_update().
points
EphemerisPoint* jeod::De4xxEphemeris::points protected
The planets and barycenter points, in De4xxEphemBodies FileBodies order.
trick_units(–)
Definition at line 341 of file de4xx_ephem.hh.
Referenced by De4xxEphemeris(), ephem_update(), initialize_items(), and ~De4xxEphemeris().
root_item
De4xxEphemItem* jeod::De4xxEphemeris::root_item protected
The root point in the reference frame tree.
trick_units(–)
Definition at line 361 of file de4xx_ephem.hh.
Referenced by determine_root_node(), ephem_build_tree(), and ephem_update().
selected_items
bool* jeod::De4xxEphemeris::selected_items
Used at initialization time only to selectively enable/disable portions of the model.
The constructor initializes all elements of this array to true. Users can set selected elements to false to disable the corresponding ephemeris items. The intent is to enable the use of multiple ephemeris models. Typical users of the model can leave this member as-is. NOTE: while the container is of length 16, Nutations and lunar librations are not currently supported by JEODtrick_units(–)
Definition at line 294 of file de4xx_ephem.hh.
Referenced by De4xxEphemeris(), initialize_items(), and ~De4xxEphemeris().
solar_system_barycenter_frame
EphemerisRefFrame jeod::De4xxEphemeris::solar_system_barycenter_frame protected
Solar system barycenter reference frame.
trick_units(–)
Definition at line 356 of file de4xx_ephem.hh.
Referenced by De4xxEphemeris(), and initialize_items().
time_dyn
const TimeDyn* jeod::De4xxEphemeris::time_dyn protected
The source of dynamic time information.
trick_units(–)
Definition at line 371 of file de4xx_ephem.hh.
Referenced by ephem_update(), initialize_time(), and propagate_lunar_rnp().
time_tt
const TimeStandard* jeod::De4xxEphemeris::time_tt protected
The source of ephemeris time information.
trick_units(–)
Definition at line 366 of file de4xx_ephem.hh.
Referenced by ephem_update(), initialize_file(), initialize_time(), and time_is_in_range().
update_time
double jeod::De4xxEphemeris::update_time protected
Time of last update, dynamic time seconds.
trick_units(s)
Definition at line 336 of file de4xx_ephem.hh.
Referenced by ephem_update(), and timestamp().
The documentation for this class was generated from the following files:
de4xx_ephem.hh
de4xx_ephem.cc
de4xx_ephem_dynmanager.cc