JEOD: jeod::De4xxFile Class Reference
jeod::De4xxFile Class Reference
Provides the ability to read and interpret a DE4xx ephemeris file.
#include <de4xx_file.hh>
Public Member Functions
De4xxFile (void)
Construct the JPL ephemeris file.
~De4xxFile (void)
Destroy the JPL ephemeris file.
void pre_initialize (void)
Pre-initialize a DE4xxFile instance.
void initialize (double epoch_time, double del_day, double time_offset, double init_time)
Initialize a DE4xxFile instance.
bool time_is_in_range (double time) const
Check whether the specified time is represented in the JPL ephemeris file.
void update (double time)
Calcuate the position and velocity states of selected planetary bodies at some point in time.
void shutdown ()
Shutdown the JPL ephemeris file.
Data Fields
De4xxFileSpec file_spec
File specification.
De4xxFileHeader header
File header.
De4xxFileItem * item
Item data.
De4xxFileIO io
File descriptor.
De4xxFileRefTime ref_time
Reference time.
De4xxFileCoef coef
Chebychev coefs.
De4xxFileRestart restart
Restart handler.
double update_time
Time of last update.
double vm_usage
trick_units(–)
double resident_set
trick_units(–)
bool logMemoryStats
trick_units(–)
Private Member Functions
void open (void)
Open the JPL ephemeris file.
void reopen (void)
Open the JPL ephemeris file on restart.
void close (void)
Close the JPL ephemeris file.
void interpolate (double time, double fblk)
Calcuate the position and velocity states of selected planetary bodies at some point in time.
De4xxFile (const De4xxFile &)
Not implemented.
De4xxFile & operator= (const De4xxFile &)
Not implemented.
void capture_mem_stats ()
Friends
class InputProcessor
class De4xxFileRestart
void init_attrjeod__De4xxFile ()
Detailed Description
Provides the ability to read and interpret a DE4xx ephemeris file.
Definition at line 617 of file de4xx_file.hh.
Constructor & Destructor Documentation
De4xxFile() [1/2]
jeod::De4xxFile::De4xxFile (void)
Construct the JPL ephemeris file.
Definition at line 252 of file de4xx_file.cc.
References jeod::De4xxBase::De4xx_File_ENutation, jeod::De4xxBase::De4xx_File_LLibration, jeod::De4xxBase::De4xx_File_MaxEntries, jeod::De4xxBase::De4xx_File_tt_tdb, item, JEOD_ALLOC_CLASS_ARRAY, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, jeod::De4xxFileItem::nitems, jeod::De4xxFileItem::pscale, and restart.
~De4xxFile()
jeod::De4xxFile::~De4xxFile (void)
Destroy the JPL ephemeris file.
Definition at line 292 of file de4xx_file.cc.
References close(), item, JEOD_DELETE_ARRAY, JEOD_DEREGISTER_CHECKPOINTABLE, and restart.
De4xxFile() [2/2]
jeod::De4xxFile::De4xxFile (const De4xxFile &) private
Not implemented.
Member Function Documentation
capture_mem_stats()
void jeod::De4xxFile::capture_mem_stats () private
Definition at line 532 of file de4xx_file.cc.
References logMemoryStats, jeod::process_mem_usage(), resident_set, and vm_usage.
close()
void jeod::De4xxFile::close (void) private
Close the JPL ephemeris file.
Assumptions and Limitations
Ephemeris file is open for input
Errors are fatal
Definition at line 433 of file de4xx_file.cc.
References jeod::De4xxFileCoef::chebyderiv, jeod::De4xxFileCoef::chebypoly, coef, jeod::De4xxFileIO::file, jeod::EphemeridesMessages::file_error, io, JEOD_DELETE_ARRAY, jeod::De4xxFileIO::metaData, and jeod::MessageHandler::warn().
Referenced by shutdown(), and ~De4xxFile().
initialize()
void jeod::De4xxFile::initialize (double epoch_time, double del_day, double time_offset, double init_time)
Initialize a DE4xxFile instance.
Parameters
[in] epoch_time Julian date
Units: day
[in] del_day Days from epoch
Units: day
[in] time_offset Terrestrial Time offet
Units: s
[in] init_time Seconds from epoch
Units: s
Definition at line 178 of file de4xx_file_init.cc.
References jeod::De4xxFileHeader::au, jeod::De4xxFileHeader::b1_em_dist_ratio, jeod::De4xxFileHeader::be_em_dist_ratio, jeod::De4xxFileRefTime::block_no, jeod::De4xxFileHeader::bm_em_dist_ratio, jeod::De4xxFileCoef::chebyderiv, jeod::De4xxFileCoef::chebypoly, coef, jeod::De4xxBase::De4xx_Const_AU, jeod::De4xxBase::De4xx_Const_CLIGHT, jeod::De4xxBase::De4xx_Const_EMRAT, jeod::De4xxBase::De4xx_Const_GM1, jeod::De4xxBase::De4xx_Const_GM2, jeod::De4xxBase::De4xx_Const_GM4, jeod::De4xxBase::De4xx_Const_GM5, jeod::De4xxBase::De4xx_Const_GM6, jeod::De4xxBase::De4xx_Const_GM7, jeod::De4xxBase::De4xx_Const_GM8, jeod::De4xxBase::De4xx_Const_GM9, jeod::De4xxBase::De4xx_Const_GMB, jeod::De4xxBase::De4xx_Const_GMS, jeod::De4xxBase::De4xx_Ephem_Earth, jeod::De4xxBase::De4xx_Ephem_EMbary, jeod::De4xxBase::De4xx_Ephem_Jupiter, jeod::De4xxBase::De4xx_Ephem_Mars, jeod::De4xxBase::De4xx_Ephem_Mercury, jeod::De4xxBase::De4xx_Ephem_Moon, jeod::De4xxBase::De4xx_Ephem_Neptune, jeod::De4xxBase::De4xx_Ephem_Pluto, jeod::De4xxBase::De4xx_Ephem_Saturn, jeod::De4xxBase::De4xx_Ephem_Sun, jeod::De4xxBase::De4xx_Ephem_Uranus, jeod::De4xxBase::De4xx_Ephem_Venus, jeod::EphemerisDataSetMeta::de_constants, jeod::EphemerisDataSetMeta::delta_epoch, jeod::De4xxFileSpec::denum, jeod::De4xxFileHeader::e1_em_dist_ratio, jeod::De4xxFileHeader::em_mass_ratio, jeod::De4xxFileRefTime::epoch_date, jeod::MessageHandler::fail(), jeod::De4xxFileRefTime::fdate, file_spec, jeod::De4xxFileHeader::gmbody, header, jeod::De4xxFileRefTime::init_time, io, JEOD_ALLOC_PRIM_ARRAY, jeod::l1_point(), jeod::De4xxFileIO::max_terms, jeod::De4xxFileIO::metaData, jeod::De4xxBase::number_grav_models(), pre_initialize(), ref_time, jeod::De4xxFileIO::segmentData, jeod::EphemerisDataSegmentMeta::start_epoch, jeod::EphemeridesMessages::time_not_in_range, jeod::De4xxFileIO::total_num_recs, update_time, and jeod::De4xxFileHeader::vlight.
Referenced by jeod::De4xxEphemeris::initialize_file().
interpolate()
void jeod::De4xxFile::interpolate (double time, double fblk) private
Calcuate the position and velocity states of selected planetary bodies at some point in time.
Parameters
[in] time Time since reference
Units: s
[in] fblk Fractional block
Definition at line 260 of file de4xx_file_update.cc.
References jeod::De4xxFileItem::active, jeod::De4xxFileCoef::chebyderiv, jeod::De4xxFileCoef::chebypoly, jeod::De4xxFileCoef::chebyterms, jeod::De4xxFileCoef::chebyx, jeod::De4xxFileCoef::coef, coef, jeod::Numerical::compare_exact(), jeod::EphemerisDataSetMeta::delta_epoch, io, item, jeod::De4xxFileItem::item_idx, jeod::De4xxFileIO::itemData, jeod::De4xxFileIO::metaData, jeod::De4xxFileItem::nitems, jeod::EphemerisDataItemMeta::npoly, jeod::EphemerisDataItemMeta::nterms, jeod::EphemerisDataSetMeta::number_file_items, jeod::EphemerisDataItemMeta::offset, jeod::De4xxFileItem::pscale, jeod::De4xxFileItem::state, and jeod::De4xxFileItem::update_time.
Referenced by update().
open()
void jeod::De4xxFile::open (void) private
Open the JPL ephemeris file.
Assumptions and Limitations
Errors are fatal
Returns
Void
Definition at line 321 of file de4xx_file.cc.
References jeod::De4xxBase::De4xx_File_MaxEntries, jeod::MessageHandler::debug(), jeod::EphemeridesMessages::debug, jeod::De4xxFileSpec::ephem_file_dir, jeod::De4xxFileSpec::ephem_file_name, jeod::MessageHandler::fail(), jeod::De4xxFileIO::file, jeod::EphemeridesMessages::file_error, file_spec, io, jeod::De4xxFileIO::itemData, jeod::De4xxFileIO::metaData, jeod::EphemerisDataSetMeta::number_file_items, jeod::De4xxFileSpec::pathname, and jeod::De4xxFileIO::segmentData.
Referenced by pre_initialize().
operator=()
De4xxFile& jeod::De4xxFile::operator= (const De4xxFile &) private
Not implemented.
pre_initialize()
void jeod::De4xxFile::pre_initialize (void)
Pre-initialize a DE4xxFile instance.
Definition at line 71 of file de4xx_file_init.cc.
References jeod::De4xxFileItem::avail, jeod::De4xxFileCoef::coef, coef, jeod::De4xxFileIO::coeffs_segment_starting_addr, jeod::De4xxFileIO::current_record_starting_addr, jeod::De4xxBase::De4xx_Const_DENUM, jeod::De4xxBase::De4xx_File_MaxEntries, jeod::EphemerisDataSetMeta::de_constants, jeod::De4xxFileSpec::denum, jeod::MessageHandler::fail(), jeod::De4xxFileIO::file, jeod::EphemeridesMessages::file_error, file_spec, jeod::EphemeridesMessages::garbage_file, jeod::EphemeridesMessages::internal_error, io, item, jeod::De4xxFileItem::item_idx, jeod::De4xxFileIO::itemData, jeod::De4xxFileIO::max_terms, jeod::De4xxFileIO::metaData, jeod::EphemerisDataItemMeta::nterms, jeod::EphemerisDataSegmentMeta::num_recs, jeod::EphemerisDataSetMeta::number_file_items, jeod::EphemerisDataSetMeta::number_segments, jeod::EphemerisDataItemMeta::offset, open(), jeod::De4xxFileSpec::pathname, jeod::De4xxFileIO::recno, jeod::De4xxFileIO::segment_index, jeod::De4xxFileIO::segment_recno, jeod::De4xxFileIO::segmentData, jeod::EphemerisDataSegmentMeta::start_epoch, jeod::EphemerisDataSegmentMeta::stop_epoch, and jeod::De4xxFileIO::total_num_recs.
Referenced by initialize(), and reopen().
reopen()
void jeod::De4xxFile::reopen (void) private
Open the JPL ephemeris file on restart.
Assumptions and Limitations
File spec has been reloaded.
Data has been allocated
Errors are fatal
Definition at line 411 of file de4xx_file.cc.
References jeod::De4xxFileIO::file, io, and pre_initialize().
Referenced by jeod::De4xxFileRestart::simple_restore().
shutdown()
void jeod::De4xxFile::shutdown (void)
Shutdown the JPL ephemeris file.
Definition at line 306 of file de4xx_file.cc.
References close().
Referenced by jeod::De4xxEphemeris::shutdown().
time_is_in_range()
bool jeod::De4xxFile::time_is_in_range (double time) const
Check whether the specified time is represented in the JPL ephemeris file.
Assumptions and Limitations
Ephemeris file is open for input
Ephemeris file is blocked per value set in the ephem_file structure
Returns
True if time is in file
Parameters
[in] time Time since reference
Units: s
Definition at line 476 of file de4xx_file.cc.
References jeod::De4xxFileRefTime::block_no, jeod::EphemerisDataSetMeta::delta_epoch, jeod::De4xxFileRefTime::init_time, io, jeod::De4xxFileIO::metaData, ref_time, and jeod::De4xxFileIO::total_num_recs.
Referenced by jeod::De4xxEphemeris::time_is_in_range().
update()
void jeod::De4xxFile::update (double time)
Calcuate the position and velocity states of selected planetary bodies at some point in time.
The EphemeridesState structure embedded in the Ephemerides structure contains an update indicator and state for each body. The state for a body is updated if the body's indicator indicates that a state update is needed.
Body selection – The 'active_bodies' array in the EphemeridesState structure indicates which planets' states are to be updated. The function updates the position and velocity for the selected bodies.
Time specification – Four input variables are available for specifying the time.
tt_offset is the offset between the remaining input times and Terrestrial Time (aka Terrestrial Dynamic Time, or TDT). Set this to zero if the other input times are already expressed in Terrestrial Time.
For highest precision, set epoch_time to the Julian date at midnight of the time point of interest and set either del_day or del_time to the difference between the time point of interest and the epoch_time.
An alternative that retains full precession is to pass the time at the start of the simulation in epoch_time and del_day and the time into the simulation in del_time. In this approach, epoch_time represents the Julian date at the midnight preceding the start of the simulation and del_day represents the time between the epoch time and simulation start.
For ease of use, set epoch_time to the Julian date representing the the time point of interest and set both del_day and del_time to 0.0. Note that this approach has a machine granularity of about 0.2 msec.
An intermediate alternative is to set the epoch_time to the start time of the simulation, del_day to zero and del_time to the simulation time in seconds. This approach will result in a small temporal bias due to the precision loss in the epoch time.
Outputs – Positions and velocities are expressed in the ICRF coordinate system. The states of the Sun and planets, including Earth-Moon barycenter, are expressed with respect to the solar system barycenter. Lunar states are expressed with respect to the center of the Earth.
NOTA BENE – The states of unselected bodies may or may not be changed.
Assumptions and Limitations
Assumption 1. Ephemeris file is open.
Assumption 2. Offset times in del_day and del_time are small. See description above.
Assumption 3. The caller will not reference the states of bodies not requested in the active_bodies array. The unselected body states are fair game and may or may not be modified by this function.
Limitation 1. No light speed time-of-travel corrections. Such corrections must be made by the caller if needed.
Limitation 2. No relativistic time corrections for the difference between Terrestrial and Barycenter Dynamic Time.
Limitation 3. The states of the sun and the major planets are expressed in ICRF coordinates relative to the Solar System barycenter. The state of the Moon is expressed in ICRF coordinates relative to the center of the Earth.
Parameters
[in] time Time since reference
Units: s
Definition at line 115 of file de4xx_file_update.cc.
References jeod::De4xxFileItem::active, jeod::De4xxFileItem::avail, jeod::De4xxFileRefTime::block_no, jeod::De4xxFileCoef::coef, coef, jeod::De4xxFileIO::coeffs_segment_starting_addr, jeod::De4xxFileIO::current_record_starting_addr, jeod::EphemerisDataSetMeta::delta_epoch, jeod::MessageHandler::fail(), jeod::De4xxFileIO::file, jeod::EphemeridesMessages::file_error, file_spec, jeod::De4xxFileRefTime::init_time, jeod::EphemeridesMessages::internal_error, interpolate(), io, item, jeod::EphemeridesMessages::item_not_in_file, jeod::De4xxFileIO::metaData, jeod::EphemerisDataSetMeta::ncoeff, jeod::EphemerisDataSegmentMeta::num_recs, jeod::EphemerisDataSetMeta::number_file_items, jeod::EphemerisDataSetMeta::number_segments, jeod::De4xxFileSpec::pathname, jeod::De4xxFileIO::recno, ref_time, jeod::De4xxFileIO::segment_index, jeod::De4xxFileIO::segment_recno, jeod::De4xxFileIO::segmentData, jeod::De4xxFileIO::total_num_recs, and update_time.
Referenced by jeod::De4xxEphemeris::ephem_update().
Friends And Related Function Documentation
De4xxFileRestart
friend class De4xxFileRestart friend
Definition at line 620 of file de4xx_file.hh.
init_attrjeod__De4xxFile
void init_attrjeod__De4xxFile () friend
InputProcessor
friend class InputProcessor friend
Definition at line 618 of file de4xx_file.hh.
Field Documentation
coef
De4xxFileCoef jeod::De4xxFile::coef
Chebychev coefs.
trick_units(–)
Definition at line 680 of file de4xx_file.hh.
Referenced by close(), initialize(), interpolate(), pre_initialize(), and update().
file_spec
De4xxFileSpec jeod::De4xxFile::file_spec
File specification.
trick_units(–)
Definition at line 655 of file de4xx_file.hh.
Referenced by jeod::De4xxEphemeris::activate_nodes(), jeod::De4xxEphemeris::determine_root_node(), jeod::De4xxEphemeris::ephem_activate(), jeod::De4xxEphemeris::ephem_build_tree(), jeod::De4xxEphemeris::ephem_initialize(), jeod::De4xxEphemeris::get_model_number(), initialize(), jeod::De4xxEphemeris::initialize_items(), open(), pre_initialize(), jeod::De4xxEphemeris::set_model_number(), and update().
header
De4xxFileHeader jeod::De4xxFile::header
File header.
trick_units(–)
Definition at line 660 of file de4xx_file.hh.
Referenced by jeod::De4xxEphemeris::ephem_update(), jeod::De4xxEphemeris::get_header_data(), and initialize().
io
De4xxFileIO jeod::De4xxFile::io
File descriptor.
trick_units(–)
Definition at line 670 of file de4xx_file.hh.
Referenced by close(), initialize(), jeod::De4xxEphemeris::initialize_file(), interpolate(), open(), pre_initialize(), reopen(), time_is_in_range(), and update().
item
De4xxFileItem* jeod::De4xxFile::item
Item data.
Sized to fit number of entries in most recent DE4xx releasetrick_units(–)
Definition at line 665 of file de4xx_file.hh.
Referenced by De4xxFile(), jeod::De4xxEphemeris::ephem_activate(), jeod::De4xxEphemeris::ephem_update(), interpolate(), pre_initialize(), update(), and ~De4xxFile().
logMemoryStats
bool jeod::De4xxFile::logMemoryStats
trick_units(–)
Definition at line 705 of file de4xx_file.hh.
Referenced by capture_mem_stats().
ref_time
De4xxFileRefTime jeod::De4xxFile::ref_time
Reference time.
trick_units(–)
Definition at line 675 of file de4xx_file.hh.
Referenced by initialize(), time_is_in_range(), and update().
resident_set
double jeod::De4xxFile::resident_set
trick_units(–)
Definition at line 700 of file de4xx_file.hh.
Referenced by capture_mem_stats().
restart
De4xxFileRestart jeod::De4xxFile::restart
Restart handler.
trick_io(**)
Definition at line 685 of file de4xx_file.hh.
Referenced by De4xxFile(), and ~De4xxFile().
update_time
double jeod::De4xxFile::update_time
Time of last update.
trick_units(s)
Definition at line 690 of file de4xx_file.hh.
Referenced by initialize(), and update().
vm_usage
double jeod::De4xxFile::vm_usage
trick_units(–)
Definition at line 695 of file de4xx_file.hh.
Referenced by capture_mem_stats().
The documentation for this class was generated from the following files:
de4xx_file.hh
de4xx_file.cc
de4xx_file_init.cc
de4xx_file_update.cc