JEOD: jeod::BodyAttachAligned Class Reference
jeod::BodyAttachAligned Class Reference
Attaches a pair of MassBody objects at a pair of MassPoints.
#include <body_attach_aligned.hh>
Public Member Functions
BodyAttachAligned ()
Construct a MassBodyAttachAligned.
~BodyAttachAligned () override
Destructor.
void initialize (DynManager &dyn_manager) override
Initialize a MassBodyAttach.
void apply (DynManager &dyn_manager) override
Initialize the core mass properties of the subject MassBody.
Public Member Functions inherited from jeod::BodyAttach
void set_parent_body (MassBody &mass_body_in)
Set the parent mass body of this action.
void set_parent_body (DynBody &dyn_body_in)
Set the parent dyn body of this action.
void set_parent_frame (RefFrame &ref_parent_in)
Set the parent ref frame of this action.
BodyAttach ()
Construct a MassBodyAttach.
~BodyAttach () override
Destructor.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()
Construct a BodyAction.
virtual ~BodyAction ()
Destruct a BodyAction.
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier (void) const
Accessor for action_identifier.
virtual bool is_ready (void)
In general, determine if the initializer is ready to be applied.
Data Fields
std::string subject_point_name
The name of the mass point on the subject mass body to be attached to to the parent_point_name mass point on the parent mass body.
std::string parent_point_name
The name of the mass point on the parent mass body to be attached to to the mass pointed named subject_point_name on the subject mass body.
Data Fields inherited from jeod::BodyAttach
bool succeeded
Did the attachment succeed?
Data Fields inherited from jeod::BodyAction
bool active
Controls when the action is performed.
bool terminate_on_error
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name
An identifier for this action.
Private Member Functions
BodyAttachAligned (const BodyAttachAligned &)
BodyAttachAligned & operator= (const BodyAttachAligned &)
Friends
class InputProcessor
void init_attrjeod__BodyAttachAligned ()
Additional Inherited Members
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Protected Attributes inherited from jeod::BodyAttach
MassBody * mass_parent
The MassBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
DynBody * dyn_parent
The DynBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
RefFrame * ref_parent
The RefFrame corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent RefFrame otherwise.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject
The DynBody of the body that is the subject of this action.
std::string action_identifier
An identifier for this action, constructed from the class name and the action name at initialization time.
Detailed Description
Attaches a pair of MassBody objects at a pair of MassPoints.
When the action is ready, the attachment proceeds as follows:
The points indicated by the subject and parent mass point names will be coincident after attachment is complete.
The orientation between the two reference frames associated with the two attach points is a 180 degree yaw.
Definition at line 87 of file body_attach_aligned.hh.
Constructor & Destructor Documentation
BodyAttachAligned() [1/2]
jeod::BodyAttachAligned::BodyAttachAligned (void)
Construct a MassBodyAttachAligned.
Definition at line 54 of file body_attach_aligned.cc.
~BodyAttachAligned()
jeod::BodyAttachAligned::~BodyAttachAligned (void) inline override
Destructor.
Definition at line 140 of file body_attach_aligned.hh.
BodyAttachAligned() [2/2]
jeod::BodyAttachAligned::BodyAttachAligned (const BodyAttachAligned &) private
Member Function Documentation
apply()
void jeod::BodyAttachAligned::apply (DynManager & dyn_manager) override virtual
Initialize the core mass properties of the subject MassBody.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAttach.
Definition at line 104 of file body_attach_aligned.cc.
References jeod::DynBody::add_mass_body(), jeod::BodyAttach::apply(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::BodyAttach::dyn_parent, jeod::BodyAction::dyn_subject, jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), jeod::BodyAttach::mass_parent, jeod::BodyAction::mass_subject, parent_point_name, jeod::BodyAttach::ref_parent, subject_point_name, and jeod::BodyAttach::succeeded.
initialize()
void jeod::BodyAttachAligned::initialize (DynManager & dyn_manager) override virtual
Initialize a MassBodyAttach.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::BodyAttach.
Definition at line 69 of file body_attach_aligned.cc.
References jeod::BodyAction::action_identifier, jeod::MessageHandler::fail(), jeod::BodyAttach::initialize(), jeod::BodyActionMessages::invalid_name, parent_point_name, and subject_point_name.
operator=()
BodyAttachAligned& jeod::BodyAttachAligned::operator= (const BodyAttachAligned &) private
Friends And Related Function Documentation
init_attrjeod__BodyAttachAligned
void init_attrjeod__BodyAttachAligned () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file body_attach_aligned.hh.
Field Documentation
parent_point_name
std::string jeod::BodyAttachAligned::parent_point_name
The name of the mass point on the parent mass body to be attached to to the mass pointed named subject_point_name on the subject mass body.
The supplied name can omit the parent mass body name dot prefix if desired.trick_units(–)
Definition at line 108 of file body_attach_aligned.hh.
Referenced by apply(), and initialize().
subject_point_name
std::string jeod::BodyAttachAligned::subject_point_name
The name of the mass point on the subject mass body to be attached to to the parent_point_name mass point on the parent mass body.
The supplied name can omit the subject mass body name dot prefix if desired.trick_units(–)
Definition at line 101 of file body_attach_aligned.hh.
Referenced by apply(), and initialize().
The documentation for this class was generated from the following files:
body_attach_aligned.hh
body_attach_aligned.cc