JEOD: jeod::LvlhRelativeDerivedState Class Reference
jeod::LvlhRelativeDerivedState Class Reference
The class used for calculating the LVLH state of a subject DynBody relative to some LVLH reference frame.
#include <lvlh_relative_derived_state.hh>
Public Member Functions
LvlhRelativeDerivedState ()
Default Constructor.
~LvlhRelativeDerivedState () override=default
LvlhRelativeDerivedState (const LvlhRelativeDerivedState &)=delete
LvlhRelativeDerivedState & operator= (const LvlhRelativeDerivedState &)=delete
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of an LvlhRelativeDerivedState.
void update () override
Update the state.
void convert_rect_to_circ (const RefFrameState &rect_rel_state)
Convert from rectilinear LVLH coordinates to circular curvilinear.
void convert_circ_to_rect (const RefFrameState &circ_rel_state)
Convert from circular curvilinear LVLH coordinates to rectilinear.
Public Member Functions inherited from jeod::RelativeDerivedState
RelativeDerivedState ()=default
~RelativeDerivedState () override
Destruct a RelativeDerivedState object.
RelativeDerivedState (const RelativeDerivedState &)=delete
RelativeDerivedState & operator= (const RelativeDerivedState &)=delete
void set_name (std::string name_in)
Setter for the name.
void set_target_frame (RefFrame &tf)
Quick shortcut allowing use of conversion routines without requiring initialization.
void set_subject_frame (BodyRefFrame &sf)
Quick shortcut allowing use of conversion routines without requiring initialization.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a RelativeDerivedState.
virtual void initialize (DynManager &dyn_manager)
Initialize a RelativeDerivedState, without a DynBody.
void update () override
Update the state.
void set_activation_flag (bool raf)
Setter for the activation flag to on or off and If off, unsubscribes subject and target frames /param raf RelativeDerivedState activation flag for RelKin manager.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()=default
virtual ~DerivedState ()=default
DerivedState (const DerivedState &)=delete
DerivedState & operator= (const DerivedState &)=delete
void set_reference_name (const std::string &new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
LvlhType::Type lvlh_type {LvlhType::Rectilinear}
Indicates type of LVLH coordinates desired.
bool use_theta_dot_correction {}
Indicates whether or not to correct for changing phase angle in curvilinear coordinates.
Data Fields inherited from jeod::RelativeDerivedState
std::string name {""}
The name of this relative derived state.
std::string subject_frame_name
The name of the frame on the subject vehicle.
std::string target_frame_name
The name of the target reference frame.
DirectionSense direction_sense {undefined}
Indicates direction in which relative state is to be computed.
RefFrameState rel_state
Computed relative state.
bool active {true}
Bool flag used by the RelKin model to turn on/off which Relative Derived State needs to be managed.
Data Fields inherited from jeod::DerivedState
DynBody * subject {}
The body that is the subject of the derived state.
std::string reference_name
The name of the object with respect to which the subject state is assessed.
Private Member Functions
void do_theta_dot_correction (double omega[3], const RefFrameState &state, const double r, bool c2r)
Compute thetadot correction to omega.
Friends
class InputProcessor
void init_attrjeod__LvlhRelativeDerivedState ()
Additional Inherited Members
Public Types inherited from jeod::RelativeDerivedState
enum DirectionSense { undefined = -1, ComputeSubjectStateinTarget = 0, ComputeTargetStateinSubject = 2 }
an enumeration to specify the direction and sense, and frame representation intended for output from the RelativeDerivedState calculations.
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
Protected Attributes inherited from jeod::RelativeDerivedState
BodyRefFrame * subject_frame {}
The reference frame corresponding to the user-input subject_frame_name.
RefFrame * target_frame {}
The reference frame corresponding to the user-input target_frame_name.
Protected Attributes inherited from jeod::DerivedState
std::string state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Detailed Description
The class used for calculating the LVLH state of a subject DynBody relative to some LVLH reference frame.
Definition at line 87 of file lvlh_relative_derived_state.hh.
Constructor & Destructor Documentation
LvlhRelativeDerivedState() [1/2]
jeod::LvlhRelativeDerivedState::LvlhRelativeDerivedState ()
Default Constructor.
Definition at line 53 of file lvlh_relative_derived_state.cc.
References jeod::RelativeDerivedState::ComputeSubjectStateinTarget, and jeod::RelativeDerivedState::direction_sense.
~LvlhRelativeDerivedState()
jeod::LvlhRelativeDerivedState::~LvlhRelativeDerivedState () override default
LvlhRelativeDerivedState() [2/2]
jeod::LvlhRelativeDerivedState::LvlhRelativeDerivedState (const LvlhRelativeDerivedState &) delete
Member Function Documentation
convert_circ_to_rect()
void jeod::LvlhRelativeDerivedState::convert_circ_to_rect (const RefFrameState & curvi_rel_state)
Convert from circular curvilinear LVLH coordinates to rectilinear.
Parameters
[in] curvi_rel_state Source state
Definition at line 190 of file lvlh_relative_derived_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_quaternion(), jeod::Vector3::copy(), do_theta_dot_correction(), jeod::MessageHandler::fail(), jeod::DerivedStateMessages::illegal_value, jeod::Matrix3x3::initialize(), jeod::RelativeDerivedState::name, jeod::RefFrameTrans::position, jeod::Matrix3x3::product_right_transpose(), jeod::RelativeDerivedState::rel_state, jeod::RefFrameState::rot, jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::RelativeDerivedState::target_frame, jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::RefFrameTrans::velocity, and jeod::Vector3::vmag().
Referenced by jeod::DynBodyInitLvlhState::apply().
convert_rect_to_circ()
void jeod::LvlhRelativeDerivedState::convert_rect_to_circ (const RefFrameState & rect_rel_state)
Convert from rectilinear LVLH coordinates to circular curvilinear.
Parameters
[in] rect_rel_state Source state
Definition at line 115 of file lvlh_relative_derived_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_quaternion(), jeod::Vector3::copy(), do_theta_dot_correction(), jeod::MessageHandler::fail(), jeod::DerivedStateMessages::illegal_value, jeod::Matrix3x3::initialize(), jeod::RelativeDerivedState::name, jeod::RefFrameTrans::position, jeod::Matrix3x3::product_right_transpose(), jeod::RelativeDerivedState::rel_state, jeod::RefFrameState::rot, jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::RelativeDerivedState::target_frame, jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::RefFrameTrans::velocity, and jeod::Vector3::vmag().
Referenced by update().
do_theta_dot_correction()
void jeod::LvlhRelativeDerivedState::do_theta_dot_correction (double omega[3], const RefFrameState & state, const double r, bool c2r) private
Compute thetadot correction to omega.
Definition at line 266 of file lvlh_relative_derived_state.cc.
References jeod::Vector3::decr(), jeod::Vector3::dot(), jeod::Vector3::incr(), jeod::RefFrameTrans::position, jeod::RefFrameState::rot, jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::RelativeDerivedState::target_frame, jeod::RefFrameState::trans, jeod::Vector3::transform(), use_theta_dot_correction, and jeod::RefFrameTrans::velocity.
Referenced by convert_circ_to_rect(), and convert_rect_to_circ().
initialize()
void jeod::LvlhRelativeDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of an LvlhRelativeDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class.
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DerivedState.
Definition at line 66 of file lvlh_relative_derived_state.cc.
References jeod::RelativeDerivedState::initialize().
operator=()
LvlhRelativeDerivedState& jeod::LvlhRelativeDerivedState::operator= (const LvlhRelativeDerivedState &) delete
update()
void jeod::LvlhRelativeDerivedState::update () override virtual
Update the state.
Reimplemented from jeod::DerivedState.
Definition at line 75 of file lvlh_relative_derived_state.cc.
References jeod::LvlhType::CircularCurvilinear, jeod::RefFrame::compute_relative_state(), convert_rect_to_circ(), jeod::LvlhType::EllipticalCurvilinear, jeod::MessageHandler::fail(), jeod::DerivedStateMessages::illegal_value, lvlh_type, jeod::LvlhType::Rectilinear, jeod::RelativeDerivedState::rel_state, jeod::RelativeDerivedState::subject_frame, and jeod::RelativeDerivedState::target_frame.
Friends And Related Function Documentation
init_attrjeod__LvlhRelativeDerivedState
void init_attrjeod__LvlhRelativeDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 89 of file lvlh_relative_derived_state.hh.
Field Documentation
lvlh_type
LvlhType::Type jeod::LvlhRelativeDerivedState::lvlh_type {LvlhType::Rectilinear}
Indicates type of LVLH coordinates desired.
Default is rectilinear.trick_units(–)
Definition at line 95 of file lvlh_relative_derived_state.hh.
Referenced by update().
use_theta_dot_correction
bool jeod::LvlhRelativeDerivedState::use_theta_dot_correction {}
Indicates whether or not to correct for changing phase angle in curvilinear coordinates.
Default is false.trick_units(–)
Definition at line 101 of file lvlh_relative_derived_state.hh.
Referenced by do_theta_dot_correction().
The documentation for this class was generated from the following files:
lvlh_relative_derived_state.hh
lvlh_relative_derived_state.cc