JEOD: jeod::FlatPlateRadiationFacet Class Reference
jeod::FlatPlateRadiationFacet Class Reference
A flat plate facet to be used for radiation interaction.
#include <flat_plate_radiation_facet.hh>
Public Member Functions
FlatPlateRadiationFacet ()
Construct a FlatPlateRadiationFacet.
~FlatPlateRadiationFacet () override
Destructor for FlatPlateRadiationFacet.
void incident_radiation (const double flux_mag, const double flux_struct_hat[3], const bool calculate_forces) override
Calculation of force and torque due to radiation pressure.
void initialize_geom (double center_grav[3]) override
Initializes the Facet for use in the model.
void define_facet (FlatPlate *flat_plate)
Defines the facet data values.
void radiation_pressure (void) override
Calculates the radiative emission force, accumulated force, and torque acting on a facet.
Public Member Functions inherited from jeod::RadiationFacet
RadiationFacet ()
Constructor for Radiationfacet.
~RadiationFacet () override
Destructor for RadiationFacet.
void initialize () override
Run sanity checks on input variables.
void define_facet_core (Facet *facet, const ThermalFacetRider &facet_thermal, RadiationParams *params)
Defines the inherent facet values.
ThermalIntegrableObject & get_thermal_integrator ()
Get the integrator for thermal characteristics.
Public Member Functions inherited from jeod::InteractionFacet
InteractionFacet ()
Default constructor.
virtual ~InteractionFacet ()
Destructor.
Public Member Functions inherited from jeod::RadiationBaseFacet
RadiationBaseFacet ()
Construct a RadiationBaseFacet.
virtual ~RadiationBaseFacet ()
Destructor for RadiationBaseFacet.
virtual void interact_with_third_body (RadiationThirdBody *third_body, const bool calc_forces)
Calculation of force, torques and irradiance due to ThirdBody flux.
virtual void initialize_runtime_values (void)
To initialize the values during each update run.
Data Fields
double * normal
Unit vector normal to the plate surface, pointing outward (structural frame).
double incident_flux_hat [3]
Temporary value.
Data Fields inherited from jeod::RadiationFacet
double crot_to_cp [3]
position of center of pressure w.r.t.
double * center_pressure
Center of pressure (in structural frame).
Data Fields inherited from jeod::InteractionFacet
double force [3]
The force on the facet caused by the environment interaction.
double torque [3]
The torque on the facet caused by the environment interaction.
Facet * base_facet
The original facet from which this interaction facet was created.
Data Fields inherited from jeod::RadiationBaseFacet
double albedo
Usable value of albedo, set to either albedo_IR or albedo_vis, depending on situation.
double albedo_vis
Fraction of incident visible radiation that is immediately reflected.
double albedo_IR
Fraction of incident IR radiation that is immediately reflected.
double diffuse
Fraction of reflected radiation that is reflected diffusely (balance reflected specularly)
ThermalFacetRider thermal
thermal characteristics of the facet.
double cx_area
cross-sectional area projected perpendicular to the radiation vector.
double areaxflux
product of momentum flux and cross-sectional area (cx_area).
double areaxflux_e
product of energy flux and cross-sectional area
double F_absorption [3]
Force due to photon absorption from ONLY ONE source.
double F_specular [3]
Force due to photon specular reflection from ONLY ONE source.
double F_diffuse [3]
Force due to photon diffuse reflection from ONLY ONE source.
double F_emission [3]
Force due to photon (thermal) emission.
Private Member Functions
FlatPlateRadiationFacet & operator= (const FlatPlateRadiationFacet &rhs)
FlatPlateRadiationFacet (const FlatPlateRadiationFacet &rhs)
Private Attributes
double sin_theta
Theta is the angle between the plate and the radiation vector.
Friends
class InputProcessor
void init_attrjeod__FlatPlateRadiationFacet ()
Additional Inherited Members
Static Protected Attributes inherited from jeod::RadiationFacet
static const double two_thirds = 2.0 / 3.0
quite literally, 2/3.
Static Protected Attributes inherited from jeod::RadiationBaseFacet
static const double speed_of_light = 299792458.0
Speed of light in vacuum.
Detailed Description
A flat plate facet to be used for radiation interaction.
Definition at line 86 of file flat_plate_radiation_facet.hh.
Constructor & Destructor Documentation
FlatPlateRadiationFacet() [1/2]
jeod::FlatPlateRadiationFacet::FlatPlateRadiationFacet (void)
Construct a FlatPlateRadiationFacet.
Definition at line 55 of file flat_plate_radiation_facet.cc.
References jeod::Vector3::initialize().
~FlatPlateRadiationFacet()
jeod::FlatPlateRadiationFacet::~FlatPlateRadiationFacet (void) override
Destructor for FlatPlateRadiationFacet.
Definition at line 218 of file flat_plate_radiation_facet.cc.
FlatPlateRadiationFacet() [2/2]
jeod::FlatPlateRadiationFacet::FlatPlateRadiationFacet (const FlatPlateRadiationFacet & rhs) private
Member Function Documentation
define_facet()
void jeod::FlatPlateRadiationFacet::define_facet (FlatPlate * flat_plate)
Defines the facet data values.
Parameters
[in] flat_plate pointer to the flat plate object
Definition at line 70 of file flat_plate_radiation_facet.cc.
References jeod::RadiationFacet::center_pressure, normal, jeod::FlatPlate::normal, and jeod::Facet::position.
Referenced by jeod::FlatPlateRadiationFactory::create_facet().
incident_radiation()
void jeod::FlatPlateRadiationFacet::incident_radiation (const double flux_mag, const double flux_struct_hat[3], const bool calculate_forces) override virtual
Calculation of force and torque due to radiation pressure.
Assumptions and Limitations
Only called when flux_mag > 0
Parameters
[in] flux_mag incident flux (per unit area)
Units: N/m
[in] flux_struct_hat the flux unit vector in structural frame
[in] calculate_forces on/off flag for whether to calculate forces.
Implements jeod::RadiationBaseFacet.
Definition at line 114 of file flat_plate_radiation_facet.cc.
References jeod::RadiationBaseFacet::albedo, jeod::Facet::area, jeod::RadiationBaseFacet::areaxflux, jeod::RadiationBaseFacet::areaxflux_e, jeod::InteractionFacet::base_facet, jeod::RadiationBaseFacet::cx_area, jeod::Vector3::diff(), jeod::RadiationBaseFacet::diffuse, jeod::Vector3::dot(), jeod::RadiationBaseFacet::F_absorption, jeod::RadiationBaseFacet::F_diffuse, jeod::RadiationBaseFacet::F_specular, jeod::Vector3::incr(), normal, jeod::ThermalFacetRider::power_absorb, jeod::Vector3::scale(), sin_theta, jeod::RadiationBaseFacet::speed_of_light, jeod::RadiationBaseFacet::thermal, and jeod::RadiationFacet::two_thirds.
initialize_geom()
void jeod::FlatPlateRadiationFacet::initialize_geom (double center_grav[3]) override virtual
Initializes the Facet for use in the model.
Parameters
[in] center_grav center of gravity position
Units: M
Implements jeod::RadiationFacet.
Definition at line 92 of file flat_plate_radiation_facet.cc.
References jeod::Facet::area, jeod::InteractionFacet::base_facet, jeod::RadiationFacet::center_pressure, jeod::RadiationFacet::crot_to_cp, jeod::Vector3::diff(), jeod::RadiationFacet::initialize(), jeod::ThermalFacetRider::initialize(), jeod::Facet::temperature, and jeod::RadiationBaseFacet::thermal.
operator=()
FlatPlateRadiationFacet& jeod::FlatPlateRadiationFacet::operator= (const FlatPlateRadiationFacet & rhs) private
radiation_pressure()
void jeod::FlatPlateRadiationFacet::radiation_pressure (void) override virtual
Calculates the radiative emission force, accumulated force, and torque acting on a facet.
Implements jeod::RadiationFacet.
Definition at line 177 of file flat_plate_radiation_facet.cc.
References jeod::ThermalIntegrableObject::active, jeod::InteractionFacet::base_facet, jeod::ThermalIntegrableObject::compute_temp_dot(), jeod::Vector3::cross(), jeod::RadiationFacet::crot_to_cp, jeod::RadiationBaseFacet::F_absorption, jeod::RadiationBaseFacet::F_diffuse, jeod::RadiationBaseFacet::F_emission, jeod::RadiationBaseFacet::F_specular, jeod::MessageHandler::fail(), jeod::InteractionFacet::force, jeod::Vector3::incr(), jeod::ThermalFacetRider::integrable_object, jeod::Facet::name, normal, jeod::ThermalFacetRider::power_emit, jeod::Vector3::scale(), jeod::RadiationBaseFacet::speed_of_light, jeod::Vector3::sum(), jeod::RadiationBaseFacet::thermal, jeod::InteractionFacet::torque, jeod::RadiationFacet::two_thirds, and jeod::RadiationMessages::unknown_numerical_error.
Friends And Related Function Documentation
init_attrjeod__FlatPlateRadiationFacet
void init_attrjeod__FlatPlateRadiationFacet () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file flat_plate_radiation_facet.hh.
Field Documentation
incident_flux_hat
double jeod::FlatPlateRadiationFacet::incident_flux_hat[3]
Temporary value.
trick_units(–)
Definition at line 104 of file flat_plate_radiation_facet.hh.
normal
double* jeod::FlatPlateRadiationFacet::normal
Unit vector normal to the plate surface, pointing outward (structural frame).
once the radiation surface is initialized, it points to the normal found in FlatPlatetrick_units(–)
Definition at line 99 of file flat_plate_radiation_facet.hh.
Referenced by define_facet(), incident_radiation(), and radiation_pressure().
sin_theta
double jeod::FlatPlateRadiationFacet::sin_theta private
Theta is the angle between the plate and the radiation vector.
trick_units(–)
Definition at line 110 of file flat_plate_radiation_facet.hh.
Referenced by incident_radiation().
The documentation for this class was generated from the following files:
flat_plate_radiation_facet.hh
flat_plate_radiation_facet.cc