JEOD: jeod::MassPropertiesInit Class Reference
jeod::MassPropertiesInit Class Reference
Contains data used to initialize a mass model object.
#include <mass_properties_init.hh>
Public Types
enum InertiaSpec {
NoSpec = 0, Body = 1, StructCG = 2, Struct = 3,
SpecCG = 4, Spec = 5
}
Specifies the origin and axes of the input inertia tensor.
Public Types inherited from jeod::MassPointInit
enum FrameSpec {
StructToBody = 0, StructToCase = 0, StructToPoint = 0, StructToChild = 0,
BodyToStruct = 1, CaseToStruct = 1, PointToStruct = 1, ChildToStruct = 1
}
Specifies sense of the input point orientation data.
Public Member Functions
MassPropertiesInit ()
Default constructor; constructs a MassPropertiesInit object.
void initialize_mass_properties (MassProperties &mass_properties) const
Initialize the subject MassProperties.
Public Member Functions inherited from jeod::MassPointInit
MassPointInit ()
virtual ~MassPointInit ()=default
void initialize_mass_point (MassPoint &mass_point) const
Default constructor; constructs a MassPointInit object.
void set_name (std::string name_in)
Set the name.
Data Fields
double mass {}
Mass of the core body.
double * cm
Location of the core body center of mass in the structural frame.
double inertia [3][3] {}
Inertia tensor of the core body in an arbitrary reference frame.
InertiaSpec inertia_spec {Body}
Indicates how the user has specified the core inertia matrix.
double inertia_offset [3] {}
Offset from inertia reference frame to the core center of mass, expressed in inertia reference frame coordinates.
Orientation inertia_orientation
Orientation of body frame wrt inertia reference frame, i.e.
Data Fields inherited from jeod::MassPointInit
double position [3] {}
Mass point location expressed in mass element structural coordinates.
Orientation pt_orientation
Mass point frame orientation specification.
FrameSpec pt_frame_spec {StructToPoint}
Indicates whether user orientation input defines the structure-to-body or body-to-structure transformation matrix.
std::string name {""}
Item name, with the following semantics for items that have a name:
Friends
class InputProcessor
void init_attrjeod__MassPropertiesInit ()
Detailed Description
Contains data used to initialize a mass model object.
Definition at line 79 of file mass_properties_init.hh.
Member Enumeration Documentation
InertiaSpec
enum jeod::MassPropertiesInit::InertiaSpec
Specifies the origin and axes of the input inertia tensor.
Enumerator
NoSpec
Inertia matrix is specified directly.
Body
Initial inertia frame is body frame.
StructCG
Initial inertia frame is struct at CG.
Struct
Initial inertia frame is structural frame.
SpecCG
Initial inertia frame is in frame at CG.
Spec
Initial inertia frame is specified frame.
Definition at line 87 of file mass_properties_init.hh.
Constructor & Destructor Documentation
MassPropertiesInit()
jeod::MassPropertiesInit::MassPropertiesInit ()
Default constructor; constructs a MassPropertiesInit object.
Definition at line 55 of file mass_properties_init.cc.
References cm, and jeod::MassPointInit::position.
Member Function Documentation
initialize_mass_properties()
void jeod::MassPropertiesInit::initialize_mass_properties (MassProperties & properties) const
Initialize the subject MassProperties.
Parameters
[out] properties Properties to initialize
Definition at line 65 of file mass_properties_init.cc.
References Body, jeod::MassBody::compute_point_mass_inertia(), jeod::Orientation::compute_transform(), jeod::Matrix3x3::copy(), jeod::MessageHandler::fail(), jeod::MassProperties::inertia, inertia, inertia_offset, inertia_orientation, inertia_spec, jeod::MassPointInit::initialize_mass_point(), jeod::MassBodyMessages::invalid_enum, jeod::MassProperties::mass, mass, NoSpec, jeod::MassPointState::position, Spec, SpecCG, Struct, StructCG, jeod::Matrix3x3::subtract(), jeod::MassPointState::T_parent_this, jeod::Orientation::trans, and jeod::Matrix3x3::transform_matrix().
Referenced by jeod::MassBody::initialize_mass().
Friends And Related Function Documentation
init_attrjeod__MassPropertiesInit
void init_attrjeod__MassPropertiesInit () friend
InputProcessor
friend class InputProcessor friend
Definition at line 81 of file mass_properties_init.hh.
Field Documentation
cm
double* jeod::MassPropertiesInit::cm
Location of the core body center of mass in the structural frame.
This is just an alias for the generic position member.trick_units(m)
Definition at line 108 of file mass_properties_init.hh.
Referenced by MassPropertiesInit().
inertia
double jeod::MassPropertiesInit::inertia[3][3] {}
Inertia tensor of the core body in an arbitrary reference frame.
trick_units(kg*m2)
Definition at line 113 of file mass_properties_init.hh.
Referenced by initialize_mass_properties().
inertia_offset
double jeod::MassPropertiesInit::inertia_offset[3] {}
Offset from inertia reference frame to the core center of mass, expressed in inertia reference frame coordinates.
trick_units(m)
Definition at line 124 of file mass_properties_init.hh.
Referenced by initialize_mass_properties().
inertia_orientation
Orientation jeod::MassPropertiesInit::inertia_orientation
Orientation of body frame wrt inertia reference frame, i.e.
the process by which the frame in which the inertia tensor is specified may be transformed to the body frame, e.g. T_{spec->body}.trick_units(–)
Definition at line 131 of file mass_properties_init.hh.
Referenced by initialize_mass_properties().
inertia_spec
InertiaSpec jeod::MassPropertiesInit::inertia_spec {Body}
Indicates how the user has specified the core inertia matrix.
trick_units(–)
Definition at line 118 of file mass_properties_init.hh.
Referenced by initialize_mass_properties().
mass
double jeod::MassPropertiesInit::mass {}
Mass of the core body.
trick_units(kg)
Definition at line 102 of file mass_properties_init.hh.
Referenced by initialize_mass_properties().
The documentation for this class was generated from the following files:
mass_properties_init.hh
mass_properties_init.cc