JEOD: jeod::SphericalHarmonicsSolidBodyTides Class Reference
jeod::SphericalHarmonicsSolidBodyTides Class Reference
Models solid body tidal effects.
#include <spherical_harmonics_solid_body_tides.hh>
Public Member Functions
SphericalHarmonicsSolidBodyTides ()
SphericalHarmonicsSolidBodyTides constructor.
~SphericalHarmonicsSolidBodyTides () override
SphericalHarmonicsSolidBodyTides destructor.
void initialize (SphericalHarmonicsDeltaCoeffsInit &var_init, BaseDynManager &dyn_manager) override
Initialize the solid body tidal model.
void update (SphericalHarmonicsGravityControls &controls) override
Update the solid-body tidal delta-coefficients.
Public Member Functions inherited from jeod::SphericalHarmonicsTidalEffects
SphericalHarmonicsTidalEffects ()
SphericalHarmonicsTidalEffects constructor.
~SphericalHarmonicsTidalEffects () override
SphericalHarmonicsTidalEffects destructor.
void initialize (SphericalHarmonicsDeltaCoeffsInit &var_init, BaseDynManager &dyn_manager) override
Initialize a SphericalHarmonicsTidalEffects object.
void update (SphericalHarmonicsGravityControls &controls) override
Pure virtual update method.
Public Member Functions inherited from jeod::SphericalHarmonicsDeltaCoeffs
SphericalHarmonicsDeltaCoeffs ()
SphericalHarmonicsDeltaCoeffs constructor.
virtual ~SphericalHarmonicsDeltaCoeffs ()
SphericalHarmonicsDeltaCoeffs destructor.
Friends
class InputProcessor
void init_attrjeod__SphericalHarmonicsSolidBodyTides ()
Additional Inherited Members
Data Fields inherited from jeod::SphericalHarmonicsTidalEffects
double xp
Copy of polar motion coefficient xp (from polar motion class).
double yp
Copy of polar motion coefficient yp (from polar motion class).
double k2
The love number.
double ** Knm
A matrix of love numbers.
unsigned int num_tidal_bodies
The number of tidal bodies named in tidal_bodies.
Data Fields inherited from jeod::SphericalHarmonicsDeltaCoeffs
SphericalHarmonicsGravitySource * grav_source
Pointer to the gravity body associated with this effect.
double ** delta_Cnm
Normalized real (cosine) variational spherical harmonic coefficients.
double ** delta_Snm
Normalized imaginary (sine) variational spherical harmonic coeffs.
unsigned int degree
Coefficient degree to be used for this SphericalHarmonicsDeltaCoeffs.
unsigned int order
Coefficient order to be used for this SphericalHarmonicsDeltaCoeffs.
double dC20
delta C20 coefficient for first order effect
Protected Attributes inherited from jeod::SphericalHarmonicsTidalEffects
Planet ** tidal_bodies
The tidal bodies.
RefFrame ** tidal_bodies_inertial
Pointers to the tidal_bodies inertial reference frames.
RefFrame * pfix
The planet fixed reference frame of the subject body.
Detailed Description
Models solid body tidal effects.
Definition at line 92 of file spherical_harmonics_solid_body_tides.hh.
Constructor & Destructor Documentation
SphericalHarmonicsSolidBodyTides()
jeod::SphericalHarmonicsSolidBodyTides::SphericalHarmonicsSolidBodyTides (void)
SphericalHarmonicsSolidBodyTides constructor.
Definition at line 58 of file spherical_harmonics_solid_body_tides.cc.
~SphericalHarmonicsSolidBodyTides()
jeod::SphericalHarmonicsSolidBodyTides::~SphericalHarmonicsSolidBodyTides (void) override
SphericalHarmonicsSolidBodyTides destructor.
Definition at line 68 of file spherical_harmonics_solid_body_tides.cc.
Member Function Documentation
initialize()
void jeod::SphericalHarmonicsSolidBodyTides::initialize (SphericalHarmonicsDeltaCoeffsInit & var_init, BaseDynManager & dyn_manager) override virtual
Initialize the solid body tidal model.
Parameters
[in] var_init Effect init structure
[in] dyn_manager Dynamics manager
Reimplemented from jeod::SphericalHarmonicsDeltaCoeffs.
Definition at line 82 of file spherical_harmonics_solid_body_tides.cc.
References jeod::SphericalHarmonicsTidalEffects::initialize().
update()
void jeod::SphericalHarmonicsSolidBodyTides::update (SphericalHarmonicsGravityControls & controls) override virtual
Update the solid-body tidal delta-coefficients.
Parameters
[in] controls Gravity controls for planet
Reimplemented from jeod::SphericalHarmonicsDeltaCoeffs.
Definition at line 98 of file spherical_harmonics_solid_body_tides.cc.
References jeod::RefFrame::compute_position_from(), jeod::SphericalHarmonicsDeltaCoeffs::dC20, jeod::SphericalHarmonicsDeltaCoeffs::grav_source, jeod::BasePlanet::grav_source, jeod::SphericalHarmonicsTidalEffects::k2, jeod::GravitySource::mu, jeod::SphericalHarmonicsTidalEffects::num_tidal_bodies, jeod::SphericalHarmonicsTidalEffects::pfix, jeod::SphericalHarmonicsGravitySource::radius, jeod::SphericalHarmonicsTidalEffects::tidal_bodies, jeod::SphericalHarmonicsTidalEffects::tidal_bodies_inertial, and jeod::Vector3::vmag().
Friends And Related Function Documentation
init_attrjeod__SphericalHarmonicsSolidBodyTides
void init_attrjeod__SphericalHarmonicsSolidBodyTides () friend
InputProcessor
friend class InputProcessor friend
Definition at line 94 of file spherical_harmonics_solid_body_tides.hh.
The documentation for this class was generated from the following files:
spherical_harmonics_solid_body_tides.hh
spherical_harmonics_solid_body_tides.cc