JEOD: jeod::RelativeKinematics Class Reference
jeod::RelativeKinematics Class Reference
Encapsulates functionality for computing relative states.
#include <relative_kinematics.hh>
Public Member Functions
RelativeKinematics ()
Construct a RelativeKinematics object.
~RelativeKinematics ()
Destruct a RelativeKinematics object.
RelativeKinematics (const RelativeKinematics &)=delete
RelativeKinematics & operator= (const RelativeKinematics &)=delete
void add_relstate (RelativeDerivedState &relstate)
Add a relative state to the list of ones maintained by this model.
void remove_relstate (RelativeDerivedState &relstate)
Remove a relative state from the list of ones maintained by this model.
RelativeDerivedState * find_relstate (const std::string &relstate_name)
Find a specific relative state maintained by this model.
void activate_relstate (RelativeDerivedState &relstate, bool raf)
Set flag for a relative state to be activated or deactivated by the RelKin manager.
void update_single (const std::string &relstate_name)
Update a single relative state maintained by this model.
void update_all ()
Update all relative states maintained by this model.
Data Fields
unsigned int num_rel_states {}
Length of above list of relative states being maintained by this.
JeodPointerVector< RelativeDerivedState >::type relative_states
List of relative states to be computed and maintained by this model.
Friends
class InputProcessor
void init_attrjeod__RelativeKinematics ()
Detailed Description
Encapsulates functionality for computing relative states.
Definition at line 85 of file relative_kinematics.hh.
Constructor & Destructor Documentation
RelativeKinematics() [1/2]
jeod::RelativeKinematics::RelativeKinematics ()
Construct a RelativeKinematics object.
Definition at line 55 of file relative_kinematics.cc.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, and relative_states.
~RelativeKinematics()
jeod::RelativeKinematics::~RelativeKinematics ()
Destruct a RelativeKinematics object.
Definition at line 65 of file relative_kinematics.cc.
References JEOD_DEREGISTER_CHECKPOINTABLE, and relative_states.
RelativeKinematics() [2/2]
jeod::RelativeKinematics::RelativeKinematics (const RelativeKinematics &) delete
Member Function Documentation
activate_relstate()
void jeod::RelativeKinematics::activate_relstate (RelativeDerivedState & relstate, bool raf)
Set flag for a relative state to be activated or deactivated by the RelKin manager.
Parameters
[in] relstate Relstate to activate/deactivate
[in] raf bool Relstate activation flag
Definition at line 151 of file relative_kinematics.cc.
References jeod::RelKinMessages::entry_not_found, jeod::MessageHandler::fail(), find_relstate(), jeod::RelKinMessages::invalid_entry, jeod::RelativeDerivedState::name, and jeod::RelativeDerivedState::set_activation_flag().
add_relstate()
void jeod::RelativeKinematics::add_relstate (RelativeDerivedState & relstate)
Add a relative state to the list of ones maintained by this model.
Parameters
[in] relstate Relstate to add
Definition at line 74 of file relative_kinematics.cc.
References jeod::RelKinMessages::duplicate_entry, jeod::MessageHandler::fail(), find_relstate(), jeod::RelativeDerivedState::name, num_rel_states, relative_states, and jeod::NamedItem::validate_name().
find_relstate()
RelativeDerivedState * jeod::RelativeKinematics::find_relstate (const std::string & relstate_name)
Find a specific relative state maintained by this model.
Returns
Void
Parameters
[in] relstate_name Relstate to find
Definition at line 128 of file relative_kinematics.cc.
References num_rel_states, and relative_states.
Referenced by activate_relstate(), add_relstate(), and update_single().
operator=()
RelativeKinematics& jeod::RelativeKinematics::operator= (const RelativeKinematics &) delete
remove_relstate()
void jeod::RelativeKinematics::remove_relstate (RelativeDerivedState & relstate)
Remove a relative state from the list of ones maintained by this model.
Parameters
[in] relstate Relstate to remove
Definition at line 105 of file relative_kinematics.cc.
References jeod::RelKinMessages::entry_not_found, jeod::MessageHandler::error(), jeod::RelativeDerivedState::name, num_rel_states, and relative_states.
update_all()
void jeod::RelativeKinematics::update_all ()
Update all relative states maintained by this model.
relstates that have been deactivated from RelKin will not be update.
Definition at line 198 of file relative_kinematics.cc.
References num_rel_states, and relative_states.
update_single()
void jeod::RelativeKinematics::update_single (const std::string & relstate_name)
Update a single relative state maintained by this model.
Parameters
[in] relstate_name Relstate to update
Definition at line 187 of file relative_kinematics.cc.
References find_relstate(), and jeod::RelativeDerivedState::update().
Friends And Related Function Documentation
init_attrjeod__RelativeKinematics
void init_attrjeod__RelativeKinematics () friend
InputProcessor
friend class InputProcessor friend
Definition at line 87 of file relative_kinematics.hh.
Field Documentation
num_rel_states
unsigned int jeod::RelativeKinematics::num_rel_states {}
Length of above list of relative states being maintained by this.
trick_units(–)
Definition at line 92 of file relative_kinematics.hh.
Referenced by add_relstate(), find_relstate(), remove_relstate(), and update_all().
relative_states
JeodPointerVector<RelativeDerivedState>::type jeod::RelativeKinematics::relative_states
List of relative states to be computed and maintained by this model.
Note that this list is not restricted to be relative states associated with only a single DynBody.trick_io(**)
Definition at line 99 of file relative_kinematics.hh.
Referenced by add_relstate(), find_relstate(), RelativeKinematics(), remove_relstate(), update_all(), and ~RelativeKinematics().
The documentation for this class was generated from the following files:
relative_kinematics.hh
relative_kinematics.cc