JEOD: jeod::TimeStandard Class Reference
jeod::TimeStandard Class Reference abstract
A class that serves as the base for all time representations that are well defined outside the simulation.
#include <time_standard.hh>
Public Member Functions
TimeStandard ()=default
~TimeStandard () override=default
TimeStandard (const TimeStandard &)=delete
TimeStandard & operator= (const TimeStandard &)=delete
void calendar_update (double simtime)
Calls the function that converts the Julian-type representation of time (dd.xxxx days) to a calendar representation.
void initialize_initializer_time (TimeManagerInit *tm_init) override
Each time type is initialized from its parent in the initialization tree, except one.
void add_type_initialize (const int seeking_status, TimeManagerInit *tm_init) override
Recursively adds elements to the initialization tree.
void initialize_from_parent (TimeManagerInit *tm_init) override
Initialize a time type from its parent on the initialization tree.
void set_time_by_seconds (const double new_seconds) override
Given a value of seconds, propagate to days and trunc_julian_time.
void set_time_by_days (const double new_days) override
Given a value of days, propagate to seconds and trunc_julian_time.
void set_time_by_trunc_julian (const double new_tjt)
Given a value of tjt, propagate to seconds and days.
double julian_date_at_epoch ()
Returns the full Julian date at epoch, rather than the Truncated Julian Time.
double seconds_of_year ()
Generate the number of seconds elapsed this year.
Public Member Functions inherited from jeod::JeodBaseTime
JeodBaseTime ()
Construct a JeodBaseTime.
virtual ~JeodBaseTime ()
Destroy a JeodBaseTime.
JeodBaseTime (const JeodBaseTime &)=delete
JeodBaseTime & operator= (const JeodBaseTime &)=delete
virtual bool must_be_singleton ()
Virtual function that indicates if class must be a singleton Defaults to yes.
void add_type_update (const int seeking_status, TimeManagerInit *tm_init)
Recursively adds elements to the update tree.
void set_name (std::string name_in)
Setter for the name.
void set_index (int idx)
Setter for the index (force user to be carefule)
int get_index ()
Getter for the index.
void override_initialized (bool init)
Force reset the initialization status.
bool is_initialized ()
Read the initialization status.
virtual void update ()
Updates each of the derived times from its parent time.
Data Fields
double last_calendar_update {-100000.0}
The simtime when the calendar update was last run.
int prev_julian_day {-1000000000}
Used for determining whether to update the date in the calendar function.
double seconds_at_year_start {}
The value of "seconds" at the start of the year in which the last seconds_of_year calculation was made.
int year_of_last_soy {-1000000}
The year in which the last seconds_of_year calculation was made.
bool send_warning_pre_1968 {true}
This flag can be turned off by developers wanting to avoid warnings about a simulation being initialized pre-1968.
const double tjt_mjt_offset {40000.0}
Difference between Truncated Julian and Modified Julian.
const double tjt_jd_offset {2440000.5}
Difference between Julian and Truncated Julian.
double trunc_julian_time {}
Truncated Julian time for this time-type.
double julian_date {}
Conventional Julian Date.
double tjt_at_epoch {}
Truncated Julian Date at epoch.
int calendar_day {}
Gregorian calendar date day number.
int calendar_hour {}
24-hour clock hour number.
int calendar_minute {}
Clock minute number.
double calendar_second {}
Clock second number.
int calendar_year {}
Gregorian calendar year.
int calendar_month {}
Gregorian calendar month.
Data Fields inherited from jeod::JeodBaseTime
double initializing_value {}
Value used to define sim start time.
int update_converter_direction {}
Determines which converter function (a_to_b (+1) or b_to_a (-1)) to use.
double seconds {}
Elapsed time from epoch.
NamedItem name
Name of time-type.
std::string initialize_from_name {""}
Name of time-type from which initial value is derived.
std::string update_from_name {""}
Name of time-type from which update values are derived.
TimeManager * time_manager {}
Pointer to the TimeManager.
TimeConverter * update_converter_ptr {}
Pointer to the converter class needed to update the time.
Protected Member Functions
virtual void convert_from_calendar ()
Calculate Truncated Julian date/time from Gregorian calendar date and 24-hour clock representation.
virtual void calculate_calendar_values ()
Calculate Gregorian calendar date and 24-hour clock representation from Truncated Julian date/time.
virtual void set_epoch ()=0
Set the epoch time.
Protected Member Functions inherited from jeod::JeodBaseTime
void add_parent (JeodBaseTime &parent)
Link the argument time as the update source for this time.
Friends
class InputProcessor
class TimeUDE
void init_attrjeod__TimeStandard ()
Additional Inherited Members
Protected Attributes inherited from jeod::JeodBaseTime
int index {}
Index-value of time-type in the registry.
bool initialized {}
Whether time has been initialized to a real time.
double days {}
Elapsed time from epoch.
double initial_value {}
Value of "seconds" at the start of the sim.
double clock_resolution {0.0001}
The resolution limit when generating clock and calendar-clock values.
TimeLinks links
Linkage to the hierarchy of time conversions.
Detailed Description
A class that serves as the base for all time representations that are well defined outside the simulation.
Definition at line 88 of file time_standard.hh.
Constructor & Destructor Documentation
TimeStandard() [1/2]
jeod::TimeStandard::TimeStandard () default
~TimeStandard()
jeod::TimeStandard::~TimeStandard () override default
TimeStandard() [2/2]
jeod::TimeStandard::TimeStandard (const TimeStandard &) delete
Member Function Documentation
add_type_initialize()
void jeod::TimeStandard::add_type_initialize (const int seeking_status, TimeManagerInit * time_manager_init) override virtual
Recursively adds elements to the initialization tree.
If the "parent" to a time-type is defined, adds the "parent" then returns to adding the "child" type. If the "parent" is not defined it searches for a suitable "parent" from the types already in the tree. If that search is successful, it adds the "child" to the tree, otherwise it returns without change.
Assumptions and Limitations
This is vastly improved if the user defines the parent type "initialize_from" for each time representation, except the top-level initializer type.
Otherwise, the code will build the tree automatically, but it takes longer and may be less than ideal
Parameters
[in] seeking_status status-value for auto-seek
[in] time_manager_init The TM initializer.
Reimplemented from jeod::JeodBaseTime.
Definition at line 128 of file time_standard.cc.
References jeod::JeodBaseTime::add_type_initialize(), jeod::NamedItem::c_str(), jeod::MessageHandler::fail(), jeod::TimeManagerInit::get_conv_dir_init(), jeod::NamedItem::get_name(), jeod::TimeManagerInit::get_status(), jeod::TimeManager::get_time_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeManagerInit::increment_status(), jeod::JeodBaseTime::index, jeod::MessageHandler::inform(), jeod::JeodBaseTime::initialize_from_name, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, jeod::TimeManager::num_types, jeod::TimeManagerInit::set_status(), jeod::TimeManager::time_lookup(), and jeod::JeodBaseTime::time_manager.
calculate_calendar_values()
void jeod::TimeStandard::calculate_calendar_values () protected virtual
Calculate Gregorian calendar date and 24-hour clock representation from Truncated Julian date/time.
Assumptions and Limitations
Coverage is from March 1, 1600 onward.
Produces a time in 24-hour clock format.
Assumes that the values year, month, day, hour, minute, second, and truncated_julian_time are all present in the same class.
Reimplemented in jeod::TimeGPS, and jeod::TimeGMST.
Definition at line 255 of file time_standard.cc.
References calendar_day, calendar_hour, calendar_minute, calendar_month, calendar_second, calendar_year, jeod::JeodBaseTime::clock_resolution, prev_julian_day, and trunc_julian_time.
Referenced by calendar_update(), and seconds_of_year().
calendar_update()
void jeod::TimeStandard::calendar_update (double simtime)
Calls the function that converts the Julian-type representation of time (dd.xxxx days) to a calendar representation.
Makes sure that the time type on which it is called is up-to-date before doing so.
Assumptions and Limitations
Derived times must have a parent; this should be defined by the user, or if not, already determined when the update_tree was built.
Parameters
[in] simtime Simulation elapsed time, on the simulation clock
Units: s
Definition at line 343 of file time_standard.cc.
References calculate_calendar_values(), jeod::Numerical::compare_exact(), last_calendar_update, jeod::TimeManager::simtime, jeod::JeodBaseTime::time_manager, and jeod::TimeManager::update().
convert_from_calendar()
void jeod::TimeStandard::convert_from_calendar () protected virtual
Calculate Truncated Julian date/time from Gregorian calendar date and 24-hour clock representation.
Assumptions and Limitations
Coverage s from March 1, 1600 onward.
Assumes that time is in 24-hour clock format; 1:00:00 pm cannot be read correctly, but 13:00:00 can.
Assumes that the values year, month, day, hour, minute, second, and truncated_julian_time are all present in the same class.
Reimplemented in jeod::TimeGPS.
Definition at line 370 of file time_standard.cc.
References calendar_day, calendar_hour, calendar_minute, calendar_month, calendar_second, calendar_year, jeod::JeodBaseTime::days, jeod::JeodBaseTime::seconds, tjt_at_epoch, and trunc_julian_time.
Referenced by initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
initialize_from_parent()
void jeod::TimeStandard::initialize_from_parent (TimeManagerInit * time_manager_init) override virtual
Initialize a time type from its parent on the initialization tree.
Assumptions and Limitations
More than 1 time-type defined, otherwise this is not called.
Parameters
[in] time_manager_init The TM initializer.
Reimplemented from jeod::JeodBaseTime.
Definition at line 593 of file time_standard.cc.
References jeod::NamedItem::c_str(), jeod::TimeConverter::convert_a_to_b(), jeod::TimeConverter::convert_b_to_a(), jeod::MessageHandler::fail(), jeod::TimeManagerInit::get_conv_dir_init(), jeod::TimeManagerInit::get_conv_ptr_index(), jeod::TimeManager::get_converter_ptr(), jeod::TimeManager::get_time_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::JeodBaseTime::index, jeod::JeodBaseTime::initial_value, jeod::TimeMessages::initialization_error, jeod::TimeConverter::initialize(), jeod::JeodBaseTime::initialize_from_name, jeod::JeodBaseTime::initialize_from_parent(), jeod::JeodBaseTime::initialized, jeod::TimeConverter::is_initialized(), jeod::JeodBaseTime::is_initialized(), jeod::TimeMessages::memory_error, jeod::JeodBaseTime::name, jeod::TimeManager::num_types, jeod::JeodBaseTime::seconds, jeod::TimeManager::time_lookup(), and jeod::JeodBaseTime::time_manager.
initialize_initializer_time()
void jeod::TimeStandard::initialize_initializer_time (TimeManagerInit * time_manager_init) override virtual
Each time type is initialized from its parent in the initialization tree, except one.
In order to have an absolute reference time, one of the time types must be defined ahead of time. This is called the initializer time. This function initializes the initializer time.
Assumptions and Limitations
TimeDyn cannot be used as the initializer time.
Each time representation can have its own initializer function, or can inherit the one in TimeStandard.
Parameters
[in] time_manager_init The TM initializer.
Implements jeod::JeodBaseTime.
Definition at line 422 of file time_standard.cc.
References jeod::NamedItem::c_str(), jeod::TimeEnum::calendar, calendar_day, calendar_hour, calendar_minute, calendar_month, calendar_second, calendar_year, jeod::TimeEnum::clock, jeod::Numerical::compare_exact(), convert_from_calendar(), jeod::JeodBaseTime::days, jeod::TimeEnum::days_since_epoch, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::MessageHandler::inform(), jeod::JeodBaseTime::initial_value, jeod::JeodBaseTime::initialize_from_name, jeod::JeodBaseTime::initialized, jeod::JeodBaseTime::initializing_value, jeod::TimeMessages::invalid_data_error, jeod::TimeMessages::invalid_setup_error, jeod::TimeEnum::Julian, jeod::TimeEnum::julian, jeod::TimeEnum::modified_julian, jeod::JeodBaseTime::name, jeod::TimeMessages::redundancy_error, jeod::JeodBaseTime::seconds, jeod::TimeEnum::seconds_since_epoch, send_warning_pre_1968, jeod::TimeManagerInit::sim_start_format, tjt_at_epoch, trunc_julian_time, jeod::TimeEnum::truncated_julian, jeod::TimeEnum::undefined, and jeod::MessageHandler::warn().
julian_date_at_epoch()
double jeod::TimeStandard::julian_date_at_epoch ()
Returns the full Julian date at epoch, rather than the Truncated Julian Time.
Returns
Truncated Julian Time at the epoch of the time-type.
Units: day
Definition at line 105 of file time_standard.cc.
References tjt_at_epoch, and tjt_jd_offset.
operator=()
TimeStandard& jeod::TimeStandard::operator= (const TimeStandard &) delete
seconds_of_year()
double jeod::TimeStandard::seconds_of_year ()
Generate the number of seconds elapsed this year.
Assumptions and Limitations
Relies on the accuracy of the JEOD2.0 calendar.
Returns
Current second of year.
Definition at line 679 of file time_standard.cc.
References calculate_calendar_values(), calendar_day, calendar_hour, calendar_minute, calendar_month, calendar_second, calendar_year, jeod::Numerical::compare_exact(), convert_from_calendar(), jeod::JeodBaseTime::days, last_calendar_update, jeod::JeodBaseTime::seconds, seconds_at_year_start, jeod::TimeManager::simtime, jeod::JeodBaseTime::time_manager, trunc_julian_time, and year_of_last_soy.
set_epoch()
virtual void jeod::TimeStandard::set_epoch () protected pure virtual
Set the epoch time.
Implemented in jeod::TimeGPS, jeod::TimeUT1, jeod::TimeUTC, jeod::TimeGMST, jeod::TimeTDB, jeod::TimeTT, and jeod::TimeTAI.
set_time_by_days()
void jeod::TimeStandard::set_time_by_days (const double new_days) override virtual
Given a value of days, propagate to seconds and trunc_julian_time.
Assumptions and Limitations
86400 seconds = 1 day
Parameters
[in] new_days new value for days
Units: day
Reimplemented from jeod::JeodBaseTime.
Definition at line 77 of file time_standard.cc.
References jeod::JeodBaseTime::days, julian_date, jeod::JeodBaseTime::set_time_by_days(), tjt_at_epoch, tjt_jd_offset, and trunc_julian_time.
Referenced by jeod::TimeConverter_UT1_GMST::convert_a_to_b(), and jeod::TimeUDE::set_epoch_std().
set_time_by_seconds()
void jeod::TimeStandard::set_time_by_seconds (const double new_seconds) override virtual
Given a value of seconds, propagate to days and trunc_julian_time.
Assumptions and Limitations
86400 seconds = 1 day
Parameters
[in] new_seconds new value for seconds
Units: s
Reimplemented from jeod::JeodBaseTime.
Definition at line 63 of file time_standard.cc.
References jeod::JeodBaseTime::days, julian_date, jeod::JeodBaseTime::set_time_by_seconds(), tjt_at_epoch, tjt_jd_offset, and trunc_julian_time.
Referenced by jeod::TimeConverter_TAI_TT::convert_a_to_b(), jeod::TimeConverter_Dyn_TAI::convert_a_to_b(), jeod::TimeConverter_Dyn_TDB::convert_a_to_b(), jeod::TimeConverter_TAI_TDB::convert_a_to_b(), jeod::TimeConverter_TAI_TT::convert_b_to_a(), jeod::TimeConverter_TAI_GPS::convert_b_to_a(), jeod::TimeConverter_STD_UDE::convert_b_to_a(), jeod::TimeConverter_TAI_TDB::convert_b_to_a(), jeod::TimeUDE::set_epoch_std(), and jeod::TimeGPS::set_time_by_seconds().
set_time_by_trunc_julian()
void jeod::TimeStandard::set_time_by_trunc_julian (const double new_tjt)
Given a value of tjt, propagate to seconds and days.
Assumptions and Limitations
86400 seconds = 1 day
Parameters
[in] new_tjt new value for Truncated Julian Time
Units: day
Definition at line 92 of file time_standard.cc.
References jeod::JeodBaseTime::days, julian_date, jeod::JeodBaseTime::seconds, tjt_at_epoch, tjt_jd_offset, and trunc_julian_time.
Referenced by jeod::TimeConverter_TAI_UTC::convert_a_to_b(), jeod::TimeConverter_TAI_UT1::convert_a_to_b(), jeod::TimeConverter_TAI_UTC::convert_b_to_a(), jeod::TimeConverter_TAI_UT1::convert_b_to_a(), jeod::TimeUDE::set_epoch_std(), and jeod::TimeGPS::set_time_by_trunc_julian().
Friends And Related Function Documentation
init_attrjeod__TimeStandard
void init_attrjeod__TimeStandard () friend
InputProcessor
friend class InputProcessor friend
Definition at line 90 of file time_standard.hh.
TimeUDE
friend class TimeUDE friend
Definition at line 90 of file time_standard.hh.
Field Documentation
calendar_day
int jeod::TimeStandard::calendar_day {}
Gregorian calendar date day number.
trick_units(day)
Definition at line 157 of file time_standard.hh.
Referenced by calculate_calendar_values(), convert_from_calendar(), initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
calendar_hour
int jeod::TimeStandard::calendar_hour {}
24-hour clock hour number.
trick_units(hr)
Definition at line 162 of file time_standard.hh.
Referenced by calculate_calendar_values(), convert_from_calendar(), initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
calendar_minute
int jeod::TimeStandard::calendar_minute {}
Clock minute number.
trick_units(min)
Definition at line 167 of file time_standard.hh.
Referenced by calculate_calendar_values(), convert_from_calendar(), initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
calendar_month
int jeod::TimeStandard::calendar_month {}
Gregorian calendar month.
trick_units(–)
Definition at line 182 of file time_standard.hh.
Referenced by calculate_calendar_values(), convert_from_calendar(), initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
calendar_second
double jeod::TimeStandard::calendar_second {}
Clock second number.
trick_units(s)
Definition at line 172 of file time_standard.hh.
Referenced by calculate_calendar_values(), convert_from_calendar(), initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
calendar_year
int jeod::TimeStandard::calendar_year {}
Gregorian calendar year.
trick_units(–)
Definition at line 177 of file time_standard.hh.
Referenced by calculate_calendar_values(), convert_from_calendar(), initialize_initializer_time(), seconds_of_year(), and jeod::TimeUDE::set_epoch_std().
julian_date
double jeod::TimeStandard::julian_date {}
Conventional Julian Date.
NOTE - because this value is typically so large, it has very little room for fine-detail precision. It should only ever be used as an output for the likes of terminal displays and for input to legacy code. Never use for newly developed code.trick_units(day)
Definition at line 147 of file time_standard.hh.
Referenced by set_time_by_days(), set_time_by_seconds(), and set_time_by_trunc_julian().
last_calendar_update
double jeod::TimeStandard::last_calendar_update {-100000.0}
The simtime when the calendar update was last run.
trick_units(–)
Definition at line 97 of file time_standard.hh.
Referenced by calendar_update(), and seconds_of_year().
prev_julian_day
int jeod::TimeStandard::prev_julian_day {-1000000000}
Used for determining whether to update the date in the calendar function.
trick_units(day)
Definition at line 103 of file time_standard.hh.
Referenced by calculate_calendar_values().
seconds_at_year_start
double jeod::TimeStandard::seconds_at_year_start {}
The value of "seconds" at the start of the year in which the last seconds_of_year calculation was made.
Used for seconds_of_year calculations only.trick_units(s)
Definition at line 110 of file time_standard.hh.
Referenced by seconds_of_year().
send_warning_pre_1968
bool jeod::TimeStandard::send_warning_pre_1968 {true}
This flag can be turned off by developers wanting to avoid warnings about a simulation being initialized pre-1968.
The flag defaults to true - warning will be sent.trick_units(–)
Definition at line 124 of file time_standard.hh.
Referenced by initialize_initializer_time().
tjt_at_epoch
double jeod::TimeStandard::tjt_at_epoch {}
Truncated Julian Date at epoch.
trick_units(day)
Definition at line 152 of file time_standard.hh.
Referenced by convert_from_calendar(), jeod::TimeConverter_TAI_GPS::initialize(), jeod::TimeConverter_TAI_TDB::initialize(), initialize_initializer_time(), julian_date_at_epoch(), jeod::TimeConverter_TAI_TDB::set_a_to_b_offset(), jeod::TimeTAI::set_epoch(), jeod::TimeTT::set_epoch(), jeod::TimeTDB::set_epoch(), jeod::TimeUTC::set_epoch(), jeod::TimeUT1::set_epoch(), jeod::TimeGPS::set_epoch(), set_time_by_days(), set_time_by_seconds(), and set_time_by_trunc_julian().
tjt_jd_offset
const double jeod::TimeStandard::tjt_jd_offset {2440000.5}
Difference between Julian and Truncated Julian.
trick_units(day)
Definition at line 134 of file time_standard.hh.
Referenced by jeod::De4xxEphemeris::initialize_file(), julian_date_at_epoch(), set_time_by_days(), set_time_by_seconds(), and set_time_by_trunc_julian().
tjt_mjt_offset
const double jeod::TimeStandard::tjt_mjt_offset {40000.0}
Difference between Truncated Julian and Modified Julian.
trick_units(day)
Definition at line 129 of file time_standard.hh.
trunc_julian_time
double jeod::TimeStandard::trunc_julian_time {}
Truncated Julian time for this time-type.
trick_units(day)
Definition at line 139 of file time_standard.hh.
Referenced by calculate_calendar_values(), jeod::TimeConverter_TAI_UTC::convert_a_to_b(), jeod::TimeConverter_TAI_UT1::convert_a_to_b(), jeod::TimeConverter_TAI_UTC::convert_b_to_a(), jeod::TimeConverter_TAI_UT1::convert_b_to_a(), convert_from_calendar(), jeod::De4xxEphemeris::ephem_update(), jeod::TimeConverter_TAI_UTC::initialize(), jeod::TimeConverter_TAI_UT1::initialize(), jeod::De4xxEphemeris::initialize_file(), initialize_initializer_time(), jeod::TimeConverter_TAI_UTC::initialize_leap_second(), jeod::TimeConverter_TAI_UT1::initialize_tai_to_ut1(), seconds_of_year(), jeod::TimeConverter_TAI_TDB::set_a_to_b_offset(), set_time_by_days(), set_time_by_seconds(), set_time_by_trunc_julian(), jeod::De4xxEphemeris::time_is_in_range(), jeod::RNPJ2000::update_rnp(), jeod::TimeConverter_TAI_UTC::verify_table_lookup_ends(), and jeod::TimeConverter_TAI_UT1::verify_table_lookup_ends().
year_of_last_soy
int jeod::TimeStandard::year_of_last_soy {-1000000}
The year in which the last seconds_of_year calculation was made.
At the start of this year, seconds had value seconds_at_year_start. Used for seconds_of_year calculations only.trick_units(–)
Definition at line 117 of file time_standard.hh.
Referenced by seconds_of_year().
The documentation for this class was generated from the following files:
time_standard.hh
time_standard.cc