JEOD: jeod::GaussJacksonIntegratorConstructor Class Reference
jeod::GaussJacksonIntegratorConstructor Class Reference
Create state and time integrators that propagate using Gauss-Jackson.
#include <gauss_jackson_integrator_constructor.hh>
Public Member Functions
GaussJacksonIntegratorConstructor (void)
GaussJackson default constructor.
GaussJacksonIntegratorConstructor (const GaussJacksonIntegratorConstructor &src)
GaussJacksonIntegratorConstructor copy constructor.
~GaussJacksonIntegratorConstructor () override
GaussJacksonIntegratorConstructor destructor.
GaussJacksonIntegratorConstructor & operator= (GaussJacksonIntegratorConstructor src)
GaussJacksonIntegratorConstructor assignment operator.
void configure (const GaussJacksonConfig &config_in, er7_utils::Integration::Technique priming_technique=er7_utils::Integration::Unspecified)
Configure the Gauss-Jackson integrator constructor.
void configure (const GaussJacksonConfig &config_in, const er7_utils::IntegratorConstructor &priming_cotr_in)
Configure the Gauss-Jackson integrator constructor.
const char * get_class_name (void) const override
Return the class name.
bool implements (er7_utils::Integration::ODEProblemType problem_type) const override
GaussJackson does not implement a 2nd order generalized step integrator.
bool provides (er7_utils::Integration::ODEProblemType problem_type) const override
GaussJackson does not provide a 2nd order generalized step integrator.
virtual void swap (GaussJacksonIntegratorConstructor &src)
Non-throwing swap.
er7_utils::IntegratorConstructor * create_copy (void) const override
Create a duplicate of the constructor.
er7_utils::IntegrationControls * create_integration_controls (void) const override
Create an integration controls that guides the GaussJackson integration process.
er7_utils::FirstOrderODEIntegrator * create_first_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls &controls) const override
Create a GaussJackson state integrator for a first order ODE.
er7_utils::SecondOrderODEIntegrator * create_second_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls &controls) const override
Create a GaussJackson state integrator for a simple second order ODE.
er7_utils::SecondOrderODEIntegrator * create_generalized_deriv_second_order_ode_integrator (unsigned int position_size, unsigned int velocity_size, const er7_utils::GeneralizedPositionDerivativeFunctions &deriv_funs, er7_utils::IntegrationControls &controls) const override
Create a GaussJackson state integrator for a generalized second order ODE where generalized position is advanced with the use of the position derivative function.
unsigned int get_buffer_size (void) const override
GaussJackson can use a large number of steps per Trick cycle.
unsigned int get_transition_table_size (void) const override
GaussJackson uses two steps per cycle once primed.
Static Public Member Functions
static er7_utils::IntegratorConstructor * create_constructor (void)
Named constructor; create an GaussJacksonIntegratorConstructor instance.
Private Attributes
er7_utils::IntegratorConstructor * priming_constructor
The integrator constructor that creates the priming integrators.
GaussJacksonConfig config
Data used to configure the Gauss-Jackson integration process.
Friends
class InputProcessor
void init_attrjeod__GaussJacksonIntegratorConstructor ()
Detailed Description
Create state and time integrators that propagate using Gauss-Jackson.
Definition at line 81 of file gauss_jackson_integrator_constructor.hh.
Constructor & Destructor Documentation
GaussJacksonIntegratorConstructor() [1/2]
jeod::GaussJacksonIntegratorConstructor::GaussJacksonIntegratorConstructor (void)
GaussJackson default constructor.
Definition at line 79 of file gauss_jackson_integrator_constructor.cc.
GaussJacksonIntegratorConstructor() [2/2]
jeod::GaussJacksonIntegratorConstructor::GaussJacksonIntegratorConstructor (const GaussJacksonIntegratorConstructor & src)
GaussJacksonIntegratorConstructor copy constructor.
Definition at line 90 of file gauss_jackson_integrator_constructor.cc.
References priming_constructor.
~GaussJacksonIntegratorConstructor()
jeod::GaussJacksonIntegratorConstructor::~GaussJacksonIntegratorConstructor () override
GaussJacksonIntegratorConstructor destructor.
Definition at line 105 of file gauss_jackson_integrator_constructor.cc.
References priming_constructor.
Member Function Documentation
configure() [1/2]
void jeod::GaussJacksonIntegratorConstructor::configure (const GaussJacksonConfig & config_in, er7_utils::Integration::Technique priming_technique = er7_utils::Integration::Unspecified)
Configure the Gauss-Jackson integrator constructor.
Definition at line 123 of file gauss_jackson_integrator_constructor.cc.
References config, priming_constructor, jeod::GaussJacksonConfig::priming_technique, and jeod::GaussJacksonConfig::validate_configuration().
configure() [2/2]
void jeod::GaussJacksonIntegratorConstructor::configure (const GaussJacksonConfig & config_in, const er7_utils::IntegratorConstructor & priming_cotr_in)
Configure the Gauss-Jackson integrator constructor.
Definition at line 141 of file gauss_jackson_integrator_constructor.cc.
References config, priming_constructor, and jeod::GaussJacksonConfig::validate_configuration().
create_constructor()
er7_utils::IntegratorConstructor * jeod::GaussJacksonIntegratorConstructor::create_constructor (void) static
Named constructor; create an GaussJacksonIntegratorConstructor instance.
The caller is responsible for deleting the returned object.
Returns
Newly created GaussJacksonIntegratorConstructor instance.
Definition at line 71 of file gauss_jackson_integrator_constructor.cc.
create_copy()
er7_utils::IntegratorConstructor * jeod::GaussJacksonIntegratorConstructor::create_copy (void) const override
Create a duplicate of the constructor.
The caller is responsible for deleting the returned object.
Returns
Duplicated constructor.
Definition at line 152 of file gauss_jackson_integrator_constructor.cc.
create_first_order_ode_integrator()
er7_utils::FirstOrderODEIntegrator * jeod::GaussJacksonIntegratorConstructor::create_first_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls & controls) const override
Create a GaussJackson state integrator for a first order ODE.
The caller is responsible for deleting the created object.
Returns
State integrator
Parameters
[in] size State size
[in,out] controls Integration controls
Definition at line 179 of file gauss_jackson_integrator_constructor.cc.
References jeod::cast_to_gj_controls(), jeod::GaussJacksonIntegrationControls::get_priming_controls(), and priming_constructor.
create_generalized_deriv_second_order_ode_integrator()
er7_utils::SecondOrderODEIntegrator * jeod::GaussJacksonIntegratorConstructor::create_generalized_deriv_second_order_ode_integrator (unsigned int position_size, unsigned int velocity_size, const er7_utils::GeneralizedPositionDerivativeFunctions & deriv_funs, er7_utils::IntegrationControls & controls) const override
Create a GaussJackson state integrator for a generalized second order ODE where generalized position is advanced with the use of the position derivative function.
The caller is responsible for deleting the created object.
Returns
State integrator
Parameters
[in] position_size Size of the generalized position
[in] velocity_size Size of the generalized velocity
[in] deriv_funs Position derivative functions container
[in,out] controls Integration controls
Definition at line 222 of file gauss_jackson_integrator_constructor.cc.
References jeod::cast_to_gj_controls(), jeod::GaussJacksonIntegrationControls::get_priming_controls(), and priming_constructor.
create_integration_controls()
er7_utils::IntegrationControls * jeod::GaussJacksonIntegratorConstructor::create_integration_controls (void) const override
Create an integration controls that guides the GaussJackson integration process.
The caller is responsible for deleting the created object.
Returns
Integration controls object
Definition at line 161 of file gauss_jackson_integrator_constructor.cc.
References config, priming_constructor, and jeod::GaussJacksonConfig::standard_configuration().
create_second_order_ode_integrator()
er7_utils::SecondOrderODEIntegrator * jeod::GaussJacksonIntegratorConstructor::create_second_order_ode_integrator (unsigned int size, er7_utils::IntegrationControls & controls) const override
Create a GaussJackson state integrator for a simple second order ODE.
The caller is responsible for deleting the created object.
Returns
State integrator
Parameters
[in] size State size
[in,out] controls Integration controls
Definition at line 200 of file gauss_jackson_integrator_constructor.cc.
References jeod::cast_to_gj_controls(), jeod::GaussJacksonIntegrationControls::get_priming_controls(), and priming_constructor.
get_buffer_size()
unsigned int jeod::GaussJacksonIntegratorConstructor::get_buffer_size (void) const inline override
GaussJackson can use a large number of steps per Trick cycle.
The magic number 192 is for order=16, ndboubling=6.
Returns
Always returns 192.
Definition at line 240 of file gauss_jackson_integrator_constructor.hh.
get_class_name()
const char* jeod::GaussJacksonIntegratorConstructor::get_class_name (void) const inline override
Return the class name.
Definition at line 147 of file gauss_jackson_integrator_constructor.hh.
get_transition_table_size()
unsigned int jeod::GaussJacksonIntegratorConstructor::get_transition_table_size (void) const inline override
GaussJackson uses two steps per cycle once primed.
Returns
Always returns 2.
Definition at line 247 of file gauss_jackson_integrator_constructor.hh.
implements()
bool jeod::GaussJacksonIntegratorConstructor::implements (er7_utils::Integration::ODEProblemType problem_type) const inline override
GaussJackson does not implement a 2nd order generalized step integrator.
Definition at line 153 of file gauss_jackson_integrator_constructor.hh.
operator=()
GaussJacksonIntegratorConstructor& jeod::GaussJacksonIntegratorConstructor::operator= (GaussJacksonIntegratorConstructor src) inline
GaussJacksonIntegratorConstructor assignment operator.
Definition at line 119 of file gauss_jackson_integrator_constructor.hh.
References swap().
provides()
bool jeod::GaussJacksonIntegratorConstructor::provides (er7_utils::Integration::ODEProblemType problem_type) const inline override
GaussJackson does not provide a 2nd order generalized step integrator.
Definition at line 164 of file gauss_jackson_integrator_constructor.hh.
swap()
void jeod::GaussJacksonIntegratorConstructor::swap (GaussJacksonIntegratorConstructor & src) virtual
Non-throwing swap.
Parameters
[in,out] src Object with which contents are to be swapped.
Definition at line 113 of file gauss_jackson_integrator_constructor.cc.
References config, and priming_constructor.
Referenced by operator=().
Friends And Related Function Documentation
init_attrjeod__GaussJacksonIntegratorConstructor
void init_attrjeod__GaussJacksonIntegratorConstructor () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file gauss_jackson_integrator_constructor.hh.
Field Documentation
config
GaussJacksonConfig jeod::GaussJacksonIntegratorConstructor::config private
Data used to configure the Gauss-Jackson integration process.
trick_units(–)
Definition at line 260 of file gauss_jackson_integrator_constructor.hh.
Referenced by configure(), create_integration_controls(), and swap().
priming_constructor
er7_utils::IntegratorConstructor* jeod::GaussJacksonIntegratorConstructor::priming_constructor private
The integrator constructor that creates the priming integrators.
trick_units(–)
Definition at line 255 of file gauss_jackson_integrator_constructor.hh.
Referenced by configure(), create_first_order_ode_integrator(), create_generalized_deriv_second_order_ode_integrator(), create_integration_controls(), create_second_order_ode_integrator(), GaussJacksonIntegratorConstructor(), swap(), and ~GaussJacksonIntegratorConstructor().
The documentation for this class was generated from the following files:
gauss_jackson_integrator_constructor.hh
gauss_jackson_integrator_constructor.cc