JEOD: jeod::JeodSimEngineAttributes< Type, true > Class Template Reference
jeod::JeodSimEngineAttributes< Type, true > Class Template Reference
Partial template instantiation of JeodSimEngineAttributes for a class.
#include <memory_attributes_templates.hh>
Static Public Member Functions
static struct ATTRIBUTES_tag attributes (bool is_exportable=true)
Construct a JEOD_ATTRIBUTES_TYPE that represents a structured type.
Detailed Description
template<typename Type>
class jeod::JeodSimEngineAttributes< Type, true >
Partial template instantiation of JeodSimEngineAttributes for a class.
Template Parameters
Type The class.
Definition at line 148 of file memory_attributes_templates.hh.
Member Function Documentation
attributes()
template<typename Type > static struct ATTRIBUTES_tag jeod::JeodSimEngineAttributes< Type, true >::attributes (bool is_exportable = true) inline static
Construct a JEOD_ATTRIBUTES_TYPE that represents a structured type.
Parameters
is_exportable True => type is exportable.
Returns
Constructed attributes object.
Definition at line 156 of file memory_attributes_templates.hh.
References jeod::JeodMemoryInterface::find_attributes(), jeod::JeodSimulationInterface::get_memory_interface(), JEOD_ATTRIBUTES_POINTER_TYPE, and jeod::JeodMemoryInterface::structure_attributes().
The documentation for this class was generated from the following file:
memory_attributes_templates.hh