JEOD: jeod::PrecessionMars Class Reference
jeod::PrecessionMars Class Reference
Implements the axial rotation portion of the "Pathfinder" Mars RNP model.
#include <precession_mars.hh>
Public Member Functions
PrecessionMars ()=default
~PrecessionMars () override=default
PrecessionMars & operator= (const PrecessionMars &)=delete
PrecessionMars (const PrecessionMars &)=delete
void update_rotation () override
PrecessionMars specific implementation of update_rotation, to calculate precession.
void compute_fixed_matrices ()
Calculate constant rotation matrices resulting from N and J.
Public Member Functions inherited from jeod::PlanetRotation
PlanetRotation ()=default
virtual ~PlanetRotation ()=default
PlanetRotation & operator= (const PlanetRotation &)=delete
PlanetRotation (const PlanetRotation &)=delete
virtual void initialize (PlanetRotationInit *init)
Initializes the invoking object from an initialization object.
virtual void update_time (double time)
Update the time that the next update_rotation call will use.
void get_rotation (double rot[3][3])
Copy the last calculated rotation to 'rot'.
void get_rotation_transpose (double rot[3][3])
Same as get_rotation, but returns the transpose.
Data Fields
NutationMars * nutation {}
Pointer to the Mars nutation object, used to access nutation in longitude information.
double psi_at_j2000 {}
The (constant) precession angle of Mars at the J2000 epoch.
double psi_dot {}
The (constant) simple precession rate of Mars.
double psi_precess {}
The most recent calculated value of the precession angle for Mars, measured since J2000 epoch.
double N {}
The (constant) angle from the J2000 vernal equinox to the node of the Mars mean orbit and ICRF x-y plane.
double J {}
The (constant) inclination of the Mars mean orbit relative to the ICRF x-y plane.
Data Fields inherited from jeod::PlanetRotation
double rotation [3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } }
The transformation matrix outputted by the model after update is called.
double current_time {}
The current time the transformation matrix will be calculated from.
Private Attributes
double NJ_matrix [3][3] {}
The (constant) rotation matrix calculated from N and J.
Friends
class InputProcessor
void init_attrjeod__PrecessionMars ()
Additional Inherited Members
Protected Attributes inherited from jeod::PlanetRotation
double RADTODEG {180.0 / M_PI}
Convert from radians to degrees.
double DEGTORAD {M_PI / 180.0}
Inverse of RADTODEG.
double DEGTOSEC {60.0 * 60.0}
Convert from degrees to arcseconds.
double SECTODEG {1.0 / (60.0 * 60.0)}
Inverse of DEGTOSEC.
double JULIANDAYTOSEC {86400.0}
Convert from julian day to seconds.
double SECTOJULIANDAY {1.0 / 86400.0}
Inverse of JULIANDAYTOSEC.
double JULIANCENTTODAY {36525.0}
Convert from julian centuries to julian days.
double DAYTOJULIANCENT {1.0 / 36525.0}
Inverse of JULIANCENTTODAY.
Detailed Description
Implements the axial rotation portion of the "Pathfinder" Mars RNP model.
Definition at line 96 of file precession_mars.hh.
Constructor & Destructor Documentation
PrecessionMars() [1/2]
jeod::PrecessionMars::PrecessionMars () default
~PrecessionMars()
jeod::PrecessionMars::~PrecessionMars () override default
PrecessionMars() [2/2]
jeod::PrecessionMars::PrecessionMars (const PrecessionMars &) delete
Member Function Documentation
compute_fixed_matrices()
void jeod::PrecessionMars::compute_fixed_matrices ()
Calculate constant rotation matrices resulting from N and J.
Definition at line 109 of file precession_mars.cc.
References jeod::Matrix3x3::initialize(), J, N, NJ_matrix, and jeod::Matrix3x3::product().
Referenced by jeod::RNPMars::initialize().
operator=()
PrecessionMars& jeod::PrecessionMars::operator= (const PrecessionMars &) delete
update_rotation()
void jeod::PrecessionMars::update_rotation () override virtual
PrecessionMars specific implementation of update_rotation, to calculate precession.
Reimplemented from jeod::PlanetRotation.
Definition at line 62 of file precession_mars.cc.
References jeod::PlanetRotation::current_time, jeod::MessageHandler::fail(), NJ_matrix, nutation, jeod::NutationMars::nutation_in_longitude, jeod::Matrix3x3::product(), psi_at_j2000, psi_dot, psi_precess, jeod::PlanetRotation::rotation, and jeod::RNPMessages::setup_error.
Friends And Related Function Documentation
init_attrjeod__PrecessionMars
void init_attrjeod__PrecessionMars () friend
InputProcessor
friend class InputProcessor friend
Definition at line 98 of file precession_mars.hh.
Field Documentation
J
double jeod::PrecessionMars::J {}
The (constant) inclination of the Mars mean orbit relative to the ICRF x-y plane.
trick_units(rad)
Definition at line 133 of file precession_mars.hh.
Referenced by compute_fixed_matrices().
N
double jeod::PrecessionMars::N {}
The (constant) angle from the J2000 vernal equinox to the node of the Mars mean orbit and ICRF x-y plane.
trick_units(rad)
Definition at line 127 of file precession_mars.hh.
Referenced by compute_fixed_matrices().
NJ_matrix
double jeod::PrecessionMars::NJ_matrix[3][3] {} private
The (constant) rotation matrix calculated from N and J.
trick_units(–)
Definition at line 140 of file precession_mars.hh.
Referenced by compute_fixed_matrices(), and update_rotation().
nutation
NutationMars* jeod::PrecessionMars::nutation {}
Pointer to the Mars nutation object, used to access nutation in longitude information.
Will be NULL (automatically) if anything but Full_Term_RNP is set in the RNPMars object.trick_units(–)
Definition at line 105 of file precession_mars.hh.
Referenced by jeod::RNPMars::initialize(), and update_rotation().
psi_at_j2000
double jeod::PrecessionMars::psi_at_j2000 {}
The (constant) precession angle of Mars at the J2000 epoch.
trick_units(rad)
Definition at line 110 of file precession_mars.hh.
Referenced by update_rotation().
psi_dot
double jeod::PrecessionMars::psi_dot {}
The (constant) simple precession rate of Mars.
trick_units(rad/s)
Definition at line 115 of file precession_mars.hh.
Referenced by update_rotation().
psi_precess
double jeod::PrecessionMars::psi_precess {}
The most recent calculated value of the precession angle for Mars, measured since J2000 epoch.
trick_units(rad)
Definition at line 121 of file precession_mars.hh.
Referenced by update_rotation().
The documentation for this class was generated from the following files:
precession_mars.hh
precession_mars.cc