JEOD: jeod::ConstrainedRigidMass Class Reference
jeod::ConstrainedRigidMass Class Reference
A constrained rigid mass is a rigid body that is constrained to more or less move with a DynBody object.
#include <constrained_rigid_mass.hh>
Public Member Functions
ConstrainedRigidMass (const ConstraintFrame *constraint_frame_in=nullptr)
Default constructor.
~ConstrainedRigidMass () override=default
Destructor.
void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state) override
Prepare this object for solving a constraint problem.
void set_inertia (const double inertia_in[3][3])
Set the constrained object's inertia tensor.
Public Member Functions inherited from jeod::ConstrainedPointMass
ConstrainedPointMass (const ConstraintFrame *constraint_frame_in=nullptr)
Default constructor.
virtual ~ConstrainedPointMass ()=default
Destructor.
virtual void update_attachment (const VehicleProperties &)
Update information about the relation between this constrained object and the root DynBody.
void set_mass (double mass_in)
Set the constrained object's effective mass.
void set_constraint_position (const double constraint_position[3])
Set the constraint point position.
void compute_constraint_position_root ()
Compute the constraint point in root structural coordinates.
void compute_constraint_position_com (const VehicleProperties &vehicle_properties)
Compute the constraint point relative to the root body center of mass, in root structural coordinates.
void compute_non_grav_accel (const VehicleNonGravState &non_grav_state)
Compute the non-gravitational acceleration at the constraint point.
Data Fields
double inertia [3][3]
The effective inertia tensor of this constrained object about its center of mass, which is assumed to be at the inherited constraint position.
double torque_constraint_frame [3]
The torque on the associated DynBody, in constraint frame coordinates.
Data Fields inherited from jeod::ConstrainedPointMass
const ConstraintFrame * constraint_frame
The frame in which the constraint position is most naturally expressed.
double mass
The effective mass of this constrained object.
double constraint_position_constraint_frame [3]
The position at which the constraint equation applies, expressed in the constraint frame.
double constraint_position_root [3]
The constraint position, expressed in root structural frame coordinates.
double constraint_position_com [3]
The constraint position relative to the root vehicle center of mass, expressed in root structural frame coordinates.
double non_grav_accel_root [3]
The non-gravitational acceleration at the constraint point in root structural coordinates.
double non_grav_accel_constraint_frame [3]
The acceleration at the constraint point due to vehicular rotation and external forces and torques, in constraint frame coordinates.
double force_constraint_frame [3]
The force at the constraint point; mass * non_grav_accel_constraint_frame.
Friends
class InputProcessor
void init_attrjeod__ConstrainedRigidMass ()
Detailed Description
A constrained rigid mass is a rigid body that is constrained to more or less move with a DynBody object.
Definition at line 76 of file constrained_rigid_mass.hh.
Constructor & Destructor Documentation
ConstrainedRigidMass()
jeod::ConstrainedRigidMass::ConstrainedRigidMass (const ConstraintFrame * constraint_frame_in = nullptr)
Default constructor.
Definition at line 30 of file constrained_rigid_mass.cc.
References inertia, and jeod::Matrix3x3::initialize().
~ConstrainedRigidMass()
jeod::ConstrainedRigidMass::~ConstrainedRigidMass () override default
Destructor.
Member Function Documentation
set_inertia()
void jeod::ConstrainedRigidMass::set_inertia (const double inertia_in[3][3]) inline
Set the constrained object's inertia tensor.
The input matrix is assumed to be symmetric; only the upper right triangle is used.
Parameters
inertia_in New inertia tensor, expressed in the constraint frame.
Definition at line 131 of file constrained_rigid_mass.hh.
References inertia.
setup_constraint()
void jeod::ConstrainedRigidMass::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) override virtual
Prepare this object for solving a constraint problem.
In this case, that means computing constraint_position_com.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state Non-Gravitational State
Note
This function is called prior to the calls to set_self_coeff(), set_cross_coeff(), and set_r_h_s().
Reimplemented from jeod::ConstrainedPointMass.
Definition at line 40 of file constrained_rigid_mass.cc.
References jeod::ConstrainedPointMass::constraint_frame, jeod::Vector3::cross_incr(), inertia, jeod::VehicleNonGravState::omega_dot_struct, jeod::VehicleNonGravState::omega_struct, jeod::ConstrainedPointMass::setup_constraint(), jeod::ConstraintFrame::T_root_constraint, torque_constraint_frame, and jeod::Vector3::transform().
Referenced by jeod::DynBodyAttachedBodyConstraint::setup_constraint().
Friends And Related Function Documentation
init_attrjeod__ConstrainedRigidMass
void init_attrjeod__ConstrainedRigidMass () friend
InputProcessor
friend class InputProcessor friend
Definition at line 79 of file constrained_rigid_mass.hh.
Field Documentation
inertia
double jeod::ConstrainedRigidMass::inertia[3][3]
The effective inertia tensor of this constrained object about its center of mass, which is assumed to be at the inherited constraint position.
trick_units(kg/m^2)
Definition at line 92 of file constrained_rigid_mass.hh.
Referenced by ConstrainedRigidMass(), jeod::TorqueConstraintComponent::get_cross_coeff(), set_inertia(), and setup_constraint().
torque_constraint_frame
double jeod::ConstrainedRigidMass::torque_constraint_frame[3]
The torque on the associated DynBody, in constraint frame coordinates.
trick_units(N*m)
Definition at line 97 of file constrained_rigid_mass.hh.
Referenced by setup_constraint(), and jeod::DynBodyAttachedBodyConstraint::setup_constraint().
The documentation for this class was generated from the following files:
constrained_rigid_mass.hh
constrained_rigid_mass.cc