JEOD: jeod::NullMemoryInterface Class Reference
jeod::NullMemoryInterface Class Reference
A NullMemoryInterface extends the JeodMemoryInterface, providing the required functionality of the parent class in a null manner.
#include <null_memory_interface.hh>
Public Member Functions
NullMemoryInterface ()
Default constructor.
~NullMemoryInterface ()
Destructor.
bool is_checkpoint_restart_supported (void) const
Checkpoint/restart is not supported here.
const std::string get_name_at_address (const void *addr, const JeodMemoryTypeDescriptor *tdesc) const
Do-nothing get_name_at_address handler.
void * get_address_at_name (const std::string &name) const
Do-nothing get_address_at_name handler.
const struct ATTRIBUTES_tag * find_attributes (const std::string &) const
Do-nothing find_attributes handler.
const struct ATTRIBUTES_tag * find_attributes (const std::type_info &) const
Do-nothing find_attributes handler.
struct ATTRIBUTES_tag primitive_attributes (const std::type_info &) const
Do-nothing primitive_attributes handler.
struct ATTRIBUTES_tag pointer_attributes (const struct ATTRIBUTES_tag &) const
Do-nothing pointer_attributes handler.
struct ATTRIBUTES_tag void_pointer_attributes (void) const
Do-nothing pointer_attributes handler.
struct ATTRIBUTES_tag structure_attributes (const struct ATTRIBUTES_tag *, std::size_t) const
Do-nothing pointer_attributes handler.
virtual bool register_allocation (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line)
Do-nothing register_allocation handler.
virtual void deregister_allocation (const void *addr, const JeodMemoryItem &item, const JeodMemoryTypeDescriptor &tdesc, const char *file, unsigned int line)
Do-nothing deregister_allocation handler.
void register_container (const void *container, const JeodMemoryTypeDescriptor &container_type, const char *elem_name, JeodCheckpointable &checkpointable)
Do-nothing register_container handler.
void deregister_container (const void *container, const JeodMemoryTypeDescriptor &container_type, const char *elem_name, JeodCheckpointable &checkpointable)
Do-nothing deregister_container handler.
Public Member Functions inherited from jeod::JeodMemoryInterface
JeodMemoryInterface ()
Default constructor.
virtual ~JeodMemoryInterface ()
Destructor.
JeodMemoryInterface (const JeodMemoryInterface &)
Copy constructor.
JeodMemoryInterface & operator= (const JeodMemoryInterface &)
Assignment operator.
Private Member Functions
NullMemoryInterface (const NullMemoryInterface &)
Not implemented.
NullMemoryInterface & operator= (const NullMemoryInterface &)
Not implemented.
Detailed Description
A NullMemoryInterface extends the JeodMemoryInterface, providing the required functionality of the parent class in a null manner.
Definition at line 82 of file null_memory_interface.hh.
Constructor & Destructor Documentation
NullMemoryInterface() [1/2]
jeod::NullMemoryInterface::NullMemoryInterface () inline
Default constructor.
Definition at line 90 of file null_memory_interface.hh.
~NullMemoryInterface()
jeod::NullMemoryInterface::~NullMemoryInterface () inline
Destructor.
Definition at line 95 of file null_memory_interface.hh.
NullMemoryInterface() [2/2]
jeod::NullMemoryInterface::NullMemoryInterface (const NullMemoryInterface &) explicit private
Not implemented.
Member Function Documentation
deregister_allocation()
virtual void jeod::NullMemoryInterface::deregister_allocation (const void * addr, const JeodMemoryItem & item, const JeodMemoryTypeDescriptor & tdesc, const char * file, unsigned int line) inline virtual
Do-nothing deregister_allocation handler.
Parameters
[in] addr Allocated memory
[in] item Description of the memory
[in] tdesc Description of the type
[in] file File containing JEOD_ALLOC
[in] line Line containing JEOD_ALLOC
Implements jeod::JeodMemoryInterface.
Definition at line 254 of file null_memory_interface.hh.
References jeod::JeodMemoryTypeDescriptor::buffer_size(), jeod::TestHarnessMessages::debug, jeod::MessageHandler::debug(), and jeod::JeodMemoryTypeDescriptor::type_spec().
deregister_container()
void jeod::NullMemoryInterface::deregister_container (const void * container, const JeodMemoryTypeDescriptor & container_type, const char * elem_name, JeodCheckpointable & checkpointable) inline virtual
Do-nothing deregister_container handler.
Parameters
[in] container Ignored
[in] container_type Ignored
[in] elem_name Ignored
[in] checkpointable Ignored
Implements jeod::JeodMemoryInterface.
Definition at line 290 of file null_memory_interface.hh.
find_attributes() [1/2]
const struct ATTRIBUTES_tag* jeod::NullMemoryInterface::find_attributes (const std::string &) const inline virtual
Do-nothing find_attributes handler.
Returns
NULL
Implements jeod::JeodMemoryInterface.
Definition at line 140 of file null_memory_interface.hh.
find_attributes() [2/2]
const struct ATTRIBUTES_tag* jeod::NullMemoryInterface::find_attributes (const std::type_info &) const inline virtual
Do-nothing find_attributes handler.
Returns
NULL
Implements jeod::JeodMemoryInterface.
Definition at line 151 of file null_memory_interface.hh.
get_address_at_name()
void* jeod::NullMemoryInterface::get_address_at_name (const std::string & name) const inline virtual
Do-nothing get_address_at_name handler.
Returns
Null pointer
Parameters
[in] name Ignored
Implements jeod::JeodMemoryInterface.
Definition at line 129 of file null_memory_interface.hh.
get_name_at_address()
const std::string jeod::NullMemoryInterface::get_name_at_address (const void * addr, const JeodMemoryTypeDescriptor * tdesc) const inline virtual
Do-nothing get_name_at_address handler.
Returns
Empty string
Parameters
[in] addr Ignored
[in] tdesc Ignored
Implements jeod::JeodMemoryInterface.
Definition at line 115 of file null_memory_interface.hh.
is_checkpoint_restart_supported()
bool jeod::NullMemoryInterface::is_checkpoint_restart_supported (void) const inline virtual
Checkpoint/restart is not supported here.
Returns
False
Implements jeod::JeodMemoryInterface.
Definition at line 102 of file null_memory_interface.hh.
operator=()
NullMemoryInterface& jeod::NullMemoryInterface::operator= (const NullMemoryInterface &) private
Not implemented.
pointer_attributes()
struct ATTRIBUTES_tag jeod::NullMemoryInterface::pointer_attributes (const struct ATTRIBUTES_tag &) const inline virtual
Do-nothing pointer_attributes handler.
Returns
Dummy
Implements jeod::JeodMemoryInterface.
Definition at line 178 of file null_memory_interface.hh.
primitive_attributes()
struct ATTRIBUTES_tag jeod::NullMemoryInterface::primitive_attributes (const std::type_info &) const inline virtual
Do-nothing primitive_attributes handler.
Returns
Dummy
Implements jeod::JeodMemoryInterface.
Definition at line 162 of file null_memory_interface.hh.
register_allocation()
virtual bool jeod::NullMemoryInterface::register_allocation (const void * addr, const JeodMemoryItem & item, const JeodMemoryTypeDescriptor & tdesc, const char * file, unsigned int line) inline virtual
Do-nothing register_allocation handler.
Returns
True
Parameters
[in] addr Allocated memory
[in] item Description of the memory
[in] tdesc Description of the type
[in] file File containing JEOD_ALLOC
[in] line Line containing JEOD_ALLOC
Implements jeod::JeodMemoryInterface.
Definition at line 232 of file null_memory_interface.hh.
References jeod::JeodMemoryTypeDescriptor::buffer_size(), jeod::TestHarnessMessages::debug, jeod::MessageHandler::debug(), and jeod::JeodMemoryTypeDescriptor::type_spec().
register_container()
void jeod::NullMemoryInterface::register_container (const void * container, const JeodMemoryTypeDescriptor & container_type, const char * elem_name, JeodCheckpointable & checkpointable) inline virtual
Do-nothing register_container handler.
Parameters
[in] container Ignored
[in] container_type Ignored
[in] elem_name Ignored
[in] checkpointable Ignored
Implements jeod::JeodMemoryInterface.
Definition at line 274 of file null_memory_interface.hh.
structure_attributes()
struct ATTRIBUTES_tag jeod::NullMemoryInterface::structure_attributes (const struct ATTRIBUTES_tag * , std::size_t) const inline virtual
Do-nothing pointer_attributes handler.
Returns
Dummy
Implements jeod::JeodMemoryInterface.
Definition at line 210 of file null_memory_interface.hh.
void_pointer_attributes()
struct ATTRIBUTES_tag jeod::NullMemoryInterface::void_pointer_attributes (void) const inline virtual
Do-nothing pointer_attributes handler.
Returns
Dummy
Implements jeod::JeodMemoryInterface.
Definition at line 194 of file null_memory_interface.hh.
The documentation for this class was generated from the following file:
null_memory_interface.hh