JEOD: jeod::TimeConverter_TAI_TT Class Reference
jeod::TimeConverter_TAI_TT Class Reference
Converts between International Atomic Time and Terrestrial Time.
#include <time_converter_tai_tt.hh>
Public Member Functions
TimeConverter_TAI_TT ()
Construct a TimeConverter_TAI_TT.
~TimeConverter_TAI_TT () override=default
TimeConverter_TAI_TT (const TimeConverter_TAI_TT &)=delete
TimeConverter_TAI_TT & operator= (const TimeConverter_TAI_TT &)=delete
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void convert_a_to_b () override
Convert from TimeTAI to TimeTT.
void convert_b_to_a () override
Convert from TimeTT to TimeTAI.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()=default
TimeConverter (const TimeConverter &)=delete
TimeConverter & operator= (const TimeConverter &)=delete
virtual bool is_initialized ()
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void reset_a_to_b_offset ()
Resets the offset between type a and type b mid-sim.
virtual void verify_table_lookup_ends ()
This function does absolutely nothing.
double get_a_to_b_offset ()
Return the offset from the parent time object to this object.
Private Attributes
TimeTAI * tai_ptr {}
Converter parent time, always a TimeTAI for this converter.
TimeTT * tt_ptr {}
Converter parent time, always a TimeTT for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_TAI_TT ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name {""}
name of time-type "a".
std::string b_name {""}
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()=default
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized {}
whether converter has been initialized.
double a_to_b_offset {}
Difference between the two time-types.
Direction valid_directions {NO_DIRECTION}
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Converts between International Atomic Time and Terrestrial Time.
Definition at line 86 of file time_converter_tai_tt.hh.
Constructor & Destructor Documentation
TimeConverter_TAI_TT() [1/2]
jeod::TimeConverter_TAI_TT::TimeConverter_TAI_TT ()
Construct a TimeConverter_TAI_TT.
Definition at line 57 of file time_converter_tai_tt.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::ANY_DIRECTION, jeod::TimeConverter::b_name, and jeod::TimeConverter::valid_directions.
~TimeConverter_TAI_TT()
jeod::TimeConverter_TAI_TT::~TimeConverter_TAI_TT () override default
TimeConverter_TAI_TT() [2/2]
jeod::TimeConverter_TAI_TT::TimeConverter_TAI_TT (const TimeConverter_TAI_TT &) delete
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_TAI_TT::convert_a_to_b () override virtual
Convert from TimeTAI to TimeTT.
Reimplemented from jeod::TimeConverter.
Definition at line 101 of file time_converter_tai_tt.cc.
References jeod::JeodBaseTime::seconds, jeod::TimeStandard::set_time_by_seconds(), tai_ptr, and tt_ptr.
convert_b_to_a()
void jeod::TimeConverter_TAI_TT::convert_b_to_a () override virtual
Convert from TimeTT to TimeTAI.
Assumptions and Limitations
Time class MET is based on time class TAI, and counts the elapsed TAI time only
Reimplemented from jeod::TimeConverter.
Definition at line 113 of file time_converter_tai_tt.cc.
References jeod::JeodBaseTime::seconds, jeod::TimeStandard::set_time_by_seconds(), tai_ptr, and tt_ptr.
initialize()
void jeod::TimeConverter_TAI_TT::initialize (JeodBaseTime * parent_ptr, JeodBaseTime * child_ptr, const int int_dir) override virtual
Initialize the converter.
Parameters
[in] parent_ptr Time used to initialize the converter
[in] child_ptr Other Time used to initialize the converter
[in] int_dir Conversion direction: +1 a=parent; -1 b=parent; 0 error
Implements jeod::TimeConverter.
Definition at line 70 of file time_converter_tai_tt.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::MessageHandler::fail(), jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, tai_ptr, tt_ptr, and jeod::TimeConverter::verify_setup().
operator=()
TimeConverter_TAI_TT& jeod::TimeConverter_TAI_TT::operator= (const TimeConverter_TAI_TT &) delete
Friends And Related Function Documentation
init_attrjeod__TimeConverter_TAI_TT
void init_attrjeod__TimeConverter_TAI_TT () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file time_converter_tai_tt.hh.
Field Documentation
tai_ptr
TimeTAI* jeod::TimeConverter_TAI_TT::tai_ptr {} private
Converter parent time, always a TimeTAI for this converter.
trick_units(–)
Definition at line 93 of file time_converter_tai_tt.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), and initialize().
tt_ptr
TimeTT* jeod::TimeConverter_TAI_TT::tt_ptr {} private
Converter parent time, always a TimeTT for this converter.
trick_units(–)
Definition at line 98 of file time_converter_tai_tt.hh.
Referenced by convert_a_to_b(), convert_b_to_a(), and initialize().
The documentation for this class was generated from the following files:
time_converter_tai_tt.hh
time_converter_tai_tt.cc