JEOD: jeod::DynBody Class Reference
jeod::DynBody Class Reference
Class DynBody is the base class for all dynamic bodies.
#include <dyn_body.hh>
Public Member Functions
DynBody ()
DynBody default constructor.
~DynBody () override
DynBody destructor.
virtual void initialize_model (BaseDynManager &dyn_manager_in)
Initialize internal and external interrelations, including registration / with the dynamics manager.
void activate ()
Activate a DynBody object.
void deactivate ()
Deactivate a DynBody object.
void set_name (const std::string &name_in)
Set the name of the vehicle.
virtual void add_control (GravityControls *control)
Add a new GravityControls to the list in grav_interaction.
virtual void initialize_controls (GravityManager &grav_manager)
Initialize the gravity controls of this DynBody.
virtual void reset_controls ()
Make the frame subscriptions for each control consistent with the requirements for that control.
virtual void sort_controls ()
Sort the gravity controls in ascending acceleration magnitude order.
virtual void collect_forces_and_torques ()
Collect forces and torques acting on the vehicle.
virtual void create_body_integrators (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls, const JeodIntegrationTime &time_mngr)
Create the integrator (integrators) needed to propagate the translational and rotational state of a DynBody.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage) override
Integrate state by the specified dynamic time interval.
virtual void switch_integration_frames (EphemerisRefFrame &new_integ_frame)
Switch the integration frame for this body and all its child bodies to the indicated frame.
virtual void switch_integration_frames (const char *new_integ_frame_name)
Switch the integration frame for this body and all its child bodies to the frame indicated by the provided name.
void create_integrators (const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls, const er7_utils::TimeInterface &time_if) override
This interface is required by er7_utils::IntegrableObject.
void destroy_integrators (void) override
Destroy the integrators.
void reset_integrators (void) override
Reset the translational and rotational integrators.
virtual BodyRefFrame * find_body_frame (const char *frame_id) const
Find the BodyRefFrame named by the provided identifier.
DynamicsIntegrationGroup * get_dynamics_integration_group ()
Get the DynamicsIntegrationGroup that integrates this DynBody object.
JeodPointerVector< er7_utils::IntegrableObject >::type get_integrable_objects ()
Get the IntegrableObjects associated with this DynBody.
void clear_integrable_objects ()
Remove all IntegrableObjects associated with this DynBody.
void migrate_integrable_objects ()
Call this method before switching this dyn body to a new group if you want the associated integrable objects to follow.
void add_integrable_object (er7_utils::IntegrableObject &associated_integrable_object)
Add an IntegrableObject to be integrated with this DynBody.
void remove_integrable_object (er7_utils::IntegrableObject &associated_integrable_object)
Remove an IntegrableObject from association with this DynBody.
void set_position (const double position[3], BodyRefFrame &subject_frame)
Set the position of the vehicle.
void set_velocity (const double velocity[3], BodyRefFrame &subject_frame)
Set the velocity of the vehicle.
void set_attitude_left_quaternion (const Quaternion &left_quat, BodyRefFrame &subject_frame)
Set the attitude of the vehicle.
void set_attitude_right_quaternion (const Quaternion &right_quat, BodyRefFrame &subject_frame)
Set the attitude of the vehicle.
void set_attitude_matrix (const double matrix[3][3], BodyRefFrame &subject_frame)
Set the attitude of the vehicle.
void set_attitude_rate (const double attitude_rate[3], BodyRefFrame &subject_frame)
Set the attitude rate of the vehicle.
void set_state (RefFrameItems::Items set_items, const RefFrameState &state, BodyRefFrame &subject_frame)
Set the parts of the specified reference frame as indicated by the set_items parameter from the supplied state and propagate these items to all dynamic bodies attached to this body.
void set_state_source (RefFrameItems::Items items, BodyRefFrame &frame)
Set the source of aspects of the state.
virtual void propagate_state ()
Propagate state from the integrated state to attached bodies.
virtual void update_integrated_state ()
Propagate state from state owners to the integrated state.
virtual void compute_vehicle_point_states (RefFrameItems::Items set_items)
Propagate structure frame state to vehicle points.
bool is_root_body ()
Indicates whether this DynBody object is a root body.
virtual const DynBody * get_parent_body () const
Returns this DynBody object's parent body.
virtual const DynBody * get_root_body () const
Finds this DynBody object's root body.
virtual void add_mass_point (const MassPointInit &mass_point_init)
Add a mass point to the dyn body's list of such and make a vehicle point that corresponds to the added mass point.
const BodyRefFrame * find_vehicle_point (const char *pt_name) const
Find the vehicle point with the given name.
virtual void compute_vehicle_point_derivatives (const BodyRefFrame &frame, FrameDerivs &derivs)
Compute the state derivatives at a vehicle point.
const RefFrameItems & get_initialized_states () const
Indicate which state elements have been initialized.
bool initialized_states_contains (RefFrameItems::Items test_items) const
Indicate whether the specified state elements have been initialized.
virtual bool add_mass_body (const char *this_point_name, const char *child_point_name, MassBody &child)
virtual bool add_mass_body (const double offset[3], const double T_pstr_cstr[3][3], MassBody &child)
virtual bool attach_to (const char *this_point_name, const char *parent_point_name, DynBody &parent)
Attach this dyn body's root body as a child of the specified dyn body such that the specified mass points on the two bodies are coincident and the frames associated with those mass points are related by a 180 degree yaw.
virtual bool attach_to (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &parent)
Attach this dyn body's root body as a child of the specified dyn body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with respect to the parent body's structural axes as specified.
virtual bool attach_child (const char *this_point_name, const char *child_point_name, DynBody &child)
Attach a child DynBody by point specification.
virtual bool attach_child (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &child)
Attach a child DynBody by location specification.
virtual bool attach_to_frame (const char *parent_ref_frame_name)
virtual bool attach_to_frame (RefFrame &parent)
virtual bool attach_to_frame (const char *this_point_name, const char *parent_ref_frame_name, const double offset_pframe_cpt_pframe[3], const double T_pframe_cpt[3][3])
virtual bool attach_to_frame (const double offset_pframe_cstr_pframe[3], const double T_pframe_cstr[3][3], RefFrame &parent)
virtual bool detach (DynBody &other_body)
Detach parent and child DynBodies, 'this' and the argument body, such that the detachment happens at the parent body level.
virtual bool detach (void)
Detach this DynBody from its parent RefFrame or DynBody parent.
virtual bool remove_mass_body (MassBody &child)
Remove connectivity between this (parent) DynBody and the argument (child) MassBody mass subbody.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Data Fields
MassBody mass
Mass properties of the vehicle, defined about the structure reference frame.
NamedItem & name
Body name, reference linked to mass.name.
char * integ_frame_name
The name of the reference frame with respect to which the body's reference frames (core, composite, structure, plus vehicle point frames) are to be represented and propagated.
EphemerisRefFrame * integ_frame
The current integration frame.
BodyRefFrame core_body
Vehicle core body reference frame.
BodyRefFrame composite_body
Vehicle composite body reference frame.
BodyRefFrame structure
Vehicle structural reference frame.
bool translational_dynamics
Is translational dynamics enabled? The body's translational state is integrated only if this member is true.
bool rotational_dynamics
Is rotational dynamics enabled? The body's rotational state is integrated only if this member is true.
bool compute_point_derivative
Should the point derivatives for the body be computed? A child body's translational and rotational derivatives are only computed if this is true.
bool three_dof
Is this a three degrees of freedom (translation only) body? This data member has effect only when set prior to the creation of the body's integrators.
GeneralizedSecondOrderODETechnique::TechniqueType rotation_integration
Specifies the preferred mechanism for integrating rotational state.
bool autoupdate_vehicle_points
Are vehicle points automatically updated? The vehicle points are automatically calculated at initialization time but are only automatically updated at runtime if this member is true.
GravityInteraction grav_interaction
Gravitational interactions.
FrameDerivs derivs
Translational/rotational accelerations.
BodyForceCollect collect
Force/Torque collection mechanism.
Protected Member Functions
virtual void set_integ_frame (EphemerisRefFrame &new_integ_frame)
Set the integration frame for this body and all its child bodies to the provided frame.
virtual void set_integ_frame (const char *new_integ_frame_name)
Set the integration frame for this body and all its child bodies to the frame indicated by the provided name.
virtual er7_utils::IntegratorResult trans_integ (double dyn_dt, unsigned int target_stage)
Integrate the vehicle's translational state.
virtual er7_utils::IntegratorResult rot_integ (double dyn_dt, unsigned int target_stage)
Integrate the vehicle's rotational state.
void set_state_source_internal (RefFrameItems::Items items, BodyRefFrame &frame)
Set the source of aspects of the state.
virtual DynBody * get_parent_body_internal ()
Returns this DynBody object's parent body.
virtual DynBody * get_root_body_internal ()
Finds this DynBody object's root body.
virtual bool attach_validate_parent (const DynBody &parent, bool generate_message) const
Validate whether the pending attachment is legal from a connectivity point of view.
virtual bool attach_validate_child (const DynBody &child, bool generate_message) const
Validate whether the pending attachment is legal from a physical point of view.
virtual bool add_mass_body_validate (const MassBody &child, bool generate_message) const
Validate whether the pending sub body is legal from a mass tree point of view.
virtual void add_mass_body_frames (MassBody &subbody)
For a newly attached mass sub-body, create body frames for the root sub-body and all child sub-bodies via recursion.
virtual void detach_mass_body_frames (MassBody &subbody)
For a newly detached mass sub-body, remove body frames for the root sub-body and all child sub-bodies via recursion.
virtual void attach_establish_links (DynBody &parent)
Establish the logical connectivity between parent and child.
virtual void attach_update_properties (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &child)
Set the relation between parent and child and update the mass properties.
virtual void process_dynamic_attachment (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody &root_body, DynBody &child_body)
Process the attachment event of one body from another.
virtual void detach_mass_internal (MassBody &child)
Update parent and child properties to reflect that they are detached.
virtual void propagate_state_from_structure ()
Propagate state to attached bodies starting from this body's structural frame.
virtual void propagate_state_from_composite ()
Propagate state to attached bodies starting from this body's composite frame.
void compute_ref_point_transform (const BodyRefFrame &source_frame, const MassPoint **const ref_point, MassPointState &rel_state)
Compute the relative state between the integrated frame's mass point and the source frame's mass point.
void compute_derived_state_forward (const BodyRefFrame &source_frame, const MassPoint &rel_state, BodyRefFrame &derived_frame) const
Compute a derived state given the source state and the position/ attitude transformation from the source to the derived state.
void compute_state_elements_forward (const BodyRefFrame &source_frame, const MassPoint &rel_state, const RefFrameItems &state_items, BodyRefFrame &derived_frame) const
Compute selected aspects of the derived state given the source state and the position/ attitude transformation from the source to the derived state.
void compute_derived_state_reverse (const BodyRefFrame &source_frame, const MassPoint &rel_state, BodyRefFrame &derived_frame) const
Compute a derived state given the source state and the position/ attitude transformation from the derived to the source state.
void compute_state_elements_reverse (const BodyRefFrame &source_frame, const MassPoint &rel_state, const RefFrameItems &state_items, BodyRefFrame &derived_frame) const
Compute selected aspects of the derived state given the source state and the position/ attitude transformation from the derived to the source state.
Protected Attributes
BaseDynManager *& dyn_manager
The dynamics manager for the simulation.
const JeodIntegrationTime * time_manager
The time manager to be used to obtain timestamp information.
DynBody * dyn_parent
The DynBody to which this body is attached.
DynBodyGenericFrameAttachment frame_attach
The RefFrame this body is attached to.
std::list< DynBody * > dyn_children
The subset of the dynamic bodies attached to this dynamic body.
std::list< MassBody * > mass_children
The subset of the mass bodies attached to this dynamic body that are themselves not dynamic bodies.
std::list< BodyRefFrame * > vehicle_points
An array of vehicle points associated with this dynamic body.
RefFrameItems initialized_states
Enum value indicating which of position, velocity, attitude, and rate have been initialized.
BodyRefFrame * position_source
The reference frame that contains the user-set position.
BodyRefFrame * velocity_source
The reference frame that contains the user-set velocity.
BodyRefFrame * attitude_source
The reference frame that contains the user-set attitude.
BodyRefFrame * rate_source
The reference frame that contains the user-set attitude rate.
BodyRefFrame * integrated_frame
The reference frame whose state is updated via the state integrator.
std::vector< er7_utils::IntegrableObject * > associated_integrable_objects
List of integrable objects to be integrated with this DynBody.
er7_utils::IntegratorResultMergerContainer integ_results_merger
The object that merges integration results.
RestartableT3SecondOrderODEIntegrator trans_integrator
Translational state checkpointable/restartable integrator generator.
RestartableSO3SecondOrderODEIntegrator rot_integrator
Rotational state checkpointable/restartable integrator generator.
Private Member Functions
DynBody (const DynBody &)
Not implemented.
DynBody & operator= (const DynBody &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__DynBody ()
Detailed Description
Class DynBody is the base class for all dynamic bodies.
A DynBody is a MassBody that is connected to the outside world. These connections are in the form of three reference frames tied to the body – the structural, core body, and composite body frames.
For a non-root body, the states for each of these frames is calculated based on the parent body's state and on the body attachment.
For a root body, one of these three frames must be integrated. The details of how that integration is performed is the subject of classes that derive from DynBody.
Definition at line 113 of file dyn_body.hh.
Constructor & Destructor Documentation
DynBody() [1/2]
jeod::DynBody::DynBody ()
DynBody default constructor.
Definition at line 63 of file dyn_body.cc.
References composite_body, jeod::MassBody::composite_properties, jeod::MassBody::compute_inverse_inertia, core_body, jeod::MassBody::core_properties, initialized_states, integrated_frame, JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, mass, jeod::BodyRefFrame::mass_point, jeod::RefFrameItems::No_Items, rot_integrator, jeod::RefFrameItems::set(), structure, jeod::MassBody::structure_point, and trans_integrator.
~DynBody()
jeod::DynBody::~DynBody () override
DynBody destructor.
Definition at line 113 of file dyn_body.cc.
References composite_body, core_body, detach(), dyn_children, dyn_manager, dyn_parent, JEOD_DELETE_OBJECT, JEOD_DEREGISTER_CHECKPOINTABLE, JEOD_IS_ALLOCATED, mass_children, jeod::RefFrame::remove_from_parent(), remove_mass_body(), jeod::BaseRefFrameManager::remove_ref_frame(), rot_integrator, structure, trans_integrator, and vehicle_points.
DynBody() [2/2]
jeod::DynBody::DynBody (const DynBody &) private
Not implemented.
Member Function Documentation
activate()
void jeod::DynBody::activate () inline
Activate a DynBody object.
The current implementation does nothing. DynBody objects are always active.
Definition at line 151 of file dyn_body.hh.
add_control()
void jeod::DynBody::add_control (GravityControls * control) virtual
Add a new GravityControls to the list in grav_interaction.
Parameters
[in] control Control to be added
Definition at line 222 of file dyn_body.cc.
References jeod::GravityInteraction::add_control(), and grav_interaction.
add_integrable_object()
void jeod::DynBody::add_integrable_object (er7_utils::IntegrableObject & associated_integrable_object)
Add an IntegrableObject to be integrated with this DynBody.
Note that the associated IntegrableObject may or may not follow this DynBody if it is moved to a new integration group/loop.
Parameters
[in] associated_integrable_object The IntegrableObject to be associated with this DynBody.
Definition at line 290 of file dyn_body.cc.
References associated_integrable_objects, and jeod::MessageHandler::warn().
Referenced by jeod::RadiationDefaultSurface::add_thermal_integrator_to(), jeod::RadiationSurface::add_thermal_integrators_to(), and jeod::PendulumConstraintComponent::attach_to_solver().
add_mass_body() [1/2]
bool jeod::DynBody::add_mass_body (const char * this_point_name, const char * child_point_name, MassBody & child) virtual
Definition at line 592 of file dyn_body_attach.cc.
References jeod::Quaternion::conjugate(), jeod::MassBody::find_mass_point(), find_vehicle_point(), jeod::Matrix3x3::identity(), jeod::Vector3::incr(), jeod::DynBodyMessages::invalid_attachment, mass, jeod::BodyRefFrame::mass_point, jeod::Vector3::negate(), jeod::MassPointState::position, jeod::Matrix3x3::product(), jeod::Matrix3x3::product_transpose_transpose(), jeod::MassPointState::Q_parent_this, jeod::MassPointState::T_parent_this, jeod::Vector3::transform(), jeod::Matrix3x3::transpose(), and jeod::MessageHandler::warn().
Referenced by jeod::BodyAttachMatrix::apply(), and jeod::BodyAttachAligned::apply().
add_mass_body() [2/2]
bool jeod::DynBody::add_mass_body (const double offset[3], const double T_pstr_cstr[3][3], MassBody & child) virtual
Definition at line 716 of file dyn_body_attach.cc.
References add_mass_body_frames(), add_mass_body_validate(), jeod::MassBody::attach_establish_links(), jeod::MassBodyMessages::attach_info, jeod::MassBody::attach_update_properties(), jeod::NamedItem::c_str(), jeod::MassPoint::compute_state_wrt_pred(), jeod::Vector3::copy(), jeod::MassBody::get_root_body_internal(), jeod::MessageHandler::inform(), jeod::MassBody::links, mass, mass_children, jeod::MassBody::name, name, jeod::TreeLinks< Links, Container, Messages >::parent(), jeod::MassPointState::position, jeod::Matrix3x3::product_left_transpose(), jeod::MassBody::structure_point, jeod::MassPointState::T_parent_this, and jeod::Vector3::transform_transpose_decr().
add_mass_body_frames()
void jeod::DynBody::add_mass_body_frames (MassBody & subbody) protected virtual
For a newly attached mass sub-body, create body frames for the root sub-body and all child sub-bodies via recursion.
Returns
Validity indicator
Parameters
[in] subbody the root of the newly attached sub-bodies
Definition at line 803 of file dyn_body_attach.cc.
References jeod::RefFrame::add_child(), jeod::BaseRefFrameManager::add_ref_frame(), jeod::NamedItem::c_str(), jeod::TreeLinks< Links, Container, Messages >::child_head(), jeod::TreeLinks< Links, Container, Messages >::child_tail(), jeod::TreeLinks< Links, Container, Messages >::container(), dyn_manager, jeod::TreeLinks< Links, Container, Messages >::has_children(), integ_frame, JEOD_ALLOC_CLASS_OBJECT, jeod::MassBody::links, jeod::BodyRefFrame::mass_point, jeod::MassBody::mass_points, name, jeod::RefFrame::set_name(), jeod::RefFrame::set_owner(), and vehicle_points.
Referenced by add_mass_body().
add_mass_body_validate()
bool jeod::DynBody::add_mass_body_validate (const MassBody & child, bool generate_message) const protected virtual
Validate whether the pending sub body is legal from a mass tree point of view.
Note
Assumptions and Limitations
The subject mass, child, must not belong to a child body.
Returns
Validity indicator
Parameters
[in] child The child body; the body to be attached to this body.
[in] generate_message Generate message if invalid?
Definition at line 185 of file dyn_body_attach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::error(), jeod::BaseDynManager::find_dyn_body(), jeod::NamedItem::get_name(), jeod::MassBody::get_root_body(), jeod::MassBodyMessages::invalid_attach, jeod::MassBody::name, and name.
Referenced by add_mass_body().
add_mass_point()
void jeod::DynBody::add_mass_point (const MassPointInit & mass_point_init) virtual
Add a mass point to the dyn body's list of such and make a vehicle point that corresponds to the added mass point.
Parameters
[in] mass_point_init Mass point specification
Definition at line 53 of file dyn_body_vehicle_point.cc.
References jeod::RefFrame::add_child(), jeod::MassBody::add_mass_point(), jeod::BaseRefFrameManager::add_ref_frame(), jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::fail(), jeod::MassPoint::get_name(), integ_frame, jeod::DynBodyMessages::invalid_body, jeod::BaseDynManager::is_dyn_body_registered(), JEOD_ALLOC_CLASS_OBJECT, mass, jeod::BodyRefFrame::mass_point, jeod::MassBody::mass_points, name, jeod::RefFrame::set_name(), jeod::RefFrame::set_owner(), and vehicle_points.
Referenced by jeod::ContactFacet::create_vehicle_point(), and jeod::MassBody::initialize_mass().
attach_child() [1/2]
bool jeod::DynBody::attach_child (const char * this_point_name, const char * child_point_name, DynBody & child) virtual
Attach a child DynBody by point specification.
See corresponding DynBody::attach_to() method for more information.
Definition at line 373 of file dyn_body_attach.cc.
References jeod::Quaternion::conjugate(), jeod::MassBody::find_mass_point(), find_vehicle_point(), jeod::Vector3::incr(), jeod::Matrix3x3::initialize(), jeod::DynBodyMessages::invalid_attachment, mass, jeod::BodyRefFrame::mass_point, jeod::Vector3::negate(), jeod::MassPointState::position, jeod::Matrix3x3::product(), jeod::Matrix3x3::product_transpose_transpose(), jeod::MassPointState::Q_parent_this, jeod::MassPointState::T_parent_this, jeod::Vector3::transform(), jeod::Matrix3x3::transpose(), and jeod::MessageHandler::warn().
Referenced by jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), and attach_to().
attach_child() [2/2]
bool jeod::DynBody::attach_child (const double xyz_cstr_wrt_pstr[3], const double T_pstr_to_cstr[3][3], DynBody & child) virtual
Attach a child DynBody by location specification.
See corresponding DynBody::attach_to() method for more information. Note that the offset and transformation are specified w.r.t. the parent in both attach_to() and attach_child()
Definition at line 511 of file dyn_body_attach.cc.
References attach_establish_links(), jeod::MassBodyMessages::attach_info, attach_update_properties(), attach_validate_child(), attach_validate_parent(), jeod::NamedItem::c_str(), jeod::MassPoint::compute_state_wrt_pred(), jeod::Vector3::copy(), get_root_body_internal(), jeod::MessageHandler::inform(), mass, name, jeod::MassPointState::position, jeod::Matrix3x3::product_left_transpose(), jeod::MassBody::structure_point, jeod::MassPointState::T_parent_this, and jeod::Vector3::transform_transpose_decr().
attach_establish_links()
void jeod::DynBody::attach_establish_links (DynBody & parent) protected virtual
Establish the logical connectivity between parent and child.
Extensibility comments –
This method is invoked before the computing the physical relation between parent and child.
The generic purpose of this method is to establish the logical connectivity between parent and child in terms of the child class.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Note
Assumptions and Limitations
The attachment is valid; not checked.
Parameters
[in,out] parent The new parent body; the body to which this body is to be attached.
Definition at line 845 of file dyn_body_attach.cc.
References jeod::MassBody::attach_establish_links(), dyn_children, dyn_parent, integ_frame, mass, and set_integ_frame().
Referenced by attach_child().
attach_to() [1/2]
bool jeod::DynBody::attach_to (const char * this_point_name, const char * parent_point_name, DynBody & parent) virtual
Attach this dyn body's root body as a child of the specified dyn body such that the specified mass points on the two bodies are coincident and the frames associated with those mass points are related by a 180 degree yaw.
Returns
Success indicator: true=success, false=attachment not performed.
Parameters
[in] this_point_name The name of a mass point contained in this dyn body's list of mass points.
[in] parent_point_name The name of a mass point contained in the parent body's list of mass points.
[in,out] parent The parent body; the body to which this body's root body is to be attached.
Definition at line 238 of file dyn_body_attach.cc.
References attach_child().
attach_to() [2/2]
bool jeod::DynBody::attach_to (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody & parent) virtual
Attach this dyn body's root body as a child of the specified dyn body such that this body's structural origin is offset from the parent body's structural origin and this body's structural axes are oriented with respect to the parent body's structural axes as specified.
Returns
Success indicator: true=success, false=attachment not performed.
Parameters
[in] offset_pstr_cstr_pstr Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the parent body.
Units: M
[in] T_pstr_cstr Transformation matrix from the parent body's structural frame to this body's structural frame.
[in,out] parent The parent body; the body to which this body's root body is to be attached.
Definition at line 257 of file dyn_body_attach.cc.
References attach_child().
attach_to_frame() [1/4]
bool jeod::DynBody::attach_to_frame (const char * parent_ref_frame_name) virtual
Definition at line 267 of file dyn_body_attach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::BaseRefFrameManager::find_ref_frame(), jeod::DynBodyMessages::invalid_attachment, mass, jeod::MassBody::name, and jeod::MessageHandler::warn().
Referenced by jeod::BodyAttachMatrix::apply(), and jeod::BodyAttachAligned::apply().
attach_to_frame() [2/4]
bool jeod::DynBody::attach_to_frame (RefFrame & parent) virtual
Definition at line 287 of file dyn_body_attach.cc.
References jeod::RefFrame::compute_relative_state(), frame_attach, get_root_body_internal(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), and structure.
attach_to_frame() [3/4]
bool jeod::DynBody::attach_to_frame (const char * this_point_name, const char * parent_ref_frame_name, const double offset_pframe_cpt_pframe[3], const double T_pframe_cpt[3][3]) virtual
Definition at line 296 of file dyn_body_attach.cc.
References jeod::MassPoint::compute_state_wrt_pred(), jeod::Vector3::copy(), jeod::Matrix3x3::copy(), jeod::RefFrameState::decr_right(), dyn_manager, jeod::MassBody::find_mass_point(), jeod::BaseRefFrameManager::find_ref_frame(), find_vehicle_point(), frame_attach, get_root_body_internal(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), jeod::DynBodyMessages::invalid_attachment, jeod::Quaternion::left_quat_from_transformation(), mass, jeod::BodyRefFrame::mass_point, jeod::RefFrameTrans::position, jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, structure, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, and jeod::MessageHandler::warn().
attach_to_frame() [4/4]
bool jeod::DynBody::attach_to_frame (const double offset_pframe_cstr_pframe[3], const double T_pframe_cstr[3][3], RefFrame & parent) virtual
Definition at line 355 of file dyn_body_attach.cc.
References jeod::Vector3::copy(), jeod::Matrix3x3::copy(), frame_attach, get_root_body_internal(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), jeod::RefFrameTrans::position, jeod::RefFrameState::rot, jeod::RefFrameRot::T_parent_this, and jeod::RefFrameState::trans.
attach_update_properties()
void jeod::DynBody::attach_update_properties (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody & child) protected virtual
Set the relation between parent and child and update the mass properties.
Extensibility comments –
This method is sent to the parent body of the attachment after the child body has established the logical connectivity between the parent body and child body.
The generic purpose of this method is to establish the physical relation between parent and child and to update any physical properties that change as a result of the attachment.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Note
Assumptions and Limitations
The attachment is valid
Logical connectivity has been established.
Neither assumption is checked.
Parameters
[in] offset_pstr_cstr_pstr Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
Units: m
[in] T_pstr_cstr Transformation matrix from the new parent body's structural frame to this body's structural frame.
[in,out] child The child body; the body newly attached to this body.
Reimplemented in jeod::StructureIntegratedDynBody.
Definition at line 871 of file dyn_body_attach.cc.
References jeod::MassBody::attach_update_properties(), get_dynamics_integration_group(), get_root_body_internal(), initialized_states, jeod::RefFrameItems::is_empty(), mass, jeod::RefFrameItems::Pos_Vel_Att_Rate, process_dynamic_attachment(), propagate_state(), set_state_source_internal(), and structure.
Referenced by attach_child(), and jeod::StructureIntegratedDynBody::attach_update_properties().
attach_validate_child()
bool jeod::DynBody::attach_validate_child (const DynBody & child, bool generate_message) const protected virtual
Validate whether the pending attachment is legal from a physical point of view.
Extensibility comments –
This method determines whether invoking attach_update_properties makes sense.
Note
Assumptions and Limitations
The subject body, child, must be a root body. This is not checked.
Returns
Validity indicator
Parameters
[in] child The child body; the body to be attached to this body.
[in] generate_message Generate message if invalid?
Definition at line 110 of file dyn_body_attach.cc.
References jeod::NamedItem::c_str(), get_root_body(), initialized_states, jeod::DynBodyMessages::invalid_attachment, jeod::RefFrameItems::is_empty(), jeod::RefFrameItems::is_full(), name, and jeod::MessageHandler::warn().
Referenced by attach_child().
attach_validate_parent()
bool jeod::DynBody::attach_validate_parent (const DynBody & parent, bool generate_message) const protected virtual
Validate whether the pending attachment is legal from a connectivity point of view.
Extensibility comments –
This method determines whether invoking attach_establish_links makes sense.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Note
Assumptions and Limitations:
The subject body, this, must be a root body. This is not checked.
Returns
Validity indicator
Parameters
[in] parent The new parent body; the body to which this body is to be attached.
[in] generate_message Generate message if invalid?
Definition at line 58 of file dyn_body_attach.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), get_root_body(), jeod::DynBodyMessages::invalid_attachment, jeod::DynBodyMessages::invalid_body, jeod::BaseDynManager::is_dyn_body_registered(), name, jeod::DynBodyMessages::not_dyn_body, and jeod::MessageHandler::warn().
Referenced by attach_child().
clear_integrable_objects()
void jeod::DynBody::clear_integrable_objects ()
Remove all IntegrableObjects associated with this DynBody.
You might do this if you want to switch the DynBody to a new group without switching the associated IntegrableObjects.
Definition at line 330 of file dyn_body.cc.
References associated_integrable_objects.
collect_forces_and_torques()
void jeod::DynBody::collect_forces_and_torques () virtual
Collect forces and torques acting on the vehicle.
Reimplemented in jeod::StructureIntegratedDynBody.
Definition at line 98 of file dyn_body_collect.cc.
References jeod::accumulate_forces(), jeod::accumulate_torques(), jeod::RefFrameRot::ang_vel_this, collect, jeod::BodyForceCollect::collect_effector_forc, jeod::BodyForceCollect::collect_effector_torq, jeod::BodyForceCollect::collect_environ_forc, jeod::BodyForceCollect::collect_environ_torq, collect_forces_and_torques(), jeod::BodyForceCollect::collect_no_xmit_forc, jeod::BodyForceCollect::collect_no_xmit_torq, composite_body, jeod::MassBody::composite_properties, jeod::MassBody::composite_wrt_pstr, compute_point_derivative, compute_vehicle_point_derivatives(), jeod::Vector3::cross(), jeod::Vector3::cross_incr(), derivs, jeod::Vector3::diff(), dyn_children, dyn_parent, jeod::BodyForceCollect::effector_forc, jeod::BodyForceCollect::effector_torq, jeod::BodyForceCollect::environ_forc, jeod::BodyForceCollect::environ_torq, jeod::BodyForceCollect::extern_forc_inrtl, jeod::BodyForceCollect::extern_forc_struct, jeod::BodyForceCollect::extern_torq_body, jeod::BodyForceCollect::extern_torq_struct, jeod::GravityInteraction::grav_accel, grav_interaction, jeod::Vector3::incr(), jeod::MassProperties::inertia, jeod::BodyForceCollect::inertial_torq, jeod::Vector3::initialize(), jeod::MassProperties::inverse_inertia, jeod::MassProperties::inverse_mass, mass, jeod::BodyForceCollect::no_xmit_forc, jeod::BodyForceCollect::no_xmit_torq, jeod::FrameDerivs::non_grav_accel, jeod::MassPointState::position, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, rotational_dynamics, jeod::Vector3::scale(), jeod::RefFrame::state, structure, jeod::MassBody::structure_point, jeod::Vector3::sum(), jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::FrameDerivs::trans_accel, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), translational_dynamics, and jeod::Vector3::zero_small().
Referenced by jeod::DynamicsIntegrationGroup::collect_derivatives(), and collect_forces_and_torques().
compute_derived_state_forward()
void jeod::DynBody::compute_derived_state_forward (const BodyRefFrame & source_frame, const MassPoint & rel_state, BodyRefFrame & derived_frame) const protected
Compute a derived state given the source state and the position/ attitude transformation from the source to the derived state.
Parameters
[in] source_frame Source state
[in] rel_state Relative state
[out] derived_frame Derived state
Definition at line 160 of file dyn_body_propagate_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Vector3::copy(), jeod::Vector3::cross(), jeod::BodyRefFrame::initialized_items, jeod::Quaternion::multiply(), jeod::Quaternion::normalize(), jeod::RefFrameItems::Pos_Vel_Att_Rate, jeod::RefFrameTrans::position, jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, jeod::RefFrameItems::set(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::RefFrame::timestamp(), jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose_incr(), and jeod::RefFrameTrans::velocity.
Referenced by compute_vehicle_point_states(), propagate_state_from_composite(), and propagate_state_from_structure().
compute_derived_state_reverse()
void jeod::DynBody::compute_derived_state_reverse (const BodyRefFrame & source_frame, const MassPoint & rel_state, BodyRefFrame & derived_frame) const protected
Compute a derived state given the source state and the position/ attitude transformation from the derived to the source state.
Parameters
[in] source_frame Source state
[in] rel_state Relative state
[out] derived_frame Derived state
Definition at line 278 of file dyn_body_propagate_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Quaternion::conjugate_multiply(), jeod::Vector3::copy(), jeod::Vector3::cross(), jeod::BodyRefFrame::initialized_items, jeod::Quaternion::normalize(), jeod::RefFrameItems::Pos_Vel_Att_Rate, jeod::RefFrameTrans::position, jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, jeod::RefFrameItems::set(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::RefFrame::timestamp(), jeod::RefFrameState::trans, jeod::Vector3::transform_transpose(), jeod::Vector3::transform_transpose_decr(), and jeod::RefFrameTrans::velocity.
Referenced by propagate_state_from_composite().
compute_ref_point_transform()
void jeod::DynBody::compute_ref_point_transform (const BodyRefFrame & source_frame, const MassPoint **const ref_point, MassPointState & rel_state) protected
Compute the relative state between the integrated frame's mass point and the source frame's mass point.
Note
Assumptions and Limitations
This method is only called to be called for a root body. This assumption is not enforced.
Parameters
[in] source_frame The frame that contains the relevant state data.
[in,out] ref_point The mass point corresponding to the previous call to this function. This is an efficiency hack used to avoid duplicative computations.
[in,out] rel_state The relative state between the integration frame mass point and the source frame mass point.
Definition at line 51 of file dyn_body_propagate_state.cc.
References jeod::NamedItem::c_str(), composite_body, jeod::MassBody::composite_properties, jeod::MassBody::composite_wrt_pbdy, jeod::MassPoint::compute_state_wrt_pred(), core_body, jeod::MassBody::core_wrt_composite, jeod::Vector3::decr(), jeod::MessageHandler::fail(), jeod::RefFrame::get_owner(), integrated_frame, jeod::DynBodyMessages::invalid_frame, jeod::Quaternion::left_quat_to_transformation(), mass, jeod::BodyRefFrame::mass_point, jeod::Quaternion::multiply_conjugate(), name, jeod::Quaternion::normalize(), jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, structure, jeod::MassBody::structure_point, jeod::MassPointState::T_parent_this, and jeod::Vector3::transform().
Referenced by update_integrated_state().
compute_state_elements_forward()
void jeod::DynBody::compute_state_elements_forward (const BodyRefFrame & source_frame, const MassPoint & rel_state, const RefFrameItems & state_items, BodyRefFrame & derived_frame) const protected
Compute selected aspects of the derived state given the source state and the position/ attitude transformation from the source to the derived state.
Parameters
[in] source_frame Source state
[in] rel_state Relative state
[in] state_items States to compute
[out] derived_frame Derived state
Definition at line 215 of file dyn_body_propagate_state.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameRot::ang_vel_this, jeod::RefFrameItems::Att, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::RefFrameItems::contains(), jeod::Vector3::copy(), jeod::Vector3::cross(), jeod::RefFrameItems::get(), jeod::BodyRefFrame::initialized_items, jeod::Quaternion::multiply(), jeod::Quaternion::normalize(), jeod::RefFrameItems::Pos, jeod::RefFrameTrans::position, jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameItems::Rate, jeod::RefFrameState::rot, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::RefFrame::timestamp(), jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose_incr(), jeod::RefFrameItems::Vel, and jeod::RefFrameTrans::velocity.
Referenced by compute_vehicle_point_states(), propagate_state_from_composite(), and propagate_state_from_structure().
compute_state_elements_reverse()
void jeod::DynBody::compute_state_elements_reverse (const BodyRefFrame & source_frame, const MassPoint & rel_state, const RefFrameItems & state_items, BodyRefFrame & derived_frame) const protected
Compute selected aspects of the derived state given the source state and the position/ attitude transformation from the derived to the source state.
Parameters
[in] source_frame Source state
[in] rel_state Relative state
[in] state_items States to compute
[out] derived_frame Derived state
Definition at line 333 of file dyn_body_propagate_state.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameRot::ang_vel_this, jeod::RefFrameItems::Att, jeod::RefFrameRot::compute_ang_vel_products(), jeod::RefFrameRot::compute_transformation(), jeod::Quaternion::conjugate_multiply(), jeod::RefFrameItems::contains(), jeod::Vector3::copy(), jeod::Vector3::cross(), jeod::RefFrameItems::get(), jeod::BodyRefFrame::initialized_items, jeod::Quaternion::normalize(), jeod::RefFrameItems::Pos, jeod::RefFrameTrans::position, jeod::MassPointState::position, jeod::MassPointState::Q_parent_this, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameItems::Rate, jeod::RefFrameState::rot, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::RefFrame::timestamp(), jeod::RefFrameState::trans, jeod::Vector3::transform_transpose(), jeod::Vector3::transform_transpose_decr(), jeod::RefFrameItems::Vel, and jeod::RefFrameTrans::velocity.
Referenced by propagate_state_from_composite().
compute_vehicle_point_derivatives()
void jeod::DynBody::compute_vehicle_point_derivatives (const BodyRefFrame & vehicle_pt, FrameDerivs & pt_derivs) virtual
Compute the state derivatives at a vehicle point.
Parameters
[in] vehicle_pt Vehicle point reference frame
[out] pt_derivs Computed derivatives
Reimplemented in jeod::StructureIntegratedDynBody.
Definition at line 129 of file dyn_body_vehicle_point.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::NamedItem::c_str(), composite_body, jeod::MassBody::composite_properties, jeod::Quaternion::compute_left_quat_deriv(), jeod::MassPoint::compute_relative_state(), jeod::Vector3::cross(), derivs, jeod::Vector3::diff(), jeod::MessageHandler::error(), get_root_body(), jeod::GravityInteraction::grav_grad, grav_interaction, jeod::DynBodyMessages::invalid_frame, mass, jeod::BodyRefFrame::mass_point, name, jeod::FrameDerivs::non_grav_accel, jeod::MassPointState::position, jeod::RefFrameRot::Q_parent_this, jeod::FrameDerivs::Qdot_parent_this, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, jeod::RefFrame::state, jeod::Vector3::sum(), jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, jeod::FrameDerivs::trans_accel, jeod::Vector3::transform(), and jeod::Vector3::transform_transpose().
Referenced by collect_forces_and_torques().
compute_vehicle_point_states()
void jeod::DynBody::compute_vehicle_point_states (RefFrameItems::Items set_items) virtual
Propagate structure frame state to vehicle points.
Parameters
[in] set_items States truly propagated
Definition at line 789 of file dyn_body_propagate_state.cc.
References compute_derived_state_forward(), compute_state_elements_forward(), jeod::BodyRefFrame::mass_point, jeod::RefFrameItems::Pos_Vel_Att_Rate, structure, and vehicle_points.
Referenced by propagate_state_from_composite(), and propagate_state_from_structure().
create_body_integrators()
void jeod::DynBody::create_body_integrators (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls, const JeodIntegrationTime & time_mngr) virtual
Create the integrator (integrators) needed to propagate the translational and rotational state of a DynBody.
Create the translational and rotational integrators for a DynBody.
Parameters
[in] generator Integrator constructor to be used to create state integrators.
[in] controls The integration ontrols created the integrator constructor's create_integration_controls method.
[in] time_mngr The JEOD time manager object.
A DynBody integrates forces and torques in the body frame and forces induced by changes in mass properties.
Parameters
[in] generator Integrator constructor to be used to create state integrators.
[in] controls The integration ontrols created the integrator constructor's create_integration_controls method.
[in] time_mngr The JEOD time manager object.
Definition at line 219 of file dyn_body_integration.cc.
References jeod::NamedItem::c_str(), jeod::RestartableT3SecondOrderODEIntegrator::create_integrator(), jeod::RestartableSO3SecondOrderODEIntegrator::create_integrator(), integ_results_merger, name, rot_integrator, rotation_integration, three_dof, time_manager, trans_integrator, and jeod::GeneralizedSecondOrderODETechnique::validate_technique().
Referenced by jeod::DynamicsIntegrationGroup::add_dyn_body(), create_integrators(), and jeod::DynamicsIntegrationGroup::initialize_group().
create_integrators()
void jeod::DynBody::create_integrators (const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls, const er7_utils::TimeInterface & time_if) override
This interface is required by er7_utils::IntegrableObject.
It should not be used. Use DynBody::create_body_integrators instead.
Parameters
[in] generator Unused.
[in] controls Unused.
[in] time_if Unused.
Definition at line 259 of file dyn_body_integration.cc.
References create_body_integrators(), jeod::MessageHandler::fail(), and jeod::DynBodyMessages::internal_error.
deactivate()
void jeod::DynBody::deactivate () inline
Deactivate a DynBody object.
The current implementation does nothing. DynBody objects are always active.
Definition at line 159 of file dyn_body.hh.
destroy_integrators()
void jeod::DynBody::destroy_integrators (void) override
Destroy the integrators.
Does nothing, but must be implemented to complete abstract function from the inherited IntegrableObject
Definition at line 285 of file dyn_body_integration.cc.
detach() [1/2]
bool jeod::DynBody::detach (DynBody & other_body) virtual
Detach parent and child DynBodies, 'this' and the argument body, such that the detachment happens at the parent body level.
Returns true if successfully detached the bodies. Returns false if unable to detach. Will fail if, for example, the bodies are not in the same mass tree.
Assumptions and Limitations
The detach point between non-immediate attachments (i.e. not parent/child attachments) takes place at whichever body is a progenitor. For example, a call to A.detach(D) in an A->B->C->D attachment is interpreted as a call desiring A // B->C->D. A call to D.detach(B) is interpreted as a call to A->B // C->D.
Returns
Success flag
Parameters
[in] other_body The other body at which the detach will occur
Reimplemented in jeod::StructureIntegratedDynBody.
Definition at line 50 of file dyn_body_detach.cc.
References jeod::NamedItem::c_str(), detach_mass_internal(), dyn_children, jeod::MassBody::dyn_owner, dyn_parent, jeod::MessageHandler::fail(), jeod::MessageHandler::inform(), jeod::DynBodyMessages::invalid_attachment, jeod::MassBody::links, mass, and name.
Referenced by jeod::BodyDetach::apply(), jeod::BodyDetachSpecific::apply(), and ~DynBody().
detach() [2/2]
bool jeod::DynBody::detach (void) virtual
Detach this DynBody from its parent RefFrame or DynBody parent.
If detaching from a DynBody, evoking this method is the equivalent to the above function via detach(*dyn_parent)
Assumptions and Limitations
Will inform and return false if the body has no parent.
Returns
Success flag
Definition at line 138 of file dyn_body_detach.cc.
References jeod::NamedItem::c_str(), jeod::DynBodyGenericFrameAttachment::clear_attachment(), dyn_parent, frame_attach, jeod::MessageHandler::inform(), jeod::DynBodyMessages::invalid_technique, jeod::DynBodyGenericFrameAttachment::isAttached(), and name.
Referenced by jeod::StructureIntegratedDynBody::detach(), remove_mass_body(), and ~DynBody().
detach_mass_body_frames()
void jeod::DynBody::detach_mass_body_frames (MassBody & subbody) protected virtual
For a newly detached mass sub-body, remove body frames for the root sub-body and all child sub-bodies via recursion.
Returns
Validity indicator
Parameters
[in] subbody the root of the newly attached sub-bodies
Definition at line 239 of file dyn_body_detach.cc.
References jeod::TreeLinks< Links, Container, Messages >::child_head(), jeod::TreeLinks< Links, Container, Messages >::child_tail(), jeod::TreeLinks< Links, Container, Messages >::container(), dyn_manager, find_body_frame(), jeod::TreeLinks< Links, Container, Messages >::has_children(), JEOD_DELETE_OBJECT, jeod::MassBody::links, jeod::MassBody::mass_points, jeod::BaseRefFrameManager::remove_ref_frame(), and vehicle_points.
Referenced by remove_mass_body().
detach_mass_internal()
void jeod::DynBody::detach_mass_internal (MassBody & child) protected virtual
Update parent and child properties to reflect that they are detached.
Extensibility comments –
This method is sent to the parent body of the detachment after the child body has severed the logical connectivity between the parent body and child body.
The generic purpose of this method is to update any physical properties that change as a result of the detachment.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Note
Assumptions and Limitations
The detachment is valid and logical connectivity has been severed. Neither assumption is checked.
Parameters
[in,out] child The child body; the body newly detached from this body.
Definition at line 285 of file dyn_body_detach.cc.
References core_body, jeod::MassBody::detach_sever_links(), jeod::MassBody::detach_update_properties(), get_root_body_internal(), mass, jeod::RefFrameItems::Pos_Vel_Att_Rate, propagate_state(), and set_state_source_internal().
Referenced by detach(), and remove_mass_body().
find_body_frame()
BodyRefFrame * jeod::DynBody::find_body_frame (const char * frame_id) const virtual
Find the BodyRefFrame named by the provided identifier.
The name of a BodyRefFrame must be prefixed by the body name. The provided identifier can include or exclude this prefix. The body name is used as the prefix if the the provided name does not start with the body name.
Note
Assumptions and Limitations
Limitation: Provided identifier must be non-NULL and non-empty. Failure to comply is a fatal error.
Limitation: The found frame must be a BodyRefFrame. Finding a non-BodyRefFrame that matches the name is a fatal error.
Assumption: Failure to find a frame is not an error. The method returns NULL if this is the case.
Returns
Found frame
Parameters
[in] frame_id Frame ID suffix
Definition at line 50 of file dyn_body_find_body_frame.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::fail(), jeod::BaseRefFrameManager::find_ref_frame(), jeod::RefFrame::get_name(), jeod::DynBodyMessages::invalid_name, name, and jeod::NamedItem::suffix().
Referenced by detach_mass_body_frames(), jeod::DynBodyInit::find_body_frame(), and jeod::RelativeDerivedState::initialize().
find_vehicle_point()
const BodyRefFrame * jeod::DynBody::find_vehicle_point (const char * pt_name) const
Find the vehicle point with the given name.
Returns
Vehicle point
Parameters
[in] pt_name Vehicle point name
Definition at line 101 of file dyn_body_vehicle_point.cc.
References name, jeod::NamedItem::size(), jeod::NamedItem::suffix(), and vehicle_points.
Referenced by add_mass_body(), attach_child(), attach_to_frame(), and jeod::ContactFacet::create_vehicle_point().
get_dynamics_integration_group()
DynamicsIntegrationGroup * jeod::DynBody::get_dynamics_integration_group ()
Get the DynamicsIntegrationGroup that integrates this DynBody object.
Returns
Pointer to the DynamicsIntegrationGroup of this DynBody.
Definition at line 261 of file dyn_body.cc.
References jeod::MessageHandler::fail(), and jeod::DynBodyMessages::internal_error.
Referenced by attach_update_properties(), and set_integ_frame().
get_initialized_states()
const RefFrameItems& jeod::DynBody::get_initialized_states () const inline
Indicate which state elements have been initialized.
Returns
Initialized states indicator.
Definition at line 528 of file dyn_body.hh.
References initialized_states.
Referenced by jeod::DynManager::check_for_uninitialized_states().
get_integrable_objects()
JeodPointerVector<er7_utils::IntegrableObject>::type jeod::DynBody::get_integrable_objects () inline
Get the IntegrableObjects associated with this DynBody.
Returns
A pointer to a JeodPointerVector containing the associated integrable objects.
Definition at line 308 of file dyn_body.hh.
References associated_integrable_objects.
Referenced by jeod::DynamicsIntegrationGroup::add_dyn_body().
get_parent_body()
const DynBody * jeod::DynBody::get_parent_body () const virtual
Returns this DynBody object's parent body.
Returns
Const pointer to the parent body.
Definition at line 177 of file dyn_body.cc.
References dyn_parent.
Referenced by jeod::StructureIntegratedDynBody::detach().
get_parent_body_internal()
DynBody * jeod::DynBody::get_parent_body_internal () protected virtual
Returns this DynBody object's parent body.
Returns
Pointer to parent body.
Definition at line 186 of file dyn_body.cc.
References dyn_parent.
get_root_body()
const DynBody * jeod::DynBody::get_root_body () const virtual
Finds this DynBody object's root body.
Returns
Const pointer to the root body.
Definition at line 194 of file dyn_body.cc.
Referenced by attach_validate_child(), attach_validate_parent(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), compute_vehicle_point_derivatives(), and set_state_source().
get_root_body_internal()
DynBody * jeod::DynBody::get_root_body_internal () protected virtual
Finds this DynBody object's root body.
Returns
Pointer to the root body.
Definition at line 205 of file dyn_body.cc.
References dyn_parent.
Referenced by attach_child(), attach_to_frame(), attach_update_properties(), detach_mass_internal(), set_attitude_left_quaternion(), set_attitude_matrix(), set_attitude_rate(), set_attitude_right_quaternion(), set_position(), set_state(), set_state_source(), set_velocity(), and update_integrated_state().
initialize_controls()
void jeod::DynBody::initialize_controls (GravityManager & grav_manager) virtual
Initialize the gravity controls of this DynBody.
Note
Initialization phasing:
The following must have been called prior to calling this method:
GravityManager::initialize_model to register the GravityManager object with the dynamics manager.
GravityManager::add_grav_source to register the pertinent GravitySource objects with the Gravity Manager.
Planet::register_model to associate the planet with a GravitySource.
Parameters
[in] grav_manager Reference to Gravity Manager
Definition at line 232 of file dyn_body.cc.
References dyn_manager, grav_interaction, and jeod::GravityInteraction::initialize_controls().
Referenced by jeod::DynManager::initialize_gravity_controls().
initialize_model()
void jeod::DynBody::initialize_model (BaseDynManager & dyn_manager_in) virtual
Initialize internal and external interrelations, including registration / with the dynamics manager.
Parameters
[in,out] dyn_manager_in Dynamics manager
Definition at line 45 of file dyn_body_initialize_model.cc.
References jeod::BaseDynManager::add_dyn_body(), jeod::BaseRefFrameManager::add_ref_frame(), jeod::NamedItem::c_str(), composite_body, core_body, dyn_manager, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), initialized_states, integ_frame, integ_frame_name, jeod::DynBodyMessages::invalid_frame, jeod::DynBodyMessages::invalid_name, mass, name, jeod::MassBody::needs_update, jeod::RefFrameItems::No_Items, jeod::RefFrameItems::set(), set_integ_frame(), jeod::RefFrame::set_name(), jeod::RefFrame::set_owner(), jeod::NamedItem::size(), structure, and jeod::Subscription::subscribe().
Referenced by jeod::PropagatedPlanet::initialize_model().
initialized_states_contains()
bool jeod::DynBody::initialized_states_contains (RefFrameItems::Items test_items) const inline
Indicate whether the specified state elements have been initialized.
Parameters
test_items States to test.
Returns
True if all test items have been initialized, false otherwise.
Definition at line 538 of file dyn_body.hh.
References jeod::RefFrameItems::contains(), and initialized_states.
integrate()
er7_utils::IntegratorResult jeod::DynBody::integrate (double dyn_dt, unsigned int target_stage) override
Integrate state by the specified dynamic time interval.
Integrate the translational and rotational state and propagate the integrated state to derived states.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 316 of file dyn_body_integration.cc.
References jeod::RefFrame::compute_relative_state(), frame_attach, jeod::DynBodyGenericFrameAttachment::get_attach_offset(), jeod::DynBodyGenericFrameAttachment::get_parent_frame(), jeod::RefFrameState::incr_right(), initialized_states, integ_frame, integ_results_merger, jeod::DynBodyGenericFrameAttachment::isAttached(), jeod::RefFrameItems::Pos_Vel_Att_Rate, propagate_state(), rot_integ(), rotational_dynamics, jeod::RefFrameItems::set(), set_state(), structure, trans_integ(), and translational_dynamics.
Referenced by jeod::DynamicsIntegrationGroup::integrate_bodies().
is_root_body()
bool jeod::DynBody::is_root_body ()
Indicates whether this DynBody object is a root body.
Returns
Is this a root body?
Definition at line 169 of file dyn_body.cc.
References dyn_parent.
Referenced by jeod::DynamicsIntegrationGroup::collect_derivatives(), jeod::DynamicsIntegrationGroup::gravitation(), jeod::DynManager::initialize_dyn_bodies(), and jeod::DynamicsIntegrationGroup::integrate_bodies().
migrate_integrable_objects()
void jeod::DynBody::migrate_integrable_objects (void)
Call this method before switching this dyn body to a new group if you want the associated integrable objects to follow.
Definition at line 337 of file dyn_body.cc.
References associated_integrable_objects, jeod::NamedItem::c_str(), jeod::MessageHandler::error(), jeod::DynBodyMessages::invalid_group, name, and jeod::JeodIntegrationGroup::remove_integrable_object().
operator=()
DynBody& jeod::DynBody::operator= (const DynBody &) private
Not implemented.
process_dynamic_attachment()
void jeod::DynBody::process_dynamic_attachment (const double offset_pstr_cstr_pstr[3], const double T_pstr_cstr[3][3], DynBody & root_body, DynBody & child_body) protected virtual
Process the attachment event of one body from another.
This method is called by the attach method after the links have established or severed and is invoked twice:
On the parent, in which case the parent argument is null and the child argument is the child that attached from the parent, and
On the detaching child, in which case the child argument is null and the parent argument is the body from which the child was detached.
Note
Assumptions and Limitations:
Instances of more derived classes, with presumably more involved dynamics, are situated higher in the mass tree than are more basic instances. For example, a simple MassBody can be a child of a DynBody, but not the other way around.
The attachment in the mass tree between the immediate child and the superior body is assumed to reflect a real physical attachment.
Parameters
[in] offset_pstr_cstr_pstr Location of this body's structural origin with respect to the new parent body's structural origin, specified in structural coordinates of the new parent body.
Units: m
[in] T_pstr_cstr Transformation matrix from the new parent body's structural frame to this body's structural frame.
[in,out] root_body Body at the root of the mass tree
[in,out] child_body Body that is being attached to this body.
Definition at line 953 of file dyn_body_attach.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::MassBody::attach_update_properties(), composite_body, jeod::MassBody::composite_properties, jeod::Vector3::copy(), core_body, jeod::Vector3::cross(), jeod::Vector3::diff(), jeod::Vector3::incr(), jeod::MassProperties::inertia, jeod::MassProperties::inverse_inertia, jeod::MassProperties::inverse_mass, jeod::MassProperties::mass, mass, jeod::RefFrameItems::Pos_Att, jeod::RefFrameTrans::position, jeod::MassPointState::position, propagate_state(), jeod::RefFrameState::rot, jeod::Vector3::scale(), set_state_source_internal(), jeod::RefFrame::state, structure, jeod::Vector3::sum(), jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::RefFrameItems::Vel_Rate, and jeod::RefFrameTrans::velocity.
Referenced by attach_update_properties().
propagate_state()
void jeod::DynBody::propagate_state () virtual
Propagate state from the integrated state to attached bodies.
Definition at line 574 of file dyn_body_propagate_state.cc.
References jeod::NamedItem::c_str(), composite_body, dyn_parent, jeod::MessageHandler::fail(), initialized_states, integrated_frame, jeod::DynBodyMessages::invalid_frame, jeod::RefFrameItems::is_empty(), name, propagate_state(), propagate_state_from_composite(), propagate_state_from_structure(), structure, and update_integrated_state().
Referenced by jeod::DynBodyInit::apply(), attach_update_properties(), detach_mass_internal(), jeod::PropagatedPlanet::ephem_update(), integrate(), process_dynamic_attachment(), propagate_state(), and switch_integration_frames().
propagate_state_from_composite()
void jeod::DynBody::propagate_state_from_composite () protected virtual
Propagate state to attached bodies starting from this body's composite frame.
Note
Assumptions and Limitations
At least some states are set.
Definition at line 700 of file dyn_body_propagate_state.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameItems::Att, autoupdate_vehicle_points, composite_body, jeod::MassBody::composite_properties, jeod::MassBody::composite_wrt_pbdy, compute_derived_state_forward(), compute_derived_state_reverse(), compute_state_elements_forward(), compute_state_elements_reverse(), compute_vehicle_point_states(), core_body, jeod::MassBody::core_wrt_composite, dyn_children, jeod::RefFrameItems::get(), jeod::BodyRefFrame::initialized_items, initialized_states, jeod::RefFrameItems::is_full(), mass, jeod::RefFrameItems::Pos_Vel, jeod::RefFrameItems::Pos_Vel_Att_Rate, propagate_state_from_composite(), propagate_state_from_structure(), jeod::RefFrameItems::Rate, jeod::RefFrameItems::remove(), jeod::RefFrameItems::set(), structure, and jeod::RefFrameItems::Vel.
Referenced by propagate_state(), and propagate_state_from_composite().
propagate_state_from_structure()
void jeod::DynBody::propagate_state_from_structure () protected virtual
Propagate state to attached bodies starting from this body's structural frame.
Note
Assumptions and Limitations
At least some states are set.
Definition at line 608 of file dyn_body_propagate_state.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameItems::Att, autoupdate_vehicle_points, composite_body, jeod::MassBody::composite_properties, compute_derived_state_forward(), compute_state_elements_forward(), compute_vehicle_point_states(), core_body, jeod::MassBody::core_properties, dyn_children, jeod::RefFrameItems::get(), jeod::BodyRefFrame::initialized_items, initialized_states, jeod::RefFrameItems::is_full(), mass, jeod::RefFrameItems::Pos_Vel, jeod::RefFrameItems::Pos_Vel_Att_Rate, propagate_state_from_structure(), jeod::RefFrameItems::Rate, jeod::RefFrameItems::remove(), jeod::RefFrameItems::set(), structure, jeod::MassBody::structure_point, and jeod::RefFrameItems::Vel.
Referenced by propagate_state(), propagate_state_from_composite(), and propagate_state_from_structure().
remove_integrable_object()
void jeod::DynBody::remove_integrable_object (er7_utils::IntegrableObject & associated_integrable_object)
Remove an IntegrableObject from association with this DynBody.
Parameters
[in] associated_integrable_object The IntegrableObject to be associated with this DynBody.
Definition at line 309 of file dyn_body.cc.
References associated_integrable_objects, and jeod::MessageHandler::warn().
Referenced by jeod::PendulumConstraintComponent::detach_from_solver().
remove_mass_body()
bool jeod::DynBody::remove_mass_body (MassBody & child) virtual
Remove connectivity between this (parent) DynBody and the argument (child) MassBody mass subbody.
The MassBody and associated body frames are removed, such that the MassBody effectively "jettisons" from dynamics operations.
Extensibility comments –
This method is invoked before the updating the parent/child states.
The generic purpose of this method is to sever all connectivity links between parent and child, most importantly mass properties.
Any class that overrides this method must either invoke this method or perform the actions performed herein.
Note
Assumptions and Limitations
The detachment must be valid or it is not performed. The MassBody must not belong to a DynBody-derived dynamic body.
Parameters
[in,out] child The child mass subbody; the body to be detached
Definition at line 166 of file dyn_body_detach.cc.
References jeod::NamedItem::c_str(), detach(), detach_mass_body_frames(), detach_mass_internal(), jeod::MassBody::dyn_owner, jeod::MassBody::get_parent_body(), jeod::MessageHandler::inform(), jeod::DynBodyMessages::invalid_technique, jeod::MassBody::links, mass, mass_children, jeod::MassBody::name, and name.
Referenced by jeod::BodyDetachSpecific::apply(), jeod::MassBody::detach(), and ~DynBody().
reset_controls()
void jeod::DynBody::reset_controls () virtual
Make the frame subscriptions for each control consistent with the requirements for that control.
Definition at line 243 of file dyn_body.cc.
References dyn_manager, grav_interaction, and jeod::GravityInteraction::reset_controls().
Referenced by jeod::DynManager::reset_gravity_controls().
reset_integrators()
void jeod::DynBody::reset_integrators (void) override
Reset the translational and rotational integrators.
Definition at line 295 of file dyn_body_integration.cc.
References jeod::RestartableT3SecondOrderODEIntegrator::reset_integrator(), jeod::RestartableSO3SecondOrderODEIntegrator::reset_integrator(), rot_integrator, rotational_dynamics, trans_integrator, and translational_dynamics.
Referenced by jeod::DynamicsIntegrationGroup::reset_body_integrators().
rot_integ()
er7_utils::IntegratorResult jeod::DynBody::rot_integ (double dyn_dt, unsigned int target_stage) protected virtual
Integrate the vehicle's rotational state.
Integrate the rotational state of a DynBody.
Parameters
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Reimplemented in jeod::StructureIntegratedDynBody.
Definition at line 388 of file dyn_body_integration.cc.
References jeod::RefFrameRot::ang_vel_mag, jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::ang_vel_unit, composite_body, jeod::Quaternion::compute_left_quat_deriv(), derivs, jeod::Vector3::initialize(), jeod::RestartableSO3SecondOrderODEIntegrator::integrate(), jeod::Quaternion::left_quat_to_transformation(), jeod::Quaternion::normalize_integ(), jeod::RefFrameRot::Q_parent_this, jeod::FrameDerivs::Qdot_parent_this, jeod::RefFrameState::rot, jeod::FrameDerivs::rot_accel, rot_integrator, jeod::Vector3::scale(), jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, and jeod::Vector3::vmag().
Referenced by integrate().
set_attitude_left_quaternion()
void jeod::DynBody::set_attitude_left_quaternion (const Quaternion & left_quat, BodyRefFrame & subject_frame)
Set the attitude of the vehicle.
Note
Assumptions and Limitations
Provided quaternion is a unit quaternion.
Parameters
[in] left_quat Attitude wrt integ frame
[out] subject_frame Frame to update
Definition at line 218 of file dyn_body_set_state.cc.
References jeod::RefFrameItems::Att, jeod::check_frame_ownership(), get_root_body_internal(), jeod::Quaternion::left_quat_to_transformation(), jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, set_state_source_internal(), jeod::RefFrame::state, and jeod::RefFrameRot::T_parent_this.
set_attitude_matrix()
void jeod::DynBody::set_attitude_matrix (const double matrix[3][3], BodyRefFrame & subject_frame)
Set the attitude of the vehicle.
Note
Assumptions and Limitations
Provided matrix is orthogonal.
Parameters
[in] matrix Attitude wrt integ frame
[out] subject_frame Frame to update
Definition at line 256 of file dyn_body_set_state.cc.
References jeod::RefFrameItems::Att, jeod::check_frame_ownership(), jeod::Matrix3x3::copy(), get_root_body_internal(), jeod::Quaternion::left_quat_from_transformation(), jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, set_state_source_internal(), jeod::RefFrame::state, and jeod::RefFrameRot::T_parent_this.
set_attitude_rate()
void jeod::DynBody::set_attitude_rate (const double attitude_rate[3], BodyRefFrame & subject_frame)
Set the attitude rate of the vehicle.
Note
Assumptions and Limitations
Provided vector is expressed in body frame coordinates.
Parameters
[in] attitude_rate Attitude wrt integ frame
Units: r/s
[out] subject_frame Frame to update
Definition at line 275 of file dyn_body_set_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::check_frame_ownership(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::Vector3::copy(), get_root_body_internal(), jeod::RefFrameItems::Rate, jeod::RefFrameState::rot, set_state_source_internal(), and jeod::RefFrame::state.
set_attitude_right_quaternion()
void jeod::DynBody::set_attitude_right_quaternion (const Quaternion & right_quat, BodyRefFrame & subject_frame)
Set the attitude of the vehicle.
Note
Assumptions and Limitations
Provided quaternion is a unit quaternion.
Parameters
[in] right_quat Attitude wrt integ frame
[out] subject_frame Frame to update
Definition at line 237 of file dyn_body_set_state.cc.
References jeod::RefFrameItems::Att, jeod::check_frame_ownership(), jeod::Quaternion::conjugate(), get_root_body_internal(), jeod::Quaternion::left_quat_to_transformation(), jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, set_state_source_internal(), jeod::RefFrame::state, and jeod::RefFrameRot::T_parent_this.
set_integ_frame() [1/2]
void jeod::DynBody::set_integ_frame (EphemerisRefFrame & new_integ_frame) protected virtual
Set the integration frame for this body and all its child bodies to the provided frame.
Note
Assumptions and Limitations
Provided frame is a valid integration frame.
Parameters
[in] new_integ_frame New integration frame
Definition at line 60 of file dyn_body_integration.cc.
References jeod::RefFrame::add_child(), composite_body, core_body, dyn_children, dyn_manager, get_dynamics_integration_group(), grav_interaction, integ_frame, jeod::RefFrame::reset_parent(), jeod::GravityInteraction::set_integ_frame(), set_integ_frame(), structure, jeod::BaseRefFrameManager::subscribe_to_frame(), jeod::BaseRefFrameManager::unsubscribe_to_frame(), and vehicle_points.
Referenced by attach_establish_links(), initialize_model(), set_integ_frame(), and switch_integration_frames().
set_integ_frame() [2/2]
void jeod::DynBody::set_integ_frame (const char * new_integ_frame_name) protected virtual
Set the integration frame for this body and all its child bodies to the frame indicated by the provided name.
Note
Assumptions and Limitations
Assumption: Provided string is a non-NULL, non-empty string.
Assumption: State is not to be updated.
Limitation: Assocated frame must be a valid integration frame.
Parameters
[in] new_integ_frame_name New integration frame
Definition at line 127 of file dyn_body_integration.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::fail(), jeod::BaseEphemeridesManager::find_integ_frame(), jeod::DynBodyMessages::invalid_name, name, and set_integ_frame().
set_name()
void jeod::DynBody::set_name (const std::string & name_in)
Set the name of the vehicle.
Parameters
[in] name_in Name of this body
Definition at line 161 of file dyn_body.cc.
References mass, and jeod::MassBody::set_name().
set_position()
void jeod::DynBody::set_position (const double position[3], BodyRefFrame & subject_frame)
Set the position of the vehicle.
Parameters
[in] position Position wrt integ frame
Units: M
[out] subject_frame Frame to update
Definition at line 184 of file dyn_body_set_state.cc.
References jeod::check_frame_ownership(), jeod::Vector3::copy(), get_root_body_internal(), jeod::RefFrameItems::Pos, jeod::RefFrameTrans::position, set_state_source_internal(), jeod::RefFrame::state, and jeod::RefFrameState::trans.
set_state()
void jeod::DynBody::set_state (RefFrameItems::Items set_items, const RefFrameState & state, BodyRefFrame & subject_frame)
Set the parts of the specified reference frame as indicated by the set_items parameter from the supplied state and propagate these items to all dynamic bodies attached to this body.
This method forms an integral part of the state initialization process and can also be used by a simulation that that receives state overrides from some other simulation.
Note
Assumptions and Limitations
The subject reference frame is owned by this dynamic body. This limitation is enforced.
Parameters
[in] set_items Items to set
[in] state State to be copied
[out] subject_frame Frame to be set
Definition at line 79 of file dyn_body_set_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameItems::Att, jeod::check_frame_ownership(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::Vector3::copy(), get_root_body_internal(), jeod::Quaternion::left_quat_to_transformation(), jeod::RefFrameItems::Pos, jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameItems::Rate, jeod::RefFrameState::rot, set_state_source_internal(), jeod::RefFrame::state, jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::RefFrameItems::Vel, and jeod::RefFrameTrans::velocity.
Referenced by jeod::DynBodyInit::apply(), integrate(), jeod::PropagatedEphemerisPlanet::update(), and jeod::PropagatedEphemerisOrientation::update().
set_state_source()
void jeod::DynBody::set_state_source (RefFrameItems::Items items, BodyRefFrame & frame)
Set the source of aspects of the state.
The setting is applied to the root of the DynBody tree.
Note
Assumptions and Limitations
The supplied frame must either be owned directly by this body or this body must be a root body and the owner of the supplied frame must be a child body of this body.
Parameters
[in] items Items to propagate
[in] frame Frame containing state
Definition at line 132 of file dyn_body_set_state.cc.
References jeod::NamedItem::c_str(), dyn_parent, jeod::MessageHandler::fail(), jeod::RefFrame::get_name(), jeod::RefFrame::get_owner(), get_root_body(), get_root_body_internal(), jeod::DynBodyMessages::invalid_frame, name, and set_state_source_internal().
set_state_source_internal()
void jeod::DynBody::set_state_source_internal (RefFrameItems::Items items, BodyRefFrame & frame) protected
Set the source of aspects of the state.
Note
Assumptions and Limitations
Assumptions, neither of which is checked:
This is a root body.
The supplied frame is owned by a body that is a child of this body.
Parameters
[in] items Items to propagate
[in] frame Frame containing state
Definition at line 293 of file dyn_body_set_state.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameItems::Att, attitude_source, jeod::BodyRefFrame::initialized_items, initialized_states, jeod::RefFrameItems::Pos, position_source, jeod::RefFrameItems::Rate, rate_source, jeod::RefFrameItems::remove(), jeod::RefFrameItems::Vel, and velocity_source.
Referenced by attach_update_properties(), detach_mass_internal(), process_dynamic_attachment(), set_attitude_left_quaternion(), set_attitude_matrix(), set_attitude_rate(), set_attitude_right_quaternion(), set_position(), set_state(), set_state_source(), and set_velocity().
set_velocity()
void jeod::DynBody::set_velocity (const double velocity[3], BodyRefFrame & subject_frame)
Set the velocity of the vehicle.
Parameters
[in] velocity Velocity wrt integ frame
Units: M/s
[out] subject_frame Frame to update
Definition at line 201 of file dyn_body_set_state.cc.
References jeod::check_frame_ownership(), jeod::Vector3::copy(), get_root_body_internal(), set_state_source_internal(), jeod::RefFrame::state, jeod::RefFrameState::trans, jeod::RefFrameItems::Vel, and jeod::RefFrameTrans::velocity.
sort_controls()
void jeod::DynBody::sort_controls () virtual
Sort the gravity controls in ascending acceleration magnitude order.
Definition at line 252 of file dyn_body.cc.
References grav_interaction, and jeod::GravityInteraction::sort_controls().
switch_integration_frames() [1/2]
void jeod::DynBody::switch_integration_frames (EphemerisRefFrame & new_integ_frame) virtual
Switch the integration frame for this body and all its child bodies to the indicated frame.
Note
Assumptions and Limitations
Limitation: Assocated frame must be a valid integration frame.
Parameters
[in] new_integ_frame New integration frame
Definition at line 148 of file dyn_body_integration.cc.
References jeod::NamedItem::c_str(), jeod::RefFrame::compute_relative_state(), dyn_manager, dyn_parent, jeod::MessageHandler::fail(), jeod::RefFrame::get_name(), integrated_frame, jeod::DynBodyMessages::invalid_frame, jeod::BaseEphemeridesManager::is_integ_frame(), name, propagate_state(), set_integ_frame(), jeod::RefFrame::state, switch_integration_frames(), and update_integrated_state().
Referenced by jeod::DynBodyFrameSwitch::apply(), and switch_integration_frames().
switch_integration_frames() [2/2]
void jeod::DynBody::switch_integration_frames (const char * new_integ_frame_name) virtual
Switch the integration frame for this body and all its child bodies to the frame indicated by the provided name.
Note
Assumptions and Limitations
Assumption: Provided string is a non-NULL, non-empty string.
Limitation: Assocated frame must be a valid integration frame.
Parameters
[in] new_integ_frame_name New integration frame
Definition at line 190 of file dyn_body_integration.cc.
References jeod::NamedItem::c_str(), dyn_manager, jeod::MessageHandler::fail(), jeod::BaseEphemeridesManager::find_integ_frame(), jeod::DynBodyMessages::invalid_name, name, and switch_integration_frames().
trans_integ()
er7_utils::IntegratorResult jeod::DynBody::trans_integ (double dyn_dt, unsigned int target_stage) protected virtual
Integrate the vehicle's translational state.
Integrate the translational state of a DynBody.
Parameters
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
Returns
The status (time advance, pass/fail status) of the integration.
Reimplemented in jeod::StructureIntegratedDynBody.
Definition at line 368 of file dyn_body_integration.cc.
References composite_body, derivs, jeod::RestartableT3SecondOrderODEIntegrator::integrate(), jeod::RefFrameTrans::position, jeod::RefFrame::state, jeod::RefFrameState::trans, jeod::FrameDerivs::trans_accel, trans_integrator, and jeod::RefFrameTrans::velocity.
Referenced by integrate().
update_integrated_state()
void jeod::DynBody::update_integrated_state () virtual
Propagate state from state owners to the integrated state.
Definition at line 396 of file dyn_body_propagate_state.cc.
References jeod::RefFrameItems::add(), jeod::RefFrameRot::ang_vel_this, jeod::RefFrameItems::Att, attitude_source, jeod::RefFrameRot::compute_ang_vel_products(), compute_ref_point_transform(), jeod::RefFrameRot::compute_transformation(), jeod::Quaternion::conjugate_multiply(), jeod::Vector3::copy(), jeod::Vector3::cross(), dyn_parent, get_root_body_internal(), jeod::JeodIntegrationTime::get_timestamp_time(), jeod::BodyRefFrame::initialized_items, initialized_states, integrated_frame, jeod::Quaternion::normalize(), jeod::RefFrameItems::Pos, jeod::RefFrameTrans::position, jeod::MassPointState::position, position_source, jeod::MassPointState::Q_parent_this, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameItems::Rate, rate_source, jeod::RefFrameState::rot, jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::MassPointState::T_parent_this, jeod::RefFrameRot::T_parent_this, time_manager, jeod::RefFrameState::trans, jeod::Vector3::transform_transpose(), jeod::Vector3::transform_transpose_decr(), update_integrated_state(), jeod::RefFrameItems::Vel, jeod::RefFrameTrans::velocity, and velocity_source.
Referenced by propagate_state(), switch_integration_frames(), and update_integrated_state().
Friends And Related Function Documentation
init_attrjeod__DynBody
void init_attrjeod__DynBody () friend
InputProcessor
friend class InputProcessor friend
Definition at line 116 of file dyn_body.hh.
Field Documentation
associated_integrable_objects
std::vector<er7_utils::IntegrableObject*> jeod::DynBody::associated_integrable_objects protected
List of integrable objects to be integrated with this DynBody.
trick_io(**)
Definition at line 1225 of file dyn_body.hh.
Referenced by add_integrable_object(), clear_integrable_objects(), get_integrable_objects(), migrate_integrable_objects(), and remove_integrable_object().
attitude_source
BodyRefFrame* jeod::DynBody::attitude_source protected
The reference frame that contains the user-set attitude.
trick_units(–)
Definition at line 1207 of file dyn_body.hh.
Referenced by set_state_source_internal(), and update_integrated_state().
autoupdate_vehicle_points
bool jeod::DynBody::autoupdate_vehicle_points
Are vehicle points automatically updated? The vehicle points are automatically calculated at initialization time but are only automatically updated at runtime if this member is true.
Setting this member to false indicates the responsibility for updating vehicle point states is performed elsewhere, such as in a scheduled call to compute_vehicle_point_states.trick_units(–)
Definition at line 762 of file dyn_body.hh.
Referenced by jeod::DynBodyInit::apply(), propagate_state_from_composite(), and propagate_state_from_structure().
collect
BodyForceCollect jeod::DynBody::collect
Force/Torque collection mechanism.
trick_units(–)
Definition at line 781 of file dyn_body.hh.
Referenced by jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::collect_local_forces_and_torques(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), and jeod::StructureIntegratedDynBody::solve_constraints().
composite_body
BodyRefFrame jeod::DynBody::composite_body
Vehicle composite body reference frame.
The reference frame origin is at the composite body center of mass, and the reference frame axes are the body frame axes as defined in the composite mass properties.trick_units(–)
Definition at line 697 of file dyn_body.hh.
Referenced by jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInitNedState::apply(), jeod::DynBodyFrameSwitch::apply(), collect_forces_and_torques(), compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), compute_vehicle_point_derivatives(), DynBody(), jeod::DynamicsIntegrationGroup::gravitation(), jeod::LvlhDerivedState::initialize(), initialize_model(), jeod::DynBodyInitPlanetDerived::is_ready(), jeod::DynBodyFrameSwitch::is_ready(), process_dynamic_attachment(), propagate_state(), propagate_state_from_composite(), propagate_state_from_structure(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), rot_integ(), set_integ_frame(), jeod::StructureIntegratedDynBody::solve_constraints(), trans_integ(), jeod::GravityTorque::update(), jeod::PlanetaryDerivedState::update(), jeod::OrbElemDerivedState::update(), jeod::EulerDerivedState::update(), jeod::NedDerivedState::update(), jeod::SolarBetaDerivedState::update(), and ~DynBody().
compute_point_derivative
bool jeod::DynBody::compute_point_derivative
Should the point derivatives for the body be computed? A child body's translational and rotational derivatives are only computed if this is true.
If this is false, they will be 0.trick_units(–)
Definition at line 731 of file dyn_body.hh.
Referenced by collect_forces_and_torques().
core_body
BodyRefFrame jeod::DynBody::core_body
Vehicle core body reference frame.
The reference frame origin is at the core body center of mass, and the reference frame axes are the body frame axes as defined in the core mass properties.trick_units(–)
Definition at line 689 of file dyn_body.hh.
Referenced by compute_ref_point_transform(), detach_mass_internal(), DynBody(), initialize_model(), process_dynamic_attachment(), propagate_state_from_composite(), propagate_state_from_structure(), set_integ_frame(), and ~DynBody().
derivs
FrameDerivs jeod::DynBody::derivs
Translational/rotational accelerations.
trick_units(–)
Definition at line 775 of file dyn_body.hh.
Referenced by jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), compute_vehicle_point_derivatives(), jeod::StructureIntegratedDynBody::rot_integ(), rot_integ(), jeod::StructureIntegratedDynBody::solve_constraints(), and trans_integ().
dyn_children
std::list<DynBody*> jeod::DynBody::dyn_children protected
The subset of the dynamic bodies attached to this dynamic body.
Definition at line 1175 of file dyn_body.hh.
Referenced by attach_establish_links(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), detach(), propagate_state_from_composite(), propagate_state_from_structure(), set_integ_frame(), and ~DynBody().
dyn_manager
BaseDynManager*& jeod::DynBody::dyn_manager protected
The dynamics manager for the simulation.
trick_units(–)
Definition at line 1149 of file dyn_body.hh.
Referenced by add_mass_body_frames(), add_mass_body_validate(), add_mass_point(), attach_to_frame(), attach_validate_parent(), detach_mass_body_frames(), find_body_frame(), initialize_controls(), initialize_model(), reset_controls(), set_integ_frame(), switch_integration_frames(), and ~DynBody().
dyn_parent
DynBody* jeod::DynBody::dyn_parent protected
The DynBody to which this body is attached.
This points to exactly the same object as does the links.parent member. While a mass body can be attached to any kind of mass body, a dynamic body can only be attached to another dynamic body.trick_units(–)
Definition at line 1162 of file dyn_body.hh.
Referenced by attach_establish_links(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), detach(), get_parent_body(), get_parent_body_internal(), get_root_body_internal(), is_root_body(), propagate_state(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), set_state_source(), jeod::StructureIntegratedDynBody::solve_constraints(), switch_integration_frames(), update_integrated_state(), and ~DynBody().
frame_attach
DynBodyGenericFrameAttachment jeod::DynBody::frame_attach protected
The RefFrame this body is attached to.
Once attached, the DynBody will no longer numerically integrate rotational or dynamic states and is considered fixed wrt the RefFrame. The DynBody's integration frame will continue to be used to populate the composite_body, structure, core_body and mass point dynamic states.
Definition at line 1170 of file dyn_body.hh.
Referenced by attach_to_frame(), detach(), and integrate().
grav_interaction
GravityInteraction jeod::DynBody::grav_interaction
Gravitational interactions.
This data member specifies how the vehicle interacts gravitationally with various planetary bodies in the simulation and contains the computed acceleration toward those planetary bodies.trick_units(–)
Definition at line 770 of file dyn_body.hh.
Referenced by add_control(), jeod::DynBodyFrameSwitch::apply(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), compute_vehicle_point_derivatives(), jeod::DynamicsIntegrationGroup::gravitation(), initialize_controls(), reset_controls(), set_integ_frame(), sort_controls(), and jeod::GravityTorque::update().
initialized_states
RefFrameItems jeod::DynBody::initialized_states protected
Enum value indicating which of position, velocity, attitude, and rate have been initialized.
trick_units(–)
Definition at line 1192 of file dyn_body.hh.
Referenced by attach_update_properties(), attach_validate_child(), DynBody(), get_initialized_states(), initialize_model(), initialized_states_contains(), integrate(), propagate_state(), propagate_state_from_composite(), propagate_state_from_structure(), set_state_source_internal(), and update_integrated_state().
integ_frame
EphemerisRefFrame* jeod::DynBody::integ_frame
The current integration frame.
trick_units(–)
Definition at line 681 of file dyn_body.hh.
Referenced by add_mass_body_frames(), add_mass_point(), jeod::DynBodyInit::apply_user_inputs(), attach_establish_links(), initialize_model(), integrate(), and set_integ_frame().
integ_frame_name
char* jeod::DynBody::integ_frame_name
The name of the reference frame with respect to which the body's reference frames (core, composite, structure, plus vehicle point frames) are to be represented and propagated.
The value must identify a valid integration frame, i.e., a non-rotating, ephemeris based reference frame.
This member is used at initialization time only. To change the integration frame post-initialization use the function DynBody::switch_integration_frames. This can be invoked directly, or indirectly via a FrameSwitch body action.trick_units(–)
Definition at line 676 of file dyn_body.hh.
Referenced by initialize_model(), and jeod::PropagatedPlanet::initialize_model().
integ_results_merger
er7_utils::IntegratorResultMergerContainer jeod::DynBody::integ_results_merger protected
The object that merges integration results.
trick_units(–)
Definition at line 1231 of file dyn_body.hh.
Referenced by create_body_integrators(), and integrate().
integrated_frame
BodyRefFrame* jeod::DynBody::integrated_frame protected
The reference frame whose state is updated via the state integrator.
All other reference frames are calculated from this frame.trick_units(–)
Definition at line 1218 of file dyn_body.hh.
Referenced by compute_ref_point_transform(), DynBody(), propagate_state(), jeod::StructureIntegratedDynBody::StructureIntegratedDynBody(), switch_integration_frames(), and update_integrated_state().
mass
MassBody jeod::DynBody::mass
Mass properties of the vehicle, defined about the structure reference frame.
Definition at line 658 of file dyn_body.hh.
Referenced by jeod::DynManager::add_dyn_body(), add_mass_body(), add_mass_point(), attach_child(), attach_establish_links(), attach_to_frame(), attach_update_properties(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), compute_vehicle_point_derivatives(), detach(), detach_mass_internal(), DynBody(), jeod::DynManager::initialize_dyn_bodies(), jeod::DynManager::initialize_dyn_body(), initialize_model(), jeod::BodyAction::is_same_subject_body(), jeod::DynManager::perform_dyn_body_initializations(), process_dynamic_attachment(), propagate_state_from_composite(), propagate_state_from_structure(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), remove_mass_body(), set_name(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::GravityTorque::update(), and jeod::BodyAction::validate_body_inputs().
mass_children
std::list<MassBody*> jeod::DynBody::mass_children protected
The subset of the mass bodies attached to this dynamic body that are themselves not dynamic bodies.
Definition at line 1181 of file dyn_body.hh.
Referenced by add_mass_body(), remove_mass_body(), and ~DynBody().
name
NamedItem& jeod::DynBody::name
Body name, reference linked to mass.name.
trick_units(–)
Definition at line 663 of file dyn_body.hh.
Referenced by jeod::DynManager::add_dyn_body(), jeod::DynamicsIntegrationGroup::add_dyn_body(), add_mass_body(), add_mass_body_frames(), add_mass_body_validate(), add_mass_point(), jeod::DynBodyInitNedState::apply(), jeod::BodyDetachSpecific::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::BodyAttach::apply(), attach_child(), jeod::StructureIntegratedDynBody::attach_update_properties(), attach_validate_child(), attach_validate_parent(), jeod::DynManager::check_for_uninitialized_states(), jeod::check_frame_ownership(), compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), compute_vehicle_point_derivatives(), create_body_integrators(), jeod::DynamicsIntegrationGroup::delete_dyn_body(), jeod::StructureIntegratedDynBody::detach(), detach(), jeod::DynBodyInit::find_body_frame(), find_body_frame(), jeod::DynManager::find_dyn_body(), find_vehicle_point(), jeod::LvlhDerivedState::initialize(), jeod::DerivedState::initialize(), jeod::OrbElemDerivedState::initialize(), jeod::NedDerivedState::initialize(), jeod::DynBodyInit::initialize(), initialize_model(), jeod::PropagatedPlanet::initialize_model(), migrate_integrable_objects(), propagate_state(), remove_mass_body(), set_integ_frame(), jeod::StructureIntegratedDynBody::set_solver(), set_state_source(), and switch_integration_frames().
position_source
BodyRefFrame* jeod::DynBody::position_source protected
The reference frame that contains the user-set position.
trick_units(–)
Definition at line 1197 of file dyn_body.hh.
Referenced by set_state_source_internal(), and update_integrated_state().
rate_source
BodyRefFrame* jeod::DynBody::rate_source protected
The reference frame that contains the user-set attitude rate.
trick_units(–)
Definition at line 1212 of file dyn_body.hh.
Referenced by set_state_source_internal(), and update_integrated_state().
rot_integrator
RestartableSO3SecondOrderODEIntegrator jeod::DynBody::rot_integrator protected
Rotational state checkpointable/restartable integrator generator.
Rotational state is much harder to integrate. The canonical position is the attitude quaternion, canonical velocity is angular velocity, and the time derivative of the attitude quaternion is a function of the orientiation and the angular velocity.trick_units(–)
Definition at line 1248 of file dyn_body.hh.
Referenced by create_body_integrators(), DynBody(), reset_integrators(), jeod::StructureIntegratedDynBody::rot_integ(), rot_integ(), and ~DynBody().
rotation_integration
GeneralizedSecondOrderODETechnique::TechniqueType jeod::DynBody::rotation_integration
Specifies the preferred mechanism for integrating rotational state.
This data member has effect only when set prior to the creation of the body's integrators. The body's rotational integrator will be created based on the value of this data member.trick_units(–)
Definition at line 752 of file dyn_body.hh.
Referenced by create_body_integrators().
rotational_dynamics
bool jeod::DynBody::rotational_dynamics
Is rotational dynamics enabled? The body's rotational state is integrated only if this member is true.
Setting this member to false indicates the responsibility for updating the rotational state is performed elsewhere, such as by a user-defined forced rotation model.trick_units(–)
Definition at line 723 of file dyn_body.hh.
Referenced by jeod::DynManager::check_for_uninitialized_states(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::collect_local_forces_and_torques(), jeod::PropagatedPlanet::ephem_activate(), integrate(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), reset_integrators(), and jeod::StructureIntegratedDynBody::solve_constraints().
structure
BodyRefFrame jeod::DynBody::structure
Vehicle structural reference frame.
The reference frame origin is at the structural origin, and the reference frame axes are the structure frame axes as defined in the composite mass properties.trick_units(–)
Definition at line 705 of file dyn_body.hh.
Referenced by attach_to_frame(), attach_update_properties(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), compute_vehicle_point_states(), DynBody(), initialize_model(), integrate(), process_dynamic_attachment(), propagate_state(), propagate_state_from_composite(), propagate_state_from_structure(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::StructureIntegratedDynBody::rot_integ(), set_integ_frame(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::StructureIntegratedDynBody::StructureIntegratedDynBody(), jeod::StructureIntegratedDynBody::trans_integ(), and ~DynBody().
three_dof
bool jeod::DynBody::three_dof
Is this a three degrees of freedom (translation only) body? This data member has effect only when set prior to the creation of the body's integrators.
The body's rotational integrator is not created and rotational_dynamics is set to false if this member's value is true.
Note that very bad mojo (a core dump) will result if this member is set to true at initialization time and rotational_dynamics is later enabled during run time.trick_units(–)
Definition at line 743 of file dyn_body.hh.
Referenced by create_body_integrators().
time_manager
const JeodIntegrationTime* jeod::DynBody::time_manager protected
The time manager to be used to obtain timestamp information.
trick_units(–)
Definition at line 1154 of file dyn_body.hh.
Referenced by create_body_integrators(), and update_integrated_state().
trans_integrator
RestartableT3SecondOrderODEIntegrator jeod::DynBody::trans_integrator protected
Translational state checkpointable/restartable integrator generator.
Translational state is comparatively easy to integrate. The canonical position is just position, canonical velocity is just velocity, and the time derivative of position is velocity.trick_units(–)
Definition at line 1239 of file dyn_body.hh.
Referenced by create_body_integrators(), DynBody(), reset_integrators(), jeod::StructureIntegratedDynBody::trans_integ(), trans_integ(), and ~DynBody().
translational_dynamics
bool jeod::DynBody::translational_dynamics
Is translational dynamics enabled? The body's translational state is integrated only if this member is true.
Setting this member to false indicates the responsibility for updating the translational state is performed elsewhere, such as by a user-defined forced translation model.trick_units(–)
Definition at line 714 of file dyn_body.hh.
Referenced by jeod::DynManager::check_for_uninitialized_states(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), collect_forces_and_torques(), jeod::StructureIntegratedDynBody::collect_local_forces_and_torques(), jeod::PropagatedPlanet::ephem_activate(), integrate(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), reset_integrators(), and jeod::StructureIntegratedDynBody::solve_constraints().
vehicle_points
std::list<BodyRefFrame*> jeod::DynBody::vehicle_points protected
An array of vehicle points associated with this dynamic body.
Definition at line 1186 of file dyn_body.hh.
Referenced by add_mass_body_frames(), add_mass_point(), compute_vehicle_point_states(), detach_mass_body_frames(), find_vehicle_point(), set_integ_frame(), and ~DynBody().
velocity_source
BodyRefFrame* jeod::DynBody::velocity_source protected
The reference frame that contains the user-set velocity.
trick_units(–)
Definition at line 1202 of file dyn_body.hh.
Referenced by set_state_source_internal(), and update_integrated_state().
The documentation for this class was generated from the following files:
dyn_body.hh
dyn_body.cc
dyn_body_attach.cc
dyn_body_collect.cc
dyn_body_detach.cc
dyn_body_find_body_frame.cc
dyn_body_initialize_model.cc
dyn_body_integration.cc
dyn_body_propagate_state.cc
dyn_body_set_state.cc
dyn_body_vehicle_point.cc