JEOD: jeod::GaussJacksonCoeffs Class Reference
jeod::GaussJacksonCoeffs Class Reference
Contains the Gauss-Jackson predictor and corrector coefficients.
#include <gauss_jackson_coeffs.hh>
Public Member Functions
GaussJacksonCoeffs ()=default
Default constructor.
GaussJacksonCoeffs (const GaussJacksonCoeffs &src)
Copy constructor.
~GaussJacksonCoeffs ()
Destructor.
GaussJacksonCoeffs & operator= (GaussJacksonCoeffs src)
Copy-and-swap assignment operator.
void swap (GaussJacksonCoeffs &src)
Non-throwing swap.
void configure (unsigned int max_order_in)
Configure to enable coefficients up to the specified maximum order.
void compute_coeffs (unsigned int order_in)
Compute coefficients for the specified order.
Data Fields
GaussJacksonCoefficientsPair predictor
Summed Adams and Gauss-Jackson predictor coefficients.
GaussJacksonCoefficientsPair * corrector {}
Summed Adams and Gauss-Jackson corrector coefficients.
unsigned int max_order {}
Maximum order; used for sizing.
unsigned int order {}
Current order; dictates the coefficient values.
Friends
class InputProcessor
void init_attrjeod__GaussJacksonCoeffs ()
std::ostream & operator<< (std::ostream &stream, const GaussJacksonCoeffs &coeff)
Print the coefficients.
Detailed Description
Contains the Gauss-Jackson predictor and corrector coefficients.
Definition at line 77 of file gauss_jackson_coeffs.hh.
Constructor & Destructor Documentation
GaussJacksonCoeffs() [1/2]
jeod::GaussJacksonCoeffs::GaussJacksonCoeffs () default
Default constructor.
GaussJacksonCoeffs() [2/2]
jeod::GaussJacksonCoeffs::GaussJacksonCoeffs (const GaussJacksonCoeffs & src) inline
Copy constructor.
Note that this doesn't copy; it recomputes. The end result is as if a copy had been made.
Parameters
src Object to be copied.
Definition at line 115 of file gauss_jackson_coeffs.hh.
References compute_coeffs(), configure(), max_order, and order.
~GaussJacksonCoeffs()
jeod::GaussJacksonCoeffs::~GaussJacksonCoeffs ()
Destructor.
Definition at line 43 of file gauss_jackson_coeffs.cc.
References corrector.
Member Function Documentation
compute_coeffs()
void jeod::GaussJacksonCoeffs::compute_coeffs (unsigned int order_in)
Compute coefficients for the specified order.
Parameters
order_in The current order.
Definition at line 75 of file gauss_jackson_coeffs.cc.
References jeod::GaussJacksonRationalCoefficients::configure_adams_corrector(), jeod::GaussJacksonRationalCoefficients::construct_predictor(), jeod::GaussJacksonRationalCoefficients::construct_stormer_cowell_corrector(), jeod::GaussJacksonRationalCoefficients::convert_to_ordinate_form(), corrector, jeod::GaussJacksonRationalCoefficients::discard_extra_terms(), jeod::GaussJacksonRationalCoefficients::displace_back(), jeod::GaussJacksonCoefficientsPair::gj_coefs, max_order, order, predictor, and jeod::GaussJacksonCoefficientsPair::sa_coefs.
Referenced by GaussJacksonCoeffs(), jeod::GaussJacksonIntegrationControls::GaussJacksonIntegrationControls(), and jeod::GaussJacksonIntegrationControls::start_cycle().
configure()
void jeod::GaussJacksonCoeffs::configure (unsigned int max_order_in)
Configure to enable coefficients up to the specified maximum order.
Parameters
max_order_in The maximum order to be used.
Definition at line 58 of file gauss_jackson_coeffs.cc.
References jeod::GaussJacksonCoefficientsPair::configure(), corrector, max_order, order, and predictor.
Referenced by GaussJacksonCoeffs(), and jeod::GaussJacksonIntegrationControls::GaussJacksonIntegrationControls().
operator=()
GaussJacksonCoeffs& jeod::GaussJacksonCoeffs::operator= (GaussJacksonCoeffs src) inline
Copy-and-swap assignment operator.
Parameters
src Object to be copied.
Definition at line 137 of file gauss_jackson_coeffs.hh.
References swap().
swap()
void jeod::GaussJacksonCoeffs::swap (GaussJacksonCoeffs & src)
Non-throwing swap.
Parameters
src Object to swap contents with.
Definition at line 49 of file gauss_jackson_coeffs.cc.
References corrector, max_order, order, predictor, and jeod::GaussJacksonCoefficientsPair::swap().
Referenced by operator=().
Friends And Related Function Documentation
init_attrjeod__GaussJacksonCoeffs
void init_attrjeod__GaussJacksonCoeffs () friend
InputProcessor
friend class InputProcessor friend
Definition at line 79 of file gauss_jackson_coeffs.hh.
operator<<
std::ostream& operator<< (std::ostream & stream, const GaussJacksonCoeffs & coeff) friend
Print the coefficients.
Parameters
stream The stream to be printed to.
coeff The coefficients to be printed.
Definition at line 130 of file gauss_jackson_coeffs.cc.
Field Documentation
corrector
GaussJacksonCoefficientsPair* jeod::GaussJacksonCoeffs::corrector {}
Summed Adams and Gauss-Jackson corrector coefficients.
trick_units(–)
Definition at line 90 of file gauss_jackson_coeffs.hh.
Referenced by compute_coeffs(), configure(), jeod::GaussJacksonIntegratorBase< State, Primer >::integrate_gj(), jeod::operator<<(), jeod::GaussJacksonIntegratorBase< State, Primer >::start_cycle(), swap(), and ~GaussJacksonCoeffs().
max_order
unsigned int jeod::GaussJacksonCoeffs::max_order {}
Maximum order; used for sizing.
trick_units(–)
Definition at line 95 of file gauss_jackson_coeffs.hh.
Referenced by compute_coeffs(), configure(), GaussJacksonCoeffs(), and swap().
order
unsigned int jeod::GaussJacksonCoeffs::order {}
Current order; dictates the coefficient values.
trick_units(–)
Definition at line 100 of file gauss_jackson_coeffs.hh.
Referenced by compute_coeffs(), configure(), GaussJacksonCoeffs(), jeod::operator<<(), and swap().
predictor
GaussJacksonCoefficientsPair jeod::GaussJacksonCoeffs::predictor
Summed Adams and Gauss-Jackson predictor coefficients.
trick_units(–)
Definition at line 85 of file gauss_jackson_coeffs.hh.
Referenced by compute_coeffs(), configure(), jeod::operator<<(), and swap().
The documentation for this class was generated from the following files:
gauss_jackson_coeffs.hh
gauss_jackson_coeffs.cc