JEOD: jeod::DynBodyConstraintsSolver Class Reference
jeod::DynBodyConstraintsSolver Class Reference
Builds and then solves a system of linear equations that describe the linear constraint forces and torques that act on a vehicle.
#include <dyn_body_constraints_solver.hh>
Public Types
typedef JeodPointerVector< DynBodyConstraintsSolver >::type SolverVectorT
Vector of pointers to DynBodyConstraintsSolver objects.
typedef JeodPointerVector< DynBodyConstraint >::type ConstraintsVectorT
Vector of pointers to DynBodyConstraint objects.
typedef JeodPrimitiveVector< double >::type DoubleVectorT
Vector of doubles.
typedef std::pair< unsigned, unsigned > IndexPairT
Pairs of unsigned integers, as indices.
typedef JeodObjectVector< IndexPairT >::type IndexPairVectorT
Vector of pairs of unsigned integers.
Public Member Functions
DynBodyConstraintsSolver ()
Default constructor, for internal (Trick and JEOD) use only.
DynBodyConstraintsSolver (LinearSystemSolver &solver_, StructureIntegratedDynBody &dyn_body_)
Non-default constructor.
~DynBodyConstraintsSolver ()
Destructor.
void add_constraint (DynBodyConstraint *constraint)
Add the specified constraint to the constraints vectors.
void remove_constraint (DynBodyConstraint *constraint)
Remove the specified constraint from the constraints vectors.
bool is_registered (const DynBodyConstraint *constraint) const
Check whether the constraint has been registered.
bool is_active (const DynBodyConstraint *constraint) const
Check whether the constraint is active.
void collect_collected_constraints ()
Add the collect_constraints to the constraints owned by this object.
SolverTypes::DecayedVector3T transform_direction_to_root (SolverTypes::ConstVector3T direction, SolverTypes::Vector3T root_direction) const
Transform a direction expressed in local structural coordinates to the root structural frame.
SolverTypes::DecayedVector3T transform_point_to_root (SolverTypes::ConstVector3T point, SolverTypes::Vector3T root_point) const
Transform a position expressed in local structural coordinates to the root structural frame.
SolverTypes::ConstMatrix3x3RefT transform_matrix_from_root (SolverTypes::ConstMatrix3x3RefT this_to_frame_transform, SolverTypes::Matrix3x3RefT root_to_frame_transform) const
Transform a transformation matrix that transforms from local structural coordinates to some other frame to a transformation matrix that transforms from the root structural frame to that other frame.
SolverTypes::ConstMatrix3x3RefT get_root_to_struct_transform () const
Get the root structural to local structural transformation matrix.
SolverTypes::ConstDecayedVector3T get_root_to_struct_offset () const
Get the location of the local structural origin in root structural coordinates.
Data Fields
ConstraintsVectorT collect_constraints
Vector of pointers to wrench constraints.
Private Member Functions
DynBodyConstraintsSolver (LinearSystemSolver *solver_, DynBody *dyn_body_)
Non-default constructor, for internal use only.
void attach (DynBodyConstraintsSolver &new_parent, const VehicleProperties &vehicle_properties)
Callback for a DynBody that has attached to another.
void detach (const VehicleProperties &vehicle_properties)
Callback for a DynBody that has detached from a parent DynBody.
void reattach (const VehicleProperties &vehicle_properties)
Callback for a DynBody that has adjusted its attach point/orientation with respect to a parent DynBody.
void solve (const VehicleProperties &vehicle_properties, VehicleNonGravState &non_grav_state)
Solve for the constraints.
void activate_constraint (DynBodyConstraint *constraint)
DynBodyConstraint activate callback to mark the constraint as active.
void deactivate_constraint (DynBodyConstraint *constraint)
DynBodyConstraint deactivate callback to mark the constraint as inactive.
DynBody * get_dyn_body ()
Get the dyn_body object associated with this solver.
bool is_ours (const DynBodyConstraint *constraint) const
Check whether the constraint belongs directly to this solver.
void add_child_constraint (DynBodyConstraint *constraint)
Add the specified constraint to inherited constraints vectors.
void remove_child_constraint (DynBodyConstraint *constraint)
Remove the specified constraint from inherited constraints vectors.
void add_attached_constraints (const ConstraintsVectorT &new_inherited_constraints, const ConstraintsVectorT &new_active_constraints)
Add constraints inherited from a newly attached solver to this object's constraints.
void compute_root_to_this (const VehicleProperties &vehicle_properties)
Compute the transformation and offset from the root to the this, and also for all children.
void update_vehicle_response (const Wrench &sum, const VehicleProperties &vehicle_properties, VehicleNonGravState &non_grav_state)
Updates the vehicle's response to sn accumulated wrench.
void build_system_of_equations (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state, unsigned n_constraints, IndexPairVectorT &constraint_indices)
Build the system of linear equations A*x = b, where each row corresponds to a specific constraint.
void send_solution (unsigned n_constraints, const IndexPairVectorT &constraint_indices)
Tell each active constrained object the solution for that constraint.
void compute_constraint_responses (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Compute the constrained objects' responses to the constraints.
DynBodyConstraintsSolver (const DynBodyConstraintsSolver &)
DynBodyConstraintsSolver & operator= (const DynBodyConstraintsSolver &)
Private Attributes
DynBody * dyn_body
The DynBody object associated with this solver.
LinearSystemSolver * solver
The object used to solve the constraints.
DoubleVectorT x_vector
Vector of constraint values.
DynBodyConstraintsSolver * parent
The solver associated with the parent DynBody object.
DynBodyConstraintsSolver * root_solver
The solver associated with the root DynBody object.
SolverVectorT children
The solvers associated with child DynBody objects.
ConstraintsVectorT own_constraints
Vector of pointers to the registered wrench constraints for this DynBody object.
ConstraintsVectorT child_constraints
Vector of pointers to the registered wrench constraints for child DynBody objects.
ConstraintsVectorT all_constraints
Vector of pointers to the registered wrench constraints for this DynBody and child DynBody objects.
ConstraintsVectorT active_constraints
Vector of pointers to the active wrench constraints.
IndexPairVectorT constraint_indices
Vector of begin, end pairs of row indices for each active constraint.
Wrench effector_wrench
The sum of the individual constraint's effector wrenches.
Wrench constraints_wrench
The sum of the individual constraint's constraint wrenches.
Wrench nonlinear_responses_wrench
The sum of the individual constraint's nonlinear response wrenches.
double root_to_this_transform [3][3]
The transformation matrix from the root DynBody object's structural frame to the DynBody object immediately associated with this solver.
double root_to_this_offset [3]
The origin of the structural frame of the DynBody object immediately associated with this solver, in root DynBody structural coordinates.
Friends
class InputProcessor
class DynBodyConstraint
class StructureIntegratedDynBody
void init_attrjeod__DynBodyConstraintsSolver ()
Detailed Description
Builds and then solves a system of linear equations that describe the linear constraint forces and torques that act on a vehicle.
Definition at line 82 of file dyn_body_constraints_solver.hh.
Member Typedef Documentation
ConstraintsVectorT
typedef JeodPointerVector<DynBodyConstraint>::type jeod::DynBodyConstraintsSolver::ConstraintsVectorT
Vector of pointers to DynBodyConstraint objects.
Definition at line 101 of file dyn_body_constraints_solver.hh.
DoubleVectorT
typedef JeodPrimitiveVector<double>::type jeod::DynBodyConstraintsSolver::DoubleVectorT
Vector of doubles.
Definition at line 106 of file dyn_body_constraints_solver.hh.
IndexPairT
typedef std::pair<unsigned, unsigned> jeod::DynBodyConstraintsSolver::IndexPairT
Pairs of unsigned integers, as indices.
Definition at line 111 of file dyn_body_constraints_solver.hh.
IndexPairVectorT
typedef JeodObjectVector<IndexPairT>::type jeod::DynBodyConstraintsSolver::IndexPairVectorT
Vector of pairs of unsigned integers.
Definition at line 116 of file dyn_body_constraints_solver.hh.
SolverVectorT
typedef JeodPointerVector<DynBodyConstraintsSolver>::type jeod::DynBodyConstraintsSolver::SolverVectorT
Vector of pointers to DynBodyConstraintsSolver objects.
Definition at line 96 of file dyn_body_constraints_solver.hh.
Constructor & Destructor Documentation
DynBodyConstraintsSolver() [1/4]
jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver () inline
Default constructor, for internal (Trick and JEOD) use only.
Definition at line 154 of file dyn_body_constraints_solver.hh.
DynBodyConstraintsSolver() [2/4]
jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver (LinearSystemSolver & solver_, StructureIntegratedDynBody & dyn_body_)
Non-default constructor.
Parameters
solver_ The linear system of equations solver to be used to solve the constraints equation.
dyn_body_ The DynBody associated with this constraints solver.
Definition at line 154 of file dyn_body_constraints_solver.cc.
References jeod::StructureIntegratedDynBody::set_solver().
~DynBodyConstraintsSolver()
jeod::DynBodyConstraintsSolver::~DynBodyConstraintsSolver ()
Destructor.
Definition at line 192 of file dyn_body_constraints_solver.cc.
References active_constraints, all_constraints, child_constraints, JEOD_DEREGISTER_CHECKPOINTABLE, and own_constraints.
DynBodyConstraintsSolver() [3/4]
jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver (LinearSystemSolver * solver_, DynBody * dyn_body_) private
Non-default constructor, for internal use only.
Parameters
solver_ The linear system of equations solver to be used to solve the constraints equation.
dyn_body_ The DynBody associated with this constraints solver.
Definition at line 165 of file dyn_body_constraints_solver.cc.
References active_constraints, all_constraints, child_constraints, jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_CLASS, own_constraints, root_to_this_offset, and root_to_this_transform.
DynBodyConstraintsSolver() [4/4]
jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver (const DynBodyConstraintsSolver &) private
Member Function Documentation
activate_constraint()
void jeod::DynBodyConstraintsSolver::activate_constraint (DynBodyConstraint * constraint) private
DynBodyConstraint activate callback to mark the constraint as active.
Parameters
constraint Constraint to be marked as active.
Definition at line 324 of file dyn_body_constraints_solver.cc.
References activate_constraint(), active_constraints, FAIL_SIMULATION, is_active(), is_registered(), and parent.
Referenced by jeod::DynBodyConstraint::activate(), activate_constraint(), and add_child_constraint().
add_attached_constraints()
void jeod::DynBodyConstraintsSolver::add_attached_constraints (const ConstraintsVectorT & new_inherited_constraints, const ConstraintsVectorT & new_active_constraints) private
Add constraints inherited from a newly attached solver to this object's constraints.
Parameters
new_inherited_constraints Items to be added to all_constraints.
new_active_constraints Items to be added to active_constraints.
Definition at line 496 of file dyn_body_constraints_solver.cc.
References active_constraints, and all_constraints.
Referenced by attach().
add_child_constraint()
void jeod::DynBodyConstraintsSolver::add_child_constraint (DynBodyConstraint * constraint) private
Add the specified constraint to inherited constraints vectors.
Parameters
constraint Constraint to be added.
Definition at line 259 of file dyn_body_constraints_solver.cc.
References activate_constraint(), add_child_constraint(), all_constraints, FAIL_SIMULATION, jeod::DynBodyConstraint::is_active(), is_registered(), and parent.
Referenced by add_child_constraint(), and add_constraint().
add_constraint()
void jeod::DynBodyConstraintsSolver::add_constraint (DynBodyConstraint * constraint)
Add the specified constraint to the constraints vectors.
Parameters
constraint Constraint to be added.
Definition at line 238 of file dyn_body_constraints_solver.cc.
References add_child_constraint(), FAIL_SIMULATION, is_ours(), own_constraints, and jeod::DynBodyConstraint::set_solver().
Referenced by jeod::StructureIntegratedDynBody::add_constraint(), and collect_collected_constraints().
attach()
void jeod::DynBodyConstraintsSolver::attach (DynBodyConstraintsSolver & new_parent, const VehicleProperties & vehicle_properties) private
Callback for a DynBody that has attached to another.
Parameters
new_parent The constraints solver for the parent DynBody of the DynBody associated with this solver.
vehicle_properties The child body's vehicle_properties object.
Definition at line 466 of file dyn_body_constraints_solver.cc.
References active_constraints, add_attached_constraints(), all_constraints, compute_root_to_this(), FAIL_SIMULATION, parent, and root_solver.
Referenced by jeod::StructureIntegratedDynBody::attach_update_properties().
build_system_of_equations()
void jeod::DynBodyConstraintsSolver::build_system_of_equations (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state, unsigned n_constraints, IndexPairVectorT & constraint_indices) private
Build the system of linear equations A*x = b, where each row corresponds to a specific constraint.
Parameters
vehicle_properties Properites of the vehicle
non_grav_state Non-gravitational state in structural coordinates.
n_constraints The number of active constraints.
constraint_indices Active constraints start and end indices.
Definition at line 625 of file dyn_body_constraints_solver.cc.
References active_constraints, constraint_indices, jeod::LinearSystemSolver::make_a_matrix_view(), jeod::LinearSystemSolver::make_b_vector_view(), jeod::LinearSystemSolver::set_n_dimensions(), solver, and x_vector.
Referenced by solve().
collect_collected_constraints()
void jeod::DynBodyConstraintsSolver::collect_collected_constraints ()
Add the collect_constraints to the constraints owned by this object.
Definition at line 375 of file dyn_body_constraints_solver.cc.
References add_constraint(), and collect_constraints.
compute_constraint_responses()
void jeod::DynBodyConstraintsSolver::compute_constraint_responses (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) private
Compute the constrained objects' responses to the constraints.
Parameters
vehicle_properties Properites of the vehicle
non_grav_state Non-gravitational state in structural coordinates, updated to include the constraints.
Definition at line 762 of file dyn_body_constraints_solver.cc.
References active_constraints.
Referenced by solve().
compute_root_to_this()
void jeod::DynBodyConstraintsSolver::compute_root_to_this (const VehicleProperties & vehicle_properties) private
Compute the transformation and offset from the root to the this, and also for all children.
Definition at line 387 of file dyn_body_constraints_solver.cc.
References children, jeod::Matrix3x3::copy(), jeod::VehicleProperties::get_parent_to_structure_offset(), jeod::VehicleProperties::get_parent_to_structure_transform(), jeod::Matrix3x3::identity(), jeod::Vector3::incr(), jeod::Vector3::initialize(), own_constraints, parent, jeod::Matrix3x3::product(), root_to_this_offset, root_to_this_transform, jeod::Vector3::sum(), and jeod::Vector3::transform_transpose().
Referenced by attach(), detach(), and reattach().
deactivate_constraint()
void jeod::DynBodyConstraintsSolver::deactivate_constraint (DynBodyConstraint * constraint) private
DynBodyConstraint deactivate callback to mark the constraint as inactive.
Parameters
constraint Constraint to be marked as inactive.
Definition at line 350 of file dyn_body_constraints_solver.cc.
References active_constraints, deactivate_constraint(), FAIL_SIMULATION, is_registered(), parent, and jeod::remove_element().
Referenced by jeod::DynBodyConstraint::deactivate(), deactivate_constraint(), and remove_child_constraint().
detach()
void jeod::DynBodyConstraintsSolver::detach (const VehicleProperties & vehicle_properties) private
Callback for a DynBody that has detached from a parent DynBody.
Definition at line 525 of file dyn_body_constraints_solver.cc.
References all_constraints, children, compute_root_to_this(), FAIL_SIMULATION, parent, remove_child_constraint(), jeod::remove_element(), and root_solver.
Referenced by jeod::StructureIntegratedDynBody::detach().
get_dyn_body()
DynBody* jeod::DynBodyConstraintsSolver::get_dyn_body () inline private
Get the dyn_body object associated with this solver.
Returns
The dyn_body object for this solver.
Definition at line 428 of file dyn_body_constraints_solver.hh.
References dyn_body.
Referenced by jeod::DynBodyConstraint::attach_to_solver(), jeod::DynBodyConstraint::detach_from_solver(), and jeod::DynBodyConstraint::get_dyn_body().
get_root_to_struct_offset()
SolverTypes::ConstDecayedVector3T jeod::DynBodyConstraintsSolver::get_root_to_struct_offset () const inline
Get the location of the local structural origin in root structural coordinates.
Returns
root_to_this_offset.
Definition at line 258 of file dyn_body_constraints_solver.hh.
References root_to_this_offset.
Referenced by jeod::ConstraintFrame::update_root_to_constraint_frame().
get_root_to_struct_transform()
SolverTypes::ConstMatrix3x3RefT jeod::DynBodyConstraintsSolver::get_root_to_struct_transform () const inline
Get the root structural to local structural transformation matrix.
Returns
root_to_this_transform.
Definition at line 248 of file dyn_body_constraints_solver.hh.
References root_to_this_transform.
Referenced by jeod::ConstraintFrame::update_root_to_constraint_frame().
is_active()
bool jeod::DynBodyConstraintsSolver::is_active (const DynBodyConstraint * constraint) const
Check whether the constraint is active.
Parameters
constraint Constraint to be tested.
Definition at line 229 of file dyn_body_constraints_solver.cc.
References active_constraints, and jeod::is_in_container().
Referenced by activate_constraint().
is_ours()
bool jeod::DynBodyConstraintsSolver::is_ours (const DynBodyConstraint * constraint) const private
Check whether the constraint belongs directly to this solver.
Parameters
constraint Constraint to be tested.
Definition at line 220 of file dyn_body_constraints_solver.cc.
References jeod::is_in_container(), and own_constraints.
Referenced by add_constraint().
is_registered()
bool jeod::DynBodyConstraintsSolver::is_registered (const DynBodyConstraint * constraint) const
Check whether the constraint has been registered.
Parameters
constraint Constraint to be tested.
Definition at line 211 of file dyn_body_constraints_solver.cc.
References all_constraints, and jeod::is_in_container().
Referenced by activate_constraint(), add_child_constraint(), and deactivate_constraint().
operator=()
DynBodyConstraintsSolver& jeod::DynBodyConstraintsSolver::operator= (const DynBodyConstraintsSolver &) private
reattach()
void jeod::DynBodyConstraintsSolver::reattach (const VehicleProperties & vehicle_properties) private
Callback for a DynBody that has adjusted its attach point/orientation with respect to a parent DynBody.
Note
This is a future hook; The MassBody reattach function is not virtual and hence can't be overridden by DynBody.
Definition at line 516 of file dyn_body_constraints_solver.cc.
References compute_root_to_this().
remove_child_constraint()
void jeod::DynBodyConstraintsSolver::remove_child_constraint (DynBodyConstraint * constraint) private
Remove the specified constraint from inherited constraints vectors.
Parameters
constraint Constraint to be removed.
Definition at line 302 of file dyn_body_constraints_solver.cc.
References all_constraints, deactivate_constraint(), jeod::DynBodyConstraint::is_active(), parent, remove_child_constraint(), and jeod::remove_element().
Referenced by detach(), remove_child_constraint(), and remove_constraint().
remove_constraint()
void jeod::DynBodyConstraintsSolver::remove_constraint (DynBodyConstraint * constraint)
Remove the specified constraint from the constraints vectors.
Parameters
constraint Constraint to be removed.
Definition at line 288 of file dyn_body_constraints_solver.cc.
References own_constraints, remove_child_constraint(), and jeod::remove_element().
Referenced by jeod::DynBodyConstraint::~DynBodyConstraint().
send_solution()
void jeod::DynBodyConstraintsSolver::send_solution (unsigned n_constraints, const IndexPairVectorT & constraint_indices) private
Tell each active constrained object the solution for that constraint.
Parameters
n_constraints The number of active constraints.
constraint_indices Active constraints start and end indices.
Definition at line 702 of file dyn_body_constraints_solver.cc.
References active_constraints, constraint_indices, and x_vector.
Referenced by solve().
solve()
void jeod::DynBodyConstraintsSolver::solve (const VehicleProperties & vehicle_properties, VehicleNonGravState & non_grav_state) private
Solve for the constraints.
Parameters
vehicle_properties Properites of the vehicle
non_grav_state Non-gravitational state in structural coordinates. On input, the translational and rotational acceleration reflect the response to external forces and torques. These are updated to also reflect the constraints on return.
Definition at line 558 of file dyn_body_constraints_solver.cc.
References active_constraints, build_system_of_equations(), compute_constraint_responses(), constraint_indices, constraints_wrench, effector_wrench, jeod::DynBodyConstraint::get_constraint_wrench(), jeod::DynBodyConstraint::get_effector_wrench(), jeod::DynBodyConstraint::get_nonlinear_response_wrench(), jeod::VehicleProperties::get_structure_to_body_offset(), nonlinear_responses_wrench, send_solution(), jeod::LinearSystemSolver::solve(), solver, update_vehicle_response(), and x_vector.
Referenced by jeod::StructureIntegratedDynBody::solve_constraints().
transform_direction_to_root()
SolverTypes::DecayedVector3T jeod::DynBodyConstraintsSolver::transform_direction_to_root (SolverTypes::ConstVector3T direction, SolverTypes::Vector3T root_direction) const
Transform a direction expressed in local structural coordinates to the root structural frame.
Parameters
direction Input direction.
root_direction The transformed direction.
Returns
root_direction.
Definition at line 432 of file dyn_body_constraints_solver.cc.
References root_to_this_transform, and jeod::Vector3::transform_transpose().
Referenced by transform_point_to_root().
transform_matrix_from_root()
SolverTypes::ConstMatrix3x3RefT jeod::DynBodyConstraintsSolver::transform_matrix_from_root (SolverTypes::ConstMatrix3x3RefT this_to_frame_transform, SolverTypes::Matrix3x3RefT root_to_frame_transform) const
Transform a transformation matrix that transforms from local structural coordinates to some other frame to a transformation matrix that transforms from the root structural frame to that other frame.
Parameters
this_to_frame_transform Input transformation matrix.
root_to_frame_transform The transformed transformation matrix.
Returns
root_to_frame_transform.
Definition at line 453 of file dyn_body_constraints_solver.cc.
References jeod::Matrix3x3::product(), and root_to_this_transform.
transform_point_to_root()
SolverTypes::DecayedVector3T jeod::DynBodyConstraintsSolver::transform_point_to_root (SolverTypes::ConstVector3T point, SolverTypes::Vector3T root_point) const
Transform a position expressed in local structural coordinates to the root structural frame.
Parameters
point Input position.
root_point The transformed position.
Returns
root_point.
Definition at line 442 of file dyn_body_constraints_solver.cc.
References jeod::Vector3::incr(), root_to_this_offset, and transform_direction_to_root().
update_vehicle_response()
void jeod::DynBodyConstraintsSolver::update_vehicle_response (const Wrench & sum, const VehicleProperties & vehicle_properties, VehicleNonGravState & non_grav_state) private
Updates the vehicle's response to sn accumulated wrench.
Parameters
sum The accumulated value of the calls to get_wrench.
vehicle_properties Properites of the vehicle
non_grav_state Non-gravitational state in structural coordinates, which is updated to reflect the accumulated wrench on return.
Definition at line 721 of file dyn_body_constraints_solver.cc.
References jeod::VehicleNonGravState::accel_struct, jeod::Wrench::get_force(), jeod::VehicleProperties::get_inverse_inertia(), jeod::VehicleProperties::get_inverse_mass(), jeod::VehicleProperties::get_structure_to_body_offset(), jeod::VehicleProperties::get_structure_to_body_transform(), jeod::Wrench::get_torque(), jeod::VehicleNonGravState::omega_dot_body, jeod::VehicleNonGravState::omega_dot_struct, jeod::Vector3::scale_incr(), jeod::Vector3::transform(), jeod::Vector3::transform_incr(), jeod::Wrench::transform_to_point(), and jeod::Vector3::transform_transpose().
Referenced by solve().
Friends And Related Function Documentation
DynBodyConstraint
friend class DynBodyConstraint friend
Definition at line 86 of file dyn_body_constraints_solver.hh.
init_attrjeod__DynBodyConstraintsSolver
void init_attrjeod__DynBodyConstraintsSolver () friend
InputProcessor
friend class InputProcessor friend
Definition at line 84 of file dyn_body_constraints_solver.hh.
StructureIntegratedDynBody
friend class StructureIntegratedDynBody friend
Definition at line 87 of file dyn_body_constraints_solver.hh.
Field Documentation
active_constraints
ConstraintsVectorT jeod::DynBodyConstraintsSolver::active_constraints private
Vector of pointers to the active wrench constraints.
trick_io(**)
Definition at line 321 of file dyn_body_constraints_solver.hh.
Referenced by activate_constraint(), add_attached_constraints(), attach(), build_system_of_equations(), compute_constraint_responses(), deactivate_constraint(), DynBodyConstraintsSolver(), is_active(), send_solution(), solve(), and ~DynBodyConstraintsSolver().
all_constraints
ConstraintsVectorT jeod::DynBodyConstraintsSolver::all_constraints private
Vector of pointers to the registered wrench constraints for this DynBody and child DynBody objects.
trick_io(**)
Definition at line 316 of file dyn_body_constraints_solver.hh.
Referenced by add_attached_constraints(), add_child_constraint(), attach(), detach(), DynBodyConstraintsSolver(), is_registered(), remove_child_constraint(), and ~DynBodyConstraintsSolver().
child_constraints
ConstraintsVectorT jeod::DynBodyConstraintsSolver::child_constraints private
Vector of pointers to the registered wrench constraints for child DynBody objects.
trick_io(**)
Definition at line 310 of file dyn_body_constraints_solver.hh.
Referenced by DynBodyConstraintsSolver(), and ~DynBodyConstraintsSolver().
children
SolverVectorT jeod::DynBodyConstraintsSolver::children private
The solvers associated with child DynBody objects.
trick_units(–)
Definition at line 298 of file dyn_body_constraints_solver.hh.
Referenced by compute_root_to_this(), and detach().
collect_constraints
ConstraintsVectorT jeod::DynBodyConstraintsSolver::collect_constraints
Vector of pointers to wrench constraints.
This member is public so it can be collected. The wrench constraints are collected into the vector at the S_define level via vcollect containing.object.constraints { pointer_to_dyn_body_constraint1, ... pointer_to_dyn_body_constraint_n }; The collected constraints become registered constraints at the call to collect_collected_constraints().
Warning
Being public, elements can be added to or removed from this member, willy nilly. This is fine prior to the call to collect_collected_constraints, not so fine after that call.
Changes to this member after the call to collect_collected_constraints() have no effect.trick_io(**)
Definition at line 142 of file dyn_body_constraints_solver.hh.
Referenced by collect_collected_constraints().
constraint_indices
IndexPairVectorT jeod::DynBodyConstraintsSolver::constraint_indices private
Vector of begin, end pairs of row indices for each active constraint.
trick_io(**)
Definition at line 326 of file dyn_body_constraints_solver.hh.
Referenced by build_system_of_equations(), send_solution(), and solve().
constraints_wrench
Wrench jeod::DynBodyConstraintsSolver::constraints_wrench private
The sum of the individual constraint's constraint wrenches.
trick_units(–)
Definition at line 336 of file dyn_body_constraints_solver.hh.
Referenced by solve().
dyn_body
DynBody* jeod::DynBodyConstraintsSolver::dyn_body private
The DynBody object associated with this solver.
trick_units(–)
Definition at line 272 of file dyn_body_constraints_solver.hh.
Referenced by get_dyn_body().
effector_wrench
Wrench jeod::DynBodyConstraintsSolver::effector_wrench private
The sum of the individual constraint's effector wrenches.
trick_units(–)
Definition at line 331 of file dyn_body_constraints_solver.hh.
Referenced by solve().
nonlinear_responses_wrench
Wrench jeod::DynBodyConstraintsSolver::nonlinear_responses_wrench private
The sum of the individual constraint's nonlinear response wrenches.
trick_units(–)
Definition at line 341 of file dyn_body_constraints_solver.hh.
Referenced by solve().
own_constraints
ConstraintsVectorT jeod::DynBodyConstraintsSolver::own_constraints private
Vector of pointers to the registered wrench constraints for this DynBody object.
trick_io(**)
Definition at line 304 of file dyn_body_constraints_solver.hh.
Referenced by add_constraint(), compute_root_to_this(), DynBodyConstraintsSolver(), is_ours(), remove_constraint(), and ~DynBodyConstraintsSolver().
parent
DynBodyConstraintsSolver* jeod::DynBodyConstraintsSolver::parent private
The solver associated with the parent DynBody object.
trick_units(–)
Definition at line 288 of file dyn_body_constraints_solver.hh.
Referenced by activate_constraint(), add_child_constraint(), attach(), compute_root_to_this(), deactivate_constraint(), detach(), and remove_child_constraint().
root_solver
DynBodyConstraintsSolver* jeod::DynBodyConstraintsSolver::root_solver private
The solver associated with the root DynBody object.
trick_units(–)
Definition at line 293 of file dyn_body_constraints_solver.hh.
Referenced by attach(), and detach().
root_to_this_offset
double jeod::DynBodyConstraintsSolver::root_to_this_offset[3] private
The origin of the structural frame of the DynBody object immediately associated with this solver, in root DynBody structural coordinates.
trick_units(m)
Definition at line 353 of file dyn_body_constraints_solver.hh.
Referenced by compute_root_to_this(), DynBodyConstraintsSolver(), get_root_to_struct_offset(), and transform_point_to_root().
root_to_this_transform
double jeod::DynBodyConstraintsSolver::root_to_this_transform[3][3] private
The transformation matrix from the root DynBody object's structural frame to the DynBody object immediately associated with this solver.
trick_units(–)
Definition at line 347 of file dyn_body_constraints_solver.hh.
Referenced by compute_root_to_this(), DynBodyConstraintsSolver(), get_root_to_struct_transform(), transform_direction_to_root(), and transform_matrix_from_root().
solver
LinearSystemSolver* jeod::DynBodyConstraintsSolver::solver private
The object used to solve the constraints.
trick_units(–)
Definition at line 277 of file dyn_body_constraints_solver.hh.
Referenced by build_system_of_equations(), and solve().
x_vector
DoubleVectorT jeod::DynBodyConstraintsSolver::x_vector private
Vector of constraint values.
These are the solution to A*x = b.trick_io(**)
Definition at line 283 of file dyn_body_constraints_solver.hh.
Referenced by build_system_of_equations(), send_solution(), and solve().
The documentation for this class was generated from the following files:
dyn_body_constraints_solver.hh
dyn_body_constraints_solver.cc