JEOD: jeod::TwoDArray Class Reference
jeod::TwoDArray Class Reference
Represents a two dimensional array, implemented as a vector that is indexed as a row major two dimensional array.
#include <two_d_array.hh>
Public Types
typedef JeodPrimitiveVector< double >::type DoubleVectorT
Vector of doubles.
Public Member Functions
TwoDArray ()
Default constructor.
virtual ~TwoDArray ()
Destructor.
TwoDArray (const TwoDArray &)=default
TwoDArray & operator= (const TwoDArray &)=default
TwoDArray (TwoDArray &&)=default
TwoDArray & operator= (TwoDArray &&)=default
virtual SolverTypes::IndexPairT size () const
Size function.
void reserve (unsigned max_elems_in)
Reserve storage for at least max_elems_in elements.
void resize (unsigned n_rows_in, unsigned n_cols_in)
Resize the array to nrows_in by n_cols_in.
double & operator() (unsigned i_row, unsigned i_col)
Non-const row major element access to the underlying representation.
double operator() (unsigned i_row, unsigned i_col) const
Const access to the underlying representation.
double & at (unsigned i_row, unsigned i_col)
Non-const row major element access to the underlying representation.
double at (unsigned i_row, unsigned i_col) const
Const access to the underlying representation.
SubArrayView< TwoDArray, double > make_view (const SolverTypes::IndexPairT &row_range, const SolverTypes::IndexPairT &col_range)
Create a 2D view into the array.
RowView< TwoDArray, double > make_view (unsigned the_row, const SolverTypes::IndexPairT &col_range)
Create a view into a part of a row of the array.
ColumnView< TwoDArray, double > make_view (const SolverTypes::IndexPairT &row_range, unsigned the_col)
Create a view into a part of a column of the array.
Private Member Functions
void register_contents ()
JEOD registration.
void deregister_contents ()
JEOD deregistration.
Private Attributes
DoubleVectorT repr
The underlying representation.
unsigned max_elems
The maximum number of elements in the array.
unsigned n_rows
The number of rows currently in use.
unsigned n_cols
The number of columns currently in use.
Friends
class InputProcessor
void init_attrjeod__TwoDArray ()
Detailed Description
Represents a two dimensional array, implemented as a vector that is indexed as a row major two dimensional array.
The function call operator provides unprotected access to an element of the array. The member function at() ensures that the indexed element is valid.
Definition at line 81 of file experimental/math/include/two_d_array.hh.
Member Typedef Documentation
DoubleVectorT
typedef JeodPrimitiveVector<double>::type jeod::TwoDArray::DoubleVectorT
Vector of doubles.
The data contents are stored in a DoubleVectorT, with 2D values stored in this 1D array using either row-major or column-major indexing.
Definition at line 94 of file experimental/math/include/two_d_array.hh.
Constructor & Destructor Documentation
TwoDArray() [1/3]
jeod::TwoDArray::TwoDArray () inline
Default constructor.
Definition at line 102 of file experimental/math/include/two_d_array.hh.
References register_contents().
~TwoDArray()
virtual jeod::TwoDArray::~TwoDArray () inline virtual
Destructor.
Definition at line 115 of file experimental/math/include/two_d_array.hh.
References deregister_contents().
TwoDArray() [2/3]
jeod::TwoDArray::TwoDArray (const TwoDArray &) default
TwoDArray() [3/3]
jeod::TwoDArray::TwoDArray (TwoDArray &&) default
Member Function Documentation
at() [1/2]
double& jeod::TwoDArray::at (unsigned i_row, unsigned i_col) inline
Non-const row major element access to the underlying representation.
Warning: This is protected, which comes at a cost.
Parameters
i_row The row number, zero based.
i_col The column number, zero based.
Returns
Reference to element at i_row, i_col.
Definition at line 208 of file experimental/math/include/two_d_array.hh.
References n_cols, and n_rows.
Referenced by at().
at() [2/2]
double jeod::TwoDArray::at (unsigned i_row, unsigned i_col) const inline
Const access to the underlying representation.
Warning: This is protected, which comes at a cost.
Parameters
i_row The row number, zero based.
i_col The column number, zero based.
Returns
Value of the element at i_row, i_col.
Definition at line 225 of file experimental/math/include/two_d_array.hh.
References at().
deregister_contents()
void jeod::TwoDArray::deregister_contents () inline private
JEOD deregistration.
Definition at line 312 of file experimental/math/include/two_d_array.hh.
References JEOD_DEREGISTER_CHECKPOINTABLE, and repr.
Referenced by ~TwoDArray().
make_view() [1/3]
SubArrayView<TwoDArray, double> jeod::TwoDArray::make_view (const SolverTypes::IndexPairT & row_range, const SolverTypes::IndexPairT & col_range) inline
Create a 2D view into the array.
Note: the end row and end column are one past the end, consistent with c++ iterators and ranges.
Parameters
row_range Rows at which view begins and ends.
col_range Columns at which view begins and ends.
Definition at line 240 of file experimental/math/include/two_d_array.hh.
make_view() [2/3]
RowView<TwoDArray, double> jeod::TwoDArray::make_view (unsigned the_row, const SolverTypes::IndexPairT & col_range) inline
Create a view into a part of a row of the array.
Note: the end column is one past the end, consistent with c++ iterators and ranges.
Parameters
the_row The row of the view.
col_range Columns at which view begins and ends/
Definition at line 254 of file experimental/math/include/two_d_array.hh.
make_view() [3/3]
ColumnView<TwoDArray, double> jeod::TwoDArray::make_view (const SolverTypes::IndexPairT & row_range, unsigned the_col) inline
Create a view into a part of a column of the array.
Note: the end row is one past the end, consistent with c++ iterators and ranges.
Parameters
row_range Rows at which view begins and ends.
the_col The column of the view.
Definition at line 268 of file experimental/math/include/two_d_array.hh.
operator()() [1/2]
double& jeod::TwoDArray::operator() (unsigned i_row, unsigned i_col) inline
Non-const row major element access to the underlying representation.
Warning: This is unprotected.
Parameters
i_row The row number, zero based.
i_col The column number, zero based.
Returns
Reference to element at i_row, i_col.
Definition at line 181 of file experimental/math/include/two_d_array.hh.
References n_cols, and repr.
operator()() [2/2]
double jeod::TwoDArray::operator() (unsigned i_row, unsigned i_col) const inline
Const access to the underlying representation.
Warning: This is unprotected.
Parameters
i_row The row number, zero based.
i_col The column number, zero based.
Returns
Value of the element at i_row, i_col.
Definition at line 194 of file experimental/math/include/two_d_array.hh.
operator=() [1/2]
TwoDArray& jeod::TwoDArray::operator= (const TwoDArray &) default
operator=() [2/2]
TwoDArray& jeod::TwoDArray::operator= (TwoDArray &&) default
register_contents()
void jeod::TwoDArray::register_contents () inline private
JEOD registration.
Definition at line 303 of file experimental/math/include/two_d_array.hh.
References JEOD_REGISTER_CHECKPOINTABLE, JEOD_REGISTER_NONEXPORTED_CLASS, and repr.
Referenced by TwoDArray().
reserve()
void jeod::TwoDArray::reserve (unsigned max_elems_in) inline
Reserve storage for at least max_elems_in elements.
Parameters
max_elems_in Amount of storage to be reserved.
Definition at line 147 of file experimental/math/include/two_d_array.hh.
References max_elems, and repr.
Referenced by resize(), jeod::GaussJordanSolver::set_max_dimensions(), and jeod::LinearSystemSolver::set_max_dimensions().
resize()
void jeod::TwoDArray::resize (unsigned n_rows_in, unsigned n_cols_in) inline
Resize the array to nrows_in by n_cols_in.
Parameters
n_rows_in The number of rows in the array.
n_cols_in The number of columns in the array.
Definition at line 161 of file experimental/math/include/two_d_array.hh.
References n_cols, n_rows, repr, and reserve().
Referenced by jeod::GaussJordanSolver::set_n_dimensions(), jeod::LinearSystemSolver::set_n_dimensions(), and jeod::GaussJordanSolver::solve().
size()
virtual SolverTypes::IndexPairT jeod::TwoDArray::size () const inline virtual
Size function.
Returns
The number of rows and columns in the view, as a pair.
Definition at line 136 of file experimental/math/include/two_d_array.hh.
References n_cols, and n_rows.
Friends And Related Function Documentation
init_attrjeod__TwoDArray
void init_attrjeod__TwoDArray () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file experimental/math/include/two_d_array.hh.
Field Documentation
max_elems
unsigned jeod::TwoDArray::max_elems private
The maximum number of elements in the array.
trick_units(–)
Definition at line 287 of file experimental/math/include/two_d_array.hh.
Referenced by reserve().
n_cols
unsigned jeod::TwoDArray::n_cols private
The number of columns currently in use.
trick_units(–)
Definition at line 297 of file experimental/math/include/two_d_array.hh.
Referenced by at(), operator()(), resize(), and size().
n_rows
unsigned jeod::TwoDArray::n_rows private
The number of rows currently in use.
trick_units(–)
Definition at line 292 of file experimental/math/include/two_d_array.hh.
Referenced by at(), resize(), and size().
repr
DoubleVectorT jeod::TwoDArray::repr private
The underlying representation.
trick_io(**)
Definition at line 282 of file experimental/math/include/two_d_array.hh.
Referenced by deregister_contents(), operator()(), register_contents(), reserve(), and resize().
The documentation for this class was generated from the following file:
experimental/math/include/two_d_array.hh