JEOD: jeod::DynBodyInitNedState Class Reference
jeod::DynBodyInitNedState Class Reference
Initialize selected aspects of a vehicle's state with respect to eithers some vehicle's North-East-Down frame or the North-East-Down frame for a specified location on the planet.
#include <dyn_body_init_ned_state.hh>
Public Member Functions
DynBodyInitNedState ()
DynBodyInitNedState default constructor.
~DynBodyInitNedState () override
DynBodyInitNedState destructor.
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
void apply (DynManager &dyn_manager) override
Apply the initializer.
void set_use_alt_pfix (const bool use_alt_pfix_in)
Setter for use_alt_pfix.
Public Member Functions inherited from jeod::DynBodyInitPlanetDerived
DynBodyInitPlanetDerived ()
DynBodyInitPlanetDerived default constructor.
~DynBodyInitPlanetDerived () override
DynBodyInitPlanetDerived destructor.
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
bool is_ready (void) override
Indicate whether the initializer is ready to run.
void apply (DynManager &dyn_manager) override
Apply the initializer: This is just a pass through.
Public Member Functions inherited from jeod::DynBodyInitWrtPlanet
DynBodyInitWrtPlanet ()
DynBodyInitWrtPlanet default constructor.
~DynBodyInitWrtPlanet () override
DynBodyInitWrtPlanet destructor.
void initialize (DynManager &dyn_manager) override
Initialize the initializer.
RefFrameItems::Items initializes_what (void) override
Indicate what parts of the vehicle state this object initializes.
bool is_ready (void) override
Indicate whether the initializer is ready to run.
void apply (DynManager &dyn_manager) override
Apply the initializer.
Public Member Functions inherited from jeod::DynBodyInit
DynBodyInit ()
Construct a DynBodyInit.
~DynBodyInit () override
Destruct a DynBodyInit.
virtual void report_failure (void)
Report on an initializer that could not be processed.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()
Construct a BodyAction.
virtual ~BodyAction ()
Destruct a BodyAction.
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier (void) const
Accessor for action_identifier.
Data Fields
AltLatLongState ref_point
Reference point for the local geodetic/geocentric, used only if the reference body is NULL.
NorthEastDown::AltLatLongType altlatlong_type
Use spherical or elliptical coordinates?
Data Fields inherited from jeod::DynBodyInitPlanetDerived
std::string ref_body_name
The name of the vehicle whose composite body frame is used to build the derived state with respect to which the vehicle initialization data are referenced.
Data Fields inherited from jeod::DynBodyInitWrtPlanet
std::string planet_name
The name of the planet about which the reference body's LVLH frame is to be computed.
RefFrameItems::Items set_items
The state elements to be set by this initializer.
Data Fields inherited from jeod::DynBodyInit
std::string body_frame_id
The suffix of the frame name (i.e., the part of the name after the vehicle identifier) to which this initializer pertains.
std::string reference_ref_frame_name
The name of the reference frame against which state data specified in a DynBodyInit subclass are referenced.
RefFrameState state
Contains state information set by the initializer, which is always a subclass of DynBodyInit.
double position [3]
Relative position between the subject and reference reference frame origins.
double velocity [3]
Relative velocity between the subject and reference reference frame origins.
Orientation orientation
Relative orientation between the subject and reference reference frame axes.
double ang_velocity [3]
Relative angular velocity between the subject and reference axes.
bool reverse_sense
Indicates how the user input state items are to be interpreted.
bool rate_in_parent
Indicates how the user input angular velocity is to be interpreted.
Data Fields inherited from jeod::BodyAction
bool active
Controls when the action is performed.
bool terminate_on_error
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name
An identifier for this action.
Protected Attributes
bool use_alt_pfix
Use pfix or alt_pfix flag.
EphemerisRefFrame * pfix_ptr
Pointer to planet fixed frame to be used, either pfix or alt_pfix.
Protected Attributes inherited from jeod::DynBodyInitPlanetDerived
DynBody * ref_body
The vehicle corresponding to the ref_body_name.
RefFrameItems::Items required_items
The state elements in the reference body's composite body frame that must be set before this initializer can proceed.
bool body_is_required
If true (default), the ref_body cannot be NULL.
Protected Attributes inherited from jeod::DynBodyInitWrtPlanet
Planet * planet
The planet corresponding to the planet_name.
Protected Attributes inherited from jeod::DynBodyInit
BodyRefFrame * body_ref_frame
The reference frame whose name is vehicle_name.body_frame_id.
RefFrame * reference_ref_frame
The reference frame whose name is reference_ref_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject
The DynBody of the body that is the subject of this action.
std::string action_identifier
An identifier for this action, constructed from the class name and the action name at initialization time.
Private Member Functions
DynBodyInitNedState (const DynBodyInitNedState &)
DynBodyInitNedState & operator= (const DynBodyInitNedState &)
Friends
class InputProcessor
void init_attrjeod__DynBodyInitNedState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DynBodyInit
void apply_user_inputs (void)
Compute the state wrt the reference reference frame, incorporate the user-input items to this relative state, and compute the state relative to the target frame's parent.
void compute_rotational_state (void)
This method is obsolete.
void compute_translational_state (void)
This method is obsolete.
Planet * find_planet (const DynManager &dyn_manager, const std::string &planet_name, const std::string &variable_name)
Find the Planet with the given name, failing if not found.
DynBody * find_dyn_body (const DynManager &dyn_manager, const std::string &dyn_body_name, const std::string &variable_name)
Find the DynBody with the given name, failing if not found.
RefFrame * find_ref_frame (const DynManager &dyn_manager, const std::string &ref_frame_name, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
BodyRefFrame * find_body_frame (DynBody &frame_container, const std::string &body_frame_identifier, const std::string &variable_name)
Find the RefFrame with the given name, failing if not found.
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Detailed Description
Initialize selected aspects of a vehicle's state with respect to eithers some vehicle's North-East-Down frame or the North-East-Down frame for a specified location on the planet.
Definition at line 90 of file dyn_body_init_ned_state.hh.
Constructor & Destructor Documentation
DynBodyInitNedState() [1/2]
jeod::DynBodyInitNedState::DynBodyInitNedState (const DynBodyInitNedState &) private
DynBodyInitNedState() [2/2]
jeod::DynBodyInitNedState::DynBodyInitNedState (void)
DynBodyInitNedState default constructor.
Definition at line 60 of file dyn_body_init_ned_state.cc.
References jeod::DynBodyInitPlanetDerived::body_is_required, jeod::RefFrameItems::Pos, and jeod::DynBodyInitPlanetDerived::required_items.
~DynBodyInitNedState()
jeod::DynBodyInitNedState::~DynBodyInitNedState (void) override
DynBodyInitNedState destructor.
Definition at line 79 of file dyn_body_init_ned_state.cc.
Member Function Documentation
apply()
void jeod::DynBodyInitNedState::apply (DynManager & dyn_manager) override virtual
Apply the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Definition at line 128 of file dyn_body_init_ned_state.cc.
References jeod::BodyAction::action_identifier, jeod::RefFrame::add_child(), altlatlong_type, jeod::NorthEastDown::altlatlong_type, jeod::DynBodyInitPlanetDerived::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::NorthEastDown::build_ned_orientation(), jeod::NamedItem::c_str(), jeod::DynBody::composite_body, jeod::RefFrame::compute_relative_state(), jeod::NorthEastDown::elliptical, jeod::MessageHandler::fail(), jeod::BodyActionMessages::illegal_value, jeod::Vector3::initialize(), jeod::PlanetFixedPosition::initialize(), jeod::DynBody::name, jeod::NorthEastDown::ned_frame, pfix_ptr, jeod::DynBodyInitWrtPlanet::planet, jeod::DynBodyInitWrtPlanet::planet_name, jeod::RefFrameTrans::position, jeod::DynBodyInitPlanetDerived::ref_body, ref_point, jeod::DynBodyInit::reference_ref_frame, jeod::RefFrame::remove_from_parent(), jeod::DynBodyInitWrtPlanet::set_items, jeod::RefFrame::set_name(), jeod::NorthEastDown::set_ned_trans_states(), jeod::NorthEastDown::spherical, jeod::RefFrame::state, jeod::RefFrameState::trans, jeod::NorthEastDown::undefined, jeod::NorthEastDown::update_from_ellip(), jeod::NorthEastDown::update_from_spher(), and jeod::RefFrameTrans::velocity.
initialize()
void jeod::DynBodyInitNedState::initialize (DynManager & dyn_manager) override virtual
Initialize the initializer.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DynBodyInit.
Reimplemented in jeod::DynBodyInitNedTransState.
Definition at line 101 of file dyn_body_init_ned_state.cc.
References jeod::BasePlanet::alt_pfix, jeod::DynBodyInitPlanetDerived::body_is_required, jeod::BasePlanet::calculate_alt_pfix(), jeod::DynBodyInitPlanetDerived::initialize(), jeod::BasePlanet::pfix, pfix_ptr, jeod::DynBodyInitWrtPlanet::planet, jeod::DynBodyInitPlanetDerived::ref_body_name, and use_alt_pfix.
Referenced by jeod::DynBodyInitNedRotState::initialize(), and jeod::DynBodyInitNedTransState::initialize().
operator=()
DynBodyInitNedState& jeod::DynBodyInitNedState::operator= (const DynBodyInitNedState &) private
set_use_alt_pfix()
void jeod::DynBodyInitNedState::set_use_alt_pfix (const bool use_alt_pfix_in)
Setter for use_alt_pfix.
Definition at line 90 of file dyn_body_init_ned_state.cc.
References use_alt_pfix.
Friends And Related Function Documentation
init_attrjeod__DynBodyInitNedState
void init_attrjeod__DynBodyInitNedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 92 of file dyn_body_init_ned_state.hh.
Field Documentation
altlatlong_type
NorthEastDown::AltLatLongType jeod::DynBodyInitNedState::altlatlong_type
Use spherical or elliptical coordinates?
trick_units(–)
Definition at line 108 of file dyn_body_init_ned_state.hh.
Referenced by apply().
pfix_ptr
EphemerisRefFrame* jeod::DynBodyInitNedState::pfix_ptr protected
Pointer to planet fixed frame to be used, either pfix or alt_pfix.
trick_units(–)
Definition at line 121 of file dyn_body_init_ned_state.hh.
Referenced by apply(), and initialize().
ref_point
AltLatLongState jeod::DynBodyInitNedState::ref_point
Reference point for the local geodetic/geocentric, used only if the reference body is NULL.
trick_units(–)
Definition at line 103 of file dyn_body_init_ned_state.hh.
Referenced by apply().
use_alt_pfix
bool jeod::DynBodyInitNedState::use_alt_pfix protected
Use pfix or alt_pfix flag.
trick_units(–)
Definition at line 115 of file dyn_body_init_ned_state.hh.
Referenced by initialize(), and set_use_alt_pfix().
The documentation for this class was generated from the following files:
dyn_body_init_ned_state.hh
dyn_body_init_ned_state.cc