JEOD: jeod::JeodMemoryItem Class Reference
jeod::JeodMemoryItem Class Reference
A JeodMemoryItem contains metadata about some chunk of allocated memory.
#include <memory_item.hh>
Public Types
enum Flags {
PlacementNew = 1, IsArray = 2, IsGuarded = 4, IsStructured = 8,
IsRegistered = 16, CheckPointed = 32
}
Identifies by name the bit flags the comprise a JeodMemoryItem::flag.
Public Member Functions
JeodMemoryItem ()=default
JeodMemoryItem (bool placement_new, bool is_array, bool is_guarded, bool is_structured, unsigned int nelems_in, unsigned int type_idx, unsigned int alloc_idx)
Construct a JeodMemoryItem.
~JeodMemoryItem ()=default
void set_unique_id (uint32_t id)
Set the unique identifier.
void set_is_registered (bool value)
Set the is_registered flag.
uint32_t get_nelems () const
Access the array size.
uint32_t get_alloc_index () const
Access the allocation information index.
uint32_t get_unique_id () const
Access the unique identifier.
uint32_t get_descriptor_index () const
Access the type descriptor index.
bool get_is_array () const
Access the is_array flag.
bool get_is_guarded () const
Access the is_guarded flag.
bool get_placement_new () const
Access the placement_new flag.
bool is_structured_data () const
Is the associated data a structure/class?
bool get_is_registered () const
Access the checkpointed flag.
bool get_checkpointed () const
Access the checkpointed flag.
Static Private Member Functions
static uint8_t construct_flags (bool placement_new, bool is_array, bool is_guarded, bool is_structured)
Construct the flags for a new JeodMemoryItem.
Private Attributes
uint32_t nelems {}
Number of elements in the allocated array.
uint32_t alloc_info_index {}
Allocation information index, max of 2^32-2 tracked locations.
uint32_t unique_id {}
Unique identifier, max of 2^32-2 allocations (zero is not used).
uint16_t descriptor_index_hi {}
High order bits of the descriptor index.
uint8_t descriptor_index_lo {}
Low order bits of the descriptor index.
uint8_t flags {}
Flags indicating whether.
Detailed Description
A JeodMemoryItem contains metadata about some chunk of allocated memory.
This is a simple datatype that contains POD elements only. All data members are private and are accessible only through getters; the members are essentially constant. The only way to change the values is via a wholesale copy.
Definition at line 86 of file memory_item.hh.
Member Enumeration Documentation
Flags
enum jeod::JeodMemoryItem::Flags
Identifies by name the bit flags the comprise a JeodMemoryItem::flag.
Enumerator
PlacementNew
Was the item constructed with placement new? There is no functional placement delete in C++.
IsArray
Was the item an array constructed via new []? This addresses the delete[] versus delete issue.
IsGuarded
Is the allocated buffer surrounded by guard words? This flag is always false in regular new mode.
IsStructured
Is the item a class (versus a primitive type)? Classes add several other twists.
IsRegistered
Has the item been registered with the simulation engine?
CheckPointed
Reserved for future work, as are flag bits 6 ando 7 (64 and 128).
Definition at line 93 of file memory_item.hh.
Constructor & Destructor Documentation
JeodMemoryItem() [1/2]
jeod::JeodMemoryItem::JeodMemoryItem () default
JeodMemoryItem() [2/2]
jeod::JeodMemoryItem::JeodMemoryItem (bool placement_new, bool is_array, bool is_guarded, bool is_structured, unsigned int nelems_in, unsigned int type_idx, unsigned int alloc_idx)
Construct a JeodMemoryItem.
The data are essentially constant, so the only viable way to set elements to meaningful values is via this non-default constructor.
Parameters
[in] placement_new Constructed with placement new?
[in] is_array Constructed with new []?
[in] is_guarded Is the item an array?
[in] is_structured Is the item a structured data type?
[in] nelems_in Number of elements
[in] type_idx Type descriptor (index)
[in] alloc_idx Macro invocation info (index)
Definition at line 86 of file memory_item.cc.
~JeodMemoryItem()
jeod::JeodMemoryItem::~JeodMemoryItem () default
Member Function Documentation
construct_flags()
uint8_t jeod::JeodMemoryItem::construct_flags (bool placement_new, bool is_array, bool is_guarded, bool is_structured) static private
Construct the flags for a new JeodMemoryItem.
Returns
Constructed flags
Parameters
[in] placement_new Constructed with placement new?
[in] is_array Constructed with new []?
[in] is_guarded Is the item an array?
[in] is_structured Is the item a structured data type?
Definition at line 47 of file memory_item.cc.
References flags, IsArray, IsGuarded, IsStructured, and PlacementNew.
get_alloc_index()
uint32_t jeod::JeodMemoryItem::get_alloc_index () const inline
Access the allocation information index.
Returns
Allocation information index
Definition at line 246 of file memory_item.hh.
References alloc_info_index.
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodMemoryManager::generate_shutdown_report(), and jeod::JeodMemoryManager::restart_clear_memory().
get_checkpointed()
bool jeod::JeodMemoryItem::get_checkpointed () const inline
Access the checkpointed flag.
Returns
Checkpointed?
Definition at line 309 of file memory_item.hh.
References CheckPointed, and flags.
get_descriptor_index()
uint32_t jeod::JeodMemoryItem::get_descriptor_index () const inline
Access the type descriptor index.
Returns
Type descriptor index
Definition at line 255 of file memory_item.hh.
References descriptor_index_hi, and descriptor_index_lo.
Referenced by jeod::JeodMemoryManager::get_type_descriptor_nolock().
get_is_array()
bool jeod::JeodMemoryItem::get_is_array () const inline
Access the is_array flag.
Returns
Allocated as an array?
Definition at line 273 of file memory_item.hh.
References flags, and IsArray.
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodTrickMemoryInterface::register_allocation(), jeod::JeodMemoryManager::restart_clear_memory(), and jeod::JeodMemoryTypeDescriptor::type_spec().
get_is_guarded()
bool jeod::JeodMemoryItem::get_is_guarded () const inline
Access the is_guarded flag.
Returns
Is allocated memory guarded?
Definition at line 282 of file memory_item.hh.
References flags, and IsGuarded.
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), and jeod::JeodMemoryManager::restart_clear_memory().
get_is_registered()
bool jeod::JeodMemoryItem::get_is_registered () const inline
Access the checkpointed flag.
Returns
Registered with sim engine?
Definition at line 300 of file memory_item.hh.
References flags, and IsRegistered.
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodMemoryManager::restart_clear_memory(), and jeod::JeodMemoryManager::~JeodMemoryManager().
get_nelems()
uint32_t jeod::JeodMemoryItem::get_nelems () const inline
Access the array size.
Returns
Array size
Definition at line 228 of file memory_item.hh.
References nelems.
Referenced by jeod::JeodMemoryManager::add_allocation_atomic(), jeod::JeodMemoryTypeDescriptor::buffer_end(), jeod::JeodMemoryTypeDescriptor::buffer_size(), jeod::JeodMemoryManager::destroy_memory_internal(), jeod::JeodTrickMemoryInterface::register_allocation(), jeod::JeodMemoryManager::restart_clear_memory(), and jeod::JeodMemoryTypeDescriptor::type_spec().
get_placement_new()
bool jeod::JeodMemoryItem::get_placement_new () const inline
Access the placement_new flag.
Returns
Allocated for placement new?
Definition at line 264 of file memory_item.hh.
References flags, and PlacementNew.
Referenced by jeod::JeodMemoryManager::destroy_memory_internal(), and jeod::JeodMemoryManager::restart_clear_memory().
get_unique_id()
uint32_t jeod::JeodMemoryItem::get_unique_id () const inline
Access the unique identifier.
Returns
Unique identifier
Definition at line 237 of file memory_item.hh.
References unique_id.
Referenced by jeod::JeodTrickMemoryInterface::deregister_allocation(), and jeod::JeodTrickMemoryInterface::register_allocation().
is_structured_data()
bool jeod::JeodMemoryItem::is_structured_data () const inline
Is the associated data a structure/class?
Returns
True for structured data
Definition at line 291 of file memory_item.hh.
References flags, and IsStructured.
set_is_registered()
void jeod::JeodMemoryItem::set_is_registered (bool value)
Set the is_registered flag.
Parameters
[in] value New value of the is_registered flag
Definition at line 132 of file memory_item.cc.
References flags, and IsRegistered.
set_unique_id()
void jeod::JeodMemoryItem::set_unique_id (uint32_t id)
Set the unique identifier.
Parameters
[in] id Unique identifier
Definition at line 105 of file memory_item.cc.
References jeod::MessageHandler::error(), jeod::MemoryMessages::internal_error, and unique_id.
Referenced by jeod::JeodMemoryManager::register_memory_internal().
Field Documentation
alloc_info_index
uint32_t jeod::JeodMemoryItem::alloc_info_index {} private
Allocation information index, max of 2^32-2 tracked locations.
The allocation information is a string of the form "file.cc:line#" that indicates where in the code the data was allocated. The underlying string is maintained in the global memory manager's string table.trick_units(–)
Definition at line 190 of file memory_item.hh.
Referenced by get_alloc_index().
descriptor_index_hi
uint16_t jeod::JeodMemoryItem::descriptor_index_hi {} private
High order bits of the descriptor index.
The descriptor_index specifies the type decriptor that describes the data. The underlying descriptor is maintained in the global memory manager's type descriptor table.trick_units(–)
Definition at line 205 of file memory_item.hh.
Referenced by get_descriptor_index().
descriptor_index_lo
uint8_t jeod::JeodMemoryItem::descriptor_index_lo {} private
Low order bits of the descriptor index.
trick_units(–)
Definition at line 210 of file memory_item.hh.
Referenced by get_descriptor_index().
flags
uint8_t jeod::JeodMemoryItem::flags {} private
Flags indicating whether.
The data was constructed with default new or placement new
The data was allocated as an array or as a single object
The allocated are guarded
The data is a structured or non-structured data type
The data has been checkpointed (future)
Plus three more future-use spares.trick_units(–)
Definition at line 221 of file memory_item.hh.
Referenced by construct_flags(), get_checkpointed(), get_is_array(), get_is_guarded(), get_is_registered(), get_placement_new(), is_structured_data(), and set_is_registered().
nelems
uint32_t jeod::JeodMemoryItem::nelems {} private
Number of elements in the allocated array.
trick_units(–)
Definition at line 182 of file memory_item.hh.
Referenced by get_nelems().
unique_id
uint32_t jeod::JeodMemoryItem::unique_id {} private
Unique identifier, max of 2^32-2 allocations (zero is not used).
The unique identifier forms the basis of the item name sent to the simulation engine for this memory item.trick_units(–)
Definition at line 197 of file memory_item.hh.
Referenced by get_unique_id(), and set_unique_id().
The documentation for this class was generated from the following files:
memory_item.hh
memory_item.cc