JEOD: jeod::RefFrameItems Class Reference
jeod::RefFrameItems Class Reference
Identify which aspects of a reference frame's state have been set.
#include <ref_frame_items.hh>
Public Types
enum Items {
No_Items = 0, Pos = 1, Vel = 2, Pos_Vel = 3,
Att = 4, Pos_Att = 5, Vel_Att = 6, Pos_Vel_Att = 7,
Rate = 8, Pos_Rate = 9, Vel_Rate = 10, Pos_Vel_Rate = 11,
Att_Rate = 12, Pos_Att_Rate = 13, Vel_Att_Rate = 14, Pos_Vel_Att_Rate = 15
}
The Items enumeration identifies the major items that can be set in a RefFrameState structure – position, velocity, attitude, and attitude rate.
Public Member Functions
RefFrameItems (void)
Construct a RefFrameItems object.
RefFrameItems (Items new_value)
Construct a RefFrameItems object.
Items get (void) const
Get the value of a RefFrameItems.
bool contains (Items test_items) const
Determine if specified aspects of a RefFrameItems are set.
bool equals (Items test_items) const
Determine whether a RefFrameItems equals the specified aspects.
bool is_empty (void) const
Determine whether a RefFrameItems has nothing set.
bool is_full (void) const
Determine whether a RefFrameItems has all bits set.
Items set (Items new_value)
Set the value of a RefFrameItems.
Items add (Items new_items)
Set aspects of a RefFrameItems.
Items remove (Items old_items)
Clear aspects of a RefFrameItems.
const char * to_string (void) const
Return a string indicating the set items.
Static Public Member Functions
static const char * to_string (Items test_items)
Return a string indicating the set items.
Data Fields
Items value
Indicates which aspects of a RefFrameState have been set.
Friends
class InputProcessor
void init_attrjeod__RefFrameItems ()
Detailed Description
Identify which aspects of a reference frame's state have been set.
The aspects that are managed are the position, velocity, attitude, and attitude rate.
Definition at line 83 of file ref_frame_items.hh.
Member Enumeration Documentation
Items
enum jeod::RefFrameItems::Items
The Items enumeration identifies the major items that can be set in a RefFrameState structure – position, velocity, attitude, and attitude rate.
The enumeration values are implemented as bit flags. The four basic items, position, velocity, attitude, and rate, have values of 1, 2, 4, and 8, respectively. Combinations thereof have values corresponding to the bitwise or of the basic components.
Enumerator
No_Items
Nothing set.
Pos
Position.
Vel
Velocity.
Pos_Vel
Position + velocity.
Att
Attitude.
Pos_Att
Position + attitude.
Vel_Att
Velocity + attitude.
Pos_Vel_Att
Position + velocity + attitude.
Rate
Attitude rate.
Pos_Rate
Position + rate.
Vel_Rate
Velocity + rate.
Pos_Vel_Rate
Position + velocity + rate.
Att_Rate
Attitude + Rate.
Pos_Att_Rate
Position + attitude + Rate.
Vel_Att_Rate
Velocity + attitude + Rate.
Pos_Vel_Att_Rate
Position + velocity + attitude + Rate.
Definition at line 100 of file ref_frame_items.hh.
Constructor & Destructor Documentation
RefFrameItems() [1/2]
jeod::RefFrameItems::RefFrameItems (void)
Construct a RefFrameItems object.
Definition at line 70 of file ref_frame_items.cc.
References No_Items, and value.
RefFrameItems() [2/2]
jeod::RefFrameItems::RefFrameItems (Items new_value) explicit
Construct a RefFrameItems object.
Parameters
[in] new_value Initial value
Definition at line 81 of file ref_frame_items.cc.
References value.
Member Function Documentation
add()
RefFrameItems::Items jeod::RefFrameItems::add (RefFrameItems::Items new_items) inline
Set aspects of a RefFrameItems.
Returns
Updated value
Parameters
[in] new_items Items to add
Definition at line 163 of file ref_frame_items_inline.hh.
References value.
Referenced by jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::DynBodyInitTransState::is_ready(), jeod::DynBodyInit::is_ready(), jeod::DynBody::propagate_state_from_composite(), jeod::DynBody::propagate_state_from_structure(), jeod::DynBody::set_state_source_internal(), and jeod::DynBody::update_integrated_state().
contains()
bool jeod::RefFrameItems::contains (RefFrameItems::Items test_items) const inline
Determine if specified aspects of a RefFrameItems are set.
Returns
Are specified items set?
Parameters
[in] test_items Test items
Definition at line 93 of file ref_frame_items_inline.hh.
References value.
Referenced by jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::DynBodyInitLvlhTransState::initialize(), jeod::DynBodyInitNedRotState::initialize(), jeod::DynBodyInitNedTransState::initialize(), jeod::DynBodyInitLvlhRotState::initialize(), jeod::DynBody::initialized_states_contains(), jeod::DynBodyInitTransState::is_ready(), jeod::DynBodyInitRotState::is_ready(), jeod::DynBodyInitPlanetDerived::is_ready(), and jeod::DynBodyInit::is_ready().
equals()
bool jeod::RefFrameItems::equals (RefFrameItems::Items test_items) const inline
Determine whether a RefFrameItems equals the specified aspects.
Returns
Exact equality?
Parameters
[in] test_items Test items
Definition at line 109 of file ref_frame_items_inline.hh.
References value.
get()
RefFrameItems::Items jeod::RefFrameItems::get (void) const inline
Get the value of a RefFrameItems.
Returns
Current value
Definition at line 79 of file ref_frame_items_inline.hh.
References value.
Referenced by jeod::DynManager::check_for_uninitialized_states(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::DynBodyInitNedRotState::initialize(), jeod::DynBodyInitNedTransState::initialize(), jeod::DynBodyInitLvlhTransState::initialize(), jeod::DynBodyInitLvlhRotState::initialize(), jeod::DynBodyInitTransState::is_ready(), jeod::DynBodyInit::is_ready(), jeod::DynBody::propagate_state_from_composite(), and jeod::DynBody::propagate_state_from_structure().
is_empty()
bool jeod::RefFrameItems::is_empty (void) const inline
Determine whether a RefFrameItems has nothing set.
Returns
Nothing set?
Definition at line 122 of file ref_frame_items_inline.hh.
References No_Items, and value.
Referenced by jeod::DynBody::attach_update_properties(), jeod::DynBody::attach_validate_child(), jeod::DynManager::check_for_uninitialized_states(), and jeod::DynBody::propagate_state().
is_full()
bool jeod::RefFrameItems::is_full (void) const inline
Determine whether a RefFrameItems has all bits set.
Returns
Fully set?
Definition at line 135 of file ref_frame_items_inline.hh.
References Pos_Vel_Att_Rate, and value.
Referenced by jeod::DynBody::attach_validate_child(), jeod::DynBody::propagate_state_from_composite(), and jeod::DynBody::propagate_state_from_structure().
remove()
RefFrameItems::Items jeod::RefFrameItems::remove (RefFrameItems::Items old_items) inline
Clear aspects of a RefFrameItems.
Returns
Updated value
Parameters
[in] old_items Items to remove
Definition at line 179 of file ref_frame_items_inline.hh.
References Pos_Vel_Att_Rate, and value.
Referenced by jeod::DynManager::check_for_uninitialized_states(), jeod::DynBodyInitLvlhTransState::initialize(), jeod::DynBodyInitNedRotState::initialize(), jeod::DynBodyInitNedTransState::initialize(), jeod::DynBodyInitLvlhRotState::initialize(), jeod::DynBodyInit::is_ready(), jeod::DynBody::propagate_state_from_composite(), jeod::DynBody::propagate_state_from_structure(), and jeod::DynBody::set_state_source_internal().
set()
RefFrameItems::Items jeod::RefFrameItems::set (RefFrameItems::Items new_value) inline
Set the value of a RefFrameItems.
Returns
Updated value
Parameters
[in] new_value New value
Definition at line 149 of file ref_frame_items_inline.hh.
References value.
Referenced by jeod::DynManager::check_for_uninitialized_states(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::DynBody::DynBody(), jeod::DynBody::initialize_model(), jeod::DynBody::integrate(), jeod::DynBodyInitTransState::is_ready(), jeod::DynBody::propagate_state_from_composite(), and jeod::DynBody::propagate_state_from_structure().
to_string() [1/2]
const char * jeod::RefFrameItems::to_string (Items test_items) static
Return a string indicating the set items.
Returns
Set items, by name
Parameters
[in] test_items Items enum value
Definition at line 39 of file ref_frame_items.cc.
References Att, Att_Rate, No_Items, Pos, Pos_Att, Pos_Att_Rate, Pos_Rate, Pos_Vel, Pos_Vel_Att, Pos_Vel_Att_Rate, Pos_Vel_Rate, Rate, Vel, Vel_Att, Vel_Att_Rate, and Vel_Rate.
Referenced by jeod::DynManager::check_for_uninitialized_states().
to_string() [2/2]
const char * jeod::RefFrameItems::to_string (void) const
Return a string indicating the set items.
Returns
Set items, by name
Definition at line 93 of file ref_frame_items.cc.
References value.
Referenced by jeod::DynBodyInit::apply(), and jeod::DynBodyInit::report_failure().
Friends And Related Function Documentation
init_attrjeod__RefFrameItems
void init_attrjeod__RefFrameItems () friend
InputProcessor
friend class InputProcessor friend
Definition at line 85 of file ref_frame_items.hh.
Field Documentation
value
Items jeod::RefFrameItems::value
Indicates which aspects of a RefFrameState have been set.
trick_units(–)
Definition at line 133 of file ref_frame_items.hh.
Referenced by add(), contains(), equals(), get(), is_empty(), is_full(), RefFrameItems(), remove(), set(), and to_string().
The documentation for this class was generated from the following files:
ref_frame_items.hh
ref_frame_items_inline.hh
ref_frame_items.cc