/* Autogenerated from interactions/aerodynamics/data/aero_model.d */

/*
PURPOSE:
    (Aerodynamics drag coefficients paramter initialization.)

REFERENCE:
    ((None))

ASSUMPTIONS AND LIMITATIONS:
    ((See model.))

*/


class AerodynamicDrag;
#define JEOD_FRIEND_CLASS AerodynamicDrag_aero_model_default_data

// JEOD includes
#include "interactions/aerodynamics/include/aero_drag.hh"

// Unsupported includes
#include "../include/aero_model.hh"



//! Namespace jeod
namespace jeod {

void
AerodynamicDrag_aero_model_default_data::initialize (
   AerodynamicDrag * AerodynamicDrag_ptr)
{
   AerodynamicDrag_ptr->param.gas_const = 287;
   AerodynamicDrag_ptr->param.temp_free_stream = 1487;
   AerodynamicDrag_ptr->active = true;

}
} // End JEOD namespace
