JEOD: jeod::RestartableSO3SecondOrderODEIntegrator Class Reference
jeod::RestartableSO3SecondOrderODEIntegrator Class Reference
A RestartableSO3SecondOrderODEIntegrator integrates a generalized second order ODE that describes rotation in three space.
#include <restartable_state_integrator.hh>
Public Member Functions
RestartableSO3SecondOrderODEIntegrator ()
Default constructor.
~RestartableSO3SecondOrderODEIntegrator () override
Destructor.
void create_integrator (GeneralizedSecondOrderODETechnique::TechniqueType technique_in, const er7_utils::IntegratorConstructor &generator, er7_utils::IntegrationControls &controls)
Create the integrator to be managed.
void destroy_integrator ()
Destroy the integrator.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage, double const *accel, double *velocity, double *position)
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
void reset_integrator ()
Tell the integrator to reset itself.
void simple_restore () override
Restore the integrator on restart.
Public Member Functions inherited from jeod::SimpleCheckpointable
SimpleCheckpointable ()
Construct a SimpleCheckpointable object.
~SimpleCheckpointable (void) override
Destruct a SimpleCheckpointable object.
const std::string get_init_name (void) override
Return the name of the initial restart action, in this case "restore".
const std::string get_item_name (void) override
Return the name of the current restart action, in this case "".
const std::string get_item_value (void) override
Return the value of the current restart action, in this case "".
void start_checkpoint (void) override
In general, start the checkpoint process.
void advance_checkpoint (void) override
In general, advance to the next checkpoint item; in this case, do nothing.
bool is_checkpoint_finished (void) override
In general, indicate when checkpointing is complete.
int perform_restore_action (const std::string &action_name, const std::string &action_value) override
In general, respond to the actions recorded in the checkpoint file.
Public Member Functions inherited from jeod::JeodCheckpointable
JeodCheckpointable ()
Default constructor; does nothing.
virtual ~JeodCheckpointable ()
Destructor; does nothing.
virtual void pre_checkpoint (void)
In general, perform object-specific operations that need to be performed in anticipation of a checkpoint, typically allocating and populating memory.
virtual void post_checkpoint (void)
In general, perform object-specific operations that need to be performed after checkpoint completion, typically freeing memory used for checkpointing.
virtual void pre_restart (void)
In general, perform object-specific operations that need to be performed in anticipation of a restart, typically releasing resources.
virtual void post_restart (void)
In general, perform object-specific operations that need to be performed after restart completion.
virtual void initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, perform initialization actions such as obtaining requisite type information, registering Checkpointable objects contained within the object, etc.
virtual void undo_initialize_checkpointable (const void *container, const std::type_info &container_type, const std::string &elem_name)
In general, undo external actions performed by initialize_checkpointable.
virtual const std::string get_init_value (void)
In general, return the value of the initialization action.
virtual const std::string get_final_name (void)
In general, return the name of the finalization action.
virtual const std::string get_final_value (void)
In general, return the value of the finalization action.
Private Member Functions
RestartableSO3SecondOrderODEIntegrator (const RestartableSO3SecondOrderODEIntegrator &)
Not implemented.
RestartableSO3SecondOrderODEIntegrator & operator= (const RestartableSO3SecondOrderODEIntegrator &)
Not implemented.
Private Attributes
GeneralizedSecondOrderODETechnique::TechniqueType technique
Specifies the mechanism for integrating rotational state.
er7_utils::SecondOrderODEIntegrator * integrator
Pointer to the object that performs integration.
RestartableGeneralizedDerivSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions > generalized_deriv_integrator_manager
SO3 generalized derivative integrator.
RestartableGeneralizedStepSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions > generalized_step_integrator_manager
SO3 Lie Group integrator.
Friends
class InputProcessor
void init_attrjeod__RestartableSO3SecondOrderODEIntegrator ()
Additional Inherited Members
Detailed Description
A RestartableSO3SecondOrderODEIntegrator integrates a generalized second order ODE that describes rotation in three space.
Definition at line 338 of file restartable_state_integrator.hh.
Constructor & Destructor Documentation
RestartableSO3SecondOrderODEIntegrator() [1/2]
jeod::RestartableSO3SecondOrderODEIntegrator::RestartableSO3SecondOrderODEIntegrator () inline
Default constructor.
Definition at line 346 of file restartable_state_integrator.hh.
References JEOD_REGISTER_CLASS.
~RestartableSO3SecondOrderODEIntegrator()
jeod::RestartableSO3SecondOrderODEIntegrator::~RestartableSO3SecondOrderODEIntegrator () inline override
Destructor.
Definition at line 360 of file restartable_state_integrator.hh.
References destroy_integrator().
RestartableSO3SecondOrderODEIntegrator() [2/2]
jeod::RestartableSO3SecondOrderODEIntegrator::RestartableSO3SecondOrderODEIntegrator (const RestartableSO3SecondOrderODEIntegrator &) private
Not implemented.
Member Function Documentation
create_integrator()
void jeod::RestartableSO3SecondOrderODEIntegrator::create_integrator (GeneralizedSecondOrderODETechnique::TechniqueType technique_in, const er7_utils::IntegratorConstructor & generator, er7_utils::IntegrationControls & controls) inline
Create the integrator to be managed.
Parameters
[in] technique_in Integration technique; generalized step vs deriv.
[in] generator Integrator constructor used to create the integrator.
[in,out] controls Integration controls to be passed to the generator.
Definition at line 371 of file restartable_state_integrator.hh.
References jeod::GeneralizedSecondOrderODETechnique::Cartesian, jeod::RestartableStateIntegrator< IntegratorType >::create_integrator(), jeod::MessageHandler::fail(), generalized_deriv_integrator_manager, generalized_step_integrator_manager, integrator, jeod::IntegrationMessages::invalid_item, jeod::GeneralizedSecondOrderODETechnique::LieGroup, jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference(), and technique.
Referenced by jeod::DynBody::create_body_integrators().
destroy_integrator()
void jeod::RestartableSO3SecondOrderODEIntegrator::destroy_integrator () inline
Destroy the integrator.
Definition at line 402 of file restartable_state_integrator.hh.
References jeod::RestartableStateIntegrator< IntegratorType >::destroy_integrator(), generalized_deriv_integrator_manager, generalized_step_integrator_manager, technique, and jeod::GeneralizedSecondOrderODETechnique::Unspecified.
Referenced by ~RestartableSO3SecondOrderODEIntegrator().
integrate()
er7_utils::IntegratorResult jeod::RestartableSO3SecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, double const * accel, double * velocity, double * position) inline
Propagate state to the specified stage of the integration process for an overall integration time interval of dyn_dt.
Note that this is a pass-through to the encapsulated integrator object. See er7_utils::SecondOrderODEIntegrator::integrate for details.
Parameters
[in] dyn_dt Dynamic time step, in dynamic time seconds.
[in] target_stage The stage of the integration process that the integrator should try to attain.
[in] accel Time derivative of the generalized velocity.
[in,out] velocity Generalized velocity vector.
[in,out] position Generalized position vector.
Returns
The status (time advance, pass/fail status) of the integration.
Definition at line 426 of file restartable_state_integrator.hh.
References integrator.
Referenced by jeod::StructureIntegratedDynBody::rot_integ(), and jeod::DynBody::rot_integ().
operator=()
RestartableSO3SecondOrderODEIntegrator& jeod::RestartableSO3SecondOrderODEIntegrator::operator= (const RestartableSO3SecondOrderODEIntegrator &) private
Not implemented.
reset_integrator()
void jeod::RestartableSO3SecondOrderODEIntegrator::reset_integrator () inline
Tell the integrator to reset itself.
This should be called when the time step or time direction changes or upon a discrete change in state such docking/undocking. Such events invalidate saved state (if any). The integrator needs to restart from scratch when such events occur.
Definition at line 444 of file restartable_state_integrator.hh.
References integrator.
Referenced by jeod::DynBody::reset_integrators().
simple_restore()
void jeod::RestartableSO3SecondOrderODEIntegrator::simple_restore (void) inline override virtual
Restore the integrator on restart.
Implements jeod::SimpleCheckpointable.
Definition at line 452 of file restartable_state_integrator.hh.
References jeod::GeneralizedSecondOrderODETechnique::Cartesian, jeod::RestartableStateIntegrator< IntegratorType >::clear_integrator_reference(), generalized_deriv_integrator_manager, generalized_step_integrator_manager, integrator, jeod::GeneralizedSecondOrderODETechnique::LieGroup, jeod::RestartableStateIntegrator< IntegratorType >::set_integrator_reference(), jeod::RestartableStateIntegrator< IntegratorType >::simple_restore(), and technique.
Friends And Related Function Documentation
init_attrjeod__RestartableSO3SecondOrderODEIntegrator
void init_attrjeod__RestartableSO3SecondOrderODEIntegrator () friend
InputProcessor
friend class InputProcessor friend
Definition at line 339 of file restartable_state_integrator.hh.
Field Documentation
generalized_deriv_integrator_manager
RestartableGeneralizedDerivSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions> jeod::RestartableSO3SecondOrderODEIntegrator::generalized_deriv_integrator_manager private
SO3 generalized derivative integrator.
trick_io(**)
Definition at line 492 of file restartable_state_integrator.hh.
Referenced by create_integrator(), destroy_integrator(), and simple_restore().
generalized_step_integrator_manager
RestartableGeneralizedStepSecondOrderODEIntegrator< 4, 3, er7_utils::LeftQuaternionGeneralizedPositionFunctions> jeod::RestartableSO3SecondOrderODEIntegrator::generalized_step_integrator_manager private
SO3 Lie Group integrator.
trick_io(**)
Definition at line 499 of file restartable_state_integrator.hh.
Referenced by create_integrator(), destroy_integrator(), and simple_restore().
integrator
er7_utils::SecondOrderODEIntegrator* jeod::RestartableSO3SecondOrderODEIntegrator::integrator private
Pointer to the object that performs integration.
This object is created and managed by one of the integrator managers defined below. The techique dictates which of the two is used.trick_units(–)
Definition at line 485 of file restartable_state_integrator.hh.
Referenced by create_integrator(), integrate(), reset_integrator(), and simple_restore().
technique
GeneralizedSecondOrderODETechnique::TechniqueType jeod::RestartableSO3SecondOrderODEIntegrator::technique private
Specifies the mechanism for integrating rotational state.
trick_units(–)
Definition at line 478 of file restartable_state_integrator.hh.
Referenced by create_integrator(), destroy_integrator(), and simple_restore().
The documentation for this class was generated from the following file:
restartable_state_integrator.hh