JEOD: jeod::RadiationDefaultSurface Class Reference
jeod::RadiationDefaultSurface Class Reference
The default spherical surface for radiation pressure.
#include <radiation_default_surface.hh>
Public Member Functions
RadiationDefaultSurface ()
Constructor for RadiationDefaultSurface.
~RadiationDefaultSurface () override
Destructor for RadiationDefaultSurface.
void initialize (void) override
initializes the default surface
void incident_radiation (const double flux_mag, const double flux_struc_hat[3], const bool calculate_forces) override
Calculation of force and torque due to radiation pressure.
void thermal_update (void)
Test for necessity of maintaining thermal updates, and performs them as necessary.
void add_thermal_integrator_to (DynBody *dyn_body)
Adds the thermal integrator of this surface to the integration group of the DynBody.
void set_name (std::string name_in)
Setter for the name.
Public Member Functions inherited from jeod::RadiationBaseFacet
RadiationBaseFacet ()
Construct a RadiationBaseFacet.
virtual ~RadiationBaseFacet ()
Destructor for RadiationBaseFacet.
virtual void interact_with_third_body (RadiationThirdBody *third_body, const bool calc_forces)
Calculation of force, torques and irradiance due to ThirdBody flux.
virtual void initialize_runtime_values (void)
To initialize the values during each update run.
Data Fields
double rad_coeff
The radiation-equivalent of a drag coefficient.
double temperature
The value of the surface kinetic temperature.
std::string name
The name of the surface.
double surface_area
surface area of the default sphere.
Data Fields inherited from jeod::RadiationBaseFacet
double albedo
Usable value of albedo, set to either albedo_IR or albedo_vis, depending on situation.
double albedo_vis
Fraction of incident visible radiation that is immediately reflected.
double albedo_IR
Fraction of incident IR radiation that is immediately reflected.
double diffuse
Fraction of reflected radiation that is reflected diffusely (balance reflected specularly)
ThermalFacetRider thermal
thermal characteristics of the facet.
double cx_area
cross-sectional area projected perpendicular to the radiation vector.
double areaxflux
product of momentum flux and cross-sectional area (cx_area).
double areaxflux_e
product of energy flux and cross-sectional area
double F_absorption [3]
Force due to photon absorption from ONLY ONE source.
double F_specular [3]
Force due to photon specular reflection from ONLY ONE source.
double F_diffuse [3]
Force due to photon diffuse reflection from ONLY ONE source.
double F_emission [3]
Force due to photon (thermal) emission.
Private Member Functions
RadiationDefaultSurface & operator= (const RadiationDefaultSurface &rhs)
RadiationDefaultSurface (const RadiationDefaultSurface &rhs)
Friends
class InputProcessor
void init_attrjeod__RadiationDefaultSurface ()
Additional Inherited Members
Static Protected Attributes inherited from jeod::RadiationBaseFacet
static const double speed_of_light = 299792458.0
Speed of light in vacuum.
Detailed Description
The default spherical surface for radiation pressure.
Definition at line 89 of file radiation_default_surface.hh.
Constructor & Destructor Documentation
RadiationDefaultSurface() [1/2]
jeod::RadiationDefaultSurface::RadiationDefaultSurface (void)
Constructor for RadiationDefaultSurface.
Definition at line 65 of file radiation_default_surface.cc.
References jeod::RadiationBaseFacet::albedo, jeod::RadiationBaseFacet::areaxflux, jeod::RadiationBaseFacet::areaxflux_e, jeod::RadiationBaseFacet::cx_area, jeod::RadiationBaseFacet::diffuse, jeod::RadiationBaseFacet::F_absorption, jeod::RadiationBaseFacet::F_diffuse, jeod::RadiationBaseFacet::F_emission, jeod::RadiationBaseFacet::F_specular, jeod::Vector3::initialize(), rad_coeff, surface_area, and temperature.
~RadiationDefaultSurface()
jeod::RadiationDefaultSurface::~RadiationDefaultSurface (void) override
Destructor for RadiationDefaultSurface.
Definition at line 299 of file radiation_default_surface.cc.
RadiationDefaultSurface() [2/2]
jeod::RadiationDefaultSurface::RadiationDefaultSurface (const RadiationDefaultSurface & rhs) private
Member Function Documentation
add_thermal_integrator_to()
void jeod::RadiationDefaultSurface::add_thermal_integrator_to (DynBody * dyn_body)
Adds the thermal integrator of this surface to the integration group of the DynBody.
Parameters
[in,out] dyn_body Body associated with this thermal object.
Definition at line 289 of file radiation_default_surface.cc.
References jeod::DynBody::add_integrable_object(), jeod::ThermalFacetRider::integrable_object, and jeod::RadiationBaseFacet::thermal.
incident_radiation()
void jeod::RadiationDefaultSurface::incident_radiation (const double flux_mag, const double flux_struc_hat[3], const bool calculate_forces) override virtual
Calculation of force and torque due to radiation pressure.
Assumptions and Limitations
Assumes that flux magnitude is positive.
Will only be called if flux magnitude is positive.
Assumes spherical surface.
Parameters
[in] flux_mag the magnitude of the incident flux
[in] flux_struc_hat the unit vector in structural frame for the flux vector.
[in] calculate_forces boolean indicating whether to calculate forces.
Implements jeod::RadiationBaseFacet.
Definition at line 218 of file radiation_default_surface.cc.
References jeod::RadiationBaseFacet::albedo, jeod::RadiationBaseFacet::areaxflux, jeod::RadiationBaseFacet::areaxflux_e, jeod::RadiationBaseFacet::cx_area, jeod::RadiationBaseFacet::diffuse, jeod::RadiationBaseFacet::F_absorption, jeod::RadiationBaseFacet::F_diffuse, jeod::RadiationBaseFacet::F_specular, jeod::Vector3::incr(), jeod::ThermalFacetRider::power_absorb, jeod::Vector3::scale(), jeod::RadiationBaseFacet::speed_of_light, and jeod::RadiationBaseFacet::thermal.
Referenced by jeod::RadiationPressure::update_default_surface().
initialize()
void jeod::RadiationDefaultSurface::initialize (void) override virtual
initializes the default surface
Reimplemented from jeod::RadiationBaseFacet.
Definition at line 89 of file radiation_default_surface.cc.
References jeod::RadiationBaseFacet::albedo, jeod::RadiationBaseFacet::cx_area, jeod::RadiationBaseFacet::diffuse, jeod::MessageHandler::fail(), jeod::RadiationBaseFacet::initialize(), jeod::ThermalFacetRider::initialize(), jeod::RadiationMessages::invalid_setup_error, jeod::RadiationMessages::operational_setup_error, rad_coeff, surface_area, temperature, jeod::RadiationBaseFacet::thermal, and jeod::MessageHandler::warn().
Referenced by jeod::RadiationPressure::initialize().
operator=()
RadiationDefaultSurface& jeod::RadiationDefaultSurface::operator= (const RadiationDefaultSurface & rhs) private
set_name()
void jeod::RadiationDefaultSurface::set_name (std::string name_in) inline
Setter for the name.
Definition at line 160 of file radiation_default_surface.hh.
References name.
thermal_update()
void jeod::RadiationDefaultSurface::thermal_update (void)
Test for necessity of maintaining thermal updates, and performs them as necessary.
Definition at line 270 of file radiation_default_surface.cc.
References jeod::ThermalFacetRider::active, jeod::ThermalFacetRider::cycle_time, jeod::ThermalFacetRider::integrate(), jeod::ThermalFacetRider::power_absorb, temperature, jeod::RadiationBaseFacet::thermal, and jeod::ThermalFacetRider::thermal_power_dump.
Referenced by jeod::RadiationPressure::update_default_surface().
Friends And Related Function Documentation
init_attrjeod__RadiationDefaultSurface
void init_attrjeod__RadiationDefaultSurface () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file radiation_default_surface.hh.
Field Documentation
name
std::string jeod::RadiationDefaultSurface::name
The name of the surface.
This is optional.trick_units(–)
Definition at line 119 of file radiation_default_surface.hh.
Referenced by set_name().
rad_coeff
double jeod::RadiationDefaultSurface::rad_coeff
The radiation-equivalent of a drag coefficient.
It is the value by which the area must be multiplied in order to generate the same force if the reflecting surface were considered a perfectly absorbing surface. For a sphere, this has a value between 1.0 (perfectly absorbing, or perfect specular reflection) to 1.4444 (all diffuse reflection). Specify either: rad_coeff OR (albedo AND diffuse). NOTE 1 - this value is used at initialization only; changes to its value mid-simulation cannot be effected. NOTE 2 - the values albedo and diffuse are inherited from RadiationBaseFacet.trick_units(–)
Definition at line 109 of file radiation_default_surface.hh.
Referenced by initialize(), and RadiationDefaultSurface().
surface_area
double jeod::RadiationDefaultSurface::surface_area
surface area of the default sphere.
trick_units(m2)
Definition at line 129 of file radiation_default_surface.hh.
Referenced by initialize(), and RadiationDefaultSurface().
temperature
double jeod::RadiationDefaultSurface::temperature
The value of the surface kinetic temperature.
trick_units(K)
Definition at line 114 of file radiation_default_surface.hh.
Referenced by initialize(), RadiationDefaultSurface(), and thermal_update().
The documentation for this class was generated from the following files:
radiation_default_surface.hh
radiation_default_surface.cc