JEOD: jeod::PropagatedPlanet Class Reference
jeod::PropagatedPlanet Class Reference
The PropagatedPlanet ephemeris model provides planetary state via a DynBody object whose state is propagated using the JEOD state integration techniques.
#include <propagated_planet.hh>
Public Types
enum Mode { TransFromPlanet_RotFromPlanet = 0, TransFromPlanet_RotFromBody = 1, TransFromBody_RotFromPlanet = 2, TransFromBody_RotFromBody = 3 }
Defines the modes in which an active PropagatedPlanet object operates.
Public Member Functions
PropagatedPlanet (void)
PropagatedPlanet default constructor.
~PropagatedPlanet (void) override
PropagatedPlanet destructor.
void initialize_model (const TimeManager &time_manager, DynManager &dyn_manager)
Initialize a PropagatedPlanet model.
void shutdown (void)
Free resources allocated by the PropagatedPlanet model.
void activate (void) override
Nominally, activate the object.
void deactivate (void) override
Deactivate the PropagatedPlanet object.
double timestamp (void) const override
Return time of last update.
const char * get_name (void) const override
Return model name.
void ephem_initialize (EphemeridesManager &ephem_manager) override
Mark appropriate items in the model as active.
void ephem_activate (EphemeridesManager &ephem_manager) override
Activate ephemerides.
void ephem_build_tree (EphemeridesManager &ephem_manager) override
Construct the ephemeris model portions of the reference frame tree.
void ephem_update (void) override
Update ephemerides for subscribed items.
void set_commanded_mode (Mode new_mode)
Setter for the commanded mode.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface (void) override
Destructor; there is nothing to destroy here.
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()
Default constructor.
virtual ~ActivateInterface ()
Destructor.
Data Fields
char * planet_name
The name of the planet.
char * parent_name
The name of the parent frame.
DynBody body
The dynamic body whose state is tied to that of the planet.
Mode commanded_mode
The mode in which the model should operate.
Protected Member Functions
void set_mode (void)
Change the behavior of a PropagatedPlanet.
Protected Attributes
bool initialized
Has the model been initialized?
Mode mode
The mode in which the model is operating.
char * ident
Model name; used for reporting errors.
bool active
Is the planet present and marked as active?
double update_time
Time of last update, dynamic time seconds.
BasePlanet * planet
The planet tied to the body.
EphemerisRefFrame * parent_frame
The parent of the planet.
DynManager * dyn_manager
The dynamics manager.
const TimeDyn * time_dyn
The source of dynamic time information.
PropagatedEphemerisPlanet ephem_planet
The ephemeris item that couples the translational states of the body's composite body frame and the planet's inertial frame.
PropagatedEphemerisOrientation ephem_orient
The ephemeris item that couples the rotational states of the body's composite body frame and the planet's planet-fixed frame.
Private Member Functions
PropagatedPlanet (const PropagatedPlanet &)
Not implemented.
PropagatedPlanet & operator= (const PropagatedPlanet &)
Not implemented.
Friends
class InputProcessor
void init_attrjeod__PropagatedPlanet ()
Detailed Description
The PropagatedPlanet ephemeris model provides planetary state via a DynBody object whose state is propagated using the JEOD state integration techniques.
Scenarios in which a simulation will use a PropagatedPlanet object include:
An object such as an asteroid for which an ephemeris model is not readily available.
An object such as a planet that is represented in some other ephemeris model but the simulation developer wants the planet to be propagated to ensure that the planet and the vehicles operating in the vicinity of the planet obey the same laws of physics.
The PropagatedPlanet model provides mechanisms that accommodate these scenarios. The class defines multiple modes in which a propagated planet planet object operates. In all modes, the model ensures consistency between the translational states of the dynamic body's composite frame and the planet's planet-centered frame and between the rotational states of the dynamic body's composite frame and the planet's planet-fixed frame.
Definition at line 246 of file propagated_planet.hh.
Member Enumeration Documentation
Mode
enum jeod::PropagatedPlanet::Mode
Defines the modes in which an active PropagatedPlanet object operates.
A PropagatedPlanet contains a BasePlanet pointer PropagatedPlanet::planet and a DynBody PropagatedPlanet::body. The translational states of the planet-centered inertial frame and the body's composite_body frame are tied to one another, as are the rotational states of the planet-fixed frame and the the body's composite_body frame. This enum identifies which of the planet or the body is the source of translational and the the rotational parts of the state.
Enumerator
TransFromPlanet_RotFromPlanet
TransFromPlanet_RotFromBody
TransFromBody_RotFromPlanet
TransFromBody_RotFromBody
Definition at line 263 of file propagated_planet.hh.
Constructor & Destructor Documentation
PropagatedPlanet() [1/2]
jeod::PropagatedPlanet::PropagatedPlanet (void)
PropagatedPlanet default constructor.
Definition at line 203 of file propagated_planet.cc.
References ephem_orient, ephem_planet, and jeod::EphemerisItem::set_owner().
~PropagatedPlanet()
jeod::PropagatedPlanet::~PropagatedPlanet (void) override
PropagatedPlanet destructor.
Definition at line 230 of file propagated_planet.cc.
References shutdown().
PropagatedPlanet() [2/2]
jeod::PropagatedPlanet::PropagatedPlanet (const PropagatedPlanet &) private
Not implemented.
Member Function Documentation
activate()
void jeod::PropagatedPlanet::activate (void) override virtual
Nominally, activate the object.
In the case of a PropagatedPlanet object, an inactive object cannot be activated.
Implements jeod::ActivateInterface.
Definition at line 258 of file propagated_planet.cc.
References active, jeod::MessageHandler::error(), and jeod::EphemeridesMessages::internal_error.
deactivate()
void jeod::PropagatedPlanet::deactivate (void) override virtual
Deactivate the PropagatedPlanet object.
Implements jeod::ActivateInterface.
Definition at line 275 of file propagated_planet.cc.
References active.
ephem_activate()
void jeod::PropagatedPlanet::ephem_activate (EphemeridesManager & ephem_manager) override virtual
Activate ephemerides.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 512 of file propagated_planet.cc.
References body, mode, jeod::DynBody::rotational_dynamics, TransFromBody_RotFromBody, TransFromBody_RotFromPlanet, TransFromPlanet_RotFromBody, and jeod::DynBody::translational_dynamics.
ephem_build_tree()
void jeod::PropagatedPlanet::ephem_build_tree (EphemeridesManager & ephem_manager) override virtual
Construct the ephemeris model portions of the reference frame tree.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 534 of file propagated_planet.cc.
References active, jeod::RefFrameManager::add_frame_to_tree(), jeod::RefFrame::get_parent(), jeod::BasePlanet::inertial, parent_frame, planet, and jeod::RefFrame::remove_from_parent().
ephem_initialize()
void jeod::PropagatedPlanet::ephem_initialize (EphemeridesManager & ephem_manager) override virtual
Mark appropriate items in the model as active.
Parameters
[in,out] ephem_manager Ephemerides manager
Implements jeod::EphemerisInterface.
Definition at line 396 of file propagated_planet.cc.
References active, ephem_orient, ephem_planet, jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_base_planet(), jeod::EphemerisItem::get_target_frame(), jeod::EphemeridesMessages::inconsistent_setup, jeod::BasePlanet::inertial, jeod::BasePlanet::pfix, planet, planet_name, set_mode(), jeod::EphemeridesManager::set_target_frame(), and jeod::Subscription::subscribe().
ephem_update()
void jeod::PropagatedPlanet::ephem_update (void) override virtual
Update ephemerides for subscribed items.
Implements jeod::EphemerisInterface.
Definition at line 555 of file propagated_planet.cc.
References active, body, commanded_mode, dyn_manager, ephem_orient, ephem_planet, jeod::DynManager::initialize_dyn_body(), initialized, mode, jeod::DynBody::propagate_state(), jeod::JeodBaseTime::seconds, set_mode(), time_dyn, TransFromBody_RotFromBody, jeod::PropagatedEphemerisPlanet::update(), jeod::PropagatedEphemerisOrientation::update(), and update_time.
get_name()
const char * jeod::PropagatedPlanet::get_name (void) const override virtual
Return model name.
Returns
Name
Implements jeod::EphemerisInterface.
Definition at line 302 of file propagated_planet.cc.
References ident.
initialize_model()
void jeod::PropagatedPlanet::initialize_model (const TimeManager & time_manager, DynManager & dyn_manager_ref)
Initialize a PropagatedPlanet model.
Assumptions and Limitations
This method must be called after the ephemeris model that defines the parent frame has been initialized.
Parameters
[in] time_manager Time manager
[in,out] dyn_manager_ref Dynamics manager
Definition at line 320 of file propagated_planet.cc.
References active, jeod::EphemeridesManager::add_ephem_item(), jeod::EphemeridesManager::add_ephemeris(), body, jeod::NamedItem::construct_name(), dyn_manager, ephem_orient, ephem_planet, jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_integ_frame(), jeod::TimeManager::get_time_ptr(), ident, jeod::EphemeridesMessages::inconsistent_setup, jeod::DynBody::initialize_model(), jeod::DynBody::integ_frame_name, jeod::DynBody::name, parent_frame, parent_name, planet_name, jeod::EphemerisItem::set_name(), jeod::NamedItem::set_name(), jeod::NamedItem::size(), and time_dyn.
operator=()
PropagatedPlanet& jeod::PropagatedPlanet::operator= (const PropagatedPlanet &) private
Not implemented.
set_commanded_mode()
void jeod::PropagatedPlanet::set_commanded_mode (PropagatedPlanet::Mode new_mode)
Setter for the commanded mode.
Parameters
[in] new_mode New commanded mode
Definition at line 453 of file propagated_planet.cc.
References commanded_mode.
set_mode()
void jeod::PropagatedPlanet::set_mode (void) protected
Change the behavior of a PropagatedPlanet.
Definition at line 464 of file propagated_planet.cc.
References commanded_mode, jeod::EphemerisItem::disable(), dyn_manager, jeod::EphemerisOrientation::enable(), jeod::EphemerisItem::enable(), jeod::EphemeridesManager::ephem_note_tree_status_change(), ephem_orient, ephem_planet, jeod::MessageHandler::fail(), jeod::EphemeridesMessages::inconsistent_setup, mode, TransFromBody_RotFromBody, TransFromBody_RotFromPlanet, TransFromPlanet_RotFromBody, and TransFromPlanet_RotFromPlanet.
Referenced by ephem_initialize(), and ephem_update().
shutdown()
void jeod::PropagatedPlanet::shutdown (void)
Free resources allocated by the PropagatedPlanet model.
Definition at line 241 of file propagated_planet.cc.
References ident, and JEOD_DELETE_ARRAY.
Referenced by ~PropagatedPlanet().
timestamp()
double jeod::PropagatedPlanet::timestamp (void) const override virtual
Return time of last update.
Returns
Timestamp
Units: day
Implements jeod::EphemerisInterface.
Definition at line 289 of file propagated_planet.cc.
References update_time.
Friends And Related Function Documentation
init_attrjeod__PropagatedPlanet
void init_attrjeod__PropagatedPlanet () friend
InputProcessor
friend class InputProcessor friend
Definition at line 247 of file propagated_planet.hh.
Field Documentation
active
bool jeod::PropagatedPlanet::active protected
Is the planet present and marked as active?
trick_units(–)
Definition at line 378 of file propagated_planet.hh.
Referenced by activate(), deactivate(), ephem_build_tree(), ephem_initialize(), ephem_update(), and initialize_model().
body
DynBody jeod::PropagatedPlanet::body
The dynamic body whose state is tied to that of the planet.
trick_units(–)
Definition at line 342 of file propagated_planet.hh.
Referenced by ephem_activate(), ephem_update(), and initialize_model().
commanded_mode
Mode jeod::PropagatedPlanet::commanded_mode
The mode in which the model should operate.
trick_units(–)
Definition at line 347 of file propagated_planet.hh.
Referenced by ephem_update(), set_commanded_mode(), and set_mode().
dyn_manager
DynManager* jeod::PropagatedPlanet::dyn_manager protected
The dynamics manager.
trick_units(–)
Definition at line 398 of file propagated_planet.hh.
Referenced by ephem_update(), initialize_model(), and set_mode().
ephem_orient
PropagatedEphemerisOrientation jeod::PropagatedPlanet::ephem_orient protected
The ephemeris item that couples the rotational states of the body's composite body frame and the planet's planet-fixed frame.
trick_units(–)
Definition at line 415 of file propagated_planet.hh.
Referenced by ephem_initialize(), ephem_update(), initialize_model(), PropagatedPlanet(), and set_mode().
ephem_planet
PropagatedEphemerisPlanet jeod::PropagatedPlanet::ephem_planet protected
The ephemeris item that couples the translational states of the body's composite body frame and the planet's inertial frame.
trick_units(–)
Definition at line 409 of file propagated_planet.hh.
Referenced by ephem_initialize(), ephem_update(), initialize_model(), PropagatedPlanet(), and set_mode().
ident
char* jeod::PropagatedPlanet::ident protected
Model name; used for reporting errors.
trick_units(–)
Definition at line 373 of file propagated_planet.hh.
Referenced by get_name(), initialize_model(), and shutdown().
initialized
bool jeod::PropagatedPlanet::initialized protected
Has the model been initialized?
trick_units(–)
Definition at line 363 of file propagated_planet.hh.
Referenced by ephem_update().
mode
Mode jeod::PropagatedPlanet::mode protected
The mode in which the model is operating.
trick_units(–)
Definition at line 368 of file propagated_planet.hh.
Referenced by ephem_activate(), ephem_update(), and set_mode().
parent_frame
EphemerisRefFrame* jeod::PropagatedPlanet::parent_frame protected
The parent of the planet.
trick_units(–)
Definition at line 393 of file propagated_planet.hh.
Referenced by ephem_build_tree(), and initialize_model().
parent_name
char* jeod::PropagatedPlanet::parent_name
The name of the parent frame.
This is used at initialization time only.trick_units(–)
Definition at line 337 of file propagated_planet.hh.
Referenced by initialize_model().
planet
BasePlanet* jeod::PropagatedPlanet::planet protected
The planet tied to the body.
trick_units(–)
Definition at line 388 of file propagated_planet.hh.
Referenced by ephem_build_tree(), and ephem_initialize().
planet_name
char* jeod::PropagatedPlanet::planet_name
The name of the planet.
This is used at initialization time only.trick_units(–)
Definition at line 331 of file propagated_planet.hh.
Referenced by ephem_initialize(), and initialize_model().
time_dyn
const TimeDyn* jeod::PropagatedPlanet::time_dyn protected
The source of dynamic time information.
trick_units(–)
Definition at line 403 of file propagated_planet.hh.
Referenced by ephem_update(), and initialize_model().
update_time
double jeod::PropagatedPlanet::update_time protected
Time of last update, dynamic time seconds.
trick_units(s)
Definition at line 383 of file propagated_planet.hh.
Referenced by ephem_update(), and timestamp().
The documentation for this class was generated from the following files:
propagated_planet.hh
propagated_planet.cc