JEOD: jeod::PropagatedEphemerisOrientation Class Reference
jeod::PropagatedEphemerisOrientation Class Reference
A PropagatedEphemerisOrientation is an EphemerisOrientation whose state is coupled with the rotational state of a DynBody reference frame.
#include <propagated_planet.hh>
Public Member Functions
PropagatedEphemerisOrientation (DynBody &dyn_body, BodyRefFrame &frame)
PropagatedEphemerisOrientation non-default constructor.
~PropagatedEphemerisOrientation () override=default
PropagatedEphemerisOrientation (const PropagatedEphemerisOrientation &)=delete
PropagatedEphemerisOrientation & operator= (const PropagatedEphemerisOrientation &)=delete
virtual void update (double time)
Copy rotational state from/to the body reference frame.
Public Member Functions inherited from jeod::EphemerisOrientation
EphemerisOrientation ()=default
~EphemerisOrientation () override=default
EphemerisOrientation (const EphemerisOrientation &)=delete
EphemerisOrientation & operator= (const EphemerisOrientation &)=delete
TargetAspect updates_what () const override
Specify the aspect of the target frame updated by the object.
void enable () override
Enable a EphemerisItem object.
void note_frame_status_change (RefFrame *frame) override
Null implementation.
std::string default_suffix () const override
Return the default suffix for this item class, i.e., "pfix".
void disconnect_from_tree () override
Disconnect the item from the tree; this is a no-op for an EphemerisOrientation.
Public Member Functions inherited from jeod::EphemerisItem
EphemerisItem ()=default
~EphemerisItem () override=default
EphemerisItem (const EphemerisItem &)=delete
EphemerisItem & operator= (const EphemerisItem &)=delete
virtual void set_name (const std::string &new_name)
Name an ephemeris item.
virtual void set_name (const std::string &pname, const std::string &fname)
Name an ephemeris item.
std::string get_name () const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this item.
double timestamp () const
Return the update time of this item.
virtual void set_owner (EphemerisInterface *new_owner)
Set the owner of this item.
EphemerisInterface * get_owner () const
Return the owner of this item.
virtual void set_manager (BaseEphemeridesManager *new_manager)
Set the manager of this item.
BaseEphemeridesManager * get_manager () const
Return the manager of this item.
virtual void set_next (EphemerisItem *next_item)
Set the next item.
EphemerisItem * get_next () const
Get the next item.
virtual void set_head (EphemerisItem *head_item)
Set the head item.
EphemerisItem * get_head () const
Get the head item.
virtual void set_target_frame (EphemerisRefFrame &frame)
Set the target frame.
EphemerisRefFrame * get_target_frame () const
Get the target frame.
virtual void disable ()
Disable an EphemerisItem object.
bool is_enabled () const
Return enabled status.
EphemerisItem * get_enabled_item () const
Get the item marked as enabled, if any.
virtual void activate ()
Activate a EphemerisItem object.
virtual void deactivate ()
Deactivate a EphemerisItem object.
bool is_active () const
Return activity status.
bool is_activatable () const
Is the item activatable?
void validate_name (const char *file, unsigned int line, const std::string &new_value, const std::string &old_value, const std::string &variable_name)
Name an ephemeris item.
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
Protected Attributes
DynBody & body
The dynamic body whose state is tied to that of the planet.
BodyRefFrame & body_ref_frame
The body reference frame whose rotational state is coupled with that of the planet's planet-fixed frame.
Protected Attributes inherited from jeod::EphemerisOrientation
bool subscribed_to_inertial {}
A subscription to the planet's inertial frame is issued whenever the planet's planet-fixed frame is active to ensure that the the planet-fixed frame is a part of the ref frame tree.
Protected Attributes inherited from jeod::EphemerisItem
std::string name
The name of the item.
EphemerisInterface * owner {}
The ephemeris model that owns this object.
BaseEphemeridesManager * manager {}
The ephemeris manager that manages this object.
EphemerisRefFrame * target_frame {}
The reference frame whose non-constant state is set by this object.
EphemerisItem * head {}
The first ephemeris item with the same name as this item.
EphemerisItem * next {}
The next ephemeris item with the same name as this item.
double update_time {}
Time of last update, dynamic time seconds.
bool enabled {}
Is the item enabled?
bool active {}
Is the item active?
Friends
class InputProcessor
void init_attrjeod__PropagatedEphemerisOrientation ()
Additional Inherited Members
Public Types inherited from jeod::EphemerisItem
enum TargetAspect { Translation = 0, Rotation = 1 }
Defines the aspect of the target frame that will be modified by the EphemerisItem object.
Protected Member Functions inherited from jeod::EphemerisItem
virtual void set_name_internal (const std::string &new_name)
Name an ephemeris item.
Detailed Description
A PropagatedEphemerisOrientation is an EphemerisOrientation whose state is coupled with the rotational state of a DynBody reference frame.
This class is intended for use by the PropagatedPlanet class. Use outside of the PropagatedPlanet is not sanctioned.
The class acts analogously to the class PropagatedEphemerisPlanet, but for rotation rather than translation. See PropagatedEphemerisPlanet for a description of the behavior of the class.
Definition at line 155 of file propagated_planet.hh.
Constructor & Destructor Documentation
PropagatedEphemerisOrientation() [1/2]
jeod::PropagatedEphemerisOrientation::PropagatedEphemerisOrientation (DynBody & dyn_body, BodyRefFrame & frame)
PropagatedEphemerisOrientation non-default constructor.
Parameters
[in,out] dyn_body The DynBody that represents the planet
[in,out] frame The body reference frame
Definition at line 112 of file propagated_planet.cc.
~PropagatedEphemerisOrientation()
jeod::PropagatedEphemerisOrientation::~PropagatedEphemerisOrientation () override default
PropagatedEphemerisOrientation() [2/2]
jeod::PropagatedEphemerisOrientation::PropagatedEphemerisOrientation (const PropagatedEphemerisOrientation &) delete
Member Function Documentation
operator=()
PropagatedEphemerisOrientation& jeod::PropagatedEphemerisOrientation::operator= (const PropagatedEphemerisOrientation &) delete
update()
void jeod::PropagatedEphemerisOrientation::update (double dyn_time) virtual
Copy rotational state from/to the body reference frame.
Parameters
[in] dyn_time Dynamic time seconds
Units: s
Definition at line 123 of file propagated_planet.cc.
References jeod::RefFrameItems::Att_Rate, body, body_ref_frame, jeod::RefFrame::compute_relative_state(), jeod::EphemerisItem::enabled, jeod::RefFrame::get_parent(), jeod::RefFrameState::rot, jeod::DynBody::set_state(), jeod::RefFrame::set_timestamp(), jeod::RefFrame::state, jeod::EphemerisItem::target_frame, and jeod::EphemerisItem::update_time.
Referenced by jeod::PropagatedPlanet::ephem_update().
Friends And Related Function Documentation
init_attrjeod__PropagatedEphemerisOrientation
void init_attrjeod__PropagatedEphemerisOrientation () friend
InputProcessor
friend class InputProcessor friend
Definition at line 157 of file propagated_planet.hh.
Field Documentation
body
DynBody& jeod::PropagatedEphemerisOrientation::body protected
The dynamic body whose state is tied to that of the planet.
trick_units(–)
Definition at line 172 of file propagated_planet.hh.
Referenced by update().
body_ref_frame
BodyRefFrame& jeod::PropagatedEphemerisOrientation::body_ref_frame protected
The body reference frame whose rotational state is coupled with that of the planet's planet-fixed frame.
trick_units(–)
Definition at line 178 of file propagated_planet.hh.
Referenced by update().
The documentation for this class was generated from the following files:
propagated_planet.hh
propagated_planet.cc