def log_3_vec(drg, var):
  for ii in range(3):
    drg.add_variable( var + "[" + str(ii) + "]")

dr_group = trick.sim_services.DRAscii("rot_state")
dr_group.set_cycle(1)
dr_group.freq = trick.sim_services.DR_Always
trick.add_data_record_group(dr_group)

dr_group.add_variable("body1.dyn_body.mass.composite_properties.mass")
log_3_vec(dr_group,   "body1.dyn_body.mass.composite_properties.inertia[0]")
log_3_vec(dr_group,   "body1.dyn_body.mass.composite_properties.inertia[1]")
log_3_vec(dr_group,   "body1.dyn_body.mass.composite_properties.inertia[2]")
log_3_vec(dr_group,   "body1.dyn_body.mass.composite_properties.position")
dr_group.add_variable("body1.dyn_body.mass.core_properties.mass")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.inertia[0]")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.inertia[1]")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.inertia[2]")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.position")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.T_parent_this[0]")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.T_parent_this[1]")
log_3_vec(dr_group,   "body1.dyn_body.mass.core_properties.T_parent_this[2]")
dr_group.add_variable("body2.dyn_body.mass.core_properties.mass")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.inertia[0]")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.inertia[1]")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.inertia[2]")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.position")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.T_parent_this[0]")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.T_parent_this[1]")
log_3_vec(dr_group,   "body2.dyn_body.mass.core_properties.T_parent_this[2]")
log_3_vec(dr_group,   "body2.effector_forc1.force")
log_3_vec(dr_group,   "body2.environ_forc1.force")
log_3_vec(dr_group,   "body2.environ_forc2.force")
log_3_vec(dr_group,   "body2.no_xmit_forc1.force")
log_3_vec(dr_group,   "body2.no_xmit_forc2.force")
log_3_vec(dr_group,   "body2.no_xmit_forc3")
log_3_vec(dr_group,   "body2.effector_torq1.torque")
log_3_vec(dr_group,   "body2.environ_torq1.torque")
log_3_vec(dr_group,   "body2.environ_torq2.torque")
log_3_vec(dr_group,   "body2.no_xmit_torq1.torque")
log_3_vec(dr_group,   "body2.no_xmit_torq2.torque")
log_3_vec(dr_group,   "body2.no_xmit_torq3")
log_3_vec(dr_group,   "body2.dyn_body.collect.effector_forc")
log_3_vec(dr_group,   "body2.dyn_body.collect.environ_forc")
log_3_vec(dr_group,   "body2.dyn_body.collect.no_xmit_forc")
log_3_vec(dr_group,   "body2.dyn_body.collect.extern_forc_struct")
log_3_vec(dr_group,   "body2.dyn_body.collect.extern_forc_inrtl")
log_3_vec(dr_group,   "body2.dyn_body.collect.effector_torq")
log_3_vec(dr_group,   "body2.dyn_body.collect.environ_torq")
log_3_vec(dr_group,   "body2.dyn_body.collect.no_xmit_torq")
log_3_vec(dr_group,   "body2.dyn_body.collect.inertial_torq")
log_3_vec(dr_group,   "body2.dyn_body.collect.extern_torq_struct")
log_3_vec(dr_group,   "body2.dyn_body.collect.extern_torq_body")
log_3_vec(dr_group,   "body1.no_xmit_forc1.force")
log_3_vec(dr_group,   "body1.no_xmit_torq1.torque")
log_3_vec(dr_group,   "body1.dyn_body.collect.effector_forc")
log_3_vec(dr_group,   "body1.dyn_body.collect.environ_forc")
log_3_vec(dr_group,   "body1.dyn_body.collect.no_xmit_forc")
log_3_vec(dr_group,   "body1.dyn_body.collect.extern_forc_struct")
log_3_vec(dr_group,   "body1.dyn_body.collect.extern_forc_inrtl")
log_3_vec(dr_group,   "body1.dyn_body.collect.effector_torq")
log_3_vec(dr_group,   "body1.dyn_body.collect.environ_torq")
log_3_vec(dr_group,   "body1.dyn_body.collect.no_xmit_torq")
log_3_vec(dr_group,   "body1.dyn_body.collect.inertial_torq")
log_3_vec(dr_group,   "body1.dyn_body.collect.extern_torq_struct")
log_3_vec(dr_group,   "body1.dyn_body.collect.extern_torq_body")
log_3_vec(dr_group,   "body1.dyn_body.derivs.trans_accel")
log_3_vec(dr_group,   "body1.dyn_body.composite_body.state.trans.velocity")
log_3_vec(dr_group,   "body1.dyn_body.composite_body.state.trans.position")
log_3_vec(dr_group,   "body1.dyn_body.structure.state.trans.velocity")
log_3_vec(dr_group,   "body1.dyn_body.structure.state.trans.position")
log_3_vec(dr_group,   "body2.dyn_body.derivs.trans_accel")
log_3_vec(dr_group,   "body2.dyn_body.composite_body.state.trans.velocity")
log_3_vec(dr_group,   "body2.dyn_body.composite_body.state.trans.position")
log_3_vec(dr_group,   "body2.dyn_body.structure.state.trans.velocity")
log_3_vec(dr_group,   "body2.dyn_body.structure.state.trans.position")
log_3_vec(dr_group,   "body1.dyn_body.derivs.rot_accel")
log_3_vec(dr_group,   "body1.dyn_body.composite_body.state.rot.ang_vel_this")
log_3_vec(dr_group,   "body1.dyn_body.composite_body.state.rot.T_parent_this[0]")
log_3_vec(dr_group,   "body1.dyn_body.composite_body.state.rot.T_parent_this[1]")
log_3_vec(dr_group,   "body1.dyn_body.composite_body.state.rot.T_parent_this[2]")
