JEOD: jeod::TimeConverter_Dyn_UDE Class Reference
jeod::TimeConverter_Dyn_UDE Class Reference
Define class TimeConverter_Dyn_UDE, which converts from simulation dynamic time to any specific instance of the generic User-Defined-Epoch Time.
#include <time_converter_dyn_ude.hh>
Public Member Functions
TimeConverter_Dyn_UDE ()
Construct a TimeConverter_Dyn_UDE.
~TimeConverter_Dyn_UDE () override
Destroy a TimeConverter_Dyn_UDE.
void reset_a_to_b_offset (void) override
Resets the value of a_to_b_offset.
void initialize (JeodBaseTime *parent, JeodBaseTime *child, const int direction) override
Initialize the converter.
void convert_a_to_b (void) override
Convert from TimeDyn to TimeUDE.
Public Member Functions inherited from jeod::TimeConverter
virtual ~TimeConverter ()
Destroy a TimeConverter.
virtual bool is_initialized (void)
Return internal initialized status bool.
void override_initialized (bool init)
bool can_convert (Direction query)
Check whether this converter is able to handle the requested conversion(s).
virtual void convert_b_to_a (void)
Default converter from time 'b' to time 'a'.
virtual void verify_table_lookup_ends (void)
This function does absolutely nothing.
double get_a_to_b_offset (void)
Return the offset from the parent time object to this object.
Private Member Functions
TimeConverter_Dyn_UDE (const TimeConverter_Dyn_UDE &)
TimeConverter_Dyn_UDE & operator= (const TimeConverter_Dyn_UDE &)
Private Attributes
TimeDyn * dyn_ptr
Converter parent time, always a TimeDyn for this converter.
TimeUDE * ude_ptr
Converter child time, always a TimeUDE for this converter.
Friends
class InputProcessor
void init_attrjeod__TimeConverter_Dyn_UDE ()
Additional Inherited Members
Public Types inherited from jeod::TimeConverter
enum Direction {
NO_DIRECTION = 0x0000, A_TO_B_INIT = 0x0001, B_TO_A_INIT = 0x0010, A_TO_B_UPDATE = 0x0100,
B_TO_A_UPDATE = 0x1000, A_TO_B = 0x0101, B_TO_A = 0x1010, ANY_DIRECTION = 0x1111
}
Possible conversion directions.
Data Fields inherited from jeod::TimeConverter
std::string a_name
name of time-type "a".
std::string b_name
name of time-type "b".
Protected Member Functions inherited from jeod::TimeConverter
TimeConverter ()
Construct a TimeConverter.
void verify_setup (const JeodBaseTime *parent, const JeodBaseTime *child, const int direction)
Verify the setup.
Protected Attributes inherited from jeod::TimeConverter
bool initialized
whether converter has been initialized.
double a_to_b_offset
Difference between the two time-types.
Direction valid_directions
Bit packed flag specifying whether how a converter can be used.
Detailed Description
Define class TimeConverter_Dyn_UDE, which converts from simulation dynamic time to any specific instance of the generic User-Defined-Epoch Time.
Definition at line 91 of file time_converter_dyn_ude.hh.
Constructor & Destructor Documentation
TimeConverter_Dyn_UDE() [1/2]
jeod::TimeConverter_Dyn_UDE::TimeConverter_Dyn_UDE (void)
Construct a TimeConverter_Dyn_UDE.
Definition at line 58 of file time_converter_dyn_ude.cc.
References jeod::TimeConverter::a_name, jeod::TimeConverter::A_TO_B, jeod::TimeConverter::b_name, dyn_ptr, ude_ptr, and jeod::TimeConverter::valid_directions.
~TimeConverter_Dyn_UDE()
jeod::TimeConverter_Dyn_UDE::~TimeConverter_Dyn_UDE (void) override
Destroy a TimeConverter_Dyn_UDE.
Definition at line 168 of file time_converter_dyn_ude.cc.
TimeConverter_Dyn_UDE() [2/2]
jeod::TimeConverter_Dyn_UDE::TimeConverter_Dyn_UDE (const TimeConverter_Dyn_UDE &) private
Member Function Documentation
convert_a_to_b()
void jeod::TimeConverter_Dyn_UDE::convert_a_to_b (void) override virtual
Convert from TimeDyn to TimeUDE.
Assumptions and Limitations
Time class UDE is based on time class TAI, and counts the elapsed TAI time only
Reimplemented from jeod::TimeConverter.
Definition at line 144 of file time_converter_dyn_ude.cc.
References jeod::TimeConverter::a_to_b_offset, dyn_ptr, jeod::JeodBaseTime::seconds, jeod::TimeUDE::set_time_by_seconds(), and ude_ptr.
initialize()
void jeod::TimeConverter_Dyn_UDE::initialize (JeodBaseTime * parent_ptr, JeodBaseTime * child_ptr, const int int_dir) override virtual
Initialize the converter.
Assumptions and Limitations
This class converts from TimeDyn to TimeUDE only
Parameters
[in] parent_ptr Time used to initialize the converter
[in] child_ptr Other Time used to initialize the converter
[in] int_dir Conversion direction: +1 a=parent; -1 b=parent; 0 error
Implements jeod::TimeConverter.
Definition at line 79 of file time_converter_dyn_ude.cc.
References jeod::TimeConverter::a_to_b_offset, jeod::NamedItem::c_str(), dyn_ptr, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeConverter::initialized, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, jeod::JeodBaseTime::seconds, ude_ptr, and jeod::TimeConverter::verify_setup().
operator=()
TimeConverter_Dyn_UDE& jeod::TimeConverter_Dyn_UDE::operator= (const TimeConverter_Dyn_UDE &) private
reset_a_to_b_offset()
void jeod::TimeConverter_Dyn_UDE::reset_a_to_b_offset (void) override virtual
Resets the value of a_to_b_offset.
Reimplemented from jeod::TimeConverter.
Definition at line 158 of file time_converter_dyn_ude.cc.
References jeod::TimeConverter::a_to_b_offset, dyn_ptr, jeod::JeodBaseTime::seconds, and ude_ptr.
Friends And Related Function Documentation
init_attrjeod__TimeConverter_Dyn_UDE
void init_attrjeod__TimeConverter_Dyn_UDE () friend
InputProcessor
friend class InputProcessor friend
Definition at line 93 of file time_converter_dyn_ude.hh.
Field Documentation
dyn_ptr
TimeDyn* jeod::TimeConverter_Dyn_UDE::dyn_ptr private
Converter parent time, always a TimeDyn for this converter.
trick_units(–)
Definition at line 100 of file time_converter_dyn_ude.hh.
Referenced by convert_a_to_b(), initialize(), reset_a_to_b_offset(), and TimeConverter_Dyn_UDE().
ude_ptr
TimeUDE* jeod::TimeConverter_Dyn_UDE::ude_ptr private
Converter child time, always a TimeUDE for this converter.
trick_units(–)
Definition at line 105 of file time_converter_dyn_ude.hh.
Referenced by convert_a_to_b(), initialize(), reset_a_to_b_offset(), and TimeConverter_Dyn_UDE().
The documentation for this class was generated from the following files:
time_converter_dyn_ude.hh
time_converter_dyn_ude.cc