JEOD: jeod::De4xxBase Namespace Reference
jeod::De4xxBase Namespace Reference
Defines enumerations used in the DE4xx ephemeris model.
Enumerations
enum De4xxFileEntries {
De4xx_File_Mercury = 0, De4xx_File_Venus = 1, De4xx_File_EMbary = 2, De4xx_File_Mars = 3,
De4xx_File_Jupiter = 4, De4xx_File_Saturn = 5, De4xx_File_Uranus = 6, De4xx_File_Neptune = 7,
De4xx_File_Pluto = 8, De4xx_File_Moon = 9, De4xx_File_Sun = 10, De4xx_File_ENutation = 11,
De4xx_File_LLibration = 12, De4xx_File_LAngVel = 13, De4xx_File_tt_tdb = 14, De4xx_File_MaxEntries
}
Defines names for planetary body descriptors in the ephemeris file.
enum De4xxEphemConsts {
De4xx_Const_DENUM = 0, De4xx_Const_LENUM, De4xx_Const_AU, De4xx_Const_EMRAT,
De4xx_Const_CLIGHT, De4xx_Const_GM1, De4xx_Const_GM2, De4xx_Const_GMB,
De4xx_Const_GM4, De4xx_Const_GM5, De4xx_Const_GM6, De4xx_Const_GM7,
De4xx_Const_GM8, De4xx_Const_GM9, De4xx_Const_GMS, De4xx_Const_MaxConsts
}
Index aliases for the constants listed in the DE header that are used by JEOD.
enum De4xxEphemBodies {
De4xx_Ephem_Sun = 0, De4xx_Ephem_Mercury = 1, De4xx_Ephem_Venus = 2, De4xx_Ephem_Earth = 3,
De4xx_Ephem_Mars = 4, De4xx_Ephem_Jupiter = 5, De4xx_Ephem_Saturn = 6, De4xx_Ephem_Uranus = 7,
De4xx_Ephem_Neptune = 8, De4xx_Ephem_Pluto = 9, De4xx_Ephem_Moon = 10, De4xx_Ephem_EMbary = 11,
De4xx_Ephem_SSbary = 12, De4xx_Ephem_EML1 = 13, De4xx_Ephem_ENutation = 14, De4xx_Ephem_LLibration = 15,
De4xx_Ephem_MaxBodies
}
Defines names for ephemeris items as represented in the JEOD DE4xx model.
Functions
static const char *point_names [32] __attribute__ ((unused))
static uint32_t number_jeod_items (int de_version_num __attribute__((unused)))
Total number of items in the JEOD ephemeris.
static uint32_t number_trans_points (int de_version_num __attribute__((unused)))
Total number of translational states in the JEOD ephemeris.
static uint32_t number_grav_models (int de_version_num __attribute__((unused)))
Number of gravity models in the JEOD ephemeris (Mercury to Sun + implied Earth) Currently only one possibility, but written for extensibility.
static uint32_t number_physical_bodies (int de_version_num __attribute__((unused)))
Number of bodies in the JEOD ephemeris (Planets + Pluto + Moon + Sun) Currently only one possibility, but written for extensibility.
Detailed Description
Defines enumerations used in the DE4xx ephemeris model.
Enumeration Type Documentation
De4xxEphemBodies
enum jeod::De4xxBase::De4xxEphemBodies
Defines names for ephemeris items as represented in the JEOD DE4xx model.
NOTA BENE: The Earth-moon barycenter follows the massive bodies as the barycenter is not itself a massive body.
Enumerator
De4xx_Ephem_Sun
Sun.
De4xx_Ephem_Mercury
Mercury.
De4xx_Ephem_Venus
Venus.
De4xx_Ephem_Earth
Earth.
De4xx_Ephem_Mars
Mars.
De4xx_Ephem_Jupiter
Jupiter.
De4xx_Ephem_Saturn
Saturn.
De4xx_Ephem_Uranus
Uranus.
De4xx_Ephem_Neptune
Neptune.
De4xx_Ephem_Pluto
Pluto.
De4xx_Ephem_Moon
Moon.
De4xx_Ephem_EMbary
Earth-moon barycenter.
De4xx_Ephem_SSbary
Solar system barycenter.
De4xx_Ephem_EML1
Earth-moon L1 point (disabled)
De4xx_Ephem_ENutation
Nutations (disabled)
De4xx_Ephem_LLibration
Librations.
De4xx_Ephem_MaxBodies
Definition at line 148 of file de4xx_base.hh.
De4xxEphemConsts
enum jeod::De4xxBase::De4xxEphemConsts
Index aliases for the constants listed in the DE header that are used by JEOD.
This is an incomplete subset of the constants provided by DE, but all of these constants must be present for JEOD ephemeris to perform.
Enumerator
De4xx_Const_DENUM
De4xx_Const_LENUM
De4xx_Const_AU
De4xx_Const_EMRAT
De4xx_Const_CLIGHT
De4xx_Const_GM1
De4xx_Const_GM2
De4xx_Const_GMB
De4xx_Const_GM4
De4xx_Const_GM5
De4xx_Const_GM6
De4xx_Const_GM7
De4xx_Const_GM8
De4xx_Const_GM9
De4xx_Const_GMS
De4xx_Const_MaxConsts
Definition at line 122 of file de4xx_base.hh.
De4xxFileEntries
enum jeod::De4xxBase::De4xxFileEntries
Defines names for planetary body descriptors in the ephemeris file.
This enum defines names for the bodies as they are represented in the ephemeris file.
Enumerator
De4xx_File_Mercury
Mercury XYZ [km].
De4xx_File_Venus
Venus XYZ.
De4xx_File_EMbary
Earth-moon barycenter XYZ.
De4xx_File_Mars
Mars XYZ.
De4xx_File_Jupiter
Jupiter XYZ.
De4xx_File_Saturn
Saturn XYZ.
De4xx_File_Uranus
Uranus XYZ.
De4xx_File_Neptune
Neptune XYZ.
De4xx_File_Pluto
Pluto XYZ.
De4xx_File_Moon
Moon, geocentric coords. XYZ.
De4xx_File_Sun
Sun XYZ.
De4xx_File_ENutation
Earth Nutations d(psi), d(eps) [rad].
De4xx_File_LLibration
Lun mantle Libratns phi,tht,psi [rad].
De4xx_File_LAngVel
Lun mantle ang vel omg_{xyz} [rad/day].
De4xx_File_tt_tdb
TDB to TT offset @ geocenter [s].
De4xx_File_MaxEntries
Definition at line 95 of file de4xx_base.hh.
Function Documentation
__attribute__()
static const char* point_names [32] jeod::De4xxBase::__attribute__ ((unused)) static
number_grav_models()
static uint32_t jeod::De4xxBase::number_grav_models (int de_version_num __attribute__(unused)) inline static
Number of gravity models in the JEOD ephemeris (Mercury to Sun + implied Earth) Currently only one possibility, but written for extensibility.
Definition at line 217 of file de4xx_base.hh.
Referenced by jeod::De4xxFileHeader::De4xxFileHeader(), and jeod::De4xxFile::initialize().
number_jeod_items()
static uint32_t jeod::De4xxBase::number_jeod_items (int de_version_num __attribute__(unused)) inline static
Total number of items in the JEOD ephemeris.
Refer to De4xxEphemBodies for identities of each item. Currently only one possibility, but written for extensibility
Definition at line 197 of file de4xx_base.hh.
Referenced by jeod::De4xxEphemeris::activate_nodes(), jeod::De4xxEphemeris::De4xxEphemeris(), jeod::De4xxEphemeris::ephem_activate(), jeod::De4xxEphemeris::ephem_initialize(), and jeod::De4xxEphemeris::initialize_items().
number_physical_bodies()
static uint32_t jeod::De4xxBase::number_physical_bodies (int de_version_num __attribute__(unused)) inline static
Number of bodies in the JEOD ephemeris (Planets + Pluto + Moon + Sun) Currently only one possibility, but written for extensibility.
Definition at line 226 of file de4xx_base.hh.
number_trans_points()
static uint32_t jeod::De4xxBase::number_trans_points (int de_version_num __attribute__(unused)) inline static
Total number of translational states in the JEOD ephemeris.
(Sun, Mercury to Pluto, EMBary, SSbary) Currently excludes EML1 Currently only one possibility, but written for extensibility
Definition at line 207 of file de4xx_base.hh.
Referenced by jeod::De4xxEphemeris::activate_nodes(), jeod::De4xxEphemeris::De4xxEphemeris(), jeod::De4xxEphemeris::determine_root_node(), jeod::De4xxEphemeris::ephem_build_tree(), and jeod::De4xxEphemeris::initialize_items().