JEOD: jeod::De4xxFileSpec Class Reference
jeod::De4xxFileSpec Class Reference
Specifies which file to use (user input initialization-time data).
#include <de4xx_file.hh>
Public Member Functions
De4xxFileSpec (void)
Construct a De4xxFileSpec object.
void set_model_number (int denum_in)
Set ephemeris model number.
uint32_t get_model_number ()
Get Ephemeris model number.
Protected Attributes
uint32_t denum
Ephemeris model number.
std::string ephem_file_dir
Ephemeris file directory.
std::string ephem_file_name
Ephemeris file name.
std::string pathname
Ephemeris file path name.
Private Member Functions
De4xxFileSpec (const De4xxFileSpec &)
Not implemented.
De4xxFileSpec & operator= (const De4xxFileSpec &)
Not implemented.
Friends
class InputProcessor
class De4xxFile
void init_attrjeod__De4xxFileSpec ()
Detailed Description
Specifies which file to use (user input initialization-time data).
Definition at line 193 of file de4xx_file.hh.
Constructor & Destructor Documentation
De4xxFileSpec() [1/2]
jeod::De4xxFileSpec::De4xxFileSpec (void)
Construct a De4xxFileSpec object.
Definition at line 87 of file de4xx_file.cc.
References set_model_number().
De4xxFileSpec() [2/2]
jeod::De4xxFileSpec::De4xxFileSpec (const De4xxFileSpec &) private
Not implemented.
Member Function Documentation
get_model_number()
uint32_t jeod::De4xxFileSpec::get_model_number () inline
Get Ephemeris model number.
This number is used to specify the de file to use the pathname is of the form PWD/build/de4xx_lib/libde<denumIn>.so
Definition at line 218 of file de4xx_file.hh.
References denum.
Referenced by jeod::De4xxEphemeris::activate_nodes(), jeod::De4xxEphemeris::determine_root_node(), jeod::De4xxEphemeris::ephem_activate(), jeod::De4xxEphemeris::ephem_build_tree(), jeod::De4xxEphemeris::ephem_initialize(), jeod::De4xxEphemeris::get_model_number(), and jeod::De4xxEphemeris::initialize_items().
operator=()
De4xxFileSpec& jeod::De4xxFileSpec::operator= (const De4xxFileSpec &) private
Not implemented.
set_model_number()
void jeod::De4xxFileSpec::set_model_number (int denum_in)
Set ephemeris model number.
This number is used to specify the de file to use the pathname is of the form PWD/build/de4xx_lib/libde<denumIn>.so
Definition at line 97 of file de4xx_file.cc.
References denum, ephem_file_dir, ephem_file_name, and pathname.
Referenced by De4xxFileSpec(), and jeod::De4xxEphemeris::set_model_number().
Friends And Related Function Documentation
De4xxFile
friend class De4xxFile friend
Definition at line 196 of file de4xx_file.hh.
init_attrjeod__De4xxFileSpec
void init_attrjeod__De4xxFileSpec () friend
InputProcessor
friend class InputProcessor friend
Definition at line 194 of file de4xx_file.hh.
Field Documentation
denum
uint32_t jeod::De4xxFileSpec::denum protected
Ephemeris model number.
This must match the DE number in the data file; a sanity checktrick_units(–)
Definition at line 231 of file de4xx_file.hh.
Referenced by get_model_number(), jeod::De4xxFile::initialize(), jeod::De4xxFile::pre_initialize(), and set_model_number().
ephem_file_dir
std::string jeod::De4xxFileSpec::ephem_file_dir protected
Ephemeris file directory.
trick_units(–)
Definition at line 236 of file de4xx_file.hh.
Referenced by jeod::De4xxFile::open(), and set_model_number().
ephem_file_name
std::string jeod::De4xxFileSpec::ephem_file_name protected
Ephemeris file name.
trick_units(–)
Definition at line 241 of file de4xx_file.hh.
Referenced by jeod::De4xxFile::open(), and set_model_number().
pathname
std::string jeod::De4xxFileSpec::pathname protected
Ephemeris file path name.
trick_io(*o) trick_units(–)
Definition at line 247 of file de4xx_file.hh.
Referenced by jeod::De4xxFile::open(), jeod::De4xxFile::pre_initialize(), set_model_number(), and jeod::De4xxFile::update().
The documentation for this class was generated from the following files:
de4xx_file.hh
de4xx_file.cc