JEOD: jeod::GravityControls Class Reference
jeod::GravityControls Class Reference abstract
Specifies whether and how a GravitySource affects a vehicle.
#include <gravity_controls.hh>
Public Member Functions
GravityControls ()=default
virtual ~GravityControls ()=default
GravityControls (const GravityControls &)=delete
GravityControls & operator= (const GravityControls &)=delete
virtual void initialize_control (GravityManager &grav_man)
Initialize this GravityControl.
virtual void reset_control (BaseDynManager &dyn_manager)
Reset subscriptions for this GravityControl.
virtual void gravitation (const double integ_pos[3], unsigned int integ_frame_idx, double body_grav_accel[3], double dgdx[3][3], double Pot[1])
Compute the gravitation at a given position toward a gravity body.
virtual void gravitation (const RefFrame &point_of_interest, unsigned int integ_frame_idx, double body_grav_accel[3], double dgdx[3][3], double &pot)
Compute the gravitation at a given position toward a gravity body.
Static Public Member Functions
static bool accel_mag_less_ptr (const GravityControls *a, const GravityControls *b)
Compares the magnitude of the two input gravity controls, returning true if a->grav_accel_magsq is less than b->grav_accel_magsq, false otherwise.
Data Fields
std::string source_name
Planet name.
bool active {}
Gravity for this body active?
bool spherical {}
Ignore non-spherical effects?
bool gradient {}
Compute gravity gradient matrix?
bool perturbing_only {}
Compute only the perturbing gravity?
bool battin_method {}
Compute third body gravity using Battin's method (Battin, Mathematics and Methods of Astrodynamics)?
bool relativistic {}
Indicates that the relativistic correction to Newtonian gravitation is to be computed.
GravitySource * body {}
Pointer to the GravitySource object named by planet_name.
double grav_accel [3] {}
Gravitational acceleration toward the GravitySource at the location of the DynBody, including third body effects.
double grav_grad [3][3] {}
Gradient of the gravitational acceleration.
double grav_pot {}
Gravitational potential.
double grav_accel_magsq {}
Square of the magnitude of grav_accel.
Protected Member Functions
virtual void calc_nonspherical (const double integ_pos[3], const double posn[3], const GravityIntegFrame &grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double &pot)=0
Nominally, compute the non-spherical contribution to gravity at a given position.
void calc_relativistic (const RefFrame &point_of_interest, const double rel_pos[3], const double rel_vel[3], double perturbing_accel[3])
Calculates the relativistic correction to gravitational acceleration.
void calc_spherical (const double integ_pos[3], const double posn[3], const GravityIntegFrame &grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double &pot)
Calculate the spherical gravitational acceleration, either directly or as a third body acceleration.
Protected Attributes
GravityManager * grav_manager {}
Pointer to the simulation-wide GravityManager object.
bool subscribed_to_inertial {}
Indicates that a subscription to the planet-centered inertial frame of the planet associated with the gravity_source been issued.
bool subscribed_to_pfix {}
Indicates that a subscription to the planet-centered, planet-fixed frame of the planet associated with the gravity_source been issued.
bool skip_spherical {}
Some derived classes' calc_nonspherical method computes all contributions to gravitation, including spherical.
Friends
class InputProcessor
void init_attrjeod__GravityControls ()
Detailed Description
Specifies whether and how a GravitySource affects a vehicle.
Definition at line 89 of file gravity_controls.hh.
Constructor & Destructor Documentation
GravityControls() [1/2]
jeod::GravityControls::GravityControls () default
~GravityControls()
virtual jeod::GravityControls::~GravityControls () virtual default
GravityControls() [2/2]
jeod::GravityControls::GravityControls (const GravityControls &) delete
Member Function Documentation
accel_mag_less_ptr()
static bool jeod::GravityControls::accel_mag_less_ptr (const GravityControls * a, const GravityControls * b) inline static
Compares the magnitude of the two input gravity controls, returning true if a->grav_accel_magsq is less than b->grav_accel_magsq, false otherwise.
Returns
Result of comparison
Parameters
a First control to be compared.
b Second control to be compared.
Definition at line 228 of file gravity_controls.hh.
References grav_accel_magsq.
Referenced by jeod::GravityInteraction::sort_controls().
calc_nonspherical()
virtual void jeod::GravityControls::calc_nonspherical (const double integ_pos[3], const double posn[3], const GravityIntegFrame & grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double & pot) protected pure virtual
Nominally, compute the non-spherical contribution to gravity at a given position.
Derived classes whose override of this function computes the full gravitation model, including the spherical contribution, should set the skip_spherical flag.
Parameters
[in] posn Inertial position of the point of interest relative to the gravitional body.
[out] body_grav_accel Acceleration at the point of interest due to the gravitional body.
[out] dgdx Gravity gradient at the point of interest.
[out] Pot Specific gravitational potential energy.
Implemented in jeod::SphericalHarmonicsGravityControls.
Referenced by gravitation().
calc_relativistic()
void jeod::GravityControls::calc_relativistic (const RefFrame & point_of_interest, const double rel_pos[3], const double rel_vel[3], double perturbing_accel[3]) protected
Calculates the relativistic correction to gravitational acceleration.
Parameters
point_of_interest The point of interest, as a reference frame.
rel_pos Displacement vector from the grav body to the POI.
rel_vel Time derivative of rel_pos.
perturbing_accel Output relativistic accel, sans the Newtonian term.
Implements equation 27 (Folkner) / equation 4 (Genova) to compute a parameteric post-Newtonian correction to gravitation. The referenced equation is of the form
where is the net acceleration of gravitating body B toward the other gravitating bodies (typically taken to be the Newtonian gravitational acceleration) and
In terms of the referenced equation, the intent of this function is to compute the relativistic portion of the acceleration of body A toward body B. With this, the expression this function computes is
Note that the common factor is unitless and thus each of the three terms in the braced expression has units of acceleration.
The referenced equations explicitly involve the parameterized post-Newtonian (PPN) factors and . This function hardcodes both of those factors as one, consistent with general relativity. For example, the factor becomes 3.5 in the code. Magic numbers that involve or , including a factor of one (e.g.,), are noted in comments.
References:
William M. Folkner, et al., Planetary and Lunar Ephemerides DE430 and DE431, IPN Progress Report 42-196, 15 February 2014.
ftp://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430_and_de431.pdf
Antonio Genova, et al., Solar system expansion and strong equivalence principle as seen by the NASA MESSENGER mission, Nature Communications 9:289, 18 January 2018, DOI: 10.1038/s41467-017-02558-1.
https://www.nature.com/articles/s41467-017-02558-1
Definition at line 456 of file gravity_controls.cc.
References body, jeod::RefFrame::compute_position_from(), jeod::Vector3::diff(), jeod::Vector3::dot(), jeod::GravityManager::get_bodies(), grav_manager, jeod::Vector3::incr(), jeod::GravitySource::inertial, jeod::GravitySource::mu, jeod::Vector3::scale(), jeod::Vector3::scale_incr(), jeod::speed_of_light_sq, jeod::RefFrame::state, jeod::Vector3::sum(), jeod::RefFrameState::trans, jeod::RefFrameTrans::velocity, and jeod::Vector3::vmagsq().
Referenced by gravitation().
calc_spherical()
void jeod::GravityControls::calc_spherical (const double integ_pos[3], const double posn[3], const GravityIntegFrame & grav_source_frame, double body_grav_accel[3], double dgdx[3][3], double & pot) protected
Calculate the spherical gravitational acceleration, either directly or as a third body acceleration.
Parameters
integ_pos Point of interest location, integ frame coordinates
posn Vector from gravitational body to point of interest
grav_source_frame Frame corresponding to the gravitational body
body_grav_accel Acceleration at integ_pos due to the grav body
dgdx Gravity gradient at integ_pos due to the grav body
pot Gravitational potential at integ_pos due to the grav body.
Definition at line 291 of file gravity_controls.cc.
References battin_method, body, jeod::Vector3::copy(), jeod::Vector3::dot(), gradient, jeod::Vector3::incr(), jeod::GravityIntegFrame::is_third_body, jeod::GravitySource::mu, jeod::GravityIntegFrame::pos, jeod::Vector3::scale(), jeod::Vector3::scale_decr(), jeod::Vector3::scale_incr(), and jeod::Vector3::vmagsq().
Referenced by gravitation().
gravitation() [1/2]
void jeod::GravityControls::gravitation (const double integ_pos[3], unsigned int integ_frame_idx, double body_grav_accel[3], double dgdx[3][3], double Pot[1]) virtual
Compute the gravitation at a given position toward a gravity body.
Parameters
[in] integ_pos Point of interest, integ coords
Units: M
[in] integ_frame_idx Integ frame index
[out] body_grav_accel Accel for given grav body
Units: M/s2
[out] dgdx Gradient for given grav body
Units: 1/s2
[out] Pot Potential
Definition at line 187 of file gravity_controls.cc.
References body, calc_nonspherical(), calc_spherical(), jeod::RefFrame::compute_position_from(), jeod::GravitySource::frames, jeod::GravitySource::inertial, jeod::Vector3::initialize(), jeod::Matrix3x3::initialize(), perturbing_only, jeod::GravityIntegFrame::pos, jeod::GravityIntegFrame::ref_frame, skip_spherical, spherical, and jeod::Vector3::sum().
Referenced by jeod::DynBodyFrameSwitch::apply(), and jeod::GravityManager::gravitation().
gravitation() [2/2]
void jeod::GravityControls::gravitation (const RefFrame & point_of_interest, unsigned int integ_frame_idx, double body_grav_accel[3], double dgdx[3][3], double & pot) virtual
Compute the gravitation at a given position toward a gravity body.
Parameters
[in] point_of_interest Point of interest, as a reference frame.
[in] integ_frame_idx Integ frame index.
[out] body_grav_accel Accel for given grav body.
[out] dgdx Gradient for given grav body.
[out] pot Specific gravitational potential for given grev body.
Definition at line 232 of file gravity_controls.cc.
References body, calc_nonspherical(), calc_relativistic(), calc_spherical(), jeod::RefFrame::compute_relative_state(), jeod::Vector3::diff(), jeod::GravitySource::frames, jeod::Vector3::incr(), jeod::GravitySource::inertial, jeod::Vector3::initialize(), jeod::Matrix3x3::initialize(), jeod::Vector3::negate(), perturbing_only, jeod::GravityIntegFrame::pos, jeod::RefFrameTrans::position, jeod::GravityIntegFrame::ref_frame, relativistic, skip_spherical, spherical, jeod::RefFrame::state, jeod::RefFrameState::trans, and jeod::RefFrameTrans::velocity.
initialize_control()
void jeod::GravityControls::initialize_control (GravityManager & grav_man) virtual
Initialize this GravityControl.
Parameters
[in] grav_man Ref to Gravity Manager
Reimplemented in jeod::SphericalHarmonicsGravityControls.
Definition at line 71 of file gravity_controls.cc.
References body, jeod::MessageHandler::error(), jeod::GravityManager::find_grav_source(), grav_manager, jeod::GravitySource::inertial, jeod::GravityMessages::invalid_object, jeod::GravityMessages::missing_entry, jeod::GravitySource::name, and source_name.
Referenced by jeod::SphericalHarmonicsGravityControls::initialize_control().
operator=()
GravityControls& jeod::GravityControls::operator= (const GravityControls &) delete
reset_control()
void jeod::GravityControls::reset_control (BaseDynManager & dyn_manager) virtual
Reset subscriptions for this GravityControl.
Parameters
[in] dyn_manager Ptr to dynamics manager
Definition at line 119 of file gravity_controls.cc.
References active, body, jeod::GravitySource::inertial, jeod::MessageHandler::inform(), jeod::GravityMessages::null_pointer, jeod::GravitySource::pfix, source_name, spherical, jeod::BaseRefFrameManager::subscribe_to_frame(), subscribed_to_inertial, subscribed_to_pfix, and jeod::BaseRefFrameManager::unsubscribe_to_frame().
Friends And Related Function Documentation
init_attrjeod__GravityControls
void init_attrjeod__GravityControls () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file gravity_controls.hh.
Field Documentation
active
bool jeod::GravityControls::active {}
Gravity for this body active?
trick_units(–)
Definition at line 101 of file gravity_controls.hh.
Referenced by jeod::DynBodyFrameSwitch::apply(), jeod::GravityManager::gravitation(), reset_control(), jeod::GravityInteraction::sort_controls(), and jeod::SphericalHarmonicsGravityControls::update_deltacoeffs().
battin_method
bool jeod::GravityControls::battin_method {}
Compute third body gravity using Battin's method (Battin, Mathematics and Methods of Astrodynamics)?
trick_units(–)
Definition at line 122 of file gravity_controls.hh.
Referenced by calc_spherical().
body
GravitySource* jeod::GravityControls::body {}
Pointer to the GravitySource object named by planet_name.
Note
Users should not set this data member in the input file.trick_units(–)
Definition at line 135 of file gravity_controls.hh.
Referenced by calc_relativistic(), calc_spherical(), gravitation(), jeod::SphericalHarmonicsGravityControls::initialize_control(), initialize_control(), and reset_control().
gradient
bool jeod::GravityControls::gradient {}
Compute gravity gradient matrix?
trick_units(–)
Definition at line 111 of file gravity_controls.hh.
Referenced by jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), calc_spherical(), and jeod::SphericalHarmonicsGravityControls::check_validity().
grav_accel
double jeod::GravityControls::grav_accel[3] {}
Gravitational acceleration toward the GravitySource at the location of the DynBody, including third body effects.
trick_units(m/s2)
Definition at line 141 of file gravity_controls.hh.
Referenced by jeod::DynBodyFrameSwitch::apply(), jeod::GravityManager::gravitation(), and jeod::GravityInteraction::sort_controls().
grav_accel_magsq
double jeod::GravityControls::grav_accel_magsq {}
Square of the magnitude of grav_accel.
trick_units(m2/s4)
Definition at line 156 of file gravity_controls.hh.
Referenced by accel_mag_less_ptr(), and jeod::GravityInteraction::sort_controls().
grav_grad
double jeod::GravityControls::grav_grad[3][3] {}
Gradient of the gravitational acceleration.
trick_units(1/s2)
Definition at line 146 of file gravity_controls.hh.
Referenced by jeod::DynBodyFrameSwitch::apply(), and jeod::GravityManager::gravitation().
grav_manager
GravityManager* jeod::GravityControls::grav_manager {} protected
Pointer to the simulation-wide GravityManager object.
Note
Users should not set this data member in the input file.trick_units(–)
Definition at line 163 of file gravity_controls.hh.
Referenced by calc_relativistic(), jeod::SphericalHarmonicsGravityControls::initialize_control(), and initialize_control().
grav_pot
double jeod::GravityControls::grav_pot {}
Gravitational potential.
trick_units(m2/s2)
Definition at line 151 of file gravity_controls.hh.
Referenced by jeod::DynBodyFrameSwitch::apply(), and jeod::GravityManager::gravitation().
perturbing_only
bool jeod::GravityControls::perturbing_only {}
Compute only the perturbing gravity?
trick_units(–)
Definition at line 116 of file gravity_controls.hh.
Referenced by gravitation().
relativistic
bool jeod::GravityControls::relativistic {}
Indicates that the relativistic correction to Newtonian gravitation is to be computed.
The public methods enable_relativistic_correction and disable_relativistic_correction set / clear this flag.trick_units(–)
Definition at line 129 of file gravity_controls.hh.
Referenced by gravitation().
skip_spherical
bool jeod::GravityControls::skip_spherical {} protected
Some derived classes' calc_nonspherical method computes all contributions to gravitation, including spherical.
Those classes need to set this flag. The flag is clear in the base class and in the SphericalHarmonicsGravityControls derived class.trick_units(–)
Definition at line 185 of file gravity_controls.hh.
Referenced by gravitation().
source_name
std::string jeod::GravityControls::source_name
Planet name.
trick_units(–)
Definition at line 96 of file gravity_controls.hh.
Referenced by jeod::SphericalHarmonicsGravityControls::check_validity(), initialize_control(), and reset_control().
spherical
bool jeod::GravityControls::spherical {}
Ignore non-spherical effects?
trick_units(–)
Definition at line 106 of file gravity_controls.hh.
Referenced by jeod::SphericalHarmonicsGravityControls::check_validity(), gravitation(), and reset_control().
subscribed_to_inertial
bool jeod::GravityControls::subscribed_to_inertial {} protected
Indicates that a subscription to the planet-centered inertial frame of the planet associated with the gravity_source been issued.
Note
Users should not set this data member in the input file.trick_units(–)
Definition at line 170 of file gravity_controls.hh.
Referenced by reset_control().
subscribed_to_pfix
bool jeod::GravityControls::subscribed_to_pfix {} protected
Indicates that a subscription to the planet-centered, planet-fixed frame of the planet associated with the gravity_source been issued.
Note
Users should not set this data member in the input file.trick_units(–)
Definition at line 177 of file gravity_controls.hh.
Referenced by reset_control().
The documentation for this class was generated from the following files:
gravity_controls.hh
gravity_controls.cc