JEOD: jeod::CheckPointInputManager Class Reference
jeod::CheckPointInputManager Class Reference
A CheckPointInputManager provides tools for reading a checkpoint file.
#include <checkpoint_input_manager.hh>
Data Structures
struct SectionInfo
A SectionInfo contains the start and end positions of a checkpoint file section.
Public Member Functions
CheckPointInputManager (const std::string &fname, const std::string &start_marker, const std::string &end_marker)
Construct a CheckPointInputManager object.
SectionedInputStream create_section_reader (const std::string &tag)
Create a C++ input stream that reads from a checkpoint file section.
bool operator! () const
Conversion to boolean.
bool have_active_reader () const
Is there an active checkpoint section reader?
bool register_reader (SectionedInputStream *reader)
Register the supplied section reader as the currently-active reader.
bool deregister_reader (const SectionedInputStream *reader)
Deregister the supplied section reader as the currently-active reader.
Private Member Functions
void initialize (void)
Determine the locations of the various sections that comprise the file.
SectionedInputStream create_section_reader (bool trick, const std::string &tag)
Create a C++ input stream that reads from a checkpoint file section.
SectionedInputStream create_trick_section_reader ()
Create a C++ input stream that reads from the Trick checkpoint file section.
CheckPointInputManager (const CheckPointInputManager &)
Not implemented.
CheckPointInputManager & operator= (const CheckPointInputManager &)
Not implemented.
Private Attributes
std::map< std::string, SectionInfo > sections
Maps section names to section start/end positions.
std::ifstream stream
The C++ file stream that reads the checkpoint file.
SectionedInputStream * current_reader
The reader that currently is active.
const std::string filename
The name of the checkpoint file.
const std::string & section_start
The string that indicates the start of a checkpoint file section.
const std::string & section_end
The string that indicates the start of a checkpoint file section.
bool is_open
Is the checkpoint file open?
Detailed Description
A CheckPointInputManager provides tools for reading a checkpoint file.
A Trick 10 checkpoint file comprises multiple sections delineated by section markers. This class recognizes those markers and generates C++ input streams that other objects can use to read the contents of one of those checkpoint file sections. The interpretation of the contents of a checkpoint file section is the responsibility of those other objects.
Definition at line 419 of file checkpoint_input_manager.hh.
Constructor & Destructor Documentation
CheckPointInputManager() [1/2]
jeod::CheckPointInputManager::CheckPointInputManager (const std::string & fname, const std::string & start_marker, const std::string & end_marker)
Construct a CheckPointInputManager object.
Parameters
[in] fname Name of file to be opened
[in] start_marker Start of section marker
[in] end_marker End of section marker
Definition at line 314 of file checkpoint_input_manager.cc.
References jeod::MessageHandler::error(), filename, jeod::SimInterfaceMessages::implementation_error, initialize(), is_open, and stream.
CheckPointInputManager() [2/2]
jeod::CheckPointInputManager::CheckPointInputManager (const CheckPointInputManager &) private
Not implemented.
Member Function Documentation
create_section_reader() [1/2]
SectionedInputStream jeod::CheckPointInputManager::create_section_reader (const std::string & tag) inline
Create a C++ input stream that reads from a checkpoint file section.
Error handling
A null SectionedInputStream is created when the CheckPointInputManager itself is invalid or when the designated section is not present in the checkpoint file.
Parameters
tag Tag that identifies the section to be read.
Returns
A SectionedInputStream object, which must be used to initialize a local SectionedInputStream variable.
Definition at line 438 of file checkpoint_input_manager.hh.
Referenced by create_trick_section_reader(), and jeod::BasicJeodTrickSimInterface::get_checkpoint_reader_internal().
create_section_reader() [2/2]
SectionedInputStream jeod::CheckPointInputManager::create_section_reader (bool trick, const std::string & tag) private
Create a C++ input stream that reads from a checkpoint file section.
Usage
Use this function as the initializer of a section reader variable.
Error handling
A null SectionedInputStream is created when the CheckPointInputManager itself is invalid or when the designated section is not present in the checkpoint file.
Returns
A SectionedInputStream object.
Parameters
[in] trick OK to create the Trick section reader?
[in] tag Tag identifying the section to be read.
Definition at line 424 of file checkpoint_input_manager.cc.
References jeod::CheckPointInputManager::SectionInfo::end_pos, jeod::MessageHandler::error(), filename, jeod::SimInterfaceMessages::implementation_error, is_open, sections, jeod::CheckPointInputManager::SectionInfo::start_pos, and stream.
create_trick_section_reader()
SectionedInputStream jeod::CheckPointInputManager::create_trick_section_reader (void) private
Create a C++ input stream that reads from the Trick checkpoint file section.
Returns
Trick SectionedInputStream object.
Definition at line 467 of file checkpoint_input_manager.cc.
References create_section_reader(), current_reader, and jeod::SectionedInputStream::deactivate().
deregister_reader()
bool jeod::CheckPointInputManager::deregister_reader (const SectionedInputStream * reader)
Deregister the supplied section reader as the currently-active reader.
Returns
True => success.
Parameters
[in] reader Reader to be deregistered
Definition at line 504 of file checkpoint_input_manager.cc.
References current_reader.
Referenced by jeod::SectionedInputStream::deactivate(), and jeod::SectionedInputStream::~SectionedInputStream().
have_active_reader()
bool jeod::CheckPointInputManager::have_active_reader () const inline
Is there an active checkpoint section reader?
Returns
True if there is an active reader, false otherwise.
Definition at line 454 of file checkpoint_input_manager.hh.
References current_reader.
Referenced by jeod::SectionedInputStream::is_activatable().
initialize()
void jeod::CheckPointInputManager::initialize (void) private
Determine the locations of the various sections that comprise the file.
Definition at line 344 of file checkpoint_input_manager.cc.
References jeod::MessageHandler::error(), filename, jeod::SimInterfaceMessages::implementation_error, section_end, section_start, sections, and stream.
Referenced by CheckPointInputManager().
operator!()
bool jeod::CheckPointInputManager::operator! () const inline
Conversion to boolean.
Returns
False if object is OK.
Definition at line 446 of file checkpoint_input_manager.hh.
References is_open, and stream.
operator=()
CheckPointInputManager& jeod::CheckPointInputManager::operator= (const CheckPointInputManager &) private
Not implemented.
register_reader()
bool jeod::CheckPointInputManager::register_reader (SectionedInputStream * reader)
Register the supplied section reader as the currently-active reader.
Returns
True => success.
Parameters
[in] reader Reader to be registered
Definition at line 485 of file checkpoint_input_manager.cc.
References current_reader.
Referenced by jeod::SectionedInputStream::activate().
Field Documentation
current_reader
SectionedInputStream* jeod::CheckPointInputManager::current_reader private
The reader that currently is active.
trick_io(**)
Definition at line 524 of file checkpoint_input_manager.hh.
Referenced by create_trick_section_reader(), deregister_reader(), have_active_reader(), and register_reader().
filename
const std::string jeod::CheckPointInputManager::filename private
The name of the checkpoint file.
Definition at line 529 of file checkpoint_input_manager.hh.
Referenced by CheckPointInputManager(), create_section_reader(), and initialize().
is_open
bool jeod::CheckPointInputManager::is_open private
Is the checkpoint file open?
trick_io(**)
Definition at line 544 of file checkpoint_input_manager.hh.
Referenced by CheckPointInputManager(), create_section_reader(), and operator!().
section_end
const std::string& jeod::CheckPointInputManager::section_end private
The string that indicates the start of a checkpoint file section.
Definition at line 539 of file checkpoint_input_manager.hh.
Referenced by initialize().
section_start
const std::string& jeod::CheckPointInputManager::section_start private
The string that indicates the start of a checkpoint file section.
Definition at line 534 of file checkpoint_input_manager.hh.
Referenced by initialize().
sections
std::map<std::string, SectionInfo> jeod::CheckPointInputManager::sections private
Maps section names to section start/end positions.
trick_io(**)
Definition at line 514 of file checkpoint_input_manager.hh.
Referenced by create_section_reader(), and initialize().
stream
std::ifstream jeod::CheckPointInputManager::stream private
The C++ file stream that reads the checkpoint file.
trick_io(**)
Definition at line 519 of file checkpoint_input_manager.hh.
Referenced by CheckPointInputManager(), create_section_reader(), initialize(), and operator!().
The documentation for this class was generated from the following files:
checkpoint_input_manager.hh
checkpoint_input_manager.cc