JEOD: jeod::RefFrame Class Reference
jeod::RefFrame Class Reference
Describe a frame of reference and define operations on reference frames.
#include <ref_frame.hh>
Public Member Functions
RefFrame (void)
Construct a RefFrame object.
~RefFrame (void) override
Destroy a RefFrame object.
void set_name (const char *name_item1)
Create a copy of the provided name.
void set_name (const char *name_item1, const char *name_item2)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5, const char *name_item6)
Construct a name as a dot-conjoined string.
void set_name (const char *name_item1, const char *name_item2, const char *name_item3, const char *name_item4, const char *name_item5, const char *name_item6, const char *name_item7)
Construct a name as a dot-conjoined string.
virtual const char * get_name (void) const
Return the name.
virtual void set_timestamp (double time)
Set the update time of this frame.
virtual double timestamp (void) const
Return the update time of this frame.
virtual void set_owner (RefFrameOwner *new_owner)
Set the owner of this frame.
virtual RefFrameOwner * get_owner (void) const
Return the owner of this frame.
void set_active_status (bool value) override
Augment Subscription::set_active_status by telling the frame owner that the active/inactive state of this frame has changed.
const RefFrame * get_parent (void) const
Return the parent of this frame.
const RefFrame * get_root (void) const
Return the root of this frame's tree.
virtual void make_root (void)
Make this frame a root frame.
virtual void add_child (RefFrame &frame)
Add a child frame to this frame.
virtual void remove_from_parent (void)
Remove this node as a child of its parent node.
bool is_progeny_of (const RefFrame &frame) const
Return true if this frame is a progeny of the provided frame, false if not.
virtual void transplant_node (RefFrame &new_parent)
Move a node to a different place in the tree, keeping the state with respect to the root frame constant.
virtual void reset_parent (RefFrame &new_parent)
Reparent a node, without updating state.
virtual void compute_relative_state (const RefFrame &wrt_frame, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame (*this) with respect to the supplied wrt_frame reference frame.
virtual void compute_relative_state (const RefFrame &wrt_frame, bool reverse_sense, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame (*this) with respect to the supplied wrt_frame reference frame.
virtual void compute_state_wrt_pred (const RefFrame &wrt_frame, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_state_wrt_pred (unsigned int wrt_frame_index, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_pred_rel_state (const RefFrame &wrt_frame, RefFrameState &rel_state) const
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
virtual void compute_pred_rel_state (unsigned int wrt_frame_index, RefFrameState &rel_state) const
Compute the complete state of the supplied reference frame wrt the invoking reference frame.
virtual void compute_position_from (const RefFrame &in_frame, double rel_pos[3]) const
Compute the relative position vector from the origin of the supplied reference frame to the origin of this reference frame, expressed in the coordinates of the supplied frame.
const RefFrame * find_last_common_node (const RefFrame &frame) const
Each reference frame has a path from the root of the reference frame tree to the frame in question.
Public Member Functions inherited from jeod::Subscription
Subscription ()
Subscription class default constructor.
Subscription (Mode)
Subscription class non-default constructor.
virtual ~Subscription ()
Subscription class destructor.
bool is_active (void) const
Return the value of the active data member.
unsigned int subscriptions (void) const
Return the value of the subscribers data member.
Mode get_subscription_mode (void) const
Return the value of the mode data member.
void activate (void)
Activate a Subscription object.
void deactivate (void)
Deactivate a Subscription object.
void subscribe (void)
Add a subscription to a Subscription object.
void unsubscribe (void)
Remove a subscription to a Subscription object.
Data Fields
RefFrameState state
The translational and rotational state of the reference frame with respect to its parent.
Protected Member Functions
int find_last_common_index (const RefFrame &frame) const
Each reference frame has a path from the root of the reference frame tree to the frame in question.
Protected Member Functions inherited from jeod::Subscription
virtual void set_subscription_mode (Mode value)
Set the value of the mode data member.
Protected Attributes
std::string name
The identifier for this reference frame.
RefFrameOwner * owner
The object that "owns" this frame.
RefFrameLinks links
Specifies the parent/child/sibling linkages between frames.
double update_time
The time that the frame was lasted updated, dynamic time seconds.
Protected Attributes inherited from jeod::Subscription
Mode mode
The mode in which the object is operating.
unsigned int subscribers
Number of subscribers for this object.
bool active
Flag indicating whether the object is active.
Private Member Functions
RefFrame (const RefFrame &frame)
Not implemented.
RefFrame & operator= (const RefFrame &frame)
Not implemented.
Friends
class InputProcessor
class RefFrameLinks
void init_attrjeod__RefFrame ()
Additional Inherited Members
Public Types inherited from jeod::Subscription
enum Mode { Detect = 0, Subscribe = 1, Activate = 2, Freeform = 3 }
The Subscription::Mode enum specifies the mode in which a Subscription object is operating.
Detailed Description
Describe a frame of reference and define operations on reference frames.
A JEOD reference frame
Is characterized by an origin and and a set of three orthogonal axes.
Provides a mechanism for specifying the translational and rotational states of an object in space (particularly, Cartesian three space).
Is itself an object whose translational and rotational states can be specified/determined in terms of some other reference frame.
Is a node in a rooted tree of reference frames, each of which has some specific state with respect to another node in the tree.
Can be active (or inactive). An active frame supposedly will have a (fairly) current state. All bets are off if the frame is inactive.
Can have subscribers, which are external entities that for some reason need the frame to be active.
Reference frames are one of the key concepts that define JEOD 2.0.
Definition at line 99 of file ref_frame.hh.
Constructor & Destructor Documentation
RefFrame() [1/2]
jeod::RefFrame::RefFrame (const RefFrame & frame) private
Not implemented.
RefFrame() [2/2]
jeod::RefFrame::RefFrame (void)
Construct a RefFrame object.
Definition at line 49 of file ref_frame.cc.
References jeod::Subscription::set_subscription_mode(), and jeod::Subscription::Subscribe.
~RefFrame()
jeod::RefFrame::~RefFrame (void) override
Destroy a RefFrame object.
Definition at line 64 of file ref_frame.cc.
References jeod::TreeLinks< Links, Container, Messages >::child_tail(), jeod::TreeLinks< Links, Container, Messages >::detach(), jeod::TreeLinks< Links, Container, Messages >::has_children(), links, and remove_from_parent().
Member Function Documentation
add_child()
void jeod::RefFrame::add_child (RefFrame & frame) inline virtual
Add a child frame to this frame.
Parameters
[in,out] frame Frame to add as child
Definition at line 190 of file ref_frame_inline.hh.
References jeod::TreeLinks< Links, Container, Messages >::attach(), and links.
Referenced by jeod::RefFrameManager::add_frame_to_tree(), jeod::DynBody::add_mass_body_frames(), jeod::DynBody::add_mass_point(), jeod::DynBodyInitNedState::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::LvlhFrame::initialize(), jeod::NedDerivedState::initialize(), jeod::BasePlanet::register_planet(), and jeod::DynBody::set_integ_frame().
compute_position_from()
void jeod::RefFrame::compute_position_from (const RefFrame & in_frame, double rel_pos[3]) const virtual
Compute the relative position vector from the origin of the supplied reference frame to the origin of this reference frame, expressed in the coordinates of the supplied frame.
Parameters
[in] in_frame Relative position vector origin
[out] rel_pos Relative position vector
Units: M
Definition at line 354 of file ref_frame_compute_relative_state.cc.
References jeod::Numerical::compare_exact(), jeod::Vector3::decr(), jeod::MessageHandler::fail(), find_last_common_index(), jeod::Vector3::incr(), jeod::Vector3::initialize(), jeod::RefFrameMessages::invalid_node, links, name, jeod::TreeLinks< Links, Container, Messages >::path_length(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, jeod::Quaternion::scalar, state, jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Vector3::transform(), and jeod::Vector3::transform_transpose().
Referenced by jeod::EarthLighting::calc_lighting(), jeod::GravityControls::calc_relativistic(), jeod::RadiationSource::calculate_flux(), jeod::GravityControls::gravitation(), jeod::DynBodyFrameSwitch::is_ready(), jeod::SphericalHarmonicsSolidBodyTides::update(), jeod::PlanetaryDerivedState::update(), jeod::SolarBetaDerivedState::update(), and jeod::RadiationThirdBody::update_third_body_state().
compute_pred_rel_state() [1/2]
void jeod::RefFrame::compute_pred_rel_state (const RefFrame & pred_frame, RefFrameState & rel_state) const virtual
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
Assumptions and Limitations
The predecessor frame is a predecessor.
Parameters
[in] pred_frame The frame with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 279 of file ref_frame_compute_relative_state.cc.
References jeod::MessageHandler::fail(), jeod::TreeLinks< Links, Container, Messages >::find_path_index(), jeod::RefFrameMessages::invalid_node, links, name, and jeod::TreeLinks< Links, Container, Messages >::path_length().
Referenced by compute_relative_state().
compute_pred_rel_state() [2/2]
void jeod::RefFrame::compute_pred_rel_state (unsigned int pred_frame_index, RefFrameState & rel_state) const virtual
Compute the complete state of the supplied reference frame wrt the invoking reference frame.
The supplied reference frame must be a predecessor of the invoking frame.
Assumptions and Limitations
The predecessor frame is a predecessor.
Parameters
[in] pred_frame_index The frame with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 313 of file ref_frame_compute_relative_state.cc.
References jeod::RefFrameState::decr_right(), links, jeod::RefFrameState::negate(), jeod::TreeLinks< Links, Container, Messages >::path_length(), and state.
compute_relative_state() [1/2]
void jeod::RefFrame::compute_relative_state (const RefFrame & wrt_frame, RefFrameState & rel_state) const virtual
Compute the complete state of the invoking reference frame (*this) with respect to the supplied wrt_frame reference frame.
The state will include:
The position and velocity of the invoking frame with respect to the supplied wrt_frame, expressed in the coordinates of the wrt_frame.
The angular velocity of the invoking frame with respect to the supplied wrt_frame, expressed in the coordinates of invoking frame.
The transformation (as a matrix and a quaternion) from the supplied wrt_frame to the invoking frame.
Assumptions and Limitations
The two frames are in the same tree.
Parameters
[in] wrt_frame The frame with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 63 of file ref_frame_compute_relative_state.cc.
References compute_pred_rel_state(), compute_state_wrt_pred(), jeod::RefFrameState::decr_left(), jeod::MessageHandler::fail(), find_last_common_index(), jeod::RefFrameState::initialize(), jeod::RefFrameMessages::invalid_node, links, name, and jeod::TreeLinks< Links, Container, Messages >::nth_from_root().
Referenced by jeod::DynBodyInitNedState::apply(), jeod::DynBodyInitOrbit::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::attach_to_frame(), compute_relative_state(), jeod::GravityControls::gravitation(), jeod::DynBody::integrate(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::DynBody::switch_integration_frames(), transplant_node(), jeod::LvlhRelativeDerivedState::update(), jeod::LvlhFrame::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::OrbElemDerivedState::update(), jeod::EulerDerivedState::update(), jeod::NedDerivedState::update(), jeod::SolarBetaDerivedState::update(), jeod::PropagatedEphemerisOrientation::update(), and jeod::RelativeDerivedState::update().
compute_relative_state() [2/2]
void jeod::RefFrame::compute_relative_state (const RefFrame & wrt_frame, bool reverse_sense, RefFrameState & rel_state) const virtual
Compute the complete state of the invoking reference frame (*this) with respect to the supplied wrt_frame reference frame.
If reverse_sense is false, the results are those from the simpler two argument form of RefFrame::compute_relative_state. If reverse_sense is true, the results from the two argument form are transformed as follows:
The position and velocity are those the invoking frame with respect to the supplied wrt_frame, but expressed in invoking frame coordinates.
The angular velocity of the invoking frame with respect to the supplied wrt_frame, expressed in the coordinates of supplied wrt_frame.
The transformation (as a matrix and a quaternion) from the invoking frame to the supplied wrt_frame.
Assumptions and Limitations
The two frames are in the same tree.
Parameters
[in] wrt_frame The frame with respect to which the state is to be expressed
[in] reverse_sense Express position and velocity in this frame, angular velocity in the wrt_frame, and the transformations from this frame to the wrt_frame.
[out] rel_state The relative state
Definition at line 162 of file ref_frame_compute_relative_state.cc.
References jeod::RefFrameRot::ang_vel_this, jeod::RefFrameRot::ang_vel_unit, compute_relative_state(), jeod::Quaternion::conjugate(), jeod::RefFrameTrans::position, jeod::RefFrameRot::Q_parent_this, jeod::RefFrameState::rot, jeod::RefFrameRot::T_parent_this, jeod::RefFrameState::trans, jeod::Vector3::transform(), jeod::Vector3::transform_transpose(), jeod::Matrix3x3::transpose(), and jeod::RefFrameTrans::velocity.
compute_state_wrt_pred() [1/2]
void jeod::RefFrame::compute_state_wrt_pred (const RefFrame & pred_frame, RefFrameState & rel_state) const virtual
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
Assumptions and Limitations
The predecessor frame is a predecessor.
Parameters
[in] pred_frame The frame with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 203 of file ref_frame_compute_relative_state.cc.
References jeod::MessageHandler::fail(), jeod::TreeLinks< Links, Container, Messages >::find_path_index(), jeod::RefFrameMessages::invalid_node, links, name, and jeod::TreeLinks< Links, Container, Messages >::path_length().
Referenced by compute_relative_state().
compute_state_wrt_pred() [2/2]
void jeod::RefFrame::compute_state_wrt_pred (unsigned int pred_frame_index, RefFrameState & rel_state) const virtual
Compute the complete state of the invoking reference frame with respect to the supplied reference frame, which must be a predecessor of the invoking frame.
Assumptions and Limitations
The predecessor frame is a predecessor.
Parameters
[in] pred_frame_index The frame with respect to which the state is to be expressed
[out] rel_state The relative state
Definition at line 237 of file ref_frame_compute_relative_state.cc.
References jeod::RefFrameState::copy(), jeod::RefFrameState::incr_left(), links, jeod::TreeLinks< Links, Container, Messages >::path_length(), and state.
find_last_common_index()
int jeod::RefFrame::find_last_common_index (const RefFrame & frame) const inline protected
Each reference frame has a path from the root of the reference frame tree to the frame in question.
The paths for two reference frames will have some initial sequence of common nodes. Find the index number of this last element in this sequence.
Returns
Last common node
Parameters
[in] frame Other frame
Definition at line 221 of file ref_frame_inline.hh.
References jeod::TreeLinks< Links, Container, Messages >::find_last_common_index(), and links.
Referenced by compute_position_from(), and compute_relative_state().
find_last_common_node()
const RefFrame * jeod::RefFrame::find_last_common_node (const RefFrame & frame) const inline
Each reference frame has a path from the root of the reference frame tree to the frame in question.
The paths for two reference frames will have some initial sequence of common nodes. Find the last element in this sequence.
Returns
Last common node
Parameters
[in] frame Other frame
Definition at line 238 of file ref_frame_inline.hh.
References jeod::TreeLinks< Links, Container, Messages >::container(), jeod::TreeLinks< Links, Container, Messages >::find_last_common_node(), and links.
get_name()
const char * jeod::RefFrame::get_name (void) const inline virtual
Return the name.
Returns
Void
Definition at line 86 of file ref_frame_inline.hh.
References name.
Referenced by jeod::SpiceEphemeris::add_barycenter(), jeod::SpiceEphemeris::add_descendants_r(), jeod::EphemeridesManager::add_ephem_item(), jeod::RefFrameManager::add_ref_frame(), jeod::BodyAttach::apply(), jeod::DynBodyInit::apply(), jeod::check_frame_ownership(), jeod::RefFrameManager::check_ref_frame_ownership(), jeod::SpiceEphemeris::ephem_build_tree(), jeod::DynBody::find_body_frame(), jeod::EphemeridesManager::find_integ_frame(), jeod::EphemeridesManager::find_integ_frame_index(), jeod::RefFrameManager::find_ref_frame(), jeod::LvlhFrame::initialize(), jeod::De4xxEphemeris::initialize_items(), jeod::PointContactPair::initialize_pair(), jeod::LineContactPair::initialize_pair(), jeod::LinePointContactPair::initialize_pair(), jeod::DynBodyInitTransState::is_ready(), jeod::DynBodyInitRotState::is_ready(), jeod::RefFrameManager::remove_ref_frame(), jeod::DynBodyInit::report_failure(), jeod::DynBody::set_state_source(), jeod::EphemeridesManager::set_target_frame(), jeod::DynBody::switch_integration_frames(), and jeod::RefFrameManager::unsubscribe_to_frame().
get_owner()
RefFrameOwner * jeod::RefFrame::get_owner (void) const inline virtual
Return the owner of this frame.
Returns
Frame owner
Definition at line 112 of file ref_frame_inline.hh.
References owner.
Referenced by jeod::check_frame_ownership(), jeod::RefFrameManager::check_ref_frame_ownership(), jeod::DynBody::compute_ref_point_transform(), and jeod::DynBody::set_state_source().
get_parent()
const RefFrame * jeod::RefFrame::get_parent (void) const inline
Return the parent of this frame.
Returns
Frame parent
Definition at line 125 of file ref_frame_inline.hh.
References links, and jeod::TreeLinks< Links, Container, Messages >::parent().
Referenced by jeod::PropagatedPlanet::ephem_build_tree(), jeod::LvlhDerivedState::initialize(), jeod::EphemerisOrientation::note_frame_status_change(), jeod::LvlhFrame::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::OrbElemDerivedState::update(), jeod::EulerDerivedState::update(), and jeod::PropagatedEphemerisOrientation::update().
get_root()
const RefFrame * jeod::RefFrame::get_root (void) const inline
Return the root of this frame's tree.
Returns
Tree root
Definition at line 138 of file ref_frame_inline.hh.
References links, and jeod::TreeLinks< Links, Container, Messages >::root().
is_progeny_of()
bool jeod::RefFrame::is_progeny_of (const RefFrame & frame) const inline
Return true if this frame is a progeny of the provided frame, false if not.
Returns
This is progeny of frame
Parameters
[in] frame Other frame
Definition at line 260 of file ref_frame_inline.hh.
References jeod::TreeLinks< Links, Container, Messages >::is_progeny_of(), and links.
Referenced by jeod::GravitySource::initialize_state().
make_root()
void jeod::RefFrame::make_root (void) inline virtual
Make this frame a root frame.
Definition at line 176 of file ref_frame_inline.hh.
References links, and jeod::TreeLinks< Links, Container, Messages >::make_root().
Referenced by jeod::RefFrameManager::add_frame_to_tree().
operator=()
RefFrame& jeod::RefFrame::operator= (const RefFrame & frame) private
Not implemented.
remove_from_parent()
void jeod::RefFrame::remove_from_parent (void) inline virtual
Remove this node as a child of its parent node.
Definition at line 203 of file ref_frame_inline.hh.
References jeod::TreeLinks< Links, Container, Messages >::detach(), and links.
Referenced by jeod::DynBodyInitNedState::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::EphemerisPoint::disconnect_from_tree(), jeod::SpiceEphemeris::ephem_build_tree(), jeod::De4xxEphemeris::ephem_build_tree(), jeod::PropagatedPlanet::ephem_build_tree(), jeod::DynBody::~DynBody(), jeod::LvlhDerivedState::~LvlhDerivedState(), jeod::LvlhFrame::~LvlhFrame(), jeod::NedDerivedState::~NedDerivedState(), and ~RefFrame().
reset_parent()
void jeod::RefFrame::reset_parent (RefFrame & new_parent) virtual
Reparent a node, without updating state.
Parameters
[in] new_parent New parent frame
Definition at line 123 of file ref_frame.cc.
References links, and jeod::TreeLinks< Links, Container, Messages >::reattach().
Referenced by jeod::DynBody::set_integ_frame().
set_active_status()
void jeod::RefFrame::set_active_status (bool value) override virtual
Augment Subscription::set_active_status by telling the frame owner that the active/inactive state of this frame has changed.
Parameters
[in] value New active value
Reimplemented from jeod::Subscription.
Definition at line 82 of file ref_frame.cc.
References jeod::RefFrameOwner::note_frame_status_change(), owner, and jeod::Subscription::set_active_status().
Referenced by jeod::EphemerisRefFrame::set_active_status().
set_name() [1/7]
void jeod::RefFrame::set_name (const char * name_item1)
Create a copy of the provided name.
Parameters
[in] name_item1 First part of the name
Definition at line 42 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), and name.
Referenced by jeod::DynBody::add_mass_body_frames(), jeod::DynBody::add_mass_point(), jeod::DynBodyInitNedState::apply(), jeod::De4xxEphemeris::De4xxEphemeris(), jeod::LvlhFrame::initialize(), jeod::LvlhDerivedState::initialize(), jeod::NedDerivedState::initialize(), jeod::DynBody::initialize_model(), jeod::SpiceEphemeris::name_barycenter_frames(), jeod::BasePlanet::register_planet(), set_name(), and jeod::EmptySpaceEphemeris::set_name().
set_name() [2/7]
void jeod::RefFrame::set_name (const char * name_item1, const char * name_item2)
Construct a name as a dot-conjoined string.
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
Definition at line 55 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), and name.
set_name() [3/7]
void jeod::RefFrame::set_name (const char * name_item1, const char * name_item2, const char * name_item3)
Construct a name as a dot-conjoined string.
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
Definition at line 71 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), name, and set_name().
set_name() [4/7]
void jeod::RefFrame::set_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4)
Construct a name as a dot-conjoined string.
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
Definition at line 92 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), name, and set_name().
set_name() [5/7]
void jeod::RefFrame::set_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4, const char * name_item5)
Construct a name as a dot-conjoined string.
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
[in] name_item5 Fifth part of the name
Definition at line 115 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), name, and set_name().
set_name() [6/7]
void jeod::RefFrame::set_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4, const char * name_item5, const char * name_item6)
Construct a name as a dot-conjoined string.
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
[in] name_item5 Fifth part of the name
[in] name_item6 Sixth part of the name
Definition at line 140 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), name, and set_name().
set_name() [7/7]
void jeod::RefFrame::set_name (const char * name_item1, const char * name_item2, const char * name_item3, const char * name_item4, const char * name_item5, const char * name_item6, const char * name_item7)
Construct a name as a dot-conjoined string.
Parameters
[in] name_item1 First part of the name
[in] name_item2 Second part of the name
[in] name_item3 Third part of the name
[in] name_item4 Fourth part of the name
[in] name_item5 Fifth part of the name
[in] name_item6 Sixth part of the name
[in] name_item7 Seventh part of the name
Definition at line 167 of file ref_frame_set_name.cc.
References jeod::NamedItem::construct_name_string(), name, and set_name().
set_owner()
void jeod::RefFrame::set_owner (RefFrameOwner * new_owner) inline virtual
Set the owner of this frame.
Parameters
[in] new_owner New owner
Definition at line 99 of file ref_frame_inline.hh.
References owner.
Referenced by jeod::DynBody::add_mass_body_frames(), jeod::DynBody::add_mass_point(), jeod::EphemerisItem::disable(), jeod::EphemerisItem::enable(), jeod::PlanetOrientation::initialize(), jeod::DynBody::initialize_model(), and jeod::EphemerisItem::set_target_frame().
set_timestamp()
void jeod::RefFrame::set_timestamp (double time) inline virtual
Set the update time of this frame.
Parameters
[in] time Time
Units: s
Definition at line 151 of file ref_frame_inline.hh.
References update_time.
Referenced by jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::EphemerisZXZOrientation::propagate(), jeod::SpiceEphemOrientation::update(), jeod::EphemerisPoint::update(), jeod::EphemerisZXZOrientation::update(), jeod::LvlhFrame::update(), jeod::LvlhDerivedState::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::NedDerivedState::update(), jeod::PropagatedEphemerisOrientation::update(), jeod::RNPJ2000::update_axial_rotation(), jeod::RNPMars::update_axial_rotation(), jeod::DynBody::update_integrated_state(), jeod::RNPJ2000::update_rnp(), jeod::RNPMars::update_rnp(), and jeod::EphemerisPoint::update_scaled().
timestamp()
double jeod::RefFrame::timestamp (void) const inline virtual
Return the update time of this frame.
Returns
Time of last update
Units: s
Definition at line 164 of file ref_frame_inline.hh.
References update_time.
Referenced by jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::LvlhFrame::update(), jeod::LvlhDerivedState::update(), and jeod::NedDerivedState::update().
transplant_node()
void jeod::RefFrame::transplant_node (RefFrame & new_parent) virtual
Move a node to a different place in the tree, keeping the state with respect to the root frame constant.
Parameters
[in] new_parent New parent frame
Definition at line 102 of file ref_frame.cc.
References compute_relative_state(), links, jeod::TreeLinks< Links, Container, Messages >::reattach(), and state.
Friends And Related Function Documentation
init_attrjeod__RefFrame
void init_attrjeod__RefFrame () friend
InputProcessor
friend class InputProcessor friend
Definition at line 101 of file ref_frame.hh.
RefFrameLinks
friend class RefFrameLinks friend
Definition at line 103 of file ref_frame.hh.
Field Documentation
links
RefFrameLinks jeod::RefFrame::links protected
Specifies the parent/child/sibling linkages between frames.
trick_units(–)
Definition at line 128 of file ref_frame.hh.
Referenced by add_child(), compute_position_from(), compute_pred_rel_state(), compute_relative_state(), compute_state_wrt_pred(), find_last_common_index(), find_last_common_node(), get_parent(), get_root(), is_progeny_of(), make_root(), remove_from_parent(), reset_parent(), transplant_node(), and ~RefFrame().
name
std::string jeod::RefFrame::name protected
The identifier for this reference frame.
trick_units(–)
Definition at line 118 of file ref_frame.hh.
Referenced by compute_position_from(), compute_pred_rel_state(), compute_relative_state(), compute_state_wrt_pred(), get_name(), jeod::EphemerisRefFrame::set_active_status(), and set_name().
owner
RefFrameOwner* jeod::RefFrame::owner protected
The object that "owns" this frame.
trick_units(–)
Definition at line 123 of file ref_frame.hh.
Referenced by get_owner(), set_active_status(), and set_owner().
state
RefFrameState jeod::RefFrame::state
The translational and rotational state of the reference frame with respect to its parent.
trick_units(–)
Definition at line 111 of file ref_frame.hh.
Referenced by jeod::DynBodyInitNedState::apply(), jeod::DynBodyFrameSwitch::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::NorthEastDown::build_ned_orientation(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::GravityControls::calc_relativistic(), jeod::BasePlanet::calculate_alt_pfix(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::LvlhFrame::compute_lvlh_frame(), compute_position_from(), compute_pred_rel_state(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), compute_state_wrt_pred(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::GravityControls::gravitation(), jeod::PlanetOrientation::initialize(), jeod::LvlhFrame::initialize(), jeod::EphemerisPoint::initialize_state(), jeod::DynBodyFrameSwitch::is_ready(), jeod::DynBody::process_dynamic_attachment(), jeod::EphemerisZXZOrientation::propagate(), jeod::StructureIntegratedDynBody::rot_integ(), jeod::DynBody::rot_integ(), jeod::BasePlanet::set_alt_inertial(), jeod::DynBody::set_attitude_left_quaternion(), jeod::DynBody::set_attitude_matrix(), jeod::DynBody::set_attitude_rate(), jeod::DynBody::set_attitude_right_quaternion(), jeod::NorthEastDown::set_ned_trans_states(), jeod::DynBody::set_position(), jeod::DynBody::set_state(), jeod::DynBody::set_velocity(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::DynBody::switch_integration_frames(), jeod::StructureIntegratedDynBody::trans_integ(), jeod::DynBody::trans_integ(), transplant_node(), jeod::SpiceEphemOrientation::update(), jeod::GravityTorque::update(), jeod::EphemerisPoint::update(), jeod::EphemerisZXZOrientation::update(), jeod::LvlhFrame::update(), jeod::LvlhDerivedState::update(), jeod::PropagatedEphemerisPlanet::update(), jeod::OrbElemDerivedState::update(), jeod::EulerDerivedState::update(), jeod::PropagatedEphemerisOrientation::update(), jeod::NorthEastDown::update_from_cart(), jeod::NorthEastDown::update_from_ellip(), jeod::NorthEastDown::update_from_spher(), jeod::DynBody::update_integrated_state(), and jeod::EphemerisPoint::update_scaled().
update_time
double jeod::RefFrame::update_time protected
The time that the frame was lasted updated, dynamic time seconds.
trick_units(s)
Definition at line 133 of file ref_frame.hh.
Referenced by set_timestamp(), and timestamp().
The documentation for this class was generated from the following files:
ref_frame.hh
ref_frame_inline.hh
ref_frame.cc
ref_frame_compute_relative_state.cc
ref_frame_set_name.cc