JEOD: jeod::METAtmosphere Class Reference
jeod::METAtmosphere Class Reference
#include <MET_atmosphere.hh>
Public Types
enum AtmosMETGeoIndexType { ATMOS_MET_GI_AP = 0, ATMOS_MET_GI_KP = 1 }
Public Member Functions
METAtmosphere ()
~METAtmosphere () override
void update_atmosphere (const PlanetFixedPosition *pfix_pos, AtmosphereState *state) override
A pure virtual function for updating the atmosphere, and inserting
void update_atmosphere (const PlanetFixedPosition *pfix_pos, METAtmosphereStateVars *state)
Front-end to the computation of the METAtmosphere at the current time Inserts the results into the METAtmosphereStateVars pointed to by ext_state.
void update_time (const TimeUTC &time_utc)
Public Member Functions inherited from jeod::Atmosphere
Atmosphere ()
virtual ~Atmosphere ()
Data Fields
AtmosMETGeoIndexType geo_index_type
double geo_index
double F10
double F10B
METAtmosphereChemical species
Data Fields inherited from jeod::Atmosphere
bool active
If true the atmosphere state will calculate, if false it will not.
Private Member Functions
void update_atmosphere (const PlanetFixedPosition *pfix_pos)
Calculates the METAtmosphere, at the current time.
void modify_densities ()
void compute_solar_angles ()
void compute_exospheric_temperature ()
void jacchia ()
void compute_seasonal_latitude_variation ()
void compute_seasonal_lat_variation_He ()
void atmos_MET_FAIR5 ()
double compute_mol_wt (double altitude)
double apply_gauss_quadrature (int altitude_index_start, double ceiling)
METAtmosphere & operator= (const METAtmosphere &rhs)
METAtmosphere (const METAtmosphere &rhs)
Private Attributes
double altitude_km
double latitude
double longitude
double barometric_equation_ceiling
double trunc_julian_time
double tjt_year_start
double fraction_of_year
int day_of_year
int max_days_this_year
int year
double solar_declination_angle
double solar_hour_angle
METAtmosphereStateVars state
METAtmosphereThermal thermal
const double R_gas_constant
const double days_per_year
const double Avogadro
const double two_pi
const double three_pi_two
const double deg_to_rad
const int days_per_century
const int minutes_per_day
const double mol_weight_barometric_ceiling
const double base_fairing_height
const double fairing_k
Static Private Attributes
static const int num_mol_wt_coeffs = 7
static const double mol_wt_coeffs [num_mol_wt_coeffs]
static const int num_integ_divisions = 8
static const double gauss_altitudes [num_integ_divisions+1]
static const int gauss_n [num_integ_divisions] = { 4, 5, 6, 6, 6, 6, 6, 6 }
Friends
class InputProcessor
void init_attrjeod__METAtmosphere ()
Detailed Description
Definition at line 175 of file MET_atmosphere.hh.
Member Enumeration Documentation
AtmosMETGeoIndexType
enum jeod::METAtmosphere::AtmosMETGeoIndexType
Enumerator
ATMOS_MET_GI_AP
ATMOS_MET_GI_KP
Definition at line 180 of file MET_atmosphere.hh.
Constructor & Destructor Documentation
METAtmosphere() [1/2]
jeod::METAtmosphere::METAtmosphere ()
Definition at line 120 of file MET_atmosphere.cc.
~METAtmosphere()
jeod::METAtmosphere::~METAtmosphere () inline override
Definition at line 297 of file MET_atmosphere.hh.
METAtmosphere() [2/2]
jeod::METAtmosphere::METAtmosphere (const METAtmosphere & rhs) private
Member Function Documentation
apply_gauss_quadrature()
double jeod::METAtmosphere::apply_gauss_quadrature (int altitude_index_start, double ceiling) private
Definition at line 1234 of file MET_atmosphere.cc.
References barometric_equation_ceiling, compute_mol_wt(), jeod::METAtmosphereThermal::compute_temperature(), jeod::MessageHandler::error(), gauss_altitudes, gauss_n, jeod::GaussQuadrature::gauss_weights, jeod::GaussQuadrature::gauss_xvalues, and thermal.
Referenced by jacchia().
atmos_MET_FAIR5()
void jeod::METAtmosphere::atmos_MET_FAIR5 () private
Definition at line 1101 of file MET_atmosphere.cc.
References altitude_km, base_fairing_height, compute_seasonal_lat_variation_He(), jeod::AtmosphereState::density, fairing_k, jeod::METAtmosphereChemical::num_density, species, and state.
Referenced by modify_densities().
compute_exospheric_temperature()
void jeod::METAtmosphere::compute_exospheric_temperature () private
Definition at line 623 of file MET_atmosphere.cc.
References ATMOS_MET_GI_KP, jeod::METAtmosphereStateVars::exo_temp, F10, F10B, fraction_of_year, geo_index, geo_index_type, latitude, jeod::AtmosphereMessages::numerical_warning, solar_declination_angle, solar_hour_angle, state, two_pi, and jeod::MessageHandler::warn().
Referenced by update_atmosphere().
compute_mol_wt()
double jeod::METAtmosphere::compute_mol_wt (double altitude) private
Definition at line 1157 of file MET_atmosphere.cc.
References barometric_equation_ceiling, jeod::MessageHandler::error(), mol_weight_barometric_ceiling, and mol_wt_coeffs.
Referenced by apply_gauss_quadrature(), and jacchia().
compute_seasonal_lat_variation_He()
void jeod::METAtmosphere::compute_seasonal_lat_variation_He () private
Definition at line 1041 of file MET_atmosphere.cc.
References jeod::AtmosphereState::density, latitude, jeod::METAtmosphereChemical::num_density, solar_declination_angle, species, and state.
Referenced by atmos_MET_FAIR5(), and modify_densities().
compute_seasonal_latitude_variation()
void jeod::METAtmosphere::compute_seasonal_latitude_variation () private
Definition at line 984 of file MET_atmosphere.cc.
References altitude_km, jeod::AtmosphereState::density, fraction_of_year, latitude, and state.
Referenced by modify_densities().
compute_solar_angles()
void jeod::METAtmosphere::compute_solar_angles () private
Definition at line 431 of file MET_atmosphere.cc.
References day_of_year, days_per_century, days_per_year, deg_to_rad, fraction_of_year, longitude, max_days_this_year, minutes_per_day, solar_declination_angle, solar_hour_angle, three_pi_two, tjt_year_start, trunc_julian_time, two_pi, and year.
Referenced by update_atmosphere().
jacchia()
void jeod::METAtmosphere::jacchia () private
Definition at line 767 of file MET_atmosphere.cc.
References altitude_km, apply_gauss_quadrature(), Avogadro, barometric_equation_ceiling, compute_mol_wt(), jeod::METAtmosphereThermal::compute_temperature(), jeod::AtmosphereState::density, jeod::METAtmosphereChemical::frac, jeod::METAtmosphereStateVars::mol_weight, jeod::METAtmosphereChemical::mol_weight, mol_weight_barometric_ceiling, jeod::METAtmosphereChemical::nominal_mol_weight, jeod::METAtmosphereChemical::num_density, R_gas_constant, species, state, jeod::METAtmosphereThermal::T_out, jeod::AtmosphereState::temperature, thermal, and jeod::METAtmosphereThermal::update().
Referenced by update_atmosphere().
modify_densities()
void jeod::METAtmosphere::modify_densities () private
Definition at line 394 of file MET_atmosphere.cc.
References altitude_km, atmos_MET_FAIR5(), base_fairing_height, compute_seasonal_lat_variation_He(), and compute_seasonal_latitude_variation().
Referenced by update_atmosphere().
operator=()
METAtmosphere& jeod::METAtmosphere::operator= (const METAtmosphere & rhs) private
update_atmosphere() [1/3]
void jeod::METAtmosphere::update_atmosphere (const PlanetFixedPosition * position, AtmosphereState * state) override virtual
A pure virtual function for updating the atmosphere, and inserting
Parameters
[in] position planet fixed position
[out] state The AtmosphereState
Implements jeod::Atmosphere.
Definition at line 288 of file MET_atmosphere.cc.
References jeod::MessageHandler::error(), jeod::AtmosphereMessages::framework_error, and state.
Referenced by update_atmosphere(), and jeod::METAtmosphereState::update_state().
update_atmosphere() [2/3]
void jeod::METAtmosphere::update_atmosphere (const PlanetFixedPosition * pfix_pos, METAtmosphereStateVars * ext_state)
Front-end to the computation of the METAtmosphere at the current time Inserts the results into the METAtmosphereStateVars pointed to by ext_state.
This function is for a METAtmosphereStateVars.
Parameters
[in] pfix_pos Geodetic altitude, latitude and longitude.
[out] ext_state Where the state results will be sent.
Definition at line 324 of file MET_atmosphere.cc.
References jeod::MessageHandler::error(), jeod::AtmosphereMessages::framework_error, state, and update_atmosphere().
update_atmosphere() [3/3]
void jeod::METAtmosphere::update_atmosphere (const PlanetFixedPosition * pfix_pos) private
Calculates the METAtmosphere, at the current time.
Parameters
[in] pfix_pos Geodetic altitude, latitude and longitude.
Definition at line 347 of file MET_atmosphere.cc.
References jeod::METAtmosphereStateVars::A, jeod::AltLatLongState::altitude, altitude_km, compute_exospheric_temperature(), compute_solar_angles(), jeod::AtmosphereState::density, jeod::PlanetFixedPosition::ellip_coords, jeod::MessageHandler::error(), jeod::AtmosphereMessages::framework_error, jeod::METAtmosphereStateVars::He, jeod::METAtmosphereStateVars::Hyd, jacchia(), jeod::AltLatLongState::latitude, latitude, jeod::METAtmosphereStateVars::log10_dens, jeod::AltLatLongState::longitude, longitude, modify_densities(), jeod::METAtmosphereStateVars::mol_weight, jeod::METAtmosphereStateVars::N2, jeod::METAtmosphereChemical::num_density, jeod::METAtmosphereStateVars::Ox, jeod::METAtmosphereStateVars::Ox2, jeod::AtmosphereState::pressure, R_gas_constant, species, state, and jeod::AtmosphereState::temperature.
update_time()
void jeod::METAtmosphere::update_time (const TimeUTC & time_utc) inline
Definition at line 310 of file MET_atmosphere.hh.
References jeod::TimeStandard::trunc_julian_time, and trunc_julian_time.
Friends And Related Function Documentation
init_attrjeod__METAtmosphere
void init_attrjeod__METAtmosphere () friend
InputProcessor
friend class InputProcessor friend
Definition at line 177 of file MET_atmosphere.hh.
Field Documentation
altitude_km
double jeod::METAtmosphere::altitude_km private
trick_units(km) Copy of vehicle altitude
Definition at line 202 of file MET_atmosphere.hh.
Referenced by atmos_MET_FAIR5(), compute_seasonal_latitude_variation(), jacchia(), modify_densities(), and update_atmosphere().
Avogadro
const double jeod::METAtmosphere::Avogadro private
trick_units(–) Avogadros number
Definition at line 241 of file MET_atmosphere.hh.
Referenced by jacchia().
barometric_equation_ceiling
double jeod::METAtmosphere::barometric_equation_ceiling private
trick_units(km) the ceiling for integration using the barometric equation. Above this value, the integration switches to the diffusion equation. Value is 105km in the 1970 paper and 100km in the 1971 paper.
Definition at line 206 of file MET_atmosphere.hh.
Referenced by apply_gauss_quadrature(), compute_mol_wt(), and jacchia().
base_fairing_height
const double jeod::METAtmosphere::base_fairing_height private
trick_units(km) Altitude at which to start fairing between the lower altitude which has no seasonal-latitude Helium density variation, and the upper atmosphere – starting at 500km – which does.
Definition at line 252 of file MET_atmosphere.hh.
Referenced by atmos_MET_FAIR5(), and modify_densities().
day_of_year
int jeod::METAtmosphere::day_of_year private
trick_units(count) day number since start of year.
Definition at line 218 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
days_per_century
const int jeod::METAtmosphere::days_per_century private
trick_units(count) days per century
Definition at line 246 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
days_per_year
const double jeod::METAtmosphere::days_per_year private
trick_units(day) days per year
Definition at line 240 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
deg_to_rad
const double jeod::METAtmosphere::deg_to_rad private
trick_units(degree/rad) degree-to-radian conversion
Definition at line 244 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
F10
double jeod::METAtmosphere::F10
trick_units(–) Solar radio noise flux.
Definition at line 192 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature().
F10B
double jeod::METAtmosphere::F10B
trick_units(–) 90 day average of solar radio noise flux.
Definition at line 194 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature().
fairing_k
const double jeod::METAtmosphere::fairing_k private
trick_units(rad/km) Factor which, when multiplied by the altitude delta above the base-fairing-height provides an angle. The square of the cosine of that angle indicates how much of the seasonal-variation in Helium density to apply. density = corrected-density * (non-corrected-density / corrected-density) ^ (cos^2 (fairing_k * delta-altitude)) At base-fairing-height, none gets applied. By 500km, it all gets applied.
Definition at line 256 of file MET_atmosphere.hh.
Referenced by atmos_MET_FAIR5().
fraction_of_year
double jeod::METAtmosphere::fraction_of_year private
trick_units(–) fraction of this year that has passed.
Definition at line 215 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature(), compute_seasonal_latitude_variation(), and compute_solar_angles().
gauss_altitudes
const double jeod::METAtmosphere::gauss_altitudes static private
Initial value:
= {
     90.0, 105.0, 125.0, 160.0, 200.0, 300.0, 500.0, 1500.0, 2500.0 }
trick_units(–) The boundaries of the cells that are used to break down the integration over the atmosphere into more manaegable pieces. NOTE - gauss_altitudes[1] must mark the upper limit of the altitude over which the barometric equation is valid, this is either 100km or 105km, depending on which paper is used; gauss-altitude[6] must be equal to 500km.
Definition at line 278 of file MET_atmosphere.hh.
Referenced by apply_gauss_quadrature().
gauss_n
const int jeod::METAtmosphere::gauss_n = { 4, 5, 6, 6, 6, 6, 6, 6 } static private
trick_units(–) The number of data-points to be used for the gauss-quadrature integration for each interval defined in the gauss_altitudes array. AKA the order of the gauss-quadrature.
Definition at line 285 of file MET_atmosphere.hh.
Referenced by apply_gauss_quadrature().
geo_index
double jeod::METAtmosphere::geo_index
trick_units(–) Geomagnetic variations index (Ap or Kp).
Definition at line 190 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature().
geo_index_type
AtmosMETGeoIndexType jeod::METAtmosphere::geo_index_type
Definition at line 187 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature().
latitude
double jeod::METAtmosphere::latitude private
trick_units(rad) Copy of vehicle latitude
Definition at line 203 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature(), compute_seasonal_lat_variation_He(), compute_seasonal_latitude_variation(), and update_atmosphere().
longitude
double jeod::METAtmosphere::longitude private
trick_units(rad) Copy of vehicle longitude
Definition at line 204 of file MET_atmosphere.hh.
Referenced by compute_solar_angles(), and update_atmosphere().
max_days_this_year
int jeod::METAtmosphere::max_days_this_year private
trick_units(count) number of days this year (365 or 366)
Definition at line 221 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
minutes_per_day
const int jeod::METAtmosphere::minutes_per_day private
trick_units(count) minutes per day
Definition at line 247 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
mol_weight_barometric_ceiling
const double jeod::METAtmosphere::mol_weight_barometric_ceiling private
trick_units(g/mol) mean molar mass at barometric-ceiling and higher.
Definition at line 250 of file MET_atmosphere.hh.
Referenced by compute_mol_wt(), and jacchia().
mol_wt_coeffs
const double jeod::METAtmosphere::mol_wt_coeffs static private
Initial value:
=
       { 28.15204, -0.085586,  1.284E-4, -1.0056E-5,
         -1.021E-5, 1.5044E-6, 9.9826E-8 }
trick_units(–) polynomial coefficients for computing the molecular weights in the region where the barometric equation is used.
Definition at line 270 of file MET_atmosphere.hh.
Referenced by compute_mol_wt().
num_integ_divisions
const int jeod::METAtmosphere::num_integ_divisions = 8 static private
trick_units(count) the number of altitude bins used for dividing the atmosphere into manageable pieces.
Definition at line 275 of file MET_atmosphere.hh.
num_mol_wt_coeffs
const int jeod::METAtmosphere::num_mol_wt_coeffs = 7 static private
trick_units(count) the number of polynomial coefficients.
Definition at line 268 of file MET_atmosphere.hh.
R_gas_constant
const double jeod::METAtmosphere::R_gas_constant private
trick_units(J/(mol*K)) R
Definition at line 239 of file MET_atmosphere.hh.
Referenced by jacchia(), and update_atmosphere().
solar_declination_angle
double jeod::METAtmosphere::solar_declination_angle private
trick_units(rad) declination angle
Definition at line 226 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature(), compute_seasonal_lat_variation_He(), and compute_solar_angles().
solar_hour_angle
double jeod::METAtmosphere::solar_hour_angle private
trick_units(rad) solar hour angle
Definition at line 228 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature(), and compute_solar_angles().
species
METAtmosphereChemical jeod::METAtmosphere::species
trick_units(–) The chemical composition of the atmosphere.
Definition at line 197 of file MET_atmosphere.hh.
Referenced by atmos_MET_FAIR5(), compute_seasonal_lat_variation_He(), jacchia(), and update_atmosphere().
state
METAtmosphereStateVars jeod::METAtmosphere::state private
trick_units(–) A scratch set of state variables, used for populating state variables internally before being copied onto the real state.
Definition at line 230 of file MET_atmosphere.hh.
Referenced by atmos_MET_FAIR5(), compute_exospheric_temperature(), compute_seasonal_lat_variation_He(), compute_seasonal_latitude_variation(), jacchia(), and update_atmosphere().
thermal
METAtmosphereThermal jeod::METAtmosphere::thermal private
trick_units(–) Thermal aspect of the model
Definition at line 234 of file MET_atmosphere.hh.
Referenced by apply_gauss_quadrature(), and jacchia().
three_pi_two
const double jeod::METAtmosphere::three_pi_two private
trick_units(–) 1.5 pi
Definition at line 243 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
tjt_year_start
double jeod::METAtmosphere::tjt_year_start private
trick_units(day) value of trunc_julian_time at the start of the current year.
Definition at line 212 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
trunc_julian_time
double jeod::METAtmosphere::trunc_julian_time private
trick_units(day) Current time
Definition at line 211 of file MET_atmosphere.hh.
Referenced by compute_solar_angles(), and update_time().
two_pi
const double jeod::METAtmosphere::two_pi private
trick_units(–) 2 pi
Definition at line 242 of file MET_atmosphere.hh.
Referenced by compute_exospheric_temperature(), and compute_solar_angles().
year
int jeod::METAtmosphere::year private
trick_units(count) current year identifier
Definition at line 224 of file MET_atmosphere.hh.
Referenced by compute_solar_angles().
The documentation for this class was generated from the following files:
MET_atmosphere.hh
MET_atmosphere.cc