JEOD: jeod::VehicleProperties Class Reference
jeod::VehicleProperties Class Reference final
Captures pointers to various vehicle properties that are commonly used in the constraint concept.
#include <vehicle_properties.hh>
Public Member Functions
VehicleProperties ()
Default constructor, for use by Trick only.
VehicleProperties (SolverTypes::Vector3RefT parent_to_structure_offset_in, SolverTypes::Matrix3x3RefT parent_to_structure_transform_in, double &mass_in, SolverTypes::Vector3RefT structure_to_body_offset_in, SolverTypes::Matrix3x3RefT inertia_in, SolverTypes::Matrix3x3RefT structure_to_body_transform_in, double &inverse_mass_in, SolverTypes::Matrix3x3RefT inverse_inertia_in)
Non-default constructor that sets all elements.
SolverTypes::ConstDecayedVector3T get_parent_to_structure_offset () const
SolverTypes::ConstMatrix3x3RefT get_parent_to_structure_transform () const
double get_mass () const
SolverTypes::ConstDecayedVector3T get_structure_to_body_offset () const
SolverTypes::ConstMatrix3x3RefT get_inertia () const
SolverTypes::Matrix3x3RefT get_structure_to_body_transform () const
double get_inverse_mass () const
SolverTypes::Matrix3x3RefT get_inverse_inertia () const
Private Attributes
SolverTypes::Vector3PointerT parent_to_structure_offset
Pointer to the vehicle's structure_point.position vector.
SolverTypes::Matrix3x3PointerT parent_to_structure_transform
Pointer to the vehicle's structure_point.T_parent_this matrix.
double * mass
Pointer to the vehicle's composite_properties.mass member.
SolverTypes::Vector3PointerT structure_to_body_offset
Pointer to the vehicle's composite_properties.position vector.
SolverTypes::Matrix3x3PointerT inertia
Pointer to the vehicle's composite_properties.inertia tensor.
SolverTypes::Matrix3x3PointerT structure_to_body_transform
Pointer to the vehicle's composite_properties.T_parent_this matrix.
double * inverse_mass
Pointer to the vehicle's inverse_mass member.
SolverTypes::Matrix3x3PointerT inverse_inertia
Pointer to the vehicle's inverse_inertia member.
Friends
class InputProcessor
void init_attrjeod__VehicleProperties ()
Detailed Description
Captures pointers to various vehicle properties that are commonly used in the constraint concept.
As this is potentially quite dangerous, access to the captured members is limited to const getters.
This class is not designed for extensibility.
Definition at line 73 of file vehicle_properties.hh.
Constructor & Destructor Documentation
VehicleProperties() [1/2]
jeod::VehicleProperties::VehicleProperties () inline
Default constructor, for use by Trick only.
Definition at line 89 of file vehicle_properties.hh.
VehicleProperties() [2/2]
jeod::VehicleProperties::VehicleProperties (SolverTypes::Vector3RefT parent_to_structure_offset_in, SolverTypes::Matrix3x3RefT parent_to_structure_transform_in, double & mass_in, SolverTypes::Vector3RefT structure_to_body_offset_in, SolverTypes::Matrix3x3RefT inertia_in, SolverTypes::Matrix3x3RefT structure_to_body_transform_in, double & inverse_mass_in, SolverTypes::Matrix3x3RefT inverse_inertia_in) inline
Non-default constructor that sets all elements.
Parameters
parent_to_structure_offset_in Reference to the vehicle's structure_point.position vector.
parent_to_structure_transform_in Reference to the vehicle's structure_point.T_parent_this matrix.
mass_in Reference to the vehicle's composite_properties.mass member.
structure_to_body_offset_in Reference to the vehicle's composite_properties.position vector.
inertia_in Reference to the vehicle's composite_properties.inertia tensor.
structure_to_body_transform_in Reference to the vehicle's composite_properties.T_parent_this matrix.
inverse_mass_in Reference to the vehicle's inverse_mass member.
inverse_inertia_in Reference to the vehicle's inverse_inertia member.
Definition at line 121 of file vehicle_properties.hh.
Member Function Documentation
get_inertia()
SolverTypes::ConstMatrix3x3RefT jeod::VehicleProperties::get_inertia () const inline
Returns
Const reference to the vehicle's inertia tensor, in vehicle body frame coordinates.
Definition at line 190 of file vehicle_properties.hh.
References inertia.
get_inverse_inertia()
SolverTypes::Matrix3x3RefT jeod::VehicleProperties::get_inverse_inertia () const inline
Returns
Const reference to the inverse of the vehicle's inertia tensor, in vehicle body frame coordinates.
Definition at line 216 of file vehicle_properties.hh.
References inverse_inertia.
Referenced by jeod::ConstraintComponent::compute_rotational_response(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
get_inverse_mass()
double jeod::VehicleProperties::get_inverse_mass () const inline
Returns
The multiplicative inverse of the vehicle's mass.
Definition at line 207 of file vehicle_properties.hh.
References inverse_mass.
Referenced by jeod::ForceConstraintComponent::setup_constraint(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
get_mass()
double jeod::VehicleProperties::get_mass () const inline
Returns
The vehicle mass.
Definition at line 171 of file vehicle_properties.hh.
References mass.
get_parent_to_structure_offset()
SolverTypes::ConstDecayedVector3T jeod::VehicleProperties::get_parent_to_structure_offset () const inline
Returns
Const reference to the offset from the parent vehicle's structural frame origin to this vehicle's structural origin, in parent structural coordinates.
Definition at line 154 of file vehicle_properties.hh.
References parent_to_structure_offset.
Referenced by jeod::DynBodyConstraintsSolver::compute_root_to_this().
get_parent_to_structure_transform()
SolverTypes::ConstMatrix3x3RefT jeod::VehicleProperties::get_parent_to_structure_transform () const inline
Returns
Const reference to the transformation matrix from the parent vehicle's structural frame to this vehicle's structural frame.
Definition at line 163 of file vehicle_properties.hh.
References parent_to_structure_transform.
Referenced by jeod::DynBodyConstraintsSolver::compute_root_to_this().
get_structure_to_body_offset()
SolverTypes::ConstDecayedVector3T jeod::VehicleProperties::get_structure_to_body_offset () const inline
Returns
Const reference to the offset from the origin of the vehicle's structural frame to the vehicle's center of mass, in vehicle structural coordinates.
Definition at line 181 of file vehicle_properties.hh.
References structure_to_body_offset.
Referenced by jeod::ConstrainedPointMass::compute_constraint_position_com(), jeod::DynBodyConstraintsSolver::solve(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
get_structure_to_body_transform()
SolverTypes::Matrix3x3RefT jeod::VehicleProperties::get_structure_to_body_transform () const inline
Returns
Const reference to the transformation matrix from the vehicle's structural frame to its body frame.
Definition at line 199 of file vehicle_properties.hh.
References structure_to_body_transform.
Referenced by jeod::ConstraintComponent::compute_rotational_response(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
Friends And Related Function Documentation
init_attrjeod__VehicleProperties
void init_attrjeod__VehicleProperties () friend
InputProcessor
friend class InputProcessor friend
Definition at line 79 of file vehicle_properties.hh.
Field Documentation
inertia
SolverTypes::Matrix3x3PointerT jeod::VehicleProperties::inertia private
Pointer to the vehicle's composite_properties.inertia tensor.
trick_units(m^2*kg)
Definition at line 248 of file vehicle_properties.hh.
Referenced by get_inertia().
inverse_inertia
SolverTypes::Matrix3x3PointerT jeod::VehicleProperties::inverse_inertia private
Pointer to the vehicle's inverse_inertia member.
trick_units(1/kg/m^2)
Definition at line 263 of file vehicle_properties.hh.
Referenced by get_inverse_inertia().
inverse_mass
double* jeod::VehicleProperties::inverse_mass private
Pointer to the vehicle's inverse_mass member.
trick_units(1/kg)
Definition at line 258 of file vehicle_properties.hh.
Referenced by get_inverse_mass().
mass
double* jeod::VehicleProperties::mass private
Pointer to the vehicle's composite_properties.mass member.
trick_units(kg)
Definition at line 238 of file vehicle_properties.hh.
Referenced by get_mass().
parent_to_structure_offset
SolverTypes::Vector3PointerT jeod::VehicleProperties::parent_to_structure_offset private
Pointer to the vehicle's structure_point.position vector.
trick_units(m)
Definition at line 228 of file vehicle_properties.hh.
Referenced by get_parent_to_structure_offset().
parent_to_structure_transform
SolverTypes::Matrix3x3PointerT jeod::VehicleProperties::parent_to_structure_transform private
Pointer to the vehicle's structure_point.T_parent_this matrix.
trick_units(–)
Definition at line 233 of file vehicle_properties.hh.
Referenced by get_parent_to_structure_transform().
structure_to_body_offset
SolverTypes::Vector3PointerT jeod::VehicleProperties::structure_to_body_offset private
Pointer to the vehicle's composite_properties.position vector.
trick_units(m)
Definition at line 243 of file vehicle_properties.hh.
Referenced by get_structure_to_body_offset().
structure_to_body_transform
SolverTypes::Matrix3x3PointerT jeod::VehicleProperties::structure_to_body_transform private
Pointer to the vehicle's composite_properties.T_parent_this matrix.
trick_units(–)
Definition at line 253 of file vehicle_properties.hh.
Referenced by get_structure_to_body_transform().
The documentation for this class was generated from the following file:
vehicle_properties.hh