JEOD: jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator Class Reference
jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator Class Reference
Integrates a generalized derivative second order ODE using Gauss-Jackson.
#include <gauss_jackson_generalized_second_order_ode_integrator.hh>
Public Member Functions
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator ()=default
Default constructor.
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator (const er7_utils::IntegratorConstructor &priming_constructor, GaussJacksonIntegrationControls &controls, unsigned int position_size, unsigned int velocity_size, const er7_utils::GeneralizedPositionDerivativeFunctions &deriv_funs, er7_utils::IntegrationControls &priming_controls)
Non-default constructor.
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator (const GaussJacksonGeneralizedDerivSecondOrderODEIntegrator &src)
Copy constructor.
~GaussJacksonGeneralizedDerivSecondOrderODEIntegrator () override
Destructor.
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator & operator= (GaussJacksonGeneralizedDerivSecondOrderODEIntegrator src)
Assignment operator.
void swap (GaussJacksonGeneralizedDerivSecondOrderODEIntegrator &other)
Non-throwing swap.
er7_utils::SecondOrderODEIntegrator * create_copy () const override
Replicate this.
void reset_integrator () override
Reset the integrator.
er7_utils::IntegratorResult integrate (double dyn_dt, unsigned int target_stage, const double *acc, double *vel, double *pos) override
Integrate state.
Private Attributes
GaussJacksonFirstOrderODEIntegrator vel_integrator
Integrator for the generalized velocity.
GaussJacksonSimpleSecondOrderODEIntegrator pos_integrator
Integrator for the generalized position.
double * posdot {}
Generalized position time derivative.
double * posdotdot {}
Generalized position second time derivative.
Friends
class InputProcessor
void init_attrjeod__GaussJacksonGeneralizedDerivSecondOrderODEIntegrator ()
Detailed Description
Integrates a generalized derivative second order ODE using Gauss-Jackson.
Generalized position is integrated via a simple second order Gauss-Jackson integrator. Generalized velocity is integrated via a first order summed Adams integrator.
Definition at line 82 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
Constructor & Destructor Documentation
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator() [1/3]
jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator () default
Default constructor.
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator() [2/3]
jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator (const er7_utils::IntegratorConstructor & priming_constructor, GaussJacksonIntegrationControls & controls, unsigned int position_size, unsigned int velocity_size, const er7_utils::GeneralizedPositionDerivativeFunctions & deriv_funs, er7_utils::IntegrationControls & priming_controls)
Non-default constructor.
Parameters
priming_constructor Integrator constructor for the technique used during priming.
controls The Gauss-Jackson integration controls that drives this state integrator.
position_size Generalized position vector size.
velocity_size Generalized velocity vector size.
deriv_funs Position vector time deriv functions.
priming_controls Integration controls used during priming.
Definition at line 34 of file gauss_jackson_generalized_second_order_ode_integrator.cc.
References posdot, and posdotdot.
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator() [3/3]
jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator (const GaussJacksonGeneralizedDerivSecondOrderODEIntegrator & src)
Copy constructor.
Definition at line 50 of file gauss_jackson_generalized_second_order_ode_integrator.cc.
References posdot, and posdotdot.
~GaussJacksonGeneralizedDerivSecondOrderODEIntegrator()
jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::~GaussJacksonGeneralizedDerivSecondOrderODEIntegrator () override
Destructor.
Definition at line 61 of file gauss_jackson_generalized_second_order_ode_integrator.cc.
References posdot, and posdotdot.
Member Function Documentation
create_copy()
er7_utils::SecondOrderODEIntegrator * jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::create_copy () const override
Replicate this.
Definition at line 81 of file gauss_jackson_generalized_second_order_ode_integrator.cc.
integrate()
er7_utils::IntegratorResult jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::integrate (double dyn_dt, unsigned int target_stage, const double * acc, double * vel, double * pos) inline override
Integrate state.
Definition at line 154 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
References jeod::GaussJacksonFirstOrderODEIntegrator::integrate(), jeod::GaussJacksonSimpleSecondOrderODEIntegrator::integrate(), pos_integrator, posdot, posdotdot, and vel_integrator.
operator=()
GaussJacksonGeneralizedDerivSecondOrderODEIntegrator& jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::operator= (GaussJacksonGeneralizedDerivSecondOrderODEIntegrator src) inline
Assignment operator.
Definition at line 123 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
References swap().
reset_integrator()
void jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::reset_integrator () inline override
Reset the integrator.
Definition at line 145 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
References pos_integrator, jeod::GaussJacksonFirstOrderODEIntegrator::reset_integrator(), jeod::GaussJacksonSimpleSecondOrderODEIntegrator::reset_integrator(), and vel_integrator.
swap()
void jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::swap (GaussJacksonGeneralizedDerivSecondOrderODEIntegrator & other)
Non-throwing swap.
Definition at line 68 of file gauss_jackson_generalized_second_order_ode_integrator.cc.
References pos_integrator, posdot, posdotdot, jeod::GaussJacksonFirstOrderODEIntegrator::swap(), jeod::GaussJacksonSimpleSecondOrderODEIntegrator::swap(), and vel_integrator.
Referenced by operator=().
Friends And Related Function Documentation
init_attrjeod__GaussJacksonGeneralizedDerivSecondOrderODEIntegrator
void init_attrjeod__GaussJacksonGeneralizedDerivSecondOrderODEIntegrator () friend
InputProcessor
friend class InputProcessor friend
Definition at line 84 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
Field Documentation
pos_integrator
GaussJacksonSimpleSecondOrderODEIntegrator jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::pos_integrator private
Integrator for the generalized position.
trick_units(–)
Definition at line 176 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
Referenced by integrate(), reset_integrator(), and swap().
posdot
double* jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::posdot {} private
Generalized position time derivative.
trick_units(–)
Definition at line 181 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
Referenced by GaussJacksonGeneralizedDerivSecondOrderODEIntegrator(), integrate(), swap(), and ~GaussJacksonGeneralizedDerivSecondOrderODEIntegrator().
posdotdot
double* jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::posdotdot {} private
Generalized position second time derivative.
trick_units(–)
Definition at line 186 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
Referenced by GaussJacksonGeneralizedDerivSecondOrderODEIntegrator(), integrate(), swap(), and ~GaussJacksonGeneralizedDerivSecondOrderODEIntegrator().
vel_integrator
GaussJacksonFirstOrderODEIntegrator jeod::GaussJacksonGeneralizedDerivSecondOrderODEIntegrator::vel_integrator private
Integrator for the generalized velocity.
trick_units(–)
Definition at line 171 of file gauss_jackson_generalized_second_order_ode_integrator.hh.
Referenced by integrate(), reset_integrator(), and swap().
The documentation for this class was generated from the following files:
gauss_jackson_generalized_second_order_ode_integrator.hh
gauss_jackson_generalized_second_order_ode_integrator.cc