JEOD: jeod::MassPointState Class Reference
jeod::MassPointState Class Reference
Defines the state – position and orientation – of a MassPoint.
#include <mass_point_state.hh>
Public Member Functions
MassPointState ()=default
virtual ~MassPointState ()=default
virtual void initialize_mass_point ()
Initialize a mass point.
void update_point (const double pt_location[3])
Update the mass point's structure-to-point vector.
void update_orientation (const double transformation[3][3])
Update the mass point's structure-to-point frame transformation matrix and items derived from it.
void update_orientation (const Quaternion &left_quat)
Update the mass point's structure-to-point frame transformation matrix and items derived from it.
void compute_quaternion ()
Compute quaternion.
void compute_transformation ()
Compute matrix.
void copy_state (const MassPointState &source)
Copy the provided state to this.
void negate (const MassPointState &source)
Copy a mass point state, negated.
void incr_left (const MassPointState &s_ab)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_B:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
void incr_right (const MassPointState &s_bc)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_A:B, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
void decr_left (const MassPointState &s_ab)
Compute S_B:C = (-S_A:B) + S_A:C, with this initially containing S_A:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
void decr_right (const MassPointState &s_bc)
Compute S_A:B = S_A:C + (-S_B:C) with this initially containing S_A:C, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Data Fields
double position [3] {}
Mass point location with respect to the origin of some parent frame and expressed in the parent frame's coordinates.
Quaternion Q_parent_this
Left transformation quaternion from the parent frame to the frame associated with the mass point.
double T_parent_this [3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } }
transformation matrix from the parent frame to the frame associated with the mass point.
Friends
class InputProcessor
void init_attrjeod__MassPointState ()
Detailed Description
Defines the state – position and orientation – of a MassPoint.
Definition at line 81 of file mass_point_state.hh.
Constructor & Destructor Documentation
MassPointState()
jeod::MassPointState::MassPointState () default
~MassPointState()
virtual jeod::MassPointState::~MassPointState () virtual default
Member Function Documentation
compute_quaternion()
void jeod::MassPointState::compute_quaternion () inline
Compute quaternion.
Someone changed the matrix under our noses.
Definition at line 188 of file mass_point_state.hh.
References jeod::Quaternion::left_quat_from_transformation(), Q_parent_this, and T_parent_this.
compute_transformation()
void jeod::MassPointState::compute_transformation () inline
Compute matrix.
Someone changed the quaternion under our noses.
Definition at line 196 of file mass_point_state.hh.
References jeod::Quaternion::left_quat_to_transformation(), Q_parent_this, and T_parent_this.
Referenced by jeod::MassBody::attach_update_properties(), decr_left(), decr_right(), incr_left(), incr_right(), and jeod::MassBody::reattach().
copy_state()
void jeod::MassPointState::copy_state (const MassPointState & source) inline
Copy the provided state to this.
Parameters
[in] source Source state
Definition at line 206 of file mass_point_state.hh.
References jeod::Vector3::copy(), jeod::Matrix3x3::copy(), position, Q_parent_this, and T_parent_this.
decr_left()
void jeod::MassPointState::decr_left (const MassPointState & s_ab)
Compute S_B:C = (-S_A:B) + S_A:C, with this initially containing S_A:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
Parameters
[in] s_ab Left addend
Definition at line 240 of file mass_point_state.cc.
References jeod::Numerical::compare_exact(), compute_transformation(), jeod::Vector3::decr(), jeod::Quaternion::multiply_conjugate(), jeod::Quaternion::normalize(), position, Q_parent_this, jeod::Quaternion::scalar, T_parent_this, and jeod::Vector3::transform().
Referenced by jeod::MassPoint::compute_relative_state().
decr_right()
void jeod::MassPointState::decr_right (const MassPointState & s_bc)
Compute S_A:B = S_A:C + (-S_B:C) with this initially containing S_A:C, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Parameters
[in] s_bc Left addend
Definition at line 283 of file mass_point_state.cc.
References jeod::Numerical::compare_exact(), compute_transformation(), jeod::Vector3::decr(), jeod::Quaternion::multiply_left_conjugate(), jeod::Quaternion::normalize(), position, Q_parent_this, jeod::Quaternion::scalar, T_parent_this, and jeod::Vector3::transform_transpose_decr().
incr_left()
void jeod::MassPointState::incr_left (const MassPointState & s_ab)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_B:C, the supplied argument containing S_A:B, and the resultant composition of states stored in this.
Parameters
[in] s_ab Left addend
Definition at line 154 of file mass_point_state.cc.
References jeod::Numerical::compare_exact(), compute_transformation(), jeod::Vector3::incr(), jeod::Quaternion::multiply(), jeod::Quaternion::normalize(), position, Q_parent_this, jeod::Quaternion::scalar, T_parent_this, and jeod::Vector3::transform_transpose().
incr_right()
void jeod::MassPointState::incr_right (const MassPointState & s_bc)
Compute S_A:C = S_A:B + S_B:C, with this initially containing S_A:B, the supplied argument containing S_B:C, and the resultant composition of states stored in this.
Parameters
[in] s_bc Right addend
Definition at line 195 of file mass_point_state.cc.
References jeod::Numerical::compare_exact(), compute_transformation(), jeod::Matrix3x3::copy(), jeod::Vector3::incr(), jeod::Quaternion::multiply_left(), jeod::Quaternion::normalize(), position, Q_parent_this, jeod::Quaternion::scalar, T_parent_this, and jeod::Vector3::transform_transpose_incr().
initialize_mass_point()
void jeod::MassPointState::initialize_mass_point () virtual
Initialize a mass point.
Reimplemented in jeod::MassPoint.
Definition at line 52 of file mass_point_state.cc.
References jeod::Matrix3x3::identity(), jeod::Vector3::initialize(), jeod::Quaternion::make_identity(), position, Q_parent_this, and T_parent_this.
Referenced by jeod::MassPoint::compute_pred_rel_state(), jeod::MassPoint::compute_relative_state(), jeod::MassPoint::compute_state_wrt_pred(), and jeod::MassPoint::initialize_mass_point().
negate()
void jeod::MassPointState::negate (const MassPointState & source)
Copy a mass point state, negated.
Parameters
[in] source Source state
Definition at line 120 of file mass_point_state.cc.
References jeod::Numerical::compare_exact(), jeod::Quaternion::conjugate(), jeod::Vector3::copy(), jeod::Matrix3x3::identity(), jeod::Quaternion::make_identity(), jeod::Vector3::negate(), position, Q_parent_this, jeod::Quaternion::scalar, T_parent_this, jeod::Vector3::transform_transpose(), and jeod::Matrix3x3::transpose().
update_orientation() [1/2]
void jeod::MassPointState::update_orientation (const double transformation[3][3]) inline
Update the mass point's structure-to-point frame transformation matrix and items derived from it.
Parameters
[in] transformation New structure-to-point xform
Definition at line 166 of file mass_point_state.hh.
References jeod::Matrix3x3::copy(), jeod::Quaternion::left_quat_from_transformation(), Q_parent_this, and T_parent_this.
Referenced by jeod::MassBody::attach_update_properties(), and jeod::MassBody::reattach().
update_orientation() [2/2]
void jeod::MassPointState::update_orientation (const Quaternion & left_quat) inline
Update the mass point's structure-to-point frame transformation matrix and items derived from it.
Parameters
[in] left_quat New structure-to-point quat
Definition at line 178 of file mass_point_state.hh.
References jeod::Quaternion::left_quat_to_transformation(), Q_parent_this, and T_parent_this.
update_point()
void jeod::MassPointState::update_point (const double pt_location[3]) inline
Update the mass point's structure-to-point vector.
Parameters
[in] pt_location New location, struct coords.
Units: M
Definition at line 155 of file mass_point_state.hh.
References jeod::Vector3::copy(), and position.
Referenced by jeod::MassBody::attach_update_properties(), jeod::MassPointInit::initialize_mass_point(), and jeod::MassBody::reattach().
Friends And Related Function Documentation
init_attrjeod__MassPointState
void init_attrjeod__MassPointState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 83 of file mass_point_state.hh.
Field Documentation
position
double jeod::MassPointState::position[3] {}
Mass point location with respect to the origin of some parent frame and expressed in the parent frame's coordinates.
trick_units(m)
Definition at line 89 of file mass_point_state.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::MassBody::attach_update_properties(), jeod::MassBody::calc_composite_cm(), jeod::MassBody::calc_composite_inertia(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::MassPoint::compute_pred_rel_state(), jeod::DynBody::compute_ref_point_transform(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPoint::compute_state_wrt_pred(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), copy_state(), decr_left(), decr_right(), incr_left(), incr_right(), initialize_mass_point(), jeod::MassPropertiesInit::initialize_mass_properties(), negate(), jeod::MassBody::print_body(), jeod::DynBody::process_dynamic_attachment(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::MassBody::reattach(), jeod::Wrench::transform_to_parent(), jeod::Facet::update_articulation_internal(), jeod::DynBody::update_integrated_state(), jeod::MassBody::update_mass_properties(), and update_point().
Q_parent_this
Quaternion jeod::MassPointState::Q_parent_this
Left transformation quaternion from the parent frame to the frame associated with the mass point.
trick_units(–)
Definition at line 95 of file mass_point_state.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::MassBody::attach_update_properties(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::MassPoint::compute_pred_rel_state(), compute_quaternion(), jeod::DynBody::compute_ref_point_transform(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPoint::compute_state_wrt_pred(), compute_transformation(), copy_state(), decr_left(), decr_right(), incr_left(), incr_right(), jeod::MassBody::initialize_mass(), initialize_mass_point(), jeod::MassPointInit::initialize_mass_point(), negate(), jeod::MassBody::reattach(), jeod::DynBody::update_integrated_state(), and update_orientation().
T_parent_this
double jeod::MassPointState::T_parent_this[3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } }
transformation matrix from the parent frame to the frame associated with the mass point.
NOTE: The MassPointState infrastructure ensures that the quaternion and matrix representations are equivalent.trick_units(–)
Definition at line 103 of file mass_point_state.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::MassBody::attach_update_properties(), jeod::MassBody::calc_composite_inertia(), jeod::DynBody::collect_forces_and_torques(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::MassPoint::compute_pred_rel_state(), compute_quaternion(), jeod::DynBody::compute_ref_point_transform(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPoint::compute_state_wrt_pred(), compute_transformation(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), copy_state(), decr_left(), decr_right(), incr_left(), incr_right(), jeod::MassBody::initialize_mass(), initialize_mass_point(), jeod::MassPointInit::initialize_mass_point(), jeod::MassPropertiesInit::initialize_mass_properties(), jeod::MassBody::MassBody(), negate(), jeod::MassBody::print_body(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::MassBody::reattach(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::Wrench::transform_to_parent(), jeod::GravityTorque::update(), jeod::FlatPlate::update_articulation_internal(), jeod::Facet::update_articulation_internal(), jeod::DynBody::update_integrated_state(), jeod::MassBody::update_mass_properties(), and update_orientation().
The documentation for this class was generated from the following files:
mass_point_state.hh
mass_point_state.cc