/* Autogenerated from environment/gravity/data/earth_solid_tides.d */

/*******************************************************************************

Purpose:
  (Default parameters for Earth solid body tides.)

References:
  (((TBS)))

Assumptions and Limitations:
  (((TBS)))


*******************************************************************************/

//! Namespace jeod
namespace jeod
{
class SphericalHarmonicsSolidBodyTidesInit;
} // namespace jeod

#define JEOD_FRIEND_CLASS SphericalHarmonicsSolidBodyTidesInit_earth_solid_tides_default_data

// JEOD includes
#include "environment/gravity/include/spherical_harmonics_delta_coeffs_init.hh"
#include "environment/gravity/include/spherical_harmonics_solid_body_tides_init.hh"
#include "environment/gravity/include/spherical_harmonics_tidal_effects_init.hh"
#include "utils/memory/include/jeod_alloc.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/earth_solid_tides.hh"

//! Namespace jeod
namespace jeod
{

void SphericalHarmonicsSolidBodyTidesInit_earth_solid_tides_default_data::initialize(
    SphericalHarmonicsSolidBodyTidesInit * SphericalHarmonicsSolidBodyTidesInit_ptr)
{
    SphericalHarmonicsSolidBodyTidesInit_ptr->k2 = 0.29525;
    // IERS elastic earth Love number
    SphericalHarmonicsSolidBodyTidesInit_ptr->tidal_body_names.push_back("Sun");
    SphericalHarmonicsSolidBodyTidesInit_ptr->tidal_body_names.push_back("Moon");
}
} // namespace jeod
