/* Autogenerated from environment/gravity/data/earth_GGM05C.d */

/*******************************************************************************

Purpose:
  (Simple model to provide a spherical earth gravity.)

References:
  (((Data extracted from the earth_GGM05C model contained in this model)))

Assumptions and Limitations:
  ((NA))


*******************************************************************************/

//! Namespace jeod
namespace jeod
{
class SphericalHarmonicsGravitySource;
} // namespace jeod

#define JEOD_FRIEND_CLASS SphericalHarmonicsGravitySource_earth_spherical_default_data

// JEOD includes
#include "environment/gravity/include/gravity_source.hh"
#include "environment/gravity/include/spherical_harmonics_gravity_source.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/earth_spherical.hh"

//! Namespace jeod
namespace jeod
{

void SphericalHarmonicsGravitySource_earth_spherical_default_data::initialize(
    SphericalHarmonicsGravitySource * SphericalHarmonicsGravitySource_ptr)
{
    SphericalHarmonicsGravitySource_ptr->name = "Earth";
    SphericalHarmonicsGravitySource_ptr->degree = 0;
    SphericalHarmonicsGravitySource_ptr->order = 0;
    SphericalHarmonicsGravitySource_ptr->mu = 3.986004415E+14;
    SphericalHarmonicsGravitySource_ptr->radius = 6378136.3;
}
} // namespace jeod
