/* Autogenerated from /Users/dhammen/work/jeod/2.0/trunk/trunk/models/environment/gravity/data/jupiter_spherical.d */

/*******************************************************************************

PURPOSE:
  (Default data to model Jupiter's gravity.)

REFERENCE:
   (((DE405)))

ASSUMPTIONS AND LIMITATIONS:
   ((1. Vehicles are sufficiently far from Jupiter))


*******************************************************************************/


//! Namespace jeod
namespace jeod {
class SphericalHarmonicsGravitySource;
}
#define JEOD_FRIEND_CLASS SphericalHarmonicsGravitySource_jupiter_spherical_default_data

// JEOD includes
#include "environment/gravity/include/spherical_harmonics_gravity_source.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/jupiter_spherical.hh"



//! Namespace jeod
namespace jeod {

void
SphericalHarmonicsGravitySource_jupiter_spherical_default_data::initialize (
   SphericalHarmonicsGravitySource * SphericalHarmonicsGravitySource_ptr)
{
   SphericalHarmonicsGravitySource_ptr->name = "Jupiter";
   SphericalHarmonicsGravitySource_ptr->mu = 1.26731229E+17;
   SphericalHarmonicsGravitySource_ptr->radius = 1000 * (71492.0);
}
} // End JEOD namespace
