/* Autogenerated from environment/gravity/data/mars_spherical.d */

/*******************************************************************************

Purpose:
  (Default data to model Mars gravity.)

References:
  (((TBS)))

Assumptions and Limitations:
  ((1. Vehicles are sufficiently far from Mars))


*******************************************************************************/


//! Namespace jeod
namespace jeod {
class SphericalHarmonicsGravitySource;
}
#define JEOD_FRIEND_CLASS SphericalHarmonicsGravitySource_mars_spherical_default_data

// JEOD includes
#include "environment/gravity/include/gravity_source.hh"
#include "environment/gravity/include/spherical_harmonics_gravity_source.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/mars_spherical.hh"



//! Namespace jeod
namespace jeod {

void
SphericalHarmonicsGravitySource_mars_spherical_default_data::initialize (
   SphericalHarmonicsGravitySource * SphericalHarmonicsGravitySource_ptr)
{
   SphericalHarmonicsGravitySource_ptr->name = "Mars";
   SphericalHarmonicsGravitySource_ptr->mu = 1000000000 * (42828.375214);
   SphericalHarmonicsGravitySource_ptr->radius = 1000 * (3396.0);
}
} // End JEOD namespace
