/* Autogenerated from environment/gravity/data/moon_spherical.d */

/*******************************************************************************

Purpose:
  (Default data to model the Moon's gravity.)

References:
  (((Konopliv, A.S., et al.)(Recent Gravity Models as a Result of the Lunar
     Prospector Mission)(Icarus, International Journal of Solar System
     Studies, vol. 150)(2001)))

Assumptions and Limitations:
  ((1. Vehicles are sufficiently far from the Moon))


*******************************************************************************/


//! Namespace jeod
namespace jeod {
class SphericalHarmonicsGravitySource;
}
#define JEOD_FRIEND_CLASS SphericalHarmonicsGravitySource_moon_spherical_default_data

// JEOD includes
#include "environment/gravity/include/gravity_source.hh"
#include "environment/gravity/include/spherical_harmonics_gravity_source.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/moon_spherical.hh"



//! Namespace jeod
namespace jeod {

void
SphericalHarmonicsGravitySource_moon_spherical_default_data::initialize (
   SphericalHarmonicsGravitySource * SphericalHarmonicsGravitySource_ptr)
{
   SphericalHarmonicsGravitySource_ptr->name = "Moon";
   SphericalHarmonicsGravitySource_ptr->mu = 1000000000 * (4902.801076);
   SphericalHarmonicsGravitySource_ptr->radius = 1000 * (1738.0);
}
} // End JEOD namespace
