/* Autogenerated from environment/gravity/data/sun_spherical.d */

/*******************************************************************************

Purpose:
  (Default data to model the Sun's gravity.)

References:
  (((Seidelmann, P.K., ed.)(Explanatory Supplement to the Astronomical
     Almanac)(University Science Books)(1992)))

Assumptions and Limitations:
  ((1. Vehicles are sufficiently far from the Sun))


*******************************************************************************/

/* Sun default data, see Seidelmann pages 696, 697, 700 */

//! Namespace jeod
namespace jeod {
class SphericalHarmonicsGravitySource;
}
#define JEOD_FRIEND_CLASS SphericalHarmonicsGravitySource_sun_spherical_default_data

// JEOD includes
#include "environment/gravity/include/gravity_source.hh"
#include "environment/gravity/include/spherical_harmonics_gravity_source.hh"
#include "utils/named_item/include/named_item.hh"

// Unsupported includes
#include "../include/sun_spherical.hh"



//! Namespace jeod
namespace jeod {

void
SphericalHarmonicsGravitySource_sun_spherical_default_data::initialize (
   SphericalHarmonicsGravitySource * SphericalHarmonicsGravitySource_ptr)
{
   SphericalHarmonicsGravitySource_ptr->name = "Sun";
   SphericalHarmonicsGravitySource_ptr->mu = 1.32712440E+20;
   SphericalHarmonicsGravitySource_ptr->radius = 1000 * (696000.0);
}
} // End JEOD namespace
