JEOD: jeod::SolarBetaDerivedState Class Reference
jeod::SolarBetaDerivedState Class Reference
The class for calculating the solar beta of a vehicle.
#include <solar_beta_derived_state.hh>
Public Member Functions
SolarBetaDerivedState ()
Construct a SolarBetaDerivedState object.
~SolarBetaDerivedState () override
Destruct a SolarBetaDerivedState.
void initialize (DynBody &subject_body, DynManager &dyn_manager) override
Begin initialization of a SolarBetaDerivedState.
void update (void) override
Update the state.
Public Member Functions inherited from jeod::DerivedState
DerivedState ()
Construct a DerivedState.
virtual ~DerivedState ()
Destruct a DerivedState.
void set_reference_name (const char *new_name)
Set the reference_name to a copy of the supplied value.
Data Fields
Planet * planet
The planet, the name of which is specified by the inherited reference_name data member.
Planet * sun
The sun, found by looking for the planetary object named "Sun".
double solar_beta
The angle between the orbital plane and the sun position vector.
bool active
Indicates whether the model is "active".
Data Fields inherited from jeod::DerivedState
DynBody * subject
The body that is the subject of the derived state.
char * reference_name
The name of the object with respect to which the subject state is assessed.
Protected Attributes
RefFrameState veh_wrt_planet
The state of the vehicle with respect to the planet.
double sun_wrt_planet [3]
The position of the sun with respect to the planet.
Protected Attributes inherited from jeod::DerivedState
char * state_identifier
An identifier for this derived state, constructed at initialization time from the class name, the subject body name, and the reference name.
Private Member Functions
SolarBetaDerivedState (const SolarBetaDerivedState &)
SolarBetaDerivedState & operator= (const SolarBetaDerivedState &)
Friends
class InputProcessor
void init_attrjeod__SolarBetaDerivedState ()
Additional Inherited Members
Protected Member Functions inherited from jeod::DerivedState
Planet * find_planet (const DynManager &dyn_manager, const char *planet_name, const char *variable_name)
Find the Planet with the given name, failing if not found.
Detailed Description
The class for calculating the solar beta of a vehicle.
Assumptions and Limitations
The vehicle must be in orbit about the named planet
Definition at line 83 of file solar_beta_derived_state.hh.
Constructor & Destructor Documentation
SolarBetaDerivedState() [1/2]
jeod::SolarBetaDerivedState::SolarBetaDerivedState (void)
Construct a SolarBetaDerivedState object.
Definition at line 59 of file solar_beta_derived_state.cc.
References jeod::Vector3::initialize(), and sun_wrt_planet.
~SolarBetaDerivedState()
jeod::SolarBetaDerivedState::~SolarBetaDerivedState (void) override
Destruct a SolarBetaDerivedState.
Definition at line 170 of file solar_beta_derived_state.cc.
References jeod::BasePlanet::inertial, planet, sun, and jeod::Subscription::unsubscribe().
SolarBetaDerivedState() [2/2]
jeod::SolarBetaDerivedState::SolarBetaDerivedState (const SolarBetaDerivedState &) private
Member Function Documentation
initialize()
void jeod::SolarBetaDerivedState::initialize (DynBody & subject_body, DynManager & dyn_manager) override virtual
Begin initialization of a SolarBetaDerivedState.
The initialize method for all subclasses of DerivedState must pass the initialize call to their immediate parent class, which in turn must do the same, eventually invoking this method.
Parameters
[in,out] subject_body Subject body
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::DerivedState.
Definition at line 80 of file solar_beta_derived_state.cc.
References active, jeod::DerivedState::find_planet(), jeod::BasePlanet::inertial, jeod::DerivedState::initialize(), planet, jeod::DerivedState::reference_name, jeod::Subscription::subscribe(), and sun.
operator=()
SolarBetaDerivedState& jeod::SolarBetaDerivedState::operator= (const SolarBetaDerivedState &) private
update()
void jeod::SolarBetaDerivedState::update (void) override virtual
Update the state.
Reimplemented from jeod::DerivedState.
Definition at line 109 of file solar_beta_derived_state.cc.
References active, jeod::DynBody::composite_body, jeod::RefFrame::compute_position_from(), jeod::RefFrame::compute_relative_state(), jeod::Vector3::cross(), jeod::DerivedStateMessages::divide_by_zero, jeod::Vector3::dot(), EPSILON, jeod::MessageHandler::fail(), jeod::BasePlanet::inertial, planet, jeod::RefFrameTrans::position, solar_beta, jeod::DerivedState::subject, sun, sun_wrt_planet, jeod::RefFrameState::trans, veh_wrt_planet, jeod::RefFrameTrans::velocity, and jeod::Vector3::vmagsq().
Friends And Related Function Documentation
init_attrjeod__SolarBetaDerivedState
void init_attrjeod__SolarBetaDerivedState () friend
InputProcessor
friend class InputProcessor friend
Definition at line 85 of file solar_beta_derived_state.hh.
Field Documentation
active
bool jeod::SolarBetaDerivedState::active
Indicates whether the model is "active".
This flag defaults to true. This default value results in
Initialization-time subscriptions issued against the planet-centered and sun-centered inertial frames to ensure that the planet and the Sun are a part of the active reference frame tree, and
Run-time calculations of the solar beta angle, updated by calls to SolarBetaDerivedState::update.
Setting the active flag to false prior to the call to SolarBetaDerivedState::initialize permanently disables the model. Setting the active flag to true after having set it to false prior to the call to initialize initially will have no effect; the model is permanently disabled.
If the value of the flag is true at the time of the call to SolarBetaDerivedState::initialize, subsequently setting the flag to false will temporarily disable the model (cause SolarBetaDerivedState::update to immediately return). Updates will once again be performed when the flag is set to true.trick_units(–)
Definition at line 136 of file solar_beta_derived_state.hh.
Referenced by initialize(), and update().
planet
Planet* jeod::SolarBetaDerivedState::planet
The planet, the name of which is specified by the inherited reference_name data member.
trick_units(–)
Definition at line 99 of file solar_beta_derived_state.hh.
Referenced by initialize(), update(), and ~SolarBetaDerivedState().
solar_beta
double jeod::SolarBetaDerivedState::solar_beta
The angle between the orbital plane and the sun position vector.
Positive solar beta will be on the side of the positive angular momentum vector.trick_units(rad)
Definition at line 111 of file solar_beta_derived_state.hh.
Referenced by update().
sun
Planet* jeod::SolarBetaDerivedState::sun
The sun, found by looking for the planetary object named "Sun".
trick_units(–)
Definition at line 104 of file solar_beta_derived_state.hh.
Referenced by initialize(), update(), and ~SolarBetaDerivedState().
sun_wrt_planet
double jeod::SolarBetaDerivedState::sun_wrt_planet[3] protected
The position of the sun with respect to the planet.
trick_units(m)
Definition at line 170 of file solar_beta_derived_state.hh.
Referenced by SolarBetaDerivedState(), and update().
veh_wrt_planet
RefFrameState jeod::SolarBetaDerivedState::veh_wrt_planet protected
The state of the vehicle with respect to the planet.
trick_units(–)
Definition at line 165 of file solar_beta_derived_state.hh.
Referenced by update().
The documentation for this class was generated from the following files:
solar_beta_derived_state.hh
solar_beta_derived_state.cc