JEOD: jeod::TimeUDE Class Reference
jeod::TimeUDE Class Reference
Represents all instances of times with a user-defined epoch, accepting that Mission Elapsed Time requires some further definition.
#include <time_ude.hh>
Public Member Functions
TimeUDE ()=default
~TimeUDE () override=default
TimeUDE (const TimeUDE &)=delete
TimeUDE & operator= (const TimeUDE &)=delete
void initialize_initializer_time (TimeManagerInit *tm_init) override
Each time type is initialized from its parent in the initialization tree, except one.
void add_type_initialize (const int seeking_status, TimeManagerInit *tm_init) override
Adds a UDE type to the initialization tree when it is appropriate to do so.
void initialize_from_parent (TimeManagerInit *tm_init) override
Initializes this time-type.
void set_time_by_clock ()
sets the decimal representation of time by the clock
void set_time_by_seconds (const double new_seconds) override
Given a seconds value, sets days and clock values.
void set_time_by_days (const double new_days) override
Given a seconds value, sets days and clock values.
void set_epoch_initializing_value (const double simtime, const double epoch_initializing_value)
sets the initial epoch value
Public Member Functions inherited from jeod::JeodBaseTime
JeodBaseTime ()
Construct a JeodBaseTime.
virtual ~JeodBaseTime ()
Destroy a JeodBaseTime.
JeodBaseTime (const JeodBaseTime &)=delete
JeodBaseTime & operator= (const JeodBaseTime &)=delete
void add_type_update (const int seeking_status, TimeManagerInit *tm_init)
Recursively adds elements to the update tree.
void set_name (std::string name_in)
Setter for the name.
void set_index (int idx)
Setter for the index (force user to be carefule)
int get_index ()
Getter for the index.
void override_initialized (bool init)
Force reset the initialization status.
bool is_initialized ()
Read the initialization status.
virtual void update ()
Updates each of the derived times from its parent time.
Data Fields
int epoch_year {}
Gregorian calendar year number at epoch.
int epoch_month {}
Gregorian calendar month number at epoch.
int epoch_day {}
Gregorian calendar day number at epoch.
int epoch_hour {}
24-hour clock hour number at epoch.
int epoch_minute {}
Clock minute number at epoch.
double epoch_second {}
Clock seconds value at epoch.
int clock_day {}
Whole number of days since epoch, in clock format.
int clock_hour {}
Whole number of hours since epoch, in clock format.
int clock_minute {}
Whole number of minutes since epoch, in clock format.
double clock_second {}
Number of seconds since epoch, in clock format.
double last_clock_update {}
Simtime at the last time the clock was updated.
TimeEnum::TimeFormat epoch_format {TimeEnum::undefined}
Format for expressing the epoch of this type (calendar, julian, etc)
TimeEnum::TimeFormat initial_value_format {TimeEnum::undefined}
Format for expressing the initial value of this type (calendar, julian, etc)
std::string epoch_defined_in_name {""}
Name of time type in which epoch defined.
Data Fields inherited from jeod::JeodBaseTime
double initializing_value {}
Value used to define sim start time.
int update_converter_direction {}
Determines which converter function (a_to_b (+1) or b_to_a (-1)) to use.
double seconds {}
Elapsed time from epoch.
NamedItem name
Name of time-type.
std::string initialize_from_name {""}
Name of time-type from which initial value is derived.
std::string update_from_name {""}
Name of time-type from which update values are derived.
TimeManager * time_manager {}
Pointer to the TimeManager.
TimeConverter * update_converter_ptr {}
Pointer to the converter class needed to update the time.
Protected Member Functions
bool must_be_singleton () override
Returns false in response to the question "does this time class have to be a singleton".
void convert_epoch_to_update (JeodBaseTime *epoch_ptr, JeodBaseTime *update_ptr, TimeManagerInit *tm_init)
Converts the time, as specified in the epoch time-type to the update_from time-type.
void set_epoch_dyn (TimeDyn *epoch_ptr)
Temporarily overwrites the simulation data in time type "epoch" with the epoch value.
void set_epoch_times (JeodBaseTime *epoch_ptr)
To set the times in the epoch time type coincident with the zero-point of this time-type.
void set_epoch_ude (TimeUDE *epoch_ptr)
Overwrites the data in time type "epoch" with that in this class that specifies the epoch.
void set_epoch_std (TimeStandard *epoch_ptr)
Overwrites the data in time type "epoch" with that in this class that specifies the epoch.
void set_initial_times ()
Sets the initial value of this type from the myriad of initialization options.
void clock_update ()
converts the decimal seconds value to a clock interface
void verify_epoch ()
Verifies that the epoch assignments are legitimate, and tests for the presence and legitimacy of values for defining the epoch.
void verify_init ()
Verifies that any assignment to initialize_from is flagged as inappropriate, and tests for the presence of initializing data.
void verify_update ()
Ensures that the time-type identified as "update_from" is legitimate.
Protected Member Functions inherited from jeod::JeodBaseTime
void add_parent (JeodBaseTime &parent)
Link the argument time as the update source for this time.
Protected Attributes
double epoch_initializing_value {}
Value of epoch in appropriate format.
bool initializing_data_present {}
Whether initializing data is present.
bool epoch_data_present {}
Whether epoch data is present.
bool epoch_value_is_set_number {}
Whether there is some numerical input that could set epoch.
bool epoch_value_is_set_calendar {}
Whether there is some calendar input that could set epoch.
bool epoch_value_is_set_clock {}
Whether there is some clock input that could set epoch.
int update_index {}
The index of the time-type from which this one is updated.
int epoch_index {}
The index of the time-type in which this one's epoch is defined.
Protected Attributes inherited from jeod::JeodBaseTime
int index {}
Index-value of time-type in the registry.
bool initialized {}
Whether time has been initialized to a real time.
double days {}
Elapsed time from epoch.
double initial_value {}
Value of "seconds" at the start of the sim.
double clock_resolution {0.0001}
The resolution limit when generating clock and calendar-clock values.
TimeLinks links
Linkage to the hierarchy of time conversions.
Friends
class InputProcessor
void init_attrjeod__TimeUDE ()
Detailed Description
Represents all instances of times with a user-defined epoch, accepting that Mission Elapsed Time requires some further definition.
Definition at line 89 of file time_ude.hh.
Constructor & Destructor Documentation
TimeUDE() [1/2]
jeod::TimeUDE::TimeUDE () default
~TimeUDE()
jeod::TimeUDE::~TimeUDE () override default
TimeUDE() [2/2]
jeod::TimeUDE::TimeUDE (const TimeUDE &) delete
Member Function Documentation
add_type_initialize()
void jeod::TimeUDE::add_type_initialize (const int seeking_status, TimeManagerInit * time_manager_init) override virtual
Adds a UDE type to the initialization tree when it is appropriate to do so.
Assumptions and Limitations
The time type from which the UDE updates must be in the tree above the UDE.
If the time type in which the epoch is defined is another UDE, it also must be in the tree above this UDE
This function is only called when the UDE is NOT being used to initialize the simulation.
Parameters
[in] seeking_status An indicator of relative level of progression in the tree.
[in] time_manager_init The TM initializer.
Reimplemented from jeod::JeodBaseTime.
Definition at line 84 of file time_ude.cc.
References jeod::JeodBaseTime::add_type_initialize(), jeod::NamedItem::c_str(), epoch_defined_in_name, epoch_index, jeod::MessageHandler::fail(), jeod::TimeManagerInit::get_conv_dir_init(), jeod::TimeManagerInit::get_status(), jeod::TimeManager::get_time_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeManagerInit::increment_status(), jeod::JeodBaseTime::index, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, jeod::TimeManager::num_types, jeod::TimeManagerInit::set_status(), jeod::JeodBaseTime::time_manager, jeod::JeodBaseTime::update_from_name, update_index, verify_epoch(), and verify_update().
clock_update()
void jeod::TimeUDE::clock_update () protected
converts the decimal seconds value to a clock interface
Assumptions and Limitations
24 hrs = 1 day; 60 minutes - 1 hour ; 60 seconds = 1 minute
Definition at line 1353 of file time_ude.cc.
References clock_day, clock_hour, clock_minute, jeod::JeodBaseTime::clock_resolution, clock_second, and jeod::JeodBaseTime::seconds.
Referenced by set_time_by_days(), and set_time_by_seconds().
convert_epoch_to_update()
void jeod::TimeUDE::convert_epoch_to_update (JeodBaseTime * epoch_ptr, JeodBaseTime * update_from_ptr, TimeManagerInit * time_manager_init) protected
Converts the time, as specified in the epoch time-type to the update_from time-type.
This sets the update_from time at the epoch of "this", and allows for the initialization of the converter.
Assumptions and Limitations
That there is a converter available to do this in one step
Future work may include an extension to this routine to cover other cases.
Parameters
[in] epoch_ptr pointer to the epoch time-type
[in] update_from_ptr pointer to the time-type from which this time-type will be updated.
[in] time_manager_init The TM initializer.
Definition at line 216 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeConverter::convert_a_to_b(), jeod::TimeConverter::convert_b_to_a(), epoch_defined_in_name, epoch_index, jeod::MessageHandler::fail(), jeod::TimeManagerInit::get_conv_dir_init(), jeod::TimeManagerInit::get_conv_ptr_index(), jeod::TimeManager::get_converter_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeConverter::initialize(), jeod::JeodBaseTime::name, jeod::TimeManager::num_types, jeod::TimeConverter::override_initialized(), jeod::JeodBaseTime::override_initialized(), jeod::JeodBaseTime::time_manager, jeod::JeodBaseTime::update_from_name, and update_index.
Referenced by initialize_from_parent(), and initialize_initializer_time().
initialize_from_parent()
void jeod::TimeUDE::initialize_from_parent (TimeManagerInit * time_manager_init) override virtual
Initializes this time-type.
Assumptions and Limitations
The subject object has a parent, a time-type with which it ticks. This has already been tested for.
Parameters
[in] time_manager_init The TM initializer.
Reimplemented from jeod::JeodBaseTime.
Definition at line 278 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeConverter::convert_a_to_b(), jeod::TimeConverter::convert_b_to_a(), convert_epoch_to_update(), jeod::JeodBaseTime::days, epoch_data_present, epoch_index, jeod::MessageHandler::fail(), jeod::TimeManagerInit::get_conv_dir_init(), jeod::TimeManagerInit::get_conv_ptr_index(), jeod::TimeManager::get_converter_ptr(), jeod::TimeManager::get_time_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::JeodBaseTime::index, jeod::JeodBaseTime::initial_value, jeod::TimeMessages::initialization_error, jeod::TimeConverter::initialize(), jeod::JeodBaseTime::initialize_from_parent(), jeod::JeodBaseTime::initialized, initializing_data_present, jeod::TimeConverter::is_initialized(), jeod::JeodBaseTime::is_initialized(), jeod::JeodBaseTime::name, jeod::TimeManager::num_types, jeod::JeodBaseTime::override_initialized(), jeod::TimeMessages::redundancy_error, jeod::JeodBaseTime::seconds, set_epoch_times(), jeod::JeodBaseTime::set_time_by_seconds(), jeod::JeodBaseTime::time_manager, jeod::JeodBaseTime::update_from_name, update_index, verify_init(), and jeod::MessageHandler::warn().
initialize_initializer_time()
void jeod::TimeUDE::initialize_initializer_time (TimeManagerInit * time_manager_init) override virtual
Each time type is initialized from its parent in the initialization tree, except one.
In order to have an absolute reference time, one of the time types must be defined ahead of time. This is called the initializer time. This function initializes the initializer time.
Parameters
[in] time_manager_init The TM initializer.
Implements jeod::JeodBaseTime.
Definition at line 488 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeConverter::convert_a_to_b(), jeod::TimeConverter::convert_b_to_a(), convert_epoch_to_update(), jeod::JeodBaseTime::days, jeod::TimeMessages::duplicate_methods, epoch_data_present, epoch_index, jeod::MessageHandler::fail(), jeod::TimeManagerInit::get_conv_dir_init(), jeod::TimeManagerInit::get_conv_ptr_index(), jeod::TimeManager::get_converter_ptr(), jeod::TimeManager::get_time_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::JeodBaseTime::index, jeod::MessageHandler::inform(), initial_value_format, jeod::TimeConverter::initialize(), jeod::JeodBaseTime::initialized, initializing_data_present, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, jeod::TimeManager::num_types, jeod::JeodBaseTime::override_initialized(), jeod::JeodBaseTime::seconds, set_epoch_times(), jeod::TimeManagerInit::sim_start_format, jeod::JeodBaseTime::time_manager, jeod::TimeManager::time_standards_exist(), jeod::TimeEnum::undefined, jeod::JeodBaseTime::update_from_name, update_index, verify_epoch(), verify_init(), verify_update(), and jeod::MessageHandler::warn().
must_be_singleton()
bool jeod::TimeUDE::must_be_singleton () override protected virtual
Returns false in response to the question "does this time class have to be a singleton".
Assumptions and Limitations
There can be more than one UDE
Returns
false
Reimplemented from jeod::JeodBaseTime.
Definition at line 65 of file time_ude.cc.
operator=()
TimeUDE& jeod::TimeUDE::operator= (const TimeUDE &) delete
set_epoch_dyn()
void jeod::TimeUDE::set_epoch_dyn (TimeDyn * epoch_ptr) protected
Temporarily overwrites the simulation data in time type "epoch" with the epoch value.
Assumptions and Limitations
"Epoch" is DynTime
Parameters
[in] epoch_ptr pointer to the epoch time-type
Definition at line 759 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeEnum::calendar, jeod::TimeEnum::clock, jeod::TimeEnum::days_since_epoch, epoch_data_present, epoch_day, epoch_defined_in_name, epoch_format, epoch_hour, epoch_initializing_value, epoch_minute, epoch_month, epoch_value_is_set_number, epoch_year, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, initializing_data_present, jeod::TimeMessages::invalid_setup_error, jeod::TimeEnum::Julian, jeod::TimeEnum::julian, jeod::TimeEnum::modified_julian, jeod::JeodBaseTime::name, jeod::TimeMessages::redundancy_error, jeod::TimeEnum::seconds_since_epoch, jeod::JeodBaseTime::set_time_by_days(), jeod::JeodBaseTime::set_time_by_seconds(), jeod::TimeEnum::truncated_julian, jeod::TimeEnum::undefined, and jeod::MessageHandler::warn().
Referenced by set_epoch_times().
set_epoch_initializing_value()
void jeod::TimeUDE::set_epoch_initializing_value (const double simtime, const double epoch)
sets the initial epoch value
Assumptions and Limitations
Assumes that the number that is passed in is correctly entered with the correct units interpretation.
Parameters
[in] simtime Used to verify that this is at initialization
[in] epoch the value to be used.
Definition at line 1328 of file time_ude.cc.
References jeod::NamedItem::c_str(), epoch_initializing_value, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, and jeod::MessageHandler::warn().
set_epoch_std()
void jeod::TimeUDE::set_epoch_std (TimeStandard * epoch_ptr) protected
Overwrites the data in time type "epoch" with that in this class that specifies the epoch.
Assumptions and Limitations
"Epoch" is Absolute Derived Time
Parameters
[in] epoch_ptr pointer to the epoch time-type
Definition at line 888 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeEnum::calendar, jeod::TimeStandard::calendar_day, jeod::TimeStandard::calendar_hour, jeod::TimeStandard::calendar_minute, jeod::TimeStandard::calendar_month, jeod::TimeStandard::calendar_second, jeod::TimeStandard::calendar_year, jeod::TimeEnum::clock, jeod::TimeStandard::convert_from_calendar(), jeod::TimeEnum::days_since_epoch, epoch_day, epoch_defined_in_name, epoch_format, epoch_hour, epoch_initializing_value, epoch_minute, epoch_month, epoch_second, epoch_value_is_set_calendar, epoch_value_is_set_number, epoch_year, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeMessages::invalid_setup_error, jeod::TimeEnum::Julian, jeod::TimeEnum::julian, jeod::TimeEnum::modified_julian, jeod::JeodBaseTime::name, jeod::TimeEnum::seconds_since_epoch, jeod::TimeStandard::set_time_by_days(), jeod::TimeStandard::set_time_by_seconds(), jeod::TimeStandard::set_time_by_trunc_julian(), jeod::TimeEnum::truncated_julian, jeod::TimeEnum::undefined, and jeod::MessageHandler::warn().
Referenced by set_epoch_times().
set_epoch_times()
void jeod::TimeUDE::set_epoch_times (JeodBaseTime * epoch_ptr) protected
To set the times in the epoch time type coincident with the zero-point of this time-type.
Assumptions and Limitations
"This" is being defined by epoch.
Parameters
[in] epoch_ptr pointer to the epoch time-type
Definition at line 722 of file time_ude.cc.
References jeod::MessageHandler::fail(), jeod::TimeMessages::invalid_setup_error, set_epoch_dyn(), set_epoch_std(), and set_epoch_ude().
Referenced by initialize_from_parent(), and initialize_initializer_time().
set_epoch_ude()
void jeod::TimeUDE::set_epoch_ude (TimeUDE * epoch_ptr) protected
Overwrites the data in time type "epoch" with that in this class that specifies the epoch.
Assumptions and Limitations
"Epoch" is a User-Defined-Epoch Time.
Parameters
[in] epoch_ptr pointer to the epoch time-type
Definition at line 1046 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeEnum::calendar, jeod::TimeEnum::clock, clock_day, clock_hour, clock_minute, clock_second, jeod::TimeEnum::days_since_epoch, epoch_day, epoch_defined_in_name, epoch_format, epoch_hour, epoch_initializing_value, epoch_minute, epoch_second, epoch_value_is_set_clock, epoch_value_is_set_number, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeMessages::invalid_setup_error, jeod::TimeEnum::Julian, jeod::TimeEnum::julian, jeod::TimeEnum::modified_julian, jeod::JeodBaseTime::name, jeod::TimeEnum::seconds_since_epoch, set_time_by_clock(), set_time_by_seconds(), jeod::TimeEnum::truncated_julian, jeod::TimeEnum::undefined, and jeod::MessageHandler::warn().
Referenced by set_epoch_times().
set_initial_times()
void jeod::TimeUDE::set_initial_times () protected
Sets the initial value of this type from the myriad of initialization options.
Assumptions and Limitations
At least one of the following is non-zero: initializing value, clock_day, clock_hour, clock_minute, clock_second, seconds, days
Definition at line 1169 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::TimeEnum::calendar, jeod::TimeEnum::clock, clock_day, clock_hour, clock_minute, clock_second, jeod::JeodBaseTime::days, jeod::TimeEnum::days_since_epoch, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, initial_value_format, initializing_data_present, jeod::JeodBaseTime::initializing_value, jeod::TimeMessages::invalid_setup_error, jeod::TimeEnum::Julian, jeod::TimeEnum::julian, jeod::TimeMessages::memory_error, jeod::TimeEnum::modified_julian, jeod::JeodBaseTime::name, jeod::TimeMessages::redundancy_error, jeod::JeodBaseTime::seconds, jeod::TimeEnum::seconds_since_epoch, jeod::TimeEnum::truncated_julian, and jeod::TimeEnum::undefined.
Referenced by verify_init().
set_time_by_clock()
void jeod::TimeUDE::set_time_by_clock ()
sets the decimal representation of time by the clock
Assumptions and Limitations
24 hrs = 1 day; 60 minutes - 1 hour ; 60 seconds = 1 minute
Definition at line 1313 of file time_ude.cc.
References clock_day, clock_hour, clock_minute, clock_second, jeod::JeodBaseTime::days, and jeod::JeodBaseTime::seconds.
Referenced by set_epoch_ude().
set_time_by_days()
void jeod::TimeUDE::set_time_by_days (const double new_days) override virtual
Given a seconds value, sets days and clock values.
Parameters
[in] new_days new value for days
Units: day
Reimplemented from jeod::JeodBaseTime.
Definition at line 1291 of file time_ude.cc.
References clock_update(), and jeod::JeodBaseTime::set_time_by_days().
set_time_by_seconds()
void jeod::TimeUDE::set_time_by_seconds (const double new_seconds) override virtual
Given a seconds value, sets days and clock values.
Parameters
[in] new_seconds new value for seconds
Units: s
Reimplemented from jeod::JeodBaseTime.
Definition at line 1301 of file time_ude.cc.
References clock_update(), and jeod::JeodBaseTime::set_time_by_seconds().
Referenced by jeod::TimeConverter_Dyn_UDE::convert_a_to_b(), jeod::TimeConverter_STD_UDE::convert_a_to_b(), and set_epoch_ude().
verify_epoch()
void jeod::TimeUDE::verify_epoch () protected
Verifies that the epoch assignments are legitimate, and tests for the presence and legitimacy of values for defining the epoch.
Definition at line 1384 of file time_ude.cc.
References jeod::NamedItem::c_str(), epoch_data_present, epoch_day, epoch_defined_in_name, epoch_format, epoch_hour, epoch_index, epoch_initializing_value, epoch_minute, epoch_month, epoch_second, epoch_value_is_set_calendar, epoch_value_is_set_clock, epoch_value_is_set_number, epoch_year, jeod::MessageHandler::fail(), jeod::TimeMessages::incomplete_setup_error, jeod::JeodBaseTime::index, jeod::TimeMessages::invalid_setup_error, jeod::JeodBaseTime::name, jeod::TimeMessages::redundancy_error, jeod::TimeManager::time_lookup(), jeod::JeodBaseTime::time_manager, and jeod::TimeEnum::undefined.
Referenced by add_type_initialize(), and initialize_initializer_time().
verify_init()
void jeod::TimeUDE::verify_init () protected
Verifies that any assignment to initialize_from is flagged as inappropriate, and tests for the presence of initializing data.
Definition at line 1491 of file time_ude.cc.
References jeod::NamedItem::c_str(), jeod::JeodBaseTime::initialize_from_name, jeod::JeodBaseTime::name, jeod::TimeMessages::redundancy_error, set_initial_times(), jeod::TimeManager::time_lookup(), jeod::JeodBaseTime::time_manager, and jeod::MessageHandler::warn().
Referenced by initialize_from_parent(), and initialize_initializer_time().
verify_update()
void jeod::TimeUDE::verify_update () protected
Ensures that the time-type identified as "update_from" is legitimate.
Definition at line 1528 of file time_ude.cc.
References jeod::MessageHandler::fail(), jeod::TimeManager::get_time_ptr(), jeod::TimeMessages::incomplete_setup_error, jeod::TimeMessages::invalid_setup_error, jeod::TimeManager::time_lookup(), jeod::JeodBaseTime::time_manager, jeod::JeodBaseTime::update_from_name, and update_index.
Referenced by add_type_initialize(), and initialize_initializer_time().
Friends And Related Function Documentation
init_attrjeod__TimeUDE
void init_attrjeod__TimeUDE () friend
InputProcessor
friend class InputProcessor friend
Definition at line 91 of file time_ude.hh.
Field Documentation
clock_day
int jeod::TimeUDE::clock_day {}
Whole number of days since epoch, in clock format.
trick_units(–)
Definition at line 125 of file time_ude.hh.
Referenced by clock_update(), set_epoch_ude(), set_initial_times(), and set_time_by_clock().
clock_hour
int jeod::TimeUDE::clock_hour {}
Whole number of hours since epoch, in clock format.
trick_units(–)
Definition at line 130 of file time_ude.hh.
Referenced by clock_update(), set_epoch_ude(), set_initial_times(), and set_time_by_clock().
clock_minute
int jeod::TimeUDE::clock_minute {}
Whole number of minutes since epoch, in clock format.
trick_units(–)
Definition at line 135 of file time_ude.hh.
Referenced by clock_update(), set_epoch_ude(), set_initial_times(), and set_time_by_clock().
clock_second
double jeod::TimeUDE::clock_second {}
Number of seconds since epoch, in clock format.
trick_units(s)
Definition at line 140 of file time_ude.hh.
Referenced by clock_update(), set_epoch_ude(), set_initial_times(), and set_time_by_clock().
epoch_data_present
bool jeod::TimeUDE::epoch_data_present {} protected
Whether epoch data is present.
trick_units(–)
Definition at line 177 of file time_ude.hh.
Referenced by initialize_from_parent(), initialize_initializer_time(), set_epoch_dyn(), and verify_epoch().
epoch_day
int jeod::TimeUDE::epoch_day {}
Gregorian calendar day number at epoch.
trick_units(day)
Definition at line 105 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_defined_in_name
std::string jeod::TimeUDE::epoch_defined_in_name {""}
Name of time type in which epoch defined.
trick_units(–)
Definition at line 161 of file time_ude.hh.
Referenced by add_type_initialize(), convert_epoch_to_update(), set_epoch_dyn(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_format
TimeEnum::TimeFormat jeod::TimeUDE::epoch_format {TimeEnum::undefined}
Format for expressing the epoch of this type (calendar, julian, etc)
trick_units(–)
Definition at line 150 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_hour
int jeod::TimeUDE::epoch_hour {}
24-hour clock hour number at epoch.
trick_units(hr)
Definition at line 110 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_index
int jeod::TimeUDE::epoch_index {} protected
The index of the time-type in which this one's epoch is defined.
trick_units(–)
Definition at line 202 of file time_ude.hh.
Referenced by add_type_initialize(), convert_epoch_to_update(), initialize_from_parent(), initialize_initializer_time(), and verify_epoch().
epoch_initializing_value
double jeod::TimeUDE::epoch_initializing_value {} protected
Value of epoch in appropriate format.
trick_units(–)
Definition at line 167 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_initializing_value(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_minute
int jeod::TimeUDE::epoch_minute {}
Clock minute number at epoch.
trick_units(min)
Definition at line 115 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_month
int jeod::TimeUDE::epoch_month {}
Gregorian calendar month number at epoch.
trick_units(–)
Definition at line 100 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), and verify_epoch().
epoch_second
double jeod::TimeUDE::epoch_second {}
Clock seconds value at epoch.
trick_units(s)
Definition at line 120 of file time_ude.hh.
Referenced by set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_value_is_set_calendar
bool jeod::TimeUDE::epoch_value_is_set_calendar {} protected
Whether there is some calendar input that could set epoch.
trick_units(–)
Definition at line 187 of file time_ude.hh.
Referenced by set_epoch_std(), and verify_epoch().
epoch_value_is_set_clock
bool jeod::TimeUDE::epoch_value_is_set_clock {} protected
Whether there is some clock input that could set epoch.
trick_units(–)
Definition at line 192 of file time_ude.hh.
Referenced by set_epoch_ude(), and verify_epoch().
epoch_value_is_set_number
bool jeod::TimeUDE::epoch_value_is_set_number {} protected
Whether there is some numerical input that could set epoch.
trick_units(–)
Definition at line 182 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), set_epoch_ude(), and verify_epoch().
epoch_year
int jeod::TimeUDE::epoch_year {}
Gregorian calendar year number at epoch.
trick_units(–)
Definition at line 95 of file time_ude.hh.
Referenced by set_epoch_dyn(), set_epoch_std(), and verify_epoch().
initial_value_format
TimeEnum::TimeFormat jeod::TimeUDE::initial_value_format {TimeEnum::undefined}
Format for expressing the initial value of this type (calendar, julian, etc)
trick_units(–)
Definition at line 156 of file time_ude.hh.
Referenced by initialize_initializer_time(), and set_initial_times().
initializing_data_present
bool jeod::TimeUDE::initializing_data_present {} protected
Whether initializing data is present.
trick_units(–)
Definition at line 172 of file time_ude.hh.
Referenced by initialize_from_parent(), initialize_initializer_time(), set_epoch_dyn(), and set_initial_times().
last_clock_update
double jeod::TimeUDE::last_clock_update {}
Simtime at the last time the clock was updated.
trick_units(s)
Definition at line 145 of file time_ude.hh.
update_index
int jeod::TimeUDE::update_index {} protected
The index of the time-type from which this one is updated.
trick_units(–)
Definition at line 197 of file time_ude.hh.
Referenced by add_type_initialize(), convert_epoch_to_update(), initialize_from_parent(), initialize_initializer_time(), and verify_update().
The documentation for this class was generated from the following files:
time_ude.hh
time_ude.cc