JEOD: jeod::DynBodyFrameSwitch Class Reference
jeod::DynBodyFrameSwitch Class Reference
Switch a DynBody's integration frame to a specified frame when the body switches to that integration frame's sphere of influence.
#include <dyn_body_frame_switch.hh>
Public Types
enum SwitchSense { SwitchOnApproach = 0, SwitchOnDeparture = 1 }
Specifies whether the is_ready() method is to look for the vehicle entering (SwitchOnApproach) the new integration frame's sphere of influence versus leaving (SwitchOnDeparture) the current integration frame's sphere of influence.
Public Member Functions
DynBodyFrameSwitch ()=default
~DynBodyFrameSwitch () override=default
DynBodyFrameSwitch (const DynBodyFrameSwitch &)=delete
DynBodyFrameSwitch & operator= (const DynBodyFrameSwitch &)=delete
void initialize (DynManager &dyn_manager) override
Initialization a DynBodyFrameSwitch instance.
void apply (DynManager &dyn_manager) override
Switch reference frames.
bool is_ready () override
Determine whether it is time to switch frames.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
Data Fields
std::string integ_frame_name {""}
The name of the new integration frame.
SwitchSense switch_sense {SwitchOnApproach}
Indicates whether the switch occurs when the subject DynBody enters a sphere of influence around the new integration frame or leaves a sphere sphere of influence around of the current integration frame.
bool sort_grav_controls {}
If set, the body's gravitational controls are sorted in ascending acceleration magnitude.
double switch_distance {9e99}
The radius of the sphere of influence.
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Attributes
EphemerisRefFrame * integ_frame {}
The reference frame corresponding to the input integ_frame_name.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Friends
class InputProcessor
void init_attrjeod__DynBodyFrameSwitch ()
Additional Inherited Members
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Detailed Description
Switch a DynBody's integration frame to a specified frame when the body switches to that integration frame's sphere of influence.
Definition at line 86 of file dyn_body_frame_switch.hh.
Member Enumeration Documentation
SwitchSense
enum jeod::DynBodyFrameSwitch::SwitchSense
Specifies whether the is_ready() method is to look for the vehicle entering (SwitchOnApproach) the new integration frame's sphere of influence versus leaving (SwitchOnDeparture) the current integration frame's sphere of influence.
Enumerator
SwitchOnApproach
SwitchOnDeparture
Definition at line 97 of file dyn_body_frame_switch.hh.
Constructor & Destructor Documentation
DynBodyFrameSwitch() [1/2]
jeod::DynBodyFrameSwitch::DynBodyFrameSwitch () default
~DynBodyFrameSwitch()
jeod::DynBodyFrameSwitch::~DynBodyFrameSwitch () override default
DynBodyFrameSwitch() [2/2]
jeod::DynBodyFrameSwitch::DynBodyFrameSwitch (const DynBodyFrameSwitch &) delete
Member Function Documentation
apply()
void jeod::DynBodyFrameSwitch::apply (DynManager & dyn_manager) override virtual
Switch reference frames.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAction.
Definition at line 119 of file dyn_body_frame_switch.cc.
References jeod::BodyAction::action_identifier, jeod::GravityControls::active, jeod::BodyAction::apply(), jeod::NamedItem::c_str(), jeod::DynBody::composite_body, jeod::MessageHandler::debug(), jeod::BodyAction::dyn_subject, jeod::GravityControls::grav_accel, jeod::GravityInteraction::grav_controls, jeod::GravityControls::grav_grad, jeod::DynBody::grav_interaction, jeod::GravityControls::grav_pot, jeod::GravityControls::gravitation(), integ_frame, jeod::GravityInteraction::integ_frame_index, integ_frame_name, jeod::DynBody::name, jeod::RefFrameTrans::position, jeod::GravityInteraction::sort_controls(), sort_grav_controls, jeod::RefFrame::state, jeod::DynBody::switch_integration_frames(), jeod::BodyActionMessages::trace, and jeod::RefFrameState::trans.
initialize()
void jeod::DynBodyFrameSwitch::initialize (DynManager & dyn_manager) override virtual
Initialization a DynBodyFrameSwitch instance.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::BodyAction.
Definition at line 57 of file dyn_body_frame_switch.cc.
References jeod::BodyAction::action_identifier, jeod::NamedItem::c_str(), jeod::BodyAction::dyn_subject, jeod::MessageHandler::fail(), jeod::EphemeridesManager::find_integ_frame(), jeod::BodyAction::initialize(), integ_frame, integ_frame_name, jeod::BodyActionMessages::invalid_name, jeod::BodyActionMessages::invalid_object, jeod::BodyAction::mass_subject, jeod::MassBody::name, and jeod::RefFrameManager::subscribe_to_frame().
is_ready()
bool jeod::DynBodyFrameSwitch::is_ready () override virtual
Determine whether it is time to switch frames.
A frame-switch action is ready if it is activated and if the vehicle has entered/left the appropriate sphere of influence.
Returns
Can action be applied?
Reimplemented from jeod::BodyAction.
Definition at line 167 of file dyn_body_frame_switch.cc.
References jeod::DynBody::composite_body, jeod::RefFrame::compute_position_from(), jeod::BodyAction::dyn_subject, integ_frame, jeod::BodyAction::is_ready(), jeod::RefFrameTrans::position, jeod::RefFrame::state, switch_distance, switch_sense, SwitchOnApproach, jeod::RefFrameState::trans, and jeod::Vector3::vmagsq().
operator=()
DynBodyFrameSwitch& jeod::DynBodyFrameSwitch::operator= (const DynBodyFrameSwitch &) delete
Friends And Related Function Documentation
init_attrjeod__DynBodyFrameSwitch
void init_attrjeod__DynBodyFrameSwitch () friend
InputProcessor
friend class InputProcessor friend
Definition at line 88 of file dyn_body_frame_switch.hh.
Field Documentation
integ_frame
EphemerisRefFrame* jeod::DynBodyFrameSwitch::integ_frame {} protected
The reference frame corresponding to the input integ_frame_name.
trick_io(**)
Definition at line 143 of file dyn_body_frame_switch.hh.
Referenced by apply(), initialize(), and is_ready().
integ_frame_name
std::string jeod::DynBodyFrameSwitch::integ_frame_name {""}
The name of the new integration frame.
This name must specify a valid valid integration frame. Failure to do so constitutes a fatal error.trick_units(–)
Definition at line 119 of file dyn_body_frame_switch.hh.
Referenced by apply(), and initialize().
sort_grav_controls
bool jeod::DynBodyFrameSwitch::sort_grav_controls {}
If set, the body's gravitational controls are sorted in ascending acceleration magnitude.
trick_units(–)
Definition at line 132 of file dyn_body_frame_switch.hh.
Referenced by apply().
switch_distance
double jeod::DynBodyFrameSwitch::switch_distance {9e99}
The radius of the sphere of influence.
trick_units(m)
Definition at line 137 of file dyn_body_frame_switch.hh.
Referenced by is_ready().
switch_sense
SwitchSense jeod::DynBodyFrameSwitch::switch_sense {SwitchOnApproach}
Indicates whether the switch occurs when the subject DynBody enters a sphere of influence around the new integration frame or leaves a sphere sphere of influence around of the current integration frame.
trick_units(–)
Definition at line 126 of file dyn_body_frame_switch.hh.
Referenced by is_ready().
The documentation for this class was generated from the following files:
dyn_body_frame_switch.hh
dyn_body_frame_switch.cc