JEOD: jeod::RNPJ2000 Class Reference
jeod::RNPJ2000 Class Reference
Implements the J2000 RNP model using the generic RNP framework.
#include <rnp_j2000.hh>
Public Member Functions
RNPJ2000 ()
default constructor.
~RNPJ2000 () override=default
RNPJ2000 & operator= (const RNPJ2000 &)=delete
RNPJ2000 (const RNPJ2000 &)=delete
void initialize (DynManager &manager) override
Apply the various options, including fidelity of RNP and if polar motion is enabled or not, then call the base class initializer.
void update_rnp (const TimeTT &time_tt, TimeGMST &time_gmst, const TimeUT1 &time_ut1)
Updates the complete RNP and supplies it to the Dynamics Manager.
void update_axial_rotation (TimeGMST &time_gmst)
Updates the axial rotation portion of RNP and supplies the entire RNP to the Dynamics Manager.
double timestamp () const override
Indicates when class was last updated.
std::string get_name () const override
A re-declaration of the pure virtual function in order to convince trick that yes, this is a pure virtual class.
void ephem_update () override
Update the model.
Public Member Functions inherited from jeod::PlanetRNP
PlanetRNP ()=default
~PlanetRNP () override=default
PlanetRNP & operator= (const PlanetRNP &rhs)=delete
PlanetRNP (const PlanetRNP &rhs)=delete
void update_rnp ()
Invokes the calculation for all rotation models contained in the RNP, used on the last time set in each model through PlanetRotation::set_time.
void update_axial_rotation ()
Same as update_rnp, but only the axial_rotation will be updated.
void propagate_rnp ()
Multiples out the (up to) four planet rotation models (nutation, precession, polar motion and rotation), leaving out models whose pointers are NULL, and feeds it to the planet attitude found in the dyn manager given in initialize.
Public Member Functions inherited from jeod::PlanetOrientation
PlanetOrientation ()=default
~PlanetOrientation () override=default
PlanetOrientation & operator= (const PlanetOrientation &rhs)=delete
PlanetOrientation (const PlanetOrientation &rhs)=delete
void activate () override
Activates the PlanetOrientation model.
void deactivate () override
Deactivates the PlanetOrientation model.
void ephem_initialize (EphemeridesManager &manager) override
Implements the EphemInterface pure virtual function ephem_initialize.
void ephem_activate (EphemeridesManager &manager) override
Mark the model as being activate or inactive.
void ephem_build_tree (EphemeridesManager &manager) override
Function, for a particular ephemeris model, nominally builds the particular models portions of the reference frame tree.
void set_name (std::string name_in)
Setter for the name.
Public Member Functions inherited from jeod::EphemerisInterface
~EphemerisInterface () override=default
Public Member Functions inherited from jeod::ActivateInterface
ActivateInterface ()=default
virtual ~ActivateInterface ()=default
Public Member Functions inherited from jeod::RefFrameOwner
RefFrameOwner ()=default
RefFrameOwner default constructor.
virtual ~RefFrameOwner ()=default
RefFrameOwner destructor.
virtual void note_frame_status_change (RefFrame *frame)
Note that a reference frame has changed its active/inactive status.
Data Fields
RotationJ2000 RJ2000
Earth J2000 rotation model.
NutationJ2000 NJ2000
Earth J2000 nutation model.
PrecessionJ2000 PJ2000
Earth J2000 precession model.
PolarMotionJ2000 PMJ2000
Earth J2000 polar motion model.
std::string internal_name {"RNPJ2000"}
The hard coded internal name to be returned on calling the overridden EphemerisInterface function "get_name".
Data Fields inherited from jeod::PlanetRNP
PlanetRotation * nutation {}
Pointer to the nutation model.
PlanetRotation * precession {}
Pointer to the precession model.
PlanetRotation * polar_motion {}
Pointer to the polar_motion model.
PlanetRotation * rotation {}
Pointer to the rotation model.
RNPFidelity rnp_type {FullRNP}
The fidelity of the RNP model.
bool enable_polar {true}
Gives the option of turning on or off polar motion.
double NP_matrix [3][3] { {1.0, 0.0, 0.0}, {0.0, 1.0, 0.0}, { 0.0, 0.0, 1.0 } }
Rotation Matrix representing: transpose(nutation->rotation) * transpose(precession->rotation)
Data Fields inherited from jeod::PlanetOrientation
bool active {true}
Is the orientation model actively updating? Defaults to true.
Planet * planet {}
The planet the attitude model will be working on.
std::string name {""}
Name of the planet the attitude model will be working on.
RefFrameRot * planet_rot_state {}
The current rotational state of the planet.
double planet_omega {}
Nominal axial velocity of the earth.
EphemerisOrientation orient_interface
The ephemeris interface to the in question orientation.
Private Member Functions
void get_dyn_time_ptr (TimeGMST &gmst)
Private Attributes
TimeGMST * gmst_ptr {}
Pointer to the TimeGMST used to update this object when ephem_update is invoked.
TimeDyn * time_dyn_ptr {}
Pointer to the TimeDyn object, used to time stamp the reference frame when it is being updated.
double last_updated_time_full {}
The last update time, when updated through update_rnp, for the RNP, referencing TimeDyn.seconds .
bool never_updated_full {true}
Indicates that last_updated_time_full has never been populated, and that the update must be done regardless of given time.
double last_updated_time_rotational {}
The last update time, when updated through update_axial_rotation, referencing TimeDyn.seconds .
bool never_updated_rotational {true}
Indicates that last_updated_time_rotational has never been populated, and that the update must be done regardless of given time.
Friends
class InputProcessor
void init_attrjeod__RNPJ2000 ()
Additional Inherited Members
Public Types inherited from jeod::PlanetRNP
enum RNPFidelity { FullRNP = 0, RotationOnly = 1, ConstantNP = 2 }
Specifies the initialization fidelity of the RNP model.
Protected Attributes inherited from jeod::PlanetRNP
double scratch_matrix [3][3] {}
A transformation matrix used for intermediate math steps.
Detailed Description
Implements the J2000 RNP model using the generic RNP framework.
Definition at line 100 of file rnp_j2000.hh.
Constructor & Destructor Documentation
RNPJ2000() [1/2]
jeod::RNPJ2000::RNPJ2000 ()
default constructor.
Initialize all data
Definition at line 73 of file rnp_j2000.cc.
References NJ2000, jeod::PlanetRNP::nutation, PJ2000, PMJ2000, jeod::PlanetRNP::polar_motion, jeod::PlanetRNP::precession, RJ2000, and jeod::PlanetRNP::rotation.
~RNPJ2000()
jeod::RNPJ2000::~RNPJ2000 () override default
RNPJ2000() [2/2]
jeod::RNPJ2000::RNPJ2000 (const RNPJ2000 &) delete
Member Function Documentation
ephem_update()
void jeod::RNPJ2000::ephem_update () override virtual
Update the model.
Implements jeod::EphemerisInterface.
Definition at line 302 of file rnp_j2000.cc.
References jeod::PlanetOrientation::active, gmst_ptr, jeod::MessageHandler::inform(), jeod::EphemerisItem::is_active(), jeod::PlanetOrientation::orient_interface, jeod::RNPMessages::setup_error, and jeod::PlanetRNP::update_axial_rotation().
get_dyn_time_ptr()
void jeod::RNPJ2000::get_dyn_time_ptr (TimeGMST & gmst) private
Definition at line 326 of file rnp_j2000.cc.
References jeod::MessageHandler::fail(), jeod::TimeManager::get_time_ptr(), jeod::RNPMessages::setup_error, time_dyn_ptr, and jeod::JeodBaseTime::time_manager.
Referenced by update_axial_rotation(), and update_rnp().
get_name()
std::string jeod::RNPJ2000::get_name () const override virtual
A re-declaration of the pure virtual function in order to convince trick that yes, this is a pure virtual class.
Returns
Planet name.
Implements jeod::PlanetRNP.
Definition at line 289 of file rnp_j2000.cc.
References internal_name.
initialize()
void jeod::RNPJ2000::initialize (DynManager & dyn_manager) override virtual
Apply the various options, including fidelity of RNP and if polar motion is enabled or not, then call the base class initializer.
Note that this function will still run even if the active flag is set to false. Additionally, note that this function does not update the rotation matrix between inertial and planet fixed. It only sets up the object to work with the DynManager. update_rnp must be called to update the RNP matrix. This function will also cache of TimeGMST from the given TimeManager
Parameters
[in,out] dyn_manager DynManager where the planet attitude to be updated is contained
Reimplemented from jeod::PlanetOrientation.
Definition at line 95 of file rnp_j2000.cc.
References jeod::PlanetRNP::ConstantNP, jeod::PlanetRNP::FullRNP, jeod::PlanetOrientation::initialize(), NJ2000, jeod::RotationJ2000::nutation, jeod::PlanetOrientation::planet_omega, jeod::RotationJ2000::planet_rotational_velocity, RJ2000, jeod::PlanetRNP::rnp_type, jeod::PlanetRNP::RotationOnly, and jeod::RotationJ2000::use_full_rnp.
operator=()
RNPJ2000& jeod::RNPJ2000::operator= (const RNPJ2000 &) delete
timestamp()
double jeod::RNPJ2000::timestamp () const override virtual
Indicates when class was last updated.
Returns
Time of last update
Units: s
Implements jeod::EphemerisInterface.
Definition at line 284 of file rnp_j2000.cc.
References last_updated_time_rotational.
update_axial_rotation()
void jeod::RNPJ2000::update_axial_rotation (TimeGMST & time_gmst)
Updates the axial rotation portion of RNP and supplies the entire RNP to the Dynamics Manager.
Parameters
[in] time_gmst current time in the GMST time standard
Units: The
Definition at line 231 of file rnp_j2000.cc.
References jeod::PlanetOrientation::active, jeod::Numerical::compare_exact(), jeod::TimeManager::dyn_time, jeod::PlanetRNP::FullRNP, get_dyn_time_ptr(), last_updated_time_rotational, never_updated_rotational, jeod::BasePlanet::pfix, jeod::PlanetOrientation::planet, jeod::PlanetRNP::rnp_type, jeod::PlanetRNP::rotation, jeod::JeodBaseTime::seconds, jeod::RefFrame::set_timestamp(), time_dyn_ptr, jeod::JeodBaseTime::time_manager, jeod::PlanetRNP::update_axial_rotation(), and jeod::PlanetRotation::update_time().
update_rnp()
void jeod::RNPJ2000::update_rnp (const TimeTT & time_tt, TimeGMST & time_gmst, const TimeUT1 & time_ut1)
Updates the complete RNP and supplies it to the Dynamics Manager.
Parameters
[in] time_tt The current time in the TT time standard
[in] time_gmst current time in the GMST time standard
Units: The
[in] time_ut1 current time in the UT1 time standard
Units: The
Definition at line 133 of file rnp_j2000.cc.
References jeod::PlanetOrientation::active, jeod::Numerical::compare_exact(), jeod::TimeManager::dyn_time, jeod::PlanetRNP::enable_polar, jeod::PlanetRNP::FullRNP, get_dyn_time_ptr(), gmst_ptr, last_updated_time_full, last_updated_time_rotational, never_updated_full, never_updated_rotational, jeod::PlanetRNP::nutation, jeod::BasePlanet::pfix, jeod::PlanetOrientation::planet, jeod::PlanetRNP::polar_motion, jeod::PlanetRNP::precession, jeod::PlanetRNP::rnp_type, jeod::PlanetRNP::rotation, jeod::JeodBaseTime::seconds, jeod::RefFrame::set_timestamp(), time_dyn_ptr, jeod::JeodBaseTime::time_manager, jeod::TimeStandard::trunc_julian_time, jeod::PlanetRNP::update_rnp(), and jeod::PlanetRotation::update_time().
Friends And Related Function Documentation
init_attrjeod__RNPJ2000
void init_attrjeod__RNPJ2000 () friend
InputProcessor
friend class InputProcessor friend
Definition at line 102 of file rnp_j2000.hh.
Field Documentation
gmst_ptr
TimeGMST* jeod::RNPJ2000::gmst_ptr {} private
Pointer to the TimeGMST used to update this object when ephem_update is invoked.
trick_units(–)
Definition at line 172 of file rnp_j2000.hh.
Referenced by ephem_update(), and update_rnp().
internal_name
std::string jeod::RNPJ2000::internal_name {"RNPJ2000"}
The hard coded internal name to be returned on calling the overridden EphemerisInterface function "get_name".
trick_units(–)
Definition at line 160 of file rnp_j2000.hh.
Referenced by get_name().
last_updated_time_full
double jeod::RNPJ2000::last_updated_time_full {} private
The last update time, when updated through update_rnp, for the RNP, referencing TimeDyn.seconds .
If the time from time_dyn_ptr is the same as this update time, then the RNP will not be updated. This is to prevent unnecessary updating.trick_units(s)
Definition at line 187 of file rnp_j2000.hh.
Referenced by update_rnp().
last_updated_time_rotational
double jeod::RNPJ2000::last_updated_time_rotational {} private
The last update time, when updated through update_axial_rotation, referencing TimeDyn.seconds .
If the time from time_dyn_ptr is the same as this update time, then the R component of RNP will not be updated. This is to prevent unnecessary updating.trick_units(s)
Definition at line 202 of file rnp_j2000.hh.
Referenced by timestamp(), update_axial_rotation(), and update_rnp().
never_updated_full
bool jeod::RNPJ2000::never_updated_full {true} private
Indicates that last_updated_time_full has never been populated, and that the update must be done regardless of given time.
trick_units(–)
Definition at line 193 of file rnp_j2000.hh.
Referenced by update_rnp().
never_updated_rotational
bool jeod::RNPJ2000::never_updated_rotational {true} private
Indicates that last_updated_time_rotational has never been populated, and that the update must be done regardless of given time.
trick_units(–)
Definition at line 208 of file rnp_j2000.hh.
Referenced by update_axial_rotation(), and update_rnp().
NJ2000
NutationJ2000 jeod::RNPJ2000::NJ2000
Earth J2000 nutation model.
trick_units(–)
Definition at line 112 of file rnp_j2000.hh.
Referenced by initialize(), and RNPJ2000().
PJ2000
PrecessionJ2000 jeod::RNPJ2000::PJ2000
Earth J2000 precession model.
trick_units(–)
Definition at line 117 of file rnp_j2000.hh.
Referenced by RNPJ2000().
PMJ2000
PolarMotionJ2000 jeod::RNPJ2000::PMJ2000
Earth J2000 polar motion model.
trick_units(–)
Definition at line 122 of file rnp_j2000.hh.
Referenced by RNPJ2000().
RJ2000
RotationJ2000 jeod::RNPJ2000::RJ2000
Earth J2000 rotation model.
trick_units(–)
Definition at line 107 of file rnp_j2000.hh.
Referenced by initialize(), and RNPJ2000().
time_dyn_ptr
TimeDyn* jeod::RNPJ2000::time_dyn_ptr {} private
Pointer to the TimeDyn object, used to time stamp the reference frame when it is being updated.
trick_units(–)
Definition at line 178 of file rnp_j2000.hh.
Referenced by get_dyn_time_ptr(), update_axial_rotation(), and update_rnp().
The documentation for this class was generated from the following files:
rnp_j2000.hh
rnp_j2000.cc