JEOD: jeod::BodyAttach Class Reference
jeod::BodyAttach Class Reference
Provides the basic ability to attach one MassBody to another.
#include <body_attach.hh>
Public Member Functions
void set_parent_body (MassBody &mass_body_in)
Set the parent mass body of this action.
void set_parent_body (DynBody &dyn_body_in)
Set the parent dyn body of this action.
void set_parent_frame (RefFrame &ref_parent_in)
Set the parent ref frame of this action.
BodyAttach ()=default
~BodyAttach () override=default
BodyAttach (const BodyAttach &)=delete
BodyAttach & operator= (const BodyAttach &)=delete
void initialize (DynManager &dyn_manager) override
Initialize a MassBodyAttach.
void apply (DynManager &dyn_manager) override
A derived class presumably has performed the attachment, which may not have worked, and forwarded the apply call to this method.
Public Member Functions inherited from jeod::BodyAction
void set_subject_body (MassBody &mass_body_in)
Set the subject mass body of this action.
void set_subject_body (DynBody &dyn_body_in)
Set the subject dyn body of this action.
bool is_same_subject_body (MassBody &mass_body_in)
Test the input mass body against the subject body and return true if they are the same body.
bool is_subject_dyn_body ()
Check if the subject is a DynBody.
DynBody * get_subject_dyn_body ()
BodyAction ()=default
virtual ~BodyAction ()=default
BodyAction (const BodyAction &)=delete
BodyAction & operator= (const BodyAction &)=delete
virtual void shutdown ()
Release resources allocated by a BodyAction object.
const std::string & get_identifier () const
Accessor for action_identifier.
virtual bool is_ready ()
In general, determine if the initializer is ready to be applied.
Data Fields
bool succeeded {}
Did the attachment succeed?
Data Fields inherited from jeod::BodyAction
bool active {true}
Controls when the action is performed.
bool terminate_on_error {true}
Indicates whether errors encountered while performing the action are to terminate the simulation.
std::string action_name {""}
An identifier for this action.
Protected Attributes
MassBody * mass_parent {}
The MassBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
DynBody * dyn_parent {}
The DynBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
RefFrame * ref_parent {}
The RefFrame corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent RefFrame otherwise.
Protected Attributes inherited from jeod::BodyAction
MassBody * mass_subject {}
The MassBody of the body that is the subject of this action.
DynBody * dyn_subject {}
The DynBody of the body that is the subject of this action.
std::string action_identifier {""}
An identifier for this action, constructed from the class name and the action name at initialization time.
Friends
class InputProcessor
void init_attrjeod__BodyAttach ()
Additional Inherited Members
Protected Member Functions inherited from jeod::BodyAction
virtual bool validate_body_inputs (DynBody *&dyn_body_in, MassBody *&mass_body_in, const std::string &body_base_name, bool allow_failure=false)
void validate_name (const std::string &variable_value, const std::string &variable_name, const std::string &variable_type)
Ensure that a string is not trivially invalid.
Detailed Description
Provides the basic ability to attach one MassBody to another.
This can be either an initialization or asynchronous BodyAction. The action will be performed when the sim user or some simulation job enables the active flag.
MassBodyAttach actions that are ready at simulation initialization time are run as a part of the initialization process, sandwiched between initializing mass properties and initializing state. Attach actions that are not ready at initialization time remain in the pending actions queue until the active flag is set.
Definition at line 94 of file body_attach.hh.
Constructor & Destructor Documentation
BodyAttach() [1/2]
jeod::BodyAttach::BodyAttach () default
~BodyAttach()
jeod::BodyAttach::~BodyAttach () override default
BodyAttach() [2/2]
jeod::BodyAttach::BodyAttach (const BodyAttach &) delete
Member Function Documentation
apply()
void jeod::BodyAttach::apply (DynManager & dyn_manager) override virtual
A derived class presumably has performed the attachment, which may not have worked, and forwarded the apply call to this method.
This method acts on the status from that child class attachment.
Parameters
[in,out] dyn_manager Jeod manager
Reimplemented from jeod::BodyAction.
Reimplemented in jeod::BodyAttachAligned, and jeod::BodyAttachMatrix.
Definition at line 101 of file body_attach.cc.
References jeod::BodyAction::action_identifier, jeod::BodyAction::apply(), jeod::MessageHandler::debug(), dyn_parent, jeod::BodyAction::dyn_subject, jeod::MessageHandler::error(), jeod::MessageHandler::fail(), jeod::BodyActionMessages::fatal_error, jeod::RefFrame::get_name(), jeod::NamedItem::get_name(), mass_parent, jeod::BodyAction::mass_subject, jeod::MassBody::name, jeod::DynBody::name, jeod::BodyActionMessages::not_performed, ref_parent, succeeded, jeod::BodyAction::terminate_on_error, and jeod::BodyActionMessages::trace.
Referenced by jeod::BodyAttachMatrix::apply(), and jeod::BodyAttachAligned::apply().
initialize()
void jeod::BodyAttach::initialize (DynManager & dyn_manager) override virtual
Initialize a MassBodyAttach.
Parameters
[in,out] dyn_manager Dynamics manager
Reimplemented from jeod::BodyAction.
Reimplemented in jeod::BodyAttachAligned.
Definition at line 52 of file body_attach.cc.
References jeod::BodyAction::action_identifier, dyn_parent, jeod::MessageHandler::fail(), jeod::BodyAction::initialize(), mass_parent, jeod::BodyActionMessages::null_pointer, ref_parent, and jeod::BodyAction::validate_body_inputs().
Referenced by jeod::BodyAttachAligned::initialize().
operator=()
BodyAttach& jeod::BodyAttach::operator= (const BodyAttach &) delete
set_parent_body() [1/2]
void jeod::BodyAttach::set_parent_body (MassBody & mass_body_in)
Set the parent mass body of this action.
Resets dyn_parent, frame_parent to null
Definition at line 74 of file body_attach.cc.
References dyn_parent, mass_parent, and ref_parent.
set_parent_body() [2/2]
void jeod::BodyAttach::set_parent_body (DynBody & dyn_body_in)
Set the parent dyn body of this action.
Resets mass_parent, frame_parent to null
Definition at line 81 of file body_attach.cc.
References dyn_parent, mass_parent, and ref_parent.
set_parent_frame()
void jeod::BodyAttach::set_parent_frame (RefFrame & ref_parent_in)
Set the parent ref frame of this action.
Resets mass_parent, dyn_parent to null
Definition at line 88 of file body_attach.cc.
References dyn_parent, mass_parent, and ref_parent.
Friends And Related Function Documentation
init_attrjeod__BodyAttach
void init_attrjeod__BodyAttach () friend
InputProcessor
friend class InputProcessor friend
Definition at line 96 of file body_attach.hh.
Field Documentation
dyn_parent
DynBody* jeod::BodyAttach::dyn_parent {} protected
The DynBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
This pointer is one of ithe 3 possible pointers that must be supplied.trick_units(–)
Definition at line 134 of file body_attach.hh.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), apply(), initialize(), set_parent_body(), and set_parent_frame().
mass_parent
MassBody* jeod::BodyAttach::mass_parent {} protected
The MassBody corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent body otherwise.
This pointer is one of ithe 3 possible pointers that must be supplied.trick_units(–)
Definition at line 126 of file body_attach.hh.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), apply(), initialize(), set_parent_body(), and set_parent_frame().
ref_parent
RefFrame* jeod::BodyAttach::ref_parent {} protected
The RefFrame corresponding to which the subject body is to be attached, directly if the subject body is a root body, and indirectly by attaching the subject body's root body to the parent RefFrame otherwise.
This pointer is one of ithe 3 possible pointers that must be supplied.trick_units(–)
Definition at line 142 of file body_attach.hh.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), apply(), initialize(), set_parent_body(), and set_parent_frame().
succeeded
bool jeod::BodyAttach::succeeded {}
Did the attachment succeed?
trick_units(–)
Definition at line 117 of file body_attach.hh.
Referenced by jeod::BodyAttachMatrix::apply(), jeod::BodyAttachAligned::apply(), and apply().
The documentation for this class was generated from the following files:
body_attach.hh
body_attach.cc