JEOD: jeod::GeneralizedSecondOrderODETechnique Class Reference
jeod::GeneralizedSecondOrderODETechnique Class Reference
Enumerates the integration schemes, generalized Cartesian or Lie group integration, and provides simple utilities that work with this.
#include <generalized_second_order_ode_technique.hh>
Public Types
enum TechniqueType { Unspecified, Cartesian, LieGroup }
Enumerates the types of second order ODE solvers that can be used to integrate a generalized second order ODE.
Public Member Functions
GeneralizedSecondOrderODETechnique ()=delete
GeneralizedSecondOrderODETechnique (const GeneralizedSecondOrderODETechnique &)=delete
GeneralizedSecondOrderODETechnique & operator= (const GeneralizedSecondOrderODETechnique &)=delete
Static Public Member Functions
static bool is_provided_by (const er7_utils::IntegratorConstructor &generator, TechniqueType technique)
Test whether an integration method provides an integrator for the specified technique.
static TechniqueType validate_technique (const er7_utils::IntegratorConstructor &generator, TechniqueType technique, const char *file, unsigned int line, const char *requester, const char *name)
Validate the specified technique with respect to the integration method.
Private Member Functions
~GeneralizedSecondOrderODETechnique ()
Detailed Description
Enumerates the integration schemes, generalized Cartesian or Lie group integration, and provides simple utilities that work with this.
Definition at line 85 of file generalized_second_order_ode_technique.hh.
Member Enumeration Documentation
TechniqueType
enum jeod::GeneralizedSecondOrderODETechnique::TechniqueType
Enumerates the types of second order ODE solvers that can be used to integrate a generalized second order ODE.
Enumerator
Unspecified
No technique specified (an error).
Cartesian
Integrate using a generalized derivative scheme.
The integrator treats generalized position as if it lives in some Cartesian space.
LieGroup
Integrate using a generalized step scheme.
The integrator treats generalized position as if it lives in some Lie group.
Definition at line 98 of file generalized_second_order_ode_technique.hh.
Constructor & Destructor Documentation
GeneralizedSecondOrderODETechnique() [1/2]
jeod::GeneralizedSecondOrderODETechnique::GeneralizedSecondOrderODETechnique () delete
GeneralizedSecondOrderODETechnique() [2/2]
jeod::GeneralizedSecondOrderODETechnique::GeneralizedSecondOrderODETechnique (const GeneralizedSecondOrderODETechnique &) delete
~GeneralizedSecondOrderODETechnique()
jeod::GeneralizedSecondOrderODETechnique::~GeneralizedSecondOrderODETechnique () private
Member Function Documentation
is_provided_by()
bool jeod::GeneralizedSecondOrderODETechnique::is_provided_by (const er7_utils::IntegratorConstructor & generator, TechniqueType technique) static
Test whether an integration method provides an integrator for the specified technique.
Parameters
[in] generator Integrator constructor for the integration technique.
[in] technique Technique to be queried.
Returns
True if the constructor can create an integrator for the specified technique, false otherwise.
Definition at line 44 of file generalized_second_order_ode_technique.cc.
References Cartesian, jeod::MessageHandler::error(), jeod::IntegrationMessages::invalid_request, LieGroup, and Unspecified.
Referenced by validate_technique().
operator=()
GeneralizedSecondOrderODETechnique& jeod::GeneralizedSecondOrderODETechnique::operator= (const GeneralizedSecondOrderODETechnique &) delete
validate_technique()
GeneralizedSecondOrderODETechnique::TechniqueType jeod::GeneralizedSecondOrderODETechnique::validate_technique (const er7_utils::IntegratorConstructor & generator, TechniqueType technique, const char * file, unsigned int line, const char * requester, const char * name) static
Validate the specified technique with respect to the integration method.
Possible outcomes are:
Failure if the generator doesn't provide either of the generalized second order ODE integrators.
Switch to plan B if the generator doesn't provide the requested integrator but does provide the alternate technique.
Nothing happens if the generator does provide the requested integrator.
Parameters
[in] generator Integrator constructor for the integration technique.
[in] technique Technique to be queried.
[in] file Typically FILE
[in] line Typically LINE
[in] requester Something to identify the caller.
[in] name The name of the object associated with the caller.
Returns
Input technique if supported, alternate if not. The function does not return is neither of the options is supported.
Definition at line 68 of file generalized_second_order_ode_technique.cc.
References Cartesian, jeod::MessageHandler::fail(), jeod::MessageHandler::inform(), jeod::IntegrationMessages::invalid_request, is_provided_by(), LieGroup, and jeod::IntegrationMessages::unsupported_option.
Referenced by jeod::DynBody::create_body_integrators().
The documentation for this class was generated from the following files:
generalized_second_order_ode_technique.hh
generalized_second_order_ode_technique.cc