JEOD: jeod::Vector3 Class Reference
jeod::Vector3 Class Reference
Provides static methods for operations that involve 3-vectors.
#include <vector3.hh>
Static Public Member Functions
static double * initialize (double vec[3])
Zero-fill vector, vec[i] = 0.0.
static double * unit (unsigned int index, double vec[3])
Construct unit vector, vec[i] = delta_ij (delta_ij is the Kronecker delta)
static double * fill (double scalar, double vec[3])
Construct a vector from scalar, vec[i] = scalar.
static double * zero_small (double limit, double vec[3])
Zero-out small components of a vector, vec[i] = 0 if abs(vec[i]) < limit.
static double * copy (double const vec[3], double copy[3])
Copy vector contents, copy[i] = vec[i].
static double dot (double const vec2[3], double const vec1[3])
Compute vector inner product, result = sum_i vec1[i] * vec2[i].
static double vmagsq (double const vec[3])
Compute square of vector magnitude, result = dot(vec,vec), but protects against underflow.
static double vmag (double const vec[3])
Compute vector magnitude, result = sqrt(vmagsq(vec))
static double * normalize (double vec[3])
Make vector a unit vector in-place, vec = vec * 1/vmag(vec)
static double * normalize (double const vec[3], double unit_vec[3])
Construct unit vector, unit_vec = vec * 1/vmag(vec)
static double * scale (double scalar, double vec[3])
Scale a vector in-place, vec[i] = scalar.
static double * scale (double const vec[3], double scalar, double prod[3])
Scale a vector, prod[i] = vec[i] * scalar.
static double * negate (double vec[3])
Negate vector in-place, vec[i] = -vec[i].
static double * negate (double const vec[3], double copy[3])
Negate vector, copy[i] = -vec[i].
static double * transform (double const tmat[3][3], double const vec[3], double prod[3])
Transform a column vector, prod[i] = tmat[i][j]*vec[j].
static double * transform (double const tmat[3][3], double vec[3])
Transform a column vector in-place, vec[i] <- tmat[i][j]*vec[j].
static double * transform_transpose (double const tmat[3][3], double const vec[3], double prod[3])
Transform a column vector with the transpose, prod[i] = tmat[j][i]*vec[j].
static double * transform_transpose (double const tmat[3][3], double vec[3])
Transform a column vector in-place with the transpose, vec[i] <- tmat[j][i]*vec[j].
static double * incr (double const addend[3], double vec[3])
Increment a vector, vec[i] += addend[i].
static double * incr (double const addend1[3], double const addend2[3], double vec[3])
Increment a vector, vec[i] += addend1[i] + addend2[i].
static double * decr (double const subtrahend[3], double vec[3])
Decrement a vector, vec[i] -= subtrahend[i].
static double * decr (double const subtrahend1[3], double const subtrahend2[3], double vec[3])
Decrement a vector, vec[i] -= subtrahend1[i] + subtrahend2[i].
static double * sum (double const addend1[3], double const addend2[3], double vec[3])
Compute the sum of two vectors, vec[i] = addend1[i] + addend2[i].
static double * sum (double const addend1[3], double const addend2[3], double const addend3[3], double vec[3])
Compute the sum of three vectors, vec[i] = addend1[i] + addend2[i] + addend3[i].
static double * diff (double const minuend[3], double const subtrahend[3], double vec[3])
Compute the difference between two vectors, diff[i] = minuend[i] - subtrehend[i].
static double * cross (double const vec_left[3], double const vec_right[3], double prod[3])
Compute the cross product between two vectors, prod[i] = epsilon_ijk * vec_left[j] * vec_right[k].
static double * scale_incr (double const vec[3], double scalar, double prod[3])
Increment a vector with a scaled vector, prod[i] += scalar*vec[i].
static double * scale_decr (double const vec[3], double scalar, double prod[3])
Decrement a vector with a scaled vector, prod[i] += scalar*vec[i].
static double * cross_incr (double const vec_left[3], double const vec_right[3], double prod[3])
Increment a vector with the the cross product between two vectors, prod[i] += epsilon_ijk * vec_left[j] * vec_right[k].
static double * cross_decr (double const vec_left[3], double const vec_right[3], double prod[3])
Decrement a vector with the the cross product between two vectors, prod[i] -= epsilon_ijk * vec_left[j] * vec_right[k].
static double * transform_incr (double const tmat[3][3], double const vec[3], double prod[3])
Increment a vector with a transformed column vector, prod[i] += tmat[i][j]*vec[j].
static double * transform_decr (double const tmat[3][3], double const vec[3], double prod[3])
Decrement a vector with a transformed column vector, prod[i] += tmat[i][j]*vec[j].
static double * transform_transpose_incr (double const tmat[3][3], double const vec[3], double prod[3])
Increment a vector with a transpose-transformed column vector, prod[i] += tmat[j][i]*vec[j].
static double * transform_transpose_decr (double const tmat[3][3], double const vec[3], double prod[3])
decrement a vector with a transpose-transformed column vector, prod[i] -= tmat[j][i]*vec[j]
Detailed Description
Provides static methods for operations that involve 3-vectors.
Definition at line 67 of file vector3.hh.
Member Function Documentation
copy()
double * jeod::Vector3::copy (double const vec[3], double copy[3]) inline static
Copy vector contents, copy[i] = vec[i].
Returns
Copied vector
Parameters
[in] vec Source vector
[out] copy Copied vector
Definition at line 158 of file vector3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBodyInitLvlhState::apply(), jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::attach_to_frame(), jeod::GravityControls::calc_spherical(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPoint::compute_state_wrt_pred(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), jeod::RefFrameTrans::copy(), jeod::RefFrameRot::copy(), jeod::MassPointState::copy_state(), jeod::PointContactFacetFactory::create_facet(), jeod::LineContactFacetFactory::create_facet(), jeod::ContactFacet::create_vehicle_point(), jeod::RefFrameState::decr_right(), jeod::ContactUtils::dist_line_segments(), jeod::Orientation::get_eigen_rotation(), jeod::Orientation::get_euler_angles(), jeod::ConstraintComponent::get_rotational_response(), jeod::GravityManager::gravitation(), jeod::PointContactPair::in_contact(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::RefFrameState::incr_right(), jeod::DynBodyGenericFrameAttachment::initialize_attachment(), jeod::Quaternion::left_quat_to_eigen_rotation(), negate(), jeod::MassPointState::negate(), jeod::RefFrameState::negate(), normalize(), jeod::Orientation::Orientation(), jeod::DynBody::process_dynamic_attachment(), jeod::Wrench::set(), jeod::DynBody::set_attitude_rate(), jeod::ConstraintComponent::set_constraint_direction(), jeod::ConstrainedPointMass::set_constraint_position(), jeod::Orientation::set_eigen_rotation(), jeod::Orientation::set_euler_angles(), jeod::Wrench::set_force(), jeod::NorthEastDown::set_ned_trans_states(), jeod::Wrench::set_point(), jeod::DynBody::set_position(), jeod::DynBody::set_state(), jeod::ConstraintFrame::set_struct_to_constraint_frame(), jeod::Wrench::set_torque(), jeod::DynBody::set_velocity(), jeod::StructureIntegratedDynBody::solve_constraints(), transform(), transform_transpose(), jeod::EphemerisPoint::update(), jeod::RadiationPressure::update_facet_surface(), jeod::NorthEastDown::update_from_cart(), jeod::PlanetFixedPosition::update_from_cart(), jeod::NorthEastDown::update_from_ellip(), jeod::NorthEastDown::update_from_spher(), jeod::DynBody::update_integrated_state(), jeod::MassBody::update_mass_properties(), jeod::MassPointState::update_point(), and jeod::Wrench::Wrench().
cross()
double * jeod::Vector3::cross (double const vec_left[3], double const vec_right[3], double prod[3]) inline static
Compute the cross product between two vectors, prod[i] = epsilon_ijk * vec_left[j] * vec_right[k].
Returns
Cross product vector
Parameters
[in] vec_left Left vector
[in] vec_right Right vector
[out] prod Cross product vector
Definition at line 602 of file vector3_inline.hh.
Referenced by jeod::EarthLighting::calc_lighting(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_derived_state_reverse(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::DynBody::compute_state_elements_forward(), jeod::DynBody::compute_state_elements_reverse(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::Quaternion::conjugate_multiply(), jeod::ContactFacet::create_vehicle_point(), jeod::OrbitalElements::from_cartesian(), jeod::TorqueConstraintComponent::get_translational_response(), jeod::ForceConstraintComponent::get_translational_response(), jeod::PointContactPair::in_contact(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::CheckItem::is_unit(), jeod::Quaternion::left_quat_transform(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_conjugate(), jeod::Quaternion::multiply_left(), jeod::Quaternion::multiply_left_conjugate(), jeod::DynBody::process_dynamic_attachment(), jeod::FlatPlateRadiationFacet::radiation_pressure(), jeod::BasePlanet::set_alt_inertial(), jeod::ForceConstraintComponent::setup_constraint(), jeod::PendulumConstraintComponent::setup_constraint(), jeod::SolarBetaDerivedState::update(), and jeod::DynBody::update_integrated_state().
cross_decr()
double * jeod::Vector3::cross_decr (double const vec_left[3], double const vec_right[3], double prod[3]) inline static
Decrement a vector with the the cross product between two vectors, prod[i] -= epsilon_ijk * vec_left[j] * vec_right[k].
Returns
Decremented vector
Parameters
[in] vec_left Left vector
[in] vec_right Right vector
[in,out] prod Decremented vector
Definition at line 690 of file vector3_inline.hh.
Referenced by jeod::Quaternion::conjugate_multiply(), jeod::RefFrameState::decr_left(), jeod::Quaternion::multiply_conjugate(), jeod::Quaternion::multiply_left_conjugate(), and jeod::RefFrameState::negate().
cross_incr()
double * jeod::Vector3::cross_incr (double const vec_left[3], double const vec_right[3], double prod[3]) inline static
Increment a vector with the the cross product between two vectors, prod[i] += epsilon_ijk * vec_left[j] * vec_right[k].
Returns
Cross product vector
Parameters
[in] vec_left Left vector
[in] vec_right Right vector
[in,out] prod Cross product vector
Definition at line 668 of file vector3_inline.hh.
Referenced by jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::DynBody::collect_forces_and_torques(), jeod::Quaternion::compute_left_quat_deriv(), jeod::Quaternion::compute_left_quat_second_deriv(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::RefFrameState::decr_right(), jeod::RefFrameState::incr_left(), jeod::RefFrameState::incr_right(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_left(), jeod::Quaternion::multiply_vector_left(), jeod::Quaternion::multiply_vector_right(), jeod::Wrench::operator+=(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::ConstrainedRigidMass::setup_constraint(), and jeod::Wrench::transform_to_point().
decr() [1/2]
double * jeod::Vector3::decr (double const subtrahend[3], double vec[3]) inline static
Decrement a vector, vec[i] -= subtrahend[i].
Returns
Decremented vector
Parameters
[in] subtrahend Decrement
[in,out] vec Vector
Definition at line 491 of file vector3_inline.hh.
Referenced by jeod::RefFrame::compute_position_from(), jeod::DynBody::compute_ref_point_transform(), jeod::Quaternion::conjugate_multiply(), jeod::MassPointState::decr_left(), jeod::RefFrameState::decr_left(), jeod::MassPointState::decr_right(), jeod::RefFrameState::decr_right(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::Quaternion::multiply_conjugate(), and jeod::Quaternion::multiply_left_conjugate().
decr() [2/2]
double * jeod::Vector3::decr (double const subtrahend1[3], double const subtrahend2[3], double vec[3]) inline static
Decrement a vector, vec[i] -= subtrahend1[i] + subtrahend2[i].
Returns
Decremented vector
Parameters
[in] subtrahend1 Decrement
[in] subtrahend2 Decrement
[in,out] vec Vector
Definition at line 512 of file vector3_inline.hh.
diff()
double * jeod::Vector3::diff (double const minuend[3], double const subtrahend[3], double vec[3]) inline static
Compute the difference between two vectors, diff[i] = minuend[i] - subtrehend[i].
Returns
Difference vector
Parameters
[in] minuend Minuend
[in] subtrahend Subtrahend
[out] vec Difference vector
Definition at line 580 of file vector3_inline.hh.
Referenced by jeod::AerodynamicDrag::aero_drag(), jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::GravityControls::calc_relativistic(), jeod::LineContactFacet::calculate_contact_point(), jeod::RadiationThirdBody::calculate_shadow(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::DynBody::collect_forces_and_torques(), jeod::ConstrainedPointMass::compute_constraint_position_com(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::ContactUtils::dist_line_segments(), jeod::GravityControls::gravitation(), jeod::PointContactPair::in_contact(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::FlatPlateRadiationFacet::incident_radiation(), jeod::FlatPlateRadiationFacet::initialize_geom(), jeod::Wrench::operator+=(), jeod::DynBody::process_dynamic_attachment(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::Wrench::transform_to_point(), jeod::MassBody::update_mass_properties(), and jeod::CheckItem::within_rss_tolerance().
dot()
double jeod::Vector3::dot (double const vec2[3], double const vec1[3]) inline static
Compute vector inner product, result = sum_i vec1[i] * vec2[i].
Returns
Inner product
Parameters
[in] vec2 Vector 2
[in] vec1 Vector 1
Definition at line 178 of file vector3_inline.hh.
Referenced by jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::EarthLighting::calc_lighting(), jeod::GravityControls::calc_relativistic(), jeod::GravityControls::calc_spherical(), jeod::SpringPairInteraction::calculate_forces(), jeod::RadiationThirdBody::calculate_shadow(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::Quaternion::compute_left_quat_deriv(), jeod::Quaternion::compute_left_quat_second_deriv(), jeod::Quaternion::compute_slerp(), jeod::Quaternion::conjugate_multiply(), jeod::ContactUtils::dist_line_segments(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::OrbitalElements::from_cartesian(), jeod::TorqueConstraintComponent::get_cross_coeff(), jeod::ForceConstraintComponent::get_cross_coeff(), jeod::FlatPlateRadiationFacet::incident_radiation(), jeod::CheckItem::is_unit(), jeod::Quaternion::left_quat_transform(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_conjugate(), jeod::Quaternion::multiply_left(), jeod::Quaternion::multiply_left_conjugate(), jeod::Quaternion::multiply_vector_left(), jeod::Quaternion::multiply_vector_right(), jeod::PendulumConstraintComponent::setup_constraint(), jeod::PendulumConstraintComponent::transition_to_horizontal(), and jeod::SolarBetaDerivedState::update().
fill()
double * jeod::Vector3::fill (double scalar, double vec[3]) inline static
Construct a vector from scalar, vec[i] = scalar.
Returns
Filled vector
Parameters
[in] scalar Scalar
[out] vec Filled vector
Definition at line 112 of file vector3_inline.hh.
incr() [1/2]
double * jeod::Vector3::incr (double const addend[3], double vec[3]) inline static
Increment a vector, vec[i] += addend[i].
Returns
Incremented vector
Parameters
[in] addend Increment
[in,out] vec Vector
Definition at line 449 of file vector3_inline.hh.
Referenced by jeod::accumulate_forces(), jeod::accumulate_torques(), jeod::DynBody::add_mass_body(), jeod::AerodynamicDrag::aero_drag(), jeod::DynBody::attach_child(), jeod::MassBody::attach_update_properties(), jeod::GravityControls::calc_relativistic(), jeod::GravityControls::calc_spherical(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), jeod::DynBody::collect_forces_and_torques(), jeod::ConstrainedPointMass::compute_constraint_position_root(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::RefFrame::compute_position_from(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::ForceConstraintComponent::get_translational_response(), jeod::GravityManager::gravitation(), jeod::GravityControls::gravitation(), jeod::FlatPlateRadiationFacet::incident_radiation(), jeod::RadiationDefaultSurface::incident_radiation(), jeod::MassPointState::incr_left(), jeod::RefFrameState::incr_left(), jeod::MassPointState::incr_right(), jeod::RefFrameState::incr_right(), jeod::Quaternion::left_quat_transform(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_left(), jeod::Wrench::operator+=(), jeod::DynBody::process_dynamic_attachment(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::FlatPlateRadiationFacet::radiation_pressure(), jeod::RadiationSurface::radiation_pressure(), jeod::MassBody::reattach(), jeod::DynBodyConstraintsSolver::transform_point_to_root(), jeod::Wrench::transform_to_parent(), jeod::MassBody::update_mass_properties(), and jeod::ConstraintFrame::update_root_to_constraint_frame().
incr() [2/2]
double * jeod::Vector3::incr (double const addend1[3], double const addend2[3], double vec[3]) inline static
Increment a vector, vec[i] += addend1[i] + addend2[i].
Returns
Incremented vector
Parameters
[in] addend1 Increment
[in] addend2 Increment
[in,out] vec Vector
Definition at line 470 of file vector3_inline.hh.
initialize()
double * jeod::Vector3::initialize (double vec[3]) inline static
Zero-fill vector, vec[i] = 0.0.
Returns
Zero-filled vector
Parameters
[out] vec Zero-filled vector
Definition at line 78 of file vector3_inline.hh.
Referenced by jeod::accumulate_forces(), jeod::accumulate_torques(), jeod::PendulumConstraintComponent::activate(), jeod::AerodynamicDrag::aero_drag(), jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::DefaultAero::aerodrag_force(), jeod::AerodynamicDrag::AerodynamicDrag(), jeod::BodyAttachAligned::apply(), jeod::DynBodyInitNedState::apply(), jeod::AtmosphereState::AtmosphereState(), jeod::BodyAttachMatrix::BodyAttachMatrix(), jeod::BodyForceCollect::BodyForceCollect(), jeod::BodyReattach::BodyReattach(), jeod::NorthEastDown::build_ned_orientation(), jeod::MassBody::calc_composite_cm(), jeod::LineContactFacet::calculate_contact_point(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), jeod::DynBody::collect_forces_and_torques(), jeod::ContactSurface::collect_forces_torques(), jeod::StructureIntegratedDynBody::collect_local_forces_and_torques(), jeod::RefFrameRot::compute_ang_vel_unit(), jeod::RefFrame::compute_position_from(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::ConstrainedPointMass::ConstrainedPointMass(), jeod::ConstraintComponent::ConstraintComponent(), jeod::ConstraintFrame::ConstraintFrame(), jeod::ContactFacet::ContactFacet(), jeod::DynBodyConstraintsSolver::DynBodyConstraintsSolver(), jeod::DynBodyInit::DynBodyInit(), jeod::EarthLighting::EarthLighting(), jeod::EphemerisZXZOrientation::EphemerisZXZOrientation(), jeod::Facet::Facet(), jeod::FlatPlate::FlatPlate(), jeod::FlatPlateRadiationFacet::FlatPlateRadiationFacet(), jeod::Force::Force(), jeod::ForceConstraintComponent::ForceConstraintComponent(), jeod::FrameDerivs::FrameDerivs(), jeod::GravityControls::gravitation(), jeod::GravityControls::GravityControls(), jeod::GravityIntegFrame::GravityIntegFrame(), jeod::GravityInteraction::GravityInteraction(), jeod::GravityTorque::GravityTorque(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::RefFrameTrans::initialize(), jeod::LvlhFrame::initialize(), jeod::RefFrameRot::initialize(), jeod::MassPointState::initialize_mass_point(), jeod::RadiationBaseFacet::initialize_runtime_values(), jeod::EphemerisPoint::initialize_state(), jeod::GravitySource::initialize_state(), jeod::InteractionFacet::InteractionFacet(), jeod::Quaternion::left_quat_to_eigen_rotation(), jeod::LightingBody::LightingBody(), jeod::LineContactFacet::LineContactFacet(), jeod::Quaternion::make_identity(), jeod::MassPointInit::MassPointInit(), jeod::MassPointState::MassPointState(), jeod::MassPropertiesInit::MassPropertiesInit(), jeod::RefFrameState::negate(), normalize(), jeod::Orientation::Orientation(), jeod::PendulumConstraintComponent::PendulumConstraintComponent(), jeod::PlanetFixedPosition::PlanetFixedPosition(), jeod::PointContactFacet::PointContactFacet(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::Quaternion::Quaternion(), jeod::RadiationSurface::radiation_pressure(), jeod::RadiationBaseFacet::RadiationBaseFacet(), jeod::RadiationDefaultSurface::RadiationDefaultSurface(), jeod::RadiationFacet::RadiationFacet(), jeod::RadiationPressure::RadiationPressure(), jeod::RadiationSource::RadiationSource(), jeod::RadiationSurface::RadiationSurface(), jeod::RadiationThirdBody::RadiationThirdBody(), jeod::Wrench::reset_force(), jeod::Wrench::reset_force_and_torque(), jeod::PendulumConstraintComponent::reset_integrators(), jeod::Wrench::reset_point(), jeod::Wrench::reset_torque(), jeod::StructureIntegratedDynBody::rot_integ(), jeod::DynBody::rot_integ(), jeod::RadiationPressure::set_calculate_forces(), jeod::Quaternion::set_to_zero(), jeod::SolarBetaDerivedState::SolarBetaDerivedState(), jeod::Torque::Torque(), jeod::RadiationPressure::update_default_surface(), jeod::MassBody::update_mass_properties(), and jeod::Wrench::Wrench().
negate() [1/2]
double * jeod::Vector3::negate (double vec[3]) inline static
Negate vector in-place, vec[i] = -vec[i].
Returns
Negated vector
Parameters
[in,out] vec Vector
Definition at line 306 of file vector3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::SpringPairInteraction::calculate_forces(), jeod::MassPoint::compute_pred_rel_state(), jeod::Quaternion::conjugate(), jeod::GravityControls::gravitation(), jeod::PointContactPair::in_contact(), jeod::Quaternion::left_quat_to_eigen_rotation(), jeod::MassPointState::negate(), and jeod::RefFrameState::negate().
negate() [2/2]
double * jeod::Vector3::negate (double const vec[3], double copy[3]) inline static
Negate vector, copy[i] = -vec[i].
Returns
Negated vector
Parameters
[in] vec Source vector
[out] copy Negated vector
Definition at line 325 of file vector3_inline.hh.
References copy().
normalize() [1/2]
double * jeod::Vector3::normalize (double vec[3]) inline static
Make vector a unit vector in-place, vec = vec * 1/vmag(vec)
Returns
Normalized vector
Parameters
[in,out] vec Vector
Definition at line 223 of file vector3_inline.hh.
References initialize(), scale(), and vmag().
Referenced by jeod::LineContactFacet::calculate_contact_point(), jeod::PointContactFacet::calculate_contact_point(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::ContactFacet::create_vehicle_point(), jeod::PointContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), normalize(), and jeod::BasePlanet::set_alt_inertial().
normalize() [2/2]
double * jeod::Vector3::normalize (double const vec[3], double unit_vec[3]) inline static
Construct unit vector, unit_vec = vec * 1/vmag(vec)
Returns
Unit vector
Parameters
[in] vec Vector
[out] unit_vec Unit vector
Definition at line 247 of file vector3_inline.hh.
References copy(), and normalize().
scale() [1/2]
double * jeod::Vector3::scale (double scalar, double vec[3]) inline static
Scale a vector in-place, vec[i] = scalar.
Returns
Scaled vector
Parameters
[in] scalar Scalar
[in,out] vec Scaled vector
Definition at line 265 of file vector3_inline.hh.
Referenced by jeod::AerodynamicDrag::aero_drag(), jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::DefaultAero::aerodrag_force(), jeod::MassBody::calc_composite_cm(), jeod::GravityControls::calc_relativistic(), jeod::GravityControls::calc_spherical(), jeod::LineContactFacet::calculate_contact_point(), jeod::PointContactFacet::calculate_contact_point(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::DynBody::collect_forces_and_torques(), jeod::RefFrameRot::compute_ang_vel_unit(), jeod::PendulumConstraintComponent::compute_bob_state_cartesian(), jeod::PendulumConstraintComponent::compute_bob_state_spherical(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::Orientation::compute_eigen_rotation_from_matrix(), jeod::Quaternion::compute_left_quat_deriv(), jeod::Quaternion::compute_left_quat_second_deriv(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::Quaternion::conjugate_multiply(), jeod::ContactUtils::dist_line_segments(), jeod::FlatPlateRadiationFacet::incident_radiation(), jeod::RadiationDefaultSurface::incident_radiation(), jeod::Quaternion::left_quat_from_eigen_rotation(), jeod::Quaternion::left_quat_to_eigen_rotation(), jeod::Quaternion::left_quat_to_transformation(), jeod::Quaternion::left_quat_transform(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_conjugate(), jeod::Quaternion::multiply_left(), jeod::Quaternion::multiply_left_conjugate(), jeod::Quaternion::multiply_vector_left(), jeod::Quaternion::multiply_vector_right(), normalize(), jeod::DynBody::process_dynamic_attachment(), jeod::EphemerisZXZOrientation::propagate(), jeod::FlatPlateRadiationFacet::radiation_pressure(), jeod::StructureIntegratedDynBody::rot_integ(), jeod::DynBody::rot_integ(), jeod::Quaternion::scale(), jeod::Wrench::scale_force(), jeod::Wrench::scale_torque(), jeod::ForceConstraintComponent::setup_constraint(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::RadiationPressure::third_body_adjustments(), jeod::EphemerisZXZOrientation::update(), jeod::EphemerisPoint::update_scaled(), and jeod::RadiationThirdBody::update_third_body_state().
scale() [2/2]
double * jeod::Vector3::scale (double const vec[3], double scalar, double prod[3]) inline static
Scale a vector, prod[i] = vec[i] * scalar.
Returns
Scaled vector
Parameters
[in] vec Source vector
[in] scalar Scalar
[out] prod Scaled vector
Definition at line 286 of file vector3_inline.hh.
scale_decr()
double * jeod::Vector3::scale_decr (double const vec[3], double scalar, double prod[3]) inline static
Decrement a vector with a scaled vector, prod[i] += scalar*vec[i].
Returns
Decremented vector
Parameters
[in] vec Source vector
[in] scalar Scalar
[in,out] prod Decremented vector
Definition at line 646 of file vector3_inline.hh.
Referenced by jeod::GravityControls::calc_spherical(), jeod::Quaternion::conjugate_multiply(), jeod::Quaternion::multiply_conjugate(), and jeod::Quaternion::multiply_left_conjugate().
scale_incr()
double * jeod::Vector3::scale_incr (double const vec[3], double scalar, double prod[3]) inline static
Increment a vector with a scaled vector, prod[i] += scalar*vec[i].
Returns
Incremented vector
Parameters
[in] vec Source vector
[in] scalar Scalar
[in,out] prod Incremented vector
Definition at line 624 of file vector3_inline.hh.
Referenced by jeod::MassBody::calc_composite_cm(), jeod::GravityControls::calc_relativistic(), jeod::GravityControls::calc_spherical(), jeod::Quaternion::compute_left_quat_second_deriv(), jeod::Quaternion::conjugate_multiply(), jeod::Quaternion::left_quat_transform(), jeod::Quaternion::multiply(), jeod::Quaternion::multiply_left(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
sum() [1/2]
double * jeod::Vector3::sum (double const addend1[3], double const addend2[3], double vec[3]) inline static
Compute the sum of two vectors, vec[i] = addend1[i] + addend2[i].
Returns
Sum vector
Parameters
[in] addend1 Addend
[in] addend2 Addend
[out] vec Sum vector
Definition at line 534 of file vector3_inline.hh.
Referenced by jeod::FlatPlateAeroFacet::aerodrag_force(), jeod::GravityControls::calc_relativistic(), jeod::LineContactFacet::calculate_contact_point(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::StructureIntegratedDynBody::collect_forces_and_torques(), jeod::DynBody::collect_forces_and_torques(), jeod::ContactSurface::collect_forces_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::MassPoint::compute_state_wrt_pred(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::ContactUtils::dist_line_segments(), jeod::GravityControls::gravitation(), jeod::PointContactPair::in_contact(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::Quaternion::left_quat_to_transformation(), jeod::DynBody::process_dynamic_attachment(), jeod::FlatPlateRadiationFacet::radiation_pressure(), jeod::Facet::update_articulation_internal(), and jeod::RadiationPressure::update_default_surface().
sum() [2/2]
double * jeod::Vector3::sum (double const addend1[3], double const addend2[3], double const addend3[3], double vec[3]) inline static
Compute the sum of three vectors, vec[i] = addend1[i] + addend2[i] + addend3[i].
Returns
Sum vector
Parameters
[in] addend1 Addend
[in] addend2 Addend
[in] addend3 Addend
[out] vec Sum vector
Definition at line 557 of file vector3_inline.hh.
transform() [1/2]
double * jeod::Vector3::transform (double const tmat[3][3], double const vec[3], double prod[3]) inline static
Transform a column vector, prod[i] = tmat[i][j]*vec[j].
Returns
Transformed vector
Parameters
[in] tmat Transformation matrix
[in] vec Source vector
[out] prod Transformed vector
Definition at line 346 of file vector3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::AerodynamicDrag::aero_drag(), jeod::DynBodyInit::apply_user_inputs(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::DynBody::collect_forces_and_torques(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::DynBody::compute_derived_state_forward(), jeod::StructureIntegratedDynBody::compute_inertial_torque(), jeod::ConstrainedPointMass::compute_non_grav_accel(), jeod::RefFrame::compute_position_from(), jeod::MassPoint::compute_pred_rel_state(), jeod::DynBody::compute_ref_point_transform(), jeod::RefFrame::compute_relative_state(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::ConstraintComponent::compute_rotational_response(), jeod::DynBody::compute_state_elements_forward(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), jeod::MassPointState::decr_left(), jeod::RefFrameState::decr_left(), jeod::LvlhRelativeDerivedState::do_theta_dot_correction(), jeod::TorqueConstraintComponent::get_cross_coeff(), jeod::LineContactPair::in_contact(), jeod::PointContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::RefFrameState::incr_right(), jeod::RefFrameState::negate(), jeod::DynBody::process_dynamic_attachment(), jeod::ConstrainedRigidMass::setup_constraint(), jeod::PendulumConstraintComponent::setup_constraint(), jeod::OrbitalElements::to_cartesian(), transform(), jeod::MassBody::update_mass_properties(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
transform() [2/2]
double * jeod::Vector3::transform (double const tmat[3][3], double vec[3]) inline static
Transform a column vector in-place, vec[i] <- tmat[i][j]*vec[j].
Returns
Transformed vector
Parameters
[in] tmat Transformation matrix
[in,out] vec Transformed vector
Definition at line 376 of file vector3_inline.hh.
References copy(), and transform().
transform_decr()
double * jeod::Vector3::transform_decr (double const tmat[3][3], double const vec[3], double prod[3]) inline static
Decrement a vector with a transformed column vector, prod[i] += tmat[i][j]*vec[j].
Returns
Decremented vector
Parameters
[in] tmat Transformation matrix
[in] vec Source vector
[in,out] prod Decremented vector
Definition at line 743 of file vector3_inline.hh.
Referenced by jeod::RefFrameState::decr_left().
transform_incr()
double * jeod::Vector3::transform_incr (double const tmat[3][3], double const vec[3], double prod[3]) inline static
Increment a vector with a transformed column vector, prod[i] += tmat[i][j]*vec[j].
Returns
Incremented vector
Parameters
[in] tmat Transformation matrix
[in] vec Source vector
[in,out] prod Incremented vector
Definition at line 712 of file vector3_inline.hh.
Referenced by jeod::RefFrameState::incr_left(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
transform_transpose() [1/2]
double * jeod::Vector3::transform_transpose (double const tmat[3][3], double const vec[3], double prod[3]) inline static
Transform a column vector with the transpose, prod[i] = tmat[j][i]*vec[j].
Returns
Transformed vector
Parameters
[in] tmat Transformation matrix
[in] vec Source vector
[out] prod Transformed vector
Definition at line 398 of file vector3_inline.hh.
Referenced by jeod::DynBodyInitOrbit::apply(), jeod::MassBody::attach_update_properties(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::LineContactFacet::calculate_torque(), jeod::PointContactFacet::calculate_torque(), jeod::DynBody::collect_forces_and_torques(), jeod::StructureIntegratedDynBody::complete_translational_acceleration(), jeod::ConstrainedPointMass::compute_constraint_position_root(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::DynBody::compute_derived_state_reverse(), jeod::RefFrame::compute_position_from(), jeod::RefFrame::compute_relative_state(), jeod::ConstraintComponent::compute_root_direction(), jeod::DynBodyConstraintsSolver::compute_root_to_this(), jeod::StructureIntegratedDynBody::compute_rotational_acceleration(), jeod::ConstraintComponent::compute_rotational_response(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPoint::compute_state_wrt_pred(), jeod::StructureIntegratedDynBody::compute_translational_acceleration(), jeod::StructureIntegratedDynBody::compute_vehicle_point_derivatives(), jeod::DynBody::compute_vehicle_point_derivatives(), jeod::RefFrameState::decr_right(), jeod::LineContactPair::in_contact(), jeod::PointContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::MassPointState::incr_left(), jeod::RefFrameState::incr_left(), jeod::MassPointState::negate(), jeod::RefFrameState::negate(), jeod::DynBody::process_dynamic_attachment(), jeod::StructureIntegratedDynBody::PropagateForcesAndTorques(), jeod::MassBody::reattach(), jeod::StructureIntegratedDynBody::solve_constraints(), jeod::DynBodyConstraintsSolver::transform_direction_to_root(), jeod::Wrench::transform_to_parent(), transform_transpose(), jeod::GravityTorque::update(), jeod::FlatPlate::update_articulation_internal(), jeod::Facet::update_articulation_internal(), jeod::DynBody::update_integrated_state(), jeod::MassBody::update_mass_properties(), jeod::ConstraintFrame::update_root_to_constraint_frame(), and jeod::DynBodyConstraintsSolver::update_vehicle_response().
transform_transpose() [2/2]
double * jeod::Vector3::transform_transpose (double const tmat[3][3], double vec[3]) inline static
Transform a column vector in-place with the transpose, vec[i] <- tmat[j][i]*vec[j].
Returns
Transformed vector
Parameters
[in] tmat Transformation matrix
[in,out] vec Transformed vector
Definition at line 428 of file vector3_inline.hh.
References copy(), and transform_transpose().
transform_transpose_decr()
double * jeod::Vector3::transform_transpose_decr (double const tmat[3][3], double const vec[3], double prod[3]) inline static
decrement a vector with a transpose-transformed column vector, prod[i] -= tmat[j][i]*vec[j]
Returns
Decremented vector
Parameters
[in] tmat Transformation matrix
[in] vec Source vector
[in,out] prod Decremented vector
Definition at line 805 of file vector3_inline.hh.
Referenced by jeod::DynBody::add_mass_body(), jeod::DynBody::attach_child(), jeod::MassBody::attach_to(), jeod::DynBody::compute_derived_state_reverse(), jeod::MassPoint::compute_pred_rel_state(), jeod::DynBody::compute_state_elements_reverse(), jeod::MassPointState::decr_right(), jeod::RefFrameState::decr_right(), and jeod::DynBody::update_integrated_state().
transform_transpose_incr()
double * jeod::Vector3::transform_transpose_incr (double const tmat[3][3], double const vec[3], double prod[3]) inline static
Increment a vector with a transpose-transformed column vector, prod[i] += tmat[j][i]*vec[j].
Returns
Incremented vector
Parameters
[in] tmat Transformation matrix
[in] vec Source vector
[in,out] prod Incremented vector
Definition at line 774 of file vector3_inline.hh.
Referenced by jeod::DynBody::compute_derived_state_forward(), jeod::DynBody::compute_state_elements_forward(), jeod::MassPointState::incr_right(), and jeod::RefFrameState::incr_right().
unit()
double * jeod::Vector3::unit (unsigned int index, double vec[3]) inline static
Construct unit vector, vec[i] = delta_ij (delta_ij is the Kronecker delta)
Returns
Unit vector
Parameters
[in] index Unit index: 0,1,2=x,y,z hat
[out] vec Unit vector
Definition at line 94 of file vector3_inline.hh.
Referenced by jeod::AerodynamicDrag::aero_drag().
vmag()
double jeod::Vector3::vmag (double const vec[3]) inline static
Compute vector magnitude, result = sqrt(vmagsq(vec))
Returns
Vector magnitude
Parameters
[in] vec Vector
Definition at line 209 of file vector3_inline.hh.
References vmagsq().
Referenced by jeod::AerodynamicDrag::aero_drag(), jeod::EarthLighting::calc_lighting(), jeod::SphericalHarmonicsGravityControls::calc_nonspherical(), jeod::LineContactFacet::calculate_contact_point(), jeod::RadiationSource::calculate_flux(), jeod::SpringPairInteraction::calculate_forces(), jeod::PlanetFixedPosition::cart_to_spher(), jeod::RefFrameRot::compute_ang_vel_products(), jeod::PendulumConstraintComponent::compute_constraint_response(), jeod::Orientation::compute_eigen_rotation_from_matrix(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::LvlhRelativeDerivedState::convert_circ_to_rect(), jeod::LvlhRelativeDerivedState::convert_rect_to_circ(), jeod::ContactUtils::dist_line_segments(), jeod::OrbitalElements::from_cartesian(), jeod::PointContactPair::in_contact(), jeod::LineContactPair::in_contact(), jeod::LinePointContactPair::in_contact(), jeod::ContactPair::in_range(), jeod::Quaternion::left_quat_to_eigen_rotation(), normalize(), jeod::StructureIntegratedDynBody::rot_integ(), jeod::DynBody::rot_integ(), jeod::SphericalHarmonicsSolidBodyTides::update(), jeod::EphemerisZXZOrientation::update(), and jeod::RadiationThirdBody::update_third_body_state().
vmagsq()
double jeod::Vector3::vmagsq (double const vec[3]) inline static
Compute square of vector magnitude, result = dot(vec,vec), but protects against underflow.
Returns
Inner product
Parameters
[in] vec Vector
Definition at line 195 of file vector3_inline.hh.
Referenced by jeod::GravityControls::calc_relativistic(), jeod::GravityControls::calc_spherical(), jeod::RadiationThirdBody::calculate_shadow(), jeod::Quaternion::compute_left_quat_second_deriv(), jeod::LvlhFrame::compute_lvlh_frame(), jeod::DynBodyFrameSwitch::is_ready(), jeod::CheckItem::is_unit(), jeod::Quaternion::norm_sq(), jeod::Quaternion::normalize_integ(), jeod::PendulumConstraintComponent::setup_constraint(), jeod::GravityInteraction::sort_controls(), jeod::SolarBetaDerivedState::update(), vmag(), and jeod::CheckItem::within_rss_tolerance().
zero_small()
double * jeod::Vector3::zero_small (double limit, double vec[3]) inline static
Zero-out small components of a vector, vec[i] = 0 if abs(vec[i]) < limit.
Returns
Truncated vector
Parameters
[in] limit Limit
[in,out] vec Truncated vector
Definition at line 129 of file vector3_inline.hh.
References jeod::Numerical::fabs().
Referenced by jeod::SpringPairInteraction::calculate_forces(), jeod::DynBody::collect_forces_and_torques(), jeod::ContactSurface::collect_forces_torques(), and jeod::StructureIntegratedDynBody::compute_rotational_acceleration().
The documentation for this class was generated from the following files:
vector3.hh
vector3_inline.hh