JEOD: jeod::ConstrainedPointMass Class Reference
jeod::ConstrainedPointMass Class Reference
A constrained point mass is a point mass that is constrained to more or less move with a DynBody object.
#include <constrained_point_mass.hh>
Public Member Functions
ConstrainedPointMass (const ConstraintFrame *constraint_frame_in=nullptr)
Default constructor.
virtual ~ConstrainedPointMass ()=default
Destructor.
virtual void update_attachment (const VehicleProperties &)
Update information about the relation between this constrained object and the root DynBody.
virtual void setup_constraint (const VehicleProperties &vehicle_properties, const VehicleNonGravState &non_grav_state)
Prepare this object for solving a constraint problem.
void set_mass (double mass_in)
Set the constrained object's effective mass.
void set_constraint_position (const double constraint_position[3])
Set the constraint point position.
void compute_constraint_position_root ()
Compute the constraint point in root structural coordinates.
void compute_constraint_position_com (const VehicleProperties &vehicle_properties)
Compute the constraint point relative to the root body center of mass, in root structural coordinates.
void compute_non_grav_accel (const VehicleNonGravState &non_grav_state)
Compute the non-gravitational acceleration at the constraint point.
Data Fields
const ConstraintFrame * constraint_frame
The frame in which the constraint position is most naturally expressed.
double mass {}
The effective mass of this constrained object.
double constraint_position_constraint_frame [3] {}
The position at which the constraint equation applies, expressed in the constraint frame.
double constraint_position_root [3] {}
The constraint position, expressed in root structural frame coordinates.
double constraint_position_com [3] {}
The constraint position relative to the root vehicle center of mass, expressed in root structural frame coordinates.
double non_grav_accel_root [3] {}
The non-gravitational acceleration at the constraint point in root structural coordinates.
double non_grav_accel_constraint_frame [3] {}
The acceleration at the constraint point due to vehicular rotation and external forces and torques, in constraint frame coordinates.
double force_constraint_frame [3] {}
The force at the constraint point; mass * non_grav_accel_constraint_frame.
Friends
class InputProcessor
void init_attrjeod__ConstrainedPointMass ()
Detailed Description
A constrained point mass is a point mass that is constrained to more or less move with a DynBody object.
The "more or less" means that this object needs to be modeled as a constrained object rather than as a rigidly attached object.
Definition at line 73 of file constrained_point_mass.hh.
Constructor & Destructor Documentation
ConstrainedPointMass()
jeod::ConstrainedPointMass::ConstrainedPointMass (const ConstraintFrame * constraint_frame_in = nullptr)
Default constructor.
Definition at line 29 of file constrained_point_mass.cc.
~ConstrainedPointMass()
virtual jeod::ConstrainedPointMass::~ConstrainedPointMass () virtual default
Destructor.
Member Function Documentation
compute_constraint_position_com()
void jeod::ConstrainedPointMass::compute_constraint_position_com (const VehicleProperties & vehicle_properties)
Compute the constraint point relative to the root body center of mass, in root structural coordinates.
Definition at line 48 of file constrained_point_mass.cc.
References constraint_position_com, constraint_position_root, jeod::Vector3::diff(), and jeod::VehicleProperties::get_structure_to_body_offset().
Referenced by setup_constraint().
compute_constraint_position_root()
void jeod::ConstrainedPointMass::compute_constraint_position_root ()
Compute the constraint point in root structural coordinates.
Definition at line 40 of file constrained_point_mass.cc.
References constraint_frame, constraint_position_constraint_frame, constraint_position_root, jeod::Vector3::incr(), jeod::ConstraintFrame::origin_position_root, jeod::ConstraintFrame::T_root_constraint, and jeod::Vector3::transform_transpose().
Referenced by set_constraint_position(), setup_constraint(), and update_attachment().
compute_non_grav_accel()
void jeod::ConstrainedPointMass::compute_non_grav_accel (const VehicleNonGravState & non_grav_state)
Compute the non-gravitational acceleration at the constraint point.
Definition at line 53 of file constrained_point_mass.cc.
References jeod::VehicleNonGravState::accel_struct, constraint_frame, constraint_position_com, jeod::Vector3::cross(), jeod::Vector3::cross_incr(), force_constraint_frame, jeod::Vector3::incr(), mass, non_grav_accel_constraint_frame, non_grav_accel_root, jeod::VehicleNonGravState::omega_dot_struct, jeod::VehicleNonGravState::omega_struct, jeod::Vector3::scale(), jeod::ConstraintFrame::T_root_constraint, and jeod::Vector3::transform().
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), and setup_constraint().
set_constraint_position()
void jeod::ConstrainedPointMass::set_constraint_position (const double constraint_position[3])
Set the constraint point position.
Parameters
constraint_position Constraint point, in constraint frame coordinates.
Definition at line 34 of file constrained_point_mass.cc.
References compute_constraint_position_root(), constraint_position_constraint_frame, and jeod::Vector3::copy().
set_mass()
void jeod::ConstrainedPointMass::set_mass (double mass_in) inline
Set the constrained object's effective mass.
Parameters
mass_in The effective mass.
Definition at line 169 of file constrained_point_mass.hh.
References mass.
setup_constraint()
virtual void jeod::ConstrainedPointMass::setup_constraint (const VehicleProperties & vehicle_properties, const VehicleNonGravState & non_grav_state) inline virtual
Prepare this object for solving a constraint problem.
In this case, that means computing constraint_position_com.
Parameters
vehicle_properties Various vehicle properties.
non_grav_state Non-gravitational State.
Note
This function is called prior to the calls to set_self_coeff(), set_cross_coeff(), and set_r_h_s().
Reimplemented in jeod::ConstrainedRigidMass.
Definition at line 155 of file constrained_point_mass.hh.
References compute_constraint_position_com(), compute_constraint_position_root(), and compute_non_grav_accel().
Referenced by jeod::ConstrainedRigidMass::setup_constraint(), jeod::PendulumConstraintComponent::setup_constraint(), and jeod::DynBodyPendulumConstraint::setup_constraint().
update_attachment()
virtual void jeod::ConstrainedPointMass::update_attachment (const VehicleProperties &) inline virtual
Update information about the relation between this constrained object and the root DynBody.
Definition at line 142 of file constrained_point_mass.hh.
References compute_constraint_position_root().
Referenced by jeod::DynBodyAttachedBodyConstraint::update_attachment(), and jeod::DynBodyPendulumConstraint::update_attachment().
Friends And Related Function Documentation
init_attrjeod__ConstrainedPointMass
void init_attrjeod__ConstrainedPointMass () friend
InputProcessor
friend class InputProcessor friend
Definition at line 75 of file constrained_point_mass.hh.
Field Documentation
constraint_frame
const ConstraintFrame* jeod::ConstrainedPointMass::constraint_frame
The frame in which the constraint position is most naturally expressed.
Definition at line 84 of file constrained_point_mass.hh.
Referenced by compute_constraint_position_root(), compute_non_grav_accel(), and jeod::ConstrainedRigidMass::setup_constraint().
constraint_position_com
double jeod::ConstrainedPointMass::constraint_position_com[3] {}
The constraint position relative to the root vehicle center of mass, expressed in root structural frame coordinates.
trick_units(m)
Definition at line 109 of file constrained_point_mass.hh.
Referenced by compute_constraint_position_com(), compute_non_grav_accel(), jeod::ForceConstraintComponent::get_cross_coeff(), and jeod::ForceConstraintComponent::setup_constraint().
constraint_position_constraint_frame
double jeod::ConstrainedPointMass::constraint_position_constraint_frame[3] {}
The position at which the constraint equation applies, expressed in the constraint frame.
Note well: This may or may not be the position of the of the constrained mass. For example, the constraint position for a pendulum whose mass is concentrated at the end of a massless rod is the hinge point position rather than the bob position.trick_units(m)
Definition at line 98 of file constrained_point_mass.hh.
Referenced by compute_constraint_position_root(), jeod::PendulumConstraintComponent::reset_integrators(), set_constraint_position(), and jeod::PendulumConstraintComponent::setup_constraint().
constraint_position_root
double jeod::ConstrainedPointMass::constraint_position_root[3] {}
The constraint position, expressed in root structural frame coordinates.
trick_units(m)
Definition at line 103 of file constrained_point_mass.hh.
Referenced by compute_constraint_position_com(), compute_constraint_position_root(), jeod::DynBodyAttachedBodyConstraint::set_constraint_values(), and jeod::ForceConstraintComponent::setup_constraint().
force_constraint_frame
double jeod::ConstrainedPointMass::force_constraint_frame[3] {}
The force at the constraint point; mass * non_grav_accel_constraint_frame.
trick_units(N)
Definition at line 126 of file constrained_point_mass.hh.
Referenced by compute_non_grav_accel(), jeod::PendulumConstraintComponent::setup_constraint(), and jeod::DynBodyAttachedBodyConstraint::setup_constraint().
mass
double jeod::ConstrainedPointMass::mass {}
The effective mass of this constrained object.
trick_units(kg)
Definition at line 89 of file constrained_point_mass.hh.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), compute_non_grav_accel(), jeod::ForceConstraintComponent::get_cross_coeff(), jeod::PendulumConstraintComponent::reset_integrators(), set_mass(), and jeod::PendulumConstraintComponent::setup_constraint().
non_grav_accel_constraint_frame
double jeod::ConstrainedPointMass::non_grav_accel_constraint_frame[3] {}
The acceleration at the constraint point due to vehicular rotation and external forces and torques, in constraint frame coordinates.
trick_units(m/s^2)
Definition at line 121 of file constrained_point_mass.hh.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), and compute_non_grav_accel().
non_grav_accel_root
double jeod::ConstrainedPointMass::non_grav_accel_root[3] {}
The non-gravitational acceleration at the constraint point in root structural coordinates.
trick_units(m/s^2)
Definition at line 115 of file constrained_point_mass.hh.
Referenced by jeod::PendulumConstraintComponent::compute_constraint_response(), and compute_non_grav_accel().
The documentation for this class was generated from the following files:
constrained_point_mass.hh
constrained_point_mass.cc